### ISSUE TITLE
"Total canvas memory use exceeds the maximum limit (256 MB)" error in safari 12 and above

### ISSUE THREAD

**Issue by mobiusy** [mozilla/pdf.js#11297] opened 2019-11-01 03:30 UTC
All PDF files have this issue.
[PD216484A.pdf](https://github.com/mozilla/pdf.js/files/3796577/PD216484A.pdf)

Configuration:
- safari 12
- iPad (6th generation), system version: 12.1.4
- PDF.js version: 1.6.0

Steps to reproduce the problem:
1. Prepare one pdf file, more pages more better
2. Open safari and open pdf file via pdf.js
3. Do not close the tab, open an new tab and open the pdf file in same way
4. Repeat step 3 until the pdf file pages shows blank
5. 
![image](https://user-images.githubusercontent.com/27566449/68000722-22c5d900-fc9c-11e9-925b-5221e6542197.png)

What is the expected behavior? 
Expected the pdf shows correctly event user do not close previous tab.

What went wrong? 
Got errors in browser inspector:
![image](https://user-images.githubusercontent.com/27566449/68000095-acc07280-fc99-11e9-9ee3-35bd49c8010c.png)

More info:
1. I tried the latest version of pdf.js(2.3.200), this issue still exists.
2. IPAD OS 13 have the same issue.

Is this a safari bug or pdf.js has workaround to avoid blank pages?

**Comment by Snuffleupagus** [comment] 2019-11-01 07:57
Duplicate of #11245.

> PDF.js version: 1.6.0

Furthermore, that's not an official release and in any case that version is a few years old and consequently no longer supported.

**Comment by mobiuskaikai** [comment] 2019-11-01 08:59
> Duplicate of #11245.
> 
> > PDF.js version: 1.6.0
> 
> Furthermore, that's not an official release and in any case that version is a few years old and consequently no longer supported.

I replaced the old version with 2.3.200, and apply the fix of [fix of 11245](https://github.com/mozilla/pdf.js/commit/f964cbc96149c6705d5a961fd6534f29a2066388#diff-b808c12269fe0c6c0bb750a140b649aa), the issue still exists.
I think it is not the same reason with #11245 , but it exceed the memory usage limit of safari browser on iPad OS.

**Comment by timvandermeij** [comment] 2019-11-01 21:38
2.3.200 also doesn't contain the fix from that issue yet. I would suggest waiting for the next release or cherry-picking the fix if need be. Closing since this should be fixed then.

**Comment by mobiuskaikai** [comment] 2019-11-02 16:10
> 2.3.200 also doesn't contain the fix from that issue yet. I would suggest waiting for the next release or cherry-picking the fix if need be. Closing since this should be fixed then.

Thanks for your reply. I applied the fix of 11245 in 2.3.200, and my issue is not been fixed. On iPad OS 12.1.4, the isIOS() check works OK before the fix, userAgent match the /IPAD/ check. I appreciate if you can do more investigation.

**Comment by Stevebel** [comment] 2019-12-20 16:59
I was having a similar issue with the viewer embedded in my app. There is a known issue with Safari

**Comment by Stevebel** [comment] 2019-12-20 17:10
I was having a similar issue when I embedded the viewer in my app. There is a [known issue](https://stackoverflow.com/questions/52532614/total-canvas-memory-use-exceeds-the-maximum-limit-safari-12) with Safari that prevents garbage collection of canvases.

There's already code in place that has a workaround to force memory to clear when scrolling through the PDF (PDFPageView.reset): 
https://github.com/mozilla/pdf.js/blob/693240cf06dfde191532450837828f67691f5a9f/web/pdf_page_view.js#L185-L188

However, this code doesn't run on pages when the viewer is "cleaned up", leaving the canvases in memory. I was able to correct the issue by changing BaseViewer.cleanup:

https://github.com/mozilla/pdf.js/blob/693240cf06dfde191532450837828f67691f5a9f/web/base_viewer.js#L950-L951

to simply:

`if (this._pages[i]) {`

I don't have enough experience with this project to know if there are any edge cases where this causes issues, but in our testing nothing has come up and we no longer have a memory leak.

**Comment by AlphaDel** [comment] 2020-05-15 15:24
https://github.com/mozilla/pdf.js/blob/7b23476e61f62caf41f3ddd8df2c70c2596bc8ba/web/base_viewer.js#L46

I workaround by reduce `DEFAULT_CACHE_SIZE` which number less than 10.
For me I changed to 3 and it's works!
Hope this will help you whom facing this problem.

**Comment by seopei** [comment] 2020-06-28 21:13
I am running into the same issue. Is there a fix available?

**Comment by visuallization** [comment] 2021-11-30 13:11
We run into the same issue on IOS Safari. @mobiusy did you find a way to solve it?

**Comment by mobiusy** [comment] 2021-12-01 09:44
> We run into the same issue on IOS Safari. @mobiusy did you find a way to solve it?
Not yet, hope safari can fix this issue

**Comment by kantsverma** [comment] 2021-12-28 07:15
I am facing the same issues with IOS 15.1 in iPhone and Mac

**Comment by jcsrb** [comment] 2022-03-31 12:20
a related article https://pqina.nl/blog/total-canvas-memory-use-exceeds-the-maximum-limit/

**Comment by Snuffleupagus** [comment] 2022-08-29 09:45
Given that we (obviously) cannot fix `canvas`-related memory handling problems in the Safari browser *itself*, and that Firefox is the *primary* development target for this library, let's close this old issue since it unfortunately doesn't really seem actionable here.

**Closed by Snuffleupagus** 2022-08-29 09:45 UTC
Labels: other, os-ios
