### ISSUE TITLE
Issue with PDF document where it shows lines in the pages with pdf.js

### ISSUE THREAD

**Issue by TrilokJaladi** [mozilla/pdf.js#16342] opened 2023-04-25 07:45 UTC
Attach (recommended) or Link to PDF file here:

Issue while rendering the PDF document where it shows horizontal lines in the pages with pdf.js. 
You can see lines in the pages while viewing the PDF document. 

Configuration:
- Web browser and its version:
Worked in Chrome Version 112.0.5615.121
Firefox 112.0.1 (64-bit)
Worked in Microsoft Edge 112.0.1722.54
- Operating system and its version:
MacBook pro Ventura 13.3.1
- PDF.js version: 3.5.141
- Is a browser extension: no

Steps to reproduce the problem:
1.  Open the attached pdf document in pdf.js 
2.

What is the expected behavior? (add screenshot)
Expected behavior is to render the pdf without horizontal line
[lines PDF document with_.pdf](https://github.com/mozilla/pdf.js/files/11319975/lines.PDF.document.with_.pdf)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-04-25 08:07
Duplicate of #7837

**Closed by Snuffleupagus** 2023-04-25 08:07 UTC
