### ISSUE TITLE
some text appears briefly but then disappears

### ISSUE THREAD

**Issue by delan** [mozilla/pdf.js#11144] opened 2019-09-14 07:24 UTC
[the-beginners-method-for-solving-the-rubiks-cube.pdf](https://github.com/mozilla/pdf.js/files/3612391/the-beginners-method-for-solving-the-rubiks-cube.pdf) ([original](https://www.cubeskills.com/uploads/pdf/tutorials/the-beginners-method-for-solving-the-rubiks-cube.pdf))

Configuration:
- Web browser and its version: Firefox/69.0
- Operating system and its version: NixOS 19.03.173489.af5481e9b77
- PDF.js version: 2.2.214
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the given file
2. Watch the red box to the left of the cubes

What is the expected behavior? Okular 1.6.3

![Screenshot_at_2019-09-14-17-18-10](https://user-images.githubusercontent.com/465303/64904873-a68b2c80-d713-11e9-8ef9-5bb31e1e2f24.png)

What went wrong?
![200](https://user-images.githubusercontent.com/465303/64904907-51034f80-d714-11e9-86ab-73e4520e2fe7.png)
![201](https://user-images.githubusercontent.com/465303/64904908-51034f80-d714-11e9-870b-e501ec9892ca.png)
![202](https://user-images.githubusercontent.com/465303/64904909-51034f80-d714-11e9-985a-dd3e3b17ed8f.png)
![203](https://user-images.githubusercontent.com/465303/64904910-519be600-d714-11e9-8abc-32f84a750dc1.png)
![204](https://user-images.githubusercontent.com/465303/64904911-519be600-d714-11e9-90be-f698586c1ef0.png)
![205](https://user-images.githubusercontent.com/465303/64904912-519be600-d714-11e9-809a-53be73c484fc.png)

~~Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):~~

**Comment by Snuffleupagus** [comment] 2019-09-14 08:21
Duplicate of #269.

**Closed** 2019-09-14 13:41 UTC
