### ISSUE TITLE
PDF fails to render

### ISSUE THREAD

**Issue by kinztechcom** [mozilla/pdf.js#12639] opened 2020-11-19 18:42 UTC
Attach (recommended) or Link to PDF file here: [25 E000 - STAMPED.pdf](https://github.com/mozilla/pdf.js/files/5568966/25.E000.-.STAMPED.pdf)

Configuration:
- Web browser and its version: Chrome 87.0.4280.66
- Operating system and its version: Windows 10
- PDF.js version: 2.5.207
- Is a browser extension: 

Steps to reproduce the problem:
1. Attempt to render attached pdf in pdfjs.

What is the expected behavior? (add screenshot) Pdf renders correctly

What went wrong? (add screenshot) Pdf fails to render, promise success function is never hit. In the demo viewer, it just spins.

**Comment by timvandermeij** [comment] 2020-11-19 20:53
This PDF file basically consists of one huge image of size 17952 x 25292, so it's no wonder rendering this takes a lot of CPU time and memory. This makes it a duplicate of #6419.

**Closed by timvandermeij** 2020-11-19 20:53 UTC
