### ISSUE TITLE
Problem With Starting New Search at Start of Document

### ISSUE THREAD

**Issue by DavidRoss** [mozilla/pdf.js#8512] opened 2017-06-11 22:25 UTC
Link to PDF file (or attach file here): https://assets.documentcloud.org/documents/3860989/Optuim-Complaint.pdf

Configuration:
- Web browser and its version:  SeaMonkey 2.46
- Operating system and its version:  Windows 7 Ultimate SP1 (x64)
- PDF.js version:  1.8.439

- Is an extension:  Yes

Steps to reproduce the problem:
1.  Open indicated URI, which is for a PDF file.  
2.  Search on term "Price of Victoza"  (without the quote marks).  
3.  Leave search bar open.  
4.  Scroll back to top of document.  
5.  Select any text at top of document.  
6.  Change search term to merely "Victoza" (again without the quote marks) and search.  

What is the expected behavior? (add screenshot)
At step 5, search should find new search term on PDF page 2.  

What went wrong? (add screenshot)
Search finds new search term on PDF page 4.  

The problem is that scrolling to the top of the document and selecting text there does not reset the location where searching should begin.  In order to reset the location, I had to delete the current search term and then close the search bar in addition to scrolling to the top of the document and selecting text there.

**Comment by timvandermeij** [comment] 2017-06-12 20:47
I personally find it questionable if the behavior you describe is actually what the user generally expects. If I search for a term and find it, I usually scroll a bit to get some context of the surrounding text. Then, if I don't find what I need yet, I want it to go to the next term from the point of the last search result and not from wherever I ended up after scrolling. If I scrolled up and want to find the next occurrence, then I would definitely not expect to end up in the same place again, which is what would happen with the behavior you describe.

I think UX people should determine what the expected behaviour is here.

**Comment by Snuffleupagus** [comment] 2017-06-12 20:59
> I personally find it questionable if the behavior you describe is actually what the user generally expects.

Interestingly, the behaviour[1] described in the OP is actually what I see when testing PDF.js version `1.8.442` in Firefox Nightly 56 :-)
So, it seems that this issue is WORKSFORME

---
[1] Issue #3935 and PR #3941 is probably relevant here.

**Comment by timvandermeij** [comment] 2017-06-12 21:04
You're right. I can reproduce that as well; it finds the match on page 2 for me. It's likely that you indeed want matches as close to where you are as possible. Closing since this seems to work as intended then.

**Closed by timvandermeij** 2017-06-12 21:04 UTC
Labels: 1-ux, 1-viewer

**Comment by DavidRoss** [comment] 2017-06-12 21:06
I searched for a term in the cited PDF document.  When I did not see what I considered a relevant result, I scrolled to the top of the document, changed the search term, and tried searching again.  This gave me results below the irrelevant results. 

I downloaded the PDF file and used Adobe Reader to search.  Repeating the prior searches, Adobe Reader began the search on the second term at the top of the document.  This has long been the way Adobe Reader works.  If pdf.js is a replacement in Mozilla-based browsers, I should think it would work similarly.

**Comment by timvandermeij** [comment] 2017-06-12 21:14
The point here is, if we follow your steps to reproduce we do end up on page 2 as expected in Firefox, so this is either a SeaMonkey-specific bug (which I doubt) or you're not using the version you listed. Could you try downloading the PDF and opening it with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button) and see if you can reproduce it there?

**Comment by DavidRoss** [comment] 2017-06-12 21:55
Yes, I had just installed pdf.js 1.8.439 on 11 June 2017, not long before encountering the problem.  That was the latest version available at that time.  

After trying your https://mozilla.github.io/pdf.js/web/viewer.html and not seeing the problem, I updated to pdf.js 1.8.444, in which the problem is resolved.

**Comment by timvandermeij** [comment] 2017-06-13 20:47
Good to know, thank you for reporting this!
