### ISSUE TITLE
Highlighting multiple phrases at a time not working

### ISSUE THREAD

**Issue by EtashGuha** [mozilla/pdf.js#11128] opened 2019-09-07 22:17 UTC
#search=whale%20that%3dIshmael&phrase=true
I am trying to highlight multiple phrases at once. This should specifically highlight the phrase "whale that" and "Ishmael". However, it does not highlight these. 
[Etash.pdf](https://github.com/mozilla/pdf.js/files/3587087/Etash.pdf)
![image](https://user-images.githubusercontent.com/10456588/64480753-84396200-d19b-11e9-8749-53fe34a5028d.png)
If I set phrase to false, I get this:
![image](https://user-images.githubusercontent.com/10456588/64480759-a0d59a00-d19b-11e9-8d44-19632530d931.png)

Configuration:
- chromium
- Any OS

**Comment by Snuffleupagus** [comment] 2019-09-07 22:43
Looks like a duplicate of #7442, note in particular https://github.com/mozilla/pdf.js/issues/7442#issuecomment-229696596.

*For future reference:* Please make sure to always fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) with *all* of the requested information.

**Comment by EtashGuha** [comment] 2019-09-07 22:57
My apologies. I am not using another reader and I tried the solutions on that forum and it still did not work.
```javascript
/web/viewer.html?file=${require('electron').remote.getGlobal('sharedObject').someProperty}#search=whale that%3DIshmael&phrase=true`
```
This still does not work as expected. I added that line as well.
Sorry and I appreciate all the help!

**Comment by timvandermeij** [comment] 2019-09-08 11:05
Closing since this is a duplicate of #7442 in which this problem is already tracked.

**Closed by timvandermeij** 2019-09-08 11:05 UTC
