### ISSUE TITLE
Translate Tagged PDF document into corelated semantic HTML document

### ISSUE THREAD

**Issue by MarioBatusic** [mozilla/pdf.js#9555] opened 2018-03-14 10:34 UTC
Configuration:
- Web browser and its version: ALL
- Operating system and its version: ALL
- PDF.js version: Last

Steps to reproduce the problem:
1. No existing PDF tags are available in the HTML output: `<h#> <ul> <il> <table>` etc.

What is the expected behavior? (add screenshot)
Screen Reader software expects to find all semantic elements and attributes that are available in a tagged PDF document.

All Tagged PDF documents should encode document text accordingly using corelative HTML semantic elements such as 

```
* <p>, 
* <h1>-<h6>, 
* <table>, <tr> <th>, <td>,
* <ul>, <ol>, <li>, <dl>, <dt>, <dd>,
* <blockquote>, etc.
```

See the attachment with PDF and HTML versions of a completely tagged document.
[A completely tagged pdf document.zip](https://github.com/mozilla/pdf.js/files/1810586/A.completely.tagged.pdf.document.zip)

**Comment by timvandermeij** [comment] 2019-11-09 13:49
Closing since this is a duplicate of #6269.

**Closed by timvandermeij** 2019-11-09 13:49 UTC
Labels: 1-core
