### ISSUE TITLE
Remove automatic Scollevent by loading dokument

### ISSUE THREAD

**Issue by chstef** [mozilla/pdf.js#8171] opened 2017-03-17 14:28 UTC
// Make all navigation keys work on document load,
 // unless the viewer is embedded in a web page.
 if (!self.isViewerEmbedded) {
   --->   // self.pdfViewer.focus(); //  
  }

to remove this is ok...

**Comment by timvandermeij** [comment] 2017-03-17 21:30
Closing since it's unclear what the problem is. This in in there for a reason and if something else is preferred, please elaborate why we should change this in the library.

**Closed by timvandermeij** 2017-03-17 21:30 UTC

**Comment by chstef** [comment] 2017-03-17 21:56
It's not needed to change the Library, sorry.
Webpage:
---------------------------------------------------------
Above Objekts: Additional Buttons and Text.
----------------------------------------------------------   --> here jumps allways to this Marker...
Here ist the Div's of the PDF's Libary.

-----------------------------------------------------------
Regards...
