### ISSUE TITLE
PDF pages broken when showcase opened in mobile web browser

### ISSUE THREAD

**Issue by saizakapps** [mozilla/pdf.js#16586] opened 2023-06-22 12:10 UTC
[Pdf.js showcase](https://mozilla.github.io/pdf.js/web/viewer.html)

Configuration:
- Web browser and its version: Chrome v108.0.5359.128
- Operating system and its version: Android v13
- PDF.js version: 3.5
- Is a browser extension: No

Steps to reproduce the problem:
1. Open pdf.js v3.5 showcase in Samsung A53 in Chrome OS

What is the expected behavior? 
![image](https://github.com/mozilla/pdf.js/assets/107913771/f89403d3-a082-4ac9-88f6-b9819225a75f)

What went wrong?
![image](https://github.com/mozilla/pdf.js/assets/107913771/2e20c3da-3aac-40a6-9172-3f48f9901de2)

**Comment by Snuffleupagus** [comment] 2023-06-22 12:32
This looks for all intents and purposes like a duplicate of issue #16459, please note https://github.com/mozilla/pdf.js/issues/16459#issuecomment-1559075043, and unfortunately everything here points to a bug in the browser, platform, and/or graphics driver (rather than in the PDF.js library).

**Closed by Snuffleupagus** 2023-06-22 12:32 UTC
