### ISSUE TITLE
Edited pages rendered as if not changed

### ISSUE THREAD

**Issue by nerkn** [mozilla/pdf.js#9129] opened 2017-11-14 15:29 UTC
Attach (recommended) or Link to PDF file here:
https://zenodo.org/record/1048152#.WgrUmd9fjeQ
or
https://waset.org/publications/10006645/red

Configuration:
- Web browser and its version:
mozilla ( under linux/windows), 
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
0. Our editors format papers, and our system using zend php, adding necessary information to header, footer, side notes.
1. Open the document, there is no header, footer, side notes 

What is the expected behavior? (add screenshot)
![screencapture-waset-org-publications-10006645-r-1510672765952](https://user-images.githubusercontent.com/725631/32788068-e5715d06-c960-11e7-93e9-b1e2dc1268e8.png)

What went wrong? (add screenshot)
![screenshot-2017-11-14 microsoft word - 17ae030135 3 - red](https://user-images.githubusercontent.com/725631/32788049-d66cedd4-c960-11e7-9f27-b4a122306759.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
expected:
https://waset.org/publication/Red/10006645
not working  :
https://zenodo.org/record/1048152#.WgrUmd9fjeQ

**Comment by timvandermeij** [comment] 2017-11-14 20:48
The version of PDF.js hosted there is really old: 1.4.192. However, it also happens in the latest version where it gives sanitizer errors:

```
Warning: Indexing all PDF objects  pdf.worker.js:342:5
PDF ff76551b2233684c9360d1a6b7172103 [1.6 Acrobat Distiller 7.0 (Windows) / PScript5.dll Version 5.2.2] (PDF.js: 2.0.114)  app.js:1083:6
downloadable font: OS/2: Adjusting head.macStyle (italic) to match fsSelection (font-family: "g_d1_f5" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,AAEAAAANAIAAAwBQT1MvMqAsjSkAAADcAAAAVmNtYXBmcCauAAABNAAAAKxjdnQg/0SilwAAAeAAAAd4ZnBnbQFau5IAAAlYAAAFzW … dHUrKysrK0UYaUQrACtzKysrKysrKysrASsrKwBzc3MrKysBQ1xYuP/esx4cMxi4A3+1KzMYJiszuf/wA4GxEjMrKysrWQFzdCsAK3N1KytzKysrKytzdSsrKysrAA==  viewer.html
downloadable font: OS/2: Adjusting head.macStyle (italic) to match fsSelection (font-family: "g_d1_f8" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,AAEAAAANAIAAAwBQT1MvMqAsjSkAAADcAAAAVmNtYXDLXhY1AAABNAAAAGRjdnQg/0SilwAAAZgAAAd4ZnBnbQFau5IAAAkQAAAFzW … Kyt0dSsrKysrRRhpRCsAK3MrKysrKysrKysBKysrAHNzcysrKwFDXFi4/96zHhwzGLgDf7UrMxgmKzO5//ADgbESMysrKytZAXN0KwArc3UrK3MrKysrK3N1KysrKysA
```

**Comment by Snuffleupagus** [comment] 2017-11-15 08:53
I cannot reproduce the sanitizer errors in https://github.com/mozilla/pdf.js/issues/9129#issuecomment-344393489, but the real problem with the PDF file is that the way it's edited in a way that makes it corrupt. From a quick look it appears that the PDF "file" is actually multiple PDF documents placed in just one file, which is a mode of corruption that can be difficult to recover from.

**Comment by nerkn** [comment] 2017-12-25 04:40
which libraries do you recommend  to edit pdf files?

**Comment by timvandermeij** [comment] 2019-07-27 13:05
Closing as a duplicate of #9552 since that one contains more information and a fixed PDF file for comparison.

**Closed by timvandermeij** 2019-07-27 13:05 UTC
Labels: 4-corrupted-pdf
