### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#10181] opened 2018-10-24 21:50 UTC
In our usual release flow we've been moving pre-release to release and generating a new pre-release from master. I was about to generate the new pre-release, but I haven't been following API changes closely lately, so I'm unsure of what the version number should be. Is the current master 2.0 or 2.1 or need to be 3.0?

We could also just remove the current pre-release and make new 2.0 release from master. Then release that.

@Snuffleupagus @timvandermeij

**Comment by timvandermeij** [comment] 2018-10-24 21:52
The current pre-release indeed needs to be removed since we fixed some regressions found in it (see the note on https://github.com/mozilla/pdf.js/projects/5). That would mean that we will only end up with a stable release, so no beta release temporarily. Possibly the download page needs to be updated slightly to handle that (i.e., not show the button).

The current master would be version 2.0. From that point on, I think we can create 2.1.

**Comment by timvandermeij** [comment] 2018-10-25 21:48
I'll coordinate the stable 2.0 release. Tasks:

- [ ] Remove the pre-release.
- [ ] Change the download page to handle a missing beta version.
- [ ] Create the release according to https://github.com/mozilla/pdf.js/wiki/Release-Process.
- [ ] Check if the NPM release is made.
- [ ] Update https://github.com/mozilla/pdf.js/wiki/Release-Process with a link to the release notes script and other information found during the process.
- [ ] Schedule the remaining work from https://github.com/mozilla/pdf.js/projects/5.

**Comment by Snuffleupagus** [comment] 2018-10-27 14:57
> That would mean that we will only end up with a stable release, so no beta release temporarily. Possibly the download page needs to be updated slightly to handle that (i.e., not show the button).

The simplest solution might be to temporarily just set *both* version numbers to the same one, to avoid having to alter the page.

**Comment by timvandermeij** [comment] 2018-10-27 19:06
Closing since version 2.0 is now stable. I had some trouble pushing the stable version to `pdfjs-dist`/NPM; this will be handled in a follow-up somewhere next week.

**Closed** 2018-10-27 19:06 UTC
Labels: 1-other

**Comment by timvandermeij** [comment] 2018-10-27 19:13
I have updated the project board at https://github.com/mozilla/pdf.js/projects/5. In particular I could use some help with writing a migration guide because I'm not sure if all `api-minor`/`api-major` PRs cover all changes that people should know about?

**Comment by Snuffleupagus** [comment] 2018-11-01 00:01
While it looks like the `npm` version has now been updated, based on https://www.npmjs.com/package/pdfjs-dist, it doesn't look like `pdfjs-dist` was updated yet, based on https://github.com/mozilla/pdfjs-dist/commits/master.

*Ninja-edit:* Although based on https://github.com/mozilla/pdfjs-dist/releases, it looks like `pdfjs-dist` was *partially* updated; is the `master` branch of `pdfjs-dist` no longer intended to be updated (if so, why?), or is there perhaps still some work to do here?

Also, it looks like https://github.com/brendandahl/botio/commit/3f0fe066e95f5864ec59573d232b07ead3cb356d#diff-c945a46d13b34fcaff544d966cffcabaR448 may accidentally have broken the links back to the main repo, since e.g. https://github.com/mozilla/pdfjs-dist/releases/tag/v2.0.943 no longer contains a click-able link:
> PDF.js version 2.0.943 - See mozilla/pdf.js@tags/v2.0.943

For earlier versions of `pdfjs-dist`, the releases looked e.g. like:
> PDF.js version 2.0.489 - See [mozilla/pdf.js@7d7bc80](https://github.com/mozilla/pdf.js/commit/7d7bc80eee7ef4486547bec7b3ecba7be7aabc69)

**Comment by timvandermeij** [comment] 2018-11-01 21:49
For `pdfjs-dist` we only make releases and tags; see https://mozilla.logbot.info/pdfjs/20181030#c15543738. I'm not entirely sure why we don't update the `master` branch anymore, but apparently we don't. Maybe @brendandahl can tell why?

I'll create a note for both points on the project board.
