### ISSUE TITLE
In pdf viewer presentation mode PDF's href links are not working

### ISSUE THREAD

**Issue by shenbagaraj** [mozilla/pdf.js#7615] opened 2016-09-08 08:42 UTC
In pdf viewer presentation mode href links are not working. Its working in normal preview mode hyperlink not working only in component presentation mode.
I have attached the pdf file for your reference.
Go to Page #:  7
Please click the button highlighted in yellow. 
![image](https://cloud.githubusercontent.com/assets/21241471/18342666/92e6b618-75cd-11e6-9342-311397f0cba0.png)

[treatment-guidelines-for-diabetes-presentation (3).pdf](https://github.com/mozilla/pdf.js/files/461170/treatment-guidelines-for-diabetes-presentation.3.pdf)

browser chrome. 
PDF.js version: pdfjs-1.5.188-dist

I have tried in pdf.js demo also. PDF's href are not working.. Kindly help me to fix this asap.

**Comment by Snuffleupagus** [comment] 2016-09-08 10:05
External links are purposely disabled in Presentation Mode, to prevent the user from accidentally navigating away from the PDF file whilst Presentation Mode is active.
Please note that Presentation Mode is intended as a very simplified mode just for showing a PDF file. If you want all of the features of the default viewer, I'd suggest that you instead utilize the "Full Screen" mode of the browser *itself* (which can usually be toggled using e.g. the <kbd>F11</kbd> key).

Closing as answered, since this is working as intended.

**Closed by Snuffleupagus** 2016-09-08 10:05 UTC

**Comment by MSchip** [comment] 2017-07-10 19:33
@Snuffleupagus are there any configuration options that I could change to allow hyperlinks in presentation mode?

**Comment by karthice2c** [comment] 2017-09-08 11:21
@Snuffleupagus same issue for me. I have link in the pdf. I have used viewer.js and turn.js and showed the pdf as flipbook. There is youtube link in the pdf which is totally not clickable. I also tried with simple link in the pdf as www.google.co.in but even normal <a> href is not clickable. Breaking my head for last 2 days. Kindly help me out. are there any configuration options for this..??
