### ISSUE TITLE
after pageView updated, textLayer disapear

### ISSUE THREAD

**Issue by Vi-dot** [mozilla/pdf.js#7871] opened 2016-12-05 16:58 UTC
Configuration:
- Web browser and its version: Firefox 50.0.2
- PDF.js version: 1.6.366

Steps to reproduce the problem:
1. Make a PDFPageView
2. Bind window resize with : call myPageView.update(scale, rotation).

What is the expected behavior?
textLayer should be displayed even after resizing

What went wrong? (add screenshot)
At first load, without resizing window : pdf rendered perfectly, textLayer works fine
After resizing windows, pdf still rendered perfectly and its content scaled fine, but there is no textLayer any more.

Thanks

**Comment by timvandermeij** [comment] 2016-12-05 17:14
There is nothing we can do without a test case for reproducing the issue. Please create a test case, using for example JSBin, JSFiddle or your own server, and post it here. Without, the issue will be closed as incomplete, as outlined in the issue template and contribution guidelines.

**Comment by Vi-dot** [comment] 2016-12-06 10:46
Ok @timvandermeij 

There is a [Demo page](https://vi-dot.github.io/ng2-pdf-viewer/)
Don't click on any button (even zoom button), just resize your browser window.
Resizing window is going to call PageView.update(scale, rotation).

In the [repository](https://github.com/Vi-dot/ng2-pdf-viewer), you can find the functions in [pdf-viewer.component.ts](https://github.com/Vi-dot/ng2-pdf-viewer/blob/page-view-way/src/pdf-viewer/pdf-viewer.component.ts) file : 
- renderPage(pageNumber: number) -> used at start to draw each PageView
- refreshSize() -> used on window resizing to update each PageView without reloading all the PageView

Thanks for your help

**Comment by Snuffleupagus** [comment] 2016-12-06 11:59
If you're basing your solution on the [pageviewer example](https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js), I think that you'll have to add a `pageView.draw();` call after `pageView.update(scale, rotation);` to get the page to re-render properly.

However if you'd use e.g. the [simpleviewer example](https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js) instead, then it be sufficient to do e.g. `pdfViewer.currentScale(newScale)` in the `resize` event handler, since the `PDFViewer` has a `PDFRenderingQueue` instance that takes care of the updating/drawing of the `PDFPageView`s.

**Comment by Vi-dot** [comment] 2016-12-06 13:34
@Snuffleupagus I was looking for something which avoid reloading all the pages.
I guess using `pageView.draw();` make reload all the content, right ?
Same for `pdfViewer.currentScale = newScale;`, do you know if everything is reloaded ?
For big pdf, it takes time.

**Comment by Snuffleupagus** [comment] 2016-12-06 14:00
> I guess using `pageView.draw();` make reload all the content, right?

That call only renders *one* page, however if you loop over all the `PDFPageView` instances you have then all of them will be re-rendered.

> Same for pdfViewer.currentScale = newScale;, do you know if everything is reloaded?

That's not correct, since the `PDFViewer` will only render the currently visible pages (utilizing the "private" `PDFViewer._getVisiblePages` method). Note that e.g. the [default PDF.js viewer](http://mozilla.github.io/pdf.js/web/viewer.html) uses this functionality, to avoid rendering pages that are not visible.

**Comment by timvandermeij** [comment] 2016-12-06 21:21
Closing as answered. You do need to re-render the page after resizing, but as said you can only render the visible pages instead of all of them. I'm not sure what else there is to discuss here, but if there is a specific issue on the PDF.js side, feel free to let us know.

**Closed by timvandermeij** 2016-12-06 21:21 UTC
Labels: 4-information-requested

**Comment by gaitho** [comment] 2020-01-07 16:22
{    .....
     pdfViewer = new PDFViewer({
      container,
      viewer,
    });
   pdfViewer.setDocument(pdfDocument);
    pdfViewer.useOnlyCssZoom = true;
}

I was experiencing the same issue, adding the useOnlyCssZoom resolved the issue for me
