### ISSUE TITLE
Search Functionality Highlighting in white space

### ISSUE THREAD

**Issue by Yash7032** [mozilla/pdf.js#15739] opened 2022-11-24 11:07 UTC
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html
Configuration:
- Web browser and its version: Microsoft Edge v107.0.1418.56
- Operating system and its version: Windows 11 Enterprise v22H2
- PDF.js version:https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: No

Steps to reproduce the problem:
1. Browse the site and search for "For" text - https://mozilla.github.io/pdf.js/web/viewer.html
2. which will highlight in white space

What is the expected behavior? (add screenshot)
Searching for text **"for"** and it got highlighted in while space
What went wrong? (add screenshot)
<img width="887" alt="image" src="https://user-images.githubusercontent.com/118966146/203769070-b6db47b5-506c-4eb3-88a5-afab44b55943.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2022-11-24 11:13
Effectively a duplicate of #15736; unfortunately there must be some setting *in your browser* that affect e.g. the font-size or position of the textLayer-elements.

**Comment by calixteman** [comment] 2022-11-24 11:16
I can reproduce (even with the local dev server) on Edge and Chrome and it should be fixed by:
https://github.com/mozilla/pdf.js/pull/15722

**Comment by Snuffleupagus** [comment] 2022-11-24 11:36
> I can reproduce (even with the local dev server) on Edge and Chrome and it should be fixed by

Oh, if affects Chromium *generally* there's a pretty good chance that it's actually a regression :-(
Most likely PR #15721 affected Chromium browsers, although Firefox obviously is fine; given that the next PDF.js release is likely this weekend I'll just revert that one for now.

**Comment by calixteman** [comment] 2022-11-24 11:41
FYI, #15722 isn't fixing the regression.

**Closed** 2022-11-24 11:44 UTC
Labels: regression, text-selection
