### ISSUE TITLE
Improper text rotation in form fields

### ISSUE THREAD

**Issue by Djphoenix719** [mozilla/pdf.js#12574] opened 2020-11-04 17:36 UTC
Attach (recommended) or Link to PDF file here:
[SWNr.Karta.edytowalna.pdf](https://github.com/mozilla/pdf.js/files/5489530/SWNr.Karta.edytowalna.pdf)

Configuration:
- Web browser and its version: Chrome 86.0.4240.111 64bit
- Operating system and its version: Windows 10 - 10.0.18362 Build 18362
- PDF.js version: 2.7.261; also tested 2.7.236 (online demo version)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached PDF in the online demo
2. Enter text into any of the boxes
3. Observe text improperly rotated

What is the expected behavior? (add screenshot)
- Text should be displayed like this, as it is in Foxit
![image](https://user-images.githubusercontent.com/28300513/98145401-e02f7180-1e98-11eb-8ad1-93730e89c5ad.png)

What went wrong? (add screenshot)
- Text is instead rotated 90 degrees, image from the online demo
![image](https://user-images.githubusercontent.com/28300513/98145660-081ed500-1e99-11eb-8231-d64e96fa399b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Not available, as it requires a proprietary software license. This was originally reported by one of my users [here](https://github.com/Djphoenix719/PDFoundry/issues/48); It is reproducible in the online demo so hopefully lack of external viewer availability should not be an issue. Let me know if you need to view it in the application my fork of PDF.js is embedded in and we can set something up.

**Comment by Snuffleupagus** [comment] 2020-11-04 17:42
Duplicate of #9596

**Closed** 2020-11-04 20:33 UTC
