### ISSUE TITLE
Overlays missing from rendering in IE11

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#6924] opened 2016-01-26 13:57 UTC
Please see an example PDF here:

[IE11 Missing Blue Layer.pdf](https://github.com/mozilla/pdf.js/files/104979/IE11.Missing.Blue.Layer.pdf)

This renders correctly in Chrome and Firefox, but there are some colored overlays missing when viewed in IE11. (I'm running 11.0.9600.17843, but others have reported the same - unable to obtain precise version numbers other than "IE11".)

Attached are screenshots showing the differences between Chrome and IE11. Most obviously, there is a dark blue overlay over most of the PDF in Chrome (correct), and also some more orange in the bottom left corner (also correct). Both of these are missing from IE11.

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/786238/12582358/8c1a59d4-c434-11e5-995b-07e8cd094ef8.png)

IE11
![ie11](https://cloud.githubusercontent.com/assets/786238/12582361/911e03f4-c434-11e5-8ad7-e438d150351d.png)

Thank you for your help!

Dan

**Comment by yurydelendik** [comment] 2016-01-26 13:59
Dup of #3900?

**Comment by Snuffleupagus** [comment] 2017-01-31 10:46
Closing as duplicate of issue #5264.

**Closed by Snuffleupagus** 2017-01-31 10:46 UTC
Labels: 2-image-quality, 4-ie11-specific
