### ISSUE TITLE
Build minified dist assets

### ISSUE THREAD

**Issue by mbaer3000** [mozilla/pdf.js#6309] opened 2015-08-04 13:27 UTC
Is there a reaon why there is no build step that adds minified versions of the dist assets (preferably via uglifyjs)? I am asking because we're using pdfjs-dist, and doing the minification of those assets in our project adds a good couple of seconds to our build chain while adding next to no value. I am about to set up a "proxy bower module" that would do nothing but minify the files from pdfjs-dist, in order to avoid minifying all the time. But wouldn't it make more sense to just have those minified assets in your project? Thanks for the clarification.

**Comment by Snuffleupagus** [comment] 2015-08-04 13:42
Closing as duplicate of issue #5487.

**Closed by Snuffleupagus** 2015-08-04 13:42 UTC
