### ISSUE TITLE
[feature request] The last page should be allowed to scroll beyond end.

### ISSUE THREAD

**Issue by shenlebantongying** [mozilla/pdf.js#14838] opened 2022-04-26 02:41 UTC
### What is the expected behaviour?

Click a link (toward the last page) should take the user to the precise position without being limited by scroll.

### Steps to reproduce the problem:
1. Click a link which leads you to the lower position of the last page of the pdf.
2. The poison will not be reached because pdf.js cannot let the user scroll beyond the last page.

### Scanerio
In most academic papers, the last page will be references & bibliographies. A user can click the citations on articles to jump to them. Mostly they work, but they cannot reach links at the bottom of the page. Scanning by eyes is annoying and maybe disrupts the simple jump <-> jump back.

### Configuration:
Firefox developer edition, 100.0b9 
Link to a viewer: Firefox and Zotero.

### Attach (recommended) or Link to PDF file here:

Sample pdf with links at the end of the page, it is open access:
https://dl.acm.org/doi/10.1145/3386330

---

I am not sure this is the right place to solve the problem, since the readers probably can add something special to handle the last page.

However, I wish the problem will be fixed here in hope that it will propagate to downstream readers (like Zotero).

**Comment by Snuffleupagus** [comment] 2022-04-26 08:04
> Click a link which leads you to the lower position of the last page of the pdf.
> The poison will not be reached because pdf.js cannot let the user scroll beyond the last page.

(Note that it'd have been a lot easier/quicker to reproduce this had you specified an actual page/link to use...)

Similar behaviour can be observed in every other PDF viewer I've tested, since (somehow) conditionally appending *additional* white-space after the document would lead to too much unnecessary complication for something that's very much an edge-case; hence closing this issue as WONTFIX.

> Link to a viewer: Firefox and Zotero.

Please note that Zotero is a completely different project, not affiliated with the PDF.js library, and consequently we cannot provide help/support for that *here*.

**Closed by Snuffleupagus** 2022-04-26 08:04 UTC
Labels: information-requested
