### ISSUE TITLE
Non native behavior on mobile 

### ISSUE THREAD

**Issue by Rodrix33333** [mozilla/pdf.js#15839] opened 2022-12-16 04:43 UTC
Attach (recommended) or Link to PDF file here:

https://mozilla.github.io/pdf.js/legacy/web/viewer.html
Configuration:
- Web browser and its version: Android and Samsung Internet browser 
- Operating system and its version: Android (latest)
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1.  Go to webpage: 
https://mozilla.github.io/pdf.js/legacy/web/viewer.html
3. Pinch with two fingers to zoom in and zoom out

What is the expected behavior? (add screenshot)
On pinch with two fingers it should zoom in and out. It does nothing.

What went wrong? Non native behavior. Users expect to be able to control zoom via touch gestures.

**Comment by Snuffleupagus** [comment] 2022-12-16 08:40
Duplicate of #2582

**Closed by Snuffleupagus** 2022-12-16 08:40 UTC
