### ISSUE TITLE
PDF.js not rendering absolute layer

### ISSUE THREAD

**Issue by grigoreme** [mozilla/pdf.js#10331] opened 2018-12-05 08:45 UTC
Attach (recommended) or Link to PDF file here: 
[document.pdf](https://github.com/mozilla/pdf.js/files/2647904/document.pdf)

Configuration:
- Web browser and its version: Chrome 71.0.3578.80
- Operating system and its version: Windows 10 x64
- PDF.js version: [PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 2.1.93)](https://mozilla.github.io/pdf.js/web/viewer.html).
- Is a browser extension: No.

Steps to reproduce the problem:
1.  Open https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload document I have attached.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/25903855/49500885-68a2d300-f87a-11e8-9133-da5c1d7dd7db.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/25903855/49500929-77898580-f87a-11e8-94e1-f33aa50740c3.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by timvandermeij** [comment] 2018-12-05 21:48
PDF.js does not support digital signatures yet, so I'm closing this as a duplicate of the issues in https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-digital-signature.

**Closed by timvandermeij** 2018-12-05 21:48 UTC
