### ISSUE TITLE
PDF rendered black in FF, stripes in Chromium

### ISSUE THREAD

**Issue by pcworld** [mozilla/pdf.js#6380] opened 2015-08-22 11:53 UTC
[This PDF](http://physik.leech.it/pub/Ana_LA/Lineare_Algebra_Klausuren/SS_95.pdf) is rendered black in Firefox 40.0 (e.g. first page; using this [online demo](https://mozilla.github.io/pdf.js/web/viewer.html)):
![selection_283](https://cloud.githubusercontent.com/assets/1506734/9423809/266c25c6-48d4-11e5-8037-40c610c94cee.png)
In Chromium 44.0.2403.89, depending on the scaling, different set of stripes appear:
![selection_284](https://cloud.githubusercontent.com/assets/1506734/9423821/6d4549d2-48d4-11e5-9b71-e6dcd75f139d.png)
This is how it is rendered in Okular:
![selection_285](https://cloud.githubusercontent.com/assets/1506734/9423824/8fe42788-48d4-11e5-8d06-1e2d7aea13f3.png)
Note that both Okular and Evince have the stripes problem as well to a certain degree, though that is still better than how non-empty parts of the PDF are rendered completely black in Firefox.

**Comment by timvandermeij** [comment] 2015-12-14 21:09
I can't reproduce the black boxes using Firefox 42.0 on Windows 10 x64 with the latest PDF.js development version. It renders almost like the Chromium screenshot for me, i.e., just with some small stripes.

**Comment by SamyCookie** [comment] 2015-12-14 23:17
I can reproduce the issue myself on my Debian Linux x64 testing (stretch) with iceweasel 42 and pdf.js trunk version 1.3.78.

**Comment by cetinsert** [comment] 2021-09-17 18:39
No working link left.

**Comment by timvandermeij** [comment] 2021-09-18 12:03
I found a cached version on https://web.archive.org/web/20190504152553/https://physik.leech.it/pub/Ana_LA/Lineare_Algebra_Klausuren/SS_95.pdf. Given that it works on Linux, could someone on Mac/Windows check if this works now with the latest version? The stripes are already tracked in #3351 so in that case we can close this one.

**Comment by cetinsert** [comment] 2021-09-19 05:58
@timvandermeij – all 16 pages render fine (no black parts) with latest Firefox 92 /Chrome 93 on Windows 10 (20H2) and macOS 11.6. The stripes are there in all of them.

**Comment by timvandermeij** [comment] 2021-09-19 10:24
That's great, thanks for checking! Let's close this one then since the stripes are already tracked in another issue.

**Closed by timvandermeij** 2021-09-19 10:24 UTC
Labels: 4-image-conversion
