### ISSUE TITLE
Cannot load a local pdf in 1.10.92

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#9081] opened 2017-10-29 13:57 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome Version 64.0.3252.0 (Official Build) canary (64-bit)
- Operating system and its version: Win 10 10.0.16229
- PDF.js version: 1.10.92
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Load a **local** file into pdf.js
2.

What is the expected behavior? (add screenshot)
File should open

What went wrong? (add screenshot)
Cannot load file
Fetch API cannot load file:///C:/Users/david/Downloads/10.1093@bjps@axu026.pdf. URL scheme must be "http" or "https" for CORS request.

The offending line is line 8352:
fetch(url, createFetchOptions(this._headers, this._withCredentials)).then(response => {

'Allow access to file URLs' is ticked in Extension settings

Works in v1.9.430

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by uggrock** [comment] 2017-11-02 09:03
I can confirm this issue. Loading files from the file:/// protocol is a critical feature for us.

**Comment by alcfeoh** [comment] 2017-11-08 18:19
Same here, that's an important feature for a client of mine.

**Comment by alcfeoh** [comment] 2017-11-08 18:19
Same here, that's an important feature for a client of mine.

**Comment by alcfeoh** [comment] 2017-11-08 18:19
Same here, that's an important feature for a client of mine.

**Comment by samuelstein** [comment] 2017-12-01 12:41
same here

**Comment by Snuffleupagus** [comment] 2018-01-27 15:58
Closing as duplicate of issue #9361.

**Closed by Snuffleupagus** 2018-01-27 15:58 UTC
Labels: 1-core
