### ISSUE TITLE
How to rotate single page in whole pdf ?

### ISSUE THREAD

**Issue by SOftEngrAtta** [mozilla/pdf.js#8750] opened 2017-08-05 10:36 UTC
Is it possible to rotate only 1 page in whole pdf ?

**Comment by Snuffleupagus** [comment] 2017-08-05 10:42
Closing as duplicate of #7892.

**Closed by Snuffleupagus** 2017-08-05 10:42 UTC

**Comment by SOftEngrAtta** [comment] 2017-08-05 10:57
Thankyou @Snuffleupagus
