### ISSUE TITLE
Page preview is not working for LaTeX listings documentation

### ISSUE THREAD

**Issue by rimace** [mozilla/pdf.js#13722] opened 2021-07-12 12:47 UTC
https://ctan.space-pro.be/tex-archive/macros/latex/contrib/listings/listings.pdf

Configuration:
- Web browser and its version: Firefox 89.0.2
- Operating system and its version: Fedora 34
- PDF.js version: 2.9.45
- Is a browser extension: No

Steps to reproduce the problem:
1.  Go to the [LaTeX listings PDF documentation](https://ctan.space-pro.be/tex-archive/macros/latex/contrib/listings/listings.pdf)
2. Look at the preview of the pages (left sidebar)

What is the expected behavior?
Previews of the pages should be shown on the left sidebar
![grafik](https://user-images.githubusercontent.com/6343665/125289265-955ed700-e30e-11eb-9652-f0b7ebcc0d84.png)

What went wrong?
The previews are not shown and instead blank pages with different colors
![grafik](https://user-images.githubusercontent.com/6343665/125289214-8546f780-e30e-11eb-998b-40bc976943db.png)

Note:
It works if the document is downloaded and opened from there

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-07-12 13:12
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1713619

**Closed by Snuffleupagus** 2021-07-12 13:12 UTC
