### ISSUE TITLE
PDF.js Can respond to the onTouch Event on the mobile end?

### ISSUE THREAD

**Issue by JiangWeian** [mozilla/pdf.js#12671] opened 2020-12-01 07:10 UTC
I want to implemet double finger operation on the mobile end to zoom PDF with reset scale

**Comment by Snuffleupagus** [comment] 2020-12-01 10:26
Likely a duplicate of #2582; however this issue is missing *all* of the information required to be actionable/valid.

**Closed** 2020-12-01 22:19 UTC
