### ISSUE TITLE
some light lines show up

### ISSUE THREAD

**Issue by loooong** [mozilla/pdf.js#10882] opened 2019-06-04 10:54 UTC
PDF is here:
http://file.finance.sina.com.cn/211.154.219.97:9494/MRGG/CNSESH_STOCK/2018/2018-12/2018-12-28/4956779.PDF

Configuration:
- Web browser and its version:
google chrome 74.0.3729.169
- Operating system and its version:
windows 10
- PDF.js version:
just use https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension:

Steps to reproduce the problem:
1. upload the pdf to https://mozilla.github.io/pdf.js/web/viewer.html
2. there are some light lines in the many cells 

What is the expected behavior? (add screenshot)
no light lines as in adobe pdf reader or native chrome
![image](https://user-images.githubusercontent.com/8617946/58874463-73d89d80-86fb-11e9-9935-d9da0f0c9432.png)

What went wrong? (add screenshot)
 there are some light lines on the pdf.
![image](https://user-images.githubusercontent.com/8617946/58874050-58b95e00-86fa-11e9-85d9-ca1257dba3ae.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-06-04 11:05
Duplicate of #4860.

**Comment by loooong** [comment] 2019-06-04 11:15
@Snuffleupagus thank you. I check #4860, but fail to find any solution for this case.

**Comment by Snuffleupagus** [comment] 2019-06-04 15:54
> I check #4860, but fail to find any solution for this case.

It's commonplace in all bug trackers to close duplicate issues, in order to keep the number of open ones more manageable and to keep relevant discussion in *one* place rather than spread out, however that does *not* imply that the issue has to be fixed.

**Closed** 2019-06-04 21:15 UTC
