### ISSUE TITLE
Pdfjs in angular module with requirejs

### ISSUE THREAD

**Issue by zen2k** [mozilla/pdf.js#7364] opened 2016-05-27 03:24 UTC
I'm using PDFJS (v1.1) in my angular app. The code to load it is posted below. This is working but I found that the getDocument function leaks memory. The memory usage goes up as and when I load new pdf documents on the browser. I thought upgrading to v1.5 might solve problems but the code below doesn't work when I try to load PDFJS in the window namespace.

I have two questions:
1. How can I fix the memory leak? I tried calling pdf.destroy() and pdf.cleanup() before every render but the memory usage keeps increasing albeit at a slower pace.Please note pdf object here is the response of the getDocument promise.
2. How can I ensure below code works with V1.5? Am I missing something? My assumption was that as soon as I load pdfjs via amd, it should be available on the window namespace.

require.config({
    paths: {
        'angular': '../utils/angular/angular',
        'angular-route': '../utils/angular/angular-route',
        'pdfjs':'../utils/pdfjs',
    }
});
define([
    'angular',
    'pdfjs/pdf',
    'pdfjs/pdf.worker',
    'pdfjs/compatibility'
], function(angular) {
    'use strict';
    var pdf = angular.module('pdf', []);
    pdf.factory('PDFJS', function () {
        return window.PDFJS;
    });
    return pdf;
});

Thanks in advance.

I also tried loading pdfjs 1.5 as below but I get an error. PDFJS is undefined.
 require([
        'http://mozilla.github.io/pdf.js/build/pdf.js'
    ], function (PDFJS) {
        PDFJS.workerSrc = '../../src/worker_loader.js';
    });

**Comment by zen2k** [comment] 2016-05-30 06:22
Guys - Any help is really appreciated here. Did no one report a memory leak problem with pdfjs before?

**Comment by Snuffleupagus** [comment] 2016-05-30 10:21
> Did no one report a memory leak problem with pdfjs before?

In this case, it could very well be caused by Angular, so it's difficult to say what the problem is given the information provided.
Regarding the problems with PDF.js version `1.5.x`, as outlined in [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), please provide access to a working example, since it's generally difficult to troubleshoot with only code snippets.

**Comment by zen2k** [comment] 2016-05-31 06:04
Thanks for replying. We ruled out angular as a possible cause for memory leak. Also, when the getDocument api call is commented, the memory leak goes away. Using pdf.destroy() api actually slows down the leak.

Coming to 1.5x issue, the code snippet i thought was pretty straightforward. I have nevertheless created a fiddle - https://jsfiddle.net/pq1tm0y0/. Please take a look. Thanks

**Comment by yurydelendik** [comment] 2016-05-31 12:20
Closing as duplicate of #7287 - you did not specify the correct AMD module name and, also, the path to the library:

```
require.config({
  paths: {'pdfjs-dist': 'https://npmcdn.com/pdfjs-dist'}
})
require(['pdfjs-dist/build/pdf'], function (PDFJS) {
alert(PDFJS);
alert(window.PDFJS);
});
```

**Closed by yurydelendik** 2016-05-31 12:20 UTC
Labels: 1-other, 4-information-requested
