### ISSUE TITLE
For pdf.js version > v3.4.120 the images cannot be extracted from the pdf pages using page.objs.get()

### ISSUE THREAD

**Issue by JMG74** [mozilla/pdf.js#17819] opened 2024-03-21 17:09 UTC
Attach (recommended) or Link to PDF file here:
[pdf.js_20240321.zip](https://github.com/mozilla/pdf.js/files/14704557/pdf.js_20240321.zip)

Configuration:
- Web browser and its version: Google Chrome 122.0.6261.129
- Operating system and its version: Windows 11
- PDF.js version:   version >= 3.5.141
- Is a browser extension:  NO

Steps to reproduce the problem:
1. Unzip the attached ZIP file in a temp directory ==> 3 files (2 html, 1 pdf)
2. The working example:
    1. Load the HTML file: repro_bug_GOOD.html
    2. Click on button and select the pdf file: Wimshurst_Machine_Wikipedia.pdf
    3. The result should be: 
img_p1_1: data.length = 184140
img_p1_2: data.length = 182655
img_p1_3: data.length = 81840
img_p1_4: data.length = 14840
img_p0_1: data.length = 268290
img_p0_2: data.length = 339570
img_p0_3: data.length = 108900
img_p0_4: data.length = 14840

4. The NOT working example:
    1. Load the HTML file: repro_bug_BAD.html
    2. Click on button and select the pdf file 
    3. Nothing is displayed because the images content are not found by command page.objs.get() (on line 77)

What is the expected behavior? (add screenshot)
See above. The expected result is described at § 1.iii above.

What went wrong? (add screenshot)
When pdf.js version is greater than v3.4.120 (loaded from https://www.jsdelivr.com/package/npm/pdfjs-dist?version=3.4.120) the images cannot be extracted from the pdf pages at line 77 where using page.objs.get()

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Thanks in advance and I'm staying at your disposal for any complement.

**Comment by Snuffleupagus** [comment] 2024-03-21 17:53
Duplicate of https://github.com/mozilla/pdf.js/issues/16282

**Closed by Snuffleupagus** 2024-03-21 17:53 UTC
