### ISSUE TITLE
Search does not find all matches

### ISSUE THREAD

**Issue by aleth** [mozilla/pdf.js#3986] opened 2013-12-01 19:21 UTC
Example: Search for "functions of order" in http://www.math.lsa.umich.edu/~idolga/modular.pdf.
There is a match on page 32 which is not found, possibly because the text there is set in italics?

**Comment by timvandermeij** [comment] 2015-01-27 19:47
Closing as fixed. I cannot reproduce the original problem posted in this issue anymore with the latest version of PDF.js. There are already issues open for the other issues mentioned here.

**Closed by timvandermeij** 2015-01-27 19:47 UTC
Labels: 4-text-selection
