### ISSUE TITLE
Can't cleanup worker memory 2 GB after rendering the 1,5m pdf file

### ISSUE THREAD

**Issue by FitsnerAS** [mozilla/pdf.js#10730] opened 2019-04-12 10:20 UTC
Attach (recommended) or Link to PDF file here:
![image](https://user-images.githubusercontent.com/13497335/56030240-0b85c500-5d25-11e9-909c-fcb2ff3597c0.png)

file https://sambazmusic.files.wordpress.com/2017/08/give-and-take.pdf
Configuration:
- Web browser and its version: Chrome 73.0.3683.103 (Official Build) (64-bit)
- Operating system and its version: win 10
- PDF.js version: Stable (v2.0.943)
- Is a browser extension: not

Steps to reproduce the problem:
1. render pages one by one threw url
2. we perform page.cleanup(); after each iteration.
3 On destroy we perform
_pdfDoc._transport.commonObjs.clear();
_pdfDoc._transport.fontLoader.clear();  
_pdfDoc._transport.loadingTask.destroy();
_pdfDoc._transport.pageCache = [];
_pdfDoc.destroy();

What is the expected behavior? 
Want to clean worker memory after rendering or by destroy
What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by FitsnerAS** [comment] 2019-04-12 10:20
Thanks a lot!

**Comment by Snuffleupagus** [comment] 2019-04-12 10:27
> Attach (recommended) or Link to PDF file here:

This information is required, in order for the issue to be actionable/valid.

> PDF.js version: all

Please make sure to always provide actual version numbers when reporting an issue, since "all" isn't that helpful in general.

> wand to clean worker memory after rendering or by destroy

You'll need to provide the code you're using, since this isn't nearly enough information as-is.

**Comment by FitsnerAS** [comment] 2019-04-12 10:36
var defer = $q.defer();
                previousPromise.then(function () {
                    
                    params.page.cleanupAfterRender = true;
                    params.page.render(params.renderContext)
                    .then(function () {
                        // Returns a promise, on resolving it will return text contents of the page
                        return params.page.getTextContent();
                    })
                    .then(function (textContent) {
                        var canvasPosition = angular.element(params.canvas).position();
                        var textLayerDiv = document.createElement('div');

                        textLayerDiv.setAttribute('class', 'text-layer');
                        params.pdfPage.appendChild(textLayerDiv);

                        // Assign CSS to the text-layer element
                        angular.element(textLayerDiv).css({
                            left: canvasPosition.left + 'px',
                            top: canvasPosition.top + 'px',
                            height: params.canvas.height + 'px',
                            width: params.canvas.width + 'px'
                        });

                        // Pass the data to the method for rendering of text over the pdf canvas.
                        _pdfjs.renderTextLayer({
                            textContent: textContent,
                            container: textLayerDiv,
                            viewport: params.renderContext.viewport,
                            textDivs: []
                        });
                        
                        params.page.cleanup();
                        
                        defer.resolve();
                    })
                    .catch(function (err) {
                        LogSvc.error('Failed to add page to container. ', err);
                    });
                })
                .catch(function () {
                    // Need to prevent possibly unhandled rejection after close pdf
                    // if page rendering still in progress
                });

**Comment by Snuffleupagus** [comment] 2019-04-12 11:10
Can you reproduce this issue when opening the PDF file, either by drag-and-drop or using the "Open File" on the toolbar) with the latest version of the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html)?

I've just tried that, and cannot spot any huge increases in memory usage when looking at the Task Manager. However, there's been a few recent patches (thus not included in version `2.0.943`) that should have improved memory usage during (some) image decoding, which could be a possible explanation here.

If you can *only* reproduce this in a custom implementation, and not in the  [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html), please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by FitsnerAS** [comment] 2019-04-12 11:48
Ok, understood. But do you have any method to clear worker? Or it is cleared by itself?

**Comment by Snuffleupagus** [comment] 2019-04-12 12:31
> But do you have any method to clear worker? Or it is cleared by itself?

With the exception of various font data, which will never reaches gigabytes in practice, the worker doesn't really cache all that much data long term (i.e. after a page has been parsed).
Hence I'd like to challenge the assumption that it's the worker holding onto all of this memory; anyway clearing out various main- *and* worker-thread caches is done with the `PDFDocumentProxy.cleanup` method: https://github.com/mozilla/pdf.js/blob/74561f58b55fc5570c1d273d1eb53ed0f1725464/src/display/api.js#L766-L771

Without PRs such as #10595 and #10644 though, it's probably the main-thread that's holding onto more data than it should. Furthermore, it's difficult to tell from just the code-snippet in https://github.com/mozilla/pdf.js/issues/10730#issuecomment-482526724, but if you're rendering *all* of the document at once it may simply be the `<canvas>` elements that's taking up memory; please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages

**Comment by timvandermeij** [comment] 2019-04-12 22:10
Closing since this is answered. If there is an actual bug after your investigation, please create a new issue specifically for that and clearly outline where the problem is with steps to reproduce. Thanks.

**Closed by timvandermeij** 2019-04-12 22:10 UTC
