### ISSUE TITLE
Worker was destroyed (multiple PDF viewer in one page)

### ISSUE THREAD

**Issue by ctessier** [mozilla/pdf.js#7679] opened 2016-09-28 10:25 UTC
Link to PDF file (or attach file here):

Configuration:

Web browser and its version: chrome, latest
Operating system and its version: Windows 7
PDF.js version: 1.5.0
Is an extension: no
Steps to reproduce the problem:

Hi,

I am trying to have multiple PDF.js viewer in one single page. Also, I have the following error message : "Worker was destroyed" in the first viewer and just the top bar for the second viewer (see screenshots below). Also, the PDF in the first viewer is actually the one supposed to be in the second viewer. Also, when wanting to go the next page on the first viewer, it jumps 2 pages instead of 1

I thought this was made possible by the pull request #6571?

![2016-09-28 12_19_43-emploi - test elise - institut national du cancer _ institut national du cancer](https://cloud.githubusercontent.com/assets/4518186/18910014/6d20017e-8576-11e6-94f6-eac37226fcd1.png)

![2016-09-28 12_24_10-emploi - test elise - institut national du cancer _ institut national du cancer](https://cloud.githubusercontent.com/assets/4518186/18910030/7cb5e2c0-8576-11e6-8e0c-97d9d9db5fdf.png)

Thanks for your help
Regards

**Comment by yurydelendik** [comment] 2016-09-28 13:03
Unable to reproduce. Closing as incomplete.

**Closed by yurydelendik** 2016-09-28 13:03 UTC
