### ISSUE TITLE
Catch "Fetch API cannot load" error

### ISSUE THREAD

**Issue by sergey-yarchuk-4ib** [mozilla/pdf.js#8941] opened 2017-09-21 15:45 UTC
Link to PDF file (or attach file here): any wrong url to pdf document :)

Configuration:
- Web browser and its version: Version 60.0.3112.113 (Official Build) (64-bit)
- Operating system and its version: Windows 10 (64-bit)
- PDF.js version: v1.9.426
- Is an extension: no

Steps to reproduce the problem:
- ```PDFJS.getDocument(wrong_url).then(...).catch(...)```
 How to catch error of wrong url to pdf document?

What is the expected behavior? (add screenshot)
Right behavior ``` PDFJS.getDocument(url).catch() ``` - without browser errors.

 What went wrong? (add screenshot)
![ce4c3997f1](https://user-images.githubusercontent.com/25957168/30704869-a80fe4b6-9efc-11e7-954a-708f67f007c2.jpg)

**Comment by timvandermeij** [comment] 2017-09-21 20:56
The solution for this is provided in #7763. Closing since this is a duplicate.

**Closed by timvandermeij** 2017-09-21 20:56 UTC

**Comment by yurydelendik** [comment] 2017-09-22 14:09
Per [documentation](https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L176),  getDocument returns PDFLoadingTask and not a promise. See its `promise` property: `PDFJS.getDocument(url).promise.catch()`. Closing as answered.

Also notice, the issue is missing browser details and complete example to reproduce the issue.
