### ISSUE TITLE
Current version does not seem to work, in none browsers!!

### ISSUE THREAD

**Issue by jmar83the2nd** [mozilla/pdf.js#9526] opened 2018-03-04 17:18 UTC
Attach (recommended) or Link to PDF file here:
http://cdn.mozilla.net/pdfjs/helloworld.pdf

Configuration:
- Web browser and its version: chrome, edge, firefox - most current versions! (Feb. 04. 2018)
- Operating system and its version: win10 x64 prof
- PDF.js version: most current from http://mozilla.github.io/pdf.js/build/pdf.worker.js, linked in the source
- Is a browser extension: no

Steps to reproduce the problem:
1. Visit that page: https://mozilla.github.io/pdf.js/examples/
2. Click on "Result"
3. It results in an empty rectangle, no content

What is the expected behavior? (add screenshot)
That it shows the PDF's content "Hello, world!" (http://cdn.mozilla.net/pdfjs/helloworld.pdf) in the rectangle!

What went wrong? (add screenshot)
https://image.ibb.co/hUz1JS/Unbenannt.jpg

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/examples/

**Comment by jmar83the2nd** [comment] 2018-03-04 17:37
- disable "Popup Blocker Pro" in Chrome does also not solve the problem!!

**Comment by jmar83the2nd** [comment] 2018-03-04 17:42
- Safari 5.1.7 (last version for windows) can't open the page, so i can't test with it..

**Comment by jmar83the2nd** [comment] 2018-03-04 17:43
- Opera does also not work!!

**Comment by p3sn** [comment] 2018-03-05 09:02
Reproduced it, visit: http://mozilla.github.io/pdf.js/examples/index.html#interactive-examples
Chrome 64.0.3282.186 on Mac.
Click on a result tab in the examples, see console error: Uncaught ReferenceError: PDFJS is not defined at window.onload ((index):61)

**Comment by p3sn** [comment] 2018-03-05 09:10
I changed my code to:
```
<script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>
<script>
    'use strict';
    var PDFJS = {};
    PDFJS.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';
    console.log(PDFJS);
</script>

```
Next error is: PDFJS.getDocument is not a function

**Comment by p3sn** [comment] 2018-03-05 10:58
Solution: download a version from 10 days ago and host it yourself: https://github.com/mozilla/pdfjs-dist/tree/ba20b1adfcad8a5d9f6126b37062d52f3bd524b2

**Comment by p3sn** [comment] 2018-03-05 12:25
The 'good' solution is to replace PDFJS with pdfjsDistBuildPdf.
So: 
pdfjsDistBuildPdf.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';
and
pdfjsDistBuildPdf.getDocument({data: pdfData});

The problem occurred after this commit: https://github.com/mozilla/pdf.js/commit/b8606abbc1448ffd26ad553b253e2fb72d7f2cb7

**Comment by Michal-sk** [comment] 2018-03-05 12:35
@p3sn  correct we can see the change here:
https://github.com/mozilla/pdf.js/commit/c33bf800cc87941cc681c3c54279ab1b9745650d

The PDFJS reference is removed.

**Comment by jmar83the3rd** [comment] 2018-03-05 12:52
(Github always lock my accounts when i enter wrong login informations, because of that i now created one account more...;) "Please wait a while and try again later." -> And WTF means "a while"...?? A minute, a hour, a day, a week, a month...?)

In your case, i would change the example's source on https://mozilla.github.io/pdf.js/examples/

I still can't believe that im the 1st person who realize that the example source code is wong...;)

However, thank you for your feedbacks. Will try it as soon as possible...

**Comment by chirag64** [comment] 2018-03-05 15:46
I reported the same thing in #9525 but it was closed as invalid :( . Basically they broke backward compatibility.

**Comment by jmar83the2nd** [comment] 2018-03-05 15:51
Oh, i didn't saw that.

**Comment by timvandermeij** [comment] 2018-03-05 22:20
Two days ago we merged the pull request that removed the `PDFJS` object. This is targeted for version 2.0, which is not officially released yet, so make sure to pin your version to 1.x until it is. The official release is tracked in #9521, the documentation about the backwards incompatible changes is tracked in #9528 and updating the JSFiddle examples is tracked in #9529, so I'm closing this issue in favor of those more specific issues.

**Closed by timvandermeij** 2018-03-05 22:20 UTC

**Comment by timvandermeij** [comment] 2018-03-07 21:55
The examples have been fixed now.
