### ISSUE TITLE
Letter alignment of diagonal text regressed in Firefox 47 on Linux

### ISSUE THREAD

**Issue by fkaelberer** [mozilla/pdf.js#7342] opened 2016-05-21 19:33 UTC
PDF file:
https://web.archive.org/web/20160328235633/http://www.bvg.de/images/content/linienverlaeufe/LinienverlaufBus101.pdf

Affected Configurations:
- Firefox 48.0a1 (2016-04-01) + Linux Mint 17.3 (screenshot, right)
- Firefox 48.0b9 + Linux Mint 17.3
- Firefox 46.0.1 + Android 6.0.1
- Firefox 47.0b6 + Android 6.0.1
- Firefox 48.0b6 + Android 6.0.1
- HWA off & on

Not Affected:
- Firefox 46.0 + Linux Mint 17.3 (screenshot, left)
- Firefox 47.0 + Linux Mint 17.3
- Firefox 50.0a1 (2016-07-11) + Linux Mint 17.3
- Google Chrome 
- Firefox 46-49 + Windows

PDF.js version: 1.5.264
Is an extension: No

What went wrong? 

The image shows the pdf file in the demo viewer on Firefox 46 (left) and Firefox 48 (right). On the right side, letters are not aligned.
![wrongletteralignment](https://cloud.githubusercontent.com/assets/4624768/15450402/eeaf8f94-1f9a-11e6-90af-56535e3e24d6.png)

**Comment by timvandermeij** [comment] 2016-05-22 11:44
This is related to #7277 where we first spotted this. As far as I know this has not yet been reported upsteam. Can someone take care of that who knows where the right place is to report these kinds of issues upsteam?

**Comment by fkaelberer** [comment] 2016-05-23 18:38
I noticed that it's broken in Firefox 46 on Android already, and updated the initial comment accordingly.

**Comment by timvandermeij** [comment] 2016-07-19 10:43
@fkaelberer Does this still happen? It seems fixed for my using Firefox 47.0.1 on Arch Linux and the bots also don't have this problem anymore, so I think upstream uplifted a patch for this.

**Comment by fkaelberer** [comment] 2016-07-19 11:19
Still broken with pdf.js 1.5.343 / Firefox 48.0b6.

**Comment by Snuffleupagus** [comment] 2016-07-21 21:17
@fkaelberer Based on your "Not Affected:" list above, it seems that this has been fixed upstream.
Would you be able to use `mozregression`, see http://mozilla.github.io/mozregression/, to find out when and in which commit/bug this was fixed.

**Comment by fkaelberer** [comment] 2016-07-21 22:25
@Snuffleupagus Awesome tool ;-) 
Broke in https://hg.mozilla.org/integration/mozilla-inbound/rev/180f3f0494a7
Fixed in https://hg.mozilla.org/integration/mozilla-inbound/rev/2a0eda9a4bb6

**Comment by timvandermeij** [comment] 2016-07-22 10:48
Thank you for looking into that! Based on these findings I'm closing this issue as fixed, also since it's not something we can address in PDF.js as it's really a browser bug.

**Closed by timvandermeij** 2016-07-22 10:48 UTC
Labels: 3-upstream, 4-firefox-specific, 4-os-linux

**Comment by Snuffleupagus** [comment] 2016-07-22 10:58
> [...] also since it's not something we can address in PDF.js as it's really a browser bug.

What could perhaps be done is to comment in https://bugzilla.mozilla.org/show_bug.cgi?id=1274111, referring to e.g. this issue and pointing out that it's affecting the PDF viewer in Firefox on Linux, and ask if the patch could perhaps be uplifted to Firefox 48.
At this point, we're getting close to the next Firefox release, but I suppose it can't hurt to ask!

**Comment by timvandermeij** [comment] 2016-07-22 11:02
Sounds good. It might prevent issues for the next release(s).
