### ISSUE TITLE
ChoiceWidgetAnnotation must not call trim() on an array of options

### ISSUE THREAD

**Issue by stephanrauh** [mozilla/pdf.js#14696] opened 2022-03-20 12:17 UTC
Attach (recommended) or Link to PDF file here:
[OoPdfFormExample.pdf](https://github.com/mozilla/pdf.js/files/8311175/OoPdfFormExample.pdf)

Configuration:
- Web browser and its version: every browser. Tested with Chromium (Version 99.0.4844.74 (Official Build, ungoogled-chromium) (arm64)).
- Operating system and its version: every OS.
- PDF.js version: current master branch (since February 12, 2021)
- Is a browser extension: no

Steps to reproduce the problem:
1. navigate to https://mozilla.github.io/pdf.js/web/viewer.html
2. open the attached document
3. select multiple options in the field "Database experience"
4. print the document

What is the expected behavior? (add screenshot)
The selected options are printed.

What went wrong? (add screenshot)
The options are not printed. The console window shows the message "util.js:407 Warning: getOperatorList - ignoring annotation data during `Warning: getOperatorList - ignoring annotation data during "GetOperatorList: page 0" task: "TypeError: value.trim is not a function".`

Debugging shows that the offending line is https://github.com/mozilla/pdf.js/blob/feea2b78fab64d1b1c000ab5a0a6bb875d2a7dfe/src/core/annotation.js#L1490. The variable `value` contains an array of the option you've selected, and arrays don't offer the method `trim()`.

![image](https://user-images.githubusercontent.com/3045767/159161646-32fb397c-f0b6-4008-ad0f-d9ab1cc3cb80.png)

The bug was introduced with the merge: https://github.com/mozilla/pdf.js/pull/12759

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
mozilla.github.io/pdf.js

**Comment by stephanrauh** [comment] 2022-03-20 12:32
After fixing the `value.trim()` bit I ran into another bug. Maybe the problem is worse. 

<img width="683" alt="image" src="https://user-images.githubusercontent.com/3045767/159162306-c5d30a8f-d5be-4e03-8d95-88554bcbab0a.png">

**Comment by Snuffleupagus** [comment] 2022-03-20 12:32
Duplicate of #12189

**Closed by Snuffleupagus** 2022-03-20 12:32 UTC
