### ISSUE TITLE
fullscreen : 2 pages next to each other

### ISSUE THREAD

**Issue by ctessier** [mozilla/pdf.js#7620] opened 2016-09-09 08:43 UTC
Link to PDF file (or attach file here):

Configuration:

Web browser and its version: chrome, latest
Operating system and its version: Windows 7
PDF.js version: latest
Is an extension: 
Steps to reproduce the problem:

Hi,

Is there a way to tell PDFjs to put two pages next to each other on fullscreen?

Thanks for your help
Regards

**Comment by Snuffleupagus** [comment] 2016-09-09 09:45
> Is there a way to tell PDFjs to put two pages next to each other on fullscreen?

No; this isn't possible either in normal mode *or* Presentation Mode.

Closing as duplicate of issue #590, which tracks the general feature of side-by-side pages. (As indicated in that issue, and in the various PRs that have tried to implement it, it's not easy feature to implement.)

**Closed by Snuffleupagus** 2016-09-09 09:45 UTC
