### ISSUE TITLE
Improving memory usage for PDF files loaded by chunks

### ISSUE THREAD

**Issue by bh213** [mozilla/pdf.js#5329] opened 2014-09-23 10:47 UTC
When file is loaded using  pdfDataRangeTransport  ChunkedStream will allocate memory for the whole file. In our case opening 1.9GB PDF file crashed practically every browser except 64-bit Chrome and even that one had 50-50 chance of crashing.

I have refactored ChunkedStream to use non-continuous memory.  Reading (but not displaying) the same file now consumes 50MB or so. My commit is here:

https://github.com/bh213/pdf.js/commit/161218e81a74c3256703f9dbc8dbf09713c5dcaf

I've added unit tests and the code passes all the tests. Still, I am not sure this is ready for pull request yet. There is no eviction (even though it is trivial to implement) and I'd like a review of both of my one line changes to core.js and worker.js. I haven't done any pull requests before so I probably did something else wrong too.

**Comment by Snuffleupagus** [comment] 2021-05-29 07:59
Closing as, mostly a, duplicate of issue #5304.

**Closed by Snuffleupagus** 2021-05-29 07:59 UTC
Labels: 1-core
