### ISSUE TITLE
[Question] Do not remove previous matches highlights

### ISSUE THREAD

**Issue by dgoiko** [mozilla/pdf.js#11748] opened 2020-03-25 17:52 UTC
I'm trying to modify pdf.js to accept an array of terms in the "find" argument (i added a different one to maintain compatibility with original software). Those terms may be single or multi word, and if there's a term like "hello world" a hello not followed by world must not match.

I've done everything by now, and it works fine: the system recieves the json stringified list, creates an array and iterates over it executing the search function.

	for(i=0; i<complexSearch.length;i++){
            var term = complexSearch[i].trim();
        	this.eventBus.dispatch('findfromurlhash', {
        	      source: this,
        	      query: term,
        	      phraseSearch: true
        	  });
        }

The problem is that when it searches for the second term, it deletes all previous matches, third term deletes second, and o on, so at the end only the last term is highlishted.

**My question is: Where should I look to avoid this behaviour? I don't mind if it is a dirty fix like "it will never be able to remove highlights again", I wouldn't mind.**

I don't need a ready to implement answer either, if someone points me in the right direction It'd be enough to get started, I'm becoming crazy. I'm not a JS developer, so this kind of complexity is far above my head.

**Edit**:
As stated in the answers, I solved this by adding a _calculateArrayMatch.
I can update this to be compilant with the master and make a clean pull request with it, if someone is interested.

**Comment by dgoiko** [comment] 2020-03-25 19:22
Note of my advances:

I found this into updateMatches:

	for (var i = 0, len = matches.length; i < len; i++) {
		        var match = matches[i];
		        var begin = Math.max(clearedUntilDivIdx, match.begin.divIdx);
		        for (var n = begin, end = match.end.divIdx; n <= end; n++) {
		          var div = textDivs[n];
		          div.textContent = textContentItemsStr[n];
		          div.className = '';
		        }
		        clearedUntilDivIdx = match.end.divIdx + 1;
		      }

And after comenting it, it is "only" overriding matches that are in the same line than an existing one.

It is done inside render matches, into the local function beginText at line textDivs[divIdx].textContent = '';

I guess "all" I have to do is find a way to preserve those results when there's a match there, maybe using regexp, although it would decrease search performance a lot...

**Comment by dgoiko** [comment] 2020-03-25 22:09
I completely changes myu approach.

Instead of kicking my head on the wall, i decided to change the search functio itself to accept an array:


    {
    key: '_calculateMatch',
    value: function _calculateMatch(pageIndex) {
    	var pageContent = this._normalize(this._pageContents[pageIndex]);
        var arraySearch = Array.isArray(this._state.query);
        var query;
        if(arraySearch) {
        	var i;
        	query = []
        	for(i=0; i<this._state.query.length; i++) {
        		query.push(this._normalize(this._state.query[i]));
        	}
        }else{
      	  query = this._normalize(this._state.query);
        }
        var _state = this._state,
            caseSensitive = _state.caseSensitive,
            entireWord = _state.entireWord,
            phraseSearch = _state.phraseSearch;

        if (query.length === 0) {
          return;
        }
        if (!caseSensitive) {
          pageContent = pageContent.toLowerCase();
          if(arraySearch) {
          	var i;
          	for(i=0; i<query.length; i++) {
          		query[i] = query[i].toLowerCase();
          	}
          }else{
              query = query.toLowerCase();
          }
        }
        if(arraySearch) {
      	  this._calculateArrayMatch(query, pageIndex, pageContent, entireWord);
        } else{
      	  if (phraseSearch) {
          	  this._calculatePhraseMatch(query, pageIndex, pageContent, entireWord);
            } else {
          	  this._calculateWordMatch(query, pageIndex, pageContent, entireWord);
            }
        }
        
        this._updatePage(pageIndex);
        if (this._resumePageIdx === pageIndex) {
          this._resumePageIdx = null;
          this._nextPageMatch();
        }
        var pageMatchesCount = this._pageMatches[pageIndex].length;
        if (pageMatchesCount > 0) {
          this._matchesCountTotal += pageMatchesCount;
          this._updateUIResultsCount();
        }
    }
      }


And:

    {
	    key: '_calculateArrayMatch',
	    value: function _calculateWordMatch(queryArray, pageIndex, pageContent, entireWord) {
	      var matchesWithLength = [];
	      for (var i = 0, len = queryArray.length; i < len; i++) {
	        var subquery = queryArray[i];
	        var subqueryLen = subquery.length;
	        var matchIdx = -subqueryLen;
	        while (true) {
	          matchIdx = pageContent.indexOf(subquery, matchIdx + subqueryLen);
	          if (matchIdx === -1) {
	            break;
	          }
	          if (entireWord && !this._isEntireWord(pageContent, matchIdx, subqueryLen)) {
	            continue;
	          }
	          matchesWithLength.push({
	            match: matchIdx,
	            matchLength: subqueryLen,
	            skipped: false
	          });
	        }
	      }
	      if (!this._pageMatchesLength) {
	        this._pageMatchesLength = [];
	      }
	      this._pageMatchesLength[pageIndex] = [];
	      this._pageMatches[pageIndex] = [];
	      this._prepareMatches(matchesWithLength, this._pageMatches[pageIndex], this._pageMatchesLength[pageIndex]);
	    }
	  }

Seems to work like a charm

**Comment by Huy2122k** [comment] 2020-10-26 15:01
> I'm trying to modify pdf.js to accept an array of terms in the "find" argument (i added a different one to maintain compatibility with original software). Those terms may be single or multi word, and if there's a term like "hello world" a hello not followed by world must not match.
> 
> I've done everything by now, and it works fine: the system recieves the json stringified list, creates an array and iterates over it executing the search function.
> 
> ```
> for(i=0; i<complexSearch.length;i++){
>         var term = complexSearch[i].trim();
>     	this.eventBus.dispatch('findfromurlhash', {
>     	      source: this,
>     	      query: term,
>     	      phraseSearch: true
>     	  });
>     }
> ```
> 
> The problem is that when it searches for the second term, it deletes all previous matches, third term deletes second, and o on, so at the end only the last term is highlishted.
> 
> **My question is: Where should I look to avoid this behaviour? I don't mind if it is a dirty fix like "it will never be able to remove highlights again", I wouldn't mind.**
> 
> I don't need a ready to implement answer either, if someone points me in the right direction It'd be enough to get started, I'm becoming crazy. I'm not a JS developer, so this kind of complexity is far above my head.
> 
> **Edit**:
> As stated in the answers, I solved this by adding a _calculateArrayMatch.
> I can update this to be compilant with the master and make a clean pull request with it, if someone is interested.

Hi dgoiko, can you tell me where I have to put your function in pdfjs ? which "js-file" I have to paste in?  
I had install your pdfjs-array_search but I don't know how to search with array,I just can only search from URL
Pleasure help me :( 
sorry about my English :(

**Comment by valh1996** [comment] 2022-07-14 08:16
HHi @dgoiko, thanks for sharing. Tell me if I'm wrong, but with this approach the concern is that parameters such as `entireWord` etc. are the same for each word, it is not possible to have different parameters ?

**Comment by Snuffleupagus** [comment] 2023-04-02 16:36
Duplicate of #7442

**Closed by Snuffleupagus** 2023-04-02 16:36 UTC
Labels: other
