### ISSUE TITLE
Using pdf-dist in node.js

### ISSUE THREAD

**Issue by weicheng95** [mozilla/pdf.js#10943] opened 2019-07-04 00:26 UTC
Link:
https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js

Configuration:
- version: 2.0.943
- Using Pdf-dist in Node.js

Steps to reproduce the problem:
1. var viewport = page.getViewport({ scale: 1.0, }); line 67

What went wrong?
`
(node:21380) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Invalid canvas size
    at NodeCanvasFactory_create [as create] (C:\Users\wlau\Desktop\NodeProject\pdf\index.js:8:5)
    at C:\Users\wlau\Desktop\NodeProject\pdf\index.js:54:21
(node:21380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Solution:
But change to `var viewport = page.getViewport(1.0)` solve the problem.

**Comment by Snuffleupagus** [comment] 2019-07-04 07:01
Duplicate of issues such as #10809 and #10889, note in particular https://github.com/mozilla/pdf.js/issues/10809#issuecomment-491511414.

**Closed** 2019-07-04 21:05 UTC
