### ISSUE TITLE
Issue on rendering font

### ISSUE THREAD

**Issue by manny42** [mozilla/pdf.js#18016] opened 2024-04-29 08:33 UTC
Attach (recommended) or Link to PDF file here:
Impossible since the document is an invoice and we don´t have the right to share it sorry...
![image](https://github.com/mozilla/pdf.js/assets/3036008/ffdb5090-1fa1-4608-a180-d7717ee7076a)

Configuration:
- Web browser and its version: Chrome 124
- Operating system and its version: OS: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
- PDF.js version: 4.0.379
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the pdf

What is the expected behavior? It should render correctly

What went wrong?
There is an issue when trying to render the pdf. The decoding of the character seems to go wrong with the Helvetica font.
This does not happen all the time, this is a client who sent us this picture. He said that after restarting his computer it worked fine.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
The viewer is behind an authentication wall so I can't share the viewer

Sorry for the lack of context but I'm having trouble being allowed to share more... I am hoping you will recognize the issue with the screenshot otherwise you can close the issue... Thank you

**Comment by Snuffleupagus** [comment] 2024-04-29 08:44
> Attach (recommended) or Link to PDF file here:
> Impossible since the document is an invoice and we don´t have the right to share it sorry...

That unfortunately means that we'll have to close this as INCOMPLETE, since no debugging can be done with screen-shots alone.

> PDF.js version: 4.0.379

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Closed by Snuffleupagus** 2024-04-29 08:44 UTC
Labels: information-requested

**Comment by sergiubologa** [comment] 2024-10-09 08:08
@manny42 please try to edit the text in that document so you can share it for debugging. I also have a similar issue but it doesn't reproduce consistently. What I see in my document is that it doesn't render properly the texts that use Helvetica Bold Oblique.
