### ISSUE TITLE
Option to specify spread mode with URL parameter

### ISSUE THREAD

**Issue by youreunwelcome** [mozilla/pdf.js#14264] opened 2021-11-12 02:06 UTC
I know that the viewer supports URL parameters like zoom and page, etc. Would it be possible to add URL parameters for some of the view options? Specifically spread, to allow a link to open the file and display in the correct method just from the URL. The current way of changing this appears to involve actually editing viewer.js, which while feasible requires duplicate files with minor changes if you need to support even and odd spreads for different files.

**Comment by Snuffleupagus** [comment] 2021-11-12 08:00
Duplicate of #10406
Duplicate of #10042

**Closed by Snuffleupagus** 2021-11-12 08:00 UTC
