### ISSUE TITLE
Missing gradient

### ISSUE THREAD

**Issue by alafr** [mozilla/pdf.js#8565] opened 2017-06-23 04:29 UTC
Link to PDF file (or attach file here):
[gradient invisible pdfjs.pdf](https://github.com/mozilla/pdf.js/files/1096729/gradient.invisible.pdfjs.pdf)

Configuration:
- Web browser and its version: 59.0.3071.109
- Operating system and its version: Windows 10
- PDF.js version: 1.8.480
- Is an extension: No

Steps to reproduce the problem:
1. Open the file in Adobe Reader or Google Chrome
2. Open the file in PDFjs online viewer
3. Compare

What is the expected behavior? (add screenshot)
- There is an orange radial gradient, from opacity 0 at the center to opacity 1 at the page bound

![image](https://user-images.githubusercontent.com/17966696/27466423-3923639e-57e3-11e7-841f-7f498732bb20.png)

What went wrong? (add screenshot)
- The gradient is completely missing

![image](https://user-images.githubusercontent.com/17966696/27466446-63e36606-57e3-11e7-86c3-9a5e0b6b0e0a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://mozilla.github.io/pdf.js/web/viewer.html

Description of the file:
An opaque orange gradient is masked with a mask. The mask's group contains a rectangle filled with a pattern. The pattern contains an other rectangle filled with a greyscale gradient from black to white. All the rectangles, patterns & groups have the same size as the page (400x400pt).

**Comment by THausherr** [comment] 2017-06-23 10:31
Possible duplicate of #8093.

**Comment by alafr** [comment] 2017-06-23 11:37
I don't think it's a duplicate. This one has to do with the combination of mask-tiling pattern-gradient. The other issue is a hack to draw pipes and doesn't use masks at all.
It appears there is some regression since the other issue was opened:
![image](https://user-images.githubusercontent.com/17966696/27480522-f0619890-5820-11e7-924a-3d340a831fff.png)

**Closed** 2021-05-13 11:26 UTC
Labels: 4-shading-pattern
