### ISSUE TITLE
Have low light modes for dyslexic people like Rust documentation has.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [mozilla/pdf.js#14684] opened 2022-03-16 22:54 UTC
The title says it all! I have a previous version of pdf.js that I modified the background color to not use white, so it would be easier for dyslexics (I have give it to other people and it hurts less if it’s not white), but you can do much more you can emulate the modes of the rust documentation “paint brush” modes of the Rust Official Book and Rust official documentation. The prefered modes are Rust and Coal. 
Do that and you have earn the hearts of the dyslexics.

Best regards,
João

**Comment by Snuffleupagus** [comment] 2022-03-16 23:05
Duplicate of #2071

**Closed by Snuffleupagus** 2022-03-16 23:05 UTC

**Comment by shivaprsd** [comment] 2022-04-15 10:33
> emulate the modes of the rust documentation .... Do that and you have earn the hearts of the dyslexics.

@joaocarvalhoopen I made a [library](https://github.com/shivaprsd/doq) that adds this to PDF.js and an [add-on](https://github.com/shivaprsd/doqment) with it for Firefox. You will find more or less [what you want](https://github.com/shivaprsd/doq#why-doq).
