### ISSUE TITLE
Issue - When dragging your mouse across spaced lines it's highlighting the whole page

### ISSUE THREAD

**Issue by omerGithub8** [mozilla/pdf.js#14408] opened 2021-12-28 21:24 UTC
Configuration:
- Web browser and its version: Chrome (most updated version) 96.0.4664.110
- Operating system and its version: Windows 10 (20H2)
- PDF.js version: (up to date version) 2.13.5
- Is a browser extension: Yes, happens on both build/chromium unpackaged from github and on the chrome extension from the store.

Steps to reproduce the problem:
1. **Hold and drag your mouse across a pdf** 
2. **If your cursor is on a space between lines it will select/highlight the whole page**

This bug is happening very frequently when I read a paragraph, and select the text with my mouse as I'm reading through the words, sliding between lines. 
Suddenly the text is flickering between highlighting the whole page and only highlighting the selected part.

### What is the expected behavior?

![image](https://user-images.githubusercontent.com/54096264/147606086-8a1ac156-6285-4b40-bec9-086daae26934.png)
![image](https://user-images.githubusercontent.com/54096264/147606682-fd603a7f-0a95-462d-9f59-0c757a13454c.png)

### What actually happens - (Selects the whole page)

![image](https://user-images.githubusercontent.com/54096264/147606349-449d7120-8692-4046-923e-fdd6dacfa5f9.png)
![image](https://user-images.githubusercontent.com/54096264/147606868-3b2c484a-d273-4e93-8ee6-d7fc3741e6c2.png)

**Comment by Snuffleupagus** [comment] 2021-12-28 21:36
Duplicate of #9843

**Closed by Snuffleupagus** 2021-12-28 21:36 UTC
