### ISSUE TITLE
Incorrect glyph rendered

### ISSUE THREAD

**Issue by stri8ed** [mozilla/pdf.js#6424] opened 2015-09-06 21:25 UTC
See image below. `PDF.JS` is the top, and native PDF Chrome plugin is the bottom. Notice the copyright is rendered as a heart.

![pdf-glyph](https://cloud.githubusercontent.com/assets/1766843/9706685/35cf593a-54b3-11e5-8e3b-d1d3a7bce4a8.png)

Running on a windows 10 machine, Chrome (45.0.2454.85 m), using the PDF.JS chrome extension version 1.1.132. In Firefox (38.0.5), this problem does not occur.

Link to PDF - 
http://www.researchgate.net/profile/Lisa_Goehler/publication/12142078_Vagal_immune-to-brain_communication_A_visceral_chemosensory_pathway/links/0912f505b4147617c8000000.pdf

**Comment by Snuffleupagus** [comment] 2015-09-07 09:23
Closing as duplicate of issue #5589.

**Closed by Snuffleupagus** 2015-09-07 09:23 UTC
