### ISSUE TITLE
pdf file lost official seal on page 

### ISSUE THREAD

**Issue by TerryChenUI** [mozilla/pdf.js#10464] opened 2019-01-17 08:38 UTC
Attach (recommended) or Link to PDF file here:
[电子签章demo.pdf](https://github.com/mozilla/pdf.js/files/2767702/demo.pdf)

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
Just load the pdf, the official seal picture doesn't load

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by THausherr** [comment] 2019-01-17 12:44
Probably #4743.

**Comment by Snuffleupagus** [comment] 2019-01-17 12:44
Duplicate of #1076.

**Closed** 2019-01-17 21:37 UTC
