### ISSUE TITLE
pdf.js and viewer.html not working with htaccess redirect rule

### ISSUE THREAD

**Issue by thosch6** [mozilla/pdf.js#6144] opened 2015-06-25 16:00 UTC
To all you super brains out there ;-)

I have all my PDF in a folder like this:
/pdf/myFile1.pdf
/pdf/myFile2.pdf
etc.

and the viewer of pdf.js is in
/pdf.js/web/viewer.html

Now if there is a link like
&lt;a href="/pdf/myFile1.pdf">Load PDF</a&gt;
I want it to be displayed in pdf.js 

So I wrote in htaccess:
RedirectMatch 301 ^pdf(.*)$ /pdf.js/web/viewer.html?file=/pdf$1

Although this loads the correct URL in the browser like
/pdf.js/web/viewer.html?file=/pdf/myFile1.pdf

pdf.js stops loading the PDF and says
"Invalid PDF structure"

even though it has found the correct PDF address and the file itself is not corrupted!
What is the problem???
Any help very much appreciated!!!

**Comment by Snuffleupagus** [comment] 2015-06-25 16:17
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md. The *forth* paragraph is especially relevant here, and I'm quoting it here:
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, please prepare a short well-documented example that demonstrates the problem and make it accessible online on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- keep in mind that just code snippets won't help us troubleshoot the problem.

**Comment by thosch6** [comment] 2015-06-26 12:29
Rest assured, I have read all the advice available on mozilla/pdf.js Unfortunately this problem comes with .htaccess which can only be installed in the root directory. So it is very complicated to show an example of the error as this behaviour would affect all visitors to my website.

After further investigation I found out that the new htaccess generated link
/pdf.js/web/viewer.html?file=/pdf/myFile1.pdf
does not load my original myFile1.pdf What is loaded is actually the html-code of the viewer.html wrapped into a file called myFile1.pdf !! Hence the message "Invalid PDF structure"

How weird is that?

**Comment by timvandermeij** [comment] 2015-06-26 13:36
Are you sure that the path to the PDF file exists? Could you check which exact URL is used and try opening it manually in your browser to see if the htaccess redirect fails or if really the URL is just wrong?

**Comment by thosch6** [comment] 2015-06-26 14:17
Thanks a lot for your interest in this problem!

Here is the link to the PDF (myFile1.pdf)
http://www.guitar.ch/tabs/Beatles/AllYouNeedIsLove.pdf
(works perfectly being displayed with internal Chrome browser)

Now the following link written manually is still OK:
http://www.guitar.ch/pdf.js/web/viewer.html?=tabs/Beatles/AllYouNeedIsLove.pdf

As I have thousands of PDF I want them to be shown in your wonderful pds.js
all the time from now on. I added the following line to htacces (at the
very moment not activated):
RedirectMatch 301 ^/tabs(.*)$  /pdf.js/web/viewer.html?file=/tabs$1

(.*) saves whatever string is coming after "tabs" , in this case
"/Beatles/AllYouNeedIsLove.pdf"
In the 2nd half of the line "/tabs" is replaced by
"/pdf.js/web/viewer.html?file=/tabs" and $1 adds the stored string.

In the browser, the transformed URL is correctly displayed as
http://www.guitar.ch/pdf.js/web/viewer.html?=/tabs/Beatles/AllYouNeedIsLove.pdf

BUT
pdf.js stops loading the PDF with the error message:
Invalid PDF structure

When I download this corrupted PDF, it has the correct name:
AllYouNeedIsLove.pdf (see the attached file)

BUT
it´s content is the html-text of the viewer.html
(open the attached PDF with a text editor)


If you would like to see this in action, I'll be happy to turn on the
RedirectRule at a precise time for you.
I really do like your pdf.js and will definitely use it if that works!


2015-06-26 15:37 GMT+02:00 Tim van der Meij <notifications@github.com>:

> Are you sure that the path to the PDF file exists? Could you check which
> exact URL is used and try opening it manually in your browser to see if the
> htaccess redirect fails or if really the URL is just wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/pdf.js/issues/6144#issuecomment-115691137>.
>



-- 
Thomas Schilling
Heidenfeldstr. 15
10249 Berlin

**Comment by thosch6** [comment] 2015-06-26 14:27
Sorry. had a typo, please use the following text::


Thanks a lot for your interest in this problem!

Here is the link to the PDF (myFile1.pdf)
http://www.guitar.ch/tabs/Beatles/AllYouNeedIsLove.pdf
(works perfectly being displayed with internal Chrome browser)

Now the following link written manually is still OK:
http://www.guitar.ch/pdf.js/web/viewer.html?=/tabs/Beatles/AllYouNeedIsLove.pdf
<http://www.guitar.ch/pdf.js/web/viewer.html?=tabs/Beatles/AllYouNeedIsLove.pdf>

As I have thousands of PDF I want them to be shown in your wonderful pds.js
all the time from now on. I added the following line to htacces (at the
very moment not activated):
RedirectMatch 301 ^/tabs(.*)$  /pdf.js/web/viewer.html?file=/tabs$1

(.*) saves whatever string is coming after "tabs" , in this case
"/Beatles/AllYouNeedIsLove.pdf"
In the 2nd half of the line "/tabs" is replaced by
"/pdf.js/web/viewer.html?file=/tabs" and $1 adds the stored string.

In the browser, the transformed URL is correctly displayed as
http://www.guitar.ch/pdf.js/web/viewer.html?=/tabs/Beatles/AllYouNeedIsLove.pdf

BUT
pdf.js stops loading the PDF with the error message:
Invalid PDF structure

When I download this corrupted PDF, it has the correct name:
AllYouNeedIsLove.pdf (see the attached file)

BUT
it´s content is the html-text of the viewer.html
(open the attached PDF with a text editor)


If you would like to see this in action, I'll be happy to turn on the
RedirectRule at a precise time for you.
I really do like your pdf.js and will definitely use it if that works!


2015-06-26 15:37 GMT+02:00 Tim van der Meij <notifications@github.com>:

> Are you sure that the path to the PDF file exists? Could you check which
> exact URL is used and try opening it manually in your browser to see if the
> htaccess redirect fails or if really the URL is just wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/pdf.js/issues/6144#issuecomment-115691137>.
>



-- 
Thomas Schilling
Heidenfeldstr. 15
10249 Berlin



-- 
Thomas Schilling
Heidenfeldstr. 15
10249 Berlin



-- 
Thomas Schilling
Heidenfeldstr. 15
10249 Berlin

**Comment by timvandermeij** [comment] 2015-06-26 21:25
Could you try the following rule instead?

`RewriteRule ^tabs/ /pdf.js/web/viewer.html?file=/tabs/ [R=301,L]`

I used the http://htaccess.madewithlove.be website to test your original rule, but it did not change the URL at all. Of course that might just be an issue with the tool, but you can always use RewriteRule instead of RedirectMatch, and with the above rule the website *is* happy. Again, I'm not sure if it will help, but it's the best I can come up with. Otherwise more triage is needed.

**Comment by thosch6** [comment] 2015-06-26 21:29
Just activated it. It doesn’t work, same error. Go here and try:
http://www.guitar.ch/en/guitars/tabs/tabs.html


Am 26.06.2015 um 23:25 schrieb Tim van der Meij <notifications@github.com>:

**Comment by thosch6** [comment] 2015-06-26 21:33
..and this rule delivers a wrong URL in the browser like
http://www.guitar.ch/pdf.js/web/viewer.html?file=/tabs/


Am 26.06.2015 um 23:25 schrieb Tim van der Meij <notifications@github.com>:

**Comment by timvandermeij** [comment] 2015-06-26 21:36
That's unfortunate. Okay, let's disable that then. We need to do more triage for this.

**Comment by timvandermeij** [comment] 2015-06-26 21:38
Perhaps this one will work:

`RewriteRule ^tabs/(.*)$ /pdf.js/web/viewer.html?file=/tabs/$1 [R=301,L]`

This explicitly makes sure that whatever is behind `tabs/` is put in the resulting URL. You could try that, and otherwise I must leave this for further triage.

**Comment by thosch6** [comment] 2015-06-26 21:40
Using RewriteRule the correct code is:
#RewriteRule ^tabs(.*)$ /pdf.js/web/viewer.html?file=/tabs$1  [R=301,L]

This delivers the expected code
http://www.guitar.ch/pdf.js/web/viewer.html?file=/tabs/Beatles/AllYouNeedIsLove.pdf

BUT
pdf.js will say 
Invalid PDF structure

as described in my case earlier.

Am 26.06.2015 um 23:25 schrieb Tim van der Meij <notifications@github.com>:

**Comment by thosch6** [comment] 2015-06-26 21:42
OK, this is the correct rule, but it will deliver the error as described. I turned it on now, check it out:
http://www.guitar.ch/en/guitars/tabs/tabs.html


Am 26.06.2015 um 23:38 schrieb Tim van der Meij <notifications@github.com>:

**Comment by timvandermeij** [comment] 2015-06-26 21:43
Wait, I think I see what is happening. http://www.guitar.ch/tabs/Beatles/AllYouNeedIsLove.pdf is correctly rewitten to http://www.guitar.ch/pdf.js/web/viewer.html?=/tabs/Beatles/AllYouNeedIsLove.pdf, but PDF.js then tries to load whatever is in the `file` parameter, which is `/tabs/Beatles/AllYouNeedIsLove.pdf`. But, the htaccess redirect rule then again decides that `/tabs/Beatles/AllYouNeedIsLove.pdf` must be rewitten to http://www.guitar.ch/pdf.js/web/viewer.html?=/tabs/Beatles/AllYouNeedIsLove.pdf, causing the actual viewer to be loaded instead of the PDF file (since you redirect away from the actual PDF file to the viewer).

The solution would be to match `/tabs/(.*)` only if `pdf.js` does not appear in the URL.

**Comment by timvandermeij** [comment] 2015-06-26 21:47
So in fact the rule causes http://www.guitar.ch/pdf.js/web/viewer.html?=/tabs/Beatles/AllYouNeedIsLove.pdf to be transformed into http://www.guitar.ch/pdf.js/web/viewer.html?=http://www.guitar.ch/pdf.js/web/viewer.html?=/tabs/Beatles/AllYouNeedIsLove.pdf, so then you see more clearly why the viewer itself is loaded instead of the PDF file :)

**Comment by thosch6** [comment] 2015-06-26 21:47
Uh, I don’t get your solution…
What do I have to do?

Am 26.06.2015 um 23:43 schrieb Tim van der Meij <notifications@github.com>:

**Comment by thosch6** [comment] 2015-06-26 21:52
So you mean the rule is excited twice?

Am 26.06.2015 um 23:47 schrieb Thomas Schilling <schillingel@googlemail.com>:

**Comment by timvandermeij** [comment] 2015-06-26 21:53
Yes, exactly. I'm trying to figure out how to avoid that with htaccess right now in the hope to give a rule for you to test.

**Comment by timvandermeij** [comment] 2015-06-26 21:55
Probably this will help:

<pre>
RewriteCond %{REQUEST_URI} !/(pdf.js)
RewriteRule ^tabs/(.*)$ /pdf.js/web/viewer.html?file=/tabs/$1 [R=301,L]
</pre>

This makes sure that the request URI does not contain pdf.js. This means that the initial rewrite still happens, and the second time pdf.js appears in the URL because of the rewrite, so then the rule is not triggered again.

**Comment by thosch6** [comment] 2015-06-26 21:58
It’s on there, but unfortunately still doesn’t work..
http://www.guitar.ch/en/guitars/tabs/tabs.html


Am 26.06.2015 um 23:55 schrieb Tim van der Meij <notifications@github.com>:

**Comment by timvandermeij** [comment] 2015-06-26 22:13
The problem is literally this: https://github.com/mozilla/pdf.js/issues/1925#issuecomment-7265552. Since we are no htaccess experts and this is therefore a custom implementation issue, it's probably better to ask this htaccess related question on a site like StackOverflow or other sites where people can help out with htaccess rules. It is almost certainly not a problem in PDF.js itself, just with your htaccess rule. The solution is to make the rule more strict, i.e., not to match `/tabs`, but for example `.ch/tabs`, because then you avoid matching `?file=/tabs` (which contains `/tabs` too), which is what is currently happening. Unfortunately we are no htaccess experts, so it would be more of a guess than a known solution for us.

Closing as out of scope as the issue is not related to a problem in PDF.js itself, but rather an implementation issue.

**Closed by timvandermeij** 2015-06-26 22:13 UTC
Labels: 4-triage-needed

**Comment by thosch6** [comment] 2015-06-26 22:26
OK, thanks a lot for your effort. It’s just very confusing that actually the correct URL is being displayed and then the wrong thing is happening in pdf.js
Hopefully, there will be found a solution to this problem as I am not the first one having it...

Am 27.06.2015 um 00:13 schrieb Tim van der Meij <notifications@github.com>:

**Comment by andreadd** [comment] 2019-11-30 20:31
Hello Thosch6, i clicked your link: http://www.guitar.ch/tabs/Beatles/AllYouNeedIsLove.pdf
and it looks like you managed the redirect! Can you share the solution? Thank you!

**Comment by thosch6** [comment] 2019-12-09 18:41
I don't remember, that was more than 4.5 years ago...

**Comment by dbeusee** [comment] 2020-08-05 13:45
You could refer to your .htaccess file.  I'm not sure how you did it, but I did it with these .htaccess entries:
# redirect pdf files to the PDF viewer
RewriteCond %{HTTP_REFERER} !viewer.html
RewriteCond %{QUERY_STRING} !view=1
RewriteRule ^(.*)\.pdf$ /demos/pdf/web/viewer.html?file=/$1 [L]

And I modified my viewer.js to change the url for the pdf file to .pdf?view=1.  Maybe one of these was enough - I didn't test, but I just figured having both was good.  And it works.
