### ISSUE TITLE
Suggest to modify bookmark.title and it doesn't work

### ISSUE THREAD

**Issue by Einere** [mozilla/pdf.js#9107] opened 2017-11-06 14:15 UTC
Attach (recommended) or Link to PDF file here: 

Configuration:
- Web browser and its version: firefox
- Operating system and its version: ubuntu
- PDF.js version: 
- Is a browser extension:

Steps to reproduce the problem:
1. open the downloaded pdf file by pdf.js
2.

What is the expected behavior? (add screenshot)
![2017-11-06 1](https://user-images.githubusercontent.com/8300010/32444769-1503de9c-c347-11e7-9db5-726cdf910781.png)

What went wrong? (add screenshot)
![2017-11-06 2](https://user-images.githubusercontent.com/8300010/32444998-c4e24c90-c347-11e7-9ed6-2870b65d1fe0.png)

in first screenshot, bookmark.title is "지금 보이는 그대로 (복사하거나 새 창에 열기)".
but i think modify it to "북마크" or "현재 pdf를 북마크에 저장" is better.
(because "지금 보이는 그대로 (복사하거나 새 창에 열기)" is so long and inappropriate expression.)
also,in second screenshot, i clicked the "지금 보이는 그대로 (복사하거나 새 창에 열기)", but it doesn't save bookmark at firefox's bookmark tab. 
i read the issue reporting guide, but i don't understand "nightly channel".. sorry..

if i have to pull request with modify suggestion, please notice me.. :)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-11-06 15:22
The purpose of the "bookmark" button is to make it possible for the user to obtain a direct link to the currently viewed section of a PDF file, which is what the `Current view (copy or open in new window)` string intends to convey.

> but it doesn't save bookmark at firefox's bookmark tab.

Please note that PDF.js is (basically) a web-page, and as such it cannot access the bookmark functionality of the browser itself.

With the caveat that I don't speak Korean (and had to resort to Google Translate), the strings you are suggesting doesn't seem entirely appropriate given the actual functionality here. (And as noted, we don't maintain the translations in this repository.) 

Closing as invalid, since this works as intended.

**Closed by Snuffleupagus** 2017-11-06 15:22 UTC

**Comment by Einere** [comment] 2017-11-07 14:50
Thank you for explain, sir!
i am begginer programer, so i don't know pdf.js's code.
so i think that i only could contribute to translate or adjust comment (and so on..). (code level pull request is hard to me..TT)

and sorry to miss that issue doesn't accept translate..
i didn't know what is "nightly channel".

finally, thank you for friendly reply!! have a nice day!
