### ISSUE TITLE
[Bug]: ios Safari and android Chrome Mobile Device does on print showing blank pages

### ISSUE THREAD

**Issue by abdulkadarsabir** [mozilla/pdf.js#18533] opened 2024-08-01 07:14 UTC
### Attach (recommended) or Link to PDF file

![303555325-1f5ead08-fe45-4be5-94fb-2f565e2245f3](https://github.com/user-attachments/assets/cbaa45cd-7635-4e5c-a32a-27ab2d629dd8)

### Web browser and its version

android and iOS phones browser.

### Operating system and its version

windows11

### PDF.js version

1.1

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1.Open any PDF file in android and iOS browser, and click print option.
2.After click you can see on print dialog box PDF file loads blank pages or just first page of PDF

### What is the expected behavior?

1. Load all pages of pdf in print dialog box as it works on laptop browser's.

### What went wrong?

Instead of getting load all pages on print option , I can see only one page and other blank pages or all blank pages.

![303555325-1f5ead08-fe45-4be5-94fb-2f565e2245f3](https://github.com/user-attachments/assets/b315a95a-4602-48cf-a588-d5f958037b0d)

**Comment by Snuffleupagus** [comment] 2024-08-01 07:35
Duplicate of #17644

---

*Please actually fill out the issue template *correctly*, since you've included various inconsistent and incomplete information.*

> ### Web browser and its version
> 
> android and iOS phones browser.

This doesn't say anything about what browser and version is actually used.

Also, as was mentioned in https://github.com/mozilla/pdf.js/issues/17644#issuecomment-1935629453:
```
If this is only broken in some browsers/platforms, that unfortunately suggests a bug in those environments rather than here.
```

> ### Operating system and its version
> 
> windows11

This doesn't agree with the information you stated above.

> ### PDF.js version
> 
> 1.1

That's not a valid or existing version number, and anything from the `1`-branch is *many years* out of support.

**Closed by Snuffleupagus** 2024-08-01 07:35 UTC
