### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by AdamBes** [mozilla/pdf.js#5718] opened 2015-02-09 22:49 UTC
Printing a range of PDF pages seems to result in the last few being cut off. (i.e. printing from 26-31 will print pages 26-28 with a blank page in between).

Padding is miles off on some tested files (9cm along the bottom and 8cm along the right edge)
- verified and viewable on print preview (seems to have so far only occurred for some microsoft word documents. 
![screenshot 2015-02-10 11 38 57](https://cloud.githubusercontent.com/assets/9940860/6117450/78c572ee-b119-11e4-8bc7-e668a0de37c5.png)

Blank pages are being added after every page (this is visible from print preview) - issues has been consistent on each PDF ive tested except the one with large padding issues above ^
![screenshot 2015-02-10 11 40 02](https://cloud.githubusercontent.com/assets/9940860/6117474/a0764ea8-b119-11e4-97ea-9141281e16e0.png)

**Comment by timvandermeij** [comment] 2015-02-09 23:15
Do you have a PDF file for us to test with?

**Comment by AdamBes** [comment] 2015-02-09 23:38
https://www.dropbox.com/s/e2xprzc853lmxlg/example_RTL.pdf?dl=0
After each page it has inserted a blank page on print preview.

**Comment by Hengjie** [comment] 2015-02-11 21:31
@Rob--W do you have any ideas what causes this?

**Comment by Rob--W** [comment] 2015-02-12 12:41
@Hengjie Not immediately, but I have some ideas about how to debug this issue. I don't have the time to debug it at the moment.

**Comment by yafp** [comment] 2015-03-10 08:01
Hi,
i am realizing pretty similar issues with some pdf documents if i am using the PDF Viewer in Mozilla Firefox - which is pdf.js based again right?

So i am not sure if that particular problem is chrome-specific.

**Comment by Rob--W** [comment] 2015-03-10 15:35
The original link to the PDF is dead. @AdamBes and @yafp Could you share a link to the PDF file?

**Comment by yafp** [comment] 2015-03-11 07:10
Hi,
i can only provide a pdf file i used to reproduce the issue.
http://kniel.de/download/96141656.02.pdf

The printing results (using always the same printer on the same linux hosts) from within
- Adobe Acrobat: - is as expected
- Chrome: almost as expected - but embedded images seem to be shrinked compared to Acrobat
- Firefox: Footer of each page is cutted off and additional empty page is printed. Fonts mismatch in header, images seem bigger then in Acrobat. Display and printing results in firefox using pdf.js differ heavily.

Hope this helps

I was willing to attach the pdf as mirror to this issue - but github only supports image formats like png, gif and jpg. Should i offer any other mirror for that pdf as i cant quaranty it will be online for unlimited time (might be replaced with an updated version in the future)

Feel free to ask further - i will provide as much information as possible/needed ;)

Greetings

**Comment by Rob--W** [comment] 2015-03-11 09:55
In Chrome 41.0.2272.77, the print preview of the PDF looks like this, unless I change the paper size from "Letter" to "A4". Using the A4 letter size, there is a blank page between every page (just like you describe for Firefox):
![chromeprint](https://cloud.githubusercontent.com/assets/1365071/6593211/b8abc8da-c7d6-11e4-9ae9-5926c49f0a0e.png)

Chrome seems to offer `@page {size: width height;}` for more control over the paper size, but it cannot be applied to a single page only, but all pages. Since most of the pages have a fixed size, adding a paged media rule might help with resolving some of the printing issues.

@yafp For comparison, could you take a screenshot of how the PDF looks in your browser/viewer?

**Comment by yafp** [comment] 2015-03-11 10:41
Hi,
i've attached the print preview in chrome as well.
![viewerchrome](https://cloud.githubusercontent.com/assets/67605/6594658/68ef6538-c7e3-11e4-8f64-06727db46b23.png)

But please keep in mind - its not about the print preview - its about the print result ;)
Regarding the extra pages: In Firefox i get 1 blank page at the end of the document - not after each printed page.


Greetings

**Comment by Rob--W** [comment] 2015-03-11 10:51
Which version of Chrome are you using? I don't see the "Fit to page" option in Chromium 41.0.2272.77, not with the Chrome extension and neither with the built-in PDF viewer (PDFium).

If you untick "Fit to page", does Chrome's result look similar to Acrobat's?

**Comment by yafp** [comment] 2015-03-11 12:49
Hi,

i am using Chrome 39.0.2171.95 (64-bit) on Ubuntu 14.04.
If i untick the option "Fit to page" and do print again - the output looks less similar to Acrobat then before ... but actually not bad either ;)
To having the setting ticket was overall a good setting.

May i asked why you are only focusing on Chrome? 
Should i open another issue for my mozilla concerns?

**Comment by Rob--W** [comment] 2015-03-11 13:55
> May i asked why you are only focusing on Chrome?

Printing is handled differently in Firefox vs other browsers, hence I'm
only focusing on Chrome (also because the issue was reported as being
Chrome-specific).

> Should i open another issue for my mozilla concerns?

You can do that when it turns out that the root cause for the bug is
different from Chrome's. For now let's keep the discussion on this issue.

**Comment by yafp** [comment] 2015-03-11 14:05
Ok - just to have it pointed out once again.
The pdf file i did provide - had small differences between Acrobat and Chrome and big differences between Acrobat and Firefox - at least on my linux machine.

so i doubt this pdf file might be the best document to focus on chrome specific issues.

Lets hope for @AdamBes then to provide his document as well.

**Comment by Rob--W** [comment] 2015-03-16 15:10
@yafp 
I've taken another look at your PDF, in Firefox. The cut-off happens when the printer is set up to print in the US letter format (instead of A4). When I change the printer setting to print as A4 instead, I get a result that is similar to PDF.js in Chrome, namely a blank page between the real pages.

Changing the units from pt to inches (with an equivalent value, http://www.printernational.org/iso-paper-sizes.php) seems to fix the blank page problem here. I've reported the inconsistency in handling pt/inch at https://code.google.com/p/chromium/issues/detail?id=467579.

@yafp Could you check whether Firefox correctly renders your PDF when the paper size is set to A4?

**Comment by yafp** [comment] 2015-03-17 09:19
@Rob--W: 
if i do change from "Letter" to "A4" the printing result is much better. Primary because it seems to use the correct fonts now. The single pages seem cutted at the correct position.

Regarding the additional blank page:
I still have an empty/blank page at the end - so i do get my 2 pages and 1 additional blank page at the end - which is wrong.

**Comment by Rob--W** [comment] 2015-03-17 09:23
@yafp The font is probably not related to the letter size (I have seen bad fonts in Firefox's print preview during testing, that's not related to this issue).

The blank page issue only occurs in Chrome, not Firefox, right?

**Comment by yafp** [comment] 2015-03-17 15:04
No - my last comment was totally targeting Firefox (v36 on linux).
So the blank page is affecting Firefox - at least for me.

But your question made me retesting Chrome again - and it works fine for me if it comes to the blank pages

To sum it up: i do have blank pages at the end of the print if i do use Firefox - but not in Chrome.

**Comment by Rob--W** [comment] 2015-03-17 17:43
@yafp Ah, I see. I also get a blank page at the end with your PDF (http://kniel.de/download/96141656.02.pdf) in Firefox 36.0 (Linux) with paper size A4 and scale 100%.

In Chrome (using the [PDF.js Chrome extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) and presumably also in the viewer demo), I get a blank page between every page. I guess that you tested using Chrome's built-in PDF viewer instead of the PDF.js viewer?

**Comment by Hengjie** [comment] 2015-03-17 18:14
@Rob--W I've reuploaded the original PDF here:

https://dl.dropboxusercontent.com/u/7246095/example_RTL.pdf

**Comment by Rob--W** [comment] 2015-03-17 18:20
@Hengjie Thanks. It seems to be the same as the PDF reported by yafp. It seems that the issue applies to EVERY A4-sized documents (see also https://github.com/mozilla/pdf.js/issues/5718#issuecomment-81725195). I'll write a patch for PDF.js to address the issue.

**Comment by yafp** [comment] 2015-03-17 18:42
@Rob--W 
Yes i always used Chromes inbuild PDF.js - wasn't aware of a viewer. Thanks for the pointer.
Gonna play with that as well.

@Hengjie 
thanks for adding your file

**Closed** 2015-05-14 14:52 UTC
Labels: 4-chrome-specific, 4-printing
