### ISSUE TITLE
Signature is display upside down - mirror

### ISSUE THREAD

**Issue by dacsy** [mozilla/pdf.js#6694] opened 2015-11-26 04:14 UTC
I signed a document but my signature image is display upside down. What could be problem and how can I fix it ?
It look like this:
![image](https://cloud.githubusercontent.com/assets/10598358/11414949/a93b5210-942e-11e5-8733-c5939dac251f.png)

But it should be like this:
![image](https://cloud.githubusercontent.com/assets/10598358/11414963/cbd68fb0-942e-11e5-8b6d-2d6d72741931.png)

**Comment by Rob--W** [comment] 2015-11-26 11:49
Please share a link to the PDF - https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md

**Comment by timvandermeij** [comment] 2015-11-26 18:29
Closing as duplicate of #5946, judging by the screenshots and the comments there.

**Closed by timvandermeij** 2015-11-26 18:29 UTC
Labels: 4-information-requested
