### ISSUE TITLE
Error in 2.5.18 und 2.4.326 (FF version)

### ISSUE THREAD

**Issue by docwarems** [mozilla/pdf.js#11733] opened 2020-03-23 13:34 UTC
[error.pdf](https://github.com/mozilla/pdf.js/files/4369656/error.pdf)
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: FF 74.0 with pdf.js 2.4.326; https://mozilla.github.io/pdf.js/web/viewer.html with 2.5.18
- Operating system and its version: Win 10
- PDF.js version: see above
- Is a browser extension: yes/no

Steps to reproduce the problem:
1. try to open PDF
2. -> error

What is the expected behavior? (add screenshot)
Display PDF without error

What went wrong? (add screenshot)
![grafik](https://user-images.githubusercontent.com/29914148/77322019-5d93e080-6d13-11ea-9c73-120c3a692474.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2020-03-23 13:46
Duplicate of #6741

**Closed** 2020-03-23 22:44 UTC
