### ISSUE TITLE
Make acroforms PDF downloadable with filled data

### ISSUE THREAD

**Issue by Nilanth** [mozilla/pdf.js#12272] opened 2020-08-24 10:32 UTC
How to download acro form PDF with filled data or render the PDF with filled data.

**Comment by Snuffleupagus** [comment] 2020-08-24 10:39
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md* since otherwise the issue isn't actionable/valid.
Furthermore, please ensure that you provide a *clear and concise* description of whatever problem you face, to save everyone's time.

Given the lack of details, the best guess is that you should be using: https://github.com/mozilla/pdf.js/blob/0f4fc12c5e02610fdba7fd03c85efac2465cd03e/src/display/api.js#L871-L879

**Comment by Nilanth** [comment] 2020-08-24 10:47
@Snuffleupagus 
Configuration:

Web browser and its version: Chrome latest
Operating system and its version: Mac Catalina
PDF.js version: latest
Is a browser extension: no
I have fillable PDF [](https://www.irs.gov/pub/irs-pdf/f1040.pdf), where user can fill the data in the PDF but how to make this PDF downloadable with filled values.

**Comment by Snuffleupagus** [comment] 2020-08-24 10:52
> Web browser and its version: Chrome latest
> Operating system and its version: Mac Catalina
> PDF.js version: latest
> Is a browser extension: no

"latest" is of no absolutely no use, since that can mean *any number* of things!
*For future reference:* You should *always* include actual version numbers when filling out the ISSUE_TEMPLATE.

> I have fillable PDF https://www.irs.gov/pub/irs-pdf/f1040.pdf, where the user can fill the data in the PDF but how to make this PDF downloadable with filled values.

The answer in https://github.com/mozilla/pdf.js/issues/12272#issuecomment-679051439 would still apply, given the limited information provided above.

**Comment by timvandermeij** [comment] 2020-08-24 19:46
Closing since this has just been implemented and not released in e.g., `pdfjs-dist` yet. For the remainder I agree with the comment above that there is not enough information.

**Closed by timvandermeij** 2020-08-24 19:46 UTC
