### ISSUE TITLE
Presentation mode does not work on Fennec

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#6752] opened 2015-12-14 14:10 UTC
Platform: Android
Browser version: Firefox Mobile 43.0b4
Screen orientation: Portrait

1. Visit https://mozilla.github.io/pdf.js/web/viewer.html in Firefox Mobile (Fennec)
2. Tap on the presentation mode button.

Observed bugs:

- At the first time I saw the toolbar at the top, behind the page.
- There is no way to navigate to a different page.

**Comment by timvandermeij** [comment] 2015-12-14 15:42
Possibly a duplicate of #5981.

**Comment by timvandermeij** [comment] 2016-05-09 22:34
Closing as duplicate of #5981.

**Closed by timvandermeij** 2016-05-09 22:34 UTC
Labels: 1-viewer, 4-os-android
