### ISSUE TITLE
pdf.js doesn't render color accurately

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#7905] opened 2016-12-20 20:07 UTC
Link to PDF file (or attach file here): https://cloud.box.com/s/bj28pkgrx5cgfco1ip3gfbzijwaf2rmk (after following step 1 below)

Configuration:
- Web browser and its version: Chrome 55
- Operating system and its version: Mac OSX El Capitan
- PDF.js version: 1.6.334
- Is an extension: No

Steps to reproduce the problem:
1. Turn on pdf.js viewer by visiting https://cloud.box.com/on/beta
2. Visit https://cloud.box.com/s/bj28pkgrx5cgfco1ip3gfbzijwaf2rmk - the page should look like https://www.screencast.com/t/j3lGRVBpkr
3. Download the file and open with Preview/Adobe Reader/Chrome's PDFium viewer
4. Compare the files, notice that the bottom border and the logo within the 'FC ST. PAULI' is a lot more orange in pdf.js than the other viewers

What is the expected behavior? (add screenshot)
http://www.screencast.com/t/YRGazQv0

What went wrong? (add screenshot)
(hard to capture with screenshot, but you can kinda see it here: http://www.screencast.com/t/jbO02T45K)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://cloud.box.com/s/bj28pkgrx5cgfco1ip3gfbzijwaf2rmk (after following step 1 above)

**Comment by Takstone1** [comment] 2017-02-15 15:36
Can anyone help out on this one? Thanks

**Comment by brendandahl** [comment] 2017-02-16 19:38
Without diving too deep, it appears the images are CMYK images. CMYK to RGB is not straight forward and we have an formula to do this (https://github.com/mozilla/pdf.js/blob/098acb126958e8f0eb18399f1182a945e5164fd2/src/core/colorspace.js#L686). In an ideal world we'd use a full ICC profile to do the conversion, but this is expensive. With our conversion we try to balance speed and accuracy.

**Comment by Takstone1** [comment] 2017-02-21 21:01
Thanks Brendan. Apologies for my lack of knowledge on this, but you mention: 'it appears the images are CMYK images'. Would one solution be for the company in question to use a different type of image that would retain the exact colour?

Kind regards,
Tim

**Comment by brendandahl** [comment] 2017-02-22 18:12
If the pdfs are intended for printing CMYK is probably a better colorspace for the PDF. However, if you just want to preview them online, RGB would be bettter. Below is the a screenshot of various modes:

- Left: PDF.js, PDF converted to sRGB in Acrobat Pro
- Middle: PDF.js, Original PDF in PDF.js
- Right: Acrobat Pro, Original PDF

<img width="357" alt="screenshot 2017-02-22 10 07 06" src="https://cloud.githubusercontent.com/assets/942640/23225544/0d505d86-f8e7-11e6-9c18-99956519b8ee.png">

**Comment by Takstone1** [comment] 2017-02-22 22:31
Thanks for the explanation Brendan

**Comment by SamyCookie** [comment] 2018-09-11 22:27
duplicate of #2856 ?

**Comment by timvandermeij** [comment] 2018-09-12 10:56
Closing since this is a duplicate of #2856, which tracks support for ICC.

**Closed by timvandermeij** 2018-09-12 10:56 UTC
Labels: 2-image-quality
