### ISSUE TITLE
render pdf to xyz location using web url

### ISSUE THREAD

**Issue by spradhan1990** [mozilla/pdf.js#16074] opened 2023-02-20 13:14 UTC
i have just a small query, i have x,y,z location available with me, how can i add that info in url so that pdfjs render it to the location.
for eg, my url is : 
viewer.html?file=%2FACD%2Fservlet%2Fservicecenter%2Frest%2Fmedia%2FElement.Media%253A%253AVj0xfnsicklkIjoiVmVoaWNsZV9JU19Hb2xmQ2FydF9WZWhpY2xlT3JnIiwib3AiOlsiVmVoaWNsZV9JU19Hb2xmQ2FydF9WZWhpY2xlT3JnIiwiSVNfRkdDX1ZlaGljbGVPcmciLCJWZWhpY2xlXzAwMDAwMTk4NTFfVmVoaWNsZU9yZ19lbi1VUyJdLCJubiI6OTgsInRzIjoxNjc2ODk3NTY1OTQ1fQ%2Ffiles%2Fsuv_synergyownermanualmap.PDF%3FcollectionId%3DVehicle%26contentLang%3Den-US%26persistentId%3DVehicle_0000019851_VehicleOrg_en-US%26SRCType%3DPDF%26count%3D2#page=3

and i know i need to render it to location : xyz(720/5790/0)
how can i achieve it by adding some parameters in the url...

**Comment by Snuffleupagus** [comment] 2023-02-20 13:17
Duplicate of #16072

**Closed by Snuffleupagus** 2023-02-20 13:17 UTC

**Comment by spradhan1990** [comment] 2023-02-20 13:31
Can you please share me some example...

**Comment by Snuffleupagus** [comment] 2023-02-20 14:13
Did you actually read *all* of the previously linked Wiki-page? Because the `zoom` parameter is what you'll need to use, since as documented there it accepts not just a zoom value but also position arguments.

**Comment by spradhan1990** [comment] 2023-02-21 08:46
i am sorry @Snuffleupagus 
i tried many permutations, but it is not working,
i am a bit new to this, please help
for eg, 
viewer.html?file=%2FACD%2Fservlet%2Fservicecenter%2Frest%2Fmedia%2FElement.Media%253A%253AVj0xfnsicklkIjoiVmVoaWNsZV9JU19Hb2xmQ2FydF9WZWhpY2xlT3JnIiwib3AiOlsiVmVoaWNsZV9JU19Hb2xmQ2FydF9WZWhpY2xlT3JnIiwiSVNfRkdDX1ZlaGljbGVPcmciLCJWZWhpY2xlXzAwMDAwMDAwNTVfVmVoaWNsZU9yZ19lbi1VUyJdLCJubiI6ODgsInRzIjoxNjc2OTY3MDM3NTczfQ%2Ffiles%2F[5.1005.8581.0-Y.PDF](https://localhost:8445/ACD/delivery/pdfjsViewer_new/viewer.html?file=%2FACD%2Fservlet%2Fservicecenter%2Frest%2Fmedia%2FElement.Media%253A%253AVj0xfnsicklkIjoiVmVoaWNsZV9JU19Hb2xmQ2FydF9WZWhpY2xlT3JnIiwib3AiOlsiVmVoaWNsZV9JU19Hb2xmQ2FydF9WZWhpY2xlT3JnIiwiSVNfRkdDX1ZlaGljbGVPcmciLCJWZWhpY2xlXzAwMDAwMDAwNTVfVmVoaWNsZU9yZ19lbi1VUyJdLCJubiI6ODgsInRzIjoxNjc2OTY3MDM3NTczfQ%2Ffiles%2F5.1005.8581.0-Y.PDF%3FcollectionId%3DVehicle%26contentLang%3Den-US%26persistentId%3DVehicle_0000000055_VehicleOrg_en-US%26SRCType%3DPDF#page=5&left%20offset=113&right%20offset=782)%3FcollectionId%3DVehicle%26contentLang%3Den-US%26persistentId%3DVehicle_0000000055_VehicleOrg_en-US%26SRCType%3DPDF**#page=5&left%20offset=113&right%20offset=782**
