### ISSUE TITLE
Doesn't render properly on certain PDFs

### ISSUE THREAD

**Issue by Havoclivekiller** [mozilla/pdf.js#12799] opened 2020-12-30 18:48 UTC
Attach (recommended) or Link to PDF file here:
[Shadowrun 5e - Core Rulebook (Master Index Version)-454-455.pdf](https://github.com/mozilla/pdf.js/files/5755315/Shadowrun.5e.-.Core.Rulebook.Master.Index.Version.-454-455.pdf)

Configuration:
- Web browser and its version: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
- Operating system and its version: Windows 10 19042.685
- PDF.js version: 2.7.434
- Is a browser extension: No

Steps to reproduce the problem:
You can use the online demo viewer https://mozilla.github.io/pdf.js/web/viewer.html to reproduce it. Just use the file.
The file was cut but it happens to all the pages where there are tables.

What is the expected behavior?
![image](https://user-images.githubusercontent.com/21118924/103374235-53d7ae80-4ad7-11eb-8e76-87b2012bf72a.png)

What went wrong?
![image](https://user-images.githubusercontent.com/21118924/103374346-a913c000-4ad7-11eb-9a62-17de00d86ee4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): -

**Comment by Snuffleupagus** [comment] 2020-12-30 18:59
Looks like a duplicate of #12798

**Closed** 2020-12-31 12:08 UTC
