### ISSUE TITLE
Cannot find name 'SVGGraphics' in api.d.ts

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#16772] opened 2023-07-31 06:05 UTC
Can't compile v3.9.179 in a node.js project.

Configuration:
- PDF.js version: v3.9.179

Steps to reproduce the problem:
1. npm run dev in a node.js project including the pdf-dist package

```
Error: node_modules/pdfjs-dist/types/src/display/api.d.ts:1472:10 - error TS2304: Cannot find name 'SVGGraphics'.
1472 export { SVGGraphics };
```

**Comment by Snuffleupagus** [comment] 2023-07-31 06:07
Duplicate of #16705

**Closed by Snuffleupagus** 2023-07-31 06:07 UTC

**Comment by okomarov** [comment] 2023-08-02 11:29
It's more likely for people to find this issue as it triggers on updates of pdf.js than 
https://github.com/mozilla/pdf.js/issues/16705. I would suggest adding the symptom/error from this issue to the other issue if you want to redirect to it.

The effect of this issue is that we won't be updating pdf.js until this symptom is fixed.

**Comment by Snuffleupagus** [comment] 2023-08-03 12:54
> The effect of this issue is that we won't be updating pdf.js until this symptom is fixed.

Fixing this will require that a TypeScript user, such as yourself, helps out here!

**Comment by amandesai01** [comment] 2023-08-06 20:11
Facing same issue :(

**Comment by dvdmunckhof** [comment] 2023-08-08 09:08
I found a _temporary_ workaround for this. I created a [custom type declaration](https://www.typescriptlang.org/docs/handbook/2/type-declarations.html):

```typescript
declare global {
    export type SVGGraphics = any;
}
```

**Comment by amandesai01** [comment] 2023-08-08 09:53
I just rolled back to previous major version

**Comment by Liu-Jinshuai** [comment] 2023-08-21 16:07
I also encountered this problem

**Comment by Liu-Jinshuai** [comment] 2023-08-29 18:09
If you don't care and want to solve this problem in the current new version, you can add in tsconfig.json:

```
{
   "compilerOptions": {
     //......
     "skipLibCheck": true,
   }
}
```

It should be noted that when you choose to use ```skipLibCheck```, you give up the type safety check of the library file, which may cause runtime errors.

It does solve your problem though (so far)

If you feel unsafe or worried, you can roll back the version, such as the older "pdfjs-dist": "^2.4.456"

If you use an old version, you can use the following code to solve the error message (*.d.ts):

```
declare module 'pdfjs-dist' {
     var pdfjsLib: any;
     export = pdfjsLib;
}
```
