### ISSUE TITLE
Plugin does not display pdf document in Safari browser.

### ISSUE THREAD

**Issue by DenisSambur97** [mozilla/pdf.js#13817] opened 2021-07-29 09:03 UTC
Attach (recommended) or Link to PDF file here:
[sample.pdf](https://github.com/mozilla/pdf.js/files/6899309/sample.pdf)

Configuration:
- Web browser and its version: Safari 14.1.1 (16611.2.7.1.4)
- Operating system and its version: Big Sur 11.4
- PDF.js version: 2.4.0. (Latest Version)
- Is a browser extension: **-**

Steps to reproduce the problem:
1. Open this page 
2. https://socialmediasignup.bubbleapps.io/version-test/terms?debug_mode=true

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/65072293/127464746-b39955bf-a0bb-4147-909a-cc610c263fa8.png)

What went wrong? (add screenshot)
<img width="1410" alt="MicrosoftTeams-image (3)" src="https://user-images.githubusercontent.com/65072293/127463632-8889aebd-6bf8-42fd-960c-27c9ecd35ca2.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
**default**

**Comment by Snuffleupagus** [comment] 2021-07-29 09:15
> PDF.js version: 2.4.0. (Latest Version)

Sorry, but this doesn't make (any) sense given that the quoted version number has *never actually existed*.
Furthermore, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

Finally, this is likely related to the huge page size, since Safari may have trouble with (even moderately) large canvases. This  might be *somewhat* similar to issues such as e.g. #11297 and the only real solution here would be to implement issue #6419 (which isn't as straightforward as you'd like).

All-in-all, closing as a duplicate of #6419.

**Closed by Snuffleupagus** 2021-07-29 09:15 UTC
