### ISSUE TITLE
(feature) Page Labels

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#5715] opened 2015-02-09 20:09 UTC
I think it would be useful implement Page Labels, so that pages in front matter are different from body matter.

This can be fould in the [PDF Specification](https://www.adobe.com/devnet/pdf/pdf_reference.html) itself.

**Comment by Snuffleupagus** [comment] 2015-02-09 21:20
Closing as duplicate of issue #3165.

**Closed by Snuffleupagus** 2015-02-09 21:20 UTC
