### ISSUE TITLE
pdf.js can use in IOS10(

### ISSUE THREAD

**Issue by jerrycnus** [mozilla/pdf.js#7759] opened 2016-10-28 05:27 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:IOS10
- Operating system and its version:IOS10
- PDF.js version:v1.5.188
- Is an extension:true

Steps to reproduce the problem:
1. publish pdfjs-1.5.188-dist on a azure website.
2.open url http://xxxx/web/viewer.html use iphone(ios10)
3.it will show error

PS:if i open url use iphone with ios9,it havn't error ,can open the pdf file.

What went wrong? (add screenshot)

![308259416945686546](https://cloud.githubusercontent.com/assets/23113339/19795831/fc83b92a-9d11-11e6-985d-428cf3ffc576.jpg)

**Comment by Snuffleupagus** [comment] 2016-10-28 08:28
Closing as duplicate of issue #7754.

**Closed by Snuffleupagus** 2016-10-28 08:28 UTC
