### ISSUE TITLE
A part of a PDF's content was removed after copy/paste options.

### ISSUE THREAD

**Issue by sergey-goryushko** [mozilla/pdf.js#18195] opened 2024-05-31 11:13 UTC
Attach (recommended) or Link to PDF file here:
[Some things I want to improve. . ..pdf](https://github.com/user-attachments/files/15512639/Some.things.I.want.to.improve.pdf)

Configuration:
- Web browser and its version: Chrome 125.0.6422.78
- Operating system and its version: macOS Sonoma 14.5
- PDF.js version: 4.4.4 [4d9c25a41]
- Is a browser extension: no 

Steps to reproduce the problem:
1. Open the attached PDF at https://mozilla.github.io/pdf.js/web/viewer.html 
2. Copy the “Canva Sans - a little bit different.“ PDF’s native content. 
3. Paste the text from the previous step within the PDF.

What is the expected behavior? 
Any content has not to be deleted.
(add screenshot)
<img width="1275" alt="expected result" src="https://github.com/mozilla/pdf.js/assets/49900728/ae228e12-9a4a-436d-a4bf-50332f0f7f1b">

What went wrong? 
Two “f“ letters were removed from the "different" word. 
(add screenshot)
<img width="1332" alt="actual result" src="https://github.com/mozilla/pdf.js/assets/49900728/86393ea0-1b95-4f21-882a-d2f965cffaa4">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2024-05-31 11:18
Duplicate of #12237

**Closed by Snuffleupagus** 2024-05-31 11:18 UTC

**Comment by sergey-goryushko** [comment] 2024-05-31 14:28
@Snuffleupagus thanks for the quick response. Could you let me know, please, when you're going to fix the issue #12237?  I wondered because you've lived with that for more than 4 years.

**Comment by marco-c** [comment] 2024-05-31 14:50
@sergey-goryushko if you want to help us and all pdf.js users by stopping the counter at 4 years instead of letting it go to 5 or 6, you're welcome to contribute a fix!

Jokes aside, there are no immediate plans to fix that issue, we are working on other things at the moment. So, we can't let you know when we're going to fix it. We do, however, happily accept contributions!

**Comment by sergey-goryushko** [comment] 2024-05-31 14:58
@marco-c got it) 

Thanks for the comprehensive feedback)
