### ISSUE TITLE
Creating Square Annotations when element is clicked

### ISSUE THREAD

**Issue by HumidBore** [mozilla/pdf.js#16146] opened 2023-03-11 13:22 UTC
Hi all,

I'm developing a web app to view pdfs and I need a specific feature, which is creating a square annotation on top of the pdf when an element is clicked. This annotation is just to highlight some content in the view to help the user understand pdf data, so there is no need to save it on top of the pdf file.

Unfortunatelly, I'm finding it hard to understand pdf.js API, but as far as I could understand, I could make use of the AnnotationEditorLayer to create a square annotation in a programmatic way. 
Since I'm using the default viewer, I would like to have as final result an annotation that, similarly to the free drawing available with the pencil tool, scales when the pdf is zoomed in/out.
My question is about which functions I could invoke to get the desired result. 

Thank you so much  for your help.

**Comment by calixteman** [comment] 2023-03-11 13:42
Basically, the idea is to add a serialized version of your annotation:
https://github.com/mozilla/pdf.js/blob/b2a86350fcf056e349a4ae985e4680f30d497e0d/src/display/editor/ink.js#L1084-L1099
in the `annotationStorage`:
https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_storage.js
Then when you call for example `saveDocument`:
https://github.com/mozilla/pdf.js/blob/b2a86350fcf056e349a4ae985e4680f30d497e0d/src/display/api.js#L2851
the `annotationStorage` will be sent in the worker and finally will call:
https://github.com/mozilla/pdf.js/blob/b2a86350fcf056e349a4ae985e4680f30d497e0d/src/core/annotation.js#L259
Hence you'll need to add some code to convert your serialized annotation into a new annotation, something similar to:
https://github.com/mozilla/pdf.js/blob/b2a86350fcf056e349a4ae985e4680f30d497e0d/src/core/annotation.js#L4113

**Comment by HumidBore** [comment] 2023-03-14 16:17
Hi calixteman,

Thank you so much for the response.
Unfortunatelly, I'm not able to get how I can add the serialized version of the annotation in the annotation storage. 
Do you know which function do I have to call from the viewer? And passing which arguments? Or do I have to add some new functionalities?
I'm sorry to ask (probably) silly questions, but I'm so confused and really need to get this feature done.
Also, any piece of code would be really appreciated. 
Thank you again for your support.

**Comment by Snuffleupagus** [comment] 2023-04-03 13:55
Duplicate of #15588

**Closed by Snuffleupagus** 2023-04-03 13:55 UTC
Labels: other
