### ISSUE TITLE
Layers rendered in incorrect order

### ISSUE THREAD

**Issue by urijah** [mozilla/pdf.js#9483] opened 2018-02-15 03:46 UTC
Attach (recommended) or Link to PDF file here:
[brochure (1).pdf](https://github.com/mozilla/pdf.js/files/1726346/brochure.1.pdf)

Configuration:
- Web browser and its version:
Firefox 58.0.1 (64-bit)
- Operating system and its version:
Windows 10 64bit 1709
- PDF.js version:
default used in Firefox 58.0.1 (64-bit)
- Is a browser extension:
built-in Firefox 58.0.1 (64-bit)

Steps to reproduce the problem:
1. view pdf in Firefox
2. see layers rendered in incorrect z order

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/2709312/36239576-c86cbe10-11d8-11e8-8424-e37c3d798cf4.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/2709312/36239587-da0ddc30-11d8-11e8-8e30-7b61a74bfb85.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2018-02-15 10:34
Closing as duplicate of issue #269.

**Closed by Snuffleupagus** 2018-02-15 10:34 UTC
