### ISSUE TITLE
feature request : add book view

### ISSUE THREAD

**Issue by rahmanshaber** [mozilla/pdf.js#9697] opened 2018-05-01 03:30 UTC
i am using this project [here](https://github.com/Archie3d/qpdf)

it is perfect fit for my project . 
but i need the book view like this

![ut](https://user-images.githubusercontent.com/30831735/39460057-2d23ea0c-4d22-11e8-8dab-74d81446f2b3.png)

i don't know anything about js.
so
please please please add the book view .

**Comment by timvandermeij** [comment] 2018-05-01 21:01
Closing since this is a duplicate of #590, for which a fix is pending.

**Closed by timvandermeij** 2018-05-01 21:01 UTC
