### ISSUE TITLE
Annotations on pdfs 

### ISSUE THREAD

**Issue by pavanisanni** [mozilla/pdf.js#12496] opened 2020-10-19 15:09 UTC
Hello! 
We are seeing a weird issue with annotations on some pdfs. The appearance of some annotations are rotated at 90 degrees as shown in the screenshot and some are upside down. We observed that this doesn't happen to all the pdfs. Any ideas or explanations are appreciated!
![image](https://user-images.githubusercontent.com/73122140/96467042-8708e200-11f8-11eb-8107-e2ad8d07da42.png)

Configuration:
- Google Chrome and its version: 85.0.4183.121
- windows 10
- PDF.js version:v2.5.207

**Comment by Snuffleupagus** [comment] 2020-10-19 15:54
> We observed that this doesn't happen to all the pdfs.

This might be a duplicate of #7631; however as-is this issue isn't actionable/valid since there's no test-case provided!

*Generally speaking:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Closed** 2020-10-19 19:45 UTC
