### ISSUE TITLE
Nimbus Sans font is not displayed properly

### ISSUE THREAD

**Issue by sergei-harbour** [mozilla/pdf.js#15528] opened 2022-09-30 05:36 UTC
PDF file: [nimbus_sans_font_issue.pdf](https://github.com/mozilla/pdf.js/files/9680877/nimbus_sans_font_issue.pdf)

Configuration:
- Web browser and its version:
  - Chrome 105.0.5195.125 (Official Build)
  - Microsoft Edge 105.0.1343.25 (Official Build)
- Operating system and its version: Windows 10 20H2 (build 19042.2006)
- PDF.js version: v2.16.105
- Is a browser extension: no

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Open the attached file

**Expected behavior**
<img width="1023" alt="Screen Shot 2022-09-30 at 8 33 09 AM" src="https://user-images.githubusercontent.com/86401513/193197396-dc62bb33-e80d-4b36-9756-b682decaf59b.png">

**What went wrong**
<img width="668" alt="Screen Shot 2022-09-30 at 8 28 15 AM" src="https://user-images.githubusercontent.com/86401513/193197450-9d437e1f-51d5-44df-97a6-6aed4d205e19.png">

Additional notes:

- The text written in Numbus Sans font (regular and bold) is not displayed
- It's reproducible on different Windows versions
- It's NOT reproducible on Mac nor Linux

**Comment by Snuffleupagus** [comment] 2022-09-30 07:03
Duplicate of #15289.

Please note https://github.com/mozilla/pdf.js/issues/15289#issuecomment-1222203041 in particular.

**Closed by Snuffleupagus** 2022-09-30 07:03 UTC
