### ISSUE TITLE
how to make this pdf file work well

### ISSUE THREAD

**Issue by 1554312244** [mozilla/pdf.js#13487] opened 2021-06-04 06:53 UTC
Attach (recommended) or Link to PDF file here:
https://pdf.dfcfw.com/pdf/H2_AN202104301488768931_1.pdf?1619977027000.pdf
Configuration:
- Web browser and its version:Google Chrome  91.0.4472.77
- Operating system and its version:
- PDF.js version: PDF.js: 2.10.22
- Is a browser extension:

Steps to reproduce the problem:
1. open https://mozilla.github.io/pdf.js/web/viewer.html
2. upload the file https://pdf.dfcfw.com/pdf/H2_AN202104301488768931_1.pdf?1619977027000.pdf
3. the page 8 looks not well .

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by 1554312244** [comment] 2021-06-04 06:54
![image](https://user-images.githubusercontent.com/12227998/120758759-cd6f3f00-c544-11eb-8077-0569e4895c99.png)

**Comment by Snuffleupagus** [comment] 2021-06-04 06:55
> PDF.js version:latest

You should always provide an actual version *number*, since "latest" is ambiguous and thus of no use.

**Comment by 1554312244** [comment] 2021-06-04 07:00
> > PDF.js version:latest
> 
> You should always provide an actual version _number_, since "latest" is ambiguous and thus of no use.

the version is '2.10.22'

**Comment by Snuffleupagus** [comment] 2021-06-28 15:23
Duplicate of #11957

**Closed by Snuffleupagus** 2021-06-28 15:23 UTC
Labels: 4-image-conversion, 4-image-jpx

**Comment by linfangrong** [comment] 2021-07-16 05:34
@1554312244
