### ISSUE TITLE
Dotted lines are seen when viewing PDF files in pdf.js viewer

### ISSUE THREAD

**Issue by dhanbhan** [mozilla/pdf.js#13615] opened 2021-06-23 10:41 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome, Firefox, Edge all versions.
- Operating system and its version: Windows, Redhat Linux
- PDF.js version: 2.7.570
- Is a browser extension: NA

Steps to reproduce the problem:
1.  Open attached pdf in pdfjs viewer. 
2. You will see dotted lines instead of text box. 

What is the expected behavior? (add screenshot)
Textbox containing text. 

What went wrong? (add screenshot)

![dotted lines](https://user-images.githubusercontent.com/86353329/123084505-d44fea00-d43e-11eb-9ce5-72215aff5e55.jpg)

![browser console-1](https://user-images.githubusercontent.com/86353329/123084422-b84c4880-d43e-11eb-8fec-4a13688f76b0.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-06-23 10:58
> PDF.js version: 2.7.570

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Open attached pdf in pdfjs viewer.

There's no PDF document attached to this issue...

**Comment by AlexWhita** [comment] 2021-06-24 18:39
[Large Lien Panel Review Form (2).pdf](https://github.com/mozilla/pdf.js/files/6711454/Large.Lien.Panel.Review.Form.2.pdf)

**Comment by dhanbhan** [comment] 2021-06-24 20:33
@Snuffleupagus 
Hi Jonas, PDF document is attached. Also we have same problem with latest pdfjs. Thanks.

**Comment by Snuffleupagus** [comment] 2021-06-24 20:46
> PDF document is attached.

*For future reference:* You should always attach the document directly when opening the issue, to save every ones time.

---

Furthermore, I'm not convinced that this is actually a bug in the PDF.js library, since it looks more like a badly generated PDF document than anything else.
Note that if you disable `renderInteractiveForms`, which thus disables form-editing, this is how the document renders:

![non-renderInteractiveForms](https://user-images.githubusercontent.com/2692120/123329952-abfae500-d53d-11eb-9dab-e27be75b927a.png)

Hence the PDF.js library simply renders what's actually present in the PDF document *itself*, and the issue is thus that you document contains a LineAnnotation which is what's visible here.

**Comment by dhanbhan** [comment] 2021-06-25 07:27
@Snuffleupagus
Hi Jonas, 

I see this dotted line problem only when document is rendered using pdf.js library. 

1. If you open sample file attached from native pdfviewer (Acrobat reader) dotted lines are not present. 
2. If you open sample file directly in other browsers (Chrome , Edge) dotted lines are not present. 
3. If you open sample file directly in mozilla firefox dotted lines are  present. 
4. If you open sample file using pdf.js library in mozilla firefox dotted lines are  present. 
5. If you open sample file using pdf.js library in other browsers (Chrome , Edge)  dotted lines are  present. 

Attached screenshot below explains the problem in detail (Left side : Chrome and
<img width="1746" alt="Screenshot 2021-06-25 at 12 29 53 PM" src="https://user-images.githubusercontent.com/86353329/123386924-cd4ae800-d5b4-11eb-8430-3545a25860dc.png">
 Right side Mozilla Firefox.)

**Comment by Snuffleupagus** [comment] 2021-06-25 07:38
>  see this dotted line problem only when document is rendered using pdf.js library.

That does *not* at all mean that it isn't your PDF document that's at fault here, and that other PDF viewers have somehow worked around that; please re-read https://github.com/mozilla/pdf.js/issues/13615#issuecomment-867940433 again. Furthermore:
- Opening the PDF document with Adobe Reader (i.e. the reference implementation), the LineAnnotations are shown *very briefly* during opening before then being "hidden" behind the textarea.
- Opening the PDF document with PDFium (in Google Chrome), and looking at the thumbnails it generates the LineAnnotations are very clearly visible there as well.

All-in-all, this just further proves my point in https://github.com/mozilla/pdf.js/issues/13615#issuecomment-867940433 about this being a bug in the PDF document *itself*.

**Comment by dhanbhan** [comment] 2021-06-25 10:52
@Snuffleupagus 

Thanks  Jonas for the details. Even I observe dotted lines flashed for a moment when its is opened in native application. 

Is there a way pdf.js can render this with a workaround as we see in other browser (Google chrome) ?

**Comment by Snuffleupagus** [comment] 2021-07-08 14:59
Duplicate of #13003

**Closed by Snuffleupagus** 2021-07-08 14:59 UTC
Labels: 1-core
