### ISSUE TITLE
how to stop in onProgress?

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [mozilla/pdf.js#10336] opened 2018-12-06 05:11 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome
- Operating system and its version:
- PDF.js version: 2.0.305
- Is a browser extension:

Steps to reproduce the problem:
1. i want to stop pdf file reading. so i used destroy(). but is not working 
how to use onProgress in destroy()?
when the other client event occurs , i want to destroy in onProgress..
i want to onProgress is proceeding, destroy method using. 
please help me 

my code 
[ const loadingTask = window.PDFJS.getDocument(url);

                loadingTask.onProgress = (progress) => {
               
                    if (this.convertIndex !== this.state.index) {
                        loadingTask.destroy(); // is not working 
                        return;
                    }
                }

                loadingTask.then((data) => {
                  this.onDocumentComplete(data);
                    }
                   }).catch(this.onDocumentError)
            }).catch((err) => {
                this.handleError('error');
                this.handleError('error');
                console.log(`commonAPIError${err}`)
            })](url)

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/30399546/49562837-877b9500-f960-11e8-9f09-89de8205bac3.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/30399546/49562843-93675700-f960-11e8-80b8-845bc216b30f.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2018-12-06 10:23
> PDF.js version: 2.0.305

That's *not* an official release, please see https://github.com/mozilla/pdf.js/releases

Currently this issue isn't actionable, and as clearly outlined in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md code-snippets are of no use (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by juuuuuuuuuuuuuu** [comment] 2018-12-07 01:47
@Snuffleupagus 
@timvandermeij 

this issue.
this code should pastes in  jsfiddle.


[](// If absolute URL from the remote server is provided, configure the CORS
// header on that server.
var url = 'https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf';

// Loaded via <script> tag, create shortcut to access PDF.js exports.
var pdfjsLib = window['pdfjs-dist/build/pdf'];

// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';

// Asynchronous download of PDF
var loadingTask = pdfjsLib.getDocument(url);
loadingTask.onProgress = (progress) => {
    loadingTask.destroy();
};

loadingTask.promise.then(function(pdf) {
  console.log('PDF loaded');
  
  // Fetch the first page
  var pageNumber = 1;
  pdf.getPage(pageNumber).then(function(page) {
    console.log('Page loaded');
    
    var scale = 1.5;
    var viewport = page.getViewport(scale);

    // Prepare canvas using PDF page dimensions
    var canvas = document.getElementById('the-canvas');
    var context = canvas.getContext('2d');
    canvas.height = viewport.height;
    canvas.width = viewport.width;

    // Render PDF page into canvas context
    var renderContext = {
      canvasContext: context,
      viewport: viewport
    };
    var renderTask = page.render(renderContext);
    renderTask.then(function () {
      console.log('Page rendered');
    });
  });
}, function (reason) {
  // PDF loading error
  console.error(reason);
});)


jsfiddle:  https://jsfiddle.net/pdfjs/9engc9mw/utm_source=website&utm_medium=embed&utm_campaign=9engc9mw


i want to stop pdf reading in onProgress method.
please help me

**Comment by Snuffleupagus** [comment] 2018-12-07 08:41
> this code should pastes in jsfiddle.

As clearly outlined in https://github.com/mozilla/pdf.js/issues/10336#issuecomment-444823099, you need to provide a *complete* and *runnable* example rather than asking people to cut-and-paste code.

> jsfiddle: https://jsfiddle.net/pdfjs/9engc9mw/utm_source=website&utm_medium=embed&utm_campaign=9engc9mw

That link is broken (it shows a 404 error), and even if I edit it to "work" it only points to one of the official examples anyway.

Again, please provide a *complete* and easily runnable example that can be used to reproduce the issue.

**Comment by timvandermeij** [comment] 2018-12-10 22:21
Closing since this is not actionable at the moment. Moreover, I don't understand what destroying within the `onProgress` method is even supposed to do.

**Closed by timvandermeij** 2018-12-10 22:21 UTC
Labels: 1-other, 4-information-requested
