### ISSUE TITLE
Remove extraction log suppression code

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#11998] opened 2020-06-12 21:58 UTC
I filed https://github.com/puppeteer/puppeteer/issues/5741 before and it just got fixed upstream. If version > 3.3.0 is released, we should upgrade and remove the extraction log suppression code since it's not necessary anymore.

**Comment by adbindal** [comment] 2020-07-31 07:50
Hi @timvandermeij, I was wondering if the issue is closed or not. If yes, does it automatically gets closed via a bot or somebody needs to do it manually?

**Comment by timvandermeij** [comment] 2020-07-31 21:13
It's not closed yet because the Puppeteer update did not work out, which is tracked in #12123. Indeed issues get closed automatically by GitHub if a pull request that lists that it fixes the issue is merged.

**Comment by timvandermeij** [comment] 2020-08-16 21:17
We should also be able to remove the `--wait-for-browser` option passing that we currently do manually after commit https://github.com/puppeteer/puppeteer/commit/054d782c823c363c418bf478b0dbefa26673b358 is released upstream.

**Closed** 2020-10-04 13:01 UTC
Labels: 1-test
