### ISSUE TITLE
Is there an issue with document.webL10n in the viewer.js under Chrome v.59

### ISSUE THREAD

**Issue by vulkodava** [mozilla/pdf.js#9220] opened 2017-11-30 12:49 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome v59
- Operating system and its version: Windows
- PDF.js version: 1.9.426
- Is a browser extension: No

Steps to reproduce the problem:
1. Open PDF file in the viewer.js

What is the expected behavior? Have no screenshot, it's on a friend's comp, I cannot reproduce it

What went wrong? 
viewer.js?9a9ec19b-900a-479f-bdfb-6deebc605334:8060 Uncaught (in promise) TypeError: Cannot read property 'setLanguage' of undefined
   at webViewerInitialized (viewer.js?9a9ec19b-900a-479f-bdfb-6deebc605334:8060)
   at <anonymous>

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-11-30 14:35
The default viewer, i.e. https://mozilla.github.io/pdf.js/web/viewer.html, works for me in Google Chrome; Version 63.0.3239.70 (Official Build) beta (64-bit), running on Windows 7.

> Web browser and its version: Chrome v59

First of all, I'm not sure if that version is still supported.

https://mozilla.github.io/pdf.js/web/viewer.html

> What is the expected behavior? Have no screenshot, it's on a friend's comp, I cannot reproduce it

Without a (working) example that can be used to reproduce this, nor *detailed* steps to reproduce the issue, there's unfortunately nothing that we can do to help.

Closing as incomplete.

**Closed by Snuffleupagus** 2017-11-30 14:35 UTC

**Comment by kamlekar** [comment] 2018-05-21 08:04
When I added this [library](https://github.com/fabi1cazenave/webL10n), it stopped saying undefined.

**Comment by Wracheng** [comment] 2024-09-06 07:36
now, I dont't konw how to do . The error : TypeError: Cannot set property 'webL10n' of undefined
