### ISSUE TITLE
Almost-blank page

### ISSUE THREAD

**Issue by samth** [mozilla/pdf.js#4967] opened 2014-06-18 13:39 UTC
This [pdf](http://static.googleusercontent.com/media/research.google.com/de//pubs/archive/42184.pdf) displays almost-totally blank on page 9. It renders properly in Evince. Other pages render fine in pdfjs. No console or pop-up errors.

PDF.js: 1.0.277, FF 33.0a1 (2014-06-17), Ubuntu 14.04
![screenshot from 2014-06-18 09 38 10](https://cloud.githubusercontent.com/assets/244723/3314163/ce9d1afa-f6ed-11e3-9406-e32767d32d58.png)

**Comment by timvandermeij** [comment] 2015-04-13 19:23
Confirmed on Arch Linux with Firefox 37.0.1.

**Comment by samth** [comment] 2015-12-15 23:12
The Firefox issue hasn't been fixed, but this now works correctly in pdf.js.

**Comment by timvandermeij** [comment] 2015-12-15 23:44
Strange, it did not work for me with Firefox 42 today. I'm reopening this so we can check it out a bit more, but good to know that it is now at least working for some configurations (like yours).

**Comment by timvandermeij** [comment] 2016-05-04 22:19
I cannot reproduce this anymore using Firefox 45.0.2 on Arch Linux. Since it's also working for the other configuration mentioned in this issue, I'm going to close this as fixed. If problems remain, please let us know (and provide all details about the configuration) so we can reopen this.

**Closed by timvandermeij** 2016-05-04 22:19 UTC
Labels: 3-pdf-broken, 3-upstream, 4-os-linux
