### ISSUE TITLE
some PNG images invisible

### ISSUE THREAD

**Issue by jsienkiewicz** [mozilla/pdf.js#6099] opened 2015-06-09 11:38 UTC
Some PNG images are not visible with pdf.js, while they are visible with Adobe Reader and other standalone pdf readers.
The test pdf has been created with iText and tried with many images. So far, all JPG and PNG images have been displayed properly. However, recently I have found a few negative tests, I'm attaching one of them (cuurently I can see option to upload PNG only, no option to upload PDF?).
![aaaa](https://cloud.githubusercontent.com/assets/12812940/8056856/9fdf6c54-0eac-11e5-885b-1dc848f43795.png)

**Comment by Snuffleupagus** [comment] 2015-06-09 11:46
Unfortunately GitHub doesn't support attaching PDF files, so you'll need to use a file sharing service such as Dropbox, Google Drive or similar.

**Comment by jsienkiewicz** [comment] 2015-06-09 12:27
Link to test pdf with the above png.
https://drive.google.com/open?id=0B6jEhwgkESNlSGpfRVZGYzhUXzQ&authuser=0

**Comment by Snuffleupagus** [comment] 2015-06-09 14:01
Thanks for the report; however this is already fixed by PR #5748 (the image uses a CalRGB colorspace), and I've confirmed that it's working in the *latest* version of PDF.js (which as of this writing is `1.1.191`). Hence I'm closing this issue as FIXED.

Since we currently don't have a test-case for this particular issue, I'm wondering:
@jsienkiewicz Are you the creator of the PDF file, and if so can we include it in our test suite?

**Closed by Snuffleupagus** 2015-06-09 14:01 UTC

**Comment by jsienkiewicz** [comment] 2015-06-09 15:41
I confim, you can include the PDF. 
By the way, I tested it today morning with http://mozilla.github.io/pdf.js/web/viewer.html and it was not working, now it works :)

**Comment by Snuffleupagus** [comment] 2015-06-09 15:46
> I confim, you can include the PDF.

Thank you!
