### ISSUE TITLE
PDF contains TIFF image will show as blank page in iOS (iPhone mobile)

### ISSUE THREAD

**Issue by johnscliang** [mozilla/pdf.js#15705] opened 2022-11-17 13:44 UTC
Attach (recommended) or Link to PDF file here: [TEST.pdf](https://github.com/mozilla/pdf.js/files/4216176/TEST.pdf)

Configuration:
- Web browser and its version: Safari
- Operating system and its version: iOS （iphone 12 14）
- PDF.js version: 2.9.359-legacy & https://mozilla.github.io/pdf.js/legacy/web/viewer.html & https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: no

Steps to reproduce the problem:
1.  Open the [Mozilla PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html) on iPhone and then choose the TEST.pdf file
2. Could see blank page if there is a tiff image.

What is the expected behavior? (add screenshot)
Should show the image content as Android version be.

Dear team, is this a compatibility issues?

**Comment by Snuffleupagus** [comment] 2022-11-17 13:47
Duplicate of #11297, since Safari on iOS having trouble with large canvases is a known limitation of that browser.

**Closed by Snuffleupagus** 2022-11-17 13:47 UTC
