### ISSUE TITLE
Firefox Add-on

### ISSUE THREAD

**Issue by ergonomical** [mozilla/pdf.js#5870] opened 2015-03-22 12:22 UTC
This no longer works in Firefox 36.0.1. Not too long ago, it was working, bur with the last update, something they changed makes it incompatible

**Comment by timvandermeij** [comment] 2015-03-22 14:30
The addon is deprecated and PDF.js is now part of Firefox itself. Please uninstall the addon.

Closing as answered and duplicate of #5750 and others.

**Closed by timvandermeij** 2015-03-22 14:30 UTC
