### ISSUE TITLE
Problem with display of image having an EXIF metadata

### ISSUE THREAD

**Issue by DarkMowah** [mozilla/pdf.js#12027] opened 2020-06-26 10:11 UTC
Hi, I hope this is a real issue an that I didn't miss something.

**Attach (recommended) or Link to PDF file here:**

[pdfjs_orientation_issue.pdf](https://github.com/mozilla/pdf.js/files/4836022/pdfjs_orientation_issue.pdf)

**Configuration:**

- Web browser and its version: Chrome 83 (Ubuntu and Android) / Firefox 77 (Ubuntu)
- Operating system and its version: Ubuntu 18.04.4 LTS / Android 10
- PDF.js version: "pdfjs-dist": "2.4.456"
- Is a browser extension: No

**Steps to reproduce the problem:**

1. Open the file in firefox (which I guess is using PDF.js ?) or in my case in a webpage/webapp using pdf.js 

**What is the expected behavior? (add screenshot)**

The pdf has been generated with the pdfkit js lib while taking in account the EXIF orientation metadata of the image, so the image is rotated according to this tag.

The image is expected to be displayed with the right orientation and no ratio distortion. It works well in some cases (see screenshot below)
This screenshot has been taken in the Google Chrome pdf viewer. The result is the same in several other situations (pdf viewer Atril, file thumbnails in ubuntu, Ubuntu's default document viewer). It is also working (surprinsingly) in Firefox 68 for Android
![image](https://user-images.githubusercontent.com/15833106/85842685-5d86ff00-b7a0-11ea-9bf0-a23d769fb26c.png)

**What went wrong? (add screenshot)**

When displayed with pdf.js, there is a problem.
The bounds of the image are ok but the pixels data seems not rotated
The screenshot has been taken in a webapp using pdfjs, the result is the same in the firefox viewer.
![image](https://user-images.githubusercontent.com/15833106/85843058-eb62ea00-b7a0-11ea-8092-8ed0c58f49e7.png)

I think this has to do with the EXIF metadata 'orientation' of the image. Here is the source image  : 
![owl_orientation_pdfjs](https://user-images.githubusercontent.com/15833106/85846266-d8064d80-b7a5-11ea-808f-f7244bfb6464.jpeg)

**Comment by Snuffleupagus** [comment] 2020-06-26 10:48
WFM in Firefox Nightly 79.0a1, which bundles PDF.js version `2.6.47`.

> PDF.js version: "pdfjs-dist": "2.4.456"

The important question is whether you can reproduce this issue in the *latest* PDF.js version, which you can check by opening your file with [the online demo viewer](https://github.com/mozilla/pdf.js#online-demo)?

**Comment by DarkMowah** [comment] 2020-06-29 07:32
Thank you for your answer !
It is indeed also working for me in Firefox Nightly 79.0a1, and also in the online demo (which I didn't know about), for both "older browsers" and "modern browsers". So this is really encouraging :)

What you suggest is just that I have to wait for the npm package pdfjs-dist to be upgraded ? Or is there another npm repository that I may not know ?

**Comment by Snuffleupagus** [comment] 2020-06-29 07:54
> What you suggest is just that I have to wait for the npm package pdfjs-dist to be upgraded?

You can try the pre-release (which is version `2.5.207` as of this writing), to see if that already helps; by either:
 - Downloading it manually from https://github.com/mozilla/pdf.js/releases
 - Using the `next` tag with the npm package, see https://www.npmjs.com/package/pdfjs-dist?activeTab=versions

---

*As an aside:* Given that there hasn't been any recent patches (that I can think of) which should affected the rotation of JPEG images, I'm slightly confused as to why this wouldn't work in e.g. PDF.js version `2.4.456` as well.
If you want to find out *exactly* when it was "fixed", then you could try using `git bisect` locally with this library.

**Comment by DarkMowah** [comment] 2020-06-29 08:01
Ok I will give it a try when I have a bit of time.
Thank you for your help, I will let know here if I find something, it can be helpful for someone else.

**Comment by timvandermeij** [comment] 2020-06-29 21:08
Closing since this seems to work now.

**Closed by timvandermeij** 2020-06-29 21:08 UTC
Labels: 1-other

**Comment by netbrothers-tr** [comment] 2025-01-16 14:39
I'm [experiencing this](https://bugzilla.mozilla.org/show_bug.cgi?id=298619) - roughly five years later - in Firefox 134.0. A regression?

**Comment by calixteman** [comment] 2025-01-16 15:40
@netbrothers-tr yep it's a regression because we switched to the [ImageDecoder](https://developer.mozilla.org/en-US/docs/Web/API/ImageDecoder) api in order to decode the jpeg images and the transform is applied while decoding (see https://bugzilla.mozilla.org/show_bug.cgi?id=1732115) when our previous decoder implementation (a pure js one) is just ignoring the exif metadata.
So an idea would be to just overwrite the orientation in the exif metadata and let the `ImageDecoder` not doing the transform.
Would you mind to file a new issue ?
Thank you.

**Comment by Snuffleupagus** [comment] 2025-01-16 15:44
> Would you mind to file a new issue ?

No need, there's already https://bugzilla.mozilla.org/show_bug.cgi?id=1942064 :-)

**Comment by netbrothers-tr** [comment] 2025-01-16 16:25
> No need, there's already https://bugzilla.mozilla.org/show_bug.cgi?id=1942064 :-)

Yes, I opened the issue there. But Google brought me here first, so I thought, I'd leave a mark to strengthen the connection. 😊
