### ISSUE TITLE
Implement Fetch API for streaming PDF loads on Chrome

### ISSUE THREAD

**Issue by jordan-thoms** [mozilla/pdf.js#6126] opened 2015-06-18 02:13 UTC
Chrome has now shipped the Fetch API ( https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/35_QSL1ABTY ) in Chrome 43. I'm not sure yet if other browser vendors will implement it, but seeing as PDF.js has support for the firefox-only moz-chunk-arraybuffer, it seems reasonable to implement this for Chrome. We often see poor network performance loading PDFs, especially when using range requests, and hopefully this can help.

I'm planning to start working on this over the next few days, any initial thoughts?

**Comment by jordan-thoms** [comment] 2015-06-18 03:02
Actually to correct that, seems it's already implemented in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1039846

**Comment by Snuffleupagus** [comment] 2015-06-18 07:57
Is this perhaps a duplicate of issue #5319?

**Comment by jordan-thoms** [comment] 2015-06-18 21:50
Yes I guess so. It appears that it's also possible to do streaming through the normal XHR api, so I'll try that first since it will most likely require less code changes.

**Comment by timvandermeij** [comment] 2015-08-12 21:52
See #6348 for additional information. If someone is willing to work on this, feel free to submit a pull request. We must be sure to remain compatible for old browsers, so we probably need a fallback to XHR or a polyfill for fetch() to do so.

**Comment by nschloe** [comment] 2015-08-12 21:58
FYI, GitHub published a [fetch polyfill](https://github.com/github/fetch).

**Comment by yurydelendik** [comment] 2015-08-12 22:06
Our main use case is progressive fetching portions of the remote file. The solution using Fetch API shall not regress our streaming and range fetching capabilities.

**Comment by yurydelendik** [comment] 2015-08-12 22:09
We use sync-XHR in l10n and cmap components. We shall probably create a (blocking?) issues to migrate both to async-XHR/fetch as well.

**Comment by Rob--W** [comment] 2015-08-13 08:20
@yurydelendik I patched l10n to not use sync XHR a while back (#5739), so only cmaps and fonts need to be fixed.

Note that fetch is not yet usable as a full replacement for XHR, because:

- Chrome: Permissions whitelists (e.g. extension permissions, or `--disable-web-security` flag) does not propagate to the `fetch` API https://crbug.com/478345 (**fixed as of 45.0.2402.0**).
- Chrome: Anything other than http: and https: is ignored, including blob:, data:, file:, filesystem: and ftp: URLs. https://crbug.com/455109 (**no fix yet**)
- Design flaw: `fetch` requests cannot be cancelled (like XHR's `abort`). There is no resolution yet, the discussion seems to have stalled due to bikeshedding (https://github.com/whatwg/fetch/issues/27)
- Firefox: `fetch` requests are not aborted upon unload: https://bugzil.la/1165237

In theory, fetch supersedes XMLHttpRequest, and `fetch` would replace XHR, but in practice that's not possible yet. `fetch`'s only advantage over XHR (from PDF.js's perspective) is streaming response bodies. Given the above limitations, if we want to use `fetch`, we still have to keep the XHR implementation in the core.

And, note that `fetch` support **does not** imply support for readable body streams support. Chrome supported fetch since 42, but streams [were only supported since 43](https://www.chromestatus.com/features/5804334163951616).

**Comment by yurydelendik** [comment] 2015-08-13 14:11
Thanks, @Rob--W 

Filed #6352 for async cmaps

**Closed** 2017-08-30 16:27 UTC
Labels: 1-core, 2-performance
