### ISSUE TITLE
[Bug]: Some characters are missing when using unicode fonts

### ISSUE THREAD

**Issue by tvsinh** [mozilla/pdf.js#18848] opened 2024-10-04 07:18 UTC
### Attach (recommended) or Link to PDF file

[Document-1.pdf](https://github.com/user-attachments/files/17254679/Document-1.pdf)

### Web browser and its version

Chrome version: 129.0.6668.72

### Operating system and its version

Win11 version 23H2 (OS Build 22631.4169)

### PDF.js version

v4.6.82

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Upload the file to the PDF.js viewer at the demo address on GitHub: https://mozilla.github.io/pdf.js/web/viewer.html

### What is the expected behavior?

Display all characters in the correct format.

![err1](https://github.com/user-attachments/assets/b14b90ab-930a-4a0e-ba54-4c24a594ec07)

### What went wrong?

Missing a few characters during display

![err2](https://github.com/user-attachments/assets/f144a2f0-ed07-4b74-b265-daf0168b1e1a)

### Additional context

I have a PDF document using the font 'UVN Hong Ha Hep'. My PDF file works well when viewed in Chrome, but some characters are missing when using PDF.js.

**Comment by calixteman** [comment] 2024-10-04 08:28
I didn't find anything wrong when looking at the ttx output of the font we generate and FontForge correctly displays the missing glyphes.
I can reproduce the issue with either Chrome or Firefox on Windows 11, but not on Mac so it's a bug somewhere around pdf.js, the browser and the os, so it's the kind of bug not among the easiest ones.
The original font is [original.ttf.gz](https://github.com/user-attachments/files/17255424/original.ttf.gz) and the generated one is [generated.ttf.gz](https://github.com/user-attachments/files/17255431/generated.ttf.gz) (just remove the .gz extension: github just doesn't like ttf files).
`ots` doesn't complain about the font we generated.

@jfkthame, would you have an idea ?

**Comment by jfkthame** [comment] 2024-10-04 11:29
I tried installing the "original" font in Windows 10, and then using it in WordPad; interestingly, the `ấ` `ệ` and `ộ` characters fail there, too, so it uses a fallback for them:

![image](https://github.com/user-attachments/assets/d7546927-190e-4c48-b26a-1fb4a43c0386)

(Note that the failures in WordPad include `ấ`, although that one worked OK in pdf.js.)

Looking at the installed "original" font in the Windows Character Map app:

![image](https://github.com/user-attachments/assets/51f98206-ebfc-4592-a395-4143a04c622f)

we see that the slots (between `ấ` and `-` on the second row) that should contain `ệ` and `ộ` appear blank. These are the same two characters as are rendering blank in pdf.js.

Checking the TTX dump of the font, one thing I noticed is that those two glyphs (`uni1EC7` and `uni1ED9`) both contain a spurious extra component `glyph00257` in between the "base" character (itself an accented composite, actually) and the `period` glyph that is being used for the dot-below. In principle that should be harmless: `glyph00257` is just an empty glyph (no outline data). However, it appears that it's causing DirectWrite rasterization to fail. If I remove that "null" component from these two glyphs, and recompile the TTF, Character Map now shows all the glyphs as expected.

I suspect, therefore, that if pdf.js were to check for such "null" components in composite glyphs during its sanitization, and discard them before generating the copy that it's going to activate in Windows, that will probably work around the problem.

(This "fixed" version of the font still doesn't work in WordPad for the three multi-accented Vietnamese characters, but I think that's a separate issue and won't block pdf.js usage.)

**Comment by calixteman** [comment] 2024-10-04 11:42
I noticed this empty glyph but I thought it could lead to a problem because it's just empty !
@jfkthame, should OTS complain about such a case ?

**Comment by jfkthame** [comment] 2024-10-04 13:14
I think this is a DirectWrite bug; I can't see anything in the spec that says it's an error to use an empty glyph as a component in a composite, and both macOS and FreeType rasterizers handle it fine.

Still, given that it causes a problem for DW, maybe OTS should at least issue a warning. Or we could try to make it actually do the sanitization (drop empty components), though that'll be quite an invasive patch for OTS as it doesn't currently do a full 'glyf' table rebuild. Does pdf.js rebuild the 'glyf' table or just copy it as-is?

**Comment by calixteman** [comment] 2024-10-04 15:45
> I think this is a DirectWrite bug; I can't see anything in the spec that says it's an error to use an empty glyph as a component in a composite, and both macOS and FreeType rasterizers handle it fine.
> 

So it'd mean that Chrome isn't using DW when rendering a pdf but they're when rendering a web page, or maybe they sanitize the font.

> Still, given that it causes a problem for DW, maybe OTS should at least issue a warning. Or we could try to make it actually do the sanitization (drop empty components), though that'll be quite an invasive patch for OTS as it doesn't currently do a full 'glyf' table rebuild. Does pdf.js rebuild the 'glyf' table or just copy it as-is?

For now, we almost copy as-it:
https://github.com/mozilla/pdf.js/blob/e5b6144bfa1a61a1dfe79c67e74e5eb08930fdab/src/core/fonts.js#L1848
only few things are fixed for simple glyph.
That said we've a `glyf` reader and writer (see https://github.com/mozilla/pdf.js/blob/master/src/core/glyf.js), I wrote few years ago to be able to rescale a font for pdf with XFA. Maybe we could add a sanitizer here.

Adding such a feature to OTS would be useful for users other than the pdf.js ones, so maybe it's the right place to do the job, but if it's out of the OTS' scope, yes we can try to improve the sanitizing. 

Don't we have a way to report bugs to Microsoft ? Do they care about this kind of bugs ?

**Comment by jfkthame** [comment] 2024-10-04 15:57
> So it'd mean that Chrome isn't using DW when rendering a pdf but they're when rendering a web page, or maybe they sanitize the font.

They ship an embedded copy of freetype, so that might be what they're using. I don't know the exact criteria they use to decide which font stack to use for any given fragment of text, but they definitely route some fonts to freetype instead of dw.

> Adding such a feature to OTS would be useful for users other than the pdf.js ones, so maybe it's the right place to do the job, but if it's out of the OTS' scope, yes we can try to improve the sanitizing.

I've been looking a bit at the OTS glyf code, and I think it may actually be feasible to do this. Though doing it in pdf.js as well would be helpful for those who use pdf.js in older browsers, or ones that don't route the resources through OTS.

**Comment by jfkthame** [comment] 2024-10-04 16:39
OK, I have an OTS patch that discards the empty-glyph components, and can confirm that using this, the example PDF displays all the characters properly on Windows.

I want to tidy it up a bit more, and then will post a PR to upstream OTS for consideration.

**Comment by tvsinh** [comment] 2024-10-07 04:13
When there is a new update, do I need to update the version of pdf.js in my project, or is this an issue of OTS? Will the OTS handle the updates and fix the issues, so I don't need to update the pdf.js version?

**Comment by jfkthame** [comment] 2024-10-10 08:38
The OTS workaround (https://github.com/khaledhosny/ots/pull/289) should be included in Firefox 133 (the patch is just landing in https://bugzilla.mozilla.org/show_bug.cgi?id=1923596). So once you update to that version, no pdf.js change will be needed.

(But if a workaround were implemented in pdf.js itself, that could be helpful for users with older browsers that don't include the OTS update.)

**Comment by Snuffleupagus** [comment] 2024-10-10 09:22
> (But if a workaround were implemented in pdf.js itself, that could be helpful for users with older browsers that don't include the OTS update.)

Experience has unfortunately shown that *many* users are either "stuck" on an older PDF.js version or just very slow to update, so it could take years before a work-around in PDF.js actually reaches a majority of users at which point they'll probably have updated their browsers many times over.

**Comment by tvsinh** [comment] 2024-10-11 03:24
> The OTS workaround ([khaledhosny/ots#289](https://github.com/khaledhosny/ots/pull/289)) should be included in Firefox 133 (the patch is just landing in https://bugzilla.mozilla.org/show_bug.cgi?id=1923596). So once you update to that version, no pdf.js change will be needed.
>
> (But if a workaround were implemented in pdf.js itself, that could be helpful for users with older browsers that don't include the OTS update.)

If I use Chrome, Edge, or any browser based on the Chromium engine, this issue will still occur, right? And I will have to wait until a solution is implemented in pdf.js.

**Comment by jfkthame** [comment] 2024-10-11 07:41
I believe Chrome also uses OTS, so the same solution should eventually appear there (though I don't know what their schedule for updating the library is like; at least, the version currently in https://source.chromium.org/chromium/chromium/src/+/main:third_party/ots/src/ looks quite out-of-date).

I'm also not sure if this applies to all Chromium-based browsers, or if it's a component where vendors make individual decisions what to do.

**Comment by calixteman** [comment] 2024-10-11 08:19
@tvsinh, you can file a bug for chromium:
https://issues.chromium.org/issues?q=
and make a link to this bug and to the @jfkthame's patches.

**Comment by Snuffleupagus** [comment] 2024-10-11 08:24
Let's close this as fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1923596, since as mentioned in https://github.com/mozilla/pdf.js/issues/18848#issuecomment-2404563527 it's not clear (at least to me) that it's really worth the time/effort to also implement a work-around on the PDF.js side of things.

**Closed by Snuffleupagus** 2024-10-11 08:24 UTC
Labels: font-conversion

**Comment by calixteman** [comment] 2024-10-11 08:25
By the way, @jfkthame thank you very much for your work !
