### ISSUE TITLE
it's too blured when pdf document is printted usring pdf.js

### ISSUE THREAD

**Issue by sky6688** [mozilla/pdf.js#8676] opened 2017-07-20 08:08 UTC
the demo pdf file

Configuration:
- IE 11 and chrome
- win7
- PDF.js 1.7.225 and PDF.js 1.8.188:
- Is not  an extension:

Steps to reproduce the problem:
1. The preview is ok ,but when I print the pdf document, the contents on the paper is too blured to use.
2.

What is the expected behavior? (add screenshot)
I hope that when I print pdf document on a browser usering pdf.js, the contents on the paper are clear enough.I have tried my best to deal with the problem, but it is not solved, help me,please. thank you.
What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/30290609/28407068-6126e16c-6d65-11e7-8af2-ce0fee52d77b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment] 2017-07-20 13:48
Closing as duplicate of #8075. See also #7488

**Closed by yurydelendik** 2017-07-20 13:48 UTC
