### ISSUE TITLE
[Bug]: Using Chinese to annotate a PDF, but the Chinese characters do not display after opening the downloaded PDF

### ISSUE THREAD

**Issue by CFKit** [mozilla/pdf.js#18329] opened 2024-06-25 03:35 UTC
### Attach (recommended) or Link to PDF file

https://mozilla.github.io/pdf.js/web/viewer.html

### Web browser and its version

版本 125.0.6422.113（正式版本） (arm64)

### Operating system and its version

macOS 14.4.1 (23E224)

### PDF.js version

new

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. open https://mozilla.github.io/pdf.js/web/viewer.html
2. add chinese text
![image](https://github.com/mozilla/pdf.js/assets/20106110/5ff6de9b-1d6f-4449-87fd-da6ee9a2f145)
3. download pdf
4. open the downloaded PDF
![image](https://github.com/mozilla/pdf.js/assets/20106110/1b9f174c-d325-44c1-b6eb-da530e43a5f5)

### What is the expected behavior?

I want the downloaded PDF file to display all of my annotations, including those in Chinese.

### Additional context

This issue might be related to the version of the browser.

**Comment by Snuffleupagus** [comment] 2024-06-25 07:49
Duplicate of #15769

**Closed by Snuffleupagus** 2024-06-25 07:49 UTC

**Comment by Snuffleupagus** [comment] 2024-06-25 07:53
***For future reference:***

> ### Web browser and its version
> 
> 版本 125.0.6422.113（正式版本） (arm64)

Please only use English in this bug tracker.

> ### PDF.js version
> 
> new

That's not a valid version number.

> 2\. add chinese text

You didn't include the string in question, which makes this issue impossible to reproduce for anyone not speaking Chinese.
