### ISSUE TITLE
PDF.js Viewer does not display PDF correctly.

### ISSUE THREAD

**Issue by ShruArora** [mozilla/pdf.js#15545] opened 2022-10-07 09:04 UTC
Attach (recommended) or Link to the PDF file here:
The file doesn't display Nimbus Sans font bold in windows in PDF.js but works fine in acrobat and chrome.
Configuration:
- Web browser and its version: Firefox latest version
- Operating system and its version: Windows only
- PDF.js version: 2.14
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached document in PDF.js viewer and  Nimbus Sans fonts bold is not displayed.

What is the expected behavior? (add screenshot) The file should render the Nimbus Sans bod font in windows.

What went wrong? (add screenshot)
![Not_Rendered_properly_PDF js](https://user-images.githubusercontent.com/115210871/194516313-9270a2f9-808a-480c-afc9-394baa6e6f71.JPG)
![Not_Rendered_properly](https://user-images.githubusercontent.com/115210871/194516385-d736549e-b5c5-4541-88d9-beea998f0335.JPG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by gerold-krommer** [comment] 2022-10-07 09:05
[Neu_EKSt-Erklärung 2020 UK_Page_2_anonymous.pdf](https://github.com/mozilla/pdf.js/files/9732419/Neu_EKSt-Erklarung.2020.UK_Page_2_anonymous.pdf)

**Comment by Snuffleupagus** [comment] 2022-10-07 09:09
> PDF.js version: 2.14

That's not a complete version number, and it's also not a supported version; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

Duplicate of #15289.

Please note https://github.com/mozilla/pdf.js/issues/15289#issuecomment-1222203041 in particular.

**Closed by Snuffleupagus** 2022-10-07 09:09 UTC
