### ISSUE TITLE
pdf_single_page_viewer show toolbar and function?

### ISSUE THREAD

**Issue by tym3515** [mozilla/pdf.js#11085] opened 2019-08-21 04:40 UTC
pdf_single_page_viewer show but not has toolbar , not switch page and other function

**Comment by Snuffleupagus** [comment] 2019-08-21 06:56
Duplicate of #11084.

**Closed** 2019-08-21 21:04 UTC

**Comment by tym3515** [comment] 2019-08-26 07:02
thank you , I mimicked presentationMode, and the function of scrolling the toolbar is single page.
