### ISSUE TITLE
Some text not rendered in attached pdf

### ISSUE THREAD

**Issue by bmm6o** [mozilla/pdf.js#17739] opened 2024-02-28 01:38 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 122.0.1 64-bit
- Operating system and its version: Windows 11
- PDF.js version: Tested with current master
- Is a browser extension: No

Steps to reproduce the problem:
1. Use http://localhost:8888/web/viewer.html to open attached pdf

What is the expected behavior? (add screenshot)
The text in the yellow boxes render

What went wrong? (add screenshot)
There is no visible text in the yellow boxes. Dev tools shows that the text is present but is transparent.
[L000674-JT52992.pdf](https://github.com/mozilla/pdf.js/files/14427494/L000674-JT52992.pdf)
![pdfjs](https://github.com/mozilla/pdf.js/assets/3179039/d84c1e46-0233-49d5-9bda-6aeb281363c7)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2024-02-28 07:47
Duplicate of #15389

**Closed by Snuffleupagus** 2024-02-28 07:47 UTC

**Comment by Snuffleupagus** [comment] 2024-02-28 07:49
*For future reference:* Please remember to place the attached PDF document *just after* the `Attach (recommended) or Link to PDF file here:` line, since that saves having to look through the entire issue just to find the file.
