### ISSUE TITLE
PDF.JS exposing password in inspector debug.

### ISSUE THREAD

**Issue by krishnaprasadgandrath-nooor** [mozilla/pdf.js#15939] opened 2023-01-18 14:06 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-01-18 14:14
Sorry, but nothing more than a title really isn't sufficient to make an issue actionable/valid.

Furthermore, we're explicitly clearing out the password-input when closing the dialog so it's not really clear what the problem is here!? Note that the password-input obviously needs to, at least temporarily, contain the password since otherwise it can't work.

**Closed by Snuffleupagus** 2023-01-18 14:15 UTC
