### ISSUE TITLE
Transparency for text broken

### ISSUE THREAD

**Issue by JanSlabon** [mozilla/pdf.js#7674] opened 2016-09-26 12:18 UTC
Link to PDF file (or attach file here): [Test.pdf](https://github.com/mozilla/pdf.js/files/493019/Test.pdf)

Configuration:
- Web browser and its version: Firefox 49.0.1
- Operating system and its version: Windows 10 Pro
- PDF.js version: 1.5.488
- Is an extension: no (but also reproduceable with the latest release)

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Open the attached file.

What is the expected behavior?
![screen](https://cloud.githubusercontent.com/assets/12390057/18833814/d6d379e6-83f2-11e6-9b4d-498fa89a8792.png)

What went wrong?
![screen2](https://cloud.githubusercontent.com/assets/12390057/18833829/f0b3fc6e-83f2-11e6-859a-82ee2e53e226.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): n/a

**Comment by Snuffleupagus** [comment] 2016-09-26 15:50
Reported upstream in https://bugzilla.mozilla.org/show_bug.cgi?id=1305447.

**Comment by Snuffleupagus** [comment] 2016-09-26 17:50
It turns out that [bug 1305447](https://bugzilla.mozilla.org/show_bug.cgi?id=1305447) is a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1304353, which has been just been fixed and should (hopefully) be uplifted to Firefox 50/51.

Closing, since there's nothing left to do here.

**Closed by Snuffleupagus** 2016-09-26 17:50 UTC
Labels: 2-image-quality, 3-regression, 3-upstream, 4-firefox-specific
