### ISSUE TITLE
Enable Javascript code to Outlines

### ISSUE THREAD

**Issue by spradhan1990** [mozilla/pdf.js#15683] opened 2022-11-11 11:35 UTC
Web browser and its version: chrome, 107.0.5304.63
Operating system and its version: Red Hat Enterprise Linux Server, 7.9 (Maipo)
PDF.js version: 3.0.279
Is a browser extension: No
Steps to reproduce the problem:

1. Open any pdf in chunks of 5 pages with Outline contents and check the response.
![PDFOutlineResponse](https://user-images.githubusercontent.com/79566088/201332319-e5b6e512-3971-4495-93dd-d353f1a5024b.png)

2.  The value for the URI is javascript code is "(javascript:openLinkDoc('pdf-loc(7/fith(7840))');)". It is accepting it as unsafe URL.

What is the expected behavior?
the Outline anchor href value should not be blank. How to make it work. Please help

**Comment by Snuffleupagus** [comment] 2022-11-11 11:37
Duplicate of #15681

**Closed by Snuffleupagus** 2022-11-11 11:37 UTC
