### ISSUE TITLE
E-signature not showing up in pdf.js viewer

### ISSUE THREAD

**Issue by StevenHarlow** [mozilla/pdf.js#4743] opened 2014-05-06 19:42 UTC
I have a document with an e-signature that is not showing up in the pdf.js viewer.  The document used zipLogix Digital Ink as their e-signature provider.  The document is uploaded into our application with the signature in place, but viewing the document in our app doesn't show the signature.  Subsequently downloading the document again confirms the signature wasn't lost in the upload process.

*Note:  I'm working on obtaining a document with the same characteristics that does not contain sensitive data.

**Comment by Osukaru** [comment] 2015-12-11 14:17
I have the same issue. In my case, the problem is only with invalid signatures. I have a pdf document with two signatures (one is valid and another one is invalid). In others pdf viewers I can see the two signatures impressed on the document, but in pdf.js I cannot. I'm sorry, I can't attach the sample document because it contains client confidential data.

**Comment by Osukaru** [comment] 2015-12-11 14:48
I think simply this functionality is not implemented: 

https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L527
````js
    // Hide unsupported Widget signatures.
    if (data.fieldType === 'Sig') {
      warn('unimplemented annotation type: Widget signature');
      this.setFlags(AnnotationFlag.HIDDEN);
    }
````

If I remove these lines I can see the signature impressed on my document. In the case of the issue attached pdf (https://dl.dropboxusercontent.com/u/5681461/dev/test-signature.pdf) I can see the signature but it appears inversed rotate:

![test_pdf](https://cloud.githubusercontent.com/assets/249598/11746461/94c2cfe2-a01e-11e5-82d3-ca3f04adf019.png)

**Comment by THausherr** [comment] 2015-12-11 17:18
Visible Signature widgets usually have an appearance stream just like most other annotations, and this one has it. The flipping may be a duplicate of #5946.

**Comment by THausherr** [comment] 2015-12-28 17:40
Flipping problem is solved now thatt #5946 is solved.

**Comment by robinblandford** [comment] 2016-02-23 16:03
Hi folks - wondering if there was any timeline on a fix for this? Many thanks.

**Comment by timvandermeij** [comment] 2016-02-23 20:55
There appears to be some progress on digital signature verification in #1076.

**Comment by robinblandford** [comment] 2016-02-23 21:27
@timvandermeij Thank you so much for the link.

**Comment by THausherr** [comment] 2016-12-15 08:52
Weird - a year ago I wrote "Flipping problem is solved" but now nothing is displayed, i.e. the yellow question mark is missing.

**Comment by WilliamTambellini** [comment] 2017-11-04 06:12
Still not solved at least for docs from zipLogix Digital Ink :
https://new.zipformplus.com 
Some warnings from pdf.worker.js:
Warning: Unimplemented widget field type "Sig", falling back to base field type.

**Comment by genglefr** [comment] 2017-11-16 15:54
Idd, same problem: Unimplemented widget field type "Sig", falling back to base field type.

Any idea by when we could have an implementation of this widget delivered?
Would be great to know when parsing the PDF that there's a signed area.

**Comment by rmhrisk** [comment] 2017-11-29 04:21
We have implemented a digital signature solution based on PKIjs and PDFjs that is capable of verifying digital signatures. You can see an example of it viewing the US Digital Signature law [here](https://manage.hancock.ink/document?url=https://peculiarventures.github.io/ExamplePDFs/signed/BILLS-106s761enr.pdf).

The viewer currently trusts the CAs on the eIDAS Trust List as well the Mozilla trusted S/MIME issuers. 

If you encounter any issues email me at ryan@peculiarventures.com with sample files if any.

**Comment by sreuter** [comment] 2018-02-26 02:24
@rmhrisk Are you going to open source your solution?

**Comment by rmhrisk** [comment] 2018-02-26 07:07
@sreuter most of the libraries have been open sourced already, you can find the components in the https://github.com/PeculiarVentures/.

I want to Open Source the PDF library we built also which lets us work with many different kinds of PDF representations but this will need time to make it ready for public consumption.

I am working with someone on an improved set of examples for PKIjs that would make it easier for others to duplicate what we have done.

**Comment by shizhipeng** [comment] 2018-09-12 10:48
so is there a configuration to enable E-signature in pdf? 
we try to comment  
```
if (data.fieldType === 'Sig') {
      warn('unimplemented annotation type: Widget signature');
      this.setFlags(AnnotationFlag.HIDDEN);
    }
```
while in developing ?
how can we do in npm install a new pkg online?

**Comment by rmhrisk** [comment] 2018-09-12 14:32
There is not.

Disabling this block does not show the signature or it’s starus, it just shows a visual representation of the signature.

Enabling this block without doing the work to verify signature means you will be giving the user a false sense of security relating to the cirectness of the documents displayed.

**Comment by jmarginier** [comment] 2018-10-05 14:33
May be, it's can be set by configuration instead the need of comment this line to render the signature widget ? 
Because otherwise it is necessary to fork the code to be able to display the signature visual.

**Comment by yunzhongbaihe** [comment] 2019-04-16 00:37
pdf.js Warning: Unimplemented widget field type "Sig", falling back to base field type.

**Comment by xtsong** [comment] 2019-05-13 07:55
The electronic postback was resolved and chrome failed to execute'postMessage'on'Dedicated Worker GlobalScope': <Dedicated Worker GlobalScope> could not be cloned.

**Comment by hxlniada** [comment] 2019-07-26 08:56
since three years ago... any progress?

**Comment by hxlniada** [comment] 2019-07-26 09:01
@yurydelendik pdf.js is just a viewer, Is not verifying digital signature too ambiguous? I can't understand why you do so much.

**Comment by Vytek** [comment] 2019-07-31 09:21
@hxlniada I think it is very important at least  to show widget signature (Graphic Signature) also without verify signature.

**Comment by robinblandford** [comment] 2019-07-31 10:58
We would also just like to see it. To say "unverified" is fine.

**Comment by zhengyuewen** [comment] 2019-08-19 01:59
电子签章没显示是为什么？

**Comment by rmhrisk** [comment] 2019-08-19 03:47
因为PDF.js不支持数字签名。 查看https://verify.ink。 如果您要进行翻译，我们可以使用它来支持中文。

**Comment by rmhrisk** [comment] 2019-08-19 03:50
If you need digital signature support we created a web component and iframe wrapping our viewer that does support this. See https://verify.ink

**Comment by timvandermeij** [comment] 2020-09-06 17:31
Closing since this is a duplicate of #1076.

**Closed by timvandermeij** 2020-09-06 17:31 UTC
Labels: 4-annotations, 4-digital-signature

**Comment by fireWinters** [comment] 2021-01-26 02:38
> 因为PDF.js不支持数字签名。 查看[https://verify.ink。](https://verify.ink%E3%80%82) 如果您要进行翻译，我们可以使用它来支持中文。

Thank you very much for the digital signature verification you provided, but our operating environment will be a LAN, so we cannot link to the path you gave for corresponding verification and display. Is there any plug-in that can be downloaded and used? We are looking forward to your reply.

**Comment by rmhrisk** [comment] 2021-01-27 00:41
> > 因为PDF.js不支持数字签名。 查看[https://verify.ink。](https://verify.ink%E3%80%82) 如果您要进行翻译，我们可以使用它来支持中文。
> 
> Thank you very much for the digital signature verification you provided, but our operating environment will be a LAN, so we cannot link to the path you gave for corresponding verification and display. Is there any plug-in that can be downloaded and used? We are looking forward to your reply.

Contact info@hancock.ink for more information

**Comment by nullhan** [comment] 2022-05-18 03:14
I have the same problem,After a couple of rounds, people just told me to comment the following code without telling me why,

// _this3.setFlags(_util.AnnotationFlag.HIDDEN);

**Comment by invisibleved** [comment] 2024-06-13 10:36
> I have the same problem,After a couple of rounds, people just told me to comment the following code without telling me why,
> 
> // _this3.setFlags(_util.AnnotationFlag.HIDDEN);

Thank you, you saved my day
