### ISSUE TITLE
Read Aloud Function

### ISSUE THREAD

**Issue by byfelipesanchez** [mozilla/pdf.js#13173] opened 2021-04-02 21:03 UTC
Has anyone thought about building a read aloud function in the PDF reader? I mean, there are some really great ones out there that do so, and I think It's a valuable tool.

**Comment by Snuffleupagus** [comment] 2021-04-02 21:22
Probably a duplicate of #13114

**Comment by byfelipesanchez** [comment] 2021-04-02 21:57
Thats true, my bad!

**Closed** 2021-04-03 10:53 UTC
