### ISSUE TITLE
if the text to be found is across pages in the file, it cannot be located

### ISSUE THREAD

**Issue by bjzhaoxy** [mozilla/pdf.js#16502] opened 2023-06-01 05:42 UTC
Attach (recommended) or Link to PDF file here:
[The.Art.of.Asking.ChatGPT.for.High-Quality.Answers.pdf](https://github.com/mozilla/pdf.js/files/11621380/The.Art.of.Asking.ChatGPT.for.High-Quality.Answers.pdf)

Configuration:
- Web browser and its version: Microsoft Edge 113.0.1774.57
- Operating system and its version: Microsoft Windows 11 pro 10.0.22621
- PDF.js version: 3.7.107
- Is a browser extension: no

Steps to reproduce the problem:
1. open attachment file 
2. find “We will discuss the different types of prompts”

What is the expected behavior? (add screenshot)
Locate the found string and highlight it

What went wrong? (add screenshot)
Not locating the found string and highlighting it, I think it's because the string is across pages.
![image](https://github.com/mozilla/pdf.js/assets/14307569/573bdc92-b2bf-435b-b7ad-33cc9a83e024)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-06-01 07:21
Duplicate of #10620, as you were informed already in #16458.

---

Please don't knowingly file the same issue *multiple* times, since that just wastes everyone's time.

**Closed by Snuffleupagus** 2023-06-01 07:21 UTC

**Comment by bjzhaoxy** [comment] 2023-06-05 08:29
Sorry，This is the first time for me to raise an issue. At first, I didn't find the issue could be modified, but now I know it

**Comment by cjyzaima** [comment] 2025-09-10 07:35
作者你解决了吗，2025年了，我看开发者还没解决这个问题，想问问后面您是怎么解决这个问题的呢
