### ISSUE TITLE
Wrong highlighted text on search

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#13292] opened 2021-04-24 12:54 UTC
Attach (recommended) or Link to PDF file here:
[LesAccentsFrancais(1).pdf](https://github.com/mozilla/pdf.js/files/6369604/LesAccentsFrancais.1.pdf)

Steps to reproduce the problem:
1. Search for "a" and  click on "Highlight All"

What is the expected behavior? (add screenshot)
The two "A" in "FRANÇAIS" must be highlighted

What went wrong? (add screenshot)
They aren't but "R" and "N" are.
![image](https://user-images.githubusercontent.com/5641725/115959448-8f760880-a50c-11eb-9a88-dd14ae3bd6bc.png)

Reproductible in Firefox nightly or in a local dev environment.

**Comment by Snuffleupagus** [comment] 2021-04-24 13:01
> Search for "a" and  click on "Highlight All"

Interestingly it seems that this is *specific* to the "Highlight All" mode, since if you do a "normal" search and simply advance through the matches the highlights are correct.

**Comment by calixteman** [comment] 2021-04-24 13:08
The HTML is:
```html
<span role="presentation" dir="ltr" style="left: 185.956px; top: 102.908px; font-size: 32.9133px; font-family: sans-serif; transform: scaleX(1.01694);">
  LES 
  <span class="highlight selected">A</span>
  CCENTS FR
  <span class="highlight">A</span>
  NÇ
  <span class="highlight">A</span>
  IS 
</span>
```
And using devtools the we can see the container for "CCENTS FR" has the same starting position has the span for the first "A".

**Comment by Snuffleupagus** [comment] 2021-04-24 13:37
This issue can be reproduced in *any* document, and a quick `git bisect` run points to being a regression from PR #13171.

**Comment by calixteman** [comment] 2021-04-24 13:39
Maybe this line:
https://github.com/mozilla/pdf.js/pull/13171/files#diff-7e8695c940b91f5615deecc4eb929bfa7f6157e29c11f9afb1fa0ed88dd183c7R26

**Comment by calixteman** [comment] 2021-04-24 13:45
Yep adding back the `>` fixes the issue.

**Comment by calixteman** [comment] 2021-04-24 13:51
So a fix could be to add a `position: relative` in `.highlight`, @Snuffleupagus wdyt ?

**Comment by Snuffleupagus** [comment] 2021-04-24 15:37
> So a fix could be to add a `position: relative` in `.highlight`, @Snuffleupagus wdyt ?

Assuming that it doesn't cause any other issues, that seems like a small/simple way to fix the issue!
(We might want to consider uplifting the patch, once landed, since "Highlight All" is now broken in Firefox 89.)

**Closed** 2021-04-28 08:15 UTC
Labels: 3-regression, 4-text-selection
