### ISSUE TITLE
Text not rendering properly in https://mozilla.github.io/pdf.js/web/viewer.html

### ISSUE THREAD

**Issue by robotestyukon** [mozilla/pdf.js#16011] opened 2023-02-06 08:42 UTC
Hi team,
I am facing some issue rendering the pdf in ngx-extended-pdf-viewer(as pdf.js was used as per the plugin developer https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1659).  Checked the same pdf in https://mozilla.github.io/pdf.js/web/viewer.html where the text in pdf is getting blurred or sometimes not rendering properly in chromium browsers(chrome,edge,etc) specific to Windows.
attached the screenshot and the pdf url https://moneyandme.pgimindiamf.com/api/v1/portal/pdf/PDF_2118943213 for reference.
![image](https://user-images.githubusercontent.com/123447793/216924935-56dbf7f9-0c07-4620-888a-a7085e48854b.png)

**Comment by Snuffleupagus** [comment] 2023-02-06 09:45
Duplicate of e.g. #14641

*For future reference:* When opening an issue, please actually provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md (rather than just deleting the template).

**Closed by Snuffleupagus** 2023-02-06 09:45 UTC
