### ISSUE TITLE
PDF-Viewer turns pdf completely black

### ISSUE THREAD

**Issue by TLucasIND** [mozilla/pdf.js#14592] opened 2022-02-21 08:11 UTC
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Chrome Version 98.0.4758.102 
- Operating system and its version: Windows 10 Build 19042.1237
- PDF.js version: current
- Is a browser extension: no

Steps to reproduce the problem:
1.  open the page with pdf-viewer inside
2. wait some seconds (maximum 1 minute)

What is the expected behavior? (add screenshot)
PDF should be shown normally

What went wrong? (add screenshot)
PDF turns completely black
![Screenshot 2022-02-21 084425](https://user-images.githubusercontent.com/49560161/154913923-c21e5c50-317d-4d4e-b7d8-3f5852d16683.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): look above

**Comment by Snuffleupagus** [comment] 2022-02-21 09:08
> PDF.js version: current

Please provide an actual version *number* when opening an issue, since "current" unfortunately isn't helpful.

> What went wrong? (add screenshot)
> PDF turns completely black

Your screen-shot *clearly* doesn't show the viewer found at https://mozilla.github.io/pdf.js/web/viewer.html, hence this issue unfortunately doesn't really make sense. Please note that we cannot provide support for *custom*, or third-party, PDF.js implementations here.

Closing as INVALID, since the demo viewer works for me when using either Firefox Nightly 99 or Google Chrome Beta 99.

**Closed by Snuffleupagus** 2022-02-21 09:08 UTC
Labels: information-requested

**Comment by TLucasIND** [comment] 2022-02-22 06:58
I reproduced the error with the same stats, this time even in incognito-mode of chrome to exclude it has something to do with extensions. I don't know how to check the version of the pdf viewer. Can you help me?
![Screenshot 2022-02-22 075400](https://user-images.githubusercontent.com/49560161/155079057-05ec8fbc-9816-4bef-a58f-9ece110476d8.png)

**Comment by TLucasIND** [comment] 2022-02-22 07:00
Update: The page turns black immediately when switching to another tab and back to the tab with the pdf viewer.

**Comment by Snuffleupagus** [comment] 2022-02-22 09:33
Unfortunately everything here points to a *browser* bug, specific to (some configurations of) Google Chrome, and as such there's not really anything we can do about it here.
If this were a PDF.js bug, you'd expect it to be consistently broken everywhere. However, as mentioned above I cannot reproduce this in either Mozilla Firefox (the primary development target) or in Google Chrome.

**Comment by TLucasIND** [comment] 2022-02-22 09:38
Did you try switching the tabs in Chrome to reproduce it? Maybe the problem is solved in the beta Chrome then.
I'm not able to install it in my environment atm.

**Comment by Snuffleupagus** [comment] 2022-02-22 09:54
> Did you try switching the tabs in Chrome to reproduce it?

Sure, and everything works just fine. Note that if the *browser* is clearing/discarding `canvas`es in inactive tabs, that *very clearly* points to the browser itself being the culprit here.

**Comment by calixteman** [comment] 2022-02-22 09:57
I can't reproduce the issue with Chrome 98.0.4758.102 in Windows 11.

**Comment by TLucasIND** [comment] 2022-02-22 10:16
Couldn't reproduce it with Chrome 98.0.4758.102 under Linux Mint 20.3 either...

**Comment by stephanrauh** [comment] 2022-02-22 22:16
Thanks a lot, @calixteman. I wasn't aware you're listening to this channel. Your help is much appreciated!

Best regards,
Stephan

**Comment by stephanrauh** [comment] 2022-02-22 22:18
FWIW, I'm using https://formulae.brew.sh/cask/eloston-chromium on MacOS, and I didn't manage to reproduce the bug yet.
