### ISSUE TITLE
polish diacritic characters break when saved

### ISSUE THREAD

**Issue by niepatryk** [mozilla/pdf.js#14482] opened 2022-01-23 15:34 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 96.0 (64-bit)
- Operating system and its version: Ubuntu
- PDF.js version: PDF.js: 2.12.248
- Is a browser extension: no

Steps to reproduce the problem:
1. https://www.gov.pl/attachment/6fd84906-d6cb-47d5-87f8-01bf7c984b3a
2. write polish character (like ś)
3. save

What is the expected behavior? (add screenshot)
ś will be shown
![image](https://user-images.githubusercontent.com/93675778/150685848-f0dbd1e7-e0bb-4929-9941-cb2e7d3059aa.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/93675778/150685868-263766f4-99b2-4ca8-a076-7b8102fd0f25.png)
this character changes to diffrent character like "Z" or "[" in 3rd party document viewer (like gnome document viewer - Evince) or Chrome pdf viewer

(issue is not present on chrome default pdf viewer)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://www.gov.pl/attachment/6fd84906-d6cb-47d5-87f8-01bf7c984b3a

**Comment by niepatryk** [comment] 2022-01-23 15:38
also issue is not present if you open this file again in Firefox (instead of Evince or Chrome)

**Comment by Snuffleupagus** [comment] 2022-01-23 15:52
WFM, with Mozilla Firefox Nightly 98 with its *built-in* PDF.js version `2.13.24`.

**Comment by Snuffleupagus** [comment] 2022-01-23 15:58
Duplicate of #12264

**Closed by Snuffleupagus** 2022-01-23 15:58 UTC

**Comment by calixteman** [comment] 2022-01-23 16:18
The font associated with the second field is helvetica which doesn't contain the glyph for "ś".
For example, doing the same in Acrobat, will render the string in using MyriadPro-regular.

**Comment by niepatryk** [comment] 2022-01-23 17:09
so it looks like chrome changes font of an field, when there is diacritic characters
 
![image](https://user-images.githubusercontent.com/93675778/150689603-a0630f46-c26f-416d-bf09-27a53b510ffa.png)
