### ISSUE TITLE
Distorted bold text

### ISSUE THREAD

**Issue by Teir** [mozilla/pdf.js#7751] opened 2016-10-24 13:43 UTC
Link to PDF file (or attach file here):
[1.pdf](https://github.com/mozilla/pdf.js/files/547937/1.pdf)
[2.pdf](https://github.com/mozilla/pdf.js/files/547936/2.pdf)

Configuration:
- Web browser and its version: Google Chrome 54.0.2840.71 m
- Operating system and its version: Windows 7
- PDF.js version: 1.5.188
- Is an extension:

Steps to reproduce the problem:
1. Open 1.pdf in pdf.js
2. Open 2.pdf in pdf.js (Order does not matter - may opening 1.pdf after 2.pdf).

What is the expected behavior? (add screenshot)
Both documents will be displayed well. (see 1 first.png and 2 first.png screenshots)

What went wrong? (add screenshot)
Distorted bold text. See screenshots 1 first.png, 2 second.png (or 2 first.png, 1 second.png if first opening was 1.pdf - this screenshots was taken after reboot browser).
1 first.png:
![1 first](https://cloud.githubusercontent.com/assets/19780067/19647799/8241fea8-9a08-11e6-83f0-6a021acccc2c.png)

2 second.png:
![2 second](https://cloud.githubusercontent.com/assets/19780067/19647798/823848fe-9a08-11e6-8101-c70e839737e7.png)

1 second.png:
![1 second](https://cloud.githubusercontent.com/assets/19780067/19647899/def5a686-9a08-11e6-8595-5f9525ba6ef5.png)

2 first.png:
![2 first](https://cloud.githubusercontent.com/assets/19780067/19647894/d6d016d0-9a08-11e6-81b7-f128b450e36c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2016-10-24 14:27
Works for me, using PDF.js version `1.6.264` (which is the latest version as of this writing).
You can easily test this yourself with the demo viewer: http://mozilla.github.io/pdf.js/web/viewer.html.

> PDF.js version: 1.5.188

This issue was fixed by PR #6571, and I'd thus suggest updating to a newer PDF.js version.
Closing as fixed.

**Closed by Snuffleupagus** 2016-10-24 14:27 UTC

**Comment by Teir** [comment] 2016-10-25 13:05
I'm updated to a newer PDF.js version (1.6.264). 
Got better: if first open 1.pdf - good, but if first open 2.pdf - the same situation :(
![1 second](https://cloud.githubusercontent.com/assets/19780067/19687092/cd51249a-9acc-11e6-923a-f255cb06edff.png)

**Comment by yurydelendik** [comment] 2016-10-25 13:23
Please explain what do you mean by "open x.pdf in pdf.js" and the "order" in which pdfs are opened. It's not clear e.g. you are using open button or something else, or you are refreshing browser or not. Can you provide more detailed steps to reproduce?

**Comment by Teir** [comment] 2016-10-25 14:12
"open x.pdf in pdf.js" - enter in browser address bar "http://localhost:8888/web/viewer.html?file=x.pdf".
Steps:
1) enter in browser address bar "http://localhost:8888/web/viewer.html?file=2.pdf"
![1](https://cloud.githubusercontent.com/assets/19780067/19689439/0ce43b98-9ad6-11e6-91ed-3025153280a0.png)
2) in the same tab enter in browser address bar "http://localhost:8888/web/viewer.html?file=1.pdf"
![2](https://cloud.githubusercontent.com/assets/19780067/19689476/3127a8d2-9ad6-11e6-9778-20c8f32b6cfc.png)
![3](https://cloud.githubusercontent.com/assets/19780067/19689477/3145dcf8-9ad6-11e6-88cd-b08d90edb57e.png)

**Comment by Teir** [comment] 2016-10-27 10:35
It was possible to repeat? Plese tell me are you will fix this?

**Comment by timvandermeij** [comment] 2016-10-27 12:47
I think this is a duplicate of #7136.

**Comment by Teir** [comment] 2016-10-27 14:30
You will not fix this?

**Comment by timvandermeij** [comment] 2016-10-27 14:34
Most likely the issue you're describing is the same as in #7136, so we're keeping tracking over there. No need to have two open issues for the same problem. The other issue is still open, so we will look into this more.

**Comment by yurydelendik** [comment] 2016-10-27 14:34
> I think this is a duplicate of #7136.

Looks familiar. But it opens a different document/tab. I wonder if it's just Chrome specific and something is wrong with font caching.

> It was possible to repeat? Plese tell me are you will fix this?

@Teir , is it Chrome specific?

**Comment by Teir** [comment] 2016-10-27 14:43
@yurydelendik , yes, in Firefox/IE/Safari ok

**Comment by yurydelendik** [comment] 2016-10-27 15:46
I wonder if giving random doc number at https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L322 will fix the issue. If yes, Chrome somehow caching fonts by the their name between document loads.

**Comment by Teir** [comment] 2016-10-28 09:22
Yes, it's helps!
Thank you!

**Comment by TZanke** [comment] 2016-10-28 10:39
We have a similar problem with bold text. In our file the text is always **not** bold. But only on some computers. (Firefox, PDF.js 1.4, 1.5, 1.6 beta).

Testing with your "1.pdf", the file randomly is bold/not bold.

Also we noticed, the PDF.js Demo on the mozilla page looks strange on this computers. (wrong font?)

At the moment we could "fix" the issue creating a new Firefox profile ("firefox -P"). Our testuser reinstalled all his stuff, plugins etc and till now PDF.js works as expected.

But we can not recreate a unknown number of Firefox profiles at our customers.

sidenote
On my personal Chrome, PDF.js embedded in an iframe, randomly sets cased letters. Only in bold lines making problems in the other Firefoxes. The cased letters are always the same, but occur randomly. It is possible to get rid of them with changing the zoom level, most of the time. A permanent fix is to set showPreviousViewOnLoad to false. But this also does not fix the bold issue.
Copy-paste the cased text into gedit works fine, also the html shows no case errors. Looks like an font issue.

![image](https://cloud.githubusercontent.com/assets/1613368/19803678/4def97dc-9d0a-11e6-8bba-a5c2042bad2b.png)

**Comment by tonyjin** [comment] 2017-04-04 18:34
> I wonder if giving random doc number at https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L322 will fix the issue. If yes, Chrome somehow caching fonts by their name between document loads.

@yurydelendik can you update what line you're referring? I'm trying to find see if that will fix the random font corruptions I'm seeing occasionally and I think the master branch has been updated since your comment.

**Comment by yurydelendik** [comment] 2017-04-04 19:08
@tonyjin we generate unique document id, so you don't have to do it anymore.

can you see what documents with issue have in common (e.g. pdf generate, font types, or how they structured)? (you can use http://brendandahl.github.io/pdf.js.utils/browser/ to check font information) if you will have some additional info, can you create a different issue with findings?

**Comment by tonyjin** [comment] 2017-04-04 22:53
Ok thanks - I will create a separate issue if I find more information. This one's difficult, happens super rarely on Chrome and disappears on reload - font/canvas/memory corruption?

**Comment by yurydelendik** [comment] 2017-04-04 23:07
@tonyjin maybe font loader reports that font is ready at wrong time. Trying disabling font loading api  https://github.com/mozilla/pdf.js/blob/master/src/display/font_loader.js#L316 -- see if old loading hack works better.
