### ISSUE TITLE
Change primary document colors and preserve image colors

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#11075] opened 2019-08-17 14:59 UTC
(This is a feature request so not sure the but template applies here)

We need a way to be able to set the document colors.

There are a few related bugs

https://github.com/mozilla/pdf.js/issues/3528

but one of the main issues is images within PDF files:

I had investigated using something like:

```css
filter: invert(85%);
```
which actually looks decent BUT the problem comes when the PDF has images.  The images end up with inverted colors.  I can't add a CSS rule for them because they're in the ```canvas``` element.

What I think is needed is a high level way to change the colors of the PDF itself.

We need to support both dark and sepia modes as these are needed to be up to par with other PDF viewers as a large number of users prefer them.

It MAY be that pdf.js already supports this but I can't find how to enable it.

This is different from theming the readder as people using just the renderer lib directly via API should be able to support this too.

**Comment by Snuffleupagus** [comment] 2019-08-17 15:05
Duplicate of #2071.

**Closed** 2019-08-18 12:29 UTC
