### ISSUE TITLE
Tiling pattern with negative bbox coordinates is not fully rendered

### ISSUE THREAD

**Issue by muzimuzhi** [mozilla/pdf.js#16038] opened 2023-02-10 04:18 UTC
Attach (recommended) or Link to PDF file here: 
- [dvisvgm-gh228.pdf](https://github.com/mozilla/pdf.js/files/10703411/dvisvgm-gh228.pdf)
- [dvisvgm-gh228-readable.pdf](https://github.com/mozilla/pdf.js/files/10703415/dvisvgm-gh228-readable.pdf) decompressed version created by `mutool clean -ad dvisvgm-gh228.pdf dvisvgm-gh228-readable.pdf`

Configuration:
- Web browser and its version: Chrome 110.0.5481.77
- Operating system and its version: macOS 12.6.2
- PDF.js version: 3.4.77 (the one used by https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: no

Steps to reproduce the problem:
1. Visit https://mozilla.github.io/pdf.js/web/viewer.html
2. Open `dvisvgm-gh228(-readable).pdf`

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/6376638/217994245-28eacffc-211a-4508-972c-b867f918ead8.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/6376638/217994272-bf18647a-8a15-4bf6-82b7-62cebf63b1c6.png)

<s>Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):</s>

**Background**

The pdf is created by LaTeX using tikz package. [dvisvgm-gh228.tex.zip](https://github.com/mozilla/pdf.js/files/10703495/dvisvgm-gh228.tex.zip) 

Specifically, the broken left pattern can be generated by the short LaTeX example below, shortened from https://github.com/mgieseki/dvisvgm/issues/228:
```tex
\documentclass[margin=5pt]{standalone}
\usepackage{tikz}
\usetikzlibrary{patterns.meta}

\begin{document}
\begin{tikzpicture}[pattern color=blue]
  \draw[draw, pattern={Lines}] (0,0) rectangle (1,1);
\end{tikzpicture}
\end{document}
```

**Analysis**
The broken left pattern has 
- `/BBox [ -1.49442 -1.49442 1.49442 1.49442 ]` and 
- content stream `q 0.3985 w -1.49442 0.0 m 1.49442 0.0 l S Q`

while the right pattern has
- `/BBox [ 0 0 2.98883 2.98883 ]` and
- content stream `q 0.3985 w 0.0 0.0 m 2.98883 0.0 l 0.0 2.98883 m 2.98883 2.98883 l S Q`

In class `TilingPattern`, when the bounding box is shifted to ensure coordinates `x0` and `y0` non-negative, it seems some transformations like `1 0 0 1 -x0 0` and `1 0 0 1 -y0 0` should be additionally applied to the stream content. The corresponding code is added in https://github.com/mozilla/pdf.js/commit/a52c0c6988e557b39c8ea56184a7874e58b6fc96. Actually its commit message already said that negative bounding boxes on tiling patterns is still broken:
> These fixes broke #11473, but highlighted that we were drawing that correctly by
accident and not correctly handling negative bounding boxes on tiling patterns.

https://github.com/mozilla/pdf.js/blob/1bdee0b59b9df507c8e1cc5efd24d78e8946e663/src/display/pattern_helper.js#L556-L572

Current issue is different from the already fixed #11473:
- The example in #11473 uses patterns provided by tikz library `patterns`, which have larger bounding box than X-/Y-steps. For tikz pattern `crosshatch`, it's `/BBox [ -.99628 -.99628 3.9851 3.9851 ] /XStep 2.98883 /YStep 2.98883`.
- The example in current issue uses (relatively newer and more powerful) pattern `Lines` provided by tikz library `patterns.meta`, which has the size of bounding box exactly the same as X-/Y-steps. For the broken left pattern, it's `/BBox [ -1.49442 -1.49442 1.49442 1.49442 ] /XStep 2.98883 /YStep 2.98883`, and for the right it's `/BBox [ 0 0 2.98883 2.98883 ] /XStep 2.98883 /YStep 2.98883`.

Also the specific stream content used in the attached example shows since the content will be clipped, shifting the bounding box may raise the need to manipulating the contents as well, which I guess could be non-trivial.

**Comment by marco-c** [comment] 2023-06-10 10:29
I created a bug on Bugzilla to track this regression: https://bugzilla.mozilla.org/show_bug.cgi?id=1837738.

**Comment by SushmaRaghu** [comment] 2023-07-10 04:15
Hi

Can we please know if there is any progress on this ?

**Comment by SushmaRaghu** [comment] 2023-08-09 04:17
Hi 

We are waiting on this fix . Can you please provide an update ?

**Comment by SushmaRaghu** [comment] 2023-09-29 06:18
@Snuffleupagus Any update on this ? I see that it is moved to high priority .. Any ETA on the same?

**Comment by jeffdare** [comment] 2024-05-02 15:29
Is there any progress on this issue? Its been open for long.

**Comment by mirnalinikarthik** [comment] 2024-05-15 17:36
This issue is a regression and has been open for almost a year. Can we have some update on this issue so that we can plan accordingly.

**Comment by jeffdare** [comment] 2024-06-04 12:17
Based on this observations in this issue, I tried making some changes in the code. By removing code for making the X and Y with their absolute value, the issue of disappearing images is solved. 

```Javascript
let adjustedX0 = x0;
    let adjustedY0 = y0;
    let adjustedX1 = x1;
    let adjustedY1 = y1;
    // Some bounding boxes have negative x0/y0 coordinates which will cause the
    // some of the drawing to be off of the canvas. To avoid this shift the
    // bounding box over.
    // if (x0 < 0) {
    //   adjustedX0 = 0;
    //   adjustedX1 += Math.abs(x0);
    // }
    // if (y0 < 0) {
    //   adjustedY0 = 0;
    //   adjustedY1 += Math.abs(y0);
    // }
    tmpCtx.translate(-(dimx.scale * adjustedX0), -(dimy.scale * adjustedY0));
    graphics.transform(dimx.scale, 0, 0, dimy.scale, 0, 0);

```

I also verified the file present that was present for the tiling pattern implementation as well, that also works - https://github.com/mozilla/pdf.js/pull/13683/files#diff-aefe7570f79e8e92a7d58fb1eb7a3c06e4d2de5761677fd4d93d39813671866d

We would like to know your views on this.

**Comment by jeffdare** [comment] 2024-06-06 04:16
@Snuffleupagus your thoughts on the above comment.

**Comment by cohnt** [comment] 2024-06-24 17:31
I've found that converting from a PDF to SVG file, and then back to a PDF file, helps if done in a certain way.

First, I convert from PDF to SVG with [pdf2svg](https://github.com/dawbarton/pdf2svg). Then, I convert back with [rsvg-convert](https://manpages.ubuntu.com/manpages/trusty/man1/rsvg-convert.1.html) ([per this answer on superuser](https://superuser.com/a/381128)).

Maybe this will help people dealing with the issue. At the very least, it will remind me how to handle it next time I run into the bug.

**Comment by jeffdare** [comment] 2024-06-27 10:17
> Based on this observations in this issue, I tried making some changes in the code. By removing code for making the X and Y with their absolute value, the issue of disappearing images is solved.
> 
> let adjustedX0 = x0;
>     let adjustedY0 = y0;
>     let adjustedX1 = x1;
>     let adjustedY1 = y1;
>     // Some bounding boxes have negative x0/y0 coordinates which will cause the
>     // some of the drawing to be off of the canvas. To avoid this shift the
>     // bounding box over.
>     // if (x0 < 0) {
>     //   adjustedX0 = 0;
>     //   adjustedX1 += Math.abs(x0);
>     // }
>     // if (y0 < 0) {
>     //   adjustedY0 = 0;
>     //   adjustedY1 += Math.abs(y0);
>     // }
>     tmpCtx.translate(-(dimx.scale * adjustedX0), -(dimy.scale * adjustedY0));
>     graphics.transform(dimx.scale, 0, 0, dimy.scale, 0, 0);
> 
> I also verified the file present that was present for the tiling pattern implementation as well, that also works - https://github.com/mozilla/pdf.js/pull/13683/files#diff-aefe7570f79e8e92a7d58fb1eb7a3c06e4d2de5761677fd4d93d39813671866d
> 
> We would like to know your views on this.

With the above fix, we are able to solve this issue and also it fixes the main issue for which this code was written. Can someone review this code and also if possible push it to the development branch?

**Comment by Snuffleupagus** [comment] 2024-06-27 11:15
Have you *successfully run all* reference tests with the diff in https://github.com/mozilla/pdf.js/issues/16038#issuecomment-2147392229 applied, since (as far as I'm concerned) it unfortunately seems unlikely to be a correct solution?
Please refer to https://github.com/mozilla/pdf.js/wiki/Contributing#4-run-lint-and-testing

**Comment by jeffdare** [comment] 2024-07-02 17:46
Yes I was able to run the tests. All the tests passed apart from 1 integration test failed("Highlight Editor Send a message when some text is selected must check that a message is sent on selection") which is not related to this code.

**Comment by Snuffleupagus** [comment] 2024-07-02 18:04
> Yes I was able to run the tests. All the tests passed apart from 1 integration test failed("Highlight Editor Send a message when some text is selected must check that a message is sent on selection") which is not related to this code.

Sorry, but then you unfortunately cannot have run the browsertests correctly since your patch breaks *at least* `issue11473` (and quite possibly other test-cases as well).

**Comment by jeffdare** [comment] 2024-07-04 04:59
Sorry not sure how i missed that, yes `issue11473` does not seem to work with my fix. 

Our customers are waiting for this fix from almost 1 year, any outlook on when we can expect the fix for this original issue?

**Comment by marco-c** [comment] 2024-07-08 11:12
@jeffdare we really want this to be fixed, but we are not sure when we'll be able to work on it as we have many higher priority things to work on.

We'd happily accept contributions though, from you, anyone else from your company, or anyone else your company or your customers might want to hire!

**Comment by rpatnani** [comment] 2024-09-04 12:46
Our customers are waiting for this fix since more than a year. Could you please let us know when the fix would be provided?

**Comment by calixteman** [comment] 2024-09-20 17:04
The fix here https://github.com/mozilla/pdf.js/issues/16038#issuecomment-2147392229 is partially correct.
Few observations:
 - the pattern should have its dimensions based on its bounding box
 - we must remove the adjustments which are just wrong (the drawing instructions take into account that they're draw in this specific bbox and it doesn't make sense in general to change that)

Of course I tried this approach but it fails with `issue11473.pdf`.
The reason is simple: the bounding box is something like [-1,-1,3,3], the draw is in the square [0,0,3,3] but the xstep and ystep are 3,3 which means that when the pattern is drawn on the canvas every tile is overlapping its neighbors.
As far as I can tell with the current canvas api, the tiles (w×h) are drawn at each p×w+q×h (where (p, q) in Z^2) which mean that the tiles cannot overlap their neighbor.
I don't really know how we can solve the problem in general...
That said, I'm inclined to think that probably the most frequent case is the one where the steps are equal to the dimensions.
So I think we should fix this bug in removing the adjustments and try to figure out some heuristics to try solve issues like the one in `issue11473.pdf`.

@Snuffleupagus, what do you think ?

**Comment by rpatnani** [comment] 2024-09-20 17:29
Our customer has been waiting for this fix for almost two years now. If anyone can fix it, it would be great!

**Comment by calixteman** [comment] 2024-09-20 17:29
I really need to think about that but maybe we could fix the case where x_step and y_step are different of width and height, in doing the following steps:
- create a tile w×h
- draw it
- compute the minimal rectangle including the bbox and where the corners have some coordinates like p×x_step+q×y_step
- create a canvas with the dimensions x_step×y_step
- file the minimal rectangle defined above and file it with the tile
- the newly canvas created canvas is the final pattern

I'm not completely sure it works be it could the right fix.

**Comment by calixteman** [comment] 2024-09-20 17:31
> Our customer has been waiting for this fix for almost two years now. If anyone can fix it, it would be great!

Sorry but your message is useless...
And if your customer isn't happy please fix the bug yourself instead of nagging the people who're working for you and for free !

**Closed** 2024-09-26 12:25 UTC
Labels: tiling-type
