### ISSUE TITLE
[Feature]: Distribute viewer with pdfjs-dist

### ISSUE THREAD

**Issue by deadbeef84** [mozilla/pdf.js#19112] opened 2024-11-27 09:44 UTC
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

It would be practical if the `pdfjs-dist` package included `viewer.html`. There are multiple npm packages doing this (pdfjs-viewer-build, pdfjs-dist-viewer-min, @suxueweibo/pdfjs-dist-es5) but they are constantly getting out-of-date.

Perhaps this is actually a bug, as it's listed in the files section of "Prebuilds" on https://mozilla.github.io/pdf.js/getting_started/ ?

**Comment by Snuffleupagus** [comment] 2024-11-27 09:48
Duplicate of #18751

**Closed by Snuffleupagus** 2024-11-27 09:48 UTC
