### ISSUE TITLE
Error in firefox while rendering complex PDF files

### ISSUE THREAD

**Issue by darkman97i** [mozilla/pdf.js#14034] opened 2021-09-17 07:36 UTC
Attach (recommended) or Link to PDF file here:
https://filetransfer.io/data-package/dzVBY8Ud#link

Configuration:
- Web browser and its version: Firefox 92.0 (64-bit)
- Operating system and its version: Linux mint ( but also do not work in Windows )
- PDF.js version: 2.9.359
- Is a browser extension: No

Steps to reproduce the problem:
1. Preview the document in firefox ( I have attached PDF.js build with the file for a quick review )

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
Preview work in Chrome but not in Firefox

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Description of files attached:
* the PDF file have been generated from complex a autocad project
* test.pdf the file what do not works
* overwritten compressed.tracemonkey-pldi-09.pdf into pdf.js/web for a quick testing
![Selección_072](https://user-images.githubusercontent.com/958703/133742979-aa33c810-11af-4197-a799-d8059ad53fa3.png)

* Sorry for the dirty PDF, but I can not share real PDF because private data, only I can share this dirty file to emulate the behaviour. In the next screen can watch how chrome render the file
![Selección_070](https://user-images.githubusercontent.com/958703/133743381-3596430b-ff6e-4ea6-b927-7d66ce73aa6b.png)

* Screenshot with error shown in firefox console:
![Selección_071](https://user-images.githubusercontent.com/958703/133743407-b6caaf6a-054f-4cb5-84fc-8eee1adbe63d.png)

**Comment by Snuffleupagus** [comment] 2021-09-17 07:51
Duplicate of #6741

**Closed by Snuffleupagus** 2021-09-17 07:51 UTC

**Comment by Bexruz999** [comment] 2024-05-24 09:56
![image](https://github.com/mozilla/pdf.js/assets/105708733/e6b9c35f-adf8-4901-a036-87089f138978)
