### ISSUE TITLE
npm install pdf.js does not install PDF.js

### ISSUE THREAD

**Issue by totty90** [mozilla/pdf.js#5777] opened 2015-03-03 11:13 UTC
As every other library an easy way to use it should be available without me to need to build it. I want to test it so, a script tag should be enough to get started. 

In my case I use webpack and require('pdf.js') doesn't work because of your coffee files. NPM should work out of the box. I've installed with `npm install pdf.js`.

I also get an error if I follow your instructions:

    module.js:340
        throw err;
              ^
    Error: Cannot find module 'C:\a\node_modules\pdf.js\make'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:906:3

I think I need `make` library. I suppose this is the command? `npm install make -g`

**Comment by Rob--W** [comment] 2015-03-03 11:19
PDF.js is written in JavaScript, not CoffeeScript. Perhaps you're confusing this repository with something else?

There are some straightforward instructions for setting up PDF.js at https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website.

**Comment by totty90** [comment] 2015-03-03 11:21
Sorry, my bad, I've installed this library: https://www.npmjs.com/package/pdf.js

You should really talk to this guy and figure out something because there is a conflict: https://github.com/mozilla/pdf.js/blob/master/package.json#L2 

Thanks for further help

**Comment by totty90** [comment] 2015-03-03 11:24
The npm to install is this: `pdfjs-dist`, right?

**Comment by Rob--W** [comment] 2015-03-03 11:26
Yes. And `pdfjs-dist` is hosted at https://github.com/mozilla/pdfjs-dist.

**Comment by totty90** [comment] 2015-03-03 11:28
Shouldn't be added on your readme? Instead of all that complicated way which requires to build it manually? Just drop: `npm install pdfjs-dist` and is pretty done. You can also add bower.

**Comment by Rob--W** [comment] 2015-03-03 11:29
Pull requests are welcome ;) And if I'm not mistaken, you can also edit the wiki that I linked before.

**Comment by totty90** [comment] 2015-03-03 11:33
Updated.

**Comment by Rob--W** [comment] 2015-03-03 11:39
Could you try out your instructions before saving them? There is a Preview tab in the wiki editor, so you can see how your changes are going to look without saving. Ping me if you're done and want me to review your changes.

**Comment by totty90** [comment] 2015-03-03 11:41
Thanks, I didn't knew about it. Ok.

**Comment by totty90** [comment] 2015-03-03 11:58
This promise `workerInitializedCapability.promise.then(function transportInitialized() {` never ends.

Here is the code with webpack:

    require('pdfjs-dist/build/pdf');
    PDFJS.disableWorker = true;
    PDFJS.workerSrc = '';

should I open a new issue or?

**Comment by Rob--W** [comment] 2015-03-03 12:00
Yes, preferably with all steps needed to reproduce the bug.

**Comment by totty90** [comment] 2015-03-03 12:10
Ok, I've figured out how to do it.

**Comment by totty90** [comment] 2015-03-03 12:17
You can review my changes. I've done the setup for webpack.

**Comment by yurydelendik** [comment] 2015-03-03 12:44
Looks like this issue is not connected with Mozilla's PDF.js. Closing as invalid.

**Closed by yurydelendik** 2015-03-03 12:44 UTC
Labels: 1-other
