### ISSUE TITLE
JPEG error: unexpected marker ffd9

### ISSUE THREAD

**Issue by andrelombaard** [mozilla/pdf.js#8160] opened 2017-03-14 10:57 UTC
[test.PDF](https://github.com/mozilla/pdf.js/files/841002/test.PDF)

Configuration:
- IE 11/Chrome 56.0.2924.87
- Windows 10:
- PDF.js 1.7.225

Steps to reproduce the problem:
1.  Got the clone from git://github.com/mozilla/pdf.js.git
2 . Ran a build using 'gulp generic'
3. Published to a web server
4. Made use of the example viewer.html to display the PDF

I see issues already opened for this problem and as far as I understand this issue should be resolved by the jpg.js file. Am I missing something?

What went wrong? 

![error](https://cloud.githubusercontent.com/assets/14308931/23897419/c3208392-08b5-11e7-83b6-f7d0f949ef45.png)

**Comment by Snuffleupagus** [comment] 2017-03-14 11:34
This is probably a duplicate of issue #7828, and the issue seems to be that we unexpectedly encounter the EOI (End Of Image) marker while parsing Scan data.

**Comment by Snuffleupagus** [comment] 2017-03-15 15:36
Closing as duplicate of issue #7828.

**Closed by Snuffleupagus** 2017-03-15 15:36 UTC
Labels: 3-pdf-broken, 4-image-conversion, 4-image-jpeg
