### ISSUE TITLE
Incorrect font spacing while viewing the pdf downloaded from Google docs with Roboto font

### ISSUE THREAD

**Issue by nitineltropy** [mozilla/pdf.js#9112] opened 2017-11-09 13:06 UTC
Link to PDF file here:
[Faulty.pdf](https://github.com/mozilla/pdf.js/files/1457618/Faulty.pdf)

Configuration:
- Web browser and its version: Google Chrome v62.0.3202.89 
- Operating system and its version: macOS Sierra 
- PDF.js version: 1.9.491
- Is a browser extension: No

Steps to reproduce the problem:
1. Download a pdf from GoogleDocs with font set to 'Roboto'
2. View the same pdf in viewer.js or in the latest firefox browser

What went wrong? (screenshot)
<img width="1440" alt="screen shot 2017-11-09 at 6 32 05 pm" src="https://user-images.githubusercontent.com/11753283/32606704-52662704-c57c-11e7-9c4f-363a7e662660.png">

The same pdf with a different font for eg. Arial works fine. 
I'm guessing there should be some issue in rendering the Roboto font.

**Comment by Snuffleupagus** [comment] 2017-11-09 13:24
Closing as duplicate of issues #9024, #9039, and #9068.

**Closed by Snuffleupagus** 2017-11-09 13:24 UTC
