### ISSUE TITLE
Add minified files in the pdfjs-dist

### ISSUE THREAD

**Issue by w3apps** [mozilla/pdf.js#6037] opened 2015-05-21 09:36 UTC
It would be great to have minified files in the pdfjs-dist. This way people can avoid waiting about 10-15 seconds to minify pdf.js (which is huge) in their own build.

**Comment by Snuffleupagus** [comment] 2015-05-21 10:04
Closing as duplicate of issue #5487.

**Closed by Snuffleupagus** 2015-05-21 10:04 UTC
