### ISSUE TITLE
Feature request: Add a `findmultiple` event

### ISSUE THREAD

**Issue by valh1996** [mozilla/pdf.js#15225] opened 2022-07-26 15:43 UTC
Hi,

Currently, we can search in the following way:

```js
eventBus.dispatch('find', {
  query: 'alex',
  highlightAll: true,
  caseSensitive: false,
  matchDiacritics: false
})
```

It would be nice to be able to search for multiple keywords (with a `findmultiple` event for example) but with different case/diacritics restrictions:
```js
eventBus.dispatch('findmultiple', [
  {
     query: 'alex',
     findPrevious: true,
     highlightAll: true,
     caseSensitive: false,
     matchDiacritics: false
  },
  {
     query: 'aLiCè',
     findPrevious: true,
     highlightAll: true,
     caseSensitive: true,
     matchDiacritics: true
  }
])
```

Would it be possible to add this feature please?

**Comment by Snuffleupagus** [comment] 2022-07-26 15:46
Duplicate of #7442 and/or #11748

**Closed by Snuffleupagus** 2022-07-26 15:46 UTC

**Comment by valh1996** [comment] 2022-07-26 15:58
It was very fast :/ 
I don't think it's a duplicate since we are talking about a "feature request". You can imagine that I came across these two issues before creating my own. But nothing seems to have moved for years and the proposed tweaks do not allow to do what my feature request proposes.

I think many people would be interested in this feature, but this is just my humble opinion.

**Comment by Snuffleupagus** [comment] 2022-07-26 16:30
> I don't think it's a duplicate since we are talking about a "feature request".

Note that the other issues are also feature requests, even if they maybe don't use those *exact* words...

> But nothing seems to have moved for years

While that's unfortunate, and probably is connected with this functionality not really being necessary for the Firefox PDF Viewer, it doesn't really mean that we need *yet another* very similar issue. Please note that in general, having (near) duplicate issues for the same thing usually just means that any discussion becomes fragmented and more difficult to follow.

> the proposed tweaks do not allow to do what my feature request proposes

While it'd likely be possible, without too much trouble, to support #7442 (note the abandoned PR #11749) it seems that what you're specifically asking for here most unfortunately wouldn't be trivial to implement/support and would risk adding unnecessary complexity to the already somewhat complicated find-functionality.
