### ISSUE TITLE
Printing correct rotation and correct font 

### ISSUE THREAD

**Issue by otorite** [mozilla/pdf.js#7983] opened 2017-01-23 12:14 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:          Mozilla 45.6.0
- Operating system and its version:   Debian Jessie 8.6
- PDF.js version:                                  1.6.471
- Is an extension:                                 Yes

Steps to reproduce the problem:
1. open pdf that include  multiple rotation pages in mozilla
2. print all pages
3. all pages printing as portait 

What is the expected behavior? (add screenshot)
print portrait as portrait, landscape as landscape with original font
with pdf.js 1.1.209 print pages correctly but it changes the original font to another

Is there any luck using 1.1.209 page scaling skill and 1.6.471 font using skill in the new version of pdf.js?

Regards,

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment] 2017-01-23 16:44
> Is there any luck using 1.1.209 page scaling skill and 1.6.471 font using skill in the new version of pdf.js?

The question is not clear. Please attach PDF and clear steps to reproduce the issue. FWIW page scaling and rotation must handled by the user -- only user can control page setup dialog (not a web page).

**Comment by timvandermeij** [comment] 2017-01-23 21:16
Closing as duplicate of multiple issues such as #4514.

**Closed by timvandermeij** 2017-01-23 21:16 UTC
Labels: 4-information-requested
