### ISSUE TITLE
Incorrect colors in CMYK JPG

### ISSUE THREAD

**Issue by photopea** [mozilla/pdf.js#10025] opened 2018-08-31 15:36 UTC
Hi, I use jpg.js from this repository to decode JPG images. I have several images in CMYK format, for which I get incorrect colors.

    var j = new PDFJS.JpegImage();
    j.parse(buff);
    var w = j.width, h = j.height;
    var data = j.getData(w,h,true);  // RGB data, w*h*3 Bytes

The "data" array contains pixels with incorrect colors. Could you fix it, or tell me if I use it in a wrong way? I attach JPG images here:  [jpg.zip](https://github.com/mozilla/pdf.js/files/2340671/jpg.zip)

The image from PDFJS is on the left, the image from a JPG viewer is on the right.
![dog](https://user-images.githubusercontent.com/15955558/44922232-1fa42580-ad45-11e8-974e-a739368f0a66.png)

**Comment by Snuffleupagus** [comment] 2018-08-31 18:11
This appears, for all intents and purposes, to be a duplicate of issue #9513.

**Comment by timvandermeij** [comment] 2018-08-31 21:43
I agree. Let's close this one and track the issue there. Thanks.

**Closed by timvandermeij** 2018-08-31 21:43 UTC

**Comment by photopea** [comment] 2018-09-01 13:38
You are right, I forgot about that issue of mine.
