### ISSUE TITLE
z-index of Image incorrect with IE11

### ISSUE THREAD

**Issue by futot1** [mozilla/pdf.js#7949] opened 2017-01-12 07:21 UTC
Link to PDF file (or attach file here):
[AN_1133935_p3.pdf](https://github.com/mozilla/pdf.js/files/700909/AN_1133935_p3.pdf)

Configuration:
- Web browser and its version: IE11 only (OK for Firefox/Chrome)
- Operating system and its version: Windows 7 (possibly any version of Windows)
- PDF.js version: Current
- Is an extension:

Steps to reproduce the problem:
1.  Open the attached PDF file
2. Scroll to middle of the page. You will see back ground image comes upper to section label text.

What is the expected behavior? (add screenshot)
![pdfjs_20170112_2](https://cloud.githubusercontent.com/assets/7111820/21880558/f7c74f48-d8e2-11e6-9d19-8057f89906db.png)

What went wrong? (add screenshot)
![pdfjs_20170112_1](https://cloud.githubusercontent.com/assets/7111820/21880561/ff6c0306-d8e2-11e6-8907-20ab2138b8f4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-01-12 10:07
Closing as duplicate of issue #5264.

**Closed by Snuffleupagus** 2017-01-12 10:07 UTC
