### ISSUE TITLE
`pdfDoc.saveDocument()` is not a function

### ISSUE THREAD

**Issue by cookgreen** [mozilla/pdf.js#17982] opened 2024-04-22 10:42 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version:
- PDF.js version: v3.5
- Is a browser extension:

I am using pdf.js for my project, the project is based on ASP.NET MVC, so I have integrated the pdfjs in the project, but when I try to save the pdf, it notice me error like this:  

![2024-04-15 21-28-29-97](https://github.com/mozilla/pdf.js/assets/21171007/ed1debc3-4cfe-4b60-b714-5c4f1d4ef227)

Here is my code to call the `saveDocument` function in the cshtml:  
```
pdfDoc.saveDocument().then((data)=>
 {
            var blob = new Blob([data], { type: "application/pdf" });
            var downloadMgr = new DownloadManager();
            downloadMgr.download(blob, url, "saved_pdf.pdf", {});
});
```

so please help me to fix this issue, thanks

**Comment by Snuffleupagus** [comment] 2024-04-22 10:47
Duplicate of #17945

---

> PDF.js version: v3.5

That's first of all not a complete version number, and secondly any `3.5.x` version is no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Here is my code to call the `saveDocument` function in the cshtml:

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Closed by Snuffleupagus** 2024-04-22 10:47 UTC
