### ISSUE TITLE
Searching a sentence with spaces between the words doesn't work.

### ISSUE THREAD

**Issue by wonjunkang** [mozilla/pdf.js#11861] opened 2020-04-30 17:27 UTC
Attach (recommended) or Link to PDF file here:
It's internal document so I couldn't provide it here.
Configuration:
- Web browser and its version: Chrome Version 81.0.4044.129 (Official Build) (64-bit)
- Operating system and its version: MacOS Catalina 10.15.4 
- PDF.js version: 2.3.200
- Is a browser extension: No browser extension.

Steps to reproduce the problem:
1. When we search a sentence in a pdf, it doesn't work.(Not found.) But if we search the same sentence after removing all the spaces between words, it searches the right sentence in the pdf. 
2. I think this depends on the type of pdf.. only certain number of pdfs gives me this problem. 

What is the expected behavior? (add screenshot)
Find the correct sentence.
What went wrong? (add screenshot)

![Screen Shot 2020-04-30 at 1 27 04 PM](https://user-images.githubusercontent.com/58698642/80740584-49978780-8ae6-11ea-8ca7-332bb20ec4fa.png)

![image](https://user-images.githubusercontent.com/58698642/80740555-3d132f00-8ae6-11ea-85e7-63042a3f62b7.png)

![image](https://user-images.githubusercontent.com/58698642/80740535-371d4e00-8ae6-11ea-8a99-200fc9d2c5c2.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by wonjunkang** [comment] 2020-04-30 17:30
The only way I could think to solve this was to change the code where the pdfjs is generating all these span html tags and put a space inside. 
1. I can't find where to look at to change this code. 
2. Is there any other way I could solve this problem? If there is a difference of these kinds of pdf, I can notify that and search it with no spaces. 
Anybody has ideas when this happens and maybe also different approach to solve this?

**Comment by Snuffleupagus** [comment] 2020-04-30 18:04
> Attach (recommended) or Link to PDF file here:
> It's internal document so I couldn't provide it here.

Without the PDF file in question, this issue unfortunately isn't actionable/valid; most likely there's probably similar issue(s) open already in https://github.com/mozilla/pdf.js/labels/4-text-selection

> PDF.js version: 3.2.1

That version number does not exist, please find actual releases at https://github.com/mozilla/pdf.js/releases

**Comment by wonjunkang** [comment] 2020-04-30 18:17
@Snuffleupagus  Thanks for your quick reply. Sorry I updated with the right version. Let me find a pdf that has the same problem but can be public.. I'm new to pdfjs if possible, do you see any issue already opened that are similar to this issue?

**Comment by Snuffleupagus** [comment] 2020-04-30 18:32
> I'm new to pdfjs if possible, do you see any issue already opened that are similar to this issue?

You could probably have look through the list I linked just as quickly as I did :-)

Based on the limited information provided, the following are reasonable candidates:
Duplicate of #9736
Duplicate of #9186

**Comment by timvandermeij** [comment] 2020-04-30 21:49
Closing since this looks like a duplicate of the issues mentioned above. If not, please provide additional details.

**Closed by timvandermeij** 2020-04-30 21:49 UTC
