### ISSUE TITLE
Rendering of alternate lines are blurry and not displayed clearly.

### ISSUE THREAD

**Issue by ShruAror** [mozilla/pdf.js#14085] opened 2021-09-27 15:48 UTC
Attach (recommended) or Link to PDF file here:
Alternate lines in a PDF document shows blurry when viewed at a zoom level of 70%
The sample document will be uploaded by the client within a couple of hours. Request you to wait.

Configuration:
- Web browser and its version: Any browser. Tested in Chrome
- Operating system and its version: Any OS. Tested in Windows
- PDF.js version: [2.5.207](URL)
- Is a browser extension: 

Steps to reproduce the problem:
1. Open the attached document
2. Alternate lines appear blurry when viewed on a monitor at zoom level 70%

What is the expected behavior? (add screenshot) No blurry lines.

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-09-27 15:57
> The sample document will be uploaded by the client within a couple of hours. Request you to wait.

Please respect peoples time, since this is an open-source projects (where many of us are *unpaid* volunteers), by waiting until you've gathered *all* of the required information *before* opening an issue!

> PDF.js version: [2.5.207](URL)

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by zeusmoss** [comment] 2021-09-28 14:26
[blur image.pdf](https://github.com/mozilla/pdf.js/files/7244892/blur.image.pdf)
please find the attached document

**Comment by ShruAror** [comment] 2021-09-30 12:51
I could see some blurriness in the text when reducing the zoom level even in the latest version. The document is uploaded. Can you please reopen the ticket?

**Comment by Snuffleupagus** [comment] 2021-10-02 10:10
WFM, when testing with the *built-in* PDF Viewer in Firefox 94.

> I could see some blurriness in the text when reducing the zoom level

That's not actually text, but rather an image. Furthermore, the ISSUE_TEMPLATE is specifically asking for screen-shots since it's not at all clear what "blurriness" you're referring to here.

> even in the latest version.

Such a statement is not helpful, since "latest" can mean any number of things. Hence why an actual version *number* is required.

---

The above is why I didn't re-open this issue, since I cannot reproduce the issue and given that it's *still* missing enough information to be actionable/valid.

**Comment by timvandermeij** [comment] 2021-10-02 10:30
I noticed that at 70% the entire page becomes a bit blurry, which is what I assume was meant here (but indeed, screenshots would have been good to confirm). I'm attaching my screenshots below:

80% is fine:
![80p](https://user-images.githubusercontent.com/1993262/135712540-5173ca1c-1956-497c-b7c1-e3fad35fb230.png)


70% looks less sharp:
![70p](https://user-images.githubusercontent.com/1993262/135712542-ca32029e-2671-4801-877f-e280811a0b6b.png)
:

**Comment by Snuffleupagus** [comment] 2021-10-02 10:39
> I guess this is simply due to everything being an image. I'm attaching my screenshots below:

Thank you!
In that case it seems that the issue is simply about the fact that downsizing of images may result in slightly different rendering at different zoom levels (depending on e.g. the particular downsizing algorithm used), since images will never look *perfect* when downsized (compared to e.g. rendering of vector-data).

All-in-all, closing as WONTFIX (or even INVALID) since this is more-or-less expected when downsizing images a lot.

**Closed by Snuffleupagus** 2021-10-02 10:39 UTC
Labels: 1-core, 4-information-requested

**Comment by ShruAror** [comment] 2021-10-04 07:41
@Snuffleupagus and @timvandermeij Thank you for your analysis and help. Appreciate that.
