### ISSUE TITLE
need event trigger if page is not visible on screen

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#6611] opened 2015-11-09 12:59 UTC
loading a huge pdf can become a crawl when so mamy pages have been viewed.

would be nice to have an event trigger that will remove the page in the dom if it is not visible.

once it gets visible again, page rendered gets called

**Comment by yurydelendik** [comment] 2015-11-10 20:26
[PDFPageViewBuffer](https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js#L57) is doing just that. Based on the information provided, closing as invalid.

**Closed by yurydelendik** 2015-11-10 20:26 UTC
Labels: 2-performance

**Comment by chitgoks** [comment] 2015-11-11 02:38
@yurydelendik hi yury, what i meant is that, let's say pages 1, 2 and 3 are loaded. they will have attribute date-loaded="true" in the div element.

and i scroll to page 8. pages 1, 2 and 3 are not visible in the browser so it would be nice if there is a way to be detected that pages 1, 2 and 3 are not visible.

at least i can manually remove the contents of div#pageContainer and add <div class="loadingIcon"></div> so when browsed, it will repopulate the contents when it gets visible in the view.

i looked at PDFPageViewBuffer and please correct me if i am wrong, there does not seem to be a function that does it.

please advise

**Comment by chitgoks** [comment] 2015-11-11 04:38
i used Javascript for this instead. id like to ask, is there an existing function that removes the pages drawn by the viewer so that when user will browse to those pages, the contents of pageContainer# will be reconstructed?

**Comment by yurydelendik** [comment] 2015-11-11 04:50
So it's pretty much a duplicate of #5765?

**Comment by chitgoks** [comment] 2015-11-11 05:04
this is it. thank you yury
