### ISSUE TITLE
Background not displayed

### ISSUE THREAD

**Issue by jpfleury** [mozilla/pdf.js#6324] opened 2015-08-06 18:09 UTC
When I open the PDF file http://gmic.eu/img/flyer.pdf with Firefox 39.0 on Xubuntu 15.04, the button background at the bottom of the page is not displayed:

![capture d ecran_2015-08-06_14-06-24](https://cloud.githubusercontent.com/assets/687082/9119375/5a6d69a8-3c44-11e5-90a6-7badf99aee18.png)

so the white text is invisible on the white background.

**Expected result:** black background. Example with Evince 3.14.2:

![capture d ecran_2015-08-06_14-08-10](https://cloud.githubusercontent.com/assets/687082/9119434/981e641e-3c44-11e5-9c1d-c60fdda27f09.png)

Same result with Okular 0.21.3.

**Comment by timvandermeij** [comment] 2015-08-06 19:30
This PDF uses shading types 2 and 3. Perhaps the issue is related to that?

**Comment by THausherr** [comment] 2015-09-03 16:00
Porbably. And it's not just the element at the bottom. The six other oval elements (shading type 3) are also not rendered correctly.

**Comment by Snuffleupagus** [comment] 2015-12-16 18:24
This is *almost* fixed by PR #6684.

**Comment by timvandermeij** [comment] 2019-09-19 11:49
Closing since this now looks exactly like in the screenshot.

**Closed by timvandermeij** 2019-09-19 11:49 UTC
Labels: 2-image-quality, 4-shading-pattern
