### ISSUE TITLE
Characters and orientation messed up during printing

### ISSUE THREAD

**Issue by wojtekmaj** [mozilla/pdf.js#10296] opened 2018-11-23 15:00 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  FF 64.0b11
- Operating system and its version: Windows 10
- PDF.js version: 2.0.936
- Is a browser extension: yes

Steps to reproduce the problem:
1. Print a PDF

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

![skan_20181123](https://user-images.githubusercontent.com/5426427/48958098-5319d900-ef5d-11e8-91a1-79f447ce1eae.jpg)

**Comment by timvandermeij** [comment] 2018-11-23 21:31
I cannot reproduce this with the default viewer. Does this happen for any PDF file or only a specific one? If so, please provide it.

**Comment by wojtekmaj** [comment] 2018-11-23 21:45
I neither have the same file, or the same printer near me right now, so I can't tell if that's something that's 100% reproducible. I tried similar PDFs (it's a ticket from Polish railways) and an option to print to PDF but I couldn't reproduce this issue. Will retry during the weekend.

**Comment by Snuffleupagus** [comment] 2019-01-26 13:37
Most likely just a (forward) duplicate of #10414, and without the actual PDF file this isn't actionable anyway.

**Closed** 2019-01-26 14:54 UTC
Labels: 4-printing
