### ISSUE TITLE
µ character displayed as infinity

### ISSUE THREAD

**Issue by kuro68k** [mozilla/pdf.js#16008] opened 2023-02-05 11:29 UTC
Example PDF: https://www.analog.com/media/en/technical-documentation/data-sheets/lt1255.pdf
(First page, left side under "Features", it says "12μA Standby Current").

Configuration:
- Web browser and its version:
Chrome 109.0.5414.120 (Official Build) (64-bit)
- Operating system and its version:
Tested on Windows 8.1 and Windows 10, both with latest patches as of February 1st 2023.
- PDF.js version:
2.3.164
- Is a browser extension:
Yes

Steps to reproduce the problem:
1. Open PDF linked above.

What is the expected behavior? (add screenshot)

The µ character id displayed correctly.

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/2674466/216816112-bf1a9d53-aef1-4ab2-8fe9-eb80d9416dc4.png)

The µ character id displayed as an infinity symbol.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm

**Comment by Snuffleupagus** [comment] 2023-02-05 11:37
> Example PDF: https://www.analog.com/media/en/technical-documentation/data-sheets/lt1255.pdf

WFM, when opening that document with https://github.com/mozilla/pdf.js#online-demo

> PDF.js version:
>       2.3.164
> [...]
> Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
> https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm

That would make this a duplicate of #13669

**Closed by Snuffleupagus** 2023-02-05 11:37 UTC
