### ISSUE TITLE
Scrolling for PDF file is slow

### ISSUE THREAD

**Issue by cyroxx** [mozilla/pdf.js#3120] opened 2013-04-19 10:41 UTC
http://www.pharmazeutische-zeitung.de/fileadmin/pdf/PZ-Beilage-ApBetrO_2012_21.pdf

This looks odd and produces a bunch of errors. Actually, it is just those two:

```
downloadable font: table 'CFF ': failed to parse table (font-family: "g_font_p3_4" style:normal weight:normal stretch:normal src index:0)
```

and

```
downloadable font: rejected by sanitizer (font-family: "g_font_p3_4" style:normal weight:normal stretch:normal src index:0)
```

The other errors are in fact only siblings of the two mentioned above, as only the font family is different.

Note that the font is provided as a data url. Please also note that the document contains German umlauts.

**EDIT**
Tested under Firefox 20.0.1.

**Comment by fkaelberer** [comment] 2015-01-04 16:41
The original issue is still (or again?) there: 
Its broken in FF Dev Edition 36.0a2 (Win), FF nightly 37.0a1 (Win&Linux), Chrome 39 (Linux), 
It works fine in FF 34 (Win&Linux)
Here is page 11 in FF 36 and 34:
![zwischenablage01](https://cloud.githubusercontent.com/assets/4624768/5606647/a1d20254-9438-11e4-902c-291c88f124ce.png)

**Comment by fkaelberer** [comment] 2015-01-04 16:47
I also consider the performance issue as not fixed, even with #5586: try to scroll down to page 25 or some other page with a lot of small text, and the large number of div elements will slow Firefox down significantly (there's one div for every two letters or so). If its not slow, try scrolling up an down for a while.

**Comment by Snuffleupagus** [comment] 2015-01-04 16:53
@fkaelberer Since the font issue was actually fixed at one point (PR #4259), would you mind running [`git bisect`](https://github.com/mozilla/pdf.js/wiki/Bisecting-a-Regression) to find out where it regressed again?

**Comment by fkaelberer** [comment] 2015-01-11 17:31
Last good commit: 2803c31... Merge pull request #5129 from Snuffleupagus/issues-4875-4881-tests
([viewer](http://107.21.233.14:8877/01aecf0715f0d71/web/viewer.html) from previous commit, #5127)
First bad commit: 6865c28... Merge pull request #5111 from nnethercote/better-cidchars 
([viewer](http://107.21.233.14:8877/75f92af42a46fc1/web/viewer.html) from following commit, #5136)

**Comment by fkaelberer** [comment] 2015-01-11 17:44
BTW, the "last good commit" wasn't really that good: The image shows on the right side (="last good commit") that the letter 'i' in the red text is not italic and the letter 'n' in the remaining text has the wrong font weight. These are exactly those letters which are missing on the left side (="first bad commit"). 

![zwischenablage03](https://cloud.githubusercontent.com/assets/4624768/5696098/36a9b38a-99c1-11e4-8580-2b4264bc7201.png)

**Comment by timvandermeij** [comment] 2015-02-27 18:52
I can reproduce the missing letters and the scrolling performance is still a bit of a problem once you get half-way scrolling through the document.

**Comment by timvandermeij** [comment] 2015-06-13 14:20
There are sanitizer errors, which might explain the missing characters:

<pre>
"PDF 956fb3798200a14d9840b55a0f7db9af [1.4 Adobe PDF Library 8.0 / Adobe InDesign CS3 (5.0.4)] (PDF.js: 1.1.203)" viewer.js:6633:0
downloadable font: CFF : failed to parse table (font-family: "g_font_98" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIDNVseoAAACcAAAB0U9TLzIEjypwAAACcAAAAGBjbWFwAAvgMwAAAtAAAAAsaGVhZKsnUAkAAAL8AAAANmhoZWEDugKaAAADNAAAACRobXR4AAAAAAAAA1gAAAAEbWF4cAABUAAAAANcAAAABm5hbWUlFWqxAAADZAAAAo5wb3N0AAMAAAAABfQAAAAgAQAEAgABAQElU0RPSVFOK0hlbHZldGljYU5ldWUtSGVhdnktT1YtR0lHVVpBAAEBAUb4G/gciwwe+B0B+B4EHQAAoZsN+z37fvrc+ksFHQAAAWIPHQAAAWMRHQAAAAAdAAAAABL4HwwVHQAAAYcMJR0AAAGJDCQABgEBBg6lqsLfQWRvYmVJZGVudGl0eUNvcHlyaWdodCBcKGNcKSAxOTg4LCAxOTkwLCAxOTkzIEFkb2JlIFN5c3RlbXMgSW5jb3Jwb3JhdGVkLiAgQWxsIFJpZ2h0cyBSZXNlcnZlZC5IZWx2ZXRpY2EgaXMgYSB0cmFkZW1hcmsgb2YgTGlub3R5cGUtSGVsbCBBRyBhbmQvb3IgaXRzIHN1YnNpZGlhcmllcy5IZWF2eS9PcmlnRm9udFR5cGUgL1R5cGUxIGRlZkhlbHZldGljYU5ldWUtSGVhdnktT1YtR0lHVVpBAAAAAAABAQEg90b3+QHT9/kD0/f5FSjaO+7u29vu7jvaKCg8PCgeDgAAAAEBARAdAAAAMx0AAAGdEvggDCZ8mvlemvtmmvc3lAb3oZTWlPy0kwd6nPlenPtqlwj3pZLvkvzplwn3JAr3PguMDA74iBQAAAAAAAMCJAH0AAUAAAKKArsAAACMAooCuwAAAd8AMQECAAAAAAYAAAAAAAAAAAAAABAAAAAAAAAAAAAAACoyMSoAAOAA4AADt/8WAGQDtwDqAAAAAAAAAAAAAAOEAADgAAADAAAAAQADAAEAAAAMAAQAIAAAAAQABAABAADgAP//AADgAP//IAAAAQAAAAAAAQAAAAAQAAAAAABfDzz1AAAD6AAAAACeC34nAAAAAJ4LficAAP8WD/8DtwAAABEAAAAAAAAAAAABAAADt/8WAAD//wAAAAAAAAOEAAAAAAAAAAAAAAAAAAAAAQAAAAAAAFAAAAEAAAAAABQA9gABAAAAAAAAABAAAAABAAAAAAABACQAEAABAAAAAAACAAcANAABAAAAAAADAAgAOwABAAAAAAAEACQAQwABAAAAAAAFAAwAZwABAAAAAAAGAAAAcwABAAAAAAAHAAcAcwABAAAAAAAIAAcAegABAAAAAAAJAAcAgQADAAEECQAAACAAiAADAAEECQABAEgAqAADAAEECQACAA4A8AADAAEECQADABAA/gADAAEECQAEAEgBDgADAAEECQAFABgBVgADAAEECQAGAAABbgADAAEECQAHAA4BbgADAAEECQAIAA4BfAADAAEECQAJAA4Bik9yaWdpbmFsIGxpY2VuY2VTRE9JUU4rSGVsdmV0aWNhTmV1ZS1IZWF2eS1PVi1HSUdVWkFVbmtub3dudW5pcXVlSURTRE9JUU4rSGVsdmV0aWNhTmV1ZS1IZWF2eS1PVi1HSUdVWkFWZXJzaW9uIDAuMTFVbmtub3duVW5rbm93blVua25vd24ATwByAGkAZwBpAG4AYQBsACAAbABpAGMAZQBuAGMAZQBTAEQATwBJAFEATgArAEgAZQBsAHYAZQB0AGkAYwBhAE4AZQB1AGUALQBIAGUAYQB2AHkALQBPAFYALQBHAEkARwBVAFoAQQBVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABTAEQATwBJAFEATgArAEgAZQBsAHYAZQB0AGkAYwBhAE4AZQB1AGUALQBIAGUAYQB2AHkALQBPAFYALQBHAEkARwBVAFoAQQBWAGUAcgBzAGkAbwBuACAAMAAuADEAMQBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= PZ-Beilage-ApBetrO_2012_21.pdf
downloadable font: rejected by sanitizer (font-family: "g_font_98" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIDNVseoAAACcAAAB0U9TLzIEjypwAAACcAAAAGBjbWFwAAvgMwAAAtAAAAAsaGVhZKsnUAkAAAL8AAAANmhoZWEDugKaAAADNAAAACRobXR4AAAAAAAAA1gAAAAEbWF4cAABUAAAAANcAAAABm5hbWUlFWqxAAADZAAAAo5wb3N0AAMAAAAABfQAAAAgAQAEAgABAQElU0RPSVFOK0hlbHZldGljYU5ldWUtSGVhdnktT1YtR0lHVVpBAAEBAUb4G/gciwwe+B0B+B4EHQAAoZsN+z37fvrc+ksFHQAAAWIPHQAAAWMRHQAAAAAdAAAAABL4HwwVHQAAAYcMJR0AAAGJDCQABgEBBg6lqsLfQWRvYmVJZGVudGl0eUNvcHlyaWdodCBcKGNcKSAxOTg4LCAxOTkwLCAxOTkzIEFkb2JlIFN5c3RlbXMgSW5jb3Jwb3JhdGVkLiAgQWxsIFJpZ2h0cyBSZXNlcnZlZC5IZWx2ZXRpY2EgaXMgYSB0cmFkZW1hcmsgb2YgTGlub3R5cGUtSGVsbCBBRyBhbmQvb3IgaXRzIHN1YnNpZGlhcmllcy5IZWF2eS9PcmlnRm9udFR5cGUgL1R5cGUxIGRlZkhlbHZldGljYU5ldWUtSGVhdnktT1YtR0lHVVpBAAAAAAABAQEg90b3+QHT9/kD0/f5FSjaO+7u29vu7jvaKCg8PCgeDgAAAAEBARAdAAAAMx0AAAGdEvggDCZ8mvlemvtmmvc3lAb3oZTWlPy0kwd6nPlenPtqlwj3pZLvkvzplwn3JAr3PguMDA74iBQAAAAAAAMCJAH0AAUAAAKKArsAAACMAooCuwAAAd8AMQECAAAAAAYAAAAAAAAAAAAAABAAAAAAAAAAAAAAACoyMSoAAOAA4AADt/8WAGQDtwDqAAAAAAAAAAAAAAOEAADgAAADAAAAAQADAAEAAAAMAAQAIAAAAAQABAABAADgAP//AADgAP//IAAAAQAAAAAAAQAAAAAQAAAAAABfDzz1AAAD6AAAAACeC34nAAAAAJ4LficAAP8WD/8DtwAAABEAAAAAAAAAAAABAAADt/8WAAD//wAAAAAAAAOEAAAAAAAAAAAAAAAAAAAAAQAAAAAAAFAAAAEAAAAAABQA9gABAAAAAAAAABAAAAABAAAAAAABACQAEAABAAAAAAACAAcANAABAAAAAAADAAgAOwABAAAAAAAEACQAQwABAAAAAAAFAAwAZwABAAAAAAAGAAAAcwABAAAAAAAHAAcAcwABAAAAAAAIAAcAegABAAAAAAAJAAcAgQADAAEECQAAACAAiAADAAEECQABAEgAqAADAAEECQACAA4A8AADAAEECQADABAA/gADAAEECQAEAEgBDgADAAEECQAFABgBVgADAAEECQAGAAABbgADAAEECQAHAA4BbgADAAEECQAIAA4BfAADAAEECQAJAA4Bik9yaWdpbmFsIGxpY2VuY2VTRE9JUU4rSGVsdmV0aWNhTmV1ZS1IZWF2eS1PVi1HSUdVWkFVbmtub3dudW5pcXVlSURTRE9JUU4rSGVsdmV0aWNhTmV1ZS1IZWF2eS1PVi1HSUdVWkFWZXJzaW9uIDAuMTFVbmtub3duVW5rbm93blVua25vd24ATwByAGkAZwBpAG4AYQBsACAAbABpAGMAZQBuAGMAZQBTAEQATwBJAFEATgArAEgAZQBsAHYAZQB0AGkAYwBhAE4AZQB1AGUALQBIAGUAYQB2AHkALQBPAFYALQBHAEkARwBVAFoAQQBVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABTAEQATwBJAFEATgArAEgAZQBsAHYAZQB0AGkAYwBhAE4AZQB1AGUALQBIAGUAYQB2AHkALQBPAFYALQBHAEkARwBVAFoAQQBWAGUAcgBzAGkAbwBuACAAMAAuADEAMQBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= PZ-Beilage-ApBetrO_2012_21.pdf
downloadable font: font load failed (font-family: "g_font_98" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIDNVseoAAACcAAAB0U9TLzIEjypwAAACcAAAAGBjbWFwAAvgMwAAAtAAAAAsaGVhZKsnUAkAAAL8AAAANmhoZWEDugKaAAADNAAAACRobXR4AAAAAAAAA1gAAAAEbWF4cAABUAAAAANcAAAABm5hbWUlFWqxAAADZAAAAo5wb3N0AAMAAAAABfQAAAAgAQAEAgABAQElU0RPSVFOK0hlbHZldGljYU5ldWUtSGVhdnktT1YtR0lHVVpBAAEBAUb4G/gciwwe+B0B+B4EHQAAoZsN+z37fvrc+ksFHQAAAWIPHQAAAWMRHQAAAAAdAAAAABL4HwwVHQAAAYcMJR0AAAGJDCQABgEBBg6lqsLfQWRvYmVJZGVudGl0eUNvcHlyaWdodCBcKGNcKSAxOTg4LCAxOTkwLCAxOTkzIEFkb2JlIFN5c3RlbXMgSW5jb3Jwb3JhdGVkLiAgQWxsIFJpZ2h0cyBSZXNlcnZlZC5IZWx2ZXRpY2EgaXMgYSB0cmFkZW1hcmsgb2YgTGlub3R5cGUtSGVsbCBBRyBhbmQvb3IgaXRzIHN1YnNpZGlhcmllcy5IZWF2eS9PcmlnRm9udFR5cGUgL1R5cGUxIGRlZkhlbHZldGljYU5ldWUtSGVhdnktT1YtR0lHVVpBAAAAAAABAQEg90b3+QHT9/kD0/f5FSjaO+7u29vu7jvaKCg8PCgeDgAAAAEBARAdAAAAMx0AAAGdEvggDCZ8mvlemvtmmvc3lAb3oZTWlPy0kwd6nPlenPtqlwj3pZLvkvzplwn3JAr3PguMDA74iBQAAAAAAAMCJAH0AAUAAAKKArsAAACMAooCuwAAAd8AMQECAAAAAAYAAAAAAAAAAAAAABAAAAAAAAAAAAAAACoyMSoAAOAA4AADt/8WAGQDtwDqAAAAAAAAAAAAAAOEAADgAAADAAAAAQADAAEAAAAMAAQAIAAAAAQABAABAADgAP//AADgAP//IAAAAQAAAAAAAQAAAAAQAAAAAABfDzz1AAAD6AAAAACeC34nAAAAAJ4LficAAP8WD/8DtwAAABEAAAAAAAAAAAABAAADt/8WAAD//wAAAAAAAAOEAAAAAAAAAAAAAAAAAAAAAQAAAAAAAFAAAAEAAAAAABQA9gABAAAAAAAAABAAAAABAAAAAAABACQAEAABAAAAAAACAAcANAABAAAAAAADAAgAOwABAAAAAAAEACQAQwABAAAAAAAFAAwAZwABAAAAAAAGAAAAcwABAAAAAAAHAAcAcwABAAAAAAAIAAcAegABAAAAAAAJAAcAgQADAAEECQAAACAAiAADAAEECQABAEgAqAADAAEECQACAA4A8AADAAEECQADABAA/gADAAEECQAEAEgBDgADAAEECQAFABgBVgADAAEECQAGAAABbgADAAEECQAHAA4BbgADAAEECQAIAA4BfAADAAEECQAJAA4Bik9yaWdpbmFsIGxpY2VuY2VTRE9JUU4rSGVsdmV0aWNhTmV1ZS1IZWF2eS1PVi1HSUdVWkFVbmtub3dudW5pcXVlSURTRE9JUU4rSGVsdmV0aWNhTmV1ZS1IZWF2eS1PVi1HSUdVWkFWZXJzaW9uIDAuMTFVbmtub3duVW5rbm93blVua25vd24ATwByAGkAZwBpAG4AYQBsACAAbABpAGMAZQBuAGMAZQBTAEQATwBJAFEATgArAEgAZQBsAHYAZQB0AGkAYwBhAE4AZQB1AGUALQBIAGUAYQB2AHkALQBPAFYALQBHAEkARwBVAFoAQQBVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABTAEQATwBJAFEATgArAEgAZQBsAHYAZQB0AGkAYwBhAE4AZQB1AGUALQBIAGUAYQB2AHkALQBPAFYALQBHAEkARwBVAFoAQQBWAGUAcgBzAGkAbwBuACAAMAAuADEAMQBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= PZ-Beilage-ApBetrO_2012_21.pdf
</pre>

**Comment by timvandermeij** [comment] 2015-07-12 12:49
The sanitizer errors are now gone for me, but the missing characters remain.

**Comment by brendandahl** [comment] 2015-12-04 00:48
I don't see any sanitizer errors anymore and it appears all the missing letters are better. Can someone else confirm?

**Comment by timvandermeij** [comment] 2015-12-04 22:56
@brendandahl The characters on page 11 are still missing for me on Windows 10 x64. It still looks like https://github.com/mozilla/pdf.js/issues/3120#issuecomment-69503187, even with the most recent development add-on.

**Comment by Snuffleupagus** [comment] 2015-12-04 23:04
> The characters on page 11 are still missing for me on Windows 10 x64.

Strange, WFM with: PDF.js `1.3.56`, Firefox Nightly 45 (buildID: 20151204030208) with HWA on, and Windows 7 (64-bit).

![page11](https://cloud.githubusercontent.com/assets/2692120/11603637/ab0123e8-9ae3-11e5-873d-8c742580f78a.png)

**Comment by fkaelberer** [comment] 2015-12-05 15:45
So the missing letters seem to depend on the browser, no matter which pdf.js version or OS is used.
From https://github.com/mozilla/pdf.js/issues/3120#issuecomment-68639145 we know that the bug appeared in Firefox 35 or 36 and recent tests show that it disappeared again in Firefox 43 or 44. 
Google Chrome 39 and 47 is also affected (Windows and Linux), but IE11 works.

Besides the missing letters, text selection is also not correct, there are too many word breaks. If I double click on "Apothekenbetriebsordnung" (in the header of page 11), then only a part of the word is selected. In Sumatra or Acrobat, text selection works as expected.

**Comment by NtH0** [comment] 2017-09-06 09:49
> disappeared again in Firefox 43 or 44

FYI: missing chars are still an issue in Firefox 52.3.0 ESR, Linux amd64.

**Comment by timvandermeij** [comment] 2020-06-07 11:36
Closing since the performance problems have been solved and the characters are no longer missing.

**Closed by timvandermeij** 2020-06-07 11:36 UTC
Labels: 2-performance, 4-font-conversion
