### ISSUE TITLE
PDFJS causes Chrome to go into infinite loop painting which causes Chrome to hang

### ISSUE THREAD

**Issue by sai571** [mozilla/pdf.js#10858] opened 2019-05-25 01:55 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 74.0.3729.131
- Operating system and its version: Mac OS Sierra 10.12.6
- PDF.js version: 1.6.210
- pdfjsBuild: 4ce2356
- Is a browser extension: No

Steps to reproduce the problem:
1.  Open a PDF file that's generated out of a DOCX file with tabular content
2. Keep the viewer application open for 2 minutes after scrolling through the pages.

What is the expected behavior? (add screenshot)
The CPU of the machine should not spike. The browser should be responsive.

What went wrong? (add screenshot)
Chrome browser hangs

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-05-25 05:51
> Attach (recommended) or Link to PDF file here:

Without this information the issue will be closed as INVALID, since there's unfortunately no actionable information provided here.

> PDF.js version: 1.6.210

That version is *many* years old and is thus no longer supported, please make sure to always use the latest release as found at https://github.com/mozilla/pdf.js/releases

**Comment by sai571** [comment] 2019-05-28 22:33
Hi, I've attached the profiling information I've gathered from Chrome browser. Can you check if that helps?

Basically we're seeing an infinite loop of Recalculate Style, Update Layout and Composite step inside the Performance profiling step. Do you know what might be causing it? It's only happening when the PDFJS Viewer is being used.


[Profile-20190528T110535.zip](https://github.com/mozilla/pdf.js/files/3229931/Profile-20190528T110535.zip)

**Comment by Snuffleupagus** [comment] 2019-05-29 21:41
Without *either* of the points mentioned in https://github.com/mozilla/pdf.js/issues/10858#issuecomment-495861277 addressed, I don't think that there's much value in re-opening this unfortunately (a profile is of limited use without a way to reproduce the problem).

**Comment by timvandermeij** [comment] 2019-05-29 21:43
I thought the actual file was provided along with the profile, but I misread it. Yes, those points need to be addressed first before we can investigate.

**Closed by timvandermeij** 2019-05-29 21:43 UTC
Labels: 1-viewer, 4-chrome-specific
