### ISSUE TITLE
Rendered text is corrupted on Windows:chrome/edge

### ISSUE THREAD

**Issue by achanizbekov** [mozilla/pdf.js#15962] opened 2023-01-25 14:03 UTC
On google chrome or edge browsers on windows machine the render text of pdf is missing pixels and as a result in some cases some letters/digits are not readable.

In Firefox of windows is also ok.

Firefox 108.0.1 (64-Bit)-> **OK**
Firefox 109.0 (64-Bit) -> **OK**
Chrome Version 109.0.5414.75 -> **NOK**
Chrome Version 109.0.5414.120 -> **NOK**

There is no issue on Ubuntu in chrom or firefox.
The original pdf is for sure not corupted. 

Pdfinfo: 
![image](https://user-images.githubusercontent.com/70684571/214583556-9e1e642f-8f12-487a-ab27-99df1579e1d5.png)

Coruption example:
![photo_2023-01-25_14-51-08](https://user-images.githubusercontent.com/70684571/214582444-d99b412a-82b0-49b1-a621-520e0b8ebc66.png)

**Comment by Snuffleupagus** [comment] 2023-01-25 14:14
Duplicate of #14641

*For future reference:* Note that the "Attach (recommended) or Link to PDF file here:"-part of the ISSUE_TEMPLATE is always required in order for any issue to be actionable/valid.

**Closed by Snuffleupagus** 2023-01-25 14:14 UTC
