### ISSUE TITLE
Choppy Text PDFJS

### ISSUE THREAD

**Issue by Self-TT** [mozilla/pdf.js#16060] opened 2023-02-15 14:36 UTC
Unable to attach file due to NDA Reasons. However, I have a screenshot and looking for guidance

![image](https://user-images.githubusercontent.com/58154752/219055900-53953955-91a9-4ff2-b056-a1f9a8e46d0a.png)

As far as I am aware, there is one PDF within our system that sometimes loses lines within the characters. Such as the image above. Similar to taking an eraser and passing it through each character randomly. Unfortunately, our project solution would have started with pdf.js version 1.6.52. Would anyone have an idea what may be the cause of rectifying this without creating an entire upgrade to the current version?

Configuration:
- Web browser and its version: As far as reports go from testers: All Browsers and their latest versions
- Operating system and its version: As far as reports go from testers: Windows 7 to 11
- PDF.js version: 1.6.52
- Is a browser extension: No

What is the expected behavior? (add screenshot)
Words within the pdf canvas render to be fully visible
![image](https://user-images.githubusercontent.com/58154752/219057395-53a23d34-9481-4bda-9414-cfb5a089b421.png)

What went wrong? (add screenshot)
Words are being chopped
![image](https://user-images.githubusercontent.com/58154752/219055900-53953955-91a9-4ff2-b056-a1f9a8e46d0a.png)

I'm just seeking any potential ideas/solutions I can try without upgrading as that would be a huge time-consuming task development wise. Though if it comes down to it I will.

**Comment by Snuffleupagus** [comment] 2023-02-15 16:05
> However, I have a screenshot and looking for guidance

With nothing more than a screen-shot, I'm guessing that this is a duplicate of e.g. issue #14641 (which contains links to Chromium bug reports). Basically this a bug *in the browser*, which affects particular hardware/software/setting combinations as follows:
 - Certain (built-in) Intel-based graphics cards.
 - Chromium-based browsers, e.g. Google Chrome or Microsoft Edge.
 - Hardware acceleration being enabled in the browser.

> PDF.js version: 1.6.52
> [...]
> I'm just seeking any potential ideas/solutions I can try without upgrading as that would be a huge time-consuming task development wise. Though if it comes down to it I will.

Please note that that version was not an official release, as found at https://github.com/mozilla/pdf.js/releases, and in any case it's well *over six years old* so you really ought to update anyway, (Since support is mostly handled by unpaid volunteers, such as myself, we can only support the latest release.)

**Closed by Snuffleupagus** 2023-02-15 16:05 UTC
