### ISSUE TITLE
pdf.worker.js:41568 Refused to get unsafe header "Accept-Ranges"

### ISSUE THREAD

**Issue by HWliao** [mozilla/pdf.js#7414] opened 2016-06-15 02:49 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2016-06-15 08:11
Since the issue template is completely empty, it's difficult to know what the problem is from only a heading. However, it sounds like it might be a CORS issue, so please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr.

Closing as answered. (And if you need further help, please ensure that you provide a lot more information than this.)

**Closed by Snuffleupagus** 2016-06-15 08:11 UTC

**Comment by gochinj** [comment] 2016-10-02 01:19
Getting same error.  

I am uploading a PDF. How it was originally created is unknown, but assuming Adobe Acrobat.  Nothing in my scenario involves HTTP.  This error occurs when using a ["data uri"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)
