### ISSUE TITLE
PDF Viewer Has a Black/Grey Overlap on Rendered File (Firefox only)

### ISSUE THREAD

**Issue by smajid25** [mozilla/pdf.js#8022] opened 2017-02-03 15:01 UTC
Link to PDF file (or attach file here):
[February Collision Generic PC R2-1.pdf](https://github.com/mozilla/pdf.js/files/750774/February.Collision.Generic.PC.R2-1.pdf)

*****Note:  Issue only appears on the first page of the documents ******
Configuration:
- Web browser and its version: FireFox latest version
- Operating system and its version: Windows 10 OS
- PDF.js version: Current Stable version
- Is an extension: No

Steps to reproduce the problem:
1. Use pdf.js and place link inside source
2. Open with all browsers
3. Problem will be seen in Firefox only and appear normal in IE and Firefox 

What is the expected behavior? (add screenshot)
![normalbackground](https://cloud.githubusercontent.com/assets/14893571/22595951/87bf80f0-e9f7-11e6-8106-be63f322bd07.JPG)

What went wrong? (add screenshot)
![blackbackground](https://cloud.githubusercontent.com/assets/14893571/22595924/6b884dfe-e9f7-11e6-91c5-5973fd74f589.JPG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment] 2017-02-03 17:24
Unable to reproduce on Mac OS

**Comment by SamyCookie** [comment] 2017-02-03 17:34
Same on Linux Debian Jessie and testing: not reproductible.

**Comment by yurydelendik** [comment] 2017-02-03 17:35
@smajid25  can you paste graphics section from about:support ?

**Comment by smajid25** [comment] 2017-02-03 17:49
What do you mean by graphics section from about:support?
I haven't tested this on Mac OS yet, but when using this link below the problem should be prevalent. Open with Firefox on Windows 10 OS:

https://s3.amazonaws.com/VCUSA/WPP/assets+/MarketingAssets/January%20Collision%20Generic%20PC%20R1-3.pdf

**Comment by smajid25** [comment] 2017-02-03 17:50
When using Firefox default pdf viewer it is also prevalent like the link I have provided abov

**Comment by yurydelendik** [comment] 2017-02-03 19:49
Sounds like regression from https://bugzilla.mozilla.org/show_bug.cgi?id=1303534 (which fixes #7556)

**Comment by Snuffleupagus** [comment] 2017-02-03 20:14
Running [mozregression](http://mozilla.github.io/mozregression/) on Windows 7 with the PDF file from issue #8019 (i.e. https://github.com/mozilla/pdf.js/files/748704/R9450_5_2_jersey.pdf), I got the following regression range: https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=4f54551cf526994ec2749bb3f39623369c423d2f&tochange=5a793218e7abe53a07a656fe0b9f330d5fc0f83f.
This thus points to https://bugzilla.mozilla.org/show_bug.cgi?id=1303534, which fixed yet another canvas regression.

I've not yet had time to bisect the PDF file in *this* issue (but it'd venture a guess that it's the same problem), and neither had time to try and create a reduced-test case for filing an upstream bug yet.

**Comment by smajid25** [comment] 2017-02-03 20:30
Hmmmm so the first link says it will work right if HWA (Hardware Acceleration?) is disabled and from what I understand, from the second link, this is an upstream issue. So I am just curious as to what is the root cause of this issue and can this issue be resolved?

**Comment by Snuffleupagus** [comment] 2017-02-03 20:56
I've just filed https://bugzilla.mozilla.org/show_bug.cgi?id=1336572 for the PDF file from issue #8019, i.e. https://github.com/mozilla/pdf.js/files/748704/R9450_5_2_jersey.pdf.

However, for the PDF file in *this* issue it seems that there's multiple regression points, since it has progressively worse over time. I'm not really sure yet how to bisect/report that upstream.

**Comment by Snuffleupagus** [comment] 2017-02-03 21:53
I've filed the following two bugs:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1336572, for issue #8019.

- https://bugzilla.mozilla.org/show_bug.cgi?id=1336591, for *this* issue.
Note that in this case, there's actually *two* different regression points.

**Comment by smajid25** [comment] 2017-02-06 14:02
Just to confirm, this issue involves the Firefox browser and not the PDF.js, right?

**Comment by yurydelendik** [comment] 2017-02-06 14:14
> Just to confirm, this issue involves the Firefox browser and not the PDF.js, right?

Correct, and only on windows with hwa enabled.

**Comment by smajid25** [comment] 2017-02-06 14:20
Ok great, and is there a specific reason why this issue only applies to certain PDFs, because it only appears on 2 of the 5 PDFs that I tested. In other words what could I do to the PDFs I create/generate to avoid this issue from occurring in the first place?

**Comment by yurydelendik** [comment] 2017-02-06 14:21
>  In other words what could I do to the PDFs I create/generate to avoid this issue from occurring in the first place?

Based on upstream bug it's related to the specific sequence of clip() and restore() operations.

**Comment by smajid25** [comment] 2017-02-06 14:35
I'm assuming that these two methods are involved in the rendering of the PDF's? I guess there's not much I can do on my end other than using less images in the PDF's I generate or avoid one's that trigger this.

**Comment by timvandermeij** [comment] 2021-04-25 15:48
Is this still a problem on Windows. It works fine for me on Linux and given the age of the issue I'm wondering if this perhaps already got fixed upstream. @Snuffleupagus Could you perhaps check this on Windows?

**Comment by Snuffleupagus** [comment] 2021-04-25 15:50
> Could you perhaps check this on Windows?

Unfortunately this is *still* just as broken as before, which isn't that surprising given that both of the bugs mentioned in https://github.com/mozilla/pdf.js/issues/8022#issuecomment-277372590 are not yet fixed :-(

**Comment by Snuffleupagus** [comment] 2021-12-06 14:18
Fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1336591

**Closed by Snuffleupagus** 2021-12-06 14:18 UTC
Labels: 3-regression, 4-os-windows, 3-upstream, 4-hwa-on, 4-firefox-specific
