### ISSUE TITLE
ShadingType 1 is unsupported

### ISSUE THREAD

**Issue by DylanTim** [mozilla/pdf.js#11971] opened 2020-06-05 11:01 UTC
[test.pdf](https://github.com/mozilla/pdf.js/files/4735578/test.pdf)

**Configuration:**
- Web browser and its version: Firefox 77.0.1 (64-Bit)
- Operating system and its version: Windows 10 Pro v.1909
- PDF.js version: 2.5.95
- Is a browser extension: No, built in to Firefox as standart PDF-viewer

**Steps to reproduce the problem:**
1. create the pdf by saving the following html code to a file and printing the output to a pdf enabling background graphics:
```
<!DOCTYPE html>

<html>

<head>
    <style>
        body {

            background: repeating-linear-gradient(44deg,
                    HSLA(174, 41%, 46%, 0.5),
                    HSLA(174, 41%, 46%, 0.5) 10px,
                    HSLA(174, 37%, 34%, 0.5) 10px,
                    HSLA(174, 37%, 34%, 0.5) 20px);
            height: 100vh;
            width: 100vw;
        }

    </style>
</head>

<body>
</body>

</html>

```
(should result in a similar file to this one)
[test.pdf](https://github.com/mozilla/pdf.js/files/4735578/test.pdf)
2. compare to opening it with chrome-based browsers

**Expected behavior: (viewed in Vivaldi Browser --> Chrome-based)**
![image](https://user-images.githubusercontent.com/59578534/83868465-330ace80-a72b-11ea-8f68-633cbbd9027a.png)

**Resulted behavior: (viewed in Firefox)**
![image](https://user-images.githubusercontent.com/59578534/83868508-46b63500-a72b-11ea-9bf1-6bc7b656ac67.png)
console:
![image](https://user-images.githubusercontent.com/59578534/83868696-a44a8180-a72b-11ea-92fe-94ac5168f279.png)

**Comment by Snuffleupagus** [comment] 2020-06-05 11:13
Looks, for all intents and purposes, like a duplicate of issue #5046 (based on the actual errors/PDF structure).

**Comment by DylanTim** [comment] 2020-06-05 14:08
> Looks, for all intents and purposes, like a duplicate of issue #5046 (based on the actual errors/PDF structure).

I've seen this issue before posting mine, but I was convinced, that this is something different.
The issue you mentioned gives the error `Warning: Error: Unknown PatternType: 1`, while mine is `Warning: FormatError: Unsupported ShadingType: 1`.

Nevertheless, even if it is related, the other issue was opened 16 years ago, pretty upsetting that this error still exists. 
Why is that?

**Comment by Snuffleupagus** [comment] 2020-06-05 14:30
> The issue you mentioned gives the error `Warning: Error: Unknown PatternType: 1`, while mine is `Warning: FormatError: Unsupported ShadingType: 1`.

The error messages has been updates since issue #5046 was opened, which should explain the differences.

>  the other issue was opened 16 years ago,

Note that it's opened in 2014, so rather *six* years ago.

---

Please note that it's common-place in all bug trackers to close duplicates, regardless if the original issue is resolved or not, in order to ensure that relevant discussion happens in *one place*.
Doing so does not constitute any judgement of the importance of the issue itself, it's simply done to keep the number of open issues more manageable.

> [...] pretty upsetting that this error still exists.
> Why is that?

Please keep in mind that this is an open-source project, with most people contributing in their *spare time*. (And the feature in question here may not be entirely straightforward to implement, and isn't that commonly used either.)

**Comment by timvandermeij** [comment] 2020-06-05 21:56
Closing since this is in fact a duplicate.

**Closed by timvandermeij** 2020-06-05 21:56 UTC
