### ISSUE TITLE
Japanease multi-byte blank character is garbled in IE browser 

### ISSUE THREAD

**Issue by TatsuyaNakaguchi** [mozilla/pdf.js#7033] opened 2016-02-26 12:38 UTC
Hi all,

I have one character problem using IE browser. Japanease multi-byte blank (UTF8  E38080) is garbled to unknown X character. This problem does not reproduce on Chrome and Safari.
Please look at the attached images.

Image1 IE problem
![ie](https://cloud.githubusercontent.com/assets/17495095/13352506/0200ed52-dcd1-11e5-8471-6f372ca62824.png)

Image2 Chrome OK
![chrome](https://cloud.githubusercontent.com/assets/17495095/13352528/2a154a40-dcd1-11e5-96f4-313809eaab40.jpg)

Original PDF
[sample.pdf](https://github.com/mozilla/pdf.js/files/148187/sample.pdf)

This problem does not related to WebServer(IIS/Apache)
My pdf.js version as follows.
PDFJS.version = '1.2.109';
PDFJS.build = '875588d';

Could you help us, if you have something information?
Thanks,

Tatsuya

**Comment by Snuffleupagus** [comment] 2016-02-26 12:52
Closing as duplicate of issue #4836.

**Closed by Snuffleupagus** 2016-02-26 12:52 UTC

**Comment by TatsuyaNakaguchi** [comment] 2016-02-29 04:11
We confirmed the #4836 and solved this problem.
Thanks a lot
