### ISSUE TITLE
URLs not clickable in PowerPoint-generated PDFs

### ISSUE THREAD

**Issue by gfairchild** [mozilla/pdf.js#6861] opened 2016-01-12 20:39 UTC
First off, I'm using FF 43.0.4 on OS X 10.11.2.

I have a PDF available at http://bsvgateway.org/flu/ that has several links contained in it. This PDF was exported from PowerPoint for Mac 2011. We explicitly made the hyperlinks (select text, Insert -> Hyperlink). Preview, Acrobat, and Safari all recognize the links. FF's built-in PDF reader (this project), however, does not recognize the links and seems to think they're just blue text. What's going on here?

**Comment by Snuffleupagus** [comment] 2016-01-12 20:50
Unfortunately the PDF file does not actually contain any links, so it would appear that the PDF generator in question isn't able to create proper links. (Other PDF viewers may have an option to create links from things that look like URLs.)

Closing as duplicate of issue #3172, which is already tracking this.

**Closed by Snuffleupagus** 2016-01-12 20:50 UTC

**Comment by gfairchild** [comment] 2016-01-12 20:51
Ah, gotcha. Must be some issue with PowerPoint then. Thanks!
