### ISSUE TITLE
[Feature]: Translate PDFs like Firefox does for Web sites

### ISSUE THREAD

**Issue by paulmenzel** [mozilla/pdf.js#18391] opened 2024-07-05 06:27 UTC
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

It’d be great, if PDF documents could be translated like Web sites can be translated now in Firefox.

### Other PDF viewers

Evince does not support this. No idea about other viewers.

**Comment by marco-c** [comment] 2024-07-08 11:11
This would be an interesting feature, but it is really hard to implement because it requires relaying out the contents of the PDF (as the translated text will have completely different size than the original text). The implementation is kind of similar to what would be required for https://connect.mozilla.org/t5/ideas/reader-mode-for-pdf-files/idi-p/9908.

Starting from Firefox 128, we will support select translation though, so you can at least select specific sentences or paragraphs in PDFs and translate them!

**Comment by Snuffleupagus** [comment] 2024-10-30 09:15
Closing as duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1917620 (to avoid tracking the same issue in multiple places).

**Closed by Snuffleupagus** 2024-10-30 09:15 UTC
Labels: feature
