### ISSUE TITLE
Some PDF headers are not a

### ISSUE THREAD

**Issue by NileshMoradiya** [mozilla/pdf.js#6755] opened 2015-12-15 09:45 UTC
Hi all,
Below are two files one of which is appear properly but one of it not.
**~~1. Not working case~~**
[Not Working File.pdf](https://github.com/mozilla/pdf.js/files/62247/Not.Working.File.pdf)
This file is not viewing properly, it's header get cut.

Here is a snap of it's header
![not working](https://cloud.githubusercontent.com/assets/4757071/11807154/0a847916-a33e-11e5-97be-b73d4890bc84.png)

**2. Working case**
[Working File.pdf](https://github.com/mozilla/pdf.js/files/62248/Working.File.pdf)
This file is viewing properly.

Here is a snap of it's header
![working](https://cloud.githubusercontent.com/assets/4757071/11807156/0fa03b1a-a33e-11e5-9a1d-5c3a004b2b84.png)

As gone through some debugging :computer: found that 1st (~~not working~~) file has some meta info **"PDF 72155bf703fed64ab28f3129a71d6c2e [1.5 Adobe PDF Library 10.0 / Acrobat PDFMaker 10.1 for PowerPoint] (PDF.js: 1.3.78)"**
and 2nd (working) fil has meta info **"PDF 774a9697a5d95e4ca8bdbd5ad1ff76d4 [1.3 Adobe PDF Library 15.0 / Adobe InDesign CC 2015 (Windows)] (PDF.js: 1.3.78)"**.

Is there any resolution for that ?

Thanks & Regards :blush:.

**Comment by Snuffleupagus** [comment] 2015-12-15 11:01
Closing as duplicate of issue #6737.

**Closed by Snuffleupagus** 2015-12-15 11:01 UTC

**Comment by Snuffleupagus** [comment] 2015-12-15 14:27
As outlined in https://github.com/mozilla/pdf.js/issues/6737#issuecomment-162909902, this issue depends on the work-in-progress pull request #6606.
