### ISSUE TITLE
Image gets rendered blurry and unreadable

### ISSUE THREAD

**Issue by fosple** [mozilla/pdf.js#9463] opened 2018-02-09 10:15 UTC
Attach (recommended) or Link to PDF file here:
[150007.pdf](https://github.com/mozilla/pdf.js/files/1710555/150007.pdf)

Configuration:
- Web browser and its version: Chrome 63.0.3239.132 
- Operating system and its version: MacOS 10.13.2
- PDF.js version: pdfjs 1.9.426

Steps to reproduce the problem:
1. Open PDF

What is the expected behavior?
![150007_blurry_image](https://user-images.githubusercontent.com/4522947/36022716-4fdd1708-0d8a-11e8-8e12-17f659ee6106.png)

What went wrong? (add screenshot)
![150007_blurry_image](https://user-images.githubusercontent.com/4522947/36022716-4fdd1708-0d8a-11e8-8e12-17f659ee6106.png)

**Comment by Snuffleupagus** [comment] 2018-02-09 10:23
Closing as duplicate of e.g. issue #6496.

**Closed by Snuffleupagus** 2018-02-09 10:23 UTC
