### ISSUE TITLE
<input type = 'file'> html tag related

### ISSUE THREAD

**Issue by youlook** [mozilla/pdf.js#9293] opened 2017-12-19 09:01 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: windows 10
- PDF.js version: 1.9.426

Steps to reproduce the problem:

1. I am having trouble adding a file upload function to my company project using pdf.js.
Adding the <input type = 'file'> tag triggers the final file selection event.

2. The problematic function is "webViewerFileInputChange". It is in the app.js file.

**Comment by Snuffleupagus** [comment] 2017-12-19 10:09
Based on the limited information provided, I'm guessing that this is a duplicate of issue #8915; hence closing as such.

> I am having trouble adding a file upload function to my company project using pdf.js.

*For future reference:* As requested in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), for issues with custom implementation of PDF.js you need to provide a complete (and runnable) example in order for the issue to be valid.

**Closed by Snuffleupagus** 2017-12-19 10:09 UTC
