### ISSUE TITLE
Thumbnails are displayed blank for XFA forms

### ISSUE THREAD

**Issue by SushmaRaghu** [mozilla/pdf.js#16948] opened 2023-09-15 07:23 UTC
Attach (recommended) or Link to PDF file here:
[purchase_order.pdf](https://github.com/mozilla/pdf.js/files/12616735/purchase_order.pdf)

Configuration:
- Web browser and its version: Firefox (latest)
- Operating system and its version: Windows
- PDF.js version: 3.11.58
- Is a browser extension:

Steps to reproduce the problem:
1. Open the attached PDF form which is a pure XFA Form. 
2. Click on thumbnail view. It is displayed blank. 

What is the expected behavior? (add screenshot)
Thumbnails should have content

What went wrong? (add screenshot)
<img width="533" alt="xfa thumbnail issue" src="https://github.com/mozilla/pdf.js/assets/5555016/e0c85981-fe54-4316-9f3d-251ba59bd87a">

Is this an expected behavior ? 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-09-15 07:27
Duplicate of [bug 1722983](https://bugzilla.mozilla.org/show_bug.cgi?id=1722983).

**Closed by Snuffleupagus** 2023-09-15 07:27 UTC
