### ISSUE TITLE
Don't show header and footer when we click on the print button

### ISSUE THREAD

**Issue by rabat22** [mozilla/pdf.js#16624] opened 2023-06-30 12:52 UTC
Hi,

I use pdfjs library for my printing. When i click on the print button, i have visualization of my print. In each of my page, I have header and footer who appair. I can remove it from my browser but i want do it in code. I try to put text of my header and footer in white colour for don't show it but i can't find how to do it in code.

I tried to change viewer.css and nothing work. The file viewer.js is complicated to do changement.

Can you help me pls ?

![header](https://github.com/mozilla/pdf.js/assets/25502578/32fef73c-1985-48d2-91e5-d250bf6ff71c)
![footer](https://github.com/mozilla/pdf.js/assets/25502578/32a3d0b0-82d6-40b9-bc07-f9acaf9f71dc)

**Comment by rabat22** [comment] 2023-06-30 12:56
![header](https://github.com/mozilla/pdf.js/assets/25502578/69dc62fc-059a-4051-bcc0-1aff77a93046)

![footer](https://github.com/mozilla/pdf.js/assets/25502578/949ab999-1f1b-4781-ae0f-0a6745cd42f8)

**Comment by Snuffleupagus** [comment] 2023-06-30 13:11
Duplicate of #11071

**Closed by Snuffleupagus** 2023-06-30 13:11 UTC
