### ISSUE TITLE
Font transparency issue on Firefox

### ISSUE THREAD

**Issue by JordanDaigle** [mozilla/pdf.js#7690] opened 2016-10-04 14:57 UTC
Link to PDF file (or attach file here):
https://drive.google.com/open?id=0BxfzEDjAum-5aGhQUzkyLXA3U3M

Configuration:
- Web browser and its version: Firefox 49.0.1
- Operating system and its version: Windows 7 Pro
- PDF.js version: v1.4.20 (https://github.com/mozilla/pdf.js/releases/tag/v1.4.20)
- Is an extension: I'm using pdf javascript (https://github.com/mozilla/pdf.js/releases/tag/v1.4.20) only

Steps to reproduce the problem:
1.  download the problematic pdf
2.  Try to load it in the pdf.js v1.4.20 on Firefox 49.0.1 (last version of firefox 2016-10-04) with the problematic pdf
3. Compare how it render on firefox vs pdf.js on any other main browser

What is the expected behavior? (add screenshot)

I have a web application that use the library FPDF (https://github.com/Setasign/FPDF) combined with AlphaPDF (http://www.fpdf.org/en/script/script74.php)  to add text over pdf with rgba(255, 0, 0, 0). The we use pdf.js as the viewer of our web application.

What went wrong? (add screenshot)

Everything was working then I dont know if it's because firefox did an update but now pdf.js ignore the font color transparency on Fire fox.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Unfortunatly I don't have any viewer online. (only on my locale machine)

here some images :

example on chrome (that doesnt have the problem)
https://drive.google.com/open?id=0BxfzEDjAum-5LUlIRm9pZXZ1clk

example on firefox that has the problem
https://drive.google.com/open?id=0BxfzEDjAum-5a3Y0TURnSDBSbFE

Console on fireBug : 
https://drive.google.com/open?id=0BxfzEDjAum-5ZDJUaVo3V1ZpTmc

Console on chrome :
https://drive.google.com/open?id=0BxfzEDjAum-5M2FIZ18xSDJ0d0E

**Comment by JanSlabon** [comment] 2016-10-25 06:32
This is a duplicate of #7674.

**Closed** 2016-10-25 08:34 UTC
