### ISSUE TITLE
some computer doesn't randering text in firefox

### ISSUE THREAD

**Issue by vivacewith** [mozilla/pdf.js#5665] opened 2015-01-22 15:23 UTC
https://drive.google.com/file/d/0B3KHRk10beerOElhbDQzNXIzQ1k/view?usp=sharing

here is screenshot

https://drive.google.com/file/d/0B3KHRk10beerZkdEZ29wNzBTZDQ/view?usp=sharing

left is firefox and adobe

**Comment by yurydelendik** [comment] 2015-01-22 18:26
Unable to reproduce on Firefox for Mac OSX:

![screen shot 2015-01-22 at 12 23 03 pm](https://cloud.githubusercontent.com/assets/1523410/5861702/7fbe9c5c-a231-11e4-8cf8-74a1e18011d4.png)

Could you provide more details Firefox and PDF.js version (the latter can be found in the javascript console)? Also can you paste Graphics section from the about:support?

**Comment by vivacewith** [comment] 2015-01-23 01:29
Firefox is the latest version that i can search in google.
and...
the problem is that only a "few" of the computers.

there is a total of 10 computers in my office, but However, the computer that happens is just 2.

**Comment by yurydelendik** [comment] 2015-11-05 15:36
Closing as incomplete. More information needed to re-open the issue, e.g. link to the PDFs and OS version, and Graphics section from the about:support. See also https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md

**Closed by yurydelendik** 2015-11-05 15:36 UTC
Labels: 4-triage-needed
