### ISSUE TITLE
Overlapping Letters in Font fallback

### ISSUE THREAD

**Issue by EdorianDark** [mozilla/pdf.js#15312] opened 2022-08-14 09:00 UTC
Attach (recommended) or Link to PDF file here:
https://www.cse.iitb.ac.in/infolab/Data/Courses/CS632/Papers/Cascades-graefe.pdf

Configuration:
- Web browser and its version:
 103.0.2 (64-bit), Snap 
- Operating system and its version:
  Ubuntu 22.04.1 LTS 
- PDF.js version:
  PDF.js: 2.15.129
- Is a browser extension:
  It is the built in version of Firefox

Steps to reproduce the problem:
1. Open pdf

What is the expected behavior? (Evince, 42.3)
![image](https://user-images.githubusercontent.com/5777938/184529813-3ab4fffc-94c4-48a9-87da-e032f682d4ba.png)

What went wrong? (pdf.js)
![image](https://user-images.githubusercontent.com/5777938/184529823-e08a9cc8-2574-4e19-a02b-f7757a1ad621.png)

Possible duplicate of https://github.com/mozilla/pdf.js/issues/13176

**Comment by Snuffleupagus** [comment] 2022-08-14 09:09
> Possible duplicate of #13176

That looks accurate, since neither document embeds any font-data.

---

Duplicate of #13176

**Closed by Snuffleupagus** 2022-08-14 09:09 UTC

**Comment by hurshprasad** [comment] 2022-10-11 23:24
@Snuffleupagus why is this accurate for a fallback font? 

Is there a way to set the fallback to an opentype font like LiberationSans with out having kerning or tracking issues?
