### ISSUE TITLE
Rendering error in circular text

### ISSUE THREAD

**Issue by jethrogb** [mozilla/pdf.js#7641] opened 2016-09-17 20:23 UTC
*Link to PDF file (or attach file here):* https://people.eecs.berkeley.edu/~rsinha/research/pubs/pldi2016.pdf

*Configuration:*
*- Web browser and its version:* Firefox 48.0
*- Operating system and its version:* Arch Linux with FreeType 2.6.5-2
*- PDF.js version:* Firefox 48.0
*- Is an extension:* No

*Steps to reproduce the problem:*
Some of the lettering in the seal on the top right of the first page looks off.

*What is the expected behavior? (add screenshot)*
![okular](https://cloud.githubusercontent.com/assets/1132307/18610775/9a26cf7c-7cd9-11e6-8255-a0d1201fdb8e.png)
This is what it looks like in Okular on the same system and Firefox on Windows.

*What went wrong? (add screenshot)*
![pdfjs](https://cloud.githubusercontent.com/assets/1132307/18610774/92df71f6-7cd9-11e6-86b6-1a83de21d8fc.png)

Possible dupe of #2594, but I don't see any errors in the PDFs in that issue.

**Comment by Snuffleupagus** [comment] 2016-09-17 21:34
Closing as duplicate of issue #7342.

**Closed by Snuffleupagus** 2016-09-17 21:34 UTC
