### ISSUE TITLE
How to access /AA dictionary of an annotation

### ISSUE THREAD

**Issue by clecap** [mozilla/pdf.js#12275] opened 2020-08-25 07:16 UTC
How would I access the contents of the /AA dictionary of an annotation?

I read somewhere that the additional actions of an annotation are not supported by pdf.js. This is fine (and I am intending to implement a portion of them). However: The promise I get via page.getAnnotations() provide me with no handle to even parse these data and I am not sure if it is indeed necessary to extend the parser, and if yes how, and if no if there is a further function via which I can get the contents of the /AA.

The issue to be repaired here: The documentation does not really help with this... :-(

**Comment by Snuffleupagus** [comment] 2020-08-25 07:40
*Generally speaking:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

> How would I access the contents of the /AA dictionary of an annotation?

You can't, since there's currently no parsing of that entry; this issue is thus (basically) a duplicate of e.g. #9776.

---

Given that all parsing happens in a worker-thread, you cannot pass data as-is to the main-thread (which is where the API is) without first carefully validating it (since all data needs to be clonable) and converting it into a format that makes sense for the display-layer.

**Closed** 2020-08-25 20:06 UTC
