### ISSUE TITLE
Null pointer exception in optional_content_config.js when viewing PDF document

### ISSUE THREAD

**Issue by ypersion1956** [mozilla/pdf.js#13851] opened 2021-08-03 13:01 UTC
The document in question: [doc_image.pdf](https://github.com/mozilla/pdf.js/files/6896539/doc_image.pdf)

Configuration:
- Web browser - Chrome
- Operating system and its version: Windows 10
- PDF.js version: 2.8.335, 2.10.377
- Is a browser extension: no

Expected document rendering:
![image](https://user-images.githubusercontent.com/54116291/127397691-77d8983f-f480-42e9-bd70-d865b8031576.png)

Actual rendering with an error
![image](https://user-images.githubusercontent.com/54116291/127398116-59fc45e9-e961-4fd3-add7-563299d32c65.png)
![image](https://user-images.githubusercontent.com/54116291/127397832-fd524736-e1fd-40e5-a783-7ed025f332eb.png)

**Comment by calixteman** [comment] 2021-08-03 13:06
I can reproduce with Firefox nightly.
@brendandahl, could you have a look ?

**Comment by ypersion1956** [comment] 2021-08-03 14:16
Thank you. When the fix might be available in a released version?

**Comment by Snuffleupagus** [comment] 2021-08-03 14:26
> Thank you. When the fix might be available in a released version?

The patch has neither been reviewed or landed yet, so you'll have to be patient :-)

It will simply be included in the next release, however no exact date for that can be provided (since we don't have a fixed release schedule) and note also that the last release was just nine days ago.
Furthermore, this isn't a recent regression either, since it's been present ever since PR #12095 which landed a year ago.

**Closed** 2021-08-03 21:34 UTC
Labels: 1-core
