### ISSUE TITLE
spaces are not displayed correctly

### ISSUE THREAD

**Issue by lovasoa** [mozilla/pdf.js#5871] opened 2015-03-23 00:43 UTC
http://www.agro-montpellier.fr/sfds/CD/textes/mballo1.pdf

**Comment by Snuffleupagus** [comment] 2015-03-23 10:08
@lovasoa Please explain what you mean with "spaces are not displayed correctly", since the file appears to render exactly the same way in PDF.js (version 1.1.11) and Adobe Reader.

Also, when reporting an issue, please make sure that you read (especially the *first* paragraph): https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.

**Comment by lovasoa** [comment] 2015-03-23 12:33
Hello,
  Sorry for the lack of explanations, I reported this issue late yesterday.
  Here is a screenshot of the issue.
![capture du 2015-03-23 13 28 49](https://cloud.githubusercontent.com/assets/552629/6779878/98e4fc40-d160-11e4-8518-9ef73f930359.png)

  And my operating system is ubuntu:
```
$uname -a
Linux ordophir 3.16.0-31-generic #43-Ubuntu SMP Tue Mar 10 17:37:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

And here is how the pdf is displayed in evince: 
![capture du 2015-03-23 13 32 54](https://cloud.githubusercontent.com/assets/552629/6779961/2f4f52f2-d161-11e4-8d6b-647d8fc24d5b.png)

**Comment by Snuffleupagus** [comment] 2015-03-23 12:48
Based on the provided information, I'm closing this issue as a duplicate of #5256.

**Closed by Snuffleupagus** 2015-03-23 12:48 UTC
Labels: 4-information-requested
