### ISSUE TITLE
Spacing Issue End of Line when Control-F

### ISSUE THREAD

**Issue by alimirzazadeh** [mozilla/pdf.js#11143] opened 2019-09-13 21:17 UTC
Attach (recommended) or Link to PDF file here:
[saturn.pdf](https://github.com/mozilla/pdf.js/files/3611857/saturn.pdf)

Configuration:
- Web browser and its version: Electron JS version 4.1.4
- Operating system and its version: Windows10 64bit
- PDF.js version: 2.0 i think
- Is a browser extension: No

Steps to reproduce the problem:
1.  try control-f and type in the following phrase:
in setting where its flexibility and passivity are best utilized.
No results. Now try removing space between are and best so its arebest. Now the result shows on page 4. This isn't the only PDF, this happens very commonly on many PDFs

What is the expected behavior? Searching the first sentence and result popping up

What went wrong? (add screenshot) No space at the end of the line was detected even though it is there in the PDF. The find function ignored it. Same document works correctly on Adobe Reader for example

**Comment by Snuffleupagus** [comment] 2019-09-13 22:15
Duplicate of e.g. issue #10109 (and probably others).

**Closed** 2019-09-14 13:40 UTC
Labels: 4-text-selection
