### ISSUE TITLE
Blocky/tiling glitch when using pinch-to-zoom in the default viewer (`viewer.html`)

### ISSUE THREAD

**Issue by rdinse** [mozilla/pdf.js#16329] opened 2023-04-20 16:10 UTC
Link to a viewer: https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Safari (default version)
- Operating system and its version: iOS 16.4.1
- PDF.js version: 3.5.141
- Is a browser extension: no

Steps to reproduce the problem:
1. Zoom in and move around

What went wrong?

Blocky glitches appear (see screenshot).

(The screenshot shows a different PDF file, but the same problem occurs in the one linked above.)

![grafik](https://user-images.githubusercontent.com/9957215/233424737-f4c3933f-c929-4e3e-80cb-5c39843174f0.png)

**Comment by Snuffleupagus** [comment] 2023-04-20 16:23
Duplicate of #16155

**Closed by Snuffleupagus** 2023-04-20 16:23 UTC
