### ISSUE TITLE
gulp does not return an error/exit code upon error

### ISSUE THREAD

**Issue by tomrittervg** [mozilla/pdf.js#15374] opened 2022-08-31 16:51 UTC
Steps to reproduce the problem:
1. Something goes wrong when running gulp
2. gulp's exit code is 0

What is the expected behavior?
If there is an error - gulp should return non-zero

I think https://stackoverflow.com/questions/21688613/gulp-returns-0-when-tasks-fail explains the situation better than I can, not knowing gulp at all, but when I was investigating https://github.com/mozilla-services/updatebot/issues/273 I was trying to figure out why we weren't detecting an error, and I am pretty sure it's because gulp isn't giving us an error when it errors.

**Comment by Snuffleupagus** [comment] 2022-08-31 17:48
I cannot help wonder if the situation in https://github.com/mozilla-services/updatebot/issues/273 wasn't a bit "special" though, since the error was caused by an old (and outdated) Node.js version.
In this particular case I don't *believe* that we can actually catch/detect the error in the `gulpfile` code, given that error was in Node.js *itself*. For comparison, if I manually [change the affected line](https://github.com/mozilla/pdf.js/blob/e9bdbe45744a3db68b4728c0b6eb326162c82ef3/gulpfile.js#L229-L230) to something like `throw new Error("test");` instead and then run e.g. `gulp mozcentral` the gulp-task seem to error out as expected.

**Comment by timvandermeij** [comment] 2022-09-03 10:25
Closing since I agree with the above; I also don't see what we could change here given that it seems to work fine if a supported Node.js version is used. Please note that we only support the most recent Node.js LTS version.

**Closed by timvandermeij** 2022-09-03 10:25 UTC
