### ISSUE TITLE
Overlapping Characters

### ISSUE THREAD

**Issue by theety** [mozilla/pdf.js#6426] opened 2015-09-08 07:01 UTC
![screenshot](https://cloud.githubusercontent.com/assets/14107539/9727887/b58d4538-563e-11e5-93ee-9aa4ca78a38d.png)
The pdf at http://www.taishukan.co.jp/kokugo/webkoku/kikanshi/kokugo_100/kokugo_100_46-48.pdf  

In vertical mode, when a punctuation mark comes at beginning or end of a group(a div in the textLayer), there is something goes wrong.   

This seems to fix it:
at line 1409, if vertical, remove unary minus.
```
// src/display/canvas.js
@@ -1406,7 +1406,11 @@
           x += fontDirection * wordSpacing;
           continue;
         } else if (isNum(glyph)) {
-          x += -glyph * fontSize * 0.001;
+          if (vertical) {
+            x += glyph * fontSize * 0.001;
+          } else {
+            x += -glyph * fontSize * 0.001;
+          }
           continue;
         }
```

**Comment by Snuffleupagus** [comment] 2015-09-08 09:51
Closing as duplicate of issue #6387.

**Closed by Snuffleupagus** 2015-09-08 09:51 UTC
