### ISSUE TITLE
Regressions after Firefox 48/49 update on the bots

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#7277] opened 2016-05-01 12:48 UTC
Recently the Linux bot updated Firefox to version 48, which introduced some regressions, but also some improvements. Below is a list of the regressions and improvements I found while going through http://107.21.233.14:8877/252b6dc246e4cae/reftest-analyzer.html#web=eq.log. We probably have to file the regressions upstream in Bugzilla, but we might need to have a better idea about the cause of the issues for that.

Regressed
--------------

- `firefox-bug946506-page1` and `firefox-issue2948-page1` (letters are moved in the rotated text)
- `firefox-intelisa-eq-page21` (italic text is now regular text)
- `firefox-issue2128-page1` (characters not bold anymore)
- `firefox-freeculture-page2` and `firefox-TrueType_without_cmap-page1` (italic characters are shifted to the left too much)
- `firefox-issue918-page1` and `firefox-issue2984-page1` (text looks less clear than before)

Improved
------------

- `firefox-tracemonkey-eq-page11` (gradients are now visible)
- `firefox-mao-page1` (random bold characters are now regular)
- `firefox-bug1011159-page1` (strange white dots are gone)
- `firefox-bug1072164-page1` (grid lines are more clear)

**Comment by Snuffleupagus** [comment] 2016-06-13 15:35
It seems that the update to Firefox 49 fixed some of the issues in the "Regressed" list above, please see the latest test runs in https://github.com/mozilla/pdf.js/pull/3891#issuecomment-225587383: http://107.21.233.14:8877/7b3e2711a547bea/reftest-analyzer.html#web=eq.log.

Unfortunately, it also seems that the update to Firefox 49 regressed some files on both Linux *and* Windows, see e.g. `firefox-bug1199237-page1` in http://107.22.172.223:8877/fa4b3965e742897/reftest-analyzer.html#web=eq.log and http://107.21.233.14:8877/7b3e2711a547bea/reftest-analyzer.html#web=eq.log.

**Comment by timvandermeij** [comment] 2016-06-13 19:31
At least some are indeed fixed, but we need to make sure to report these upstream, or at least make upstream developers aware of this GitHub issue somehow.

**Comment by Snuffleupagus** [comment] 2016-06-13 19:40
@timvandermeij In the meantime, do you think that we should just `makeref` the current state (e.g. in #3891), since it's currently not really meaningful to run the reference tests given all the changes?

**Comment by timvandermeij** [comment] 2016-06-14 21:11
Generally things look better (I haven't had time to check all of them), so I'm fine with `makeref`. It doesn't make sense to keep the current reference images because the tests will then fail for all other PRs too. The most important part is that we track the regression here (with the links above) and let upstream know about it.

**Comment by timvandermeij** [comment] 2016-09-11 19:58
Given that some of the issues here were already fixed and recently a couple of patches landed upstream, I'm not sure if there is anything else we need to do here. @Snuffleupagus What do you think?

**Comment by Snuffleupagus** [comment] 2016-09-11 20:09
Let's just close it for now.
We can always open new issues if we find more regressions, the important part is that we remember to *always* file upstream bugs if we actually want them fixed :-)

**Closed by Snuffleupagus** 2016-09-11 20:09 UTC
Labels: 1-test, 3-regression, 3-upstream
