### ISSUE TITLE
PDF.js intermittently causes black boxes/glitches on Chrome

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#7497] opened 2016-07-20 19:32 UTC
Link to PDF file (or attach file here):
No reliable repro case :( - I used to see this issue consistently with Chrome 49

Configuration:
- Web browser and its version: Various versions of Chrome 51+, a specific repro happened on 51.0.2704.106 (64-bit)
- Operating system and its version: Both Mac & Windows, a specific repro happened on 10.10.4 (14E46) with Intel HD Graphics 6000 1536 MB
- PDF.js version: 1.5.336 from https://github.com/mozilla/pdfjs-dist
- Is an extension: No

Steps to reproduce the problem:
No reliable repro case - I used to see this issue consistently with Chrome 49

What is the expected behavior?
PDF renders normally

What went wrong?
Intermittent black boxes & glitches: http://imgur.com/a/SkOOw

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
1. Visit this first to enable feature: https://app.box.com/cookieswitch/amsterdam/enable
2. Then see viewer via any file on Box, or with an open shared link: https://cloud.box.com/v/chicken

**Comment by tonyjin** [comment] 2016-07-20 19:34
Doing some research online point to things like:
https://productforums.google.com/forum/#!topic/chrome/VXoAbUygYdM
https://productforums.google.com/forum/#!topic/chrome/dQ1SEXYUigU

And refer to the feature 'slimming-paint' as a flag in Chrome that no longer exist, but this is still intermittently (very rarely) happening in version of Chrome 51+

I know this isn't a lot to work on, but was wondering if anyone else knows or suspects what this may be caused by.

**Comment by yurydelendik** [comment] 2016-07-20 20:08
I cannot reproduce that on 10.11.5 NVIDIA. Can you reproduce that on Chromium? See if you can narrow it down using bisecting prebuilt packages: see https://www.chromium.org/developers/bisect-builds-py (?). Since it has no reliable repro, you may need to repeat process several times.

**Comment by tonyjin** [comment] 2016-07-20 23:17
I haven't been able to reproduce this issue since Chrome ~48/49. Mainly filed this issue to see if anyone else has seen this and can provide a repro case.

Suspect this has something to do with slimming paint and/or hardware acceleration in Chrome.

**Comment by tonyjin** [comment] 2016-07-21 18:26
I received some additional information:

A user experienced this issue (black glitches) when opening a PDF with a lot of rows columns (from an Excel file converted to PDF) with this browser/graphics card setup:
Chrome 51.0.2704.106 (64-bit)
Mac Yosemite 10.10.4 (14E46), Intel HD Graphics 6000 1536 MB

When they turned off 'Use hardware acceleration when available', they no longer experienced the issue and PDF.js loaded much faster.

I was personally able to see Chrome start glitching out when following these steps:
1. Visit www.box.com/cookieswitch/amsterdam/enable to turn the PDF.js viewer feature on
2. Visit https://darth.app.box.com/s/ituq2a74l6afrfo40s5a6tbresa9bt3n
3. See that PDF loads slowly
4. Navigate to another Chrome tab and see black boxes appear on random web pages

This is my setup:
Chrome 51.0.2704.106 (64-bit)
Mac 10.11.5, AMD Radion R9 M370X
'Use hardware acceleration when available' checked

**Comment by timvandermeij** [comment] 2016-07-21 19:28
It's probably best to report this upstream in the Chrome issue tracker as it does not look like something that we can solve in PDF.js. Marking as upstream bug for now.

**Comment by tonyjin** [comment] 2016-07-21 20:18
Filed here: https://bugs.chromium.org/p/chromium/issues/detail?id=630394

**Comment by tonyjin** [comment] 2016-08-17 21:24
An update - there seem to be OOM issues reported in a separate Chromium ticket related to the PDF.js viewer extension on Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=623375

Not sure if there any asks yet of the PDF.js team, but from an initial read there seem to be complications due to large canvases possibly not being garbage collected quickly enough. Just wanted to get this ticket on your guys' radar.

**Comment by timvandermeij** [comment] 2020-05-24 14:17
The viewer is more efficient nowadays and the upstream bugs have been closed, so this should be done now. If there are still issues, this should most likely be reported to Chrome upstream.

**Closed by timvandermeij** 2020-05-24 14:17 UTC
Labels: 3-upstream, 4-chrome-specific
