### ISSUE TITLE
NS_ERROR_FAILURE while opening pdf file.

### ISSUE THREAD

**Issue by Bael** [mozilla/pdf.js#9621] opened 2018-04-02 03:51 UTC
problem file:
[Схема для компонента(1).pdf](https://github.com/mozilla/pdf.js/files/1867062/1.pdf)

Configuration:
- Web browser and its version:59.0.2 (64-бит)
- Operating system and its version:Windows 7, 64 bit
- PDF.js version:PDF.js: 2.0.288 
- Is a browser extension:no

Steps to reproduce the problem:
1. open file
2. see blank screen.

What is the expected behavior? (add screenshot)
file displays correctly

What went wrong? (add screenshot)
https://i.imgur.com/6JywFlz.png
In console I see error text:

PDF 55567dd97be30474c28edcdd234dd0c6 [1.4 iText 2.0.7 (by lowagie.com) / -] (PDF.js: 2.0.288)
viewer.js:1629:7
NS_ERROR_FAILURE: 
pdf.js:8374
putBinaryImageData
resource://pdf.js/build/pdf.js:8374:9
CanvasGraphics_paintInlineImageXObject
resource://pdf.js/build/pdf.js:9578:9
CanvasGraphics_paintImageXObject
resource://pdf.js/build/pdf.js:9537:7
CanvasGraphics_executeOperatorList
resource://pdf.js/build/pdf.js:8565:11
InternalRenderTask__next
resource://pdf.js/build/pdf.js:3213:30
InternalRenderTask__next self-hosted:991:17

**Comment by Snuffleupagus** [comment] 2018-04-02 08:18
This is a duplicate of e.g. issue #6741.

**Comment by timvandermeij** [comment] 2018-04-02 14:52
Closing as such.

**Closed by timvandermeij** 2018-04-02 14:52 UTC
