### ISSUE TITLE
PDF does not load -- stack trace but no error message

### ISSUE THREAD

**Issue by aaronmcs** [mozilla/pdf.js#10512] opened 2019-02-01 00:39 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 64.0
- Operating system and its version: Windows_NT 10.0 build 17763.253
- PDF.js version: v2.0.936
- Is a browser extension: No

Steps to reproduce the problem:
1. Load This PDF 
2. Stack Trace of Error: 
An error occurred while rendering the page.
PDF.js v2.0.936 (build: d2189293)
Message: 
Stack: putBinaryImageMask@resource://pdf.js/build/pdf.js:6566:7
CanvasGraphics_paintImageMaskXObject@resource://pdf.js/build/pdf.js:7640:7
CanvasGraphics_executeOperatorList@resource://pdf.js/build/pdf.js:6726:11
InternalRenderTask__next/<@resource://pdf.js/build/pdf.js:5546:32
InternalRenderTask__next@resource://pdf.js/build/pdf.js:5542:14
InternalRenderTask__scheduleNext/<@resource://pdf.js/build/pdf.js:5535:11
 6 viewer.js:832:7
	error/< resource://pdf.js/web/viewer.js:832:7

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/38263503/52094987-2a721900-2576-11e9-97e1-af5420d2b687.png)
(Image of PDF loaded in Chrome)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/38263503/52095030-4c6b9b80-2576-11e9-80c5-07d0f138394d.png)
(image in FF)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://s3-us-west-2.amazonaws.com/aaroncmcs/Structural_S001.pdf

**Comment by THausherr** [comment] 2019-02-01 07:41
Contains an image of size 26399 x 20399

**Comment by Snuffleupagus** [comment] 2019-02-01 08:59
Duplicate of #6741.

**Closed** 2019-02-01 23:40 UTC
