### ISSUE TITLE
Chrome the font size is quite large than in firefox 

### ISSUE THREAD

**Issue by hiteshk764** [mozilla/pdf.js#16656] opened 2023-07-07 06:44 UTC
Steps to reproduce the problem:
1.  Open pdf viewer in chrome automatic zoom text is quite bigger than when open in firefox

What is the expected behavior? font size in chrome should be same as that in firefox

What went wrong? 
![image](https://github.com/mozilla/pdf.js/assets/25202384/902667aa-d1d8-487e-a80f-e8e5ed5ab49d)
As it can be seen in above image that font size is quite large

**Comment by Snuffleupagus** [comment] 2023-07-07 07:05
Duplicate of #16024

**Closed by Snuffleupagus** 2023-07-07 07:05 UTC
