### ISSUE TITLE
wrong characters for ∈, −, /, θ and others (page 4 for example)

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#7217] opened 2016-04-18 14:27 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Version 50.0.2661.75 beta (64-bit)

- Operating system and its version: OS X El Capitan 10.11.3 (15D21)
- PDF.js version: online viewer as of April 18, 2016
- Is an extension:

Steps to reproduce the problem:
1. select text from page 4 where it reads "C(k, l), with k, l ∈ [−n/2, n/2]" or formula below it with sinθ)
2. notice the text copied does not have most symbols

What is the expected behavior? (add screenshot)
I expected the right unicode characters to be selected.
What went wrong? (add screenshot)
Characters were either missing or wrong unicode.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[ircdl2016_paper_1.pdf](https://github.com/mozilla/pdf.js/files/223946/ircdl2016_paper_1.pdf)

**Comment by yurydelendik** [comment] 2016-04-18 14:43
fwiw, adobe reader has the same issue and mac osx preview works as expected

**Comment by ldenoue** [comment] 2016-04-19 14:12
Other libraries work well too, e.g. MuPDF, jPedal and XPDF.

**Comment by ldenoue** [comment] 2016-04-20 14:58
I noticed that for these characters, the function charToGlyph gets a unicode value < 32.
https://github.com/mozilla/pdf.js/blob/2dd03e178594ff9958819114c0e5f097e9e1f1ec/src/core/fonts.js#L2714

However, the font in the PDF has an /Encoding entry that maps these < 32 values to glyphnames.

But the object "this" inside charToGlyph doesn't have its "encoding" defined.
How can we get the encoding and resolve the unicode to the corresponding glyphname?

Laurent.

**Comment by ldenoue** [comment] 2016-04-20 15:21
I have a fix for this issue.
Needs to modify the code at 2 places:
1) in
https://github.com/mozilla/pdf.js/blob/2dd03e178594ff9958819114c0e5f097e9e1f1ec/src/core/fonts.js#L684 we need to keep the builtInEncoding if there was one:
this.encoding = properties.builtInEncoding || properties.baseEncoding;

2) charToGlyph at line L2716, insert this code:
https://github.com/mozilla/pdf.js/blob/2dd03e178594ff9958819114c0e5f097e9e1f1ec/src/core/fonts.js#L2716
      // Laurent fixes issue https://github.com/mozilla/pdf.js/issues/7217 with ircdl2016_paper_1.pdf
      if (this.encoding)
      {
        var glyphName = this.encoding[charcode];
        var glyphsUnicodeMap = getGlyphsUnicode();
        var unicode = getUnicodeForGlyph(glyphName, glyphsUnicodeMap);
        unicode = String.fromCharCode(unicode);
      }
      // end fixing issue https://github.com/mozilla/pdf.js/issues/7217

**Comment by yurydelendik** [comment] 2016-04-20 15:39
> I have a fix for this issue.

Can you explain the solution from PDF32000 spec point of view? (Since Adobe Reader is using that as a base and looks like the PDF is not valid according to the spec) Can you also test the solution with reftests before proposing it. In the past, simple fix in the font code, could trigger multiple regressions in the rest of the PDFs.

**Comment by Snuffleupagus** [comment] 2016-04-20 15:51
The problem with the PDF file is that doesn't contain a single `ToUnicode` entry, which would have prevented this issue from occurring, so it's more of an issue with a particular PDF rather than PDF.js.

> In the past, simple fix in the font code, could trigger multiple regressions in the rest of the PDFs.

What immediately strikes me as (potentially) problematic with the suggested solution, is that it would override any `ToUnicode` data included in the PDF file, which could very easily lead to breakage.
Even if the above solution seems to pass tests, you'd probably need to somehow limit it to e.g. only fonts without included `ToUnicode` data, to at least mitigate the regression risk somewhat

**Comment by ldenoue** [comment] 2016-04-20 18:09
When there's a ToUnicode table AND an encoding, shouldn't the entries of the encoding be merged into the ToUnicode table?

Laurent

**Comment by yurydelendik** [comment] 2016-04-21 15:49
> When there's a ToUnicode table AND an encoding, shouldn't the entries of the encoding be merged into the ToUnicode table?

See section 9.10 of the PDF32000 at http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#page=300

**Comment by ldenoue** [comment] 2016-04-21 16:49
It states:
"there is no way to determine what the character code represents in which case a conforming reader may choose a character code of their choosing."

So if we don't have a ToUnicode then we're free to try with what we have, in this case we have an encoding (builtInEncoding)

Can't we?

**Comment by yurydelendik** [comment] 2016-04-21 17:05
(I'm a little bit confused about mixed statements in the comments above) Attaching fonts structure:

<img width="506" alt="screen shot 2016-04-21 at 12 02 49 pm" src="https://cloud.githubusercontent.com/assets/1523410/14717904/39a9f4f2-07b9-11e6-93e9-9d0b154734b6.png">

**Comment by yurydelendik** [comment] 2016-04-21 19:00
Right place would be to look at type1FontGlyphMapping and check which documents could be affecteed and how if we change logic there.

**Comment by Snuffleupagus** [comment] 2016-09-16 16:29
Closing as fixed by PR #7550.

**Closed by Snuffleupagus** 2016-09-16 16:29 UTC
Labels: 4-text-selection
