### ISSUE TITLE
Text height returned by getTextContent is way off

### ISSUE THREAD

**Issue by stri8ed** [mozilla/pdf.js#5896] opened 2015-04-01 16:16 UTC
I am having an issue extracting text from [this PDF](http://www.dfki.uni-kl.de/~kieni/publications/spie98.pdf). My goal is to extract the text bounding-boxes via getTextContent. The problem is, the height of the extracted text chunks are off by a large margin. The height I am getting (for all texts) is `0.12`, while the actual height looks closer to `12.0`.

In the native adobe-reader, the text bounding boxes are correct, as evidenced by highlighting the text. Furthermore, the text height is rendered correctly by PDFJS (the text is indeed being rendered, its not an image), so I don't believe the PDF is providing incorrect info.

After some digging around, it looks like the issue might be related to the textMatrix. For the all the texts on the page, the TM scaling is `[0.12, 0, 0, -0.12, tx, ty]`, the CTM is `[1, 0, 0, 1, 0, 0]`, while the fontSize is `1`. Is this information being wrongly parsed/scaled? How does the renderer get it right?

The issue is experienced both in Chrome and Firefox.

Below is a screenshot of the text bounding-boxes drawn over the rendered page.
![screenshot](http://i.imgur.com/GLOu6r6.png?1)

**Comment by Snuffleupagus** [comment] 2015-04-01 16:23
This is most likely a duplicate of issue #3360.

**Comment by stri8ed** [comment] 2015-04-01 19:09
Indeed, the issue appears to be related to Type3 fonts. I suspect the issue is caused by the glyph operator-list modifying the CTM with the appropriate height values, instead of setting the value via the textMatrix? If this is the case, how about using the `FontBBox` to get an estimate of the text height?

**Closed** 2015-05-13 19:07 UTC
Labels: 4-font-type3, 4-text-selection
