### ISSUE TITLE
Getting error using with Angular

### ISSUE THREAD

**Issue by csname1910** [mozilla/pdf.js#13199] opened 2021-04-08 04:49 UTC
I am getting the following error.

You can reproduce it, see here:

https://github.com/csname1910/errordemo

    Error: ./node_modules/pdfjs-dist/build/pdf.js 2413:45
    Module parse failed: Unexpected token (2413:45)
    File was processed with these loaders:
     * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
     * ./node_modules/@ngtools/webpack/src/ivy/index.js
    You may need an additional loader to handle the result of these loaders.
    |         intent: renderingIntent,
    |         renderInteractiveForms: renderInteractiveForms === true,
    >         annotationStorage: annotationStorage?.getAll() || null
    |       });
    |     }

**Comment by Snuffleupagus** [comment] 2021-04-08 09:11
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since there's too much information missing for this to be actionable/valid.

However, this looks like a duplicate of https://github.com/mozilla/pdf.js/issues/13200#issuecomment-815594505

**Comment by Snuffleupagus** [comment] 2021-04-08 09:44
Unfortunately "Angular" isn't something that the PDF.js contributors can support.

Furthermore, please make sure to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue.

---

You probably need to use the *correct* type of build here, as explained at https://www.npmjs.com/package/pdfjs-dist/v/2.7.570?activeTab=readme
> For usage with older browsers or environments, without support for modern features such as e.g. `async`/`await`, `ReadableStream`, optional chaining, and nullish coalescing; please see the `es5` folder.

**Closed** 2021-04-09 18:40 UTC

**Comment by niralishah1599** [comment] 2021-05-10 14:56
I have same issue. please tell me. what solution of this issue

.

**Comment by PLQin** [comment] 2021-07-14 07:17
解决办法:

`npm install pdfjs-dist@2.3.200 --save`

**Comment by georgezouq** [comment] 2021-08-18 06:31
same problem, any solution?? @niralishah1599  @timvandermeij
