### ISSUE TITLE
Printing stops Javascript execution

### ISSUE THREAD

**Issue by stupkad** [mozilla/pdf.js#13888] opened 2021-08-11 07:36 UTC
Hi there,

I am currently looking for a possibility to display (and print) a pdf document within a webpage.  When I open the demo page (see link below) and click print, it seems Javascript execution is stopped at all for the whole page. I have verified this by setting up an simple interval using the console.

`setInterval(() => console.log(new Date()), 500);`

https://mozilla.github.io/pdf.js/web/viewer.html

I have experienced the same issue when printing the content of any div by script, regardless which async way I have tried.

Is this a know issue, or is thera a way how to circumvent this issue?
Or is this behaviour by design?

Thanks a lot,
Dietmar

**Comment by Snuffleupagus** [comment] 2021-08-11 07:57
I can reproduce this on *any* web-page (e.g. even http://example.com/) in both Firefox and Chrome, by manually triggering printing with `window.print()` (which is what the demo viewer uses), hence this is a more general browser issue and not a PDF.js library one as far as I can tell.
Looking at https://developer.mozilla.org/en-US/docs/Web/API/Window/print, there's also this sentence which seem to explain things:
> In most browsers, this method will block while the print dialog is open. However in more recent versions of Safari, it may return immediately.

All-in-all, closing as "invalid" here since this is a browser (or possibly even specification) limitation and not actually related to and/or caused by the PDF.js demo viewer.

**Closed by Snuffleupagus** 2021-08-11 07:57 UTC
