### ISSUE TITLE
PDF print must ignore unprintable layers

### ISSUE THREAD

**Issue by mvorisek** [mozilla/pdf.js#17723] opened 2024-02-24 10:21 UTC
Configuration:
- Web browser and its version: Firefox 122.0.1
- Operating system and its version: Windows 10 x64
- PDF.js version: 4.0.348
- Is a browser extension: bundled in Firefox 122.0.1

(originally posted as Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1826783)

Steps to reproduce the problem:

1. Open and print the attached pdf file [1] with label that has unprintable border.
2. Do the same a) with Mozilla Firefox, b) using Adobe Acrobat Reader and notice, the border around the label is printed unexpectedly with Mozilla Firefox. When printed using Adobe Acrobat Reader app, the border is correctly not printed.

Actual results:

Label border is printed when printed using Firefox.

Expected results:

The border is defined in the pdf as unprintable layer and therefore must not be printed.

I would also expect the border to be NOT visible in a print preview.

[1] https://bugzilla.mozilla.org/attachment.cgi?id=9327375

**Comment by mvorisek** [comment] 2024-02-24 10:26
> The OCG dictionary contains an entry Usage which is specified:
https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#page=240
and in this pdf, the View layer must be off when the document is printed.

citing Calixte Denizet (@calixteman), https://bugzilla.mozilla.org/show_bug.cgi?id=1826783#ct-4

**Comment by Snuffleupagus** [comment] 2024-02-24 10:27
> (originally posted as Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1826783)

Closing as duplicate of that one, since there's no need to file the same issue in both Bugzilla and GitHub.

**Closed by Snuffleupagus** 2024-02-24 10:27 UTC

**Comment by mvorisek** [comment] 2024-02-24 10:29
@Snuffleupagus wouldn't be better to have an issue open in the source code repo instead? When someone else have the issue unrelated to Firefox, he won't he able to find it.

**Comment by Snuffleupagus** [comment] 2024-02-24 10:38
> wouldn't be better to have an issue open in the source code repo instead?

Bugzilla has better functionality for tracking things and that one was filed first, hence why I "duped" this issue.

> When someone else have the issue unrelated to Firefox, he won't he able to find it.

Maybe, but we'll simply point to the relevant Bugzilla entry in that case.
