### ISSUE TITLE
when the searched words are wrap in two lines, the search will fail - with my solution at the end

### ISSUE THREAD

**Issue by lvyq800** [mozilla/pdf.js#10109] opened 2018-09-27 22:05 UTC
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: all chrom and IE
- Operating system and its version: any
- PDF.js version: the latest
- Is a browser extension: no

Steps to reproduce the problem:
1.  open link https://mozilla.github.io/pdf.js/web/viewer.html, it opens the default pdf.
2. search "dynamic languages" , then search "dynamiclanguages"
    problem: when search "dynamiclanguages", the title is marked; when search "dynamic languages", the title is missed.
problem analysis: with in one sentense, the end word of one line will be conjuncted with the first word of the following new line - in the case of the title, "dynamic" is connected with "languages" without adding a blank between them.

What is the expected behavior? (add screenshot)
search with words such as "dynamic languages" and all places are marked whenever there is a newline between the words or not
![image](https://user-images.githubusercontent.com/27040239/46175985-edfd8a80-c301-11e8-9d23-3715602f36ba.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/27040239/46176188-a1667f00-c302-11e8-8471-5397e790047a.png)

![image](https://user-images.githubusercontent.com/27040239/46176281-fdc99e80-c302-11e8-9372-1056fb751fec.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

My solution is to rewrite the method calcFindPhraseMatch in viewer.js with the following code, and it works, to contribute to the PDFJS project, and thank you all for your great contributions.
                {
                    key: 'calcFindPhraseMatch',
                    value: function calcFindPhraseMatch2(query, pageIndex, pageContent) {
                        var matches = [];
                        var matchLength = [];
                        var queryLen = query.length;
                        var matchIdx = 0;
                        var endIdx = 0;
                        var queryArray = query.match(/\S+/g);

                        while (true) {
                            var subquery = queryArray[0];
                            var subqueryLen = subquery.length;
                            matchIdx = pageContent.indexOf(subquery, endIdx);

                            if (matchIdx === -1) {
                                break;
                            }

                            endIdx = matchIdx + subqueryLen;

                            var isMatch = true;
                            for (var i = 1, len = queryArray.length; i < len; i++) {
                                subquery = queryArray[i];
                                subqueryLen = subquery.length;
                                var subMatchIdx = pageContent.indexOf(subquery, endIdx);
                                if ((subMatchIdx === -1)) { //no sequencial matching
                                    isMatch = false;
                                    break;
                                }
                                if (pageContent.substr(endIdx, subMatchIdx - endIdx).trim() != "") {
                                    isMatch = false;
                                    break;
                                }
                                endIdx = subMatchIdx + subqueryLen;
                            }
                            if (isMatch) {
                                matches.push(matchIdx);
                                matchLength.push(endIdx - matchIdx);
                            }
                        }
                        this.pageMatches[pageIndex] = matches;
                        this.pageMatchesLength[pageIndex] = matchLength;
                    }

                },

**Comment by Snuffleupagus** [comment] 2021-05-29 09:23
Duplicate of #4742

**Closed by Snuffleupagus** 2021-05-29 09:23 UTC
Labels: 4-text-selection
