### ISSUE TITLE
InternalRenderTask does not work correctly with Render Task cancellation

### ISSUE THREAD

**Issue by evadne** [mozilla/pdf.js#8384] opened 2017-05-05 23:43 UTC
Consider the following pattern:

- User scrolls to a certain page.
- Page needs to be rendered.
- Render called via `PDFPageProxy_render`, a task is returned.
- User scrolls away from page.
- Page no longer needs to be rendered, the task is cancelled via `RenderTask_cancel`.
- This is ineffective.

If you set logging to high verbosity via: `PDFJS.verbosity = PDFJS.VERBOSITY_LEVELS.infos`, you can see that `getOperatorList` still runs for every single render task that has since been cancelled. This means that task cancellation merely allows a new task to be enqueued, and does not alleviate the underlying worker from doing the now unnecessary work.

I’m not too sure how this can be made to work, but this seems like something that I would really like to sort.

**Comment by Snuffleupagus** [comment] 2017-05-05 23:49
Unless I'm mistaken, isn't this (basically) a duplicate of issue #1887.

**Comment by yurydelendik** [comment] 2017-05-05 23:56
Currently there is no way to stop getOperatorList on worker side. By cancelling rendering task, only render operations are cancelled. I hope this will change with moving to Streams API.

/cc @mukulmishra18 

Closing this since a rendering task cancellation is doing right things from design point of view. Interruption of getOperatorList will be addressed somewhere else (e.g. #1887).

**Closed by yurydelendik** 2017-05-05 23:56 UTC

**Comment by evadne** [comment] 2017-05-06 00:00
No I disagree as this means that cancelling a render task does not imply that all of its side effects will cease. In this case rendition cancellation can no longer be trusted.

If I could introspect how deep the message queue is, I could protect the worker by not queueing additional rendition tasks (that can potentially also be cancelled) until whatever is in its queue has completed.

**Comment by evadne** [comment] 2017-05-06 00:06
One solution I see (if even possible) is to emit a nonce value for each task queued from the Internal Render Task. Assign this with each worker task queued under `WorkerTasks`. Add a handler for internal task termination. Call said handler from the Internal Render Task when something is cancelled.

The assumption is that `PartialEvaluator_getOperatorList` already checks whether the task is alive so what is missing really is the ability to get cancellation done in a very thorough manner.

Does that make sense

**Comment by yurydelendik** [comment] 2017-05-06 00:10
Currently we are channeling efforts into introducing Streams API, which will address this issue by design. But we will be glad to review proposed above solution (a pull request) if it's not complex and does not regress performance of the library.

**Comment by evadne** [comment] 2017-05-06 00:34
Noted. I’ll give it a try regardless. I think it can be had with 50 lines or fewer. Any outstanding material at hand for Streams?
