### ISSUE TITLE
Search from URL highlights the search term but does not open the "Find" box

### ISSUE THREAD

**Issue by JLavalleyENet** [mozilla/pdf.js#14939] opened 2022-05-19 15:43 UTC
Configuration:
- Chrome: 101.0.4951.67
- Windows 10 64-bit
- PDF.js version:  v2.14.305

Steps to reproduce the problem:
1.  Use "#Search" in the URL to find a term or terms in the PDF.  Example:
https://mozilla.github.io/pdf.js/web/viewer.html#search=trace

Expected result:
![image](https://user-images.githubusercontent.com/50142510/169339507-e89bfefb-3bd3-433a-baa7-214a08bd6c24.png)

Actual result

![image](https://user-images.githubusercontent.com/50142510/169338697-3b06ad08-0257-4d5e-9c01-4cb9c460f84e.png)

**Comment by Snuffleupagus** [comment] 2022-05-19 15:49
Duplicate of #8185

**Closed by Snuffleupagus** 2022-05-19 15:49 UTC
