### ISSUE TITLE
Orientation of text within textboxes

### ISSUE THREAD

**Issue by ClaudeMartel** [mozilla/pdf.js#14465] opened 2022-01-17 19:28 UTC
Attach (recommended) or Link to PDF file [Untitled.pdf](https://github.com/mozilla/pdf.js/files/7884232/Untitled.pdf)

Configuration:
- Google Chrome Version 97.0.4692.71 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Pro 21H1
- PDF.js version: Demo (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension:

Steps to reproduce the problem:
1. Open the attached pdf file that contain two textboxes.
2. The content of the second textbox (BBB..) should be displayed vertically but is displayed horizontally.

What is the expected behavior? 
![image](https://user-images.githubusercontent.com/25962333/149826571-67831eef-2b8e-4c39-bd4f-a865f2eba5e9.png)

What went wrong? 
![image](https://user-images.githubusercontent.com/25962333/149826689-42897d7b-04bc-4be9-96f4-7b0684219339.png)

**Comment by Snuffleupagus** [comment] 2022-01-17 19:31
Duplicate of #9596

**Closed by Snuffleupagus** 2022-01-17 19:31 UTC
