### ISSUE TITLE
How to retrieve Resources dictionary for a page?

### ISSUE THREAD

**Issue by dwightkelly** [mozilla/pdf.js#6227] opened 2015-07-17 14:11 UTC
I've tried to find a solution by reviewing the code for pdf.js but can not determine how to retrieve the Resource dictionary for a certain page. How do I get access to the Catalog object so I can directly access PDF objects?

```javascript
PDFJS.getDocument("test.pdf").then(function(doc) {
  var numPages = doc.numPages;
  var pgPromise = doc.getPage(1);
  pgPromise.then(function(page) {
    console.log( 'page number: ' + page.pageNumber + " " + page.ref.num + " " + page.ref.gen + " obj");

    /* I have the num/gen for the page object but how do I retrieve the PDF object and then lookup Resources dictionary? */
  });
});
```

**Comment by timvandermeij** [comment] 2015-07-17 17:59
I think your case is covered with #5117. We do not expose internal objects through the API yet.

**Comment by dwightkelly** [comment] 2015-07-17 19:48
Is there a way I can create a PDFDocument object then?

**Comment by yurydelendik** [comment] 2015-11-05 16:39
> Is there a way I can create a PDFDocument object then?

You have to directly use files/objects in src/core/ directory. The existing API will not be useful for you in this case.

Closing as answered (and probably as duplicate of #5117)

**Closed by yurydelendik** 2015-11-05 16:39 UTC
Labels: 1-other
