### ISSUE TITLE
getDocument function

### ISSUE THREAD

**Issue by wangzhiming1999** [mozilla/pdf.js#16478] opened 2023-05-26 09:40 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:chrome
- Operating system and its version:
- PDF.js version:3.6.172
- Is a browser extension:

Steps to reproduce the problem:
1. getDocument and getTextContent get content differently than display
2.file=https://core.ac.uk/download/pdf/41446564.pdf
![image](https://github.com/mozilla/pdf.js/assets/48944224/f12a093c-73ae-419a-b789-98c64642a1ef)
![image](https://github.com/mozilla/pdf.js/assets/48944224/fa7b4d29-7e38-434d-b09c-7c8c763fa8c4)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-05-26 09:53
Duplicate of #16477

**Closed by Snuffleupagus** 2023-05-26 09:53 UTC
