### ISSUE TITLE
Characters overlapping when PDF is opened in Mozilla and Chrome, but works fine under IE

### ISSUE THREAD

**Issue by VelaOne** [mozilla/pdf.js#8010] opened 2017-01-30 21:56 UTC
Link to PDF file (or attach file here):
It's a confidential PDF so I cannot share it here
Configuration:
- Web browser and its version: Both Mozilla and Chrome are up to date
- Operating system and its version: WINDOWS7 Enterprise SP1
- PDF.js version: 1.3.91, but in demo site it also shows the same result
- Is an extension: No

Steps to reproduce the problem:
1. Open the PDF file in the demo site under either Chrome or Mozilla
2. Open the PDF file in the demo site under IE 

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/17605941/22443437/80632046-e704-11e6-8e7b-07fbafd9341b.png)

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/17605941/22443381/55a66002-e704-11e6-87c3-fee62c6f486e.png)
Got "Warning: Failed to load font "g_d1_f1": SyntaxError: Invalid font data in ArrayBuffer" in the console
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2017-01-30 22:00
There is nothing we can do about this when no example PDF file is provided. Based on the description, I'm closing this issue as a duplicate of e.g., #5798.

**Closed by timvandermeij** 2017-01-30 22:00 UTC
