### ISSUE TITLE
PDF does not render (infinite spinner)

### ISSUE THREAD

**Issue by gitarra** [mozilla/pdf.js#8511] opened 2017-06-11 08:47 UTC
Link to PDF file (or attach file here):
[11680.pdf](https://github.com/mozilla/pdf.js/files/1066314/11680.pdf)

Configuration:
- Web browser and its version: Firefox Nightly
- Operating system and its version: Ubuntu 17.04
- PDF.js version: ?
- Is an extension: No

Steps to reproduce the problem:
1. Try to view the file.
2. Infinite spinner.

**Comment by Snuffleupagus** [comment] 2017-06-11 09:30
Closing as duplicate of issue #6741.

**Closed by Snuffleupagus** 2017-06-11 09:30 UTC
