### ISSUE TITLE
Text with "ti" sequence not rendered correctly

### ISSUE THREAD

**Issue by ngsankha** [mozilla/pdf.js#9504] opened 2018-02-22 21:56 UTC
Attach (recommended) or Link to PDF file here: https://www.cse.iitb.ac.in/~pratikm/resume.pdf

Configuration:
- Web browser and its version: Firefox 58.0.2
- Operating system and its version: MacOS High Sierra 10.13.3
- PDF.js version: PDF.js: 2.0.106
- Is a browser extension: Native PDF.js that comes with Firefox by default

Steps to reproduce the problem:
1. Open the linked PDF file.
2. The text sequence "ti" in headings is not rendering correctly.

What is the expected behavior?

<img width="1146" alt="screen shot 2018-02-22 at 4 54 32 pm" src="https://user-images.githubusercontent.com/1267409/36566318-227ffc5a-17f1-11e8-8e02-2a4d8d814e61.png">

What went wrong?

<img width="886" alt="screen shot 2018-02-22 at 4 55 20 pm" src="https://user-images.githubusercontent.com/1267409/36566345-371f168c-17f1-11e8-9069-ed4abbbabd8c.png">

**Comment by Snuffleupagus** [comment] 2018-02-28 09:11
> Attach (recommended) or Link to PDF file here: https://www.cse.iitb.ac.in/~pratikm/resume.pdf

The file isn't accessible, please attach it directly to the issue to avoid such problems.

> PDF.js version: PDF.js: 2.0.106

Is this issue reproducible in the latest version of PDF.js, which can always be found at https://mozilla.github.io/pdf.js/web/viewer.html (use the "Open file" button on toolbar to open your file)?

**Comment by THausherr** [comment] 2018-02-28 11:08
I can access it now and it works in the current viewer.

**Comment by Snuffleupagus** [comment] 2018-02-28 11:17
Closing as duplicate of issue #9458, which was fixed by PR #9460.

**Closed by Snuffleupagus** 2018-02-28 11:17 UTC
Labels: 4-font-conversion, 4-information-requested
