### ISSUE TITLE
How to add onclick event on image elements & get image data?

### ISSUE THREAD

**Issue by dim0147** [mozilla/pdf.js#16104] opened 2023-03-03 15:32 UTC
Hi, I want to add on click event when the user clicks on the image & gets that image data, my intention is when the user clicks on the image I will show the popup the box that shows the image with zoom in & zoom out features, if I not wrong image is render by canvas, which is different from annotation, how can I accomplish this? Thanks

**Comment by Snuffleupagus** [comment] 2023-03-03 16:01
Duplicate of #6347

**Closed by Snuffleupagus** 2023-03-03 16:01 UTC
