### ISSUE TITLE
Image size is too large in PDF which causes Uint8ClampedArray initialization to fail

### ISSUE THREAD

**Issue by ethan-zhs** [mozilla/pdf.js#14758] opened 2022-04-07 02:12 UTC
Configuration:
- Web browser and its version:   Webview
- Operating system and its version:   Android 11
- PDF.js version:  2.12.313

What went wrong? 

The datalength is too large causes error in webview
![image](https://user-images.githubusercontent.com/20236999/162109024-1298485d-97e6-43be-a2bb-21e7761a6177.png)

![image](https://user-images.githubusercontent.com/20236999/162109928-4de32f2e-157d-4962-8e1d-743ede9e9963.png)

How can I fix it ?
Can images be compressed?

**Comment by Snuffleupagus** [comment] 2022-04-07 07:23
First of all, please note that the `Attach (recommended) or Link to PDF file here:`-part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> PDF.js version:  2.12.313

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> How can I fix it?
> Can images be compressed?

You'd have to use PDF editing software to re-create the document, with a smaller image, however the PDF.js library contains no such functionality.

---

Closing as INVALID, since this issue unfortunately contains no actionable information (and it's likely a duplicate of existing issues).

**Closed by Snuffleupagus** 2022-04-07 07:23 UTC
Labels: information-requested
