### ISSUE TITLE
seal not show!!!

### ISSUE THREAD

**Issue by tanglinhai** [mozilla/pdf.js#11361] opened 2019-11-26 11:01 UTC
[http://testweixin1.365trade.com.cn/compressed.tracemonkey-pldi-09.pdf](http://testweixin1.365trade.com.cn/compressed.tracemonkey-pldi-09.pdf)

seal not show!!!seal not show!!!seal not show!!!seal not show!!!seal not show!!!

**Comment by Snuffleupagus** [comment] 2019-11-26 12:08
Duplicate of #1076 

> seal not show!!!seal not show!!!seal not show!!!seal not show!!!seal not show!!!

*For future reference:* You need to actually provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue.

Furthermore, the kind of spamming quoted above really isn't warranted and will *definitely not* help to get any issue resolved!

**Closed** 2019-11-26 22:07 UTC

**Comment by tanglinhai** [comment] 2019-11-27 16:00
Thank you for your reply。
I made the same change as the previous answer, and opened the option to display the signature, but it still can't be displayed
