### ISSUE TITLE
pdf.js/web/viewer.html ridiculously slow since commit 74b31ab

### ISSUE THREAD

**Issue by jawatech** [mozilla/pdf.js#9021] opened 2017-10-11 19:54 UTC
Attach (reccomened) or Link to PDF file here:

Configuration:
- Web browser and its version:
chrome 61.0.3163.100 64-bit
- Operating system and its version:
win10 
- PDF.js version:
v1.8.188
- Is an extension:
N
Steps to reproduce the problem:
1. open pdf.js/web/viewer.html
2. ridiculously slow since commit 74b31ab18f1a368963f7337e2b7313a5f335e618

What is the expected behavior? (add screenshot)
should load like immediately
What went wrong? (add screenshot)
load after about 10 seconds
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N.A.

I see many changes made in web folder. Can't pinpoint the exact cause. Any ideas?

**Comment by yurydelendik** [comment] 2017-10-11 20:11
Please provide exact steps to reproduce. If you are trying to use PDF.js directly from this repo without compiling/building it via `gulp generic`, then some slow down is expected.

**Comment by yurydelendik** [comment] 2017-10-11 20:21
> 10 seconds

I looks like the viewer is run in the development mode. 10 seconds is sounds a reasonable time to recompile es6 sources to legacy es5. Closing as answered.

**Closed by yurydelendik** 2017-10-11 20:21 UTC
Labels: 4-information-requested

**Comment by Snuffleupagus** [comment] 2017-10-11 20:24
> I looks like the viewer is run in the development mode.

Ensure that you're using a version of PDF.js that includes PR #8364, since that should have improved load times quite a bit in development mode.

**Comment by jawatech** [comment] 2017-10-12 02:06
@yurydelendik indeed, I found the built files in pdf.js\build\generic\web and it works as expected.
@Snuffleupagus would keep your advice in mind when i monkey patch again ;p
