### ISSUE TITLE
Extraneous Blank Page at End When Printing from Safari 10.x on MacOS

### ISSUE THREAD

**Issue by jscheller** [mozilla/pdf.js#8520] opened 2017-06-13 03:27 UTC
Link to PDF file (or attach file here):

Seems to be reproducible with ANY PDF file printed, including the one with the viewer from the PDF.js demo...

https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version:   Safari 10.1

- Operating system and its version:   MacOS 10.12.4
- PDF.js version:  1.7.225
- Is an extension: No

Steps to reproduce the problem:
1. Open the pdf.js sample under MacOS and Safari 10.x
2. Click the 'Print' button in the pdf.js toolbar.
3. The printed output will include an extra blank page.

What is the expected behavior? 

The printed output should only contain the actual number of pages in the PDF file and should not include an extra blank page.

What went wrong? (add screenshot)

![screen shot 2017-06-12 at 8 22 19 pm](https://user-images.githubusercontent.com/1310028/27064574-e4e2fbde-4fac-11e7-84cc-94c295255496.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

https://mozilla.github.io/pdf.js/web/viewer.html

http://www.dadsworksheets.com/worksheets/addition/spiral-addition-all-facts-v1.html

I've also verified this behavior exists under MacOS 10.12 and Safari 10.0.0. The documents all seem to print correctly from Chrome.

Thanks for your help!

**Comment by jscheller** [comment] 2017-09-02 16:31
Just reconfirmed that this issue is still present in pdf.js 1.9.426...

**Comment by forrestmid** [comment] 2018-05-29 22:34
I can confirm that I experience this as well on 1.9.426, the latest stable version.

**Comment by alexey-peshin** [comment] 2019-07-30 13:38
The issue is still there on v2.2.228 (Safari 12.1, OSX 10.14.4)
The default supplied document is fine thou.

**Comment by Kienz** [comment] 2021-03-25 08:24
Still exists in v2.6.347 (Safari 14.0.3 / macOS 11.2.3)

**Comment by timvandermeij** [comment] 2021-03-26 19:43
Does it also happen with https://mozilla.github.io/pdf.js/web/viewer.html? Recently some fixes related to this have been merged in the version that currently runs there.

**Comment by Snuffleupagus** [comment] 2021-04-16 12:06
If this is indeed specific to a *particular* platform/browser, it unfortunately seems quite unlikely to be something that we can fix here. (Note that the web-platform, generally speaking, has quite limited support for controlling printing.)

**Closed** 2021-04-16 18:23 UTC
Labels: 4-printing
