### ISSUE TITLE
annotationStorage: annotationStorage?.getAll() || null

### ISSUE THREAD

**Issue by hzj19980803** [mozilla/pdf.js#13403] opened 2021-05-19 12:04 UTC
error  in ./node_modules/pdfjs-dist/build/pdf.js

You may need an appropriate loader to handle this file type.
|         intent: renderingIntent,
|         renderInteractiveForms: renderInteractiveForms === true,
>         annotationStorage: annotationStorage?.getAll() || null
|       });
|     }

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/electronicDossier/contrast.vue?vue&type=script&lang=js& 87:12-33
 @ ./src/views/electronicDossier/contrast.vue?vue&type=script&lang=js&
 @ ./src/views/electronicDossier/contrast.vue
 @ ./src/router/routers.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.11:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by Snuffleupagus** [comment] 2021-05-19 12:08
Duplicate of #13248

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md (and remember to write only in English) since as-is this issue isn't really actionable/valid.

**Comment by hzj19980803** [comment] 2021-05-19 12:09
What is the reason for my error in compiling with pdfjs dist in Vue cli3? Please tell me

**Closed** 2021-05-21 17:50 UTC
