### ISSUE TITLE
Fonts with no widths in metrics are broken for PDF.js with Chrome 92 Upgrade

### ISSUE THREAD

**Issue by pbhuynh** [mozilla/pdf.js#13799] opened 2021-07-26 23:46 UTC
Attach (recommended) or Link to PDF file here: https://www.w3.org/Style/XSL/TestSuite/contrib/FOP/fonts.pdf

Configuration:
- Web browser and its version: **Chrome 92**
- Operating system and its version: Linux
- PDF.js version: Latest
- Is a browser extension: No

Steps to reproduce the problem:
1. Use Chrome extension for pdf.js to open up that example PDF
2. It's broken and no text is showing where Courier font is supposed to show.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/3080100/127072646-af68fb0c-9dee-4257-999e-eb25b1e95d9b.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/3080100/127072582-669391af-c165-42fc-b28e-f4f11c1c0e91.png)
![image](https://user-images.githubusercontent.com/3080100/127073173-55f667ea-51e0-4d33-90dd-7dfd08017325.png)

I narrowed down to what the issue is. Chrome added an [at() method ](https://www.chromestatus.com/feature/6123640410079232) to the Array.prototype. Because of that, when `widthsByGlypName` is an empty array, it becomes `[]["at"]` and it adds the `at` native function to the width array. https://github.com/mozilla/pdf.js/blob/51f0a810851c311598748f637fb583b20b7dce03/src/core/evaluator.js#L3636-L3638

Suggested fix is to use `Array.indexOf` to check for key existence.
```
for (let charCode = 0; charCode < 256; charCode++) {
  if (charCode in differences && widthsByGlyphName.indexOf([differences[charCode]]) >= 0) {
    widths[charCode] = widthsByGlyphName[differences[charCode]];
    continue;
  }
  if (charCode in encoding && widthsByGlyphName.indexOf([encoding[charCode]]) >= 0) {
    widths[charCode] = widthsByGlyphName[encoding[charCode]];
    continue;
  }
}
```

**Comment by Snuffleupagus** [comment] 2021-07-26 23:49
> PDF.js version: Latest

Please provide an actual version *number*, since latest isn't really helpful.

---

Duplicate of #13798

**Closed by Snuffleupagus** 2021-07-26 23:49 UTC

**Comment by lbittner-pdftron** [comment] 2021-07-30 14:55
@pbhuynh Thank you, you are a life saver my friend.
