### ISSUE TITLE
The PDF file electronic signatures are not displayed please try again

### ISSUE THREAD

**Issue by changbin666** [mozilla/pdf.js#11103] opened 2019-08-28 08:05 UTC
// if (data.fieldType === 'Sig') {
    //   data.fieldValue = null;
    //
    //   _this2.setFlags(_util.AnnotationFlag.HIDDEN);
    // }

 If this code has comments。And then pdf file part of the show. please use the following file.
[mainContract (1).pdf](https://github.com/mozilla/pdf.js/files/3549799/mainContract.1.pdf)

**Comment by Snuffleupagus** [comment] 2019-08-28 08:37
Duplicate of #1076.

**Closed** 2019-08-28 21:11 UTC

**Comment by changbin666** [comment] 2019-08-29 06:27
This is about the issue of electronic signatures, but it is different from the previous ones. Also try to give a solution, how can I solve this problem?

**Comment by timvandermeij** [comment] 2019-08-29 21:35
It's not any different. Digital signatures are not supported properly, so we hide them. Showing them without verifying them, for which we don't have support, defeats the purpose and the issue above is tracking that.

**Comment by THausherr** [comment] 2019-08-30 09:28
I didn't know that... why don't you show a grey bar like with AcroForm fields?

**Comment by timvandermeij** [comment] 2019-08-30 21:51
I'm certainly not excluding that we can reconsider this given https://github.com/mozilla/pdf.js/issues/4743#issuecomment-516801290 and similar comments, but it has to made very clear that the signature is unverified in that case. In any case, this is tracked in the issues in https://github.com/mozilla/pdf.js/labels/4-digital-signature.
