### ISSUE TITLE
Failed to load font XXXX, SyntaxError: Invalid font data in ArrayBuffer.

### ISSUE THREAD

**Issue by sarankup** [mozilla/pdf.js#8623] opened 2017-07-06 14:53 UTC
Hi,

We have the same problem, both in Firefox and Chrome browser, but it works well in IE, and Safari. Here is error message:

Warning: Failed to load font "g_d1_f1": SyntaxError: Invalid font data in ArrayBuffer.
Warning: Failed to load font "g_d1_f3": SyntaxError: Invalid font data in ArrayBuffer.
We have tested with 1.8.522 at https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2017-07-06 15:57
When reporting an issue, please provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) (rather than just deleting it completely); of particular importance is that you provide the PDF file.

Without that information, this issue will be closed as incomplete.

**Comment by timvandermeij** [comment] 2017-07-14 10:52
Closing since the issue is incomplete. Provide the information requested above to reopen.

**Closed by timvandermeij** 2017-07-14 10:52 UTC
Labels: 4-information-requested

**Comment by ash-recommind** [comment] 2017-09-21 12:33
I would like to reopen this ticket.

When loading the attached PDF
[TheBlueLights_chapter1_DIE_ZWEITE_UND_LÄNGERE_VERSION.PDF](https://github.com/mozilla/pdf.js/files/1321074/TheBlueLights_chapter1_DIE_ZWEITE_UND_LANGERE_VERSION.PDF)
into the viewer, I get the very same warning in the JS console using Chrome (Version 60.0.3112.113 (Official Build) (64-bit)):
`Warning: Failed to load font "g_d1_f1": SyntaxError: Invalid font data in ArrayBuffer.`

As a result the PDF is rendered using a different font.

Firefox (55.0.3 (32-bit)) shows related errors:
```
downloadable font: rejected by sanitizer (font-family: "g_d1_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIK2um+oAAACcAAAcJk9TLzJFiipkAAAcxAAAAGBjbWFwxfsnUQAAHSQAAADmaGVhZKsnT/0AAB4MAAAANm … AHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

downloadable font: font load failed (font-family: "g_d1_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIK2um+oAAACcAAAcJk9TLzJFiipkAAAcxAAAAGBjbWFwxfsnUQAAHSQAAADmaGVhZKsnT/0AAB4MAAAANm … AHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

In IE10 and IE11 the PDF seems to be loaded without any font loading issue - at least there are no font-related warnings/errors in the JS console and in turn it looks similar to if you open it in e.g. Adobe Reader.


This is reproducible with the pdf.js demo page:
https://mozilla.github.io/pdf.js/web/viewer.html


What's causing this kind of font loading error and how can it be solved?

**Comment by timvandermeij** [comment] 2017-09-21 20:51
There are already open issues for this; see https://github.com/mozilla/pdf.js/search?q=SyntaxError%3A+Invalid+font+data+in+ArrayBuffer.&type=Issues&utf8=%E2%9C%93.
