### ISSUE TITLE
bad quality result when use chrome after print

### ISSUE THREAD

**Issue by 425131361** [mozilla/pdf.js#9700] opened 2018-05-02 07:24 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 66.0.3359.139
- Operating system and its version: Windows 10  16299
- PDF.js version:  v1.9.426
- Is a browser extension: yes
- printer : EPSON LQ-2680k 

Steps to reproduce the problem:
1.  open pdf file  in the attachment use   chrome..
2. clieck 'print' button . you will found the issue....

[https://github.com/425131361/attach/blob/master/document_wrapper.pdf](url)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by 425131361** [comment] 2018-05-03 02:01
i was upload the result 
[https://github.com/425131361/attach/blob/master/bad%20quality.jpg](url)

**Comment by timvandermeij** [comment] 2021-03-14 15:17
Closing since this is a duplicate of #2750.

**Closed by timvandermeij** 2021-03-14 15:17 UTC
Labels: 4-printing
