### ISSUE TITLE
Keyboard shortcut to change view to "page width"

### ISSUE THREAD

**Issue by vitlib** [mozilla/pdf.js#11351] opened 2019-11-21 17:49 UTC
That would be very useful, since it's the view that maximize screen usage.
Ctrl+2 is a suggestion, it's used in Adobe Reader.
Thanks!

**Comment by Snuffleupagus** [comment] 2019-11-21 18:38
> Ctrl+2 is a suggestion, 

That would clash with an existing Firefox shortcut; this is for all intents and purposes a duplicate of https://github.com/mozilla/pdf.js/issues/5206#issuecomment-462042755 and this is thus WONTFIX.

**Closed** 2019-11-21 22:35 UTC
