### ISSUE TITLE
pdf render as black canvas on the first page on mac and windows using chrome 

### ISSUE THREAD

**Issue by Nadeermalangadan** [mozilla/pdf.js#9204] opened 2017-11-28 12:39 UTC
Pdf render as black canvas on the first page on mac and windows using chrome for some time. after this if i trying reload Page or PDF then rendering Properly.

Attach (recommended) or Link to PDF file here:
![vaultedgecapture](https://user-images.githubusercontent.com/6101789/33319923-7fe5bc64-d466-11e7-9493-1228227c9c94.PNG)

Configuration:
- Web browser and its version: Chrome 62.
- Operating system and its version: Windows 10 and mac 10.12
- PDF.js version: 1.7.354
- Is a browser extension: No.

Steps to reproduce the problem:
This issue not happening always.  once in a day or twice. Not able to reproduce always

**Comment by Snuffleupagus** [comment] 2017-11-28 14:36
Based on the information provided, closing as duplicate of #7497 since this seem to be browser specific and given that no STR (steps to reproduce) are provided.

**Closed by Snuffleupagus** 2017-11-28 14:36 UTC
