### ISSUE TITLE
Pink background

### ISSUE THREAD

**Issue by Teir** [mozilla/pdf.js#8490] opened 2017-06-06 13:16 UTC
Link to PDF file (or attach file here):
[pink_pdf.pdf](https://github.com/mozilla/pdf.js/files/1055112/pink_pdf.pdf)

Configuration:
- Web browser and its version: Google Chrome 58.0.3029.110 (64-bit)
- Operating system and its version: Windows 7
- PDF.js version: demo(1.8.426)
- Is an extension:

Steps to reproduce the problem:
1. Open pink_pdf.pdf in pdf.js.

What is the expected behavior? (add screenshot)
No pink background.

What went wrong? (add screenshot)
Some lines have a pink background.
![pink](https://cloud.githubusercontent.com/assets/19780067/26830985/7642a5c2-4ad3-11e7-8293-60779f6c110c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-06-06 13:20
Closing as duplicate of issue #5046.

**Closed by Snuffleupagus** 2017-06-06 13:20 UTC
