### ISSUE TITLE
Prevents printing from Google Slides on Chrome OS

### ISSUE THREAD

**Issue by seanmcandrew** [mozilla/pdf.js#7068] opened 2016-03-07 15:17 UTC
When installed as an extension on a Chrome OS device, one is unable to print from Google Slides. Nothing happens when 'Print' is selected.

Tested from Chomebook and Chromebox Version 48.0.2564.116 (64-bit)

**Comment by Rob--W** [comment] 2016-03-12 10:00
Could you post a link to a Google Slides page where this issue occurs, so I can look into the issue, develop a solution and test it?

**Comment by timvandermeij** [comment] 2016-03-21 20:31
Closing until the information requested above is provided.

**Comment by seanmcandrew** [comment] 2016-09-27 15:02
Here you go...

https://docs.google.com/presentation/d/1fIB6Lc3MqiSETQgPMO2BVJ_xtEBFRKUD4uECoNX2txY/edit#slide=id.p

Happens from *any* Google Slide one tries to print.

**Comment by Rob--W** [comment] 2016-09-29 17:01
Even without PDF.js, Google Slides shows a Save As dialog to me instead of a print dialog. PDF.js does not try to get and show the PDF file, it's up to the Chrome browser to do something with the response, which is downloading the file in my case.

Does printing work when the extension is disabled?

**Comment by timvandermeij** [comment] 2016-10-09 15:02
I can reproduce this as well. When I click the `Print` button, without PDF.js, it shows a `Save as` dialog for me as well. It looks like this is something that PDF.js cannot resolve as it's an issue with Google Slides itself, so it should be reported upstream with Google instead.

**Closed by timvandermeij** 2016-10-09 15:02 UTC
Labels: 4-chrome-specific, 4-information-requested
