### ISSUE TITLE
I used the example pdftopng but the font is broken □□□□

### ISSUE THREAD

**Issue by misaroses** [mozilla/pdf.js#11194] opened 2019-10-02 21:48 UTC
Attach (recommended) or Link to PDF file here: [pdf](https://dteflorence.blob.core.windows.net/18669585-2/5_24_738.pdf)

I used the pdftopng example

Steps to reproduce the problem:
1. i deploy expressjs app to app services on azure
2. then with postman, i send the pdfUrl.
3. the express app convert the pdf to png and then to base64
4. the base64 image obtain a broken font = □□□□

What is the expected behavior? (add screenshot)

![checking](http://misatrincado.com/img/github/checking.png)

What went wrong? (add screenshot)

![error](http://misatrincado.com/img/github/error.png)

```

function PdfToPngUrl(body, callback) {
    function NodeCanvasFactory() { }
    NodeCanvasFactory.prototype = {
        create: function NodeCanvasFactory_create(width, height) {
            assert(width > 0 && height > 0, 'Invalid canvas size');
            var canvas = Canvas.createCanvas(width, height);
            var context = canvas.getContext('2d');
            return {
                canvas: canvas,
                context: context,
            };
        },

        reset: function NodeCanvasFactory_reset(canvasAndContext, width, height) {
            assert(canvasAndContext.canvas, 'Canvas is not specified');
            assert(width > 0 && height > 0, 'Invalid canvas size');
            canvasAndContext.canvas.width = width;
            canvasAndContext.canvas.height = height;
        },

        destroy: function NodeCanvasFactory_destroy(canvasAndContext) {
            assert(canvasAndContext.canvas, 'Canvas is not specified');

            // Zeroing the width and height cause Firefox to release graphics
            // resources immediately, which can greatly reduce memory consumption.
            canvasAndContext.canvas.width = 0;
            canvasAndContext.canvas.height = 0;
            canvasAndContext.canvas = null;
            canvasAndContext.context = null;
        },
    };

    var pdfjsLib = require('pdfjs-dist');

    // Load the PDF file.
    var loadingTask = pdfjsLib.getDocument({ url: body, disableFontFace: false });
    loadingTask.promise.then(function (pdfDocument) {
        console.log('# PDF document loaded.');

        // Get the first page.
        pdfDocument.getPage(1).then(function (page) {
            // Render the page on a Node canvas with 100% scale.
            var viewport = page.getViewport({ scale: 1.0, });
            var canvasFactory = new NodeCanvasFactory();
            var canvasAndContext =
                canvasFactory.create(viewport.width, viewport.height);
            var renderContext = {
                canvasContext: canvasAndContext.context,
                viewport: viewport,
                canvasFactory: canvasFactory,
            };

            var renderTask = page.render(renderContext);
            renderTask.promise.then(function () {
                // Convert the canvas to an image buffer.
                var image = canvasAndContext.canvas.toDataURL();
                fs.writeFile('output.png', image, function (error) {
                    if (error) {
                        callback(false, null, error)
                        console.error('Error: ' + error);
                    } else {
                        callback(true, image, null)
                        console.log('Finished converting first page of PDF file to a PNG image.');
                    }
                });
            });
        });
    }).catch(function (reason) {
        console.log(reason);
        callback(false, null, reason)
    });
}
```

**Comment by Snuffleupagus** [comment] 2019-10-03 20:26
This looks, for all intents and purposes, like a duplicate of #4244.

**Closed** 2019-10-03 20:33 UTC

**Comment by misaroses** [comment] 2019-10-03 22:17
#4244 is resolved with disableFontFace, but in this case it only works in local.
when I deploy on app service azure linux, the font is broken and show this □ □

**Comment by stygmate** [comment] 2019-10-05 07:35
same problem than @misaroses

**Comment by moataseem** [comment] 2019-10-27 13:45
I had the same issue when I've uploaded it to azure function too
