### ISSUE TITLE
QR Code from TCPDF not displayed and printed correctly

### ISSUE THREAD

**Issue by thomasgg23** [mozilla/pdf.js#3331] opened 2013-06-04 14:09 UTC
QR codes generated with the php library TCPDF cannot be read by a QR reader when the pdf is printed with pdf.js

Around the borders of each square there will be white lines (see the attached image, 300% magnified from pdf)

QR code will be recognized fine when viewed with Acrobat Reader or Foxit Reader.
I could send the PDF file if necessary.

![qr_code](https://f.cloud.github.com/assets/2633051/605793/36601160-cd1e-11e2-80b1-291591b3a1b5.jpg)

**Comment by SamyCookie** [comment] 2015-07-10 17:17
Hi,
I think it seems to be a subpixel rasterization issue inside canvas. I try to reduce the bug, you can test the issue here: http://jsbin.com/cugigivuwa/edit?html,css,output

I suspect that "imageSmoothingEnabled" property is not correctely its job when disabled (set to false).
It may be strongly related to this upstream issue: https://bugzilla.mozilla.org/show_bug.cgi?id=696630

I wanted to test the patched Firefox version, but I did not find a built version.

**Comment by timvandermeij** [comment] 2015-07-10 17:59
@SamyCookie That is a really nice find! If this is in fact a Firefox-only issue, then it might well be the cause. We need to figure out if other browsers also have this defect and if not, if the upstream patch helps. Unfortunately no build has been made there and I'm not sure how to do that either.

**Comment by SamyCookie** [comment] 2015-07-10 18:11
Small update of reduced issue: http://jsbin.com/cacigeture/edit?html,output
I do three test inside it: all are "failing" with Firefox, and only one seems to work with chromium. So IF this is a bug and not an intended behaviour, both browser has it.

**Comment by SamyCookie** [comment] 2015-07-17 10:28
@mbebenita Do you think your upstream bug may be related to this bug and is your bugfix still relevant ?
upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=696630
reduce case: http://jsbin.com/cacigeture/edit?html,output

If all yes, a lot of pdf.js issues seems to be related to this bug, so is it possible to push up your fix ?
Thanks !

**Comment by fbender** [comment] 2015-11-16 12:37
I pinged the assignee on Bug 696630. Otherwise the bug seems to have stalled.

**Comment by SamyCookie** [comment] 2015-11-25 08:53
Thanks @fbender, now the upstream bug is fixed and has been pushed in mozilla-central. I'll test later when a beta will be released to confirm (or not) if it really fix this issue.

**Comment by fbender** [comment] 2015-11-25 11:11
The fix will be in the Nightlies (Fx 45) starting today or (at the latest) tomorrow: https://nightly.mozilla.org/
Fix will be in Dev Edition starting with the week of Dec 14th -- you can easily install the Dev Edition alongside your existing install without those installs interfering with each other.
Fix will be in Beta starting with the week of Jan 25th

See https://wiki.mozilla.org/RapidRelease/Calendar or https://wiki.mozilla.org/Releases for up-to-date information

**Comment by SamyCookie** [comment] 2016-01-07 11:59
I have tested Firefox v45a2, and the line bug is still present. My reduce test case is not fixed either. Unfortunately, the upstream patch https://bugzilla.mozilla.org/show_bug.cgi?id=696630 does not solve this case as I expected. The solution is elsewhere :(

**Comment by SamyCookie** [comment] 2017-10-06 16:58
NB: http://jsbin.com/gukuhosowu/1/edit?html,output

**Comment by Snuffleupagus** [comment] 2022-02-14 10:33
Duplicate of #3351

(Since the PDF document linked in https://github.com/mozilla/pdf.js/issues/3331#issuecomment-18912538 is no longer available, it's probably not meaningful to keep this one open.)

**Closed by Snuffleupagus** 2022-02-14 10:33 UTC
Labels: image-quality
