### ISSUE TITLE
Add an About page to Tools menu

### ISSUE THREAD

**Issue by pal1000** [mozilla/pdf.js#5884] opened 2015-03-27 08:50 UTC
This needs to include version information.

There are various questions mostly regarded to what is the PDF.JS version bundled with Firefox and unfortunately there is no appropriate means of finding this information for standard users. I found a way to get this information on Google docs but unfortunately this is not something that inexperienced users can handle, not to mention that only experienced users read the release notes of Firefox which also include this information.

-Google docs page showing how to get PDF.JS version: https://groups.google.com/forum/#!topic/mozilla.dev.pdf-js/R-SFRzwptyk (mostly helps for PDF.JS bundled with Firefox)
-A user being confused about why PDF Viewer extension from Firefox Add-ons page is no longer supported as of Firefox 35.
https://support.mozilla.org/en-US/questions/1044926

**Comment by yurydelendik** [comment] 2015-03-27 12:04
Could you explain "This needs to include version information...  for standard users" part? Mostly why end user needs to know version of the PDF.js?

From support point of view getting something like "built-in PDF viewer in Firefox 36" will be enough information to pin the version of PDF.js and followup on regression. (That partially also drove decision to remove the add-on -- to remove configurations with Firefox and the add-on).

If the external project that embed PDF.js library, we don't need to appear as a separate product and support shall fall on the shoulders of the maintainers of the external project rather than PDF.js contributors -- in most of the case those solutions are just not getting updated.

**Comment by pal1000** [comment] 2015-03-27 18:21
It is mostly needed for Firefox built-in variant which is significantly out of date and probably other software programs or websites that rely on PDF.JS. Yes, you are right this is not for beginner users but rather for those wanna-be power users who are not yet skilled enough or plain curious users who noticed that same information is more accessible with similar software (e.g. other PDF viewers).

**Comment by yurydelendik** [comment] 2015-03-27 19:51
> It is mostly needed for Firefox built-in variant which is significantly out of date and probably other software programs or websites that rely on PDF.JS

@pal1000 please explain this statement. Firefox built-in variant is tested with same process as Release, Beta & Nightly versions of Firefox. If you are pointing to the development version of PDF.js addon, then it shall newer be used by end user since it's not tested by beta testers.

**Comment by timvandermeij** [comment] 2015-03-27 20:38
I agree that this would be rather unnecessary. Only power users will need that and they can just look it up in the console or in the source code. For a regular user it is just cluttering the UI.

**Comment by timvandermeij** [comment] 2015-03-31 19:27
Closing as won't-fix.

**Closed by timvandermeij** 2015-03-31 19:27 UTC
Labels: 4-information-requested
