### ISSUE TITLE
PDF.js don't display image : Unable to decode image / Not enough memory

### ISSUE THREAD

**Issue by Max-ADC** [mozilla/pdf.js#9246] opened 2017-12-07 10:38 UTC
Attach (recommended) or Link to PDF file here:
[annexe.pdf](https://github.com/mozilla/pdf.js/files/1538691/annexe.pdf)

Configuration:
- Web browser and its version: Internet Explorer 11.0.9600.18837CO 
- Operating system and its version: Windows 7 64Bits
- PDF.js version: 1.9.426

Steps to reproduce the problem:
1. Simply load the document in the viewer

What is the expected behavior? 
Document should be loaded

What went wrong? (add screenshot)
The viewer stays empty and this error appears in the console :
![errorpdfjs](https://user-images.githubusercontent.com/34338317/33711081-f7ac893e-db42-11e7-8795-8e2a7f005e63.jpg)

The problem does not occurs in Firefox

**Comment by Snuffleupagus** [comment] 2017-12-07 18:17
Closing as duplicate of e.g. issue #6741.

**Closed by Snuffleupagus** 2017-12-07 18:17 UTC
