### ISSUE TITLE
Low resolution when viewing large pages

### ISSUE THREAD

**Issue by zznidar** [mozilla/pdf.js#17295] opened 2023-11-19 16:20 UTC
Pages with very large dimensions appear blurry.

Attach (recommended) or Link to PDF file here: 
[very-long-page_3.pdf](https://github.com/mozilla/pdf.js/files/13403761/very-long-page_3.pdf)

Configuration:
- Web browser and its version: Firefox 119.0.1
- Operating system and its version: Windows 10
- PDF.js version: PDF.js: 3.11.183 [d37cd65c5] (built into Firefox), as well as PDF.js: 4.0.242 [3459615ec] (currently published demo)
- Is a browser extension: Built into Firefox

Steps to reproduce the problem:
1. Open a PDF which has a very long page, for example _579.6 × 30,810.1 mm_ (file attached)
2. Zoom in so it fits the screen.
3. In the attached file, there's content at the top of the first page, in the centre of it and at the bottom of it.

What is the expected behavior? 
Text and images should be high-resolution and readable.
![image](https://github.com/mozilla/pdf.js/assets/20877556/3bf76fe8-7181-4f38-87b9-8ab0f0a49e74)

What went wrong? 
Text and images are low-resolution and blurry.
![image](https://github.com/mozilla/pdf.js/assets/20877556/d77c7312-d6e4-4303-b14a-c20a2793840c)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

## Other PDF-readers
* Currently published demo of pdf.js is blurry in both Firefox and Chrome
* Adobe Acrobat Reader shows a warning about large page dimensions; the upper part of each page is discarded; the bottom of each page is rendered correctly
* Chrome's built-in PDF-reader renders whole page correctly

**Comment by Snuffleupagus** [comment] 2023-11-19 16:27
Duplicate of #6419

**Closed by Snuffleupagus** 2023-11-19 16:27 UTC
