### ISSUE TITLE
Warning: Error during font loading: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by q569608465** [mozilla/pdf.js#7044] opened 2016-03-01 02:22 UTC
I use the compressed pdf.worker.js in the Google Chrome browser(version:48.0.2564.116 m (64-bit)) in PC,and it throws a warning: "Error during font loading: Maximum call stack size exceeded".But it works well in the Google Chrome browser(version: 48.0.2564.95) in Android 4.4.2, and when I use the uncompressed pdf.worker.js in the Google Chrome browser in PC, it also works well.
Is there any way to solve the above problem?

**Comment by Snuffleupagus** [comment] 2016-03-01 11:04
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.
At the very least, you *need* to provide a PDF file that can be used to replicate the issue!

**Comment by timvandermeij** [comment] 2016-03-04 12:28
Closing as incomplete until the information requested above is provided.

**Closed by timvandermeij** 2016-03-04 12:28 UTC
Labels: 4-information-requested

**Comment by artursvonda** [comment] 2016-03-15 14:05
I think we got the same error: 
![error](https://www.dropbox.com/s/2pht8oxe33tg9uf/Screenshot%202016-03-15%2015.55.58.png?dl=1)

PDF.js v1.4.137
Chrome: Version 50.0.2661.26 beta (64-bit)
OS X 10.11.4 Beta (15E56a)

**Comment by adamziel** [comment] 2016-03-17 01:07
For me it was caused by "properties=true" uglifyjs option, after setting it to false it works fine again

**Comment by syafiqfaiz** [comment] 2016-04-11 05:45
Hi, I am having the same issue here. 
http://stackoverflow.com/questions/36540566/warning-error-during-font-loading-maximum-call-stack-size-exceeded-error-with

**Comment by yurydelendik** [comment] 2016-04-11 19:36
@syafiqfaiz see workaround at https://github.com/mozilla/pdf.js/blob/be6754a1a05b59668677154cedb3ec43d0f96169/make.js#L709
