### ISSUE TITLE
Jpx infinite loop for tiles with 0 Psot

### ISSUE THREAD

**Issue by madej** [mozilla/pdf.js#10793] opened 2019-05-07 16:20 UTC
JPEG2000 allows to set tile-part length to 0 in SOT segment (only the last part). This case is not handled in the code resulting in an infinite loop. End of data stream is marked by EOC in this case. As padding is possible, it must be found. Below possible solution:
```js
tile.length = readUint32(data, position + 4);
if (tile.length === 0) {
  for (var i = end - 2; i > position + length; i--) {
    if (0xFFD9 === readUint16(data, i)) {
      tile.dataEnd = i;
      break;
    }
  }
  if (tile.dataEnd === undefined) {
    throw new Error('JPX Error: missing EOC');
  }
} else {
  tile.dataEnd = tile.length + position - 2;
}
```

**Comment by Snuffleupagus** [comment] 2019-05-07 16:31
As asked for in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, please provide a PDF file which can be used to reproduce this (also since a PR will require a regression test to be accepted).

Pointer to the relevant part of the specification, to save anyone else from having to look for it: https://www.ic.tu-berlin.de/fileadmin/fg121/Source-Coding_WS12/selected-readings/20_T-REC-T_1_.800-200208-I__PDF-E.pdf#page=35

**Comment by madej** [comment] 2019-05-07 18:10
I can't help with this one. I've noticed it playing with JpxImage. I don't have any pdf file with j2k, nor tools to create one. Maybe someone else will be able to help.

**Comment by Motard** [comment] 2019-05-08 15:00
I do not know if this is related but I started having a similar issue with some pdf's in the application I am developing.

What seems to be happening is an infinite loop, and the pdf never finishes loading, and it looks like it's flickering, because it shows a page, then the loader, page again and so on.

This PDF I attach here is displaying that behaviour

[Guide to Residential Building Loans.pdf](https://github.com/mozilla/pdf.js/files/3157940/Guide.to.Residential.Building.Loans.pdf)

**Comment by Snuffleupagus** [comment] 2019-05-09 05:58
@timvandermeij Sorry, but I think the right label would be `4-image-jpx` here.

---

Also, the document in https://github.com/mozilla/pdf.js/issues/10793#issuecomment-490522099 doesn't contain a single JPX image, actually it doesn't even contain any `XObject` of any kind.
Hence that comment is *completely* unrelated to this issue, and only serves to add confusion to the discussion. (It seems related to a custom implementation, since the file renders fine in the default viewer.)

@timvandermeij Mind hiding/removing https://github.com/mozilla/pdf.js/issues/10793#issuecomment-490522099 and also this comment itself; thank you!

**Comment by Snuffleupagus** [comment] 2021-02-04 11:48
Unfortunately it's probably not meaningful to keep this issue open, when there's no PDF file (or even standalone JPEG2000 image) included that can be used to reproduce this; I'd suggest closing this issue for now.

**Comment by madej** [comment] 2021-02-04 12:53
On the other hand solution is right there, just review it and add it to codebase. Creating j2k file seems quite easy with hex editor.

**Comment by Snuffleupagus** [comment] 2021-02-20 11:42
> On the other hand solution is right there, just review it and add it to codebase.

As purely a matter of principle, we don't want to make these types of code changes without *any* way of either verifying or testing them since doing so has the potential to cause regressions elsewhere.

> Creating j2k file seems quite easy with hex editor.

If it's indeed easy, then please just provide a PDF file that can be used to reproduce this :-)

---

Without more information, I'd still suggest closing this issue as INCOMPLETE for now.

**Closed** 2021-02-20 13:45 UTC
Labels: 4-image-jpx

**Comment by madej** [comment] 2021-02-20 14:29
> > On the other hand solution is right there, just review it and add it to codebase.
> 
> As purely a matter of principle, we don't want to make these types of code changes without _any_ way of either verifying or testing them since doing so has the potential to cause regressions elsewhere.

If you look closer, it's just an 'if' statement for this special case, 'else' doesn't change anything
> 
> > Creating j2k file seems quite easy with hex editor.
> 
> If it's indeed easy, then please just provide a PDF file that can be used to reproduce this :-)

I said j2k.
> 
> Without more information, I'd still suggest closing this issue as INCOMPLETE for now.

It's closed by now. :+1:
