### ISSUE TITLE
Need smooth pinch zoom

### ISSUE THREAD

**Issue by CIELOplus** [mozilla/pdf.js#16878] opened 2023-08-28 06:43 UTC
Configuration:
- Web browser and its version: Safari and Chrome
- Operating system and its version: iOS16 and Android13
- PDF.js version: 3.3.122 or later

Until PDF.js version 3.2.146, smooth pinch zoom was possible on both iPhones and Android smartphones. However, in releases from 3.3.122 onwards, when you pinch out on the smartphone screen, the zoomed display becomes choppy and stutters.
Since smooth zoom functionality is essential, I continued to use version 3.2.146 despite newer releases. However, I've recently discovered that on certain Android 13 smartphones, PDFs aren't displaying correctly. This has left me with no option but to use the new release, which unfortunately results in the jerky zoom behavior.
Are there any adjustment methods or solutions available?

**Comment by Snuffleupagus** [comment] 2023-08-28 08:15
I cannot reproduce any problems with pinch-to-zoom when testing https://github.com/mozilla/pdf.js#online-demo in Firefox Beta on Android. Also, please keep in mind that Firefox is the *primary* development target for this library.

> in releases from 3.3.122 onwards

That release is the first one that implemented proper pinch-to-zoom support in the viewer, since that'd never actually been supported before.

> the zoomed display becomes choppy and stutters.

It's also *really difficult* to understand exactly what this looks like, with nothing more than a text description. Most likely a video of the issue would be necessary to actually show what you're seeing.

**Comment by CIELOplus** [comment] 2023-08-28 11:02
Thank you for your advise.

I have tested Firefox running on my Pixel7.

![Firefox_version](https://github.com/mozilla/pdf.js/assets/143143059/95364a8f-7752-4139-bc4c-d3ed03026951)

Would you please see this movie PDFjs_Release3.2.146.mp4 first.
https://github.com/mozilla/pdf.js/assets/143143059/b92a4cf8-eaa3-4a10-a716-75b264e8c1bd

Then, next is PDFjs_Release3.9.179.mp4.
https://github.com/mozilla/pdf.js/assets/143143059/8fb8ddbe-f2a4-4b6b-bb48-f316bd4fc856

I hope you can see the difference between those two movie files.
I believe the chart portion is easier to recognize, especially more than the text. In PDFjs_Release3.9.179.mp4, you can see the zooming display exhibits a jerky motion.
Furthermore, you might also notice that PDFjs_Release3.9.179.mp4 shows the starting point of the display shifting towards the upper left direction. This might be a reason making the jerky appearance of the display.

**Comment by Snuffleupagus** [comment] 2023-08-28 11:22
> shows the starting point of the display shifting towards the upper left direction. This might be a reason making the jerky appearance of the display.

Works for me, since I cannot reproduce any such "shifting".

---

Can you reproduce this with the *latest version* of the demo viewer, see https://github.com/mozilla/pdf.js#online-demo?

**Comment by CIELOplus** [comment] 2023-08-30 05:08
I wasn't aware v3.10.111, so tested again online demo.
On Pixel 7 running Android 13, it worked with Firefox and Edge, except in combination with Chrome. Additionally, on Pixel 3 running Android 12, it worked with Firefox, Edge, and Chrome. There is no "shifting".
However, pinch zoom is smoother in Release 3.2.146 although it was not officially supported.
https://github.com/mozilla/pdf.js/assets/143143059/b92a4cf8-eaa3-4a10-a716-75b264e8c1bd
Is it impossible to achieve the smoothness of zooming like in Release 3.2.146?

And I will post another issue found during this test as a separate topic.
Pixel7 Android13+Chrome doesn't display correctly and iPhone iOS16.6+Firefox, Edge, Chrome shows distortion in pinch zooming.

**Comment by Snuffleupagus** [comment] 2023-08-30 05:47
> I wasn't aware v3.10.111, so tested again online demo.
> On Pixel 7 running Android 13, it worked with Firefox and Edge, except in combination with Chrome. Additionally, on Pixel 3 running Android 12, it worked with Firefox, Edge, and Chrome. There is no "shifting".

Given that Firefox, and particularly its *built-in* PDF Viewer is the primary development target for this library I think that we can close this issue as WFM then.

> Is it impossible to achieve the smoothness of zooming like in Release 3.2.146?

As already mentioned, that version didn't actually support proper pinch-to-zoom. Note that our implementation purposely, for performance reasons, uses CSS-zooming initially and only re-renders the PDF document once pinching stops; this could be the effect that you're seeing as "less smooth".

---

> And I will post another issue found during this test as a separate topic. Pixel7 Android13+Chrome doesn't display correctly and iPhone iOS16.6+Firefox, Edge, Chrome shows distortion in pinch zooming.

Please note that issues not affecting the *built-in* Firefox PDF Viewer are very likely to be platform and/or browser bugs, which are unfortunately (most of the time) not actionable in the PDF.js library itself.

**Closed by Snuffleupagus** 2023-08-30 05:47 UTC
Labels: information-requested
