### ISSUE TITLE
PDF.js in Adroid native browser (4.0.3 and 4.0.4)

### ISSUE THREAD

**Issue by jazzy-em** [mozilla/pdf.js#5568] opened 2014-12-21 06:30 UTC
Hello!
Viewer (http://mozilla.github.io/pdf.js/web/viewer.html) not working on Android native browser (i tested it on 4.0.3 and 4.0.4 devices). PDF-file is loaded (progress bar show progress), but not displayed.

**Comment by kyoK** [comment] 2015-01-15 11:19
Agree +1

**Comment by kyoK** [comment] 2015-01-20 19:22
any workaround ?

**Comment by timvandermeij** [comment] 2015-01-20 20:01
Is it only with the native Android browser? I cannot reproduce this with Firefox for Android on a Nexus 6 with Android 5.0.1.

**Comment by timvandermeij** [comment] 2015-01-20 20:02
Could you see if the console gives you an error message?

**Comment by kyoK** [comment] 2015-01-20 20:04
No, console does not show any error.

 

Loading icon is always present.

 

Atentamente,

 

Departamento de soporte al cliente 

ZICLOPE INGENIERIA INFORMATICA, SL

 

Web:   <http://www.ziclope.net/> www.ziclope.net

 

Email: info@ziclope.net

 

Teléfono de Ayuda: 807 499 181

 

 <http://www.ziclope.net/oficinas-y-horarios.htm> Horario de atención al cliente

 

Facebook:  <http://www.facebook.com/ziclope> http://www.facebook.com/ziclope

 

Twitter:  <http://twitter.com/ziclope> http://twitter.com/ziclope

 

 

Aviso legal:

 

Este mensaje electrónico está dirigido únicamente a la(s) dirección(es) indicadas anteriormente; el carácter confidencial, personal e intransferible del mismo está protegido legalmente. Cualquier revelación, uso o reenvío no autorizado, completo o en parte, está prohibido. Si ha recibido este mensaje por equivocación, notifíquelo inmediatamente a la persona que lo ha enviado y borre el mensaje original junto con sus ficheros anexos sin leerlo ni grabarlo, total o parcialmente.

 

Gracias. 

 

De: Tim van der Meij [mailto:notifications@github.com] 
Enviado el: martes, 20 de enero de 2015 21:03
Para: mozilla/pdf.js
CC: kyoK
Asunto: Re: [pdf.js] PDF.js in Adroid native browser (4.0.3 and 4.0.4) (#5568)

 

Could you see if the console gives you an error message?

**Comment by kyoK** [comment] 2015-01-20 20:07
Yes, native Android browser you can test it with Chrome:

 

Using device HTC:

 

Remember download to PC and test viewer.html directly. 

 



 

Atentamente,

 

Departamento de soporte al cliente 

ZICLOPE INGENIERIA INFORMATICA, SL

 

Web:   <http://www.ziclope.net/> www.ziclope.net

 

Email: info@ziclope.net

 

Teléfono de Ayuda: 807 499 181

 

 <http://www.ziclope.net/oficinas-y-horarios.htm> Horario de atención al cliente

 

Facebook:  <http://www.facebook.com/ziclope> http://www.facebook.com/ziclope

 

Twitter:  <http://twitter.com/ziclope> http://twitter.com/ziclope

 

 

Aviso legal:

 

Este mensaje electrónico está dirigido únicamente a la(s) dirección(es) indicadas anteriormente; el carácter confidencial, personal e intransferible del mismo está protegido legalmente. Cualquier revelación, uso o reenvío no autorizado, completo o en parte, está prohibido. Si ha recibido este mensaje por equivocación, notifíquelo inmediatamente a la persona que lo ha enviado y borre el mensaje original junto con sus ficheros anexos sin leerlo ni grabarlo, total o parcialmente.

 

Gracias. 

 

De: Tim van der Meij [mailto:notifications@github.com] 
Enviado el: martes, 20 de enero de 2015 21:02
Para: mozilla/pdf.js
CC: kyoK
Asunto: Re: [pdf.js] PDF.js in Adroid native browser (4.0.3 and 4.0.4) (#5568)

 

Is it only with the native Android browser? I cannot reproduce this with Firefox for Android on a Nexus 6 with Android 5.0.1.

**Comment by gabrielarcos** [comment] 2015-02-02 17:15
I don't know if is realated to this issue but I'm having some warnings with a Cordova app trying to use PDFjs on android 4.0.4:

Warning: Setting up fake worker.
Warning: Unhandled rejection: Error: SYNTAX_ERR: DOM Exception 12

**Comment by timvandermeij** [comment] 2015-02-02 19:52
Could be, thank you for adding that.

**Comment by Lord-of-Darkness** [comment] 2015-05-15 20:23
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by Lord-of-Darkness** [comment] 2015-05-15 20:25
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by Lord-of-Darkness** [comment] 2015-05-15 20:26
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by Lord-of-Darkness** [comment] 2015-05-15 20:30
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by Lord-of-Darkness** [comment] 2015-05-15 20:32
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by Lord-of-Darkness** [comment] 2015-05-15 20:32
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by vtliem** [comment] 2015-05-21 05:26
I have the same issues on Android 4.0-4.3.
If pdf file has no image, it works fine, but if has some images, it shows "loading " and blank pages (some pdfs with images works just fine).
I tried to fix by myself and found an "unhandled exception" in file pdf.worker.js at
```javascript
 PDFJS.createBlob
```
if I change code to:
```javascript
PDFJS.createBlob = function createBlob(data, contentType) {
  //if (typeof Blob !== 'undefined') {
  //  return new Blob([data], { type: contentType });
  //}
  //// Blob builder is deprecated in FF14 and removed in FF18.
  //var bb = new MozBlobBuilder();
  //bb.append(data);
	//return bb.getBlob(contentType);

	if (typeof Blob !== 'undefined') {
		try {

			var blob = new Blob([data], { type: contentType });
			console.warn("create Blob:" + contentType);
			return blob;
		} catch (e) {
			console.error("Error:PDFJS.createBlob(" + contentType + "," + data + ":" + data.length + ")");

			if (!window.BlobBuilder) {
				window.BlobBuilder = window.BlobBuilder ||
					 window.WebKitBlobBuilder ||
					 window.MozBlobBuilder ||
					 window.MSBlobBuilder;
			}
			if (e.name == 'TypeError' && window.BlobBuilder) {
				var bb = new BlobBuilder();
				bb.append(data);
				return bb.getBlob(contentType);
			}
			console.error("Error:PDFJS.createBlob exception:" + e);
			console.error(backtrace());
			return null;
		}
	}
	// Blob builder is deprecated in FF14 and removed in FF18.
	var bb = new MozBlobBuilder();
	bb.append(data);
	return bb.getBlob(contentType);
};
```
(logs added just for debug)
The pdf file will be displyed but missing some images (show as empty blocks)

sample pdf file for test is "Visual Studio Icon Library - Icons.pdf" of "VS2012 Modern Image Library" which can be downloaded at: http://www.microsoft.com/en-us/download/details.aspx?id=35825

Another issue when load pdf in android is "out of memory" with larger file when scroll cross number of pages.

**Comment by vtliem** [comment] 2015-05-21 09:21
finally, I found a workaround for my case.
If I use BlobBuilder, the pdf will be displayed with some missing imges (not throw a exception but doesn't show image). If use "falling back to data schema", all images are displayed.
So I changed code as showed blow:
```javascript
PDFJS.createBlob = function createBlob(data, contentType) {
		//if (typeof Blob !== 'undefined') {
		//  return new Blob([data], { type: contentType });
		//}
		//// Blob builder is deprecated in FF14 and removed in FF18.
		//var bb = new MozBlobBuilder();
		//bb.append(data);
		//return bb.getBlob(contentType);
		

		if (typeof Blob !== 'undefined') {
			try {

				var blob = new Blob([data], { type: contentType });
				//
				return blob;
			} catch (e) {
				if (e.name == 'TypeError') {
//bug in android browser?
					return null;
				}
				throw e;
			}
		}
		// Blob builder is deprecated in FF14 and removed in FF18.
		var bb = new MozBlobBuilder();
		bb.append(data);
		return bb.getBlob(contentType);
	};

```

and 
```javascript
PDFJS.createObjectURL = (function createObjectURLClosure() {
		// Blob/createObjectURL is not available, falling back to data schema.
		var digits =
		  'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';

		return function createObjectURL(data, contentType) {
			if (!PDFJS.disableCreateObjectURL &&
				typeof URL !== 'undefined' && URL.createObjectURL) {
				var blob = PDFJS.createBlob(data, contentType);
				//failed, use fallback method
				if (blob) {
					return URL.createObjectURL(blob);
				}
				
			}

			var buffer = 'data:' + contentType + ';base64,';
			for (var i = 0, ii = data.length; i < ii; i += 3) {
				var b1 = data[i] & 0xFF;
				var b2 = data[i + 1] & 0xFF;
				var b3 = data[i + 2] & 0xFF;
				var d1 = b1 >> 2, d2 = ((b1 & 3) << 4) | (b2 >> 4);
				var d3 = i + 1 < ii ? ((b2 & 0xF) << 2) | (b3 >> 6) : 64;
				var d4 = i + 2 < ii ? (b3 & 0x3F) : 64;
				buffer += digits[d1] + digits[d2] + digits[d3] + digits[d4];
			}
			return buffer;
		};
	})();
```

I don't known this changed will make any issue to lib, so I posted as a comment and hope this will help fix the issue soon.

**Comment by timvandermeij** [comment] 2016-05-10 19:25
The stock Android browser is not supported anymore since Android 4.4. We are currently at Android 6.0.1, so there is not much we can do about this. There are open issues for the WebView component in Android (such as #7157), so I'm closing this one.

**Closed by timvandermeij** 2016-05-10 19:25 UTC
Labels: 4-os-android

**Comment by twofaz** [comment] 2016-06-14 01:36
Use this!
https://crosswalk-project.org

**Comment by MaluNoPeleke** [comment] 2016-06-23 13:42
Why is there no integrated PDF.js viewer in Firefox for Android?
Everytime I click on a PDF with my mobile phone (Android Marshmallow, Firefox Beta 48) it gets downloaded instead of displayed inside of the browser.
The extension is deprecated: https://addons.mozilla.org/de/android/addon/pdfjs/

**Comment by sapq** [comment] 2017-06-08 03:49
is this proplem  fix ????

i need to fix this proplem  i have  app on google play i have  500K Download  but this  proplem  make my app have  lose many pople 

pls  we want fix this proplem

**Comment by xcarpentier** [comment] 2018-05-31 06:56
Any news on it?

**Comment by ktbby** [comment] 2019-04-02 05:04
any version of pdf.js that is compatible with android version 4.0? even if it is old one.
