### ISSUE TITLE
Provisional header are shown

### ISSUE THREAD

**Issue by valiantboymaksud** [mozilla/pdf.js#14089] opened 2021-09-28 01:35 UTC
<img width="1020" alt="Screen Shot 2021-09-27 at 10 53 33 PM" src="https://user-images.githubusercontent.com/39328011/135007569-a76d3d74-0186-4edc-afa5-e9f82af4a25b.png">

Using the latest version.

I want to load pdf from google drive, but it fetches failed. I added required headers such as allow-control-access-origin, but the same issue. Please look at the attachment, and please anyone give me a solution.
Thanks.

**Comment by Snuffleupagus** [comment] 2021-09-28 07:11
Duplicate of #14086

**Closed by Snuffleupagus** 2021-09-28 07:11 UTC

**Comment by valiantboymaksud** [comment] 2021-09-28 15:04
I am unable to achieve my goal.
