### ISSUE TITLE
Extracted data and rendered data of a PDF file is differ in PDF.js version 2.0.943

### ISSUE THREAD

**Issue by nikhilshinde57** [mozilla/pdf.js#10821] opened 2019-05-15 05:14 UTC
**Configuration:**
- Web browser: Firefox
- Operating system: macOS Mojave version 10.14.4
- PDF.js version: 2.0.943
- Is a browser extension: No
   
**Steps to reproduce the problem:**

1. Open developer tool in browser and attach debugger in _calculateMatch. 
2. Click on Find in document button then enter word and search that word.
3. The controller will hit that debugger point now check the page content. 

**Expected behavior:** 

Render a pdf file in the browser using PDF.js as shown below. 

<img width="1251" alt="Screenshot 2019-05-14 at 10 27 08 AM" src="https://user-images.githubusercontent.com/11044864/57749872-7ac44f80-76fd-11e9-8fac-004a43ac8f0b.png">

Click on any word like I click on word “Chronic” then it will highlight that word. 
Next when I am extracting that same page data in the background function _calculateMatch(Default PDF.js function) which is in file viewer.js that time the data which we are getting is not as it is shown on web browser. The some of the word are concatenated with other words. They are not separated out. But on web browser the word shown as separate single and that word is also represented as single in div if you inspect that word on web browser. 

<img width="1672" alt="Screenshot 2019-05-14 at 10 54 12 AM" src="https://user-images.githubusercontent.com/11044864/57749650-8cf1be00-76fc-11e9-8063-696c8a3df2d5.png">

**What went wrong:**

<img width="1639" alt="Screenshot 2019-05-15 at 10 28 44 AM" src="https://user-images.githubusercontent.com/11044864/57749593-469c5f00-76fc-11e9-9e2e-c359e39cc94a.png">

As shown in above screenshot. In the left hand side the word “Chronic” is a single separate word. But in the left hand side for that same page the extracted page data is shown in blue coloured. In that the word “Chronic” is concatenated with previous line end word and shown as “DATE:01/09/2015Chronic”. What is the expected result is the word “Chronic” should be separated in extracted page data in left hand side. 

**What causes this to me:**
My requirement is also to highlight the word but I am doing this not form “Find in Document” button but for that I have my custome code wil at the end use PDF.js functions. But I have some condition listed below:
The condition to highlight word or phrase is like 
e.g. Requirement is highlight word “Chronic” word 
**Condition:**
Word should be single 
e.g Chronic pulmonary heart disease - Highlight this word
Word should be separate 
e.g Chronic pulmonary heart disease - Highlight this word
Should not concatenated with any other word 
e.g XYZChronic pulmonary heart - Do not highlight this
Should not be substring in any other word
e.g XYZChronicpulmonary heart - Do not highlight this

But as explained above in extracted page content the word “Chronic” is concatenated with previous line word my condition fails and that word is not getting highlighted.

**Comment by Snuffleupagus** [comment] 2019-05-16 09:13
This is most likely a duplicate of an existing issue (which I cannot find right now), but in any case it's not really meaningful to keep this open since it's not actionable without a test-case (it's missing the `Attach (recommended) or Link to PDF file here:` part of the [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md)).

**Closed** 2019-05-16 19:19 UTC
Labels: 4-text-selection
