### ISSUE TITLE
pdf.worker.js: Invalid XRef stream header for every PDF.

### ISSUE THREAD

**Issue by TBNijon** [mozilla/pdf.js#6882] opened 2016-01-16 11:20 UTC
Hope this is the right place to ask this question (I don't know for sure, because it isn't actually an issue with pdf.js itself, but more with my implementation of it). If it isn't, I will be glad to move this question to the appropriate page.

Whenever I try to display a PDF using pdf.js I get the following error:

```
Error: Invalid XRef stream header

XRef_readXRef@[...]/pdf.js/build/generic/build/pdf.worker.js:23811:13
XRef_parse@[...]/pdf.js/build/generic/build/pdf.worker.js:23394:23
PDFDocument_setup@[...]/pdf.js/build/generic/build/pdf.worker.js:40294:7
PDFDocument_parse@[...]/pdf.js/build/generic/build/pdf.worker.js:40175:7
LocalPdfManager_ensure/<@[...]/pdf.js/build/generic/build/pdf.worker.js:40484:22
LocalPdfManager_ensure@[...]/pdf.js/build/generic/build/pdf.worker.js:40479:1
BasePdfManager_ensureDoc@[...]/pdf.js/build/generic/build/pdf.worker.js:40413:14
loadDocument/</<@[...]/pdf.js/build/generic/build/pdf.worker.js:40746:11 

Warning: Indexing all PDF objects

InvalidPDFException: Invalid PDF structure
```

Where I have replaced the path leading to the pdf.js directory with [...], and which is prepended by a whole list of warnings, for just about any character, like these:

```
Warning: Ignoring invalid character "114" in hex string 
Warning: Ignoring invalid character "115" in hex string 
Warning: Ignoring invalid character "45" in hex string
```

Now, this looks like I am trying to display a corrupt PDF (which was my first thought). However, no matter what example PDF I plug in, it always results in exactly the same error, including the same number and ordering of *Invalid Character Warnings*. This strikes me as very peculiar, because I would not suspect that two PDFs would have characters in the exact same ordering.

This led me to believe that it might be loading a corrupt PDF from the cache, but after clearing it the problem persisted. I also updated my PDF.js plugin to the latest version, and again to the most recent release. This also did not result in any improvements.

To determine if this really occurred with every PDF, I eventually use this piece of Javascript code, loading the (certainly not corrupt) example PDF of this github page:

```javascript
var url = encodeURIComponent('compressed.tracemonkey-pldi-09.pdf');
PDFJS.getDocument('http://mozilla.github.io/pdf.js/web/viewer.html?file=' + url).then(function(pdfFile) {
...
});
```

*Note that this url var is declared separately because that is how I would normally load the value of the PDF I want to obtain.*

I load these scripts:

```html
<script type="text/javascript" src="{% static 'website/search/pdf.js/build/generic/build/pdf.js' %}"></script>
<script type="text/javascript" src="{% static 'website/search/pdf.js/build/generic/web/compatibility.js' %}"></script>
```

Where these files are the ones generated by running
```
node make generic
```
after following the _getting started_ instructions from the github page.

Is there anybody here that can help me detect this problem? Did I miss something obvious? Do you require additional information? And again, if this isn't the correct place to ask this question, please refer me to the location where it should be.

Thanks in advance.

**Comment by timvandermeij** [comment] 2016-01-16 12:52
I think the problem is this line: `PDFJS.getDocument('http://mozilla.github.io/pdf.js/web/viewer.html?file=' + url)`. You should be feeding the file *itself* (PDF content) to the `getDocument` call, whereas you are now feeding it HTML content because of the web page. Most likely `PDFJS.getDocument(url)` will be better. If not, please setup a demo page somewhere (own server, JSBin, JSFiddle, et cetera) so we can try to debug the issue.

**Comment by TBNijon** [comment] 2016-01-16 13:05
Thank you very much, your solution has indeed fixed my problem. I don't know why I was feeding it the HTML content of that page, it must have been a remnant from an example I have used some time ago. Thanks for the rapid response; is there any way I should tag your answer as correct / up vote something? If not, I will close the thread afterwards.

**Comment by timvandermeij** [comment] 2016-01-16 13:31
You're welcome, I'm glad you can use PDF.js now! I'll close the issue for you, as that indicates that the issue is solved. If you have more questions, feel free to contact us on IRC or the mailing list.

**Closed by timvandermeij** 2016-01-16 13:31 UTC
Labels: 4-information-requested
