### ISSUE TITLE
PDF missing parts

### ISSUE THREAD

**Issue by gitarra** [mozilla/pdf.js#7498] opened 2016-07-21 14:31 UTC
Link to PDF file (or attach file here): http://www.liikennevirasto.fi/documents/20473/23384/Rataverkkokartta+2015/f1800f35-d3f7-4723-bb6e-c0091a75cff3

Configuration:
- Web browser and its version: Firefox Nightly 50.0a1 (2016-07-21)
- Operating system and its version: Ubuntu 16.04
- PDF.js version: PDF.js: 1.5.337
- Is an extension: No

Steps to reproduce the problem:
1. Open PDF
2. PDF is missing parts

What is the expected behavior? (add screenshot)

![correct](https://cloud.githubusercontent.com/assets/4739888/17026253/288ddcb4-4f68-11e6-927e-90d40da7524d.png)

What went wrong? (add screenshot)

![incorrect_pdfjs](https://cloud.githubusercontent.com/assets/4739888/17026261/317d0368-4f68-11e6-822b-ad48ee3ce07a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://nightly.mozilla.org/

**Comment by timvandermeij** [comment] 2016-07-21 14:33
This might be a duplicate of #7486.

**Comment by timvandermeij** [comment] 2016-07-21 14:39
The fix for the referenced bug landed today, so it will probably be in today's or tomorrow's Nightly. @gitarra Could you confirm if upstream fixed this bug in that Nightly?

**Comment by gitarra** [comment] 2016-07-21 14:41
Well how did I miss that.. I will check if its fixed and report back.

**Comment by Snuffleupagus** [comment] 2016-07-21 14:46
Based on the result of `mozregression`, see http://mozilla.github.io/mozregression/, I'm closing this as a duplicate of issue #7498.

**Closed by Snuffleupagus** 2016-07-21 14:46 UTC
Labels: 3-upstream, 4-firefox-specific
