### ISSUE TITLE
Converting an XFA form to images shows Adobe Reader upgrade warning

### ISSUE THREAD

**Issue by nonprofittechy** [mozilla/pdf.js#14421] opened 2022-01-05 22:22 UTC
Attach (recommended) or Link to PDF file here: [XFA-PDF-Sample.pdf](https://github.com/mozilla/pdf.js/files/7818063/XFA-PDF-Sample.pdf)

Configuration:
- Web browser and its version: n/a
- Operating system and its version: WSL2  on Windows 11
- PDF.js version: Latest: https://github.com/mozilla/pdf.js/commit/290cbc523281cb86fdf0117cf8f2cae521518fb9
- Is a browser extension: no

Steps to reproduce the problem:
1. I used pdf.js gulp-dist and the example [pdf2svg.js](https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2svg.js) file to convert the attached [XFA-PDF-Sample.pdf](https://github.com/mozilla/pdf.js/files/7818063/XFA-PDF-Sample.pdf) to SVG.
2. It output the attached SVG file, which displays the Adobe Reader upgrade warning (note I could not attach an SVG here--I put in a screenshot instead).

What is the expected behavior? (add screenshot)

The output should look like this (Adobe Reader)

![image](https://user-images.githubusercontent.com/7645641/148297175-156b75cd-cba2-4be7-b45f-804b2578ccc5.png)

Or at least this (interactive pdf.js)

![image](https://user-images.githubusercontent.com/7645641/148297015-c6bec001-8ec6-4b59-9d35-4d83eeccb7a9.png)

The XFA form renders just fine in pdf.js interactively.

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/7645641/148296682-dcb021b1-c43d-417c-8023-3b9199775fb2.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

The viewer is fine, although it is missing the embedded image. The issue is only with the commandline version.

### What I'm doing

I'm trying to both batch convert XFA PDFs to regular Acroform PDFs as well as do frequent one-off conversions. This will be just one part of the process. It would be great to use the commandline tool, but I figured out [a workaround](https://www.nonprofittechy.com/2022/01/05/batch-convert-adobe-livecycle-xfa-forms-into-ordinary-pdfs/) thanks to help from the Mozilla team which uses pdf.js as a server and then Chrome headless to save to a PDF.

Ideally, it would be great to be able to save directly to PDF to avoid this complex workaround. Even being able to save to SVG and then convert the SVG to PDF would be better than running two extra servers to do the conversion.

This will be part of an open source project, https://suffolklitlab.org/form-explorer/, to help courts improve legacy PDF form processes.

**Comment by Snuffleupagus** [comment] 2022-01-06 10:14
> I used pdf.js gulp-dist and the example [pdf2svg.js](https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2svg.js) file

As outlined in the FAQ, please note that the SVG-backend is *not officially* supported nor has it received any meaningful development since it was first introduced in 2014; see also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends
Please note that maintaining *two separate* backends doesn't seem entirely feasible/reasonable for the PDF.js project, especially when the SVG-backend often performs worse in practice (given that browsers don't handle huge amounts of DOM elements well).

Please keep in mind that the `pdf2svg` example is thus quite old and that it doesn't (in any way) support working with XFA documents; hence this not working (as you'd hope) is thus somewhat expected unfortunately.

> The viewer is fine, although it is missing the embedded image.

That part would be a duplicate of issue #13707.

**Closed by Snuffleupagus** 2022-01-06 10:14 UTC
