### ISSUE TITLE
Numeric destination in URL taken as page number

### ISSUE THREAD

**Issue by AlainArachnid** [mozilla/pdf.js#7746] opened 2016-10-21 19:23 UTC
**Link to PDF file (or attach file here):**
http://unesdoc.unesco.org/images/0021/002160/216066f.pdf#216095
http://unesdoc.unesco.org/images/0013/001346/134685E.pdf#4.3
http://unesdoc.unesco.org/images/0013/001346/134685E.pdf#4

**Configuration:**
- Web browser and its version:
Firefox 49.0.2
- Operating system and its version:
Windows 10
- PDF.js version:
[don't know], the regular version for Fx 49
- Is an extension:
[don't know]

**Steps to reproduce the problem:**
Open the 3 PDFs given above in Firefox+pdf.js or IE + Acrobat Reader

**What is the expected behavior? (add screenshot)**
The expected behavior is Acrobat Reader's behavior : the document opens at the given destination which is on
page 14 for first example
page 42 for second example
page 41 for third example

**What went wrong? (add screenshot)**
With pdf.js, only the second example opens correctly
The first one opens on first page
The third one opens on page 4

I suspect that pdf.js takes the destination as a page number when the destination is a integer decimal number (in the first example, the given number is too big)

At UNESCO, we rely heavily on destinations often formed of a single integer number and the behavior of pdf.js does not allow to get the correct document part

**Comment by Snuffleupagus** [comment] 2016-10-21 19:35
To prevent issues in cases where it's ambiguous whether the part after `#` is to be interpreted as a named destination, or as a page number, you should use the `#nameddest=...` form instead; please also see [Parameters for Opening PDF Files](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf#G4.1500435).

Hence if you change the links like below, things should work as intended:
http://unesdoc.unesco.org/images/0021/002160/216066f.pdf#nameddest=216095
http://unesdoc.unesco.org/images/0013/001346/134685E.pdf#nameddest=4.3
http://unesdoc.unesco.org/images/0013/001346/134685E.pdf#nameddest=4

**Comment by AlainArachnid** [comment] 2016-10-21 19:49
Thank you for your comments and for the link to the Adobe specification

This specification has a special paragraph 3 pages later "Specifying parameters in a URL" with examples.
For destination, the only example does not use the syntax "nameddest=xxx" but takes the destination directly behind the #

However, as the syntax nameddest=xxx works on recent Adobe readers (tested on reader XI and reader DC), I shall change the generated URLs to be compatible with Acrobat Reader and pdf.js

Thanks again for the hint. Do I close the issue?

**Comment by Snuffleupagus** [comment] 2016-10-22 10:46
Given that other PDF viewers, e.g. Adobe Reader, does not seem to support page numbers after the `#`, I'm actually starting to wonder if we ought to [remove this code](https://github.com/mozilla/pdf.js/blob/master/web/pdf_link_service.js#L261-L262) to improve our compatibility with other viewers!?

**Comment by timvandermeij** [comment] 2016-10-22 13:16
If other PDF viewers do not support this, removing it may indeed prevent confusion. Is it also not present in the specification?

**Comment by Snuffleupagus** [comment] 2016-10-23 15:18
> Is it also not present in the specification?

Based on a cursory search, I'm not finding any mention of this in the [PDF specification](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf) *itself*.
Besides comparing the actual behaviour with Adobe Reader, the only official document that I'm aware of is http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf.

**Comment by AlainArachnid** [comment] 2016-10-23 19:44
Older version 6.0 of the document gives only the "nameddest=xxx" syntax in the examples
http://partners.adobe.com/public/developer/en/acrobat/PDFOpenParams.pdf#page=7

Does not specify what happen when a number alone is given...

**Comment by timvandermeij** [comment] 2016-10-27 14:17
Pull request #7749 has been merged that fixes most of this issue. Should we close it or do we want to remove the page number feature altogether for better compatibility with other viewers?

**Comment by yurydelendik** [comment] 2016-10-27 14:23
Let's remove it for the extensions and mark with deprecate warning for generic viewer.

**Comment by Snuffleupagus** [comment] 2016-10-27 19:37
> Pull request #7749 has been merged that should fix this issue.

That PR only fixed http://unesdoc.unesco.org/images/0013/001346/134685E.pdf#4.3, the other ones are still an issue since other PDF viewers don't seem to support this form.
It should be possible to deprecate this in a way that provides a good fallback behaviour, I'll submit a PR for consideration.

**Closed** 2016-10-27 21:56 UTC
Labels: 1-viewer
