### ISSUE TITLE
[Bug]: Cannot edit or delete existing pdf document ink annotations

### ISSUE THREAD

**Issue by heyong3235** [mozilla/pdf.js#18987] opened 2024-11-01 11:57 UTC
### Attach (recommended) or Link to PDF file

When using pdf.js to open the last saved pdf file, the pdf file has ink type annotations, which cannot be edited or deleted when opened again. Other types of annotations can be edited or deleted by double-clicking

### Web browser and its version

Edge

### Operating system and its version

win11

### PDF.js version

4.7.76

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1.When using pdf.js to open the last saved pdf file, the pdf file has ink type annotations, which cannot be edited or deleted when opened again. Other types of annotations can be edited or deleted by double-clicking

### What is the expected behavior?

1.Can edit or delete existing PDF annotations normally

### What went wrong?

1.When using pdf.js to open the last saved pdf file, the pdf file has ink type annotations, which cannot be edited or deleted when opened again. Other types of annotations can be edited or deleted by double-clicking

**Comment by marco-c** [comment] 2024-11-01 12:00
Duplicate of #16883.

**Closed by marco-c** 2024-11-01 12:00 UTC
