### ISSUE TITLE
Unsupported pdf notification message buttons not working anymore if canceling print/save action

### ISSUE THREAD

**Issue by bogdanmaris** [mozilla/pdf.js#12284] opened 2020-08-26 08:53 UTC
**Affected versions**
* Firefox 81.0b2
* Latest Nightly 82.0a1

**Affected platforms**
* Windows 10 64bit
* MacOS 10.15.6
* Ubuntu 18.04 64bit

**Steps to reproduce**
1. Open a pdf with form (eg: https://www.irs.gov/pub/irs-pdf/f1040.pdf)
2. Click inside the pdf so that the yellow notification bar will appear
2. Click the print button inside pdf/Hit CTRL+S
3. Cancel the print action/save action
4. Reload/close the tab with the pdf
5. Click `Open With Different Viewer` or `X` button from the yellow notification bar

**Expected result**
* The buttons from yellow notification bar can be used.

**Actual result**
* Clicking the buttons from yellow notification bar does nothing.

**Regression range**
* First bad: 79f9ec2f6fece69848aefefb9300fa3d35aa5593
* Last good: 9877228c87db0fe7f1dd353ff8bc5981f52d8622
* Pushlog: https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=9877228c87db0fe7f1dd353ff8bc5981f52d8622&tochange=79f9ec2f6fece69848aefefb9300fa3d35aa5593
* Potential regressor: Bug 1660617 - Update pdf.js to version 2.6.302 / https://github.com/mozilla/pdf.js/pull/12265

**Additional notes**
* These are the errors thrown in Browser console:
`InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable PdfjsParent.jsm:276:12`
`Uncaught DOMException: An attempt was made to use an object that is not, or is no longer, usable PdfjsParent.jsm:276`

**Suggested severity**
* I my opinion this should have the S2 severity since the notification will be stuck on the page and user has to close the tab to get rid of it.

**Comment by Snuffleupagus** [comment] 2020-08-26 09:07
> Potential regressor: Bug 1660617 - Update pdf.js to version 2.6.302 / #12265

Huh, those changes really cannot be responsible for the problem described here...

> These are the errors thrown in Browser console:
> ```
> InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable PdfjsParent.jsm:276:12
> Uncaught DOMException: An attempt was made to use an object that is not, or is no longer, usable PdfjsParent.jsm:276

... note how these errors mention files not even found in this repository, but only found in mozilla-central.

**Comment by Snuffleupagus** [comment] 2020-08-26 09:29
> * First bad: 79f9ec2f6fece69848aefefb9300fa3d35aa5593
> 
> * Last good: 9877228c87db0fe7f1dd353ff8bc5981f52d8622
> 
> * Pushlog: https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=9877228c87db0fe7f1dd353ff8bc5981f52d8622&tochange=79f9ec2f6fece69848aefefb9300fa3d35aa5593
> 
> * Potential regressor: Bug 1660617 - Update pdf.js to version 2.6.302 / #12265

As it turns out, it's actually very easy to determine that the above isn't relevant and that it's rather an older and more general problem.

__Steps to reproduce__:
 1. Open any "regular" PDF document, e.g. http://mirrors.ctan.org/info/lshort/english/lshort.pdf
 2. Open the web-console, using e.g. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>.
 3. Execute `PDFViewerApplication.fallback();` in the web-console.
 4. Re-load the tab, using e.g. <kbd>F5</kbd>.
 5. Click `Open With Different Viewer` or `X` button from the yellow notification bar.

Here you'll notice the same error message, as mentioned above, in the browser-console for a document *without* forms.

**Comment by timvandermeij** [comment] 2020-08-26 20:32
Does this have something to do with #12285 or is that unrelated?

**Comment by Snuffleupagus** [comment] 2020-08-26 20:58
> Does this have something to do with #12285 or is that unrelated?

Unfortunately it's unrelated, since the errors mentioned above happens on browser-side (and in the parent process nonetheless, rather than in the content process).

**Comment by Snuffleupagus** [comment] 2020-11-20 20:38
This is actually a (forward) duplicate of #12305, which is has been fixed now!

**Comment by Snuffleupagus** [comment] 2020-11-20 20:39
This is actually a (forward) duplicate of #12305, which was fixed a while back!

**Closed** 2020-11-21 13:34 UTC
Labels: 1-viewer
