### ISSUE TITLE
Images are rendered blank in pdf.js viewer

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#18084] opened 2024-05-14 06:45 UTC
Attach (recommended) or Link to PDF file here:
[Uploading Example1_page8.pdf…]()

Certain images which were rendered fine in earlier versions of pdf.js are now not rendering as blank. 
Configuration:
- Web browser and its version: chrome 124.0.6367.202
- Operating system and its version: Windows 11
- PDF.js version: pdf.js 4.2.67
- Is a browser extension:

Steps to reproduce the problem:
1. Open the attached pdf in pdf.js viewer. 
2.

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/79515387/ec946b12-5604-4ff6-8218-fc1a2bc94c24)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/79515387/15aaee15-de4c-4897-96de-755dc3d04ba4)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2024-05-14 07:00
> Attach (recommended) or Link to PDF file here:

No issue is valid without this information. Please don't keep reporting incomplete and non-actionable issues, since that just wastes our time!

> Configuration:
>     * Web browser and its version: chrome
>     * Operating system and its version: Windows
>     * PDF.js version: pdf.js latest
>     * Is a browser extension

You need to provide actual *numbers* here, since "latest" is not helpful.

**Comment by mirnalinikarthik** [comment] 2024-05-14 09:33
Updated the pdf.js version. The above issue is not seen in pdf.js 2.5.207 version.

**Comment by mirnalinikarthik** [comment] 2024-05-15 05:29
[Example1_page8.pdf](https://github.com/mozilla/pdf.js/files/15316643/Example1_page8.pdf)

**Comment by calixteman** [comment] 2024-05-15 07:37
It's a regression from:
https://github.com/mozilla/pdf.js/pull/13361

**Comment by Snuffleupagus** [comment] 2024-05-15 07:41
Duplicate of #16038

**Closed by Snuffleupagus** 2024-05-15 07:41 UTC
Labels: shading-pattern, tiling-type
