### ISSUE TITLE
The PDF file is displayed on the mobile terminal, the font is very small, the font size is modified, the interface is displayed without any effect, and what solution is there?

### ISSUE THREAD

**Issue by LJZJIANG** [mozilla/pdf.js#9680] opened 2018-04-20 03:49 UTC
![image](https://user-images.githubusercontent.com/29171486/39029863-d10a1e92-4490-11e8-9722-37443760fa39.png)

**Comment by timvandermeij** [comment] 2018-04-20 21:38
Closing since almost no information from the issue template is provided, in particular configuration information, a working example and the PDF file to reproduce the issue.

**Closed by timvandermeij** 2018-04-20 21:38 UTC
