### ISSUE TITLE
Garbage characters in chinese and some character can not display

### ISSUE THREAD

**Issue by chip-man** [mozilla/pdf.js#14078] opened 2021-09-26 03:39 UTC
Attach (recommended) or Link to PDF file here:
[education.pdf](https://github.com/mozilla/pdf.js/files/7230639/education.pdf)

Configuration:
- Web browser and its version: chrome 92.0.4515.159
- Operating system and its version: Ubuntu 20.04 LTS
- PDF.js version: 2.9.359
- Is a browser extension: no

Steps to reproduce the problem:
1. follow the official document to use pdf.js (http://mozilla.github.io/pdf.js/examples/)

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/56503594/134792007-189189ab-5468-4d38-9570-8639a9efac7e.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/56503594/134792052-59f25303-8908-4f94-a76b-d7eaf588f712.png)

Related information
Firstly,I have read the pdf.js code and console the  param in "showText" method. The attribute "fontChar" which will be used in canvas render is a garbage characters,but the attribute "unicode" is correct characters in chinese.
Secondly,some character can't display and i find "font.missingFile" , "glyph.isInFont" is false.

![image](https://user-images.githubusercontent.com/56503594/134792495-ac4dc717-2902-4204-acec-9ab96ccae95d.png)
![image](https://user-images.githubusercontent.com/56503594/134792504-eafc8f8a-e0e3-4004-9f37-7d2ddb9f1993.png)
![image](https://user-images.githubusercontent.com/56503594/134792553-3b1ae15a-b445-4bb1-86ef-d35cff60f8ea.png)

When i use browser to open the pdf,there is no problem.

**Comment by Snuffleupagus** [comment] 2021-09-26 08:16
Duplicate of #13309

**Closed by Snuffleupagus** 2021-09-26 08:16 UTC
