### ISSUE TITLE
Questions regarding disabling Worker

### ISSUE THREAD

**Issue by estcap2** [mozilla/pdf.js#8503] opened 2017-06-08 14:45 UTC
I have some basic questions regarding **disableWorker**.

1. What would be the benefits and disadvantages of disabling the worker?
2. In my implementation what really takes time is the worker's loading. Does **disableWorker** prevent **pdf.js** invoking the worker?
3. And lastly, can I call **disableWorker** just before the document is loaded or am I missing something?

Thanks in advance

**Comment by yurydelendik** [comment] 2017-06-08 15:56
> What would be the benefits and disadvantages of disabling the worker?

Mostly there are no advantages for disabling worker. This option was introduce for compatibility with IE9 and as a workaround for legacy browser bugs.

>  In my implementation what really takes time is the worker's loading. Does disableWorker prevent pdf.js invoking the worker?

Loading pdf.worker.js code loading in web page or worker shall have no difference (notice that when disableWorker = true, pdf.worker.js code is still loaded by on main page). The pdf.worker.js is not loaded until getDocument is invoked or PDFWorker is created, that gives a web page fast load time -- pdf.js is relatively small.

>  And lastly, can I call disableWorker just before the document is loaded or am I missing something?

That's correct. But why do you want to disable worker?

Closing as answered.

**Closed by yurydelendik** 2017-06-08 15:56 UTC

**Comment by estcap2** [comment] 2017-06-08 16:31
Thanks for your answer!
In my implementation, a PDF is encoded in a Uint8Array and is loaded with the entire page.
I use this method since my PDFs are in a DB. This way I have a single PDF loaded which doesn't change in a given page. One calls `https://myimplementation/pdf/pdfID` and that single PDF identified by **pdfID** is loaded in that window until page closed.
It is a quite simple implementation, but I wanted to disable the worker to try to narrow down the source of an issue where several tabs with different **pdfID** fail to load at the same time.
For example if I have 3 PDFs one with **pdfID** A , other B and C. I open A in a tab of chrome and loads fine. I open B in other tab and fails and nothing prompts in developer console. I open A again in other tab and loads perfectly . C fails.
If I clean cache and open first B, then A and C can´t be loaded.
My guess was maybe simplifying the implementation and removing the worker which might use a cache of sorts might enlighten me to which was the real issue.

**Comment by yurydelendik** [comment] 2017-06-08 17:42
If you cannot reproduce the same issue with http://mozilla.github.io/pdf.js/web/viewer.html (it's using workers) in multiple tabs, then it's luckily something wrong with your server code or way PDFs are delivered.

**Comment by shabyWoks** [comment] 2019-12-20 11:12
can we avoid installation of pdf.worker.js?

**Comment by speedplane** [comment] 2021-09-01 17:14
I know this question is closed, but does anyone know what the advantage of using a worker is? Will the PDF load faster, or are some things prefetched? 

I'm asking because I have certain PDFs that are only opening with `disableWorker=True`, and want to know what I'm losing if I set that true permanently.

**Comment by alshdavid** [comment] 2023-10-27 02:08
I too am wondering how best to use this in the context of bundlers, given the worker needs to be an external script and pdfjs is being bundled.

**Comment by sovetski** [comment] 2025-10-26 20:53
> Mostly there are no advantages for disabling worker. This option was introduced for compatibility with IE9 and as a workaround for legacy browser bugs.

In 2025 we don't really need to support IE9 or old browsers, how to disable this worker option?
