### ISSUE TITLE
Table not rendering properly

### ISSUE THREAD

**Issue by keedap** [mozilla/pdf.js#7291] opened 2016-05-04 09:26 UTC
Link to PDF file (or attach file here):
[ContentSharingSuite Solution Architecture.pdf](https://github.com/mozilla/pdf.js/files/248464/ContentSharingSuite.Solution.Architecture.pdf)

Configuration:
- Web browser and its version: Firefox v45.0.2
- Operating system and its version: Windows 7 
- PDF.js version:
- Is an extension: No

Steps to reproduce the problem:
1.  Open the file in the browser and view the table on page 10
white artifact lines are shown
2.

What is the expected behavior? 
![original](https://cloud.githubusercontent.com/assets/496359/15010155/48cc2370-1208-11e6-849e-73428e0e8cb3.JPG)

What went wrong? (add screenshot)
![errorview](https://cloud.githubusercontent.com/assets/496359/15010158/4deece5c-1208-11e6-9cf1-823743e2b27a.JPG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2016-05-04 09:33
I've not looked into the PDF file, but this issue is most likely a duplicate of e.g. #4860.

**Comment by Snuffleupagus** [comment] 2016-05-04 10:59
Closing as duplicate of issue #4860.

**Closed by Snuffleupagus** 2016-05-04 10:59 UTC
