### ISSUE TITLE
print blank pages from firefox and chrome

### ISSUE THREAD

**Issue by alonisoft** [mozilla/pdf.js#7644] opened 2016-09-18 08:50 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: chrome 53 + firefox 48.02
- Operating system and its version: windows 10 pro 64 bit
- PDF.js version: in my site 1.4.20 + current in your site : http://mozilla.github.io/pdf.js/web/viewer.html
- Is an extension:
just open the embeded file in a new tab (not download only view) and let the browser deal with printing.

![blank](https://cloud.githubusercontent.com/assets/3242708/18614171/7ea58612-7d92-11e6-9fd1-745e0b706ebf.PNG)

Steps to reproduce the problem:
**print blank pages**

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by alonisoft** [comment] 2016-09-19 08:44
my suggestion on All Printing issues - open the embeded file in a new tab (not download only view) and let the browser deal with printing !

**Comment by yurydelendik** [comment] 2016-10-06 13:24
I cannot reproduce with provided steps. WFM. Closing as incomplete.

**Closed by yurydelendik** 2016-10-06 13:24 UTC
Labels: 4-printing
