### ISSUE TITLE
github-bugzilla-pr-linker being decommissioned

### ISSUE THREAD

**Issue by willkg** [mozilla/pdf.js#15354] opened 2022-08-26 15:15 UTC
We're decomissioning github-bugzilla-pr-linker. See https://github.com/mozilla/github-bugzilla-pr-linker/issues/41 for details.

**Comment by timvandermeij** [comment] 2022-08-27 11:04
Does this affect PDF.js in any way? As far as I know we're not using this project here, unless I'm mistaken?

**Comment by Snuffleupagus** [comment] 2022-08-27 11:20
I *believe* it's being used currently, given comments such as https://bugzilla.mozilla.org/show_bug.cgi?id=1787456#c5

**Comment by marco-c** [comment] 2022-08-29 09:45
Yes, we introduced it recently. We can switch to the addon then, it'll be worse as we'll have to manually link things, but better than nothing.
@willkg I have the addon installed, do you know why I don't see the links in PRs such as https://github.com/mozilla/pdf.js/pull/15009?

**Comment by Snuffleupagus** [comment] 2022-08-29 09:50
> @willkg I have the addon installed, do you know why I don't see the links in PRs such as #15009?

I can also reproduce this intermittently, however I've found that *refreshing* the page seems to fix things.

**Comment by marco-c** [comment] 2022-08-29 11:18
@willkg also, the addon doesn't play nice with containers (I have GitHub opening in a "work" container and Bugzilla opening in the default container). Should I file an issue?

**Comment by Snuffleupagus** [comment] 2022-08-31 12:06
Can we close this issue, since I don't believe that there's anything (more) that we do on the PDF.js side of things?

**Closed** 2022-08-31 12:20 UTC
Labels: other

**Comment by willkg** [comment] 2022-09-06 12:26
> @willkg I have the addon installed, do you know why I don't see the links in PRs such as #15009?

I don't know. I haven't been having any issues. Maybe another extension you're using is modifying the github page? Can you write up an issue here? https://github.com/willkg/rob-bugson/issues

> @willkg also, the addon doesn't play nice with containers (I have GitHub opening in a "work" container and Bugzilla opening in the default container). Should I file an issue?

Because rob-bugson is effectively redirecting you to bugzilla in a new tab, I'm not sure why it's not playing nice with containers (or even what that entails). Can you write up an issue with details?

> Can we close this issue, since I don't believe that there's anything (more) that we can do on the PDF.js side of things?

I wrote up this issue to give you notice that I was decommissioning the service so you weren't surprised. You can remove the webhook in pdf.js project, but you don't _have_ to do anything.

**Comment by marco-c** [comment] 2022-09-06 20:09
> I don't know. I haven't been having any issues. Maybe another extension you're using is modifying the github page? Can you write up an issue here? https://github.com/willkg/rob-bugson/issues

I see intermittently just like @Snuffleupagus mentioned

**Comment by marco-c** [comment] 2022-09-06 20:12
Filed https://github.com/willkg/rob-bugson/issues/37 regarding containers.
