### ISSUE TITLE
tikz pattern lines show as dashed lines

### ISSUE THREAD

**Issue by Firestar-Reimu** [mozilla/pdf.js#17209] opened 2023-11-01 08:08 UTC
Original issue: https://github.com/James-Yu/LaTeX-Workshop/issues/4051

PDF.js v3.8.162

```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{patterns.meta}
\begin{document}
\begin{tikzpicture}
    \draw [pattern={Lines[angle=45,distance=4pt]},pattern color=red]
    (0,0) rectangle (1,1);
\end{tikzpicture}


\begin{tikzpicture}
    \draw [pattern={Lines[angle=0,distance=4pt]},pattern color=red]
    (0,0) rectangle (1,1);
\end{tikzpicture}
\end{document}
```

![Screenshot_20231101_100745](https://github.com/James-Yu/LaTeX-Workshop/assets/65082432/309955a2-f797-42b0-bcd2-6fbb072cd138)

This is what it is like on vscode

![Screenshot_20231101_144030](https://github.com/James-Yu/LaTeX-Workshop/assets/65082432/331eb882-6040-43d5-a0e4-6cf2e50ab02b)

This is what it is like on okular

**Comment by Snuffleupagus** [comment] 2023-11-01 08:29
When opening an issue, please fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) *completely* rather than just removing it. Note  that the `Attach (recommended) or Link to PDF file here:`-part is *always required* in order for any issue to be actionable/valid.
(Note that references to another bug tracker, or a piece of LaTeX-code, isn't a substitute for providing all information we ask for.)

> PDF.js v3.8.162

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

Given the lack of actionable details, I'm guessing that this is a duplicate of e.g. issue #16038.

**Closed by Snuffleupagus** 2023-11-01 08:29 UTC
Labels: information-requested

**Comment by Firestar-Reimu** [comment] 2023-11-01 09:23
[1.pdf](https://github.com/mozilla/pdf.js/files/13225348/1.pdf)
