### ISSUE TITLE
Better API docs using webdoc

### ISSUE THREAD

**Issue by SukantPal** [mozilla/pdf.js#13028] opened 2021-02-27 02:31 UTC
I see the docs say your working on something better. Do you think that [webdoc](https://github.com/webdoc-labs/webdoc)'s template (see https://api.pixijs.io/index.html) would be a good fit for PDF.js? I'd be glad to help you setup better docs.

**Comment by Snuffleupagus** [comment] 2021-02-27 10:33
This looks *essentially* like a duplicate of #6526, or at least sort of covered by that issue.

It also seems somewhat questionable (at least to me) if changing the entire documentation build step is really worth the effort!?

**Comment by timvandermeij** [comment] 2021-02-27 10:39
Yes, this is a duplicate of that issue. If you're willing to help out for that issue, feel free to provide ideas there on how it can be improved. Note that we're mainly concerned about the contents of the documentation; the visual representation is a bit less important for now.

**Closed by timvandermeij** 2021-02-27 10:39 UTC
