### ISSUE TITLE
Thumbnail sidebar has background with text and shapes instead of solid color

### ISSUE THREAD

**Issue by ianli** [mozilla/pdf.js#14995] opened 2022-06-06 01:39 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari 15.4
- Operating system and its version: Mac OS X Monterey 12.0.1
- PDF.js version: 2.14.305
- Is a browser extension: No

Steps to reproduce the problem:
1. Open this URL: https://www.usmanafzali.com/cv

What is the expected behavior? (add screenshot)
PDF sidebar has gray background.

Screenshot from Chrome 102.0.5005.61 (Mac OS X Big Sur 11.6.5)
<img width="626" alt="Screen Shot 2022-06-05 at 9 33 28 PM" src="https://user-images.githubusercontent.com/278230/172080327-6a115b5a-c2ad-49cf-8c43-35177e8d2b0c.png">

What went wrong? (add screenshot)
PDF sidebar has text ("Title:", "Author:") and graphics (shapes and lines) in the background.

![gSTo6b2M](https://user-images.githubusercontent.com/278230/172080115-032d4123-2034-4b6a-af02-2c9699209cf0.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

**Comment by ianli** [comment] 2022-06-06 01:43
Additional examples:

Steps to reproduce the problem:

1. Open this URL: https://muriliis.owlstown.net/cv

What went wrong? (add screenshot)
Left side of PDF has text (Pe, Au, Te) and graphics (shapes and lines) in the background.

![fJZEyqlS](https://user-images.githubusercontent.com/278230/172080954-cbbfe4e2-cfa1-488a-abf1-9c524b909fe4.jpg)

**Comment by ianli** [comment] 2022-06-06 01:47
Last example:

Steps to reproduce the problem:

1. Open this URL: https://www.kalinaslavkova.com/cv

What went wrong? (add screenshot)
Viewer doesn't show PDF. Instead, it shows text (File name:, File size:, Author:) and graphics (shapes and lines) in the background.

![wqwzmLH-](https://user-images.githubusercontent.com/278230/172081207-0a79491e-0d70-431b-affb-5a31d7c5c439.jpg)

**Comment by Snuffleupagus** [comment] 2022-06-06 07:32
> PDF.js version: 2.14.305
> [...]
> Open this URL: https://www.usmanafzali.com/cv
> [...]
> Open this URL: https://muriliis.owlstown.net/cv
> [...]
> Open this URL: https://www.kalinaslavkova.com/cv

Either of those URLs trigger the *built-in* browser PDF Viewer in both Firefox and Chrome in my testing, since an `<embed>`-element is being used to provide the PDF document. Hence the quoted PDF.js version number doesn't really make sense here.

---

Can you reproduce this with https://github.com/mozilla/pdf.js#online-demo, since I'd have hoped that PR #14984 should prevent older browsers from having trouble with `<dialog>`-elements?

**Comment by Snuffleupagus** [comment] 2022-06-06 07:33
> PDF.js version: 2.14.305
> [...]
> Open this URL: https://www.usmanafzali.com/cv
> [...]
> Open this URL: https://muriliis.owlstown.net/cv
> [...]
> Open this URL: https://www.kalinaslavkova.com/cv

Either of those URLs trigger the *built-in* browser PDF Viewer in both Firefox and Chrome in my testing, since an `<embed>`-element is being used to provide the PDF document. Hence the quoted PDF.js version number doesn't really make sense here.

---

Can you reproduce this with https://github.com/mozilla/pdf.js#online-demo, since I'd have hoped that PR #14984 should prevent older browsers from having trouble with `<dialog>`-elements?

**Comment by timvandermeij** [comment] 2022-06-09 19:47
I also can't reproduce any of this. All links indeed trigger the built-in viewer. Closing until more information is provided (see above).

**Closed by timvandermeij** 2022-06-09 19:47 UTC
Labels: viewer, information-requested
