### ISSUE TITLE
Unknown gulp version while building the extension 

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#18245] opened 2024-06-14 13:40 UTC
Attach (recommended) or Link to PDF file here: Irrelevant

Configuration:

Web browser and its version: 128.0.6536.0 (Official Build) canary (64-bit) (cohort: Clang-64)
Operating system and its version: Microsoft Windows 10 Home Version 10.0.19045 Build 19045
PDF.js version: 4.4.30
Is a browser extension: Yes
Steps to reproduce the problem:
Try to build the extension per the instructions at https://github.com/mozilla/pdf.js

What is the expected behavior? (add screenshot):
Code should build

What went wrong? (add screenshot)
"Unknown gulp version" at $gulp chromium step
I had to change $npm install -g gulp-cli@^2.3.0 to $npm install -g gulp-cli to make it work

**Comment by timvandermeij** [comment] 2024-06-14 13:42
Closing since this is a duplicate of #18232; please refer to https://github.com/mozilla/pdf.js/issues/18232#issuecomment-2161192845.

**Closed by timvandermeij** 2024-06-14 13:42 UTC

**Comment by qwer1304** [comment] 2024-06-14 15:58
So why do you keep a wrong version in the instructions instead of fixing them?

**Comment by timvandermeij** [comment] 2024-06-14 16:13
Oh right, that's indeed an oversight. I misread the issue and thought it was related to `gulp` rather than `gulp-cli`. I have reopened #18232 to address the issue (so this one can remain closed).

**Comment by timvandermeij** [comment] 2024-06-14 18:30
Fixed by #18247.
