### ISSUE TITLE
Unable to get cMap - nullAdobe-Japan1-UCS2 - console errors

### ISSUE THREAD

**Issue by heyligengregory** [mozilla/pdf.js#7017] opened 2016-02-23 09:40 UTC
Hello,

I'm using pdf.js, with the SVG, for a pdf with a lot of line and I have this error in my console : 

`Error: Unable to get cMap at: nullAdobe-Japan1-UCS2 util.js:258:5
createBuiltInCMap@http://localhost:8888/src/core/cmap.js:992:7
CMapFactoryClosure/<.create@http://localhost:8888/src/core/cmap.js:1003:16
Font_buildToUnicode@http://localhost:8888/src/core/fonts.js:2726:24
Font@http://localhost:8888/src/core/fonts.js:499:45
PartialEvaluator_translateFont@http://localhost:8888/src/core/evaluator.js:2066:14
PartialEvaluator_loadFont@http://localhost:8888/src/core/evaluator.js:655:1
PartialEvaluator_handleSetFont@http://localhost:8888/src/core/evaluator.js:424:14
next@http://localhost:8888/src/core/evaluator.js:826:22
next/<@http://localhost:8888/src/core/evaluator.js:831:19
 util.js:259:1
Warning: Error during font loading: Unable to get cMap at: nullAdobe-Japan1-UCS2`

I have seen that there is a similar issue in 2014 and it looks like it was closed but it seems that there is this issue again. 
I don't know if it is the cause of this but there is this strange print of the document, Japan print. I hope that It will help you to improve your lib.

![strange](https://cloud.githubusercontent.com/assets/17003290/13247373/7f401aa0-da19-11e5-8069-8cd6cddc4191.png)

Update 1 : Ok it seems that there is a OCR on my pdf but is this normal that pdf.js display these characters ?

**Comment by timvandermeij** [comment] 2016-02-23 20:55
Could you post an example PDF file here for us to debug the issue?

**Comment by yurydelendik** [comment] 2016-02-23 21:53
Since it's a custom solution provide URL for us to try out. 

Looks like you are just forgetting to CMap locations.

**Comment by Lordful** [comment] 2016-02-24 08:00
Yes of course, this is the PDF which provides this : 

[conv3.pdf](https://github.com/mozilla/pdf.js/files/144109/conv3.pdf)

**Comment by yurydelendik** [comment] 2016-02-24 15:11
Could you provide steps to reproduce the issues on different computer? It's really hard to understand the problem from the description above.

**Comment by Lordful** [comment] 2016-02-24 15:36
Well, I don't know why I don't send the code with the PDF, sorry.

I produce this issues by using your example of svgviewer and by replacing yours pdf file by this file that I posted previously.

I hope that it will help you.

**Comment by liuzhen2008** [comment] 2016-02-26 19:04
I can reproduce the same error log on the client console and see that it trys to make a GET  PATH/"nullAdobe-Japan1-UCS2" request. (PATH is where pdf.worker.js resides)

**Comment by timvandermeij** [comment] 2016-02-27 12:28
The errors have been fixed by #7036. This issue is now only tracking the rendering issues.

**Comment by Lordful** [comment] 2016-02-29 08:12
Ok that's good. Can I be prevent if you find the solution about the rendering ?

**Comment by moneytree-doug** [comment] 2016-06-03 05:55
I just received the same error with a PDF that has Japanese characters with version 1.5.279.

**Closed** 2018-08-29 21:51 UTC
Labels: 4-svg
