### ISSUE TITLE
PDF render partially fails on some Android phones (presumably only Pixel phones) in Cordova and Google Chrome

### ISSUE THREAD

**Issue by wartab** [mozilla/pdf.js#15827] opened 2022-12-14 15:14 UTC
Attach (recommended) or Link to PDF file here:
[v factu 304288 1 20221208153250.pdf](https://github.com/mozilla/pdf.js/files/10228857/v.factu.304288.1.20221208153250.pdf)

Configuration:
- Web browser and its version: Cordova 11.0.0 and Google Chrome 108
- Operating system and its version: 
Android 13 on Pixel phones. This is conjecture. We have tested this on six Android phones and it only happened on Pixel 6a phones, but both had Android 13.
- PDF.js version: happens on 2.13.216 and 3.1.18 (didn't test more versions)
- Is a browser extension: No

Steps to reproduce the problem:
1. Try to render some PDFs

What is the expected behavior? (add screenshot)
This is what it looks like on most Android phones.

![Screenshot_20221214_160658_Falco](https://user-images.githubusercontent.com/9607577/207632495-7f4ff2a7-60a9-4fe0-8ca0-2c1c3f4fb40a.jpg)

What went wrong? (add screenshot)
![Screenshot_20221214-152442](https://user-images.githubusercontent.com/9607577/207632678-05ffdcb4-0b18-46e0-8cb6-5f05fdc66cad.png)

It happens 95% of the time with different PDFs (some PDFs never cause this issue). The attached PDF fails every time. 
With the attached PDF, the top 60% of the PDF is rendered correctly for a split second, then the bottom part of the PDF is rendered, but the top part becomes white immediately. Note that the text overlay is not erased and is correct, just the rendered PDF in the Canvas becomes broken.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Managed to replicate it on Google Chrome on said phones without using Cordova. This does not happen on Firefox on those phones!
https://vadimdez.github.io/ng2-pdf-viewer/

**Comment by Snuffleupagus** [comment] 2022-12-14 15:19
Duplicate of #14897

**Closed by Snuffleupagus** 2022-12-14 15:19 UTC
