### ISSUE TITLE
PDF loses text when rendering 

### ISSUE THREAD

**Issue by jonassode** [mozilla/pdf.js#5499] opened 2014-11-21 03:47 UTC
PDF loses text when rendering with pdf.js

See example
![image](https://cloud.githubusercontent.com/assets/204505/5137398/38960368-718c-11e4-85c5-c8f3124f668a.png)
Left is pdf.js and right is how the PDF looks like in other Previewers.

Example pdfs can be downloaded here.
http://frialigan.se/wp-content/uploads/2013/06/Svavelvinter_quick-start_set.zip

Recreate
Download zip from above
Extract and locate Svavelvinter_scenario.pdf
Upload Svavelvinter_scenario.pdf to pdf.js previewer
Go to second page. Now most of the text is missing.

Similar errors with other pdf in the same zip above.

**Comment by ashley-hu** [comment] 2018-03-27 16:12
Hi, 
I could not reproduce the issue. All the text showed up in all the pdfs in the given download. 

The text shows up for "Svavelvinter_scenario.pdf".
![screen shot 2018-03-27 at 12 06 23 pm](https://user-images.githubusercontent.com/19430665/37979817-8a50eb0c-31b7-11e8-9973-eae26663acf1.png)

The text also showed up in "Svavelvinter_quick-start_rules.pdf" on the 3rd page. 
![screen shot 2018-03-27 at 12 07 54 pm](https://user-images.githubusercontent.com/19430665/37979819-8d0c9508-31b7-11e8-9428-ca0aec550725.png)


Browser: Chrome Version 64.0.3282.186 (Official Build) (64-bit) 
PDF version: 1.7
OS: OSX 10.11.6

**Comment by timvandermeij** [comment] 2018-03-27 19:51
Marking as upstream for now since it doesn't directly look like it's caused by PDF.js itself.

**Comment by Snuffleupagus** [comment] 2019-02-22 10:59
Given the age of this issue, and the fact that it seems related to a *particular* browser (and its version) rather than the PDF.js library itself, should this simply be closed now?

**Closed** 2019-02-22 21:14 UTC
Labels: 1-core, 3-upstream
