### ISSUE TITLE
Bad rendering result on Mac

### ISSUE THREAD

**Issue by rlisario** [mozilla/pdf.js#9715] opened 2018-05-11 10:00 UTC
Dear all,
I've used pdf.js library to have a preview of PDF files in my Java application.

On same Mac  (MacBook Pro with MACOSX 10.12.6) I have a problem with rendering result.

As see in attached, it seems all doubled.

![screenshot_20180510-222405](https://user-images.githubusercontent.com/34242916/39919155-0f5024e8-5513-11e8-9e90-74d3e3a84934.jpg)

Somebody have any suggestions?

Bye,
Rinaldo

**Comment by THausherr** [comment] 2018-05-11 12:48
Please attach your PDF and try with https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by timvandermeij** [comment] 2018-05-14 22:09
Closing since the issue is not actionable without more information. It can be reopened once a PDF file is attached.

**Closed by timvandermeij** 2018-05-14 22:09 UTC
Labels: 4-information-requested
