### ISSUE TITLE
Problem with french diacritics

### ISSUE THREAD

**Issue by symac** [mozilla/pdf.js#5011] opened 2014-06-26 20:32 UTC
Hello,
I've got problems with the following file http://www.geobib.fr/tmp/IFLA_WikiCP_v0.pdf opened with pdf.js. The é characters aren't displayed correctly, the diacritics which should be dislplayed above the character centered, is shifted to the right.

The PDF works fine with other PDF viewers.

**Comment by timvandermeij** [comment] 2016-05-10 21:36
The link is dead and the file cannot be found anymore on Google or the Internet Archive. Closing because this cannot be reproduced anymore. If the problem remains, please provide a new PDF file so we can reopen this.

**Comment by symac** [comment] 2016-05-11 07:16
@timvandermeij the PDF is not on my server anymore but you can find it there : https://hal.inria.fr/hal-01076038/document 
I have just tested, ubuntu 16.04, FF 46.0 and the é in the title are displaying as e' with the diacritic not on top of the letter.

**Comment by timvandermeij** [comment] 2016-05-11 11:34
This is working as expected for me on Arch Linux, but I'm reopening the issue to track the problem for Ubuntu. Thanks.

**Comment by SamyCookie** [comment] 2016-05-11 12:24
Same issue on Debian too.

**Comment by brendandahl** [comment] 2017-11-05 19:24
I can't reproduce on Ubuntu 16.04 w/ Firefox 58. I'll close the issue, but if there are still problems let us know and we'll re-open.

**Comment by SamyCookie** [comment] 2017-11-06 09:50
Problem is still here with Firefox 57 and Debian testing (> stretch).
cf. pictures on page 2 with référence (okular)
![okular](https://user-images.githubusercontent.com/2362591/32435078-4061a5d6-c2e0-11e7-8d6b-1b43b1f93a37.png)
![pdfjs](https://user-images.githubusercontent.com/2362591/32435079-407d827e-c2e0-11e7-8b65-633226c43e20.png)

**Comment by symac** [comment] 2017-11-06 10:02
As @SamyCookie points it, the é are fine on the first page, but on page 2, with FF 56.0 with ubuntu 16.04.3 I have the same issue.

**Comment by SamyCookie** [comment] 2017-11-06 10:30
Here is the original PDF file with the same issue without the first page (added by the french HAL platform).
https://iflaparis2014.sciencesconf.org/file/92290

**Comment by timvandermeij** [comment] 2018-09-08 19:59
Closing since this is now fixed, most likely by #9340 since I cannot reproduce it anymore now but could a few days ago.

**Closed by timvandermeij** 2018-09-08 19:59 UTC
Labels: 4-font-conversion

**Comment by SamyCookie** [comment] 2018-09-10 14:52
I cannot reproduce this bug either. Thanks for the fix !
