### ISSUE TITLE
Font is getting disturbed in Chrome

### ISSUE THREAD

**Issue by gsampath127** [mozilla/pdf.js#7462] opened 2016-07-01 06:20 UTC
Link to PDF file (or attach file here):
1.http://www.rightprospectus.com/documents/Nuveen/SUM_AllAmericanMunicipalBondFund.pdf
2.http://www.rightprospectus.com/documents/Nuveen/PRO_AllAmericanMunicipalBond.pdf

Configuration:
- Web browser and its version:Chrome 
- Operating system and its version:Windows 7
- PDF.js version:1.1.469
- Is an extension:

Steps to reproduce the problem:
1. Open First link with Pdf Js Viewer in Chrome
2.In the same tab Open Second link with Pdf Js Viewer.(Chrome)
3.We will able to see the disturbed font as in attached Picture.
4.But if we open the second link for the first time , there is no issue.
5.A User in our system always navigate to documents in same tab , so we are facing this issue.
6.**Issue is in second link provided above.**

What is the expected behavior? (add screenshot)
![fondd_nuveen_original](https://cloud.githubusercontent.com/assets/12858790/16513339/8bf92a48-3f81-11e6-9141-8343872b3fbe.PNG)

What went wrong? (add screenshot)
![fondd_nuveen](https://cloud.githubusercontent.com/assets/12858790/16513368/d33f31fe-3f81-11e6-870c-369be2ee0d13.PNG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome **extension):**

**Comment by gsampath127** [comment] 2016-07-01 06:25
We Tried applying fix by https://github.com/mozilla/pdf.js/pull/6715/commits/87762afec477b0951681df65e6a8286f9d5a1c6a , provided by pdf js team.

This does not work for us. Can you please provide any suggestions or code changes that we can apply here to solve the issue and please let us know any problem with the pdf.

Thanks in Advance!!!

**Comment by timvandermeij** [comment] 2016-07-04 18:22
You are using a very old version of PDF.js. Many font fixes have been applied since. Try to open the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) to see if the problem remains.

**Comment by gsampath127** [comment] 2016-07-05 02:57
Hi, We integrated latest version of PDF.js(v1.4.20), issue still persist. It happens only in chrome when we open below two documents in same tab one after another.
1.http://www.rightprospectus.com/documents/Nuveen/SUM_AllAmericanMunicipalBondFund.pdf
2.http://www.rightprospectus.com/documents/Nuveen/PRO_AllAmericanMunicipalBond.pdf

Could you please verify if something is wrong with above PDF documents related to font settings?

We tried to open these documents using demo URL-  https://mozilla.github.io/pdf.js/web/viewer.html it works fine. Demo URL uses open file button in toolbar whereas we pass PDF url in query string. **When we use open file button, its working with our old version also.**
Do we have any way to open PDF in demo site using query string?

**Comment by Rob--W** [comment] 2016-07-05 06:06
FYI, I've also encountered this issue a couple of times in the past month when I was reading papers for research. After opening the PDF Viewer (Chromium 51, Linux), the fonts looked a bit weird (sometimes thin, sometimes doubled like the picture above).

@gsampath127 Can you try the beta version? If that doesn't solve the issue, can you apply the patch at #7347 and see whether it resolves the problem (note: this is just a font issue, I didn't check whether it is related to your test case).

**Comment by gsampath127** [comment] 2016-07-05 12:46
Hi, We tried by integrating with beta version, issue is still present. We also tried to apply the patch at #7347 but it did not work for us.

Please suggest.

**Comment by gsampath127** [comment] 2016-07-07 15:18
Hi, Could you please look into above issue? Please let us know if something is wrong in PDF so that we can get those PDF's corrected.
Thanks.

**Comment by gsampath127** [comment] 2016-07-11 20:22
Hi Team, Could you please look into above issue? or  Please let us know if something is wrong in PDF so that we can get those PDF's corrected.

This issue is a kind of work stopper for us and we have tried all options from our side.

Thanks.

**Comment by timvandermeij** [comment] 2016-07-12 10:30
I cannot reproduce the issue using Firefox 47.0.1 on Arch Linux with the latest PDF.js development version. I really think this is some kind of regression in Chrome that should be reported upstream if it cannot be reproduced with other browsers.

**Comment by yurydelendik** [comment] 2016-07-12 19:17
Base on the conversation above, problem occurs for custom solution and reported didn't provide steps to reproduce the issue. Closing as incomplete. The workaround was found at https://github.com/mozilla/pdf.js/issues/7462#issuecomment-232102161, however it does not guarantee a correct solution and without steps to reproduce it's impossible to validate/verify it.

**Closed by yurydelendik** 2016-07-12 19:17 UTC
Labels: 4-chrome-specific, 4-font-conversion
