### ISSUE TITLE
Zoom not working in presentation mode

### ISSUE THREAD

**Issue by devanonyme** [mozilla/pdf.js#9069] opened 2017-10-25 22:17 UTC
Hello,

Zoom is not working in presentation mode.  Is this a known issue?

I have searched the issues and have not found something closely related. Maybe the toolbar should be optionnally available in presentation mode ?

Configuration:
- Web browser and its version: Chrome / Firefox 
- Operating system and its version:
- PDF.js version: Reproducible in latest demo (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension:

Steps to reproduce the problem:
1. Set presentation mode
2. Try to zoom using the keyboard shortcuts or control + wheel

What is the expected behavior? (add screenshot)
Zoom

What went wrong? (add screenshot)
No zoom

Thanks!

**Comment by yurydelendik** [comment] 2017-10-25 22:28
> Is this a known issue?

Presentation mode is for running a presentation. Zoom is not available in presentation mode in the demo viewer by design.

> Maybe the toolbar should be optionnally available in presentation mode ?

Browsers have a full screen mode -- use it preserve toolbar. Closing as answered.

**Closed by yurydelendik** 2017-10-25 22:28 UTC

**Comment by devanonyme** [comment] 2017-10-26 14:09
Hi Yury,

Sorry, I have given a bad exemple, we are actually using PDF.js in a iframe, so browser fullscreen brings all our app in fullscreen not just pdf.js viewer. I guess that use case fall off the initial design intent.

I understand that we will have to modify the viewer ourselves if it's really something that is important to us.

Thanks for the precision!
