### ISSUE TITLE
Missing JPX images with no indication of a problem

### ISSUE THREAD

**Issue by augustin** [mozilla/pdf.js#15532] opened 2022-10-01 14:13 UTC
Attach (recommended) or Link to PDF file here: *Liber Tertius at [this page on IMSLP](https://imslp.org/wiki/XXXV_Magnificat_(Palestrina,_Giovanni_Pierluigi_da))*

*Configuration:*
- Web browser and its version: Firefox 104.0.2
- Operating system and its version: Windows 10
- PDF.js version: 2.15.303
- Is a browser extension: No

*Steps to reproduce the problem:*
Open the PDF. Most of the actual music will simply not appear (although strangely some of it does.)

This appears to thus be related to #5649, **however** there is notably no "Unsupported header type" or "Unsupported colorspace" errors in the console, just the "Out of packets" and "COD options" errors.

More worryingly: there is no indication anything has gone wrong. (Has the "this PDF may not be displayed correctly" banner been removed altogether...?) I would at least expect a warning rather than having to open the PDF in a totally different viewer to see that indeed there is nothing wrong with the PDF itself.

From the console:
```
PDF c19f6ea0a8667d40ab52376d7fabdf92 [1.6 Adobe Acrobat 8.1 / PScript5.dll Version 5.2.2] (PDF.js: 2.15.303) viewer.js:1531:13
Warning: JPX: Unsupported COD options (terminationOnEachCodingPass, verticallyStripe, predictableTermination). pdf.worker.js:1121:13
Warning: Unable to decode image "img_p2_2": "JpxError: JPX error: JPX error: Out of packets". pdf.worker.js:1121:13
Warning: JPX: Unsupported COD options (terminationOnEachCodingPass, verticallyStripe, predictableTermination). pdf.worker.js:1121:13
Warning: Unable to decode image "img_p2_3": "JpxError: JPX error: JPX error: Out of packets". pdf.worker.js:1121:13
Warning: JPX: Unsupported COD options (terminationOnEachCodingPass, verticallyStripe, predictableTermination). pdf.worker.js:1121:13
Warning: Unable to decode image "img_p2_4": "JpxError: JPX error: JPX error: Out of packets". pdf.worker.js:1121:13
Warning: Dependent image isn't ready yet 3 pdf.js:454:13
Warning: JPX: Unsupported COD options (terminationOnEachCodingPass, verticallyStripe, predictableTermination). pdf.worker.js:1121:13
Warning: Unable to decode image "img_p3_2": "JpxError: JPX error: JPX error: Out of packets". pdf.worker.js:1121:13
Warning: JPX: Unsupported COD options (terminationOnEachCodingPass, verticallyStripe, predictableTermination). pdf.worker.js:1121:13
Warning: Unable to decode image "img_p3_3": "JpxError: JPX error: JPX error: Out of packets". pdf.worker.js:1121:13
Warning: JPX: Unsupported COD options (terminationOnEachCodingPass, verticallyStripe, predictableTermination). pdf.worker.js:1121:13
Warning: Unable to decode image "img_p3_4": "JpxError: JPX error: JPX error: Out of packets". pdf.worker.js:1121:13
Warning: Dependent image isn't ready yet 3 pdf.js:454:13
Warning: JPX: Unsupported COD options (terminationOnEachCodingPass, verticallyStripe, predictableTermination). pdf.worker.js:1121:13
Warning: Unable to decode image "img_p4_2": "JpxError: JPX error: JPX error: Out of packets". pdf.worker.js:1121:13
Warning: JPX: Unsupported COD options (terminationOnEachCodingPass, verticallyStripe, predictableTermination). pdf.worker.js:1121:13
Warning: Unable to decode image "img_p4_3": "JpxError: JPX error: JPX error: Out of packets". pdf.worker.js:1121:13
Warning: JPX: Unsupported COD options (terminationOnEachCodingPass, verticallyStripe, predictableTermination). pdf.worker.js:1121:13
Warning: Unable to decode image "img_p4_4": "JpxError: JPX error: JPX error: Out of packets". pdf.worker.js:1121:13
Warning: JPX: Unsupported COD options (terminationOnEachCodingPass, verticallyStripe, predictableTermination). pdf.worker.js:1121:13
Warning: Unable to decode image "img_p4_5": "JpxError: JPX error: JPX error: Out of packets". pdf.worker.js:1121:13
Warning: Dependent image isn't ready yet
```

**Comment by Snuffleupagus** [comment] 2022-10-01 14:28
Duplicate of #5649, since the errors look do identical to the ones in e.g. https://github.com/mozilla/pdf.js/issues/5649#issuecomment-1220397117.

> Has the "this PDF may not be displayed correctly" banner been removed altogether...?

Yes, that was done some time ago; see https://bugzilla.mozilla.org/show_bug.cgi?id=1705327

**Closed by Snuffleupagus** 2022-10-01 14:28 UTC

**Comment by augustin** [comment] 2022-10-01 15:12
Well, notably this one doesn't have "Unsupported header type" anywhere to be seen... but sure.
