### ISSUE TITLE
SVGGraphics getSVG() generated pattern cannot be displayed correctly

### ISSUE THREAD

**Issue by ngwaitat** [mozilla/pdf.js#14687] opened 2022-03-18 03:41 UTC
new pdfjsLib.SVGGraphics(page.commonObjs, page.objs).getSVG(...);

PDF that can reproduce this issue:

[Testing.pdf](https://github.com/mozilla/pdf.js/files/8301359/Testing.pdf)

Result of generated SVG:

![Screenshot_2022-03-18_11-38-54](https://user-images.githubusercontent.com/30998103/158933309-071ce523-d8d6-4215-a519-5c95aaff0ff0.png)

It works fine with PDF.js demo site, I checked code the implementation of SVG seems not the same as the Canvas version.

**Comment by Snuffleupagus** [comment] 2022-03-18 09:53
This is most likely a duplicate of one (or more) existing issue in https://github.com/mozilla/pdf.js/labels/svg

Furthermore, please note that as mentioned in the FAQ the SVG back-end is *not* officially supported; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

**Closed by Snuffleupagus** 2022-03-18 09:53 UTC
