### ISSUE TITLE
Pdf print in Microsoft Edge slow and incorrect

### ISSUE THREAD

**Issue by adineag** [mozilla/pdf.js#7348] opened 2016-05-23 18:36 UTC
Link to PDF file (or attach file here): https://mozilla.github.io/pdf.js/web/viewer.html

**Configuration:**
- Web browser and its version: Microsoft Edge 25.10586.0.0
- Operating system and its version: Windows 10 Pro (Version 1511 - OS Build 10586.318)
- PDF.js version: 1.4.20
- Is an extension: no

**Steps to reproduce the problem:**
1. Open the demo viewer (https://mozilla.github.io/pdf.js/web/viewer.html) in MS Edge browser.
2. Click on the print button

**What is the expected behavior ?**
On clicking the print button in the demo viewer, a print dialog containing the preview of the pdf that will be printed is displayed.

**What went wrong ?**
- When clicking print button, before opening the print dialog, a popup with a progress bar appears. 
![preparing](https://cloud.githubusercontent.com/assets/16132222/15480154/a87a2938-212c-11e6-9901-49bc0c7a90b5.PNG). This process takes a large amount of time (~1 minute) considering the size of the pdf (<1Mb)

- The pdf in the print dialog is incorrect. The bottom half of the page is blank (missing).
![capture](https://cloud.githubusercontent.com/assets/16132222/15480381/efac703a-212d-11e6-95d2-ad4b85ecdf61.PNG)

**Comment by pixelbits-mk** [comment] 2016-07-16 16:43
The printing issue where part of the page is being printed is related to issue 3983:
https://github.com/mozilla/pdf.js/issues/3983

There is a fix described in 3983 which works, but it hasn't made it into a release yet

**Comment by freeweel** [comment] 2016-07-28 14:58
The issue printing a half page also occurs in IE11, although the print speed is much faster on IE11.

**Comment by timvandermeij** [comment] 2016-07-29 12:25
We have a pull request under review to solve the cut-off pages issue. Edge is terrible in terms of performance: last time I worked with it it was indeed slower than IE11. Not much we can do about that. It appears new versions of Edge have a faster promises implementation, but I'm not sure if it will be as fast as Firefox or Chrome for example.

**Comment by mkurz** [comment] 2016-07-29 13:33
@timvandermeij Which PR do you mean?

**Comment by timvandermeij** [comment] 2016-07-30 19:40
It is pull request #7499.

**Comment by yurydelendik** [comment] 2016-10-06 13:36
Closing as duplicate of #3983

**Closed by yurydelendik** 2016-10-06 13:36 UTC
Labels: 4-ie-edge-specific, 4-printing
