### ISSUE TITLE
Some of the chemical formulas are rendered incorrectly during the preview, as shown in the figure

### ISSUE THREAD

**Issue by OnePsycho** [mozilla/pdf.js#14930] opened 2022-05-18 02:35 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Edge lastest version
- Operating system and its version: windows10
- PDF.js version:2.8.335
- Is a browser extension:no

Steps to reproduce the problem:
1.  PDF link : https://psycho-1300960840.cos.ap-chengdu.myqcloud.com/A6%E6%8A%80%E6%9C%AF%E6%94%AF%E6%8C%81%E7%9A%84%E8%AF%BE%E5%A0%82%E8%AE%B2%E6%8E%88%E6%95%99%E5%AD%A6%E8%AE%BE%E8%AE%A1%EF%BC%88%E4%BC%8D%E5%B0%8F%E8%93%89%EF%BC%89.pdf
2. preview PDF

What is the expected behavior? (add screenshot)
chemical formulas need be  Normal display
![image](https://user-images.githubusercontent.com/43296632/168945283-680087ad-d66b-4c32-b782-d6213100db72.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/43296632/168945288-bf4e1238-06e9-4c15-a21d-1f0895cdfba8.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://psycho-1300960840.cos.ap-chengdu.myqcloud.com/A6%E6%8A%80%E6%9C%AF%E6%94%AF%E6%8C%81%E7%9A%84%E8%AF%BE%E5%A0%82%E8%AE%B2%E6%8E%88%E6%95%99%E5%AD%A6%E8%AE%BE%E8%AE%A1%EF%BC%88%E4%BC%8D%E5%B0%8F%E8%93%89%EF%BC%89.pdf

**Comment by Snuffleupagus** [comment] 2022-05-19 09:22
WFM, using PDF.js version `2.14.290` in Firefox Nightly 102; hence this is likely a duplicate of #13193

> PDF.js version: 2.8.335

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Closed by Snuffleupagus** 2022-05-19 09:22 UTC

**Comment by akaQiang** [comment] 2024-12-05 11:40
how to fix it
