### ISSUE TITLE
Opening PDF documents in Chromium-based browsers causes a STATUS_STACK_OVERFLOW failure

### ISSUE THREAD

**Issue by rodolfoorl** [mozilla/pdf.js#18135] opened 2024-05-21 14:30 UTC
Attach (recommended) or Link to PDF file here:
   - For RGPD reasons I cannot send the document PDF

Configuration:
- Web browser and its version:
   - Chromium-based: 125.0.6422.60 _(Crash with **STATUS_STACK_OVERFLOW**)_
   - Mozilla Firefox 126.0 _(Slow and consumes a lot of CPU, but not crash)_
- Operating system and its version:
   - Windows Pro 11 Version: 10.0.22631 Build: 22631
- PDF.js version:
   - v4.2.67
   - v3.11.174
   - v2.9.359
- Is a browser extension: No

Steps to reproduce the problem:
- I still don't know how to replicate the problem from another PDF.
- Information I have and can provide:
   - This PDF was powered by Crystal Reports; modified using iText® 7.1.13 @ 2000-2020 iText Group NV _(AGPL-version)_
   - This PDF has been altered or corrupted since it was signed _(Information obtained when I open it in Adobe Acrobat)_

What is the expected behavior?
- Open the specific document PDF file with [pdf.js](https://github.com/mozilla/pdf.js) in a Chromium-based browser without causing a **STATUS_STACK_OVERFLOW**

What went wrong?
- Case 1 - Using Chromium-based browser:
In this case, I try to open the specific document in Chromium-based browsers _(In the video I used the Brave browser, but the same problem occurred in Edge and Chorme)_ - And after a few seconds the browser crashes with **STATUS_STACK_OVERFLOW**

https://github.com/mozilla/pdf.js/assets/20021506/544e862c-aed5-45bb-bc22-c581e50e8383

- Case 2 - Using Mozilla Firefox browser:
In this case, I try to open the specific document in the Mozilla Firefox browser, using the browser's own native [pdf.js](https://github.com/mozilla/pdf.js) - It spends time consuming a lot of CPU and the entire browser interface slows down and freezes, but does not crash - The message is also displayed that this tab is slowing down the browser and asks me if I want to stop it.

https://github.com/mozilla/pdf.js/assets/20021506/86f61451-d9cc-4a7b-8b8c-e0695f198d01

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
- https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2024-05-21 14:35
> Attach (recommended) or Link to PDF file here:
>     * For RGPD reasons I cannot send the document PDF

Unfortunately the only way for this, or any other, issue to be actionable/valid is if you provide access to the PDF document since it's impossible to fix/improve something that cannot be reproduced.

**Comment by calixteman** [comment] 2024-05-21 14:39
Sorry but we aren't genius and we can't guess what's wrong with just a video showing a number.
You can file a bug for Firefox:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=PDF%20Viewer
attach your pdf and check the box Confidential Mozilla employee:
![image](https://github.com/mozilla/pdf.js/assets/5641725/560c1bb2-3e1b-4aad-9429-eb422837042b)
or send it to me on my pro email (I'm the triage owner of the bug component from the link above)
And if it's too much confidential, sorry but as Snuffleupagus said, there is no way to fix your issue.

**Comment by rodolfoorl** [comment] 2024-05-21 14:43
> Unfortunately the only way for this, or any other, issue to be actionable/valid is if you provide access to the PDF document since it's impossible to fix/improve something that cannot be reproduced.

I understand... I will check the possibility of sending a document with the same problem that does not contain sensitive information so that we do not have problems with GDPR on our part.

I will get back to you soon and thanks for the quick response.

**Comment by rodolfoorl** [comment] 2024-05-21 19:11
> Sorry but we aren't genius and we can't guess what's wrong with just a video showing a number. You can file a bug for Firefox: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=PDF%20Viewer attach your pdf and check the box Confidential Mozilla employee: ![image](https://private-user-images.githubusercontent.com/5641725/332468202-560c1bb2-3e1b-4aad-9429-eb422837042b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTc2NTUsIm5iZiI6MTcxNjMxNzM1NSwicGF0aCI6Ii81NjQxNzI1LzMzMjQ2ODIwMi01NjBjMWJiMi0zZTFiLTRhYWQtOTQyOS1lYjQyMjgzNzA0MmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjFUMTg0OTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDFmMjJjYzc2ZmFiZWM5MjVlN2U4ZDk2NzZlY2MxNjkzYWJlMmYxMjk4MWY4OTYyZjBmZGU2NTVhN2U3YWQ4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BN8cori04YV_DozcZZxCcIp4QQMSYKVkZGA3tENwIqY) or send it to me on my pro email (I'm the triage owner of the bug component from the link above) And if it's too much confidential, sorry but as Snuffleupagus said, there is no way to fix your issue.

I created the issue at **bugzilla.mozilla.org**
[https://bugzilla.mozilla.org/show_bug.cgi?id=1898053](url)

**Comment by calixteman** [comment] 2024-05-21 19:57
@rodolfoorl in the bug, could you change the product to Firefox and the component to PDF Viewer ? I don't have access to the bug  (or you can cc me on the bug and I'll make the change).

**Comment by rodolfoorl** [comment] 2024-05-21 20:17
> @rodolfoorl in the bug, could you change the product to Firefox and the component to PDF Viewer ? I don't have access to the bug (or you can cc me on the bug and I'll make the change).

Done!
![image](https://github.com/mozilla/pdf.js/assets/20021506/b93e432a-2a1a-4273-84ae-a26bf1149463)

**Comment by Snuffleupagus** [comment] 2024-10-30 09:19
Closing as duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1898053 (to avoid tracking the same issue in multiple places).

**Closed by Snuffleupagus** 2024-10-30 09:19 UTC
Labels: performance
