### ISSUE TITLE
 Hello, there are 2 problems in using DPF.JS in the project:

### ISSUE THREAD

**Issue by beijingalex** [mozilla/pdf.js#10984] opened 2019-07-18 07:55 UTC
1.The PDF file viewed by using PDF.JS is not clear enough when printed on paper.
2.When printing on paper, horizontal and vertical cannot adapt themselves.

May I know what can be done?

**Comment by THausherr** [comment] 2019-07-18 08:34
How about sharing your PDF, the printed PDF and explaining what you mean? And "Hello, there are 2 problems in using DPF.JS in the project" is not really a useful title. If everybody would do that, the bug list would look like this:

```
10985 I got this error and please help
10986 Something doesn't work right in the Xfdh.js projekt
10987 Please help me I don't know what is happening
10988 Is this real? The paper looks weird
10999 PDF problem, pls guide me
10100 image is wrong in that browser on my computer
10111 My computer mad at me
10112 I'm lost here why is this so
10113 Screen is wrong
```

**Comment by timvandermeij** [comment] 2019-07-18 20:51
I agree. Unless more information is provided, I'm closing this as a duplicate of many other issues in https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-printing.

**Closed by timvandermeij** 2019-07-18 20:51 UTC
