### ISSUE TITLE
arabic characters

### ISSUE THREAD

**Issue by amira2i** [mozilla/pdf.js#7336] opened 2016-05-17 23:09 UTC
[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/265335/compressed.tracemonkey-pldi-09.pdf)

Configuration:

chrome 
windows 7
PDF.js version 1.4.20 
1.open pdf in viewer.html
2.when i try to highlight text 

instead of select two line i got
![2016-05-16_10-39-31](https://cloud.githubusercontent.com/assets/631406/15284617/a2e652d8-1b52-11e6-9855-f44f70fb5e31.jpg)

and some charchters like ٌ  or ً  are missed in selected text

**Comment by Snuffleupagus** [comment] 2016-05-18 09:13
Closing as duplicate of issue #7328.

**Closed by Snuffleupagus** 2016-05-18 09:13 UTC
