### ISSUE TITLE
It takes 4 minutes to open a 40M pdf file，How can I be faster?

### ISSUE THREAD

**Issue by victorychao** [mozilla/pdf.js#9395] opened 2018-01-23 02:45 UTC
When opening a pdf, 652 pdf.js were called.The code to be called is " xhr.send (null);"   How to read the hurry。

**Comment by yurydelendik** [comment] 2018-01-23 03:08
To improve performance, see FAQs [What types of PDF files are slow in PDF.js? Can I optimize a PDF file to make PDF.js faster?](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-types-of-pdf-files-are-slow-in-pdfjs-can-i-optimize-a-pdf-file-to-make-pdfjs-faster) and [PDF.js is fetching the entire PDF file from a server. Can it fetch only the required portions for rendering?](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#pdfjs-is-fetching-the-entire-pdf-file-from-a-server-can-it-fetch-only-the-required-portions-for-rendering) at https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions

The issue is incomplete -- closing as such.

**Closed by yurydelendik** 2018-01-23 03:08 UTC
