### ISSUE TITLE
Internal links move to incorrect page

### ISSUE THREAD

**Issue by riccimatic** [mozilla/pdf.js#8177] opened 2017-03-20 12:00 UTC
Hi,
 i'm opening this issue because with some pdf files, i get a strange library response with internal links embedded in the PDF.
I try a custom fix, without success. This fix generate the issue on others pdfs.

Link to PDF file (or attach file here):
1. [pdf 1 - ok.pdf](https://github.com/mozilla/pdf.js/files/854630/pdf.1.-.ok.pdf)
2. [pdf 2 - ok.pdf](https://github.com/mozilla/pdf.js/files/854631/pdf.2.-.ok.pdf)
3. [pdf 3 - navigation error.pdf](https://github.com/mozilla/pdf.js/files/854632/pdf.3.-.navigation.error.pdf)

Configuration:
- Web browser and its version: Chrome versions from 2016-10-01 to actual
- Operating system and its version: Windows 7/8/8.1/10
- PDF.js version: 1.5.188, 1.6.210
- Is an extension: no, only the library is used to provide the feature

Steps to reproduce the problem (use pdf 3 to understand the issue):
1. open page 1
2. click on link with label "veicoli a gas"
3. the editor go to page 5 instead of page 4 

What is the expected behavior? (add screenshot)
Open page 4

What went wrong? (add screenshot)
The editor open page 5, or generally the next page, i have this issue on other files

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
The library is hosted on an other site and the pdf's files are related to a visibility policy (no public access).
I can provide only the files in attachment.

Thanks for the support

**Comment by Snuffleupagus** [comment] 2017-03-20 12:14
Closing as duplicate of issue #7154.

**Closed by Snuffleupagus** 2017-03-20 12:14 UTC
