### ISSUE TITLE
PDFRenderingQueue not exported in pdf_viewer.js ?

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#11760] opened 2020-03-29 19:29 UTC
Trying to give more constructive feedback.

I want to rebuild the viewer but in react and still having lots of problems.  

For example, it doesn't seem like PDFRenderingQueue is exported. 

What's weird is that looking at the generated code in pdf_viewer.js ... it is:

```
exports.PDFRenderingQueue = PDFRenderingQueue;
```

but if I try to use it it's undefined.  

It's thinks like this that yield a great deal of confusion because it doesn't seem possible to actually build the demo viewer with pdf.js. It's only possible to build more simple single page PDF renders.

**Comment by Snuffleupagus** [comment] 2020-03-29 21:28
> What's weird is that looking at the generated code in pdf_viewer.js ... it is:
> ```
> exports.PDFRenderingQueue = PDFRenderingQueue;
> ```
> but if I try to use it it's undefined.

Without actual links to the code in question, it's quite frankly difficult to know *exactly* what code you're referring to here!
Are you perhaps asking for https://github.com/mozilla/pdf.js/blob/master/web/pdf_rendering_queue.js to be exposed through https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.component.js, or something else?

> [...] it doesn't seem possible to actually build the demo viewer with pdf.js.

Please note that that's on purpose, see e.g. http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by burtonator** [comment] 2020-03-29 22:28
Right.  this is basically what I'm trying to do now.  I have a basic viewer which doesn't use your skin, it's using ours, but the problem is it renders EVERY pages.

I had thought that PDFRenderingQueue was what was limiting the number of pages but after building my custom version, it won't work.

PDFRenderingQueue, I don't think, would enable you to just take the full skin.  It's just sort of an internal buffer anyway.

The problem I have now is if I have a 200 page PDF it will render ALL 200 pages.  I need it to use a window and only render 2-10 at a time and the rest are in 'loading' state like the viewer currently does.

For some reason this isn't enabled in the default build which makes loading super slow.

Also, once loaded, CPU is hammered too.. 

How can I get it to just use the windowed rendering like it does in the viewer?

**Comment by Snuffleupagus** [comment] 2020-03-29 22:33
Based on https://github.com/mozilla/pdf.js/issues/11760#issuecomment-605711763, this sounds like a duplicate of issue #11626.

**Comment by timvandermeij** [comment] 2020-03-30 21:38
Closing as a duplicate for now to focus the discussion over there.

**Closed** 2020-03-30 21:38 UTC
Labels: 1-other
