### ISSUE TITLE
SVG with pattern embedded in PDF not getting rendered

### ISSUE THREAD

**Issue by ameyghate** [mozilla/pdf.js#8167] opened 2017-03-16 19:27 UTC
Link to PDF file (or attach file here):
[SVG Pattern in PDF.pdf](https://github.com/mozilla/pdf.js/files/848548/SVG.Pattern.in.PDF.pdf)

Configuration:
- Web browser and its version:
FireFox 45.8.0, Google Chrome 57.0.2987.98, IE 11
- Operating system and its version:
- PDF.js version: 
PDFJS.version = '1.0.907';
- Is an extension:

Steps to reproduce the problem:
1.  Application has logic of inserting SVG with various patterns in PDF.
2.  Application uses PDF JS (V 1.0.907) for rendering this PDF on UI.
3.  But pdf.js simply skips the rendering of the pattern (
 - Looks like TilingPattern is expecting bbox details in x0, y0, x1, y1
 - But the pattern from attached PDF is x0, y1, x1, y0
 - Note: this.bbox = PDFJS.Util.normalizeRect(IR[4]); change seams to fix this issue

What is the expected behavior? (add screenshot)
[SVG Pattern in PDF.pdf](https://github.com/mozilla/pdf.js/files/848605/SVG.Pattern.in.PDF.pdf)

What went wrong? (add screenshot)
![svg pattern in pdf with pdf js](https://cloud.githubusercontent.com/assets/26466688/24011101/2e61d8e0-0a50-11e7-8327-f871332d8249.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Same issue is reproducible if we upload attached pdf on PDF JS demo link : https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2017-03-16 20:04
Closing as duplicate of issue #8117.

**Closed by Snuffleupagus** 2017-03-16 20:04 UTC
