### ISSUE TITLE
Some spaces are extracted as dots

### ISSUE THREAD

**Issue by markb-trustifi** [mozilla/pdf.js#13475] opened 2021-06-01 09:29 UTC
Attach (recommended) or Link to PDF file here:
[Erudition_HSUHK-e-newsletter_May-2021.pdf](https://github.com/mozilla/pdf.js/files/6574977/Erudition_HSUHK-e-newsletter_May-2021.pdf)

Configuration:
- Web browser and its version: chrome 91
- Operating system and its version: MacOS 10.14
- PDF.js version: 2.7.570
- Is a browser extension: no

Steps to reproduce the problem:
1. open attached PDF file
2. find link `https://rb.gy/lmwemz`
3. copy a few lines around it and past them to the notepad

What is the expected behavior? (add screenshot)
The spaces should be extracted as spaces:
<img width="1477" alt="Screen Shot 2021-06-01 at 12 10 05" src="https://user-images.githubusercontent.com/29097494/120298020-5b8fbf00-c2d2-11eb-885c-832b355786e8.png">

What went wrong? (add screenshot)
When doing copy/paste some spaces are copied as dots:
`The.University.would.like.to.seek.your.help.in.inviting.more.alumni.to.reconnect.with.us..If.you.happen.to.know.of.any.alumni.via.your.network,.please.pass.on.this.link.(https://rb.gy/lmwemz).so.that.we.can.keep.them.abreast.of.the.latest.news.and.developments.of.their.alma.mater.恒大一直重視與校友的聯繫，我們祈盼您能協助聯絡身邊的恒大校友，讓他們也能緊貼母校的最新資訊及發展。歡迎分享此連結（https://rb.gy/lmwemz），讓更多校友與母校保持聯繫。
Graduates of the School of Translation and Foreign Languages take a group photo with the faculty members. 翻譯及外語學院畢業生與教職員合照留念`

The same issue occurs when parsing PDF file with `pdfjs-dist` library (Node.js v14):
```
const pdfjsLib = require('pdfjs-dist/es5/build/pdf.js');
let doc = await pdfjsLib.getDocument({data: filebuffer, nativeImageDecoderSupport: pdfjsLib.NativeImageDecoding && pdfjsLib.NativeImageDecoding.DISPLAY, disableFontFace: true, verbosity: 0}).promise;
let page = await doc.getPage(i);
let content = await page.getTextContent();
let text = content.items.map(itm => itm.str).join(' ');
```

**Comment by Snuffleupagus** [comment] 2021-06-01 09:37
Duplicate of #12237

**Closed by Snuffleupagus** 2021-06-01 09:37 UTC

**Comment by markb-trustifi** [comment] 2021-06-01 10:42
@Snuffleupagus :
- this file doesn't have `/ActualText` tags
- when this file is opened in Chrome browser PDF viewer the text around the `https://rb.gy/lmwemz` link is copied correct. The issue exists with MacOS viewer and with `pdfjs-dist` library.

**Comment by Snuffleupagus** [comment] 2021-06-01 11:08
> this file doesn't have `/ActualText` tags

Yes, it most certainly does:

![actualtext](https://user-images.githubusercontent.com/2692120/120313446-40c14880-c2da-11eb-8652-7439a3a24440.png)

**Comment by markb-trustifi** [comment] 2021-06-01 11:40
> It most certainly does:

It is strange. I don't see it in:
```
let doc = await pdfjsLib.getDocument({data: dataObject.buffer, disableFontFace:true, verbosity:0}).promise;
let pdfstr = (await doc.getData()).toString();
```

**Comment by calixteman** [comment] 2021-06-01 11:48
The pdf contains sequences like the following:
```
BT /Span <</ActualText (þÿ\0 )>>BDC  8 0 0 8 75.1664 356.8281 Tm <0001>Tj EMC  ET
```
The `ActualText` entry contains a white space but here we use the char drawn in the `Tj` instruction to put in the text layer.
So it's definitely a duplicate of #12237. 
You can use `qpdf` to uncompress streams and have a look to the pdf in a text editor to see all the `ActualText` by yourself.

**Comment by markb-trustifi** [comment] 2021-06-01 12:30
> You can use qpdf to uncompress streams

I'll check it. Thank you.
