### ISSUE TITLE
Would it be possible to apply Dark Reader on top of pdf.js?

### ISSUE THREAD

**Issue by avatar-lavventura** [mozilla/pdf.js#14646] opened 2022-03-08 10:23 UTC
I want to apply dark-theme on top of pdf.js (dark background)

Would it be possible to apply https://addons.mozilla.org/en-US/firefox/addon/darkreader/ on the of pdf.js?

**Comment by Snuffleupagus** [comment] 2022-03-08 10:34
Duplicate of #2071

**Closed by Snuffleupagus** 2022-03-08 10:34 UTC
