### ISSUE TITLE
ChoiceWidgetAnnotationElement should support EDIT flag on the ChoiceWidget

### ISSUE THREAD

**Issue by farling42** [mozilla/pdf.js#17471] opened 2023-12-28 22:38 UTC
When the "Allow user to enter custom text" is ticked on a dropdown list, the generated HTML should probably be input(text) + datalist rather than a select element for the generated HTML. (see https://community.adobe.com/t5/acrobat-discussions/learn-how-to-create-a-dropdown-list-in-a-pdf-form/td-p/10985058 for where that option is described for Adobe PDF editor).

Currently the EDIT flag is ignored, so the user can only select an entry from the predefined list.

(In my simple testing, the fieldFlags had the value 0x420000 when no custom text is allowed, but the value 0x460000 when custom text is allowed. This corresponds to AnnotationFieldFlag.EDIT

Example PDF can be found at https://mrgone.rocksolidshells.com/pdf/VtM/VampireRev4-Page_Editable.pdf

On page 1, the fields Clan/Generation/Sire at the top of the first page have dropdown lists which allow custom text.
On page 2, the "Bonus" column in the top section contain dropdown lists that do NOT allow custom text.

**Comment by Snuffleupagus** [comment] 2023-12-29 08:43
Duplicate of #10669.

---

*For future reference:* Please remember to fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when reporting an issue.

**Closed by Snuffleupagus** 2023-12-29 08:43 UTC
