### ISSUE TITLE
Content-Disposition filename ignored somehow

### ISSUE THREAD

**Issue by schmitch** [mozilla/pdf.js#6396] opened 2015-08-28 16:07 UTC
Hello, currently I render my Browser documents with PDFJS however I have patched the viewer.js to support my Authorization header i just added httpHeaders to paramters before PDFJS.getdocument so nothing special, however PDFJS ignore's my Content-Disposition Header which has a filename=
it always gives me document.pdf

I tested against a CORS version and non cors currently this is my content-disposition:

```
 Content-Disposition:inline; filename="Angebot_412356.pdf"
```

Is there a setting that it should use this filename or do I miss something?

Currently it isn't related to https://github.com/mozilla/pdf.js/issues/2407 since that will work on save + s.
However on my side either Firefox/Chrome nobody gets the correct content-disposition i tried:

```
 Content-Disposition: inline; filename=name.pdf
 Content-Disposition: attachment; filename=name.pdf
 Content-Disposition: inline; filename="name.pdf"
 Content-Disposition: attachment; filename="name.pdf"
```

Also that's the Code I added in viewer.js starting after Line 6373 and the PDFJS line is already there:

```
 var token = window.localStorage.getItem('token');
 var typ = window.localStorage.getItem('type');
 parameters.httpHeaders = {'Authorization': typ + ' ' + token};
 PDFJS.getDocument(parameters, pdfDataRangeTransport, passwordNeeded,
```

btw. I could also set the filename by myself, I think of the possibility that I know the filename already.

**Comment by Rob--W** [comment] 2015-08-28 19:27
The Content-Disposition header is currently not parsed.

Patches are welcome! If you're interested:

- Get the header (search for `onHeadersReceived` in the src/core directory to find an entry point), and parse it. (note that this parsing is not trivial, e.g. account for special encodings, see other open-source libraries for inspiration).
- Add an API or use an existing API to communicate the `Content-Disposition` header from the worker to the main thread.
- Search for uses of `getPDFFileNameFromURL` in files in `web/`, e.g. in `web/viewer.js` and update it to take the filename in Content-Disposition into account.

**Comment by schmitch** [comment] 2015-08-28 22:07
@Rob--W oh I thought it is cause of some issue's. However if' just appended a &filename="name.pdf" to my url I think that parsing it wouldn't be too trivial for my use case.

**Comment by jumbosushi** [comment] 2015-12-01 06:27
Does this still need work? I would love to make this my first contribution to oss

**Comment by Rob--W** [comment] 2015-12-02 11:41
@jumbosushi This still needs work indeed. A few comments back I have described the steps that you can follow to implement this feature. If there's anything unclear, feel free to ask.

**Comment by corblanc** [comment] 2016-04-26 15:19
@Rob--W Would like to give this a try if it's still open.

**Comment by Rob--W** [comment] 2016-04-26 15:40
@corblanc This is still open, thanks for giving it a try!

The invitation to ask questions is also still open.

**Comment by corblanc** [comment] 2016-04-26 15:41
@Rob--W Great! Mind if I shoot you an email? Bit new to all of this.

**Comment by Rob--W** [comment] 2016-04-26 15:44
@corblanc Go ahead. You can also join us at #pdfjs on Freenode if you want to have a conversation.

**Comment by david0603** [comment] 2017-01-30 16:22
Any updates on this?  Thanks!

**Comment by Koolstr** [comment] 2017-06-07 22:12
This is still an issue, for me at least. Any updates? It's been over a year.

**Comment by Maiestas28** [comment] 2018-01-06 05:53
Hey guys, im new to OSS and this would be my first contribution. The tag looks open. How can i contribute and any guidance is very much needed and much appreciated. Thank you.

**Comment by Rob--W** [comment] 2018-01-06 12:17
See https://github.com/mozilla/pdf.js/issues/6396#issuecomment-135866793

I have recently written a simple yet complete Content-Disposition parser, its functionality can be reused: https://github.com/Rob--W/open-in-browser/blob/master/extension/content-disposition.js

**Comment by timvandermeij** [comment] 2018-01-06 13:26
Note that there is already a pull request for this issue above (and it's almost finished), hence I would suggest working on another issue instead.

**Comment by Maiestas28** [comment] 2018-01-06 18:16
Got it. Thank you.

**Comment by timvandermeij** [comment] 2018-01-18 22:30
Fixed in #9379.

**Closed by timvandermeij** 2018-01-18 22:30 UTC
Labels: 1-viewer, 2-feature, 5-good-beginner-bug

**Comment by ddemoss222** [comment] 2022-05-27 21:29
Has there been regression on this? I am trying to open a base64 pdf from an <a> tag. I set the "download" attribute to the filename which correctly names the PDF on chrome, but with the pdfjs opener in firefox it shows only "document.pdf". If I set the:
```
 Content-Disposition: attachment; filename=name.pdf
 Content-Disposition: attachment; filename="name.pdf"
```
The above too is ignored by pdf.js and I just see:
```
Warning: getPdfFilenameFromUrl: ignore "data:"-URL for performance reasons.
```
Why does pdf.js still ignore the Content-Disposition and download attribute in the a tag. Is this regression? Are there any known workarounds for JSON base64 responses?

**Comment by Snuffleupagus** [comment] 2022-05-28 09:49
@ddemoss222 *For future reference:* Note that it's always recommended to open a new issue, rather than commenting on one that was closed many years ago, since it's often very easy for comments on old issues to be overlooked/ignored.

Without a runnable test-case it's difficult (or rather impossible) to know for sure, but this is likely fixed by the PR referenced above.
