### ISSUE TITLE
PDF.js start from last page viewed for a pdf

### ISSUE THREAD

**Issue by AyahBot-Dev** [mozilla/pdf.js#17876] opened 2024-04-03 11:50 UTC
Attach (recommended) or Link to PDF file here: Any PDF running locally

Configuration:
- Web browser and its version: Firefox Developer 125.0b7 (64-bit)
- Operating system and its version: Windows 11 23H2
- PDF.js version: 4.1.287
- Is a browser extension: No

Steps to reproduce the problem:
1. Open Firefox and go to a local pdf file, and go to any page other than page 1
2. Close the tab, and go again, and you will see it starting from page 1, not from the last page viewed

What is the expected behavior? (add screenshot)
Start from the last page viewed

**Comment by Snuffleupagus** [comment] 2024-08-14 07:03
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1911420

**Closed by Snuffleupagus** 2024-08-14 07:03 UTC
Labels: viewer
