### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by karan-sdplabs** [mozilla/pdf.js#10072] opened 2018-09-13 12:25 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome v69+
- Operating system and its version: macOSX high serriea
- PDF.js version: v1.9
- Is a browser extension: no extension using

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
![screenshot of pdf page which i am converting](https://user-images.githubusercontent.com/43239875/45487961-8251e400-b77d-11e8-9f98-d20267cb4ea0.png)
![output_image](https://user-images.githubusercontent.com/43239875/45487971-8aaa1f00-b77d-11e8-9d48-90e4290e899a.jpg)

below is the code i am using

`var Canvas = require('canvas');
var assert = require('assert');
var fs = require('fs');
var moment = require('moment')
var express = require('express');
var app = express();
var port = process.env.PORT || 8080;
var router = express.Router(); 

app.get('/', function(req, res) {
  function NodeCanvasFactory() {}
NodeCanvasFactory.prototype = {
  create: function NodeCanvasFactory_create(width, height) {
    assert(width > 0 && height > 0, 'Invalid canvas size');
    var canvas = new Canvas(width, height);
    var context = canvas.getContext('2d');
    context.imageSmoothingEnabled = true;
    context.mozImageSmoothingEnabled = true;
    context.webkitImageSmoothingEnabled = true;
    context.msImageSmoothingEnabled = true;
    context.filter = 'blur(11120px)'
    // context.filter = 'blur(220000000000000000000000000098076543020089807654089075643070787654650px)'
    return {
      canvas: canvas,
      context: context,
    };
  },

  reset: function NodeCanvasFactory_reset(canvasAndContext, width, height) {
    assert(canvasAndContext.canvas, 'Canvas is not specified');
    assert(width > 0 && height > 0, 'Invalid canvas size');
    canvasAndContext.canvas.width = width;
    canvasAndContext.canvas.height = height;
    // canvasAndContext.context.imageSmoothingEnabled = false;
    // canvasAndContext.context.mozImageSmoothingEnabled = false;
    // canvasAndContext.context.webkitImageSmoothingEnabled = false;
    // canvasAndContext.context.msImageSmoothingEnabled = false;
    // canvasAndContext.context.filter = 'blur(100%)'
  },

  destroy: function NodeCanvasFactory_destroy(canvasAndContext) {
    assert(canvasAndContext.canvas, 'Canvas is not specified');

    // Zeroing the width and height cause Firefox to release graphics
    // resources immediately, which can greatly reduce memory consumption.
    canvasAndContext.canvas.width = 0;
    canvasAndContext.canvas.height = 0;
    canvasAndContext.canvas = null;
    canvasAndContext.context = null;
  },
};

var pdfjsLib = require('pdfjs-dist');

// Relative path of the PDF file.
// var pdfURL = '../../../web/compressed.tracemonkey-pldi-09.pdf';

// Read the PDF file into a typed array so PDF.js can load it.
// var rawData = new Uint8Array(fs.readFileSync(pdfURL));

// Load the PDF file.
pdfjsLib.getDocument({
  url:'./pdfs/BishopTyrrellAnglicanCollege-eduSITE.pdf',
  disableFontFace:true,
  nativeImageDecoderSupport: 'none',
  disableWorker:false,
  disableStream:true,
  disableAutoFetch:true
}).then(function (pdfDocument) {
  console.log('# PDF document loaded.');

  // Get the first page.
  pdfDocument.getPage(4).then(function (page) {
    // console.log(page)
    // Render the page on a Node canvas with 100% scale.
    var viewport = page.getViewport(1.0);
    var canvasFactory = new NodeCanvasFactory();
    var canvasAndContext = canvasFactory.create(viewport.width, viewport.height);
    // var ctx = Canvas.getContext('2d');
    var renderContext = {
      canvasContext: canvasAndContext.context,
      viewport: viewport,
      canvasFactory: canvasFactory,
      intent:'print',
      background:'rgb(0,0,255)',
      enableWebGL:true
    };
    page.render(renderContext).then(function () {
      // Convert the canvas to an image buffer.
      var image = canvasAndContext.canvas.toDataURL()
        // var newImg = changeDPI.changeDpiDataUrl(image,75);
        // console.log(newImg)
      res.send('<img src="'+image+'"/>')
      //       fs.writeFile(`./images/output_${moment().format('MMMM Do YYYY, h:mm:ss a')}.jpg`, image, function (error) {
      //   if (error) {
      //     console.error('Error: ' + error);
      //   } else {
      //     console.log('Finished converting first page of PDF file to a PNG image.');
      //   }
      // });
    });
  });
}).catch(function(reason) {
  console.log(reason);
});
})
app.use('/api', router);

app.listen(port);
console.log('Magic happens on port ' + port);
`

**Comment by timvandermeij** [comment] 2018-09-13 18:40
Closing since no PDF file is provided to reproduce the issue, the issue is not clearly stated (what is wrong with the colors?) and there is no runnable example for verification (code snippets don't help to reproduce the issue). Please read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, especially the second paragraph, and provide the necessary details to reopen.

**Closed by timvandermeij** 2018-09-13 18:40 UTC
