### ISSUE TITLE
Enable support for AcroForms in viewer

### ISSUE THREAD

**Issue by jviereck** [mozilla/pdf.js#1459] opened 2012-03-31 06:09 UTC
There is some code for AcroForms under examples, but it's not used within the viewer due to a bug in the Firefox printing codebase that is fixed in Firefox Aurora 13. See https://bugzilla.mozilla.org/show_bug.cgi?id=703171#c5.

**Comment by edpirone** [comment] 2015-01-28 21:00
I'm a bit confused by the previous thread comments. This seems like it is still an issue. I just downloaded the most recent stable and cannot fill out fields in a PDF form. Is this still being worked on or has it been tabled?

**Comment by timvandermeij** [comment] 2015-01-28 21:08
We have partial AcroForms support, but indeed it's far from complete. We have seen telemetry results and asked users, but there was not much demand for AcroForms support. If someone wants to work on this, feel free to so and submit a pull request for review though!

**Comment by edpirone** [comment] 2015-01-28 21:11
Thanks for the quick response. Ill keep posted.

**Comment by wamatt** [comment] 2015-02-17 03:03
:+1: for AcroForms. Not sure why it's not showing up in telemetry data. Seems like a fairly common use case. Pretty much every federal .gov (and most state gov) pdf I've seen have fillable fields.

@timvandermeij any idea how many dev hours it might take to ship something sort of usable? Like, are the input primitives and datastructs mapped, leaving mostly UI work? Or, is it more complicated than that?

It might make sense for my team to work on it, if there is a quick win.

**Comment by wamatt** [comment] 2015-02-17 03:40
Interesting, support is actually further developed than I realized. As you can see below from the AcroForm example.

![image](https://cloud.githubusercontent.com/assets/1271434/6222976/eb790f3c-b612-11e4-9778-f11430f5a482.png)

That said, still some issues. For example block input is currently unsupported

![image](https://cloud.githubusercontent.com/assets/1271434/6222984/1dcc74c4-b613-11e4-98d7-d2fb850b11c0.png)

XFA is probably a whole new kettle of fish and more complicated to support. For now however, solid a solid AcroForm implementation might be a nice win

**Comment by 1ec5** [comment] 2015-02-17 03:47
That acroforms example relies on a forms.js that’s included in the example but not in the normal viewer. For what it’s worth, Preview.app does the same thing with block input:

![preview app](https://cloud.githubusercontent.com/assets/1231218/6223063/abdf424a-b614-11e4-8350-466aba069c7b.png)

**Comment by wamatt** [comment] 2015-02-17 04:46
@1ec5 good point on preview.

While we making comparisons, it's interesting to see Chrome/Blink perform really well. 

![image](https://cloud.githubusercontent.com/assets/1271434/6223382/98c3c26e-b61c-11e4-8a53-6bcef5889cfa.png)

Block letter support and proper color/shading.

I suspect that might be because Chrome is using an Adobe plugin rather than their own rendering library?

**Comment by timvandermeij** [comment] 2015-02-17 19:17
It's really good to hear that you are interested in further developing this feature. I think the best implementation reference would be section 8.6 from the PDF specification: https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf#page=671&zoom=auto,-306,313

`forms.js` is an example implementation, but as you can see it is not complete, nor does it do everything described in the specification. I think that's also the reason that it is not yet included in the PDF.js core. In order to be able to include it in the PDF.js core, the existing code has to be rewritten in a more object-oriented way and it should support most of the features used in the found PDF files.

If you would like help with this, you can always reach us on IRC (irc.mozilla.org, #pdfjs) or ask here.

**Comment by joepie91** [comment] 2015-06-11 06:44
For what it's worth, I've had a user of [PDFy](https://pdf.yt/) request this functionality for a registration form.

**Comment by wscalf** [comment] 2015-08-03 20:00
Somewhat random, and possibly off-topic question: what about adding support for more of the properties of widget annotations? As it is, the AcroForms sample demonstrates how to add basic fillable form functionality when rehosting pdf.js, but anything beyond the basics isn't really possible because the annotations returned from getAnnotations() are missing properties (sometimes vital things, like the options in a choice control.)

While it would require a pretty robust solution in order to offer fillable forms in the viewer (ie: to users), simply expanding the data available via the public APIs would be useful to people like me who are rehosting/expanding on it (based on the AcroForms sample), and would also chip away at the core work that would need to be done to support forms completely. ..If that makes sense.

My schedule for the next while is a bit dicey, but I might be available to work on it. I also noticed there's a fork of pdf.js here: https://github.com/mainegreen/pdf.js that has a lot of that functionality already, but it's a few hundred commits behind and the current version crashes on choice controls.

Thoughts?

**Comment by timvandermeij** [comment] 2015-08-03 21:51
@wscalf We agree that that would be useful and we are tracking that request in #5283. Indeed a bit off-topic here, so any discussion should occur in that issue from now on. Thanks!

**Comment by fbender** [comment] 2015-11-16 10:22
> We have seen telemetry results and asked users, but there was not much demand for AcroForms support.

This may be a chicken-egg-problem. People will download PDFs instead of opening them in Fx because they cannot edit them, or websites will force-download to work around this issue with browser sniffing. Since browsers are retiring NPAPI and thus the Acrobat Plugin next year, this method will only advance. Additionally, a [2% usage figure](https://groups.google.com/forum/#!msg/mozilla.dev.pdf-js/XSAD98rYW5I/RKpl5P4Bl4AJ) is *huge* considering the overall amount of Fx users, and does not take into account further uses of pdf.js as well as people that disabled pdf.js in favor of the Acrobat plugin, which is highly likely for people having to deal with forms in PDFs on a regular basis. Also, more up-to-date information would be nice.

This issue should be top priority right now since (almost) all other major browsers (relative to market share) do support forms in one form or the other, and plugins will be deprecated. Furthermore, some OSes do not support forms in PDF natively, leaving an opportunity for a unique selling point.

**Comment by Hyangyong** [comment] 2016-05-15 06:09
I think some problem can be fixed if you go and watch to the site named www.smarttest.kr.
Radiobutton,textbox and submit control are good working now. These samples are for students to test on internet and to score.

**Comment by MickL** [comment] 2016-06-03 09:16
Any news / status updates on this issue? :)

**Comment by timvandermeij** [comment] 2016-06-03 19:20
Not yet. There is an open PR for some of this functionality, but it is a work in progress.

**Comment by timvandermeij** [comment] 2016-09-13 11:45
Closing as duplicate of #7613, in which we now track interactive forms (AcroForms) support. Parts of this feature have already been merged and the other parts are tracked there.

**Closed by timvandermeij** 2016-09-13 11:45 UTC
Labels: 1-viewer, 2-feature, 4-form-acroform
