### ISSUE TITLE
File displays on desktop, but not on mobile

### ISSUE THREAD

**Issue by aparker** [mozilla/pdf.js#10684] opened 2019-03-26 18:48 UTC
[1553116465 (1).pdf](https://github.com/mozilla/pdf.js/files/3009759/1553116465.1.pdf)
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari
- Operating system and its version: iPhone version 12.1.4
- PDF.js version: most current
- Is a browser extension: no

Steps to reproduce the problem:
1.  download the attached file into PDF.js - displays a white page 
2. Works fine on a desktop

What is the expected behavior? (add screenshot) the page should display on mobile device

What went wrong? (add screenshot) Sorry no screen shot, just got a white page

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
![desktop_edge](https://user-images.githubusercontent.com/198661/55024831-a9f7f380-4fcd-11e9-9bd8-0904dbe7ff0c.JPG)

**Comment by timvandermeij** [comment] 2019-03-26 21:40
Closing since this is a duplicate of #9474. This file contains a huge image (7152 x 4862 pixels) which a mobile device can't render because of limited resources.

**Closed by timvandermeij** 2019-03-26 21:40 UTC

**Comment by GarrettCulos** [comment] 2020-02-21 17:25
@timvandermeij Is this limit device dependent? or is the limit coded in the library.

**Comment by timvandermeij** [comment] 2020-02-21 21:34
It is enabled for mobile devices, see https://github.com/mozilla/pdf.js/blob/47ab4b839f6c16ff022c7152417950627d796cee/web/viewer_compatibility.js, but configurable in custom deployments, see https://github.com/mozilla/pdf.js/blob/93aa613db7a874e6ed964f394241605d5586c142/web/app_options.js#L97-L102
