### ISSUE TITLE
Show wrong second page when set default zoom value.

### ISSUE THREAD

**Issue by Priestch** [mozilla/pdf.js#16304] opened 2023-04-17 08:26 UTC
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/11247940/test_pdf_3.pdf)

Configuration:
- Web browser and its version: Chrome Version 110.0.5481.177 (Official Build) (64-bit)
- Operating system and its version: Ubuntu 22.04.1 5.19.0-38-generic
- PDF.js version: latest https://github.com/mozilla/pdf.js/releases/tag/v3.5.141 
- Is a browser extension: No 

Steps to reproduce the problem:
1. use git to checkout to b135dadb17793f02821910921a1277005c03a516
1. `npm install --force` to install dependencies
1. after running `gulp generic`, modify defaultOptions in `build/generic/viewer.js`
```javascript
defaultOptions.defaultUrl = {
    value: "test.pdf",
    kind: OptionKind.VIEWER
};
defaultOptions.disablePreferences = {
    value: true,
    kind: OptionKind.VIEWER
};
```  
1. copy `test.pdf` to the directory where `compressed.tracemonkey-pldi-09.pdf` located
1. setup a static server to host the viewer.html in `build/generic/viewer.html`, I run ` http-server` in `build/generic` directory
1. open the viewer.html with https://mozilla.github.io/pdf.js/web/viewer.html#zoom=100

What is the expected behavior? (add screenshot)
It should show the first page instead of the second page.

What went wrong? (add screenshot)
![secondpage](https://user-images.githubusercontent.com/2059801/232427423-aaa8fe4a-4387-4a20-9975-b7aebab04257.png)

**Comment by Snuffleupagus** [comment] 2023-04-17 08:29
Duplicate of #2843

**Closed by Snuffleupagus** 2023-04-17 08:29 UTC
