### ISSUE TITLE
Apache mod_rewrite empty arguments.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [mozilla/pdf.js#9661] opened 2018-04-13 01:36 UTC
I'm trying to apply pdf.js to any pdf file automatically. So I've put the following rule for Apache mod_rewrite:
```
RewriteRule ^(.*\.pdf)\.html$ /pdf.js/web/viewer.html?file=$1 [L]
```
And replaced all URIs to the absolute ones in the pdf.js. But now requesting of ".pdf.html" gives an error:
```
PDF.js v2.0.489 (build: 7d7bc80e)
Message: Missing PDF "https://.../dir/compressed.tracemonkey-pldi-09.pdf".
```

I'm absolutely sure that apache work well as the next rule is:
```
RewriteRule ^(.*)_colorized\.xhtml$ /colorizer?filename=$1 [L]
```
and "https://.../dir/file.c_colorized.xhtml" is displayed properly.

P.S. Yes, I've seen multiple receipts in the internet witch says to add the "R" flag to the rewrite rule I want a clean URL.

**Comment by Rob--W** [comment] 2018-04-14 08:26
Have you looked at what's being sent over the network? Usually the PDF URL is based on the `?file=` query string parameter, but since you have removed it, you'll need to set the URL in another way.

You could rewrite your code to use `var url = location.pathname.replace(/\.html$/, '');` instead of:

https://github.com/mozilla/pdf.js/blob/c33bf800cc87941cc681c3c54279ab1b9745650d/examples/svgviewer/viewer.js#L11

I'll close this issue since this looks like a problem caused by your server configuration, and not by PDF.js.

**Closed by Rob--W** 2018-04-14 08:26 UTC
Labels: 1-other
