### ISSUE TITLE
Engineering Drawings are not rendered

### ISSUE THREAD

**Issue by dalbir** [mozilla/pdf.js#9375] opened 2018-01-18 03:52 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: **Chrome 63.0.3239.132 (Official Build) (64-bit)**
- Operating system and its version: **Windows 10**
- PDF.js version:**On Demo Site** https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension:

Steps to reproduce the problem:
1. **Open attached file**
[7aa0b34c-f220-45b8-854f-06eac0754c47.pdf](https://github.com/mozilla/pdf.js/files/1641551/7aa0b34c-f220-45b8-854f-06eac0754c47.pdf)

2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
**Nothing is rendered.**
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2018-01-20 00:00
Closing as duplicate of issue #6741.

**Closed by Snuffleupagus** 2018-01-20 00:00 UTC
Labels: 3-pdf-broken
