### ISSUE TITLE
Links in the Bookmark not working

### ISSUE THREAD

**Issue by kvk123456** [mozilla/pdf.js#6788] opened 2015-12-21 21:30 UTC
If the bookmark is an html link in the PDF, then PDF.js disables the link.

https://fbutools-stage.rightmix.com/Viewer.aspx?file=%2fViewer%2fHosted%2fGetDocument.ashx%3ffile%3dhttp%3a%2f%2fstage.efinancialdocs.com%2fdocuments%2fDocData%2fFBU2001_DOC_S_201532112645_FBU2001_LOAD.PDF

Below is the screenshot from Adobe PDF viewer, which shows the link and able to click and navigate
![link_in_bookmark](https://cloud.githubusercontent.com/assets/13853369/11941778/15e31620-a800-11e5-8703-76d2426cca9e.jpg)

**Comment by timvandermeij** [comment] 2015-12-21 21:32
Closing as duplicate of #3214 which not only has links that do not work but also markup that is not shown.

**Closed by timvandermeij** 2015-12-21 21:32 UTC
