### ISSUE TITLE
invisible text divs from another page show up on page 2 and following

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#7319] opened 2016-05-11 19:33 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome Version 51.0.2704.36 beta (64-bit)
- Operating system and its version: Mac OS X El Capitan 10.11.3 (15D21)
- PDF.js version: online version as of May 22, 2016
- Is an extension:

Steps to reproduce the problem:
1. move cursor over the top of page 2, you'll "see" there are non-visible text divs around the page that do not correspond to any displayed text
2. it becomes hard to select text from the actual text
[reach.pdf](https://github.com/mozilla/pdf.js/files/260039/reach.pdf)

What is the expected behavior? (add screenshot)
not being able to select text other than what's visible text
What went wrong? (add screenshot)
text from another page was selectable.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment] 2016-05-11 19:39
I see the same problem with Adobe Viewer and Mac OS X Preview. @ldenoue can you explain what we do different?

**Comment by ldenoue** [comment] 2016-05-11 19:59
true, but it's still a strange behavior. The text is not visible and yet it is selectable.
not optimum for extracting text from pdfs :)

**Comment by yurydelendik** [comment] 2016-05-11 20:04
@ldenoue by design, PDF can contain the hidden text and it shall be selectable. Hidden text was designed to be under/over the scanned images, but it can be used anywhere.

**Comment by ldenoue** [comment] 2016-05-11 20:07
ok, thanks.
do you know how I could detect that it is not drawn so I can exclude it from the text items returned by getTextContent?

**Comment by yurydelendik** [comment] 2016-05-11 20:15
we cannot disable that for the reason that it can be used for scanned images, but you can check what getTextContent is doing and discard text when TextRenderingMode.INVISIBLE is set. Closing the issue as invalid/answered.

**Closed by yurydelendik** 2016-05-11 20:15 UTC
Labels: 4-information-requested
