### ISSUE TITLE
Unable to "select all" text in pdf

### ISSUE THREAD

**Issue by basketofcats** [mozilla/pdf.js#7650] opened 2016-09-20 17:43 UTC
Configuration:
- Web browser: Chrome Version 53.0.2785.116
- Operating system: OSX El Capitan Version 10.11.6
- PDF.js version: 1.5.294

Steps to reproduce the problem:
1. Open (apparently any) PDF JS viewer
2. ⌘+A (or Edit > Select All)

Attempting to select all text only selects current page and perhaps a few pages before and/or after.

**Comment by Snuffleupagus** [comment] 2016-09-20 17:45
Closing as duplicate of issue #1995.

**Closed by Snuffleupagus** 2016-09-20 17:45 UTC
