### ISSUE TITLE
Signature (interactive form field) non visible

### ISSUE THREAD

**Issue by dario8282** [mozilla/pdf.js#8713] opened 2017-07-28 12:56 UTC
Link to PDF file (or attach file here): [test.pdf](https://github.com/mozilla/pdf.js/files/1183043/test.pdf)
Configuration:
- Web browser and its version: Firefox
- PDF.js version: latest version online

Steps to reproduce the problem:
1.  Open test.pdf from Firefox or from the latest version of pdf.js (https://mozilla.github.io/pdf.js/ -> demo)

What is the expected behavior? At the bottom of the page there should a signature. It appears if you open the file from Internet Explorer , Chrome, FoxitReader. It is a interactive form field.

**Comment by timvandermeij** [comment] 2017-07-28 20:02
Closing since this is a duplicate of other open issues regarding this: https://github.com/mozilla/pdf.js/search?q=signature&type=Issues&utf8=%E2%9C%93

**Closed by timvandermeij** 2017-07-28 20:02 UTC

**Comment by THausherr** [comment] 2017-07-31 12:29
@dario8282 Although this isn't the cause of the problem here, the file contains two PDFs. First the unsigned, then the signed file. (instead of just the signature related changes). I.e. the signed file (which contains the unsigned file) was appended to the unsigned file. To understand what I mean open the file with NOTEPAD++ and search for %PDF-1.4 , which will appear twice.
