### ISSUE TITLE
In annotated pdf file cannot select text accurately on contents with annotation.

### ISSUE THREAD

**Issue by georgehandrew** [mozilla/pdf.js#14223] opened 2021-11-02 20:32 UTC
Attach (recommended) or Link to PDF file here:
Any pdf files with highlight/underline annotation.
Configuration:
- Web browser and its version: chrome Version 95.0.4638.54 (Official Build) (64-bit)
- Operating system and its version: win8.1
- PDF.js version: 2.10.337
- Is a browser extension: yes

Steps to reproduce the problem:
1.  open any pdf files with highlight/underline annotation on blocks of paragraph.
2.  choose text selection tool, push left mouse key and move and select text.

What is the expected behavior? (add screenshot)
On the words that has no highlight or underline annotation, words can be selected one by one accurately.

What went wrong? (add screenshot)
when mouse is moved on the words that has been highlight or underline annotation, the whole annotated block will be all selected.

An easy workaround might be let pdf.js provide a function to hide the annotation temporarily.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-11-02 20:37
Duplicate of #7013 (which is a best guess, given the lack of a test-case).

**Closed by Snuffleupagus** 2021-11-02 20:37 UTC

**Comment by georgehandrew** [comment] 2021-11-02 21:43
correct me if I am wrong---
@sharanmunyal commented it can be workaround (imperfectly) by hiding annotationlayer during the mouse down time in his own application,
https://github.com/mozilla/pdf.js/issues/7013#issuecomment-216370936
this function is not directly in pdf.js. 

It is possible pdf.js direct give the function(for example an check sign switch in menu) user can temporarily hide the annotation.
