### ISSUE TITLE
Sum and big sum symbols wrongly rendered (math equations)

### ISSUE THREAD

**Issue by Naereen** [mozilla/pdf.js#6749] opened 2015-12-13 11:14 UTC
Hi. First, thanks for the great work on ``pdf.js``.

I regularly encounter display issues with LaTeX sum and big sum symbols which are often wrongly rendered.
For example [on this article (end of page 2)](https://papers.nips.cc/paper/5701-anytime-influence-bounds-and-the-explosive-behavior-of-continuous-time-diffusion-networks.pdf#page=2) (but any other fails similarly):

![ex1](https://cloud.githubusercontent.com/assets/11994719/11766652/29a2024e-a192-11e5-9dfe-83918dc38614.png)
![ex2](https://cloud.githubusercontent.com/assets/11994719/11766653/2df9f270-a192-11e5-9015-0123639e1d10.png)

It's probable just a zoom issue : the \sum (big sigma) symbol does not scale as the rest of the equation. E.g. the first screen-shoot has a low zoom (80%) while the second one is at 250%.
(*Note:* I'm using Firefox v42 on XUbuntu 15.10 but the issue is not new)

**Comment by Snuffleupagus** [comment] 2015-12-13 11:18
Closing as duplicate of #2594.

**Closed by Snuffleupagus** 2015-12-13 11:18 UTC
