### ISSUE TITLE
Download button does not do anything until PDF is fully-loaded

### ISSUE THREAD

**Issue by hikari-no-yume** [mozilla/pdf.js#6660] opened 2015-11-18 23:24 UTC
For the longest time I thought this was some sort of magically-disappearing unreproducible bug, where I'd have to click several times on the download arrow to get the embedded PDFs on Blackboard.com (my university lecture notes) to actually bring up Firefox's download prompt.

Now, though, I realise it's just that the button will do nothing until the PDF has finished downloading. It would be more helpful if it either worked immediately, or the button was greyed out/replaced with a spinner until the document finished loading.

**Comment by Snuffleupagus** [comment] 2015-11-19 00:13
This is strange, because technically it *should* have been fixed some time ago by PR #4455, but I'm still able reproduce it with version `1.2.131` of the addon.
I'm wondering if that patch is missing some of the necessary machinery in `PdfStreamConverter.jsm` (or perhaps `firefoxcom.js`), in order for this to work correctly!?

**Comment by timvandermeij** [comment] 2015-11-19 20:33
I'm also able to reproduce this. I agree that this has worked before, so it must have regressed somewhere.

**Comment by Snuffleupagus** [comment] 2016-03-21 11:33
This behaviour in the addon/built-in version, where the download button appears unresponsive until the file has finished loading, is caused by using [asyncFetchChannel](https://github.com/mozilla/pdf.js/blob/41efb92d3a6af0be38afaf27808504e404491afd/extensions/firefox/content/PdfStreamConverter.jsm#L331). That function relies on `NetUtil.fetchAsync`, which [according to the docs](https://dxr.mozilla.org/mozilla-central/rev/f14898695ee0dd14615914f3e1401f17df57fdd7/netwerk/base/NetUtil.jsm#97-102) won't run the callback until the channel has finished loading.

The dependency on `NetUtil.asyncFetch` was added in PR #1786, which I suppose is where this broke.
After doing some quick testing, it seems to me that a simple solution would be to *not* use `asyncFetchChannel` when the `download` method (in `PdfStreamConverter`) is called *without* passing in a `blobUrl`, and rather just trigger the download directly then.

/cc @brendandahl, @yurydelendik Does the above sound like an acceptable solution to you?

---
*See also:* https://bugzilla.mozilla.org/show_bug.cgi?id=920702

**Comment by Snuffleupagus** [comment] 2016-03-24 11:47
I've tried implementing the suggestion in https://github.com/mozilla/pdf.js/issues/6660#issuecomment-199234593 (see https://gist.github.com/Snuffleupagus/e6ef3303439c10d52968), and in some quick testing it does appear to work.
I'm not sure if that is close enough to a proper solution to warrant a PR though, since my knowledge of the addon code isn't that great.

Another way to "solve" this issue could also be, as suggested above, to disable the download button until loading is complete. But that might not be a much better UX than the current behaviour though.

**Comment by Snuffleupagus** [comment] 2021-06-06 09:35
Given that all of the relevant code now lives in `mozilla-central`, let's close this as a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=920702

**Closed by Snuffleupagus** 2021-06-06 09:35 UTC
Labels: 1-addon, 3-regression

**Comment by hikari-no-yume** [comment] 2021-06-06 09:38
Maybe you should link this issue on the bugzilla, so that people can see the comments here about what the problem may be?
