### ISSUE TITLE
PDF blank in pdf viewer

### ISSUE THREAD

**Issue by milanminmin** [mozilla/pdf.js#5954] opened 2015-04-21 20:43 UTC
when i try to view this pdf in pdf viewer, it's all blank.

![bugs2](https://cloud.githubusercontent.com/assets/7914880/7262134/403620dc-e845-11e4-9c13-0617f8e25d02.jpg)

and web console shows 'Warning: Error during font loading: Font F1 is not available'

I think the reason is because of my pdf's font:
![bugs](https://cloud.githubusercontent.com/assets/7914880/7262157/6f5e7300-e845-11e4-86c9-dfd8bef99f34.jpg)

Is there any way to fix this error without change the pdf?

**Comment by timvandermeij** [comment] 2015-04-21 20:45
Confirmed broken with Windows 7 x64, Firefox 37.0.1 and the latest PDF.js development version.

**Comment by maxrails** [comment] 2015-05-13 21:18
Looks like similar issue for this pdf. Attached pdfjs demo  and original document
![encoding_trouble](https://cloud.githubusercontent.com/assets/1497819/7621304/3115dfa8-f99c-11e4-81a2-bb0647a30b83.png)

**Comment by Snuffleupagus** [comment] 2015-05-18 10:47
For some reason, the link to the original file was removed. For verification purposes, I'm temporarily re-hosting the PDF file here: https://www.dropbox.com/s/blxc2eci6s4mycl/issue5954.pdf?dl=0.

**Comment by mjstyle** [comment] 2015-05-21 22:33
Just following up to see if a fix has been pushed for the above 2 issues yet? Thanks!

**Comment by timvandermeij** [comment] 2015-05-22 18:04
@mjstyle Not yet. There is a pull request, it just has to be reviewed.

**Comment by mjstyle** [comment] 2015-05-25 22:32
@timvandermeij Thank you so much!

**Closed** 2015-05-30 13:34 UTC
Labels: 1-core, 3-pdf-broken

**Comment by mjstyle** [comment] 2015-05-31 01:19
Just following up to see when this fix will be pushed? Thanks!!

**Comment by timvandermeij** [comment] 2015-05-31 11:40
Probably two or three Firefox versions from now. It has to go through a few developement channels before it reaches the release channel.

**Comment by mjstyle** [comment] 2015-06-01 16:30
@timvandermeij Thank you for your response. Do you mean probably two or three Firefox versions from now? Do you know how long typically a new Firefox version comes out?

Thanks!!

**Comment by timvandermeij** [comment] 2015-06-01 18:40
Yes, two or three Firefox versions from now. See https://wiki.mozilla.org/RapidRelease/Calendar for exact dates.

**Comment by mjstyle** [comment] 2015-06-08 17:50
@timvandermeij Got it.

**Comment by mjstyle** [comment] 2015-10-26 14:41
@timvandermeij Would you say this issue will be fixed at Firefox 48?

Thanks!

**Comment by Snuffleupagus** [comment] 2015-10-26 15:17
> Would you say this issue will be fixed at Firefox 48?

The patch is already included in the current release version, i.e. Firefox 41.
(It was uplifted as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1175142.)

**Comment by mjstyle** [comment] 2015-12-02 21:37
@Snuffleupagus Got it. Do you know when they will be releasing this version?

**Comment by yurydelendik** [comment] 2015-12-02 21:51
@mjstyle please provide information about your configuration: operating system and pdf.js version. Also attach link to the pdf. I also recommend to open different issue if PDF is different than reported.

**Comment by mjstyle** [comment] 2015-12-03 20:38
@yurydelendik Hi! We are reporting the same issues as above since @Snuffleupagus mentioned it's fixed, but it's still not. 

Operating system: Mac
Pdf.js version: '1.1.1'

Here are the links:

https://oneclass.com/#!/notes/university-of-toronto-st-george-/economics/ECO100Y1/522940-eco100y1-lecture-1-la-1-first-principles-pdf

https://oneclass.com/#!/notes/mcgill-university/anatomy-and-cell-biology/ANAT%20416/530470/anat-416-lecture-18-bone-2-metastatic-bone-cancer-responsible-for-majority-of-cancer-deaths-docx

Please advise. Thank you.

Regards,
Jack

**Comment by timvandermeij** [comment] 2015-12-03 20:44
Those links have an embedded PDF.js instance running at version 1.1.1, i.e., very outdated. That really has to be updated to apply the fix. I cannot download anything from those links without an account, so try opening the PDF files with https://mozilla.github.io/pdf.js/web/viewer.html (the most recent viewer version) to see if the problem persists.

**Comment by yurydelendik** [comment] 2015-12-03 20:59
@mjstyle please contact https://oneclass.com/ so they update PDF.js version to newer one. Supporting custom deployments is out of scope of this project.

**Comment by mjstyle** [comment] 2015-12-03 22:11
@timvandermeij This is still happening for one of the documents, where weird characters show up. Here is the original file - https://www.dropbox.com/s/ygmic028oykprkw/respond_document_print.pdf?dl=0 when I upload it into the newly updated viewer, it's still showing up weird characters. Thank you so much!

**Comment by timvandermeij** [comment] 2015-12-03 22:15
It seems like a different issue, so I have opened #6721 to track that file.
