### ISSUE TITLE
Incognito mode issues

### ISSUE THREAD

**Issue by javalan** [mozilla/pdf.js#10976] opened 2019-07-16 01:33 UTC
Configuration:
- Web browser and its version: Kiwi browser 75.0.3770.101
- Operating system and its version: Android 8.1.0
- PDF.js version: 2.2.191
- Is a browser extension: Yes

Hi. The extension works great, except in incognito mode. When the "Allow in incognito" toggle is first switched on, the pdfs open properly in the incognito tabs, but as soon as the incognito tabs are closed and reopened, the pdfs do not open anymore, but are download instead. To work around this issue, one has to manually switch the extension off and back on again within an ingognito tab - which is a big hassle. Please have a look at this issue.

**Comment by timvandermeij** [comment] 2019-07-16 20:25
I don't know Kiwi browser, but the Google Play Store states that it's built upon Chromium, so I presume the extension here is the Chrome extension.

/cc @Rob--W: have you perhaps seen bug reports regarding incognito mode in combination with the extension before?

**Comment by Rob--W** [comment] 2019-07-17 17:51
Cannot reproduce in Chromium 75.0.3770.90 on desktop. Chromium doesn't officially support extensions on mobile, so this looks like a bug in the Kiwi browser.

Firefox for Android does officially support extensions though, so if you want to use a mobile browser with proper extension support, consider using Firefox.

PDF.js does currently not have an official Firefox add-on for Android, but it is technically possible to build one that works even better than in Chrome (because Firefox provides extra features (compared to Chromium) that enables extensions to replace the content without requiring an ugly URL). The following add-on also uses PDF.js (without taking full advantage of what I just mentioned, but it works): https://addons.mozilla.org/en-US/android/addon/android-pdf-js/

Closing bug because this looks like a bug in the Kiwi browser, not PDF.js.

**Closed by Rob--W** 2019-07-17 17:51 UTC
Labels: 1-addon, 4-chrome-specific
