### ISSUE TITLE
Printing not showing all the pages.

### ISSUE THREAD

**Issue by LuigiMaestrelli** [mozilla/pdf.js#9015] opened 2017-10-10 14:23 UTC
Attach (reccomened) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 61.0.3163.100 x64
- Operating system and its version: Windows 10
- PDF.js version: Last on at https://mozilla.github.io/pdf.js/web/viewer.html
- Is an extension: No

Steps to reproduce the problem:
1. Open de PDF on https://mozilla.github.io/pdf.js/web/viewer.html
2. Right click on the page and select the print option.

What is the expected behavior? (add screenshot)
Print the full page.

What went wrong? (add screenshot)
It only shows a couple pages, or, some times just a blank page.
![image](https://user-images.githubusercontent.com/5038871/31391500-18bab966-adad-11e7-81fa-5a2014e39b55.png)

**Comment by THausherr** [comment] 2017-10-20 12:12
Print Preview on FF 56.0.1 (64-Bit) shows only 2 pages.

**Comment by yurydelendik** [comment] 2017-10-26 00:19
> Right click on the page and select the print option.

I wonder why beforeprint/afterprint are not working anymore. Maybe regression.

**Comment by timvandermeij** [comment] 2021-03-14 14:43
Closing since this is fixed now in both Firefox and Chrome. It looks like this got fixed upstream.

**Closed by timvandermeij** 2021-03-14 14:43 UTC
Labels: 3-regression, 4-printing
