### ISSUE TITLE
Selection of a paragraph jumping to selection of the whole document

### ISSUE THREAD

**Issue by lionelscorsearch** [mozilla/pdf.js#14659] opened 2022-03-11 10:01 UTC
Attach (recommended) or Link to PDF file here:
[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/8231398/compressed.tracemonkey-pldi-09.pdf)

Configuration:
- Web browser and its version: chrome 99
- Operating system and its version: windows 10
- PDF.js version: unknown (the file available here: https://mozilla.github.io/pdf.js/build/pdf.js )
- Is a browser extension: no

Steps to reproduce the problem:
1. Have a PDF file shown using PDF.JS
2. Have a paragraph in the PDF
3. Using mouse, select the paragraph, from the beginning to the end
4. At the end of the paragraph, keep mouse pressed and go a bit (1 char) beyond the end of the paragraph

Expected behavior: only the paragraph should be selected
![image](https://user-images.githubusercontent.com/91599270/157857232-d2c1f2e5-9fac-4770-84e9-d2052b61c3a6.png)

What went wrong: the next paragraph gets selected
![image](https://user-images.githubusercontent.com/91599270/157857299-51023496-eb4b-4e6c-b791-dc3969662643.png)

I found a kind of solution (hack) but I'm afraid of the side effects
```
                let textLayerChildren = document.querySelector(".textLayer").children;
                for (let i = 0; i < textLayerChildren.length; i++) {
                    textLayerChildren[i].style.width = '500em';
                    textLayerChildren[i].style.height = '10em';
                }
```
Can you either fix the issue or tell me if my solution (hack) is safe to use here ?

**Comment by Snuffleupagus** [comment] 2022-03-11 10:40
The `Attach (recommended) or Link to PDF file here:`-part of the ISSUE_TEMPLATE is *always required* when opening an issue, since as-is this unfortunately isn't actionable/valid.

> Can you either fix the issue or tell me if my solution (hack) is safe to use here?

It's *completely impossible* to fix an issue without access to the PDF document in question, and your hack is *definitely not* correct/safe in general.

**Comment by lionelscorsearch** [comment] 2022-03-11 11:21
I added a PDF sample where the issue occurs.
I also updated the screenshots to match the PDF sample.

**Comment by Snuffleupagus** [comment] 2022-03-11 11:31
Duplicate of #9843

**Closed by Snuffleupagus** 2022-03-11 11:31 UTC
Labels: information-requested
