### ISSUE TITLE
MissingPDFException if the file or folder has a hash (#)

### ISSUE THREAD

**Issue by ollm** [mozilla/pdf.js#17834] opened 2024-03-24 17:31 UTC
### Configuration

- Web browser and its version: `electron v25.9.8`
- Operating system and its version: `Ubuntu 22.04`
- PDF.js version: `pdfjs-dist v4.0.379`

### Steps to reproduce the problem:

The steps are simple, just add a hash (#) to the pdf file or folder, I don't know if it happens with other characters.

```js
await unpdf.getDocument({url: 'example/path/#name/file.pdf'}).promise;
```

### What is the expected behavior?

pdf.js should correctly load the file.

A temporary solution I have found is to use `encodeURIComponent`, I don't know if this is already the expected behavior.

```js
await unpdf.getDocument({url: encodeURIComponent('example/path/#name/file.pdf').replace(/\%2F/g,'/')}).promise;
```

**Comment by Snuffleupagus** [comment] 2024-03-24 17:54
Duplicate of #10632

**Closed by Snuffleupagus** 2024-03-24 17:54 UTC
