### ISSUE TITLE
FreeText annotation, does not support arabic

### ISSUE THREAD

**Issue by ahmadmarafa** [mozilla/pdf.js#15350] opened 2022-08-25 22:09 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google chrome 104.0.5112.79 
- Operating system and its version: Debian GNU/Linux 11 (bullseye) 
- PDF.js version: 2.15.349
- Is a browser extension: No

Steps to reproduce the problem:
1.  Open PDF file, try to add FreeText annotation in Arabic
2. Save PDF file and, you will find that Arabic text is not displayed probably

**Comment by Snuffleupagus** [comment] 2022-08-25 22:32
This is, for all intents and purposes, a duplicate of issue #12430 and [bug 1666824](https://bugzilla.mozilla.org/show_bug.cgi?id=1666824).

**Closed by Snuffleupagus** 2022-08-25 22:32 UTC
