### ISSUE TITLE
PDFJS rendering barcode as text 

### ISSUE THREAD

**Issue by justrajesh** [mozilla/pdf.js#7887] opened 2016-12-11 06:03 UTC
Hi, 
I integrated PDFJS in one of my internal sites, and it works great, but I am stuck with one of the PDF, where the texts are in chinese and barcode do not get rendered. the encoded font type is "ArialUnicodeMS" (subtype = Type0 font)

Initially I had a blank PDF rendered, even though the pdf had text and Barcode was blank, Then I saw the error in the console and added a try catch arround the code in pdfjs.work.js file --> [data = this.convert(name, cff, properties);], then chinese text statred rendering but I am still stuck with the barcode, the barcode shows the text "ÍÂÂ"8Â!Î" instead of the actual barcode.

Referred code where try catch block is added 

var Font = (function FontClosure() {
..............

try { 
        	data = this.convert(name, cff, properties);
        }catch (e) {
        	console.log(e.message); //Cannot read property '1' of undefined        	
        }

The barcode on the PDF file in rendered as a text and not as barcode.
The pdf file has some account information, so I am not able to attach the pdf file, but I will try to attach one with similar issue soon
Kindly help me, 
I am using PDFJS version 1.4.20

Thanks and Regards
Rajesh
![image](https://cloud.githubusercontent.com/assets/23747392/21078442/cda0ee78-bf3c-11e6-931d-1767c0444650.png)

**Comment by timvandermeij** [comment] 2016-12-11 15:24
Update to the most recent release to check if that makes any difference (see https://github.com/mozilla/pdf.js/releases). If not, we do need a PDF file to look into this issue. Try to create a new one without sensitive information, or remove the sensitive information from the PDF file. Without it, this issue will be closed as incomplete.

**Comment by justrajesh** [comment] 2016-12-11 17:56
Link to PDF file : I will upload the PDF file tomorrow afternoon EST (I have to upload it from my office laptop)

Configuration:
- Web browser and its version: Chrome 54, Firefox 50.02, IE 11 (I tried in all these browsers and the issue is reproducible consistently)
- Operating system and its version: Windows 7
- PDF.js version: 1.4.20 (tried in 1.5.188 and 1.6.380 and same issue is found, so reverted to 1.4.20 )
- Is an extension: (I am able to reproduce this issue in Firefox default PDF Viewer too on firefox, but the same works correctly in Chrome default PDF viewer and Acrobat reader, but strangely it does not work with the PDFJS library downloaded on all browsers).

Most of my other PDFs are good on PDFJS, but only pdf files from one specific team is giving trouble.

**Comment by justrajesh** [comment] 2016-12-13 16:17
The PDF with the reported issue has customer confidential data, I am not allowed to share that PDF as is. I will try to create another PDF with some other similar content. Once I have the PDF ready I will come back and update this ticket.

**Comment by timvandermeij** [comment] 2016-12-18 14:44
Closing as incomplete. However, we will reopen this once a PDF file is provided.

**Comment by justrajesh** [comment] 2017-06-26 17:48
Hi, 
I am again facing the same issue with another similar font, where the PDF.js code flows throw the same exception path. This time also the font type is same. I guess I badly need support.
I extracted the font file from the faulty PDF and created a blank PDF with the fault font 
font Type: "CIDFontType0"
font Name: ArialNarrowUnicode-Bold
Issue: Fails to load font with the below exception:
Warning: Error during font loading: Cannot read property '1' of undefined
Some how in my local pdf-worker.js, I could manage to add a try catch and preserve the text information on the pdf, but could not succeed in retrieving the barcode in the PDF. I guess the font files need to be loaded correctly, otherwise I may end up in multiple issues.

I cannot add the original PDF, so I created a blank PDF with the a Hello world text, for some reason I could not map the font and text correctly, so the PDF is going to be blank. But I am getting the error message in the debugger window (exactly the same error). I hope you should be fine to see the debugger console.
[extract.pdf](https://github.com/mozilla/pdf.js/files/1103001/extract.pdf)
formation and hope that you should be ok with the blank PDF for your analysis.

**Comment by justrajesh** [comment] 2017-06-26 17:49
I am not sure how to reopen this issue, but added the test PDF, could you please reopen this issue?

**Comment by Snuffleupagus** [comment] 2017-06-26 18:55
This is what I see in the console:
```
PDF 1e83e10ed16766d7601d1957675f8f16 [1.4 iText® 5.5.10 ©2000-2015 iText Group NV (AGPL-version) / -] (PDF.js: 1.8.493) viewer.js:1509:7
Warning: Invalid "Length1" property in Type1 font -- trying to recover. pdf.worker.js:344:5
Warning: Unable to recover "Length1" property in Type1 font -- using as is. pdf.worker.js:344:5
Warning: Error during font loading: ranges[(ranges.length - 1)] is undefined pdf.js:344:5
```
The font file looks *initially* like a Type1 font file, but doesn't actually seem to contain proper Type1 font data.

Since it appears that the the provided example PDF file renders completely blank in other PDF viewers as well (e.g. Adobe Reader), it's difficult to tell what it "should" look like (provided that it works).
In my opinion, the provided `extract.pdf` file looks somewhat broken with regards to its font handling, which thus makes any sort of meaningful debugging of the *font* specific issues very difficult. Furthermore, it's also not really clear if the reduced test-case is a good representation of the original PDF file.

Unfortunately I don't think that it makes sense to re-open this given the above; we'd really need a reduced test-case that clearly works in other PDF viewers (e.g. Adobe Reader).

**Closed by Snuffleupagus** 2017-06-26 18:55 UTC
Labels: 4-information-requested

**Comment by justrajesh** [comment] 2017-06-26 19:20
Hi, 
The error message you see is exactly correct, the same issue is what I am getting on PROD server too. I debugged with the real PDF and this blank PDF and they both run through the same lines of pdf.worker.js file.

If I use the pdf.worker.js as is, the page breaks as soon as it sees this font. and the page is blank.
As you pointed out the below JS error (I copied the error message from your reply) is what I am also getting on the real PDF.

Warning: Invalid "Length1" property in Type1 font -- trying to recover. pdf.worker.js:344:5
Warning: Unable to recover "Length1" property in Type1 font -- using as is. pdf.worker.js:344:5
Warning: Error during font loading: ranges[(ranges.length - 1)] is undefined pdf.js:344:5

The PROD version of PDF works correctly on Acrobat Reader and the default PDF Viewer on Chrome, but it do not work/render this font on custom PDF.js file as well as the default firefox browser. This is a valid font and I have couple of fonts with the same issue. I thought if we could fix the current one, I assume that the rest of the fonts also gets fixed.

Could you please check why we are getting "Warning: Invalid "Length1" property in Type1 font "?

**Comment by Snuffleupagus** [comment] 2017-06-26 19:30
> I debugged with the real PDF and this blank PDF and they both run through the same lines of pdf.worker.js file.

While I see no reason to doubt that, how are we supposed to meaningfully debug this when the PDF file renders completely blank by design!?
Even if we managed to fix the issue, it would be impossible to know that for certain (and we wouldn't be able to add a regression test with a blank file either).

> This is a valid font and I have couple of fonts with the same issue.

Please keep in mind that just because you've got a number of examples, that doesn't *necessarily* imply that the font is actually *valid*. Many PDF generators unfortunately include more or less broken font data in files.

> Could you please check why we are getting "Warning: Invalid "Length1" property in Type1 font "?

Quoting from https://github.com/mozilla/pdf.js/issues/7887#issuecomment-311149911: "The font file looks *initially* like a Type1 font file, but doesn't actually seem to contain proper Type1 font data."
