### ISSUE TITLE
PDF with blank pages

### ISSUE THREAD

**Issue by pkelbern** [mozilla/pdf.js#8182] opened 2017-03-22 12:26 UTC
[PDF with blank pages.pdf](https://github.com/mozilla/pdf.js/files/861340/PDF.with.blank.pages.pdf)

Configuration:
- Web browser and its version: Firefox 52.0.1 32 Bits
- Operating system and its version: Windows 8.1 64 bits
- PDF.js version: 1.6.315
- Is an extension: No

The pdf opens on firefox but with blank pages, On Chrome and Adobe it works correctly

**Comment by timvandermeij** [comment] 2017-03-22 22:59
I looked into this a bit. The last valid marker is 0xFFDA (SOS marker). When the offset is increased at https://github.com/mozilla/pdf.js/blob/master/src/core/jpg.js#L831, we end up at the 0xEA28 marker, which is invalid. I think we end up too far in the stream, as a few bytes back we have 0xFFD4, which is a valid RST marker.

**Comment by timvandermeij** [comment] 2017-03-22 23:21
Marking as a regression as this worked in https://github.com/mozilla/pdf.js/pull/6606#issuecomment-154712772.

**Comment by timvandermeij** [comment] 2017-03-22 23:27
116ba19dd90c56d729c0d1b163adcece9c291296 is the first bad commit
commit 116ba19dd90c56d729c0d1b163adcece9c291296
Author: Jonas Jenwald <jonas.jenwald@gmail.com>
Date:   Thu Sep 22 14:07:20 2016 +0200

    Respect the 'ColorTransform' entry in the image dictionary when decoding JPEG images (bug 956965, issue 6574)
    
    Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=956965.
    Fixes 6574.

**Comment by Snuffleupagus** [comment] 2017-03-23 08:13
This isn't really a regression from PR #7661 as such, since quoting myself (from PR #8164):
> Note that while issue #7828 became a problem after PR #7661, it isn't really a regression from that PR. The explanation is rather that we're now relying on `core/jpg.js` instead of the Native Image decoder in more situations than before, which thus exposed an existing issue in our JPEG decoder.

> I think we end up too far in the stream somehow, as a few bytes back we have 0xFFD4,

I'd say that the problem actually is that we're not reading *enough* of the image, i.e. it seems that there may be more scan data than expected. Anyway, I look into this later on, and see if I can fix it!

**Closed** 2017-03-27 15:20 UTC
Labels: 3-pdf-broken, 4-image-conversion, 4-image-jpeg
