### ISSUE TITLE
Text Selection and Search does not work as expected.

### ISSUE THREAD

**Issue by dhanbhan** [mozilla/pdf.js#18124] opened 2024-05-21 10:07 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
https://github.com/mozilla/pdf.js/issues/17362 is the original issue reported and we have no further updates from PDFjs on their next plan. 

By when we can expect progress on this issue after issue is confirmed and accepted by PDSFjs ?

**Comment by Snuffleupagus** [comment] 2024-05-21 10:15
Duplicate of #17362

---

***Please don't spam the bug tracker by asking for updates, since that waste peoples time.
Please keep in mind that this is an open-source project that you're able to use for free.***

**Closed by Snuffleupagus** 2024-05-21 10:15 UTC
