### ISSUE TITLE
Stop mixing "import" and "require"

### ISSUE THREAD

**Issue by hbi99** [mozilla/pdf.js#11552] opened 2020-01-30 15:44 UTC
Any chance you will clean up the mess of mixing **import** and **require**?

**Comment by Snuffleupagus** [comment] 2020-01-30 15:59
> Any chance you will clean up the mess of mixing **import** and **require**?

What "mess" are you actually referring to here, since this issue is currently missing sufficient details to really be actionable/valid!?

There's potential for some additional `import` usage once #10965 is resolved one way or another (see e.g. https://github.com/mozilla/pdf.js/issues/10965#issuecomment-568252833), but we'll most likely never get rid of *all* `require` calls[1].

All-in-all, I'd suggest closing this as a duplicate of #10965.

---
[1] The ones in [`src/shared/compatibility.js`](https://github.com/mozilla/pdf.js/blob/master/src/shared/compatibility.js), and the build-specific ones in [`web/viewer.js`](https://github.com/mozilla/pdf.js/blob/master/web/viewer.js), probably won't/can't be changed.

**Closed** 2020-01-30 22:35 UTC

**Comment by hbi99** [comment] 2020-02-02 18:11
There is no reason to use require in the files below...it breaks overall coding practices.

```
// core/glyphlist.js
17: var getLookupTableFactory = require("./core_utils.js").getLookupTableFactory;
```
```
// core/unicode.js
var getLookupTableFactory = require("./core_utils.js").getLookupTableFactory;
```

**Comment by Snuffleupagus** [comment] 2020-02-02 18:49
> There is no reason to use require in the files below...it breaks overall coding practices.

Yes, it is most certainly necessary!
Unless those files are kept ES5-compatible, providing Babel translated builds of the PDF.js library wouldn't work because size of those files; see https://github.com/mozilla/pdf.js/pull/8287#issue-115954313.

**Comment by Snuffleupagus** [comment] 2020-02-02 18:50
> There is no reason to use require in the files below...it breaks overall coding practices.

Yes, it is most certainly necessary!
Unless those files are kept ES5-compatible, providing Babel translated builds of the PDF.js library wouldn't work because Babel cannot handle files that large; see https://github.com/mozilla/pdf.js/pull/8287#issue-115954313.

**Comment by hbi99** [comment] 2020-02-02 23:06
Then I am really sorry you are dealing with this mess - a lot bigger than I first thought :-(
