### ISSUE TITLE
Publish web/viewer.html to pdfjs-dist npm package

### ISSUE THREAD

**Issue by paulproteus** [mozilla/pdf.js#5709] opened 2015-02-08 02:37 UTC
As a prospective user of the `pdfjs-dist` npm package (stored in github here https://github.com/mozilla/pdfjs-dist and listed here https://www.npmjs.com/package/pdfjs-dist ), I'm interested in using the `web/viewer.html` component that is available in the PDF.js source.

I may work on a pull request to implement this, but wanted to file this issue first as a heads-up. If there's a reason it's not included right now, I would love to hear it.

Thanks!

**Comment by Snuffleupagus** [comment] 2015-02-08 09:36
Closing as duplicate of issue #5609.

**Closed by Snuffleupagus** 2015-02-08 09:36 UTC
