### ISSUE TITLE
[Bug]: White horizontal lines are displayed on pictures

### ISSUE THREAD

**Issue by tengel07** [mozilla/pdf.js#18969] opened 2024-10-28 10:17 UTC
### Attach (recommended) or Link to PDF file

[TS017594660.pdf](https://github.com/user-attachments/files/17540886/TS017594660.pdf)

### Web browser and its version

Chrome, Firefox, MS Edge (latest versions)

### Operating system and its version

Windows, Mac

### PDF.js version

Latest released

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the attached sample document using pdf.js viewer.
2. White horizontal lines are displayed on pictures.

### What is the expected behavior?

Pictures should be displayed clearly without white horizontal lines.

### What went wrong?

White horizontal lines are displayed on pictures.

**Comment by Snuffleupagus** [comment] 2024-10-28 10:26
Duplicate of #3351

**Closed by Snuffleupagus** 2024-10-28 10:26 UTC

**Comment by Snuffleupagus** [comment] 2024-10-28 10:32
> ### Web browser and its version
> 
> Chrome, Firefox, MS Edge (latest versions)
> ### Operating system and its version
> 
> Windows, Mac
> ### PDF.js version
> 
> Latest released

*For future reference:* Please remember to always provide version *numbers*, since it's not entirely clear what "latest" actually refers to (it could mean the latest stable, beta, or development versions) and by e.g. next week what latest means can have changed as well.

**Comment by calixteman** [comment] 2024-10-28 10:42
For info, Acrobat shows the same artifacts but not Chrome.
Here the white lines are because of the clip box around each images:
 - we round the coordinates before drawing an image
 - we don't round coordinates of the points in paths.

If I just disable clipping in `canvas.js`, the display is correct.

**Comment by TejapriyaV** [comment] 2024-10-29 12:31
What are the other impacts of disabling clipping in canvas.js?

**Comment by calixteman** [comment] 2024-10-29 13:33
> What are the other impacts of disabling clipping in canvas.js?

You'll get a lot of very bad rendering issues.

I tested that just to confirm that it's an issue related to the coordinates of the clip box.
If you're the pdf producer, you can try to remove the stuff which clips each sub-part of the overall image.

**Comment by TejapriyaV** [comment] 2024-10-30 12:04
Thanks for the details. We are not PDF producer but user can use any PDF and open it in our viewer. 
Will fix be given to address this issue in future release?
