### ISSUE TITLE
Open the PDF content blank

### ISSUE THREAD

**Issue by zhuyi1995** [mozilla/pdf.js#10721] opened 2019-04-09 10:22 UTC
Attach (recommended) or Link to PDF file here:
http://7n.m-visitor.medsci.cn/mhst/pdf/%E4%BA%8C%E7%94%B2%E5%8F%8C%E8%83%8D%E7%BC%93%E9%87%8A%E5%89%82%E6%95%88%E4%BB%B7%E6%AF%94%E4%BC%98%E5%8A%BF%E6%98%8E%E6%98%BE.pdf

Steps to reproduce the problem:
1.  
![TIM截图20190409182214](https://user-images.githubusercontent.com/29394520/55792960-5d93d400-5af4-11e9-9b5f-0df30e4bf8b4.png)
Open the PDF content blank
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-04-09 10:44
Duplicate of #10660; please see https://github.com/mozilla/pdf.js/issues/10660#issuecomment-475185456 for additional details.

**Closed** 2019-04-09 21:11 UTC
