### ISSUE TITLE
Blurry graph in pdf

### ISSUE THREAD

**Issue by MarcABernard** [mozilla/pdf.js#9648] opened 2018-04-10 12:03 UTC
Attach (recommended) or Link to PDF file here:
[Test PDF.pdf](https://github.com/mozilla/pdf.js/files/1894462/Test.PDF.pdf)

Configuration:
- PDF.js version: latest (from https://mozilla.github.io/pdf.js/web/viewer.html)

Steps to reproduce the problem:
1. Open pdf using viewer.html. Line graph looks very blurry.
2. Open pdf in Chrome, Adobe, etc. Line graph looks great.

What is the expected behavior? (add screenshot)

In Chrome:
![chrome](https://user-images.githubusercontent.com/20442835/38555783-78689b40-3c95-11e8-90ba-06abc53c7918.png)

What went wrong? (add screenshot)

In viewer.html:

![pdfjs](https://user-images.githubusercontent.com/20442835/38555821-971f1794-3c95-11e8-9f2c-488b26542818.png)

**Comment by Rob--W** [comment] 2019-03-27 17:57
Looks good to me in PDF.js in Chrome, but bad in Firefox. Could it be browser-specific?

**Comment by MarcABernard** [comment] 2019-03-27 18:09
It does look good using the latest version. This was logged back when 1.10.88 was probably the current version.

We worked around it by scaling that image ourselves, rather than letting the browser do it.

**Comment by timvandermeij** [comment] 2019-03-27 22:44
Looks bad for me in Firefox 66 on Arch Linux as well. Marking as Firefox-specific for now.

**Comment by Snuffleupagus** [comment] 2021-04-17 15:53
According to some quick (manual) bisecting, this was *indirectly* fixed by PR #11707 and/or #11601 (this issue looks for all intents and purposes like a duplicate of #7041).

**Closed** 2021-04-17 16:01 UTC
Labels: 1-viewer, 2-image-quality, 4-firefox-specific
