### ISSUE TITLE
PDFjs mispositions footer/header logos in this pdf, overlapping other content

### ISSUE THREAD

**Issue by gijsk** [mozilla/pdf.js#11830] opened 2020-04-21 10:32 UTC
(The issue summary probably should be updated based on the technical cause of this issue.)

Attach (recommended) or Link to PDF file here:

https://www.christianaid.org.uk/sites/default/files/2020-04/Christian%20Aid%20Week%20Order%20of%20Service.pdf

Configuration:
- Web browser and its version: Firefox 75 release, 76 beta
- Operating system and its version: macOS
- PDF.js version: can reproduce on https://mozilla.github.io/pdf.js/web/viewer.html when downloading and opening the PDF there
- Is a browser extension: no, builtin to the browser.

Steps to reproduce the problem:
1. open PDF, scroll down to the bottom of the first page or top of the last page

What is the expected behavior?
Bottom of first page:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/375983/79855875-76032380-83c3-11ea-998f-8bdcb2166c82.png">

What went wrong?

Bottom of first page in pdfjs:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/375983/79855926-8adfb700-83c3-11ea-840c-b706f533559d.png">

There is also a strange raster pattern visible on the entire PDF when viewed in pdfjs, but not in pdfium or Preview.app .

**Comment by Snuffleupagus** [comment] 2020-04-21 10:51
Duplicate of #269

**Comment by timvandermeij** [comment] 2020-04-21 21:21
Yes, this is because of missing layer support tracked in the issue above. Closing as a duplicate of that one; thanks!

**Closed by timvandermeij** 2020-04-21 21:21 UTC
