### ISSUE TITLE
Short circuit when no glyphs?

### ISSUE THREAD

**Issue by logannc** [mozilla/pdf.js#9492] opened 2018-02-16 20:47 UTC
I am not familiar enough with PDFs to fully describe this issue and I cannot upload the PDF that generated this behaviour (as it was a client's PDF). The 'fix', however, is straightforward and someone can tell me whether it is a crap idea or not.

Configuration:
- Web browser and its version: Version 63.0.3239.132 (Official Build) (64-bit)
- Operating system and its version: Ubuntu 17.10
- PDF.js version: Dunno

Steps to reproduce the problem:
1. Have a janky PDF where `glyphs === [] && this.current.font === undefined` in https://github.com/mozilla/pdf.js/blob/25bbff46927cb91cb72f62cbd681a20535d914f6/src/display/canvas.js#L1432

What is the expected behavior? (add screenshot)
Render the page

What went wrong? (add screenshot)
Didn't render the page due to an exception (cannot read property 'isType3Font' of undefined on line https://github.com/mozilla/pdf.js/blob/25bbff46927cb91cb72f62cbd681a20535d914f6/src/display/canvas.js#L1435

My local fix was to simply add

```
if (!glyphs.length) { return; }
```
at the top of the function to short circuit when there is no work to do.

I didn't want to go through the effort of forking and making a PR if there is a valid reason for `glyphs === []` that means we can't short circuit. I assume someone on here can tell me fairly shortly.

**Comment by Rob--W** [comment] 2018-02-16 23:38
`this.current.font === undefined` implies that `showText` is called before `setFont` is called, potentially after `this.current` was reset again (e.g. in function `restore` or `beginAnnotation`).

I tried to manually create a PDF that triggers the code pathts:

```
BT
q % Save
/F1 20 Tf % setFont using a font identified by "F1" that I created elsewhere.
Q % restore
19 49 Td(Some text here) Tj % showText
ET
```

The result is a file that cannot be displayed, not in PDF.js, not in Chrome. If I comment out the line with "Q", then the file is shown as expected in both viewers.

When I create a PDF without ever setting the font, then the page cannot be displayed either:

```
BT
19 49 Td(Some text here) Tj % showText
ET
```

The thing that I haven't tried is to create an annotation. Do you know whether the PDF is using annotations? Is the PDF displaying correctly in other PDF Viewers?
Can you try to extract the specific page of the PDF that is displayed incorrectly, and share it (you can privately mail it).

For the record, this is the hand-written PDF where I attempted to reproduce the problem (the text drawing commands are between "stream" and "endstream"):

```
%PDF-1.1
1 0 obj
<</Type/Catalog/Pages 2 0 R>>
endobj
2 0 obj
<</Type/Pages/Count 1/Kids[3 0 R]/MediaBox [0 0 200 100]>>
endobj
3 0 obj
<</Type/Page/Parent 2 0 R/Resources<</Font<</F1<</Type/Font/Subtype/Type1/BaseFont/Arial>>>>>>/Contents 4 0 R>>
endobj
4 0 obj
<</Length 34>>
% BT = beginText
% Tf = setFont
% Tj = showText
% ET = endText
% "/F1 20 Tf" should follow after BT, but I removed it below.
stream
BT
19 49 Td(Some text here) Tj
ET
endstream
endobj
xref
0 5
0000000000 65535 f 
0000000009 00000 n 
0000000054 00000 n 
0000000128 00000 n 
0000000255 00000 n 
trailer
<</Root 1 0 R/Size 5>>
startxref
461
%%EOF

```

**Comment by logannc** [comment] 2018-02-17 00:24
It is 2 pages and the first page fails to display but the second does. Would the way we invoke PDF.js matter?

I will not be able to send a copy.

The PDF does display correctly in other viewers (well, it displays - there were some graphs where the lines and dots seemed missing, so it's hard to say whether it was 'correct'). How would I extract the pdf contents in a form like you have here?

I will have to check for annotations and look into the contents directly Monday.

**Comment by logannc** [comment] 2018-02-17 00:25
Also, the client regenerated the PDF, which now works. I can possibly diff the two if you can tell me how to get it into that text form.

**Comment by Rob--W** [comment] 2018-02-17 00:33
You could try the following to normalize and decompress the PDF (using the `qpdf` tool):

```
qpdf --empty --stream-data=uncompress --object-streams=disable --pages inputfile.pdf 1-1 -- outputfile.pdf
```

This extracts the first page of the PDF. Since you mention issues in `showText`, I suggest to look for an object that contains something like `number number (some text) Tj`. You can then redact the section if needed (if you are not sure if it is the correct page, see if the text matches up with what you see in the JavaScript debugger when you stepped through the code), and share the result here. It would be even more awesome if you (manually) recreate a file that you can share, but if not, you can start with sharing the specific section.

**Comment by timvandermeij** [comment] 2018-03-02 22:25
I'm going to close this issue since it's not actionable without a PDF file to reproduce the issue. If you manage to create one, we can reopen this.

**Closed by timvandermeij** 2018-03-02 22:25 UTC
Labels: 4-font-conversion, 4-information-requested
