### ISSUE TITLE
some confuse about the api getTextContent

### ISSUE THREAD

**Issue by RangoEnvy** [mozilla/pdf.js#12866] opened 2021-01-16 02:42 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 84
- Operating system and its version: macOS 10.15.5
- PDF.js version: 2.5.207
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/50538883/104794873-8aa30980-57e5-11eb-8717-725173b14cce.png)

when i parse a pdf, it parse the content to so many single letters, i am confuse that why not merge them into a word?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by RangoEnvy** [comment] 2021-01-16 06:01
i want to know the function getTextContent's logic so that i can avoid it

**Comment by Snuffleupagus** [comment] 2021-01-16 09:17
> Attach (recommended) or Link to PDF file here:

Without this information, the issue is not actionable/valid.

> i am confuse that why not merge them into a word?

In general that's actually done, however this is a very complex topic with a lot of heuristics and sometimes things aren't perfect.

---

As-is, this issue contains no actionable information and furthermore it's more-or-less guaranteed to be a duplicate of existing issues in https://github.com/mozilla/pdf.js/labels/4-text-selection

**Closed** 2021-01-16 14:28 UTC
