### ISSUE TITLE
Strange PDF display behavior 

### ISSUE THREAD

**Issue by Todai88** [mozilla/pdf.js#8476] opened 2017-06-02 10:48 UTC
## Important **EDIT**:

I have now tried picking up the .PDF from a url inside of the project. Error still occurs...

## Here is a SO thread about the problem with all code:
[https://stackoverflow.com/questions/44326665/strange-behavior-when-displaying-pdf-in-html](https://stackoverflow.com/questions/44326665/strange-behavior-when-displaying-pdf-in-html)

## Configuration:
- Web browser and its version: **Chrome Version 58.0.3029.110 (64-bit)**
- Operating system and its version: ** Windows 10 **
- PDF.js version:  Latest Stable
- Is an extension:

## Steps to reproduce the problem:

As this is using a unsecured REST API I can't really tell you how to reproduce the error.

But basically what's happening is that I'm using AngularJS $http library to grab a JSON Array from said API. One of the fields of the JSONObjects in the Array is a `varbinary(max)` reprentation of a PDF which in Angular gets decoded into a string (according to `typeof`). 

**Code:**

This is how I pull out the data using Angular: 

    $http.post("http://some-example.com/api/PDF/Get", JSON.stringify(vm.content))
    	.then(function (response) {
    		//success
    
    		vm.data = response.data;
    		$sce.trustAsResourceUrl(vm.data[0].Pdf);
    	},
    	function (error) { 
    
    	})
    	.finally(function () {
    		let pdf = atob(vm.data[0].Pdf);
    		let loadingTask = PDFJS.getDocument({ data: pdf }); 
    
    		loadingTask.promise.then(function (pdf) { 
    
    			let pageNumber = 1;
    			pdf.getPage(pageNumber).then(function (page) {
    				let scale = 1;
    				let viewport = page.getViewport(scale);
    
    				let canvas = document.getElementById('test-canvas');
    				let context = canvas.getContext('2d');
    				canvas.height = viewport.height;
    				canvas.width = viewport.width;
    
    				let renderContext = {
    					canvasContext: context,
    					viewport: viewport
    				};
    				let renderTask = page.render(renderContext);
    				renderTask.then(function () { 
    					// Wait for rendering to finish
    					renderTask.promise.then(function () {
    						pageRendering = false;
    						if (pageNumPending !== null) {
    							// New page rendering is pending
    							renderPage(pageNumPending);
    							pageNumPending = null;
    						}
    					});
    				}); 
    			});
    		});
    	});

Checking out the `Pdf` of the returned object it seems to be of type `string` and seems to have a decoded binary value as the Pdf value in the database is encoded.

This is how the data is returned by my REST API (C#):

    [HttpPost]
    public HttpResponseMessage Get(int get_id = 0)
    {
    	HttpContent req = Request.Content;
    	int val = 0;
    	string jsonContent = req.ReadAsStringAsync().Result;
    	JObject jobobj = JObject.Parse(jsonContent);
    	string where = null;
    	List<test_pdf_table> list = new List<test_pdf_table>();
    	DataSet ds = null;
    	
    	try
    	{
    		where = (jobobj["where"] == null) ? null : (string)jobobj["where"];
    		string strcon = ConfigurationManager.ConnectionStrings[(string)jobobj["strcon"]].ConnectionString;
    		ds =  dc.FETCHtest_pdf_table((where == null) ? "Where ID = " + get_id : where, (strcon == null) ? conStr : strcon, "REST");
    	}
    	
    	catch (Exception e)
    	{
    		return Request.CreateResponse(HttpStatusCode.InternalServerError, e.ToString());
    	}
    	
    	if (where == null) 
    	{
    		ds = dc.FETCHtest_pdf_table("WHERE ID = " + get_id, conStr, "REST");
    	} 
    	else 
    	{
    		ds = dc.FETCHtest_pdf_table(where, conStr, "");
    	}
    	
    	foreach (DataTable table in ds.Tables)
    	{
    
    		foreach (DataRow row in table.Rows)
    		{
    			int? id = row["ID"] as int?;
    			int? userid = row["UserID"] as int?;
    			int? worksiteid = row["WorksiteID"] as int?;
    			Byte[] pdf = row["Pdf"] as Byte[];
    			String path = row["Path"] as String;
    
    		list.Add(new test_pdf_table
    				{
    					ID = id,
    					UserID = userid,
    					WorksiteID = worksiteid,
    					Pdf = pdf,
    					Path = path
    			});
    		}
    	} 
    	return Request.CreateResponse(HttpStatusCode.OK, list);
    }

And finally this is how I am displaying it:

    <canvas id="test-canvas"></canvas>

I then follow the instructions in one of the examples.

## What is the expected behavior? (add screenshot)

To display the PDF correctly in my AngularJS controller's view:

![image](https://cloud.githubusercontent.com/assets/2641122/26722772/5d973d3c-4789-11e7-8b57-9574e2806b7e.png)

## What went wrong? (add screenshot)

Miss representation of the data:

![image](https://cloud.githubusercontent.com/assets/2641122/26722754/49a985a0-4789-11e7-9b45-7ab9a229e0f1.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2017-06-02 21:44
Closing since this is a duplicate of #3758. It comes down to this: https://github.com/mozilla/pdf.js/issues/3758#issuecomment-41737305. No runnable demo is provided, so there is not more we can debug for this, unfortunately.

**Comment by Todai88** [comment] 2017-06-05 08:43
Thanks for taking some of your time to answer my question. Following the example provided by yury (onPrevNext) I am still getting the same unexpected behavior. I'm almost certain it has to do with the rendering, but even calling the render-function at the end of anything else in my controller I seem to be facing the same issue. This is using the EXACT implementation of the onPrevNext example that was provided in the issue you linked...

**Comment by timvandermeij** [comment] 2017-06-05 14:48
I'll reopen this now that the example is provided. Note that none of us are Angular experts, but maybe someone else with Angular experience knows what's going on.

**Comment by yurydelendik** [comment] 2017-06-05 15:54
The reason of failure stands: the same canvas is used for painting. I don't see how you preventing using the same canvas to be used by several render operations in the example above. You *have to* create a new canvas every time you paint in your case (instead of accessing already created `<canvas id="test-canvas"></canvas>`).

**Comment by csicky** [comment] 2017-06-12 20:26
I have the same problem. Only on IE 11, even after I delete and re-create the canvas I get rendering upside down. All other browsers work well. 
I have read lots of issues like this and always the answer is to delete and create new canvas. If I want more pdf files, or even switching the document in the same PDFJS object, the only safe and stable way is to have the PDFJS inside an iframe and that for sure will keep it contained.
What I see is that all these methods are just trying to fix something from outside. Why can't pdf.js be made in such a way to not require all these hacks? 

You are so used to give the same advice that you don't realize that it's not normal, it's a hack: 

> The reason of failure stands: the same canvas is used for painting.

I am not sure, but it seems like it started as an experiment? I think it's time to finish the experiment phase and make it a real library with clean API and no requirements for special treatment or hacks.
I don't remember fabric.js, or any other library asking me to delete/re-create the canvas before drawing.

Sorry for my tone. I spent all day long fighting IE 11 not getting along with PDFJS, and still no idea how to make it work :|

**Comment by yurydelendik** [comment] 2017-06-12 21:11
@csicky can you provide complete example online (e.g. publish complete offline example at github pages)? normally we ask that with any bug report -- having non-executable snippets of code will not allow us to help with the issues.

**Comment by csicky** [comment] 2017-06-12 21:53
@yurydelendik I managed to make it work with a very ugly piece of code. Still, in my opinion the library should contain itself and handle itself. If one calls render a thousand times the library should handle it.
Drop all previous calls and go render the last one.

**Comment by yurydelendik** [comment] 2017-06-12 22:01
> Still, in my opinion the library should contain itself and handle itself

There is a high level interface that manages canvas (see https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js) -- you can use that but it requires proper CSS configuration.

**Comment by yurydelendik** [comment] 2017-06-12 22:02
> I managed to make it work 

Closing as fixed.

**Closed by yurydelendik** 2017-06-12 22:02 UTC
Labels: 1-other, 4-information-requested

**Comment by csicky** [comment] 2017-06-13 08:56
> There is a high level interface that manages canvas
I will try it, thank you.
