### ISSUE TITLE
Clear search field on close.

### ISSUE THREAD

**Issue by kaySharma** [mozilla/pdf.js#8905] opened 2017-09-13 10:27 UTC
Link to PDF file (or attach file here):

Configuration:
- Chrome Version 60.0.3112.113
- Windows 10
- PDF.js version: 1.7.225.
- Is an extension: No

Steps to reproduce the problem:
1. Click search icon.
2. Search text.
3. Click search icon to close.
4. On close, the search field is not cleared.

What is the expected behavior?
I need to clear the search field on the close of search toolfield.

**Comment by Snuffleupagus** [comment] 2017-09-13 10:35
Closing as duplicate of #7468.

**Closed by Snuffleupagus** 2017-09-13 10:35 UTC
