### ISSUE TITLE
pdf.js screws up openload

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#9486] opened 2018-02-15 11:45 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 66.0.3348.0 (Official Build) canary (64-bit), also in Chrome Version 66.0.3343.3 (Official Build) dev (64-bit)
- Operating system and its version: Win 10 x64
- PDF.js version: 2.0.301
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Go to https://openload.co/f/eWCiP4gSM80/NBA-2018.02.14_MIA-PHI-2.torrent
2.

What is the expected behavior? (add screenshot)
A screen to download a file should open

![image](https://user-images.githubusercontent.com/2311076/36255071-2edd6e56-1256-11e8-8b41-a4d04281bd6f.png)

What went wrong? (add screenshot)
openload thinks there's an embedding violation

![image](https://user-images.githubusercontent.com/2311076/36255104-4bd51fe0-1256-11e8-8369-e458365f3034.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Rob--W** [comment] 2018-02-16 23:54
I can't reproduce this in Chromium 64.0.3282.167 on Linux. I installed the PDF Viewer and uBlock Origin (as seen in your screenshot), visited the page and clicked on the Free Download button (I also tried waiting before clicking).

What makes you believe that this issue is caused by PDF.js?

**Comment by qwer1304** [comment] 2018-02-17 08:45
I'm on Chrome Version 66.0.3346.8 (Official Build) dev (64-bit), Win 10 x64.
PDF Viewer is the only extension.
Without it there's no problem with openload.
With it, the problem occurs.

PS 
1.No need for uBlock Original
2.It's Win 10, not Unix
3.It's Chrome, not Chromium

**Comment by Rob--W** [comment] 2018-02-17 11:25
@qwer1304 If I look at your screenshot, I clearly see that uBlock Origin is installed (and at least one other extension). Did you try to reproduce this bug without those other extensions enabled? Or similarly, can you reproduce the problem if you temporarily disable PDF.js's PDF Viewer?

Before testing, could you visit `chrome://net-export` to capture the network requests, and upon completion of the test stop the capture and mail it to me? Then I can check whether there is anything special going on.

**Comment by qwer1304** [comment] 2018-02-17 12:32
I repeated the experiments with ONLY PDF Viewer installed and the results are as reported above.

Sent you two logs w/ and w/o

**Comment by Rob--W** [comment] 2018-02-17 16:35
The above log entry does not indicate that PDF.js itself is blocking anything. It merely shows that PDF.js was at some point notified of a request, and that the request handling was blocked until the PDF viewer extension returned.

I've managed to reproduce the issue in Chrome on Windows 10, and found a specific snippet in the page that is responsible for the behavior you're observing. Deobfuscated, the snippet is:

```javascript
function isSandboxed(_0x7089x2) {
    try {
        if (window.frameElement.hasAttribute("sandbox")) {
            _0x7089x2();
            return
        }   
    } catch (err) {}; 
    if (location.href.indexOf("data") != 0 && document.domain == "") {
        _0x7089x2();
        return
    };  
    if (typeof navigator.plugins != "undefined" && typeof navigator.plugins.namedItem != "undefined" && navigator.plugins.namedItem("Chrome PDF Viewer") != null) {
        var _0x7089x3 = document.createElement("object");
        _0x7089x3.onerror = function() {
            _0x7089x2()
        };  
        _0x7089x3.setAttribute("type", "application/pdf");
        _0x7089x3.setAttribute("style", "visibility:hidden;width:0;height:0;position:absolute;top:-99px;");
        _0x7089x3.setAttribute("data", "data:application/pdf;base64,JVBERi0xLg0KdHJhaWxlcjw8L1Jvb3Q8PC9QYWdlczw8L0tpZHNbPDwvTWVkaWFCb3hbMCAwIDMgM10+Pl0+Pj4+Pj4=");
        document.body.appendChild(_0x7089x3);
        setTimeout(function() {
            _0x7089x3.parentElement.removeChild(_0x7089x3)
        }, 150)
    }   
}
isSandboxed(function() {
    location.href = "/embedblocked?referer=" + encodeURIComponent(document.referrer.substring(0, 150))
})

```

They are trying to detect whether the Chrome PDF Viewer plugin exists in the browser, and if so, they try to load the plugin and see if an error event is dispatched (and if so, assume that the embed is blocked).
As a side effect of how embedded PDFs are detected in PDF.js, the `"error"` event is triggered when PDF.js renders the viewer in `<object>` elements, and there is no good way to prevent the "error" event from triggering.

I'm closing this bug since I currently don't plan to add a work-around to support this website, but I will follow up by mail so you can use the site again.

**Closed by Rob--W** 2018-02-17 16:35 UTC
Labels: 1-addon, 4-chrome-specific, 4-information-requested

**Comment by alexchandel** [comment] 2018-05-30 06:04
Could you add a workaround for this? Or at least disable PDF.js from loading on openload.co?
