### ISSUE TITLE
Some PDFs don't look good

### ISSUE THREAD

**Issue by rjgarciar** [mozilla/pdf.js#14419] opened 2022-01-05 10:42 UTC
Attach (recommended) or Link to PDF file here: 

[7157997.pdf](https://github.com/mozilla/pdf.js/files/7814212/7157997.pdf)

Configuration:

- Web browser and its version: Chrome 97.0.4692.71 (Build oficial) (64 bits)
- Operating system and its version: Windows 10
- PDF.js version: unknown
- Is a browser extension: PDF Viewer 2.3.164

Steps to reproduce the problem:
1. Open attached PDF with _PDF Viewer_ extension

What is the expected behavior? (add screenshot) **open with internal Chrome PDF Viewer:**

![Captura de pantalla 2022-01-05 113858](https://user-images.githubusercontent.com/57114512/148204111-f90685a3-2227-43fa-baf2-58360d9f7188.png)

What went wrong? (add screenshot) **open with PDF Viewer extension (based on PDF.js)**

![Captura de pantalla 2022-01-05 114422](https://user-images.githubusercontent.com/57114512/148204852-dacc4a18-f65c-49ac-9c96-098647c12e06.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-01-05 10:45
Duplicate of #3351

**Closed by Snuffleupagus** 2022-01-05 10:45 UTC
