### ISSUE TITLE
Digital Signature Not Visible on PDF when opened in PDF.js

### ISSUE THREAD

**Issue by rpschool88** [mozilla/pdf.js#11105] opened 2019-08-29 00:50 UTC
Attach (recommended) or Link to PDF file here:

[OF-0185-IT-2019.pdf](https://github.com/mozilla/pdf.js/files/3553402/OF-0185-IT-2019.pdf)

**Configuration:**
- Web browser and its version: Chrome 76.0.3809.132, Firefox 68.0.2, IE 11.950.17134.0, Edge 42.17134.1.0
- Operating system and its version: Windows 10 version 1803 (OS Build 17134.984)
- PDF.js version: 1.7.225, also version used in latest firefox
- Is a browser extension: No

**Steps to reproduce the problem:**
1. Upload attached PDF to a blank tab in Firefox.
2. Visually inspect the lower left hand corner of page 1. Note there is no visible signature.
3. Compare to attached screenshot of the same PDF opened in Adobe, where the signature is visible.

**What is the expected behavior?** (add screenshot)

The signature is visible in the lower left hand corner of page 1. 
![working_signature_PDF_adobe](https://user-images.githubusercontent.com/54648913/63901792-ff8c5e00-c9ba-11e9-9028-ef7513368fcb.png)

**What went wrong? (add screenshot)**

The signature is not visible in the lower left hand corner of page 1. 
![No_Signature_1](https://user-images.githubusercontent.com/54648913/63902002-0a93be00-c9bc-11e9-9776-5828375fae5c.png)

**Link to a viewer** (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): None.

**Additional notes**- per our customer, they use bit4id, which is a 3rd party e-sig app.

**Comment by ervinewell** [comment] 2019-08-29 04:08
I‘ve the same question, too

**Comment by Snuffleupagus** [comment] 2019-08-29 06:46
Duplicate of #1076.

**Closed** 2019-08-29 21:36 UTC
