### ISSUE TITLE
When the Google Chrome font is smaller than 12px, the cursor is selected misplaced

### ISSUE THREAD

**Issue by mobile-xd** [mozilla/pdf.js#12767] opened 2020-12-22 03:19 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  Chrome  87.0.4280.88
- Operating system and its version: macos 10.14.5
- PDF.js version: 2.5.207
- Is a browser extension: no

Steps to reproduce the problem:
1. Use official example：https://mozilla.github.io/pdf.js/web/viewer.html
2. Zoom out to 50% and select text

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/30429945/102844626-c5b05800-4446-11eb-91c0-c9de56d3ac71.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/30429945/102844566-a9acb680-4446-11eb-8d20-07458020d8b8.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): none

When the pdf is zoomed, the font size is adjusted in response, but the minimum font size of Google Chrome is 12px, so there is an offset.

![image](https://user-images.githubusercontent.com/30429945/102844732-0019f500-4447-11eb-9bbd-80a8b4addb19.png)

**Comment by Snuffleupagus** [comment] 2020-12-22 08:32
Duplicate of #12243

**Closed** 2020-12-28 18:48 UTC

**Comment by dverbovyi** [comment] 2022-01-28 16:08
I managed to fix with `pdfPage.getTextContent({ normalizeWhitespace: true })`
