### ISSUE TITLE
PDF Files with pound signs (hashtags) in the file name generate errors and don't render

### ISSUE THREAD

**Issue by alantlau** [mozilla/pdf.js#14746] opened 2022-04-04 16:08 UTC
Sample file and error message screenshot is attached.

Configuration:
- Web browser and its version: Chrome Version 100.0.4896.60 (Official Build) (64-bit)
- Windows 10 Pro 64-bit Version 21H2 (OS Build 19044.1526)
- PDF.js version: Stable (v2.13.216)
- Is a browser extension: Not sure what this means
- Web server is IIS 7.0

Steps to reproduce the problem:
1. On a server where you have PDF.js installed, pass it a filename that has a hashtag or pound sign in it.  Doesn't matter if you URLEncode the filename.

Note: Passing just the url of the filename to the webserver (without PDF.js) does render the PDF.  For example:
This doesn't work: http://sql-14/web/viewer.html?file=/AppFiles/APPS/0000001/sam%23ple.pdf
But this does work: http://sql-14/AppFiles/APPS/0000001/sam%23ple.pdf

What is the expected behavior? (add screenshot) The expected behavior is it would render the PDF

What went wrong? (add screenshot) See Error.jpg (attached)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[sam#ple.pdf](https://github.com/mozilla/pdf.js/files/8411132/sam.ple.pdf)
![Error](https://user-images.githubusercontent.com/8886856/161581976-724f5b23-03b7-4dc5-b4d5-97007a16c854.jpg)

**Comment by Snuffleupagus** [comment] 2022-04-04 17:12
Duplicate of #10632

**Closed by Snuffleupagus** 2022-04-04 17:12 UTC

**Comment by alantlau** [comment] 2022-04-04 20:11
Weird, searching for hashtag and pound sign brought up zero results ¯\_(ツ)_/¯
