### ISSUE TITLE
Add keyboard shortcut for text and draw tools

### ISSUE THREAD

**Issue by megamorphg** [mozilla/pdf.js#17107] opened 2023-10-10 21:42 UTC
Attach (recommended) or Link to PDF file here: any

Configuration:
- Web browser and its version: Firefox 118.0.1
- Operating system and its version: Windows 10
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1. Select text or drawing tool via mouse
![image](https://github.com/mozilla/pdf.js/assets/1782353/96b3aa55-ead6-4720-ad7f-7ca9a120defc)

What is the expected behavior? (add screenshot)
Have a keyboard shortcut available for all tools
![Screenshot from 2023-08-07 16-03-59](https://github.com/mozilla/pdf.js/assets/1782353/e69e91f4-1672-4696-bad7-d9eb2f9a53ce)

What went wrong? (add screenshot)
Keyboard shortcuts not available for Text and Draw tools
![Screenshot from 2023-08-07 16-03-59](https://github.com/mozilla/pdf.js/assets/1782353/3e2011ee-bda9-4eca-bed8-4f5fb1892051)

It would also be good to have a tooltip indicating the keyboard shortcut definition.

**Comment by Snuffleupagus** [comment] 2023-10-11 07:17
Duplicate of #16064

**Closed by Snuffleupagus** 2023-10-11 07:17 UTC
