### ISSUE TITLE
Is it possible to search the text that you have inputted with pdf.js?

### ISSUE THREAD

**Issue by rusty-peilin** [mozilla/pdf.js#16853] opened 2023-08-20 01:49 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome latest
- Operating system and its version: macos 13.2.1
- PDF.js version: v3.9.179
- Is a browser extension: no

Steps to reproduce the problem:
1. search the word I have inputted but didn't get it.
2. didn't find a similiar question in this repo.

What is the expected behavior? (add screenshot)
I want to search and find the word I have inputted.

What went wrong? (add screenshot)
I searched but didn't get the word I input
<img width="460" alt="image" src="https://github.com/mozilla/pdf.js/assets/77475610/9dd0bf44-0cf4-4cf8-9e5f-703c19719b1f">

**Comment by Snuffleupagus** [comment] 2023-08-20 08:09
Duplicate of #15193

**Closed by Snuffleupagus** 2023-08-20 08:09 UTC
