### ISSUE TITLE
Some characters not rendered well

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#9194] opened 2017-11-27 14:44 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 63.0.3239.59 (Official Build) beta (64-bit)
- Operating system and its version: MacOS High Sierra 10.13.1 (17B48)
- PDF.js version: online version as of Nov 27, 2017
- Is a browser extension: no

Steps to reproduce the problem:
1. load attached pdf
2. see how the characters are not rendered well (Option 1, Option 2, ...)

What is the expected behavior? (add screenshot)
The character should look nice like in Preview.

What went wrong? (add screenshot)
The character are not drawn well
![pdfjs-bad-rendering](https://user-images.githubusercontent.com/149561/33272206-c355afbe-d389-11e7-94b5-eb3628761ae5.png)
![preview-good-rendering](https://user-images.githubusercontent.com/149561/33272207-c3780460-d389-11e7-87d4-48b91c9652f2.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[bank-accounts-registration-form.pdf](https://github.com/mozilla/pdf.js/files/1506232/bank-accounts-registration-form.pdf)

**Comment by Snuffleupagus** [comment] 2017-11-27 20:52
WFM, using PDF.js version `2.0.161` in Firefox Nightly 59 on Windows 7; see screen-shot below.

![temp](https://user-images.githubusercontent.com/2692120/33288599-2675c902-d3bd-11e7-91cf-df61e5af1353.png)

**Comment by timvandermeij** [comment] 2017-11-27 21:06
Works for me too using PDF.js version 2.0.161 in Firefox 57 on Arch Linux. It looks like a graphics driver issue to me. Could you try checking if there are graphics driver updates for your computer?

**Comment by ldenoue** [comment] 2017-11-28 10:03
I confirm that only Chrome on my Mac has issues rendering.
The PDF is rendered correctly on Safari (Version 11.0.1) and Firefox 57.0 (64-bit) (Quantum).

But what could cause Chrome to behave that way?

**Comment by brendandahl** [comment] 2017-11-29 01:38
Seems fine on Chrome 62, MacOS Sierra. Can you try Chrome 62?

> But what could cause Chrome to behave that way?

In the past chrome has had issues with the font loading api saying a font is ready before it really was ready. I thought that was all fixed though.

**Comment by ldenoue** [comment] 2017-11-29 15:15
I can't try on Chrome 62, but both Chrome 63 and 64 have the same issue.
Do you have a link to the font loading api problem you mentioned?

**Comment by brendandahl** [comment] 2017-11-29 22:15
Sorry, I misremembered, it was webkit that had this issue.

BTW, I tried chrome 64 and it also worked for me.

**Comment by brendandahl** [comment] 2017-11-29 22:21
Also, I tried loading the PDF without loading our custom fonts and to see if it looked the same as your above issue, but it doesn't. Not sure what's happening with your setup.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/942640/33402095-5d6e1d3e-d510-11e7-944a-783cb871bc4f.png">

**Comment by dorasun** [comment] 2018-03-27 21:37
I just tried this with PDF.js 2.0.466 web viewer and Chrome extension, Chrome 65.0.3325.181, and MacOS 10.12.5, but the PDF displayed as intended, is this still a problem for anyone?

<img width="1280" alt="screen shot 2018-03-27 at 5 22 52 pm" src="https://user-images.githubusercontent.com/10905385/37996185-d264fc12-31e4-11e8-9b93-9b7fce2a6c70.png">

**Comment by ldenoue** [comment] 2018-03-28 07:36
It works well now for me as well on Version 66.0.3359.45 (Official Build) beta (64-bit) for Mac 10.13.1 (17B1003)

**Comment by timvandermeij** [comment] 2018-03-28 19:56
Closing since it looks like this is fixed then.

**Closed by timvandermeij** 2018-03-28 19:56 UTC
Labels: 3-upstream, 4-chrome-specific, 4-font-conversion, 4-os-mac, 4-triage-needed
