### ISSUE TITLE
PDF.js Support for ES6 or Scripting Support for Web Component

### ISSUE THREAD

**Issue by trustsantosh** [mozilla/pdf.js#13027] opened 2021-02-26 15:56 UTC
This one is the general inquiry related to support for **ES6** and **Web Component** Framework.

To use pdf.js in Web Component framework, lots of _polyfill_ codes are required.
I tried to use it in my application which ends up resulting to do more codes which wasn't required in normal scripting(a single html page).
Also support for **Worker** in Web Component is not as it should be.

I am looking forwards to have this particular aspect supported.

**JS Documentation** is also worrying part. as I have to explore various options in it by debugging and looking at source codes.

**Comment by Snuffleupagus** [comment] 2021-02-26 16:16
This is possibly a duplicate of issue #10317, however that's really a best guess considering that it's *very difficult* to even understand what's being reported here!

As-is this issue is unfortunately INCOMPLETE, and will be closed as such, since there's no easily actionable information provided nor any outright questions asked here.

**Comment by trustsantosh** [comment] 2021-02-26 17:05
@Snuffleupagus 
This is a huge issue related to use of PDF,js in webcomponent.
I know that there is not easily actionable. But would be more interested to know the way out.

**Comment by Snuffleupagus** [comment] 2021-02-26 17:17
> This is a huge issue related to use of PDF,js in webcomponent.

The problem is that you've (still) not at all explained what you perceive to be wrong here, or what you'd like to see changed.

While this issue may make sense to *you*, for anyone else it's simply impossible to understand what you actually mean here without both a lot more and clearer information. Hence why the ISSUE_TEMPLATE explicitly asks for "steps to reproduce", such that issues become actionable.

**Closed** 2021-02-26 21:15 UTC
