### ISSUE TITLE
multi language pdf renders all languages at the same time

### ISSUE THREAD

**Issue by mehlis** [mozilla/pdf.js#6363] opened 2015-08-18 14:18 UTC
pdf: http://meinfernbus.de/download/map/simple

"PDF d49c051bda114135ac2da88fbe77a517 [1.6 Adobe PDF library 11.00 / Adobe Illustrator CC 2014 (Macintosh)] (PDF.js: 1.1.387)" viewer.js:6645:0

pdf does work in evince

**Comment by Snuffleupagus** [comment] 2015-08-18 14:39
The PDF file uses layers, which we currently don't support.
Closing as duplicate of issue #269.

**Closed by Snuffleupagus** 2015-08-18 14:39 UTC
