### ISSUE TITLE
Why is there a memory leak when rendering pages to pdf.js?

### ISSUE THREAD

**Issue by sofvlad** [mozilla/pdf.js#9662] opened 2018-04-13 05:43 UTC
Hi, everybody. I use a pdf.js for rendering pages that are stored on the server, receiving data from each page. But if use the cycle to load 180 pages Ajax requests, it burns **500 MB** of memory. In particular, they occupy rendered pages with mathematical formulas and graphs. A ready Pre-built version always eats about 100-200MB. I'm using a Pre-build version with a self-written script using your API. 
Why so can be? 

Here is the page render method. The file is taken and a single page is rendered, as each file is divided into Pdf files.

```
PDFJS.getDocument({
    data: atob(pageData)
}).then(function(pdf) {
    pdf.getPage(1).then(function(page) {
        var canvas = document.getElementById('page-' + pageNum);
        var context = canvas.getContext('2d');
        var viewport = page.getViewport(settings.scale);
        canvas.height = viewport.height;
        canvas.width = viewport.width;

        var canvasP = document.getElementById('preview-page-' + pageNum);
        var contextP = canvasP.getContext('2d');
        var viewportP = page.getViewport(settings.previewScale);
        canvasP.height = viewportP.height;
        canvasP.width = viewportP.width;

        Promise.all([
            page.render({
                canvasContext: context,
                viewport: viewport
            }),
            page.render({
                canvasContext: contextP,
                viewport: viewportP
            })
        ]).then(function() {
            pdf.cleanup();
            pdf.destroy();
            page.cleanup();
        });
    });
}, function (reason) {
    console.error(reason);
});
```

After use method `pdf.destroy()` the amount of memory decreases significantly, but it still grows with the number of rendered pages.

_P.S. Sorry for my English._

**Comment by Snuffleupagus** [comment] 2019-01-20 14:52
This can probably just be considered a (forward) duplicate of issue #10021, especially considering https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Closed** 2019-01-20 14:54 UTC
Labels: 1-other
