### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by bitsflew** [mozilla/pdf.js#10992] opened 2019-07-19 16:02 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: N/A
- Operating system and its version: Debian9
- PDF.js version: 2.2.228 (pdfjs-dist, node 10.16.0)
- Is a browser extension: NO

Steps to reproduce the problem:
Render the following PDF using pdfjs-dist / node 10.16.0 and save the output to a jpeg file
[https://www.dropbox.com/s/6pjiuhygnmum4s1/document.pdf?dl=1](url)

What is the expected behavior?
![macos-mojave-page-1](https://user-images.githubusercontent.com/488260/61548566-439c5280-aa4e-11e9-91f7-a4e875395577.jpg)

What went wrong?
![debian9-page-1](https://user-images.githubusercontent.com/488260/61548578-49923380-aa4e-11e9-896e-6bf6c4265037.jpg)

Note:  This only happens on Debian9! The output is correct when running the same program on macOS Mojave

**Comment by Snuffleupagus** [comment] 2019-07-19 19:38
> Render the following PDF using pdfjs-dist / node 10.16.0 and save the output to a jpeg file

Without clear steps outlining *exactly* how the "save the output to a jpeg file" part is actually done, preferably with a runnable example as asked for in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine below), this issue is unfortunately not really be actionable.
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> Note: This only happens on Debian9! The output is correct when running the same program on macOS Mojave

Based on this it seems doubtful that it's actually a PDF.js bug, since if it were you'd expect it to be consistently broken everywhere.

**Comment by timvandermeij** [comment] 2019-07-19 20:18
Closing because of the above. If it's clear that it's in fact not a platform issue but a PDF.js issue, please provide clear steps to reproduce.

**Comment by bitsflew** [comment] 2019-07-22 08:58
Here is a small node.js sample project illustrating the issue.
It will render every page from the embedded sample pdf document to a jpeg file
Again: I can pnly reproduce the issue on Denian9, the code produces the correct output on macOS..

https://www.dropbox.com/s/595dza21xyl2fpw/pdf2jpg.zip?dl=1

Preseequites:
Debian9, 
Node 10.16.0

Installation:
cd <project-dir>
npm install
npm start

The generated jpeg files are written to <project-dir>/test/output

**Comment by timvandermeij** [comment] 2019-07-22 20:18
Reopening in case anyone wants to take a look, but labeling it as upstream and Linux-only for now.

**Comment by Sride** [comment] 2019-07-29 05:35
Hi @timvandermeij, any updates?

**Comment by Snuffleupagus** [comment] 2021-01-31 09:36
> Again: I can pnly reproduce the issue on Denian9, the code produces the correct output on macOS..

Is it actually meaningful to keep this issue open, when everything clearly points to a *platform* bug rather than a PDF.js one?

**Closed** 2021-01-31 13:10 UTC
Labels: 1-other, 3-upstream, 4-os-linux
