### ISSUE TITLE
Working with layers

### ISSUE THREAD

**Issue by jonimnim** [mozilla/pdf.js#8037] opened 2017-02-07 13:58 UTC
Please tell me how to work with layers in the PDF document that is rendered in the canvas? For example I have a document contains multiple layers some of which I want to hide, as part of the show.

**Comment by Snuffleupagus** [comment] 2017-02-07 14:06
Layers are currently not supported in PDF.js, closing as duplicate of issue #269 (which already tracks this).

**Closed by Snuffleupagus** 2017-02-07 14:06 UTC

**Comment by jonimnim** [comment] 2017-02-07 14:21
Thank you
