### ISSUE TITLE
blurry qr-code / image when zooming

### ISSUE THREAD

**Issue by TZanke** [mozilla/pdf.js#7838] opened 2016-11-22 07:54 UTC
Hello,

i have a problem zooming into a file with a image / qr-code. In PDF.js it is not re-rendered on zooming. In Chrome native PDF viewer it works. See below.

[example.pdf](https://github.com/mozilla/pdf.js/files/605747/example.pdf)

Configuration:
- Chrome 53 / Firefox 50
- Ubuntu 16.04 LTS
- PDF.js version: Demo Page ( 1.6.332 )

What is the expected behavior? (Zoom 200%, Chrome)
![image](https://cloud.githubusercontent.com/assets/1613368/20515183/ab530352-b090-11e6-9300-fd19d1791a20.png)

What went wrong? (Zoom 200%, PDF.js)
![image](https://cloud.githubusercontent.com/assets/1613368/20515214/cc2ed9de-b090-11e6-8fd2-55ff2a2a79cc.png)

**Comment by Snuffleupagus** [comment] 2021-05-13 07:47
Duplicate of #4706

**Closed** 2021-05-13 11:13 UTC
Labels: 2-image-quality
