### ISSUE TITLE
viewer.html not loading demo pdf in Microsoft Edge

### ISSUE THREAD

**Issue by greddyatpt** [mozilla/pdf.js#9711] opened 2018-05-10 04:00 UTC
This issue was there a while ago but it was closed.  Not sure if it's a regression or was never fixed... it's happening again in Edge.  The demo doc doesn't load if you clone the latest code but it does work in the stable build.

**Comment by greddyatpt** [comment] 2018-05-10 04:02
The latest code works in Chrome but seems to be a lot slower than the stable build.

**Comment by timvandermeij** [comment] 2018-05-10 11:30
If it doesn't load, are there any messages in the browser's console?

**Comment by timvandermeij** [comment] 2018-05-14 22:09
Closing since the issue is not actionable without more information.

**Closed by timvandermeij** 2018-05-14 22:09 UTC
Labels: 4-information-requested
