### ISSUE TITLE
Copy All (control+a)

### ISSUE THREAD

**Issue by seblurtz** [mozilla/pdf.js#3907] opened 2013-11-12 14:49 UTC
Hello,

I am trying to replace an old Java PDF Viewer by the PDF.js viewer which works quite nicely. 
I am just facing 2 problems with copy/paste functionnality :

1) Abusive breaks
I already found a submitted issue : Bug 810636 - Poor copy & paste behavior with pdf.js. If someone have a good solution, feel free.

2) Copy All content (control+A)
I didn't find anything related tothis problem.
Is there a way to copy the entire content of the document (with control+A) ? 
As the document is displayed asynchronously depending on the page we are, i don't get all content but instead a very small amount of lines... 

Does anybody have a solution to that problem ?
Is there a way to do it : 
- simply from PDF.js ?
- from raw PDF content ?
- by displaying all document content with PDF.js (200 pages for example) ?

Thanks in advance for your help.

**Comment by speedplane** [comment] 2015-03-04 16:09
PR #5783 may at least partially fix this.

**Comment by timvandermeij** [comment] 2016-09-02 14:40
Closing as duplicate of #1995.

**Closed by timvandermeij** 2016-09-02 14:40 UTC
Labels: 4-text-selection
