### ISSUE TITLE
Error: Protocol "blob:" not supported. Expected "https:" could not be cloned.

### ISSUE THREAD

**Issue by pepri** [mozilla/pdf.js#9071] opened 2017-10-26 05:09 UTC
Fails to open drag&dropped file when running in NW.js. This is regression from version 1.8.581 where the file could be opened.

Configuration:
- Web browser and its version:  NW.js (0.26.0)
- Operating system and its version: Windows 10
- PDF.js version: 1.10.86 (worked before with version 1.8.581)
- Is a browser extension: yes (I think NW.js runs it internally as an extension)

Steps to reproduce the problem:
1. Create a NW.js application:
1a: Create `package.json`:
~~~json
{
	"name": "pdfjs-bug",
	"version": "1.0.0",
	"dependencies": {
		"nw": "0.26.0-sdk",
		"pdfjs-dist": "1.10.86",
		"copyfiles": "1.2.0"
	},
	"scripts": {
		"start": "copyfiles -f node_modules/pdfjs-dist/build/pdf.js node_modules/pdfjs-dist/build/pdf.worker.js src && nw src"
	}
} 
~~~
1b. Create `src/package.json`:
~~~json
{
	"name": "PDFJS",
	"main": "index.html"
}
~~~
1c. Create `src/index.html`:
~~~html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Test</title>
		<script src="pdf.js"></script>
	</head>
	<body>
		DROP<br />
		<script>
const el = document.documentElement;
el.ondragover = e => {
	e.preventDefault();
};
el.ondrop = e => {
	e.preventDefault();
	const file = e.dataTransfer.files[0];
	const url = URL.createObjectURL(file);
	PDFJS.getDocument(url).then(pdf => document.body.insertAdjacentHTML('beforeend', pdf.numPages + '<br />'));
};
		</script>
	</body>
</html>
~~~
2. Install and run the NW.js application.
2a. Install the application with `npm install`.
2b. Run the application with `npm start`.
3. Drag&drop any PDF file from filesystem to the application.

What is the expected behavior? (add screenshot)
The number of pages is shown on the page.

What went wrong? (add screenshot)
The number of pages is not shown. Exception is logged into the console:

~~~
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': Error: Protocol "blob:" not supported. Expected "https:" could not be cloned.
    at MessageHandler.postMessage (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:1390:19)
    at sendStreamRequest (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:1207:14)
    at chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:1272:7
    at <anonymous>
index.html:1 Uncaught (in promise) UnknownErrorExceptiondetails: "UnknownErrorException: Cannot read property 'headersReady' of null"message: "Cannot read property 'headersReady' of null"name: "UnknownErrorException"__proto__: Error
    at UnknownErrorExceptionClosure (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:443:37)
    at Object.<anonymous> (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:446:2)
    at __w_pdfjs_require__ (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:45:30)
    at Object._typeof (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:8064:23)
    at __w_pdfjs_require__ (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:45:30)
    at Object.defineProperty.value (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:88:18)
    at chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:91:10
    at webpackUniversalModuleDefinition (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:24:59)
    at chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:25:3
~~~

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment] 2017-10-26 13:42
Can NW.js support fetch() or XHR with blob: url? Can you reduce your example to use fetch() ?

```
fetch(url).then(req => req.arrayBuffer()).then(pdf => document.body.insertAdjacentHTML('beforeend', pdf.byteLength + '<br />'));
};
```

**Comment by pepri** [comment] 2017-10-26 14:22
Yes, it can. After altering the code, the length of the dropped file is being shown on drop.

**Comment by burtonator** [comment] 2018-06-05 17:22
I get the same thing in Electron.

**Comment by morille** [comment] 2018-11-06 14:57
Tested locally and @corwin-of-amber is right.
#10228 fixes this.

**Comment by corwin-of-amber** [comment] 2018-11-07 09:14
Thanks for the fix. I would like to correct my previous statement that `fetch_stream` works well in NW.js, I was able to open PDF files using the `file://` protocol on my Mac, but on a Windows machine it failed with
```
Fetch API cannot load file:///... URL scheme must be "http" or "https" for CORS request.
```

Don't know if the problem is within `fetch_stream` or the choice between the different streams.

**Comment by morille** [comment] 2018-11-07 09:20
It's still much safer to consider NW.js as a browser, as it just copies some object from nodejs, [as explained in their doc](http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/#access-nodejs-and-nwjs-api-in-browser-context).

**Comment by timvandermeij** [comment] 2018-11-07 22:51
Closing since this is fixed by the pull request above. If any issues remain after this, please open a new issue.

**Closed** 2018-11-07 22:51 UTC
Labels: 1-core

**Comment by Pringmore** [comment] 2019-09-13 09:50
Hi @burtonator !
I m using *Electron* too for our application and we have got an error related to *PDFjs* and *blob* data.
The generated *pathToData* which is used later to call *getDocument()* is generating an    

>  UnknownErrorException

Is it related to the protocole used by *Electron* ? have you found a solution for your issue?

**Comment by corwin-of-amber** [comment] 2019-09-13 10:21
Opening a `file://` resource still results in `UnknownErrorException` because PDFjs tries to use the `fetch` API. Setting `window.Response = null` forces it to use `network.js`.
