### ISSUE TITLE
Test WebGL

### ISSUE THREAD

**Issue by bikb** [mozilla/pdf.js#8880] opened 2017-09-07 10:00 UTC
I want to test the WebGL feature.
But it is not so easy to enable it. (setting in the preferences seems not to affect at all)
Please can you tell me how to enable it by default and have a HTML5 canvas fallback?

Thank you.

**Comment by Snuffleupagus** [comment] 2017-09-07 13:20
If you're using the default viewer, running `PDFViewerApplication.preferences.set('enableWebGL', true)` in the browser console and then reloading the viewer will enable WebGL support.

If instead you're using the API directly, you'll need to set `PDFJS.disableWebGL = false` *before* calling `getDocument()`; please refer to https://github.com/mozilla/pdf.js/blob/9b14f8ea2a512ddf13ca6797048eeda08df380a7/src/display/global.js#L208-L213

However, please keep in mind that WebGL is only used to speed-up a *subset* of all the possible canvas rendering operations; please see https://github.com/mozilla/pdf.js/blob/9b14f8ea2a512ddf13ca6797048eeda08df380a7/src/display/canvas.js#L704 and https://github.com/mozilla/pdf.js/blob/9b14f8ea2a512ddf13ca6797048eeda08df380a7/src/display/pattern_helper.js#L183

Closing as answered.

**Closed by Snuffleupagus** 2017-09-07 13:20 UTC

**Comment by bikb** [comment] 2017-09-07 14:41
Thank you for the fast reply. 
I tried with an enabled WebGL supported Browser.
But https://github.com/mozilla/pdf.js/blob/9b14f8ea2a512ddf13ca6797048eeda08df380a7/src/display/pattern_helper.js#L184
is never entered.
WebGLUtils is undefined.
Please can you help?

**Comment by bikb** [comment] 2017-09-07 15:05
I am using the demo [https://mozilla.github.io/pdf.js/web/viewer.html](url)
WFM with this pdf file too.
WebGLUtils.drawFirgures is entered.
So the question which I have to ask now: Why is "normal" text and the plots from the test file not rendered with WebGL? Why is personwithdog.pdf rendered instead?

**Comment by Snuffleupagus** [comment] 2017-09-07 15:17
> So the question which I have to ask now: Why is "normal" text and the plots from the test file not rendered with WebGL? Why is personwithdog.pdf rendered instead?

Did you actually read *all* of https://github.com/mozilla/pdf.js/issues/8880#issuecomment-327796972? Quoting (myself) from that comment:
> However, please keep in mind that WebGL is only used to speed-up a subset of all the possible canvas rendering operations;

Not all operations benefit that much from rendering using WebGL vs canvas (consider also the complexity of the solution), and the focus of the (somewhat experimental) WebGL support was to provide a speed-up where it'd (potentially) help the most.

**Comment by bikb** [comment] 2017-09-07 15:52
Yes I did read.
You write a subset.
BUT: In my opinion a subset should be at least one (1) element of a pdf file. In fact you know that only a specific test pdf file was rendered by WebGL. Not at least one character of text or one symbol of plot of the standard text pdf file in  [https://github.com/mozilla/pdf.js/issues/url](url) is rendered.  
Do you confirm this?
I think we need to specify what means subset in detail.

Now my question: Is it possible to render text with existing pdf.js code with WebGL? How ist the state of coding. I know that yury doesn't think it makes sense to do this. But this is my problem. I want to test text rendering feature of pdf.js with WEBGL.
If it lacks of it perhaps another javascript library can help.

Yury says "there is no sense to use webgl for text/glyph painting". But can you be sure that it does not make sense in specific compatibility cases?
Please see my posting here:
[https://github.com/mozilla/pdf.js/issues/8863](url)
There it would make sense to extend compatibility.js for fast rendering at firefox for android.
Performance is not all, but for some projects it could be the base. And I think all contributors want to make pdf.js better.
A fallback can be used of course.

So please reopen the issue if you share my opinion.

**Comment by yurydelendik** [comment] 2017-09-07 18:52
> So please reopen the issue if you share my opinion.

You was able to test WebGL, means the issue is somewhat resolved. Implementing text rendering in WebGL is out of scope of this issue and is not very thought through (in context of PDF.js). See also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md#pdfjs-issue-reporting

**Comment by bikb** [comment] 2017-09-07 19:42
OK, I will read the code.
It seems the existing WebGl code lacks rendering text.
