### ISSUE TITLE
Random spaces and font issue in Safari

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#8329] opened 2017-04-25 09:11 UTC
Link to PDF file (or attach file here):

[2017_MHOF_Spring_Newsletter.pdf](https://github.com/mozilla/pdf.js/files/954481/2017_MHOF_Spring_Newsletter.pdf)

Configuration:
- Safari Version 10.1 (10603.1.30.0.34)
- OS/X 10.10.5 (14F2315)

Using the standard viewer at https://mozilla.github.io/pdf.js/web/viewer.html

In the following screenshot the left hand side shows the Safari view, and the right hand side is the default OS/X Preview:

![screen shot 2017-04-21 at 6 39 55 pm](https://cloud.githubusercontent.com/assets/786238/25377407/5da08e8a-299f-11e7-8da5-8a8edda9d438.png)

All the fonts are incorrect in Safari, and there are also inexplicable gaps e.g. in the main headline the first part of "The" is missing.

Everything seems fine in Chrome...

Please let me know if you need any further information.

Thank you.

Dan

**Comment by Snuffleupagus** [comment] 2017-04-25 10:57
Based on the information provided, closing as duplicate of issue #8231.

**Closed by Snuffleupagus** 2017-04-25 10:57 UTC
