### ISSUE TITLE
Text not fully visible on www.myconsumers.org PDF

### ISSUE THREAD

**Issue by wisniewskit** [mozilla/pdf.js#17906] opened 2024-04-08 15:07 UTC
Some sections have missing text on Firefox. This was reported at [webcompat.com in https://github.com/webcompat/web-bugs/issues/135653](https://webcompat.com/issues/135653)

A link to the reported PDF: https://www.myconsumers.org/docs/default-source/default-document-library/consumer_fee_schedule3cb1f27b220b46e38278186d8f609a23fc8e3ea533ad421d8caf5ccbd8df1cb5.pdf

**Comment by timvandermeij** [comment] 2024-04-08 16:30
I can reproduce the issue with Firefox 124.0.2 on Arch Linux. In the console various errors are logged, but they all seem annotation-related and indeed https://brendandahl.github.io/pdf.js.utils/browser confirms that the missing text is part of annotations that are not being rendered. Opening the PDF file with Okular confirms that the missing text is different from the other text because the missing text can be selected (and is rendered correctly) in Okular while the other text cannot and appears to actually be an image.

I'm not sure if the "invalid canvas size" error is breaking things here, but it is strange and should not be logged. However, looking at the PDF browser output, it looks like the warning is actually relevant here: the missing text is in button widget annotations that don't have an action dictionary, which might make this a duplicate of e.g. #12746 and #12593.

```
PDF 879eb646c7b7ba328bca1ddd115dfcb1 [1.6 iText 2.1.4 (by lowagie.com) / LiquidOffice Java Publishing Framework] (PDF.js: 4.1.249 [d07f37f44]) viewer.mjs:11444:13

Warning: Push buttons without action dictionaries are not supported 4 pdf.worker.mjs:344:13

renderView: "Error: Invalid canvas size" viewer.mjs:5596:19
Message: Invalid canvas size
Stack: create@resource://pdf.js/build/pdf.mjs:850:13
beginAnnotation@resource://pdf.js/build/pdf.mjs:7181:52
executeOperatorList@resource://pdf.js/build/pdf.mjs:6108:20
_next@resource://pdf.js/build/pdf.mjs:10594:37
_scheduleNext/<@resource://pdf.js/build/pdf.mjs:10584:14
FrameRequestCallback*_scheduleNext@resource://pdf.js/build/pdf.mjs:10583:14
renderContinueCallback@resource://pdf.js/web/viewer.mjs:8243:7
_continue@resource://pdf.js/build/pdf.mjs:10576:17
executeOperatorList@resource://pdf.js/build/pdf.mjs:6124:11
_next@resource://pdf.js/build/pdf.mjs:10594:37
_scheduleNext/<@resource://pdf.js/build/pdf.mjs:10584:14
FrameRequestCallback*_scheduleNext@resource://pdf.js/build/pdf.mjs:10583:14
renderContinueCallback@resource://pdf.js/web/viewer.mjs:8243:7
_continue@resource://pdf.js/build/pdf.mjs:10576:17
operatorListChanged@resource://pdf.js/build/pdf.mjs:10568:10
_renderPageChunk@resource://pdf.js/build/pdf.mjs:9541:26
_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.mjs:9577:14
promise callback*pump@resource://pdf.js/build/pdf.mjs:9566:21
_pumpOperatorList@resource://pdf.js/build/pdf.mjs:9600:5
render@resource://pdf.js/build/pdf.mjs:9355:12
draw@resource://pdf.js/web/viewer.mjs:8296:55
renderView@resource://pdf.js/web/viewer.mjs:5590:14
forceRendering/<@resource://pdf.js/web/viewer.mjs:9464:29
promise callback*forceRendering@resource://pdf.js/web/viewer.mjs:9463:43
renderHighestPriority@resource://pdf.js/web/viewer.mjs:5520:24
update@resource://pdf.js/web/viewer.mjs:9360:25
webViewerScaleChanging@resource://pdf.js/web/viewer.mjs:12097:34
dispatch@resource://pdf.js/web/viewer.mjs:1362:15
#setScaleUpdatePages@resource://pdf.js/web/viewer.mjs:9151:19
#setScale@resource://pdf.js/web/viewer.mjs:9210:32
set currentScaleValue@resource://pdf.js/web/viewer.mjs:8600:19
scrollPageIntoView@resource://pdf.js/web/viewer.mjs:9307:9
setHash@resource://pdf.js/web/viewer.mjs:1046:24
setInitialView@resource://pdf.js/web/viewer.mjs:11575:27
load/</<@resource://pdf.js/web/viewer.mjs:11290:14
promise callback*load/<@resource://pdf.js/web/viewer.mjs:11256:109
promise callback*load@resource://pdf.js/web/viewer.mjs:11253:22
open/<@resource://pdf.js/web/viewer.mjs:11090:12
promise callback*open@resource://pdf.js/web/viewer.mjs:11089:32
onOpenWithTransport@resource://pdf.js/web/viewer.mjs:10952:14
windowMessage@resource://pdf.js/web/viewer.mjs:1845:21
EventListener.handleEvent*initPassiveLoading@resource://pdf.js/web/viewer.mjs:1829:12
initPassiveLoading@resource://pdf.js/web/viewer.mjs:10950:27
run@resource://pdf.js/web/viewer.mjs:10836:10
async*webViewerLoad@resource://pdf.js/web/viewer.mjs:12728:24
@resource://pdf.js/web/viewer.mjs:12732:3
viewer.mjs:11199:13
```

**Comment by timvandermeij** [comment] 2024-04-08 16:43
The traceback from a local development build is more useful because it lists the individual source files and lines (which gets lost when all files are combined for the Firefox build) and is quite a bit easier to read:

```
PDF 879eb646c7b7ba328bca1ddd115dfcb1 [1.6 iText 2.1.4 (by lowagie.com) / LiquidOffice Java Publishing Framework] (PDF.js: ? [?]) app.js:1504:13

Warning: Push buttons without action dictionaries are not supported 4 util.js:373:13

Message: Invalid canvas size
Stack: create@http://localhost:8888/src/display/base_factory.js:49:13
beginAnnotation@http://localhost:8888/src/display/canvas.js:2700:52
executeOperatorList@http://localhost:8888/src/display/canvas.js:1084:20
_next@http://localhost:8888/src/display/api.js:3401:37
_scheduleNext/<@http://localhost:8888/src/display/api.js:3390:14
app.js:1149:13
renderView: "Error: Invalid canvas size" pdf_rendering_queue.js:204:21
```

Given that the error seems to occur at https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L2700-L2703, it seems like the annotation canvas we try to create is somehow invalid. We should start debugging there, since the error might prevent the canvas-side of the annotation from rendering (that the annotation layer-side of the annotation is not rendering would be less bad and explained by the warning).

**Comment by calixteman** [comment] 2024-04-08 16:45
Some annotations have their rect reduced to one point, for example for annotation 325R, the rect is `[0,792,0,792]` and in considering its `TU` which is "A hidden field" we can consider that it's on purpose.
Instead of throwing we should set something like `width = Math.max(0, width)` and the the same for the `height`.

**Closed** 2024-04-10 07:33 UTC
Labels: core, annotations, form-acroform
