### ISSUE TITLE
PDF renders with text blacked out as if censored

### ISSUE THREAD

**Issue by ssokolow** [mozilla/pdf.js#5760] opened 2015-02-25 13:22 UTC
Attempting to open this PDF file with the version of PDF.js included in Firefox 37.0a2 (2015-02-18)...
https://ece.uwaterloo.ca/~dwharder/NumericalAnalysis/02Numerics/Double/paper.pdf

...results in this output...
![2015-02-25-082041_1279x944_scrot](https://cloud.githubusercontent.com/assets/46915/6371203/3a534f72-bcc7-11e4-876f-84f51bd3b3e2.png)

...when it should look more like this...
![2015-02-25-082153_1276x977_scrot](https://cloud.githubusercontent.com/assets/46915/6371216/67ad814a-bcc7-11e4-86aa-b93959cc7f19.png)

**Comment by Snuffleupagus** [comment] 2015-02-25 14:41
Closing as a duplicate of the upstream bug https://bugzilla.mozilla.org/show_bug.cgi?id=1122363, see also https://bugzilla.mozilla.org/show_bug.cgi?id=976322 for the root cause.

**Closed by Snuffleupagus** 2015-02-25 14:41 UTC
Labels: 3-upstream
