### ISSUE TITLE
Hello, if you need to not only show the preview, but also add a signature function, is there any other way besides modifying the source code

### ISSUE THREAD

**Issue by infosecliqin** [mozilla/pdf.js#11888] opened 2020-05-09 02:12 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2020-05-09 22:11
Digital signatures are not yet supported in PDF.js, so no, that's not possible now. Duplicate of issues in https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-digital-signature.

**Closed by timvandermeij** 2020-05-09 22:11 UTC
