### ISSUE TITLE
Possible to CACHE PDF document?

### ISSUE THREAD

**Issue by aamakerlsa** [mozilla/pdf.js#7666] opened 2016-09-22 17:33 UTC
I have a relatively simple implementation where I am allowing the user to select a PDF document from an array of files on my server, to load it into the viewer.... what I'm noticing is that as each document is selected the memory that firefox consumes increases until it eventually crashes... is there a way to CACHE the PDF once its been loaded fully once and then prevent a full reload each time a PDF is chosen by the user?  

As each file LI element is clicked, I'm basically using the following to retrieve the PDF and display it in an existing iframe, changing the SRC attribute of the iframe with jquery:

$('#fileViewer-1').find('iframe').attr('src', 'js/pdfjs-1.4.20/web/viewer.html?file%2FHouseWaysMeans%2Fhwm%2Fimages%2FPDFdocs%2F' + filename + '#zoom=page-width');

Is there a more efficient way to do this that doesnt cause such a cummalative effect on the memory consumption for the browser (in this case Firefox)?

Does the API have some way to allow for CACHING of pdf content?

Thanks!

**Comment by timvandermeij** [comment] 2016-09-22 19:47
Even in a custom viewer you must have some `close` method. Take a look at how we do it in the default viewer: https://github.com/mozilla/pdf.js/blob/master/web/app.js#L541. Without this, it may happen that memory is not deallocated properly.

There is no support for caching yet. Since another issue is open for that, I'm closing this one as a duplicate of #5720.

**Closed by timvandermeij** 2016-09-22 19:47 UTC

**Comment by aamakerlsa** [comment] 2016-09-23 22:17
Thanks timvandermeji.   Is there any documentation that shows how to do this in a scenario like mine, where I have an iframe and am using the url syntax such as: 

js/pdfjs-1.4.20/web/viewer.html?file%2Fmypdffile.pdf#zoom=page-width

in my parent page (the page that contains the iframe), can I call this 'CLOSE' method?  

Is there a way for me to always call pdfViewClose() before ANY PDF is loaded and is that a possible solution here?

can I call function pdfViewClose() directly as a 'cleanup' process prior to any PDF is loaded or attempted to be loaded?

**Comment by BillLori** [comment] 2016-09-24 00:58
sounds like good
