### ISSUE TITLE
Header is not visible

### ISSUE THREAD

**Issue by prmanik** [mozilla/pdf.js#16757] opened 2023-07-27 12:43 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 115.0.5790.110 (Official Build) (64-bit)
- Operating system and its version: Windows version 10 enterprise
- PDF.js version: Latest
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the attached document through the solution added or from https://mozilla.github.io/pdf.js/examples/ ->  interactive example
2. Headers are not visible fully

What is the expected behavior? (add screenshot)
![image-2023-06-28-18-01-01-877](https://github.com/mozilla/pdf.js/assets/140620152/c3fa2c52-16aa-46c2-9af5-68f0a0af6c57)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/140620152/ba1a9555-8dc5-495d-9237-63903c53a3a6)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/examples/ ->  interactive example 

or 

[PDFJSSampleZip.zip](https://github.com/mozilla/pdf.js/files/12183541/PDFJSSampleZip.zip)

**Comment by Snuffleupagus** [comment] 2023-07-27 13:06
Duplicate of #16747

---

As mentioned in https://github.com/mozilla/pdf.js/issues/16747#issuecomment-1651801786 it works in the default viewer, please see https://github.com/mozilla/pdf.js#online-demo

> Load the attached document through the solution added or from https://mozilla.github.io/pdf.js/examples/ ->  interactive example

That's purposely a very simple example, and it's thus possible that you need to provide additional API-parameter(s) in the `getDocument`-call in order it to work. Please look in the web-console for any error- and/or warning-messages.

> PDFJSSampleZip.zip

Unfortunately that's not possible for anyone else to run directly; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Closed by Snuffleupagus** 2023-07-27 13:06 UTC

**Comment by Snuffleupagus** [comment] 2023-07-27 13:56
It seems that your PDF document uses CMaps, hence you need to provide the path to them when calling `getDocument`; please see https://github.com/mozilla/pdf.js/blob/611acf52c46ab78a30f6b600fa15ff61cdd7fe24/src/display/api.js#L148-L149

Basically, change your code into something along the following lines. (If that's not enough help, then you *must* provide a directly runnable example.)
```
pdfjsLib.getDocument({
 url: /* PDF document URL goes here. */,
 cMapUrl: /* CMap path goes here.*/,
});
```

**Comment by prmanik** [comment] 2023-07-28 06:31
I was able to load document header with below change

 var loadingTask = pdfjsLib.getDocument({
            url: parameters.url,
            cMapUrl: 'https://unpkg.com/pdfjs-dist@3.7.107/cmaps/',
            cMapPacked: true
        });

But when I tried to use local files like below, it is showing me error as "Error: fetch Built In CMap: failed to fetch file "../web/cmap/UniKS-UTF16-H.cmap" with "Not Found".".

var loadingTask = pdfjsLib.getDocument({
            url: parameters.url,
            cMapUrl: '../web/cmaps/',
            cMapPacked: true
        });

Do you know why it is not accessing local files?

**Comment by prmanik** [comment] 2023-07-31 04:43
do we need to do extra settings to access local file successfully?
