### ISSUE TITLE
XFA document would not be loaded, an error occurs

### ISSUE THREAD

**Issue by dmillard70** [mozilla/pdf.js#14747] opened 2022-04-04 17:35 UTC
Configuration:
- Online Demo Page: https://mozilla.github.io/pdf.js/web/viewer.html
- PDF.js: 2.14.135
- Chrome 100.0.4896.60 (and other) on windows and mac

Document:
[Selbstauskunft_XFA.pdf](https://github.com/mozilla/pdf.js/files/8411860/Selbstauskunft_XFA.pdf)

Steps to reproduce the problem:
1. Load attached XFA document into pdf.js

**Error on loading (in console)**
util.js:400 Warning: XFA - an error occurred during layout: TypeError: Cannot set properties of undefined (setting 'Symbol(extra)')
viewer.html:1 Uncaught (in promise) 

UnknownErrorException {message: "Cannot read properties of undefined (reading 'length')", name: 'UnknownErrorException', details: "TypeError: Cannot read properties of undefined (reading 'length')"}
details: "TypeError: Cannot read properties of undefined (reading 'length')"
message: "Cannot read properties of undefined (reading 'length')"

**Comment by Snuffleupagus** [comment] 2022-04-07 07:27
Duplicate of #14444

**Closed by Snuffleupagus** 2022-04-07 07:27 UTC
