### ISSUE TITLE
Adding Standard 14 Font Support - For Acroform use

### ISSUE THREAD

**Issue by bpetty-formfast** [mozilla/pdf.js#11637] opened 2020-02-27 21:52 UTC
The Issue:
Today Acroform text input elements are not being styled correctly in regard to font, font size, etc.
There are two issues there, one involving a half baked font reference issue where fontRefName is never being set.  Even when implemented, there may never be a font reference.  The second issue is that pdf.js does not have "Standard 14" font support that describes 14 fonts that acrobat reader instinctively knows about.

Questions:
1. Would the project be interested if I submit a pull request adding support for these fonts?  This would make acroform input look better until full font reference support is eventually added.
2. If so, I have a basic implementation that works but it uses my own function for parsing DA for text annotations.  I think the right way would be to use the EvaluatorPreprocessor, but being new to the codebase I am not sure exactly how to go about leveraging it, or if you would like any of this information exposed through your public api when someone uses pdfjs-dist to find all annotations, or if this should be used in a more general place.  So basically I am asking if someone would provide some guidance on what you would like to see, if you would even find this useful in the first place.

Thanks!
![image](https://user-images.githubusercontent.com/18601381/75489862-ace72b00-5978-11ea-803f-cc978b244b97.png)

**Comment by timvandermeij** [comment] 2020-02-27 22:17
There is some DA parsing in https://github.com/mozilla/pdf.js/pull/10122/files, but it was never finished.

I think we don't have the 14 standard fonts because of licensing issues, but perhaps @Snuffleupagus can chime in on that part?

**Comment by bpetty-formfast** [comment] 2020-02-28 15:14
@timvandermeij, thanks for the pull reference.

My thought was to have a small array of these fonts with their properties.  Something like this:
` HeBO: { name: 'Helvitica-BoldOblique', root: 'Helvitica', bold: true, italic: true },`

We could parse the DA to get the font-code and size, use the code to look up the actual font and font characteristics, and then do the equivalent of "_setTextStyle" in annotation_layer.js.

Because this is strictly working in the display within the browser, the fonts do not necessarily need to be shipped (I assume that was the licensing issue).  All we would be doing is simply providing browser hints to what we are looking for.  I can see this being useful until the fontRefName issue for acroforms is resolved, and for PDFs that do not actually embed these fonts at all.

**Comment by brendandahl** [comment] 2020-02-28 16:49
> I think we don't have the 14 standard fonts because of licensing issues, but perhaps @Snuffleupagus can chime in on that part?

I think we could use the fonts in pdfium since the project is also apache 2.0.

**Comment by sayo96** [comment] 2020-12-06 14:26
@brendandahl @timvandermeij  What is the current status of this issue? If possible please let me know when you guys will release a update with fix in `pdf-dist`npm package as well

**Comment by Snuffleupagus** [comment] 2021-06-08 14:06
Duplicate of #4244

**Closed by Snuffleupagus** 2021-06-08 14:06 UTC
Labels: 4-annotations
