### ISSUE TITLE
Some pages of a particular pdf document gets distorted when opened using pdf.js

### ISSUE THREAD

**Issue by coderjeet19** [mozilla/pdf.js#11397] opened 2019-12-09 14:27 UTC
Attach (recommended) or Link to PDF file here:
[ALO_Workbook_V9_CM .pdf](https://github.com/mozilla/pdf.js/files/3939975/ALO_Workbook_V9_CM.pdf)

Configuration:
- Web browser and its version:
Reproducible on Google Chrome version 78.0.3904.108 (Official Build) (64-bit)
and Firefox version 70.0.1 (64-bit)
- Operating system and its version:
MacOS version 10.14.6
- PDF.js version:
Reproducible at https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension:
No
Steps to reproduce the problem:
1. Navigate to https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload the attached pdf document
3. Goto page 3-4.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/54810902/70442278-0481a300-1abc-11ea-888a-50c5d8b3f098.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/54810902/70442156-bd93ad80-1abb-11ea-9aaf-d6b6578d1353.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-12-09 14:41
Duplicate of #269.

**Closed** 2019-12-09 20:57 UTC
