### ISSUE TITLE
PDF Does Not Save With Original Filename

### ISSUE THREAD

**Issue by Koolstr** [mozilla/pdf.js#8501] opened 2017-06-07 18:23 UTC
I am downloading my credit card statements from Discover.com and when saving the PDFs from within your extension, the files are all renamed to stmt.pdf. With your extension disabled, the files save as intended as "Discover-Statement-20170202.pdf", for example. It is a terrible pain to have to rename all the downloaded statements manually.

I have to disable your extension until this issue is resolved. Who knows where else it is having this effect, causing my downloads to be more confusing than they need to be.

Configuration:
- Web browser and its version: Google Chrome, Version 58.0.3029.110 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Home, Version 1703, Build 15063.332
- PDF.js version: 1.6.293
- Is an extension: Yes

**Comment by yurydelendik** [comment] 2017-06-07 18:37
Closing as duplicate of #6396

**Closed by yurydelendik** 2017-06-07 18:37 UTC
Labels: 1-addon, 4-chrome-specific
