### ISSUE TITLE
Characters in Unicode Private Use Area fail to render

### ISSUE THREAD

**Issue by Jap2-0** [mozilla/pdf.js#15358] opened 2022-08-28 18:50 UTC
Attach (recommended) or Link to PDF file here: https://drive.google.com/drive/folders/1UDhozC8FN0-8EfWT0zt8i0ekl85IKPyP
Initially found previewing PDFs at https://www.humblebundle.com/books/tech-book-bundle-get-more-pi-diy-electronics-w-arduino-raspberry-pi-books

Configuration:
- Web browser and its version: Firefox Nightly 106
- Operating system and its version: Windows 10 21H1
- PDF.js version: 2.16.71
- Is a browser extension: No

Steps to reproduce the problem:
1. Open attached PDFs
2. Text is rendered incorrectly (see below)

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/40511669/187089868-afc90309-9f41-4161-93b6-529ad77d42dc.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/40511669/187089911-d8925a68-a4c5-4f5a-9460-5590ea0e172d.png)

Looking further, these characters all appear to come from the Unicode Private Use Area.  However, the (invisible) text layer (for copy/past etc.) understands these characters.

**Comment by Snuffleupagus** [comment] 2022-08-28 19:24
Duplicate of #15289

**Comment by Snuffleupagus** [comment] 2022-08-28 19:25
Please note https://github.com/mozilla/pdf.js/issues/15289#issuecomment-1222203041 in particular.

**Closed by Snuffleupagus** 2022-08-28 19:24 UTC

**Comment by Jap2-0** [comment] 2022-08-28 19:28
Yup, thanks.  Poor searching on my part, sorry.
