### ISSUE TITLE
Message: undefined is not a function (evaluating 'window.requestAnimationFrame(function () 

### ISSUE THREAD

**Issue by FabioLins** [mozilla/pdf.js#10523] opened 2019-02-06 10:50 UTC
Attach (recommended) or Link to PDF file here:
The PDF is the example suggested by PDF JS. (compressed.tracemonkey-pldi-09)

Configuration:
- Web browser and its version: JAVA FX 1.8
- Operating system and its version: Windows 7
- PDF.js version: 2.0.943
- Is a browser extension: JAVA FX 1.8

Steps to reproduce the problem:
1. To include the PDF (it only this)
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
PDF.js v2.0.943 (build: dc98bf76)

Message: undefined is not a function (evaluating 'window.requestAnimationFrame(function () {

          _this16._nextBound().catch(_this16.callback);

        })')

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-02-06 11:01
> Is a browser extension: JAVA FX 1.8

Please note that this question refers to https://github.com/mozilla/pdf.js#browser-extensions.

Most likely "JAVA FX 1.8", whatever that is, is providing an incomplete `window` polyfill that doesn't include *all* of the expected methods (such as e.g. `requestAnimationFrame`). If that's the case this would suggest a bug in "JAVA FX 1.8", rather than in the PDF.js library.

Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment] 2019-02-06 22:33
Closing since this is also a duplicate of #10198. Basically if JavaFX does not support `requestAnimationFrame`, then it's not supported by PDF.js. You'll need to polyfill it yourself in that case.

**Closed by timvandermeij** 2019-02-06 22:33 UTC
