### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by leoakino** [mozilla/pdf.js#7278] opened 2016-05-02 16:55 UTC
Hello experts!

I use the PDFJS to display engineering drawings. As I have a very large vectorized file (bigger than 3mb) when i click on the function "zoomin" occur a certain performance degradation on renderization (at this moment i can´t work with the hand tool and this is very bad for my end user). 

I wonder if is there  any initiative to improve the rendering response time of PDF files?

I also would like to acknowledge and thank to the great work you have done with this plugin!

Best Regards,

Leonardo Aquino

**Comment by yurydelendik** [comment] 2016-05-02 17:08
> I wonder if is there any initiative to improve the rendering response time of PDF files?

Most likely it's a duplicate of #6419. Would you like to track it there?

> when i click on the function "zoomin" occur a certain performance degradation on renderization

This might depend on web browser and most likely present on other native viewers. Please provide more information and measurements (and also document a way for us to preproduce the issue). As is the issue is incomplete.

**Comment by leoakino** [comment] 2016-05-03 14:28
Thanks for reply yurydelendik,

I belive i can follow this issue in #6419, no problems

Unfortunately, i can´t send an example file, because there are some confidential informations.. but, i think would be a great improvement if just the zoom part were processed instead of all the file..

**Comment by yurydelendik** [comment] 2016-05-03 14:29
> I belive i can follow this issue in #6419, no problems

Closing this one then.

**Closed by yurydelendik** 2016-05-03 14:29 UTC
Labels: 4-information-requested
