### ISSUE TITLE
Image data loss, blurry image when converting from Uint8ClampedArray to jpeg file

### ISSUE THREAD

**Issue by DVGY** [mozilla/pdf.js#13711] opened 2021-07-10 04:37 UTC
Attach (recommended) or Link to PDF file here:

[imagepdf.pdf](https://github.com/mozilla/pdf.js/files/6794665/imagepdf.pdf)

Configuration:
using Node V 14.16.1
[live code link](https://codesandbox.io/s/image-data-loss-vci0n)

Steps to reproduce the problem:
1. Go to live sandbox link. Open terminal on right bottom , run `cd src`  run `node index.js`
2. You will notice that new file is created but the file is blurred out. There is some data loss,

What is the expected behavior? (add screenshot)
Writing image file to disk should look similar to in pdf

What went wrong? (add screenshot)
![1625891772757](https://user-images.githubusercontent.com/46158826/125151815-876e5200-e166-11eb-9aab-356fc6a55145.jpeg)
**Can someone put in right direction what went wrong plss ?**

**Comment by Snuffleupagus** [comment] 2021-07-10 08:16
Duplicate of #13709, note in particular https://github.com/mozilla/pdf.js/issues/13709#issuecomment-877395163.

**Closed by Snuffleupagus** 2021-07-10 08:16 UTC
