### ISSUE TITLE
PDF Renders as blank white canvas.

### ISSUE THREAD

**Issue by kinztechcom** [mozilla/pdf.js#9632] opened 2018-04-04 22:10 UTC
Attach (recommended) or Link to PDF file here: 
[0014 A1-41 First floor Finish Plan.pdf](https://github.com/mozilla/pdf.js/files/1877856/0014.A1-41.First.floor.Finish.Plan.pdf)
[0016 A1-71 Roof Plan.pdf](https://github.com/mozilla/pdf.js/files/1877857/0016.A1-71.Roof.Plan.pdf)
[0042 M2-22 Mechanical and Electrical Coordination Plan For Reference Only.pdf](https://github.com/mozilla/pdf.js/files/1877858/0042.M2-22.Mechanical.and.Electrical.Coordination.Plan.For.Reference.Only.pdf)
[0006 C-2.0 Site Development Plan.pdf](https://github.com/mozilla/pdf.js/files/1877859/0006.C-2.0.Site.Development.Plan.pdf)
[0010 L-1.0 Site Landscape Plan.pdf](https://github.com/mozilla/pdf.js/files/1877860/0010.L-1.0.Site.Landscape.Plan.pdf)

Configuration:
- Web browser and its version: Version 65.0.3325.181 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: v1.10.88
- Is a browser extension: No

Steps to reproduce the problem:
1. Attempt to open any of these files listed above.
2. Instead of the pdf rendering correctly, there is a blank white page.

What is the expected behavior? (add screenshot)
Expected behavior is for the pdf to render.
Here's an example of the first file from above:
![screenshot_2](https://user-images.githubusercontent.com/2922507/38337464-edfd8e16-382a-11e8-9086-9d9f10b0d08a.png)

What went wrong? (add screenshot)
Pdf renders a blank white page instead of its content.
![download 1](https://user-images.githubusercontent.com/2922507/38337407-b7690934-382a-11e8-99fe-58c401d7e924.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
I used the example viewer: https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by THausherr** [comment] 2018-04-05 10:09
Likely duplicate of #6741

**Comment by kinztechcom** [comment] 2018-04-06 14:53
Is there an explanation anywhere of what is causing this or what the 4-image-conversion label means?

**Comment by timvandermeij** [comment] 2018-04-06 20:51
This label indicates to the developers that the issue is probably caused by the conversion/rendering of image data.

**Comment by kavisherlock** [comment] 2018-06-12 13:41
Might be similar to https://github.com/mozilla/pdf.js/issues/9474
There's a PR for it https://github.com/mozilla/pdf.js/pull/9645

**Comment by kinztechcom** [comment] 2018-11-24 16:42
Is there any update on this issue?
There are currently two PR #9255 and #9645 
My application in which pdf.js is used frequently has many of these types of pdf's uploaded to it. Right now I just tell them to use pdf compression websites before uploading.

**Comment by nikhil525** [comment] 2019-03-25 22:39
Is there a solution for this at all? There are references to different PRs and I am ending up with no solution in any of them.
Is there at least any hack to resolve this issue?

**Comment by KeiBontakun** [comment] 2019-07-30 09:22
I tested with Windows 10 (1903) 
Edge could render the PDF partially. (see attached image)
Chrome 75.0 shows blank page.
Firefox shows error dialog.

![2019-07-30 181541](https://user-images.githubusercontent.com/3262436/62116989-19704d80-b2f6-11e9-859e-ac4927722470.png)

error dialog by firefox is following:
`
PDF.js v2.3.53 (ビルド: 323b2eab)
メッセージ: 
スタック: putBinaryImageData@https://mozilla.github.io/pdf.js/build/pdf.js:14638:13
CanvasGraphics_paintInlineImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:16107:9
CanvasGraphics_paintImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:16061:12
CanvasGraphics_executeOperatorList@https://mozilla.github.io/pdf.js/build/pdf.js:14911:22
_callee$@https://mozilla.github.io/pdf.js/build/pdf.js:12206:51
tryCatch@https://mozilla.github.io/pdf.js/build/pdf.js:12292:17
invoke@https://mozilla.github.io/pdf.js/build/pdf.js:12467:22
defineIteratorMethods/</prototype[method]@https://mozilla.github.io/pdf.js/build/pdf.js:12335:21
asyncGeneratorStep@https://mozilla.github.io/pdf.js/build/pdf.js:9827:103
_next@https://mozilla.github.io/pdf.js/build/pdf.js:9829:194
_asyncToGenerator/</<@https://mozilla.github.io/pdf.js/build/pdf.js:9829:364
_asyncToGenerator/<@https://mozilla.github.io/pdf.js/build/pdf.js:9829:97
_next@https://mozilla.github.io/pdf.js/build/pdf.js:12231:25
_scheduleNext/<@https://mozilla.github.io/pdf.js/build/pdf.js:12182:21
`

**Comment by Benguenette** [comment] 2020-05-26 02:14
It's been a while since the last update about this topic.

Anything new? We are struggling with our customer viewing scanned pdf through pdf.js.

Is there a workaround or at least a way to know if a file is over 150 dpi?

Thank you in advance

**Comment by kavisherlock** [comment] 2020-05-26 12:22
@Benguenette our team has been maintaining a private fork of this repo with our fix
It had been in PR for a while but got closed without merging. I see that my colleague put a new PR for it a couple of months ago https://github.com/mozilla/pdf.js/pull/11783, but it hasn't been approved yet.
But you can try using his fork: https://github.com/CIE81/pdf.js/tree/IOS600DPI

**Comment by Benguenette** [comment] 2020-05-27 19:54
@kavisherlock Thank you for your answer. We built pdf.js and pdf.worker.js from his fork successfully. It does not seem to fix our problem:

- We are using pdfjs on our webapp on Chrome (not IOS).
- pdf file of 150 dpi always worked good.
- pdf file of 300 dpi and up didn't work before (blank page) and still doesn't work with the new build.

Any suggestion? Is it normal?

Thank you in advance

**Comment by Snuffleupagus** [comment] 2021-09-27 10:30
Duplicate of #6741

**Closed by Snuffleupagus** 2021-09-27 10:30 UTC
Labels: 4-image-conversion
