### ISSUE TITLE
PDF file not rendered

### ISSUE THREAD

**Issue by TerjeHelgesen-rx** [mozilla/pdf.js#14283] opened 2021-11-17 11:55 UTC
Configuration:
Chrome 95.0.4638.69
Windows 10
PDF.js: 2.12.182

Tested with:
https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1.
Open the file
2.
Only a white page is displayed.
In Acrobat a black and white image is displayed.

[MEC-11-12-Q7NX-DE-41-16501 (SH. 12 OF 32) REV.-0.PDF](https://github.com/mozilla/pdf.js/files/7554407/MEC-11-12-Q7NX-DE-41-16501.SH.12.OF.32.REV.-0.PDF)

**Comment by Snuffleupagus** [comment] 2021-11-17 12:07
Duplicate of #6741

**Closed by Snuffleupagus** 2021-11-17 12:07 UTC
