### ISSUE TITLE
slow on reload

### ISSUE THREAD

**Issue by aloispichler** [mozilla/pdf.js#12599] opened 2020-11-08 21:37 UTC
Configuration:
- chrome, firefox
- windows

If the pdf changes on the disk, pdf.js refreshes the displayed content as well:
1) first, a white screen/ cleaned view is displayed, then
2) pdf.js presents the new content.

The first point 1) above is very distracting (the screen dangles). It would be much better and smoother to omit 1) and to refresh the displayed content by overloading/ overwriting the content.

So removing 1) on refreshing constitutes an important and essential improvement for pdf.js.

Thank you.

Remark: SumatraPDF omits 1) and for pdfs with about 10 usual pages, SumatraPDF reloads about 4 seconds faster than pdf.js on a usual machine.

**Comment by Snuffleupagus** [comment] 2020-11-09 10:40
> [...] and VS Code

We know nothing about "VS Code" here, and consequently we cannot provide support for that.

Generally speaking, there's unfortunately a bit too much of the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md missing for this issue to be actionable.

> If the pdf changes on the disk, pdf.js refreshes the displayed content as well:

There's simply put no functionality in the PDF.js library that does this, hence this doesn't really make sense, Are you perhaps using another project, which itself uses PDF.js *internally*? In that case, please direct you questions to that project *first*.

> Working with LaTeX (from within VS Code, e.g.),

Again, that really sounds like another project, since there's neither any LaTeX nor VS Code integration provided by the PDF.js library.

All-in-all, this unfortunately doesn't seem like a valid PDF.js issue and it looks like it was perhaps opened in the wrong bug-tracker.

**Comment by aloispichler** [comment] 2020-11-09 13:27
If the pdf changes on the disk, pdf.js refreshes the displayed content as well:
* first, a white screen/ cleaned view is displayed, then
* pdf.js presents the new content.

The first point 1) above is very distracting (the screen dangles). It would be much better and smoother to omit 1) and to refresh the displayed content by overloading/ overwriting the content.

So removing 1) on refreshing constitutes an important and essential improvement for pdf.js.

**Comment by timvandermeij** [comment] 2020-11-09 21:54
PDF.js doesn't have functionality to refresh a PDF file. You'll have to reopen it, which will remove the existing canvases and render new ones. All in all, this looks like a duplicate of #11827 to me.

**Closed by timvandermeij** 2020-11-09 21:54 UTC
