### ISSUE TITLE
1.7.348 + 1.8.439 (Firefox) wrong metrics for text runs

### ISSUE THREAD

**Issue by evadne** [mozilla/pdf.js#8869] opened 2017-09-04 14:22 UTC
Link to PDF file (or attach file here): 
[SMPembedded.2006.10.09b.pdf](https://github.com/mozilla/pdf.js/files/1274923/SMPembedded.2006.10.09b.pdf)

Configuration:
- Web browser and its version: Firefox 55.0.3. Same on Safari
- Operating system and its version: macOS 10.12.6 (16G29)
- PDF.js version: 1.7.348 + 1.8.439 — both exhibit same issue
- Is an extension: No

Steps to reproduce the problem:
1. Open file in Firefox
2. Attempt to select text

What is the expected behavior? — text selection roughly conforms with the text runs

What went wrong? — highlighted area do not conform to text runs

![screen shot 2017-09-04 at 15 19 23](https://user-images.githubusercontent.com/104086/30030334-af28ec28-9184-11e7-8d02-b7148c213c1a.png)

**Comment by Snuffleupagus** [comment] 2017-09-04 14:59
It looks much better in PDF.js  `1.9.524`, using Firefox Nightly 57 running on Windows 7 (with HWA on).
The vertical alignment is a bit off, but the horizontally alignment seems mostly fine. (Note that, as is often the case with Type3 fonts, the text layer only contains gibberish. This can be observed in e.g. Adobe Reader as well.)

![issue8869](https://user-images.githubusercontent.com/2692120/30031437-ba536fda-9191-11e7-9c91-d0f859dcac74.png)

**Comment by cetinsert** [comment] 2021-09-17 20:15
(`?` ⋯ `2.8.` also ⋯) **`2.11.`** has severely regressed on this file: first paragraph is mostly not selectable now1

https://mozilla.github.io/pdf.js/web/viewer.html?file=//try.httpfs.net/github.com/mozilla/pdf.js:/files/1274923/SMPembedded.2006.10.09b.pdf

[![image](https://user-images.githubusercontent.com/27027/133848013-9f0e519b-baea-49ab-911e-bfcc94c779f7.png)](https://mozilla.github.io/pdf.js/web/viewer.html?file=//try.httpfs.net/github.com/mozilla/pdf.js:/files/1274923/SMPembedded.2006.10.09b.pdf)

**Comment by Snuffleupagus** [comment] 2022-04-18 19:51
Duplicate of #6011

**Closed by Snuffleupagus** 2022-04-18 19:51 UTC
Labels: text-selection, font-type3
