### ISSUE TITLE
Fetch calls are not happening for specific PDF Document when disableAutofetch and disableStream are set to true. 

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#16488] opened 2023-05-29 13:31 UTC
Attach (recommended) or Link to PDF file here:
[10kpageslinear.pdf](https://github.com/mozilla/pdf.js/files/11592096/10kpageslinear.pdf)

Configuration:
- Web browser and its version: chrome, firefox
- Operating system and its version: Windows
- PDF.js version: latest
- Is a browser extension:

Steps to reproduce the problem:
1. Open above pdf in pdf.js viewer
2. Scroll to 2000 th page
3. 

What is the expected behavior? (add screenshot)
Fetch call should be seen for the 2000 th page
What went wrong? (add screenshot)
No fetch call happens on scrolling. Entire document is fetched. 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-05-29 13:36
Duplicate of #16411

**Closed by Snuffleupagus** 2023-05-29 13:36 UTC
Labels: core
