### ISSUE TITLE
Investigate if we can remove "transitionend" event listener

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#17347] opened 2023-11-28 12:26 UTC
The bug described in https://bugzilla.mozilla.org/show_bug.cgi?id=1866773 is because at some point a blur event is triggered by:
https://github.com/mozilla/pdf.js/blob/4bf7ff20270ec5dd6458a136c79fdf1cc590a1c6/web/app.js#L687-L695
This code has been added a while back:
https://github.com/mozilla/pdf.js/pull/1614

If I understand correctly the idea was to resize to main container once the transition for the sidebar resize is done.
The transitionend event is triggered for whatever transition we've in the main container, so for example when we're searching a word in the pdf, the event is triggered (because of the spinner).
I'd be in favor to remove this listener because it doesn't make sense to trigger a resize for whatever transition and we should figure out how to resize correctly the main container without such an event.

@Snuffleupagus, any ideas, opinions ?

**Comment by Snuffleupagus** [comment] 2023-11-28 15:07
> If I understand correctly the idea was to resize to main container once the transition for the sidebar resize is done.

Yes, it's intended to trigger rendering in the viewer (for the "named" zoom value) when the sidebar has been opened/closed.

We obviously need to keep that working, and another possibility would be to use an already existing `ResizeObserver` to trigger re-rendering. However, the only annoying thing would be that the `ResizeObserver` also fires *while* the sidebar is opening/closing and we really don't want to trigger re-rendering for all those "intermediate" events. We could perhaps use a timeout to avoid triggering re-sizing until things have settled down; I'll try to do some experiments later this week.

**Comment by Snuffleupagus** [comment] 2023-11-30 19:26
> The transitionend event is triggered for whatever transition we've in the main container, so for example when we're searching a word in the pdf, the event is triggered (because of the spinner).

Using the latest Nightly version, on Windows 11, I cannot actually reproduce this; maybe it's different on other OSes?

**Comment by calixteman** [comment] 2023-11-30 19:35
Yes Emilio fixed the bug so it isn't a concern anymore.
But, for me at least, the bug highlights this use of `transitionend` and I think we shouldn't use it, so it's why I filed this issue.

**Closed** 2023-12-01 09:22 UTC
Labels: viewer
