### ISSUE TITLE
Image data always null

### ISSUE THREAD

**Issue by buttercoding** [mozilla/pdf.js#17037] opened 2023-09-26 19:41 UTC
The following code always returns "No image data for image on page".  `imgData?.data` is always null.  This is client-side code that is executing within a NextJs/React `useEffect` if that matters.  I am not rendering the image to the page, but am instead wanting to OCR it.

```typescript
      const pages = await Promise.all(Array.from({ length: pdf.numPages }, (_, i) => pdf.getPage(i + 1)));

      await Promise.all(
        pages.map(async (page, pageIndex) => {
          const ops = await page.getOperatorList();
          const imageDataPromises = [];

          async function loadImageData(imageName: string) {
            // Retrieve image data
            const imgData = await page.objs.get(imageName).promise;
            return imgData;
          }

          for (let i = 0; i < ops.fnArray.length; i++) {
            if (ops.fnArray[i] === pdfJS.OPS.paintImageXObject) {
              const [imageName] = ops.argsArray[i];
              Console.log(imageName);
              // Push the promise into the array without awaiting it
              imageDataPromises.push(loadImageData(imageName));
            }
          }

          // Wait for promises to resolve
          const imgDataArray = await Promise.all(imageDataPromises);

          // Process the results
          imgDataArray.forEach((imgData) => {
            if (imgData?.data instanceof Uint8Array) {
              Console.log(`Image data for image on page ${pageIndex}:`, imgData.data);
            } else {
              Console.error(`No image data for image on page`);
            }
          });
      })
      );

```

**Comment by Snuffleupagus** [comment] 2023-09-26 19:57
Duplicate of #16282

**Closed by Snuffleupagus** 2023-09-26 19:57 UTC
