### ISSUE TITLE
Some artifacts are not being rendered. 

### ISSUE THREAD

**Issue by jonathan-mui** [mozilla/pdf.js#4788] opened 2014-05-13 06:34 UTC
I have a file that contains e-signatures https://drive.google.com/file/d/0B4tNrTucB2D_M0FwQ3VrdEFUdms/edit?usp=sharing. When rendering with PDF.js, The signed areas only appear with the timestamp like so:
![screenshot 2014-05-12 23 28 57](https://cloud.githubusercontent.com/assets/575212/2953931/e5e13edc-da67-11e3-9c83-fd891815ae08.png)
On other readers such as Acrobat, Google Drive, and Apple Preview, the signatures show up correctly like so (in Acrobat):
![screenshot 2014-05-12 23 30 14](https://cloud.githubusercontent.com/assets/575212/2953939/0ffa8386-da68-11e3-8349-632154e56027.png)

I don't know much about PDF signatures, so I'm not sure what makes this document cause the bug. Thanks!

**Comment by timvandermeij** [comment] 2018-09-12 11:05
Closing since this is a duplicate of #4202.

**Closed by timvandermeij** 2018-09-12 11:05 UTC
Labels: 4-annotations
