### ISSUE TITLE
Use full width of container for PDF display

### ISSUE THREAD

**Issue by nschloe** [mozilla/pdf.js#5654] opened 2015-01-16 18:20 UTC
I would like the displayed PDF to use the entire width of the containing element. I thought I achieve this by setting
```
container.addEventListener('pagesinit', function () {
  pdfViewer.currentScaleValue = 'page-width';
});
```
but this doesn't quite do the trick; see 
![margin2](https://cloud.githubusercontent.com/assets/181628/5781681/eef15e92-9db4-11e4-89f6-1f0e2b0e19fe.png)

What setting is required?

**Comment by Snuffleupagus** [comment] 2015-01-16 20:46
Closing as duplicate of issue #5559.

**Closed by Snuffleupagus** 2015-01-16 20:46 UTC
Labels: 1-other

**Comment by nschloe** [comment] 2015-01-16 23:12
Wow, that's embarrassing. Thanks @Snuffleupagus for pointing out this is a dup if my _own_ bug report.
