### ISSUE TITLE
I want to highlight particular line dynamically

### ISSUE THREAD

**Issue by Abdurraheem** [mozilla/pdf.js#7314] opened 2016-05-11 05:07 UTC
I want to highlight particular line dynamically for that i used  

```javascript
var dynElems = document.getElementById('page1').getElementsByClassName('textLayer');
var dynElems = document.getElementsByClassName('textLayer');
for (var i=0; i<dynElems.length; i++) {
     dynElems[i].className += " highlight";
}
```

 but its not working can anyone suggest me anything.....

**Comment by yurydelendik** [comment] 2016-05-11 09:35
The issue is unrelated to pdf.js. Closing as invalid

**Closed** 2016-05-11 10:01 UTC
