### ISSUE TITLE
Pdf.js not found Issue

### ISSUE THREAD

**Issue by DrastiGohel** [mozilla/pdf.js#17116] opened 2023-10-13 19:37 UTC
We are using pdf.worker.js and all of a sudden it started giving the error 404 file not found!

Below is the typescript code:

```
protected loadPDF(url: any) {

    var pdfjsLib = window['pdfjs-dist/build/pdf'];

    pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://mozilla.github.io/pdf.js/build/pdf.worker.js';

    pdfjsLib.getDocument({ data: url }).promise.then((pdfDoc_) => {

        this.pdfDoc = pdfDoc_;
        $('#page_count').text(this.pdfDoc.numPages);

        this.renderPage(this.pageNum);
    });
}
```

.cshtml:

`<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>`

Error:
![image](https://github.com/mozilla/pdf.js/assets/98172041/e999001b-7021-46f5-b63c-a587f31686a9)

Trying to visit the cdn link gives the same error on browser:

![image](https://github.com/mozilla/pdf.js/assets/98172041/d08086a7-d46d-4cf0-8848-2028421d314a)

The above was working correctly and it stopped working recently, Please advise!

**Comment by Snuffleupagus** [comment] 2023-10-13 19:42
Duplicate of #17092, please note https://github.com/mozilla/pdf.js/issues/17092#issuecomment-1752881489 in particular.

**Closed by Snuffleupagus** 2023-10-13 19:42 UTC
