### ISSUE TITLE
[Bug]: Mobile keyboard disappears when I try to write on the document

### ISSUE THREAD

**Issue by AndreaZari1** [mozilla/pdf.js#18363] opened 2024-07-02 07:41 UTC
### Attach (recommended) or Link to PDF file

https://github.com/mozilla/pdf.js/assets/174119937/fd2e89b8-408b-44e5-a516-2cfe53933a8b

### Web browser and its version

Google Chrome mobile 126.0.6478.122

### Operating system and its version

Android 9

### PDF.js version

I am using pdf-extended-viewer v20.5.2

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

- Open the pdf and try to write on the document pressing the "T" button on the toolbar
- tap anywhere on the document to write
-
I am using a HUAWEI MediaPad M5, the screen is 10.8"

### What is the expected behavior?

to write on the document

### What went wrong?

as you can see in the video i attached, the keyboard goes away as soon as it spawns.

### Link to a viewer

it also happens in the showcase https://mozilla.github.io/pdf.js/web/viewer.html.

### Additional context

I opened this issue on pdf-extended-viewer's github and I was then told to submit the bug here as well

**Comment by Snuffleupagus** [comment] 2024-07-02 07:48
Duplicate of #18095

**Closed by Snuffleupagus** 2024-07-02 07:48 UTC

**Comment by Snuffleupagus** [comment] 2024-07-02 07:51
> ### PDF.js version
> 
> I am using pdf-extended-viewer v20.5.2

*For future reference:* Please remember to provide a valid PDF.js version number, since "pdf-extended-viewer v20.5.2" is not being developed here and the quoted version number thus isn't really helpful here.
