### ISSUE TITLE
Selected text isn't equivalent to shown text in this pdf

### ISSUE THREAD

**Issue by piotrex** [mozilla/pdf.js#3673] opened 2013-09-11 15:13 UTC
In this pdf http://blog.fpmurphy.com/2011/02/firefox-4-restartless-add-ons.html?output=pdf#page=1&zoom=auto,0,553 selected text isn't equal to shown in the same place text. 

For example try select "extension" word in first paragraph, copy it and paste somewhere. It will paste "more". The same issues are in almost whole pdf.

In PDF X-Change Viewer 2.5 pdf works well.

PDF.js version 0.8.505.
Firefox 23.0.1
Windows 7 x64

**Comment by Snuffleupagus** [comment] 2015-01-26 21:50
I cannot reproduced this, using PDF.js 1.0.1118.
Closing as worksforme.

**Closed by Snuffleupagus** 2015-01-26 21:50 UTC
Labels: 4-text-selection

**Comment by timvandermeij** [comment] 2015-01-27 19:11
Confirmed to be fixed.
