### ISSUE TITLE
Text cannot be properly parsed

### ISSUE THREAD

**Issue by mirh** [mozilla/pdf.js#15433] opened 2022-09-13 13:19 UTC
https://www.turunkonekeskus.fi/media/tiedostot/kayttoohjeet/17510598-juwel7mt.pdf

**Configuration:**
- Web browser and its version: Firefox 105
- Operating system and its version: W10
- PDF.js version: 2.16.71
- Is a browser extension: yes

Steps to reproduce the problem:
1. Open the pdf
2. Copy/search anything

**What is the expected behavior?**

The text is properly recognized

**What went wrong?**

Everything is garbled.

**Comment by calixteman** [comment] 2022-09-13 13:27
I get the same garbled text in Edge and in Acrobat.
So for me the issue is very likely in the pdf itself.
I'd say that the encoding is wrong.

**Comment by Snuffleupagus** [comment] 2022-09-13 13:37
> I get the same garbled text in Edge and in Acrobat.
> So for me the issue is very likely in the pdf itself.
> I'd say that the encoding is wrong.

There's no /ToUnicode data present for any of the fonts in the PDF document, which means that it's simply *impossible* for text-selection and copying to work "correctly" unfortunately.
This is a bug in the particular PDF document *itself*, which is why no PDF viewer (not even Adobe Reader) is able to handle it; hence closing this issue since we most unfortunately cannot fix it.

**Closed by Snuffleupagus** 2022-09-13 13:37 UTC

**Comment by mirh** [comment] 2022-09-13 16:36
How is it that it can be displayed then?
Btw, while edge and mupdf seem to be able to at least zoom-in indefinitely, firefox built-in reader has text become blurry on extreme magnifications.

**Comment by Snuffleupagus** [comment] 2022-09-13 17:19
> How is it that it can be displayed then?

Because rendering and text-extraction uses *separate* code-paths in PDF documents (according to the specification).

> Btw, while edge and mupdf seem to be able to at least zoom-in indefinitely, firefox built-in reader has text become blurry on extreme magnifications.

That sounds unrelated to this issue, however that's already (effectively) covered by issue #6419.
