### ISSUE TITLE
Drop pdf document when dragging from mail app do not work

### ISSUE THREAD

**Issue by Pldi23** [mozilla/pdf.js#14942] opened 2022-05-20 07:01 UTC
When I drag and drop a pdf from local directory pdf.js works fine and document gets displayed. But when the file dragged from mail app pdf.js do not display pdf.

Attach (recommended) or Link to PDF file here: not important, any pdf could be used to reproduce the issue.

Configuration:
- Web browser and its version: Chrome Version 101.0.4951.64 (Official Build) (arm64) (the same issue on other browsers)
- Operating system and its version: MacOS Monterey version 12.4 (but the same happens on windows based systems)
- PDF.js version: 2.10.562 and later
- Is a browser extension: no (not sure what is it)

Steps to reproduce the problem:
1. prepare an email with a pdf document
2. drag and drop pdf directly from the mail app

What is the expected behavior?
pdf.js should display a document

What went wrong?
pdf.js do **not** display a document

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-05-20 07:28
> When I drag and drop a pdf from local directory pdf.js works fine and document gets displayed. But when the file dragged from mail app pdf.js do not display pdf.

That unfortunately suggests a bug in your "mail app", rather than in the PDF.js viewer/library, since otherwise you'd really expect it to be consistently broken in all use-cases.

> PDF.js version: 2.10

That's first of all not a *complete* version number. Furthermore that version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:
>     1. prepare an email with a pdf document
>     2. drag and drop pdf directly from the mail app

That's not really sufficient information unfortunately, since you've not mentioned anything about *which exact* "mail app" you're using here (making it impossible for anyone to actually reproduce this).

Closing, since this doesn't seem to be a PDF.js bug and that the provided information unfortunately isn't sufficient for this to be actionable.

**Comment by Pldi23** [comment] 2022-05-20 07:45
@Snuffleupagus 
> That unfortunately suggests a bug in your "mail app", rather than in the PDF.js viewer/library, since otherwise you'd really expect it to be consistently broken in all use-cases.
> 
This could be reproduced with several Mail Apps on different OS, I simply put a default Mac Os Mail App client, why did you say that I didn't mention exact app?

> That's first of all not a complete version number. Furthermore that version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
>
ok maybe more correct would be 
PDF.js version: 2.10.562 and later (including latest)

> Closing, since this doesn't seem to be a PDF.js bug and that the provided information unfortunately isn't sufficient for this to be actionable.
>

Why do you think it's not a pdf.js bug? I made some research and it seems that https://github.com/mozilla/pdf.js/blob/master/web/app.js#L2190 should be `evt.dataTransfer.dropEffect = "copy";`
I've made some manual testing and it solves the issue.

Do you want me to submit a PR with such fix?

**Comment by Snuffleupagus** [comment] 2022-05-20 08:10
> This could be reproduced with several Mail Apps on different OS, I simply put a default Mac Os Mail App client, why did you say that I didn't mention exact app?

This sentence clearly mentions the exact software used, however previously only "mail app" was used which is ambiguous (especially for people not using MacOS).

> I made some research and it seems that https://github.com/mozilla/pdf.js/blob/master/web/app.js#L2190 should be `evt.dataTransfer.dropEffect = "copy";`

Based on https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect, it seems strange that it should matter given that it's described as providing visual feedback:
> The DataTransfer.dropEffect property controls the feedback (typically visual) the user is given during a drag and drop operation. It will affect which cursor is displayed while dragging. For example, when the user hovers over a target drop element, the browser's cursor may indicate which type of operation will occur.

Hence it's really quite difficult to see why `dropEffect` matters, from a functionality perspective, and consequently it's not clear why we want to change this (since having a "move" effect is generally correct here). Can you reproduce this in other browsers, e.g. in Firefox, or is it perhaps specific to Google Chrome?

**Comment by Pldi23** [comment] 2022-05-20 08:33
From what I see (tested quickly with https://mozilla.github.io/pdf.js/web/viewer.html) It woks in Firefox only. In Chrome, Edge and Opera do not work.

**Comment by calixteman** [comment] 2022-05-20 09:31
I manage to reproduce the issue on a mac.
I dump the `dataTransfer` on `dragOver` and in Firefox the `effectAllowed` property is set to `uninitialized` when it's `copy` in Chrome.
According to the doc, `uninitialized` is equivalent to `all`:
https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/effectAllowed#uninitialized
If I understand correctly, `effect` is not only related to something visual but it's about the consequence of the drop.
Anyway I think `copy` should be the right thing to do: there is no way to "move" a pdf in a web browser.

**Comment by Snuffleupagus** [comment] 2022-05-20 09:36
> Anyway I think `copy` should be the right thing to do: there is no way to "move" a pdf in a web browser.

That'd be actually look inconsistent, since dragging *any* local document into e.g. a Firefox tab will display as a "move" (at least on Windows).

**Comment by calixteman** [comment] 2022-05-20 09:48
I quote [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect):
"... if the desired dropEffect is 'move', then the data being dragged should be removed from the source. "
So if I understand correctly, the idea behind a dnd action in the pdf viewer isn't to "move" the file but just "copy" it into the browser. I suppose it's why the Mail app is setting the effect to "copy": the dnd action won't remove the attachment from the email.

**Comment by calixteman** [comment] 2022-05-20 09:58
A fix could be to set the value of `dropEffect` based on the value of `effectAllowed`.
When the `effectAllowed` is `copy` then we must set `dropEffect` to `copy` and for  `uninitialized` or `all` we can keep `move`.

**Comment by Snuffleupagus** [comment] 2022-05-20 10:49
> A fix could be to set the value of `dropEffect` based on the value of `effectAllowed`.

That seems like the nicest solution overall (assuming it works), since that'd not change the existing default behaviour.

**Closed** 2022-05-22 13:34 UTC
Labels: viewer
