### ISSUE TITLE
PDF incorrectly rendered: first page is repeated in the background of all other pages

### ISSUE THREAD

**Issue by Underground78** [mozilla/pdf.js#13499] opened 2021-06-05 13:17 UTC
Attach (recommended) or Link to PDF file here: [bug_firefox_pdfjs.pdf](https://github.com/mozilla/pdf.js/files/6602581/bug_firefox_pdfjs.pdf) ([source](https://www.ratp.fr/sites/default/files/inline-files/Dossier%20de%20Presse%20travaux%20ete.pdf))

Configuration:
- Web browser and its version: Firefox 89.0
- Operating system and its version: Windows 10
- PDF.js version: 2.9.45
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached PDF file in Firefox.
2. Check any page starting from page 2, the content of the first page incorrectly appears in the background at the top right.
3. Compare with another viewer, for example Adobe Acrobat Reader DC.

What is the expected behavior?
Screenshot from Adobe Acrobat Reader DC:
![image](https://user-images.githubusercontent.com/371636/120892920-c281e080-c610-11eb-824f-cc7b00f85ce2.png)

What went wrong?
Screenshot from Firefox:
![image](https://user-images.githubusercontent.com/371636/120892901-a4b47b80-c610-11eb-89e8-9dee9c189389.png)

**Comment by calixteman** [comment] 2021-06-05 13:21
Works for me on linux with Firefox 89 and 91 (nightly) using the buildin viewer.

**Comment by Underground78** [comment] 2021-06-05 15:36
I can indeed confirm that this issue cannot be reproduced on Linux.

**Comment by cetinsert** [comment] 2021-06-08 07:26
I can reproduce it in Firefox 89 on Window. `pdfjsLib.version` is `2.9.45`.

No issues with

- https://mozilla.github.io/pdf.js/web/viewer.html
- custom rendering without the viewer layer

**Comment by Snuffleupagus** [comment] 2021-12-06 14:36
Related to issue #8019 and/or #8022; hence fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1336572 and/or https://bugzilla.mozilla.org/show_bug.cgi?id=1336591

**Closed by Snuffleupagus** 2021-12-06 14:36 UTC
Labels: 3-pdf-broken, 4-os-windows, 3-upstream

**Comment by Underground78** [comment] 2022-01-15 12:36
I can confirm the issue is fixed in Firefox 96.0.1.
