### ISSUE TITLE
SVG Renderer displays layers (at least highlights) in incorrect order

### ISSUE THREAD

**Issue by mishase** [mozilla/pdf.js#14468] opened 2022-01-18 17:54 UTC
Attach (recommended) or Link to PDF file here:
[example-1.pdf](https://github.com/mozilla/pdf.js/files/7891303/example-1.pdf)

Configuration:
- Web browser and its version: Chrome 97.0.4692.71
- Operating system and its version: Windows 11
- PDF.js version: `gulp dist` generated from [master](https://github.com/mozilla/pdf.js/tree/f955b0e20c109919399a35f06bce3a75d7d4caaa)
- Is a browser extension: No

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/43600912/149990985-309a008b-c8ca-4818-8285-4b24c11fb23b.png)

What went wrong? (add screenshot)
Highlight covers the text
![image](https://user-images.githubusercontent.com/43600912/149990935-83c163f7-a1e0-4d72-af99-cb5ed52158b2.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
PDF.js SVG viewer using built components (examples/svgviewer/index.html)

**Comment by Snuffleupagus** [comment] 2022-01-18 18:37
Duplicate of #10165

Please also note that the SVG-backend is not officially supported, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

**Closed by Snuffleupagus** 2022-01-18 18:37 UTC
