### ISSUE TITLE
Cannot switch between annotation layer form fields on Safari (macOS/iOS)

### ISSUE THREAD

**Issue by cetinsert** [mozilla/pdf.js#13191] opened 2021-04-07 04:28 UTC
Attach (recommended) or Link to PDF file here: [OoPdfFormExample.pdf](https://github.com/mozilla/pdf.js/files/6268923/OoPdfFormExample.pdf)

Configuration:
- Web browser and its version: **Safari** &ndash; v14.0.3
- Operating system and its version: **macOS** &ndash; Big Sur v11.2.3

(the issue persists in latest versions of Safari on iOS as well)

- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: no

Steps to reproduce the problem:
1. open attached PDF
2. click/tap into the **Given Name** field
3. click/tap into any other field

What is the expected behavior? (add screenshot)
Focus switches to the field from step 3

What went wrong? (add screenshot)
Focus stays stuck in the Given Name field.
Tab button does not work either.

**Comment by Snuffleupagus** [comment] 2021-04-07 07:56
WFM, using PDF.js version `2.8.320` in Firefox Nightly.

> Web browser and its version: **Safari** – v14.0.3

If this is specific to Safari, that'd suggest a bug in the browser *itself* rather than the PDF.js library.

---

For anyone trying to debug/fix this, please keep in mind that we'll generally not accept browser-specific compatibility hacks placed in the main code-base and such things should usually live in https://github.com/mozilla/pdf.js/blob/master/src/shared/compatibility.js

**Comment by cetinsert** [comment] 2021-04-07 09:00
This is specific to Safari - to which there is no alternative on iOS (tablets, phones).

**Comment by cetinsert** [comment] 2021-04-07 09:07
- Removing contents of the entire `viewer.css` does not help.
- Clicking into developer tools (browser chrome (such as address bar) does not work) and back into an unfocused field does switch focus.

**Comment by cetinsert** [comment] 2021-04-07 09:13
> Steps to reproduce the problem:
> 1. open attached PDF
> 2. click/tap into the **Given Name** field
> 3. click/tap into any other field

in step 3. other viewer inputs (such as `#pageNumber` and `#findInput`) cannot be focused into either.

**Comment by cetinsert** [comment] 2021-04-07 09:25
- issue persists in other documents with forms

**Comment by Snuffleupagus** [comment] 2021-04-07 18:04
Looks, for all intents and purposes, like a duplicate of #12592

**Comment by Snuffleupagus** [comment] 2021-04-07 18:04
This looks, for all intents and purposes, like a duplicate of #12592.

**Closed** 2021-04-07 18:30 UTC
