### ISSUE TITLE
Failed to preview the PDF.js online sample in IE 11!

### ISSUE THREAD

**Issue by hsheng12** [mozilla/pdf.js#12608] opened 2020-11-11 03:40 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE11 11.1139.18362
- Operating system and its version: Windows 10 Home CHINESE Edition
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1.  Open this link in IE 11: https://mozilla.github.io/pdf.js/web/viewer.html
Or
https://mozilla.github.io/pdf.js/es5/web/viewer.html

What is the expected behavior? (add screenshot)
![1](https://user-images.githubusercontent.com/9734961/98762443-9b648700-2412-11eb-9b62-93e59b89d45e.png)

What went wrong? (add screenshot)
![2](https://user-images.githubusercontent.com/9734961/98762452-9ef80e00-2412-11eb-8772-4d02cddf2576.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2020-11-11 10:12
Duplicate of #12602

**Closed** 2020-11-11 19:28 UTC
