### ISSUE TITLE
If "Allow pages to choose their own fonts" option is disabled in FF, PDF.s can be empty

### ISSUE THREAD

**Issue by mhoye** [mozilla/pdf.js#12518] opened 2020-10-22 18:07 UTC
PDF:  http://web.mit.edu/~simsong/www/ugh.pdf

In Firefox options, general -> language and appearance -> advanced switch off the option to let web pages choose their own fonts and open that PDF.

Configuration:
Win10 current, Nightly current, PDF.js built into Nightly.

What went wrong? (add screenshot)

With that option checked, that document is almost entirely blank, containing only the clipart and no text.

**Comment by Snuffleupagus** [comment] 2020-10-23 08:11
Duplicate of #4244

**Closed** 2020-10-23 20:29 UTC
Labels: 1-core
