### ISSUE TITLE
Unable to render font family

### ISSUE THREAD

**Issue by rynangeles** [mozilla/pdf.js#14852] opened 2022-04-28 10:54 UTC
@Snuffleupagus sorry for the incomplete details of my issue. Basically, I was planning to update my project dependencies.
Application: https://typescript-35ttx9.stackblitz.io/ 
Code: https://stackblitz.com/edit/typescript-35ttx9?file=index.html  
this is the actual code I use to render the PDF and the custom text layers. 

In 2.0.274 I was able to display fontFaces of each text layer by just adding the **textItem.fontName** to its font-family rule in styles (as shown in my initial screenshots). e.g. **font-family: g_d0_f1, sans-serif;**. But in 2.10.377 its not rendering the fontFace.

_Originally posted by @rynangeles in https://github.com/mozilla/pdf.js/issues/14330#issuecomment-984030087_

**Comment by Snuffleupagus** [comment] 2022-04-28 11:10
Duplicate of #14330

---

As mentioned in https://github.com/mozilla/pdf.js/issues/14330#issuecomment-983461175, the way that you were using the font names was never really intended/supported since rendering and text-extraction uses *different* code-paths (even in the PDF specification itself); please keep in mind that the text-layer is *supposed to be invisible*.
Hence this likely worked purely by a happy coincidence, but it was never actually intended/supported unfortunately.

**Closed by Snuffleupagus** 2022-04-28 11:10 UTC
