### ISSUE TITLE
Show blank for some pdf 

### ISSUE THREAD

**Issue by shiguanglu** [mozilla/pdf.js#9942] opened 2018-07-31 08:40 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
Chrome:Version 67.0.3396.99 (Official Build) (64-bit)
- Operating system and its version:
MacOSX:V10.13.5
- PDF.js version: 
Offical pdf viewer:https://mozilla.github.io/pdf.js/web/viewer.html 
- Is a browser extension:
No.

Steps to reproduce the problem:
1. Import pdf and try to view with pdf.js
2. It shows blank instead of content 

[From David Thomas 03-P2.pdf](https://github.com/mozilla/pdf.js/files/2244424/From.David.Thomas.03-P2.pdf)

**Comment by Snuffleupagus** [comment] 2018-07-31 09:12
Duplicate of issue #6741.

**Closed** 2018-07-31 21:03 UTC
