### ISSUE TITLE
Acroform Textfield doesn't set the stored user's value in the html element if it has a default value

### ISSUE THREAD

**Issue by TaTo30** [mozilla/pdf.js#16723] opened 2023-07-22 01:21 UTC
Attach (recommended) or Link to PDF file here: [_pdf4.pdf](https://github.com/mozilla/pdf.js/files/12135307/_pdf4.pdf)

Configuration:
- Web browser and its version: Firefox 115
- Operating system and its version: Windows 10
- PDF.js version: 3.7.107
- Is a browser extension: no

Implementing a web application with pdfjs-dist package and enabling forms, if a textfield has a default value it always will render with that value even if there are a different value in storage.

![sample](https://github.com/mozilla/pdf.js/assets/57086025/47fdb401-3e75-46b4-a2d4-bd1b59e2f342)

The expected behavior is for textfields hold the user's value.

I think the issue is probably caused by this code: [https://github.com/mozilla/pdf.js/blob/abb24f82fb0a39c8b8f647768a77623e67d649f6/src/display/annotation_layer.js#L1181](https://github.com/mozilla/pdf.js/blob/abb24f82fb0a39c8b8f647768a77623e67d649f6/src/display/annotation_layer.js#L1181)

```js
const elementData = {
  userValue: textContent,
  formattedValue: fieldFormattedValues,
  lastCommittedValue: null,
  commitKey: 1,
};

if (this.data.multiLine) {
  element = document.createElement("textarea");
  element.textContent = fieldFormattedValues ?? textContent; // <-- here
  if (this.data.doNotScroll) {
    element.style.overflowY = "hidden";
  }
} else {
  element = document.createElement("input");
  element.type = "text";
  element.setAttribute("value", fieldFormattedValues ?? textContent); // <-- also here...
  if (this.data.doNotScroll) {
    element.style.overflowX = "hidden";
  }
}
```
`textContent` has the stored user's value and `fieldFormattedValues` look to has the default value, you can see that `fieldFormattedValues` has more precedence than `textContent`, maybe switching the precedence could fix it.

**Comment by TaTo30** [comment] 2023-07-22 03:03
I also noticed when `blur` event is dispatched textfield restores to default because `fieldFormattedValues` has the default value, so i think both problems could be fixed by adding this line:

```js
// if `textContent` has user's value `fieldFormattedValues` isn't needed
fieldFormattedValues = textContent ? null : fieldFormattedValues

const elementData = {
  userValue: textContent,
  formattedValue: fieldFormattedValues,
  lastCommittedValue: null,
  commitKey: 1
};
```

**Comment by Snuffleupagus** [comment] 2023-07-22 07:39
> PDF.js version: 3.7.107

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Implementing a web application with pdfjs-dist package and enabling forms, if a textfield has a default value it always will render with that value even if there are a different value in storage.

This would be much easier to reproduce/understand with a *runnable example*, as asked for in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md

**Comment by Snuffleupagus** [comment] 2023-09-28 16:42
Duplicate of #17046

**Closed by Snuffleupagus** 2023-09-28 16:42 UTC
Labels: annotations, form-acroform
