### ISSUE TITLE
Filename spaces replaced with + sign?

### ISSUE THREAD

**Issue by sottwell** [mozilla/pdf.js#6507] opened 2015-10-06 16:32 UTC
It appears that this doesn't accept + signs used to replace spaces in the filename. Is there any way to fix that?

**Comment by timvandermeij** [comment] 2015-10-06 16:46
Opening a file with a + in the file name works for me using https://mozilla.github.io/pdf.js/web/viewer.html. Could you elaborate on what the issue is exactly and provide an example link?

**Comment by sottwell** [comment] 2015-10-06 17:09
Works OK with spaces, works OK with %20 instead of spaces, but the exact same link with + instead of spaces throws the missing file error. 

http://sottwell.com/pdf.html?file=/assets/files/Wayfinder+Cheatsheet.pdf

**Comment by yurydelendik** [comment] 2015-10-06 17:35
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-specify-a-different-pdf-in-the-default-viewer : "the PDF path/URL must be encoded using encodeURIComponent()"

`encodeURIComponent(" ") === "%20"`

**Comment by sottwell** [comment] 2015-10-06 17:42
I kind of thought so, but others seem to feel it's a fault in the script consuming the URI to not recognize a +. Plenty of ways to work around it.

**Comment by yurydelendik** [comment] 2015-10-06 17:46
AFIAK, only php's `urlencode` produces such encoding for legacy reasons and though it is recommended to use `rawurlencode`. ("it's a fault in the script" if it is not documented, in our case we explicitly require in which format we expect the input)

**Comment by timvandermeij** [comment] 2015-10-06 17:48
I agree with @yurydelendik. The documentation clearly describes what kind of input is necessary. I have never heard of a `+` in the URL being encoded as a space, so I'm leaning towards closing this issue as is not a bug in PDF.js.

**Comment by sottwell** [comment] 2015-10-06 17:49
Well, I've made a pull request to the CMS that I use that uses urlencode(). It's just one teeny tiny change, but they're acting like I want to eat their baby or something. I'm pretty stubborn, so it'll get done eventually.

**Comment by sottwell** [comment] 2015-10-06 17:49
Of course, telling the client not to upload files with spaces in the filename is one battle I know better than to try to fight.

**Comment by timvandermeij** [comment] 2016-01-03 12:53
I'm going to close this issue as there does not appear to be anything we should do about this on the PDF.js side.

**Closed by timvandermeij** 2016-01-03 12:53 UTC
Labels: 2-feature
