### ISSUE TITLE
Unable to view digitally signed pdf file using pdf.js

### ISSUE THREAD

**Issue by evergreen-shankar** [mozilla/pdf.js#13895] opened 2021-08-13 05:45 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 
Google Chrome Version 92.0.4515.107
- Operating system and its version: 
Windows 10
- PDF.js version: 
1.5.188
- Is a browser extension:
No

Steps to reproduce the problem:

Actually i don't want to expose file name and its path to end user, so only using btoa for the filepath and its working fine with older version of pdfjs but due to digital signed pdf just updated to latest pdfjs version. 

I am using angular js 1.x and codegniter 3.x. And below is the code i am trying to use.

View Page

`<a ng-click="openViewer()" style="cursor:pointer;">Digitally_signed.pdf</a>`

js side

```
$scope.finalurl = btoa(BASE_URL+'/pdf_files/Digitally_signed.pdf');
$scope.openViewer = function() {
    var url = BASE_URL + '/web/pdfviewer.html?file=' + $scope.finalurl;
    window.open(url, 'newwindow', config = 'height=700, width=1000, ' +
        'toolbar=no, menubar=no, scrollbars=no, resizable=no, location=no, ' +
        'directories=no, status=no');
}
```
1. Clicking on above view page link it will open Final URL as below in new window of a browser 
http://localhost:9999/mywebapp/web/pdfviewer.html?file=aHR0cDovL2xvY2FsaG9

But it gives error which is attached as screen shot here.

2. I have removed these lines from pdf.worker.js  but still same error
```
// Hide unsupported Widget signatures.
    if (data.fieldType === 'Sig') {
      warn('unimplemented annotation type: Widget signature');
      this.setFlags(AnnotationFlag.HIDDEN);
    }
```
3. I have used latest version of **pdfjs-2.9.359** then also its giving same error
What went wrong? (add screenshot)

![while_opening_digitally_signed_pdf](https://user-images.githubusercontent.com/12459663/129310024-c8edce3e-3baf-44a5-ae50-48d5bbc948f9.JPG)

In console tab of browser it prints message **_Warning: Filter "Crypt" is not supported._**

What changes do i need so that it should open the content of signed pdf file, Please suggest. Thanks in advance

**Comment by Snuffleupagus** [comment] 2021-08-13 07:52
> Attach (recommended) or Link to PDF file here:

This part of the issue template is *required* in order for any issue to be actionable and valid.

> PDF.js version: 1.5.188

That version is more than five years old and (obviously) no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I am using angular js 1.x and codegniter 3.x. And below is the code i am trying to use.

As already explained in issue #13809, we cannot help with various frameworks. Furthermore code-snippets are of no use, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> I have removed these lines from pdf.worker.js  but still same error
> [...]
> I have used latest version of **pdfjs-2.9.359** then also its giving same error
> What went wrong? (add screenshot)

If you'd actually use a *supported* release those modifications are not relevant (and they were never supported anyway).
Furthermore, the screen-shot also clearly shows an old and now (completely) unsupported version of the PDF.js demo viewer.

Closing as INCOMPLETE (or possibly even a duplicate of issue #13809).

**Closed by Snuffleupagus** 2021-08-13 07:52 UTC

**Comment by evergreen-shankar** [comment] 2021-08-17 09:34
@Snuffleupagus I have cloned the **latest version** of pdfjs from [github ](https://github.com/mozilla/pdf.js) And setup using node.js, npm and gulp and run using the url suggested in github `http://localhost:8888/web/viewer.html`, 

but getting the same error.  Please find the attachment for the same.

![image](https://user-images.githubusercontent.com/12459663/129701616-5f38e9d8-2249-46be-b35e-02541244bce3.png)
