### ISSUE TITLE
Failure to render most text when zoomed out on Chrome

### ISSUE THREAD

**Issue by messman** [mozilla/pdf.js#9049] opened 2017-10-20 15:44 UTC
_Attach or Link to PDF file here:_
[EMR-Archival-Whitepaper-Galen-Healthcare-Solutions.pdf](https://github.com/mozilla/pdf.js/files/1402448/EMR-Archival-Whitepaper-Galen-Healthcare-Solutions.pdf)

_Configuration:_
- Web browser and its version: Chrome Version 61.0.3163.100, 64-bit
- Operating system and its version: Windows 10.0.15063
- PDF.js version: 1.9.648
- Is an extension: No(?)

_Steps to reproduce the problem:_
1. Load the attached PDF in the PDF.js viewer.
2. Zoom out using the "-" button to 25%, or open at the thumbnails view.

_What is the expected behavior?_
PDF text (and first-page footer) should render even at this smaller size.
![expected](https://user-images.githubusercontent.com/5817216/31829367-04719b6a-b58b-11e7-8534-486ab533327a.png)

_What went wrong?_
PDF text on most pages (and first-page footer) are not rendered, leaving the pages mostly blank.
![actual](https://user-images.githubusercontent.com/5817216/31829476-5b7479f0-b58b-11e7-975d-a57d905ebd9c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Issue can be reproduced on the latest mozilla.github.io/pdf.js viewer.

(Also publicly available from <https://www.galenhealthcare.com/wp-content/uploads/2016/07/EMR-Archival-Whitepaper-Galen-Healthcare-Solutions.pdf>)

**Comment by timvandermeij** [comment] 2017-10-20 19:07
I cannot reproduce this using Firefox 56.0.1 (64 bit) on Arch Linux. Is it Chrome-specific or does it also happen in Firefox?

**Comment by messman** [comment] 2017-10-20 21:00
I tested on Edge 40.15063 and Firefox 56.0 (32 bit) on the same Windows 10.0.15063 and did not get this issue, so I believe it is Chrome-specific.

**Comment by timvandermeij** [comment] 2018-03-20 22:27
Closing since it looks like it's fixed in recent Chrome versions. If not, it's most likely a graphics driver issue, so try updating that or file an upstream bug in the Chrome issue tracker since it doesn't look related to PDF.js.

**Closed by timvandermeij** 2018-03-20 22:27 UTC
Labels: 4-chrome-specific, 4-triage-needed

**Comment by messman** [comment] 2018-03-21 01:40
I can confirm that this must have been fixed with some update to Chrome. Thanks all!
