### ISSUE TITLE
Vertical alignment of letters

### ISSUE THREAD

**Issue by Kubuxu** [mozilla/pdf.js#7494] opened 2016-07-18 15:12 UTC
Link to PDF file: http://gavwood.com/paper.pdf, http://mozilla.github.io/pdf.js/web/viewer.html
Configuration:
- Web browser and its version: Firefox 48.0b7
- Operating system and its version: Linux4.6.4-1-ARCH  x86_64 GNU/Linux using Infinality 
- PDF.js version: PDF Viewer 1.5.341
- Is an extension: tried both build in and as extension

Steps to reproduce the problem:
1. Open a paper, not all PDFs are affected.

What is the expected behaviour? (add screenshot)
Lines are straight.
What went wrong? (add screenshot)
![pdf js2](https://cloud.githubusercontent.com/assets/2259282/16919333/24903f12-4d01-11e6-9ae7-78b6df6c926f.jpg)
![pdf js](https://cloud.githubusercontent.com/assets/2259282/16919334/2490fcb8-4d01-11e6-9861-d009fe9dea83.jpg)

**Comment by timvandermeij** [comment] 2016-07-19 10:17
I cannot reproduce this on Arch Linux with Firefox 47.0.1 and the latest PDF.js development version. Could you test this with Firefox 47.0.1? There might be some issues in the beta version. Otherwise it might be a graphics driver issue.

**Comment by Kubuxu** [comment] 2016-07-19 10:30
For me it is present with Firefox 47.0.1 too.

**Comment by Kubuxu** [comment] 2016-07-19 10:38
Removing NVIDIA drivers resolved the issue.
Any idea how to follow it up?2

**Comment by timvandermeij** [comment] 2016-07-19 10:40
Not really. We have seen this multiple times and it appears to be a mismatch between the browser and the graphics driver. Either the driver is out of date or there is a conflict with the browser. I think the best thing to do is to report this issue at the Firefox bug tracker at https://bugzilla.mozilla.org. Since it's more a browser bug than a PDF.js bug, I'm closing the issue here. Thank you for looking into this.

**Closed by timvandermeij** 2016-07-19 10:40 UTC
Labels: 2-image-quality, 4-os-linux, 4-triage-needed

**Comment by merlinschumacher** [comment] 2016-08-30 15:48
I have the same issue with Nouveau. This is on ArchLinux with Firefox 48.0.2
![bildschirmfoto am 2016-08-30 um 17 47 00](https://cloud.githubusercontent.com/assets/7475989/18096245/d75f60ce-6ed9-11e6-9da1-48d90e6aee0f.png)

**Comment by Kubuxu** [comment] 2016-08-30 15:57
Yeah, I have the same issue all the time if I have any display driver installed, after removing nvidia's and reboot the intel one loaded (I have two GFX cards) and the issue was back.

**Comment by zhou13** [comment] 2016-09-21 03:29
I have the same problem with my Intel graphics on my archlinux.  Uninstalling the nvidia driver does NOT work for me.

**Comment by zhou13** [comment] 2016-09-21 03:36
Solution: https://bbs.archlinux.org/viewtopic.php?id=217208

Is it possible to workaround it in pdf.js since autohint should always be disabled in PDF rendering.

**Comment by merlinschumacher** [comment] 2016-09-21 08:11
The solution linked to by @zhou13 fixes it for me.
