### ISSUE TITLE
JPEG marker FFD1

### ISSUE THREAD

**Issue by photopea** [mozilla/pdf.js#11794] opened 2020-04-09 19:04 UTC
Hi, I am using your library for dcoding JPEG files. I ran into a file, which has a FFD1 marker, and it crashes the whole JPEG decoding process. Could you implement the support for this marker? It occurs in the file attached below (and all JPG viewers can open it).
![IMG_0015](https://user-images.githubusercontent.com/15955558/78931140-b6020680-7aa5-11ea-9e8b-946f49d44517.JPG)
.

**Comment by timvandermeij** [comment] 2020-04-09 21:24
There are some implementation details at https://stackoverflow.com/questions/8748671/jpeg-restart-markers. Could you provide a PDF file with such an image so we know that it can exist in a PDF file and how other viewers handle it?

**Comment by Snuffleupagus** [comment] 2020-04-09 21:39
> I ran into a file, which has a FFD1 marker, and it crashes the whole JPEG decoding process. Could you implement the support for this marker?

The assumption seem to be that Restart markers are not supported in `src/core/jpg.js`, but if that actually were the case then we'd not be able to decode most (or any?) JPEG images; please see the existing code (part of the MCU decoding): https://github.com/mozilla/pdf.js/blob/12aba0f91a5cd3e36fa81cb799540f8073990831/src/core/jpg.js#L448-L453

The problem is much more likely that this particular JPEG image is *corrupt* in one way or another, and as mentioned above debugging would be easier with a PDF file containing the JPEG image.
(Also, please remember to fill out the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue.)

**Comment by automatedbugreportingfacility** [comment] 2020-04-10 00:24
Here's a PDF file with the JPEG image: [test.pdf](https://github.com/mozilla/pdf.js/files/4459214/test.pdf) -- it displays blank in pdf.js and works in PDFium.

**Comment by timvandermeij** [comment] 2020-04-15 22:09
Fixed by the PR above.

**Closed** 2020-04-15 22:08 UTC
Labels: 4-image-jpeg

**Comment by photopea** [comment] 2020-04-27 17:09
Could you also update these? https://github.com/mozilla/pdfjs-dist/tree/master/image_decoders

**Comment by timvandermeij** [comment] 2020-04-28 21:13
`pdfjs-dist` will be updated automatically when the next release is made.
