### ISSUE TITLE
Glyph spacing is incorrect in Safari

### ISSUE THREAD

**Issue by rijk** [mozilla/pdf.js#8852] opened 2017-08-31 10:17 UTC
Link to PDF file: https://s3.eu-central-1.amazonaws.com/s3.envoy.rocks/uniti/sitomeca/algemene-voorwaarden/BBCtqc_Sitomeca+GTCs+v1.2.pdf

Configuration:
- Web browser and its version: Safari Version 10.1.2 (12603.3.8)
- Operating system and its version: OS X 10.12.6
- PDF.js version: pdfjs-dist@1.9.491 
- Is an extension: no

What is the expected behavior? (screenshot from Chrome)

<img width="457" alt="screen shot 2017-08-31 at 12 16 22" src="https://user-images.githubusercontent.com/159500/29918597-441dc516-8e46-11e7-9ec4-9032e889c358.png">

What went wrong? (screenshot from Safari)

<img width="465" alt="screen shot 2017-08-31 at 12 16 33" src="https://user-images.githubusercontent.com/159500/29918606-49b3630a-8e46-11e7-9f0f-da4e5939e23d.png">

**Comment by Snuffleupagus** [comment] 2017-08-31 10:30
Closing as duplicate of #8231 (and a multitude of other issues referenced there).

**Closed by Snuffleupagus** 2017-08-31 10:30 UTC
