### ISSUE TITLE
Pdfjs find controller search issue

### ISSUE THREAD

**Issue by manojmanic** [mozilla/pdf.js#12565] opened 2020-11-03 08:17 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

**Working Angular 6**

searchQuery(newQuery: string, frompage) {
this.pdfComponent.pdfFindController.executeCommand('find', {
caseSensitive: false,
findPrevious: undefined,
highlightAll: true,
phraseSearch: true,
query: ''alubmin'',
});
}

My pdf size is - 59.5MB

Pages - 1203

When I call the searchQuery() for the first time and parallelly load pdf rendering the highlighted text taken a minimum of 1 minute.

What is the reason?

The below screenshot when I search a query as **alubmin** but on that page, there is no highlighted text like that.

After pdf fully download 59.5 MB then will take 1 minute after that the word **alubmin** highlighted.

![search](https://user-images.githubusercontent.com/23070512/97962363-0393e700-1ddb-11eb-8f39-1d6d79f52f9b.png)

**Comment by manojmanic** [comment] 2020-11-03 08:18
Please give anyone Solution for the above issue?

The Question is not get let me know?

**Comment by Snuffleupagus** [comment] 2020-11-03 09:37
> Attach (recommended) or Link to PDF file here:
>
>Configuration:
> - Web browser and its version:
> - Operating system and its version:
> - PDF.js version:
> - Is a browser extension:

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md (including *clear* and *concise* steps to reproduce the issue); as-is this issue unfortunately isn't actionable/valid and will be closed as INVALID.

> Working Angular 6

We don't know anything about "Angular 6" here, and consequently we cannot help with that.

> searchQuery(newQuery: string, frompage) {
> this.pdfComponent.pdfFindController.executeCommand('find', {
> caseSensitive: false,
> findPrevious: undefined,
> highlightAll: true,
> phraseSearch: true,
> query: ''alubmin'',
> });
> }

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> My pdf size is - 59.5MB
> Pages - 1203

That's a lot of data, and it's not reasonable to expect that all of it could be parsed *immediately*.

---

All-in-all, this issue is missing all of the information required to be valid and it's also somewhat difficult to even understand what (if any) the problem is here.

**Comment by manojmanic** [comment] 2020-11-03 10:06
@Snuffleupagus ok.thanks for your reply. let me know in **pdfjs-dist** up to how much amount of data size support?

Tel me the pdf size I will be restricted in my application.

Because small size pdf has highlighted my search query immediately but large size pdf file to much amount of time
taken for my search query to highlight the text.

**Comment by Snuffleupagus** [comment] 2020-11-03 10:24
> let me know in **pdfjs-dist** up to how much amount of data size support?

There's no particular restrictions in the PDF.js library; hence performance is simply limited by the speed of your computer.

> Because small size pdf has highlighted my search query immediately but large size pdf file to much amount of time
taken for my search query to highlight the text.

It *should* hopefully be obvious that larger PDF files takes longer to parse than smaller files, however if you don't provide *any* of the requested data (such that the issue is easily actionable) it's simply *impossible* for anyone to assist further!

(Also, the screen-shot in https://github.com/mozilla/pdf.js/issues/12565#issue-735113419 doesn't show the default viewer, hence there could e.g. be bugs in your viewer.)

**Comment by manojmanic** [comment] 2020-11-03 10:34
@Snuffleupagus I am using ng2-pdf-viewer

I am using **pdfjs-dist** is the dependency file for **ng2-pdf-viewer**

Is That any option to give the solution in the **pdfjs-dist** directory?

**Comment by Snuffleupagus** [comment] 2020-11-03 10:51
> I am using ng2-pdf-viewer

That's a completely *different* project, which we know nothing about here and consequently cannot provide support for.
Unless you can reproduce the problem using the PDF.js library *directly*, without another library on top of it, it's unfortunately not possible for anyone here to really help.

Finally, you've still not provided *any* of the information required for this issue to be actionable/valid; please read through https://github.com/mozilla/pdf.js/issues/12565#issuecomment-721006544 carefully.

**Closed** 2020-11-03 20:22 UTC
