### ISSUE TITLE
Cannot set property hasCanvasTypedArrays of [object Object] which has only a getter

### ISSUE THREAD

**Issue by vincent-cm** [mozilla/pdf.js#8679] opened 2017-07-20 11:17 UTC
This issue only exist to npm repository. If build by myself with gulp dist, the error gone.
The pdfjs-dist are used in node_module as a reference by another angular 2 module ng2-pdf-viewer. So build by myself is a workaround but it needs the test pdf file to be exist in root folder. 

So Following error is to directly download from npm install pdfjs-dist

Uncaught TypeError: Cannot set property hasCanvasTypedArrays of [object Object] which has only a getter
at Object._typeof2 (main.bundle.js:319943)
at w_pdfjs_require (main.bundle.js:291266)
at Object._typeof (main.bundle.js:338481)
at w_pdfjs_require (main.bundle.js:291266)
at Object.defineProperty.value (main.bundle.js:291312)
at main.bundle.js:291315
at webpackUniversalModuleDefinition (main.bundle.js:291239)
at Object.<anonymous> (main.bundle.js:291246)
at Object.exports.byteLength (main.bundle.js:340040)
at webpack_require (main.bundle.js:51)
at Object.<anonymous> (main.bundle.js:291021)
at webpack_require (main.bundle.js:51)
at Object.defineProperty.value (main.bundle.js:291009)
at webpack_require (main.bundle.js:51)
at Object.<anonymous> (main.bundle.js:182289)
at webpack_require (main.bundle.js:51)
at Object.<anonymous> (main.bundle.js:172933)
at webpack_require (main.bundle.js:51)
at Object.<anonymous> (main.bundle.js:172879)
at webpack_require (main.bundle.js:51)
at Object.<anonymous> (main.bundle.js:144683)
at webpack_require (main.bundle.js:51)
at Object.defineProperty.value (main.bundle.js:144671)
at webpack_require (main.bundle.js:51)
at Object.defineProperty.value (main.bundle.js:146)
at main.bundle.js:149

**Comment by yurydelendik** [comment] 2017-07-20 13:46
Unable to reproduce (due to absence of STR). Closing as incomplete.

**Closed by yurydelendik** 2017-07-20 13:46 UTC

**Comment by Rushikesh12792** [comment] 2017-11-07 06:49
I am also having the same issue.

**Comment by wangzpjava** [comment] 2018-08-23 01:34
Is this problem solved? I also encountered the same problem.
