### ISSUE TITLE
Directly open attached files

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#17274] opened 2023-11-13 13:22 UTC
Attach (recommended) or Link to PDF file here:
https://www.grafton-ma.gov/DocumentCenter/View/10871/Exhibit-31---Comment-Tammy-Kalinowski-Board-of-Assessors-November-9-2023

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

Steps to reproduce the problem:
1. Open the pdf 
2. The displayed page invites the user to download a software
3. It isn't obvious that the contents are in the attachments.

When I open the pdf in either Acrobat or in Foxit, the attachment (i.e. `58 Follette Street.pdf`) is opened.
Since the displayed page is a kind of advertisement I think it's fine to not render it but it could be something more useful.
@Snuffleupagus would you know if there is a flag somewhere allowing us to directly display the attachment ?

**Comment by Snuffleupagus** [comment] 2023-11-13 13:39
> It isn't obvious that the contents are in the attachments.

The sidebar does open automatically, at the Attachments-view (since the PDF document has `PageMode = /UseAttachments`), which should provide at least some indication here.

> Since the displayed page is a kind of advertisement I think it's fine to not render it but it could be something more useful.

Yes, the problem is that in the general case that's probably difficult (or even impossible) to know.
Not to mention that there could be any number of attached documents, and none of them need to be a PDF document.

> would you know if there is a flag somewhere allowing us to directly display the attachment ?

Not really, unless you want to add "proper" support for the `Collections` feature; see https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#M11.9.39646.2Heading.824.Collections

---

Duplicate of #4282

**Closed by Snuffleupagus** 2023-11-13 13:39 UTC
