### ISSUE TITLE
Selection end becomes the start of page when not directly over text

### ISSUE THREAD

**Issue by scrapmac** [mozilla/pdf.js#2542] opened 2013-01-10 10:29 UTC
open any pdf and start selecting some text.
Until you are directly over text while dragging your mouse, the selection will have proper starting and ending. As soon as you move over some empty space , say space between two paragraphs that you want to select, the selection's end point will shift to the start of the page.

My hunch is that when you are not over any text, and you convert the mouse coordinates to text offset, it returns -1, so the selection end goes to offset -1, or 0, that is the start of the page. If this is the issue, we should probably fallback to the previously used selection end offset in such cases.

**Comment by timvandermeij** [comment] 2015-11-05 21:41
I cannot reproduce this anymore with the latest viewer at https://mozilla.github.io/pdf.js/web/viewer.html. This has likely been addressed by #6591. Closing as fixed.

**Closed by timvandermeij** 2015-11-05 21:41 UTC
Labels: 4-text-selection
