### ISSUE TITLE
firefox open this pdf file has wrong with picture in the file

### ISSUE THREAD

**Issue by wowplayer01** [mozilla/pdf.js#12579] opened 2020-11-05 06:12 UTC
Attach (recommended) or Link to PDF file here:
[（3）2020年中心组学习记录情况资料(1).pdf](https://github.com/mozilla/pdf.js/files/5492304/3.2020.1.pdf)

Configuration:
- Web browser and its version:  firefox  82.0.2
- Operating system and its version: windows 10
- PDF.js version: 2.0
- Is a browser extension: 

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
![Dingtalk_20201105142744](https://user-images.githubusercontent.com/42967421/98205437-222ce600-1f73-11eb-8aa0-dabe8d7aa4af.jpg)

![Dingtalk_20201105141020](https://user-images.githubusercontent.com/42967421/98204294-b9dd0500-1f70-11eb-93ee-1f25e6201918.jpg)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by SamyCookie** [comment] 2020-11-05 09:46
seems to be a duplicate of #11957

**Closed** 2020-11-05 21:07 UTC
