### ISSUE TITLE
Render pdf to fixed size?

### ISSUE THREAD

**Issue by Glinkis** [mozilla/pdf.js#9973] opened 2018-08-09 14:47 UTC
I'm currently writing an [Electron app](https://github.com/Glinkis/reverse-image-finder), which needs to get the `rgba` pixel data from PDF files.
Now the below code I have is working fine, but I was wondering if it's possible to render the pdf to a specific size?

This would probably(?) make processing large PDF files faster, as I only need `64x64`worth of pixel data.

```js
const create2dContext = (width, height) => {
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  return canvas.getContext("2d");
};

const decodePdf = async (imagePath) => {
  const pdf = await PDFJS.getDocument(imagePath);
  const page = await pdf.getPage(1);

  const viewport = page.getViewport(1);
  const { width, height } = viewport;

  const canvasContext = create2dContext(width, height);
  await page.render({ canvasContext, viewport });

  return canvasContext.getImageData(0, 0, width, height);
};
```

**Comment by Snuffleupagus** [comment] 2018-08-09 19:55
Looks (basically) like a duplicate of issue #7464.

**Comment by timvandermeij** [comment] 2018-08-09 20:27
Closing since this also looks like a duplicate to me. Please refer to https://github.com/mozilla/pdf.js/issues/7464#issuecomment-230338167.

**Closed by timvandermeij** 2018-08-09 20:27 UTC

**Comment by Glinkis** [comment] 2018-08-09 21:09
I don't think it's a duplicate. I don't want to crop the image, but rather render the whole image to a smaller area.

**Comment by Snuffleupagus** [comment] 2018-08-09 22:08
Did you try just setting the canvas size to whatever you want/need, and then simply using that when rendering?
That's (basically) how the thumbnails work in the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html), so it should just work.

**Comment by Glinkis** [comment] 2018-08-10 06:32
That doesn't seem to work, no.
It doesn't scale the image, but rather just render the image of the original size in whatever room there is on the canvas.

Meaning, if I render a 32x32px pdf to a 64x64px canvas, it only render to the top left quadrant of the canvas.

And if I render a 128x128px pdf to a 64x64px canvas, it only renders a quadrant of the pdf into the canvas.

**Comment by Snuffleupagus** [comment] 2018-08-10 08:09
You'll obviously need to resize the viewport as well; look at how a thumbnail canvas size is set in
https://github.com/mozilla/pdf.js/blob/309b6f820e5250e6290f1fb986c7c92f7a1431cd/web/pdf_thumbnail_view.js#L106-L112
and how the scale of the viewport is then changed in
https://github.com/mozilla/pdf.js/blob/309b6f820e5250e6290f1fb986c7c92f7a1431cd/web/pdf_thumbnail_view.js#L316
before rendering is triggered in
https://github.com/mozilla/pdf.js/blob/309b6f820e5250e6290f1fb986c7c92f7a1431cd/web/pdf_thumbnail_view.js#L329-L333

**Comment by Snuffleupagus** [comment] 2018-08-11 12:08
> Although it will always be the same aspect ratio as the PDF, while what I want is the image to be distorted to the specific size of exactly 64x64.

You could perhaps try and manually distort the canvas *after* rendering is done, to achieve the desired effect, however I don't know if it'll work. Another possible approach may be to manually set the width/height of the `viewport` before rendering, but again that might not work too well.
(It seems that your use-case is perhaps one that the PDF format itself doesn't easily lend itself to.) 

> Also, I am wondering if this will improve performance or not.
> Is it actually faster to render to a smaller canvas?

While using a smaller canvases does reduce *memory* usage, it probably won't improve general performance in any other way though. Keep in mind that the entire page (of the PDF file) still needs to be parsed, regardless of the output size, and that all the rendering operations still need to be executed.

**Comment by Glinkis** [comment] 2018-08-11 12:14
My [solution](https://github.com/Glinkis/reverse-image-finder/blob/master/src/decoders/decodePdf.ts) is currently to scale the smallest axis down to 64, and then scale the other one proportionally.

And then I squish the image at a later stage. This is a decent tradeoff, and certainly saves some memory compared to previously.
