### ISSUE TITLE
Double-click to select a word at start/end of line also selects adjacent word on previous/next line

### ISSUE THREAD

**Issue by hubgit** [mozilla/pdf.js#9341] opened 2018-01-05 11:09 UTC
## Steps to reproduce the problem:
1. Open [the demo PDF viewer](https://mozilla.github.io/pdf.js/web/viewer.html).
2. Double-click a non-hyphenated word at the start or end of a line to select it.

## What is the expected behavior?

Only the double-clicked word should be selected.

## What went wrong?

Adjacent words on the previous/next lines are also included in the selection.

![pdfjs-word-selection](https://user-images.githubusercontent.com/14294/34606843-daab8650-f208-11e7-8fed-400567da16a2.gif)

---

This is the same issue described in #8408 but it's not specific to double-column PDFs (see [a single-column example](https://zenodo-review.now.sh/1120265)), and is probably the same as the issue described in #6678.

The issue is present in Chrome and Safari, but not Firefox.

---

## Configuration

- Web browser and its version:
Chrome v63

- Operating system and its version:
macOS 10.13

- PDF.js version:
Latest

- Is a browser extension:
No

**Comment by Snuffleupagus** [comment] 2018-01-05 11:51
> This is the same issue described in #8408 but it's not specific to double-column PDFs (see a single-column example), and is probably the same as the issue described in #6678.

Closing as duplicate of the aforementioned issues.

**Closed by Snuffleupagus** 2018-01-05 11:51 UTC
