### ISSUE TITLE
Rendering of text rendering mode example doesn't progress

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6301] opened 2015-08-01 19:02 UTC
http://www.tcpdf.org/examples/example_026.pdf
Only the first three lines are rendered, the progress animation keeps running.

The file shows the effects of the text rendering mode operator (Tr).

**Comment by Snuffleupagus** [comment] 2015-08-02 08:27
Closing as duplicate of issue #4244.

**Closed by Snuffleupagus** 2015-08-02 08:27 UTC
