### ISSUE TITLE
differenece in picture quality in PDF.JS before printing in viewer and after print

### ISSUE THREAD

**Issue by ArjunPatil** [mozilla/pdf.js#6521] opened 2015-10-12 08:44 UTC
differenece in picture quality in PDF.JS before printing in viewer and after print in print preview of chrome.

Also print quality degrades with system configuration degraded form core i5,i3 to dual core.

i am attaching screen shots of same copy before print and after print.

Before print  in Pdf.js viewer:
![dms_2015-10-12_13-8-42_no-00](https://cloud.githubusercontent.com/assets/12855547/10424250/4d697dc4-70eb-11e5-9078-c338e90d0de5.jpg)

After taking print:
![dms_2015-10-12_13-10-3_no-00](https://cloud.githubusercontent.com/assets/12855547/10424249/4d635d36-70eb-11e5-8ae1-3832f7e60680.jpg)

**Comment by ArjunPatil** [comment] 2015-10-12 08:51
This issue solved by changing code in Viewer.js file but problrm still persistent with variety of system configuration as Windows 7, windows XP or also hardware configuration as differnt processor and motherboard driver.

Code changed by me.	beforePrint: function PDFPageView_beforePrint() {
				var pdfPage = this.pdfPage;
				
				var viewport = pdfPage.getViewport(2);
				// Use the same hack we use for high dpi displays for printing to get
				// better output until bug 811002 is fixed in FF.
				console.log('vp: wt='+viewport.width+' ht='+viewport.height);
				var PRINT_OUTPUT_SCALE =2;
				
				var canvas = document.createElement('canvas');
				canvas.width = Math.floor(viewport.width) * PRINT_OUTPUT_SCALE;
				canvas.height = Math.floor(viewport.height)* PRINT_OUTPUT_SCALE;
				
				 // The rendered size of the canvas, relative to the size of canvasWrapper.
				//canvas.style.width = (PRINT_OUTPUT_SCALE * Math.floor(viewport.width)) + 'px';
				//canvas.style.height = (PRINT_OUTPUT_SCALE * Math.floor(viewport.height)) + 'px';
				canvas.style.width = (PRINT_OUTPUT_SCALE * 100)+'%';
				canvas.style.height = (PRINT_OUTPUT_SCALE * 100)+'%';
		
				
			var cssScale = 'scale(' + (1 / PRINT_OUTPUT_SCALE) + ', ' +	(1 / PRINT_OUTPUT_SCALE) + ')';
			/*if(viewport.height>1700 || viewport.width>1200 ){
				cssScale = 'scale(' + (0.5) + ', ' +	(0.5) + ')';
			}*/
			
			//var cssScale = 'scale(' + (1) + ', ' +	(1) + ')';
									//width				//height	
			CustomStyle.setProp('transform' , canvas, cssScale);
			CustomStyle.setProp('transformOrigin' , canvas, '0% 0%');

				var printContainer = document.getElementById('printContainer');
				var canvasWrapper = document.createElement('div');
				if(viewport.width<viewport.height){ //for portrait paper
					
					canvasWrapper.style.width = (Math.floor(viewport.width)/PRINT_OUTPUT_SCALE) + 'pt';
					canvasWrapper.style.height = (Math.floor(viewport.height)/PRINT_OUTPUT_SCALE+30) + 'pt'; //plus 30
					if(viewport.height>1700  ){ //for if height is greter than standard height
						var temp=((viewport.height-1700)/PRINT_OUTPUT_SCALE-30);        //minus 50
						canvasWrapper.style.height = (Math.floor(viewport.height)/PRINT_OUTPUT_SCALE-temp) + 'pt';
					}
					if(viewport.height<1650  ){ //for if height is less than standard height
						var temp=((1650-viewport.height)/PRINT_OUTPUT_SCALE)+30;        //plus 30
						canvasWrapper.style.height = (Math.floor(viewport.height)/PRINT_OUTPUT_SCALE+temp) + 'pt'; //plus temp
					}
				}else{ //for landscape paper
					canvasWrapper.style.width = (Math.floor(viewport.width)/PRINT_OUTPUT_SCALE) + 'pt';
					canvasWrapper.style.height = (Math.floor(viewport.height)/PRINT_OUTPUT_SCALE) + 'pt';
				}
				
				canvasWrapper.style.pageBreakAfter = 'always';
				canvasWrapper.appendChild(canvas);
			
				printContainer.appendChild(canvasWrapper);

				canvas.mozPrintCallback = function(obj) {
					var ctx = obj.context;

					ctx.save();
					ctx.fillStyle = 'rgb(255, 255, 255)';
					ctx.fillRect(0, 0, canvas.width, canvas.height);
					ctx.restore();
					ctx.scale(PRINT_OUTPUT_SCALE, PRINT_OUTPUT_SCALE);

					var renderContext = {
							canvasContext: ctx,
							viewport: viewport,
							intent: 'print'
					};

					pdfPage.render(renderContext).promise.then(function() {
						// Tell the printEngine that rendering this canvas/page has finished.
						obj.done();
					}, function(error) {
						console.error(error);
						// Tell the printEngine that rendering this canvas/page has failed.
						// This will make the print proces stop.
						if ('abort' in obj) {
							obj.abort();
						} else {
							obj.done();
						}
.
.
.
.
If there is any other solution or change to improve quality please suggest me.

**Comment by timvandermeij** [comment] 2015-10-12 12:29
Closing as duplicate of #6513. Please don't open multiple issues for the same problem.

**Closed by timvandermeij** 2015-10-12 12:29 UTC
