### ISSUE TITLE
Printing on Android device

### ISSUE THREAD

**Issue by gigaga** [mozilla/pdf.js#7104] opened 2016-03-23 10:59 UTC
Hello,

Actually, the printing feature from Android device seems to be not usable. Indeed, if i try to launch a printing from my device when viewer is displayed in iframe, not only the pdf content is sent to the printer but the entire window (with window parent content):
https://jsfiddle.net/300gykh9/
There is a possibility to be usable?

Thx

**Comment by timvandermeij** [comment] 2016-10-11 19:46
Closing as duplicate of #7599.

**Closed by timvandermeij** 2016-10-11 19:46 UTC
Labels: 4-os-android, 4-printing
