### ISSUE TITLE
some annotations appear to have a rectangle entry that covers most of the page

### ISSUE THREAD

**Issue by a7vickey** [mozilla/pdf.js#11704] opened 2020-03-17 06:54 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 74
- Operating system and its version: 8.1 
- PDF.js version:2.0
- Is a browser extension:

Steps to reproduce the problem:
1. some annotations appear entire cover page. we cant able to access rest other annotation. 
2. Annotation pop layer overflow other annotation layer 

What is the expected behavior? Page 5 

What went wrong? Page 6 we can access only one annotation. rest of other hide.

[sample.pdf](https://github.com/mozilla/pdf.js/files/4341876/sample.pdf)

**Comment by a7vickey** [comment] 2020-03-17 06:56
Need solution if your already resolve this issue please provide source code.  All annotation pop render wrong   position. please check page 6.

**Comment by Snuffleupagus** [comment] 2020-03-17 09:05
**This is your one and only warning to ***stop spamming*** the bug tracking with duplicate issues!**
**If you continue doing this, your account will most likely be blocked!**

Duplicate of #11286

**Closed** 2020-03-17 21:25 UTC

**Comment by a7vickey** [comment] 2020-03-18 05:37
your people not resolving the issue without resolving issue how is bug is closed Snuffleupagus Are You mad dont have seance

**Comment by Snuffleupagus** [comment] 2020-03-18 08:54
@timvandermeij Can you please block that user, and also remove the latest round of spam that were posted to numerous issues; thank you!

**Comment by timvandermeij** [comment] 2020-03-18 21:37
I have removed all comments and reported the user to GitHub.
