### ISSUE TITLE
infoDict.has is not a function // undefined is not a function

### ISSUE THREAD

**Issue by ochsusd** [mozilla/pdf.js#5824] opened 2015-03-10 14:58 UTC
PDF files generated via a certain book scanner can not be displayed in owncloud 7.0.4 (stable).
A sample file will be prepared and sent to me soon.

Product: 	book2net
Component: 	tocosa
Version: 	5.84 (tocosa) 

All 3 browsers are affected but with different error messages:

Mozilla FireFox 36.0.1
Internet Explorer 11.0.9600.17631
Internet Explorer Updateversion 11.0.16
Chrome Version 40.0.2214.115 m

after clicking on that file start  all 3 error messages start with:

///////////////////////////////////////////////////////
[Could not load PDF file]
PDF.js v0.8.1136 (build: ca612e5)
///////////////////////////////////////////////////////

followed by:

[1] Mozilla Firefox - Message: infoDict.has is not a function
[2] Internet Explorer - Message: Object doesn't support property or method "has"
[3] Google Chrome - Message: undefined is not a function

PDF document properties are: PDF Version 1.6 (Acrobat 7.x)

Adobe Acrobat xmp output for the PDF file:

<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
xmlns:xmp="http://ns.adobe.com/xap/1.0/"
xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:pdf="http://ns.adobe.com/pdf/1.3/">
xmp:CreateDate2015-03-05T22:01:26+01:00/xmp:CreateDate
xmp:ModifyDate2015-03-05T22:01:26+01:00/xmp:ModifyDate
xmp:CreatorToolBGD-PDF Library Ver. 3.4/xmp:CreatorTool
dc:formatapplication/pdf/dc:format
pdf:ProducerBusiness Graphics Datentechnik GmbH/pdf:Producer
/rdf:Description
/rdf:RDF
/x:xmpmeta
<?xpacket end="w"?>

**Comment by yurydelendik** [comment] 2015-03-10 15:07
Could you provide a link to a sample PDF that generates this kind of error?

**Comment by yurydelendik** [comment] 2015-03-10 15:21
Closing as duplicate of #5825

**Closed by yurydelendik** 2015-03-10 15:21 UTC
