### ISSUE TITLE
Unknown IR type: 0.517647

### ISSUE THREAD

**Issue by mdesn** [mozilla/pdf.js#10785] opened 2019-05-02 19:44 UTC
I get the following error when opening a specific PDF using the default hosted viewer (https://mozilla.github.io/pdf.js/web/viewer.html). Unfortunately I can't share the PDF because it's a personal invoice of one of our customers.

![image](https://user-images.githubusercontent.com/50217150/57101973-6a20dc00-6cf0-11e9-918b-9dbf3b299c27.png)

![image](https://user-images.githubusercontent.com/50217150/57102072-989eb700-6cf0-11e9-86dc-43a465043529.png)

**Comment by timvandermeij** [comment] 2019-05-02 19:53
Closing since we can't help without a PDF file. If you can provide a non-confidential file (i.e., one generated by the same PDF generator that also has the problem) and you can provide it, we can reopen this.

**Closed by timvandermeij** 2019-05-02 19:53 UTC

**Comment by mdesn** [comment] 2019-05-02 20:10
Is there some way that I could provide the confidential file without making it public in this issue?

**Comment by Snuffleupagus** [comment] 2019-05-03 20:14
The general principle in this bug tracker is usually to require publicly available test-cases, and the reasons for this are twofold:
 1. To make it possible for any contributor to attempt to help debug and/or fix the issue.
 2. To ensure that a PR fixing a particular issue will always contain a regression test, since that's essentially a requirement for the patch being accepted. (Without tests there's nothing stopping the same bug from occurring again, which leads to a lot of wasted time for everyone involved.)
