### ISSUE TITLE
PDF form checkboxes - adjust offset settings for some files

### ISSUE THREAD

**Issue by cfogelSV** [mozilla/pdf.js#12311] opened 2020-09-01 10:30 UTC
**Affected versions**
* 81.0b4, 82.0a1(2020-08-30);

**Affected platforms**
* Windows 10, macOS 10.15

**Steps to reproduce**
1. Launch Firefox, access http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf
2. Zoom in a bit;
3. Click on any checkbox;

**Expected result**
* checkbox is properly displayed;

**Actual result**
* purple color is offset from top by a few pixels;

**Regression range**
* not a regression

**Additional notes**
* S4 as suggested severity since this particular issue is not that visible;
* attached screenshot to illustrate the issue:
<img width="480" alt="Screenshot 2020-09-01 at 13 07 49" src="https://user-images.githubusercontent.com/49230899/91837759-1e1fd780-ec55-11ea-9656-efa7eb52318e.png">

**Comment by Snuffleupagus** [comment] 2020-09-01 10:48
This looks, for all intents and purposes, like a duplicate of #12239.
(Based on the fact that both issues seem connected to CSS-only zooming.)

**Comment by Snuffleupagus** [comment] 2021-02-04 11:34
Duplicate of #12239

**Closed** 2021-02-04 22:53 UTC
Labels: 1-viewer, 4-form-acroform
