### ISSUE TITLE
DIgital Signature not visible in my custom pdfjs viewer

### ISSUE THREAD

**Issue by bikramnayak** [mozilla/pdf.js#10825] opened 2019-05-16 05:54 UTC
Hi,

I have created a pdf viewer using pdfjs and there is requirement of showing digital signatures in the pdf as well as in a separate signature panel so is there any provision provided in pdfjs

can any one guide me to achieve this things.

Attach (recommended) or Link to PDF file here:
[blank_signed.pdf](https://github.com/mozilla/pdf.js/files/3185564/blank_signed.pdf)

Configuration:
- Web browser and its version: Google Chrome 74.0.3729.131 
- Operating system and its version: WIndows 10 
- PDF.js version: 2.0.943
- Is a browser extension:

Steps to reproduce the problem:
1. Upload any digitally signed pdf

What is the expected behavior? (add screenshot)
Digital signature should display

What went wrong? (add screenshot)
Signature is not getting displayed in the viewer

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by llo-dia** [comment] 2019-05-16 07:37
See [this issue](https://github.com/mozilla/pdf.js/issues/10507).

**Comment by bikramnayak** [comment] 2019-05-16 09:40
I have already commented few lines in annotation.js and able to see the signature but if I take update then that will be lost, so can you please tell if there is any flag which can be passed and will do the same work for me?

Actually I have created the viewer in an Angular application.

**Comment by llo-dia** [comment] 2019-05-16 09:46
> I have already commented few lines in annotation.js and able to see the signature but if I take update then that will be lost, so can you please tell if there is any flag which can be passed and will do the same work for me?

Currently there is no support for digital signatures in pdf.js and no flag or setting exists.
See issue #1076

**Comment by timvandermeij** [comment] 2019-05-16 19:20
Closing since this is a duplicate of that issue.

**Closed by timvandermeij** 2019-05-16 19:20 UTC

**Comment by bikramnayak** [comment] 2019-05-20 05:30
Hi, Is there any way to get the signature content of the page like we are getting text content?
I have to show the signatures in a different canvas or div can you please guide me to achieve this.
