### ISSUE TITLE
Horizontal lines displayed on certain pages of a PDF

### ISSUE THREAD

**Issue by pdfhandler** [mozilla/pdf.js#10612] opened 2019-03-04 12:13 UTC
Attach (recommended) or Link to PDF file here:

[HorizontalLines2.pdf](https://github.com/mozilla/pdf.js/files/2926264/HorizontalLines2.pdf)
[HorizontalLines1.pdf](https://github.com/mozilla/pdf.js/files/2926265/HorizontalLines1.pdf)

I think this is the same issue as "Horizontal lines displayed on certain pages of a PDF #6851". 

Configuration:
- Web browser and its version:  Chrome 71.0.3578.98, Firefox 65.0.1, IE 11.0.9600.19266
- Operating system and its version: Windows 7
- PDF.js version: 2.1.97
PDF 9f4e5a2ca6264a4aa8d9f3558f9b509e [1.6 Acrobat Distiller 9.3.3 (Windows) / PScript5.dll Version 5.2.2] (PDF.js: 2.1.97)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF

What is the expected behavior? (add screenshot)
The document displays without horizontal lines across the page

![image](https://user-images.githubusercontent.com/42236192/53732671-95b15280-3e76-11e9-9843-7ba2835ef4d2.png)

What went wrong? (add screenshot)
Horizontal lines are displayed

![image](https://user-images.githubusercontent.com/42236192/53732723-b8dc0200-3e76-11e9-903b-9a080e35ad7a.png)

****
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-03-04 12:23
Duplicate of issue #7837.

**Closed** 2019-03-04 23:19 UTC
