### ISSUE TITLE
Free Text Editor will Lose the First Line on Save when Adding more than One Lines by Enter Key

### ISSUE THREAD

**Issue by Ztong55** [mozilla/pdf.js#17468] opened 2023-12-28 08:40 UTC
**THIS DOES NOT HAPPEN IN FIREFOX WEB BROWSER**

Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 120.0.6099.130 (Official Build) (64-bit)
- PDF.js version: v4.0.269
- Is a browser extension: No

Steps to reproduce the problem:
1. Open a viewer to view an example PDF file.
2. Use free text to add some text with two or more lines.
3. Save the PDF file and reopen it using any PDF viewer.

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/149151442/f85107b9-aeea-4525-adc2-412f679d3098)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/149151442/7c971879-654c-4604-acb2-83b19c387f04)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by Snuffleupagus** [comment] 2023-12-28 08:44
Duplicate of #17079

**Closed by Snuffleupagus** 2023-12-28 08:44 UTC
