### ISSUE TITLE
PDF Text not rendering properly

### ISSUE THREAD

**Issue by ms3534** [mozilla/pdf.js#15669] opened 2022-11-07 11:19 UTC
Attach (recommended) or Link to PDF file here:
[Faulty PDF.pdf](https://github.com/mozilla/pdf.js/files/9950874/Faulty.PDF.pdf)

Configuration:
- Web browser and its version:
Chrom Version 106.0.5249.120 
Firefox Version 106.0.5 (64 bit)

- Operating system and its version:
- Windows 10

- PDF.js version: 2.1.5

Steps to reproduce the problem:
1. Open the attached PDF in Chrome & Firefox with URL https://mozilla.github.io/pdf.js/web/viewer.html
2. Adjust the zoom level to 75%
3. Notice the pdf rendering in both the browsers, in chrome its blurry

What is the expected behavior? (add screenshot)
It needs to render properly as incase of Firefox

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2022-11-07 11:23
> PDF.js version: 2.1.5

That's not an official release; please find the latest (supported) releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

Duplicate of #14641

**Closed by Snuffleupagus** 2022-11-07 11:23 UTC
