### ISSUE TITLE
Find cannot be used by either keyboard or mouse when browser zoom is used

### ISSUE THREAD

**Issue by Thunderforge** [mozilla/pdf.js#6259] opened 2015-07-23 15:36 UTC
In viewer.js, if you increase your browser zoom level (a common action for those with visual impairments), the find functionality becomes completely inaccessible via either keyboard or mouse. To reproduce:

<ol start="1">
<li>Go to the [PDF.js](http://mozilla.github.io/pdf.js/web/viewer.html) demo in any browser</li>
<li>Note that you can access find either by clicking on the magnifying glass icon, tabbing to the element, or by using a keyboard shortcut (Control + F on Windows)</li>
</ol>

![image](https://cloud.githubusercontent.com/assets/6200170/8854376/3a37e8cc-3125-11e5-99fa-23004bb945b0.png)

<ol start="3">
<li>Increase the browser-level zoom (not the PDF-level zoom) several levels. Note that buttons such as Print and Download disappear from the toolbar and are moved to the sidebar.</li>
<li>Continue increasing the browser-level zoom and notice that eventually magnifying glass find icon disappears and obviously cannot be . Also notice that the find keyboard shortcut (Control + F on Windows) no longer works within the PDF (make sure the PDF has focus so that you aren't confusing it with the browser-level find command).</li>
</ol>

![image](https://cloud.githubusercontent.com/assets/6200170/8854582/2ecc6c1e-3126-11e5-9395-6ea3f0a5feb5.png)

While other functions such as printing and downloading files can still be accessed through either a mouse, tabbing to the element, or keyboard shortcuts, the find functionality is completely inaccessible when the user has increased the zoom on their browser. This needs to be possible. As is, visually impaired users who increase their browser-level zoom cannot use the find command in viewer.js.

**Comment by timvandermeij** [comment] 2015-07-23 19:26
This is actually the same as #6191 and it is due to the responsiveness CSS that makes the button disappear because it simply does not fit in the toolbar anymore. I'm closing this as a duplicate of that issue and we continue tracking the issue over there.

**Closed by timvandermeij** 2015-07-23 19:26 UTC
