### ISSUE TITLE
Ligatures rendering as emojis in iOS Safari

### ISSUE THREAD

**Issue by JustinHoldstock** [mozilla/pdf.js#8267] opened 2017-04-10 22:26 UTC
Link to PDF file (or attach file here):
[WalmartAcademy_Ligatures_Issue.pdf](https://github.com/mozilla/pdf.js/files/911611/WalmartAcademy_Ligatures_Issue.pdf)

Configuration:
- Web browser and its version: Safari 602.1
- Operating system and its version: iOS 10.3.1
- PDF.js version: 1.7.406
- Is an extension: No

Steps to reproduce the problem:
1. Open PDF in PDF.js 1.7.406 on IOS Safari

What is the expected behavior? 
<img width="282" alt="ligatures_expected" src="https://cloud.githubusercontent.com/assets/763560/24885084/660828fc-1e01-11e7-8537-99a5522c71b1.png">

What went wrong? Note the trolley car emoji
<img width="282" alt="ligatures_as_emojis" src="https://cloud.githubusercontent.com/assets/763560/24884994/00aa1038-1e01-11e7-9534-37fc06754775.png">

**Comment by evadne** [comment] 2017-04-11 01:26
You also seem to have been hit by the Safari 10 issue #8231 too, note font rendition for “Coaching for Success” looks a bit off.

That said, I suspect this can be worked around with `PDFJS.disableFontFace = true` which I tried by inducing a horrible hack…

	diff --git a/web/app.js b/web/app.js
	index e3380722..662509c6 100644
	--- a/web/app.js
	+++ b/web/app.js
	@@ -1459,6 +1459,7 @@ function webViewerInitialized() {
	     if ('disablefontface' in hashParams) {
	       PDFJS.disableFontFace = (hashParams['disablefontface'] === 'true');
	     }
	+    PDFJS.disableFontFace = true;
	     if ('disablehistory' in hashParams) {
	       PDFJS.disableHistory = (hashParams['disablehistory'] === 'true');
	     }
	(END)

And then rendition works as intended albeit much slower.

![screen shot 2017-04-11 at 02 24 02](https://cloud.githubusercontent.com/assets/104086/24888837/1ae8534e-1e5e-11e7-9d2d-08c34ffaf725.png)

**Comment by sadayamanda** [comment] 2017-04-12 07:32
Same issue here with iOS 10.3 and a cordova app with pdfjs (using UIWebView)

**Comment by John-F-C2** [comment] 2017-04-13 12:34
We had the same issue for folks who were running the latest version of iOS. (10.3.1)
Try setting:
"disableFontFace": true in the list of defaultPreferences for web/viewer.js
That fixed it for us.

**Comment by sadayamanda** [comment] 2017-04-13 12:37
Hi,

Thanks for the reply! This is exactly what I did and it fixed the issue.

Best regards,
Christoph

---
Christoph Schlumpf
Hegifeldstrasse 68
8404 Winterthur

**Comment by tgrosh** [comment] 2017-05-01 14:41
When we apply this fix, flipping the disableFontFace to true, we immediately experience significant performance issues when downloading PDFs. Flipping the flag back to false restores the performance.

**Comment by yurydelendik** [comment] 2017-05-01 15:33
> flipping the disableFontFace to true, we immediately experience significant performance issues

yes, that's expected

**Comment by taenzerme** [comment] 2017-05-15 16:54
Any other fix other than the disableFontFace solution? The performance is really bad. What is the primary thing causing this? Ligatures? Fonts?

**Comment by yurydelendik** [comment] 2017-05-15 17:02
> The performance is really bad. What is the primary thing causing this?

The letters/glyphs are painted using lines/polygons.

**Comment by taenzerme** [comment] 2017-05-16 09:22
@yurydelendik Thanks for the reply, actually I meant what the problem with the original PDF is. Is there a way to convert it to solve the problem?

**Comment by brendandahl** [comment] 2017-05-17 00:45
I didn't really get anywhere on this, but some notes on looking at this a bit:

I can reproduce on desktop safari (Version 10.1 (12603.1.30.0.34)), the 'fi' glyph isn't an emoji but it doesn't show up. The problem seems to be fixed with the technology preview (Release 29 (Safari 10.2, WebKit 12604.1.19.0.1)).

Initially, I thought it was an issue with font `g_d0_f2`, since I can see font `g_d0_f1` successfully draws. I extracted font `g_d0_f2` and loaded it in a vanilla html page (no pdf.js) and put charcode `57374` into a div and painted it on a canvas and the font seems to load correctly and I see the correct 'fi' glyph. Further, if I use the FontFace API and paint to canvas it also seems to work correctly.

Since the font worked in my vanilla tests, I thought it may just be the first font loaded works, but after disabling the load of g_d0_f1 and only loading g_d0_f2 it still was broken. I also tried delaying various promise resolutions and even immediately painting on font load (thinking the font was being GC'ed), but still no luck.

Either safari font loading is buggy or there seems to be something PDF.js is doing that causes it to fail, but I'm out of time to look at this anymore.

The issue seems to be rather strange and I'm not sure it's related to the bug linked to above with promise resolution, but at least it seems to be fixed in future versions.

**Comment by devanonyme** [comment] 2017-07-04 22:25
Same probleme here.

Using disable font face seem to be problematic (performance and incomplete rendering). By exemple, for my test document the two first page seems to be rendered blank, other pages seem to be better when I navigate with page navigator.

![screen shot 07-04-17 at 06 15 pm](https://user-images.githubusercontent.com/21067311/27843769-d05a7238-60e5-11e7-8efc-b1ea0498ff91.PNG)

I will test some more but my first impression is that we will have to wait for Apple to fix this one.

**Comment by tonyjin** [comment] 2017-07-18 01:41
Update here - I just removed the `PDFJS.disableFontFace = true` fix we originally had since that seems to have recently started causing issues. Removing that seems to work and we aren't seeing any garbled emoji fonts in iOS 10.3.2.

**Comment by tonyjin** [comment] 2017-07-25 19:22
@timvandermeij feel free to close this out - 10.3.2 no longer has this issue, thanks!

**Comment by devanonyme** [comment] 2017-07-25 19:29
Hello. I dont have a 10.3.2 at work, I will test with my personnal tablet tonight and report.

**Closed** 2017-07-25 20:04 UTC
Labels: 4-font-conversion, 4-safari-specific

**Comment by devanonyme** [comment] 2017-07-26 00:51
Still see the issue on IOS 10.3.2 and latest 10.3.3. Our app is running lastest release 1.7.
I can check with latest later...

**Comment by t2thec** [comment] 2017-08-01 11:14
I am experiencing the the same issues here too sadly.

iOS Safari 11 beta is all good. iOS Safari 10.3.3 causes issues.

Did anyone find a solution to this?

Cheers

**Comment by BeatriceThalo** [comment] 2018-10-11 18:20
We had this iOS 10 Safari issue with Minion Pro font, but no issue with Gotham font plus outlining the text before creating the PDF.
