### ISSUE TITLE
[Bug]: Changing a chapter causes zoom to change

### ISSUE THREAD

**Issue by swistak** [mozilla/pdf.js#18891] opened 2024-10-12 20:33 UTC
### Attach (recommended) or Link to PDF file

What happens:

When clicking a link or changing a chapter via outline a zoom level changes and resets to the default (`fit-page`) from the previous value (eg. `page-width` or `actual-size`)

Expected behaviour:

Zoom level should be preserved when navigating via outline.

### Web browser and its version

131.0.2 (64-bit)

### Operating system and its version

Windows 11

### PDF.js version

One shipped with 131.0.2 (64-bit) (there's no about menu in PDF.js)

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

Yes

### Steps to reproduce the problem

1. Open pdf with outline
2. Change zoom level to page width
3. Navigate via outline

### What is the expected behavior?

Zoom level should stay the same.

### What went wrong?

Zoom level reset to default

**Comment by Snuffleupagus** [comment] 2024-10-12 20:58
Duplicate of https://github.com/mozilla/pdf.js/issues/11970, which is a best guess given that no PDF document was provided (something that the issue template explicitly mentioned being *required*).

Please refer to https://github.com/mozilla/pdf.js/issues/11970#issuecomment-639064721 which explains how this behaviour can be turned off.

**Closed by Snuffleupagus** 2024-10-12 20:58 UTC
Labels: information-requested
