### ISSUE TITLE
Jumping to a Bookmark Resets Page Zoom

### ISSUE THREAD

**Issue by 28531** [mozilla/pdf.js#16322] opened 2023-04-19 09:15 UTC
Attach (recommended) or Link to PDF file here: (any pdf with bookmarks)

Configuration:
- Web browser and its version: Firefox Version 112.0
- Operating system and its version: Windows 11
- PDF.js version:
- Is a browser extension: no

Steps to reproduce the problem:
1. open a pdf with at least two bookmarks
2. set zoom to an option other than "Page Width" (ex. Actual Size)
3. click on a bookmark
4. zoom automatically gets reset to "Page Width"

What is the expected behavior? (add screenshot)
I have modified the defaultZoomValue preference to 'page-actual' and it should default to "Actual Size" option, jumping to a bookmark shouldn't reset the option. Even if manually changing to Actual Size, jumping to a bookmark will still reset

**Comment by Snuffleupagus** [comment] 2023-04-19 09:49
Duplicate of #11606; please see the `ignoreDestinationZoom` preference.

**Closed by Snuffleupagus** 2023-04-19 09:49 UTC
