### ISSUE TITLE
printing pdf shows wrong orientation in both portrait and landscape mode and also adds white space around it

### ISSUE THREAD

**Issue by parthapaul7** [mozilla/pdf.js#14544] opened 2022-02-07 18:49 UTC
Attach (recommended) or Link to PDF file here:
[_dce87b74565ae355fae88568aefb8f5e_1-Basic-Authentication(1).pdf](https://github.com/mozilla/pdf.js/files/8017860/_dce87b74565ae355fae88568aefb8f5e_1-Basic-Authentication.1.pdf)

Configuration:
- Web browser and its version: firefox Version 96.0.3 (64-bit)
- Operating system and its version: fedora 34
- PDF.js version: 2.12.313 (latest)
- Is a browser extension: no 

Steps to reproduce the problem:
1. open the sample pdf  
2. try to print the pdf 

What is the expected behavior : it should be in the orientation which his viewing on the pdf /screen also it should not add any white negetive space around the pdf on the print screen.

What went wrong? (add screenshot)
![Screenshot from 2022-02-07 01-43-43](https://user-images.githubusercontent.com/83518670/152850675-0889d6ce-526a-4649-a37f-e21f461a4169.png)

![Screenshot from 2022-02-07 01-43-46](https://user-images.githubusercontent.com/83518670/152850779-8a58f216-35c3-449b-ba6e-1b5f5d72b28d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-02-07 18:58
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=844090

**Closed by Snuffleupagus** 2022-02-07 18:58 UTC
