### ISSUE TITLE
Ctrl+mouse wheel zooming zooms in too quickly

### ISSUE THREAD

**Issue by fwsmit** [mozilla/pdf.js#14476] opened 2022-01-20 17:05 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: firefox 96.0
- Operating system and its version: Arch linux, sway (wayland)
- PDF.js version: Whatever came with the browser
- Is a browser extension: no

Steps to reproduce the problem:
1. Open any pdf, can reproduce it on https://mozilla.github.io/pdf.js/web/viewer.html
2. Scroll in with ctrl+mouse wheel using a normal mouse, not a touch pad.

Expected behaviour:
It zooms in with small steps. It can for example be the same steps as ctrl+plus.

Behaviour:
It scrolls in and out way to quickly. It jumps in the steps: 10%, 70%, 150%, 300%, 570%, 1000%.

Notes:
Cannot reproduce on chromium with the web viewer on https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2022-01-20 17:10
That's strange; something similar was seen during development of PR #12203, but the final patch definitely should have fixed that.

/cc @staktrace Do you happen to know if something changed in Firefox *itself* to case this, and if so how we can fix it?

**Comment by staktrace** [comment] 2022-01-21 14:25
There have been some changes to the Firefox code but off the top of my head I can't think of anything that would have caused this. So yes, bisecting Firefox would be useful. Probably starting from version 81 which has the fix to https://bugzilla.mozilla.org/show_bug.cgi?id=1392361. if version 81 is also affected then this is likely a pre-existing issue.

**Comment by staktrace** [comment] 2022-01-21 14:26
Although if it's reproducible in Chrome it might be a regression in pdf.js itself, which should be faster to bisect.

**Comment by fwsmit** [comment] 2022-01-21 22:51
I'll give bisecting pdf.js a try on firefox

**Comment by fwsmit** [comment] 2022-01-25 10:42
I've made an attempt at bisecting, but I ran into troubles installing the dependencies through npm. Maybe it's on my side, I don't use npm often. I made a bug report at https://github.com/npm/cli/issues/4309. Did I do something wrong, or can I do something to fix this? I'm not able to install any packages through npm...

**Comment by Snuffleupagus** [comment] 2022-01-25 16:28
> Although if it's reproducible in Chrome it might be a regression in pdf.js itself, which should be faster to bisect.

It's possible that this has never worked "correctly" in Google Chrome, but since I don't use that browser I cannot really tell.

---

Given that I'm pretty certain that it worked in Mozilla Firefox back when we landed PR #12203 *and* that the PDF.js code in question has not actually changed since then, I decided to run `mozregression`. Doing so points to this being a regression from https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=cc32d9fb952e335bd39137544f597eae95b8d658&tochange=84821aa766abdebcf91be4913082218da63d96ca and thus https://bugzilla.mozilla.org/show_bug.cgi?id=1708829.

**Comment by emilio** [comment] 2022-01-25 17:58
https://github.com/mozilla/pdf.js/pull/14495 should fix this.

**Comment by emilio** [comment] 2022-01-25 17:59
@staktrace is right that this is consequence of that bug, though then https://bugzilla.mozilla.org/show_bug.cgi?id=1708829 corrected the pixel deltas so that they match what Firefox actually scrolls, and exacerbated the problem more.

**Closed** 2022-01-25 18:55 UTC
Labels: 1-viewer, 3-regression

**Comment by fwsmit** [comment] 2022-01-26 10:30
Thanks, it's fixed for me in the demo! Now it's just waiting for the fix to land in firefox.
