### ISSUE TITLE
Special characters not working at all in Safari

### ISSUE THREAD

**Issue by rijk** [mozilla/pdf.js#8853] opened 2017-08-31 10:20 UTC
Certain character combinations like "ff" are completely hidden in Safari, making the text illegible.

Link to PDF file: https://s3.eu-central-1.amazonaws.com/s3.envoy.rocks/uniti/sitomeca/algemene-voorwaarden/BBCtqc_Sitomeca+GTCs+v1.2.pdf

Configuration:
- Web browser and its version: Safari Version 10.1.2 (12603.3.8)
- Operating system and its version: OS X 10.12.6
- PDF.js version: pdfjs-dist@1.9.491 
- Is an extension: no

What is the expected behavior? (screenshot from Chrome)

<img width="459" alt="screen shot 2017-08-31 at 12 18 58" src="https://user-images.githubusercontent.com/159500/29918692-9f9d1ce8-8e46-11e7-8aeb-c1dc01f45ae7.png">

What went wrong? (screenshot from Safari)

<img width="458" alt="screen shot 2017-08-31 at 12 19 11" src="https://user-images.githubusercontent.com/159500/29918700-a52af93c-8e46-11e7-8876-43514706971e.png">

**Comment by Snuffleupagus** [comment] 2017-08-31 10:31
Closing as duplicate of #8852.

**Closed by Snuffleupagus** 2017-08-31 10:31 UTC
