### ISSUE TITLE
Some fonts not shown in pdf

### ISSUE THREAD

**Issue by gHensges** [mozilla/pdf.js#9263] opened 2017-12-11 15:27 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 62
- Operating system and its version: Windows 7
- PDF.js version: Actual demo project 
- Is a browser extension: No
[Rechnungsnummer_16173091.PDF](https://github.com/mozilla/pdf.js/files/1548284/Rechnungsnummer_16173091.PDF)

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/29802177/33838547-1d3ed17a-de90-11e7-8bb1-996c72dde36f.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/29802177/33838498-fd0b770a-de8f-11e7-9fcd-3736cd6392ef.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-12-11 15:31
```
PDF aafc35539e0207ffb0ed3cc48b25f7fa [1.4 3005ci KX / KMPD6399.DLL Version 5.2] (PDF.js: 2.0.203)   viewer.js:1607:7
Warning: Error during font loading: invalid array length   pdf.js:340:5
```

**Comment by Snuffleupagus** [comment] 2017-12-11 16:04
Closing as duplicate of issue #7074.

**Closed by Snuffleupagus** 2017-12-11 16:04 UTC
Labels: 4-font-conversion, 4-font-type0
