### ISSUE TITLE
How can I display a PDF in my web page without displaying the toolbar?

### ISSUE THREAD

**Issue by theWiz06** [mozilla/pdf.js#6087] opened 2015-06-05 20:16 UTC
How can I display a PDF in my web page without displaying the toolbar?  I don't want to display print/save as/download and etc.  

I have tried 'something.pdf#toolbar=0&navpanes=0'
'something.pdf#toolbar=0&navpanes=0' and that doesn't work.

**Comment by timvandermeij** [comment] 2015-06-06 09:24
There is no such option. I you want that, you would have to disable those components manually in your fork of PDF.js. Closing as answered and as duplicate of #2784.

**Closed by timvandermeij** 2015-06-06 09:24 UTC

**Comment by niranjans** [comment] 2015-06-17 00:12
I would like to do something very similar. Could you please point me in the right direction as to which components to disable / which files to touch.
I'm trying to go through the source but I'm not too sure.

**Comment by timvandermeij** [comment] 2015-06-17 17:30
You could try hiding the toolbar by either setting it to `display:none;` in CSS or by completely removing the code altogether: https://github.com/mozilla/pdf.js/blob/master/web/viewer.html#L203-L291 and more parts in viewer.html. The former option is the easiest, the latter option might require some changes in viewer.js too.

**Comment by JakeQZ** [comment] 2021-03-28 01:39
It seems a bit cludgy to have to hack the distribution HTML and/or CSS files to achieve what must be a fairly common requirement.  Another (I expect common) requirement would be to remove the margins around the PDF.

These could be achieved via additional URL parameter(s) to `web/viewer.html` - perhaps the simplest and most generic solution would be to provide an optional path to an additional CSS file...

(Another and not mutually-exclusive approach would be to provide a PHP version of `viewer.html` through which the actual downloaded markup could be controlled via URL parameters.)

Could this be re-opened as a feature request?

**Comment by Snuffleupagus** [comment] 2021-03-28 09:10
> It seems a bit cludgy to have to hack the distribution HTML and/or CSS files to achieve what must be a fairly common requirement.

Please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

> Another (I expect common) requirement would be to remove the margins around the PDF.

Please note this parameter: https://github.com/mozilla/pdf.js/blob/ba76dd4000c0efa570558dd56d551b773bb4e856/web/base_viewer.js#L62-L63

> These could be achieved via additional URL parameter(s) to `web/viewer.html` - perhaps the simplest and most generic solution would be to provide an optional path to an additional CSS file...

Besides the information above, we are *absolutely not* going to add configuration via URL parameters; please see e.g. issue #4954 and the issues referenced from there.

> Could this be re-opened as a feature request?

Again, please note that the viewer is written primarily for the Firefox use-case. Futhermore, there's however also issue #2784 (which isn't entirely straightforward to implement in an acceptable way).
