### ISSUE TITLE
Firefox 36.0 issue - blank page

### ISSUE THREAD

**Issue by ghost** [mozilla/pdf.js#5774] opened 2015-03-02 17:53 UTC
Once upgrading to Firefox 36.0 for Android, the plugin stopped functioning.  Just brings up a blank tab. Tried fresh install of firefox and plugin with same results.

**Comment by jumpig** [comment] 2015-03-03 13:03
Same result here. Any feedback?

**Comment by Premierautomotive** [comment] 2015-03-05 19:37
Same here. We are using this work work purposes, so any help is much appreciated. 

We use a website that has multiple repair manuals that are in pdf format. I will be more than happy to provide access to the site to anyone that would like to help.

**Comment by ousia** [comment] 2015-03-07 17:34
The same here in Fedora 20.

After upgrading to Firefox 36, the addons tab shows a warning message:

> PDF Viewer is incompatible with Firefox 36.0.

Just in case it helps, I have version 1.0.277 installed and automatically disabled.

**Comment by timvandermeij** [comment] 2015-03-07 18:32
I see. The add-on has been marked as incompatible from Firefox 36 and onward because it is integrated in Firefox completely. While that is true for the desktop versions, I'm not sure about the mobile versions of Firefox. Perhaps a quick fix for now is to uninstall the PDF.js add-on you have now and install the development add-on that we use: http://mozilla.github.io/pdf.js/extensions/firefox/pdf.js.xpi
That way you should be able to still work with the PDF.js addon.

**Comment by timvandermeij** [comment] 2015-03-07 18:34
@yurydelendik Is there a better solution to the problem? I think a while back there was a conversation about a custom Android viewer; perhaps we have to enable that for mobile Firefox versions.

**Comment by ousia** [comment] 2015-03-07 18:59
@timvandermeij, many thanks for your tip. It solved my issue.

**Comment by Premierautomotive** [comment] 2015-03-07 23:38
@timvandeemeij, so far this has worked on our nexus 9. I will update the nexus 7 when I get a hold of them next week. Thanks in advance!

**Comment by timvandermeij** [comment] 2015-03-08 14:10
@Premierautomotive Good to hear! We will work on a more structural solution for Android and any other mobile device for that matter, but for now this solution should work for you.

**Comment by yurydelendik** [comment] 2015-03-08 17:43
The idea is to create special add-on version for mobile devices with ui similar to what we have for b2g. I started slowly creating a new version of b2g viewer but got distracted by other project.

**Comment by yurydelendik** [comment] 2015-03-08 17:45
P.S. ideally we shall not advertise developer version of add-on to the end users.

**Comment by timvandermeij** [comment] 2015-03-08 19:43
@yurydelendik I completely agree, but until we have the mobile add-on, I don't think there is another option to get PDF.js working on mobile devices any time soon (since the add-on was blocked for Firefox 36+ without a good alternative for mobile).

**Comment by jumpig** [comment] 2015-03-09 07:21
@timvandermeij , your solution works fine also on Lenovo Yoga tablet. We are also using this a work enviroment for deploying documentation to end users. Thank you so much!

**Comment by ghangalee** [comment] 2015-03-17 16:10
much thanks @timvandermeij for "breaking protocol" giving access to this working add-on...!!!

**Comment by TrashbinPornoDolske** [comment] 2015-05-10 19:19
You can lick my Penis and my golden Eggs, and kiss my Ass son of a bitch with a personality Disorder from the deepest pits of hell from the Depths of Mozilla!

Fuck you and your Mother you autistic son of a bitch, you're going to lick Putin's Eggs, Fucking Faggot Fascist!

The shit out of your Dog, your Cat and your dirty mountain Goat that Faggot Asshole!

Sucking Mozilla Cocks and all together go and suck on Google's Ass full of Shit!

To fuck in your knee you cock suckers! And who the Fuck Australis Chrome clone of shit! Fucking Mozilla gay lesbian homosexual bastards of hell!

**Comment by TrashbinPornoDolske** [comment] 2015-05-10 19:20
Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

**Comment by AssholeDotzler** [comment] 2015-05-10 20:04
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by AssholeDotzler** [comment] 2015-05-10 20:04
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by AssholeDotzler** [comment] 2015-05-10 20:13
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by AssholeDotzler** [comment] 2015-05-10 20:13
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by Lord-of-Darkness** [comment] 2015-05-15 20:14
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by timvandermeij** [comment] 2016-11-25 15:50
Closing as duplicate of #5774. Let's track this issue over there.

**Closed by timvandermeij** 2016-11-25 15:50 UTC
Labels: 1-addon, 4-os-android
