### ISSUE TITLE
Bad / Garbled Font When Viewing PDF

### ISSUE THREAD

**Issue by speedplane** [mozilla/pdf.js#11859] opened 2020-04-29 22:48 UTC
[Attach Link to PDF file here](https://github.com/mozilla/pdf.js/files/4555185/Courthouse.News.Service.v.David.Yamasaki.8_17-cv-00126.No.1.C.D.Cal.Jan.24.2017.pdf)

Configuration:
- Chrome Version 81.0.4044.129 (Official Build) (64-bit)
- Windows 10
- PDFJS: https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Load [This PDF into the viewer](https://github.com/mozilla/pdf.js/files/4555185/Courthouse.News.Service.v.David.Yamasaki.8_17-cv-00126.No.1.C.D.Cal.Jan.24.2017.pdf)

Notice that the font looks very strange, this is especially notciable on page 2:
![image](https://user-images.githubusercontent.com/671052/80654274-e0623680-8a49-11ea-8043-40b54508fa32.png)

I tested the same PDF in Foxit, and did not have this problem:
![image](https://user-images.githubusercontent.com/671052/80654309-ec4df880-8a49-11ea-9d31-a94e828dd982.png)

**Comment by Snuffleupagus** [comment] 2020-04-29 22:59
Duplicate of #5550

**Closed** 2020-04-30 21:44 UTC
