### ISSUE TITLE
Chrome: Support locating the current page in document ToC/outline

### ISSUE THREAD

**Issue by jeenuv** [mozilla/pdf.js#7747] opened 2016-10-22 12:56 UTC
Some native PDF viewers have a feature where it helps to locate where in the ToC the current page lies, usually with a the click of a button. Basically it's the reverse of what clicking on a ToC entry does: maps the page back to the ToC. If the the ToC tree was folded, the all nodes leading to the current page will be expanded. It'd be great if PDF.js Chrome extension could do this.

(As had happened before, I'm not sure if it's already capable of doing this)

**Comment by timvandermeij** [comment] 2016-10-22 13:17
Closing as duplicate of #7557.

**Closed by timvandermeij** 2016-10-22 13:17 UTC
