### ISSUE TITLE
Links not working in pdf.js / Firefox 38.05

### ISSUE THREAD

**Issue by jugmac00** [mozilla/pdf.js#6116] opened 2015-06-15 12:04 UTC
Links are not clickable in following document, only for Firefox / builtin pdf.js - other browsers/pdf viewers are working as intended:

https://www.apis.de/pub/docs/training/ApisTR02WI.pdf
-> Page 4, hotelasam

**Comment by Snuffleupagus** [comment] 2015-06-15 12:14
That PDF file doesn't actually contain any links, but just text styled to *look* like standard hyperlinks.

Those links can work in e.g. Adobe Reader, but only if you have enabled automatic creation of hyperlinks (this setting seems to default to on).

The issue is tracked in #3172, hence I'm closing this this as duplicate.

**Closed by Snuffleupagus** 2015-06-15 12:14 UTC

**Comment by jugmac00** [comment] 2015-06-15 12:39
Thank you very much for claryfing this issue!
