### ISSUE TITLE
Text copied to clipboard without spaces

### ISSUE THREAD

**Issue by Teir** [mozilla/pdf.js#8280] opened 2017-04-13 10:20 UTC
Link to PDF file (or attach file here):
[no_spaces.pdf](https://github.com/mozilla/pdf.js/files/919196/no_spaces.pdf)

Configuration:
- Web browser and its version: Google Chrome 57.0.2987.133
- Operating system and its version: Windows 7
- PDF.js version: demo (1.8.186)
- Is an extension:

Steps to reproduce the problem:
1. Open no_spaces.pdf in pdf.js.
2. Copy text to the clipboard and paste it into the Notepad (or another text editor).

What is the expected behavior? (add screenshot)
Text copied to clipboard with spaces.

What went wrong? (add screenshot)
Text copied to clipboard without spaces.
![no_spaces](https://cloud.githubusercontent.com/assets/19780067/25000959/f106d2cc-204b-11e7-96c3-9e7b8183a1b8.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by darylteo** [comment] 2017-12-21 00:57
[suspension-from-official-quotation-ctxha-1675262.pdf](https://github.com/mozilla/pdf.js/files/1577506/suspension-from-official-quotation-ctxha-1675262.pdf)

We are experiencing this as well. Hopefully this pdf will assist in diagnosing issue. Let me know if I can help anymore as we have a wide variety of PDFs available that we need to render... 

Thanks!
Daryl

**Comment by timvandermeij** [comment] 2018-09-01 20:05
The first PDF now copies as:

```
и
передать
в
качестве
параметра
```

The second PDF now copies as:

```
Caltex
Australia
Limited
–
Caltex
Subordinated
Notes
```

Closing since the issue is now a duplicate of #2140.

**Closed by timvandermeij** 2018-09-01 20:05 UTC
Labels: 4-text-selection
