### ISSUE TITLE
AdobeSongStd-light font cannot display properly ，PDF.JS  can not  display content

### ISSUE THREAD

**Issue by lizhengjian1220** [mozilla/pdf.js#14251] opened 2021-11-08 02:11 UTC
I want to add the new font to pdF.js when I preview the PDF. What do I need to do? I'm in Linux
to install this font, is this ok?

**Comment by lizhengjian1220** [comment] 2021-11-08 03:28
Fetch API  cannot load  : file:////D:/2.10/web/cmaps/UniGb-UCS2-h.bcmap
loadFont -translation failed:"TypeError:Failed to fetch"
Error during font loading :Failed to fetch  

When using the same font:
The encoding format of this PDF is: UNIGB-UCS2-H，It doesn't work
I have tested other encoding formats and it is OK，For example,identity-H

**Comment by Snuffleupagus** [comment] 2021-11-08 08:54
Duplicate of #14231

**Closed by Snuffleupagus** 2021-11-08 08:54 UTC
