### ISSUE TITLE
Message: Invalid PDF structure

### ISSUE THREAD

**Issue by eswarpdf** [mozilla/pdf.js#7247] opened 2016-04-25 11:34 UTC
Link to PDF file (or attach file here):
Can't add pdf file here as it is confidential.

Configuration:
- Web browser and its version: Firefox 38.0.1
- Operating system and its version:  Windows 7
- PDF.js version: v1.3.91 (build: d1e83b5)
- Is an extension: No

Steps to reproduce the problem:
1.  Passing blob to viewer.html

What is the expected behavior? (add screenshot)
pdf viewer rendering pdf file successfully.

What went wrong? (add screenshot)
![pdfviewerror](https://cloud.githubusercontent.com/assets/18658733/14782463/1b01501c-0b07-11e6-95e1-7c40f388b619.JPG)

Other notes:
I'm using pdf.js viewer in multiple modules. I was able to use viewer in couple of modules successfully. But in one module I'm getting the error. All the pdf files are either scanned files or normal pdf's.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2016-04-25 12:51
> PDF.js version: v1.3.91 (build: d1e83b5)

Please check if the issue is present in the *latest* version of PDF.js, which as of this writing is `1.5.201`, by opening the file with http://mozilla.github.io/pdf.js/web/viewer.html (Use the "Open file" button on the right-hand side of the toolbar).

If the issue is still present there, you need to provide the PDF file in order for the issue to be valid.

**Comment by yurydelendik** [comment] 2016-04-25 15:16
> Can't add pdf file here as it is confidential.

Make the non-confidential example for us.

**Comment by eswarpdf** [comment] 2016-04-26 05:50
Thanks for the quick reply. I'm trying use the latest version. And finding the right document to test and share if it fails.
Thank you.

**Comment by eswarpdf** [comment] 2016-04-26 13:18
I tested with 1.5.188 version.  

I'm getting this error as well - Error: Invalid XRef stream header.   I'm not able to share the pdf file as I'm unable to upload and test in our server.  
What I'm doing is this : 
- Convert base64 to uinit8. 
- Create blob from it , type: application/pdf
- then  call - viewer.html?file=' + encodeURIComponent(url);

Please provide your comments.

**Comment by yurydelendik** [comment] 2016-04-26 13:23
Without complete example it's hard to tell. So far we can assume you are doing one of the steps above wrong or you have incorrectly encoded base64 pdf data.

**Comment by yurydelendik** [comment] 2016-04-26 13:25
>  I'm not able to share the pdf file as I'm unable to upload and test in our server.

Closing as incomplete based on the statement above. Please provide complete example to reproduce the issue on the computer other than yours to reopen the issue.

**Closed by yurydelendik** 2016-04-26 13:25 UTC
Labels: 4-information-requested

**Comment by eswarpdf** [comment] 2016-04-26 13:50
The same code is working in another module. The base64 conversion is done in java and returned.

**Comment by yurydelendik** [comment] 2016-04-26 13:57
It works for me if I run the following in the console (of http://mozilla.github.io/pdf.js/web/viewer.html page):
```
PDFViewerApplication.pdfDocument.getData().then(function (data) { 
  window.open('viewer.html?file=' + encodeURIComponent(URL.createObjectURL(new Blob([data], {type: 'application/pdf'})))); 
});
```

The difference is that there is no base64 transforms, so if you are doing create blob and url opening steps right the problem is with your base64 encoding and/or decoding.

**Comment by eswarpdf** [comment] 2016-04-26 14:23
- Base64 conversion is done by standard jar (commons-codec.jar) and decode is done using the below code

function base64DecToArr(sBase64, nBlocksSize) {
			var sB64Enc = sBase64.replace(/[^A-Za-z0-9\+\/]/g, ""), nInLen = sB64Enc.length, nOutLen = 	nBlocksSize? Math
					.ceil((nInLen * 3 + 1 >> 2) / nBlocksSize)
					* nBlocksSize
					: nInLen * 3 + 1 >> 2, taBytes = new Uint8Array(nOutLen);
			for (var nMod3, nMod4, nUint24 = 0, nOutIdx = 0, nInIdx = 0; nInIdx < nInLen; nInIdx++) {
				nMod4 = nInIdx & 3;
				nUint24 |= b64ToUint6(sB64Enc.charCodeAt(nInIdx)) << 18 - 6 * nMod4;
				if (nMod4 === 3 || nInLen - nInIdx === 1) {
					for (nMod3 = 0; nMod3 < 3 && nOutIdx < nOutLen; nMod3++, nOutIdx++) {
						taBytes[nOutIdx] = nUint24 >>> (16 >>> nMod3 & 24) & 255;
					}
					nUint24 = 0;
	
				}
			}
			return taBytes;
	}
	
	
	function b64ToUint6(nChr) {
			return nChr > 64 && nChr < 91 ? nChr - 65
				: nChr > 96 && nChr < 123 ? nChr - 71 : nChr > 47
					&& nChr < 58 ? nChr + 4 : nChr === 43 ? 62
					: nChr === 47 ? 63 : 0;
		}

**Comment by eswarpdf** [comment] 2016-04-26 14:23
Forgot to mention, Thank you so much for quick responses.

**Comment by yurydelendik** [comment] 2016-04-26 15:24
Running the code above in the browser does not produce any output.

**Comment by eswarpdf** [comment] 2016-04-26 15:44
Can you share the code to decode base64 string to uint8array

**Comment by yurydelendik** [comment] 2016-04-26 15:45
See https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html . Notice that Blob can accept output from atob as well.

**Comment by eswarpdf** [comment] 2016-04-27 04:30
Tried with ;atob' function passing base64 string. Still getting "Invalid PDF Structure". Will try to attach PDF today.

**Comment by eswarpdf** [comment] 2016-04-27 15:34
If I'm getting byte array from java. What is the way to use it with viewer.html.  Sample code will help me.

**Comment by yurydelendik** [comment] 2016-04-27 16:42
@eswarpdf don't use base64, just return stream of bytes using setContentType, setContentLength as getOutputStream. See for example http://www.avajava.com/tutorials/lessons/how-do-i-serve-up-a-pdf-from-a-servlet.html . base64 is wasteful for a server's and a web browser's resources.

**Comment by eswarpdf** [comment] 2016-04-28 10:54
That's not working either. Getting byte array as mentioned above and passing it to viewer.html as shown below.

1.  viewer.html?file=' + prjURL + '&param1='+ value1 + '&param2=' + value2;
2.  viewer.html?file=' + encodeURIComponent(prjURL) + '&param1='+ value1 + '&param2=' + value2;

**Comment by eswarpdf** [comment] 2016-04-28 11:57
My initial approach itself working. There was mismatch is params passed to URL. 
Thank you so much Yury, for quick response and patience.

**Comment by eswarpdf** [comment] 2016-04-29 09:24
Consider for example I've a URL like this.
   url : myUrl
  headers : {'**param1**' : **value1**, '**param2**' : **value2 **}

How can I pass myUrl along with headers to  viewer.html?

**Comment by eswarpdf** [comment] 2016-05-04 11:36
viewer.html?file=' + encodeURIComponent(url)';  is not working in IE11 whereas its working in Firefox.

![pdf-not-working-in-ie11](https://cloud.githubusercontent.com/assets/18658733/15012871/aac95884-1219-11e6-96b0-6f7dd354267c.JPG)

**Comment by eswarpdf** [comment] 2016-05-04 12:22
I've gone through this thread - https://github.com/mozilla/pdf.js/issues/3977 and using latest PDF.js version( 1.5.188).  The #1103 is different in 1.5.188 version. 

Is it still an open issue?

**Comment by eswarpdf** [comment] 2016-05-04 13:27
I'm not displaying the print button and want to disable printing.  How to prevent/block Ctrl + P?

**Comment by eswarpdf** [comment] 2016-05-10 05:53
Added evt.preventDefault() in viewer.html  keydown event handler, when Ctrl + P is pressed, like below.

`
if (cmd === 1 || cmd === 8) {
    switch (evt.keyCode) {
    case 80: // p
                  console.log("ctrl + p is pressed");Z
 		  evt.preventDefault();
                  return;
}
`

Getting **"ctrl + p is pressed"** log but still the print is allowed, why **evt.preventDefault()** is not working?
Please help me?

**Comment by eswarpdf** [comment] 2016-05-11 05:41
I've working code to open pdf in new browser window. Now I've to open pdf inside dynamic div container(page tab). I'm trying like this.

`var newTabContent = '<div id="'+tabId+'" class="tab_content" style="display: block;"></div>';
                    $('#dynamicTabContent').append(newTabContent);
                    $('#pageContent').hide();
                    $("#"+tabId).show();
                    $("#"+tabId).html(); 
                    $dynamicTabContent(viewerUrl);


**viewerUrl **= viewer.html?file + encodeURIComponent(url_createdFrom_blob);`

The background color of the div container changes to dark gray but I'm getting this error -  "**TypeError: pdfViewer is null**".  Please help me I'm stuck with this error for days.

**Comment by timvandermeij** [comment] 2016-05-11 11:33
Please do not post comment on this issue that are not related to the original reason this issue was opened. Use the mailing list or IRC to get help with custom solutions.
