### ISSUE TITLE
_setCurrentPageNumber() not triggering in ie11

### ISSUE THREAD

**Issue by supertrip86** [mozilla/pdf.js#11205] opened 2019-10-04 08:35 UTC
As per title, pdf.js is not triggering the function _setCurrentPageNumber() on Internet Explorer 11.
If you open the following link to the pdf.js demo on ie11:
http://mozilla.github.io/pdf.js/web/viewer.html
You will see that is not possible to use the toolbar to change pages.

![Untitled](https://user-images.githubusercontent.com/40668622/66193353-a3d88300-e692-11e9-849b-87fe72d77443.png)

**Comment by Snuffleupagus** [comment] 2019-10-04 08:39
Duplicate of #4551.

Please also note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Comment by supertrip86** [comment] 2019-10-04 08:59
I apologize if the issue has already been reported. It was many years ago and I wasn't able to find it.

**Closed** 2019-10-04 21:01 UTC
