### ISSUE TITLE
dynamically give pdf path in pdf.js

### ISSUE THREAD

**Issue by piyusharc** [mozilla/pdf.js#7933] opened 2017-01-06 14:29 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. Somebody please help me to fix my issue:-
i've developed a small application in php and mysql, where i'm uploading pdf and moving file to UPLOADS folder and storing path in database. But in viewing after passing path i'm not able to open pdf on browser.
i've uploaded PDF.JS files in my folder aswel.
please help me to come out of it. below is my testing url please visit

http://www.farukhzama.com/fileupload/index.php
http://www.farukhzama.com/fileupload/view.php
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment] 2017-01-06 15:04
Looks like your PHP app is broken and there is no way to see a source code (provide path to the public source control repo?) to see structure of this app. I don't think the problem is PDF.js but rather the way it's deployed. Closing as incomplete.

**Closed by yurydelendik** 2017-01-06 15:04 UTC

**Comment by piyusharc** [comment] 2017-01-06 15:05
there

**Comment by piyusharc** [comment] 2017-01-06 15:06
Sir are you there actually i was trying something

**Comment by yurydelendik** [comment] 2017-01-06 15:09
Looks like you are trying to implement https://github.com/joepie91/pdfy -- see this project first.

**Comment by piyusharc** [comment] 2017-01-06 15:11
Sir could you please tell me where to put the datapath  can i send you the file

**Comment by piyusharc** [comment] 2017-01-06 15:24
Sir 
Thank you so much for your quick response, please check your mail I've sent you the complete code or also now you can check above url now its working

**Comment by yurydelendik** [comment] 2017-01-06 15:55
> Sir could you please tell me where to put the datapath can i send you the file

> Thank you so much for your quick response, please check your mail I've sent you the complete code or also now you can check above url now its working

At the moment, I'm just triaging the issue and have no intent on fixing somebody's issue in timely manner. If you provide enough details, project contributors or other people may assist you, but so far not enough information was provided and php language specifics out-of-scope.

**Comment by nikitasheth** [comment] 2017-08-18 06:30
sir i want to open pdf file dynamically from my database instead of displaying from web folder. How can i provide dynamic path of pdf from database to viewer.html
