### ISSUE TITLE
Feature request: pdf at a glance

### ISSUE THREAD

**Issue by yurivict** [mozilla/pdf.js#2377] opened 2012-11-13 19:54 UTC
Now the thumbnails feature shows the previews of several pages in one column on the left.
It would be beneficial to see previews of more pages at the same time, tiling the whole screen.

So I suggest to add the "pdf at a glance" feature, showing the same thumbnails as current thumbnails feature, but covering the whole screen.

For example, there is a large pdf with 100+ pages, and I need to find something in it. There is no text search in it, and I only remember how some picture looks. Seeing all pages at once is very beneficial in such case.

**Comment by Snuffleupagus** [comment] 2017-11-07 09:57
With PR #9026 landed, it's now possible to (in reasonably modern browsers) resize the sidebar such that it occupies *half* of the available viewer width.
Considering first of all that rendering of thumbnails is just as resource intensive as the rendering of "normal" pages, and also that the feature requested in this issue (i.e. nothing but thumbnails shown) seems like enough of a special case to not warrant the code complexity, I think that we can close this.

Closing as duplicate of #2072.

**Closed by Snuffleupagus** 2017-11-07 09:57 UTC
Labels: 2-feature
