### ISSUE TITLE
Thin line in the blue box is getting displayed in PDF viewer.

### ISSUE THREAD

**Issue by gsampath127** [mozilla/pdf.js#8277] opened 2017-04-12 18:59 UTC
Link to PDF file (or attach file here):  http://hosted.rightprospectus.com/documents/TIAACREF/PRO_InternationalandGlobal.pdf

Configuration:
- Web browser and its version:  all browsers
- Operating system and its version: latest
- PDF.js version: latest
- Is an extension: NA

Steps to reproduce the problem:

1. Open PDF file ( http://hosted.rightprospectus.com/documents/TIAACREF/PRO_InternationalandGlobal.pdf) in Pdf Js Viewer.
2. Issue can be seen when we open PDF here - https://mozilla.github.io/pdf.js/web/viewer.html
3. Thin line in the blue box is getting displayed in PDF viewer. Please find expected behavior screen shot from adobe. 

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/12858790/24974456/32e5aa86-1f90-11e7-8284-0923d2a409dc.png)

What went wrong? (add screenshot)

![image](https://cloud.githubusercontent.com/assets/12858790/24974501/5bd1f648-1f90-11e7-8679-9004e8ad7cf6.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2017-04-12 20:11
Closing since this is a duplicate of #4860 and others.

**Closed by timvandermeij** 2017-04-12 20:11 UTC
