### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by vivacewith** [mozilla/pdf.js#5661] opened 2015-01-20 07:22 UTC
Illegal digit in hex char in name: -1

     at error (http://localhost/lib/pdf/shared/util.js:221:15)
    at Object.Lexer_getName [as getName] (http://localhost/lib/pdf/core/parser.js:733:59)
    at Object.Lexer_getObj [as getObj] (http://localhost/lib/pdf/core/parser.js:818:23)
    at Object.Parser_shift [as shift] (http://localhost/lib/pdf/core/parser.js:53:32)
    at Object.Parser_getObj [as getObj] (http://localhost/lib/pdf/core/parser.js:58:12)
    at Object.Parser_getObj [as getObj] (http://localhost/lib/pdf/core/parser.js:88:34)
    at Object.XRef_fetchUncompressed [as fetchUncompressed] (http://localhost/lib/pdf/core/obj.js:1261:28)
    at Object.XRef_fetch [as fetch] (http://localhost/lib/pdf/core/obj.js:1218:26)
    at Object.XRef_fetchIfRef [as fetchIfRef] (http:/localhost/lib/pdf/core/obj.js:1199:19)

**Comment by CodingFabian** [comment] 2015-01-20 09:50
Can you please provide the PDF which produces this error? Also other relevant information like pdf.js version used.

**Comment by Snuffleupagus** [comment] 2015-01-20 11:06
When reporting an issue, please make sure that you read (especially the *first* paragraph): https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.

**Comment by vivacewith** [comment] 2015-01-21 06:02
I'm downloaded from the banner on the right side.

PDF file send to e-mail

**Comment by Snuffleupagus** [comment] 2015-01-21 15:50
GitHub doesn't support attaching PDF files, and neither does the mailing list ([cross-posted here]( https://groups.google.com/forum/#!topic/mozilla.dev.pdf-js/n5GYcUQK3m4)).

@vivacewith Please upload the PDF file to a file sharing service, such as e.g. Dropbox, Google Drive, or [PDFy](https://pdf.yt/), and attach a link to the file here.

**Comment by yurydelendik** [comment] 2015-01-21 16:02
I don't think PDF here a fault, but it's how the PDF.js is deployed. You did not provide enough information about how the custom application was deployed. The best way for us is to see that via public URL we can access. Otherwise describe in details what you did so we can reproduce your steps.

**Comment by vivacewith** [comment] 2015-01-22 02:38
This problem does not occur in most PDF.JS program. Even if working properly loaded in the demo code http://mozilla.github.io/pdf.js/web/viewer.html. However, the code is applied to my server results in an error. I'm not a matter of PDF.JS I want to know that you are applying to any part would raise the wrong article. Uploading a PDF file edaga It will be meaningless tasks.

**Comment by timvandermeij** [comment] 2015-01-22 17:43
Closing as incomplete. If we cannot reproduce this error, it is almost impossible to find the cause of it. Make sure your server uses the most recent version of PDF.js. Provide steps to reproduce the issue (for example a link to your server) to reopen.

**Closed by timvandermeij** 2015-01-22 17:43 UTC
Labels: 4-information-requested
