### ISSUE TITLE
Pdf page is not visible whenever we switch browser tabs

### ISSUE THREAD

**Issue by Saran5775** [mozilla/pdf.js#18139] opened 2024-05-22 07:07 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome - version 124.0.6367.202
- Operating system and its version: Mac OS Montery, version 12.7.4
- PDF.js version: Latest pdfjs version
- Is a browser extension: No

Steps to reproduce the problem:
Please refer this below screenrecording to reproduce this case.

I am using the default pdfjs example preview `https://mozilla.github.io/pdf.js/web/viewer.html` .I am using the pdfjs in our webapp as well, But I cannot share any info related to it. But I found the same issue reproducible in the default viewer as well.

Attaching the screenrecording in [this](https://drive.google.com/file/d/1HnxnO__Edze2VurG3fY8x1ZAzOLAhgrg/view?usp=drive_link) link.

Try to keep the pdf open in a tab and move to two different tabs and come back to the same pdf tab, the page contents are not visible.

When we zoom in or zoom out, the page is rendered again.
We can even select the text in that page, but the text is not visible.

What is the expected behavior? (add screenshot)

the page should be visible when we switch tab

What went wrong? (add screenshot)

Not sure. But seems the issue with the default pdfjs viewer page itself. Hope it uses the latest pdfjs version.

This issue seems reproducibe in chrome alone as of now. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
-

**Comment by nicolo-ribaudo** [comment] 2024-05-22 08:00
Could you double-check your Chrome version? This looks a lot like a duplicate of https://github.com/mozilla/pdf.js/issues/18100, but in the linked Chrome bug report (https://issues.chromium.org/issues/339654395) they said that it was a regression introduced in Chrome 126.

**Comment by Snuffleupagus** [comment] 2024-05-22 08:47
Duplicate of #18100

**Closed by Snuffleupagus** 2024-05-22 08:47 UTC
