### ISSUE TITLE
Dev version of PDF.js is not verified

### ISSUE THREAD

**Issue by Airon90** [mozilla/pdf.js#6383] opened 2015-08-25 10:24 UTC
I can't install development version of PDF.js because the XPI file you provide in [README](https://github.com/mozilla/pdf.js/blob/master/README.md#firefox) file is not signed and verified by Mozilla. I'm using latest Firefox Nightly version available as of now.

**Comment by Snuffleupagus** [comment] 2015-08-25 10:29
Closing as duplicate of issue #6137.

**Closed by Snuffleupagus** 2015-08-25 10:29 UTC
