### ISSUE TITLE
Adobe Interarctive Form (Checkbox behavior)

### ISSUE THREAD

**Issue by SuperNoob13** [mozilla/pdf.js#8159] opened 2017-03-14 09:06 UTC
Hi,

I read in #7613 that pdf.js supports checkboxes and their behavior. 
![checkboxes](https://cloud.githubusercontent.com/assets/26303053/23893209/e952d104-089d-11e7-9d5b-51e0abe1a95b.PNG)
[GN10_NASA.pdf](https://github.com/mozilla/pdf.js/files/840725/GN10_NASA.pdf)

I use the converter to convert my pdf into your page view.
The rendering process is correct but I can't flag the checkboxes. 

JS code:
 promise = promise.then(function (pageNum) 
				{
					return doc.getPage(pageNum).then(function (pdfPage) 
						{
							var pdfPageView = new PDFJS.PDFPageView
							({
							container: container,
							id: pageNum,
							scale: DEFAULT_SCALE,
							defaultViewport: pdfPage.getViewport(DEFAULT_SCALE),
							annotationLayerFactory: new PDFJS.DefaultAnnotationLayerFactory(),
							renderInteractiveForms: true,
							});
					// Associate the actual page with the view and draw it.
						pdfPageView.setPdfPage(pdfPage);
						return pdfPageView.draw();
						});
				}.bind(null, i));

PDF is attached

Thanks for your help!

**Comment by SuperNoob13** [comment] 2017-03-15 07:52
I investigated furhter:
The state of the checkbox changes, but the css doesn't. So maybe it just an CSS problem.

**Comment by rmhrisk** [comment] 2017-03-25 19:36
I suspect this is a dupe of : https://github.com/mozilla/pdf.js/issues/8047

**Comment by timvandermeij** [comment] 2017-03-26 19:00
This is indeed a CSS problem and is unrelated to the issue above. While this definitely used to work, I see that it does not work in the current Nightly. The checkboxes/radio buttons are styled, but the "clicked" style is no longer inherited, where previously is was.

**Comment by timvandermeij** [comment] 2017-03-26 19:06
This works in Firefox 53.0b6, but is broken in Nightly. This is either a regression in Firefox or an upstream change that we don't know about.

@Snuffleupagus Could you test this on Windows to make sure that this is not Linux-specific? If it is indeed a regression, could you report it in the appropriate place upstream?

**Comment by timvandermeij** [comment] 2017-09-24 12:43
Closing since this is fixed by #8877.

**Closed by timvandermeij** 2017-09-24 12:43 UTC
Labels: 4-form-acroform
