### ISSUE TITLE
multimedia content not played

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#13929] opened 2021-08-23 17:54 UTC
> Attach (recommended) or Link to PDF file here:

[Uncompressed PDF file with embedded MP3 file.](https://github.com/mozilla/pdf.js/files/7033916/uncompressed-a.pdf)

> Configuration:
- Web browser and its version: Firefox 91.
- Operating system and its version: Windows 7.
- PDF.js version: The one shipped with Firefox 91.
- Is a browser extension: Yes.

> Steps to reproduce the problem:
1. Open the attached file and click on the frame. 
2. Sound should be played.

> What is the expected behavior? (add screenshot)

Sound playing.

> What went wrong? (add screenshot)

Sound isn’t played. Warning about missing Screen annotation implementation.

Many thanks for your help.

**Comment by Snuffleupagus** [comment] 2021-08-23 18:01
Duplicate of #6078

**Closed by Snuffleupagus** 2021-08-23 18:01 UTC
