### ISSUE TITLE
Uncaught (in promise) Error: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".   at pdf.js:2336

### ISSUE THREAD

**Issue by sdeass** [mozilla/pdf.js#13659] opened 2021-07-03 10:38 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:2.9.359 2.8.335 2.5.207 2.4.456
- Is a browser extension:

Steps to reproduce the problem:
1. All version I had tried to reinstall. First I uninstall pdfjs-dist Second I install pdfjs-dist@2.9.359 or and so on.
2.
var pdfjsLib = require('pdfjs-dist')
// import { TextLayerBuilder } from 'pdfjs-dist/web/pdf_viewer'
pdfjsLib.GlobalWorkerOptions.workerSrc = require('pdfjs-dist/build/pdf.worker.js')
import 'pdfjs-dist/web/pdf_viewer.css'
const CMAP_URL = './cmaps/'
var container
export default class DrawPdf {
  static getPDF(url) {
    const loadingTask = pdfjsLib.getDocument({
      url: url,
      cMapUrl: CMAP_URL,
      cMapPacked: true
    })

    loadingTask.promise.then(function(pdfDocument) {
      // Document loaded, retrieving the page.
      console.log(pdfDocument)
    })
  }

What is the expected behavior? (add screenshot)
Please help me to fix the problem.

What went wrong? (add screenshot)
Uncaught SyntaxError: Unexpected token '<'
Uncaught (in promise) Error: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".   at pdf.js:2336
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2021-07-03 10:41
Closing since this is a duplicate of many others is https://github.com/mozilla/pdf.js/search?q=workermessagehandler+of+undefined&type=issues and https://github.com/mozilla/pdf.js/issues/11787#issuecomment-610867258 is most likely the cause of this.

**Closed by timvandermeij** 2021-07-03 10:41 UTC
