### ISSUE TITLE
Page is not rendered, it remains blank and scrolling leads to broken image.

### ISSUE THREAD

**Issue by anirudh-modi** [mozilla/pdf.js#7132] opened 2016-03-30 10:48 UTC
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Google chrome - Version 49.0.2623.87 (64-bit)
- OS X - Version 10.10.5
- PDF.js version: whatever is available on the demo link.
- Is an extension: no

Steps to reproduce the problem:
1. The issue is cannot reproduced everytime, however, I have encountered the issue randomly, I have noticed that after text selection if I am inactive in the browser and switch back to the pdf tab, then the visible pages are not rendered, the pages remain empty and on scrolling the broken images appear. 

What is the expected behavior? (add screenshot)
It should have rendered the page, with text selection.

What went wrong? (add screenshot)
As you can see in the attached screenshots, that the page is entirely blank and on scrolling i see broken images of the page.

![screen shot 2016-03-30 at 4 08 03 pm](https://cloud.githubusercontent.com/assets/16587779/14139683/221d94ca-f692-11e5-9176-8f40dfd6fc75.png)
![screen shot 2016-03-30 at 4 08 10 pm](https://cloud.githubusercontent.com/assets/16587779/14139682/221c9f2a-f692-11e5-8b07-68488679aa40.png)

**Comment by sharanmunyal** [comment] 2016-03-31 00:07
Even I am seeing the same issue on Chrome on Mac.

**Comment by matsteen** [comment] 2016-03-31 17:40
+1 for this issue!

**Comment by yurydelendik** [comment] 2016-03-31 18:16
Unable to reproduce on 10.11. @sharanmunyal and @matsteen what's your configuration?

**Comment by yurydelendik** [comment] 2016-03-31 18:18
Can you also provide more detailed steps to reproduce with time intervals, key strokes, mouse movements?

**Comment by xlc** [comment] 2016-03-31 20:48
I am also seeing this issue but I think it is a Chrome/OSX bug.
I use PDF.js open some file and leave it for overnight, next day morning I am seeing empty canvas. But it doesn't always happen.
Switch to a different tab in Chrome then switch back fixed it.

**Comment by matsteen** [comment] 2016-03-31 20:56
@yurydelendik same steps as @xlc, I just open a tab and leave it.  When I come back the canvas is either blank or garbled as I scroll it.  It only affects the canvases that are rendered with content and as soon as I trigger 'draw' the problem goes away.  A quick fix could be to redraw in Chrome when the tab gets focus again.

**Comment by sharanmunyal** [comment] 2016-03-31 21:03
seems to be an issue at the browser level. Refer http://stackoverflow.com/questions/36198813/canvas-content-disappears-on-chrome-49-on-mac-with-an-angularjs-tooltip

**Comment by yurydelendik** [comment] 2016-03-31 21:09
@matsteen For how long 2, 8 or 16 hours? Do you have version Max OS 10.10.5 or 10.11.3?

**Comment by matsteen** [comment] 2016-03-31 21:14
Sometimes minutes, sometimes hours.  I also usually have 20+ tabs open at any given moment. OSX Yosemite: 10.10.5

I haven't noticed it today, just yesterday and earlier.  It's worth noting Chrome just upgraded today to 49.0.2623.110 (64-bit).

**Comment by yurydelendik** [comment] 2016-03-31 21:20
Looks like it's https://bugs.chromium.org/p/chromium/issues/detail?id=588434

Marked as fixed. Closing

**Closed by yurydelendik** 2016-03-31 21:20 UTC
Labels: 3-upstream, 4-chrome-specific, 4-os-mac

**Comment by yurydelendik** [comment] 2016-03-31 21:22
(Also https://codereview.chromium.org/1762783002)

**Comment by anirudh-modi** [comment] 2016-04-01 05:57
Thanks for such quick response.
