### ISSUE TITLE
Invert document colors (night mode)

### ISSUE THREAD

**Issue by PeterNerlich** [mozilla/pdf.js#8253] opened 2017-04-07 09:01 UTC
[Feature Request]

Configuration:
- Web browser and its version: Chromium 57.0.2987.98
- Operating system and its version: Elementary OS Loki (elementary 0.4, 64-bit)
- PDF.js version: 1.6.293
- Is an extension: Yes

The systems default PDF viewer has this handy feature inverting the colors of the document, which I use all the time as it is considerably more convenient, especially at night. To my understanding, this should be very easy to implement, as it required no more than applying `filter: invert();` to the `.pdfViewer .page` and maybe inverting the border image again.
It would also be handy to have the keyboard shortcut [Ctrl] + [I] for it, as it is used in the systems viewer.

**Comment by Snuffleupagus** [comment] 2017-04-07 09:09
Closing as duplicate of issue #2071 (and #2163).

**Closed by Snuffleupagus** 2017-04-07 09:09 UTC

**Comment by alexchandel** [comment] 2019-05-17 09:43
Please re-open.  Night mode refers specifically to `@media (prefers-color-scheme: dark) { ... }` CSS, which is not the same as the user generically changing text/background colors.

**Comment by silgon** [comment] 2020-04-02 11:50
Please re-open. Something like `[Ctrl] + [I]` would be really neat.

**Comment by let-def** [comment] 2023-07-18 01:23
Thanks for the CSS rule. Since it seems this feature is not going to make it to PDF.js anytime soon, I saved it as a [bookmarklet](https://en.wikipedia.org/wiki/Bookmarklet). If anybody is interested:

`javascript:(function(f){if(f.cssRules.length)f.deleteRule(0);else f.insertRule('.pdfViewer .page{filter:invert();}');})(window['_pdfsty']=window['_pdfsty']||document.head.appendChild(document.createElement('style')).sheet))`

It creates a new stylesheet element with the right rule, and toggle it (removing or re-adding it) if applied again.

**Comment by pegvin** [comment] 2026-05-10 07:28
> Thanks for the CSS rule. Since it seems this feature is not going to make it to PDF.js anytime soon, I saved it as a [bookmarklet](https://en.wikipedia.org/wiki/Bookmarklet). If anybody is interested:
> 
> `javascript:(function(f){if(f.cssRules.length)f.deleteRule(0);else f.insertRule('.pdfViewer .page{filter:invert();}');})(window['_pdfsty']=window['_pdfsty']||document.head.appendChild(document.createElement('style')).sheet))`
> 
> It creates a new stylesheet element with the right rule, and toggle it (removing or re-adding it) if applied again.

Unfortunately this didn't work for me due to some mismatched parenthesis issue, But the following did: https://support.mozilla.org/en-US/questions/1281116

To everyone time:
```js
javascript:/*PDF - toggle filter invert*/(function(){var L='style_PDFI',S='#viewerContainer>#viewer.pdfViewer>.page{filter: invert(100%)}',SS,E=document.querySelector('style[id="'+L+'"]');if(E){SS=E.disabled;E.disabled=(SS==true)?false:true}else{SS=document.createElement('style');SS.setAttribute('type','text/css');SS.id=L;SS.innerHTML=S;document.querySelector('head').appendChild(SS);}})()
```
