### ISSUE TITLE
Rendering Issue #11886

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#12047] opened 2020-06-30 13:53 UTC
I raised this issue at the beginning of May and noted that the pdf rendered correctly in the current FireFox but not in the pdfjs demo viewer.

At the time it was closed "Given that it works in 2.5, I can only assume a PDF.js patch or, more likely, an upstream Firefox patch fixed the rendering issue. Hence I don't think there is anything we can do here anymore."

So now 6 weeks later it still doesn't work in the pdf demo viewer and still works in current FireFox.

Is there anything that can be done to fix this or is it really a "won't fix" issue 

We have an app that is dependent on the pdfjs lib and clients who continue to complain about the issue and we are trying to give them some response.

[29203_fccu-OutputPROOF.pdf](https://github.com/mozilla/pdf.js/files/4852262/29203_fccu-OutputPROOF.pdf)

**Comment by Snuffleupagus** [comment] 2020-06-30 14:22
Honestly, it's quite likely that this issue is *somehow* related to e.g. the operating system and/or graphics driver used, rather than the PDF.js library itself.

If it would in fact be a PDF.js rendering bug you'd kind of expect it to be consistently broken *everywhere*, and personally I've not been able reproduce the described problems (although the original issue didn't include *any* screen-shots, making it difficult to even understand the problem).

**Comment by blackmambahk** [comment] 2020-07-01 10:00
The issue is a moment after loading every page turns orange (see below) and most of the content is lost.

![Webpage Screenshot](https://user-images.githubusercontent.com/947206/86230150-b4a12100-bb5e-11ea-88f7-a0f84bd5768e.png)
.

"Honestly, it's quite likely that this issue is somehow related to e.g. the operating system and/or graphics driver that's being used"
To my personal knowledge it's been observed by at least 20 different people using widely different PC's (graphic drivers) , on Windows 10 with Chrome and PDFJS.


On Windows 10 if you don't use PDFJS and try the Chrome native viewer it displays correctly. 
Firefox PC and all Mac seem ok. 

So you can say it's only a combo of Windows 10 and Chrome and PDFJS issue.
But since the Windows 10/Chrome combo accounts for over 75% of usage its effecting pretty much everyone.

**Comment by Snuffleupagus** [comment] 2021-07-27 13:48
Given that this works fine in Firefox Nightly 92.0a1 (2021-07-27), tested with its built-in PDF viewer (version `2.11.5`), closing as WORKSFORME since we cannot really fix a browser/driver bug here (and please note that Firefox is the main focus of development).

**Closed by Snuffleupagus** 2021-07-27 13:48 UTC
Labels: 1-other
