### ISSUE TITLE
fit printing content to printer margins when required

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#8832] opened 2017-08-27 20:06 UTC
Would it be possible that, such as _SumatraPDF_ does, _PDF.js_ fits printing contents to printer margins **only when required**?

I attach a [PDF document](https://github.com/mozilla/pdf.js/files/1254684/a.pdf) in A4 paper size and no margins.

**Comment by ousia** [comment] 2017-08-27 20:10
I think #8701 depends on this. And #8550 might depend on this too.

**Comment by yurydelendik** [comment] 2017-08-30 13:28
Browser has not access or cannot control printing settings. Closing as duplicate of #8839

**Closed by yurydelendik** 2017-08-30 13:28 UTC
Labels: 4-printing
