### ISSUE TITLE
File renders blank white canvas on iOS

### ISSUE THREAD

**Issue by kinztechcom** [mozilla/pdf.js#9176] opened 2017-11-21 20:12 UTC
Attach (recommended) or Link to PDF file here:
[Donahue Crossing.pdf](https://github.com/mozilla/pdf.js/files/1492826/Donahue.Crossing.pdf)

Configuration:
- Web browser and its version: Safari Latest
- Operating system and its version: iOS 11.1.1
- PDF.js version: v1.10.88

Steps to reproduce the problem:
1. Load attached file in any pdf.js renderer or viewer.

What is the expected behavior? (add screenshot)
Rendering of PDF

What went wrong? (add screenshot)
Blank white canvas is shown rather than the pdf. 
This only happens on iOS browsers. It works on all browsers for windows and all browsers for MacOS. It also works on Google Chrome on an Android device.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by ClarkXia** [comment] 2018-01-03 07:28
I have the same problem with pdf file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/1599652/test.pdf)

**Comment by georgeemr** [comment] 2018-02-05 18:35
same

**Comment by kinztechcom** [comment] 2018-04-20 14:11
[Courtridge_Gardner.pdf](https://github.com/mozilla/pdf.js/files/1932408/Courtridge_Gardner.pdf)

It is also occurring for this document. Any update on this or idea as to why it is happening?

**Comment by wklu** [comment] 2018-05-09 01:48
在IOS中，默认字体分为三类：

1：STHeiti-Light.ttc和STHeiti-Medium.ttc代表汉字。

2：_H_Helvetica.ttc和_H_HelveticaNeue.ttc代表英文和数字字体。

3：LockClock.ttf代表锁屏时间字体。

如果PDF有其他字体，IOS将需要很长时间。
解决方案：请更改字体或插入字体

**Comment by Snuffleupagus** [comment] 2021-09-29 08:13
Duplicate of #9474

**Closed by Snuffleupagus** 2021-09-29 08:13 UTC
Labels: 1-viewer, 4-os-ios
