### ISSUE TITLE
Performance issue getTextContent() method

### ISSUE THREAD

**Issue by thomas-ama** [mozilla/pdf.js#11368] opened 2019-11-28 11:25 UTC
**Configuration:**
- Web browser and its version:
Google Chrome 78.0.3904.108 / Opera 64.0.3417.92
- Operating system and its version:
macOS Majove 10.14.6
- PDF.js version:
2.0.550: No bugs
2.2.228: Bug
2.3.200: Bug
- Is a browser extension:
No

**PDF used**
216 pages
http://www.montefiore.ulg.ac.be/~boigelot/cours/oop/slides/oop.pdf

**Steps to reproduce the problem:**
I am using PDFJS (`pdfjs-dist`) to render all pages in an iframe. I loop sequentially on pages:
- I use the `render()` method to render the current page
- I use the `getTextContent()` method to apply custom text highlights on the text layer

This process was quite fast using version 2.0.550.

However, since version 2.2.228, the `getTextContent()` method has performance issues:
- For the first 50 pages of the PDF, the method is executed at a normal speed (~100ms)
- For the following pages, the method is executed 10 times slower (~1s-3s)

I measure the execution time as follows:
```
let startTime;
...
.then(() =>
{
  startTime = Date.now();
  return page.getTextContent();
})
.then((textContent) =>
{
  console.log(Date.now() - startTime, pageNumber);
  ...
})
```

Do you have any idea what caused this performance problem on Google Chrome/Opera?

**Comment by Snuffleupagus** [comment] 2019-11-28 11:54
> PDF.js version:
> 2.0.550: No bugs
> 2.2.228: Bug
> 2.3.200: Bug

*Please note:* `2.0.550` wasn't an official stable release, as listed on https://github.com/mozilla/pdf.js/releases

The first thing to do here, given that it appears to be a regression, would be to use `git bisect` to find the *exact* commit in which the problem started. (For information about obtaining the code, please see https://github.com/mozilla/pdf.js#getting-the-code)

> I measure the execution time as follows: [...]

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine), which is especially important if you're not able to run `git bisect` yourself:
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Finally, note that the default viewer is no longer using [`getTextContent` ](https://github.com/mozilla/pdf.js/blob/dcf998a1c1737be3d14b68f378a18ea32df2cbe7/src/display/api.js#L1185-L1213) when creating the textLayer, instead the [`streamTextContent`](https://github.com/mozilla/pdf.js/blob/dcf998a1c1737be3d14b68f378a18ea32df2cbe7/src/display/api.js#L1165-L1183) method is being used.

**Comment by Snuffleupagus** [comment] 2019-11-29 11:04
Given that there's no link to a *runnable* test-case in https://github.com/mozilla/pdf.js/issues/11368#issue-529854671, it's very difficult to know exactly how this was tested.

As mentioned above, the default viewer isn't using `getTextContent` for the textLayer. However, that method is being used by [`PDFFindController`](https://github.com/mozilla/pdf.js/blob/dcf998a1c1737be3d14b68f378a18ea32df2cbe7/web/pdf_find_controller.js) when searching occurs in the document. Just to have *something* to test here, I've modified the code according to the following diff:
```diff
diff --git a/web/pdf_find_controller.js b/web/pdf_find_controller.js
index 63ba44dc..8fbbc3bd 100644
--- a/web/pdf_find_controller.js
+++ b/web/pdf_find_controller.js
@@ -443,12 +443,15 @@ class PDFFindController {
       const extractTextCapability = createPromiseCapability();
       this._extractTextPromises[i] = extractTextCapability.promise;
 
+      let start;
       promise = promise.then(() => {
         return this._pdfDocument.getPage(i + 1).then((pdfPage) => {
+          start = Date.now();
           return pdfPage.getTextContent({
             normalizeWhitespace: true,
           });
         }).then((textContent) => {
+          console.log(`page ${i + 1}: ${Date.now() - start} ms`);
           const textItems = textContent.items;
           const strBuf = [];
```
Testing that code locally with the *latest* development version of PDF.js (`2.4.154` as of this writing), in Windows 7, yields the results below for Firefox Nightly 72 and Chrome Beta 79.
Based on these results it's not really clear (at least to me) that there's even a problem here, let alone that it's a regression. It could be that it's *platform* dependent, or an issue with the way that `getTextContent` is used in your case, or something else...

All in all, without a complete test-case there's probably not much that can be done here unfortunately.

---

 - With Firefox Nightly 72
```
PDF 2ea3df525368c4ed649e2936d0c68068 [1.5 pdfTeX-1.40.17 / TeX] (PDF.js: -) app.js:2185:21
page 1: 18 ms pdf_find_controller.js:432:27
page 2: 4 ms pdf_find_controller.js:432:27
page 3: 56 ms pdf_find_controller.js:432:27
page 4: 36 ms pdf_find_controller.js:432:27
page 5: 19 ms pdf_find_controller.js:432:27
page 6: 7 ms pdf_find_controller.js:432:27
page 7: 4 ms pdf_find_controller.js:432:27
page 8: 11 ms pdf_find_controller.js:432:27
page 9: 5 ms pdf_find_controller.js:432:27
page 10: 6 ms pdf_find_controller.js:432:27
page 11: 5 ms pdf_find_controller.js:432:27
page 12: 10 ms pdf_find_controller.js:432:27
page 13: 4 ms pdf_find_controller.js:432:27
page 14: 5 ms pdf_find_controller.js:432:27
page 15: 3 ms pdf_find_controller.js:432:27
page 16: 10 ms pdf_find_controller.js:432:27
page 17: 5 ms pdf_find_controller.js:432:27
page 18: 15 ms pdf_find_controller.js:432:27
page 19: 7 ms pdf_find_controller.js:432:27
page 20: 5 ms pdf_find_controller.js:432:27
page 21: 3 ms pdf_find_controller.js:432:27
page 22: 0 ms pdf_find_controller.js:432:27
page 23: 3 ms pdf_find_controller.js:432:27
page 24: 3 ms pdf_find_controller.js:432:27
page 25: 4 ms pdf_find_controller.js:432:27
page 26: 9 ms pdf_find_controller.js:432:27
page 27: 6 ms pdf_find_controller.js:432:27
page 28: 3 ms pdf_find_controller.js:432:27
page 29: 4 ms pdf_find_controller.js:432:27
page 30: 4 ms pdf_find_controller.js:432:27
page 31: 4 ms pdf_find_controller.js:432:27
page 32: 4 ms pdf_find_controller.js:432:27
page 33: 3 ms pdf_find_controller.js:432:27
page 34: 2 ms pdf_find_controller.js:432:27
page 35: 5 ms pdf_find_controller.js:432:27
page 36: 4 ms pdf_find_controller.js:432:27
page 37: 5 ms pdf_find_controller.js:432:27
page 38: 4 ms pdf_find_controller.js:432:27
page 39: 5 ms pdf_find_controller.js:432:27
page 40: 4 ms pdf_find_controller.js:432:27
page 41: 4 ms pdf_find_controller.js:432:27
page 42: 6 ms pdf_find_controller.js:432:27
page 43: 3 ms pdf_find_controller.js:432:27
page 44: 5 ms pdf_find_controller.js:432:27
page 45: 4 ms pdf_find_controller.js:432:27
page 46: 1 ms pdf_find_controller.js:432:27
page 47: 6 ms pdf_find_controller.js:432:27
page 48: 3 ms pdf_find_controller.js:432:27
page 49: 3 ms pdf_find_controller.js:432:27
page 50: 2 ms pdf_find_controller.js:432:27
page 51: 6 ms pdf_find_controller.js:432:27
page 52: 4 ms pdf_find_controller.js:432:27
page 53: 9 ms pdf_find_controller.js:432:27
page 54: 6 ms pdf_find_controller.js:432:27
page 55: 3 ms pdf_find_controller.js:432:27
page 56: 14 ms pdf_find_controller.js:432:27
page 57: 4 ms pdf_find_controller.js:432:27
page 58: 4 ms pdf_find_controller.js:432:27
page 59: 2 ms pdf_find_controller.js:432:27
page 60: 3 ms pdf_find_controller.js:432:27
page 61: 4 ms pdf_find_controller.js:432:27
page 62: 4 ms pdf_find_controller.js:432:27
page 63: 1 ms pdf_find_controller.js:432:27
page 64: 6 ms pdf_find_controller.js:432:27
page 65: 18 ms pdf_find_controller.js:432:27
page 66: 2 ms pdf_find_controller.js:432:27
page 67: 4 ms pdf_find_controller.js:432:27
page 68: 4 ms pdf_find_controller.js:432:27
page 69: 6 ms pdf_find_controller.js:432:27
page 70: 4 ms pdf_find_controller.js:432:27
page 71: 5 ms pdf_find_controller.js:432:27
page 72: 3 ms pdf_find_controller.js:432:27
page 73: 5 ms pdf_find_controller.js:432:27
page 74: 6 ms pdf_find_controller.js:432:27
page 75: 3 ms pdf_find_controller.js:432:27
page 76: 1 ms pdf_find_controller.js:432:27
page 77: 3 ms pdf_find_controller.js:432:27
page 78: 2 ms pdf_find_controller.js:432:27
page 79: 3 ms pdf_find_controller.js:432:27
page 80: 3 ms pdf_find_controller.js:432:27
page 81: 2 ms pdf_find_controller.js:432:27
page 82: 4 ms pdf_find_controller.js:432:27
page 83: 4 ms pdf_find_controller.js:432:27
page 84: 6 ms pdf_find_controller.js:432:27
page 85: 3 ms pdf_find_controller.js:432:27
page 86: 7 ms pdf_find_controller.js:432:27
page 87: 2 ms pdf_find_controller.js:432:27
page 88: 4 ms pdf_find_controller.js:432:27
page 89: 7 ms pdf_find_controller.js:432:27
page 90: 2 ms pdf_find_controller.js:432:27
page 91: 5 ms pdf_find_controller.js:432:27
page 92: 1 ms pdf_find_controller.js:432:27
page 93: 4 ms pdf_find_controller.js:432:27
page 94: 6 ms pdf_find_controller.js:432:27
page 95: 2 ms pdf_find_controller.js:432:27
page 96: 3 ms pdf_find_controller.js:432:27
page 97: 4 ms pdf_find_controller.js:432:27
page 98: 1 ms pdf_find_controller.js:432:27
page 99: 2 ms pdf_find_controller.js:432:27
page 100: 4 ms pdf_find_controller.js:432:27
page 101: 3 ms pdf_find_controller.js:432:27
page 102: 6 ms pdf_find_controller.js:432:27
page 103: 4 ms pdf_find_controller.js:432:27
page 104: 3 ms pdf_find_controller.js:432:27
page 105: 5 ms pdf_find_controller.js:432:27
page 106: 3 ms pdf_find_controller.js:432:27
page 107: 3 ms pdf_find_controller.js:432:27
page 108: 4 ms pdf_find_controller.js:432:27
page 109: 4 ms pdf_find_controller.js:432:27
page 110: 4 ms pdf_find_controller.js:432:27
page 111: 4 ms pdf_find_controller.js:432:27
page 112: 3 ms pdf_find_controller.js:432:27
page 113: 4 ms pdf_find_controller.js:432:27
page 114: 4 ms pdf_find_controller.js:432:27
page 115: 3 ms pdf_find_controller.js:432:27
page 116: 3 ms pdf_find_controller.js:432:27
page 117: 3 ms pdf_find_controller.js:432:27
page 118: 4 ms pdf_find_controller.js:432:27
page 119: 6 ms pdf_find_controller.js:432:27
page 120: 6 ms pdf_find_controller.js:432:27
page 121: 3 ms pdf_find_controller.js:432:27
page 122: 3 ms pdf_find_controller.js:432:27
page 123: 6 ms pdf_find_controller.js:432:27
page 124: 4 ms pdf_find_controller.js:432:27
page 125: 5 ms pdf_find_controller.js:432:27
page 126: 5 ms pdf_find_controller.js:432:27
page 127: 3 ms pdf_find_controller.js:432:27
page 128: 3 ms pdf_find_controller.js:432:27
page 129: 3 ms pdf_find_controller.js:432:27
page 130: 4 ms pdf_find_controller.js:432:27
page 131: 4 ms pdf_find_controller.js:432:27
page 132: 3 ms pdf_find_controller.js:432:27
page 133: 3 ms pdf_find_controller.js:432:27
page 134: 3 ms pdf_find_controller.js:432:27
page 135: 3 ms pdf_find_controller.js:432:27
page 136: 10 ms pdf_find_controller.js:432:27
page 137: 3 ms pdf_find_controller.js:432:27
page 138: 4 ms pdf_find_controller.js:432:27
page 139: 4 ms pdf_find_controller.js:432:27
page 140: 4 ms pdf_find_controller.js:432:27
page 141: 3 ms pdf_find_controller.js:432:27
page 142: 2 ms pdf_find_controller.js:432:27
page 143: 5 ms pdf_find_controller.js:432:27
page 144: 4 ms pdf_find_controller.js:432:27
page 145: 2 ms pdf_find_controller.js:432:27
page 146: 3 ms pdf_find_controller.js:432:27
page 147: 4 ms pdf_find_controller.js:432:27
page 148: 2 ms pdf_find_controller.js:432:27
page 149: 2 ms pdf_find_controller.js:432:27
page 150: 4 ms pdf_find_controller.js:432:27
page 151: 7 ms pdf_find_controller.js:432:27
page 152: 3 ms pdf_find_controller.js:432:27
page 153: 3 ms pdf_find_controller.js:432:27
page 154: 3 ms pdf_find_controller.js:432:27
page 155: 5 ms pdf_find_controller.js:432:27
page 156: 1 ms pdf_find_controller.js:432:27
page 157: 4 ms pdf_find_controller.js:432:27
page 158: 2 ms pdf_find_controller.js:432:27
page 159: 6 ms pdf_find_controller.js:432:27
page 160: 1 ms pdf_find_controller.js:432:27
page 161: 5 ms pdf_find_controller.js:432:27
page 162: 9 ms pdf_find_controller.js:432:27
page 163: 7 ms pdf_find_controller.js:432:27
page 164: 4 ms pdf_find_controller.js:432:27
page 165: 6 ms pdf_find_controller.js:432:27
page 166: 15 ms pdf_find_controller.js:432:27
page 167: 7 ms pdf_find_controller.js:432:27
page 168: 2 ms pdf_find_controller.js:432:27
page 169: 5 ms pdf_find_controller.js:432:27
page 170: 4 ms pdf_find_controller.js:432:27
page 171: 3 ms pdf_find_controller.js:432:27
page 172: 6 ms pdf_find_controller.js:432:27
page 173: 3 ms pdf_find_controller.js:432:27
page 174: 1 ms pdf_find_controller.js:432:27
page 175: 3 ms pdf_find_controller.js:432:27
page 176: 3 ms pdf_find_controller.js:432:27
page 177: 3 ms pdf_find_controller.js:432:27
page 178: 5 ms pdf_find_controller.js:432:27
page 179: 3 ms pdf_find_controller.js:432:27
page 180: 5 ms pdf_find_controller.js:432:27
page 181: 4 ms pdf_find_controller.js:432:27
page 182: 3 ms pdf_find_controller.js:432:27
page 183: 1 ms pdf_find_controller.js:432:27
page 184: 2 ms pdf_find_controller.js:432:27
page 185: 5 ms pdf_find_controller.js:432:27
page 186: 3 ms pdf_find_controller.js:432:27
page 187: 5 ms pdf_find_controller.js:432:27
page 188: 3 ms pdf_find_controller.js:432:27
page 189: 7 ms pdf_find_controller.js:432:27
page 190: 4 ms pdf_find_controller.js:432:27
page 191: 5 ms pdf_find_controller.js:432:27
page 192: 5 ms pdf_find_controller.js:432:27
page 193: 4 ms pdf_find_controller.js:432:27
page 194: 1 ms pdf_find_controller.js:432:27
page 195: 3 ms pdf_find_controller.js:432:27
page 196: 4 ms pdf_find_controller.js:432:27
page 197: 2 ms pdf_find_controller.js:432:27
page 198: 4 ms pdf_find_controller.js:432:27
page 199: 5 ms pdf_find_controller.js:432:27
page 200: 4 ms pdf_find_controller.js:432:27
page 201: 3 ms pdf_find_controller.js:432:27
page 202: 3 ms pdf_find_controller.js:432:27
page 203: 2 ms pdf_find_controller.js:432:27
page 204: 4 ms pdf_find_controller.js:432:27
page 205: 4 ms pdf_find_controller.js:432:27
page 206: 4 ms pdf_find_controller.js:432:27
page 207: 6 ms pdf_find_controller.js:432:27
page 208: 3 ms pdf_find_controller.js:432:27
page 209: 4 ms pdf_find_controller.js:432:27
page 210: 4 ms pdf_find_controller.js:432:27
page 211: 4 ms pdf_find_controller.js:432:27
page 212: 3 ms pdf_find_controller.js:432:27
page 213: 2 ms pdf_find_controller.js:432:27
page 214: 4 ms pdf_find_controller.js:432:27
page 215: 4 ms pdf_find_controller.js:432:27
page 216: 5 ms pdf_find_controller.js:432:27
```
 - With Chrome Beta 79
```
PDF 2ea3df525368c4ed649e2936d0c68068 [1.5 pdfTeX-1.40.17 / TeX] (PDF.js: -)
pdf_find_controller.js:432 page 1: 9 ms
pdf_find_controller.js:432 page 2: 2 ms
pdf_find_controller.js:432 page 3: 24 ms
pdf_find_controller.js:432 page 4: 16 ms
pdf_find_controller.js:432 page 5: 13 ms
pdf_find_controller.js:432 page 6: 5 ms
pdf_find_controller.js:432 page 7: 5 ms
pdf_find_controller.js:432 page 8: 9 ms
pdf_find_controller.js:432 page 9: 5 ms
pdf_find_controller.js:432 page 10: 4 ms
pdf_find_controller.js:432 page 11: 6 ms
pdf_find_controller.js:432 page 12: 9 ms
pdf_find_controller.js:432 page 13: 3 ms
pdf_find_controller.js:432 page 14: 5 ms
pdf_find_controller.js:432 page 15: 2 ms
pdf_find_controller.js:432 page 16: 8 ms
pdf_find_controller.js:432 page 17: 4 ms
pdf_find_controller.js:432 page 18: 8 ms
pdf_find_controller.js:432 page 19: 3 ms
pdf_find_controller.js:432 page 20: 4 ms
pdf_find_controller.js:432 page 21: 7 ms
pdf_find_controller.js:432 page 22: 1 ms
pdf_find_controller.js:432 page 23: 6 ms
pdf_find_controller.js:432 page 24: 7 ms
pdf_find_controller.js:432 page 25: 4 ms
pdf_find_controller.js:432 page 26: 8 ms
pdf_find_controller.js:432 page 27: 4 ms
pdf_find_controller.js:432 page 28: 3 ms
pdf_find_controller.js:432 page 29: 4 ms
pdf_find_controller.js:432 page 30: 3 ms
pdf_find_controller.js:432 page 31: 4 ms
pdf_find_controller.js:432 page 32: 2 ms
pdf_find_controller.js:432 page 33: 3 ms
pdf_find_controller.js:432 page 34: 2 ms
pdf_find_controller.js:432 page 35: 8 ms
pdf_find_controller.js:432 page 36: 2 ms
pdf_find_controller.js:432 page 37: 4 ms
pdf_find_controller.js:432 page 38: 5 ms
pdf_find_controller.js:432 page 39: 6 ms
pdf_find_controller.js:432 page 40: 4 ms
pdf_find_controller.js:432 page 41: 5 ms
pdf_find_controller.js:432 page 42: 7 ms
pdf_find_controller.js:432 page 43: 4 ms
pdf_find_controller.js:432 page 44: 6 ms
pdf_find_controller.js:432 page 45: 3 ms
pdf_find_controller.js:432 page 46: 2 ms
pdf_find_controller.js:432 page 47: 3 ms
pdf_find_controller.js:432 page 48: 3 ms
pdf_find_controller.js:432 page 49: 3 ms
pdf_find_controller.js:432 page 50: 1 ms
pdf_find_controller.js:432 page 51: 13 ms
pdf_find_controller.js:432 page 52: 5 ms
pdf_find_controller.js:432 page 53: 9 ms
pdf_find_controller.js:432 page 54: 4 ms
pdf_find_controller.js:432 page 55: 3 ms
pdf_find_controller.js:432 page 56: 15 ms
pdf_find_controller.js:432 page 57: 4 ms
pdf_find_controller.js:432 page 58: 11 ms
pdf_find_controller.js:432 page 59: 1 ms
pdf_find_controller.js:432 page 60: 4 ms
pdf_find_controller.js:432 page 61: 4 ms
pdf_find_controller.js:432 page 62: 3 ms
pdf_find_controller.js:432 page 63: 2 ms
pdf_find_controller.js:432 page 64: 5 ms
pdf_find_controller.js:432 page 65: 12 ms
pdf_find_controller.js:432 page 66: 3 ms
pdf_find_controller.js:432 page 67: 4 ms
pdf_find_controller.js:432 page 68: 3 ms
pdf_find_controller.js:432 page 69: 4 ms
pdf_find_controller.js:432 page 70: 6 ms
pdf_find_controller.js:432 page 71: 3 ms
pdf_find_controller.js:432 page 72: 29 ms
pdf_find_controller.js:432 page 73: 9 ms
pdf_find_controller.js:432 page 74: 9 ms
pdf_find_controller.js:432 page 75: 61 ms
pdf_find_controller.js:432 page 76: 8 ms
pdf_find_controller.js:432 page 77: 7 ms
pdf_find_controller.js:432 page 78: 3 ms
pdf_find_controller.js:432 page 79: 2 ms
pdf_find_controller.js:432 page 80: 2 ms
pdf_find_controller.js:432 page 81: 2 ms
pdf_find_controller.js:432 page 82: 3 ms
pdf_find_controller.js:432 page 83: 2 ms
pdf_find_controller.js:432 page 84: 4 ms
pdf_find_controller.js:432 page 85: 2 ms
pdf_find_controller.js:432 page 86: 4 ms
pdf_find_controller.js:432 page 87: 2 ms
pdf_find_controller.js:432 page 88: 2 ms
pdf_find_controller.js:432 page 89: 4 ms
pdf_find_controller.js:432 page 90: 3 ms
pdf_find_controller.js:432 page 91: 9 ms
pdf_find_controller.js:432 page 92: 3 ms
pdf_find_controller.js:432 page 93: 4 ms
pdf_find_controller.js:432 page 94: 5 ms
pdf_find_controller.js:432 page 95: 4 ms
pdf_find_controller.js:432 page 96: 14 ms
pdf_find_controller.js:432 page 97: 4 ms
pdf_find_controller.js:432 page 98: 1 ms
pdf_find_controller.js:432 page 99: 3 ms
pdf_find_controller.js:432 page 100: 2 ms
pdf_find_controller.js:432 page 101: 4 ms
pdf_find_controller.js:432 page 102: 4 ms
pdf_find_controller.js:432 page 103: 3 ms
pdf_find_controller.js:432 page 104: 8 ms
pdf_find_controller.js:432 page 105: 4 ms
pdf_find_controller.js:432 page 106: 2 ms
pdf_find_controller.js:432 page 107: 1 ms
pdf_find_controller.js:432 page 108: 4 ms
pdf_find_controller.js:432 page 109: 2 ms
pdf_find_controller.js:432 page 110: 3 ms
pdf_find_controller.js:432 page 111: 2 ms
pdf_find_controller.js:432 page 112: 2 ms
pdf_find_controller.js:432 page 113: 2 ms
pdf_find_controller.js:432 page 114: 6 ms
pdf_find_controller.js:432 page 115: 3 ms
pdf_find_controller.js:432 page 116: 4 ms
pdf_find_controller.js:432 page 117: 3 ms
pdf_find_controller.js:432 page 118: 4 ms
pdf_find_controller.js:432 page 119: 5 ms
pdf_find_controller.js:432 page 120: 5 ms
pdf_find_controller.js:432 page 121: 4 ms
pdf_find_controller.js:432 page 122: 3 ms
pdf_find_controller.js:432 page 123: 4 ms
pdf_find_controller.js:432 page 124: 5 ms
pdf_find_controller.js:432 page 125: 3 ms
pdf_find_controller.js:432 page 126: 3 ms
pdf_find_controller.js:432 page 127: 4 ms
pdf_find_controller.js:432 page 128: 7 ms
pdf_find_controller.js:432 page 129: 4 ms
pdf_find_controller.js:432 page 130: 4 ms
pdf_find_controller.js:432 page 131: 4 ms
pdf_find_controller.js:432 page 132: 3 ms
pdf_find_controller.js:432 page 133: 1 ms
pdf_find_controller.js:432 page 134: 3 ms
pdf_find_controller.js:432 page 135: 3 ms
pdf_find_controller.js:432 page 136: 2 ms
pdf_find_controller.js:432 page 137: 4 ms
pdf_find_controller.js:432 page 138: 2 ms
pdf_find_controller.js:432 page 139: 3 ms
pdf_find_controller.js:432 page 140: 6 ms
pdf_find_controller.js:432 page 141: 3 ms
pdf_find_controller.js:432 page 142: 4 ms
pdf_find_controller.js:432 page 143: 5 ms
pdf_find_controller.js:432 page 144: 4 ms
pdf_find_controller.js:432 page 145: 2 ms
pdf_find_controller.js:432 page 146: 2 ms
pdf_find_controller.js:432 page 147: 2 ms
pdf_find_controller.js:432 page 148: 1 ms
pdf_find_controller.js:432 page 149: 3 ms
pdf_find_controller.js:432 page 150: 2 ms
pdf_find_controller.js:432 page 151: 5 ms
pdf_find_controller.js:432 page 152: 4 ms
pdf_find_controller.js:432 page 153: 6 ms
pdf_find_controller.js:432 page 154: 15 ms
pdf_find_controller.js:432 page 155: 9 ms
pdf_find_controller.js:432 page 156: 3 ms
pdf_find_controller.js:432 page 157: 8 ms
pdf_find_controller.js:432 page 158: 3 ms
pdf_find_controller.js:432 page 159: 5 ms
pdf_find_controller.js:432 page 160: 2 ms
pdf_find_controller.js:432 page 161: 5 ms
pdf_find_controller.js:432 page 162: 6 ms
pdf_find_controller.js:432 page 163: 12 ms
pdf_find_controller.js:432 page 164: 11 ms
pdf_find_controller.js:432 page 165: 6 ms
pdf_find_controller.js:432 page 166: 17 ms
pdf_find_controller.js:432 page 167: 7 ms
pdf_find_controller.js:432 page 168: 5 ms
pdf_find_controller.js:432 page 169: 4 ms
pdf_find_controller.js:432 page 170: 6 ms
pdf_find_controller.js:432 page 171: 3 ms
pdf_find_controller.js:432 page 172: 3 ms
pdf_find_controller.js:432 page 173: 2 ms
pdf_find_controller.js:432 page 174: 2 ms
pdf_find_controller.js:432 page 175: 2 ms
pdf_find_controller.js:432 page 176: 2 ms
pdf_find_controller.js:432 page 177: 3 ms
pdf_find_controller.js:432 page 178: 5 ms
pdf_find_controller.js:432 page 179: 3 ms
pdf_find_controller.js:432 page 180: 6 ms
pdf_find_controller.js:432 page 181: 3 ms
pdf_find_controller.js:432 page 182: 4 ms
pdf_find_controller.js:432 page 183: 2 ms
pdf_find_controller.js:432 page 184: 4 ms
pdf_find_controller.js:432 page 185: 3 ms
pdf_find_controller.js:432 page 186: 3 ms
pdf_find_controller.js:432 page 187: 7 ms
pdf_find_controller.js:432 page 188: 3 ms
pdf_find_controller.js:432 page 189: 6 ms
pdf_find_controller.js:432 page 190: 4 ms
pdf_find_controller.js:432 page 191: 4 ms
pdf_find_controller.js:432 page 192: 5 ms
pdf_find_controller.js:432 page 193: 5 ms
pdf_find_controller.js:432 page 194: 2 ms
pdf_find_controller.js:432 page 195: 3 ms
pdf_find_controller.js:432 page 196: 3 ms
pdf_find_controller.js:432 page 197: 2 ms
pdf_find_controller.js:432 page 198: 3 ms
pdf_find_controller.js:432 page 199: 3 ms
pdf_find_controller.js:432 page 200: 2 ms
pdf_find_controller.js:432 page 201: 3 ms
pdf_find_controller.js:432 page 202: 3 ms
pdf_find_controller.js:432 page 203: 4 ms
pdf_find_controller.js:432 page 204: 2 ms
pdf_find_controller.js:432 page 205: 3 ms
pdf_find_controller.js:432 page 206: 3 ms
pdf_find_controller.js:432 page 207: 3 ms
pdf_find_controller.js:432 page 208: 3 ms
pdf_find_controller.js:432 page 209: 4 ms
pdf_find_controller.js:432 page 210: 3 ms
pdf_find_controller.js:432 page 211: 2 ms
pdf_find_controller.js:432 page 212: 4 ms
pdf_find_controller.js:432 page 213: 3 ms
pdf_find_controller.js:432 page 214: 3 ms
pdf_find_controller.js:432 page 215: 3 ms
pdf_find_controller.js:432 page 216: 3 ms
```

**Comment by thomas-ama** [comment] 2019-12-02 11:35
Thank you for your answers Snuffleupagus!

While looking for the cause of the problem, I realized that the `getTextContent` execution time was only a side effect of the real problem.

The real problem seems to be related to canvas memory, when canvases are large.

I created a [Fiddle](https://jsfiddle.net/ama_dev/uvcpdr98/) where I render the pages of my PDF one at a time then add them in a `div`.

When the `scale` is equal to `0.8`, this code works on all browsers.

When it is equal to `3`:
- On FF, the code works
- On Google Chrome and Opera, the tab crashes
- On Safari, warnings are displayed, canvas are not always well rendered
> Total canvas memory use exceeds the maximum limit (2151 MB)

The Fiddle uses PDFJS version `2.2.228`.

As mentioned in my first message, there was no canvas memory problem with version `2.0.550`.

Unfortunately, I didn't manage to test my Fiddle with a previous version (version `2.0.550` for example). Canvases are not rendered I don't know why.

Do you have any idea of a change that could have affected canvas memory?

**Comment by Snuffleupagus** [comment] 2019-12-02 11:47
> I created a [Fiddle](https://jsfiddle.net/ama_dev/uvcpdr98/) where I render the pages of my PDF one at a time then add them in a `div`.

As mentioned in the Wiki, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages, rendering all of the pages at once is simply *never* a good idea!

**Comment by thomas-ama** [comment] 2019-12-02 13:06
Unfortunately, I'm generating a printable web page that must contain all pages.

In high resolution mode (300 ppi), canvases are quite big. I guess I have to forbid high resolution print for large PDF or do it server-side.

I understand that PDFJS won't make changes to deal with my use case.

Thank you for your quick answers Snuffleupagus.

**Comment by timvandermeij** [comment] 2019-12-02 23:29
Closing since this is answered. Rendering all pages is a heavy operation that, depending on the resolution, most browsers won't handle well. This is a browser limitation; perhaps the experimental SVG back-end could provide a solution for this, but it's not production-ready yet. Refer to https://github.com/mozilla/pdf.js/projects/2 for the tracking of that feature.

**Closed by timvandermeij** 2019-12-02 23:29 UTC
Labels: 2-performance, 3-regression, 4-text-selection
