### ISSUE TITLE
PDF with 2400 DPI scanned image won't render.

### ISSUE THREAD

**Issue by kwank555** [mozilla/pdf.js#10830] opened 2019-05-16 17:25 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 65.0.1 64-bit, Chrome 72.0.3626.121 64-bit
- Operating system and its version: Windows 10.0.16299
- PDF.js version: 2.1.266
- Is a browser extension:

Steps to reproduce the problem:
1. Try to open the file in question.

What is the expected behavior? (add screenshot)
The PDF file should be rendered.

What went wrong? (add screenshot)
Just a blank screen was displayed.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2019-05-16 19:22
Closing since this is a duplicate of #6419.

**Closed by timvandermeij** 2019-05-16 19:22 UTC
