### ISSUE TITLE
App crashesh

### ISSUE THREAD

**Issue by awadeyar** [mozilla/pdf.js#6703] opened 2015-11-30 05:29 UTC
Hi,

When I load 2 to 3 pdf the App crashes and gives error 
"GL_OUT_OF_MEMORY".

I think pdf.js is not releasing the memory it took to render the pdf page.

Thanks,
Amasid.

**Comment by timvandermeij** [comment] 2015-11-30 12:56
We need a link to the PDF files as we are not able to reproduce this otherwise. It's likely that the PDFs are not optimized for web usage. Be sure to read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md too.

**Comment by timvandermeij** [comment] 2015-12-02 22:08
Closing as incomplete until the information requested above is provided.

**Closed by timvandermeij** 2015-12-02 22:08 UTC
Labels: 4-information-requested
