### ISSUE TITLE
PDF preview is displayed incorrectly, with artifacts, on Chrome and Edge, on Intel Iris Xe

### ISSUE THREAD

**Issue by bart1924** [mozilla/pdf.js#15918] opened 2023-01-13 11:31 UTC
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples

Configuration:
- pdf.js version = ^3.1.81 (bug is reproducible on older versions too)
- OS: Windows 10 (up-to-date)
- Browsers: Chrome and Edge (up-to-date)
- GPU: Intel(R) Iris(R) Xe Graphics, driver version: 31.0.101.3413

Steps to reproduce the problem:
1. Open https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples
2. Move to "Previous/Next example"
3. Press "Result"
4. PDF is displayed with artifacts

What is the expected behavior?
![image](https://user-images.githubusercontent.com/122609502/212307768-acc1af98-8741-444e-b031-daab11942aac.png)

What went wrong?
![image](https://user-images.githubusercontent.com/122609502/212307835-e040bd5f-fef9-4f70-a206-4a2ecc07c580.png)

This bug occurs on many computers with Intel Iris Xe, on Chrome and Edge web browsers. On Firefox everything is ok.
Moreover, on others graphic cards, pdf is displayed correctly on all web browsers.

**Comment by Snuffleupagus** [comment] 2023-01-13 11:39
Duplicate of e.g. issue https://github.com/mozilla/pdf.js/issues/14641.

**Closed by Snuffleupagus** 2023-01-13 11:39 UTC
