### ISSUE TITLE
I am not able to search content in PDF

### ISSUE THREAD

**Issue by dhanbhan** [mozilla/pdf.js#17850] opened 2024-03-27 07:11 UTC
Attach (recommended) or Link to PDF file here:
[HebrewText.pdf](https://github.com/mozilla/pdf.js/files/14769363/HebrewText.pdf)

Configuration:
- Web browser and its version: Firefox 124
- Operating system and its version: Mac OS
- PDF.js version: v4.0.379
- Is a browser extension: NO

Steps to reproduce the problem:
1. Open attached document in Mozila firefox
2. search for the available content `ההתרחבות הבינלאומית התרחשה גם היא`

What is the expected behavior? (add screenshot)
I should be able to search multi word contents in PDF when underlying Language is RTL (Hebreww in this case)
Why pdf.js fails to search such cases ? It is a show stopper in large scale when it comes to RTL languages. 

What went wrong? (add screenshot)
Multi word content search is not possible in PDF documents1.  with RTL language where as I can do the search when same PDF is opened in chrome browser directly.

**Comment by Snuffleupagus** [comment] 2024-03-27 07:49
Duplicate of #16716

**Closed by Snuffleupagus** 2024-03-27 07:49 UTC

**Comment by dhanbhan** [comment] 2024-03-27 08:03
@Snuffleupagus May I know next plans by pdf.js on searching multi words in PDF containing RTL languages ? 

Can you please share some details to make us aware if PDF.js consider this as defect to address or permanent limitation  ?

Many thanks!
