### ISSUE TITLE
How can I change the locale option and update the Viewer UI?

### ISSUE THREAD

**Issue by carloshpds** [mozilla/pdf.js#17572] opened 2024-01-24 14:24 UTC
How can I change the locale option and update the Viewer UI? 

Configuration:
- Web browser and its version: Brave 1.61.120
- Operating system and its version: MacOS Sonoma 14.2.1
- PDF.js version: 4.0.379
- Is a browser extension: no

Steps to reproduce the problem:
1. I've tried to update de `locale` options using PDFViewerApplicationOptions:
```javascript
PDFViewerApplicationOptions.set("locale", "en")
```
But the ui does not update for the new value (it doesn't refresh the messages) 

What is the expected behavior? (add screenshot)
Change the ui messages for the new locale value

What went wrong? (add screenshot)
The l10n messages stay the same (navigator.language which is pt-BR)

![Captura de Tela 2024-01-24 às 11 22 21](https://github.com/mozilla/pdf.js/assets/2482989/a2fe1102-0ab5-4928-99db-464b8f2aa90c)

**Comment by Snuffleupagus** [comment] 2024-01-24 14:30
Duplicate of #17567

**Closed by Snuffleupagus** 2024-01-24 14:30 UTC

**Comment by carloshpds** [comment] 2024-02-01 17:05
@Snuffleupagus shoudn't we be able to change the options any time?
The `webviewerloaded ` event is never called.

**Comment by Snuffleupagus** [comment] 2024-02-01 18:13
> shoudn't we be able to change the options any time?

No, since as already explained in https://github.com/mozilla/pdf.js/issues/17572#issuecomment-1908273079 (all) options must be set *before* the viewer has been initialized.

> The `webviewerloaded` event is never called.

It should be, however it's likely that you're not registering the event listener correctly. Possible explanations include:
 - Registering it on the wrong DOM-element, since it should (generally) be the `document` that embeds the viewer.
 - Registering it too late, since the event is dispatched just after the standard "DOMContentLoaded" event.
 - Something else, which is impossible to tell given the lack of details; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
 
   > If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
