### ISSUE TITLE
Running into out of memory issue when opening large pdf

### ISSUE THREAD

**Issue by ThalapaneniSushma** [mozilla/pdf.js#14679] opened 2022-03-15 19:18 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome(99.0.4844.51)
- Operating system and its version: Windows 10
- PDF.js version: v2.13.216
- Is a browser extension: No

Steps to reproduce the problem:
1. In our web application there is a requirement to open the pdf files on click of the hyperlinks and fetching/streaming the pdf file content from the server
2. When loading the large pdf with a size of 130MB and more than 25k pages we are running into Out of memory issue

What is the expected behavior? (add screenshot)
Opening/Displaying a pdf file without any issue as we are streaming the pdf file content from the server based on the chunk size(Initially 65KB size and then the chunk size keeps on increasing) without loading the entire pdf at a time

What went wrong? (add screenshot)
Running into Out of memory issue and the whole web application is breaking.
Attaching the screenshots for reference
![pdf-failed](https://user-images.githubusercontent.com/91343957/158443607-3c370cb7-18de-469f-a928-42099292edfe.PNG)
![pdf-failed-1](https://user-images.githubusercontent.com/91343957/158443613-987d08da-69e0-4e74-ab41-e4d668979d14.PNG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Please find the url to open the pdf - [https://quisitive-my.sharepoint.com/:b:/p/sushma_thalapaneni/EQSjnWUh77JJhwl0c6WbRT8ByGgaElkwC7Mfo_mGoEcBEQ?e=hdjrKP](https://quisitive-my.sharepoint.com/:b:/p/sushma_thalapaneni/EQSjnWUh77JJhwl0c6WbRT8ByGgaElkwC7Mfo_mGoEcBEQ?e=hdjrKP)

Please find the url where we recorded this issue - [https://watch.screencastify.com/v/MdfPfkgq0641KyahtuHU](https://watch.screencastify.com/v/MdfPfkgq0641KyahtuHU)

Please any suggestions/help would be appreciated as its the heart of our application.

Thank you

**Comment by Snuffleupagus** [comment] 2022-03-15 19:34
Duplicate of #14673

As was mentioned in https://github.com/mozilla/pdf.js/issues/14673#issuecomment-1066578800, given that this appears to be *specific* to Google Chrome it unfortunately doesn't really seem to be a PDF.js bug as such.
Note that opening that PDF document with https://mozilla.github.io/pdf.js/web/viewer.html in Mozilla Firefox works just fine.

> PDF.js version: v2.13.216
> Please find the url where we recorded this issue - https://watch.screencastify.com/v/MdfPfkgq0641KyahtuHU

That screen-cast clearly shows a *very old*, and completely unsupported, version of the default viewer which is thus at odds with the PDF.js version that you claim to be using here.

**Closed by Snuffleupagus** 2022-03-15 19:34 UTC
