### ISSUE TITLE
Display pdf with transparent background

### ISSUE THREAD

**Issue by yohann84L** [mozilla/pdf.js#8809] opened 2017-08-22 15:48 UTC
Link to PDF file (or attach file here): [tempPDF.pdf](https://github.com/mozilla/pdf.js/files/1242474/tempPDF.pdf)

I have a pdf with 4 pages, each of the page has a transparent background. I would like to display them with a transparent background on my html page but I can't figure out how I could do that, there is always a white background : 

<img width="1188" alt="capture d ecran 2017-08-22 a 16 55 56" src="https://user-images.githubusercontent.com/22057089/29574393-b47d6758-8761-11e7-90a4-c9496e05f007.png">

Here is my javascript file to display the four pages : 
``` js
var pdfFile;
PDFJS.getDocument('/assets/pdf/tempPDF.pdf').then(function (pdf) {
    pdfFile = pdf;

    for(var i = 1; i <= 4; i++) {
        var canvas = document.getElementById('canvas'+i);
        var context = canvas.getContext('2d');
        PDFJS.disableStream = true;
        openPage(pdf, i, context, 80);
    }
});

function openPage(pdfFile, pageNumber, context, ratio) {
    var scale = 5;
    pdfFile.getPage(pageNumber).then(function (page) {
        viewport = page.getViewport(scale);
        // reference canvas via context
        var canvas = context.canvas;
        canvas.width = viewport.width;
        canvas.height = viewport.height;
        canvas.style.width = ratio+"%";
        canvas.style.height = ratio+"%";
        var renderContext = {
            canvasContext: context
            , viewport: viewport
        };
        page.render(renderContext);
    });
}
```

And my html page in case that could be useful : 
``` html
<!DOCTYPE html>
<html>
<body
        style="background-color:powderblue;">
</body>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="PDF Viewer" />
    <title>My page</title>
</head>
<body>
    <form action="pdf_latex_test.php">
        <input type="submit" value="execute" /> </form>
</body>
<body>
    <canvas id="canvas1" width="300" height="300"></canvas>
    <canvas id="canvas2" width="300" height="300"></canvas>
    <canvas id="canvas3" width="300" height="300"></canvas>
    <canvas id="canvas4" width="300" height="300"></canvas>
<script src="/assets/js/pdf.js"></script>
<script src="/assets/js/pdf.worker.js"></script>
<script src="/assets/js/pdf.latex.main.js"></script>
</body>
</html>
```

Configuration:
- Web browser and its version: Firefox 55.0.2 (64 bits)
- Operating system and its version: macos Sierra 10.12.6
- PDF.js version: v1.8.188
- Is an extension:

**Comment by colasbd** [comment] 2017-08-22 15:56
👍

**Comment by yurydelendik** [comment] 2017-08-22 16:08
Duplicate of #7911

**Closed by yurydelendik** 2017-08-22 16:08 UTC
