### ISSUE TITLE
Magazine PDF with side-by-side pages renders off-screen

### ISSUE THREAD

**Issue by dalin-** [mozilla/pdf.js#9359] opened 2018-01-12 17:30 UTC
Attach (recommended) or Link to PDF file here:
https://www.aclu.org/sites/default/files/field_document/aclu_stand_mag_summer_2015.pdf

**Configuration:**
- Web browser and its version: FF 58, but it doesn't seem to matter.
- Operating system and its version: OSX 10.13, but it doesn't seem to matter.
- PDF.js version: 1.10.88, but that doesn't seem to matter either
- Is a browser extension: No

**Steps to reproduce the problem:**

1.  Use the PDF viewer embedded here:
https://www.aclu.org/other/read-latest-issue-stand
The cover page will show auto zoom (and I think it is choosing fit-width).
2. Scroll down to the next page (other than the cover, all pages are side-by-side).  Odd pages are rendered off-screen.

![image](https://user-images.githubusercontent.com/1127349/34886664-bd52a78a-f791-11e7-8be4-f71f15853074.png)

**What is the expected behavior? (add screenshot)**

If you play around with opening the PDF viewer sidebar and choosing individual pages and/or switching between Automatic Zoom and Page Width, you can get into a state where the cover page is on its own, but subsequent pages are side-by-side. See screenshots. 

![image](https://user-images.githubusercontent.com/1127349/34886260-7b6c6410-f790-11e7-90f9-6ff3d02890ea.png)

![image](https://user-images.githubusercontent.com/1127349/34886273-824e0284-f790-11e7-965b-d84652a5b42c.png)

I'm trying to make this the default state when opening the PDF.  I've been playing around with the [viewer options](https://github.com/mozilla/pdf.js/wiki/Viewer-options).  The closest that I've gotten is 
`#page=2&zoom=page-fit,0,1100`
which results in this:

![image](https://user-images.githubusercontent.com/1127349/34887311-0d7da438-f794-11e7-9088-88310b7b6380.png)

So close..., but if I add any more top offset it goes back to looking like the original screenshots. 

**Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):**
https://www.aclu.org/other/read-latest-issue-stand

I'm not sure if this is a bug, or just some hidden configuration value that I don't know about.

**Comment by brendandahl** [comment] 2018-01-12 19:39
I haven't looked to deeply yet, but I think it's because we base page-fit off the size of the first page. We could probably do something smarter and look at subsequent page sizes.

**Comment by dalin-** [comment] 2018-01-16 15:11
So that I can go back to my client with the full range of possible options, does this project have a bug bounty program?  Formal or otherwise?  The only other offer of a bounty that I could find is
https://github.com/mozilla/pdf.js/issues/2594#issuecomment-232006047
And it's not clear whether or not the bounty was actually claimed.

**Comment by brendandahl** [comment] 2018-01-16 20:03
There's no formal bug bounty program. I do believe the one you referenced above was claimed though.

**Comment by brendandahl** [comment] 2018-01-16 21:48
Somewhat off topic... I'm not sure what the intentions of the above site, but if it's purely for viewing the PDF online, you (or your client) may want to export that PDF as a PDF optimized for the web. It looks like some of the images in it have a really high DPI and could be much smaller if it only needs to be shown online.

**Comment by dalin-** [comment] 2018-01-18 18:20
Thanks for your thoughts.  The current plan is to modify the PDF, and see how that works.

**Comment by Snuffleupagus** [comment] 2021-11-08 10:42
Duplicate of #5628

**Closed by Snuffleupagus** 2021-11-08 10:42 UTC
Labels: 1-viewer
