### ISSUE TITLE
Rendering Issue in Chrome

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#12501] opened 2020-10-20 22:19 UTC
Attach (recommended) or Link to PDF file here:

PDF rendered using the PDFJS github demo. Some graphics are missing when rendered in Chrome as compared to FireFox

Configuration:
[TestRenderingIssue.pdf](https://github.com/mozilla/pdf.js/files/5411849/TestRenderingIssue.pdf)

- Web browser and its version: Chrome 86.0.4240.75 (Official Build) (64-bit)
- Operating system and its version: Windows 10 latest version
- PDF.js version: 2.7.164 (PDFJS GitHUb demo viewer)
- Is a browser extension: No

Steps to reproduce the problem:
1. open attached PDF in the PDFJS github demo viewer in Chrome
2.open attached PDF in the PDFJS github demo viewer in FireFox

What went wrong? (add screenshot)
![NEL-1220 NEBRASKAland Gift Giving Ad_DEC 20 - NEL-1220_NEBRASKAland_Gift_Giving_Ad_DEC_20 pdf](https://user-images.githubusercontent.com/947206/96650172-60ce6980-1300-11eb-8ba1-a091bfc953cd.png)

What is the expected behavior? (add screenshot)
![Screenshot_2020-10-20 NEL-1220 NEBRASKAland Gift Giving Ad_DEC 20 - TestRenderingIssue pdf](https://user-images.githubusercontent.com/947206/96649922-fa494b80-12ff-11eb-9b48-74681f72c3ca.png)

Note that in the screenshot of Chrome some cards (graphics) are missing

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2020-10-21 09:21
> Some graphics are missing when rendered in Chrome as compared to FireFox

That would suggest a canvas, hardware acceleration, and/or driver issue specific to Google Chrome, rather than the PDF.js library; as such it's unfortunately very difficult to see that this can be fixed here.

**Comment by blackmambahk** [comment] 2020-10-21 09:38
> > Some graphics are missing when rendered in Chrome as compared to FireFox
> 
> That would suggest a canvas, hardware acceleration, and/or driver issue specific to Google Chrome, rather than the PDF.js library; as such it's unfortunately very difficult to see that this can be fixed here.

FYI it's reproducible by 15 people in 6 different companies and a whole random range of equipment, with different graphic cards  and it's not an issue for the exact same people in the same browser if they use the Chrome native viewer.

**Comment by Snuffleupagus** [comment] 2020-10-21 09:45
> FYI it's reproducible by 15 people in 6 different companies and a whole random range of equipment, with different graphic cards

That'd would probably suggest a `canvas`-related bug in Google Chrome then...

> it's not an issue for the exact same people in the same browser if they use the Chrome native viewer.

Given that PDFium (i.e. the built-in Google Chrome PDF viewer) isn't using `canvas` for rendering (or any part of the web-platform really), which the PDF.js library does, that's not entirely surprising either.

All-in-all, given that the PDF.js project is run by Mozilla, it's probably reasonable to expect that Google Chrome isn't the main focus of development :-)

**Comment by timvandermeij** [comment] 2020-10-21 21:05
Closing since this looks _very_ similar to #12502 and other very recently reported bugs. I'd strongly recommend to report this to the Chrome development team in their issue tracker instead since from the number of similar-looking reports here it looks like there may be a regression in Chrome itself, which is obviously not something we can fix.

**Closed by timvandermeij** 2020-10-21 21:05 UTC

**Comment by TMmaxx** [comment] 2020-10-22 10:03
A workaround that we are using for the interim is turning of hardware acceleration. Definitely not ideal, but it allows our users to continue working while we work to fix the issue

**Comment by SamyCookie** [comment] 2020-11-03 10:06
for cross references: duplicate of #12462
