### ISSUE TITLE
[Feature Request] Support links to open local files in an external app

### ISSUE THREAD

**Issue by Atreyu-94** [mozilla/pdf.js#16010] opened 2023-02-05 13:38 UTC
Attach (recommended) or Link to PDF file here: 
[See latest page of document](https://drive.google.com/file/d/112BEl_hjlGuY3QX3ZIOf6rzKWZckP6WG/view?usp=sharing)

Configuration:
- Web browser and its version: 109.0.1
- Operating system and its version: Windows 10
- PDF.js version: I can't find PDF.js version, it's packaged with Firefox 109.0.1
- Is a browser extension: No

Steps to reproduce the problem:
1. Open an PDF page with a hyperlink to run a file.
2. Hyperlink is not clickable. 

What is the expected behavior? (add screenshot)
Link should be clickable, and should be able to open local file from an absolute o relative path with default app or show a list of options like when you open a file on browser. This is very useful when you want to make a presentation with PDF format, and you need to play a video or run some app.
Link to file on PDF.js is not clickable | If I try to open a APK file in Firefox, and what would be able to do PDF.js
:------------------------------------:|:--------------------------------------------------------------------------:
![pdfjs](https://user-images.githubusercontent.com/39834909/216820868-ad2028c1-9aa4-451d-b962-21202c2c9ffe.jpg) | ![pdfjswould](https://user-images.githubusercontent.com/39834909/216822010-7158ba93-5b2f-40a4-8ba4-0e04b22c5f54.jpg)

What went wrong? (add screenshot)
Link to local file was not clickable. I add some screenshots about what is happening in Foxit Reader, which is able to open this. (Note that Print Screen doesn't show mouse, but it is clickable)

Foxit Reader clickable link | Foxit Reader option to select open external app
:-------------------------:|:-------------------------------------------------:
![foxit1](https://user-images.githubusercontent.com/39834909/216821268-5ee5c422-341b-44f0-8331-5267d9222bd0.jpg) | ![foxit2](https://user-images.githubusercontent.com/39834909/216821287-1195ec1e-1897-4fe5-923f-a445d21b0012.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-02-05 13:48
This is, for all intents and purposes, a duplicate of e.g. #12415 and [bug 1678914](https://bugzilla.mozilla.org/show_bug.cgi?id=1678914).

**Closed by Snuffleupagus** 2023-02-05 13:48 UTC
