### ISSUE TITLE
PDF Rendering Issue at 100%

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#16764] opened 2023-07-28 11:47 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 114.0.5735.199 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: 3.9.167
- Is a browser extension: No

Steps to reproduce the problem:
1. Load PDF into the mozilla pdfjs viewer 
[174-437_Pharma_Page_Rev2.pdf](https://github.com/mozilla/pdf.js/files/12194055/174-437_Pharma_Page_Rev2.pdf)

2. Choose display at actual size

What is the expected behavior? (add screenshot) It should render correctly - Renders correctly in the Chrome native built in viewer.

What went wrong? (add screenshot) Renders a very blurry image that is only about 20% of the actual file. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-07-28 11:51
Duplicate of #14982

**Closed by Snuffleupagus** 2023-07-28 11:51 UTC
