### ISSUE TITLE
PDF JS Rendering issue - Edge  44.17763.771.0

### ISSUE THREAD

**Issue by Nataraj67** [mozilla/pdf.js#11225] opened 2019-10-10 09:35 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Edge  44.17763.771.0
- Operating system and its version: windows 10
- PDF.js version: 2.1.266 stable
- Is a browser extension: No

Steps to reproduce the problem:
1. open pdf URL in Edge  44.17763.771.0

What is the expected behavior? (add screenshot)
 Normal PDF 

What went wrong? (add screenshot)
![Edge_44_issue](https://user-images.githubusercontent.com/56388429/66557042-e5739d00-eb6e-11e9-9ccd-25f8b9e710a7.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-10-10 09:46
Duplicate of #11224, and please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support;
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Closed** 2019-10-10 21:05 UTC
