### ISSUE TITLE
Feature Request: Support link to local file in Document Outline 

### ISSUE THREAD

**Issue by rameezrajas** [mozilla/pdf.js#7398] opened 2016-06-09 23:02 UTC
Web browser and its version: Chrome Version 51.0.2704.84 (64-bit)
Operating system and its version: Win 7
PDF.js version: 1.5.292

Bookmark is not working, If the bookmark has a link to file in the local file system.
Bookmark is working, if the bookmark has link in the form of URI.

Please add support to local file system as well

**Comment by timvandermeij** [comment] 2016-06-10 20:07
Please provide an example PDF file for us to work with as requested in the issue template.

**Comment by timvandermeij** [comment] 2016-06-13 19:33
Closing as incomplete until the information requested above is provided.

**Closed by timvandermeij** 2016-06-13 19:33 UTC
Labels: 4-information-requested

**Comment by rameezrajas** [comment] 2016-06-15 02:16
[Sample_2.pdf](https://github.com/mozilla/pdf.js/files/315319/Sample_2.pdf)
[Sample_1.pdf](https://github.com/mozilla/pdf.js/files/315321/Sample_1.pdf)

I have two pdf files named Sample_1.pdf and Sample_2.pdf

Sample_1.pdf has a bookmark named Sample_2. If i click on that bookmark, Sample_2.pdf file should is getting opened. 
Both the files are in same location.
I want this feature impemented in pdfjs

**Comment by Snuffleupagus** [comment] 2016-06-15 07:36
Given the information in https://github.com/mozilla/pdf.js/issues/7398#issuecomment-226070194, this is a duplicate of issues #6616 and #1778.
