### ISSUE TITLE
Selected text disappears when window is not active

### ISSUE THREAD

**Issue by aleth** [mozilla/pdf.js#4268] opened 2014-02-10 16:30 UTC
Selected text appears black on purple when the window is active. When the window loses focus, both background and text become grey, making the text illegible. (FX Aurora 29 on OSX)
![pdf selection inactive window](https://f.cloud.github.com/assets/327844/2127581/972c271e-9270-11e3-8bd1-5f83cdb4f78b.png)

**Comment by timvandermeij** [comment] 2015-05-14 18:31
I cannot reproduce this anymore (use http://arxiv.org/pdf/1402.1418.pdf for example). It indeed becomes grey when the window is not active, but it is now semi-transparent and the black text remains. Closing as fixed.

**Closed by timvandermeij** 2015-05-14 18:31 UTC
Labels: 1-viewer, 4-text-selection
