### ISSUE TITLE
Current page is reset to page 1 on the way to tabbing to doc content

### ISSUE THREAD

**Issue by Sharpblade32** [mozilla/pdf.js#7603] opened 2016-09-06 23:15 UTC
Link to PDF file: https://mozilla.github.io/pdf.js/web/viewer.html

**Configuration:**
- App and its version: Apple Safari version 9.1.3 (11601.7.8)
- Operating system and its version: Apple OS/X El Capitan
- PDF.js version: PDF.js 0.8.0 (latest)

**Steps to reproduce the problem:**

1. Enter a number different than 1 in the page number input field of the pdf.js toolbar.
![user has tabbed out of page number input field - pdfjs toolbar - apple safari](https://cloud.githubusercontent.com/assets/22039011/18294371/bf99cb64-74ec-11e6-94f4-ad6330223b79.png)

2. Press the tab key to move the focus to the zoom out button (minus sign) of the pdf.js toolbar. The page selected at step 1 is loaded and displayed as expected.
3. Press the tab key multiple times until the zoom dropdown list in the PdfJs toolbar has been reached. The page selector is then reset to 1, and page 1 of the document is loaded and displayed. Please note that the present issue cannot be reproduced in the most recent versions of Mozilla Firefox and Google Chrome: it is an issue specific to Apple Safari.

**What is the expected behavior?**
At step 3, the page selector must not be reset to page 1 and the currently displayed page and page number must remain the same.

**What went wrong?**
For some reason, the page selector is reset to 1 on completion of step 3.
![page number has been reset to 1 - pdfjs toolbar - apple safari](https://cloud.githubusercontent.com/assets/22039011/18294113/21bd2c8e-74eb-11e6-9604-24f95cb3553b.png)

**Comment by yurydelendik** [comment] 2016-09-06 23:41
Unable to reproduce on the same configuration at https://mozilla.github.io/pdf.js/web/viewer.html More information needed.

**Comment by Sharpblade32** [comment] 2016-09-06 23:53
Updating the description to explain that the page is reset to 1 on tabbing to the zoom dropdown list in PdfJs toolbar

**Comment by slimjim181** [comment] 2016-09-06 23:54
I can re-produce based on @Sharpblade32 updated description

**Comment by yurydelendik** [comment] 2016-09-07 00:49
Still no repro: 
![saf1](https://cloud.githubusercontent.com/assets/1523410/18295909/02704f62-746b-11e6-9fcb-2197c1e160cd.gif)

**Comment by slimjim181** [comment] 2016-09-07 01:13
hmm this might be to do with keyboard settings @yurydelendik what are you settings on? The first dialog is safari settings the second is system preferences
![keyboard settings](https://cloud.githubusercontent.com/assets/20076864/18296286/abd8b990-74fc-11e6-8c66-c01c5d3b193f.jpg)

**Comment by yurydelendik** [comment] 2016-09-07 15:16
Still no issue. Try to resetting your safari and remove all extensions -- out of the box it works as expected.

**Comment by slimjim181** [comment] 2016-09-07 21:57
Ok so we have worked out what the issue is:
If you turn voiceover on then off before following the above steps, you can then reproduce this bug. This bug is actually only related to voiceover.

**Comment by yurydelendik** [comment] 2016-09-08 12:57
> This bug is actually only related to voiceover. 

I don't think we can do anything on the PDF.js side. Closing as invalid.

**Closed by yurydelendik** 2016-09-08 12:57 UTC
Labels: 4-information-requested
