### ISSUE TITLE
on exporting pdf page to image, ( images inside pdf ) not displaying in the output image in ubuntu.

### ISSUE THREAD

**Issue by Sride** [mozilla/pdf.js#11006] opened 2019-07-24 07:03 UTC
Exporting pdf to images, image inside the PDF is not displaying, refer the attached PDF.
[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/blob/master/web/compressed.tracemonkey-pldi-09.pdf) in PDF second page as image, this image is not displaying on Ubuntu but shows well in windows 10 same node and pdf.js version.

Configuration:
- Chrome, firefox...
- OS: Ubuntu 16.04
- pdf.js ("pdfjs-dist": "^2.1.266"), nodejs (10.5.0)

```
var loadingTask = pdfjsLib.getDocument("compressed.tracemonkey-pldi-09.pdf");
loadingTask.promise.then(function(pdfDocument) {
	console.log('# PDF document loaded.');
	main (2)
	async function main (i) {
		const page = await pdfDocument.getPage(i);
		var viewport = await page.getViewport({ scale: 1.0, });
		var canvasFactory = new NodeCanvasFactory();
		var canvasAndContext =
		  canvasFactory.create(viewport.width, viewport.height);
		var renderContext = {
		  canvasContext: canvasAndContext.context,
		  viewport: viewport,
		  canvasFactory: canvasFactory,
		};

		var renderTask = await page.render(renderContext);
		//var base64 = canvasAndContext.canvas.toDataURL('image/jpeg');
		var image = canvasAndContext.canvas.toBuffer();
		await fs.writeFile('output'+i+'.jpeg', image, function (error) {
		    if (error) {
		      console.error('Error: ' + error);
		    } else {
		      console.log(
		        'Finished converting first '+i+' of PDF file to a PNG image.');
		    }
		});
	}
}).catch(function(reason) {
  console.log(reason);
});

function NodeCanvasFactory() {}
NodeCanvasFactory.prototype = {
  create: function NodeCanvasFactory_create(width, height) {
    assert(width > 0 && height > 0, 'Invalid canvas size');
    var canvas = Canvas.createCanvas(width, height);
    var context = canvas.getContext('2d');
    return {
      canvas: canvas,
      context: context,
    };
  },

  reset: function NodeCanvasFactory_reset(canvasAndContext, width, height) {
    assert(canvasAndContext.canvas, 'Canvas is not specified');
    assert(width > 0 && height > 0, 'Invalid canvas size');
    canvasAndContext.canvas.width = width;
    canvasAndContext.canvas.height = height;
  },

  destroy: function NodeCanvasFactory_destroy(canvasAndContext) {
    assert(canvasAndContext.canvas, 'Canvas is not specified');

    // Zeroing the width and height cause Firefox to release graphics
    // resources immediately, which can greatly reduce memory consumption.
    canvasAndContext.canvas.width = 0;
    canvasAndContext.canvas.height = 0;
    canvasAndContext.canvas = null;
    canvasAndContext.context = null;
  },
};

```
Any suggestions?

**Comment by Snuffleupagus** [comment] 2019-07-24 07:21
Most likely duplicate of #10992.

**Closed** 2019-07-24 21:01 UTC
