### ISSUE TITLE
PageContent is not in correct order.

### ISSUE THREAD

**Issue by subhashlg26** [mozilla/pdf.js#8964] opened 2017-09-28 14:15 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome 61
- Operating system and its version: Mac OSx
- PDF.js version: 1.8.188-dist
- Is an extension: No

Steps to reproduce the problem:
1. Unzip the library. Update viewer.js  to set var DEFAULT_URL = "example.pdf" on line number 7698. (This files is attached).
2. Place attached example.pdf in web folder.
3. Start server (python -m SimpleHTTPServer  50000)
4. Open viewer.html with Chrome debugger.
5. Place breakpoint in viewer.js at line number 3036.
6. Search for "XYZ"
7. Check the value of this.pageContent[3]

What is the expected behaviour? (add screenshot)
Header in the PDF are present at the tail end of the "pagecontent".

What went wrong? (add screenshot)
Because of this any content to be searched broken between header and body does not work.

[example.pdf](https://github.com/mozilla/pdf.js/files/1341199/example.pdf)

**Comment by Snuffleupagus** [comment] 2017-09-29 07:51
> Search for "XYZ"

Searching for this phrase does not yield any result in either PDF.js *or* Adobe Reader, so I'm not sure how to interpret that part of the STR; please clarify what this means.

> Header in the PDF are present at the tail end of the "pagecontent".

If what you're trying to report here (in this issue) is that text-selection "order" seems wrong, when you select text from the top right corner of a page and to the bottom right corner, then that is caused by the order of the text rendering operators in the PDF file *itself*.
Please note that the text-selection behaviour described just above can *also* be observed in Adobe Reader.

**Comment by timvandermeij** [comment] 2017-10-01 12:12
Closing since this looks like it works as expected as the order is defined in the PDF file itself. If not, please provide the above mentioned details.

**Closed by timvandermeij** 2017-10-01 12:12 UTC
Labels: 4-information-requested
