### ISSUE TITLE
Toggle Layer Visibility

### ISSUE THREAD

**Issue by Kampii** [mozilla/pdf.js#7002] opened 2016-02-17 06:30 UTC
Hi!
I came across this library as I was doing a research on how to embed a pdf into html and toggle the pdf layers with javascript. Is that doable using your tool, the keyword search did not return any results. If it is currently not possible, do you know if there is any other way to achieve this?

**Comment by Snuffleupagus** [comment] 2016-02-17 15:08
This is currently not supported, closing as duplicate of issue #269.

**Closed by Snuffleupagus** 2016-02-17 15:08 UTC
