### ISSUE TITLE
PDF edit: polish diacritics rendered but invalid when save to PDF or printed

### ISSUE THREAD

**Issue by adamws** [mozilla/pdf.js#15667] opened 2022-11-05 19:06 UTC
Configuration:
- Web browser and its version: Mozilla Firefox 106.0.2
- Operating system and its version: Arch Linux 6.0.6
- PDF.js version: master
- Is a browser extension: no

Steps to reproduce the problem:
1. Use `Text` tool, add polish diacritics letters: `ć, ń, ó, ś, ź, ż, ą, ę, ł`:
![image](https://user-images.githubusercontent.com/12676586/200136619-5b8ef5e8-1705-4595-a3ea-95844aaed317.png)
2. `Print` - preview will show invalid characters (or nothing rendered at all) - only `ó` works as expected:
![image](https://user-images.githubusercontent.com/12676586/200136663-61ffa4b7-853c-41e2-94c7-6454aa71f8ee.png)
When printed (or saved to PDF) result will be same as in preview.

**Comment by Snuffleupagus** [comment] 2022-11-05 19:12
Duplicate of #12264

**Closed by Snuffleupagus** 2022-11-05 19:12 UTC
