### ISSUE TITLE
Export PDFDocumentProxy type defenition in pdfjs-dist

### ISSUE THREAD

**Issue by IRelaxxx** [mozilla/pdf.js#12926] opened 2021-01-28 07:43 UTC
In pdfjs-dist 2.6.347 the Typescript types where added to the package, making @types/pdfjs-dist obsolete. This broke the compile step of my Typescript application because the PDFDocumentProxy type is not exported from pdfjs-dist. Please export the PDFDocumentProxy type from pdfjs-dist.

**Comment by Snuffleupagus** [comment] 2021-01-28 09:01
Duplicate of #12384, note in particular https://github.com/mozilla/pdf.js/issues/12384#issuecomment-695143287 and that it'll be up to TypeScript users to help maintain the definitions.

**Closed** 2021-01-28 22:37 UTC
