### ISSUE TITLE
[Feature]: Callout annotation

### ISSUE THREAD

**Issue by jimvella** [mozilla/pdf.js#18642] opened 2024-08-23 08:56 UTC
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

Would it be possible to support callout annotations (text plus arrow) such as those used in Bluebeam? At the moment it seems as though these annotations are recognized as free text annotations, so the information on what the callout is pointing at isn't represented in the result from getAnnotations(). An alternative could be to expose the annotation's appearance stream?

**Comment by Snuffleupagus** [comment] 2024-08-23 09:03
Duplicate of #3192 (since it already mentions that anotation-type, among others).

*For future reference:* Including a PDF document with the feature is question is generally helpful.

**Closed by Snuffleupagus** 2024-08-23 09:03 UTC

**Comment by jimvella** [comment] 2024-08-24 01:12
![image](https://github.com/user-attachments/assets/d0a3e468-ef6a-410a-93d4-c840978cb346)
[Bluebeam_Callout_annotations.pdf](https://github.com/user-attachments/files/16734765/Bluebeam_Callout_annotations.pdf)
