### ISSUE TITLE
pdf viewer errors in chrome

### ISSUE THREAD

**Issue by lszhu** [mozilla/pdf.js#6459] opened 2015-09-19 14:10 UTC
I have a pdf file which has some pages with different page size/format (A4/letter/B5 pictures). When I'm printing it in pdf viewer in chrome, I find each page size/format will be change to the the first page size/format. This will squeeze or stretch the page (pictures).

OS: windows 7 x64
chrome v44/v45 x64/x86

**Comment by Rob--W** [comment] 2015-09-19 20:17
Link to PDF? See https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md

**Comment by lszhu** [comment] 2015-09-21 10:28
I've tested some pdf files (made from jpg pictures),  each file with different page size/format can reproduce the bug.
I also find pdf.js v1.0 do not has the bug.

**Comment by lszhu** [comment] 2015-09-21 10:51
example
link to pdf
http://ge.tt/7pCBPHO2/v/0
print preview for the second page
http://ge.tt/3teKQHO2/v/0

**Comment by Rob--W** [comment] 2015-09-21 13:31
@lszhu If "pdf.js v1.0 do not have the bug", then this bug is most likely caused by #6462. That PR resolved a problem with page size, but due to the lack of support for targetting specific pages via CSS, pages with different sizes are scaled to fit on a single page.

The console will contain a warning when the page sizes are incorrect. Perhaps we should not try to unify the page size when we detect that the PDF pages have different page sizes? The relevant ode is here: https://github.com/mozilla/pdf.js/blob/f06aa6a3802ef6fb6c8919ef3de49bcfe774cb51/web/viewer.js#L1107-L1133

If I prevent the stylesheet from being inserted, the images are not rescaled, but three pages are printed, which is also incorrect (if you want to test it yourself, type `document.body.appendChild=function(e) { console.log('would have appended', e); };` in the console and try to print; the stylesheet won't be appended, which brings PDF.js back to the pre-#6462 state).

The best way to get rid of this bug is to use named pages (as you can see in the comments in our source code), but Chrome doesn't support that yet.

**Comment by yurydelendik** [comment] 2016-10-06 13:41
Shall be addressed by #7677

**Closed by yurydelendik** 2016-10-06 13:41 UTC
Labels: 4-chrome-specific, 4-printing
