### ISSUE TITLE
FreeText saved as garbled code when I input Chinese

### ISSUE THREAD

**Issue by ChaoxuWei** [mozilla/pdf.js#15638] opened 2022-10-28 13:43 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: latest
- Operating system and its version: Windows 10
- PDF.js version: latest live demo
- Is a browser extension: No

Steps to reproduce the problem:
1. open [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)
2. enable FreeText
3. input some Chinese (e.g. "输入中文")
4. download the example pdf
5. and you will see the garbled code

What is the expected behavior? (add screenshot)
The added freetext should be 输入中文 after downloading
![62ca9ecb144b94f583c9fa42b72b497](https://user-images.githubusercontent.com/110231141/198617642-98eae364-1543-42b4-ad26-6f05b86a070e.png)

What went wrong? (add screenshot)
The added freetext should be 输入中文， but I get ”e- 
![505eeca3da4fe24c7947bce5cb7f9c1](https://user-images.githubusercontent.com/110231141/198617714-8f4bd9a3-51bd-4a50-94af-c69b621fe1ae.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)

Anyone knows how to fixed it?

**Comment by Snuffleupagus** [comment] 2022-10-28 13:47
Duplicate of #12264

**Closed by Snuffleupagus** 2022-10-28 13:47 UTC
