### ISSUE TITLE
Auto scroll when add an annotation

### ISSUE THREAD

**Issue by abrancorrea** [mozilla/pdf.js#17143] opened 2023-10-19 20:39 UTC
Attach (recommended) or Link to PDF file here: Any

Configuration:
- Web browser and its version: Chrome 118.0.5993.88
- Operating system and its version: Windows 11 22621.2428
- PDF.js version: 3.11.174
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the sandbox
2. Select a File
3. Click on toggle highlight and try to draw

What is the expected behavior? I don't know if this is the normal behavior but I would expect that when a start drawing the scroll doesn't change. This is only happening when the first time you draw.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://codesandbox.io/s/react-with-pdfjs-dist-jq99kh

**Comment by Snuffleupagus** [comment] 2023-10-20 09:57
Can you reproduce the problem in the demo viewer, see https://github.com/mozilla/pdf.js#online-demo?

(Trying to debug a React-application will probably be quite difficult unless you're already familiar with that framework, and I don't believe that any of the PDF.js developers/contributors know much about it.)

**Comment by abrancorrea** [comment] 2023-10-20 19:46
Hi, thanks for your response!

Actually, I based the code in the demo viewer you provided, also I made another demo but with just plain TS:

https://codesandbox.io/s/pdfjs-dist-with-ts-hd2j3n

The behavior with the auto scroll once I start drawing is the same with this one (using same version and configuration described above).

**Comment by Snuffleupagus** [comment] 2023-11-24 10:10
Duplicate of #17327

**Closed by Snuffleupagus** 2023-11-24 10:10 UTC
Labels: chrome-specific
