### ISSUE TITLE
Update chrome extension

### ISSUE THREAD

**Issue by ecstrema** [mozilla/pdf.js#15654] opened 2022-11-01 22:37 UTC
According to the chrome web store, the last published version is from September 13, **2019**, which makes it from more than 3 years ago. 

[This page](https://github.com/mozilla/pdf.js/wiki/PDF-Viewer-%28Chrome-extension%29) explains how to update it on the store, but it seems this hasn't been done recently.

Or is it some kind of progressive delivery on the chrome web store?

Anyway, if anyone wants an up to date version, it is very easy to build it by one's self, and here's even a zip file with the built extension.

[chromium.zip](https://github.com/mozilla/pdf.js/files/9914385/chromium.zip)

**Comment by Snuffleupagus** [comment] 2022-11-02 08:36
Duplicate of #13669

**Closed by Snuffleupagus** 2022-11-02 08:36 UTC
