### ISSUE TITLE
Can't find phrases in justified text

### ISSUE THREAD

**Issue by johnmellor** [mozilla/pdf.js#11753] opened 2020-03-26 14:17 UTC
**Attach PDF file here:** [1503.01817v2.pdf](https://github.com/mozilla/pdf.js/files/4387305/1503.01817v2.pdf) (from https://arxiv.org/pdf/1503.01817v2.pdf)

**Configuration:**
- Web browser version: Chrome 80.0.3987.158
- Operating system version: Chrome OS 80.0.3987.158
- PDF.js version: 2.5.40 https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: no (but also reproduces on https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm version 2.3.164)

**Steps to reproduce the problem:**
1. Open the attached PDF.
2. Search for "are not yet".

**What is the expected behavior?**

The line "tions **are not yet** available for the YFCC100M at present," should match. It matches as normal in Chrome's built-in PDF viewer.

**What went wrong?**

"are not yet" is not matched, as you can see in this screenshot:

![image](https://user-images.githubusercontent.com/563043/77655663-a09bc100-6f6a-11ea-8031-42d17ddda36f.png)

You have to search for
```
are  not  yet
```
with doubled spaces in order for it to be found:

![image](https://user-images.githubusercontent.com/563043/77655747-ba3d0880-6f6a-11ea-8843-554316b36eb9.png)

**Analysis**

This seems to happen because pdf.js is misunderstanding justified text and inserting extra spaces. If you copy the line and surrounding lines using pdf.js, you get the following string, with doubled spaces for the middle line which was more heavily justified:
```
boxes, segmentations of objects and faces, and image cap-tions  are  not  yet  available  for  the  YFCC100M  at  present,although generating and releasing them is on our roadmap.
```

whereas if you copy the same text using Chrome's PDF viewer, you get the following string with normal spacing:
```
boxes, segmentations of objects and faces, and image captions are not yet available for the YFCC100M at present,
although generating and releasing them is on our roadmap.
```

**Additional information**

Related to:
- #4742 (Can't search across lines in some PDFs) and its PR #5783 (Improve Copy/Paste), but those are about there being too little whitespace not too much.
- #11752 (Can't find words hyphenated across lines)

The PDF was generated with standard software for scientific papers: [1.5 pdfTeX-1.40.12 / LaTeX with hyperref package]

**Comment by Snuffleupagus** [comment] 2020-03-26 14:19
Duplicate of #7355.

**Comment by johnmellor** [comment] 2020-03-26 14:47
Ah yes, #7355 seems to be the same issue, though I'd suggest a different solution. Rather than making Find in Document handle variable whitespace (or in addition), it seems it'd be cleaner to fix parsing of justified text so that spaces aren't doubled up. That way copied text would also have the correct whitespace, as in Chrome's pdfium.

**Comment by timvandermeij** [comment] 2020-03-26 22:39
Closing as a duplicate of that issue for now. Possible solutions can be discussed there to keep the discussion in a central place. I also feel like the correct solution would be to not double up the spaces, but text selection in PDF files is difficult and currently (partly) heuristic-based, which we should improve.

**Closed by timvandermeij** 2020-03-26 22:39 UTC
