### ISSUE TITLE
clipping paths / bitmaps rendered poorly on chrome

### ISSUE THREAD

**Issue by cvlmtg** [mozilla/pdf.js#7286] opened 2016-05-03 15:59 UTC
Hi, I'm having some issues rendering some pdfs and I wonder if someone more knowledgeable than me on the pdf formats could help me somehow.

There's a proprietary program which reads a pdf generated by InDesign and then applies various transformations and optimizations (like trimmig everything outside the TrimBox, flattening all the graphics layers etc). It then generates a PDF/X file.
For some reason unknown to me, the text on the page sometimes is transformed in a mix of normal text (_TextRenderingMode.FILL_ in pdfjs jargon) and clipping paths (_TextRenderingMode.ADD_TO_PATH_).

When I display such pdf in Firefox, everything is fine (except for a very tiny visibile difference between the two kind of texts), while in chrome the path text is rendered very poorly:

**firefox**
![ex1](https://cloud.githubusercontent.com/assets/6401008/14987960/0488b68a-1152-11e6-9002-fc10f2e52457.png)

**chrome**
![ex2](https://cloud.githubusercontent.com/assets/6401008/14988472/42b16f04-1154-11e6-9f45-1ea87d29c4fa.png)

Since this pages are still quite big, we try to optimize them with ghostscript, but the result is that the path text is transformed in a bitmap, which is rendered fine on firefox and poorly on chrome (the output is basically the same of the two examples above).

I found a way to patch pdf.js to display the text correctly on chrome with the original pdf, but since there's apparently no way to tell ghostscript not to convert that text in a bitmap, we either use the bigger pdf, or have a smaller poorly rendered one.

Does anyone have some idea on how to fix the issue on chrome? I tried to play with gs options, tried to convert the pdf to postscript, debugged pdf.js code, searched for bugs / known issues etc, but since I really have very little knowledge on the pdf format my attempts where mostly by trial and error...

Thanks in advance!

---

Link to PDF file (or attach file here): https://www.dropbox.com/s/emqkeui3lssd428/test.pdf?dl=0

Configuration:
- Web browser and its version: chrome v49 and v50
- Operating system and its version: OSX 10.11, Windows 8 and Windows 7
- PDF.js version: v1.4.227, v1.5.211 and v1.5.218
- Is an extension: ??

Steps to reproduce the problem: please see above

**Comment by yurydelendik** [comment] 2016-05-03 16:21
> and clipping paths (TextRenderingMode.ADD_TO_PATH).

And draws black text using JPEG image (?). I'm thinking the combination of these two producing this effect

**Comment by yurydelendik** [comment] 2016-05-03 16:23
duplicate of #7041 ?

@cvlmtg is there an option to disable JPEG and make it JBIG2/CCITT?

**Comment by cvlmtg** [comment] 2016-05-04 07:54
> And draws black text using JPEG image (?). I'm thinking the combination of these two producing this effect

@yurydelendik probably my description of the problem was a bit confusing, sorry. the "source" pdf has the TextRenderingMode.ADD_TO_PATH text, while the one processed with ghostscript has that text turned into an image.

the source pdf has the text drawn inside the CanvasGraphics_endText() function, while the processed one has the image drawn inside CanvasGraphics_paintJpegXObject().

> @cvlmtg is there an option to disable JPEG and make it JBIG2/CCITT?

No idea, I should do more experiments with ghostscript. I think that at a certain point the image was drawn inside CanvasGraphics_paintInlineImageXObject() instead of CanvasGraphics_paintJpegXObject() so I suppose something changed about the compression or the image format, but honestly I don't remember when and how it happened. However on both cases the rendering was still poor.

> duplicate of #7041 ?

it may be for the rendering of the processed pdf, where the text has been turned to a bitmap by ghostscript. but on the source pdf the issue is with canvas paths drawing. this is what happens on windows 7 with the source pdf (i.e. the text is still text)

![immagine](https://cloud.githubusercontent.com/assets/6401008/15008011/5aca956e-11dd-11e6-8006-f9dd4fb839c9.png)

so it seems there are some issues with path rendering on canvas inside CanvasGraphics_endText(). On OSX the result is the one showed in my first message, while on Windows the result is much worse as shown above.

thanks for the help!

**Comment by cvlmtg** [comment] 2016-06-17 15:24
Hi, any news on this issue? I understand it might not be top priority, but I want to understand if I need to provide more examples / data or if it's just queued until someone have some time to look at it.
thanks!

**Comment by timvandermeij** [comment] 2016-06-18 11:51
It is primarily queued until someone has time to look into the issue at the moment. As far as I can see you did provide all necessary data for us to work with.

**Comment by cvlmtg** [comment] 2016-06-18 15:47
Thanks!

**Comment by Sbdea** [comment] 2016-12-06 15:47
Hi, I'm wondering If someone had already look into it and has any news?
Thanks.
BR,
Seb

**Comment by Snuffleupagus** [comment] 2021-03-22 15:55
Given the age of this issue, and that it's specific to a *particular* platform/browser (and possibly even graphics driver), it's probably not meaningful to keep this open since it's unfortunately not really something that can be fixed *here*.

**Closed** 2021-03-24 19:30 UTC
Labels: 2-image-quality, 4-chrome-specific
