### ISSUE TITLE
Extracting text color?

### ISSUE THREAD

**Issue by matt-curtis** [mozilla/pdf.js#7895] opened 2016-12-14 16:02 UTC
Is this possible? The current `getTextContent` function does not return any information regarding text color.

**Comment by yurydelendik** [comment] 2016-12-14 16:05
> The current getTextContent function does not return any information regarding text color.

That's by design. The getTextContent is designed for the text search or selection functionality. See getOperatorList to get entire information about fonts and color. Closing as answered.

**Closed by yurydelendik** 2016-12-14 16:05 UTC
