### ISSUE TITLE
Cannot select text for PDF generated by hocr-pdf

### ISSUE THREAD

**Issue by HKWhyIP** [mozilla/pdf.js#6829] opened 2016-01-03 13:29 UTC
I used hocr-pdf (https://github.com/tmbdev/hocr-tools/blob/master/hocr-pdf) to generate a PDF (attached). hocr-pdf can merge a hocr file with an image file to generate a PDF.  The hocr file is generated by Tesseract.  Adobe Reader and Chrome default PDF viewer both have no problem to let me select and copy text from the PDF.  But PDF.js does not allow me to select the text.  

Anyone knows why? Is it an issue with hocr-pdf or PDF.js?  Any suggestion on how to resolve the issue?

[tesseract_hocr.pdf](https://github.com/mozilla/pdf.js/files/76606/tesseract_hocr.pdf)

**Comment by Snuffleupagus** [comment] 2016-01-03 14:45
Closing as duplicate of issue #4684.

**Closed by Snuffleupagus** 2016-01-03 14:45 UTC

**Comment by HKWhyIP** [comment] 2016-01-04 02:16
Thanks for the pointer.  To those who are interested in the solution for using hocr-pdf, I simply replaced the fontname from "invisible" to "Courier". Then everything works fine.  There is no more problem reported by PDF.js.
