### ISSUE TITLE
Pages shrinked and grouped in mobile print

### ISSUE THREAD

**Issue by solis-eduardo** [mozilla/pdf.js#12839] opened 2021-01-08 21:07 UTC
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf

Configuration:
- Chrome 87.0.4280.141, Samsung Internet 13.0.2.9, Edge 45.12.4.5121;
- Android 10;
- PDF.js 2.5.207;

Steps to reproduce the problem:
1. Open viewer.html (any PDF file seems to work, even the example one)
2. Try to print the document using the print button on the secondary toolbar

What is the expected behavior?
All pages should be printed separately
![7108b7b2-0377-43f3-a6b5-f9dc0b1f95de](https://user-images.githubusercontent.com/77171633/104064347-9175bf00-51dc-11eb-990d-4a2ae1be5679.jpeg)

What went wrong?
Pages are shrinked and grouped
![b0cb5aae-0527-4a19-ad61-ae02a7cc04d8](https://user-images.githubusercontent.com/77171633/104063890-b289e000-51db-11eb-9efa-c705436ea019.jpeg)

**Comment by Snuffleupagus** [comment] 2021-04-11 14:24
Unfortunately this looks more like a platform/browser bug, rather than a PDF.js one, and the web-platform has (in general) quite limited support for controlling printing via JavaScript; hence I wonder if it makes sense to keep this issue open when it's unlikely to be fixable here?

**Comment by Snuffleupagus** [comment] 2021-04-11 14:29
Duplicate of #12020

**Closed** 2021-04-11 16:23 UTC
Labels: 4-printing
