### ISSUE TITLE
Make it possible to run xfa reftests exclusively

### ISSUE THREAD

**Issue by marco-c** [mozilla/pdf.js#13744] opened 2021-07-16 10:47 UTC
Currently, the bot will run all refests. It'd be nice to add a command to only run xfa reftests, a command to only run !xfa reftests and keep a command to run all.

**Comment by Snuffleupagus** [comment] 2021-07-16 11:03
While I understand where you're coming from here, my worry would be that such a setup *could* make it easier to introduce (entirely avoidable) regressions by not running enough tests for any given code change. (Given that recently, a number of patches have been approved *and* landed despite failing tests.)

If this was implemented, that'd put a much larger burden on both the patch author *and* reviewer to very carefully think about all the changes in a patch to ensure that you're not picking the "wrong" set of tests to run.
For example: A patch that *mostly* touches the `src/core/xfa/`-folder may still change some code in e.g. the `src/core/`-folder and that could possibly cause bugs in "regular" PDF documents.

Also, please note PRs https://github.com/mozilla/pdf.js/pull/13730 and https://github.com/mozilla/botio-files-pdfjs/pull/33 which will make it possible to *only* run the reference tests (since that wasn't previously possible).

**Comment by calixteman** [comment] 2021-07-28 12:13
We could have such a command just to iterate quickly over XFA stuff and when everything is fine (patch + XFA tests) then run a final `botio test`.
@Snuffleupagus wdyt ?

**Comment by Snuffleupagus** [comment] 2021-07-28 14:42
> We could have such a command just to iterate quickly over XFA stuff and when everything is fine (patch + XFA tests) then run a final `botio test`.

I wouldn't really recommend something that *only* runs the XFA-reftests and nothing more, since that's unlikely to be helpful (given that there's also XFA unit-tests).

If we do this, I'd suggest adding a special `gulp test-xfa` command (or similar) which runs *everything* that the standard `gulp test` does *except* that any non-XFA ref-tests are ignored. Then you'd only have to finish things off with a `botio browsertest` run at the end, and be done.

While I'm still not *crazy* about this idea, I suppose that I can try putting a patch along these lines later in the week!

**Comment by timvandermeij** [comment] 2021-08-03 21:49
The `gulp xfatest` command and the Botio `xfatest` commands are now available.

**Comment by Snuffleupagus** [comment] 2021-08-03 21:57
> The `gulp xfatest` command and the Botio `xfatest` commands are now available.

As far as I understand, the bots need to be *manually* updated after changes have been made in the https://github.com/mozilla/botio-files-pdfjs repository. (Unless you've got bot access, in which case please disregard this message :-).

**Comment by timvandermeij** [comment] 2021-08-03 22:00
Ah, I had hoped they would update automatically. @brendandahl If you have access to both bots, please deploy https://github.com/mozilla/botio-files-pdfjs/pull/34 there.

**Comment by marco-c** [comment] 2021-09-15 22:31
@brendandahl was this done?

**Comment by brendandahl** [comment] 2021-09-15 23:36
Should be fixed now.

**Closed by brendandahl** 2021-09-15 23:36 UTC
Labels: 1-test
