### ISSUE TITLE
iOS 8, Horizontal Chinese characters don't render, no warnings

### ISSUE THREAD

**Issue by reggersusa** [mozilla/pdf.js#5794] opened 2015-03-05 19:26 UTC
link to the PDF: https://www.dropbox.com/s/3on7u85qeejv493/346d270c_i.pdf?dl=0
location in the PDF: first page
screenshot: none
browser version: Safari 8 
operating system: iOS 8
PDF.js version: 1.0.1175
JavaScript console warning/error messages:
PDF a963cd5c45371b2705cc3c8d6ec8d10a [1.4 Adobe Acrobat 9.4 Paper Capture Plug-in / CanoScan 8800F] (PDF.js: -)
Chrome only (although renders ok): Unhandled promise rejection Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: DOMException: Invalid font data in ArrayBuffer.}__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: DOMException: Invalid font data in ArrayBuffer.

**Comment by timvandermeij** [comment] 2015-03-05 19:42
Closing as duplicate of #5792 (same error).

**Closed by timvandermeij** 2015-03-05 19:42 UTC

**Comment by indystar-jamesearlywine** [comment] 2015-09-17 15:44
Is anyone working to fix this? I've got the same problem:

http://bookshelfb.indystardev.com/#/app/publication/view/228

I get these errors in Chrome console:

Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.

These are the fonts in the document (embedded subsets):

FrutigerLTPro-Roman okay
AgilitaLTPro-MediumCond--Identity-H bad
AgilitaLTPro-Heavy--Identity-H bad
AgilitaLTPro-Regular--Identity-H bad
ZapfDingbatsStd okay
GlyphaLTStd-Black--Identity-H bad
AgilitaLTPro-BoldItalic--Identity-H bad
AgilitaLTPro-Light--Identity-H bad
AgilitaLTPro-Bold--Identity-H bad
AlbertinaMTStd-Regular--Identity-H okay
AgilitaLTPro-LightItalic--Identity-H bad
AgilitaLTPro-BoldCond--Identity-H bad
AgilitaLTPro-BoldCond okay
AgilitaLTPro-Medium--Identity-H bad
NotecLTPro--Identity-H bad
AgilitaLTPro-Condensed--Identity-H bad
GigiStd--Identity-H okay

The ones marked "bad" are the ones that throw the error.
