### ISSUE TITLE
Can PDF.js Core/Display/Viewer supports «Reference XObjects» (PDF 1.4) as an ISO PDF/X-5 standard?

### ISSUE THREAD

**Issue by marcantonifemfum** [mozilla/pdf.js#13228] opened 2021-04-12 17:10 UTC
Hi,

We have tested this PDF pair of files attached…

`RXO_www_enPatufet_19200410.pdf` (as a proxy recto/verso 8+8 nUp pages imposed)
`patufet_avuiFa100anys_19200410-23204.pdf` (as a target)

…as a clear _Reference XObjects_ sample, that can be used to import content, via URL, from one PDF document into another (see Section 4.9.3, _Reference XObjects_ on PDF Reference v1.7).

But PDF.js does'nt work (you can see one blue/red cross for each empty page).
[RXO_www_enPatufet_19200410.pdf](https://github.com/mozilla/pdf.js/files/6298513/RXO_www_enPatufet_19200410.pdf)
[patufet_avuiFa100anys_19200410-23204.pdf](https://github.com/mozilla/pdf.js/files/6298514/patufet_avuiFa100anys_19200410-23204.pdf)

Configuration:

- Mozilla Firefox 87.0 (64 bits)
- MacOSX 10.14

**Do you plan to implement this?**

**As a PDF developer, how can we help?**

In the other hand, you can see how it works (this is an ISO PDF/X-5 compliant feature), via the unique application can (I know) manage _Reference XObjects_ locally: Adobe Reader/Acrobat `[1]`. This couple of proxy/target files will work with AdobeReader (or Acrobat) in all platforms…

http://femfum.com/PDF/RXO_local_enPatufet_19200410.pdf (proxy recto/verso 8+8 nUp pages imposed)
http://www.femfum.com/patufet_avuiFa100anys_19200410-23204.pdf (target)

…preferably both files (proxy&target) in the same directory.

Many thanks,

`[1]`
Is mandatory to set it to:
```
# Preferences > Page Display > Show reference XObject target: Always & Location of referenced files: (browse location path)
# Preferences > Security (Enhaced) > Enable Enhaced Security (add folder path on privileged locations)
```

**Comment by Snuffleupagus** [comment] 2021-04-12 18:14
Sorry, but I'm finding it somewhat difficult to follow/understand what you're actually trying to report/ask here; can you please try to rephrase/improve this issue to make it easier to understand since as-is it's quite difficult to make sense of it?

For example, clearer "Steps to reproduce" would definitely help here (assuming you're reporting a bug)!
Also, direct links to the relevant part of the PDF specification would also help.

> But PDF.js does'nt work (you can see one blue/red cross for each empty page).
> [RXO_www_enPatufet_19200410.pdf](https://github.com/mozilla/pdf.js/files/6298513/RXO_www_enPatufet_19200410.pdf)
> [patufet_avuiFa100anys_19200410-23204.pdf](https://github.com/mozilla/pdf.js/files/6298514/patufet_avuiFa100anys_19200410-23204.pdf)

Those files render identical in PDF.js when I'm comparing (locally on Windows with) with other viewers, including e.g. Adobe Reader and PDFium in Google Chrome.

**Comment by Snuffleupagus** [comment] 2021-04-12 18:34
> But PDF.js does'nt work (you can see one blue/red cross for each empty page).
> [RXO_www_enPatufet_19200410.pdf](https://github.com/mozilla/pdf.js/files/6298513/RXO_www_enPatufet_19200410.pdf)
> [patufet_avuiFa100anys_19200410-23204.pdf](https://github.com/mozilla/pdf.js/files/6298514/patufet_avuiFa100anys_19200410-23204.pdf)

Those PDF files render *identically* in all PDF viewer I've tried (locally on Windows), which beside the PDF.js library include e.g. Adobe Reader and PDFium (in Google Chrome).

> …as a clear _Reference XObjects_ sample, that can be used to import content, via URL, from one PDF document into another (see Section 4.9.3, _Reference XObjects_ on PDF Reference v1.7).

This issue is a little bit difficult to follow/understand, so I'm guessing that you're actually referring to https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G7.2088383
Currently PDF.js simply falls into the following category, which all things considered seems fine:
> Those readers that do implement reference XObjects shall use the proxy in place of the imported content if the latter is unavailable.

First of all, I really cannot imagine that this feature is commonly used (since this is the first time we've seen it reported). Secondly, supporting something like that, i.e. loading arbitrary content from a URL seems like it could very well cause all sorts of security (and other) problems in general.

All things considered, I'd be strongly inclined to suggest WONTFIX here.

**Comment by marcantonifemfum** [comment] 2021-04-13 16:32
Hi Jonas,

> This issue is a little bit difficult to follow/understand, so I'm guessing that you're actually referring to https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G7.2088383

Yes, this is also an ISO PDF/X-5 feature… https://www.iso.org/standard/55844.html

&nbsp;
> First of all, I really cannot imagine that this feature is commonly used (since this is the first time we've seen it reported).

Pay attention on… https://www.iso.org/obp/ui/#iso:std:iso:15930:-8:ed-2:v1:en …section **8 PDF/X-5g conforming external graphical content** (screenshot attached)

On the other hand, we are implementing this function in an open source development (@marcantonifemfum pliegOS), which greatly simplifies the page imposition (nUp) in small editions (chapbooks). But this feature, for now, only works with Adobe Acrobat Reader (proprietary software) and we would like it to also be available in an Open Source viewer tool, like PDF.js

&nbsp;
> Secondly, supporting something like that, i.e. loading arbitrary content from a URL, seems like it could very well cause all sorts of security (and other) problems in general.

This is true on URL contexts, but not in local contexts. Please, download and try again, locally, with this sample:

`Configure the Adobe Acrobat Reader viewer (local working folder*)…`

1. First, select the local folder in: Preferences > Page Display > Show reference XObject target: Always & Location of referenced files: (select the path*)

2. Second, select also the local folder in: Preferences > Security (Enhaced) >  [Add Folder Path*] on Privileged Locations

3. Folders local names are not relevant, but never change the target filename! (also the trailer object /ID key is not validated)

Like this clip…
http://femfum.com/PDF/AdobeReaderPreferences_configuringReferenceXObjects.mov

`Download, copy in the working folder* the target file, 12 MB, portrait (822x1105.5 pt), a newspaper with 64 pages…`
http://femfum.com/bin/pliegOS/ATypI2020/SantJordi_diariARA_23042020.pdf

`Download, copy in the working folder* and OPEN this proxy file with the Acrobat viewer, 2 pages 8+8 nUp, 26 Kb file, landscape duplex A3 (1191x842 pt), that inoculates the first 16 pages from the target file…`
http://femfum.com/bin/pliegOS/ATypI2020/diariARAsantJordi_pliegOS.pdf

Do you think we can talk about implementing this ISO PDF/X-5 feature on PDF.js?

Thanks a lot,
&nbsp;

&nbsp;

![PDF_X-5_summaryContents](https://user-images.githubusercontent.com/1732712/114538956-3ed0f680-9c54-11eb-8565-8951679096d5.png)

**Comment by Snuffleupagus** [comment] 2021-04-13 17:35
> This is true on URL contexts, but not in local contexts.

Please keep in mind that the PDF.js library is *primarily* relevant when opening document from URLs (and not locally), since it's being used in browsers.

> On the other hand, we are implementing this function in an open source development (@marcantonifemfum pliegOS), which greatly simplifies the page imposition (nUp) in small editions (chapbooks).

Those use-cases doesn't seem entirely relevant to the PDF.js project (as far as I can tell), and please keep in mind that you can always implement your *own* viewer (based on the PDF.js library) with e.g. the requested features.

> Do you think we can talk about implementing this ISO PDF/X-5 feature on PDF.js?

I've already stated *my* position in https://github.com/mozilla/pdf.js/issues/13228#issuecomment-818036786, which is that this feature seem both uncommon enough and somewhat problematic (from a security perspective); unless this feature becomes *commonly* requested it doesn't really seem worth the trouble of implementing (possibly a subset of) it at this point.

**Comment by marcantonifemfum** [comment] 2021-04-15 09:57
Well, then, thank you and we will put it on the _ToDo_ list for the next few months…

**Closed** 2021-05-28 06:42 UTC
Labels: 1-other
