### ISSUE TITLE
Presentation mode does not retain the page magnification

### ISSUE THREAD

**Issue by TejAllam** [mozilla/pdf.js#14907] opened 2022-05-13 00:06 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 100
- Operating system and its version: Windows 10
- PDF.js version:
- Is a browser extension: No

Steps to reproduce the problem:
1. Open any PDF and magnify the document to 150%
2. Click on the 'Switch to Presentation Mode'

What is the expected behavior?
Expect to view the document magnified 

What went wrong?
The document magnification reverts back to original dimension. to Fit the screen maybe? 

Link to a viewer :

**Comment by Snuffleupagus** [comment] 2022-05-13 07:36
Duplicate of #5336

**Closed by Snuffleupagus** 2022-05-13 07:36 UTC
