### ISSUE TITLE
helloworld failed to render on one specific pdf

### ISSUE THREAD

**Issue by Skalkaz** [mozilla/pdf.js#7215] opened 2016-04-18 10:24 UTC
I have tested pdf.js with 12 independent pdf from the net. One of them failed.
Link to PDF file (or attach file here):
https://www.ets.org/Media/Tests/GRE/pdf/gre_research_validity_data.pdf

Console.log:
pdf.worker.js:42554 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
pdf.worker.js:2311 Error: JPEG error: marker was not found
pdf.worker.js:2312     at error (http://localhost:8081/pdf.worker.js:2312:17)
    at Object.JpegStream_ensureBuffer [as ensureBuffer] (http://localhost:8081/pdf.worker.js:20614:7)
    at Object.JpegStream_getBytes [as getBytes] (http://localhost:8081/pdf.worker.js:20619:10)
    at Object.PDFImage_getImageBytes [as getImageBytes] (http://localhost:8081/pdf.worker.js:34359:25)
    at Object.PDFImage_createImageData [as createImageData] (http://localhost:8081/pdf.worker.js:34262:31)
    at http://localhost:8081/pdf.worker.js:37141:34
pdf.worker.js:2298 Warning: Unable to decode image: Error: JPEG error: marker was not found
pdf.js:277 Warning: Dependent image isn't ready yet

Configuration:
- Web browser and its version: latest chrome
- Operating system and its version: ubuntu
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2016-04-18 10:30
Closing as duplicate of issue #4090.

**Closed by Snuffleupagus** 2016-04-18 10:30 UTC
