### ISSUE TITLE
Always in light mode even when using a dark mode firefox theme

### ISSUE THREAD

**Issue by bjorn3** [mozilla/pdf.js#12290] opened 2020-08-27 10:44 UTC
Attach (recommended) or Link to PDF file here: Any pdf

Configuration:
- Web browser and its version: Firefox Developer Edition 81.0b1 (64-bit)
- Operating system and its version: Debian 10
- PDF.js version: PDF.js: 2.6.276
- Is a browser extension: Firefox builtin pdf reader

Steps to reproduce the problem:
1. Set builtin dark theme for Firefox.
2. Open any pdf in Firefox.

What is the expected behavior? (add screenshot)

pdf.js uses dark colors

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/17426603/91433024-e71b8180-e862-11ea-8123-17be8bb59324.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by timvandermeij** [comment] 2020-08-27 19:56
@utopianknight From your screenshots you did manage to get the viewer in the dark theme, and the code is also there. Do you perhaps have an idea why this might not work here?

**Comment by brendandahl** [comment] 2020-08-27 22:58
Strange, dark mode works fine for web version, but not built in version. Looks like there's some code to override this in Firefox. I'll open an upstream bug.

**Comment by brendandahl** [comment] 2020-08-27 23:12
One thing to clarify, using a dark mode theme in Firefox doesn't change everything to dark mode that uses the CSS `prefers-color-scheme: dark`. That has to be set at the operating system level. 

Though even if I set the OS to dark mode, the built in PDF viewer doesn't change themes.

**Comment by utopianknight** [comment] 2020-08-28 04:45
This seems to be a problem with Firefox, not PDF.js. Open these and play around with it in Firefox and in a chromium browser:
- https://codepen.io/jonneal/pen/vzPwWo
- https://color-scheme-demo.glitch.me/

Until this is fixed and as a temporary workaround, I can make the dark theme the default since it's what Firefox users have been accustomed to.

**Comment by utopianknight** [comment] 2020-08-28 04:57
Changing the theme with Menu > Customize > Themes > Light/Dark does not work.

But changing the theme in the dev tools (with devtools.inspector.color-scheme-simulation.enabled set to true in about:config) does work.

**Comment by bjorn3** [comment] 2020-08-28 05:31
> One thing to clarify, using a dark mode theme in Firefox doesn't change everything to dark mode that uses the CSS prefers-color-scheme: dark. That has to be set at the operating system level.

Unfortunately setting a dark mode theme for the xfce desktop is not detected by firefox.

**Comment by brendandahl** [comment] 2020-08-28 17:50
On linux there isn't a concept of light/dark mode in gtk, so a heuristic is used https://searchfox.org/mozilla-central/rev/d54712b9644b49cec6cc90a9e0c325fdfab04e7c/widget/gtk/nsLookAndFeel.cpp#1009-1023

**Comment by brendandahl** [comment] 2020-09-02 20:36
> Though even if I set the OS to dark mode, the built in PDF viewer doesn't change themes.

After a browser restart dark mode is working on MacOS for me.

**Comment by Silur** [comment] 2020-09-25 09:48
untill today using the Dark Reader addon worked fine but after yesterday's update the pdf.js page got "protected by browser" so addons cannot access it and we are back to the eye burning bright version

**Comment by sunjerry019** [comment] 2020-09-27 06:19
A temporary fix that worked for me was going to `about:config` and adding a new property `ui.systemUsesDarkTheme` of type `Number` with value `1`.

**Comment by bjorn3** [comment] 2020-09-27 08:02
Thanks @sunjerry019 for pointing me to that config!

**Comment by A6GibKm** [comment] 2020-09-28 09:31
The solution by sunjerry019 did not work for me. What did work was setting `privacy.resistFingerprinting` to false. This is clearly not a good solution.

**Comment by k4yt3x** [comment] 2020-09-28 16:37
I can also confirm setting `privacy.resistFingerprinting` to `false` also works for me.

**Comment by A6GibKm** [comment] 2020-09-28 16:49
Somehow privacy settings do not allow the ~~hack~~ heuristic described above used to detect dark theme on gtk.

**Comment by bayuah** [comment] 2020-10-11 07:28
I can confirm that @sunjerry019 method works for me on my Lubuntu 20.04 system.

> A temporary fix that worked for me was going to `about:config` and adding a new property `ui.systemUsesDarkTheme` of type `Number` with value `1`.

**Comment by gsbnlda** [comment] 2020-11-03 05:03
> 
> 
> A temporary fix that worked for me was going to `about:config` and adding a new property `ui.systemUsesDarkTheme` of type `Number` with value `1`.

not working on win 10 64 bit FF stable.

**Comment by gsbnlda** [comment] 2020-11-03 05:12
I need help still do not find a best solution to make all web pages in dark mode with clear fonts . tried add-ons night eye , dark reader , midnight lizard, shadowbox , https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/ , css file ( https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme ) but not perfect dark mode with clear fonts . pages are not well settled in center and boxes are not perfect. set ui.systemUsesDarkTheme to 1 in about:config also not working .

**Comment by Mulej** [comment] 2020-11-14 14:14
How hard would it be to add a toggle to the secondary toolbar for toggling dark/light mode (regardless of the system theme)? This would add a workaround for all current and any future issues with light/dark mode detection.

**Comment by k4yt3x** [comment] 2020-11-14 20:35
I hope this gets addressed soon. For now I'm downloading all PDFs and viewing them locally so my eyes aren't burnt out. Turning off RFP works, but is not a solution nor a workaround. It's a security compromise.

**Comment by qwer1304** [comment] 2020-11-27 09:56
Why isn't this preference exported to Options?

**Comment by alonetrifle** [comment] 2021-01-01 16:05
> 
> 
> A temporary fix that worked for me was going to `about:config` and adding a new property `ui.systemUsesDarkTheme` of type `Number` with value `1`.

worked perfectly i was going to use pdf.js on chrome but this worked very well thanks for your help <3 ,also happy new year

**Comment by Silur** [comment] 2021-01-02 12:36
> A temporary fix that worked for me was going to `about:config` and adding a new property `ui.systemUsesDarkTheme` of type `Number` with value `1`.

Does not work on 84.0.1 (64-bit) arch linux

**Comment by bjorn3** [comment] 2021-01-02 12:52
Do you have `privacy.resistFingerprinting` set to `true`? That will force a light mode theme to be reported to everyone.

**Comment by Snuffleupagus** [comment] 2021-01-20 16:08
Please note that after PR #12625, there's a preference that can be used to *force* the use of either the light or dark viewer theme.

Specifically, for the Firefox built-in PDF Viewer, the preference is named `pdfjs.viewerCssTheme` and can be created/set using `about:config` starting with Firefox 85.
The Firefox preference is of the `number`-kind, with the following values supported:
 - `0` = automatic theme, based on e.g. operating system and/or browser settings; this is the default value.
 - `1` = light theme.
 - `2` = dark theme.

With those changes I don't believe that we can realistically do much more about this issue *here*, and any further improvement requests (w.r.t. to e.g. auto-detecting the mode "better") would need to be filed in Bugzilla instead.

**Comment by A6GibKm** [comment] 2021-01-20 16:36
Thanks for the headsup, saddly it did not work here.

**Comment by Snuffleupagus** [comment] 2021-01-20 17:17
> sadly it did not work here.

Without any more context/information, such a statement unfortunately isn't actionable!

If I were to guess, you might have missed the "starting with **Firefox 85**."-part in https://github.com/mozilla/pdf.js/issues/12290#issuecomment-763739702.

**Comment by timvandermeij** [comment] 2021-01-20 19:48
Closing since all that can be done on our end is done now. The rest should be tracked upstream in Bugzilla instead.

**Closed by timvandermeij** 2021-01-20 19:48 UTC
Labels: 1-viewer, 3-upstream

**Comment by A6GibKm** [comment] 2021-01-20 20:11
@Snuffleupagus Thanks, for the reply, otherwise I would have never seen that small, and very easy to miss detail ( /s ), indeed it worked thanks.
