### ISSUE TITLE
Extremly slow rendering since iOS 11 Update (iPad mini 4)

### ISSUE THREAD

**Issue by ghost** [mozilla/pdf.js#8954] opened 2017-09-25 15:39 UTC
Link to PDF file (or attach file here):

Configuration:
- Device
iPad Mini 4

- Web browser and its version:
Google Chrome Version 61.0.3163.73

- Operating system and its version:
iOS 11

- PDF.js version:
1.9.598

Steps to reproduce the problem:
The attached PDF is served as base64-encoded-String to PDF.js and the rendering is very very slow. It takes about 6 seconds per page.

What is the expected behavior?
Rendering the whole file in about 1 second (like in iOS 10)

**Comment by yurydelendik** [comment] 2017-09-25 15:56
Looks like it's a regression in iPad 4 / iOS11. Did you contact the vendor with the problem?

**Comment by StriesseParadise** [comment] 2017-09-25 16:01
You mean i should contact Apple, that the rendering speed of is so much slower since the upgrade?

**Comment by yurydelendik** [comment] 2017-09-25 16:05
> You mean i should contact Apple, that the rendering speed of is so much slower since the upgrade?

yes, if the same software (PDF.js) behaves different after OS upgrade -- problem mostly likely with OS.

**Comment by yoerivdm** [comment] 2017-12-19 12:01
Experiencing the same problem on iOS11 and Safari 11.

A few things we tested and noticed 
- Only Safari 11+, tested on 10 without any problem.
- Safari 11 on macOS High Sierra is unresponsive while rendering this pdf
- Firefox an Chrome have no problem rendering this PDF.

My PDFs are rendered with PhantomPDF (jsReport), the one you referenced is created with wkhtmltopdf. 

I think it's a combination of renderer and safari that causes the problem ...

**Comment by Snuffleupagus** [comment] 2021-01-30 11:34
This issue is quite old, and given that it mentions a specific platform/browser it unfortunately seems quite unlikely to be actionable/valid for the PDF.js project; hence I'd suggest closing this issue.

**Closed** 2021-01-30 12:17 UTC
Labels: 4-os-ios
