### ISSUE TITLE
Pdf files will become blurred when enlarged

### ISSUE THREAD

**Issue by PandaLi0** [mozilla/pdf.js#13927] opened 2021-08-23 07:24 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Google Chrome  83.0.4103.97
- Operating system and its version:windows 10
- PDF.js version:v2.9.359
- Is a browser extension:

Steps to reproduce the problem:
1. Preview PDF files online
2. Zoom in 400 times
3. It is very clear in version 1.x

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by PandaLi0** [comment] 2021-08-23 07:57
![L~ $EL5G @5RF1_9 KKMS3C](https://user-images.githubusercontent.com/89379131/130411339-188bb9f4-9f60-4053-8e34-153ba0165089.png)

**Comment by Snuffleupagus** [comment] 2021-08-23 08:17
> Attach (recommended) or Link to PDF file here:

This part of the issue template is *always required* in order for any issue to actionable/valid.

> Steps to reproduce the problem:
>     1. Preview PDF files online
>     2. Zoom in 400 times
>     3. It is very clear in version 1.x

In that case, I'm guessing that this is essentially a duplicate of #6419.

**Closed by Snuffleupagus** 2021-08-23 08:17 UTC
