### ISSUE TITLE
Rendering Layered Content

### ISSUE THREAD

**Issue by punithAcuta** [mozilla/pdf.js#9315] opened 2017-12-26 05:39 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Any
- Operating system and its version: Any
- PDF.js version: Any
- Is a browser extension: No

Steps to reproduce the problem:
1. When opening any PDF Document which as 'Layered' in PDF.js its does not differentiate the layered Content, in fact the  directly rendered in text layer.
2. When Open the same PDF document(Layered) in Adobe, we can show and hide the layered content by check and un-check the check box in layer tab 

What is the expected behavior? (add screenshot)
Can we able to find where exactly the layers content are build and can we able to show and hide the layered content...?

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-12-26 10:08
> When opening any PDF Document which as 'Layered' [...]

*For future reference:* As explicitly asked for in the issue template, please remember to *always* attach an example PDF file to the issue. 

---
Closing as duplicate of issue #269.

**Closed by Snuffleupagus** 2017-12-26 10:08 UTC
