### ISSUE TITLE
ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/pdf.js#10355] opened 2018-12-13 19:29 UTC
I'm trying to run |gulp mozcentral| on an up-to-date pdf.js tree and am hitting the following error:

```
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/home/ryanvm/repos/pdfjs/node_modules/natives/index.js:137:5)
    at require (/home/ryanvm/repos/pdfjs/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/home/ryanvm/repos/pdfjs/node_modules/natives/index.js:137:5)
    at require (/home/ryanvm/repos/pdfjs/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/home/ryanvm/repos/pdfjs/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/ryanvm/repos/pdfjs/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/ryanvm/repos/pdfjs/node_modules/gulp/node_modules/graceful-fs/fs.js:1:99)
```

I've tried updating my npm packages and everything is current AFAICT.

**Comment by timvandermeij** [comment] 2018-12-13 22:01
This problem occurs on the master branch here as well because Gulp 4 became `latest` recently. Pull request #10266 will fix this, so I'm closing this as a duplicate of that one.

**Closed by timvandermeij** 2018-12-13 22:01 UTC
