### ISSUE TITLE
not show seal

### ISSUE THREAD

**Issue by skioll** [mozilla/pdf.js#9399] opened 2018-01-24 04:56 UTC
Attach (recommended) or Link to PDF file here:
[B25N236012018026603-204.pdf](https://github.com/mozilla/pdf.js/files/1658464/B25N236012018026603-204.pdf)

Configuration:
- Web browser and its version: Mozilla/5.0 (Linux; Android 4.4.4; MI 5 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Safari/537.36 Truck Alliance/Consignor (domainId 1; Version 4.9.0)
- Operating system and its version: Android4.4.4
- PDF.js version:1.9.426
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
red seal not show
in pdf.js
![image](https://user-images.githubusercontent.com/18202306/35315176-e34f5d48-0105-11e8-8e6d-3217b395c5e2.png)
in pc client
![image](https://user-images.githubusercontent.com/18202306/35315200-f69178c8-0105-11e8-81dc-0e3e2d25f59b.png)

**Comment by Snuffleupagus** [comment] 2018-01-24 09:09
Closing as duplicate of issues such as #1076, #4202, and #4743.

**Closed by Snuffleupagus** 2018-01-24 09:09 UTC

**Comment by rmhrisk** [comment] 2018-02-26 07:22
@skioll FYI: the file you provided has at least two issues:

1. It does not include the issuer certificate, e.g. it only includes the signing certificate and it should contain everything but the root certificate.
2. The signing certificate includes a AIA:issuercert reference that points to a non-existent host (http://bjca.org/).

No client that has not been configured to work around these situations will be able to validate this file with this issue.

**Comment by rmhrisk** [comment] 2018-02-27 18:40
If your interested here is your document viewed in a PDFjs based web viewer that supports signatures: https://manage.hancock.ink/document?url=https://peculiarventures.github.io/ExamplePDFs/signed/B25N236012018026603-204.pdf
