### ISSUE TITLE
Please include all information about annotations necessary to render them ourselves

### ISSUE THREAD

**Issue by kevinbeal** [mozilla/pdf.js#12484] opened 2020-10-16 15:09 UTC
Attach (recommended) or Link to PDF file here:

[download (4).pdf](https://github.com/mozilla/pdf.js/files/5392464/download.4.pdf)

Configuration:
- Web browser and its version: Brave 1.14.84
- Operating system and its version: Ubuntu 20.04.1
- PDF.js version: 2.6.347
- Is a browser extension: no

Steps to reproduce the problem:
1. Load a pdf
2. get the annotations via `page.getAnnotations()`

What is the expected behavior? (add screenshot)
That there be information like the fill color of a circle annotation, the end cap style of a line, font information, etc. There is nothing for stamps but it's location, size.

What went wrong? (add screenshot)
We only get a bare bones location of the annotation, its type and some coordinates for points in lines, polylines, etc.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
The demo viewer is sufficient to highlight the issue. You just have to put a breakpoint where the annotations are returned.

**Comment by timvandermeij** [comment] 2020-10-16 19:17
Duplicate of #5283.

**Closed by timvandermeij** 2020-10-16 19:17 UTC
