### ISSUE TITLE
wrong recognition for non-BMP Unicode characters

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#5890] opened 2015-03-29 09:01 UTC
I’m afraid that pdf.js suffers from the bug described at sumatrapdfreader/sumatrapdf/issues/150.

http://www.unicode.org/charts/PDF/U20000.pdf#page=46 contains character U+20A3B 𠨻 which is recognized as character U+0A3B ਻.

As far as I know, glyph is displayed fine. It affects to search and copy.

**Comment by Snuffleupagus** [comment] 2019-02-10 09:28
Duplicate of #10529.

**Closed** 2019-02-10 13:49 UTC
Labels: 4-text-selection
