### ISSUE TITLE
URL not displaying as hyperlink in document footer

### ISSUE THREAD

**Issue by ApoorvaDx22** [mozilla/pdf.js#14960] opened 2022-05-26 09:30 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Version 101.0.4951.67 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Enterprise
- PDF.js version:  '2.8.335'
- Is a browser extension: no

Steps to reproduce the problem:
1. Open any PDF using this plugin
2. Go to the footer section and check the url in the text

What is the expected behavior? (add screenshot)
url should show as hyperlink
What went wrong? (add screenshot)
url is showing as plain text

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

<img width="868" alt="pdf1" src="https://user-images.githubusercontent.com/106306644/170460377-db971fa2-4249-4ef2-b657-995940b07941.png">
<img width="868" alt="pdf2" src="https://user-images.githubusercontent.com/106306644/170460389-0ae60fd8-0ca0-4e28-8c4a-4a7d7fa49022.png">

**Comment by Snuffleupagus** [comment] 2022-05-26 09:52
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required*, since as-is this issue unfortunately isn't actionable.

> PDF.js version:  '2.8.335'

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

Duplicate of #3172 (which is a best guess, given the lack of enough details).

**Closed by Snuffleupagus** 2022-05-26 09:52 UTC
Labels: information-requested

**Comment by ApoorvaDx22** [comment] 2022-05-26 10:06
Hi , The latest version of this viewer has size greater than 5 MB which the file size limitation for our system which is Salesforce and we are using this as astatic resource. Could we get a compressed version (size< 5 MB) for the latest release. Thanks!
