### ISSUE TITLE
PDF note rendering correctly

### ISSUE THREAD

**Issue by pythonBerg** [mozilla/pdf.js#11190] opened 2019-10-01 20:14 UTC
Attach (recommended) or Link to PDF file here:
[bad pdf.pdf](https://github.com/mozilla/pdf.js/files/3678314/bad.pdf.pdf)

I am using a customized pdfjs viewer to create a review and annotation platform for financial documents. I have processed 1000's with no problems as each document has been used in transactions across multiple users and desktop configurations. Recently, I've  hit something I need some help understanding.

Client app on windows 10, served from ubuntu 18.10. Rendering is issue on Chrome, Firefox, MS Edge and every other browser I've tried. It is not an issue in acrobat or Abbyy fine reader. It also renders incorrectly on these same browsers run on linux client. It renders incorrectly from both my custom viewer and the pdfjs demo online...

I was always under the impression that the text layer was embedded underneath the image...I would better understand if there was misalignment. I've seen references to issues here re font configuration but wouldn't that affect equally the other viewers?

Any guidance for potential steps I might undertake to resolve is appreciated.

current:
![image](https://user-images.githubusercontent.com/22894385/65996625-c46fc580-e465-11e9-92bc-303a66614fe2.png)

expected:
![image](https://user-images.githubusercontent.com/22894385/65996724-f97c1800-e465-11e9-8ccd-b328e6205a27.png)

**Comment by Snuffleupagus** [comment] 2019-10-01 20:19
Looks like a duplicate of #5550.

**Closed** 2019-10-01 21:12 UTC

**Comment by pythonBerg** [comment] 2019-10-01 21:28
Has this been open since 2014 without a resolution? Is there any way I can
help resolve this?
