### ISSUE TITLE
Slow rendering of PDF document

### ISSUE THREAD

**Issue by PdfRegistry** [mozilla/pdf.js#10719] opened 2019-04-09 09:08 UTC
Attach (recommended) or Link to PDF file here:
Document 24087563_noclientinfo.pdf attached below.

Configuration:
Web browser and its version: Firefox, Chrome, IE
Operating system and its version: Windows 7, Windows 10
PDF.js version: latest (or whatever's on mozilla.github.io/pdf.js/web/viewer.html)
Is a browser extension: No

Steps to reproduce the problem:
Open the PDF in the Demo viewer

What is the expected behavior? (add screenshot)
Expected the PDF to open and render each page in a second or less.

What went wrong? (add screenshot)
The document is taking over 5 seconds to open and render.
Page 4 takes the longest to render.

**Comment by timvandermeij** [comment] 2019-04-09 21:18
Closing until the PDF file is provided (in which case we can reopen this), otherwise the issue is not actionable.

**Comment by RickGan** [comment] 2019-04-10 00:47
[24087563_noclientinfo.pdf](https://github.com/mozilla/pdf.js/files/3061504/24087563_noclientinfo.pdf)

**Comment by THausherr** [comment] 2019-04-12 11:24
Page 4 has a JPX image (3507 x 2480, so probably 300dpi) but its size is 4 MB. The page 3 image is much smaller (180KB) despite that it looks similar. This PDF was created by "Redax Enterprise Server 3.1.2 Linux Kernel 2.6 64bit Dec  6 2010 Library 9.0.1".

**Comment by menver** [comment] 2019-05-17 14:18
From our analysis this PDF is made up of many objects which is causing a delay for all pages.
I dont think PDF.js is processing this as images but as objects.
We are doing further analysis in-house to see if we can provide further insight.

**Comment by menver** [comment] 2019-12-23 14:54
We have analysed this as far as we can. Same conclusion as THausherr

**Comment by amit777** [comment] 2020-09-27 04:57
I've just tried opening this in Chrome on my macbook air, 8GB ram (about 5 years old).  seems to load fine for me:

```
const pdfjsVersion = '2.7.90';
const pdfjsBuild = '6728c8fa6';
```

**Comment by menver** [comment] 2020-09-28 09:25
HI amit77 thank you for your comment.
I can only conclude this is a windows specific issue if you cannot see this on a mac.
Many thanks

**Comment by d3xMachina** [comment] 2023-10-02 13:53
3 years later and the issue is still present. The above pdf linked by RickGan and many others I usually open have the same performance issue, they take ages to load. On Edge the pdf loads instantly. I have a 13600k and I'm on Windows 11. I tried using the troubleshooting mode and it's the same.

**Comment by timvandermeij** [comment] 2024-04-16 16:24
Closing since the pages now render in about one second, most likely thanks to #17946 which introduced a more performant decoder, which is likely the best we can reach for such large images.

**Closed by timvandermeij** 2024-04-16 16:24 UTC
Labels: core, performance, image-jpx, image-conversion
