### ISSUE TITLE
PDF printing not look like display

### ISSUE THREAD

**Issue by brouillon** [mozilla/pdf.js#8497] opened 2017-06-07 12:52 UTC
Link to PDF file (or attach file here):
[#-186.pdf](https://github.com/mozilla/pdf.js/files/1057969/-186.pdf)

This document is generated with dompdf

Configuration:
- Web browser and its version: Firefox 53.0.3 (64 bits)
- Operating system and its version: Linux Mint 18.1
- PDF.js version: default version in Firefox 53.0.3 ?

Steps to reproduce the problem:
1. Display the attached pdf is --> OK
2. Print in file or with a printer

What is the expected behavior?
The printed version should be the same as the displayed version
This is a print in file with evince :
[sortie.pdf](https://github.com/mozilla/pdf.js/files/1057995/sortie.pdf)

What went wrong? (add screenshot)
Quality was poor, font was blur, and mainly the footer table was not part of printing version
This is a print in file with pdf.js :
[Fac.pdf](https://github.com/mozilla/pdf.js/files/1057999/Fac.pdf)

**Comment by yurydelendik** [comment] 2017-06-07 14:53
Closing as duplicate of #8075

**Closed by yurydelendik** 2017-06-07 14:53 UTC

**Comment by brouillon** [comment] 2017-06-07 16:56
The mainly thing here is not the blurry effect as in #8075 but the footer table was not part of printing version.
Evince result :
![evince](https://user-images.githubusercontent.com/2931266/26890715-cbeba0fc-4bb2-11e7-83a6-6bd0bbc16587.png)
PDF.js result :
![pdfjs](https://user-images.githubusercontent.com/2931266/26890725-d50b746e-4bb2-11e7-9a3b-0e3ad4d74afe.png)

Where is the table ? 
Please @yurydelendik reopen this issue

**Comment by yurydelendik** [comment] 2017-06-07 17:08
was paper size (8.27 × 11.7 inches) selected properly -- Fac.pdf appears to be 8.5 × 11? it is #8166 ? Currently there is no way for web application to know paper size.

**Comment by brouillon** [comment] 2017-06-07 17:28
Good catch ! Default value in print setting was "US letter" instead of "A4", after that print is alright !

You say no way for a web application to know paper size, bad thing :( 
It seem's firefox won't get this value correctly configured for my locale (FR_fr)
Any idea where to ask about that ? Mint ? cinnamon ? ubuntu ? debian ? firefox ? pdf.js ?

**Comment by yurydelendik** [comment] 2017-06-07 17:30
is this value configured in printer settings (at OS level) and can be changed in Firefox?

**Comment by brouillon** [comment] 2017-06-07 19:08
Evince, Geany use the same window printer settings as Firefox, Writer (LO) use another one.
this window is at OS level, I test in a VM with Firefox on win XP and this was set to A4.

Evince give me good result without any change, but don't know if A4 or US Letter was set before i change it for pdf.js, maybe different values were used ?
