### ISSUE TITLE
Type 1 shadings not supported

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6295] opened 2015-07-31 20:40 UTC
tested with
http://107.21.233.14:8877/2d43c75f950d82e/web/viewer.html

not rendered:
http://asymptote.sourceforge.net/gallery/latticeshading.pdf
http://asymptote.sourceforge.net/gallery/functionshading.pdf
http://asymptote.sourceforge.net/gallery/strokeshade.pdf
https://issues.apache.org/jira/secure/attachment/12625919/FUNSH01.pdf
https://issues.apache.org/jira/secure/attachment/12625920/RGBCUBE.pdf

All are type 1 shadings = function based shadings. To get this to work, the trick is to "clean" a device coordinate of any transforms (i.e. reverse-apply them), then apply the function(s), to get the color. (No I can't do it myself here, my JS capabilities are too limited)

see also:
https://issues.apache.org/jira/secure/attachment/12646800/eci_altona-test-suite-v2_technical_H.pdf
That file is impossible to render correctly (even Adobe Reader doesn't render it perfectly) and too complex to debug, but it is a sort of success indicator. The first rectangle on the left is a type 1 shading.

**Comment by yurydelendik** [comment] 2016-01-05 23:23
Dup of #5046

**Comment by Snuffleupagus** [comment] 2017-06-06 13:22
Closing as duplicate of issue #5046.

**Closed by Snuffleupagus** 2017-06-06 13:22 UTC
Labels: 2-image-quality, 4-shading-pattern
