### ISSUE TITLE
Doesn't show up images and signatures included in the PDF 

### ISSUE THREAD

**Issue by eugen-admortgage** [mozilla/pdf.js#15106] opened 2022-06-27 13:16 UTC
Attach (recommended) or Link to PDF file here: [test.pdf](https://github.com/mozilla/pdf.js/files/8993902/test.pdf)

~~[https://dropmefiles.com/vOFWN](https://dropmefiles.com/vOFWN) (*Edit:* Attached the file directly above, to save peoples time.)~~

Configuration:
- Web browser and its version: Chrome 103.0.5060.53, Firefox 101.0.1
- Operating system and its version: MacOs 12.4 and Windows 7, 10
- PDF.js version: 2.14.305
- Is a browser extension: no

Steps to reproduce the problem:
1. Open that document in pdf.js
2. Doesn't show up images included in the PDF 

What is the expected behavior? (add screenshot)
normal showing if opened only in google chrome

**normal view**: https://i.imgur.com/q2mfsil.png

What went wrong? (add screenshot)
Doesn't show up images included in the PDF 
if that PDF doc open in chrome or acrobat reader that images are showed

**sample issue**: https://i.imgur.com/DqFtQ0P.png

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-06-27 14:51
Closing as INCOMPLETE for now, please see https://github.com/mozilla/pdf.js/issues/15106#issuecomment-1167356072 to re-open the issue.

**Comment by eugen-admortgage** [comment] 2022-06-27 16:05
doc's link shared

**Comment by eugen-admortgage** [comment] 2022-06-29 13:43
there are no errors in the console

**Comment by Snuffleupagus** [comment] 2023-06-18 14:57
Duplicate of #16038

**Closed by Snuffleupagus** 2023-06-18 14:57 UTC
Labels: tiling-type
