### ISSUE TITLE
 if the text to be found is across pages in the file, it cannot be located

### ISSUE THREAD

**Issue by bjzhaoxy** [mozilla/pdf.js#16458] opened 2023-05-23 08:25 UTC
When I use the following code to find and highlight the specified text in a document, if the text to be found is across pages in the file, it cannot be located. This has nothing to do with the specific file, the file in the attachment is randomly uploaded, any file can be reproduced.

if (keyword?.length) {
	findBar.findField.value = keyword
	findBar.findField.select()
	findBar.highlightAll.checked = true
	findBar.dispatchEvent('highlightallchange')
}

[The Art of Asking ChatGPT for High-Quality Answ... (Z-Library).pdf](https://github.com/mozilla/pdf.js/files/11541349/The.Art.of.Asking.ChatGPT.for.High-Quality.Answ.Z-Library.pdf)

**Comment by Snuffleupagus** [comment] 2023-05-23 08:27
Duplicate of #10620

*For future reference:* Please actually fill out the ISSUE_TEMPLATE properly when opening an issue.

**Closed by Snuffleupagus** 2023-05-23 08:27 UTC
