### ISSUE TITLE
Fonts don't load when rendering to external document/window

### ISSUE THREAD

**Issue by jsg2021** [mozilla/pdf.js#12121] opened 2020-07-24 20:57 UTC
This happens with all pdfs I've tried. I don't think its document specific. I'm adding pdf viewer to an app, and its working as expected, however, I was asked to pop the view into its own window. I've simulated the behavior in a sandbox link below by rendering it into an iframe.  Is there a way I can load fonts in the new 'window' context? Other than the fonts it looks to be working as expected. This is a pretty fringe case, so I don't expect it to be "fixed" in the library, but it would be nice to be pointed to where I can pull the fonts into the other window.

Configuration:
- Web browser and its version: any?
- Operating system and its version: any?
- PDF.js version: 2.4.456
- Is a browser extension: no

Steps to reproduce the problem:
1. give the pdf viewer a container node in a different window/document.

What is the expected behavior? (add screenshot)
Fonts load

What went wrong? (add screenshot)
No fonts
![image](https://user-images.githubusercontent.com/577453/88434295-844b4c00-cdc5-11ea-96af-4722918aa35f.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://codesandbox.io/s/lucid-architecture-xxw8h?file=/src/App.js

**Comment by Snuffleupagus** [comment] 2020-07-24 21:01
Looks like a duplicate of #8271.

**Closed** 2020-07-24 21:11 UTC

**Comment by jsg2021** [comment] 2020-07-24 21:13
Sure enough! Doesn't look like there were any tips about getting the fonts into my alt frame. I don't want to render just one page in a canvas in a frame... I want the whole viewer, with the app context. Sorry for the duplicate. I'll look for a way to trigger the fonts to load or sync them.
