### ISSUE TITLE
Texts show up in the wrong place and overlapped over other texts.

### ISSUE THREAD

**Issue by takahiroyoshi** [mozilla/pdf.js#4841] opened 2014-05-26 13:32 UTC
http://www.kccs.co.jp/ict/mobile-pilina/leaflet_pilina_wimax_201312.pdf
Open the second page.

![wrong_place](https://cloud.githubusercontent.com/assets/3334552/3082835/08b3278c-e4da-11e3-9e1b-352b3fb1d1a0.jpg)

Firefox 29.0 on Windows 8.1
I tested it at:
http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by richerm** [comment] 2016-04-18 14:40
We ran into a similar issue with hidden layers in the PDF, properly not showing in Adobe Acrobat but visible in PDF.JS.

I'm not familiar with the code base to attempt a fix but I did take some time to look at PDFs to determine where that information is stored using the PDF Object Browser (http://brendandahl.github.io/pdf.js.utils/browser/).

1) Root has OCProperties/D dictionaries for ON/OFF layers.  Layers which are visible are listed under "ON" layers that are hidden are listed under "OFF".

2) Those layers in #1 are in the OCGs array under OCProperties which includes the layer name and the 'intent array'.  Note this intent array ID.

3) For a given page, under Resources/Properties there are references to MC0-MCX which has the layer name and the intent array which refers to the same id found in #2.

4) Under "Contents (stream)" each resource (in the content itself) refers to the layer it corresponds to: "/OC /MC0 BDC" (i.e. MC0).

Granted I don't have the Adobe spec to confirm that is sufficient but that should point in the right direction.  With the above information, you can determine which resources should (and should not) be displayed.

Hope that helps point someone in the right direction for a fix!

**Comment by dionatanaraujo** [comment] 2017-07-17 19:26
Richerm thanks for shared your experience!

It helped a lot.

Below is the code generated for solve the similar problem with "hidden layers".
```
var _hiddenLayers = resources.xref.root.map.OCProperties.map.D.get('OFF');
for (var _xx = 0; _xx < _hiddenLayers.length; _xx++) {
     // _propName is key that you want remove. It's possible use another.
     var _propName = resources.xref.fetchIfRef(_hiddenLayers[_xx]).get('Name');
     if (dict.get(_propName)) {
	return true;
     }
}
```

I hope it helps other people.

**Comment by Snuffleupagus** [comment] 2019-11-10 10:56
Duplicate of #269

**Closed** 2019-11-10 12:02 UTC
Labels: 2-feature, 2-image-quality
