### ISSUE TITLE
android and ipad prolem with zoom

### ISSUE THREAD

**Issue by sabq-ads** [mozilla/pdf.js#7912] opened 2016-12-23 01:45 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Firefox 47.0.1
- Operating system and its version: Windows 10 Pro 64 bits
- PDF.js version:
- Is an extension: zoom proplem with android

Steps to reproduce the problem:
1. Extra space on the right when i use  zoom on iphone, ipad, android and cant show full image when i use zoom

What is the expected behavior? (add screenshot)
![img_0030_1](https://cloud.githubusercontent.com/assets/8226450/21445445/f645727c-c8c9-11e6-9d91-fdc9ddf5f2ed.png)

What went wrong? (add screenshot)

The normal picture
![img_0032_1](https://cloud.githubusercontent.com/assets/8226450/21445479/62b9b008-c8ca-11e6-84b1-c5357731c9b8.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2016-12-23 14:07
Closing as incomplete. No PDF.js version, as well as no link to the custom solution, has been provided. It's not really clear from the issue description what the problem is. If it's more black background space on the right than on the left, then it's a duplicate of #4186.

**Closed by timvandermeij** 2016-12-23 14:07 UTC
