### ISSUE TITLE
someone know how to support Optional Content

### ISSUE THREAD

**Issue by dawnlvcn** [mozilla/pdf.js#10624] opened 2019-03-06 17:54 UTC
case 'UseOC':
 // Not implemented, since we don't support Optional Content Groups yet.

**Comment by timvandermeij** [comment] 2019-03-06 22:29
Closing since this is basically a duplicate of #269. It's a large feature to implement and doesn't seem to be used very often, so it's not on our priority list.

**Closed by timvandermeij** 2019-03-06 22:29 UTC
