### ISSUE TITLE
Font not displaying characters properly (standard char set)

### ISSUE THREAD

**Issue by hamble** [mozilla/pdf.js#8480] opened 2017-06-02 16:38 UTC
Link to PDF file (or attach file here): https://www.ordinate.buzz/sample.pdf

Configuration:
- Web browser and its version: Issue occurs on FF and Chrome. Works on IE
- Operating system and its version: Windows 10
- PDF.js version: //mozilla.github.io/pdf.js/build/pdf.js
- Is an extension:

Steps to reproduce the problem:
My code (standard code pasted from samples) is below. The file displays 'normally' in a PDF viewer, but with PDF.JS on Chrome/Firefox, it doesn't. 

What went wrong? 

Various letters of the font in the top line of text don't get rendered properly. The font in question is called 'GE Inspira Sans'

See Screenshot.

![capture](https://cloud.githubusercontent.com/assets/13876525/26735484/0905e832-47ba-11e7-9489-496ab0cc9ea6.PNG)

<script>	
	var url = 'sample.pdf';

// Disable workers to avoid yet another cross-origin issue (workers need
// the URL of the script to be loaded, and dynamically loading a cross-origin
// script does not work).
// PDFJS.disableWorker = true;

// The workerSrc property shall be specified.
PDFJS.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';

// Asynchronous download of PDF
var loadingTask = PDFJS.getDocument(url);
loadingTask.promise.then(function(pdf) {
  console.log('PDF loaded');
  
  // Fetch the first page
  var pageNumber = 1;
  pdf.getPage(pageNumber).then(function(page) {
    console.log('Page loaded');
    
    var scale = 1.5;
    var viewport = page.getViewport(scale);

    // Prepare canvas using PDF page dimensions
    var canvas = document.getElementById('the-canvas');
    var context = canvas.getContext('2d');
    canvas.height = viewport.height;
    canvas.width = viewport.width;

    // Render PDF page into canvas context
    var renderContext = {
      canvasContext: context,
      viewport: viewport
    };
    var renderTask = page.render(renderContext);
    renderTask.then(function () {
      console.log('Page rendered');
    });
  });
}, function (reason) {
  // PDF loading error
  console.error(reason);
});	
</script>	
<canvas id="the-canvas" style=" position: absolute;top:0;bottom: 0;left: 0;right: 0;margin:auto;"></canvas>

**Comment by timvandermeij** [comment] 2017-06-02 21:48
I can reproduce this using Firefox 53.0.3 on Arch Linux with the latest PDF.js development add-on.

**Comment by hamble** [comment] 2017-06-08 11:05
Hi @Snuffleupagus  -  do you have any advice on this one? Hoping to have this working next week :) Any help is much appreciated!

**Comment by Snuffleupagus** [comment] 2017-06-08 11:48
> Hi @Snuffleupagus - do you have any advice on this one? Hoping to have this working next week :) Any help is much appreciated!

I've only looked briefly, and concluded that it's related to how we detect OpenType fonts, but haven't had time to look into a possible solution yet.
When making changes to the font code in PDF.js, it's possible to cause regressions elsewhere, which often makes fixing font bugs time consuming. When it comes to OpenType in particular, we've had a number of issues/regressions in the relevant code, which means that testing a potential solution takes some time.

Since I'm *not* paid to work on PDF.js, but rather do it for "fun" in my spare time, I cannot promise a time-line for a patch.[1] I'll *possibly* look at this later in the week, but please do not interpret that as a guarantee!

---
[1] Also, please keep in mind that since PDF.js is free open-source software, giving exact time-lines for when a certain issue will be fixed can often be difficult.

**Comment by THausherr** [comment] 2017-06-08 12:08
@hamble did you generate this PDF yourself? The FontFile2 stream must be "A stream containing a TrueType font program". Yours isn't, it is an OpenType font containing CFF data. See "Embedded font organization for various font types" in the [PDF specification](https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf).

**Comment by hamble** [comment] 2017-06-08 12:19
I generated it using Bytescout PDFSDK. It opens and displays correctly in various PDF viewers, and within the browsers themselves, and indeed in IE within PDF.JS.

**Comment by hamble** [comment] 2017-06-08 12:24
@Snuffleupagus  - yes of course, completely understand! Your efforts are much appreciated :)

**Comment by THausherr** [comment] 2017-06-08 12:37
@hamble The argument "but it displays on ....." comes up all the time. It works on some (not all - I have two where it doesn't) viewers because the devs put a lot of effort to be lenient on bad PDFs. Nevertheless, your PDF is incorrect. The best thing would be to tell the problem to Bytescout PDFSDK and/or use a truetype font.

**Comment by hamble** [comment] 2017-06-08 13:57
Thanks for info. I have contacted them.

________________________________

**Comment by hamble** [comment] 2017-06-08 15:36
An online OTF-TTF converter resolves the problem. Thanks both for your advice.

**Closed** 2017-06-23 20:36 UTC
Labels: 4-font-conversion, 4-font-opentype
