### ISSUE TITLE
The browser is closing automatically while trying to open long PDF files

### ISSUE THREAD

**Issue by 1396252309** [mozilla/pdf.js#5759] opened 2015-02-25 09:43 UTC
Hi, I use the pdf.js to show PDF files in browser,but the browser(safari) is closing automatically while trying to open long PDF files(more than 30 pages) on ipad, so I let it to to displays 10 page at each time, before it display new pages, I remove the old canvas, but browser still closed, I guess pdf.js is very memory intensive, is there any fix for this?

**Comment by yurydelendik** [comment] 2015-02-27 13:40
Closing as duplicate of #5563

**Closed by yurydelendik** 2015-02-27 13:40 UTC
Labels: 4-os-ios
