### ISSUE TITLE
An eraser tool is also required with the recently added pdf annotation tool

### ISSUE THREAD

**Issue by diovalos** [mozilla/pdf.js#15610] opened 2022-10-22 03:13 UTC

**Comment by Snuffleupagus** [comment] 2022-10-22 07:29
This is possibly a duplicate of #15519, but it's simply *impossible* to tell with no other information than a a slightly cryptic title (which is why you should always fill out the ISSUE_TEMPLATE when opening an issue).

**Closed by Snuffleupagus** 2022-10-22 07:29 UTC
