### ISSUE TITLE
Cannot a open a pdf using local dev server in Chrome

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14533] opened 2022-02-04 17:19 UTC
STR:
 - run `gulp server`
 - open http://localhost:8888/web/viewer.html?file=/test/pdfs/tracemonkey.pdf in Chrome

In the console I get:
```
ReferenceError: require is not defined                     es-module-shims.js:769
    at checkStructuredClone (compatibility.js:114:5)
    at compatibility.js:115:5
```

**Comment by Snuffleupagus** [comment] 2022-02-04 17:49
Duplicate of #14512; please update to Google Chrome 98 (or above) to fix that.

**Closed by Snuffleupagus** 2022-02-04 17:49 UTC
