### ISSUE TITLE
Potential CSS Conflicts

### ISSUE THREAD

**Issue by tymoorej** [mozilla/pdf.js#14760] opened 2022-04-07 14:01 UTC
Please move to using more unique css class names.

For example, instead of:
textLayer

use
PDFJS-textLayer

This will prevent css conflicts that may occur.

**Comment by Snuffleupagus** [comment] 2022-04-07 14:05
Duplicate of #6706

Generally we advise placing the viewer in e.g. an `<iframe>` element to prevent these sort of issues.

**Closed by Snuffleupagus** 2022-04-07 14:05 UTC
