### ISSUE TITLE
zooms only bar when "zoom text only"

### ISSUE THREAD

**Issue by mihacz** [mozilla/pdf.js#8547] opened 2017-06-20 06:05 UTC
When "zoom text only" is on and you hit ctrl++ or ctrl+-, only bar gets bigger.
Just disable "zoom text only" on pdf.js cards and it will be ok.

Mozilla 52 on 64 bit ubuntu 16.04 lts

**Comment by Snuffleupagus** [comment] 2017-06-20 10:21
> When "zoom text only" is on and you hit ctrl++ or ctrl+-, only bar gets bigger.

I'm assuming that the underlying issue is that the PDF viewer wasn't focused when the keyboard shortcuts were used, which implies that this actually is a duplicate of issue #4263.
In particular, see https://github.com/mozilla/pdf.js/issues/4263#issuecomment-34553317; closing as duplicate of the various Bugzilla bugs referred there.

**Closed by Snuffleupagus** 2017-06-20 10:21 UTC
