### ISSUE TITLE
Only the characters are on the left. It is out of line with the underline on Japanese documents.

### ISSUE THREAD

**Issue by Ja22sasa** [mozilla/pdf.js#13342] opened 2021-05-06 03:20 UTC
Attach (recommended) or Link to PDF file here:
[jpb6094287.pdf](https://github.com/mozilla/pdf.js/files/6431509/jpb6094287.pdf)
[jpb6235261.pdf](https://github.com/mozilla/pdf.js/files/6431511/jpb6235261.pdf)

Configuration:
- Web browser and its version: Google Chrome v89.0.4389.114 /IE ver 20H2 (OS build 19042.928)/Microsoft Edge 89.0.774.77 (64 bit)
- Operating system and its version: Windows 10 Pro 20H2 19042.928
- PDF.js version: 2.7.570
- Is a browser extension: No

Steps to reproduce the problem:

As you can see from the attached jpb6094287.pdf [jpb6094287.pdf](https://github.com/mozilla/pdf.js/files/6431509/jpb6094287.pdf) or jpb6235261.pdf [jpb6235261.pdf](https://github.com/mozilla/pdf.js/files/6431511/jpb6235261.pdf),
When using PDF.js, only the characters move to the left on Japanese documents. It is out of line with the underline.
What went wrong? I hope to solve this problem.

I tried to improve after seeing these pages.

https://github.com/mozilla/pdf.js/issues/12110
https://github.com/mozilla/pdf.js/pull/13067

But the problem with this information was that the textLayer output and the canvas drawing were out of alignment.
In the case I give this time, the textLayer output and the canvas drawing are not out of alignment. Both are left-aligned.
Adobe Reader does not have this problem.

What is the expected behavior? (add screenshot)
See the right side of the image below
![error1](https://user-images.githubusercontent.com/82868736/117236901-b0235400-ae64-11eb-8031-d583401c6943.jpg)
![error2](https://user-images.githubusercontent.com/82868736/117236909-b44f7180-ae64-11eb-94fa-16e60f8c2262.jpg)

What went wrong? (add screenshot)
See the left side of the image below
![error1](https://user-images.githubusercontent.com/82868736/117236901-b0235400-ae64-11eb-8031-d583401c6943.jpg)
![error2](https://user-images.githubusercontent.com/82868736/117236909-b44f7180-ae64-11eb-94fa-16e60f8c2262.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-05-06 07:00
Duplicate of #13343, please note https://github.com/mozilla/pdf.js/issues/13343#issuecomment-833278377.

**Closed** 2021-05-07 18:39 UTC
