### ISSUE TITLE
PDF renders incorrectly with error

### ISSUE THREAD

**Issue by sethnk** [mozilla/pdf.js#6243] opened 2015-07-21 20:59 UTC
Tested in the latest build (1.1.326).

PDF file:  http://seth.redirectme.net/med/pdf/55ae64d8a0db5.pdf

The following PDF renders incorrectly and throws the following error:

Message: Invalid number: ¬
Stack: Error: Invalid number: ¬
    at error (chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:247:9)
    at Object.Lexer_getNumber [as getNumber](chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:30760:9)
    at Object.Lexer_getObj [as getObj](chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:31001:23)
    at Object.Parser_shift [as shift](chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:30142:32)
    at Object.Parser_makeStream [as makeStream](chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:30519:12)
    at Object.Parser_getObj [as getObj](chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:30187:28)
    at Object.XRef_fetchUncompressed [as fetchUncompressed](chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:4289:28)
    at Object.XRef_fetch [as fetch](chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:4246:26)
    at Object.XRef_fetchIfRef [as fetchIfRef](chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:4227:19)
    at Object.Dict_get [as get](chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:3120:28)

**Comment by timvandermeij** [comment] 2015-07-21 21:06
I get `bad Xref entry` and `"Error: Illegal character: 41`, but the cause is the same: the parser is probably ending up in the middle of stream because the Xref stream header cannot be read.

**Comment by Snuffleupagus** [comment] 2015-07-21 21:57
Prior to PR #5910, this PDF file actually rendered correctly, despite triggering `Error: Invalid XRef stream header`. Hence I'm labelling this issue as a regression.

/cc @jordan-thoms

**Comment by Snuffleupagus** [comment] 2015-09-01 09:33
It appears that the file is broken enough that we've never been able to successfully render all pages.

It did get somewhat worse (with even fever pages rendering) after PR #5910 landed, but with PR #6375 landed it now renders approximately as before; hence I'm removing the `regression` label.

**Comment by Snuffleupagus** [comment] 2019-11-01 22:13
At this point in time I do wonder if it wouldn't make sense to close this issue as WONTFIX, given that as mentioned in https://github.com/mozilla/pdf.js/pull/11231#issue-327325948 no PDF viewer seem to be able to handle this file particularly well (not even Adobe Reader).

/cc @timvandermeij What do you think?

**Comment by timvandermeij** [comment] 2019-11-02 22:06
Yes, I also don't think there is more we can do about this PDF file after all recent fixes. It's just too broken to recover.

**Closed by timvandermeij** 2019-11-02 22:06 UTC
Labels: 1-core, 3-pdf-broken, 4-corrupted-pdf
