### ISSUE TITLE
pdf.js interacts poorly with Chrome's cache in some cases

### ISSUE THREAD

**Issue by osheroff** [mozilla/pdf.js#13452] opened 2021-05-28 02:11 UTC
Hi, 
PDFs of certain sizes don't seem to play well with Chrome's cache in a cold-cache scenario; the range-request (206) HTTP calls seem to queue up behind the full-PDF request, leading to situations where the browser downloads the PDF fully before anything is rendered.  See the following screenshot:

<img width="1387" alt="Screen Shot 2021-05-27 at 6 58 29 PM" src="https://user-images.githubusercontent.com/260084/119918829-06dcf480-bf1e-11eb-909a-965dbd916eb1.png">

As you can see from the waterfall graph, Chrome decides that the range-requests -- the ones that could lead to a faster time-to-first-page render -- should instead simply wait until the full request is finished.  I haven't done a deep-dive into the chromium source code, but there seems to be a heuristic at play here; a 40mb PDF triggers this condition whereas a 100mb PDF does not.  

I'm looking into a couple of local workarounds.  Due to the size of these PDFs (presentations, very graphic heavy) I'd prefer to not just slap `no-cache` directives everywhere, but I'm thinking it might be ok to default to `no-cache` behavior on the range-requests?  This could also probably be worked around if one simply ensured that the 206 requests were fired off before the full-pdf download.

Any thoughts?  I know it's technically not pdf.js' problem, but it certainly is a bad user experience; in some cases PDF.js simply goes blank for >10 seconds while the whole file loads.

Configuration:
Chrome  90.0.4430.212, arm64
OSX Big Sur 11.2.3
PDF.js 2.8.335
Note that I am running with the vue-pdf wrapper.  Haven't yet verified that it's not the cause, but all it's really doing is `.getDocument()`

Try rendering a 40mb pdf with a cold cache.

**Comment by Snuffleupagus** [comment] 2021-05-28 06:15
> but there seems to be a heuristic at play here; a 40mb PDF triggers this condition whereas a 100mb PDF does not.

That does indeed seem to put the blame entirely on Chrome here, and it's unfortunately very difficult to see that we could do anything about this issue *here*.

Furthermore, as-is this cannot really be easily reproduced, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by osheroff** [comment] 2021-05-28 10:09
sorry, which are you saying here?  Are you WONTFIX'ing this or are you asking for a repro?  

If you're interested in seeing the issue for yourself and collaborating a possible patch, I'm happy to spend the time putting together a repro of the issue.  But if you're not interested in a work-around (and I deeply suspect the best that can be done here is a work-around), then it's hard for me to want to spend the time to package up the issue for you to see; in that world I'll just continue tinkering around with the issue locally and look for a reasonable fix.

**Comment by timvandermeij** [comment] 2021-05-28 19:20
If there is something we can do here we can certainly attempt, but the issue as reported is not actionable at the moment. If this only happens in Chrome, it would be much better to report it to their issue tracker instead since it's unlikely we can do something about it here. Moreover, as it's written now we can't actually reproduce this, mainly because no PDF files are provided that showcase this issue.

Therefore at this point in time this would be a WONTFIX unless more details are provided that point to an actual bug in PDF.js.

**Comment by timvandermeij** [comment] 2021-05-30 10:59
Closing until more details are provided that show that this is in fact an actionable issue for PDF.js since that's currently not clear. Note that we keep browser-specific workarounds to the bare minimum, so if this does involve a workaround it's likely we won't accept it. Chances are that it's more likely to be resolved upstream in Chrome.

**Closed by timvandermeij** 2021-05-30 10:59 UTC
Labels: 4-information-requested

**Comment by osheroff** [comment] 2021-05-30 17:00
your perogative, I suppose.  If you won't accept a possible patch I won't bother to put together a repro.

For anyone who might find this in the future that actually needs to fix their issue, this patch is a fairly easy workaround:

```
diff --git a/src/display/fetch_stream.js b/src/display/fetch_stream.js
index f2225fa49..703c684ad 100644
--- a/src/display/fetch_stream.js
+++ b/src/display/fetch_stream.js
@@ -229,6 +229,7 @@ class PDFFetchStreamRangeReader {
     }

     this._headers = createHeaders(this._stream.httpHeaders);
+    this._headers.append("cache-control", "no-cache");
     this._headers.append("Range", `bytes=${begin}-${end - 1}`);

     const url = source.url;
```

If I come up with a cleaner way than this I'll post it.
