### ISSUE TITLE
bounding box around all rendered content

### ISSUE THREAD

**Issue by nschloe** [mozilla/pdf.js#5880] opened 2015-03-25 09:00 UTC
I would like to display a PDF page "autocropped", i.e., with all white space from the page border removed. Is this possible yet in PDF.js by any chance? Where would I have to dig if not? 
(I can see that this relates to https://github.com/mozilla/pdf.js/issues/2550, plus computing a bounding box around the rendered page content.)

**Comment by timvandermeij** [comment] 2015-03-25 19:03
It is not possible yet, and as far as I can tell from your description this appears to be a duplicate of #2288, so for now I'm closing this as such.

**Closed by timvandermeij** 2015-03-25 19:03 UTC
