### ISSUE TITLE
Horizontal stripes in images

### ISSUE THREAD

**Issue by fosple** [mozilla/pdf.js#9464] opened 2018-02-09 10:20 UTC
Attach (recommended) or Link to PDF file here:
[124368.pdf](https://github.com/mozilla/pdf.js/files/1710568/124368.pdf)
[109059.pdf](https://github.com/mozilla/pdf.js/files/1710569/109059.pdf)

Configuration:

Web browser and its version: Chrome 63.0.3239.132
Operating system and its version: MacOS 10.13.2
PDF.js version: pdfjs 1.9.426

Steps to reproduce the problem:
- Open PDF

What is the expected behavior? / What went wrong?

Stripes in image:

![124368_stripes](https://user-images.githubusercontent.com/4522947/36022960-24400f32-0d8b-11e8-93a9-6bf359877723.png)
![109059_stripes](https://user-images.githubusercontent.com/4522947/36023237-0ea2114c-0d8c-11e8-854e-023ecb5c3cd3.png)

**Comment by Snuffleupagus** [comment] 2018-02-09 10:26
Closing as duplicate of e.g. issue #3351.

**Closed by Snuffleupagus** 2018-02-09 10:26 UTC
