### ISSUE TITLE
IE 11 not showing the characters properly when font download is disabled.

### ISSUE THREAD

**Issue by ssurana2** [mozilla/pdf.js#7424] opened 2016-06-20 06:18 UTC
Link to PDF file (or attach file here): 
[sample.pdf](https://github.com/mozilla/pdf.js/files/322766/sample.pdf)

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: Windows 7 Virtual Machine
- PDF.js version: 1.4.20
- Is an extension: No

Steps to reproduce the problem:
1. Open IE 11
2. Open `settings` and then go to `Internet Options`
3. Go to `security` tab and click on `customize level...` button
4. Scroll down to the section `Downloads`
5. Under `Downloads` disable `Font download`
6. Click on `Ok` and then click on `Apply`.
7. Open the above attached PDF, you would see that the horse that is getting displayed at the bottom of the page in other browsers would be replaced with 123 in font download disabled IE 11.

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/10023250/16184557/df7f0a0c-36da-11e6-8934-4b29facd5927.png)

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/10023250/16184529/a5a81116-36da-11e6-833d-a6187b1951d2.png)

Have used viewer.html to render the attached pdf file.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Regards
Sumit

**Comment by Snuffleupagus** [comment] 2016-06-20 09:57
Closing as duplicate of issue #6018.
In particular, please refer to https://github.com/mozilla/pdf.js/issues/6018#issuecomment-103162379 for a possible work-around.

**Closed by Snuffleupagus** 2016-06-20 09:57 UTC
