### ISSUE TITLE
Zoom level is changing after printing

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15324] opened 2022-08-16 10:11 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Mac OS 12.5

Steps to reproduce the problem:
1. Open a pdf and set the zoom level to auto 
2. click on the print button
3. dismiss the print dialog
4. the pdf is unzoomed (around 80%)

Before printing:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5641725/184854681-fc37b1fd-de98-4711-9d97-d16353f94f2d.png">

After printing:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5641725/184854436-573c49d0-0f28-4323-94c0-cef525d6c0f3.png">

**Comment by Snuffleupagus** [comment] 2022-08-16 10:41
This affect both the Firefox PDF Viewer as well as the generic viewer (i.e. https://github.com/mozilla/pdf.js#online-demo), and according to mozregression it's caused by the following commit:
```
2022-08-16T12:38:14.836000: DEBUG : Found commit message:
Bug 774398 - Hack to make print and viewport media query listeners fire when printing. r=geckoview-reviewers,owlish,dholbert

This still doesn't fire on print settings changes, so it uses the
default page size. Which is probably better than nothing, but...

To make viewport-size media-query listeners work more generally for
printed documents, we would need to re-clone the top document
unconditionally for all print settings changes, which needs front-end
work at least, and is dubious if the page changes dynamically.

Differential Revision: https://phabricator.services.mozilla.com/D150499

2022-08-16T12:38:14.836000: DEBUG : Did not find a branch, checking all integration branches
2022-08-16T12:38:14.840000: INFO : The bisection is done.
2022-08-16T12:38:14.868000: INFO : Stopped
```

**Comment by calixteman** [comment] 2022-08-16 10:55
I get this exception in the console:
```
offsetParent is not set -- cannot scroll [viewer.js:2958:13](resource://pdf.js/web/viewer.js)
    scrollIntoView resource://pdf.js/web/viewer.js:2958
    #scrollIntoView resource://pdf.js/web/viewer.js:10430
    scrollPageIntoView resource://pdf.js/web/viewer.js:10693
    _setScaleUpdatePages resource://pdf.js/web/viewer.js:10475
    _setScale resource://pdf.js/web/viewer.js:10556
    set currentScaleValue resource://pdf.js/web/viewer.js:9914
    webViewerResize resource://pdf.js/web/viewer.js:2268
    dispatch resource://pdf.js/web/viewer.js:3543
    windowResize resource://pdf.js/web/viewer.js:1954
    triggerPrinting resource://pdf.js/web/viewer.js:1849
    webViewerPrint resource://pdf.js/web/viewer.js:2303
    dispatch resource://pdf.js/web/viewer.js:3543
    bindListeners resource://pdf.js/web/viewer.js:13911
    (Asynchrone : EventListener.handleEvent)
    #bindListeners resource://pdf.js/web/viewer.js:13899
    Toolbar resource://pdf.js/web/viewer.js:13851
    _initializeViewerComponents resource://pdf.js/web/viewer.js:751
    initialize resource://pdf.js/web/viewer.js:494
    run resource://pdf.js/web/viewer.js:790
    webViewerLoad resource://pdf.js/web/viewer.js:15275
    (Asynchrone : EventListener.handleEvent)
    <anonyme> resource://pdf.js/web/viewer.js:15283
    <anonyme> resource://pdf.js/web/viewer.js:15285
    <anonyme> resource://pdf.js/web/viewer.js:15287
```

**Comment by Snuffleupagus** [comment] 2022-08-16 10:58
The problem is that "resize" event, on the original window, is now triggered during printing which is wasn't before https://bugzilla.mozilla.org/show_bug.cgi?id=774398 landed.
We could easily hack-around that for now, which given the dates in https://wiki.mozilla.org/Release_Management/Calendar probably makes sense to do here.

**Closed** 2022-08-16 12:41 UTC
Labels: regression, upstream, printing, firefox-specific
