### ISSUE TITLE
re. resolution, font issues

### ISSUE THREAD

**Issue by parksuhyun9321** [mozilla/pdf.js#17866] opened 2024-04-02 01:10 UTC
Attach (recommended) or Link to PDF file here:

Configuration:

Web browser and its version: chrome
Operating system and its version: android 11
PDF.js version: v3.11.174
Is a browser extension: No

Steps to reproduce the problem:  
1. When in portrait mode on a specific page, the text is overlapped. Rendered normally in landscape mode
2. Open same pdf file in https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)
https://github.com/mozilla/pdf.js/assets/59465364/5baed7c4-b887-49af-84a0-7923de020e2f

What went wrong? (add screenshot)
https://github.com/mozilla/pdf.js/assets/59465364/369edd5d-b209-4e5b-b1db-386338070c2a

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2024-04-02 07:28
Duplicate of #17864

**Closed by Snuffleupagus** 2024-04-02 07:28 UTC
