### ISSUE TITLE
Incorrect view of PDF

### ISSUE THREAD

**Issue by VictoriaSarycheva** [mozilla/pdf.js#14302] opened 2021-11-24 15:20 UTC
Attach (recommended) or Link to PDF file here:  https://drive.google.com/file/d/1Dwg0H5uEnmgikKyVpB5T1x-KKwtzRm0G/view?usp=sharing

Configuration:
- Web browser and its version: Chrome 96.0.4664.55
- Operating system and its version: MAC OS, Catalina 0.15.4 
- PDF.js version: the last one
- Is a browser extension: no

Steps to reproduce the problem:
1. open pdf on pdf.js demo page and any application to preview the original view

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/41724810/143265588-2c29a2ed-37a8-435c-912c-251eb6517fd3.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/41724810/143265648-10ed2c6e-8683-4e1b-9523-20dea2c84966.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by SamyCookie** [comment] 2021-11-25 09:05
I can reproduce this bug with Chromium 93 and PDF.js 2.11.243 on a Linux Debian Buster OS.

However, on the same machine, I cannot reproduce in Firefox 93 with the builtin PDF.js and with the 2.11.243 version, nore with Okular viewer and the built-in Chromium viewer too.

So, it seems a PDF.js bug specific to Chromium browser (or a Chromium browser bug).

**Comment by VictoriaSarycheva** [comment] 2021-11-26 10:22
Could be. But it's much important for us and our users to use a Chrom. Would be great to have a fix
Thank you

**Comment by Snuffleupagus** [comment] 2021-11-26 10:26
> PDF.js version: the last one

As mentioned previously, please provide an actual version *number* when reporting an issue (since "the last one" is ambiguous and consequently not useful).

> But it's much important for us and our users to use a Chrome.

Please keep in mind that the *primary focus* of development for the PDF.js library is Firefox.

**Comment by VictoriaSarycheva** [comment] 2021-11-29 14:29
PDF.js version: 2.10.377

**Comment by Snuffleupagus** [comment] 2021-12-12 15:03
Given that this apparently is specific to just *one* browser (i.e. Google Chrome), it unfortunately suggests e.g. a `canvas`-related bug in the browser *itself* rather than a general PDF.js library bug. If it were a bug *here*, you'd really expect it to be consistently broken across all browsers; hence closing since this unfortunately doesn't look fixable here.

**Closed by Snuffleupagus** 2021-12-12 15:03 UTC
Labels: 1-core, 4-chrome-specific
