### ISSUE TITLE
PDF.js renderer crashing on transparent shapes

### ISSUE THREAD

**Issue by antjkennedy** [mozilla/pdf.js#7675] opened 2016-09-26 14:09 UTC
Link to PDF file (or attach file here): http://www.gsk.com/media/1017500/annual-report-2015.pdf

Configuration:
- Web browser and its version: **Google Chrome 53.0.2785.116 (64-bit)**
- Operating system and its version: **Mac OSX 10.11.6**
- PDF.js version: Version included with extension from Chrome Web Store
- Is an extension: Yes [1.5.294 from Chrome Web Store](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm)

Steps to reproduce the problem:
1. Open this link http://www.gsk.com/media/1017500/annual-report-2015.pdf and the extension will crash whilst trying to render the PDF
2. Looking through the Chrome Logs and doing some further investigation it looks like the WebGL renderer is crashing when trying to render the translucent bubbles found on some of the pages. Removing the offending pages allows the extension to render the PDF just fine.

What is the expected behavior? The PDF is rendered without crashing 

![good_render](https://cloud.githubusercontent.com/assets/1441259/18837258/00708660-83fb-11e6-84d0-9f6ba8d995ff.png)

What went wrong? Rendering of the PDF crashes the extension.
![bad_render](https://cloud.githubusercontent.com/assets/1441259/18837318/401a9774-83fb-11e6-9ad2-5e6141b8b983.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm

**Comment by yurydelendik** [comment] 2016-09-26 17:29
Able to reproduce using demo viewer at http://mozilla.github.io/pdf.js/web/viewer.html. It does not crash in 55 though. Looks like the Chrome team fixed the upstream issue. You are welcome to bisect and find when/how it was fixed.

**Comment by timvandermeij** [comment] 2016-10-09 15:04
Closing as fixed as it appears there is nothing else we can do here since it's already fixed upstream.

**Closed by timvandermeij** 2016-10-09 15:04 UTC
Labels: 3-upstream, 4-chrome-specific
