### ISSUE TITLE
Fonts not applied correctly when render target is in an iFrame

### ISSUE THREAD

**Issue by bdares** [mozilla/pdf.js#5902] opened 2015-04-02 16:28 UTC
This might be user error, but I have a use case where I'm trying to render to a container that is in an iFrame.  The rendering mostly works, but fonts do not appear to be applied correctly.

You can see a live example [here](http://station.tagcreativestudio.com/PDFTest/reader.html).  The same page is rendered to a div in the main document (left), and the body of an iframe (right).

**Comment by yurydelendik** [comment] 2015-04-02 16:36
Canvas is using fonts registered in the current HTML document. PDF.js is registering fonts in the documents it's running at. So either you have to move code into iframe or keep the canvas in the main document.

**Comment by Snuffleupagus** [comment] 2015-04-02 17:59
Closing as duplicate of issue #5148.

**Closed by Snuffleupagus** 2015-04-02 17:59 UTC

**Comment by bdares** [comment] 2015-04-02 18:23
This isn't a duplicate - it's not caused by conflicting font IDs, it's a result of rendering to a canvas that doesn't have access to the fonts that are loaded (correctly).  I think a "wontfix" may be more appropriate.

**Comment by yurydelendik** [comment] 2015-04-03 15:13
agree
