### ISSUE TITLE
"1 setlinecap 100 100 moveto closepath stroke" fails to display

### ISSUE THREAD

**Issue by ms0** [mozilla/pdf.js#11882] opened 2020-05-07 15:20 UTC
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/4593480/test.pdf)

Configuration:
- Web browser and its version: firefox 76.0 (64-bit)
- Operating system and its version: Windows 10 Home version 1909
- PDF.js version: 2.4.456 (prebuilt, freshly downloaded from github)
- Is a browser extension: no

Steps to reproduce the problem:
1. open attached pdf file in pdf.js viewer
2. notice that a blank page is shown

What is the expected behavior? (add screenshot)
should see what is shown when viewed by Acrobat reader (three black dots arranged horizontally)

What went wrong? (add screenshot)
blank page was shown

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2020-05-07 15:47
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1633908 - there's no reason to track this twice.

**Closed** 2020-05-07 21:50 UTC
