### ISSUE TITLE
Various rendering errors

### ISSUE THREAD

**Issue by jethrogb** [mozilla/pdf.js#8600] opened 2017-07-02 21:13 UTC
Link to PDF file (or attach file here): https://docs.wixstatic.com/ugd/afc658_9d3aff6b4a554a35bb70c8234e770fce.pdf

Configuration:
- Web browser and its version: Firefox 53.0.3 (64-bit)
- Operating system and its version: Arch Linux
- PDF.js version: whatever comes with Firefox

There are various hidden elements that PDFjs renders but are not shown in other viewers I've tried: Okular, Imagemagick, etc.

Expected:
![imagemagick](https://user-images.githubusercontent.com/1132307/27773531-f3124e38-5f7b-11e7-9dff-cc22ffb0446d.png)

PDF.js:
![pdfjs](https://user-images.githubusercontent.com/1132307/27773532-f3176e18-5f7b-11e7-9a16-d24b38096348.png)

**Comment by Snuffleupagus** [comment] 2017-07-03 07:32
Closing as duplicate of issue #269.

**Closed by Snuffleupagus** 2017-07-03 07:32 UTC
