### ISSUE TITLE
Regular zoom

### ISSUE THREAD

**Issue by aleksamatic** [mozilla/pdf.js#7678] opened 2016-09-28 10:25 UTC
This is not really an issue, it is a question.

I'm using pdf.js library for an Android project.
Could you tell me how to enable standard webview zoom in the provided viewer.js.
Best regards,
Hope you don't mind I've raised an issue for this

**Comment by yurydelendik** [comment] 2016-09-28 13:06
The issue/question does not contain a problem statement and its resolution. I'm guessing it's a duplicate of #2582. Closing as such.

**Closed by yurydelendik** 2016-09-28 13:06 UTC
