### ISSUE TITLE
Strange characters in some pdfs

### ISSUE THREAD

**Issue by danielehrhardt** [mozilla/pdf.js#15895] opened 2023-01-05 12:59 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
108.0.2 32bit 
- Operating system and its version:
Windows 11
- PDF.js version:
embedded in firefox
- Is a browser extension:
no

Steps to reproduce the problem:
1. open the file in firefox
2. chrome works

[test.pdf](https://github.com/mozilla/pdf.js/files/10352303/test.pdf)

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/19570043/210785538-61ae4c46-8fbd-45af-8fdc-fad684d9310c.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/19570043/210785572-9c4141b8-734d-44c9-ba7d-e61050ed6072.png)

**Comment by Snuffleupagus** [comment] 2023-01-05 13:40
Effectively a duplicate of https://github.com/mozilla/pdf.js/issues/15289, please see e.g. https://github.com/mozilla/pdf.js/issues/15289#issuecomment-1208565298 for additional details.

**Closed by Snuffleupagus** 2023-01-05 13:40 UTC

**Comment by calixteman** [comment] 2023-01-06 15:08
@danielehrhardt do you have the original fonts used to create this pdf ? If yes, could you attach the font named `NimbusSans-Regular` ?
What is the software used to create this pdf ?

**Comment by danielehrhardt** [comment] 2023-01-11 08:16
> @danielehrhardt do you have the original fonts used to create this pdf ? If yes, could you attach the font named `NimbusSans-Regular` ? What is the software used to create this pdf ?
[DNO_20220922ONO_08153333.docx](https://github.com/mozilla/pdf.js/files/10390093/DNO_20220922ONO_08153333.docx)

Arial 12 Microsoft Word saved as PDF. I attached to Word Document.
