### ISSUE TITLE
Cross or X input showing in all checkboxes, not just user selected

### ISSUE THREAD

**Issue by mvg2967** [mozilla/pdf.js#13086] opened 2021-03-12 16:13 UTC
Attach (recommended) or Link to PDF file here:
[UAI.pdf](https://github.com/mozilla/pdf.js/files/6131267/UAI.pdf)

Configuration:
- Web browser and its version: Firefox 86.0.1 (64 bit)
- Operating system and its version: macOS Mojave 10.14.6
- PDF.js version: 2.7.510
- Is a browser extension: False

Steps to reproduce the problem:
1. Open pdf in Firefox and go to section title Demographics, all checkboxes under Race and Communications of Needs are selected

What is the expected behavior? (add screenshot)
From Adobe Acrobat, under Race, only _Unknown_ is selected, and under Communication of Needs, only _Verbally, English_ is selected. This expected behavior is reproducible in Chrome, IE, Edge and Safari.
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/7281265/110966174-01124280-8323-11eb-924e-49bceb018c95.png">

What went wrong? (add screenshot)
All checkboxes under Race and Communications of Needs are selected, despite user only selecting one choice underneath each section.
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/7281265/110966677-83026b80-8323-11eb-8808-a8a5497ac4b0.png">

**Comment by Snuffleupagus** [comment] 2021-03-12 16:24
Duplicate of #12716

**Comment by calixteman** [comment] 2021-03-12 17:22
It works as expected in firefox nighly (88).

**Closed by calixteman** 2021-03-12 17:22 UTC
