### ISSUE TITLE
PDF of an HD image not displayed

### ISSUE THREAD

**Issue by pirasalbe** [mozilla/pdf.js#12658] opened 2020-11-25 08:31 UTC
### Attach (recommended) or Link to PDF file here:

I can't share the original file, but I managed to create some others:
* [example 15MB](https://github.com/mozilla/pdf.js/files/5595239/32k.pdf)
* [example 5MB](https://github.com/mozilla/pdf.js/files/5595313/16k.pdf) (this one works with the Angular Library but not with Firefox)

The error seems to happen with PDF files of a single HD image. I can't compress the file or the original image.

### Configuration:
- Web browser and its version: 
  * Firefox 83.0
  * [Angular Library ng2-pdfjs-viewer](https://github.com/intbot/ng2-pdfjs-viewer) 
- Operating system and its version: Linux Mint 20 Cinnamon and Windows 10
- PDF.js version: 
  * PDF.js v2.7.99 (build: 88f72d6b1) in Firefox
  * PDF.js v2.2.171 in Angular
- Is a browser extension: No

### Steps to reproduce the problem:
1. Open the PDF
2. View the page that has the problem. Page is blank.

### What is the expected behavior? (add screenshot)
PDF should be displayed as it displays in Chrome PDF viewer.
Left Chrome, Right Firefox.
![Comparison](https://i.imgur.com/VQbufhH.png)

### What went wrong? (add screenshot)
See screenshot above.

File attached (15MB) error:
```
PDF 312c804d1e0bfe15efe728a2e88faa42 [1.7 - / -] (PDF.js: 2.7.99) viewer.js:1351:13
An error occurred while rendering the page.
PDF.js v2.7.99 (build: 88f72d6b1)
Message: 
Stack: putBinaryImageData@resource://pdf.js/build/pdf.js:4876:13
CanvasGraphics_paintInlineImageXObject@resource://pdf.js/build/pdf.js:6341:27
CanvasGraphics_paintImageXObject@resource://pdf.js/build/pdf.js:6287:12
CanvasGraphics_executeOperatorList@resource://pdf.js/build/pdf.js:5112:22
_next@resource://pdf.js/build/pdf.js:3878:39
_scheduleNext/<@resource://pdf.js/build/pdf.js:3866:16
FrameRequestCallback*_scheduleNext@resource://pdf.js/build/pdf.js:3865:16
renderContinueCallback@resource://pdf.js/web/viewer.js:10862:9
paintOnCanvas/renderTask.onContinue@resource://pdf.js/web/viewer.js:11017:16
_continue@resource://pdf.js/build/pdf.js:3857:19
operatorListChanged@resource://pdf.js/build/pdf.js:3846:12
_renderPageChunk@resource://pdf.js/build/pdf.js:2608:34
pump/<@resource://pdf.js/build/pdf.js:2641:14
promise callback*pump@resource://pdf.js/build/pdf.js:2628:21
_pumpOperatorList@resource://pdf.js/build/pdf.js:2671:5
render@resource://pdf.js/build/pdf.js:2344:12
paintOnCanvas@resource://pdf.js/web/viewer.js:11011:37
draw@resource://pdf.js/web/viewer.js:10899:108
renderView@resource://pdf.js/web/viewer.js:4294:14
forceRendering/<@resource://pdf.js/web/viewer.js:10130:29
promise callback*forceRendering@resource://pdf.js/web/viewer.js:10129:43
renderHighestPriority@resource://pdf.js/web/viewer.js:4222:24
update@resource://pdf.js/web/viewer.js:9997:25
webViewerScaleChanging@resource://pdf.js/web/viewer.js:2357:34
dispatch/<@resource://pdf.js/web/viewer.js:3448:16
dispatch@resource://pdf.js/web/viewer.js:3435:29
_setScaleUpdatePages@resource://pdf.js/web/viewer.js:9756:19
_setScale@resource://pdf.js/web/viewer.js:9817:12
set currentScaleValue@resource://pdf.js/web/viewer.js:9424:10
scrollPageIntoView@resource://pdf.js/web/viewer.js:9922:9
setHash@resource://pdf.js/web/viewer.js:7466:24
setInitialView@resource://pdf.js/web/viewer.js:1532:27
load/</<@resource://pdf.js/web/viewer.js:1230:14
promise callback*load/<@resource://pdf.js/web/viewer.js:1183:119
promise callback*load@resource://pdf.js/web/viewer.js:1181:22
open/<@resource://pdf.js/web/viewer.js:936:12
promise callback*open@resource://pdf.js/web/viewer.js:935:32
onOpenWithData@resource://pdf.js/web/viewer.js:760:30
windowMessage@resource://pdf.js/web/viewer.js:12536:21
EventListener.handleEvent*initPassiveLoading@resource://pdf.js/web/viewer.js:12488:12
initPassiveLoading@resource://pdf.js/web/viewer.js:751:27
webViewerOpenFileViaURL@resource://pdf.js/web/viewer.js:1997:26
webViewerInitialized@resource://pdf.js/web/viewer.js:1985:28
promise callback*run@resource://pdf.js/web/viewer.js:660:29
webViewerLoad@resource://pdf.js/web/viewer.js:260:36
EventListener.handleEvent*@resource://pdf.js/web/viewer.js:266:12
__webpack_require__@resource://pdf.js/web/viewer.js:42:30
@resource://pdf.js/web/viewer.js:106:18
@resource://pdf.js/web/viewer.js:109:10
viewer.js:1099:15
renderView: "[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://pdf.js/build/pdf.js :: putBinaryImageData :: line 4876"  data: no]" viewer.js:4301:19
An error occurred while rendering the page.
PDF.js v2.7.99 (build: 88f72d6b1)
Message: 
Stack: putBinaryImageData@resource://pdf.js/build/pdf.js:4876:13
CanvasGraphics_paintInlineImageXObject@resource://pdf.js/build/pdf.js:6341:27
CanvasGraphics_paintImageXObject@resource://pdf.js/build/pdf.js:6287:12
CanvasGraphics_executeOperatorList@resource://pdf.js/build/pdf.js:5112:22
_next@resource://pdf.js/build/pdf.js:3878:39
_scheduleNext/<@resource://pdf.js/build/pdf.js:3866:16
FrameRequestCallback*_scheduleNext@resource://pdf.js/build/pdf.js:3865:16
renderContinueCallback@resource://pdf.js/web/viewer.js:10862:9
paintOnCanvas/renderTask.onContinue@resource://pdf.js/web/viewer.js:11017:16
_continue@resource://pdf.js/build/pdf.js:3857:19
operatorListChanged@resource://pdf.js/build/pdf.js:3846:12
_renderPageChunk@resource://pdf.js/build/pdf.js:2608:34
pump/<@resource://pdf.js/build/pdf.js:2641:14
promise callback*pump@resource://pdf.js/build/pdf.js:2628:21
_pumpOperatorList@resource://pdf.js/build/pdf.js:2671:5
render@resource://pdf.js/build/pdf.js:2344:12
paintOnCanvas@resource://pdf.js/web/viewer.js:11011:37
draw@resource://pdf.js/web/viewer.js:10899:108
renderView@resource://pdf.js/web/viewer.js:4294:14
forceRendering/<@resource://pdf.js/web/viewer.js:10130:29
promise callback*forceRendering@resource://pdf.js/web/viewer.js:10129:43
renderHighestPriority@resource://pdf.js/web/viewer.js:4222:24
update@resource://pdf.js/web/viewer.js:9997:25
webViewerScaleChanging@resource://pdf.js/web/viewer.js:2357:34
dispatch/<@resource://pdf.js/web/viewer.js:3448:16
dispatch@resource://pdf.js/web/viewer.js:3435:29
_setScaleUpdatePages@resource://pdf.js/web/viewer.js:9756:19
_setScale@resource://pdf.js/web/viewer.js:9817:12
set currentScaleValue@resource://pdf.js/web/viewer.js:9424:10
webViewerResize@resource://pdf.js/web/viewer.js:2182:5
dispatch/<@resource://pdf.js/web/viewer.js:3448:16
dispatch@resource://pdf.js/web/viewer.js:3435:29
bindWindowEvents/_boundEvents.windowResize@resource://pdf.js/web/viewer.js:1738:16
EventListener.handleEvent*bindWindowEvents@resource://pdf.js/web/viewer.js:1772:12
initialize@resource://pdf.js/web/viewer.js:445:10
async*run@resource://pdf.js/web/viewer.js:660:10
webViewerLoad@resource://pdf.js/web/viewer.js:260:36
EventListener.handleEvent*@resource://pdf.js/web/viewer.js:266:12
__webpack_require__@resource://pdf.js/web/viewer.js:42:30
@resource://pdf.js/web/viewer.js:106:18
@resource://pdf.js/web/viewer.js:109:10
viewer.js:1099:15
renderView: "[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://pdf.js/build/pdf.js :: putBinaryImageData :: line 4876"  data: no]" viewer.js:4301:19
```

Original file (17MB) error:
```
PDF 312c804d1e0bfe15efe728a2e88faa42 [1.7 - / -] (PDF.js: 2.7.99) viewer.js:1351:13
An error occurred while rendering the page.
PDF.js v2.7.99 (build: 88f72d6b1)
Message: 
Stack: putBinaryImageData@resource://pdf.js/build/pdf.js:4876:13
CanvasGraphics_paintInlineImageXObject@resource://pdf.js/build/pdf.js:6341:27
CanvasGraphics_paintImageXObject@resource://pdf.js/build/pdf.js:6287:12
CanvasGraphics_executeOperatorList@resource://pdf.js/build/pdf.js:5112:22
_next@resource://pdf.js/build/pdf.js:3878:39
_scheduleNext/<@resource://pdf.js/build/pdf.js:3866:16
FrameRequestCallback*_scheduleNext@resource://pdf.js/build/pdf.js:3865:16
renderContinueCallback@resource://pdf.js/web/viewer.js:10862:9
paintOnCanvas/renderTask.onContinue@resource://pdf.js/web/viewer.js:11017:16
_continue@resource://pdf.js/build/pdf.js:3857:19
operatorListChanged@resource://pdf.js/build/pdf.js:3846:12
_renderPageChunk@resource://pdf.js/build/pdf.js:2608:34
pump/<@resource://pdf.js/build/pdf.js:2641:14
promise callback*pump@resource://pdf.js/build/pdf.js:2628:21
_pumpOperatorList@resource://pdf.js/build/pdf.js:2671:5
render@resource://pdf.js/build/pdf.js:2344:12
paintOnCanvas@resource://pdf.js/web/viewer.js:11011:37
draw@resource://pdf.js/web/viewer.js:10899:108
renderView@resource://pdf.js/web/viewer.js:4294:14
forceRendering/<@resource://pdf.js/web/viewer.js:10130:29
promise callback*forceRendering@resource://pdf.js/web/viewer.js:10129:43
renderHighestPriority@resource://pdf.js/web/viewer.js:4222:24
update@resource://pdf.js/web/viewer.js:9997:25
webViewerScaleChanging@resource://pdf.js/web/viewer.js:2357:34
dispatch/<@resource://pdf.js/web/viewer.js:3448:16
dispatch@resource://pdf.js/web/viewer.js:3435:29
_setScaleUpdatePages@resource://pdf.js/web/viewer.js:9756:19
_setScale@resource://pdf.js/web/viewer.js:9817:12
set currentScaleValue@resource://pdf.js/web/viewer.js:9424:10
scrollPageIntoView@resource://pdf.js/web/viewer.js:9922:9
setHash@resource://pdf.js/web/viewer.js:7466:24
setInitialView@resource://pdf.js/web/viewer.js:1532:27
load/</<@resource://pdf.js/web/viewer.js:1230:14
promise callback*load/<@resource://pdf.js/web/viewer.js:1183:119
promise callback*load@resource://pdf.js/web/viewer.js:1181:22
open/<@resource://pdf.js/web/viewer.js:936:12
promise callback*open@resource://pdf.js/web/viewer.js:935:32
onOpenWithData@resource://pdf.js/web/viewer.js:760:30
windowMessage@resource://pdf.js/web/viewer.js:12536:21
EventListener.handleEvent*initPassiveLoading@resource://pdf.js/web/viewer.js:12488:12
initPassiveLoading@resource://pdf.js/web/viewer.js:751:27
webViewerOpenFileViaURL@resource://pdf.js/web/viewer.js:1997:26
webViewerInitialized@resource://pdf.js/web/viewer.js:1985:28
promise callback*run@resource://pdf.js/web/viewer.js:660:29
webViewerLoad@resource://pdf.js/web/viewer.js:260:36
EventListener.handleEvent*@resource://pdf.js/web/viewer.js:266:12
__webpack_require__@resource://pdf.js/web/viewer.js:42:30
@resource://pdf.js/web/viewer.js:106:18
@resource://pdf.js/web/viewer.js:109:10
viewer.js:1099:15
renderView: "[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://pdf.js/build/pdf.js :: putBinaryImageData :: line 4876"  data: no]" viewer.js:4301:19
An error occurred while rendering the page.
PDF.js v2.7.99 (build: 88f72d6b1)
Message: 
Stack: putBinaryImageData@resource://pdf.js/build/pdf.js:4876:13
CanvasGraphics_paintInlineImageXObject@resource://pdf.js/build/pdf.js:6341:27
CanvasGraphics_paintImageXObject@resource://pdf.js/build/pdf.js:6287:12
CanvasGraphics_executeOperatorList@resource://pdf.js/build/pdf.js:5112:22
_next@resource://pdf.js/build/pdf.js:3878:39
_scheduleNext/<@resource://pdf.js/build/pdf.js:3866:16
FrameRequestCallback*_scheduleNext@resource://pdf.js/build/pdf.js:3865:16
renderContinueCallback@resource://pdf.js/web/viewer.js:10862:9
paintOnCanvas/renderTask.onContinue@resource://pdf.js/web/viewer.js:11017:16
_continue@resource://pdf.js/build/pdf.js:3857:19
operatorListChanged@resource://pdf.js/build/pdf.js:3846:12
_renderPageChunk@resource://pdf.js/build/pdf.js:2608:34
pump/<@resource://pdf.js/build/pdf.js:2641:14
promise callback*pump@resource://pdf.js/build/pdf.js:2628:21
_pumpOperatorList@resource://pdf.js/build/pdf.js:2671:5
render@resource://pdf.js/build/pdf.js:2344:12
paintOnCanvas@resource://pdf.js/web/viewer.js:11011:37
draw@resource://pdf.js/web/viewer.js:10899:108
renderView@resource://pdf.js/web/viewer.js:4294:14
forceRendering/<@resource://pdf.js/web/viewer.js:10130:29
promise callback*forceRendering@resource://pdf.js/web/viewer.js:10129:43
renderHighestPriority@resource://pdf.js/web/viewer.js:4222:24
update@resource://pdf.js/web/viewer.js:9997:25
webViewerScaleChanging@resource://pdf.js/web/viewer.js:2357:34
dispatch/<@resource://pdf.js/web/viewer.js:3448:16
dispatch@resource://pdf.js/web/viewer.js:3435:29
_setScaleUpdatePages@resource://pdf.js/web/viewer.js:9756:19
_setScale@resource://pdf.js/web/viewer.js:9817:12
set currentScaleValue@resource://pdf.js/web/viewer.js:9424:10
webViewerResize@resource://pdf.js/web/viewer.js:2182:5
dispatch/<@resource://pdf.js/web/viewer.js:3448:16
dispatch@resource://pdf.js/web/viewer.js:3435:29
bindWindowEvents/_boundEvents.windowResize@resource://pdf.js/web/viewer.js:1738:16
EventListener.handleEvent*bindWindowEvents@resource://pdf.js/web/viewer.js:1772:12
initialize@resource://pdf.js/web/viewer.js:445:10
async*run@resource://pdf.js/web/viewer.js:660:10
webViewerLoad@resource://pdf.js/web/viewer.js:260:36
EventListener.handleEvent*@resource://pdf.js/web/viewer.js:266:12
__webpack_require__@resource://pdf.js/web/viewer.js:42:30
@resource://pdf.js/web/viewer.js:106:18
@resource://pdf.js/web/viewer.js:109:10
viewer.js:1099:15
renderView: "[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://pdf.js/build/pdf.js :: putBinaryImageData :: line 4876"  data: no]" viewer.js:4301:19
```

### Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
See above.

**Comment by Snuffleupagus** [comment] 2020-11-25 10:28
This is, for all intents and purposes, a duplicate of #6419.

**Closed** 2020-11-25 20:27 UTC
