### ISSUE TITLE
404 error. Has the URL changed?  //mozilla.github.io/pdf.js/build/pdf.worker.js

### ISSUE THREAD

**Issue by HTS-Craig** [mozilla/pdf.js#17092] opened 2023-10-07 22:06 UTC
Attach (recommended) or Link to PDF file here:

You example that is not working but was 2 weeks ago.
https://jsfiddle.net/pdfjs/wagvs9Lf/

//mozilla.github.io/pdf.js/build/pdf.worker.js (404 error)

Steps to reproduce the problem:
1. Run the example
2. https://jsfiddle.net/pdfjs/wagvs9Lf/

What went wrong? (add screenshot)
console log error: "<a class='gotoLine' href='#64:10'>64:10</a> Uncaught TypeError: Cannot read properties of undefined (reading 'GlobalWorkerOptions')"
<img width="1515" alt="Screenshot 2023-10-07 at 3 04 44 PM" src="https://github.com/mozilla/pdf.js/assets/53853889/21d33da1-6ff9-444a-8890-4e3944afb385">

**Comment by MangoFreak** [comment] 2023-10-08 08:41
Facing the very same issue.
I spotted that main file (src/pdf.js) had a push yesterday and the file extensions were changed to .mjs , however I don't know how to cope with such situation.
I guess new way of importing is required
![image](https://github.com/mozilla/pdf.js/assets/91157101/e587f802-d435-4d7c-9179-e98a606ec0e3)

**Comment by Snuffleupagus** [comment] 2023-10-08 11:19
This affects https://mozilla.github.io/pdf.js/examples/#interactive-examples but unfortunately I don't know how to update those.

**Comment by Snuffleupagus** [comment] 2023-10-08 11:24
This affects https://mozilla.github.io/pdf.js/examples/#interactive-examples but unfortunately I don't know how to update those examples (since I don't have access to the JSFiddle account).

**Comment by ArviinM** [comment] 2023-10-09 05:50
What was the reason for changing it into mjs extension?

**Comment by justlucdewit** [comment] 2023-10-09 09:32
we are having troubles due to this too, we have a pretty critical dependency on this library in older versions of our product. Is there a proposed solution or workaround? We would prefer if it got fixed without us having to change the URL.

**Comment by MangoFreak** [comment] 2023-10-09 10:07
Hey Luc, just wondering - why do you care about the script URL? It's available under the https://mozilla.github.io/pdf.js/build/pdf.worker.**m**js instead of https://mozilla.github.io/pdf.js/build/pdf.worker.js
For me the issue is initialization of library on the window object:
`var pdfjsLib = window['pdfjs-dist/build/pdf'];`

**Comment by justlucdewit** [comment] 2023-10-09 10:17
> [https://mozilla.github.io/pdf.js/build/](https://mozilla.github.io/pdf.js/build/pdf.worker.**m**js)

Thanks for your reply @MangoFreak. The reason we need this is because we have older versions of our application that are still in use, and retrieve the pdf.js library via that specific URL

so it would be great if that starts working again so we don't need to force our users to upgrade the version to the newest release where we change it.

The URL we retrieve the library from is `https://mozilla.github.io/pdf.js/build/pdf.js`

**Comment by YogeshTelawane** [comment] 2023-10-09 10:58
We're also facing the same issue as @justlucdewit . Getting 404 while accessing###  https://mozilla.github.io/pdf.js/build/pdf.js

**Comment by ArviinM** [comment] 2023-10-09 11:08
> > [https://mozilla.github.io/pdf.js/build/](https://mozilla.github.io/pdf.js/build/pdf.worker.**m**js)
> 
> Thanks for your reply @MangoFreak. The reason we need this is because we have older versions of our application that are still in use, and retrieve the pdf.js library via that specific URL
> 
> so it would be great if that starts working again so we don't need to force our users to upgrade the version to the newest release where we change it.
> 
> The URL we retrieve the library from is `https://mozilla.github.io/pdf.js/build/pdf.js`

Yes I agree with you. We are also having trouble previewing PDFs with our applications using that URL returning 404 and some of the library’s dependencies we use, is using that URL.

**Comment by MangoFreak** [comment] 2023-10-09 11:12
Could you guys please share how you initialized the whole library?
I'm using dist package, which became unavailable

**Comment by rjuevesano** [comment] 2023-10-09 11:40
any updates please?

**Comment by Snuffleupagus** [comment] 2023-10-09 12:03
> we have a pretty critical dependency on this library in older versions of our product.

Please note that files found under https://mozilla.github.io/pdf.js/build/ are *development snapshots*[1], which are potentially updated multiple times per day, that were *never intended* to be used in a production environment or as a CDN.

The fact that this has "worked" up until now can probably be attributed to nothing more than pure luck, and you really should be using *official releases* in production environments; please refer to:
 - https://mozilla.github.io/pdf.js/getting_started/#download
 - https://github.com/mozilla/pdf.js/releases
 - https://www.npmjs.com/package/pdfjs-dist

> Is there a proposed solution or workaround?

Yes, please use *official releases* instead; note the links just above.

> We would prefer if it got fixed without us having to change the URL.

That's really not possible, since after PR #17055 we're building JavaScript modules and the file-extensions were updated to reflect that. Hence you'll need to make additional changes to your code, in addition to just updating the URLs.

**Comment by laluheri** [comment] 2023-10-09 22:14
i have same issue. please help me.  Cannot read properties of undefined (reading 'GlobalWorkerOptions')"

**Comment by ArviinM** [comment] 2023-10-10 00:54
As a workaround I used this CDN.

`https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js`

I am still testing it since we use it only for previewing pdf files.

**Comment by amar-1999** [comment] 2023-10-10 06:00
We're also facing the same issue 
"Cannot read properties of undefined (reading 'GlobalWorkerOptions')"
 
and Getting 404 while accessing https://mozilla.github.io/pdf.js/build/pdf.js

Please update the thread if it is resolved.

**Comment by justlucdewit** [comment] 2023-10-10 07:04
@amar-1999 i had the same issue as you, apparently you should not be using that URL to get the library since
1) they took it offline
2) its a development build and thus not suitable for production

use a proper CDN instead, I chose for this (open this site and you will see what URLS you can use) -> https://cdnjs.com/libraries/pdf.js/2.6.347

**Comment by laluheri** [comment] 2023-10-10 07:59
> @amar-1999Saya memiliki masalah yang sama dengan Anda, tampaknya Anda tidak boleh menggunakan URL itu untuk mendapatkan perpustakaan sejak saat itu
> 
> 1. mereka mengambilnya secara offline
> 2. ini adalah bangunan pengembangan dan karenanya tidak cocok untuk produksi
> 
> gunakan CDN yang tepat sebagai gantinya, saya memilih untuk ini (buka situs ini dan Anda akan melihat URL apa yang dapat Anda gunakan) -> https://cdnjs.com/libraries/pdf.js/2.6.347


Terimakasih, kode saya berhasil dengan CDN <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js"></script>

**Comment by Snuffleupagus** [comment] 2023-10-10 08:07
The "Interactive examples" have now been updated, see https://mozilla.github.io/pdf.js/examples/#interactive-examples, to account for changes in the *upcoming* version `4` of the PDF.js library.

However, as was mentioned in https://github.com/mozilla/pdf.js/issues/17092#issuecomment-1752881489 you should always use [*the official releases*](https://mozilla.github.io/pdf.js/getting_started/#download) and ***NOT*** link directly to code found at e.g. https://mozilla.github.io/pdf.js/.

**Closed by Snuffleupagus** 2023-10-10 08:07 UTC
Labels: other
