### ISSUE TITLE
Annotation Popup Rendering {{date}} {{time}}

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#14567] opened 2022-02-15 01:06 UTC
Attach (recommended) or Link to PDF file here:
[1000.pdf](https://github.com/mozilla/pdf.js/files/8064949/1000.pdf)

Configuration:
- Web browser and its version: Chrome Version 98.0.4758.82
- Operating system and its version: windows 11 build 22000.493
- PDF.js version: '2.9.359'
- Is a browser extension: No

Steps to reproduce the problem:
1.Please see attached sample pdf
Open PDF, move mouse cursor to annotation, see the popup

2.

What is the expected behavior? (add screenshot)
date and time should be populated

What went wrong? (add screenshot)
![test](https://user-images.githubusercontent.com/3955470/153972834-b789c122-1d6c-463b-b72d-0b8f21743c6f.png)

Not a problem, but more of a question. I have exported an annotation to pdf. When pdf.js displays them it shows beside the username {{date}} {{time}}. viewer rendering since in acrobat or even chrome's pdf viewer, it does not show date and time info beside the username

in pdf.js line 18681 is where this is set modificationDate.textContent = "{{date}}, {{time}}";

and line 18683
```

modificationDate.dataset.l10nArgs = JSON.stringify({
          date: dateObject.toLocaleDateString(),
          time: dateObject.toLocaleTimeString()
        });
```

the date and time values actually have values but it does not seem to show in the popup, nor does it replace the {{date}} and {{time}} with such values. could this be a bug? dateObject.toLocaleDateString() has value. I figure this is the json that is used when the popup is shown and localization values are replaced

**Comment by Snuffleupagus** [comment] 2022-02-15 08:54
> date and time should be populated

That works when using e.g. https://github.com/mozilla/pdf.js#online-demo

> PDF.js version: '2.9.359'

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

Duplicate of #14169

**Closed by Snuffleupagus** 2022-02-15 08:54 UTC
