### ISSUE TITLE
Weird text rendering

### ISSUE THREAD

**Issue by monsterfish** [mozilla/pdf.js#15171] opened 2022-07-15 14:49 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 103.0.5060.114 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Pro 21H1
- PDF.js version: latest (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: no

Steps to reproduce the problem:
1. View attached PDF [Archivační a skartační řád-1-2.pdf](https://github.com/mozilla/pdf.js/files/9121776/Archivacni.a.skartacni.rad-1-2.pdf) in latest pdf.js viewer
2. Text is not rendered correctly

What is the expected behavior? See screenshot
![image](https://user-images.githubusercontent.com/3245988/179247617-20c6ac87-91b7-4548-9459-0cf7e29bad8e.png)

What went wrong? See screenshot
![image](https://user-images.githubusercontent.com/3245988/179247667-708cf383-1765-41bc-8ba8-cc456f2bafe0.png)

**Comment by Snuffleupagus** [comment] 2022-07-15 14:54
Duplicate of #14641

**Closed by Snuffleupagus** 2022-07-15 14:54 UTC
