### ISSUE TITLE
Overflow on PDFs with alternating page sizes

### ISSUE THREAD

**Issue by dwatsp** [mozilla/pdf.js#16203] opened 2023-03-24 07:03 UTC
Attach (recommended) or Link to PDF file here: 
[testFile.pdf](https://github.com/mozilla/pdf.js/files/11059159/testFile.pdf)

Configuration:
- Web browser and its version: Chrome: 111.0.5563.110
- Operating system and its version: Windows 10 Pro 22H2
- PDF.js version: 2.14.305 (via ng2-pdf-viewer 9.1.2)
- Is a browser extension: ?? no

Steps to reproduce the problem:
1.  Open dev tools, set width: 40% on <div id="viewerContainer">
2. Upload given example File to https://mozilla.github.io/pdf.js/web/viewer.html
3. Scroll down

What is the expected behavior? (add screenshot)
Last PDF page is rendered correctly, zoom of other pages are adjusted accordingly
![image](https://user-images.githubusercontent.com/128708919/227449824-a07b780d-4229-4dfe-9dce-494062f0f8f1.png)

What went wrong? (add screenshot)
Last PDF page overflows as it wasn't taken into account when determining size and scale of PDFs

![image](https://user-images.githubusercontent.com/128708919/227447323-e34592f1-c78e-44b5-98f0-f43cd99f9aae.png)

Issue originated from:
https://github.com/VadimDez/ng2-pdf-viewer/issues/988#issuecomment-1481536895

One Workaround (funnelled through the angular library) is to track canvas width on each page rendered event and adjust zoom factor if page breaks allocated width, but this leads to a visual jump every time the zoom factor gets updated.
Alternatively you can obscure the view, scrollTop() every page, recalculate the zoom, apply, scroll up again and lift the curtain (but this takes a ridiculous amount of time)

What would help here (if pdf.js can't account for 'surprises' later down the pages) would be an array of page dimensions on load completion. We already know how many pages there aught to be. Maybe there is a way to find out their sizes relative to each other in advance?

**Comment by Snuffleupagus** [comment] 2023-03-24 08:19
Duplicate of #5628

**Closed by Snuffleupagus** 2023-03-24 08:19 UTC
