### ISSUE TITLE
 can i set font color and backgroud-color?

### ISSUE THREAD

**Issue by wjfc** [mozilla/pdf.js#14774] opened 2022-04-13 02:37 UTC
I want to set pdf font color and bg color. Is there an API that can do this.
Best regards

**Comment by wjfc** [comment] 2022-04-13 03:04
I have the way to change background
```js
 var renderContext = {
            canvasContext: context,
            // background: 'rgba(0,0,0)',
            transform: transform,
            viewport: viewport,
          };
          page.render(renderContext);
```

**Comment by Snuffleupagus** [comment] 2022-04-13 09:49
Duplicate of #2071

---

Which is a best guess, given that this issue is missing most (if not all) details required to be actionable. When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Closed by Snuffleupagus** 2022-04-13 09:49 UTC

**Comment by shivaprsd** [comment] 2022-04-14 17:25
@wjfc I wrote a library that adds this functionality to PDF.js. Visit: https://github.com/shivaprsd/doq.
