### ISSUE TITLE
[Feature] Tool to rotate single pages

### ISSUE THREAD

**Issue by JackAndersen** [mozilla/pdf.js#15678] opened 2022-11-10 06:42 UTC
We have a national government PDF archive that was previously physical documents in big file cabinets. However it was decided some years ago, that they should all be digitized. Unfortunately the government choose a cheaper scan mehtod of just taking the documents from the file cabinet, putting them in a pile and throw then into the scanner :). However that leaves me with a need for a PDF viewer that can rotate single pages.
We use PDF.js in our web app to show a list of these documents, and allow our users to view them. But it would be awesome with a tool that can rotate single pages within a pdf document.
Furthermore our documents often contain varying page sizes, which makes them even more unhandy :)

scanned, Attach (recommended) or Link to PDF file here:
[example_single_pages_rotated.pdf](https://github.com/mozilla/pdf.js/files/9978006/example_single_pages_rotated.pdf)

**Comment by Snuffleupagus** [comment] 2022-11-10 06:53
Duplicate of #7892

---

This would add too much code/complexity for an edge-case feature, and would require a bunch more UI elements as well. However, you can obviously implement this yourself; please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Closed by Snuffleupagus** 2022-11-10 06:53 UTC

**Comment by namannjain** [comment] 2024-04-30 05:02
> We have a national government PDF archive that was previously physical documents in big file cabinets. However it was decided some years ago, that they should all be digitized. Unfortunately the government choose a cheaper scan mehtod of just taking the documents from the file cabinet, putting them in a pile and throw then into the scanner :). However that leaves me with a need for a PDF viewer that can rotate single pages. We use PDF.js in our web app to show a list of these documents, and allow our users to view them. But it would be awesome with a tool that can rotate single pages within a pdf document. Furthermore our documents often contain varying page sizes, which makes them even more unhandy :)
> 
> scanned, Attach (recommended) or Link to PDF file here: [example_single_pages_rotated.pdf](https://github.com/mozilla/pdf.js/files/9978006/example_single_pages_rotated.pdf)

@JackAndersen I have a similar usecase. Were you able to solve this using pdf.js libary?
