### ISSUE TITLE
file=http:// works, not file=https://

### ISSUE THREAD

**Issue by furiop** [mozilla/pdf.js#13422] opened 2021-05-22 16:29 UTC
In Chrome & Apache web server and secure layer https in Debian GNU/Linux 10 (buster)

OK with
http://www.quellidel68.it/pdfview/web/viewer.html?file=http://www.quellidel68.it/doc/1968/151168studentigreci.pdf
Note: file=http://

KO with
http://www.quellidel68.it/pdfview/web/viewer.html?file=https://www.quellidel68.it/doc/1968/151168studentigreci.pdf
Note: file=https://

https://www.quellidel68.it/doc/1968/151168studentigreci.pdf has not problems, and is readable in Chrome

pdfjs-2.7.570-dist
Chrome  90.0.4430.212

Furio

**Comment by timvandermeij** [comment] 2021-05-22 16:41
The error message is pretty self-explanatory: "file origin does not match viewer's". In the second link the file origin is HTTPS whereas the viewer origin is HTTP, so that's a mismatch. The second link does work it the viewer also uses HTTPS: https://www.quellidel68.it/pdfview/web/viewer.html?file=https://www.quellidel68.it/doc/1968/151168studentigreci.pdf

Closing since this is not a bug.

**Closed by timvandermeij** 2021-05-22 16:41 UTC
