### ISSUE TITLE
Text Layer boxes are too long

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#7239] opened 2016-04-22 15:24 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Version 50.0.2661.75 beta (64-bit)
- Operating system and its version: Mac OS X El Capitan
- PDF.js version: online viewer as of April 22, 2016
- Is an extension:

Steps to reproduce the problem:
1. select text from second column of first page
2. notice how the boxes extend beyond the last character of each line?
[wiese.pdf](https://github.com/mozilla/pdf.js/files/232091/wiese.pdf)

What is the expected behavior? (add screenshot)
The text selection should visually end at the last character of the text line

What went wrong? (add screenshot)
The selection shows beyong the last character of each text line
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by ldenoue** [comment] 2016-04-24 18:51
Setting var MULTI_SPACE_FACTOR_MAX to 0 (instead of 4) in https://github.com/mozilla/pdf.js/blob/070f2d32ada10bd877bdfd6cae2a2179a20a9930/src/core/evaluator.js#L1142 solved the issue for this PDF.

Who could pitch in about the usefulness of this constant?
How can I find which PDFs to test with it?

Laurent

**Comment by yurydelendik** [comment] 2016-04-25 02:55
> Who could pitch in about the usefulness of this constant?

As part of the text restoration heuristic, MULTI_SPACE_FACTOR indicates how much spaces will be replaced instead of long horizontal movement in the text operators into the spaces. MULTI_SPACE_FACTOR_MAX sets limit how much spaces can be replaced, otherwise text will break into separate runs. 

Looks like it's trying to replace single space by two, so looks like space symbol is set too short for the font in the PDF and it's not printed, so PDF.js has to guess where to insert it.

> How can I find which PDFs to test with it?

AFIAK most of PDF will show regression but changing this to 0 -- you just disable heiristic. Try reftest marked with "text". See also old issues labels as "4-text-selection".

**Comment by timvandermeij** [comment] 2021-04-30 18:05
Fixed by #13257 and possibly other patches.

**Closed by timvandermeij** 2021-04-30 18:05 UTC
Labels: 4-text-selection
