### ISSUE TITLE
A text in the text field is not fully displayed in the view mode

### ISSUE THREAD

**Issue by ilnur-slv** [mozilla/pdf.js#16358] opened 2023-04-27 09:56 UTC
Attach (recommended) or Link to PDF file here:
[dod_character.pdf](https://github.com/mozilla/pdf.js/files/11341911/dod_character.pdf)

**Configuration:**
- Web browser and its version: Chrome 112.0.5615.138
- Operating system and its version: Windows 10
- PDF.js version: 3.5.141
- Is a browser extension: no

**Steps to reproduce the problem:**
1. Open the attached pdf file (AnnotationMode = ENABLE_FORMS (default))
2. Fill in the text field with some long text
3. Save the pdf
4. Open the saved pdf file (AnnotationMode = ENABLE)

**What is the expected behavior? (add screenshot)**
It's possible to scroll the input field (or some other solution to view the entire text)

![Animation3](https://user-images.githubusercontent.com/1205974/234828077-b088768e-d566-4ab9-bc51-55897277c25b.gif)

**What went wrong? (add screenshot)**
A text in the text field is not fully displayed and you can't scroll.

![image](https://user-images.githubusercontent.com/1205974/234825391-81d64dfa-8d39-42a6-afff-52155615bab8.png)

**Comment by Snuffleupagus** [comment] 2023-04-27 10:07
Duplicate of #15605

**Closed by Snuffleupagus** 2023-04-27 10:07 UTC
