### ISSUE TITLE
Use accessibility tags embedded in PDF

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#1671] opened 2012-05-08 19:53 UTC
Per conversation with Marco Zehe:

If a PDF file has accessibility tags embedded, such as for headings, tables, form fields, graphics with alternative text etc., try to use them in the text layer

**Comment by trjohnst** [comment] 2018-03-15 22:44
@RyanEdwardHall if the elements contained within the text layer have appropriate resetting applied to them via CSS, would that alleviate concerns around the positioning of the DOM elements?

**Comment by somascope** [comment] 2019-11-29 23:40
I too would like such a feature for document structure tagging for accessible PDFs. If it's of helpful reference, these is [Adobe's Acrobat page for doing this in software](https://helpx.adobe.com/acrobat/using/editing-document-structure-content-tags.html), which possible provides some insight.

**Comment by cuhaller** [comment] 2020-01-27 23:41
I've also been looking for a solution to this for a while now and came across this article, https://engineering.linkedin.com/blog/2019/04/under-the-hood--learning-with-documents, outlining how LinkedIn solved this issue using PDF.js for the PDFs uploaded to LinkedIn Learning. I contacted the authors to learn more and they initially seemed open to contribute their edits back, but I haven't heard back after following up and offering to pay for their efforts. Guess they got busy with other projects.

**Comment by trjohnst** [comment] 2020-01-28 00:36
@cuhaller that was the very project I was working on that needed accessible tagging. The PDF format when created correctly is surprisingly close to basic HTML elements that aid page readers. I've since left so, unfortunately, do not have access to any of the code. I will check in with the dev that worked on that component.

**Comment by cuhaller** [comment] 2020-02-03 22:51
@trjohnst thanks, much appreciated, let us know what you find out.

**Comment by jcsteh** [comment] 2020-04-16 23:43
This issue and #6269 are duplicates. I'd suggest this should be closed as a duplicate of #6269, as the latter has more technical details.

**Closed** 2020-04-17 21:04 UTC
Labels: 1-core, 2-feature
