### ISSUE TITLE
"Segoe UI" TTF font render wrong

### ISSUE THREAD

**Issue by fletchsod-developer** [mozilla/pdf.js#13312] opened 2021-04-28 16:28 UTC
[BuyersGuide_4_26_2021 12_00_31 PM.pdf](https://github.com/mozilla/pdf.js/files/6393348/BuyersGuide_4_26_2021.12_00_31.PM.pdf)
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36

- Operating system and its version:

    Windows 10
    
- PDF.js version:

   Unknown but latest version in Google Chrome
   
- Is a browser extension:

   Yes, in latest version Google Chrome

Steps to reproduce the problem:
1.PDF I'm attaching, open it in this JS PDF viewer (render wrong)
2.PDF I'm attaching, open it in Adobe Acrobat Reader DC (render correctly)

What is the expected behavior? (add screenshot)

    "Segoe UI" font should render correctly in this JS PDF Viewer

What went wrong? (add screenshot)

    "Segoe UI" font is render wrong in this JS PDF Viewer

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-04-28 17:10
Your PDF document uses non-standard fonts, but doesn't embed any of them, which means that the PDF document *itself* is violating the PDF specification and it simply cannot be guaranteed that the document will render as intended in all viewers.

**Comment by fletchsod-developer** [comment] 2021-04-28 17:18
Segoe UI is a TTF file that come with Windows 10, in the "C:\Windows\Fonts" folder.  The "Quick PDF" software doesnt have the embedding API object

**Comment by Snuffleupagus** [comment] 2021-04-28 17:28
> Segoe UI is a TTF file that come with Windows 10,

That means that anything which isn't Windows will be, more or less, guaranteed to not render the PDF document correctly.
Note that the whole point of the "Portable Document Format" is that files should be *portable*, and by not embedding fonts you're basically guaranteeing that problems can/will occur.

>  The "Quick PDF" software doesnt have the embedding API object

If a particular PDF generator cannot embed fonts correctly, that's a bug in that software.

**Comment by timvandermeij** [comment] 2021-04-30 17:38
Closing since this is a duplicate of some of the issues in https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-non-standard-fonts.

**Closed by timvandermeij** 2021-04-30 17:38 UTC
