### ISSUE TITLE
Text blur when zoom in

### ISSUE THREAD

**Issue by wumingwuan** [mozilla/pdf.js#6794] opened 2015-12-23 07:31 UTC
We have a lot of pdf files that need to zoom in.
but when we zoom in, the text didn't clear enough to for users to see.

Normal Adobe Reader:
![normalpdf](https://cloud.githubusercontent.com/assets/11922624/11972601/8b2c8b3e-a989-11e5-8e1a-f31428902c88.png)

Pdf.js :
![blur](https://cloud.githubusercontent.com/assets/11922624/11972600/8b27452a-a989-11e5-89ff-eec15750eb1a.png)

Orignial File:
[test.pdf](https://github.com/mozilla/pdf.js/files/70521/test.pdf)

Is there any way to improve this situation ?

**Comment by cHewN** [comment] 2019-02-13 08:57
Is there any update on this? We have the same issue but with zoom level 100% where the text becomes blurry in pdfjs, but not in other pdf viewers. Actually it's more than just the text, lines become blurry as well.

These are documents that need to be measured, so it's quite hard when you can't see the end of a line because the object next to it is so blurry.

I can't share the source because of gdpr but I attached 2 images to show the difference. The very blurred one is pdfjs.

![100_percent_otherviewers](https://user-images.githubusercontent.com/36958022/52699267-aa847f80-2f75-11e9-962f-d12490e474fd.png)
![100_percent_pdfjs](https://user-images.githubusercontent.com/36958022/52699268-aa847f80-2f75-11e9-8814-b70a9cb57814.png)

**Comment by Snuffleupagus** [comment] 2021-05-13 14:09
This is, for all intents and purposes, another duplicate of issue #6419.

**Closed** 2021-05-13 16:56 UTC
Labels: 1-core, 2-image-quality
