### ISSUE TITLE
IE 11 cannot rendering page have annotations

### ISSUE THREAD

**Issue by quanth29** [mozilla/pdf.js#5845] opened 2015-03-17 09:10 UTC
I'm using latest stable release of PDF.JS (1.0.1040), and PDF.JS cannot render page have annotations in IE 11 (Windows 8.1) but it wokrs in Chrome and Firefox. It rendered content and disappear immediately. I have only background page.
Here is my pdf https://copy.com/ttxyWC1szNr6x33d

**Comment by Snuffleupagus** [comment] 2015-03-17 09:22
Works for me, using: Windows 7 (64-bit), Firefox Nightly 39 (buildID: 20150316030202) with HWA on, and PDF.js 1.0.1209.

However I can reproduce in IE11, this is the relevant portion of the console output:
```
PDF b1c2a51b8fdd12eec41e27884370d115 [1.5 iText 2.1.7 by 1T3XT / pdfsam-console (Ver. 2.4.3e)] (PDF.js: 1.0.1209)
Warning: globalCompositeOperation "multiply" is not supported
Warning: globalCompositeOperation "multiply" is not supported
[...]
```
The messages indicate that this issue is related to blend modes, rather than annotations.

**Comment by timvandermeij** [comment] 2019-11-09 13:28
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.

**Closed by timvandermeij** 2019-11-09 13:28 UTC
Labels: 1-core, 4-ie11-specific
