### ISSUE TITLE
PDF viewer (still) adding margins to print preview and printout.

### ISSUE THREAD

**Issue by TomatoJoe** [mozilla/pdf.js#11226] opened 2019-10-10 14:50 UTC
![58606988-dd604280-82dc-11e9-8639-854f68681f3f](https://user-images.githubusercontent.com/4572738/66579922-1c749d80-ebc5-11e9-8685-2450da1b5d12.jpg)
![58606990-e05b3300-82dc-11e9-8159-60a29877a129](https://user-images.githubusercontent.com/4572738/66579960-27c7c900-ebc5-11e9-9228-03c14e9b5f23.jpg)

Since the previous report of this issue was closed, marked as fixed,  but it clearly is not fixed,  I post this report. This issue is still causing us grief.

We print labels , 4 per sheet this adding anything to the margins of the final print is a critical fault/bug.
Now forced to go with the latest version of FF due to continuous addon issues.
Here's the problem:
FF v52.2.1esr Win 7 : Added ~0.5" to Left, Right, Top and Bottom margins.
FF v67.0 (latest) Win 7 : Added ~0.5" to Top and Bottom margins
FF v67.0 MX Linux : No added margins, however cannot use due to another bug with the Linux version of PDF.js .
I have tried/checked:

    Set in about:config , all margins for the printer to 0 (print.printer_4100DN_USB.print_margin_top etc)
    Ensure there are no additional Gutter or Margins added by the Printer properties.
    Ensure the Application adds no add'l margin
    Symptoms:
    Preview in Firefox - No margins added and looks as it should.
    Paper printout and Print Preview - Added extra Margin.

We are forced to use the FF Preview in FF because there is no Adobe Acrobat Reader plugin support since v57. With the old v52.2.1 FF with Acrobat Plugin everything works perfectly.

**Comment by timvandermeij** [comment] 2019-10-10 21:08
Could you provide a sample PDF file for which this happens?

**Comment by TomatoJoe** [comment] 2019-10-11 01:34
Well,  its not a stand-alone file as such,  its from a Print-Labels function of Australia Post eParcel portal.
I'll try to grab the page code.

**Comment by fdesforges** [comment] 2019-10-22 15:02
Same problems here in Firefox 69/ win10 (using pdf.js as pdf reader).

Sample where I reproduce : 
https://www.maths.ed.ac.uk/~dmarsh/files/printer-testcard-colour.pdf

when opening it firefox it's ok, when i print it or print to pdf it i get an extra margin and truncated document like here : 
![pdfprint](https://user-images.githubusercontent.com/1534307/67298971-5a8a8f00-f4ec-11e9-9538-e68b71a4ab49.PNG)

It's also reproductable with the same document using the firefox print preview : 
![image](https://user-images.githubusercontent.com/1534307/67299598-2d8aac00-f4ed-11e9-8c86-de4b21776043.png)

it can also be reproduced with this document :
http://www.africau.edu/images/default/sample.pdf

First note that i don't reproduce with this document : 
https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf

Second problem (I don't know if it can be related) : 
Every pdf sent to print to my differents office printers (differents models) ask for a manual papers addition instead of using the default one. It don't have any issue using chrome or acrobat reader.

**Comment by timvandermeij** [comment] 2021-04-25 16:07
Closing since we recently merged quite a few fixes for page positioning when printing. If this is still an issue, it's most likely related to the printer settings which we cannot control from JavaScript, thus it's not something that can be fixed here.

**Closed by timvandermeij** 2021-04-25 16:07 UTC
Labels: 4-printing
