### ISSUE TITLE
Displaced shading pattern

### ISSUE THREAD

**Issue by luis4a0** [mozilla/pdf.js#9243] opened 2017-12-05 19:35 UTC
Attach (recommended) or Link to PDF file here:
[shading_pattern.pdf](https://github.com/mozilla/pdf.js/files/1532598/shading_pattern.pdf)

Configuration:
- Web browser and its version: Firefox 57.0
- Operating system and its version: Debian GNU/Linux 9 64-bit
- PDF.js version: tried with Firefox's 1.9.583 and with online viewer 2.0.185
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached file with the online viewer https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/11061462/33626267-d9a57dee-d9d8-11e7-8712-cfa17c038259.png)
(Image captured from Adobe Reader CS.) The shading needs to be inside the letters.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/11061462/33626285-eaabd462-d9d8-11e7-94e2-96480b57750d.png)
The shading seems to be displaced and upside-down, for it does not cover all the characters of the word.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-12-05 19:44
Closing as duplicate of issue #8111; see also https://github.com/mozilla/pdf.js/blob/f299473697dab586946bbbe4e1aa288aaffc0ec6/src/display/canvas.js#L1463-L1464.

**Closed by Snuffleupagus** 2017-12-05 19:44 UTC
