### ISSUE TITLE
Some ultra large and ultra high PDFs cannot obtain clear images.

### ISSUE THREAD

**Issue by DiverYang** [mozilla/pdf.js#16907] opened 2023-09-06 02:19 UTC
![image](https://github.com/mozilla/pdf.js/assets/30024556/154cb4d4-d610-4437-bb74-309cb9255710)
![image](https://github.com/mozilla/pdf.js/assets/30024556/d05286ef-3353-4725-9370-76b51d01c19f)

Configuration:
- Web browser and its version: firefox 117 and chrome 116.0.5845.141
- Operating system and its version: window10 ,window11
- PDF.js version: pdfjs-3.7.107-dist
- Is a browser extension:

Steps to reproduce the problem:
1.  open pdf
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-09-06 07:15
> PDF.js version: pdfjs-3.7.107-dist

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:
>     1. open pdf

Unfortunately that's *impossible* since you didn't attach the PDF document to this issue, which is the very first thing that the ISSUE_TEMPLATE asks for; without that information no issue is actionable.

This might be a duplicate of e.g. issue #6419, but it's unfortunately impossible to tell given the lack of information.

**Closed by Snuffleupagus** 2023-09-06 07:15 UTC
Labels: information-requested

**Comment by DiverYang** [comment] 2023-09-07 03:14
I will try to create a PDF file that I can upload. This is a combination of three A0 drawings into one page. I tried integrating pdfjs-3.10.111-dist with firefox117, and still have this situation with pdf.js. The integration in Chrome and Edge is normal. Is it due to the height limitation of PDFJS that the image cannot be drawn at the normal scale.
