### ISSUE TITLE
Text layer is missing characters in place of ligatures

### ISSUE THREAD

**Issue by mrtcode** [mozilla/pdf.js#17410] opened 2023-12-11 10:56 UTC
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/13634345/test.pdf)

Configuration:
- Web browser and its version: All
- Operating system and its version: All
- PDF.js version: 4.0.341
- Is a browser extension: no

What went wrong? (add screenshot)
The 'fi' characters are skipped when copying text.
![Screenshot 2023-12-11 at 12 50 03](https://github.com/mozilla/pdf.js/assets/6362989/8391de81-5af3-4e4b-8b63-cd830d6132c7)

Acrobat Reader correctly recognizes and copies ligatures from this file.

**Comment by Snuffleupagus** [comment] 2023-12-11 11:00
Duplicate of #12237

**Closed by Snuffleupagus** 2023-12-11 11:00 UTC
