### ISSUE TITLE
Blank page rendering when using graphics operator "n"

### ISSUE THREAD

**Issue by skuhnert** [mozilla/pdf.js#14026] opened 2021-09-15 11:43 UTC
Attach (recommended) or Link to PDF file here:
[image2021-09-14-120957.pdf](https://github.com/mozilla/pdf.js/files/7169623/image2021-09-14-120957.pdf)

Configuration:
- Web browser and its version:
for example Firefox 92.0 (64-Bit) (makes no difference)
- Operating system and its version:
Windows 10
- PDF.js version:
2.11.91 (also with most recent version)
- Is a browser extension:
No

Steps to reproduce the problem:
1. Open the attached PDF in PDF.js  
2. Control the PDF with another PDF-Viewer

What is the expected behavior?
When a graphics operator "n" occoured in an graphics stream, no operation should be applied

What went wrong? (add screenshot)
The first page contains the following stream:
`q
Q
q
W
n
n
n
n
n
n
q
595
0
0
842
0
0 cm
/I7 Do
Q
Q`

In this example are multiple "n" operators, which leads to an blank page rendering. It seems, that the endPath-function in pdf.js calls an "this.consumePath()" which manipulates the canvas-context in an unexpected way:
https://github.com/mozilla/pdf.js/blob/7fb653b19a855adfb7fcc658fa4d70c89f0cbdab/src/display/canvas.js#L1676

After temporary disabling this function call, the pdf renders as expected.

**Comment by janpe2** [comment] 2021-09-16 04:55
Duplicate of #12306

**Closed** 2021-09-16 06:40 UTC
Labels: 1-core
