### ISSUE TITLE
Scaling issues in non-text PDFs

### ISSUE THREAD

**Issue by unclecomrade** [mozilla/pdf.js#12806] opened 2021-01-02 20:59 UTC
Attach (recommended) or Link to PDF file here: [attached-pdf.pdf](https://github.com/mozilla/pdf.js/files/5760845/attached-pdf.pdf)

Configuration:
- Web browser and its version: Mozilla Firefox 84.0.1 (64 bit), Google Chrome 87.0.4280.88 (64 bit), Chromium 87.0.4280.88 (64 bit, snap version)
- Operating system and its version: Microsoft Windows 10 Version 20H2 (Build 19042.685), Manjaro Linux XFCE Edition (Version 20.2 "Nibia")
- PDF.js version: 2.5.207
- Is a browser extension: no

Steps to reproduce the problem:
1. Open PDF either in a web version or, in case of Firefox, natively
2. Try zooming in beyond ~150%

What is the expected behavior?
![chrome_CzgVnKheKe](https://user-images.githubusercontent.com/56726344/103466370-a2927c00-4d55-11eb-853c-22974963e21b.png)

What went wrong?
![firefox_QM6gEyLgyQ](https://user-images.githubusercontent.com/56726344/103466440-4f6cf900-4d56-11eb-83d1-7e0c7f7fa719.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): -

**Comment by Snuffleupagus** [comment] 2021-01-02 21:02
This is, for all intents and purposes, a duplicate of #6419.

**Closed** 2021-01-03 11:37 UTC
