### ISSUE TITLE
build without the generic viewer

### ISSUE THREAD

**Issue by clarkk** [mozilla/pdf.js#8292] opened 2017-04-15 10:09 UTC
I just need to use the API (I want to create a custom viewer)

How to...
- build WITHOUT the generic viewer
- build with all dependencies
- compatible with all browsers
- build a worker file together with one pdf.js file where all source files are merged together

```
# npm install -g gulp-cli
# cd /path/to/pdfjs
# npm install
# gulp bundle

/var/www/pdfjs/node_modules/webpack/lib/webpack.js:7
const Compiler = require("./Compiler");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/pdfjs/gulpfile.js:36:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by timvandermeij** [comment] 2017-04-15 18:19
If you just want to use the API, use https://github.com/mozilla/pdfjs-dist. It does not include the generic viewer and should therefore be what you are looking for.

**Comment by clarkk** [comment] 2017-04-16 17:57
Shouldn't it work if I copy `build` from `pdfjs-dist` in the root of this repository?

**Comment by yurydelendik** [comment] 2017-04-16 18:13
> Shouldn't it work if I copy build from pdfjs-dist in the root of this repository?

if you install pdfjs-dist as a package, `require('pdfjs-dist/build/pdf');` shall give you what you need

**Comment by clarkk** [comment] 2017-04-16 18:23
I dont get it.. I just need the mentioned `pdf.js`

Here I use `pdf.js` from `pdfjs-dist/build`
```
<!doctype html>
<html>

<head>
	<script src="pdf.js"></script>
  <script src="hello.js"></script>
</head>

<body>
  <canvas id="the-canvas" style="border:1px solid black;"/>
</body>

</html>
```

Here I use `pdf.worker.js` from `pdfjs-dist/build`
```
'use strict';

// The workerSrc property shall be specified.
//
PDFJS.workerSrc = 'pdf.worker.js';

// Some PDFs need external cmaps.
//
// PDFJS.cMapUrl = '../../build/dist/cmaps/';
// PDFJS.cMapPacked = true;

var DEFAULT_URL = 'helloworld.pdf';
var PAGE_TO_VIEW = 1;
var SCALE = 1.0;

var container = document.getElementById('the-canvas');

// Loading document.
PDFJS.getDocument(DEFAULT_URL).then(function (pdfDocument) {
  // Document loaded, retrieving the page.
  return pdfDocument.getPage(PAGE_TO_VIEW).then(function (pdfPage) {
    // Creating the page view with default parameters.
    var pdfPageView = new PDFJS.PDFPageView({
      container: container,
      id: PAGE_TO_VIEW,
      scale: SCALE,
      defaultViewport: pdfPage.getViewport(SCALE),
      // We can enable text/annotations layers, if needed
      textLayerFactory: new PDFJS.DefaultTextLayerFactory(),
      annotationLayerFactory: new PDFJS.DefaultAnnotationLayerFactory()
    });
    // Associates the actual page with the view, and drawing it
    pdfPageView.setPdfPage(pdfPage);
    return pdfPageView.draw();
  });
});
```

**Comment by timvandermeij** [comment] 2017-04-16 18:51
It looks like you're using the `simpleviewer` components example. In that case, you also need https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.html#L41 for viewer features like `DefaultTextLayerFactory`.

I would advice to first try to get the provided examples (in the `examples` directory of this repository) running before attempting to adjust them. It will make modifications easier if you start from a working version first.

**Comment by clarkk** [comment] 2017-04-16 21:20
Actually I have used an about 1-2 years old version of PDF.js in a previuos project.. 

At that time it was really easy to get it running.. I cant say that now.. Have already tried the simpleviewer version but cant make anything work..

But will give it one more try

**Comment by clarkk** [comment] 2017-04-16 21:30
What is `pdf_viewer.js` for?

**Comment by timvandermeij** [comment] 2017-04-16 21:43
I tried this in an empty folder:

```
git clone https://github.com/mozilla/pdf.js
cd pdf.js
npm install
gulp dist
gulp server
```

Then I visited http://localhost:8888/examples/components/simpleviewer.html where I see this in the console:

```
TypeError: _ui_utils.mozL10n is undefined
TypeError: _dom_events.domEvents is undefined
```

So it's not just you; something regressed in the recent ES6 conversion. Reopening and labeling as regression.

**Comment by clarkk** [comment] 2017-04-16 21:48
But a very striped version (without the generic viewer) only with `pdf.js`, `pdf_worker.js` and the textlayer thing would really help..

And without all these new "helper" files around it..

**Comment by timvandermeij** [comment] 2017-04-17 12:59
The regressions have been fixed and the examples are working again. The steps outlined in https://github.com/mozilla/pdf.js/issues/8292#issuecomment-294376046 should make all examples work for you as well. I think most problems arose because we have been refactoring the codebase to use ES6 syntax and you uncovered something we forgot about during the refactoring.

The `pageviewer`/`simpleviewer` examples are about as easy as it gets while still having the functionality you ask for, so I don't think there is more we can do here. Of course, if you feel improvements can be made, feel free to submit a pull request for review. Closing for now as all actionable issues seem to have been resolved.

**Closed by timvandermeij** 2017-04-17 12:59 UTC
Labels: 1-other, 3-regression
