### ISSUE TITLE
Printing incorrectly on label printer with small page size

### ISSUE THREAD

**Issue by stephenross** [mozilla/pdf.js#8166] opened 2017-03-16 19:15 UTC
I am using Firefox 52 x32 on Windows 10 x64 to try and print a small PDF on a Zebra LP 2844 label printer. The PDF is generating to be a 3"x2" PDF, which is the printable size on the label printer. When printing the PDF from Firefox inside of PDF.js, the content appears shifted to the left and the label printer spits out enough labels to make the height of a standard 8.5"x11" sheet of paper (plus a little extra to finish spitting out the last label). When I print the PDF from the builtin viewers in Chrome or Edge, the label comes out fine.

The source PDF is [here](https://github.com/mozilla/pdf.js/files/848760/Prescription-P17PHE3014383_300x200.pdf) and I have uploaded a picture of the labels with a small pencil labeling of which one was printed from which application [here](https://imgur.com/RHi9YAE). All data is randomly generated test data, so don't worry about the contents.

**Comment by retrazil** [comment] 2019-06-22 10:41
PDF in the first link looks fine on Firefox 67.0.1 (64-bit), PDF.js (2.2.71). Second link is broken.

**Comment by timvandermeij** [comment] 2019-06-22 13:37
I fixed the second link (it was missing the `https://` prefix).

**Comment by maverick74** [comment] 2021-12-09 15:41
@stephenross Source PDF link is broken/unavailable.

Is this still broken?

**Comment by maverick74** [comment] 2021-12-09 16:03
@stephenross Thanks for your update. :)

I'll leave the "Closing" decision to Mozilla collaborators as this might still be valid and/or related to bug #13264 and worthy of keeping open

**Comment by Snuffleupagus** [comment] 2021-12-09 16:12
Given the above, let's just mark this as a duplicate of #13264

**Closed by Snuffleupagus** 2021-12-09 16:12 UTC
Labels: 4-printing
