### ISSUE TITLE
Call to getMetadata returns only parts of metadata when performed from a Chrome extension

### ISSUE THREAD

**Issue by nkartashov** [mozilla/pdf.js#8180] opened 2017-03-21 21:14 UTC
Hi, I'm trying to use pdf.js for extracting metadata (author, title, etc) from a PDF in a Chrome extension. When pdf.js file is included with an script tag from a separate file (see js/libs/pdfjs/web/viewer.html from the zip archive attached), call to getMetadata returns all the needed fields, but when performed from a Chrome extension background view (see js/background.js), the getMetadata call returns only three fields: "PDFFormatVersion", "IsAcroFormPresent", "IsXFAPresent".
Can you direct me to the cause of such difference?

Link to PDF file: https://arxiv.org/pdf/1703.01161.pdf (hardcoded in js/background.js).
Archive with project: [plugin-test.zip](https://github.com/mozilla/pdf.js/files/859674/plugin-test.zip).

Configuration:
- Browser: Chrome version 56.0.2924.87 (64-bit)
- System: macOS 10.12
- PDF.js version: 1.7.376
- Is an extension: true

I am sorry if it is a wrong place to ask a question, but I am completely at a loss and cannot understand what causes such a difference in behaviour.

P.S. if there is an easier way to do the same (i.e. extract metadata from a PDF in a current tab), I would be happy to hear it.

**Comment by Rob--W** [comment] 2017-03-22 12:42
This issue is not caused by the extension. When I open viewer.html, and run the following code twice (after running the code once, I wait until all chunks have been fetched before repeating the code again), then all information is shown:

```javascript
url = 'https://arxiv.org/pdf/1703.01161.pdf';
if(!window.doc)doc=PDFJS.getDocument(url);
else doc.then(doc => doc.getMetadata()).then(meta => {console.log(meta.info)})
```

If, on the other hand, I run the following, then only the limited information is displayed:

```javascript
url = 'https://arxiv.org/pdf/1703.01161.pdf';
doc=PDFJS.getDocument(url);
doc.then(doc => doc.getMetadata()).then(meta => {console.log(meta.info)})
```

I guess that the `GetMetadata` handler is resolving too early - the documentInfo getter seems to fulfill to quickly: https://github.com/mozilla/pdf.js/blob/e2e13df4a5af1707768f64591f387ba34a920007/src/core/document.js#L588-L616

@timvandermeij Do you have any immediate suggestion to resolve this?

**Closed** 2017-03-22 13:46 UTC
Labels: 1-core

**Comment by topuhit** [comment] 2017-09-18 00:38
Does anyone know how to get Page Size of a PDF. This is the only field i cant access
![untitled](https://user-images.githubusercontent.com/23435954/30526423-fb0e010c-9c3b-11e7-8295-5dfb5f1954e7.png)

**Comment by Rob--W** [comment] 2017-09-18 14:36
@topuhit Every page in a PDF can have a different size. For the common case that all sizes are equal, it could make sense to add a page size field. You could file a new feature request for that,

**Comment by yurydelendik** [comment] 2017-09-18 14:57
page size/metadata is available from getPage() method.

**Comment by topuhit** [comment] 2017-09-18 17:05
@yurydelendik Can you please write me a short code. I am trying to get the Page Size ( or fist page's dimension) and Page Count of an uploaded PDF. Here's a sample code.  https://jsfiddle.net/topuhit/mo9nzbr3/ Thanks for the reply.

**Comment by yurydelendik** [comment] 2017-09-18 17:16
Find examples at http://mozilla.github.io/pdf.js/examples/ (use scale = 1.0).

```
doc.getPage(1).then(page => {
   var vp = page.getViewport(1);
   console.log((vp.width / 72) + 'in x ' + (vp.height / 72) + 'in');
});
```

**Comment by topuhit** [comment] 2017-09-18 17:42
Thank you @yurydelendik . It solved my problem. I am really glad. Thank you. You are awesome.
