### ISSUE TITLE
Graphics in PDF file is incorrectly drawn

### ISSUE THREAD

**Issue by deepj** [mozilla/pdf.js#6032] opened 2015-05-18 22:20 UTC
PDF document: http://www.barkleyus.com/files/moonshot_techroadmap_poster.pdf
Versions: Firefox 38, pdf.js 1.1.153
OS: Mac OS X 10.10.3

Problem:
The circle is drawn blackly instead of grey.

Here is a correct picture of what would have drawn correctly

![screen shot 2015-05-19 at 00 18 06](https://cloud.githubusercontent.com/assets/33736/7691680/c2cecc9c-fdbc-11e4-8a2b-6ebb77d9d48c.png)

Console output:

None

**Comment by Snuffleupagus** [comment] 2015-05-19 09:04
This is a regression from PR #4161.

**Comment by tkoski** [comment] 2015-05-19 12:23
I wonder if I'm having the same bug.

Version: pdf.js 1.1.155
OS & Browser: any

Problem:
The image on the right hand side is drawn as a black box.

Image drawn OK on this pdf: http://62.210.181.5/ok.pdf
Not OK (image drawn black) on this pdf: http://62.210.181.5/nok.pdf

The difference between the two pdfs is that the later has been "optimized for web". Both look OK at least in couple of other PDF viewers (Chrome's own PDF viewer, Ubuntu's Document Viewer).

Same bug causing these "black areas"?

**Comment by yurydelendik** [comment] 2015-05-19 12:27
@tkoski I don't think it's related. Also it has black area in Mac OSX Preview.

**Comment by tkoski** [comment] 2015-05-19 12:43
@yurydelendik true. Tested more. Works on some viewers but not on all, like Mac OSX Preview, IE 11 inbuild PDF viewers. Will open another issue for this to find the reason what is wrong with the nok.pdf.

**Comment by deepj** [comment] 2015-12-02 14:05
@yurydelendik Hello, any news about this issue?

**Comment by Snuffleupagus** [comment] 2015-12-03 21:22
Closing as fixed by #6720.

**Closed by Snuffleupagus** 2015-12-03 21:22 UTC
Labels: 2-image-quality, 3-regression, 4-smask
