### ISSUE TITLE
Czech characters not displayed correctly when printing or after download

### ISSUE THREAD

**Issue by Andrew5445** [mozilla/pdf.js#15140] opened 2022-07-07 06:00 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 102.0
- Operating system and its version: macOS 12.0.1
- PDF.js version: v2.14.305
- Is a browser extension: No

Steps to reproduce the problem:
1. Fill in the linked pdf file with czech characters **ěščřžýáíééňť** in the Firefox pdf viewer
2. Try to print the file or download it and open it in Adobe Acrobat Reader
3. See that some of those characters - **ě, č, ř, ň, ť** are not displayed correctly

What is the expected behavior? Those newly added characters should be displayed correctly, just as they were written
<img width="1580" alt="Screenshot 2022-07-07 at 7 47 33" src="https://user-images.githubusercontent.com/47328547/177700877-80837033-4120-4226-a08b-091bb6ddc7fb.png">

What went wrong? 
<img width="1564" alt="Screenshot 2022-07-07 at 7 49 04" src="https://user-images.githubusercontent.com/47328547/177701066-664176c3-f6d9-4e60-9488-213e301c3a35.png">

For the first screenshot, characters were added (and document was saved there) before opening it in the default pdf viewer in Firefox. For the second use case, characters were added directly in the Firefox pdf viewer.
[Example of font issues.pdf](https://github.com/mozilla/pdf.js/files/9060761/Example.of.font.issues.pdf)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-07-07 07:49
Duplicate of #12264

**Closed by Snuffleupagus** 2022-07-07 07:49 UTC
