### ISSUE TITLE
Put tools (or at least "Go to first/last page") directly in the tool bar (not in an expandable button)

### ISSUE THREAD

**Issue by nortexoid** [mozilla/pdf.js#7365] opened 2016-05-27 11:33 UTC
I guess most have their browser windows wide enough to fit all the tools directly in the toolbar. But in any case, the negation tools "Go to first/last page" are (in my opinion) incorrectly categorized, since they are not "tools" as the term is usually understood. It makes more sense to move them to the other page navigation buttons.

If there is a desire to have no more buttons in the bar then there currently is, I would consider moving the page navigation buttons into the toolbar and moving presentation mode and print to Tools.

**Comment by Snuffleupagus** [comment] 2016-05-27 12:25
Given that the <kbd>Home</kbd>/<kbd>End</kbd> keyboard keys can also be used for `Go to First/Last Page`, I'm not sure how much value adding them to the primary toolbar would bring for a majority of users.

Regarding moving existing buttons from the primary toolbar into the secondary toolbar, I'm not sure I think that would be a great idea, given that by now users have probably gotten used the placement of functions such as e.g. Print and Presentation Mode.

**Comment by nortexoid** [comment] 2016-05-27 19:53
By that reasoning, the zoom in/out, print, find, etc. buttons should be removed since they have shortcuts assigned to them. Some keyboards don't have home/end keys (like Chromebooks including the one I'm typing on--though they have a combo shortcut that not many are aware of), and there is sometimes a benefit to using a mouse/touchpad instead of a keyboard. (There's also a lot of smaller keyboards these days that don't have home/end keys, including 60% ones.)

I would really reconsider.

**Comment by Snuffleupagus** [comment] 2021-05-30 08:58
Duplicate of #9200

**Closed by Snuffleupagus** 2021-05-30 08:58 UTC
Labels: 1-ux
