### ISSUE TITLE
Pdfs with large size files and Scanned pdfs are not loading in ipad

### ISSUE THREAD

**Issue by shivabalena** [mozilla/pdf.js#4337] opened 2014-02-26 05:45 UTC
issue 1:
scanned pdfs are not working in ipad and showing blank page after 1 minute

issue 2:
pdfs with large size(above 20MB) are not loading in ipad and crash the safari browser after 1 minute.
my configurations:
ipad 2  version:7.0.4

safari(ipad) version:9537.53
pdf link: http://www.digitalscanning.com/images/Samples/Microfilm_Sample_2_OCR.pdf

please help me for this issue ASAP.

**Comment by Snuffleupagus** [comment] 2021-06-28 10:44
> pdf link: http://www.digitalscanning.com/images/Samples/Microfilm_Sample_2_OCR.pdf

That link no longer works; however let's close this as a duplicate of e.g. issue #9474 (since the underlying problem should be similar enough).

**Closed by Snuffleupagus** 2021-06-28 10:44 UTC
Labels: 4-os-ios
