### ISSUE TITLE
Improper Image Display in Internet Explorer

### ISSUE THREAD

**Issue by gsampath127** [mozilla/pdf.js#7375] opened 2016-06-01 04:33 UTC
Please provide quick response for below

Link to PDF file (or attach file here):
1. http://hosted-stage.rightprospectus.com/Wasatch/Fund.aspx?cu=936772201&dt=SAR
2.http://hosted-stage.rightprospectus.com/documents/Wasatch/SEMI_Wasatch.pdf

Configuration:
- Web browser and its version: Internet Explorer , version:11
- Operating system and its version:Windows7
- PDF.js version:1.1.469
- Is an extension:

Steps to reproduce the problem:
1. Go to the given links with PDFJs Viewer both in Chrome and IE.
2.Compare the first page in IE with Chrome.
3.We can find the  the picture on the front cover is not displayed properly.

What is the expected behavior? (add screenshot):
![chromewas](https://cloud.githubusercontent.com/assets/12858790/15698160/2e67db7c-27df-11e6-8739-def1cd56f020.png)

What went wrong? (add screenshot):
![iewas](https://cloud.githubusercontent.com/assets/12858790/15698187/7423da8a-27df-11e6-83db-1d300f40e2c7.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://hosted-stage.rightprospectus.com/Wasatch/Fund.aspx?cu=936772201&dt=SAR

**Comment by Snuffleupagus** [comment] 2016-06-01 08:02
Closing as duplicate of issue #5264; please note https://github.com/mozilla/pdf.js/issues/5264#issuecomment-61472772.

**Closed by Snuffleupagus** 2016-06-01 08:02 UTC

**Comment by gsampath127** [comment] 2016-06-01 09:33
Hi 
 The fix mentioned in Issues #5264 , #3900 does not helped us . Can you please verify this from your side and give the necessary solution/fix.
Attached the PDF Document.
[SEMI_Wasatch.pdf](https://github.com/mozilla/pdf.js/files/293063/SEMI_Wasatch.pdf)
