### ISSUE TITLE
PDF Fonts do not render properly in Safari 

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#8700] opened 2017-07-25 19:56 UTC
Link to PDF file (or attach file here): 
[coxp-3899-safari-font.pdf](https://github.com/mozilla/pdf.js/files/1174584/coxp-3899-safari-font.pdf)

Configuration:
- Web browser and its version: Safari 10.1.2 (12603.3.8)
- Operating system and its version: macOS Sierra 10.12.6
- PDF.js version: latest on demo page (1.8.575?)
- Is an extension: no

Steps to reproduce the problem:
1. View PDF
2. Note that fonts are incorrect (spacing + look/feel)

What is the expected behavior? (add screenshot)
![2017-07-25_12-56-40](https://user-images.githubusercontent.com/689351/28590870-93265b9e-7138-11e7-9bc1-aab47cf8319a.png)

What went wrong? (add screenshot)
![2017-07-25_12-57-08](https://user-images.githubusercontent.com/689351/28590883-a2c98990-7138-11e7-900b-f35ed0ca3195.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

May be related to https://github.com/mozilla/pdf.js/issues/8231? Issue does not manifest in Firefox or Chrome.

**Comment by Snuffleupagus** [comment] 2017-07-26 11:56
> May be related to #8231? Issue does not manifest in Firefox or Chrome.

Looks similar enough, let's close this as a duplicate of #8231.

**Closed by Snuffleupagus** 2017-07-26 11:56 UTC
Labels: 4-font-conversion, 4-safari-specific
