### ISSUE TITLE
webpack should turn on optimization when building files

### ISSUE THREAD

**Issue by stof** [mozilla/pdf.js#11852] opened 2020-04-27 14:06 UTC
Currently, built files are generated by webpack in dev mode. While this indeed achieves the result of not minifying them, it makes them bigger than necessary when minifying them later, as it also disables other webpack optimization which help a lot with minification (the module concatenation feature especially, which allows to have local variables that can be mangled for all internal imports, and also benefits performance by removing wrapper functions).
I think it would make sense to turn on these optimizations in the webpack config (either by enabling relevant prod optimization, or by switching webpack to prod mode and disabling only the minification).

Note that the module concatenation optimization is applied only for ES modules. The current setup converts ES modules to CommonJS ones in Babel, so they are not ES modules from webpack's point of view. To benefit from the optimization, Babel should preserves ES imports and exports (relying on webpack to manage them).

**Comment by Snuffleupagus** [comment] 2021-05-29 12:49
> I think it would make sense to turn on these optimizations in the webpack config (either by enabling relevant prod optimization, or by switching webpack to prod mode and disabling only the minification).

Generally speaking, for future reference, this is probably the sort of case where additional details such as e.g. links to documentation/examples would be of help.

> Note that the module concatenation optimization is applied only for ES modules.

In that case, we can probably close this issue as (effectively) a duplicate of issue #10317.
(Also, please keep in mind that the built-in Firefox PDF Viewer is still the *main* development target of this library.)

**Closed by Snuffleupagus** 2021-05-29 12:49 UTC
Labels: 1-other
