### ISSUE TITLE
multiline annotation only storage last line

### ISSUE THREAD

**Issue by hbghlyj** [mozilla/pdf.js#17097] opened 2023-10-09 07:01 UTC
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Chrome 117.0.5938.150 (Official Build) (64-bit) (cohort: Control) 
- Operating system and its version: Windows 11 Version 22H2 (Build 22621.2283)
- PDF.js version: PDF.js: 4.0.40 [d64f223d0]
- Is a browser extension: No

Steps to reproduce the problem:
1. Add annotation 111111 and line break and 222222<img width="410" alt="image" src="https://github.com/mozilla/pdf.js/assets/53823634/b6426a07-0623-4ccd-ab28-89e1a74f3f9c">
2. Print or Save the PDF

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
The first line is missing, only second line 222222
<img width="543" alt="image" src="https://github.com/mozilla/pdf.js/assets/53823634/c33af6d5-7bf9-4f5d-ae24-3097e24acf41">

**Comment by Snuffleupagus** [comment] 2023-10-09 07:18
Duplicate of #17079

**Closed by Snuffleupagus** 2023-10-09 07:18 UTC
