### ISSUE TITLE
Big product/sum signs looks funny

### ISSUE THREAD

**Issue by chisophugis** [mozilla/pdf.js#9602] opened 2018-03-25 06:58 UTC
Attach (recommended) or Link to PDF file here:

[itila.pdf](https://github.com/mozilla/pdf.js/files/1845081/itila.pdf)

Configuration:
- Web browser and its version: firefox 59.0.1 (64-bit)
- Operating system and its version: ubuntu linux 16.04
- PDF.js version: the one built in to firefox
- Is a browser extension: it is built in

Steps to reproduce the problem:
1. open http://www.inference.org.uk/itprnn/book.pdf (attached above for convenience)
2. go to page 349 (it is the page that has the number 337 in the text itself)

What is the expected behavior? (add screenshot)

Notice the big product sign in equation 26.15 here for reference. And the inline big sum sign just below (Z=\sum ...).
(rendered by evince; `evince --version` "GNOME Document Viewer 3.10.3")

![screenshot from 2018-03-24 23-40-42](https://user-images.githubusercontent.com/358163/37872440-cb3f49a8-2fbc-11e8-80dd-488583f86cc1.png)

What went wrong? (add screenshot)

The big product sign in equation 26.15 looks weird. Also the inline big sum sign looks weird. The sum and product signs look weird on the next page too (and throughout the book integral signs and big brackets and big square roots look funny too)

![screenshot from 2018-03-24 23-38-00](https://user-images.githubusercontent.com/358163/37872429-8f48d2e8-2fbc-11e8-902c-ed3964c026ec.png)

**Comment by chisophugis** [comment] 2018-03-25 07:08
Note: it looks correct on http://mozilla.github.io/pdf.js/web/viewer.html in chromium `Version 64.0.3282.167 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)`.

**Comment by chisophugis** [comment] 2018-03-25 07:10
And it looks incorrect on http://mozilla.github.io/pdf.js/web/viewer.html in the same firefox as the original report. So it seems to be something firefox-specific.

**Comment by Snuffleupagus** [comment] 2019-02-01 12:19
> And it looks incorrect on http://mozilla.github.io/pdf.js/web/viewer.html in the same firefox as the original report. So it seems to be something firefox-specific.

This issue looks, on the face of it, like another duplicate of #2594. However, that one was fixed all the way back in 2016 and https://github.com/mozilla/pdf.js/issues/9602#issuecomment-375950372 was posted more than a year later.

In closing though, I cannot image this being a problem after PR #9340 since all glyphs are now re-mapped to the Private Use Area (which ought to exclude them from any auto-hinting routines).

**Comment by timvandermeij** [comment] 2019-02-01 23:41
Closing until we receive more information that this still happens with the latest version.

**Closed by timvandermeij** 2019-02-01 23:41 UTC
Labels: 1-core, 4-firefox-specific
