### ISSUE TITLE
[Bug]: ff ligature (and friends) can't be found and is improperly copied

### ISSUE THREAD

**Issue by ellis-hebbia** [mozilla/pdf.js#18662] opened 2024-08-28 23:47 UTC
### Attach (recommended) or Link to PDF file

[Chrome Page 1 Terms of Service – Hugging Face.pdf](https://github.com/user-attachments/files/16789949/Chrome.Page.1.Terms.of.Service.Hugging.Face.pdf)

### Web browser and its version

Chrome 127 or Firefox 129

### Operating system and its version

Mac OS 14

### PDF.js version

4.4

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

In the attached PDF (webpage downloaded from Chrome): 

- Try to command + F for the words "Effective", "drafted", or "offer" and you will get no results.
- If you copy the text directly from the PDF into the search bar it will work even though it appears to be incorrect because it includes a hidden char for the 'ff'/'ft'.
- Typing the broken search in manually will yield no results as it requires the broken char.

### What is the expected behavior?

'ff' and friends should be parsed correctly and therefore be findable and copy-able.

### What went wrong?

Can't find the text using the search feature.

The same exact webpage downloaded in Firefox works perfectly fine in the PDF.js viewer, so clearly Chrome pdf exports are formatting the PDF differently in this case. I'm guessing there's some issue with the font or unicode mapping data? Theres also a missing emoji which may be a clue.

### Additional context

This is possibly related to https://github.com/mozilla/pdf.js/issues/12237, however examining the internals of the PDF I didn't find any /ActualText data that could have been used to correct the text. The chrome PDF viewer and adobe acrobat are able to command + F and copy the words properly.

**Comment by Snuffleupagus** [comment] 2024-08-29 07:07
> ### PDF.js version
> 
> 4.4

That's not a complete version number, please remember to state the *full* version when reporting an issue.
(Also, any `4.4.x` version is no longer supported.)

> This is possibly related to #12237, however examining the internals of the PDF I didn't find any /ActualText data that could have been used to correct the text.

Duplicate of #12237.
In this case (which is a very common one) the /Contents streams are compressed, hence you cannot e.g. just open the PDF document in a text-editor and search for occurrences of a word.

**Closed by Snuffleupagus** 2024-08-29 07:07 UTC

**Comment by THausherr** [comment] 2024-08-29 14:54
/ActualText is there:

```
        /Span << /ActualText (ff) >> BDC
          9.6839905 0 Td
          (\000{) Tj
        EMC
...
        /Span << /ActualText (ft) >> BDC
          9.071991 0 Td
          (\000|) Tj
        EMC
```
