### ISSUE TITLE
Pixelation problem when loading a pdf document with large size page.

### ISSUE THREAD

**Issue by gb-ui-tester** [mozilla/pdf.js#5733] opened 2015-02-14 00:23 UTC
When I loaded a pdf document that has large size page (long height, width, or both), the entire page was pixelated like the following screenshot:

![screen shot 2015-02-13 at 3 56 46 pm](https://cloud.githubusercontent.com/assets/11000203/6197458/78d438f0-b39a-11e4-88e0-ead75e328d8e.png)
left: pdf.js viewer (PDF.JS: 1.0.1143), right: Mac OS X 10.10.2 Preview

I tested it in FF, Chrome, and IE (on PC).

**Comment by Snuffleupagus** [comment] 2021-03-22 15:51
I'd suggest closing this issue now, since:
 - It doesn't include the PDF file in question, meaning that it's not possible to replicate what's seen in the screen-shots.
 - It's very old, and most likely (for all intents and purposes) a duplicate of issue #6419.

**Closed** 2021-03-24 19:30 UTC
Labels: 2-image-quality
