### ISSUE TITLE
bug: Characters are rendered incorrectly

### ISSUE THREAD

**Issue by carlinmack** [mozilla/pdf.js#17953] opened 2024-04-16 14:51 UTC
Attach (recommended) or Link to PDF file here: https://zenodo.org/records/10561061

Configuration:
- Web browser and its version: Vivaldi
- Operating system and its version: Mac
- PDF.js version: circa 2016
- Is a browser extension: No

Steps to reproduce the problem:
1. https://zenodo.org/records/10561061

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/6676843/e90d8924-3a0c-4c67-bcb7-8d98ee872d32)

What went wrong? (add screenshot)

![image](https://github.com/mozilla/pdf.js/assets/6676843/c67b6b43-ed81-4976-a886-4808409a96ff)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://zenodo.org/records/10561061

**Comment by timvandermeij** [comment] 2024-04-16 15:00
The PDF.js version on that website is 1.10.100 according to the web console, which is over 6 years old and therefore long out of support. I have confirmed that the most recent version of PDF.js (try https://mozilla.github.io/pdf.js/web/viewer.html for example) doesn't have the issue anymore. Closing since this issue is therefore invalid (and please inform the owner of that website that their PDF.js version is severely out of date and should not be used anymore).

**Closed by timvandermeij** 2024-04-16 15:00 UTC
