### ISSUE TITLE
Import a large document in the demo, click the enlarge button, the page content is not clear

### ISSUE THREAD

**Issue by QM36** [mozilla/pdf.js#12955] opened 2021-02-04 08:57 UTC
Configuration:
Web browser and its version: chrome & firefox
Operating system and its version: chrome(88.0.4324.96) firefox(84.0.2)
Operating system and its version: macOS Catalina 10.15.7
PDF.js version: the latest(here are the logs)

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/32392850/106868537-d6bcdc00-6709-11eb-898c-220b338df706.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/32392850/106868487-cb69b080-6709-11eb-9ac7-426ed2540975.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[生理学—10.神经系统.pdf](https://github.com/mozilla/pdf.js/files/5924359/10.pdf)

Thanks for your reply, I would like to know under what circumstances the blur will appear. By the way, are there any restrictions on pdf.js, and where are the restrictions in the code?

**Comment by Snuffleupagus** [comment] 2021-02-04 09:14
> PDF.js version: the latest(here are the logs)

Again, you should provide an actual version *number* here, since "latest" can mean any number of things.

> I would like to know under what circumstances the blur will appear.

It's related to the `maxCanvasPixels` value, since CSS zooming occurs above that threshold to prevent huge canvases (similar to your previous issue #12495).

---

This issue is, for all intents and purposes, a duplicate of #6419.

**Comment by QM36** [comment] 2021-02-04 09:58
Sorry forgot to paste my commit record, here are the logs
![image](https://user-images.githubusercontent.com/32392850/106876286-826a2a00-6712-11eb-8d7d-3ae496922e9f.png)

**Closed** 2021-02-04 22:52 UTC
