### ISSUE TITLE
window.url.createobjecturl(blob) not working in Edge

### ISSUE THREAD

**Issue by patelsumit5192** [mozilla/pdf.js#10173] opened 2018-10-22 12:27 UTC
Firstly, I tried all the questions & answers related to this topic. Additionally and I tried related questions and try to solve it but no the success. So please read my question thoroughly.

**Search Questions:**

1. [Displaying Blob PDF in Edge/IE11](https://stackoverflow.com/questions/38505424/displaying-blob-pdf-in-edge-ie11)
2. [Windows Edge and opening a blob URL](https://stackoverflow.com/questions/32217537/windows-edge-and-opening-a-blob-url)
3. [Blob download is not working in IE](https://stackoverflow.com/questions/20310688/blob-download-is-not-working-in-ie)

I've searched related questions and tried to write the code but not had any success. I work with the PDFJS Project. I have open blob file in new tap. The below code works in all browsers (Chrome, Firefox, IE) but it's not working in Edge. I also use `viewer.js` in my project. I want to load my PDF file in Edge browser **Microsoft Edge 42.17134.1.0*.

**code**

```
 var xhr = new XMLHttpRequest();
    xhr.open('POST', '/pdfblob.aspx', true);
    xhr.responseType = 'blob';
    xhr.onload = function (e) {
      var url = window.URL.createObjectURL(this.response);
      window.open('/web/viewer.html?file=' + url);
    };
    xhr.send();
```

This is the error I get:
https://i.stack.imgur.com/EXUQ4.png

**Comment by timvandermeij** [comment] 2018-10-22 20:58
Don't you need to do something like this then? https://stackoverflow.com/a/16179887

**Comment by patelsumit5192** [comment] 2018-10-23 07:05
i try to `PDFViewerApplication.open(blob_data)` 

```
var xhr = new XMLHttpRequest();
    xhr.open('POST', '/pdfblob.aspx', true);
    xhr.responseType = 'blob';
    xhr.onload = function (e) {
      var url = window.URL.createObjectURL(this.response);
     // window.open('/web/viewer.html?file=' + url);
    var blob_data = this.response;
     PDFViewerApplication.open(blob_data);
    };
    xhr.send();
```

> i got error

 **PDFViewerApplication' is not defined**

**Comment by patelsumit5192** [comment] 2018-10-23 13:01
I tried this` PDFViewerApplication.open(blob_data)`  it is not working in Microsoft Edge 42.17134.1.0 . it was working in the previous version of Edge. the same function is also working in all other browsers (Chrome, Firefox, IE).

**Comment by Snuffleupagus** [comment] 2019-02-07 15:44
> [...] it is not working in Microsoft Edge 42.17134.1.0 . it was working in the previous version of Edge.

This rather clearly points to a bug/regression in the Edge browser, rather than in the PDF.js library/viewer, which should thus be reported to the Edge developers instead.

> the same function is also working in all other browsers (Chrome, Firefox, IE).

This furthermore confirms that this isn't a general bug in PDF.js, and this issue should probably be closed as INVALID since there's nothing we can do here.

**Closed** 2019-02-07 21:59 UTC
Labels: 1-other, 4-ie-edge-specific
