### ISSUE TITLE
add annotation to a pdf file by using the pdfbox

### ISSUE THREAD

**Issue by weihuiHong** [mozilla/pdf.js#9850] opened 2018-06-28 08:56 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome v67
- Operating system and its version: macOs High Sierra v10.13.4
- PDF.js version:2.0
- Is a browser extension:No

Steps to reproduce the problem:
I used the pdfbox to add annotation to a pdf file. And I use the local pdf reader to open the pdf file to display normally.
![image](https://user-images.githubusercontent.com/29445277/42024161-23c5f9d2-7af4-11e8-93d0-e850a999e5d4.png)
![image](https://user-images.githubusercontent.com/29445277/42023802-517bb480-7af3-11e8-8a29-c98373ed3189.png)
While I use the pdf.js to display the pdf file, it would show below:
![image](https://user-images.githubusercontent.com/29445277/42023903-91aa9b52-7af3-11e8-9105-e89176f739c2.png)
This highlight effect does not display normally.
And the developer tools prompts me for this message:
![image](https://user-images.githubusercontent.com/29445277/42024065-ef85be3c-7af3-11e8-8a55-0c7527c8dc4f.png)

Does anyone know how to solve it?

**Comment by THausherr** [comment] 2018-06-28 10:56
PDFBox 2.* does not set the appearance stream of an annotation. PDFBox trunk ( https://repository.apache.org/content/groups/snapshots/org/apache/pdfbox/pdfbox-app/3.0.0-SNAPSHOT/ ) does it for many (you have to call constructAppearance()), but not all. PDF.js cannot calculate the missing appearance stream, see #6810.

**Comment by timvandermeij** [comment] 2018-06-28 21:08
Closing since this is a duplicate of #6810.

**Closed by timvandermeij** 2018-06-28 21:08 UTC

**Comment by THausherr** [comment] 2018-06-29 04:45
@weihuiHong I'd love to hear (in PDFBOX-3353) if there are any troubles with the ongoing PDFBox development re: annotations. To test this, use the latest snapshot from the link I posted above and run java -jar pdfbox-app-3.0.0-20180628.182724-716.jar PDFDebugger YOURFILE.PDF. This displays the files with PDFBox and should show the missing appearance even if you used PDFBox 2.0. If it doesn't work, please drop your files on PDFBOX-3353 (you may have to register). That URL also has some code that can be used together with PDFBox 2.0, see the attached file (there, not here) ShowAnnotation-6.java.
