### ISSUE TITLE
Error during font loading: Font Arial is not available

### ISSUE THREAD

**Issue by SwatiMaheshwari** [mozilla/pdf.js#11040] opened 2019-08-04 15:33 UTC
Attach (recommended) or Link to PDF file 
[FORM16.pdf](https://github.com/mozilla/pdf.js/files/3465029/FORM16.pdf)

Configuration:
- Web browser and its version: chrome
- Operating system and its version: windows7 
- PDF.js version: 1.x
- Is a browser extension:no

Steps to reproduce the problem:
1. open the pdf using pdf.js
2.eror come during loading font

What is the expected behavior? (add screenshot) no error should come as all the fonts are embedded in pdf.

**Comment by Snuffleupagus** [comment] 2019-08-04 15:46
Looks like a duplicate of issue #10524.

> PDF.js version: 1.x

*For future reference:* The information you provide in the issue template must make sense, and the above is definitely *not* a valid version number.
Furthermore, as has already been explained to you elsewhere, the `1.x.y` branch is no longer supported and you'll need to update latest release (see https://github.com/mozilla/pdf.js/releases).

**Comment by SwatiMaheshwari** [comment] 2019-08-04 17:02
I have upgraded to latest version.still getting same error?
are only on/off values supported for checkbox?

**Comment by timvandermeij** [comment] 2019-08-04 17:37
> no error should come as all the fonts are embedded in pdf

Okular tells me that at least "ZapfDingbats" and "Helvetica" are not embedded, so this isn't entirely correct. You'll have to make sure that all fonts are embedded, otherwise the PDF file is likely to be rendered differently (or incorrectly) across devices.

Once that is fixed, this is most likely a duplicate of #7788, so I'm closing this as such.

**Closed by timvandermeij** 2019-08-04 17:37 UTC

**Comment by SwatiMaheshwari** [comment] 2019-08-06 05:31
Hi,
I have changed all the checkbox values to yes/no. Still I am getting error.

Also all the fonts are embedded in the pdf but after opening it with pdf.js the pdf gets corrupted with non embedded fonts.

Chceking embedded fonts =>choose File > Properties > Fonts.

**Comment by timvandermeij** [comment] 2019-08-06 20:39
Based on the description, I can only guess this being #7788 for which we don't have a solution yet.
