### ISSUE TITLE
Add "Send as Mail" Feature to Toolbar - Alternatively Choose Action at Download

### ISSUE THREAD

**Issue by JiPa2022** [mozilla/pdf.js#15326] opened 2022-08-17 13:41 UTC
Hello,

Until Firefox 101.01 it was possible, to still use the "Choose What to do with the file" when You clicked on the "Download" Button inside PDF.JS Toolbar. - I ´ve already tried known Workarounds from here https://support.mozilla.org/en-US/questions/1370409 to bring back this feature without any effect. 

I guess the true issue is somewhere in the area of how PDF.JS parses the output - since there are instances when you simply click on a PDF download link, and it still behaves as wished (probably due to the above mentioned workarounds)

The main reason is, that there needs to be a way to send a File from the Viewer by mail, without the need to handle the download manually first. So I would like to ask for these following features, which of each I would see as good solution 

1. Is there any known way, to bring back the old way of behaviour of the "Download" Button inside of a PDF.JS viewer, so we can again choose if we want to open it in Full Acrobat or Save it.
2. Implement a "Send as Attachment by Mail" Button
3. Implement a direct "Open in Full Version of Acrobat" Button

Any ideas? I list this as an issue, as it is actually workflow dependant

**Comment by Snuffleupagus** [comment] 2022-08-17 14:02
> 1. Is there any known way, to bring back the old way of behaviour of the "Download" Button inside of a PDF.JS viewer, so we can again choose if we want to open it in Full Acrobat or Save it.

Not that I'm aware of unfortunately, since this is the result of changes on the browser side in Firefox (rather than in *this* repository).

 > 2\. Implement a "Send as Attachment by Mail" Button

Duplicate of #5527

> 3\. Implement a direct "Open in Full Version of Acrobat" Button

Duplicate of #2553

**Closed by Snuffleupagus** 2022-08-17 14:02 UTC
