### ISSUE TITLE
Cropped file display

### ISSUE THREAD

**Issue by hitman4an** [mozilla/pdf.js#17530] opened 2024-01-17 08:25 UTC
File cropped at the end,

at pdf.js:
![image](https://github.com/mozilla/pdf.js/assets/23082585/88813e62-a263-4786-b821-999292919059)

at Acrobat Reader:
![image](https://github.com/mozilla/pdf.js/assets/23082585/f9af9256-582c-4dd6-9ba7-ebdad2d8594f)

File:
[Работа с пожеланиями от клиента.pdf](https://github.com/mozilla/pdf.js/files/13960444/default.pdf)

**Comment by Snuffleupagus** [comment] 2024-01-17 09:23
Duplicate of #14982

---

*For future reference:* Please fill out the ISSUE_TEMPLATE properly, rather than ignoring it, when opening an issue.

**Closed by Snuffleupagus** 2024-01-17 09:23 UTC
