### ISSUE TITLE
[Bug]: Regression in outline navigation

### ISSUE THREAD

**Issue by mrtcode** [mozilla/pdf.js#18408] opened 2024-07-08 16:08 UTC
### Attach (recommended) or Link to PDF file

Can’t provide an example due to copyright restrictions.

### Web browser and its version

Chrome, Safari, Firefox

### Operating system and its version

macOS

### PDF.js version

4.5.47

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Click on any outline item.

### What is the expected behavior?

Navigate to desired destination.

### What went wrong?

pdf_link_service.js:149 goToDestination: "null" is not a valid destination array, for dest="section*.5.2".
goToDestination	@	pdf_link_service.js:149
await in goToDestination (async)		
element.onclick	@	pdf_outline_viewer.js:153

### Additional context

This seems to be a regression because it works as expected in PDF.js 3.7.96 and all other PDF viewers, but not in PDF.js 4.5.47.

Hopefully, the error message is enough to isolate the problem, but if not, you can contact me for the file.

**Comment by wikisqueaks** [comment] 2024-07-09 23:49
I am also experiencing this behaviour.

**Comment by timvandermeij** [comment] 2024-07-10 13:11
Unfortunately the PDF file is a required part of the issue template because we can't debug the issue with just the error message, and PDF files need to be attached to the issue so everyone can immediately help out without having to contact the issue reporter first. Therefore, please try to either provide a non-copyrighted file or create a new PDF file without copyrighted content that triggers the issue.

**Comment by timvandermeij** [comment] 2024-07-13 13:45
Closing due to the above. The issue can be reopened if a publicly available PDF file that shows the issue is attached to this issue.

**Comment by mrtcode** [comment] 2024-07-14 11:09
All right, I found an open-access book with the same problem:

https://link.springer.com/content/pdf/10.1007/978-3-319-93935-3.pdf

**Comment by mrtcode** [comment] 2024-07-17 20:50
Can the issue be reopened now that I have provided the file?

**Closed** 2024-07-18 11:32 UTC
Labels: information-requested
