### ISSUE TITLE
Invalid calling object in IE11

### ISSUE THREAD

**Issue by coder-5943123** [mozilla/pdf.js#10481] opened 2019-01-22 13:29 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Internet Explorer 11 (version 11.523.17134.0) (update version 11.0.105 KB4480965)
- Operating system and its version: Windows 10 1803 (17134.523)
- PDF.js version: 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. Update to pdfjs-dist 2.0.943
2. Launch web appplication

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
The web application doesnt load and a error is displayed in the console. If the document mode is changed from 11 to 10 the web application successfully loads.

See image below:
![2019-01-22 14_20_38_internet_explorer_11](https://user-images.githubusercontent.com/45265821/51538722-51339f80-1e52-11e9-9c23-9b17efbf7011.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-01-22 13:36
Duplicate of #10460.

**Closed** 2019-01-22 22:37 UTC
