### ISSUE TITLE
Unable to get parameters of current view in a local pdf

### ISSUE THREAD

**Issue by sttst** [mozilla/pdf.js#15333] opened 2022-08-19 12:11 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox Nightly 105.0a1
- Operating system and its version: Debian 11
- PDF.js version: 2.16.71
- Is a browser extension: No

Steps to reproduce the problem:
1. Download a pdf.
2. Open the pdf in Firefox.
3. Click on current view.
What is the expected behavior? (add screenshot)
The url should update.
![grafik](https://user-images.githubusercontent.com/111575303/185615091-d6b03b4c-e6f6-4029-9446-c9f9ca2e7115.png)

What went wrong? (add screenshot)
The url does not get updated. Security Error in the console.
![grafik](https://user-images.githubusercontent.com/111575303/185615460-3911ba1f-2872-47dc-a842-b5f78961fd94.png)

**Comment by Snuffleupagus** [comment] 2022-08-19 12:20
This is, for all intents and purposes, a duplicate of e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1678914

**Closed by Snuffleupagus** 2022-08-19 12:20 UTC
