### ISSUE TITLE
[textLayerMode bug]When selecting text, a large number of text will be selected when the mouse slides down

### ISSUE THREAD

**Issue by zhanghexin** [mozilla/pdf.js#15680] opened 2022-11-11 02:26 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome v107.0.5304.87 (Official) (arm64)
- Operating system and its version: Window 10
- PDF.js version:3.0.279
- Is a browser extension:: no

Steps to reproduce the problem:
1. Open the pdf link .
2. When the mouse moves downward, many words will be selected

What is [the](url) expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/8513026/201250212-57e9db18-769b-4642-8e97-0f8917e1f338.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/8513026/201250252-212888ba-57cf-4545-9312-8f47293cf3f6.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-11-11 08:47
Duplicate of #9843

**Closed by Snuffleupagus** 2022-11-11 08:47 UTC
