### ISSUE TITLE
Search functionality of phrases not working for certain pdfs

### ISSUE THREAD

**Issue by Rebecca90** [mozilla/pdf.js#12589] opened 2020-11-06 07:10 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: 

Steps to reproduce the problem:
1. Opened a pdf from my local machine onto this link -https://mozilla.github.io/pdf.js/web/viewer.html
2.Copied a phrase from the pdf and searched for it in the pdf.
3. The search is unable to find the phrase in the pdf.

What is the expected behavior? (add screenshot)
Tried opening the **same** pdf using chrome browser and microsoft edge, searched for the phrase there. It works in those browsers.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2020-11-06 08:39
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is there's no actionable information provided and the issue is thus INCOMPLETE.

> 1. Opened a pdf from my local machine onto this link -https://mozilla.github.io/pdf.js/web/viewer.html

You've not attached the PDF file in question here, hence this part of the STR is impossible to follow!

> 2. Copied a phrase from the pdf and searched for it in the pdf.

Furthermore, without the *exact* phrase used this part of the STR is also not helpful.

**Comment by Rebecca90** [comment] 2020-11-06 09:29
Hi , 
Attaching the PDF below
[d_c (1).pdf](https://github.com/mozilla/pdf.js/files/5500312/d_c.1.pdf)

Copied phrase from the pdf - External Partyis a provider of certain

**Comment by Snuffleupagus** [comment] 2021-04-30 19:11
WFM, most likely fixed by PR #13257.

**Closed** 2021-04-30 19:15 UTC
Labels: 4-text-selection
