### ISSUE TITLE
Works SOMETIMES with Toyota Information System

### ISSUE THREAD

**Issue by Premierautomotive** [mozilla/pdf.js#5784] opened 2015-03-04 13:52 UTC
We are an automotive repair shop that uses tablets to view repair information. We use TIS or Technical Information System. Seems like any repair section on 2002 and older won't load... Could you please take a look at it? I will provide you with login information to access the website.

Thanks in advance

**Comment by timvandermeij** [comment] 2015-03-04 18:39
Could you post a PDF file here that causes problems for you so we can all take a look at it?

**Comment by yurydelendik** [comment] 2015-03-04 22:08
@Premierautomotive could you also provide more information about the configuration (operating system, browser, etc, see https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md)? it will be helpful for a contributor to decide if he/she can work on it.

**Comment by Premierautomotive** [comment] 2015-03-04 23:32
https://techinfo.toyota.com/t3Portal/resources/jsp/siviewer/index.jsp?dir=rm/RM911U&href=xhtml/RM911U_0608.html&locale=en&model=ES300&MY=2002&keyWord=spark%20&t3id=RM911U_0608&User=false&publicationNumber=RM911U&objType=rm&docid=785517&context=ti

Hopefully the above link works. I can download the pdf, but I am unsure how to go about attaching it to this message. 

We are using both a Nexus 7 and Nexus 9 with the most recent Lolipop updates and firefox browser.

Please let me know if there is anything else I can answer.

**Comment by timvandermeij** [comment] 2015-03-05 19:20
@Premierautomotive I can't seem to use that link; it asks for a login. You can post the PDF using any file sharing website such as Dropbox or Google Drive.

**Comment by Premierautomotive** [comment] 2015-03-05 19:27
https://drive.google.com/file/d/0Bxvjg_80YVFvLXNVdGJHTlNsdUk/view?usp=sharing

Tim, I would be more than happy to privately exchange login information to the website to correct the condition if necessary.

Thanks for your quick response.

**Comment by timvandermeij** [comment] 2015-03-05 19:32
The PDF renders perfectly fine for me using Firefox on Windows. Marking as Android-specific for now. Might also be related to #5774.

**Comment by timvandermeij** [comment] 2015-03-05 19:39
Closing as duplicate of #5774. Let's move all triage to there.

**Closed by timvandermeij** 2015-03-05 19:39 UTC
Labels: 4-os-android
