### ISSUE TITLE
PDF document containing images of scanned documents not displaying correctly

### ISSUE THREAD

**Issue by dblohm7** [mozilla/pdf.js#6044] opened 2015-05-24 17:47 UTC
When I look at this PDF document:
https://www.nsa.gov/public_info/_files/nash_letters/nash_letters1.pdf

Only the first of eighteen pages contains any content. When I look at it in Acrobat, the remaining pages are visible and appear to be images of scanned documents.

**Comment by CodingFabian** [comment] 2015-05-24 19:00
Thank you for your report, however it does render fine with the latest version of PDF.js. Can you please doublecheck that and in case it does not work provide details on your OS/Browser and PDF.js version.

**Comment by Snuffleupagus** [comment] 2015-05-25 08:42
Closing as duplicate of issue #6017.

**Closed by Snuffleupagus** 2015-05-25 08:42 UTC
