### ISSUE TITLE
Cannot print Google Slide or Drawing from Chromebook

### ISSUE THREAD

**Issue by cslobo** [mozilla/pdf.js#7249] opened 2016-04-25 19:10 UTC
Configuration:
- Operating system and its version: 50

Steps to reproduce the problem:
1. Create a slide or drawing
2. Attempt to print and nothing (no print dialog) appears

What is the expected behavior?
A print dialog box

**Comment by timvandermeij** [comment] 2016-10-09 15:13
Closing as duplicate of #7068.

**Closed by timvandermeij** 2016-10-09 15:13 UTC
Labels: 4-chrome-specific, 4-printing
