### ISSUE TITLE
Angular 2/ExpressJS - Refused to get unsafe header “Accept-Ranges”

### ISSUE THREAD

**Issue by natcohen** [mozilla/pdf.js#7701] opened 2016-10-08 23:09 UTC
Using a webapp with NodeJS and ExpressJS as a server (CORS not configured) and Angular 2 for the client. I read here and there that I should enable CORS... I'm not sure where I should enable it and why should I enable CORS. The server is running in localhost.

Configuration:
- Web browser and its version: Chrome 53.0.2785.143
- Operating system and its version: Windows 10
- PDF.js version: 1.5.118 and 1.6.210
- Is an extension: - 

Steps to reproduce the problem:
1. Make a local server with NodeJS and ExpressJS
2. Make an Angular 2 app
3. Use an html input to upload any pdf
4. Read the pdf with FileReader (with .readAsDataURL)
5. Try to open the pdf with pdf.js as follow:

```
PDFJS.disableWorker = true;
PDFJS.getDocument(reader.result).then(function getPdf(pdf) {
        pdf.getPage(1).then(function getPage(page) {

        })
})
```

What is the expected behavior? (add screenshot)
Not getting an error...

What went wrong? (add screenshot)
Getting the following error:

```
pdf.worker.js:43268  -   Refused to get unsafe header "Accept-Ranges"
```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment] 2016-10-09 03:40
Steps 1 and 2 are not clear: not everyone knows how to do those. Please provide complete examples.

**Comment by natcohen** [comment] 2016-10-09 07:56
@yurydelendik use the following seed: https://github.com/vyakymenko/angular2-seed-express

**Comment by timvandermeij** [comment] 2016-10-09 14:33
You need to provide a link to a complete example (on your own server, JSBin, or another service) so we can reproduce the issue, otherwise this issue will be closed as incomplete because we cannot see the exact code/steps you took.

**Comment by natcohen** [comment] 2016-10-11 07:04
@timvandermeij Here is a [working demo](http://plnkr.co/edit/fCfgAxR8408zXT0vSb3e?p=preview) (checked with chrome 53)

Look at the console when you upload a pdf and you will see the following warning and error:

```
pdf.worker.js:43024 - The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
pdf.worker.js:43333 - Refused to get unsafe header "Accept-Ranges"
```

PS I've posted [here](https://github.com/mozilla/pdf.js/issues/6306) and [here](https://github.com/nnarhinen/react-pdf/issues/27) for the warning

**Comment by yurydelendik** [comment] 2016-10-11 14:04
Thank you for the demo. Looks like it's just XHR is not happy with pulling headers from the data: URI (at https://github.com/mozilla/pdf.js/blob/master/src/core/network.js#L407)

We can avoid getting headers if it's not an HTTP(S) response. Marking as good beginner bug.

Also, XHR with data: on all browsers -- you can avoid warning and save memory by passing Uint8Array instead of data URI.

**Comment by natcohen** [comment] 2016-10-13 10:57
@yurydelendik Passing Uint8Array instead of data got rid of the error but not the warning :-S

**Comment by timvandermeij** [comment] 2016-10-13 11:42
You can ignore the warning about `moz-chunked-arraybuffer` in Chrome. It's not a problem as it's Firefox-only, but other browsers will display this warning (see #7553 and others).

**Comment by crebuh** [comment] 2016-10-28 08:36
Any example on how to convert from a URL to an Uint8Array if this is even possible?

**Comment by mukulmishra18** [comment] 2016-10-31 15:56
@yurydelendik, you mentioned that "we can avoid getting headers if it's not an HTTP(S) response", how we can do this. I am interested in this issue and want to work on that, please guide.

**Comment by yurydelendik** [comment] 2016-10-31 16:11
> you mentioned that "we can avoid getting headers if it's not an HTTP(S) response", how we can do this. I am interested in this issue and want to work on that, please guide.

In the network.js, provide additional checks for the URL protocol probably at validateRangeRequestCapabilities.

**Comment by mukulmishra18** [comment] 2016-10-31 18:05
> In the network.js, provide additional checks for the URL protocol probably at 
validateRangeRequestCapabilities.    

By some exploration, i came across that, remote pdf should return the following http header:
Access-Control-Expose-Headers: Accept-Ranges, Content-Encoding, Content-Length, Content-Range

In validateRangeRequestCapabilities, we had checked for Accept-Ranges, Content-Encoding and Content-Legth but not Content-Range, so i think we have to add an additional check for Content-Range. Am i going right?

**Comment by mukulmishra18** [comment] 2016-11-12 20:25
@yurydelendik i have implemented extra check for http protocol and it works fine for a simple webapp on my local machine. Please find the PR linked below and point me out if i made some mistake. 

[https://github.com/mozilla/pdf.js/pull/7803](url)

**Closed** 2016-11-14 12:04 UTC
Labels: 1-other, 5-good-beginner-bug
