### ISSUE TITLE
feature request: make pdf.js subject to firefox-themes / global gtk-theme

### ISSUE THREAD

**Issue by LordTaifleh** [mozilla/pdf.js#8026] opened 2017-02-04 19:01 UTC
i'd like to have the pdf.js viewer adhere to the theme i set in firefox. right now the gray tones of the background and toolbar do not match firefox at all

cheers

**Comment by timvandermeij** [comment] 2017-02-04 19:22
Closing as duplicate of #3528, which tracks theme support.

**Closed by timvandermeij** 2017-02-04 19:22 UTC
