### ISSUE TITLE
how do pdf.js support pinch and expand gesture?

### ISSUE THREAD

**Issue by geyuVito** [mozilla/pdf.js#9014] opened 2017-10-10 09:05 UTC
Attach (reccomened) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-10-10 09:13
Closing as duplicate of #2582.

**Closed by Snuffleupagus** 2017-10-10 09:13 UTC
