### ISSUE TITLE
Cannot display PDF on canvas with active CSP

### ISSUE THREAD

**Issue by dmsalex** [mozilla/pdf.js#9746] opened 2018-05-22 06:20 UTC
Attach (recommended) or Link to PDF file here:
[example.zip](https://github.com/mozilla/pdf.js/files/2025216/example.zip)

Configuration:
- Web browser and its version:
Mozilla Firefox 61.0b6 (64-Bit)
- Operating system and its version:
Windows 10 Version 1709 (Build 16299.431)
- PDF.js version:
1.9.426
- Is a browser extension:
No

Steps to reproduce the problem:
1. Download example [example.zip](https://github.com/mozilla/pdf.js/files/2025216/example.zip)
2. Open viewer/Index.htm

What is the expected behavior? (add screenshot)
Four pages from lorem.pdf with text and background image should be displayed.

What went wrong? (add screenshot)
Only shows first page with background image but all texts are missing.
If i deactivate the csp everythings works fine. The problem is i dont want to use style-src unsafe-inline. What can i do about it ?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2018-05-22 21:36
Closing since this looks like a duplicate of #8066.

**Closed by timvandermeij** 2018-05-22 21:36 UTC
