### ISSUE TITLE
Text annotation in hebrew is rendered in LTR mode

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14046] opened 2021-09-18 14:12 UTC
Attach (recommended) or Link to PDF file here:
[mytestfile.pdf](https://github.com/mozilla/pdf.js/files/7190033/mytestfile.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: linux debian

Steps to reproduce the problem:
1. Open the pdf  
2. Click on the yellow area

What is the expected behavior? (add screenshot)
The text layout should be RTL.

What went wrong? (add screenshot)
The text layout is LTR.

It works correctly in evince and in acrobat.
I added a `dir="rtl"` on the `p` element in using devtools and the rendering is the same as in acrobat.

**Comment by timvandermeij** [comment] 2021-09-19 17:14
Looking at the PDF file contents using https://brendandahl.github.io/pdf.js.utils/browser/, we should most likely use the `RC` field of the annotation since it contains `rtl` spans, which would make this a duplicate of #2966 I think?

**Comment by calixteman** [comment] 2021-09-20 09:02
I checked the contents of the `RC` field and they aren't exactly what we have in the rendered annotation.
In acrobat, they're used for the in the text editor for the annotation (I changed some colors in the xml and there wer no impact in the rendered annotation but just in the editor).

**Comment by timvandermeij** [comment] 2021-09-22 20:05
Ah, okay. I wonder what Acrobat uses then; the only related property I could find otherwise is the language property in one of the root nodes. The annotation itself doesn't seem to contain anything other than the `RC` property that indicates that it should be RTL, unless I missed something of course.

**Comment by raheemalzeeshan** [comment] 2021-09-23 06:16
Just for clarifying the issue what I have understand
Basically Hebrew languages start from **RIGHT TO LEFT _(RTL)_** but in **pdf.js** is to start from **LEFT TO RIGHT _(LTR)_**
Here there are some screenshot

![hebrew ltr](https://user-images.githubusercontent.com/48020482/134461909-6a4a9ed0-2285-4cdf-9e63-da2bf53462af.png)
![hebrew RTL](https://user-images.githubusercontent.com/48020482/134461912-354a0087-c56f-4f1e-9bbd-17ce5aac656e.png)

**Comment by calixteman** [comment] 2021-09-23 17:30
I'd say that they're using classical algorithms to guess what are the ltr/rtl parts in the text.
So we could try to see if we can use https://github.com/mozilla/pdf.js/blob/master/src/core/bidi.js which could help to fix this issue since almost all text is LTR.
For a text 50% in english and 50% in hebrew we would have to detect the different parts and either insert some LTR/RTL markers or generate some spans with a dir attribute.

**Comment by Snuffleupagus** [comment] 2021-09-24 10:33
> For a text 50% in english and 50% in hebrew we would have to detect the different parts and either insert some LTR/RTL markers or generate some spans with a dir attribute.

How common would such a case actually be in practice though? My guess is that it'd probably be quite rare.
Also, how does e.g. Adobe Reader handle the /Contents being an equal mix LTR and RTL locales?

Basically I cannot help wonder if we need to "complicate" the (initial) implementation all that much, or if we could simply use the `dir`-property that the `bidi`-function returns as-is and not worry about any edge-cases?

**Comment by calixteman** [comment] 2021-09-24 10:42
I fully agree with you: there are no need to over-complicate things because my guesses are the same as yours.

**Comment by Snuffleupagus** [comment] 2021-09-24 15:29
So, the `bidi` approach seems to work nicely for this case :-)
However, I've not yet run tests so I suppose that there may be some fallout that needs to be fixed; I'll assign this to myself and continue working on it during the weekend.

**Closed** 2021-09-25 10:37 UTC
Labels: 4-annotations
