### ISSUE TITLE
words broken up into letters

### ISSUE THREAD

**Issue by devcon14** [mozilla/pdf.js#4863] opened 2014-05-29 14:11 UTC
pdf.js seems to render text in blocks of a couple of letters within the browser.
If I view the same pdf within google drive preview then the text blocks seem to make more sense.

Is it possible to get a better text representation from the API within pdf.js?
The reason I want to do this is that I am writing a browser plugin for users to select and classify text for extraction.
pdf.js adds pdf to the list of documents that can be tagged.
But like this I can't see how to tokenize the text.

Only a few thousand of my samples are like this, so could this be because of the internal pdf structure?
I know little about the pdf format only html markup, so if anyone could point me in the right direction I'd really appreciate it and be happy to get involved.

**Comment by yurydelendik** [comment] 2015-11-06 19:09
Closing as duplicate of #1045

**Closed by yurydelendik** 2015-11-06 19:09 UTC
Labels: 4-text-selection
