### ISSUE TITLE
Safari font rendering errors

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#8376] opened 2017-05-04 09:38 UTC
Link to PDF file (or attach file here):
[CF-April-2017.pdf](https://github.com/mozilla/pdf.js/files/975693/CF-April-2017.pdf)

Configuration:
- Safari Version 10.1 (10603.1.30.0.34)
- OSX 10.10.5 (14F2315)

Using latest viewer at https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)
From Chrome:
![screen shot 2017-05-04 at 10 35 57](https://cloud.githubusercontent.com/assets/786238/25698189/c0e3fcbc-30b5-11e7-9319-16489ec8b0cd.png)

What went wrong? (add screenshot)
From Safari:
![screen shot 2017-05-04 at 10 35 34](https://cloud.githubusercontent.com/assets/786238/25698196/c86f5c9c-30b5-11e7-8924-28209ce06a77.png)
The font spacing and italics are incorrect.

May be the same as #8231 

Thanks,
Dan

**Comment by Snuffleupagus** [comment] 2017-05-04 09:50
Closing as duplicate of issue #8231.

**Closed by Snuffleupagus** 2017-05-04 09:50 UTC
