### ISSUE TITLE
Image is not rendered

### ISSUE THREAD

**Issue by saibotma** [mozilla/pdf.js#16643] opened 2023-07-05 19:57 UTC
Attach (recommended) or Link to PDF file here:
[C3FF697205724AB564E96E05DB6D1E9798BD9776-1.pdf](https://github.com/mozilla/pdf.js/files/11961432/C3FF697205724AB564E96E05DB6D1E9798BD9776-1.pdf)

Configuration:
- Web browser and its version: 114.0.1 (64-bit) Apple Silicon
- Operating system and its version: macOS 13.4 
- PDF.js version: Firefox built in
- Is a browser extension: Also not working in private window with extensions disabled

Steps to reproduce the problem:
1. Open the PDF in Firefox using the built-in PDF viewer

What is the expected behavior? (add screenshot)
There should be an image in the top right corner.
<img width="843" alt="Screenshot 2023-07-05 at 21 55 58" src="https://github.com/mozilla/pdf.js/assets/26022902/e0a27763-4b12-4c92-9e8d-60c71039051a">

What went wrong? (add screenshot)
There is no image.
<img width="1021" alt="Screenshot 2023-07-05 at 21 56 57" src="https://github.com/mozilla/pdf.js/assets/26022902/e77406bc-1e9d-4bb8-9e50-e04af997151e">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-07-05 20:07
Duplicate of #16038

**Closed by Snuffleupagus** 2023-07-05 20:07 UTC
