### ISSUE TITLE
Error Failed to fetch Using PDF.JS

### ISSUE THREAD

**Issue by teemer22** [mozilla/pdf.js#10875] opened 2019-05-31 02:38 UTC
I am encountering error "Failed to fetch" when calling PDF file from https://checkmateinvoice.blob.core.windows.net/invoices/test.pdf. Any suggestions for this issue? I already included my server to the origins list.

<img width="466" alt="3" src="https://user-images.githubusercontent.com/44570101/58678016-b95e3900-8390-11e9-8ce3-6b9d3be8e246.PNG">

**Comment by Snuffleupagus** [comment] 2019-05-31 08:07
Duplicate of #10870; please refrain from knowingly open duplicate issues.

**Closed** 2019-05-31 10:31 UTC
