### ISSUE TITLE
blurring of pdf on pinch to zoom 'only' on iOS based devices

### ISSUE THREAD

**Issue by kshantanu94** [mozilla/pdf.js#9983] opened 2018-08-17 10:53 UTC
PFA screenshots on both Android and iOS devices of pdfs rendered with pdf.js.

iOS - https://imgur.com/a/2KkPAdj
Android - https://imgur.com/a/UImRNab

As can be observed, on pinch to zoom iOS devices face a significant loss in sharpness while Android maintains the clarity. Is there a way around it?

**Comment by timvandermeij** [comment] 2019-12-27 14:10
Closing since this is a duplicate of #6419.

**Closed by timvandermeij** 2019-12-27 14:10 UTC
Labels: 1-other
