### ISSUE TITLE
Support touch events

### ISSUE THREAD

**Issue by vyv03354** [mozilla/pdf.js#3765] opened 2013-10-03 15:18 UTC
Currently pdf.js is disabled on Metrofox due to the lack of the touch support.
https://bugzilla.mozilla.org/show_bug.cgi?id=859579

**Comment by MickL** [comment] 2016-04-25 11:41
Any news on this? Especially pinch to zoom? (The PR is closed btw)

**Comment by Snuffleupagus** [comment] 2020-10-25 09:19
> Currently pdf.js is disabled on Metrofox due to the lack of the touch support.

Given that "Metrofox" is no longer a thing, and that touch-zooming is already tracked elsewhere; let's close this as a duplicate of issue #2582 instead.

**Closed** 2020-10-25 11:20 UTC
Labels: 1-viewer, 2-feature
