### ISSUE TITLE
Incorrect font rendering in single PDF

### ISSUE THREAD

**Issue by mdelorme** [mozilla/pdf.js#15440] opened 2022-09-15 08:02 UTC
Hi, 

Here is a link to a "problematic" pdf : https://arxiv.org/pdf/2209.06450.pdf

Configuration:
- Web browser and its version: Firefox, 104.0.2
- Operating system and its version: Ubuntu 22.04 LTS

What is the expected behavior?

![article2](https://user-images.githubusercontent.com/2743366/190349052-ef8c5709-6063-4f18-826d-4524586c55c4.png)

What went wrong? (add screenshot)

![article](https://user-images.githubusercontent.com/2743366/190348999-7a8232fc-0cfd-4a2c-b422-774dcd25a975.png)

I tried opening it with evince and okular and both render it correctly.

**Comment by Snuffleupagus** [comment] 2022-09-15 08:05
Duplicate of #13176

**Closed by Snuffleupagus** 2022-09-15 08:05 UTC
