### ISSUE TITLE
PDF with arrabic embeded in a form seem to be picking up the wrong font.

### ISSUE THREAD

**Issue by menver** [mozilla/pdf.js#11238] opened 2019-10-14 10:29 UTC
Attach (recommended) or Link to PDF file here:
PDF will be uploaded shortly

Configuration:
- Web browser and its version: Any
- Operating system and its version: Windows
- PDF.js version:  2.1.266 and latest
- Is a browser extension: No

Steps to reproduce the problem:
1.  Open PDF

What is the expected behavior? (add screenshot)
Notice the font/text in the form elements is wrong compared to other PDF viewers

**Comment by menver** [comment] 2019-10-14 10:31
May be related to https://github.com/mozilla/pdf.js/issues/11151 or 
https://github.com/mozilla/pdf.js/issues/7367

**Comment by timvandermeij** [comment] 2019-10-14 20:37
Closing since this is almost definitely a duplicate of those issues. We don't do anything with fonts inside the `AcroForm` dictionary yet, so this not working is expected since the AcroForms functionality is experimental. If we are allowed to use the PDF file as a test case, please do upload it since it allows us to make a regression test once we implement this feature. Thanks.

**Closed by timvandermeij** 2019-10-14 20:37 UTC

**Comment by nenad-sf** [comment] 2019-10-15 04:36
[FormCWResult.pdf](https://github.com/mozilla/pdf.js/files/3727369/FormCWResult.pdf)
Here is the sample file.
