### ISSUE TITLE
Support Thin Space

### ISSUE THREAD

**Issue by jasonabullard** [mozilla/pdf.js#13148] opened 2021-03-26 13:16 UTC
Request that support for [thin space](https://www.fileformat.info/info/unicode/char/2009/index.htm) be added. Currently, only regular spaces, tabs, and a few others are valid.  When a thin space is parsed, no space is actually added and words are combined together (i.e. ihavenospace).

Configuration:
NodeJS v12.6.1
PDF.js version: 2.6.347

Steps to reproduce:
- Create word document with some text
- Highlight a normal space and type 2009 then highlight 2009 and hit Ctrl + X
- Copy the newly created thin-space to other spots
- Print/save as PDF

Expected Outcome
```
[
  "I have regular spaces.",
  "I have thin spaces."
]
```

Actual Outcome
```
[
  "I have regular spaces.",
  " ",
  " ",
  "I",
  " ",
  "have",
  " ",
  "thin",
  " ",
  "s paces.",
  " "
]
```

[Test.pdf](https://github.com/mozilla/pdf.js/files/6212215/Test.pdf)

Code
```
const fs = require('fs');
const path = require('path');
const pdfjs = require('pdfjs-dist/es5/build/pdf');

const filePath = path.resolve(__dirname, 'files', 'Test.pdf');
const fileNameWithExt = path.basename(filePath);
const fileNameWithoutExt = fileNameWithExt.replace(path.extname(filePath), '');

async function parseDocument(src) {
  const doc = await pdfjs.getDocument(src).promise;

  for (let i = 1; i <= doc.numPages; i++) {
    const page = await doc.getPage(i);
    const content = await page.getTextContent();

    // output raw data
    fs.writeFileSync('raw.json', JSON.stringify(content));

    const pageFilePath = path.join(
      __dirname,
      'files',
      'out',
      `${fileNameWithoutExt}-page-${i}.json`,
    );

    const strContent = content.items.map((item) => item.str);

    fs.writeFileSync(pageFilePath, JSON.stringify(strContent));
  }
}
```

**Comment by Snuffleupagus** [comment] 2021-03-26 13:21
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue is not actionable/valid; especially the `Attach (recommended) or Link to PDF file here:`-part is *required* here.

> [pdf.js/src/core/core_utils.js](https://github.com/mozilla/pdf.js/blob/63471bcbbeee3fc1c6b1df988174640a124f097a/src/core/core_utils.js#L183-L185)

Furthermore, it's *very* unlikely that this particular code is relevant here; hence why you must provide all of the require information.

**Comment by typefish** [comment] 2021-03-26 19:59
So closing with no response means....

**Comment by timvandermeij** [comment] 2021-03-26 20:21
It was closed since the requested information was missing, but it has since been added, so we can reopen this.

**Comment by calixteman** [comment] 2021-12-11 16:26
From a text selection point of view, when I copy/paste the text in the pdf I get the exact same strings as in either Acrobat or Chrome (with some " " instead of "\u2009").
From an api point of view, I've no opinion on what we should do, the thin space is transformed into a normal space here:
https://github.com/mozilla/pdf.js/blob/d856ed93951b6674d8385167406bc0c36fa41f28/src/core/evaluator.js#L2621
and because of:
https://github.com/mozilla/pdf.js/blob/d856ed93951b6674d8385167406bc0c36fa41f28/src/core/unicode.js#L314

@Snuffleupagus, what do you think here ?

**Comment by Snuffleupagus** [comment] 2021-12-11 17:49
> From a text selection point of view, when I copy/paste the text in the pdf I get the exact same strings as in either Acrobat or Chrome (with some " " instead of "\u2009").

Yes, that seems reasonable since we *generally* replace arbitrary whitespace with standard spaces (i.e. `0x20`).

Looking at https://github.com/mozilla/pdf.js/issues/13148#issue-841949816 (under "Actual Outcome"), it *appears* (at least to me) that the issue isn't so much with the "thin spaces" themselves. Rather is seems that because of how the PDF document is constructed[1], with a bunch of font switching, we're not able to concatenate the individual text items in the `getTextContent` output.

This, to me, is basically a case of a particular broken PDF document and/or bad generator software; hence I'd lean towards closing as WONTFIX here.

---
[1] The page uses the following /Contents stream, where a *separate* font is being used for the offending spaces:
```
BT
/P <</MCID 0 >>BDC 
/TT0 1 Tf
-0.004 Tc 0.004 Tw 12 -0 0 12 72 709.08 Tm
[(I)9 ( h)-14 (av)-4 (e r)-11 (e)-10 (g)6 (u)-4 (l)-6 (ar)-1 ( s)-5 (p)-14 (aces)-5 (.)]TJ
0 Tc 0 Tw 8.66 0 Td
( )Tj
EMC 
/P <</MCID 1 >>BDC 
-8.66 -1.91 Td
( )Tj
EMC 
/P <</MCID 2 >>BDC 
0 -1.91 TD
(I)Tj
/C2_0 1 Tf
0.32 0 Td
<0BD7>Tj
/TT0 1 Tf
-0.004 Tc 0.004 Tw [(h)-14 (av)-4 (e)]TJ
/C2_0 1 Tf
0 Tc 0 Tw <0BD7>Tj
/TT0 1 Tf
0.002 Tc -0.002 Tw [(th)2 (in)]TJ
/C2_0 1 Tf
0 Tc 0 Tw 3.85 0 Td
<0BD7>Tj
/TT0 1 Tf
(s)Tj
-0.004 Tc 0.004 Tw 0.59 0 Td
[(p)-4 (ac)-10 (es)-5 (.)]TJ
0 Tc 0 Tw 2.48 0 Td
( )Tj
EMC 
ET
```

**Comment by Snuffleupagus** [comment] 2022-07-05 20:19
Closing as WONTFIX, for the reasons outlined in https://github.com/mozilla/pdf.js/issues/13148#issuecomment-991727745.

**Closed by Snuffleupagus** 2022-07-05 20:19 UTC
Labels: text-selection
