### ISSUE TITLE
Dotted line/rule missing parts of line

### ISSUE THREAD

**Issue by mikedanger** [mozilla/pdf.js#6999] opened 2016-02-16 16:35 UTC
Sorry if this has already been reported elsewhere, I'm not sure what the term for this type of line is, and my search didn't turn up anything. :S 

Link to PDF: http://demo.finalsite.com/supporttest1/uploaded/mike_test/ISZL_ApplicForm_2016-17_feb.pdf

Location in PDF: all pages

Screenshots:
In Firefox: http://fnlst.com/1dN1Q
In Chrome (correct appearance, note that there are no interruptions in the lines where you fill in your information): http://fnlst.com/QZ9q

Browser version: Firefox 44.0.2 http://fnlst.com/11FCu

Operating system: OS X 10.10.5 http://fnlst.com/13lzj

PDF.js version: 1.1.551 http://fnlst.com/nErj

JavaScript console warning/error messages:
Unknown pseudo-class or pseudo-element 'selection'.  Ruleset ignored due to bad selector. viewer.css:59:13
Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:151:21
Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:199:37
Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:214:21
Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:222:21
Unknown pseudo-class or pseudo-element 'selection'.  Ruleset ignored due to bad selector. viewer.css:1356:2
PDF 008862aa73194b928d1463b63859b1f8 [1.4 Adobe PDF Library 9.9 / Adobe InDesign CS5.5 (7.5.3)] (PDF.js: 1.1.551) viewer.js:6846:1

**Comment by timvandermeij** [comment] 2016-02-16 20:18
Renders fine for my using Windows 10 x64, Firefox 44.0.2 and the latest PDF.js development version. Could you try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html (the latest version of PDF.js, using the Open File button in the toolbar) and see if that works?

**Comment by yurydelendik** [comment] 2016-02-16 20:23
Looks like it's fixed in newer version of PDF.js. Regression window is wanted.

**Comment by mikedanger** [comment] 2016-02-16 20:52
@timvandermeij looks good in the latest version! http://fnlst.com/11frN

**Comment by timvandermeij** [comment] 2016-02-16 21:47
Good to know. Version 1.1.551 is reasonably old (current stable release is 1.3.91), so upgrading PDF.js will address the issue. Closing as resolved.

**Closed by timvandermeij** 2016-02-16 21:47 UTC
Labels: 4-information-requested
