### ISSUE TITLE
Text draws crazily

### ISSUE THREAD

**Issue by waddlesplash** [mozilla/pdf.js#2739] opened 2013-02-19 03:27 UTC
The text "Release 313 Graphics..." on the first page is not evenly spaced. It looks obviously wrong in pdf.js, much better in Adobe.

http://us.download.nvidia.com/Windows/314.07/314.07-win8-win7-winvista-desktop-release-notes.pdf

**Comment by informatorius** [comment] 2016-01-03 10:06
Still reproducable with every Nvidia driver document
http://us.download.nvidia.com/Windows/361.43/361.43-win10-win8-win7-winvista-desktop-release-notes.pdf
![nvidia_font_spacing_problem](https://cloud.githubusercontent.com/assets/6989214/12078242/18a94636-b20a-11e5-95d5-aa392e96e872.PNG)

**Comment by timvandermeij** [comment] 2018-12-23 12:36
Closing since this no longer happens, most likely after recent font fixes. Th letters are now evenly spaced.

**Closed by timvandermeij** 2018-12-23 12:36 UTC
Labels: 2-image-quality, 4-non-standard-fonts

**Comment by informatorius** [comment] 2018-12-30 18:34
Fixed in Firefox 64.0 64bit, Windows 7 64bit, Nvidia driver 391.35

**Comment by birdie-github** [comment] 2018-12-30 18:36
But what about Fedora/Linux in general?

On December 30, 2018 6:35:01 PM UTC, informatorius <notifications@github.com> wrote:
>Fixed in Firefox 64.0 64bit, Windows 7 64bit, Nvidia driver 391.35

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by timvandermeij** [comment] 2018-12-31 11:11
This PDF file looks good now on Arch Linux, i.e., it renders exactly the same in PDF.js for me as it does in Okular. Since the file does not embed its fonts, there is not much more we can do here.
