### ISSUE TITLE
Warning: TT: undefined function: 32  VM_Unknown:1

### ISSUE THREAD

**Issue by dotNetAthlete** [mozilla/pdf.js#10288] opened 2018-11-22 09:55 UTC
This browser error occurs in the debug console when running Angular 7 app in VS code.
Code:

`import { PDFDocumentProxy, PdfViewerComponent } from 'ng2-pdf-viewer';`

relevant link:
https://medium.com/factory-mind/angular-pdf-forms-fa72b15c3fbd

There is no support available on that link, though I would love to get it working in my project because it looks great.

Also if someone could explain what the 'ugly cast' contribution means in this line of code, I'd be happy to help, because that might be the source of the error!

`loadComplete(pdf: PDFDocumentProxy): void {

    for (let i = 1; i <= pdf.numPages; i++) {

      // track the current page...
      let currentPage = null;

      if (i == 2){ // temp dev solution...
        pdf.getPage(i).then(p => {
          currentPage = p;
          console.log('currentPage ', p);
          return p.getAnnotations();
  
        }).then(ann => {
  
          // ugly cast due to missing typescript definitions - please contribute to complete @types/pdfjs-dist
          const annotations = (<any>ann) as PDFAnnotationData[];
  
          annotations.filter(a => a.subtype === 'Widget') // get the form field annotation only
            .forEach(a => {
              // get the rectangle that represents the single field
              // and resize it according to the current DPI
              console.log('rectangle of field ', a);

              const fieldRect = currentPage.getViewport(this.dpiRatio).convertToViewportRectangle(a.rect);
  
              // add the corresponding input
              this.addInput(a, fieldRect);
            })
        });
      } 
    }
  }`

**Comment by Snuffleupagus** [comment] 2018-11-22 12:07
> This browser error occurs in the debug console when running Angular 7 app in VS code.
> Code:
> 
> `import { PDFDocumentProxy, PdfViewerComponent } from 'ng2-pdf-viewer';`

We (obviously) cannot provide support for third-party libraries that use/embed the PDF.js project in various ways, hence this issue is invalid; please contact the maintainer of the "ng2-pdf-viewer" project for support questions related to using it.

Furthermore, most (if not all) of the information requested https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md is missing in this issue. Also, note that as clearly explained in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, code snippets are *not* useful.

**Comment by dotNetAthlete** [comment] 2018-11-22 15:16
As pointed out, there is no project support available for that link !!!

I guess the reason it's so difficult to work with anything other than read-only PDFs is that Adobe have locked it down because they charge a fortune for anything other than the free adobe viewer for windows 10

**Comment by timvandermeij** [comment] 2018-11-22 21:50
Closing since this is a duplicate of #3768. In particular the comment at https://github.com/mozilla/pdf.js/issues/3768#issuecomment-36468349 is relevant here. Moreover, no PDF file is provided to reproduce the issue, as well as the other details from the issue template. If need be, you can get support for that external library at https://github.com/VadimDez/ng2-pdf-viewer.

**Closed by timvandermeij** 2018-11-22 21:50 UTC
