### ISSUE TITLE
Extra Empty Page that only exist when print the file to printer

### ISSUE THREAD

**Issue by shingl** [mozilla/pdf.js#10688] opened 2019-03-27 09:00 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: FireFox 38.0.1, 60.4.0
- Operating system and its version: Windows 7 (x86), Windows 10 (x64)
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html (online demo)
- Is a browser extension: Not sure. 

Steps to reproduce the problem:
1.  Use open function to open the online demo
2. Click the print icon to print ( Not select print to pdf)
3. Select a real printer to print the pdf
4. Disable "print on both side"
5. Print (Select print all, but not select the range)

What is the expected behavior? (add screenshot)
The number of printed pages should be the same as the pdf

What went wrong? (add screenshot)
1. The printer prints an extra blank page at the end.
2. The above problem does not exist when print to pdf file.
3. If we select the range to print (e.g.: page 1 to 1), the extra page will not be printed.

**Comment by timvandermeij** [comment] 2019-03-27 22:38
Closing since this is a duplicate of some other issues; see https://github.com/mozilla/pdf.js/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A4-printing+blank+.

**Closed by timvandermeij** 2019-03-27 22:38 UTC

**Comment by shingl** [comment] 2019-03-28 06:26
> 
> 
> Closing since this is a duplicate of some other issues; see https://github.com/mozilla/pdf.js/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A4-printing+blank+.

Sorry, I am not quite sure am i right, but i have read those cases before i post the issue, and found that it is a bit different between my case and those cases. They are:
1. It seems not a pdf file problem (e.g., the height is too high) as it occurs even my input file is in landscape.
2. In the provided demo link, I click print, there is no print preview. But I am quite sure that no extra blank page is added in the print process. And the print range also showing the file is only 1 page.
3. The problem is only occurred when it is printed to a **real** printer.

I afraid that I have missing some posts about this problem, so I would like to know whether this problem is solved or not?  Or this is not a bug, just can be solved by setting some parameters?

**Comment by timvandermeij** [comment] 2019-03-28 22:21
This is a know bug and as far as I can tell it should already be covered by the open bug reports.

**Comment by shingl** [comment] 2019-04-16 02:52
Thank you for your explanation.  However, I would like to know will this bug will be fixed in coming versions? A little bit updates on my problem. I found that the extra blank page problem seems only occur when the orientation of the document is landscape. I would like to know will it be any auto rotate solution to avoid it?

**Comment by timvandermeij** [comment] 2019-04-16 21:40
Auto-rotation is implemented, but last time I checked didn't work anymore. It's a good beginner bug tracked in #9297.
