### ISSUE TITLE
Poor text quality on lasted MS Edge

### ISSUE THREAD

**Issue by uniauto** [mozilla/pdf.js#15525] opened 2022-09-29 12:36 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Microsoft Edge v105
- Operating system and its version: MS Windows 11 PRO
- PDF.js version: 2.16.105
- Is a browser extension:

Steps to reproduce the problem:
1. Open Microsoft Edge.
2. Go to "Previous/Next example" in https://mozilla.github.io/pdf.js/examples/ 
3. Go to "Result" tab.

What is the expected behavior? (add screenshot)
<img width="201" alt="image" src="https://user-images.githubusercontent.com/106304773/193029273-ba650c6f-cd39-458f-ad72-e9a3341f51e8.png">

What went wrong? (add screenshot)
<img width="199" alt="image" src="https://user-images.githubusercontent.com/106304773/193029425-455616f9-c3d8-4485-a41f-c404e2818462.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Previous/Next example: https://mozilla.github.io/pdf.js/examples/

**Comment by Snuffleupagus** [comment] 2022-09-29 12:59
Duplicate of #15353

**Closed by Snuffleupagus** 2022-09-29 12:59 UTC

**Comment by StevenStPierre** [comment] 2022-11-10 21:39
@uniauto see the workaround proposed here https://github.com/mozilla/pdf.js/issues/15353
