### ISSUE TITLE
LESS or SASS for viewer.css?

### ISSUE THREAD

**Issue by SwartHack** [mozilla/pdf.js#9275] opened 2017-12-13 23:57 UTC
Was wondering if there are any LESS and/or SASS files for viewer.css?

There is a specific reason why I need it. I am "embedding" the pdf-viewer in an asynchronous container in my web-site. Your current .css clobbers many standard CSS naming conventions. Consider using "vendor" specific prefixes to isolate your styles. e.g. pdfjs-container-main or pdfjsContainerMain.

If no LESS or SASS files exists, I will create SASS file(s)from the existing generic viewer.css and share the results here. I will try to keep the viewer css names "as is" and isolate them using a wrapper of sorts.

Thanks for any feedback and insight. Cheers!

**Comment by Snuffleupagus** [comment] 2017-12-14 00:18
> Was wondering if there are any LESS and/or SASS files for viewer.css?

No such files exist in this repo. (Also, as mentioned in e.g. http://mozilla.github.io/pdf.js/getting_started/ and https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#from-examples, the default viewer isn't really intended to be used as-is in custom deployments.)

> Your current .css clobbers many standard CSS naming conventions. Consider using "vendor" specific prefixes to isolate your styles. e.g. pdfjs-container-main or pdfjsContainerMain.

This part sounds like a duplicate of issue #6706.

Closing as answered.

**Closed by Snuffleupagus** 2017-12-14 00:18 UTC
