### ISSUE TITLE
PDF displays white blocks and lines when rendering

### ISSUE THREAD

**Issue by jvoigts-crossway** [mozilla/pdf.js#13070] opened 2021-03-09 19:50 UTC
[pdfjs_white_cutouts_example.pdf](https://github.com/mozilla/pdf.js/files/6110994/pdfjs_white_cutouts_example.pdf)

Configuration:
- Web browser and its version: Mozilla Firefox 85.0.2
- Operating system and its version: macOS 10.14.6
- PDF.js version: Version builtin to Firefox
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open PDF in Firefox

What is the expected behavior? (add screenshot)

<img width="844" alt="Screen Shot 2021-03-09 at 1 47 17 PM" src="https://user-images.githubusercontent.com/14224900/110528638-fca91800-80dd-11eb-854f-33a77686611d.png">

What went wrong? (add screenshot)

Rendered PDF displays white boxes and lines.

<img width="826" alt="Screen Shot 2021-03-09 at 1 48 16 PM" src="https://user-images.githubusercontent.com/14224900/110528904-41cd4a00-80de-11eb-97cc-44dfbd7ba113.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by janpe2** [comment] 2021-03-11 14:13
This is an overprint issue. Acrobat Reader draws the file like PDF.js if I disable overprint preview (Edit > Preferences > Page Display. Set "Use Overprint Preview" to "Never"). This is a PDF/X file, so by default Acrobat Reader draws an overprint preview.

**Comment by Snuffleupagus** [comment] 2021-03-11 14:24
> This is an overprint issue.

In that case, this is probably a duplicate of #7360.

**Closed** 2021-03-12 19:56 UTC
Labels: 4-image-conversion
