### ISSUE TITLE
Pdf.js ES5 version contains non ES6 syntax(Arrow functions)

### ISSUE THREAD

**Issue by muhammetkaya** [mozilla/pdf.js#12974] opened 2021-02-09 12:34 UTC
Attach (recommended) or Link to PDF file here: [dummy.pdf](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)

Configuration:
- Web browser and its version: Internet Explorer
- Operating system and its version: Windows 10
- PDF.js version: 2.7.570 (es5) and 2.8.39 (es5) 
- Is a browser extension: No

Steps to reproduce the problem:
1. Just open the pdf file on Internet Explorer

What is the expected behavior? (add screenshot)
Showing the pdf file 
![image](https://user-images.githubusercontent.com/16261501/107363963-c3778b00-6ad2-11eb-8ea2-03fb3964be5c.png)

What went wrong? (add screenshot)
pdf.js contains arrow function which is not supported on Internet Explorer
![image](https://user-images.githubusercontent.com/16261501/107364347-3ed93c80-6ad3-11eb-9682-6f4176b5b040.png)

**Comment by Snuffleupagus** [comment] 2021-02-09 12:57
Duplicate of #12906

**Closed** 2021-02-09 22:35 UTC
