### ISSUE TITLE
Strings in Array from getTextContent() are split per character

### ISSUE THREAD

**Issue by codeofsumit** [mozilla/pdf.js#11904] opened 2020-05-14 11:51 UTC
Hi All,

Normally, `getTextContent()` puts strings together into an item of an array. I have a case now for two PDFs where every character is in a separate array item 🤔 . Is this a problem discovered before where you can push me into the right direction how to get more meaningful strings attached together?
Unfortunately, the PDF has personal financial data of a user so I can't provide it here but below are screenshots, showing the problem.

Configuration:
- Web browser and its version: Latest Chrome and Firefox (I think it happens in all browsers)
- Operating system and its version: (tested on mac)
- PDF.js version: `"pdfjs-dist": "^2.3.200"`

Steps to reproduce the problem:
Unfortunately, the PDF has personal financial data of a user so I can't provide it here.
This is how the text is extracted:
```js
import pdfjs from 'pdfjs-dist/build/pdf';
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry';

const parsePage = async page => {
  // extract content of page as an array of strings
  let textArr;

  const tc = await page.getTextContent();
  console.log(tc) // text items I'm talking about

  var out = [];
  for (let c of tc.items) {
    out.push(c.str.trim());
  }
  textArr = out.filter(i => i.length > 0);

  return textArr;
};

  const result = new Uint8Array(e.currentTarget.result);
  const pdf = await pdfjs.getDocument(result).promise;

  // get contents of all pages as array of textArrays
  const contents = [];
  const loopHelper = Array.from(Array(pdf.numPages)).entries();

  for (const [i] of loopHelper) {
    const pageNum = i + 1;
    const page = await pdf.getPage(pageNum);
    const textArr = await parsePage(page);

    contents.push(textArr);
  }
```

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/2399810/81930457-e3802980-95e8-11ea-859b-3290cf658a5c.png)
(Don't worry, that address in there is not valid)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/2399810/81930367-c9dee200-95e8-11ea-80f3-e2a4dc1e20cf.png)

Thanks for any advice!

**Comment by Snuffleupagus** [comment] 2020-05-14 12:02
> Unfortunately, the PDF has personal financial data of a user so I can't provide it here but below are screenshots, showing the problem.

Without access to a test-case, this issue unfortunately isn't actionable/valid (and unfortunately screen-shots aren't at all helpful for debugging these kind of issues).

This is almost guaranteed to be a duplicate of existing issues in https://github.com/mozilla/pdf.js/labels/4-text-selection, but it's simply impossible to pin-point the issue *exactly* given the current information.

**Comment by codeofsumit** [comment] 2020-05-14 12:05
@Snuffleupagus I can provide a PDF in private via email to test it if that helps? But I can't post it here.

**Comment by timvandermeij** [comment] 2020-05-15 09:17
We have many open issues for this at the link above, so let's close this one.

**Closed by timvandermeij** 2020-05-15 09:17 UTC
