### ISSUE TITLE
PDFJS not rendering majority of font in pdf document

### ISSUE THREAD

**Issue by DBQC** [mozilla/pdf.js#10257] opened 2018-11-14 17:45 UTC
Attach (recommended) or Link to PDF file here:
[7IM AAP Income Fund S Acc Prospectus.PDF](https://github.com/mozilla/pdf.js/files/2581810/7IM.AAP.Income.Fund.S.Acc.Prospectus.PDF)

Configuration:
- Web browser and its version: Chrome 70.0.3538.77 (Official Build) (64-bit) (cohort: Stable)
- Operating system and its version: Windows 10 pro Version 1803 (OS Build 17134.376)
- PDF.js version: Not sure where to find this? But our pdfjs is as of commit 45758dd2d5f6417053e88f98d89da18c4178df7b
- Is a browser extension: No

Steps to reproduce the problem:
1. Load attached document through PDFJS
2. Observer the majority of the document does not render

What is the expected behavior? (add screenshot)
The document should render properly. Here is a pdf of the same document that renders correctly in pdfjs (This was achieved by opening the erroring file in Microsoft word, saving to PDF and using that file in pdfjs)
[Resaved 7IM AAP Income Fund S Acc Prospectus.pdf](https://github.com/mozilla/pdf.js/files/2581836/Resaved.7IM.AAP.Income.Fund.S.Acc.Prospectus.pdf)

Here are screenshots of it rendering correctly:
![textrenderscorrectly](https://user-images.githubusercontent.com/16135252/48501086-3fbb8f00-e834-11e8-9bf4-19f87b74302a.PNG)
![textcorrect2](https://user-images.githubusercontent.com/16135252/48501092-41855280-e834-11e8-9891-043da401ceaf.PNG)

What went wrong? (add screenshot)
Tehse two screenshots should be equivelent to the two corret screenshots above
![textmissing](https://user-images.githubusercontent.com/16135252/48501282-d0926a80-e834-11e8-8ded-78b945b5647d.PNG)
![textmissing2](https://user-images.githubusercontent.com/16135252/48501357-f586dd80-e834-11e8-9868-4fd95c96b79c.PNG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Not sure how to add this, if you attempt to open the two attached files in pdfjs the first will error and the second will not.

I've looked at a few issues in the backlog an this could be related to: 
https://github.com/mozilla/pdf.js/issues/10084
and
https://github.com/mozilla/pdf.js/issues/10014
some fonts not rendered correctly(not showing up)

Let me know if any more details are needed.
The Bad pdf was created using Nitro Pro, unsure of the version as the pdf is from another company

**Comment by jamesdaily** [comment] 2019-01-16 17:18
I'm unable to reproduce the missing text you identified in your screenshots.  I'm using Chrome 71 on Windows 7 with the current demo viewer at https://mozilla.github.io/pdf.js/web/viewer.html and Adobe Acrobat Reader DC for comparison.

![image](https://user-images.githubusercontent.com/987389/51266128-5ee7b180-1988-11e9-85c1-ca2899771bb9.png)

**Comment by timvandermeij** [comment] 2019-01-16 21:49
Yes, both the original and the re-saved file work now. Closing as fixed.

**Closed by timvandermeij** 2019-01-16 21:49 UTC
Labels: 4-font-conversion

**Comment by IllidanS4** [comment] 2022-03-13 12:08
Maybe a wrong thread to post this, but if someone encounters this issue, setting `gfx.canvas.accelerated` to true in `about:config` fixed the issue.
