### ISSUE TITLE
Slow rendering of PDF with time spent in genericComposeSMask

### ISSUE THREAD

**Issue by mstange** [mozilla/pdf.js#17838] opened 2024-03-25 18:00 UTC
Attach PDF file here: [d2_cheat_sheet.pdf](https://github.com/mozilla/pdf.js/files/14747604/d2_cheat_sheet.pdf)

Configuration:

- Web browser and its version: Firefox Nightly 2024-03-25
- Operating system and its version: macOS
- PDF.js version: ?
- Is a browser extension: browser-native

Steps to reproduce the problem:
1. Load the PDF

What is the expected behavior? It should draw quickly.

What went wrong? It was slow.

Profile: https://share.firefox.dev/49axVfO

---

The profile shows that all the time is spent waiting for readback in `getImageData` for `genericComposeSMask`.
What does `genericComposeSMask` do? Which APIs would be needed in canvas to allow implementing it on the GPU?

**Comment by marco-c** [comment] 2024-03-25 19:15
This is probably the same as https://bugzilla.mozilla.org/show_bug.cgi?id=1874013.

**Comment by marco-c** [comment] 2024-03-25 19:25
See also https://github.com/mozilla/pdf.js/issues/14982#issuecomment-1466141810.

**Comment by Snuffleupagus** [comment] 2024-03-26 09:03
Duplicate of e.g. issue #17779?

**Comment by marco-c** [comment] 2024-03-26 09:18
Yes!

It seems to be frequent enough that we should prioritize it soon.

**Closed** 2024-05-01 14:12 UTC
Labels: performance, smask
