### ISSUE TITLE
Cannot retrieve pdf from the same folder

### ISSUE THREAD

**Issue by juliobguedes** [mozilla/pdf.js#10598] opened 2019-02-28 13:31 UTC
Attach (recommended) or Link to PDF file here:
[sample.pdf](https://github.com/mozilla/pdf.js/files/2915121/sample.pdf)

Configuration:
- Web browser and its version: Chrome 69.0.3497.100 64bits
- Operating system and its version: Debian GNU/Linux 9 (stretch) 64-bit
- PDF.js version: 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. Downloaded the dist folder
2. Added the pdf.min.js and pdf.worker.min.js to the libraries folder
3. Imported the pdf.min.js with `<script type="text/javascript" src="js/libs/pdf.min.js"></script>`
4. Accessed PDFJS using `const pdfjs = window['pdfjsLib']` PS: I also tried to load it with `window['pdfjs-dist/build/pdf']` as is in the [examples website](https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples) but the result is the same error 
5. In my display (async) function, I try to retrieve the document using `const myPdf = await pdfjs.getDocument('sample.pdf')` (my sample pdf is in the same folder than the lib)
6. An InvalidPDFException is thrown

What is the expected behavior? (add screenshot)
Its expected to retrieve the pdf from the folder for me to display it

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/23748073/53569634-62ec1f00-3b43-11e9-8f27-275e8b6d55c7.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-02-28 21:28
> Added the pdf.min.js and pdf.worker.min.js to the libraries folder

To rule out the possibility of errors in the `minified` build target, can you reproduce this issue when using the regular (non-minified) `pdf.js`/`pdf.worker.js` files as well?

If yes, that would suggest an error in your implementation which is *very* difficult to debug without access to a complete example; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> I try to retrieve the document using `const myPdf = await pdfjs.getDocument('sample.pdf')`

I don't think it should matter for the issue at hand, but please note that [`getDocument`](https://github.com/mozilla/pdf.js/blob/21d70b19c23c688a10d870e49dc9b58fff691610/src/display/api.js#L213-L226) doesn't return a Promise but a [`PDFDocumentLoadingTask`](https://github.com/mozilla/pdf.js/blob/21d70b19c23c688a10d870e49dc9b58fff691610/src/display/api.js#L421-L510) instance; hence what you really want here is something like this:
`const myPdf = await pdfjs.getDocument('sample.pdf').promise;`

**Comment by juliobguedes** [comment] 2019-02-28 21:36
Since I am already at home and have no access to the code, I'll try what you suggested tomorrow as soon as I can (probably around 5AM UTC) and I'll get back here with more content. Thanks for the quick response, @Snuffleupagus

**Comment by juliobguedes** [comment] 2019-03-06 19:55
@Snuffleupagus @timvandermeij I could only try again today, sorry for that. I've used the "not minified version" of pdfjs and still it would not display the page of the pdf... When I tried to use the pdfjs using `<script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>` to import, it was correctly displayed. Maybe a problem during the generation of the [dist](https://mozilla.github.io/pdf.js/getting_started/#download)?

**Comment by Snuffleupagus** [comment] 2019-03-07 10:20
> I've used the "not minified version" of pdfjs and still it would not display the page of the pdf...

That would, at least for now, point to an issue with your implementation; see https://github.com/mozilla/pdf.js/issues/10598#issuecomment-468445386 which clearly outlines the next steps (i.e. provide a *complete* and runnable example) you'll need to take in order for anyone to provide further assistance here.

**Comment by timvandermeij** [comment] 2019-03-08 21:44
Closing until a runnable example is provided since everything points at this being an implementation defect.

**Closed by timvandermeij** 2019-03-08 21:44 UTC
Labels: 1-other
