### ISSUE TITLE
Update the npm pdfjs-dist to use most recent webpack

### ISSUE THREAD

**Issue by jdell64** [mozilla/pdf.js#8975] opened 2017-09-29 14:12 UTC
my issue is more with `pdfjs-dist@1.9.604` but there is no issues tab over there.

The most recent version of webpack is 3.x and that uses `webpack@>=0.9 <2 || ^2.1.0-beta || ^2.2.0`. Can this be updated? 

Configuration:
- N/A, but running an angular 2 application, using `pdfjs-dist@1.9.604` 

Steps to reproduce the problem:
1. add `"webpack": "^3.6.0"` to `devDependencies` and `"pdfjs-dist": "^1.9.604",` to your dependencies
2.` npm install`

**Comment by jdell64** [comment] 2017-09-29 14:15
Or maybe a better thing to ask is, if I install webpack 3.6, can I safely use pdfjs-dist and ignore this warning?

```
npm WARN worker-loader@0.8.1 requires a peer of webpack@>=0.9 <2 || ^2.1.0-beta || ^2.2.0 but none was installed.
```

**Comment by Snuffleupagus** [comment] 2017-09-29 14:21
Based on https://github.com/mozilla/pdf.js/issues/8975#issuecomment-333138197, closing as duplicate of #8970.

**Closed by Snuffleupagus** 2017-09-29 14:21 UTC
