### ISSUE TITLE
Safari does not load Scanned PDF

### ISSUE THREAD

**Issue by KeiBontakun** [mozilla/pdf.js#10977] opened 2019-07-16 04:20 UTC
Safari (PC browser)  is very very slow at loading scanned PDFs.
Affected configuration is Safari on Mac
Unaffected configuration: Chrome, Firefox on Mac, Windows with major browsers.

Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
Safari 11.2

- Operating system and its version:
OS X 10.11.6

- PDF.js version:
latest on demo site

- Is a browser extension:
no

Steps to reproduce the problem:
1. Upload attached PDF to the demo page.
https://mozilla.github.io/pdf.js/web/viewer.html
[ScannedPDFcolor.pdf](https://github.com/mozilla/pdf.js/files/3395154/ScannedPDFcolor.pdf)

What is the expected behavior? (add screenshot)
Show the pdf like this. 
![2019-07-16 125102](https://user-images.githubusercontent.com/3262436/61264874-02dfd780-a7c9-11e9-8f76-f2f845f9d34e.jpg)

What went wrong? (add screenshot)
Blank page with loading icon shows, takes 10 minutes to load one page.

![screenshot](https://user-images.githubusercontent.com/3262436/61265382-ddec6400-a7ca-11e9-9f4d-27a7e59b872a.jpg)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): no. (Hosted on mozilla.github.io)

**Comment by timvandermeij** [comment] 2019-07-16 20:28
I cannot reproduce this at all using Firefox on Linux, so I share your thought about this being Safari-specific. I'm not sure if there is much we can do here since it looks like a browser bug instead. Perhaps it's good to also file an issue with the Safari developers.

**Comment by KeiBontakun** [comment] 2019-07-17 06:53
Thanks for reply, I understand it is considered to be Safari's issue.
I'll look for the way to contact Safari support.

**Comment by timvandermeij** [comment] 2019-07-17 20:46
Closing since I don't think we can do anything about this. If it turns out there is something that we can do on the PDF.js side, we can always reopen.

**Closed by timvandermeij** 2019-07-17 20:46 UTC
Labels: 1-other, 2-performance, 3-upstream, 4-safari-specific

**Comment by KeiBontakun** [comment] 2020-02-04 04:09
P.S. Our engineer made a detailed benchmark and found Safari has performance issue with window.postMessage method when message is a large array object. It takes greater time compared to Chrome or Firefox.
I reported that to Apple 6 month ago and waiting...
