### ISSUE TITLE
QR code present in the pdf file is not clearly visible (blurred) when opened in Mozilla Firefox 87.0 (64-bit)

### ISSUE THREAD

**Issue by prmahima** [mozilla/pdf.js#13362] opened 2021-05-11 04:08 UTC
Attach (recommended) or Link to PDF file here:
The PDF file is attached in the comment section.

Configuration:
- Web browser and its version: Mozilla Firefox 87.0 (64-bit)
- Operating system and its version: Windows (Not specific to OS)
- PDF.js version: 2.7.570
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the pdf file using pdf.js viewer.
2. Notice the QR code present in the pdf file is not clearly visible, it is blurred.

What is the expected behavior? (add screenshot)
The QR code present in the pdf file renders sharply and clearly on Google Chrome (Version 90.0.4430.72 (Official Build) (64-bit))

What went wrong? (add screenshot)
The QR code present in the pdf file is not rendered clearly, it is blurred.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by prmahima** [comment] 2021-05-11 05:51
[](url)

**Comment by Snuffleupagus** [comment] 2021-05-11 07:10
> Attach (recommended) or Link to PDF file here:
> The PDF file is attached in the comment section.

Please save everyone's time by actually following the ISSUE_TEMPLATE and *directly attaching* the PDF document to the initial post *immediately* when opening an issue; as-is this issue was opened three hours ago but is still not actionable/valid.

Please keep in mind that this is an open-source *bug tracker*, frequented by many volunteers, rather than paid tech-support.

**Comment by prmahima** [comment] 2021-05-11 07:32
> > Attach (recommended) or Link to PDF file here:
> > The PDF file is attached in the comment section.
> 
> Please save everyone's time by actually following the ISSUE_TEMPLATE and _directly attaching_ the PDF document to the initial post _immediately_ when opening an issue; as-is this issue was opened three hours ago but is still not actionable/valid.
> 
> Please keep in mind that this is an open-source _bug tracker_, frequented by many volunteers, rather than paid tech-support.

Sorry for the delay. Please find the PDF file attached by janakarajp in the comment.

**Comment by THausherr** [comment] 2021-05-11 10:22
Duplicate of #4706 ?

**Comment by timvandermeij** [comment] 2021-05-12 18:06
Closing since this is most likely indeed a duplicate.

**Closed by timvandermeij** 2021-05-12 18:06 UTC
