### ISSUE TITLE
Thin box around graphics is getting displayed

### ISSUE THREAD

**Issue by gsampath127** [mozilla/pdf.js#8965] opened 2017-09-28 18:16 UTC
Link to PDF file (or attach file here):
http://fundcompli-stage.rightprospectus.com/documents/TIAACREFVA/TIAA_REA_pro.pdf

Configuration:
Web browser and its version: all browsers
Operating system and its version: latest
PDF.js version: latest
Is an extension: NA

Steps to reproduce the problem:
1. Open PDF file ( http://fundcompli-stage.rightprospectus.com/documents/TIAACREFVA/TIAA_REA_pro.pdf
) in Pdf Js Viewer.
Issue can be seen when we open PDF here - https://mozilla.github.io/pdf.js/web/viewer.html
2. Thin box around graphics is getting displayed as shown in the screen shot
3. Issue can be seen on pages 2, 103, 108, 113, 118, 122, 127, 132, 137, 142 and last page.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/12858790/30982847-ab82dd88-a456-11e7-80db-5849e94ae0bd.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/12858790/30983235-ce7af75c-a457-11e7-83b1-2a34da302b5d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Issue can be seen when we open PDF here - https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by THausherr** [comment] 2017-10-05 11:02
I remember it happened last week, but this week it doesn't happen any more... (FF 56.0) I also remember that page 2 had a content stream with 8 parts and now only one... has the file been changed?

**Comment by timvandermeij** [comment] 2017-10-05 20:42
This particular PDF file works for me too. Since we cannot reproduce the issue, I'm closing this one, but do note that we have many similar issues still open for this, for example #4860. Hence, I think this is also a duplicate of those.

**Closed by timvandermeij** 2017-10-05 20:42 UTC
Labels: 4-image-conversion

**Comment by janpe2** [comment] 2017-10-10 13:52
> has the file been changed?

Indeed, the linked file has been changed. I downloaded the PDF early last week and it still has the problem. 

Here is the original page 2: 
[issue8965_p2.pdf](https://github.com/mozilla/pdf.js/files/1372107/issue8965_p2.pdf)

Here is a reduced version: 
[issue8965_p2_reduced.pdf](https://github.com/mozilla/pdf.js/files/1372113/issue8965_p2_reduced.pdf)

This is the problematic stream fragment:

```
0 g
1 0 0 1 236.75 579.046001 cm
0 0 m
121.89 0 l
121.89 -35.036 l
0 -35.036 l
f*
1 g
0 0 m
121.89 0 l
121.89 -35.036 l
0 -35.036 l
f*
```

The same rectangular path is first filled with black and then with white. I agree, this issue is very similar to #4860.
