### ISSUE TITLE
Rename default branch in the repository

### ISSUE THREAD

**Issue by flodolo** [mozilla/pdf.js#18847] opened 2024-10-04 06:22 UTC
Just noticed that the repository is still using `master` as the default branch. Might be worth updating it at some point?
Renaming in GitHub is straightforward, but it might get trickier with external CI dependencies.

Not sure if this was considered already, in case feel free to close.

**Comment by Snuffleupagus** [comment] 2024-10-04 06:29
Duplicate of #14263

**Closed by Snuffleupagus** 2024-10-04 06:29 UTC
