### ISSUE TITLE
Did not render unembedd font `SimSun` correctly

### ISSUE THREAD

**Issue by axetroy** [mozilla/pdf.js#16873] opened 2023-08-25 02:29 UTC
Attach (recommended) or Link to PDF file here: [test.pdf](https://github.com/mozilla/pdf.js/files/12434903/test.pdf)

Configuration:
- Web browser and its version: Firefox  117
- Operating system and its version: macOS
- PDF.js version: 3.5.141 - 3.9
- Is a browser extension: no

Steps to reproduce the problem:
1. Upload the file to [mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html) 
2. PDF are not rendered correctly

What is the expected behavior? (add screenshot)

![截屏2023-08-25 09 57 23](https://github.com/mozilla/pdf.js/assets/9758711/9183d9e3-c749-4b04-8cf7-ca8ea6250c24)

Chrome/Edge can render it correct.

and here is font properties:

![截屏2023-08-25 10 01 09](https://github.com/mozilla/pdf.js/assets/9758711/97e93ab7-d00c-4d8a-bb11-5a748afaee05)

What went wrong? (add screenshot)

![截屏2023-08-25 09 56 25](https://github.com/mozilla/pdf.js/assets/9758711/477ef1a9-45ec-49c5-8580-aab5225bea90)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by axetroy** [comment] 2023-08-25 02:35
Is there a way to resolve it via embed a font in pdf viewer?

I search issue and wiki can't found it.

**Comment by Snuffleupagus** [comment] 2023-08-25 06:30
Unfortunately your PDF document is *corrupt*, since it uses a non-standard font but doesn't embed it.

This is effectively a duplicate of e.g. issue #16606, please see https://github.com/mozilla/pdf.js/issues/16606#issuecomment-1610056287 for a way to "fix" your PDF document.

**Closed by Snuffleupagus** 2023-08-25 06:30 UTC

**Comment by axetroy** [comment] 2023-08-25 07:27
Tanks for you help, and I try it out that you memtion for fix PDF, but it doesn't working for this file.

```diff
// A simple script to fix the broken fonts in PDF files generated by S22PDF.

if (scriptArgs.length != 2) {
	print("usage: mutool run fix-s22pdf.js input.pdf output.pdf");
	quit();
}

var doc = Document.openDocument(scriptArgs[0]);

var font = new Font("zh-Hans");
var song = doc.addCJKFont(font, "zh-Hans", "H", "serif");
var heiti = doc.addCJKFont(font, "zh-Hans", "H", "sans-serif");
song.Encoding = 'GBK-EUC-H';
heiti.Encoding = 'GBK-EUC-H';

var MAP = {
	"/#CB#CE#CC#E5": song, // SimSun
	"/#BA#DA#CC#E5": heiti, // SimHei
	"/#BF#AC#CC#E5_GB2312": song, // SimKai
	"/#B7#C2#CB#CE_GB2312": heiti, // SimFang
	"/#C1#A5#CA#E9": song, // SimLi
+  '/SimSun': song,
+	'/NDMVTY+SimSun': song
}

var i, n = doc.countPages();
for (i = 0; i < n; ++i) {
	var fonts = doc.findPage(i).Resources.Font;
	if (fonts) {
		fonts.forEach(function (font, name) {
			if (font.BaseFont in MAP && font.Encoding == 'WinAnsiEncoding')
				fonts[name] = MAP[font.BaseFont];
		});
	}
}

doc.save(scriptArgs[1]);
```
