### ISSUE TITLE
Multimedia 'home' links created in Indesign fail

### ISSUE THREAD

**Issue by drizzdo** [mozilla/pdf.js#10762] opened 2019-04-24 13:01 UTC
windows 10 Chrome

We have embedded PDF.js as PDF reader on our website. In documents where we have added multimedia elements for navigation (using Adobe/Indesign), the multimedia / hyperlinks elements for 'Home' 'Previous' and 'next' are not working (clicking results in no response while 'home' should point to table of content. 

see https://resources.norrag.org/pdf/view/viewer.html?file=https://resources.norrag.org/storage/documents/nqvqcvRU7rlA4hf1KvTI9WKwTVYD2HnhoSa57QsX.pdf

**Comment by Snuffleupagus** [comment] 2019-04-24 13:36
> We have embedded PDF.js as PDF reader on our website.

Please keep https://mozilla.github.io/pdf.js/getting_started/ in mind:
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. *However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.*

Furthermore, it appears that you're using an older (`1.9.426`) and no longer supported version of the PDF.js library; please find the latest releases at https://github.com/mozilla/pdf.js/releases

---

The actual console output, in an up-to-date version of PDF.js, is:
> PDF 05f1bf4867bc794795a6f545b13e88bd [1.7 Adobe PDF Library 15.0 / Adobe InDesign 14.0 (Windows)] (PDF.js: 2.2.154)
> Warning: Push buttons without action dictionaries are not supported

**Comment by drizzdo** [comment] 2019-04-24 14:49
thanks I have informed the developers

**Comment by timvandermeij** [comment] 2019-04-24 21:36
Closing since this is then a duplicate of #9776.

**Closed by timvandermeij** 2019-04-24 21:36 UTC
