### ISSUE TITLE
System font name is not interpreted properly

### ISSUE THREAD

**Issue by xdenser** [mozilla/pdf.js#10144] opened 2018-10-09 13:49 UTC
[ABD_13DE586500008657E5.pdf](https://github.com/mozilla/pdf.js/files/2460586/ABD_13DE586500008657E5.pdf)

Configuration:
- Web browser and its version: does not depend on browser 
- Operating system and its version: Windows 10
- PDF.js version: current from https://mozilla.github.io/pdf.js/web/viewer.htm
- Is a browser extension: no

What is the expected behavior? 
![image](https://user-images.githubusercontent.com/523984/46673145-69501d80-cbd9-11e8-8d66-853b8a5d1664.png)

What went wrong? 
![image](https://user-images.githubusercontent.com/523984/46673158-6d7c3b00-cbd9-11e8-854c-db5fdb60cb4e.png)

Barcode is not rendered properly. The font is not embedded(but installed locally), font name is  'Code-128'. Pdfjs by some reason uses wrong font name 'Code'. I have variant of the same document with the same font embedded - there it works properly. With svg renderer when I replace font name  (Code to Code-128) by dev tools in the svg dom - it is also displayed ok.

**Comment by timvandermeij** [comment] 2020-05-24 14:12
You should always embed fonts in PDF files. If you don't, there is a big risk that the file will not be rendered consistently everywhere.

My guess is that the font name change happens because of https://github.com/mozilla/pdf.js/blob/a13db5d91ae08f4d164fe75fb6f22a4eeab9e960/src/core/fonts.js#L1425. I don't know enough of the code to know why that is done unfortunately, but maybe this initial debugging helps to find the root cause here.

**Comment by Snuffleupagus** [comment] 2021-09-02 08:21
Unfortunately this is a bug in the PDF document *itself*, rather than the PDF.js library, since all non-standard fonts should *always* be embedded into the PDF document in order to guarantee that it renders correctly in all environments.

Furthermore, please note that with the PDF.js library being a web-application it means that we cannot just load locally available fonts either; all-in-all closing as INVALID since it's a particular PDF document that's at fault here.

**Closed by Snuffleupagus** 2021-09-02 08:21 UTC
Labels: 4-font-conversion
