### ISSUE TITLE
PDF print is not rendering the document second time on safari browsers

### ISSUE THREAD

**Issue by eparirishit** [mozilla/pdf.js#13562] opened 2021-06-15 07:45 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari / 14.0.3
- Operating system and its version: BigSur
- PDF.js version: Latest
- Is a browser extension: No

Steps to reproduce the problem:
1. Navigate to the demo link - https://mozilla.github.io/pdf.js/web/viewer.html
2. Click on print 
3. The print renders the exact 14 pages 
4. Cancel the operation and click on print for the second time
5. A pop-up comes up asking your permission to print/ cancel
6. Click on print, rather than showing the 14 pages it shows 3 blank pages.

I am trying to skin on top of the default viewer and our team supports safari browser while implementation we came across this issue. I observed that during the second time when the pop-up is displayed the "_data-pdfjsprinting_" attribute is getting destroyed and it is unable to render the pages as expected.

What is the expected behavior? (add screenshot)
It should show the exact 14 pages as it did for the first time

![image](https://user-images.githubusercontent.com/9528214/122013180-89e5c200-cddb-11eb-8009-f5f419d6c77b.png)

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/9528214/122013252-9f5aec00-cddb-11eb-9c59-01b0e6eb9c03.png)

![image](https://user-images.githubusercontent.com/9528214/122013306-ada90800-cddb-11eb-979c-b13c1c5cefa6.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): NA

**Comment by Snuffleupagus** [comment] 2021-06-15 08:08
Duplicate of #7597

**Comment by Snuffleupagus** [comment] 2021-06-15 08:10
Looks similar enough to issue #7597, hence closing as such.
Please note that the web platform unfortunately has quite limited support for controlling printing, and that Safari isn't the main focus of development in the PDF.js library.

Duplicate of #7597

**Closed by Snuffleupagus** 2021-06-15 08:10 UTC

**Comment by Snuffleupagus** [comment] 2021-06-15 08:12
Duplicate of #7597, since this issue looks similar enough.

Please note that the web platform unfortunately has quite limited support for controlling printing, and that Safari isn't the main focus of development in the PDF.js library.

**Comment by eparirishit** [comment] 2021-06-16 08:04
@Snuffleupagus, I think the issue I raised looks similar to #9578.
