### ISSUE TITLE
Unimplemented annotation type (Widget signature)

### ISSUE THREAD

**Issue by JasnaPaka** [mozilla/pdf.js#4202] opened 2014-01-27 08:32 UTC
When I try to show this almost empty document I see info message that this pdf document can be showed in a wrong way. I use latest Firefox Nightly on Windows.

Document for test:
http://www.jasnapaka.com/bugs/pdf-js-pdf-test.pdf

Console output:
"PDF e7bebed68f057fccbb46e62786e65d2 [1.4 iText 2.1.7 by 1T3XT / -](PDF.js: 0.8.759)" viewer.js:2601
"Warning: AcroForm/XFA is not supported" viewer.js:2616
"Warning: TODO: unimplemented annotation type: Widget signature" pdf.js:198
"Warning: TODO: unimplemented annotation type: Widget"

**Comment by luozt** [comment] 2016-09-07 03:10
I also encountered this problem... I added the signature by wacom device and it produced a pdf with signature. However the pdf viewer of Mozilla Firefox did not show the signature when opening the pdf. And the chrome supports pdf with signature.

**Comment by rmhrisk** [comment] 2017-11-29 04:23
We have implemented a digital signature solution based on PKIjs and PDFjs that is capable of verifying digital signatures. You can see an example of it viewing the US Digital Signature law [here](https://manage.hancock.ink/document?url=https://peculiarventures.github.io/ExamplePDFs/signed/BILLS-106s761enr.pdf).

The viewer currently trusts the CAs on the eIDAS Trust List as well the Mozilla trusted S/MIME issuers. 

If you encounter any issues email me at ryan@peculiarventures.com with sample files if any.

**Comment by timvandermeij** [comment] 2020-09-06 17:32
Closing since this is a duplicate of #1076.

**Closed by timvandermeij** 2020-09-06 17:32 UTC
Labels: 4-annotations, 4-digital-signature
