### ISSUE TITLE
image is distorted - showing as half circle

### ISSUE THREAD

**Issue by banjahman** [mozilla/pdf.js#8446] opened 2017-05-25 13:54 UTC
Link to PDF file (or attach file here):
https://content.highmarkprc.com/Files/EducationManuals/ProviderTraining/fdr-medicare-general-compliance-training.pdf

Configuration:
- Web browser and its version: Chrome 58.0.3029.110 (64-bit)
- Operating system and its version: Windows 7
- PDF.js version: 1.8.384
- Is an extension: Yes/No

Steps to reproduce the problem:
1. View PDF in Acrobat
2. View PDF in PDF.js viewer

What is the expected behavior? (add screenshot)
Page 1: Should have a blue background covering the page (view in Acrobat)

What went wrong? (add screenshot)
Page 1: Blue background is being rendered as a half circle (view in Viewer)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://dev.highmarkprc.com/pdfviewer/web/viewer.html?file=ViewPdf.aspx%3Furl%3Dhttps%3A%2F%2Fcontent.highmarkprc.com%2FFiles%2FEducationManuals%2FProviderTraining%2Ffdr-medicare-general-compliance-training.pdf

**Comment by Snuffleupagus** [comment] 2017-05-25 14:45
This looks like a duplicate of issue #6183.

**Comment by Snuffleupagus** [comment] 2017-05-28 15:32
Closing as duplicate of issue #6183.

**Closed by Snuffleupagus** 2017-05-28 15:32 UTC
Labels: 4-image-conversion
