### ISSUE TITLE
Some email-links (mailto:-anchor) cannot be clicked in pdf.js viewers, while they are 'clickable' in other viewers (Chrome/Edge/Acrobat)

### ISSUE THREAD

**Issue by kad-rothul** [mozilla/pdf.js#18150] opened 2024-05-23 06:57 UTC
Problem, see [https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2342](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2342)

Attach (recommended) or Link to PDF file here:
I cannot share the PDF unfortunately due to confidential information

Configuration:
- Web browser and its version: Firefox 126.0
- Operating system and its version: Windows 10
- PDF.js version: 4.1
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF in either Firefox or https://mozilla.github.io/pdf.js/web/viewer.html
2. The emails in the table seem to be clickable, try clicking om them
3. Nothing happens when clicking

What is the expected behavior? (add screenshot)
When clicking, a mailto:-anchor should redirect the user to a email program. But the email links are not clickable in these specific viewers.

What went wrong? (add screenshot)
I cannot share a PDF at this point, but the problem seems to lie with PDF viewers using pdf.js, like Firefox and the ngx-extended-pdf-viewer I use in my application. The PDF has email links, but these do not work in these viewers, while they do work in Edge/Chrome/Acrobat. The PDF is generated and includes a table with emails that each have an anchor with the email prefixed with mailto:. The anchors work in other PDF viewers.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
At this point, I do not have a viewer with PDF (working on it). I first mentioned this issue at [https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2342](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2342)

I am looking for a way to make the emails clickable, as they only fail in pdf.js viewers. Is this a known issue by pdf.js, or does pdf.js have another method of creating anchors/links that causes problems with my PDF?

**Comment by Snuffleupagus** [comment] 2024-05-23 07:52
Duplicate of #3172, which is a best guess given the lack of *crucial* details.

**Closed by Snuffleupagus** 2024-05-23 07:52 UTC
