### ISSUE TITLE
Math rendering problems

### ISSUE THREAD

**Issue by marozols** [mozilla/pdf.js#8224] opened 2017-04-01 10:34 UTC
PDF.js often has trouble rendering mathematical expressions in PDF documents that are compiled from LaTeX. Particularly affected are summation signs (`\sum`), square roots (`\sqrt`), tensor products (`\otimes`), and brackets (`\langle`, `\rangle`, `(`, `)` etc.). They are often stretched vertically way too much. This effect is diminished if one zooms in sufficiently. This problem is quite pervasive and it seems to affect a large fraction of PDF files on the arXiv repository. Below are several examples from a [document](https://arxiv.org/pdf/1703.08346.pdf) where the problem is particularly noticeable.

Link to PDF file (or attach file here): https://arxiv.org/pdf/1703.08346.pdf

Configuration:
- Web browser and its version: Firefox 52.0.1 (64-bit)
- Operating system and its version: Linux Mint 18.1 Cinnamon 64-bit
- PDF.js version: 1.6.315
- Is an extension: no

Steps to reproduce the problem:
1. Open the [document](https://arxiv.org/pdf/1703.08346.pdf)
2. Set zoom to 100% or similar and scroll to pages 12, 13, 16, 22.

What is the expected behavior? (add screenshot)

**Page 12:**
![bug1](https://cloud.githubusercontent.com/assets/11517467/24577832/7d025a86-16cd-11e7-86f3-b45eb5742061.png)

**Page 13:**
![bug3](https://cloud.githubusercontent.com/assets/11517467/24577845/cb9266e6-16cd-11e7-90d8-ee85870fece1.png)

**Page 16:**
![bug2](https://cloud.githubusercontent.com/assets/11517467/24577833/80132f34-16cd-11e7-8193-9a7f52d0be15.png)

**Page 22:**
![bug4](https://cloud.githubusercontent.com/assets/11517467/24577847/cda8d4a6-16cd-11e7-9ad1-fba96b6c2878.png)

What went wrong? (add screenshot)

Several mathematical symbols are stretched vertically.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
I'm using the default viewer in Firefox.

**Comment by Snuffleupagus** [comment] 2017-04-01 10:49
From the information provided, I believe that this is a duplicate of (the fixed) issue #2594.

> PDF.js version: 1.6.315

This issue should already be fixed by PR #7705, but please note that the patch is *only* included in PDF.js versions of `1.6.380` and above.

@marozols Please try downloading the file and opening it (using the "Open file" button on the right-hand side of the toolbar) with https://mozilla.github.io/pdf.js/web/viewer.html. Does the file render correctly there?

**Comment by marozols** [comment] 2017-04-01 12:40
It renders just fine with the latest version of PDF.js. Too bad that Firefox doesn't ship the latest version.

**Comment by Snuffleupagus** [comment] 2017-04-01 13:31
> It renders just fine with the latest version of PDF.js.

In that case, I'm closing this as duplicate of issue #2594.

> Too bad that Firefox doesn't ship the latest version.

It's included in Firefox 53, since it was part of [bug 1323915](https://bugzilla.mozilla.org/show_bug.cgi?id=1323915).

**Closed by Snuffleupagus** 2017-04-01 13:31 UTC
Labels: 4-information-requested
