### ISSUE TITLE
White, horizontal lines appearing between images

### ISSUE THREAD

**Issue by KazaHesto** [mozilla/pdf.js#16696] opened 2023-07-15 17:22 UTC
Attach (recommended) or Link to PDF file here:
https://www.abcb.gov.au/sites/default/files/resources/2022/Gutter-downpipe-provisions-for-housing.pdf

Configuration:
- Web browser and its version: Firefox 117.0a1 (2023-07-15) (64-bit)
- Operating system and its version: Windows 11 Preview 23493.1000
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the linked pdf with https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)
Images in pdf render without visual issues (Screenshot from Edge 114.0.1823.82 built-in pdf reader)
![Screenshot 2023-07-16 031538](https://github.com/mozilla/pdf.js/assets/19279387/56985ee2-d4cd-49b3-96c6-841bf3ec8145)

What went wrong? (add screenshot)
White, horizontal lines all over the image at the top of the pdf
![Screenshot 2023-07-16 031703](https://github.com/mozilla/pdf.js/assets/19279387/a112885a-6e6d-40cd-89b0-8b88ab2cba7b)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-07-18 08:42
*Updated the title slightly, to better describe the underlying problem.*
The images in this document are narrow "strips", with white lines occurring *between* them (likely because of rounding issues).

**Comment by marco-c** [comment] 2023-07-18 08:53
Duplicate of #3351?

**Comment by Snuffleupagus** [comment] 2023-07-18 08:59
Duplicate of #3351

**Closed by Snuffleupagus** 2023-07-18 08:59 UTC
Labels: image-quality
