### ISSUE TITLE
Text marked at the wrong place

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6636] opened 2015-11-14 13:14 UTC
https://www.netbank.de/nb/downloads/Informationsbogen.pdf

enter "obergrenze" in the search field. There are 5 hits, the 2nd, 4th and 5th are at the wrong place.

I am using FF 42 on a W7 system.

![obergrenze-screenshot](https://cloud.githubusercontent.com/assets/6665575/11163719/f0c82346-8ad9-11e5-8e1b-fdcf9e6946b8.png)

**Comment by timvandermeij** [comment] 2015-11-14 20:26
This appears to have been fixed by a recent commit as I cannot reproduce it with the latest PDF.js development version. Could you try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if you can still reproduce it? It works fine for me with that version.

**Comment by THausherr** [comment] 2015-11-14 20:33
That's the viewer I used... and I just retested it right now!

![obergrenze-screenshot2](https://cloud.githubusercontent.com/assets/6665575/11165700/3987720c-8b17-11e5-8d2b-234eb2a7c06c.png)

**Comment by Snuffleupagus** [comment] 2015-11-15 12:56
From looking at the screen-shots: it seems like the entire viewer (including the UI) is slightly zoomed in, which might explain the alignment issues.
@THausherr If you reset the zoom level of the browser (<kbd>Ctrl</kbd>+<kbd>0</kbd>), does the problem go away?

**Comment by timvandermeij** [comment] 2015-11-16 22:03
I can indeed reproduce the behavior in the screenshot when I zoom in to 110%. For 100% zoom there is no problem. This is now a confirmed issue, but I'm not sure if it is a regression from one of the text selection PRs.

**Comment by THausherr** [comment] 2015-11-16 22:12
@Snuffleupagus it happens also with CTRL-0. And with different zoom levels below 170%. However I have set up windows that it has slightly bigger fonts than normal (125%).

Btw I didn't receive a copy from your message, only from Tim. And nothing in my spam folder.

**Comment by timvandermeij** [comment] 2015-11-16 22:16
Yes, that font size change might also have something to do with this. Thank you for reporting it, we need to look into this.

**Comment by haql** [comment] 2015-12-09 10:20
I think I have a same problem with this. when I select text to copy and paste it into the editor, the text look like moved some letters from my selection.

![select-and-copy](https://cloud.githubusercontent.com/assets/16188652/11682563/5b887a60-9e98-11e5-9b92-20ba30364552.png)

I have tried with search:
![search](https://cloud.githubusercontent.com/assets/16188652/11682569/6e1359c0-9e98-11e5-98ae-e264d599fa21.png)

I used this document: 
[C-View Letter to Vendor.pdf](https://github.com/mozilla/pdf.js/files/56618/C-View.Letter.to.Vendor.pdf)

This bug just happen on Firefox only. I am using version 42.0.

Please support this. Thanks a lot.

**Comment by THausherr** [comment] 2019-10-13 09:26
new example on this:
https://www.klinikum.uni-heidelberg.de/fileadmin/inst_hygiene/med_mikrobiologie/download/MB-Desinfektionsmittel.pdf
[MB-Desinfektionsmittel.pdf](https://github.com/mozilla/pdf.js/files/3721588/MB-Desinfektionsmittel.pdf)
Enter "Rezeptur" into the search field, and see this:
![grafik](https://user-images.githubusercontent.com/6665575/66713478-c150cf80-edab-11e9-8965-cf0c769f64ad.png)
The "offset" seems to be cumulative, it starts small when searching for "Sterillium® classic pure" and gets bigger and bigger. Searching for "standardmäßigen" shows this:
![grafik](https://user-images.githubusercontent.com/6665575/66713523-2efcfb80-edac-11e9-9529-0e6a3b7b0030.png)
So it is now marked on two different lines!

**Comment by timvandermeij** [comment] 2021-02-13 14:56
Closing since this is now fixed after recent search normalization and text layer fixes.

**Closed by timvandermeij** 2021-02-13 14:56 UTC
Labels: 4-text-selection
