### ISSUE TITLE
load bar What does this mean

### ISSUE THREAD

**Issue by sapq** [mozilla/pdf.js#8509] opened 2017-06-10 04:57 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. load bar What does this mean
2. what mean that how  i fix this i dont want this bar

What is the expected behavior? (add screenshot)
befor i move to new server it is good loding  

but what mean this loadin ?
![loading bar](https://user-images.githubusercontent.com/8040862/27000095-4c9e6c56-4db2-11e7-8a7c-1036172c553b.jpg)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment] 2017-06-10 11:57
Not enough information provided to reproduce the issue. Works for me. Closing as incomplete

**Closed by yurydelendik** 2017-06-10 11:57 UTC
