### ISSUE TITLE
sign is misplaced

### ISSUE THREAD

**Issue by pcwang0205** [mozilla/pdf.js#10146] opened 2018-10-10 03:22 UTC
When the pdf contains sign，the sign is misplaced. How to solved the problem.
![image](https://user-images.githubusercontent.com/10112141/46711498-1e88e100-cc7f-11e8-89b8-c565fd394298.png)

![image](https://user-images.githubusercontent.com/10112141/46711356-94407d00-cc7e-11e8-807f-67ed332b5305.png)

**Comment by timvandermeij** [comment] 2018-10-10 21:38
You should provide the PDF file so we can take a look. Without it, the issue is not actionable and will be closed. Try opening your PDF file with https://mozilla.github.io/pdf.js/web/viewer.html too to see if it's perhaps any custom modification that's causing this.

**Comment by timvandermeij** [comment] 2018-10-12 21:44
Closing until the information is provided.

**Closed by timvandermeij** 2018-10-12 21:44 UTC
Labels: 1-other, 4-information-requested
