### ISSUE TITLE
customize the color that drag to select text

### ISSUE THREAD

**Issue by surefish** [mozilla/pdf.js#12471] opened 2020-10-11 20:18 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- chrome and its 86.0.4240.75
- macos and 10.15.6:
- saladict:
- Is a browser extension:

Steps to reproduce the problem:
1. right click the saladict extension and open the pdf reader
<img width="260" alt="open pdf" src="https://user-images.githubusercontent.com/7425888/95689244-ea67a280-0c41-11eb-8237-b499555f57aa.png">

2.open a pdf book then drag to select text

What is the expected behavior? (add screenshot)
![expected](https://user-images.githubusercontent.com/7425888/95689150-7af1b300-0c41-11eb-86bd-fa55e8c7f3c0.jpg)
What went wrong? (add screenshot)
![sadone](https://user-images.githubusercontent.com/7425888/95689168-8f35b000-0c41-11eb-9ed7-c2d251bc2d3d.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by surefish** [comment] 2020-10-11 20:26
![Uploading macos invert color.png…]()

**Comment by surefish** [comment] 2020-10-11 20:27
![macos invert color](https://user-images.githubusercontent.com/7425888/95689416-2d764580-0c43-11eb-9172-58c49833bfce.jpg)

**Comment by timvandermeij** [comment] 2020-10-12 20:21
Closing since this is essentially a duplicate of https://github.com/mozilla/pdf.js/issues/9184#issuecomment-475872865. In a custom deployment this color can be changed. We're not aware of how "saladict" uses PDF.js, so this might be something they tweaked as well.

**Closed by timvandermeij** 2020-10-12 20:21 UTC
