### ISSUE TITLE
[Feature]: Font family and bold/italic options for Free Text annotation

### ISSUE THREAD

**Issue by Stamo-Gochev** [mozilla/pdf.js#18710] opened 2024-09-09 09:46 UTC
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

RIght now, adding a text annotation seem to only allow for changing its font color and size:

![image](https://github.com/user-attachments/assets/76e78e42-e1e8-4123-a40b-5a1348014635)

The "Helvetica" font seem to be inlined in various places:

https://github.com/mozilla/pdf.js/blob/a1b45d6e69d37b76e675a7f247943b70f186baca/src/core/annotation.js#L342-L351

What do you think about exposing an option for changing the font family and/or allowing it to be bold/italic?

In addition, as I have a requirement to implement such capabilities, can you provide more information how to approach this, so I can contribute to the code? Can you guide me in which files should I make changes in order to allow changing the font to a list like "Arial", "Times New Roman" and "Courier New"?

**Comment by Snuffleupagus** [comment] 2024-09-09 10:26
Duplicate of [bug 1846690](https://bugzilla.mozilla.org/show_bug.cgi?id=1846690) respectively [bug 1841889](https://bugzilla.mozilla.org/show_bug.cgi?id=1841889).

---

Again, this seems like something that may require UI/UX feedback *first*.

**Closed by Snuffleupagus** 2024-09-09 10:26 UTC

**Comment by marco-c** [comment] 2024-09-16 15:19
We're definitely planning this, but as @Snuffleupagus mentioned we'd need UI/UX design first.
This one could be easier though, as we already have a panel, we could "just" add another field in that panel
