### ISSUE TITLE
IE11 bad rendering

### ISSUE THREAD

**Issue by sl-jz** [mozilla/pdf.js#7258] opened 2016-04-27 12:53 UTC
Link to PDF file (or attach file here):
[R6x-PSL-BG-DIN_prv.pdf](https://github.com/mozilla/pdf.js/files/238616/R6x-PSL-BG-DIN_prv.pdf)

Configuration:
- Web browser and its version: IE11
- Operating system and its version: Windows 10 64 bits
- PDF.js version: http://mozilla.github.io/pdf.js/web/viewer.html
- Is an extension: No

Steps to reproduce the problem:
1. Click open file
2. Select file

What is the expected behavior? (add screenshot)
Like in Firefox, Chrome, Safari: 

![firefox-correct](https://cloud.githubusercontent.com/assets/18699657/14852390/4902f2c4-0c86-11e6-806e-eb0a78fd5358.png)

What went wrong? (add screenshot)
Just renders a gray box in IE11.

IE11:
![ie11](https://cloud.githubusercontent.com/assets/18699657/14852391/491a07fc-0c86-11e6-90d9-7ac57275c795.png)

Additional comments:
I heard that the rendering was correct for a second in IE11 and then became a grey box, however I haven't been able to verify that.

**Comment by yurydelendik** [comment] 2016-04-27 14:33
Darken blend mode is used. IE11 and below (I did not test with Edge) is the only browser that does not support this canvas feature. See http://blogs.adobe.com/webplatform/2013/01/28/blending-features-in-canvas/

**Comment by yurydelendik** [comment] 2016-04-27 14:40
Closing as duplicate of #5264.

Looks like Edge implements blending modes https://developer.microsoft.com/en-us/microsoft-edge/platform/status/compositingandblendingincanvas2d

**Closed by yurydelendik** 2016-04-27 14:40 UTC
Labels: 4-ie11-specific

**Comment by sl-jz** [comment] 2016-04-27 14:43
Thank you Yury!

You're doing an awesome job.
