### ISSUE TITLE
Weird behavior in scrollIntoView

### ISSUE THREAD

**Issue by EtienneCoumont** [mozilla/pdf.js#14383] opened 2021-12-16 17:11 UTC
Hello,

I have a strange behaviour in the scroll when changing page.
If the viewer itself has a scrollbar, changing page scrolls the viewer to the target page (it is ok).
But if the viewer does not have a scrollbar, the parent container is scrolled instead.

Configuration:
- Web browser and its version: Chrome 96
- Operating system and its version: Windows 10
- PDF.js version: last commit on December 15th, but version 2.2.228 already had the same behavior
- Is a browser extension: no

Steps to reproduce the problem:
1. Go to https://etiennecoumont.github.io/pdf.js/web/viewer.html
2. Scroll to top of the page to see only the upper half of the viewer
3. Ensure the zoom is 50% or more
4. Change the page using arrows buttons. The page change normally in the viewer
5. Set the zoom to 20% by using the "-" button
6. The page scroll by itself to display the viewer
7. Re-scroll to the top of the page to see only the upper half of the viewer
8. Now changing the page is also scrolling the whole page

What is the expected [behavior?]
Changing page changes the scroll of the viewer
[ok with zoom 50%](https://etiennecoumont.github.io/pdf.js/scrollintoview_ok.PNG)

What went wrong? (add screenshot)
Changing zoom (when 20% or less) or changing page will scroll the whole page
[screenshot](https://etiennecoumont.github.io/pdf.js/scrollintoview_ko.PNG)

The issue is in the function scrollIntoView which basically takes the first parent having a scrollbar to make it scroll. Is it expected for this function to go outside of the viewer boundaries and make external containers scroll ?

Thanks

**Comment by Snuffleupagus** [comment] 2021-12-16 17:17
The default viewer was, and still is, written specifically to be used as the *built-in* PDF Viewer in Firefox. Hence it's never been intended to be used in the sort of situation described above[1], and we thus recommend placing it in an `<iframe>` to avoid any issues there.

Furthermore, there's also issue #11626 which is *possibly* relevant here as well; hence closing as answered and/or duplicate of that one.

---
[1] Please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Closed by Snuffleupagus** 2021-12-16 17:17 UTC
