### ISSUE TITLE
pdf doc in pdfjs with IE11/Win7 blank paper on printing

### ISSUE THREAD

**Issue by venusakthiv** [mozilla/pdf.js#8428] opened 2017-05-19 13:20 UTC
Link to PDF file (or attach file here):
attaching the test pdf

Configuration:
- Web browser and its version: IE & 11
- Operating system and its version: Windows 7
- PDF.js version: 1.6.461
- Is an extension: No
[print_issue_pdf.pdf](https://github.com/mozilla/pdf.js/files/1014358/print_issue_pdf.pdf)

Steps to reproduce the problem:
1.  when we opened this document and click on print it shows blank paper
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-05-19 13:39
> PDF.js version: 1.6.461

That version is very outdated, please ensure that the problem is still present in the *latest* version of PDF, available at https://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by venusakthiv** [comment] 2017-05-19 13:47
not working with latest version of PDF.js

**Comment by Sterlingtech** [comment] 2018-06-11 07:51
Hi team,

We are also facing the exact same issue, we are using the latest version of PDF.js, could we have an ETA on the fix for this issue?

Thanks

**Comment by timvandermeij** [comment] 2019-11-09 13:31
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.

**Closed by timvandermeij** 2019-11-09 13:31 UTC
Labels: 4-ie11-specific, 4-printing
