### ISSUE TITLE
Incorrect glyph spacing

### ISSUE THREAD

**Issue by gene1wood** [mozilla/pdf.js#9068] opened 2017-10-25 17:32 UTC
Attach (recommended) or Link to PDF file here: [howto-electronic-adversaries.pdf](https://github.com/mozilla/pdf.js/files/1415544/howto-electronic-adversaries.pdf)

Configuration:
- Web browser and its version: Firefox 56.0
- Operating system and its version: Ubuntu 16.04
- PDF.js version: PDF 95294b374852b7ee2162744a3a4059a4 [1.5 Skia/PDF m64 / -] (PDF.js: 1.8.618)
- Is a browser extension: I'm not sure what this means. This is the builtin PDF rendering behavior in Firefox

Steps to reproduce the problem:
1. Browse to https://www.cs.rice.edu/~dwallach/howto-electronic-adversaries.pdf

What is the expected behavior? (add screenshot)

![selection_001](https://user-images.githubusercontent.com/1134034/32013339-ab295f28-b96f-11e7-82b0-844c908ed6d3.png)

What went wrong? (add screenshot)

![selection_002](https://user-images.githubusercontent.com/1134034/32013344-afe87fd0-b96f-11e7-97aa-94c9da1e4193.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-10-25 17:39
Closing as duplicate of issue #9024 (which was fixed by PR #8938).

**Closed by Snuffleupagus** 2017-10-25 17:39 UTC
