### ISSUE TITLE
Signature and Text Box Mirrored and Upside Down

### ISSUE THREAD

**Issue by MatthewSickler** [mozilla/pdf.js#6598] opened 2015-11-06 15:29 UTC
With certain pdf files there seems to be an issue where user input elements are being mirrored.  Issue exists in both my implementation and the viewer provided at http://mozilla.github.io/pdf.js/web/viewer.html

PDF as shown in Preview:
![screen shot 2015-11-06 at 9 55 41 am](https://cloud.githubusercontent.com/assets/8290545/10999923/c20e6f60-846c-11e5-9073-8a2dd3995221.png)

PDF as shown in pdfjs
![screen shot 2015-11-06 at 9 56 36 am](https://cloud.githubusercontent.com/assets/8290545/10999927/c9fe7210-846c-11e5-9445-f9c9b1dde03e.png)

The program used to last edit the pdf was PDF Expert for iPad.  I can open the pdf in Preview and immediately tell it to save and it fixes the issue.

PDF File Used: https://drive.google.com/file/d/0B50_w6kFwOTuXzd4LU1jbFcxUUU/view?usp=sharing

MacBook Air
OSX El Capitan 10.11.1
Chrome Version 46.0.2490.80 (64-bit) and Firefox 42.0
Problem exists in both pdfjs dist versions 1.0.1040 and 1.1.366

Console Output after opening the file:
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
viewer.js:7064 PDF 31415926535897932384626433832795 [1.6 - / -] (PDF.js: 1.2.70)
viewer.js:7088 Warning: AcroForm/XFA is not supported
pdf.worker.js:224 Warning: Unimplemented annotation type "Ink", falling back to base annotation
2pdf.worker.js:224 Warning: fontRes not available
pdf.js:224 Warning: Error during font loading: Font Helv is not available

**Comment by timvandermeij** [comment] 2015-11-06 20:48
Closing as duplicate of #5946.

**Closed by timvandermeij** 2015-11-06 20:48 UTC
