### ISSUE TITLE
Rendering large pdf in web worker

### ISSUE THREAD

**Issue by KKzLEO** [mozilla/pdf.js#15278] opened 2022-08-05 06:38 UTC
Configuration:
- Web browser and its version: Chrome 103.0.5060.134
- Operating system and its version: Win 10
- PDF.js version: "pdfjs-dist": "^2.14.305"
- Is a browser extension: No

Steps to reproduce the problem:

Thanks for creating this awesome library, it really helps me a lot. But I am wondering is there any way we can render the pdf in the web woker? like the code blow
```
    const pdfSource = await pdfjsLib.getDocument({
      url
    }).promise

    const page = await pdfSource.getPage(pageNumber)

    const viewport = page.getViewport({ scale: 5 })
    const canvasForPdf = createPdf(viewport.width, viewport.height)

    // that part is very slow
    await page.render({
      canvasContext: canvasForPdf.getContext('2d') as any,
      viewport,
    }).promise
```
The slow part is rendering PDF page in the canvas, I want to process that in the web worker(using `OffscreenCanvas`) and preload next 1~2 pages, but when I try to post `pdfSource` to woker, I got the error
```
Failed to execute 'postMessage' on 'Worker': (event)=>{
                            const data = event.data;
                            if (data.targetName...<omitted>... } could not be cloned.
```

Is there any way I can process that in the web worker or boost the loading time? thanks

**Comment by Snuffleupagus** [comment] 2022-08-05 07:30
Duplicate of #10319

**Closed by Snuffleupagus** 2022-08-05 07:30 UTC
