### ISSUE TITLE
 Incomplete Online Printing of pdfjs IE11

### ISSUE THREAD

**Issue by wangjian1212** [mozilla/pdf.js#10931] opened 2019-06-27 08:06 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE11
- Operating system and its version:Window7
- PDF.js version:2.0.943
- Is a browser extension:

Steps to reproduce the problem:
1. The pdfjs version I use is the latest. When I print online with the IE11 browser, the printed files are not printed on the right side. It feels like the font is bigger than the actual font and does not display all of them. See the screenshot for details.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/32234924/60248336-06342180-98f5-11e9-9c30-d3d2dd218472.png)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-06-27 08:25
Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:

> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which completely prevent the library and/or the default viewer from running will be accepted.

**Comment by timvandermeij** [comment] 2019-06-27 18:24
Closing because of the above and because there is no PDF file to reproduce this.

**Closed by timvandermeij** 2019-06-27 18:24 UTC
