### ISSUE TITLE
"Text annotation" in Japanese rotate,and the font size decrease.

### ISSUE THREAD

**Issue by skit-s-ikeda** [mozilla/pdf.js#16349] opened 2023-04-26 01:46 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome ver:112.0.5615.121
- Operating system and its version: Windows 11
- PDF.js version: v3.6.115
- Is a browser extension:

Steps to reproduce the problem:
1. Add "text annotation" in Japanese(by using free text editor) to the PDF file with rotation prpblem.
   e.g "あああ"
2. Download PDF file.
3. Display downloaded PDF file.
 
What is the expected behavior? (add screenshot)
What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/72960107/234444492-dab95da8-956e-48e6-889f-343413519358.png)
![image](https://user-images.githubusercontent.com/72960107/234444624-47206e1b-ef4e-4cbe-8e3c-0e97d7834404.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-04-26 06:51
Duplicate of #15769

**Closed by Snuffleupagus** 2023-04-26 06:51 UTC
