### ISSUE TITLE
Some pages in a PDF file are not rendered ( come up as blank) 

### ISSUE THREAD

**Issue by nehamishra-1** [mozilla/pdf.js#14800] opened 2022-04-19 10:30 UTC
Attach (recommended) or Link to PDF file here:
The first two pages of few pdf documents appears blank.
   pdfjs-2.5.207  - Blank pages for page 1, 2 and 4. Page 3 is rendered
   pdfjs-2.9.359. - Blank pages for page 1, 2 and 4. Page 3 is rendered
   pdfjs-2.13.216 - Blank pages for page 1, 2 and 4. Page 3 is rendered
If the PDF doc is opened directly in Chrome - All pages render fine.

The sample document will be uploaded by the client within couple of hours. Request you to wait.

Configuration:
- Web browser and its version: Firefox (tested on 97.0.1 )
- Operating system and its version: tested on windows
- PDF.js version:  pdfjs-2.5.207,   pdfjs-2.9.359 , pdfjs-2.13.216.
- Is a browser extension:

Steps to reproduce the problem:
Test the sample document with pdf.js, first two pages of few pdf documents appears blank.

What is the expected behavior? (add screenshot) : All pages to be rendered successfully.

What went wrong? (add screenshot) : first two pages of few pdf documents appears blank.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-04-19 10:39
> The sample document will be uploaded by the client within couple of hours. Request you to wait.

Please note that this is an *open source* bug tracker, for a software project that you're able to use *for free*, and many of the people that you interact with here are *unpaid* volunteers.
Hence please respect other peoples time, by waiting until you've gathered *all* of the necessary information *before* opening an issue!

> PDF.js version:  pdfjs-2.5.207,   pdfjs-2.9.359

Neither of those versions are supported now, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by tthompsonAtenchoice** [comment] 2022-04-21 21:18
Uploaded pdf document.

**Comment by nehamishra-1** [comment] 2022-04-22 05:26
Uploaded sample document.
Also tested with latest pdf js version (pdfjs-2.13.216.), same result. 
thus reopening the ticket.

**Comment by timvandermeij** [comment] 2022-04-22 09:15
I got the following stack trace from the development viewer:

```
PDF.js v2.14.206 (build: 452a98b0e)
Bericht: 
Stack: putBinaryImageData@https://mozilla.github.io/pdf.js/build/pdf.js:5420:11
paintInlineImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:7332:25
paintImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:7283:10
executeOperatorList@https://mozilla.github.io/pdf.js/build/pdf.js:5805:20
_next@https://mozilla.github.io/pdf.js/build/pdf.js:3457:37
__webpack_modules__</_scheduleNext/<@https://mozilla.github.io/pdf.js/build/pdf.js:3445:14
FrameRequestCallback*_scheduleNext@https://mozilla.github.io/pdf.js/build/pdf.js:3444:14
renderContinueCallback@https://mozilla.github.io/pdf.js/web/viewer.js:12203:9
__webpack_modules__</paintOnCanvas/renderTask.onContinue@https://mozilla.github.io/pdf.js/web/viewer.js:12388:16
_continue@https://mozilla.github.io/pdf.js/build/pdf.js:3436:17
operatorListChanged@https://mozilla.github.io/pdf.js/build/pdf.js:3425:10
_renderPageChunk@https://mozilla.github.io/pdf.js/build/pdf.js:2093:26
__webpack_modules__</_pumpOperatorList/pump/<@https://mozilla.github.io/pdf.js/build/pdf.js:2132:14
promise callback*pump@https://mozilla.github.io/pdf.js/build/pdf.js:2119:21
_pumpOperatorList@https://mozilla.github.io/pdf.js/build/pdf.js:2162:5
render@https://mozilla.github.io/pdf.js/build/pdf.js:1819:12
paintOnCanvas@https://mozilla.github.io/pdf.js/web/viewer.js:12382:37
draw@https://mozilla.github.io/pdf.js/web/viewer.js:12240:108
renderView@https://mozilla.github.io/pdf.js/web/viewer.js:7990:14
__webpack_modules__</forceRendering/<@https://mozilla.github.io/pdf.js/web/viewer.js:11003:29
promise callback*forceRendering@https://mozilla.github.io/pdf.js/web/viewer.js:11002:43
renderHighestPriority@https://mozilla.github.io/pdf.js/web/viewer.js:7897:24
update@https://mozilla.github.io/pdf.js/web/viewer.js:10827:25
_scrollUpdate@https://mozilla.github.io/pdf.js/web/viewer.js:10470:10
viewAreaElementScrolled@https://mozilla.github.io/pdf.js/web/viewer.js:3225:15
FrameRequestCallback*debounceScroll@https://mozilla.github.io/pdf.js/web/viewer.js:3207:18
EventListener.handleEvent*watchScroll@https://mozilla.github.io/pdf.js/web/viewer.js:3237:19
BaseViewer@https://mozilla.github.io/pdf.js/web/viewer.js:9882:45
PDFViewer@https://mozilla.github.io/pdf.js/web/viewer.js:9695:1
_initializeViewerComponents@https://mozilla.github.io/pdf.js/web/viewer.js:707:22
initialize@https://mozilla.github.io/pdf.js/web/viewer.js:505:16
async*run@https://mozilla.github.io/pdf.js/web/viewer.js:795:10
webViewerLoad@https://mozilla.github.io/pdf.js/web/viewer.js:15599:29
EventListener.handleEvent*@https://mozilla.github.io/pdf.js/web/viewer.js:15607:12
@https://mozilla.github.io/pdf.js/web/viewer.js:15609:3
@https://mozilla.github.io/pdf.js/web/viewer.js:15611:12
```

In the web console we see:

```
renderView: "[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: https://mozilla.github.io/pdf.js/build/pdf.js :: putBinaryImageData :: line 5420"  data: no]" pdf_rendering_queue.js:205:20
    renderView pdf_rendering_queue.js:205
    (Async: promise callback)
    renderView pdf_rendering_queue.js:201
    forceRendering base_viewer.js:1563
    (Async: promise callback)
    forceRendering base_viewer.js:1562
    renderHighestPriority pdf_rendering_queue.js:80
    update base_viewer.js:1350
    webViewerScaleChanging app.js:2578
    dispatch event_utils.js:126
    _setScaleUpdatePages base_viewer.js:1039
    _setScale base_viewer.js:1118
    set currentScaleValue base_viewer.js:445
    scrollPageIntoView base_viewer.js:1271
    setHash pdf_link_service.js:409
    setInitialView app.js:1723
    load app.js:1284
    (Async: promise callback)
    load app.js:1232
    (Async: promise callback)
    load app.js:1221
    open app.js:931
    (Async: promise callback)
    open app.js:929
    webViewerFileInputChange app.js:2447
    dispatch event_utils.js:126
    webViewerInitialized app.js:2171
    (Async: EventListener.handleEvent)
    webViewerInitialized app.js:2166
    (Async: promise callback)
    run app.js:627
    webViewerLoad viewer.js:243
    (Async: EventListener.handleEvent)
    <anoniem> viewer.js:257
    <anoniem> viewer.js:15609
    <anoniem> viewer.js:15611
```

**Comment by Snuffleupagus** [comment] 2022-04-22 09:51
Duplicate of #12307

**Closed by Snuffleupagus** 2022-04-22 09:51 UTC
Labels: core

**Comment by dhanbhan** [comment] 2023-05-25 11:38
@Snuffleupagus I see this issue is closed on April 2022. I have verified in latest pdfjs build `pdfjs-3.6.172` with same test document provided, I see blank page for 15-20 seconds and page displays at later. 

May I know if it is already delivered in `pdfjs-3.6.172` ? If yes I don't see it is working as expected.
