### ISSUE TITLE
PageLabels not taking into account for resolving urls

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#8225] opened 2017-04-01 17:57 UTC
Link to PDF file (or attach file here):

* https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=585

Configuration:

- Web browser and its version: Firefox 52 (32bit)
- Operating system and its version: Fedora 25
- PDF.js version: I’m afraid I cannot check it.
- Is an extension: no (bundled with Firefox, `about:addons` doesn’t display anything related to the extension).

Steps to reproduce the problem:
1.  Paste the url https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=585.
2. pdf.js lands in document page 585 (which is page label 577). It should resolve the page label.

**Comment by Snuffleupagus** [comment] 2017-04-02 09:46
I get the *exact* same behaviour in Adobe Reader as well (when used in Internet Explorer).
Please note that http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf#G4.1501771 mentions *only* page numbers and says nothing about page labels. It explicitly states that the `page=...` parameter should be an integer, which rule out page labels since they are strings. (If page labels were supported in the hash that would create inconsistent behaviour, since not all PDF viewers support that; see e.g. PDFium in Chrome.)

So trying to resolve page labels in the hash would be inconsistent with the *both* specification and the reference implementation of it, which is Adobe Reader. (Furthermore, it would also unnecessarily delay the initial loading of *all* PDF files in PDF.js, if we were to wait for the page labels too.)

Based on all of the above, I'm closing this as WONTFIX, since this is working as intended.

**Closed by Snuffleupagus** 2017-04-02 09:46 UTC
Labels: 1-viewer
