### ISSUE TITLE
Protocol "blob:" not supported. Expected "https:" error in NW.js

### ISSUE THREAD

**Issue by Haris-Jamil** [mozilla/pdf.js#11481] opened 2020-01-07 12:05 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome (79.0.3945.88)
- Operating system and its version: Windows 10
- PDF.js version: 2.0.943
- Is a browser extension: Yes (Angular App running in NW.js)

Steps to reproduce the problem:
1. App should be running on NW.js
2. Pass blob URL with "blob:" protocol to PDFJS.getDocument() method

What is the expected behavior? (add screenshot)
Should get document still if the url have blob protocol

What went wrong? (add screenshot)
Giving following error: 
_UnknownErrorException: Protocol "blob:" not supported. Expected "https:"_

**In previous version i.e (1.5.391) it was working fine.**

here is the sample code to replicate the error

```
getPdf( fileLocation ).then( (blobUrl) => {

    var PDFJS = parent['pdfjs-dist/build/pdf'];
    PDFJS.GlobalWorkerOptions.workerSrc = "/app/js/pdf.worker.js";   
    PDFJS.disableWorker = true;

    PDFJS.getDocument({url: blobUrl}, null, null, null).then(  // error causing line
        (pdf:any) => {
        }
    );
});

getPDF(url) {
     return new Promise((fulfill, reject)=> {
          this.fs.readFile(url, (err, data)=> {
              if (err) {
                  reject(err);
              } else {
                  var arrayBuffer = baselib.UtilityClass.toArrayBuffer(data);
                  var blob = new Blob([arrayBuffer], {type: "application/pdf"});
                  fulfill(this.getBlobURL(blob));
               }
          });
     });
}


```

**Comment by Snuffleupagus** [comment] 2020-01-07 12:48
Duplicate of #9071

**Comment by Haris-Jamil** [comment] 2020-01-07 12:58
Yes i went through complete thread of this issue, although the issue is marked as fixed but i didn't get how to resolve this problem.  Can you please help me out.

**Comment by Snuffleupagus** [comment] 2020-01-07 13:02
> PDF.js version: 2.0.943
>
> [...] although the issue is marked as fixed but i didn't get how to resolve this problem.

Update to the *latest* release, see https://github.com/mozilla/pdf.js/releases, since the version you're using is too old.

**Closed** 2020-01-07 22:44 UTC
