### ISSUE TITLE
Can’t install dependencies

### ISSUE THREAD

**Issue by bramus** [mozilla/pdf.js#15787] opened 2022-12-07 02:33 UTC
Tested with Node v16.16.0 and v18.12.1 (through nvm).

Running `npm i` gives me this:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: eslint-plugin-mozilla@3.0.0
npm ERR! Found: eslint-plugin-prettier@4.2.1
npm ERR! node_modules/eslint-plugin-prettier
npm ERR!   dev eslint-plugin-prettier@"^4.2.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-prettier@"^3.0.0" from eslint-plugin-mozilla@3.0.0
npm ERR! node_modules/eslint-plugin-mozilla
npm ERR!   dev eslint-plugin-mozilla@"^3.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint-plugin-prettier@3.4.1
npm ERR! node_modules/eslint-plugin-prettier
npm ERR!   peer eslint-plugin-prettier@"^3.0.0" from eslint-plugin-mozilla@3.0.0
npm ERR!   node_modules/eslint-plugin-mozilla
npm ERR!     dev eslint-plugin-mozilla@"^3.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Using macOS 13.0.1 (22A400)

**Comment by Snuffleupagus** [comment] 2022-12-07 08:46
Duplicate of #15429

**Closed by Snuffleupagus** 2022-12-07 08:46 UTC
