### ISSUE TITLE
Viewer is blank after enabling presentation mode in Chrome 49

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#6789] opened 2015-12-22 11:15 UTC
After entering full screen mode, the canvas blanks out (in Chrome 49 on Mac).
For videos and other details, see https://code.google.com/p/chromium/issues/detail?id=571342.

Could anyone with a Mac install Chrome Canary (https://www.google.com/chrome/browser/canary.html) and debug the issue? Is this a bug in Chrome or PDF.js?

**Comment by yurydelendik** [comment] 2015-12-22 14:23
Unable to reproduce on mac 10.11.2 version 49.0.2598.0. One of the commenters reports it's reproducable on mac 10.10.

**Comment by Rob--W** [comment] 2015-12-23 09:55
And apparently it is not reproducible with the web version, so it could either be a bug in an old version of PDF.js or (most likely) a Chrome bug.

The Chrome extension is not using the latest version of PDF.js, and I don't see any obvious related changes to PDF.js in the range: https://github.com/Rob--W/pdf.js/compare/chrome-1.1.527...mozilla:9f23e11

Are you aware of any changes related to render (scheduling) / full screen / page resize?

**Comment by yurydelendik** [comment] 2015-12-23 16:14
@Rob--W https://github.com/mozilla/pdf.js/pull/6630 is in the range -- long shot but this can affect.

**Comment by timvandermeij** [comment] 2016-05-09 22:15
The upstream issue is closed and it appeared to be a Chrome bug. Closing as fixed here too.

**Closed by timvandermeij** 2016-05-09 22:15 UTC
Labels: 4-chrome-specific, 4-os-mac
