### ISSUE TITLE
the Chrome browser displays a fork

### ISSUE THREAD

**Issue by liuqian1996** [mozilla/pdf.js#12783] opened 2020-12-28 03:47 UTC
[Test.pdf](https://github.com/mozilla/pdf.js/files/5745778/Test.pdf)

Configuration:
- Chrome: 86.0.4240.183
- Opera: 70.0.3728.95
- System: WIndows 10 2004

Steps to reproduce the problem:

When I use the official online address: [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)
I opened the local file [Test.pdf](https://github.com/mozilla/pdf.js/files/5745778/Test.pdf)
The opera browser displays normally, and the Chrome browser displays a fork

![image](https://user-images.githubusercontent.com/11707934/103187980-8c259400-4901-11eb-8740-783b2bf8a8b5.png)

**Comment by Snuffleupagus** [comment] 2020-12-28 10:31
Duplicate of #12462

**Closed** 2020-12-28 18:43 UTC
