### ISSUE TITLE
PDFJS Library does not see some links

### ISSUE THREAD

**Issue by iberezansky** [mozilla/pdf.js#9224] opened 2017-12-01 10:19 UTC
Attach (recommended) or Link to PDF file here:
[QX_link test.pdf](https://github.com/mozilla/pdf.js/files/1521141/QX_link.test.pdf)

Configuration:
- Web browser and its version: Chrome, Firefox, IE11,
- Operating system and its version: Windows 7
- PDF.js version: github 2017/12/01
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached PDF and get its first page (pdfPage).
2. Get the annotations: pdfPage.getAnnotations().then(function(anno){console.log(anno);})

What is the expected behavior? (add screenshot)
There is not annotations, but there has to be links: www.vauxhalltavern.com, www.herupstairs.co.uk, www.underbellyfestival.com, www.the2brewers.com, www.leicestersquaretheatre.com, www.sohotheatre.com

What went wrong? (add screenshot)
There is not annotations.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-12-01 10:23
That PDF file doesn't actually contain any links, but just text styled to look like standard hyperlinks.

Those links can work in e.g. Adobe Reader, but only if you have enabled automatic creation of hyperlinks (this setting seems to default to on).

The issue is tracked in #3172, hence I'm closing this this as duplicate.

**Closed by Snuffleupagus** 2017-12-01 10:23 UTC
