### ISSUE TITLE
Investigate replacing the `URL` polyfill with the, upcoming, one from core-js

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#10490] opened 2019-01-24 13:58 UTC
An *upcoming* release of core-js, see https://github.com/zloirock/core-js/releases/tag/v3.0.0-beta.5, will include a `URL` polyfill. Since various core-js polyfills are already in use, and with good results, once the core-js `URL` polyfill is officially released it would probably be a good idea to try and use it instead of including/maintaining one in the PDF.js library; see https://github.com/mozilla/pdf.js/blob/master/external/url/url-lib.js.

**Comment by brianmhunt** [comment] 2019-06-14 14:42
Since polyfills are something that can be remedied in documentation, it might be worthwhile to consider removing `compatibility.js` entirely, whereas there is no easy fix for hard-coded dependencies on deprecated library versions.

**Comment by Snuffleupagus** [comment] 2019-07-27 13:27
A better, not the mention simpler, solution here would obviously be to remove support for browsers (= Internet Explorer) without `URL` native support, such that no polyfill is needed any more :-)

**Comment by phtyson** [comment] 2019-08-16 21:16
I made a small change in a fork, which revealed a problem with core-js@2, having to do with Symbol.iterator. This was fixed in core-js@3. Symptom only showed up in IE11.
I fixed with attached patch. I have not done full regression testing, but casual use in a browser does not show any problems.
[corejs.patch.zip](https://github.com/mozilla/pdf.js/files/3511186/corejs.patch.zip)

**Comment by phtyson** [comment] 2019-08-19 22:33
I found a deeper problem with `core-js internals/internal-state` throwing an error that is not caught, which causes IE11 to stop processing. I don't know how to fix that problem, we will have to exclude IE11 browsers for now.
Another question for pdf.js `src/shared/compatibility.js` is whether to require `core-js/features/symbol` or follow the earlier pattern using `core-js/es/symbol` (instead of core-js@2 `core-js/es6/symbol`)

**Closed** 2019-09-19 21:30 UTC
Labels: 1-core, 1-viewer
