### ISSUE TITLE
PDF fails to load in Firefox 58 on OSX High Sierra

### ISSUE THREAD

**Issue by daredevil82** [mozilla/pdf.js#9536] opened 2018-03-06 18:02 UTC
We went live with an update for our client written in React with PDF.js.  A customer reported an infinite loading screen of the application when using Firefox 58.0.2 on OSX High Sierra.  This issue cannot be duplicated in Chrome or Safari on the same machine.

I cannot duplicate this in El Captain, Sierra, Windows 7 or 8 with the same FF version, and tracking down the issue is made more difficult due to my lack of access to a usable machine with this OS

http://catalogs.degreedata.com/viewer/47547

Configuration:
- Web browser and its version:  Firefox 58
- Operating system and its version: OSX High Sierra
- PDF.js version: 1.8.532 and 2.0.419
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the URL above 

What is the expected behavior? (add screenshot)
PDF loads in React application

What went wrong? (add screenshot)
Infinite loading screen with following output via ngrok tunnel:

```
message: "Unexpected server response (0) while retrieving PDF \"http://s3-us-west-2.amazonaws.com/degreedata-pdf/47547.pdf\"."
   name: "UnexpectedResponseException"
    stack: 
"UnexpectedResponseExceptionClosure
@http://39b8d9ae.ngrok.io/static/js/bundle.js:31294:43\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:31288:44\n
__w_pdfjs_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:30868:12\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:38887:23\n
__w_pdfjs_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:30868:12\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:30911:18\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:30849:18\n
webpackUniversalModuleDefinition
@http://39b8d9ae.ngrok.io/static/js/bundle.js:30841:20\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:30839:11\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:30824:29\n
__webpack_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:689:12\nfn
@http://39b8d9ae.ngrok.io/static/js/bundle.js:110:20\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:100637:14\n
__w_pdfjs_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:100580:12\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:103652:16\n
__w_pdfjs_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:100580:12\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:100623:18\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:100561:18\n
webpackUniversalModuleDefinition
@http://39b8d9ae.ngrok.io/static/js/bundle.js:100553:20\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:100551:11\n
__webpack_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:689:12\nfn
@http://39b8d9ae.ngrok.io/static/js/bundle.js:110:20\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:69149:84\n
__webpack_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:689:12\nfn
@http://39b8d9ae.ngrok.io/static/js/bundle.js:110:20\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:69576:69\n
__webpack_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:689:12\nfn
@http://39b8d9ae.ngrok.io/static/js/bundle.js:110:20\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:16058:63\n
__webpack_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:689:12\nfn
@http://39b8d9ae.ngrok.io/static/js/bundle.js:110:20\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:67885:84\n
__webpack_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:689:12\nfn
@http://39b8d9ae.ngrok.io/static/js/bundle.js:110:20\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:67468:84\n
__webpack_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:689:12\nfn
@http://39b8d9ae.ngrok.io/static/js/bundle.js:110:20\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:66139:63\n
__webpack_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:689:12\nfn
@http://39b8d9ae.ngrok.io/static/js/bundle.js:110:20\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:141803:18\n
__webpack_require__
@http://39b8d9ae.ngrok.io/static/js/bundle.js:689:12\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:790:18\n
@http://39b8d9ae.ngrok.io/static/js/bundle.js:1:11\n"
status: 0
```

**Comment by timvandermeij** [comment] 2018-03-06 20:45
It looks like the server configuration is wrong here. Does the server support range (chunked) loading and is it enabled? It's hard to tell because it's a custom deployment, but perhaps you can look at the actual request being made and what the response code/response body is.

**Comment by daredevil82** [comment] 2018-03-06 22:19
So, the application is a React app, and it makes a direct request to the S3 bucket with the `$db_id.pdf` key.  S3 supports chunk loading, and I've enabled a CORS configuration to the following:

```<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>http://*</AllowedOrigin>
    <AllowedOrigin>https://*</AllowedOrigin>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>Accept-Ranges</ExposeHeader>
    <ExposeHeader>Content-Range</ExposeHeader>
    <ExposeHeader>Content-Encoding</ExposeHeader>
    <ExposeHeader>Content-Length</ExposeHeader>
</CORSRule>
</CORSConfiguration>
```

Interesting that it would happen only with FF on a specific OS version.

**Comment by daredevil82** [comment] 2018-03-07 17:55
Follow up - Testing in Yosemite and Sierra shows no issues.

**Comment by timvandermeij** [comment] 2019-03-08 22:32
Closing since this doesn't appear to be caused by PDF.js, but rather by server/OS configuration, so I don't see anything for us to do here.

**Closed by timvandermeij** 2019-03-08 22:32 UTC
Labels: 1-other
