### ISSUE TITLE
externalLinkTarget set to _blank

### ISSUE THREAD

**Issue by agriverae** [mozilla/pdf.js#10600] opened 2019-02-28 20:55 UTC
Attach (recommended) or Link to PDF file here:
https://www.antennahouse.com/XSLsample/pdf/sample-link_1.pdf

Configuration:
- Web browser and its version: Chrome Version 72.0.3626.109 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Pro, version 1803
- PDF.js version: 2.0.428
- Is a browser extension: No

Steps to reproduce the problem:
1.  Set externalLinkTarget in PDFLinkService to value 2.
2. Open browser console.
3. Open pdf.
4. Check the console, error messages are shown in the console for each external link.. (check image)

![image](https://user-images.githubusercontent.com/31800323/53594066-cf354580-3b78-11e9-88ac-c9230bafc5b7.png)

What is the expected behavior? (add screenshot)

The expected behavior is for no error messages in the console.

What went wrong? (add screenshot)

https://user-images.githubusercontent.com/31800323/53594066-cf354580-3b78-11e9-88ac-c9230bafc5b7.png

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-02-28 21:12
> PDF.js version: 2.0.428

Please note that that's *not* an official release, you can find the latest releases at https://github.com/mozilla/pdf.js/releases

> * Set externalLinkTarget in PDFLinkService to value 2.
> 
> * Open browser console.
> 
> * Open pdf.
> 
> * Check the console, error messages are shown in the console for each external link.. (check image)

Sorry, but I really cannot understand how `externalLinkTarget` would ever affect the method referenced in your screen-shot; please see https://github.com/mozilla/pdf.js/blob/21d70b19c23c688a10d870e49dc9b58fff691610/web/pdf_link_service.js#L339-L349

> Attach (recommended) or Link to PDF file here:
> https://www.antennahouse.com/XSLsample/pdf/sample-link_1.pdf

Finally, there's something fishy here since the errors in your screen-shot refers to objects `30 0 obj` and `39 0 obj` despite neither of them actually existing in that PDF file.

**Comment by timvandermeij** [comment] 2019-02-28 22:17
The PDF file renders just fine for me in Firefox and as indicated above the description doesn't seem to match what is going on in the PDF file. Closing until more information is provided.

**Closed by timvandermeij** 2019-02-28 22:17 UTC

**Comment by daniilhmslf** [comment] 2019-03-01 14:52
Hi all,

I am facing a similar issue on my end. The issue appears to be unrelated to the externalLinkTarget parameter, as I do not modify it. Here are my specs:

For the sake of consistency, I'm using the same PDF as the OP: 
https://www.antennahouse.com/XSLsample/pdf/sample-link_1.pdf

Configuration:

* Web browser and its version: Chrome Version 72.0.3626.109 (Official Build) (64-bit)
* Operating system and its version: Windows 10 Pro, version 1803
* PDF.js version: 2.0.943
* Is a browser extension: No

Steps to reproduce the problem:

1. initialize a PDFLinkService.
I am doing this like so:
```
    const PDFLinkService = new PDFJSViewer.PDFLinkService({});
    const viewerContainer = ReactDOM.findDOMNode(this);
    this.pdfViewer = new PDFJSViewer.PDFViewer({
      container: viewerContainer,
      eventBus: this.eventBus,
      linkService: PDFLinkService,
    });
```
2. Open browser console.
3. Open pdf.
4. Check the console, error messages are shown in the console for each external link.. (check image)
![image](https://user-images.githubusercontent.com/24642666/53645327-65b84400-3c17-11e9-9d82-346ccd100c82.png)

Adressing @Snuffleupagus' last point:

> Finally, there's something fishy here since the errors in your screen-shot refers to objects `30 0 obj` and `39 0 obj` despite neither of them actually existing in that PDF file.

These elements are created by pdf.js itself in line 1844 of  /pdfjs-dist/web/pdf_viewer:
![image](https://user-images.githubusercontent.com/24642666/53645207-22f66c00-3c17-11e9-9e75-c02b86ddf851.png)

Later in line 1845 it tries to append to `this._pagesRefCache` which is null by that point:
![image](https://user-images.githubusercontent.com/24642666/53645430-a021e100-3c17-11e9-937d-db1d364edeaf.png)

Bear in mind that `this._pagesRefCache` is initialized as `null` in line of the same file:
![image](https://user-images.githubusercontent.com/24642666/53645744-51287b80-3c18-11e9-8536-f2a0c968fd73.png)

Thanks in advance for any help you can provide.

**Comment by Snuffleupagus** [comment] 2019-03-01 15:16
> > Finally, there's something fishy here since the errors in your screen-shot refers to objects `30 0 obj` and `39 0 obj` despite neither of them actually existing in that PDF file.
>
> These elements are created by pdf.js itself in line 1844 of /pdfjs-dist/web/pdf_viewer:

No they're not, since that method is called from https://github.com/mozilla/pdf.js/blob/34022d2fd19caa98a56bc60c4e8ebde9eb7ea196/web/base_viewer.js#L458 using the `/Ref` of the page as provided by the API in https://github.com/mozilla/pdf.js/blob/34022d2fd19caa98a56bc60c4e8ebde9eb7ea196/src/display/api.js#L899-L905

Hence my comment still stands, since the original screen-shot didn't actually match the PDF file. (The one in https://github.com/mozilla/pdf.js/issues/10600#issuecomment-468690401 makes slightly more sense, since those pages actually exist.)

> 1. initialize a PDFLinkService.
> I am doing this like so:
> [...]

Please make sure to follow e.g. the `simpleviewer` example, see https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js

> Later in line 1845 it tries to append to `this._pagesRefCache` which is null by that point:

That shouldn't happen, provided that you're actually initializing the `PDFLinkService` instance *correctly*; note in particular https://github.com/mozilla/pdf.js/blob/34022d2fd19caa98a56bc60c4e8ebde9eb7ea196/examples/components/simpleviewer.js#L73

The conclusion is thus that the problem is caused by a simple oversight in a custom implemention; for future reference please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
