### ISSUE TITLE
unable to view signatures in pdf js

### ISSUE THREAD

**Issue by landyg** [mozilla/pdf.js#6105] opened 2015-06-11 18:33 UTC
When opening a pdf in pdf js signatures are not being displayed.
![pdfjsissue](https://cloud.githubusercontent.com/assets/12849871/8115048/d8d17e94-1046-11e5-9e4f-67589b4e2f50.JPG)

**Comment by Snuffleupagus** [comment] 2015-06-11 19:05
Closing as duplicate of issue #1076.

**Closed by Snuffleupagus** 2015-06-11 19:05 UTC
