### ISSUE TITLE
include pdf.js with url parameters cause pdfjsDistBuildPdfWorker is undefined

### ISSUE THREAD

**Issue by marcolafranca** [mozilla/pdf.js#8485] opened 2017-06-05 11:09 UTC
Configuration:
- Web browser and its version: Chrome 58.0.3029.110 (64-bit) / Firefox 53.0.3 (32 bit)
- Operating system and its version: win 10 - v.1703
- PDF.js version: 1.7.225

Steps to reproduce the problem:
1. include pdf.js in html page with an url param -> `<script src=".../pdf.js?param=value" type="text/javascript"></script>`
2. pdfjsDistBuildPdfWorker is not defined

What is the expected behavior?
window.pdfjsDistBuildPdfWorker is defined at line 8129
What went wrong?
window.pdfjsDistBuildPdfWorker is undefined

Solution:
Change function getWorkerSrc() at line 8116, in thi mode:
`return pdfjsFilePath.replace(/\.js$/i, '.worker.js');` -> `return pdfjsFilePath.replace(/\.js(\?.*)?$/i, '.worker.js');`

**Comment by Snuffleupagus** [comment] 2017-06-05 11:18
Closing as duplicate of issue #5710, which was fixed by PR #8309.

**Closed by Snuffleupagus** 2017-06-05 11:18 UTC
