### ISSUE TITLE
PDF Viewer not displaying pdf in Chrome and IE with javascript errors

### ISSUE THREAD

**Issue by illumna76** [mozilla/pdf.js#9296] opened 2017-12-19 17:47 UTC
Attach (recommended) or Link to PDF file here: http://localhost:51535/PdfViewer/Web/Viewer.html?file=http%3a%2f%2flocalhost%3a51535%2fextract.aspx%3ffile%3doutput%5ccompanyFolder%5c2017_10%5ccda3306d-b0bc-4245-ae7b-664712a5f60b.pdf

Configuration:
- Web browser and its version: Chrome 63.0.3239.108
- Operating system and its version: Windows 10
- PDF.js version: 1.9.426
- Is a browser extension: ??

What is the expected behavior? We pass Viewer.html a url path to our extract.aspx page. The extract.aspx page is our way of bypassing domain restrictions to get/download files. The viewer should be rendering pdfs but I sporadically receive an empty viewer with javascript errors. Currently, Chrome and IE are generating JavaScript errors while Firefox works. Upon debugging my extract.aspx page, when I do not receive JavaScript errors my breakpoints in extract.aspx are hit but when I receive JavaScript errors the breakpoints in extract.aspx do not get hits which tells me the issue lies somewhere in Viewer.html and/or in the browser--the viewer still renders but without a pdf.

What went wrong? (add screenshot)
Prior to version 1.9.426 we had sporadic behavior w/ getting the viewer to show our pdf docs. The viewer would show but wouldn't load the pdf. Sometimes it would work and others it wouldn't and this is with the same pdf. At one point no browser worked so I upgraded pdf.js to 1.9.426. Now, In firefox the document shows perfectly given the above url. In Chrome I receive three javascript errors (errors listed below) and the viewer shows w/ no pdf. In IE I receive a different JavaScript error (error listed below) and also an empty viewer.

I am working w/ the prebuilt .zip file.

(Sorry but in Firefox I cannot upload screenshots so messages are below)

**Chrome Errors:**
_Uncaught (in promise) TypeError: Cannot read property 'getDirection' of undefined
    at webViewerLocalized (viewer.js:7109)
    at <anonymous>
webViewerLocalized @ viewer.js:7109
Promise resolved (async)
(anonymous) @ viewer.js:7108
root.pdfjsWebPDFPrintService @ viewer.js:5578
(anonymous) @ viewer.js:5579
(anonymous) @ viewer.js:7374
viewer.js:3107 Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at Toolbar_updateUIState [as _updateUIState] (viewer.js:3107)
    at Toolbar_localized [as _localized] (viewer.js:3073)
    at <anonymous>
Toolbar_updateUIState @ viewer.js:3107
Toolbar_localized @ viewer.js:3073
Promise resolved (async)
Toolbar_bindClickListeners @ viewer.js:3068
Toolbar @ viewer.js:2994
(anonymous) @ viewer.js:5843
_initializeViewerComponents @ viewer.js:5778
(anonymous) @ viewer.js:5692
Promise resolved (async)
pdfViewInitialize @ viewer.js:5691
pdfViewRun @ viewer.js:5876
webViewerLoad @ viewer.js:7489
viewer.js:2906 Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at SecondaryToolbar_bindClickListeners [as _bindClickListeners] (viewer.js:2906)
    at new SecondaryToolbar (viewer.js:2872)
    at viewer.js:5844
    at new Promise (<anonymous>)
    at Object._initializeViewerComponents (viewer.js:5778)
    at viewer.js:5692
    at <anonymous>_

**IE Error:** 
_SCRIPT5009: 'require' is undefined viewer.js (573,3)._

**Comment by Snuffleupagus** [comment] 2017-12-19 21:24
> Attach (recommended) or Link to PDF file here: http://localhost:51535/PdfViewer/Web/Viewer.html?file=http%3a%2f%2flocalhost%3a51535%2fextract.aspx%3ffile%3doutput%5ccompanyFolder%5c2017_10%5ccda3306d-b0bc-4245-ae7b-664712a5f60b.pdf

Since the link above contains `localhost`, it unfortunately won't help anyone else to reproduce this issue.

> What is the expected behavior? We pass Viewer.html a url path to our extract.aspx page. The extract.aspx page is our way of bypassing domain restrictions to get/download files. The viewer should be rendering pdfs but I sporadically receive an empty viewer with javascript errors.

Since this appears to be an issue with a custom implementation of PDF.js, as asked for in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), please provide access to a complete (and runnable) example since it really isn't possible to provide any meaningful assistance otherwise.

**Comment by timvandermeij** [comment] 2017-12-20 21:29
It looks like some elements were removed from the viewer UI without adjusting the viewer JS code. Therefore, I think modifications to the viewer are causing these issues. As stated, we cannot debug this any further without access to a complete example, so until that's provided, I'm closing this since it's not actionable right now.

**Closed by timvandermeij** 2017-12-20 21:29 UTC
Labels: 4-information-requested

**Comment by illumna76** [comment] 2018-01-03 15:46
I left for the holidays and am now back. This isn't my custom implementation of the viewer. This was downloaded from your site. I will attempt to make a version I can put on our public domain.
