### ISSUE TITLE
PDF Digital Signatures warning message not correct

### ISSUE THREAD

**Issue by larrykluger** [mozilla/pdf.js#2486] opened 2012-12-19 08:01 UTC
If a pdf is signed with a standard digital signature, then the viewer:
1. Only displays the base level text/images of the pdf. (Doesn't show the digital signatures nor indicates that they exist in the document)
2. Gives a warning message that the "document might not be displayed correctly"

Issue: the warning message is incorrect -- the document will NOT be displayed correctly because digital signatures are not yet handled by the viewer.

Some test pdf's that were digitally signed: 
http://ftp.arx.com/Samples/signed_with_graphical_sig.pdf  -- signed with a private certificate
http://ftp.arx.com/Samples/signed_with_no_graphical_sig.pdf -- signed with a digital signature but no graphical signature – a typical application-generated file

It would be great if the error message (not warning message) said that the document includes one or more digital signatures. 

If you'd like to digitally sign your own pdf documents, I can provide some no-cost licenses for our signing software for your testing purposes.

Regards,
Larry Kluger
larryk@arx.com

More about digital signatures
There are compatible US and international standards for digitally signing pdfs, and other types of datasets (xml, etc). 
For pdf's, the standards are:  ISO 32000-1:2008  FIPS 186-3 from NIST and  ETSI.org PAdES TS 102 778 (search for PAdES here)

The signatures can be correctly viewed when using Adobe reader (standalone or as a plugin), and other pdf viewers too. See below for more info.

The standards are obtuse and have many options that are either usually or rarely used by the digital signature ISV community. If you would like more info about this or interoperability issues, please let us know. ARX is 25 years old and we have a great deal of development expertise in these cryptographic issues.

**Comment by timvandermeij** [comment] 2020-09-06 17:32
Closing since this is a duplicate of #1076.

**Closed by timvandermeij** 2020-09-06 17:32 UTC
Labels: 2-feature, 4-digital-signature
