### ISSUE TITLE
PDF.js displays the document empty

### ISSUE THREAD

**Issue by Documenti** [mozilla/pdf.js#12434] opened 2020-10-01 14:00 UTC
Attach (recommended) or Link to PDF file here:

[10000135.pdf](https://github.com/mozilla/pdf.js/files/5312465/10000135.pdf)
[10000136.pdf](https://github.com/mozilla/pdf.js/files/5312466/10000136.pdf)
[10000134.pdf](https://github.com/mozilla/pdf.js/files/5312467/10000134.pdf)

Configuration: 
- Web browser and its version: Firefox 81.0
- Operating system and its version: Windows 10.0.18363
- PDF.js version: All versions inclusive latest on https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension:

Steps to reproduce the problem:
1. load example PDFs with pdf.js
2.

What is the expected behavior? (add screenshot)
![grafik](https://user-images.githubusercontent.com/72209106/94818954-fca23f00-03fe-11eb-928d-233a3a3d1bd9.png)

What went wrong? (add screenshot)
![grafik](https://user-images.githubusercontent.com/72209106/94818887-e5fbe800-03fe-11eb-8e4a-8ccb7cd44b8b.png)

**Comment by Snuffleupagus** [comment] 2020-10-01 14:05
Duplicate of #12306

**Comment by Documenti** [comment] 2020-10-01 14:27
I am not sure if the cause is identical.
We were able to identify the problem in the content stream that pdf.js cannot interpret. There is an unnecessary clipping at the page margin inserted at the beginning of the page description. 
pdf.js seems to fail to position this clipping correctly.

**Comment by Snuffleupagus** [comment] 2020-10-01 14:29
> There is an unnecessary clipping at the page margin inserted at the beginning of the page description.

But that's *exactly* what issue #12306 is about, see https://github.com/mozilla/pdf.js/issues/12306#issuecomment-684618086

**Comment by calixteman** [comment] 2020-10-01 14:35
Canvas.clip with no path is clipping to nothing so nothing is displayed.

**Comment by Snuffleupagus** [comment] 2020-10-01 19:41
> Is this the same issue as #12431?

Not at all, since that one seems platform and/or browser specific.

---

Anyway, as mentioned previously, *this* issue is a duplicate of #12306.

**Closed** 2020-10-01 20:23 UTC
