### ISSUE TITLE
The PDF file has links, but when opened with PDF.js, there are no links.

### ISSUE THREAD

**Issue by huimei123** [mozilla/pdf.js#11053] opened 2019-08-08 06:20 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. The PDF file has links, but when opened with PDF.js, there is no link, and it becomes a span tag.
2.
![image](https://user-images.githubusercontent.com/28640116/62679609-a054b280-b9e7-11e9-86b7-e41d635bc7fa.png)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by huimei123** [comment] 2019-08-08 06:22
I hope I can click the click

**Comment by Snuffleupagus** [comment] 2019-08-08 06:55
Unless you provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md this issue will be closed as INCOMPLETE.

**Comment by huimei123** [comment] 2019-08-08 07:21
I updated the document on GitHub. You can reply to me when you are free. Thank you.


------------------ 原始邮件 ------------------
发件人: "Jonas Jenwald"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午2:56
收件人: "mozilla/pdf.js"<pdf.js@noreply.github.com>;
抄送: "千笔"<1009628609@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mozilla/pdf.js] The PDF file has links, but when opened withPDF.js, there are no links. (#11053)




Unless you provide all of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md this issue will be closed as INCOMPLETE.

**Comment by huimei123** [comment] 2019-08-08 08:19
Attach (recommended) or Link to PDF file here:
http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=DoulosSIL-features5.000.pdf&filename=DoulosSIL-features5.000.pdf

Configuration:
- Web browser and its version:
Google Chrome  version: 75.0.3770.142（正式版本） （64 位）

- Operating system and its version:
- PDF.js version:
pdfjsVersion = '2.3.63';
- Is a browser extension:

Steps to reproduce the problem:
1. 
1. <iframe name="my-viewer" class="pdf-viewer dev-course" :src="'/static/pdf/web/viewer.html?file=/static/pdf/devCourse.pdf'" scrolling="no">
    Your browser does not support PDF reading
    </iframe>
2.

What is the expected behavior? (add screenshot)
can click the link of pdf 

What went wrong? (add screenshot)

https://user-images.githubusercontent.com/28640116/62682154-06dccf00-b9ee-11e9-9778-f3dcbf7390b5.png
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-08-08 08:27
Duplicate of #3172.

**Closed** 2019-08-08 21:26 UTC
