### ISSUE TITLE
pdf.js displays hidden layers

### ISSUE THREAD

**Issue by stephanrauh** [mozilla/pdf.js#11589] opened 2020-02-12 20:16 UTC
Attach (recommended) or Link to PDF file here:
[hidden-layers.pdf](https://github.com/mozilla/pdf.js/files/4194800/hidden-layers.pdf)

Configuration:
- Web browser and its version: any
- Operating system and its version: any
- PDF.js version: both 2.3.200 and 2.4.351
- Is a browser extension: no

Steps to reproduce the problem:
1. navigate to https://mozilla.github.io/pdf.js/web/viewer.html
2. open the file I've attached

What is the expected behavior? (add screenshot)
The PDF file consists of four blocks and six layers. According to @Jonani92 who reported this bug on ngx-extended-pdf-viewer (https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/181), layers 1,2,3 and 6 are hidden in Acrobat Reader. Unfortunately, pdf.js displays them.

Overview over the layers of the document: 
1. Hidden
2. No print
3. Hidden no print
4. Guide
5. Guide no print
6. Headline

What went wrong? (add screenshot)
pdf.js seems to display everything:
![image](https://user-images.githubusercontent.com/3045767/74373369-9a97b980-4ddc-11ea-8aa2-585faa540ca8.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
mozilla.github.io/pdf.js suffices to reproduce the bug.

**Comment by Snuffleupagus** [comment] 2020-02-12 20:45
Duplicate of #269.

**Closed** 2020-02-12 22:36 UTC
