### ISSUE TITLE
PDF fonts Misrendered 

### ISSUE THREAD

**Issue by marcosps** [mozilla/pdf.js#10352] opened 2018-12-12 18:42 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox Nightly, 65.0a1 (2018-12-10) 
- Operating system and its version: openSUSE Leap 15
- PDF.js version: Firefox Nightly version
- Is a browser extension:

Steps to reproduce the problem:
1. Open https://www.intel.com/content/dam/www/public/us/en/documents/product-briefs/scsi-accessed-enclosures.pdf
2. See the misrendered fonts

What is the expected behavior? (add screenshot)
Evince:

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://www.intel.com/content/dam/www/public/us/en/documents/product-briefs/scsi-accessed-enclosures.pdf

**Comment by brendandahl** [comment] 2018-12-12 20:19
Looks fine to me, can you attach screenshots?

**Comment by marcosps** [comment] 2018-12-12 23:09
Sorry, I forgot to add the print screen. Mine Firefox Nightly comes from Flatpak: https://firefox-flatpak.mojefedora.cz/

I don't know if this has something different from the "normal" Nightly distribution.

Is the image bellow enough to show the problem? I can't see errors in console.

![image](https://user-images.githubusercontent.com/1039418/49904624-7ee7fa80-fe49-11e8-8c48-d386719d5da8.png)

**Comment by timvandermeij** [comment] 2018-12-13 21:59
Yes, this does make the issue more clear. However, I can't reproduce it. Could you try the regular (stable) Firefox or an official nightly? It might be a bug in Nightly.

**Comment by jaswdr** [comment] 2018-12-17 11:22
I haven't this problem too, using Firefox Quantum 63.0.3 (64-bit) on OpenSUSE Tumbleweed, default font Roboto (16pt), zoom at 300%, see screenshot bellow:

![image](https://user-images.githubusercontent.com/6409113/50084044-ca4d3080-01dc-11e9-948a-d0043f8ac456.png)

**Comment by brendandahl** [comment] 2018-12-18 18:36
> Should I open a bug in another place regarding this issue with flatpak?

I think that would be good. Maybe they're changing some prefs? Also, do you see anything in the web console?

**Comment by marcosps** [comment] 2018-12-18 18:43
@brendandahl anything on console, so I opened a bug in flatpak repo. Thanks!

**Comment by timvandermeij** [comment] 2018-12-18 21:41
I'll close this issue since it does not look like a problem on the PDF.js side. If there is something that needs fixing here, feel free to let us know and we can reopen. Thank you.

**Closed by timvandermeij** 2018-12-18 21:41 UTC
Labels: 1-other
