### ISSUE TITLE
The incorrect font when you print a document

### ISSUE THREAD

**Issue by juicylevel** [mozilla/pdf.js#6781] opened 2015-12-19 11:18 UTC
Hello! I opened using pdf.js document. The font is displayed correctly. But after the printing font of Firefox is not correct. The build downloaded from https://github.com/mozilla/pdf.js/archive/gh-pages.zip

In pdf viewer:

![Image of imglink](http://imglink.ru/pictures/19-12-15/5a904ee97662b61ec31cbb76a92833ad.jpg)

After printing:

![Image of imglink](http://imglink.ru/pictures/19-12-15/8984676ce4bc5d15f469fc1e661cf227.jpg)

What could be the reason?

**Comment by timvandermeij** [comment] 2015-12-19 13:11
Closing as duplicate of #6498.

**Closed by timvandermeij** 2015-12-19 13:11 UTC

**Comment by juicylevel** [comment] 2015-12-20 06:53
I did not understand, the problem has already been solved [GitHub](https://github.com/mozilla/pdf.js/issues/6498)?

**Comment by timvandermeij** [comment] 2015-12-20 11:50
No, the problem is not solved, but it is being tracked in the mentioned issue, so there is no need to have exact duplicate issues open.

**Comment by juicylevel** [comment] 2015-12-21 06:46
Thanks!
