### ISSUE TITLE
Doesn't render PDF,  shows empty canvas.

### ISSUE THREAD

**Issue by aonyskiv** [mozilla/pdf.js#9060] opened 2017-10-23 12:07 UTC
Attach (recommended) or Link to PDF file here:
[Plumbing_History_Revised.pdf](https://github.com/mozilla/pdf.js/files/1406939/Plumbing_History_Revised.pdf)

Configuration:
- Web browser and its version: Chrome 56.0.2924.87 (64-bit)
- Operating system and its version: Windows, Linux, doesn't depend on OS
- PDF.js version: 1.9.450
- Is a browser extension: no

Doesn't render attached PDF, shows empty canvas. 1.3.91 PDF.js version renders well.

Thank you.

**Comment by zhmura** [comment] 2017-10-23 12:13
[creative_writing.pdf](https://github.com/mozilla/pdf.js/files/1406998/creative_writing.pdf)
The same issue with the same config for document above (page #3)

**Comment by Snuffleupagus** [comment] 2017-10-23 21:15
WFM, using PDF.js version `1.10.80` in Firefox Nightly 58 on Windows.

Is the issue reproducible in the *latest* version of PDF.js?
To test this, please try opening the PDF file in question with the demo viewer (by clicking on the "Open File" button on the right-hand side of the toolbar), available at https://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by aonyskiv** [comment] 2017-10-25 10:05
Yes, it is reproducible in the latest version. 
Attached pdf is rendered by https://mozilla.github.io/pdf.js/web/viewer.html, but is is rendered with multiple div elements like simple html document. It is rendered by different PDF Readers, Acrobat Reader for example or chrome browser. In our application it tries to be rendered with canvas and it doesn't work.

Thanks

**Comment by yurydelendik** [comment] 2017-10-25 13:14
> multiple div elements like simple html document

Can you attach the screenshot?

**Comment by aonyskiv** [comment] 2017-10-27 09:48
Ups, im sorry. It is rendered with canvas.

**Comment by yurydelendik** [comment] 2017-10-27 13:21
> It is rendered with canvas.

This issue can be closed, is it correct? Otherwise, we are missing information to reproduce the issue.

**Comment by timvandermeij** [comment] 2017-10-27 20:09
Closing since it cannot be reproduced and it's indicated that it works using canvas rendering.

**Closed by timvandermeij** 2017-10-27 20:09 UTC
Labels: 4-information-requested
