### ISSUE TITLE
Use a saved edited pdf file the ink can't drag

### ISSUE THREAD

**Issue by SeanWang0403** [mozilla/pdf.js#17297] opened 2023-11-20 08:45 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome(119.0.6045.159 )
- Operating system and its version: mac(13.5)
- PDF.js version: v3.11.174
- Is a browser extension: no

Steps to reproduce the problem:
1. Use ink to draw something
2. Save pdf
3. Replace example pdf file
4. Reload web
5. Use ink

What is the expected behavior? (add screenshot)
Like freetext can drag
<img width="1470" alt="截圖 2023-11-20 下午4 34 24" src="https://github.com/mozilla/pdf.js/assets/24874184/ce5a9510-0e6d-47a7-923d-f59a443091e3">

What went wrong? (add screenshot)
Ink can't drag
<img width="1470" alt="截圖 2023-11-20 下午4 34 29" src="https://github.com/mozilla/pdf.js/assets/24874184/e1871018-8975-4545-b3ea-6e12130781bc">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-11-20 08:51
Duplicate of #16883 (which is a best guess, since the STR is a slightly difficult to understand).

> PDF.js version: v3.11.174

Note that that version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Closed by Snuffleupagus** 2023-11-20 08:51 UTC
