### ISSUE TITLE
Highlighted text doesn't always match up with text

### ISSUE THREAD

**Issue by deweydb** [mozilla/pdf.js#5387] opened 2014-10-08 00:24 UTC
Sometimes there are spaces in the highlighted text between words.  Sometimes there are no spaces.  Sometimes the highlighting is not fully covering a letter.
![screen shot 2014-10-07 at 5 21 06 pm](https://cloud.githubusercontent.com/assets/885167/4552313/483d94bc-4e81-11e4-858b-46cc7f42c4b8.png)

for example between the words "home" and "oxygen" on the last line.

**Comment by timvandermeij** [comment] 2016-10-13 14:17
Closing as duplicate of other text layer alignment issues. Furthermore the link is dead.

**Closed by timvandermeij** 2016-10-13 14:17 UTC
Labels: 4-text-selection
