### ISSUE TITLE
White crosses appear on images in Chromium browsers

### ISSUE THREAD

**Issue by kbuckinx** [mozilla/pdf.js#12660] opened 2020-11-25 09:46 UTC
Attach (recommended) or Link to PDF file here:
[Presentación eService Tutoriales de Usuario.pdf](https://github.com/mozilla/pdf.js/files/5595733/Presentacion.eService.Tutoriales.de.Usuario.pdf)

Configuration:
- Web browser and its version: Chrome 87, Edge Chromium 87
- Operating system and its version: tested on Mac OSX 10.15.7, Windows 10
- PDF.js version: 2.0.0
- Is a browser extension: no

Steps to reproduce the problem:
1. open the attached PDF in web/viewer.html
2. notice the blue background boxes get a white cross in chromium browsers

What is the expected behavior? (add screenshot)
![Screenshot 2020-11-24 at 15 03 57](https://user-images.githubusercontent.com/71509781/100209259-f2d21f00-2f09-11eb-82bf-d7a0bd301220.png)

What went wrong? (add screenshot)
![Screenshot 2020-11-24 at 15 04 12](https://user-images.githubusercontent.com/71509781/100209307-ff567780-2f09-11eb-8500-f79376cf6f31.png)
I assumed this was a hidden layer that was somehow rendering. But I tried opening the PDF in Acrobat Pro and Illustrator and couldn't find these white crosses.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): localhost

**Comment by Snuffleupagus** [comment] 2020-11-25 10:11
Looks like a duplicate of #12650; note in particular https://github.com/mozilla/pdf.js/issues/12650#issuecomment-732160610.

> PDF.js version: 2.0.0

For future reference, please note that that version number has *never* existed.

**Comment by timvandermeij** [comment] 2020-11-25 20:25
Works for me using Firefox as well. Unfortunately this does like like one of the long list of Chromium-specific issues from https://github.com/mozilla/pdf.js/issues/12462#issuecomment-713878908 that needs to be addressed upstream, so there is nothing we can do about this here.

**Closed by timvandermeij** 2020-11-25 20:25 UTC
