### ISSUE TITLE
Nonuniform filling background

### ISSUE THREAD

**Issue by jul059** [mozilla/pdf.js#7976] opened 2017-01-20 01:18 UTC
Link to PDF file (or attach file here): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2465600/pdf/938.pdf

Configuration:
- Web browser and its version: Firefox 50.1.0
- Operating system and its version: Windows 7 SP1 x64
- PDF.js version according to "resource://pdf.js/build/pdf.js" : 1.5.365
- Is an extension: no

Steps to reproduce the problem:
1. Open the file with Firefox 50.1.0 and go to page 5.
2. At the top left, the background of the "Box 2" element is not uniform.

The expected behaviour in Adobe Pro Extended 9.5 is :
![image](https://cloud.githubusercontent.com/assets/25236477/22131684/f21342a0-de82-11e6-8fac-7b3b21620f9e.png)

PDF.js within Firefox displays the following :
![image](https://cloud.githubusercontent.com/assets/25236477/22131754/5525e208-de83-11e6-9b36-6098c475569f.png)

Note that the image size differs since 100% in Adobe Pro is different from 100% in PDF.js. Also note that the dark colour seems slightly different, which may or may not be related to the issue.

**Comment by timvandermeij** [comment] 2017-01-21 01:04
Closing as duplicate of #4860.

**Closed by timvandermeij** 2017-01-21 01:04 UTC
