### ISSUE TITLE
Warning: Knockout groups not supported.

### ISSUE THREAD

**Issue by Liestambeur** [mozilla/pdf.js#9241] opened 2017-12-05 12:46 UTC
Attach (recommended) or Link to PDF file here:
[Pdfpage-353221_1.pdf](https://github.com/mozilla/pdf.js/files/1531128/Pdfpage-353221_1.pdf)

Configuration:
- Web browser and its version: Chrome ( 62.0.3202.94) Safari (11.0.2 )
- Operating system and its version: macOS Sierra 10.12.6
- PDF.js version: 1.8.254

Steps to reproduce the problem:

1. render pdf

What is the expected behavior? (add screenshot)
<img width="766" alt="screen shot 2017-12-05 at 13 40 46" src="https://user-images.githubusercontent.com/2464070/33607605-01cc85cc-d9c2-11e7-87b9-c9a218cdbd31.png">
What went wrong? (add screenshot)
<img width="903" alt="screen shot 2017-12-05 at 13 40 34" src="https://user-images.githubusercontent.com/2464070/33607584-f35b7200-d9c1-11e7-92a2-5156e16c6d9a.png">

The pdf is only partly rendered and I get a warning ' Knockout groups not supported'

**Comment by Snuffleupagus** [comment] 2017-12-05 12:51
Closing as duplicate of e.g. issue #3136.

**Closed by Snuffleupagus** 2017-12-05 12:51 UTC
