### ISSUE TITLE
PDFs with form fields crash in Safari

### ISSUE THREAD

**Issue by jhacksworth** [mozilla/pdf.js#13726] opened 2021-07-13 23:39 UTC
The following PDFs from the `test/pdfs/` directory crash the viewer in Safari:

- `test/pdfs/160F-2019.pdf` 
- `test/pdfs/annotation-text-widget.pdf`
- `test/pdfs/issue12963.pdf`
- `test/pdfs/issue6127.pdf`
- `test/pdfs/prefilled_f1040.pdf`

### Affected version

- Commit: a17bd1302
- Date: 2021-07-13
- `pdfjs.config`:

        {
          "betaVersion": "2.9.359",
          "stableVersion": "2.8.335",
          "baseVersion": "e667c8cbcf8a8368dfab5eccb6b6f7999f1ae275",
          "versionPrefix": "2.10."
        }

### Affected platforms

Safari on the following OS's:

- MacOS 11.4 Big Sur (Safari 14.1.1)
- iPadOS 14.6
- iOS 14.6

### Steps to reproduce

1. Install and then run web server:

        $ git clone https://github.com/mozilla/pdf.js.git
        $ cd pdf.js
        $ npm install
        $ gulp server

2. Open <http://localhost:8888/test/pdfs/?frame> in Safari.

3. Click on top link in list, for `160F-2019.pdf`

### Expected result

File `160F-2019.pdf` is rendered correctly.

### Actual result

The web page crashes with the error:

    A problem repeatedly occurred with "localhost:8888/test/pdfs/?frame"

There are no errors logged in the JavaScript console.

### Additional notes

- Here is a .gif showing the issue:
![screen600](https://user-images.githubusercontent.com/286057/125538408-f062e59a-10e4-449d-8eb3-2f3cfe57baa7.gif)

- These PDFs load properly and also have (some) form fields:

    - `test/pdfs/annotation-tx.pdf`
    - `test/pdfs/annotation-tx2.pdf`
    - `test/pdfs/annotation-tx3.pdf`
    - `test/pdfs/bug1669099.pdf`
    - `test/pdfs/doc_actions.pdf`
    - `test/pdfs/evaljs.pdf`
    - `test/pdfs/issue12504.pdf`
    - `test/pdfs/issue12706.pdf`
    - `test/pdfs/issue12750.pdf`
    - `test/pdfs/issue13269.pdf`
    - `test/pdfs/issue13271.pdf`
    - `test/pdfs/issue9972-1.pdf`
    - `test/pdfs/issue9972-2.pdf`
    - `test/pdfs/issue9972-3.pdf`
    - `test/pdfs/js-authors.pdf`
    - `test/pdfs/js-buttons.pdf`
    - `test/pdfs/js-colors.pdf`
    - `test/pdfs/listbox_actions.pdf`
    - `test/pdfs/pr12828.pdf`

**Comment by Snuffleupagus** [comment] 2021-07-14 07:41
> * Open http://localhost:8888/test/pdfs/?frame in Safari.
> * Click on top link in list, for `160F-2019.pdf`

Can those PDF documents be opened successfully in the *built* viewer, you can test with https://github.com/mozilla/pdf.js#online-demo (where you can either use the "Open File" button, or drag-and-drop to open the files)?

**Comment by ahasan09** [comment] 2021-07-14 09:00
I also face this issue on iPhone & iPad for some of my pdf. Then I try it using [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html) this link, but here is the same issue. iPhone Safari & Chrome browser have same issue.

**Comment by Snuffleupagus** [comment] 2021-07-14 14:38
My only possible suggestion is that this is *somehow* related to the scripting-bundle loading/initialization not working correctly in the Safari browser, which could e.g. be tested in the following way:
1. Open the viewer, and wait for it to load.
2. Open the console, and run `PDFViewerApplication.preferences.set("enableScripting", false)`.
3. Re-load the viewer.
4. Try opening the troublesome PDF documents.

My *hunch* is that this could "fix" the problems described in this issue, however that'd also suggest that support for PDF-scripting is currently broken only in the Safari browser which seems strange (since it works in Mozilla Firefox and Google Chrome).

In any case, someone with access to Safari would need to debug this further (at least *some* familiarity with the PDF-scripting implementation would probably help as well).

**Comment by calixteman** [comment] 2021-07-14 15:35
I can reproduce on linux with epiphany (webkit-based browser) and https://mozilla.github.io/pdf.js/web/viewer.html in trying to open `160F-2019.pdf` form.
I get a: `RuntimeError: Out of bounds memory access (evaluating 'g.apply(null,k)')` in the console.
and of course I've no issue with a local server...

Anyway, I don't have any errors with: https://github.com/mozilla/pdf.js/blob/master/test/pdfs/js-colors.pdf
@jhacksworth could try this file too ?

If `js-colors.pdf` works for you too, I'd say that maybe something is wrong when we try to allocate some memory to initialize the sandbox:
https://github.com/mozilla/pdf.js/blob/a17bd13023b476db874e8ebe240e4d8969cb793e/src/pdf.sandbox.js#L78
and for any reason there is something wrong with the free:
https://github.com/mozilla/pdf.js/blob/a17bd13023b476db874e8ebe240e4d8969cb793e/src/pdf.sandbox.js#L90

I tried again (several times) and I cannot reproduce anymore.

**Comment by jhacksworth** [comment] 2021-07-14 16:28
@calixteman I can confirm that `js-colors.pdf` works fine in the online viewer and locally with Safari.

@Snuffleupagus I followed the instructions regarding `PDFViewerApplication.preferences.set("enableScripting", false)`, but there was no change in behavior.

**Comment by Snuffleupagus** [comment] 2021-07-14 16:40
> I followed the instructions regarding `PDFViewerApplication.preferences.set("enableScripting", false)`, but there was no change in behavior.

Sorry, but I have to ask: Are you absolutely sure that you followed *all* the steps outlined above, especially `3. Re-load the viewer.` *before* testing your files?

The reason for me asking is that code mentioned in https://github.com/mozilla/pdf.js/issues/13726#issuecomment-879995818 should no longer either load or run, with that preference correctly disabled.

**Comment by jhacksworth** [comment] 2021-07-14 18:26
@Snuffleupagus , sorry, I should have been more explicit. When I disable scripting support, there was no change with the crashing behavior of the file `160F-2019.pdf`, or any of the other files that I listed above as crashing:

- `test/pdfs/160F-2019.pdf` 
- `test/pdfs/annotation-text-widget.pdf`
- `test/pdfs/issue12963.pdf`
- `test/pdfs/issue6127.pdf`
- `test/pdfs/prefilled_f1040.pdf`

The file `js-colors.pdf` loads properly with scripting enabled and also disabled, but the buttons only work with scripting enabled. I thought @calixteman was asking if `js-colors.pdf` loaded without crashing, sorry if I mixed that up.

Here is a .gif of: 

1) Loading `js-colors.pdf` in the viewer with scripting support enabled.
2) Disabling scripting support and reloading the viewer and `js-colors.pdf`.
3) Loading `160F-2019.pdf` with scripting support still disabled and the crashing behavior  present.

![pref600](https://user-images.githubusercontent.com/286057/125672777-d571e2bc-c286-4c3e-a265-04c819fa8805.gif)

**Comment by jhacksworth** [comment] 2021-07-15 02:44
Some additional info—in the `system.log` for MacOS I see the following output as the result of the errors:

```
Jul 14 21:15:23 mbpro com.apple.xpc.launchd[1] (com.apple.WebKit.WebContent.2D1BEE8F-5BB3-44EF-A40E-3FDC261826A2[5362]): Service exited due to SIGSEGV | sent by exc handler[5362]
Jul 14 21:15:34 mbpro com.apple.xpc.launchd[1] (com.apple.WebKit.WebContent.11011FA7-8800-4913-839D-1BA2FC7E6D7A[5363]): Service exited due to SIGSEGV | sent by exc handler[5363]
```

**Comment by jhacksworth** [comment] 2021-07-23 22:30
I tracked down the cause of the crash to this line:

https://github.com/mozilla/pdf.js/blob/51f0a810851c311598748f637fb583b20b7dce03/src/display/annotation_layer.js#L900

The following PDFs from the `test/pdfs/` directory will no longer crash the viewer in Safari with that line commented out (although letter spacing is now messed up in certain cases):

    test/pdfs/160F-2019.pdf
    test/pdfs/annotation-text-widget.pdf
    test/pdfs/issue12963.pdf
    test/pdfs/issue6127.pdf
    test/pdfs/prefilled_f1040.pdf

It seems that Safari's CSS `calc` function can't handle `ch` units.

I created a minimum test for this, in case anyone with access to Safari wants to try it out:

```html
<!doctype html>
<html>
    <head>
        <title>CSS calc() with ch units</title>
        <style>
         #fail {letter-spacing: calc(1ch);}
        </style>
    </head>
    <body>
        <h1 id="fail">This will cause a crash</h1>
    </body>
</html>
```

I installed the Safari Technology Preview for Big Sur from here: https://developer.apple.com/safari/download/ and the bug is fixed there. For reference, I think this WebKit bug report and patch might be related to the crashing behavior:

- https://bugs.webkit.org/show_bug.cgi?id=216659
- https://trac.webkit.org/changeset/271688/webkit/

I have no idea when Safari will actually see this fix. In the meantime, the crashing behavior is present across MacOS, iOS and iPadOS.

**Comment by calixteman** [comment] 2021-07-26 13:55
Can't we just replace `1ch` by `0.5em` ? (see https://developer.mozilla.org/en-US/docs/Web/CSS/length#ch)

**Comment by Snuffleupagus** [comment] 2021-07-26 13:58
> Can't we just replace `1ch` by `0.5em` ?

Assuming that it's indeed the same bug, then https://bugs.webkit.org/show_bug.cgi?id=216659 contains a reduced test-case that uses `em` and that apparently *also* fails :-(

**Comment by jhacksworth** [comment] 2021-07-26 14:47
> Can't we just replace `1ch` by `0.5em` ? (see https://developer.mozilla.org/en-US/docs/Web/CSS/length#ch)

This works, but unfortunately it doesn't render the same. Here are screenshots from a part of `test/pdfs/annotation-text-widget.pdf`, using Chrome. The first is using `1ch`:

<img width="960" alt="Chrome - using 1ch" src="https://user-images.githubusercontent.com/286057/127007241-b7074dc3-2a15-46bf-aaa0-14c902e5ca5b.png">

The second is using `0.5em`:

<img width="958" alt="Chrome - using 0 5em" src="https://user-images.githubusercontent.com/286057/127007283-ee21885d-ca8c-4e4c-8e71-d48ae4708a68.png">

> Assuming that it's indeed the same bug, then https://bugs.webkit.org/show_bug.cgi?id=216659 contains a reduced test-case that uses em and that apparently also fails

I think that first test-case was too general. The [Further reduction](https://bugs.webkit.org/attachment.cgi?id=417528) test only uses `ex` units. The only units that I've found to crash using `calc` in `letter-spacing` are `ch` and `ex`. I'm not sure how helpful that is, though.

**Comment by jhacksworth** [comment] 2021-09-28 18:30
> I have no idea when Safari will actually see this fix. In the meantime, the crashing behavior is present across MacOS, iOS and iPadOS.

I can confirm that the CSS bug is now **fixed in Safari 15** on:

- MacOS (available for Big Sur & Catalina)
- ipadOS 15
- iOS 15

I put up a page for people to easily check if their browser version has this bug:

https://jhacksworth.github.io/safari-css-bug-test.html

That page won't load properly for browser versions with the bug.

**Comment by Snuffleupagus** [comment] 2021-09-29 08:23
Given https://github.com/mozilla/pdf.js/issues/13726#issuecomment-929517624 let's close this issue here, since:
 - This was clearly *a browser bug*, which has now been fixed. Given that a single line of very simple CSS was enough to "crash" the browser, you'd really hope that previous versions of Safari will be patched as well.
 - Historically, in the PDF.js project, we've always been reluctant to add browser-specific compatibility hacks in the main code-base for reasons of readability/maintainability/performance.
 - This only affects a small number of PDF documents, when Safari is used, since the document needs to contain forms *and* also have "comb"-fields.

**Closed by Snuffleupagus** 2021-09-29 08:23 UTC
Labels: 3-upstream, 4-safari-specific
