### ISSUE TITLE
Blurry PDF in Firefox built-in viewer with unknown mosaic

### ISSUE THREAD

**Issue by xuyuehang** [mozilla/pdf.js#12588] opened 2020-11-06 05:47 UTC
Attach (recommended) or Link to PDF file here:
[attachment.pdf](https://github.com/mozilla/pdf.js/files/5498856/4.1.pdf)

Configuration:
- Web browser and its version: Firefox 82
- Operating system and its version: Win10 x64
- PDF.js version: 
- Is a browser extension: yes, maybe?

Steps to reproduce the problem:
Open attachment in Firefox & Chrome, and you will find the difference.
![Compared](https://user-images.githubusercontent.com/17559985/98323524-ee11fd80-2024-11eb-82f7-d4fdc5681df6.png)
Unidentified mosaic appeared in Firefox, the whole is more blurred, and Chrome is cleaner. Also test in online demo, behave the same.

**Comment by Snuffleupagus** [comment] 2020-11-06 08:36
Looks like a duplicate of issue #11957.

**Closed** 2020-11-06 19:57 UTC
