### ISSUE TITLE
Cannot render a pdf file which is generate from MacOS preview

### ISSUE THREAD

**Issue by beyondkmp** [mozilla/pdf.js#17416] opened 2023-12-12 04:33 UTC
Attach (recommended) or Link to PDF file here:
[specia PDF.pdf](https://github.com/mozilla/pdf.js/files/13643707/specia.PDF.pdf)

Configuration:
- Web browser and its version:
latest version
- Operating system and its version:
Win11 and macOS 14
- PDF.js version:
latest
- Is a browser extension:
No

Steps to reproduce the problem:
open the pdf

What is the expected behavior? (add screenshot)
render is ok

What went wrong? (add screenshot)
cannot render

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
<img width="1082" alt="image" src="https://github.com/mozilla/pdf.js/assets/5462444/2ac7e368-be8f-4b8b-8478-fb0e355887e5">

**Comment by Snuffleupagus** [comment] 2023-12-12 09:05
Duplicate of #16782

---

> * Web browser and its version:
>   latest version
> 
> * Operating system and its version:
>   Win11 and macOS 14
> 
> * PDF.js version:
>   latest
> 
> * Is a browser extension:
>   No

*For future reference:* Please remember to fill out this part of the ISSUE_TEMPLATE properly, since "latest" isn't really helpful.

**Closed by Snuffleupagus** 2023-12-12 09:05 UTC

**Comment by beyondkmp** [comment] 2024-07-31 09:58
@Snuffleupagus #16782 has already been closed, but testing this PDF with the patched version from that MR still presents issues, so these two might not be the same problem. I hope to reopen this issue.

**Comment by Snuffleupagus** [comment] 2024-07-31 10:04
The document renders fine when opened with https://mozilla.github.io/pdf.js/web/viewer.html, so you likely need to update to the *latest* version: https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by beyondkmp** [comment] 2024-07-31 11:07
Cool, thanks very much.
