### ISSUE TITLE
Page scrolling works slow in Chrome with "Page Width" mode

### ISSUE THREAD

**Issue by dmitryskey** [mozilla/pdf.js#7684] opened 2016-10-02 13:59 UTC
Link to PDF file (or attach file here):
[ItextsharpPrintPackage.pdf](https://github.com/mozilla/pdf.js/files/504972/ItextsharpPrintPackage.pdf)
[PrintPackageActivePDF.pdf](https://github.com/mozilla/pdf.js/files/504973/PrintPackageActivePDF.pdf)

Configuration:
- Web browser and its version: 53.0.2785.116 m (64-bit)
- Operating system and its version: Windows 7 x64
- PDF.js version: 1.5.500
- Is an extension: No

Steps to reproduce the problem:
1. Open attached forms (the former is created in ActivePDF 2011, the latter in iTextSharp 5.2.1 or 5.5.9) in the viewer
2. Set the "Page Width" zooming and scroll to the page 7

What is the expected behavior? (add screenshot)

The scrolling is smooth.

What went wrong? (add screenshot)

Chrome starts working very slow, the following message is added to the console:
_Handling of 'wheel' input event was delayed for 189 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive. Viewer.js:9271_

Notes:
1. Scrolling works fine in Firefox, IE 11 and Safari@Mac
2. We checked both PDF.JS 1.4.20 and 1.5.500, it looks like that scrolling performance was improved in the 1.5 but it was still too slow.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Rob--W** [comment] 2016-10-02 23:51
1. Are you using hardware acceleration? (`chrome://gpu`)
2. How easily can you reproduce the problem? I have a beefy laptop and while scrolling through, I see some jank but nothing out of the ordinary. Sometimes I see that message with a delay of around 100ms.
3. Does the Timeline of the devtools show anything special? https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/timeline-tool?hl=en
4. Do you have any special mouse wheel settings? E.g. a high-resolution scrollwheel.
5. Do you have enough RAM? (if memory is scarce, I guess that garbage collection may be triggered more often and require more time to complete)

**Comment by dmitryskey** [comment] 2016-10-03 00:15
1.  Yes, please see attached file [chromegpu.pdf](https://github.com/mozilla/pdf.js/files/505320/chromegpu.pdf)
2. We were able to reproduce it in 3 corporate laptops
3. Yes - most of time is spent on painting, see attached 
![timelinerawdata-20161002t201029](https://cloud.githubusercontent.com/assets/1661986/19024918/d857efba-88dc-11e6-889b-e5a9b30ec073.png)

4. I tried it with 2 mouses - wireless and wired, so I don't think there are some special settings. Besides see point 2
5. We got this problem in corporate laptops with 8GB on board. Corporate desktops with 16gb seems working file. Also I noticed that laptops are using corporate TRITON AP-ENDPOINT web-sense tool, desktop seems under different web-sense tool.

**Comment by timvandermeij** [comment] 2019-09-15 13:12
Closing since this should be fixed by #11106 and other performance optimizations that were merged since this issue was opened.

**Closed by timvandermeij** 2019-09-15 13:12 UTC
Labels: 2-performance
