### ISSUE TITLE
Notification for PDF containing forms with pref enabled still displayed on some files

### ISSUE THREAD

**Issue by cfogelSV** [mozilla/pdf.js#12217] opened 2020-08-17 07:51 UTC
**Affected versions**
* 81.0a1 (2020-08-16)

**Affected platforms**
* Windows 10, macOS 11.0, Ubuntu 16;

**Steps to reproduce**
pdfjs.renderInteractiveForms - enabled

1. Launch Firefox;
2. Access a PDF form with fillable content such as [link](http://www.aloaha.com/wp-content/uploads/2016/07/SampleForm-1.pdf);
3. Click inside any field, start filling in data;

**Expected result**
* data is filled, no unexpected warning notifications appear;

**Actual result**
* warning banner for [Document containing forms & Filling of forms unsupported] is displayed;
 
Additional notes:
* S3 as suggested severity;
* attached screenshot with the issue;
<img width="624" alt="Screenshot 2020-08-17 at 10 45 29" src="https://user-images.githubusercontent.com/49230899/90371483-b6c03000-e077-11ea-8f37-98a087c129b8.png">

**Comment by Snuffleupagus** [comment] 2020-08-17 07:56
This is expected, note https://github.com/mozilla/pdf.js/pull/12201#issuecomment-672993338, and this issue is for all intents and purposes thus a duplicate of e.g. issue #2373.

**Comment by timvandermeij** [comment] 2020-08-17 13:36
Thinking about this a bit more, I think we should just ignore XFA for now since it's tracked in another issue and it's not blocking the filling/saving/printing of AcroForm forms. If both occur in a PDF document, we can remove the fallback bar and log a warning that XFA features are unsupported. AFAICT they are an extension and not vital for filling in forms, and looking at the above issue it's not likely to be implemented anytime soon, so showing the fallback bar in those cases seems incorrect.

**Closed** 2020-08-25 22:18 UTC
Labels: 1-viewer, 4-form-acroform
