### ISSUE TITLE
How to Extract XFA pdf form field details(i.e field name , value) using javascript

### ISSUE THREAD

**Issue by SubratTest** [mozilla/pdf.js#16157] opened 2023-03-15 09:49 UTC
Hi Team,

I want to extract the existing fields details inside a XFA pdf form once the form is loaded in the viewer.
On click of any button i want to get the field name and value for the field using javascript

**Comment by Snuffleupagus** [comment] 2023-03-15 09:53
Duplicate of #16156 (please don't open another issue for the same thing, especially when neither of them contain enough details to be easily actionable).

As already mentioned, there's no code available that'll do this and you'll have to implement it yourself.

**Closed by Snuffleupagus** 2023-03-15 09:53 UTC
