### ISSUE TITLE
Compilation Error in angular project when I try to upgrade my pdfjs-dist from 3.11.174 to 4.0.189

### ISSUE THREAD

**Issue by Srinivasan0311** [mozilla/pdf.js#18050] opened 2024-05-06 17:58 UTC
### Discussed in https://github.com/mozilla/pdf.js/discussions/17480

<div type='discussions-op-text'>

<sup>Originally posted by **Srinivasan0311** January  5, 2024</sup>
Attach (recommended) or Link to PDF file here: Any basic pdf can be used 

Configuration:
- Web browser and its version: chrome 120.0.6099.199 
- Operating system and its version: windows 11
- PDF.js version: 4.0.189
- Angular project version 16
- Is a browser extension: 

Steps to reproduce the problem:
1. upgrading pdfjs-dist using the command "npm i pdfjs-dist@4.0.189"
2. npm start

What is the expected behavior? (add screenshot)
Expected behaviour is should compile successfully without any errors.
What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/78212388/d545f8e9-52d7-4ab3-a9ad-b5ce80b2cc50)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
</div>

**Comment by timvandermeij** [comment] 2024-05-06 18:01
Closing since this is a duplicate of #17245; please refer to the discussion in that issue.

**Closed by timvandermeij** 2024-05-06 18:01 UTC
