### ISSUE TITLE
Pdf rendering problem. Colors are not rendering properly.

### ISSUE THREAD

**Issue by PriyankaKakade6837** [mozilla/pdf.js#13000] opened 2021-02-18 10:42 UTC
Attach (recommended) or Link to PDF file here:
[PAC4629 (2.2)_low (1).pdf](https://github.com/mozilla/pdf.js/files/6001793/PAC4629.2.2._low.1.pdf)

Configuration:
- Web browser and its version:
   Window 10 Chrome (Version 88.0.4324.182), Mac High sierra Chrome(Version 86.0.4240.111)
- PDF.js version: v2.3.200, v2.5.207

Steps to reproduce the problem:
1. Open original pdf in browser
2. Open same pdf in pdf js sample demo

What is the expected behavior? (add screenshot)
1. In original document you can see line draw by pencil is with color. Please find attached for the original pdf screenshot.
![OriginalPdf](https://user-images.githubusercontent.com/73522882/108345074-df320e00-7203-11eb-82b2-427ab52c9d90.PNG)

What went wrong? (add screenshot)
1. In original document you can see line draw by pencil is with color. But in rendered pdf it shows only with blue color. Please see attached for issue.
![ColorIssue](https://user-images.githubusercontent.com/73522882/108345190-fffa6380-7203-11eb-8b03-0659ed1bca8a.PNG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by janpe2** [comment] 2021-02-22 14:29
The pencil scribble is a stroked path with a shading pattern as the color. Looks like a duplicate of #10955.

**Closed** 2021-02-22 22:10 UTC
Labels: 1-core
