### ISSUE TITLE
Ability to search phrase and term simultaneously from URL parameter was lost

### ISSUE THREAD

**Issue by mainseq** [mozilla/pdf.js#13459] opened 2021-05-28 20:44 UTC
Configuration:
Chrome 90.0.4430.212
Steps to reproduce the problem:
1.  open URL: https://mozilla.github.io/pdf.js/web/viewer.html#SEARCH=dynamic%20application%3Dlogic%20machine%3Dcode&phrase=false

2. The phrases are no longer highlighting

What is the expected behavior? (add screenshot)
The older version highlights the term and the phrases

What went wrong? (add screenshot)
Somehow a line of code was removed from viewer.js that was in my original PR. I compared the files.

viewer.js line ~#3361
***

//check for phrase  
subquery = subquery.replace(/\=/ig, ' ');

***

This line allowed terms and phrases to be search simultaneously. Now you can only do one or the other.
The syntax was: 
1. dynamic application=logic machine=code 
2. then url encode to #SEARCH=dynamic%20application%3Dlogic%20machine%3Dcode 

The result was both the phrases and terms were highlighted. This no longer works. I am assuming it was removed to allow searching for the equals sign. But effectively it broke all the phrase searching...

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
See above

**Comment by timvandermeij** [comment] 2021-05-28 20:54
The pull request that got merged is https://github.com/mozilla/pdf.js/pull/5579/files and I also don't see that line in there, so did this really ever work? If so, you can use `git bisect` to find out which commit regressed this. There is unit test coverage now for the find controller, so if this is indeed a regression we should also add a unit test for this to avoid this happening again in the future.

**Comment by mainseq** [comment] 2021-05-28 21:34
The hundred or so other lines are there... so not sure where this line went. It is in my local branch.

**Comment by Snuffleupagus** [comment] 2021-05-29 07:03
> The older version highlights the term and the phrases

We've *never* had support for mixing phrase and term searches in the `PDFFindController` (and that thus includes searches from the URL); hence this issue as files in INVALID since this isn't a regression.

> Somehow a line of code was removed from viewer.js that was in my original PR.

Please note that as far as I know, we never merged any or your search-related PRs (see e.g. #5496 and #5497) since they contained too many unrelated changes, your use-case was somewhat specialized if I recall correctly, the implementations didn't really fit all that well into the PDF.js code-base, and they also tried to use non-standard hash-parameters.

As already mentioned in https://github.com/mozilla/pdf.js/issues/13459#issuecomment-850664985, what did land was PR #5579 which allowed *either* phrase or term searches.

There's a WIP PR, see #11749, which if accepted (it still requires a fair amount of work) would add the possibility of *combining* term and phrase searches when using the `PDFFindController` directly. (Please note however that it's *very* unlikely that the functionality would be exposed through the URL, since we really don't want to add any more non-standard hash-parameters.)

---

All-in-all, as already mentioned, it cannot be a regression if something has never worked and improving this further is already covered by existing issues/PRs; hence closing as INVALID.

**Closed by Snuffleupagus** 2021-05-29 07:03 UTC
Labels: 1-viewer
