### ISSUE TITLE
Problems rendering the "Fedra Serif A Std Medium" font

### ISSUE THREAD

**Issue by mahajangaurav** [mozilla/pdf.js#6782] opened 2015-12-19 22:22 UTC
I am using viewer.js (which in turn uses pdf.js) to render pdf documents in the browser. These documents are showing up fine with all fonts except the "Fedra Serif A Std Medium". While the uppercase characters for this font are showing fine, the lowercase characters are either missing or showing up as boxes depending on the browser used. Attached are the screenshots from chrome (Version 47.0.2526.106 m), IE 11 (v 11.0.9600.17031) & that showing the original text. 
![invalidtext](https://cloud.githubusercontent.com/assets/10227531/11915440/51ce074a-a674-11e5-86c8-b2e3f5b445c8.png)

Following is the console log from Chrome:
pdf.worker.js:224 Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
pdf.worker.js:232 Error: Not tracking location of CharStrings
pdf.worker.js:233     at error (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:233:17)
    at Object.CFFOffsetTracker_setEntryLocation [as setEntryLocation] (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21256:9)
    at Object.CFFCompiler_compile [as compile] (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21371:22)
    at Object.CFFFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:20224:28)
    at Object.Font (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:16998:11)
    at Object.PartialEvaluator_translateFont [as translateFont] (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:12514:14)
    at Object.PartialEvaluator_loadFont [as loadFont] (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11264:16)
    at handleSetFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11670:21)
    at next (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11809:22)
pdf.worker.js:224 Warning: Unsupported feature "unknown"
pdf.worker.js:224 Warning: Failed to compile font g_font_3
pdf.js:224 Warning: Unsupported feature "unknown"
pdf.js:224 Warning: Failed to load font "g_font_3": SyntaxError: Invalid font data in ArrayBuffer.
.
Following is the Console Log from IE:
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: viewerjs
HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>".
File: about:blank, Line: 1, Column: 1
HTML1405: Invalid character: U+0000 NULL. Null characters should not be used.
File: about:blank, Line: 1, Column: 14
HTML1507: Unexpected character: U+0000 NULL. Null characters should not be used.
File: about:blank, Line: 1, Column: 14
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: about:blank
SCRIPT1003: Expected ':'
File: compatibility.js, Line: 119, Column: 30
SCRIPT5007: Unable to get property 'namespaceURI' of undefined or null reference
File: viewerjs, Line: 75, Column: 283
SCRIPT438: Object doesn't support property or method 'forEach'
File: viewerjs, Line: 73, Column: 174
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Error: Not tracking location of CharStrings
   at error (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:233:5)
   at CFFOffsetTracker_setEntryLocation (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21256:9)
   at CFFCompiler_compile (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21371:7)
   at CFFFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:20224:7)
   at Font (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:16997:9)
   at PartialEvaluator_translateFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:12514:7)
   at PartialEvaluator_loadFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11263:9)
   at handleSetFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11670:9)
   at next (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11809:15)
Warning: Unsupported feature "unknown"
Warning: Unsupported feature "unknown"
Warning: Failed to compile font g_font_3
CSS3111: @font-face encountered unknown error.
File: wAAAAAAAALDAAAAAAAAAAAAAAAAAAABRgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAFGAAAAAAAUAPYAAQAAAAAAAAAQAAAAAQAAAAAAAQAbABAAAQAAAAAAAgAHACsAAQAAAAAAAwAIADIAAQAAAAAABAAbADoAAQAAAAAABQAMAFUAAQAAAAAABgAAAGEAAQAAAAAABwAHAGEAAQAAAAAACAAHAGgAAQAAAAAACQAHAG8AAwABBAkAAAAgAHYAAwABBAkAAQA2AJYAAwABBAkAAgAOAMwAAwABBAkAAwAQANoAAwABBAkABAA2AOoAAwABBAkABQAYASAAAwABBAkABgAAATgAAwABBAkABwAOATgAAwABBAkACAAOAUYAAwABBAkACQAOAVRPcmlnaW5hbCBsaWNlbmNlRkFBQUNCK0ZlZHJhU2VyaWZBU3RkTWVkaXVtVW5rbm93bnVuaXF1ZUlERkFBQUNCK0ZlZHJhU2VyaWZBU3RkTWVkaXVtVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUARgBBAEEAQQBDAEIAKwBGAGUAZAByAGEAUwBlAHIAaQBmAEEAUwB0AGQATQBlAGQAaQB1AG0AVQBuAGsAbgBvAHcAbgB1AG4AaQBxAHUAZQBJAEQARgBBAEEAQQBDAEIAKwBGAGUAZAByAGEAUwBlAHIAaQBmAEEAUwB0AGQATQBlAGQAaQB1AG0AVgBlAHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1
Error: Not tracking location of CharStrings
   at error (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:233:5)
   at CFFOffsetTracker_setEntryLocation (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21256:9)
   at CFFCompiler_compile (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:21371:7)
   at CFFFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:20224:7)
   at Font (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:16997:9)
   at PartialEvaluator_translateFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:12514:7)
   at PartialEvaluator_loadFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11263:9)
   at handleSetFont (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11670:9)
   at next (http://site.subdomain.domain/content/viewerjs/pdf.worker.js:11809:15)
Warning: Unsupported feature "unknown"
Warning: Failed to compile font g_font_3
Warning: Unsupported feature "unknown"
CSS3111: @font-face encountered unknown error.
File: wAAAAAAAALDAAAAAAAAAAAAAAAAAAABRgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAFGAAAAAAAUAPYAAQAAAAAAAAAQAAAAAQAAAAAAAQAbABAAAQAAAAAAAgAHACsAAQAAAAAAAwAIADIAAQAAAAAABAAbADoAAQAAAAAABQAMAFUAAQAAAAAABgAAAGEAAQAAAAAABwAHAGEAAQAAAAAACAAHAGgAAQAAAAAACQAHAG8AAwABBAkAAAAgAHYAAwABBAkAAQA2AJYAAwABBAkAAgAOAMwAAwABBAkAAwAQANoAAwABBAkABAA2AOoAAwABBAkABQAYASAAAwABBAkABgAAATgAAwABBAkABwAOATgAAwABBAkACAAOAUYAAwABBAkACQAOAVRPcmlnaW5hbCBsaWNlbmNlRkFBQUNCK0ZlZHJhU2VyaWZBU3RkTWVkaXVtVW5rbm93bnVuaXF1ZUlERkFBQUNCK0ZlZHJhU2VyaWZBU3RkTWVkaXVtVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUARgBBAEEAQQBDAEIAKwBGAGUAZAByAGEAUwBlAHIAaQBmAEEAUwB0AGQATQBlAGQAaQB1AG0AVQBuAGsAbgBvAHcAbgB1AG4AaQBxAHUAZQBJAEQARgBBAEEAQQBDAEIAKwBGAGUAZAByAGEAUwBlAHIAaQBmAEEAUwB0AGQATQBlAGQAaQB1AG0AVgBlAHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==

Urgent help will be greatly appreciated!
Thanks in advance!

**Comment by timvandermeij** [comment] 2015-12-20 11:48
viewer.js is, unfortunately, known for using out-of-date versions of PDF.js. Please try opening your file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar), which is the most recent version of PDF.js. The error messages you posted indicate that this is indeed an already fixed bug. If it still does not work with this link, please provide the PDF file here so we can look into it.

**Comment by mahajangaurav** [comment] 2015-12-20 19:23
Hello Tim! 
Thank you for your prompt response. I am able to replicate the issue with the web viewer at the above mentioned Url. Please find attached a sample pdf.

Thanks again and I am looking forward to your response. Keep up the great work!
Gaurav
[Viewer.js.pdf](https://github.com/mozilla/pdf.js/files/67917/Viewer.js.pdf)

**Comment by mahajangaurav** [comment] 2015-12-20 20:00
Sorry, I accidentally closed the issue instead of just adding the comment.
I also wanted to send this quick note that I am noticing this issue only in PDF/A compliant pdf files.I can view these files correctly in a reader such as the Adobe or FoxIt readers.
Thanks!

**Comment by timvandermeij** [comment] 2015-12-20 20:54
I can reproduce this on Windows 10 x64 with Firefox 43.0.1 and the development version of PDF.js. I suspect that this is a font conversion problem of PDF.js. The console output for further triage is below:

<pre>
Warning: Not enough parameters for vmoveto; actual: 0, expected: 1 pdf.worker.js:281:5
Error: Not tracking location of CharStrings pdf.worker.js:294:5
CFFOffsetTracker_setEntryLocation@https://mozilla.github.io/pdf.js/build/pdf.worker.js:31456:9
CFFCompiler_compile@https://mozilla.github.io/pdf.js/build/pdf.worker.js:31571:1
CFFFont@https://mozilla.github.io/pdf.js/build/pdf.worker.js:30424:19
Font@https://mozilla.github.io/pdf.js/build/pdf.worker.js:27171:11
PartialEvaluator_translateFont@https://mozilla.github.io/pdf.js/build/pdf.worker.js:37858:14
PartialEvaluator_loadFont@https://mozilla.github.io/pdf.js/build/pdf.worker.js:36447:1
PartialEvaluator_handleSetFont@https://mozilla.github.io/pdf.js/build/pdf.worker.js:36216:14
next@https://mozilla.github.io/pdf.js/build/pdf.worker.js:36618:22
PartialEvaluator_getOperatorList@https://mozilla.github.io/pdf.js/build/pdf.worker.js:36550:1
Page_getOperatorList/pageListPromise<@https://mozilla.github.io/pdf.js/build/pdf.worker.js:39722:16
 pdf.worker.js:295:1
Warning: Failed to compile font g_d1_f1 pdf.worker.js:281:5
downloadable font: CFF : zero-length table (font-family: "g_d1_f1" style:normal weight:normal stretch:normal src index:0) source: (invalid URI) <onbekend>
downloadable font: rejected by sanitizer (font-family: "g_d1_f1" style:normal weight:normal stretch:normal src index:0) source: (invalid URI) <onbekend>
downloadable font: font load failed (font-family: "g_d1_f1" style:normal weight:normal stretch:normal src index:0) source: (invalid URI) <onbekend>
Warning: Failed to load font ""g_d1_f1"": SyntaxError: An invalid or illegal string was specified pdf.js:281:5
</pre>

**Comment by timvandermeij** [comment] 2015-12-20 20:57
@mahajangaurav Could we use your sample PDF for our test suite when we fix this issue, to avoid regressions in the future?

**Comment by mahajangaurav** [comment] 2015-12-21 09:51
Hey Tim
Absolutely! Thank you for checking an your prompt help!
Cheers
Gaurav

**Comment by mahajangaurav** [comment] 2015-12-27 18:15
Hey Tim
Just wanted to check with you to see if there's an ETA for a fix for this issue?
Cheers 
Gaurav

**Comment by timvandermeij** [comment] 2015-12-27 21:32
@mahajangaurav Not yet. It is usually difficult to find the cause of these types of font issues, so it might take some time when someone looks into it.

**Comment by mahajangaurav** [comment] 2015-12-28 13:34
@timvandermeij Thanks! We urgently need this before our application can go live. Will it be possible for you to provide an approximate time-frame (days/ weeks/ months) so I can set the right expectations? Also, please do let me know if I can be of any additional help.
Thanks again for your prompt responses!

**Comment by timvandermeij** [comment] 2015-12-28 14:21
I really cannot say. Maybe @brendandahl or @Snuffleupagus could triage this issue to determine how much time it will take, if they have time.

**Comment by mahajangaurav** [comment] 2015-12-30 12:05
@timvandermeij Thanks! 
@brendandahl or @Snuffleupagus Will it be possible for you to provide me with a rough time frame so I can set some expectations?

**Comment by Snuffleupagus** [comment] 2015-12-30 12:30
> Will it be possible for you to provide me with a rough time frame so I can set some expectations?

First of all, please understand that debugging/fixing font issues can be both time-consuming and difficult.
I thus don't think that it's possible to provide a time-frame for this work, hence this issue will be fixed once someone with enough knowledge/time looks into it.

If waiting for a fix is a problem, then my only suggestion (I understand that it's not a particularly good one, or that it might even be unfeasible) is to try and use a different font in the meantime.

**Comment by mahajangaurav** [comment] 2015-12-30 12:48
Thanks. Unfortunately due to corporate branding guidelines/ restrictions using an alternate font is not an option.

Also, just to be sure, I am not looking for a hard timeline. All I am looking for is a rough idea of a time frame in terms of weeks or months or if it could potentially be even an year before the issue gets fixed. 

I understand if you are telling me you cannot even provide me with that level of an estimate but want to be sure I make myself clear on what is it that I am requesting from you.

Thanks!

**Comment by brendandahl** [comment] 2016-01-05 19:55
I did a little investigation. The problem is the font descriptor says the font is a CIDFontType0C so we parse the font data as a CFF font. However, the font is actually an open type font so we need to parse those tables then pass the real charstring data in to the cff parser. Not a trivial change, so I won't be fixing this quickly.

**Comment by mahajangaurav** [comment] 2016-01-06 15:57
@brendandahl Thanks Brendan. I appreciate your working on the fix. So do you think it would help getting the descriptor fixed by the font owners (if they agree to fixing it that is)?
Thanks!

**Comment by timvandermeij** [comment] 2016-01-06 16:00
Fixing the font itself would indeed be the best solution. Note that we do have a patch for this issue at #6839 now, but it needs review to determine if we can land it or not.

**Comment by brendandahl** [comment] 2016-01-06 19:12
> @brendandahl Thanks Brendan. I appreciate your working on the fix. So do you think it would help getting the descriptor fixed by the font owners (if they agree to fixing it that is)?
> Thanks!

The font descriptor is meta data about the font and is part of the PDF itself, so you'd need to fix it in the PDF.

**Comment by mahajangaurav** [comment] 2016-01-07 16:46
@timvandermeij @brendandahl Thank you again for your prompt help and for your inputs. So do we know how soon we can get an updated release for Viewer.js?
**Brendan**: We are using Aspose.words to build the pdf so maybe it is picking it from the font descriptor itself? Could that be a possibility?

**Closed** 2016-01-11 16:56 UTC
Labels: 4-font-conversion, 4-font-type0
