### ISSUE TITLE
Define File url manually in viewer.html

### ISSUE THREAD

**Issue by robiulala** [mozilla/pdf.js#7667] opened 2016-09-23 10:26 UTC
I am using the prebuilt version of pdf.js (1.4.20)

I am trying to define PDF File url manually from viewer.html but not being able to do this.

To be more specific, I'll actually use an encoded url which I'll decode on viewer.php (viewer.html)

Can anyone please tell me how can I assign file url manually in viewer.html ?

Thanks

**Comment by yurydelendik** [comment] 2016-09-23 16:14
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-specify-a-different-pdf-in-the-default-viewer . Closing as answered.

**Closed by yurydelendik** 2016-09-23 16:14 UTC

**Comment by robiulala** [comment] 2016-10-17 12:20
Thanks for your reply.
It worked with version 1.4.20 but I'm getting an error on newer versions. The error I get in console is:

`Uncaught ReferenceError: PDFViewerApplication is not defined`

**Comment by yurydelendik** [comment] 2016-10-17 12:56
Please be more specific: there is nothing we can do if we are not able to reproduce the issue you are experiencing.

**Comment by robiulala** [comment] 2016-10-17 13:06
Ok,
Please have a look at this screenshot, This is how I added the code to viewer.html: http://prnt.sc/cvdk3e
And
This is the error I get when I open viewer on browser: http://prntscr.com/cvdlup

Please let me know if you need any more details.

Thanks

**Comment by yurydelendik** [comment] 2016-10-17 13:09
The error is correct `PDFViewerApplication is not defined` at the spot we are inserting it. Please find different location.

**Comment by robiulala** [comment] 2016-10-17 13:15
I've tried in different locations but no luck. Won't it work from viewer.html ?

If it supposed to work in viewer.html, can you suggest a place please ?

Thanks
