### ISSUE TITLE
Two page spread view

### ISSUE THREAD

**Issue by mishimu** [mozilla/pdf.js#2376] opened 2012-11-13 18:40 UTC
Hi, is it possible to view the pdf as a two page spread and add a left-right sliding functionality on top? I picture this to work on touch screen devices too but not sure if this is feasible?

Thanks in advance.

**Comment by Snuffleupagus** [comment] 2015-02-13 17:06
Closing as duplicate of issue #590.

**Closed by Snuffleupagus** 2015-02-13 17:06 UTC
Labels: 2-feature

**Comment by collinanderson** [comment] 2019-04-02 16:24
For anyone finding this feature request from Google, this feature can now be found under the top-left menu as "Spreads"

![image](https://user-images.githubusercontent.com/129234/55419061-00bb7b00-5542-11e9-9eb9-582afce340e1.png)
