### ISSUE TITLE
PDF generated from Illustrator renderes disabled layers

### ISSUE THREAD

**Issue by tiriana** [mozilla/pdf.js#11395] opened 2019-12-09 13:17 UTC
Example file: [Dokument-3.pdf](https://github.com/mozilla/pdf.js/files/3939750/Dokument-3.pdf)

File in question has three layers, where two of them are disabled. When the file is opened on Windows, it shows only the visible layer. When it is opened with a pdf.js previewer, all three layers are visible. It caused an issue for our customer when a disabled layer covered completely the enabled one and made the file look like it was not updated.

Configuration:
- Chrome 78 and FF 70:
- Windows 10:
- PDF.js version: 1.9.661
- It also occurs on the demo: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: No

Steps to reproduce the problem:
1. Open attached file in pdf.js viewer
2. See that disabled layers are rendered

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/5216143/70438308-cbcad500-1a8d-11ea-941d-52490c07dd9d.png)

What went wrong? (add screenshot)
Disabled layers were rendered 
![image](https://user-images.githubusercontent.com/5216143/70438555-62979180-1a8e-11ea-8614-16d303c8bdba.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://phantombit.egnyte.com/dl/xMWOei36xc

**Comment by Snuffleupagus** [comment] 2019-12-09 13:40
Duplicate of #269.

**Closed** 2019-12-09 20:57 UTC
