### ISSUE TITLE
Image with Flate and Jpeg2000 does not work.

### ISSUE THREAD

**Issue by JimPalo** [mozilla/pdf.js#14441] opened 2022-01-11 16:24 UTC
Java and .net fail on image with Flate and Jpeg2000

Just decompress and it crashes.
[1.-9-8-2.pdf](https://github.com/mozilla/pdf.js/files/7848202/1.-9-8-2.pdf)

**Comment by Snuffleupagus** [comment] 2022-01-11 16:28
Duplicate of #12738

**Closed by Snuffleupagus** 2022-01-11 16:28 UTC
