### ISSUE TITLE
Rotated interactive forms matrix bug

### ISSUE THREAD

**Issue by mainegreen** [mozilla/pdf.js#10843] opened 2019-05-21 17:57 UTC
Attach (recommended) or Link to PDF file here:
[Subcontract-Performance-Bond.pdf](https://github.com/mozilla/pdf.js/files/3203769/Subcontract-Performance-Bond.pdf)

Configuration:
- Web browser: Any
- Operating system and its version: Any
- PDF.js version: Latest
- Is a browser extension: no

Steps to reproduce the problem:
1. Render the pdf with renderInteractiveForms = true

What is the expected behavior? 
The text in the inputs not be incorrectly rotated

What went wrong? 
The default viewport from the PDF has a rotation of 270. The container uses the transform to create a matrix transformation to position the input elements. This would be all well and good, but HTML inputs always start with text alignment left to right, while the annotation logic for the widgets incorrectly assumes the text alignment matches the page's rotation property. This results in an incorrect text alignment of the text: 
https://imgur.com/a/y7MHp1Q

What really has to happen is that the matrix needs to be pre-rotated so that it's alignment is left to right (0), and the css matrix transformations are performing no skewing on the container contained in _createContainer for widgets.

I don't know if that means having a overriden _createContainer in WidgetAnnotationElement or what the best way to pre-rotate the matrix for the container is.

And if 'pre-rotate the matrix' isn't the right term, I apologize, but matrixes are not really my strong suite. 

[Subcontract-Performance-Bond.pdf](https://github.com/mozilla/pdf.js/files/3203770/Subcontract-Performance-Bond.pdf)

Thanks!
Ned Andre

(btw I love the new forms rendering layer. Much easier to work with and override)

**Comment by Snuffleupagus** [comment] 2019-05-21 18:11
Duplicate of #9596.

**Closed** 2019-05-21 21:43 UTC
