### ISSUE TITLE
Offer a ''fit-width'' option for 2x2 and change the background color of the pdf

### ISSUE THREAD

**Issue by Janaue** [mozilla/pdf.js#12708] opened 2020-12-08 16:18 UTC
Hello

I have firefox 83 stock profile and I read a lot of pdf, for ex from here
https://arxiv.org/list/math-ph/pastweek?show=100
and I want to do a few things on the default appearance of the pdf reader
- I want  to close all the side bar, which i managed to do with ''pdfjs.sidebarViewOnLoad;0'' in firefox

- I want to change the white background color and selection color of the pdf itself, because it burns my eyes. I don't know how to this. Can you add an option to set the colors ? I want to the color to be like in my config for in sumatrapdf:
	BackgroundColor = #c1bdb7
	SelectionColor = #f5fc0c

-I want the pages to be shown 2 by 2, odd pages on the left by default, but I don't see the user_pref for this.

-I want the possibility to fit the 2x2 pages according to their width, ie the screen should have the 2 pages showing the full width of each page [currently it is achieved by setting the zoom to 80%] like this:

![2020-12-08 17_14_11-2012 03917 pdf](https://user-images.githubusercontent.com/10972636/101509238-d8bc2600-3978-11eb-805a-9f6ac74d84ec.jpg)

instead of the current setting which shows the first page, but not much of the page 2,

![2020-12-08 17_12_17-2012 03917 pdf](https://user-images.githubusercontent.com/10972636/101509323-effb1380-3978-11eb-9fa3-bba8d60969a6.jpg)

for instance the pdf https://arxiv.org/pdf/2012.03917.pdf looks like this in sumatra

![2020-12-08 17_16_21-2012 03917 pdf - SumatraPDF](https://user-images.githubusercontent.com/10972636/101509523-246ecf80-3979-11eb-9505-a78819fec7c5.jpg)

**Comment by Snuffleupagus** [comment] 2020-12-08 17:13
> I want to change the white background color and selection color of the pdf itself,

This part is a duplicate of issue #2071.

> I want the pages to be shown 2 by 2, odd pages on the left by default, but I don't see the user_pref for this.

Setting `pdfjs.spreadModeOnLoad = 1` in about:config should fix that; please find the supported integer values at https://github.com/mozilla/pdf.js/blob/b194c820bfbf30734589bb37f7f632bcc7790352/web/ui_utils.js#L53-L58

> I want the possibility to fit the 2x2 pages according to their width, ie the screen should have the 2 pages showing the full width of each page

This part is a duplicate of issue #12699.

**Comment by Janaue** [comment] 2020-12-08 17:31
thanks, the settings work.
What is the  setting to get the ''hand'' by default, instead of 'text selection''

**Closed** 2020-12-08 17:32 UTC
