### ISSUE TITLE
Print orientation in IE11

### ISSUE THREAD

**Issue by pgod1960** [mozilla/pdf.js#8443] opened 2017-05-25 07:32 UTC
When printing in IE 11 the orientation of the file is not preserved and needs to be manually set by the user in a reduced print dialog. As no preview dialog is shown the print result is often distorted. The native pdf experience in IE produces a better user experience which mirrors other browsers. Typically a landscape 'report' will print in portrait mode which leads to frustration for the site users. Is there a way to set up viewer.js to force the correct browser behaviour? 

Using pdfjs-1.8.170-dist
[CHROME.pdf](https://github.com/mozilla/pdf.js/files/1028285/CHROME.pdf)
[IE.pdf](https://github.com/mozilla/pdf.js/files/1028286/IE.pdf)

**Comment by berenddeschouwer** [comment] 2017-05-26 12:56
I've got a similar problem in Firefox on Linux.  The printout uses whatever the default layout is, it doesn't tell the print dialog what orientation the PDF actually is in.  So if the last print was 'portrait', it stays portrait even if the new PDF is landscape.  If the previous print was landscape, it seems to "remember" landscape.

If this is not the same bug, I'll open a new one.

**Comment by timvandermeij** [comment] 2017-05-26 12:59
This is indeed the same issue, but the problem is that browsers generally provide no way to control this through JavaScript. The `@page` CSS rule is not (well) supported, unfortunately, so at the moment this is hard to fix.

**Comment by timvandermeij** [comment] 2019-11-09 13:31
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.

**Closed by timvandermeij** 2019-11-09 13:31 UTC
Labels: 4-ie11-specific, 4-printing
