### ISSUE TITLE
Generic viewer in Chrome: page does not render after downloading

### ISSUE THREAD

**Issue by Zwillinge** [mozilla/pdf.js#7533] opened 2016-08-08 18:34 UTC
It seems that canvas is not refreshed on page resizing. The issue occurs in Chrome browser: 
1. Open the generic viewer http://mozilla.github.io/pdf.js/web/viewer.html
2. Push "download" button and open the downloaded file. 
3. Close the tab with the downloaded file to  be redirected to the tab with the viewer (if you just switch to the viewer tab manually, everything is ok). 
4. As a result, current page is black and blank.

**Comment by dorasun** [comment] 2018-03-27 15:47
I attempted to follow the steps you listed here (especially step 3!) but I didn't see any problems, my current page showed the PDF properly. Maybe this got already got resolved since the issue occurred for you?

**Comment by timvandermeij** [comment] 2018-03-27 19:49
Thank you for verifying this. Moreover, it's missing details like Chrome version, OS name/version and whether or not hardware acceleration is on. Currently the issue is not really actionable, so I'm going to close this until more information is provided if this is still a problem.

**Closed by timvandermeij** 2018-03-27 19:49 UTC
Labels: 4-chrome-specific, 4-triage-needed
