### ISSUE TITLE
Highlight the search results in scrollbar

### ISSUE THREAD

**Issue by ligq** [mozilla/pdf.js#14768] opened 2022-04-11 06:36 UTC
I hope in pdf viewer, the search results could be shown with highlighted small bars in the scrollbar. That will be very convenient to overview the search results.
Chrome, Edge, those browsers have this functionality, both for webpage and pdf. But Firefox has this feature only for the webpage, not for pdf. I do not know if it is an issue with pdf.js. PDF Xchange also has this feature. Hope this feature could be implemented in pdf.js.

**Comment by Snuffleupagus** [comment] 2022-04-11 06:46
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1693784

---

Please note that searching in PDF.js is completely asynchronous, and that only a limited number of pages rendered at once, hence this feature will unfortunately not be possible to implement particularly well for most PDF documents (or it'd be very inefficient).

**Closed by Snuffleupagus** 2022-04-11 06:46 UTC
