### ISSUE TITLE
hang when scrolling this PDF

### ISSUE THREAD

**Issue by gavinsharp** [mozilla/pdf.js#5656] opened 2015-01-19 01:36 UTC
STR:
1) Load http://www.juneau.org/airport/projects/documents/10_JNURunwayRehabEDR.pdf
2) Go to page 9 of the PDF with the page selector (i.e. click the "next page" button 8 times)
3) Slowly scroll down (I use two finger touchpad scrolling) at a normal reading pace to bring page 10 into view

This causes an unresponsive script dialog to pop up pretty consistently for me.

I first saw this in an up to date Dev Edition build (built from https://hg.mozilla.org/releases/mozilla-aurora/rev/1655198ac60a, pdf.js version 1.0.937), but I also see this in an up to date Nightly build (built from https://hg.mozilla.org/mozilla-central/rev/0c454540fc2b, pdf.js version 1.0.1040). I'm testing on Mac OS X 10.9.5 on a Macbook Pro.

When I hit "debug script" on the slow script dialog in the Aurora build, I was able to get a stack:
![isds9h32sw](https://cloud.githubusercontent.com/assets/327839/5794941/5f0b227e-9f38-11e4-9964-c00f54bab30f.png)

**Comment by gavinsharp** [comment] 2015-01-19 01:37
I notice now there's a diagram on page 11 of the PDF that takes a long time to load even when I don't see this hang, maybe trying to render that is what causes the issue.

**Comment by timvandermeij** [comment] 2015-01-19 19:10
The diagram is a bit slow (it takes approx. three seconds for me to render completely), but other than that the PDF is very fast for me on Windows 7 x64 (using Firefox 35.0 and the development build of PDF.js).

**Comment by yurydelendik** [comment] 2015-01-19 23:22
Was able to reproduce on Mac OSX, but not on Windows. On windows it is stuck for ~1sec on certain graphics operation, might be related to the stack/hang above.

**Comment by yurydelendik** [comment] 2015-01-19 23:35
Also works good with gfx.canvas.azure.backends=skia

 @gavinsharp this is sounds like a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1026009

**Comment by Snuffleupagus** [comment] 2020-03-09 21:27
> Load http://www.juneau.org/airport/projects/documents/10_JNURunwayRehabEDR.pdf

Given that the above file is no longer available directly, or via the Internet Archive, and that e.g. https://github.com/mozilla/pdf.js/issues/5656#issuecomment-70580012 points to this being a browser issue; is it meaningful to keep this issue open?

**Closed** 2020-03-09 21:46 UTC
Labels: 2-performance, 3-upstream
