### ISSUE TITLE
Can't open find bar using ctrl+F or "Find in This Page"

### ISSUE THREAD

**Issue by Octocontrabass** [mozilla/pdf.js#12548] opened 2020-10-29 03:32 UTC
Link to PDF file here: https://raw.githubusercontent.com/Jaycar-Electronics/high-efficiency-psu/master/LM2678-5-datasheet.pdf

Configuration:
- Web browser and its version: Firefox 82.0.2 (64-bit)
- Operating system and its version: Windows 10 version 2004 (19041.572)
- PDF.js version: the one included in Firefox?
- Is a browser extension: no

Steps to reproduce the problem:
1. Open any PDF hosted on raw.githubusercontent.com (but do not download it)
2. Attempt to use ctrl+F or Edit -> Find in This Page...

What is the expected behavior?

The find bar should open.

What went wrong?

The find bar does not open, and the "Find in This Page..." menu item is grayed out.
![Capture](https://user-images.githubusercontent.com/5341981/97521105-12e9df00-195a-11eb-92bd-ba50b64765b8.PNG)

**Comment by timvandermeij** [comment] 2020-10-29 21:38
That's really odd. Indeed it works for other PDF files but not for this one. This seems like an upstream problem in the Firefox integration.

**Comment by brendandahl** [comment] 2020-10-29 22:39
Seems to be fine in firefox 84.

**Comment by timvandermeij** [comment] 2020-10-29 22:54
I'm also on Firefox 82 like the reporter, so maybe this is indeed an upstream bug with the integrated find functionality that got fixed upstream. Labeling the issue as such for now; thanks!

**Comment by SamyCookie** [comment] 2020-10-30 09:02
I can reproduce the issue with Firefox 81 either.

**Comment by Snuffleupagus** [comment] 2020-10-30 09:47
Mozregression gives the following *fixed* pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=736e01530c6dd091935a98276d423cebad8cec02&tochange=14b2a31d38d744eca38a0fb192e98fcdaa318e86

Hence this is a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1657263, which is fixed in Firefox 83.

**Comment by timvandermeij** [comment] 2020-10-30 22:23
Thank you for finding this out! We can close this then.

**Closed** 2020-10-30 22:23 UTC
Labels: 1-viewer, 3-upstream
