### ISSUE TITLE
PDF Rendering issue in IE

### ISSUE THREAD

**Issue by gsampath127** [mozilla/pdf.js#8011] opened 2017-01-30 22:18 UTC
Link to PDF file (or attach file here): http://www.rightprospectus.com/documents/Ariel/fund_sumpro.pdf

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: Window 7
- PDF.js version: Latest
- Is an extension: NA

Steps to reproduce the problem:
1.	Open PDF file ( http://www.rightprospectus.com/documents/Ariel/fund_sumpro.pdf) in Pdf Js Viewer in IE 11
2.	Issue can be seen when we open PDF here - https://mozilla.github.io/pdf.js/web/viewer.html
3.	PDF is not getting displayed properly. Please find expected behavior screen shot.

What is the expected behavior? (add screenshot)

![image](https://cloud.githubusercontent.com/assets/12858790/22444159/d0c63324-e70f-11e6-9f7e-b5f489b13af4.png)

What went wrong? (add screenshot)

![image](https://cloud.githubusercontent.com/assets/12858790/22444183/e5f826bc-e70f-11e6-9f67-c868aecd3542.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-01-31 10:45
Closing as duplicate of issue #5264.

**Closed by Snuffleupagus** 2017-01-31 10:45 UTC
Labels: 4-ie11-specific, 4-image-conversion
