### ISSUE TITLE
Image smoothing issue on Chrome

### ISSUE THREAD

**Issue by gjactat** [mozilla/pdf.js#17139] opened 2023-10-19 11:49 UTC
Hello,

First of al, thanks for your valuable project ! 

The rendering of the attached pdf file through pdfjs is quite different on Firefox and Chrome. As you can see on the following snapshots, Firefox renders **smooth images** while Chrome doesn't. The pdf file seems to be bitmap text with an OCR layer.

**Firefox rendering :**

![image](https://github.com/mozilla/pdf.js/assets/1826064/bafaa8ee-f161-497e-9018-ccca6413d074)

**Chrome rendering :**

![image](https://github.com/mozilla/pdf.js/assets/1826064/af4a783f-4a65-43d8-b187-3d1b886b2861)

I already have tested to enable/disable the "**Accelerated 2D canvas**" setting in Chrome (without any improvement).

**Interesting observation :**

While poking around with this issue, I tried to comment the code inside the "**getImageSmoothingEnabled**" function, like so :

![image](https://github.com/mozilla/pdf.js/assets/1826064/f0fc0d9a-0a62-448a-b557-1a28c2c956f0)

For some reason, this change improved the rendering on Chrome (to the point it was identical to the Firefox rendering) :

**Chrome rendering with patched code :**

![image](https://github.com/mozilla/pdf.js/assets/1826064/ea665ece-d4a4-4363-bcb2-bb52436808f4)

I can't explain why this minor change has an effect at all. But there must be something here.

Configuration:
- Chrome v 118.0.5993.89 (Build officiel) (64 bits)
- Firefox v 118.0.2 (64 bits)
- Operating system and its version: Windows 11 (up to date)
- PDF.js version: 3.11.174
- Is a browser extension: No

Pdf file used in the snapshots :
[CED_FIN_0058_FR_WIFI.pdf](https://github.com/mozilla/pdf.js/files/13041940/CED_FIN_0058_FR_WIFI.pdf)

**Comment by Snuffleupagus** [comment] 2023-10-19 11:56
Duplicate of #16273

**Closed by Snuffleupagus** 2023-10-19 11:56 UTC
