### ISSUE TITLE
PDF JS Annotation

### ISSUE THREAD

**Issue by Bharani14** [mozilla/pdf.js#11286] opened 2019-10-29 15:19 UTC
Attach (recommended) or Link to PDF file here:
[sample.pdf](https://github.com/mozilla/pdf.js/files/3784299/sample.pdf)

Configuration:
- Web browser and its version: 77.0.3865.120 (Official Build) (64-bit)
- Operating system and its version: Windows 7
- PDF.js version: 2.2
- Is a browser extension: 

Steps to reproduce the problem:
1. Make correction to a pdf through adobe acrobat.
2. Open the pdf through pdf js.

What is the expected behavior? (add screenshot)
When we place the cursor hover the changes made should give a annotation popup for the changes in the exact cursor position.
![expect](https://user-images.githubusercontent.com/31505000/67780719-85e12100-fa8c-11e9-9ca4-f6a99222575a.png)

What went wrong? (add screenshot)
While clicking on this page whatever the changes are the annotation popup doesn't show for the corresponding changes it shows same popup for all changes in the right top corner.
![issue](https://user-images.githubusercontent.com/31505000/67780758-90031f80-fa8c-11e9-81cc-083e435c3ee3.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2019-10-29 21:58
The problem here is that some annotations appear to have a rectangle entry that covers most of the page and we use that since we don't use the quad points yet. We should be using that if it is available and forget about the rectangle entry in that case.

**Comment by nanikanna** [comment] 2019-10-30 09:45
Is there anyway to fix this issue?

**Comment by timvandermeij** [comment] 2019-10-30 21:42
Yes, quad points are already supported in the core layer since a recent patch, but we do not use it in the display layer yet, which should still be done.

**Comment by Bharani14** [comment] 2019-11-19 10:33
I am trying to get the start and end offset of the annotation. When the annotation is within a single line the offset which i am getting is correct. But, when i try to get offset of multiple line annotation I am getting wrong instead.   
Please look into the screenshot:
    Start and End offset of the strikeout text is wrong while getting annotation. Instead of getting start and end point of the text i am getting the offset of the canvas layer which cover entire two lines.  Note : Actually the marked start and end points to be get.
![startandend](https://user-images.githubusercontent.com/31505000/69139047-c52bec00-0ae5-11ea-962d-330dfbf7d73b.png)

**Comment by tomyitav** [comment] 2020-03-23 14:58
Hi, is there any progress on this issue?
Thanks!

**Comment by timvandermeij** [comment] 2020-03-23 22:43
Unfortunately not, https://github.com/mozilla/pdf.js/issues/11286#issuecomment-548125140 still holds.

**Comment by timvandermeij** [comment] 2020-05-23 14:00
Closing since this is a duplicate of #6811.

**Closed by timvandermeij** 2020-05-23 14:00 UTC
Labels: 4-annotations
