### ISSUE TITLE
PDF formular not displayed

### ISSUE THREAD

**Issue by PifPof73** [mozilla/pdf.js#10836] opened 2019-05-20 08:53 UTC
Attach (recommended) or Link to PDF file here:
[Unbenannt.1.pdf](https://github.com/mozilla/pdf.js/files/3197032/Unbenannt.1.pdf)

Configuration:
- Web browser and its version: Firefox Quantum 66.0.5 (64-Bit)
- Operating system and its version: Win 10 Pro
- PDF.js version: 1.10
- Is a browser extension: Owncloud PDF Viewer

Steps to reproduce the problem:
1. Upload a pdf with Acrobat form inside
2. PDF.js displays a error message inside the pdf instead of the pdf.

What is the expected behavior? (add screenshot)
The PDF formular is displayed and can be filled out directly

What went wrong? (add screenshot)
Instead of the pdf the following text is formatted inside a pdf:

> Please wait... 
If this message is not eventually replaced by the proper contents of the document, your PDF 
viewer may not be able to display this type of document. 
You can upgrade to the latest version of Adobe Reader for Windows®, Mac, or Linux® by 
visiting  http://www.adobe.com/go/reader_download. 
For more assistance with Adobe Reader visit  http://www.adobe.com/go/acrreader. 
Windows is either a registered trademark or a trademark of Microsoft Corporation in the United States and/or other countries. Mac is a trademark 
of Apple Inc., registered in the United States and other countries. Linux is the registered trademark of Linus Torvalds in the U.S. and other 
countries.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): [https://github.com/owncloud/files_pdfviewer](url)

**Comment by Snuffleupagus** [comment] 2019-05-20 12:15
WFM, using PDF.js version `2.2.177`.

> PDF.js version: 1.10

No such version number has ever existed, please find the latest releases at https://github.com/mozilla/pdf.js/releases

> Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): [https://github.com/owncloud/files_pdfviewer](url)

That's a different project, and while it may be using the PDF.js library it's not something that we can provide support for; please contact that project directly for support instead.

**Comment by THausherr** [comment] 2019-05-20 15:41
I suspect that you uploaded the wrong file. The "please wait" text isn't in the PDF at all. I know it from XFA PDFs.

**Comment by timvandermeij** [comment] 2019-05-20 22:00
Closing since this is a duplicate of #1773.

**Closed by timvandermeij** 2019-05-20 22:00 UTC

**Comment by PifPof73** [comment] 2019-05-21 07:26
> 
> 
> I suspect that you uploaded the wrong file. The "please wait" text isn't in the PDF at all. I know it from XFA PDFs.

Yes, the attached PDF is an Example. Instead of the inside I see the text I discribed inside the pdf. I didn't attach the "wrong" pdf. And yes it is with XFA PDFs.

**Comment by PifPof73** [comment] 2019-05-21 07:28
> 
> 
> Closing since this is a duplicate of #1773.

sorry, I didn't find this duplicate as I just checked the summary descriptions and #1773 is open since 2012.
Is there any plan to get pdf forms supported (after 7 years as open issue)?

**Comment by timvandermeij** [comment] 2019-05-21 21:41
AcroForms support is only experimental and not enabled yet (tracked in #7613).
