### ISSUE TITLE
Can't open Report-PDF

### ISSUE THREAD

**Issue by Norfok91** [mozilla/pdf.js#11289] opened 2019-10-30 15:15 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox ESR 68.2.0
- Operating system and its version: Win10 and Win7 
- PDF.js version: 2.2.178
- Is a browser extension: no Extensions

Steps to reproduce the problem:
Problem couldn't be reproduced by you because it's in our Intranet.
We have reports which are exported as pdf. if you try to open that report, a tab opens in Firefox but the pdf-viewer is empty (grey site with a grey loadingbar). 

Browser-Log says: 
Viewer.js:979:15 
During Loading an error occured. 
PDF.js Version 2.2.178 (build: 3e869a28)
Message: undefined
error: resource://pdf.js/web/viewer.js:979

What does that mean? 

![2019-10-30 15_58_28-PC177F1 - Netop Remote Control](https://user-images.githubusercontent.com/57185052/67871220-4704a700-fb30-11e9-96a5-0b99960d3b85.png)
![2019-10-30 16_16_01-PC177F1 - Netop Remote Control](https://user-images.githubusercontent.com/57185052/67871221-479d3d80-fb30-11e9-8403-e532bf440f4f.png)

**Comment by Norfok91** [comment] 2019-10-30 15:17
Issue is very important -  we need this for our company!  
Thx for any help! 
Best Regards from Austria

**Comment by Snuffleupagus** [comment] 2019-10-30 16:15
> Attach (recommended) or Link to PDF file here:

This part of the issue template is a *requirement* in order for the issue to be actionable/valid.

> Problem couldn't be reproduced by you because it's in our Intranet.

Without a way to reproduce the issue, there's unfortunately nothing anyone can do here. Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment] 2019-10-30 21:40
In addition to the comment above, 2.2.178 is not an official release. You should use 2.2.228 instead. Closing since we cannot do anything until a PDF file is provided to reproduce the issue, assuming that the PDF is at fault here.

**Closed by timvandermeij** 2019-10-30 21:40 UTC
