### ISSUE TITLE
Selected text misplaced problem when the system zoom rate is 125%

### ISSUE THREAD

**Issue by zjw1111** [mozilla/pdf.js#14275] opened 2021-11-15 03:19 UTC
Attach (recommended) or Link to PDF file here:
[BAVP Blockchain-Based Access Verification Protoco.pdf](https://github.com/mozilla/pdf.js/files/7535501/Wei.Songjie.-.2018.-.BAVP.Blockchain-Based.Access.Verification.Protoco.pdf)

Configuration:
- Web browser and its version: Chrome 95.0.4638.69  and  Edge 95.0.1020.53 
- Operating system and its version: Win10 10.0.18363.1256
- PDF.js version: 2.10.377
- Is a browser extension: It does not matter. I have tried to use it in the browser extension and on the website https://mozilla.github.io/pdf.js/web/viewer.html, this problem will appear

Steps to reproduce the problem:
1. Set the system zoom rate to 125% in Win10 display settings（And there is some other display options in my computer, for reference）
![image](https://user-images.githubusercontent.com/30893610/141716553-dc6782a5-b6c8-44b1-b2d1-e7dfb38f7aae.png)
2. Select a few lines of text arbitrarily

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/30893610/141715910-e9516ec3-1496-47d9-a848-cd937a01ae59.png)

What went wrong? (add screenshot)
I have two monitors. The selected text is right displayed in 100%-zoom monitor, and misplaced displayed in 125%-zoom monitor.
![image](https://user-images.githubusercontent.com/30893610/141713651-e800e8b8-2084-45d3-87fd-bb70cc0eb03d.png)

**Comment by Snuffleupagus** [comment] 2021-11-15 09:31
Duplicate of #12523 (since it looks similar enough, and it's also likely to be a OS/browser problem rather than a PDF.js bug).

**Closed by Snuffleupagus** 2021-11-15 09:31 UTC
