### ISSUE TITLE
eSignatures are not visible in the PDF.js

### ISSUE THREAD

**Issue by suhaz** [mozilla/pdf.js#13428] opened 2021-05-24 19:21 UTC
I am uploading an eSigned PDF and once uploaded, the eSignature is not visible when loaded with pdf.js. What could be the issue? Am I doing anything incorrectly? Below are the details. Due to data sensitivity, I cannot upload the entire PDF here. Please excuse me for that.

Thank you.

Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome Version 90.0.4430.212
- Operating system and its version: macOS Big Sur 11.2.3
- PDF.js version: 2.7.570
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/629389/119396678-ccdbda80-bcf2-11eb-9449-7d8da70e7eac.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/629389/119396725-dfeeaa80-bcf2-11eb-8b61-177cdb98d12f.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-05-24 19:55
> Due to data sensitivity, I cannot upload the entire PDF here. Please excuse me for that.

Without a test-case, this issue (or any other one really) is unfortunately not actionable/valid; please note that it's *impossible* do to any testing/debugging with nothing more than a screen-shot.

This might be fixed by #13214, and thus be a duplicate of #1076, but it's simply impossible to tell.

**Comment by suhaz** [comment] 2021-05-24 21:12
Okay, here is the URL where you can try it out.

https://d3.mpcompliance.com/testpdfjs.php

Thank you.

**Comment by timvandermeij** [comment] 2021-05-25 18:27
The direct link to the file is https://d3.mpcompliance.com/esigned.pdf. Opening this with https://mozilla.github.io/pdf.js/web/viewer.html shows that this is fixed by #13214, but that PR is not in a release yet, which will hopefully happen very soon.

**Closed by timvandermeij** 2021-05-25 18:27 UTC
