### ISSUE TITLE
Fanta are overlapping/corrupted

### ISSUE THREAD

**Issue by Anand-setty** [mozilla/pdf.js#8710] opened 2017-07-27 11:26 UTC
Link to PDF file (or 
[1-25.pdf](https://github.com/mozilla/pdf.js/files/1179721/1-25.pdf)
attach file here):

Configuration:
- Google chrome 59.0.3071.115 64 bit
- Mac and windows OS
- PDF.js version: Latest
- Is an extension: Nope

Steps to reproduce the problem:
 Open  attached pdf in pdf js viewer

What is the expected behavior? (add
<img width="1283" alt="screen shot 2017-07-27 at 4 55 53 pm" src="https://user-images.githubusercontent.com/16985967/28668232-84a6436c-72ec-11e7-8725-62b132030c26.png">
 screenshot)
Fonts should not overlap. it works fine on safari browser. issue is only in chrome and firefox

What went wrong? (add screenshot)
Fonts are over lapping

**Comment by Snuffleupagus** [comment] 2017-07-27 11:55
Closing as duplicate of #7507.

**Closed by Snuffleupagus** 2017-07-27 11:55 UTC
