### ISSUE TITLE
Problem with gradient in stroke

### ISSUE THREAD

**Issue by SerDIDG** [mozilla/pdf.js#12664] opened 2020-11-27 00:13 UTC
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/5605357/test.pdf)

Configuration:
- Firefox (84.0b4):
- Windows 10 Pro (2004):
- PDF.js version: latest

Steps to reproduce the problem:
1. Open attached pdf file in pdf.js demo viewer.
2. Circle is not affected by gradient and significantly wider.

What is the expected behavior? (Latest Chrome)
![изображение](https://user-images.githubusercontent.com/1660640/100397905-ee664d00-3054-11eb-97ac-1335401277ed.png)

What went wrong? (Latest Firefox)
![изображение](https://user-images.githubusercontent.com/1660640/100397959-2d949e00-3055-11eb-8b9a-f6141dae6460.png)

I used Adobe InDesign to export my project into pdf which contains svg layers. Here is a sample of svg i used for a demo above:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100">
    <defs>
        <linearGradient id="gradient" gradientUnits="userSpaceOnUse" x1="10" x2="90" y1="90" y2="10">
            <stop offset="0%" stop-color="#0a00b2"/>
            <stop offset="50%" stop-color="#ff0000"/>
            <stop offset="100%" stop-color="#fffc00"/>
        </linearGradient>
        <style>
            .circle {
                fill: none;
                stroke: url(#gradient);
                stroke-width: 2px;
            }
        </style>
    </defs>
    <circle class="circle" cx="50" cy="50" r="43"/>
</svg>
```

**Comment by janpe2** [comment] 2020-11-30 13:36
Maybe a duplicate of #6769 and #10955.

**Closed** 2020-11-30 20:45 UTC
Labels: 4-shading-pattern
