### ISSUE TITLE
open pdfjs error

### ISSUE THREAD

**Issue by stevenliuit** [mozilla/pdf.js#10046] opened 2018-09-06 02:04 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
- Operating system and its version: ios 11.4.1
- PDF.js version:2.0.550、1.10.100
- Is a browser extension:

Steps to reproduce the problem:
1. I can open this pdf with chrome and android phone, I can't open this pdf with ios11.4.1.
2.i use 2.0.550 debug warning:
![image](https://user-images.githubusercontent.com/4044994/45130571-c5c7b380-b1bb-11e8-9137-1fb41fbbf801.png)

What is the expected behavior? (add screenshot)
open this pdf
pdf path:https://drive.google.com/file/d/1yOkOCvBAvPJXg71xDh4aWX3aZCeSEqBA/view?usp=sharing

What went wrong? (add screenshot)
i don't know.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2018-09-06 07:52
> 2.i use 2.0.550 debug warning:

Those are just warnings, not errors, and as such does *not* explain why things aren't working.

> I can't open this pdf with ios11.4.1.

In that case, this is probably a duplicate of the already existing issue #10044.

**Comment by stevenliuit** [comment] 2018-09-06 08:11
You can open it with my pdf.
use iphone open this pdf。
pdf url：https://drive.google.com/file/d/1yOkOCvBAvPJXg71xDh4aWX3aZCeSEqBA/view?usp=sharing

**Comment by stevenliuit** [comment] 2018-09-14 09:04
When is this problem solved?

**Comment by Snuffleupagus** [comment] 2019-02-22 12:08
As mentioned in https://github.com/mozilla/pdf.js/issues/10046#issuecomment-419000058, let's close this as a duplicate of #10044.

**Closed** 2019-02-22 21:14 UTC
Labels: 1-core, 4-os-ios
