### ISSUE TITLE
All the comments for a text annotation are not displayed

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14047] opened 2021-09-18 14:31 UTC
Attach (recommended) or Link to PDF file here:
[comments.pdf](https://github.com/mozilla/pdf.js/files/7190076/comments.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: linux debian

Steps to reproduce the problem:
1. Open the pdf
2. Click on the yellow button

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/5641725/133892283-fe3fe3e6-5e85-4334-9948-3e15b0a29a99.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/5641725/133892230-b427c2f3-7ad2-4a5b-a663-54a9861eda5a.png)

**Comment by timvandermeij** [comment] 2021-09-18 14:32
Isn't this a duplicate of 10982?

**Comment by Snuffleupagus** [comment] 2021-09-18 14:34
> Isn't this a duplicate of 10982?

Sure looks like it to me too, let's indeed mark it as duplicate of #10982

**Closed by Snuffleupagus** 2021-09-18 14:34 UTC
Labels: 4-annotations
