### ISSUE TITLE
Text become jagged at specific zoom ratio

### ISSUE THREAD

**Issue by wengh** [mozilla/pdf.js#12876] opened 2021-01-19 19:25 UTC
Attach (recommended) or Link to PDF file here: [pdfjs bug.pdf](https://github.com/mozilla/pdf.js/files/5838113/pdfjs.bug.pdf)

Configuration:
- Web browser and its version: Chromium 87

- Operating system and its version: Windows 10 20H2
- PDF.js version: 2.7.533
- Is a browser extension: it's the demo

Steps to reproduce the problem:
1. Open the linked "pdfjs bug.pdf"
2. Set zoom to 125% 

What is the expected behavior? (add screenshot)
Smooth text (screenshot of PDF-XChange)
![image](https://user-images.githubusercontent.com/16470555/105082453-96026900-5a61-11eb-9853-7a1c76fcd55b.png)

What went wrong? (add screenshot)
Jagged text (screenshot of PDF.js)
![image](https://user-images.githubusercontent.com/16470555/105082390-7ec37b80-5a61-11eb-8017-3cb063122194.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2021-10-03 12:01
Duplicate of #8201

**Closed by Snuffleupagus** 2021-10-03 12:01 UTC
Labels: 1-viewer
