### ISSUE TITLE
TypeError: this.info.toSource is not a function

### ISSUE THREAD

**Issue by prmanik** [mozilla/pdf.js#17316] opened 2023-11-22 05:27 UTC
Attach (recommended) or Link to PDF file here: 
[nonclinical-overview.pdf](https://github.com/mozilla/pdf.js/files/13433921/nonclinical-overview.pdf)

Configuration:
Web browser and its version: Chrome Version 119.0.6045.160 (Official Build) (64-bit)
Operating system and its version: Windows version 11 enterprise
PDF.js version: [v4.0.189]
Is a browser extension: No

Steps to reproduce the problem:

1.Open any Published MasterControl documents
and will get an error - TypeError: this.info.toSource is not a function and in text layer stating that "Published MasterControl documents frequently use JavaScript. If you are seeing this message, your viewer either does not support JavaScript or it is disabled. If you are using Adobe Acrobat, please enable JavaScript. If you are using another viewer, you will need to configure your browser to view PDF files externally in Adobe Acrobat."
What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/140620152/958536b4-421d-4cab-983c-8edbb2867df2)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/140620152/168a0ec7-89de-4700-9f82-ac4fb999fea8)

Could you please let us know, how to resolve the issue? Is there any settings on browser to be enabled?
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2023-11-22 09:12
Duplicate of #17308

**Closed by Snuffleupagus** 2023-11-22 09:12 UTC

**Comment by prmanik** [comment] 2023-11-22 13:38
[#17308](https://github.com/mozilla/pdf.js/issues/17308) closed because the pdf is not shared.

I have provided the PDF document which is having issue, still the issue is closed without understanding the request raised. Please read the request fully before closing. 

We are using your library in our project, and the mentioned issue is escalated by our customer. We are not able to see the full content of the file using this library. Kindly read the request and provide the resolution. 

As the ticket is closed and we are raising the request again. So please be reasonable to your customer who is seeking your assistance.

**Comment by Snuffleupagus** [comment] 2023-11-22 13:48
> [#17308](https://github.com/mozilla/pdf.js/issues/17308) closed because the pdf is not shared.

... and because it's a duplicate of an existing issue, which was already mentioned in https://github.com/mozilla/pdf.js/issues/17308#issuecomment-1820711805.

> So please be reasonable to your customer who is seeking your assistance.

Please keep in mind that this is an open-source project that you're able to use *for free*.

**Comment by prmanik** [comment] 2023-11-24 05:57
So you wont answer for the queries users have?
