### ISSUE TITLE
After this weekend update of Chrome and Edge, certain PDF files will not display the text. You can copy the text by highlighting it and ctrl-C.  Current Edge version 92.0.902.55.  I tried an older version of Edge on a different computer and it works fine.

### ISSUE THREAD

**Issue by darenm01** [mozilla/pdf.js#13802] opened 2021-07-27 12:00 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-07-27 12:03
Duplicate of #13798

(Which is a best guess, since this issue is missing *every* single piece of required information in order to be actionable/valid.)

**Comment by darenm01** [comment] 2021-07-27 12:03
Configuration
[test.pdf](https://github.com/mozilla/pdf.js/files/6885173/test.pdf)
Edge : 92.0.902.55
Windows 10 (same result on a Mac)
PDF Viewer 2.3.164
Steps to reproduce
Open the file with the extension and you will see that it is blank

**Closed by Snuffleupagus** 2021-07-27 12:03 UTC
