### ISSUE TITLE
PDF will not view pages because of "Bad encoding in flate stream" error

### ISSUE THREAD

**Issue by mdnorman** [mozilla/pdf.js#11207] opened 2019-10-04 19:31 UTC
Attach (recommended) or Link to PDF file here:

Cannot attach or link - proprietary client docs.

Configuration:
- Web browser and its version: Firefox 69.0.1 & Chrome 77.0.3865.90
- Operating system and its version: macOS Mojave 10.4.6
- PDF.js version: 2.2.8
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF
2. View the page that has the problem. Page is blank.

What is the expected behavior? (add screenshot)

> Page would be displayed (cannot attach screenshot, but it displays in Chrome PDF viewer)

What went wrong? (add screenshot)

<img width="1967" alt="Blank Viewer" src="https://user-images.githubusercontent.com/451017/66235297-5de0e680-e6b5-11e9-9d6f-aa2914770a18.png">

`Bad encoding in flate stream` error is suppressed (not rethrown) from https://github.com/mozilla/pdf.js/blob/master/src/core/worker.js#L488 and https://github.com/mozilla/pdf.js/blob/master/src/core/worker.js#L527, but it's happening from both. 

Tracing the code, the error is happening in both `FlateStream.getBits` (https://github.com/mozilla/pdf.js/blob/master/src/core/stream.js#L451) and `FlateStream.getCode` (https://github.com/mozilla/pdf.js/blob/master/src/core/stream.js#L471)

I was able to take the original compressed block and read it using [pako](https://github.com/nodeca/pako) without errors. Pako reads the last byte as a different value than `FlateStream`.

It only appears to happen for dynamic blocks (with included Huffman table), not fixed blocks. That leads me to believe that the Huffman table decoding is incorrect, but I've been unable to find the issue.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

> Used both hosted viewer and downloaded the source and tried it with `gulp server`.

**Comment by timvandermeij** [comment] 2019-10-04 21:05
Unfortunately there is nothing we can do without a PDF file for reproducing the problem. You could try to find a document that is not proprietary for sharing here, or make a reduced PDF file from the original PDF file by stripping away all objects not relevant for the issue and removing confidential data so it can be shared. In that case we can reopen this.

**Comment by mdnorman** [comment] 2019-10-07 18:31
Is there a secure location that I can upload my client's PDF? They likely won't want it to be in the public domain, but if it can be put somewhere securely, we may be able to get it approved.

**Comment by timvandermeij** [comment] 2019-10-07 20:49
I would really recommend to reduce the PDF file or create a new one without confidential data and upload it here because that allows any contributor to help out, which may help to get the issue resolved sooner. You can remove all pages that are not relevant to reproduce the issue and get rid of unimportant objects. If that is really not possible, we might be able to arrange that you send it to us in private so we can attempt to reduce the PDF file to the bare minimum.

**Comment by mdnorman** [comment] 2019-10-08 22:06
I understand. Unfortunately, I don't know how to `break` the file. Once I use another tool to manipulate it, the problem goes away.

I'll just have to wait for the client to approve uploading it.

**Comment by mdnorman** [comment] 2019-10-22 21:26
@timvandermeij we have permission from the client to send you the documents as long as they are kept confidential.

**Comment by timvandermeij** [comment] 2019-10-22 21:34
In that case, let's reopen this. I don't have much experience with reducing PDF files myself, but perhaps there is someone here willing to take care of that so we can get a good reduced test case without confidential data to work with.

/cc @Snuffleupagus @THausherr Would any of you perhaps be willing/able to reduce such a PDF file? If not, that's totally fine, it's just that I'm asking because I don't have much experience with it myself.

**Comment by THausherr** [comment] 2019-10-23 06:10
Yes please send to  tilman at snafu dot de. However don't expect too much from me, the whole thing could fail due to not being able to decompress that stream. My strategy (I'm sure there are others) is usually to delete objects with NOTEPAD++, open the PDF and resave it (sometimes with Apache PDFBox, sometimes with Adobe Reader).

**Comment by mdnorman** [comment] 2019-10-23 16:32
@THausherr I have sent you an email with the documents. Thanks for taking a look!

**Comment by THausherr** [comment] 2019-10-23 19:21
I had a look... I get "uncaught exception: Object" in the console. The file displays without trouble in PDFBox, and if I split it or decode it, I can display it in PDF.js. The file has several revisions.

The content streams are all cut off. The "Michael" file ends like this in the content stream of page 2:

```
q
  0.0 0.0 0.0 RG
  0.0 0.0 0.0 rg
  416.46375 507.1061 m
  416.46375 38.79117 l
  417.18387 38.79117 l
  417.18387 507.1061 l
  f
Q
q
  0.0 0.0 0.0 RG
  0.0 0.0 0.0 rg
  365.09555 472.0605 m
  365.09555 3 
```
So I guess some Flate decoder exits with error and some don't.

**Comment by Snuffleupagus** [comment] 2019-11-12 15:40
Given that it's apparently not been possible to produce a reduced test-case for this issue (since that can be *really* difficult sometimes), it unfortunately doesn't seem meaningful to keep this issue open given that it contains no actionable information. /cc @timvandermeij

**Comment by mdnorman** [comment] 2019-11-12 16:01
Please don't close this issue. This is still a bug, and there are at least two PDFs with the problem. The PDF is valid because the pages appear in many different PDF viewers.

I can provide the PDFs to someone else who have the ability to work on the problem.

**Comment by Snuffleupagus** [comment] 2019-11-12 16:54
> Please don't close this issue.

Sorry, but it's unfortunately not reasonable to keep non-actionable issues open perpetually. (In that case, the bug tracker would quickly get overrun with issues that are impossible to ever close.)

> This is still a bug, and there are at least two PDFs with the problem. 

No one is saying that there isn't a problem here, just that it's unfortunately impossible to fix it given the information currently available.

> The PDF is valid because the pages appear in many different PDF viewers.

*Please note:* Just because other PDF viewers can open the document, that does *not at all* imply that it's a valid one unfortunately. Most PDF viewers, including the PDF.js project, has had to implement *a lot* of code to deal specifically with corrupt documents.

Furthermore, the information in https://github.com/mozilla/pdf.js/issues/11207#issuecomment-545597084 would indicate that the document is in fact corrupt.

> I can provide the PDFs to someone else who have the ability to work on the problem.

Given that this is an *open source* project, with most people contributing in their spare time, the only reasonable way[1] to get bugs fixed is generally by providing publicly available test-cases. (Also, keep in mind that a patch would normally be required to include tests as well.)

---
[1] If you're using the PDF.js library in commercial setting, you may also consider hiring/paying someone to help you write a patch to address this issue.

**Comment by THausherr** [comment] 2019-11-12 17:52
I have deleted the two confidential files.

**Comment by timvandermeij** [comment] 2019-11-12 22:45
I mostly agree with https://github.com/mozilla/pdf.js/issues/11207#issuecomment-552983536 and think the only reasonable way forward is to have a public test file here so everyone can work on this. Is it really not possible to create a document with non-sensitive/dummy information, using the same PDF generator, that also shows the problem?

**Comment by mdnorman** [comment] 2019-11-19 14:54
Unfortunately, we (both us and our client) are unaware what software created the PDF.

**Comment by mdnorman** [comment] 2019-12-09 19:32
Based on the PDF, the `Content Creator` is `Paychex MMS PDF Creator v1.1.0` and the `Encoding Software`  `Adobe Acrobat Standard DC 15.6.30503` (https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/classic/dcclassic15.006august2019qfe.html), which was pretty old (2015)

**Comment by peterrobinson** [comment] 2020-04-04 12:24
I have a file with this issue too. I attach it here. The pdf was created by dragging a single page from a multipage pdf. It opens in all the viewers I can find. The error comes when I attempt to use pdf.js getTextContent, so:

        var loadingTask = this.pdfjsLib.getDocument({data: text});
	loadingTask.promise.then(function(pdf) {
		pdf.getPage(1).then(function(page) {
			page.getTextContent().then(function(textContent) {
				// don't get here with error bad encoding in flate stream
			});
		});
	});
[WBP1-451 -P1.pdf](https://github.com/mozilla/pdf.js/files/4431309/WBP1-451.-P1.pdf)

**Comment by Snuffleupagus** [comment] 2020-04-04 12:46
Unfortunately https://github.com/mozilla/pdf.js/issues/11207#issuecomment-609021055 doesn't seem relevant to *this* issue, since that file (and its text-layer) renders just fine in e.g. the `master` version of the PDF.js library; most likely an older/out-dated PDF.js version was used to test with.

*For future reference:* Please note that it's always recommended to open a *new* issue when you encounter a PDF document that doesn't render/work correctly, since it's easy to mark it as a duplicate if that turns out to be the case. However, having potentially different documents reported in the same issue makes tracking things more difficult.

**Comment by peterrobinson** [comment] 2020-04-04 14:56
The issue is not rendering: it is the error in getTextContent which is the problem.   There are other problems with pdf.js. See the question at [stackoverflow](https://stackoverflow.com/questions/61028966/pdf-js-gettextcontent-fails-to-extract-text)
Good point about the possibly out-of-date pdg.js. I'll check that.

**Comment by Snuffleupagus** [comment] 2020-04-04 15:04
*Please directly any additional follow-up/questions regarding https://github.com/mozilla/pdf.js/issues/11207#issuecomment-609021055 to a **new issue**, since it doesn't seem relevant to this one; thank  you!*

**Comment by Snuffleupagus** [comment] 2021-02-20 11:29
*Note that the comments starting at https://github.com/mozilla/pdf.js/issues/11207#issuecomment-609021055 are *completely* irrelevant to this issue.*

---

Given that this issue is still effectively *not* actionable with a publicly available test-case, and that the points in https://github.com/mozilla/pdf.js/issues/11207#issuecomment-552983536 still applies (more than a year later), I'd suggest closing this issue as INCOMPLETE for now.

**Closed** 2021-02-20 13:45 UTC
Labels: 1-core, 3-pdf-broken
