### ISSUE TITLE
Request: Limit pixelRatio used for output/rendering

### ISSUE THREAD

**Issue by CONOVA24** [mozilla/pdf.js#17343] opened 2023-11-27 13:43 UTC
I previously raised this issue, but I feel it's crucial to address it.

My concern involves high-resolution scanned PDFs, typically construction blueprints, which are significantly large in size. These documents, being scanned, essentially consist of a single, expansive image. When displayed on high-resolution screens (where devicePixelRatio exceeds 1), the image's size surpasses the maximum canvas pixel limit of the **browser**. Given the high resolution of these PDFs, it's unnecessary for the output to maintain a PixelRatio greater than 1 to ensure good quality. Currently, attempting to load these PDFs results in failure and a warning, which I'm unable to capture or display in the browser.

Therefore, I suggest implementing a feature to adjust/limit the output scale/resolution. This adjustment would enable the browser to effectively handle PDFs containing large images, ensuring they load properly without compromising quality.

Another potential solution is to divide the image into smaller sections. However, I believe this approach might be more complex.

**Comment by Snuffleupagus** [comment] 2023-11-27 13:50
> I previously raised this issue, but I feel it's crucial to address it.

Duplicate of #17170; please don't knowingly open duplicate issues!

> Therefore, I suggest implementing a feature to adjust/limit the output scale/resolution. This adjustment would enable the browser to effectively handle PDFs containing large images, ensuring they load properly without compromising quality.

As already mentioned in https://github.com/mozilla/pdf.js/issues/17170#issuecomment-1778700498 that's probably less straightforward than you think, and we cannot implement options for everything that users may want (since every options adds maintenance/support burden).

> Another potential solution is to divide the image into smaller sections. However, I believe this approach might be more complex.

This is already tracked in issue #6419, which was mentioned previously as well.

**Closed by Snuffleupagus** 2023-11-27 13:50 UTC
