### ISSUE TITLE
Error: Invalid XRef stream

### ISSUE THREAD

**Issue by sweety-wo** [mozilla/pdf.js#6572] opened 2015-10-28 11:33 UTC
I am trying to load one file using stable version of pdf.js (v1.1.366) but keeps getting same error while other files works well.

Here is the error log:

Error: Invalid XRef stream
pdf.worker.js:233     at error (http://localhost:8080/viewer/js/pdf.worker.js:233:17)
    at Object.XRef_readXRef [as readXRef] (http://localhost:8080/viewer/js/pdf.worker.js:4258:15)
    at Object.XRef_parse [as parse] (http://localhost:8080/viewer/js/pdf.worker.js:3856:28)
    at Object.PDFDocument_setup [as setup] (http://localhost:8080/viewer/js/pdf.worker.js:3029:17)
    at Object.PDFDocument_parse [as parse] (http://localhost:8080/viewer/js/pdf.worker.js:2910:12)
    at http://localhost:8080/viewer/js/pdf.worker.js:2465:26
    at LocalPdfManager_ensure [as ensure] (http://localhost:8080/viewer/js/pdf.worker.js:2460:12)
    at LocalPdfManager.BasePdfManager_ensureDoc [as ensureDoc] (http://localhost:8080/viewer/js/pdf.worker.js:2392:19)
    at http://localhost:8080/viewer/js/pdf.worker.js:34164:22
pdf.worker.js:224 Warning: Unsupported feature "unknown"
pdf.worker.js:224 Warning: Indexing all PDF objects
pdf.js:224 Warning: Unsupported feature "unknown"
PDFViewerPlugin.js:6384 PDF 83739da88f933552ca4aabe9d3ffe5bd [1.3 Acrobat Distiller 4.05 for Windows / -] (PDF.js: 1.1.469)
pdf.worker.js:232 Error: Bad encoding in flate stream
pdf.worker.js:233     at error (http://localhost:8080/viewer/js/pdf.worker.js:233:17)
    at Object.FlateStream_getCode [as getCode] (http://localhost:8080/viewer/js/pdf.worker.js:32119:7)
    at Object.FlateStream_readBlock [as readBlock] (http://localhost:8080/viewer/js/pdf.worker.js:32301:20)
    at Object.DecodeStream_getByte [as getByte] (http://localhost:8080/viewer/js/pdf.worker.js:31837:14)
    at Object.Lexer_nextChar [as nextChar] (http://localhost:8080/viewer/js/pdf.worker.js:31076:46)
    at Object.Lexer (http://localhost:8080/viewer/js/pdf.worker.js:31018:10)
    at Object.EvaluatorPreprocessor (http://localhost:8080/viewer/js/pdf.worker.js:12915:30)
    at Object.PartialEvaluator_getOperatorList [as getOperatorList] (http://localhost:8080/viewer/js/pdf.worker.js:11366:26)
    at http://localhost:8080/viewer/js/pdf.worker.js:2753:33
pdf.worker.js:224 Warning: Unsupported feature "unknown"
pdf.js:224 Warning: Unsupported feature "unknown"

Thank you in advance.

**Comment by yurydelendik** [comment] 2015-10-28 12:00
Based on provided information, the PDF document as corrupted. Closing as answered.

**Comment by sweety-wo** [comment] 2015-10-28 12:22
but it works in chrome default viewer then how can it be marked as courrpted??

**Comment by yurydelendik** [comment] 2015-10-28 12:27
To re-open an issue, please provide more information as requested by [guidelines for contributing](https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md), especially:

```
nk to the PDF, location in the PDF, screenshot, browser version, operating system, PDF.js version 
```

**Comment by sweety-wo** [comment] 2015-10-29 05:20
![image](https://cloud.githubusercontent.com/assets/14175105/10810775/598e93ae-7e2a-11e5-900f-9de1f818f002.png)


Link to PDF: https://drive.google.com/file/d/0BzKoRDCi8fjMOXNXeVUzcmdlVGs/view?usp=sharing
Browser Version: Chrome Version 46.0.2490.80 m
Operating system: Windows 7
PDF.Js Version: v1.1.366

**Comment by Snuffleupagus** [comment] 2015-10-29 12:27
I'm not able to reproduce any of the aforementioned issues with [PDF file linked above](https://drive.google.com/file/d/0BzKoRDCi8fjMOXNXeVUzcmdlVGs/view?usp=sharing), in either the latest version (`1.2.38`) *or* in version `1.1.366` of PDF.js.
I've tested in both Firefox Nightly 44 (buildID: 20151028030432) and Google Chrome Beta (47.0.2526.35 beta-m).

**Comment by yurydelendik** [comment] 2015-10-29 13:09
Closing as invalid. 

Based on screenshot, you are using viewer.js -- try to seeking support from them first since it's working with PDF.js without issue.

**Closed by yurydelendik** 2015-10-29 13:09 UTC

**Comment by sweety-wo** [comment] 2015-10-29 13:23
Yeah it is resolved..there was issue because server was serving chunked requests.. thank you for reviewing my issue.
