### ISSUE TITLE
PDF Text randomly missing strokes / is layered with white pixels

### ISSUE THREAD

**Issue by noelli** [mozilla/pdf.js#15624] opened 2022-10-25 14:24 UTC
Attach (recommended) or Link to PDF file here: https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf

Configuration:
- Web browser and its version: Chrome 105.0.5195.127 
- Operating system and its version: Windows 10 Education 10.0.19045
- PDF.js version: 2.16.105
- Is a browser extension: no

Steps to reproduce the problem:
1. Implemented the Previous/Next example from [here](https://mozilla.github.io/pdf.js/examples/) using the CDN-Version from jsdelivr on a Test-Website
2. calculate the scale to fit the devices width

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/26084306/197798315-12fc7142-fc32-40ca-883b-3482d0f2a943.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/26084306/197798032-9f7f7fee-7e2e-4bfa-a249-02ed4d0c4ccc.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://test.evgb.de/pages/aktuelles/gemeindebrief.php

**Comment by Snuffleupagus** [comment] 2022-10-25 16:10
Duplicate of #15304

**Closed by Snuffleupagus** 2022-10-25 16:10 UTC
