### ISSUE TITLE
Some document parts in pdf are missing

### ISSUE THREAD

**Issue by beyondkmp** [mozilla/pdf.js#16190] opened 2023-03-22 05:41 UTC
Attach (recommended) or Link to PDF file here: 
https://drive.google.com/file/d/1g2hLSyvgWeupRWYrseREP4eztuo6UZ3R/view?usp=sharing

Configuration:
- Web browser and its version:
Firefox 111.0.1 (64-bit)
- Operating system and its version:
Windows 11   10.29.0.7919
- PDF.js version:
v3.4.120
- Is a browser extension:
no

Steps to reproduce the problem:
1.  Open the file(https://drive.google.com/file/d/1g2hLSyvgWeupRWYrseREP4eztuo6UZ3R/view?usp=sharing)
2. When you scroll down, you will see that some document parts are missing. But when you switch to presentation mode, the file looks ok.

What is the expected behavior? (add screenshot)

Display completely, without any missing parts.

![image](https://user-images.githubusercontent.com/5462444/226813233-05663dc3-03be-4fb2-a2a9-f7602081cdcd.png)
![image](https://user-images.githubusercontent.com/5462444/226813251-22b24801-118e-42d2-9e9c-a7f20fba87b6.png)

What went wrong? (add screenshot)

1. Some document parts are missing.

![image](https://user-images.githubusercontent.com/5462444/226812280-cfcde6b2-e36d-4be9-9e09-a3c45b10c925.png)
![image](https://user-images.githubusercontent.com/5462444/226812313-b608b70a-968e-4bf8-97f3-c65a8a4c0de7.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-03-22 07:52
Duplicate of #14982

**Closed by Snuffleupagus** 2023-03-22 07:52 UTC
