### ISSUE TITLE
keybindings

### ISSUE THREAD

**Issue by aloispichler** [mozilla/pdf.js#15316] opened 2022-08-14 13:42 UTC
The viewers Evince, Okular, Zathura all use the vim-based keybindings

- `j` to scroll down a line (same as `↑`), and 

- `k` to scroll up a line (same as `↓`).

The vimum extension on chrome and on firefox does the same, as do all programs following the vim paradigm.

pdf.js, unfortunately, scrolls pages instead of lines. This breaks so many workflows when working with other programs. Even browser tabs behave differently depending on whether there is a pdf handled or not, and this is really annoying. It would be _really nice and important_ to reconcile this behavior.
Please check this inconsistency carefully and, please, do not just turn it down for some simplistic reason.

**Comment by Snuffleupagus** [comment] 2022-08-14 14:15
Duplicate of #14845

---

What's asked for here would require trying to *emulate* native browser scrolling-behaviour with JavaScript-code, which will never be perfect and would risk adding too much code/complexity for an edge-case feature.

**Closed by Snuffleupagus** 2022-08-14 14:15 UTC
