### ISSUE TITLE
PDF.js: Problems with German umlaut “ß” and “ü”

### ISSUE THREAD

**Issue by BerndS2020** [mozilla/pdf.js#14015] opened 2021-09-13 14:08 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 92.0 (64 bit)
- Operating system and its version: Windows 10
- PDF.js version: 2.11.91
- Is a browser extension: ?

Steps to reproduce the problem:
1. See chapter "What went wrong"

What is the expected behavior? (add screenshot)
Correct display of german umlaute "ü" and "ß"

What went wrong? (add screenshot)
Wrong display of german umlaute "ü" and "ß"
![grafik](https://user-images.githubusercontent.com/90627791/133097571-fd56252b-e23b-4152-9b00-0075968b56d6.png)

Our use case:
1. We create a PDF from our software. We use the font **ArialMT** for our PDF document.
2. The PDF is displayed correctly in PDF viewer tools (Adobe, Sumatra, FreePDF, …) 
3. The only tool in which the PDF is not displayed correctly is the built-in PDF viewer in Firefox.
4. It effects the characters “ß”, “ü”
5. German umlaute “ö” & "ä" works instead.

We have already analyzed the behavior and were able to determine that the internal character code in your PDF is (Identity-H). Could this encoding be the problem?
![grafik](https://user-images.githubusercontent.com/90627791/133097764-c00bc1d3-d684-46b8-af1e-059cb2d473c7.png)

Here is our understanding:
The 'Identity-H' encoding in a PDF means that the bytes in the string specify Glyph IDs: values that identify specific glyphs in a TrueType or OpenType font file. These Glyph IDs are not the same from font to font (e.g. 'A' may map to glyph ID 12 in a Helvetica font file, but to glyph ID 37 in Comic Sans). Because the string directly depends on a specific font, an 'Identity-H' encoding requires that the font file be embedded or subset within the PDF.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-09-13 14:12
> Attach (recommended) or Link to PDF file here:

Sorry, but this part of the issue template is *required* in order for this (or any other issue) to be actionable!

---

Generally speaking, the only way to *guarantee* that fonts always render correctly is by embedding them into the PDF document.

**Comment by Snuffleupagus** [comment] 2021-09-14 07:35
Closing as INCOMPLETE for now, we can re-open this is all of the necessary information is provided (see above).

**Closed by Snuffleupagus** 2021-09-14 07:35 UTC
Labels: 4-information-requested

**Comment by BerndS2020** [comment] 2021-09-14 07:38
We prepare a PDF document today for better understanding and to reproduce the problem.

**Comment by BerndS2020** [comment] 2021-09-14 13:06
Missing document delivered. Please re-open the issue again.

**Comment by Snuffleupagus** [comment] 2021-09-14 15:05
This looks (for all intents and purposes) like a duplicate of e.g. issue #11915, hence I don't think it needs to be re-opened.

Fixing these issues, without breaking other things in the process, may not be entirely simple unfortunately. Note also that if you're in control of the PDF generation, simply embedding the fonts in question will generally prevent these kind of problems.

**Comment by BerndS2020** [comment] 2021-09-15 07:25
Helllo @Snuffleupagus, 
is there a list of fonts that are fully supported and do not have this problem?

**Comment by Snuffleupagus** [comment] 2021-09-15 07:31
> is there a list of fonts that are fully supported and do not have this problem?

I'm not sure that I really understand the question here.

The problem is that you have a PDF document without embedded fonts, which thus forces the PDF viewer to essentially make some educated guesses on a suitable fallback (which isn't always perfect, as seen here.)
Hence the solution is to *always to embed fonts* into the PDF document, and these problems should generally not occur.
