### ISSUE TITLE
PDF is printed as image

### ISSUE THREAD

**Issue by adineag** [mozilla/pdf.js#8075] opened 2017-02-16 09:46 UTC
**Link to PDF file**: https://mozilla.github.io/pdf.js/web/viewer.html

**Configuration:**
- Web browser and its version: any
- Operating system and its version: Windows 10
- PDF.js version: 1.6.210

**Steps to reproduce the problem:**
1. Open the viewer in the link and press the print button
2. Select "Microsoft print to pdf" in the printer dialog and press ok

**What is the expected behavior?**
I expect the resulted pdf to be a copy of the printed pdf at the same quality
![clear-print](https://cloud.githubusercontent.com/assets/16132222/23015751/abe6cff2-f43c-11e6-8ca4-6e7c5f2bd255.PNG)

**What went wrong?** 
I get a pdf file that is a printed image of the actual pdf. If you zoom in you will notice this. I'm not sure if this is pdf.js related or this is the way pdf.js does the printing. If I use Adobe plugin to view the pdf in browser and print it with "Microsoft print to pdf" option, I get a same quality pdf ( with vectors, not images). Is this possible in pdf.js ? 
![blurred-print](https://cloud.githubusercontent.com/assets/16132222/23015825/f054b32a-f43c-11e6-8408-a4a23baf7dfc.PNG)

**Link to a viewer**: https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by jtnw** [comment] 2017-03-16 21:59
I'm pretty sure pdf.js renders each page as a 150dpi canvas which is then converted to an img tag. That would explain the quality degradation. Also you'll note you can no longer select text. I don't think there is a way around this.

**Comment by timvandermeij** [comment] 2017-03-16 22:01
You're right. There is nothing we can do at this moment as increasing the quality would mean a great increase in memory consumption, which most browsers won't take well. There is an open project for an SVG back-end (https://github.com/mozilla/pdf.js/projects/2) that would allow us to print vectors instead of images, but it's still a work in progress.

**Comment by zjf123** [comment] 2017-03-17 06:54
there is  something  you can try it.
[Improve print quality for all browsers #7488 ](https://github.com/mozilla/pdf.js/issues/7488)
[Fixed partial printing for IE / Edge and improved print quality for all browsers #7487](https://github.com/mozilla/pdf.js/issues/7487)

**Comment by NtH0** [comment] 2017-08-10 09:32
Cross-referencing Bugzilla report on this same issue
https://bugzilla.mozilla.org/show_bug.cgi?id=1386573

**Comment by timvandermeij** [comment] 2021-03-14 15:05
Closing since this is a duplicate of #2750.

**Closed by timvandermeij** 2021-03-14 15:05 UTC
Labels: 4-printing

**Comment by insinfo** [comment] 2023-10-31 20:56
Why is it that when you open a PDF file in Firefox, click on the print icon, it prints the PDF correctly without converting it to a Bitmap image, but when you use the PDF viewer in PDF.js, it prints as an image?
