### ISSUE TITLE
Slow rendering in IE

### ISSUE THREAD

**Issue by tudoragaf** [mozilla/pdf.js#8887] opened 2017-09-08 19:27 UTC
Link to PDF file (or attach file here):
https://files.fm/u/2qq444ss

Configuration:
- Internet Explorer 11.0.9600.18762
- Windows 7
- PDF.js version: 1.9.528

It takes more than one second to render each page. Firefox and Chrome behave as expected. Do you have any idea, why IE renders so slowly? 

![slow_rendering_ie](https://user-images.githubusercontent.com/16950929/30227962-00349a0e-94dc-11e7-9e3c-18a16f0acf98.png)

Link to the viewer: mozilla.github.io/pdf.js

**Comment by timvandermeij** [comment] 2017-09-08 20:05
IE11 lacks some features that we have to polyfill, which is almost always slower than using natively supported features. Although I'm not sure what particular feature is causing your issue, generally subpar performance in IE is caused by this.

**Comment by tudoragaf** [comment] 2017-09-19 20:09
Could you have a look at polyfills to find out, what feature causes this issue? I noticed, that the test files contain an embedded font and disabled some features (e.g font-face) but nothing changed.

**Comment by wojtekmaj** [comment] 2017-11-17 21:32
I suppose this might help us: #9121

**Comment by Snuffleupagus** [comment] 2017-12-09 13:04
Closing, since the PDF file is no longer available; please attach the file here (rather than linking it) in order to re-open the issue.

**Closed by Snuffleupagus** 2017-12-09 13:04 UTC
Labels: 4-ie11-specific
