### ISSUE TITLE
Scaling issue with screenshotted text

### ISSUE THREAD

**Issue by creulcat** [mozilla/pdf.js#15396] opened 2022-09-05 07:24 UTC
Attach (recommended) or Link to PDF file here:
[scaling_example.pdf](https://github.com/mozilla/pdf.js/files/9487535/scaling_example.pdf)
File contains a screenshot of a webpage with text, plus added notes.
Saved as a pdf file. Acrobat does show the text properly scaled and readable on 100%
In Firefox, the text is also scaled and readable.
Opening the exact same in Chrome, shows unreadable texts.

Configuration:
- Web browser and its version: Chrome 104.0.5112.102 (x64)
- Operating system and its version: Windows 11- 21H2
- PDF.js version: 2.16.105

Steps to reproduce the problem:
1. Download version 2.16.105
2. Change the pdf source in viewer.js to the attached file.
3. Open this in both FireFox and Chrome
4. Zoom to 100%

What is the expected behavior? (add screenshot)
In Firefox this show the PDF with properly scaled text
![firefox_js](https://user-images.githubusercontent.com/10871153/188390017-7edec99e-8e45-4b23-b608-84c03e95c352.png)

What went wrong? (add screenshot)
In Chrome, this text does not scale properly
![chrome_pdfjs](https://user-images.githubusercontent.com/10871153/188390010-09b2722b-2723-42bb-97bd-dc4f39fb9736.png)

**Comment by Snuffleupagus** [comment] 2022-09-05 08:56
Duplicate of #14641

**Closed by Snuffleupagus** 2022-09-05 08:56 UTC
