### ISSUE TITLE
Document outline sidebar opens on load

### ISSUE THREAD

**Issue by CristianNanan** [mozilla/pdf.js#8972] opened 2017-09-28 21:59 UTC
Link to PDF file (or attach file here):
[WorkingwithBookmarks.pdf](https://github.com/mozilla/pdf.js/files/1342480/WorkingwithBookmarks.pdf)

Configuration:
- Web browser and its version: Firefox 55
- Operating system and its version: Windows 8.1
- PDF.js version: 1.9.426
- Is an extension: No

What is the expected behavior? (add screenshot)
The sidebar is not open on load

What went wrong? (add screenshot)
![pdfjssidebar](https://user-images.githubusercontent.com/6821073/30992162-72848b9c-a476-11e7-8669-e6cef5601af5.PNG)

**Comment by Snuffleupagus** [comment] 2017-09-29 08:00
You get the exact same behaviour in Adobe Reader as well, since the PDF file *itself* specifies that this should happen when the document is opened (through the `/PageMode /UseOutlines` entry in the Root of the document).

In PDF.js default viewer, this behaviour can be turned off with by setting the `disablePageMode` preference to `true` if you wish to turn this behaviour off.[1]

Closing as answered, since this is working as intended.

---
[1] Setting the preference is done by executing `PDFViewerApplication.preferences.set('disablePageMode', true);` in the console, and then reloading the viewer.

**Closed by Snuffleupagus** 2017-09-29 08:00 UTC

**Comment by jscher2000** [comment] 2017-10-09 00:21
For users who do not want the sidebar to open automatically and are baffled by the above reference to the console:

(1) In a new tab, type or paste **about:config** in the address bar and press Enter/Return. Click the button accepting the risk.

(2) In the search box above the list, type or paste **pdfjs** and pause while the list is filtered

(3) Double-click the **pdfjs.disablePageMode** preference to switch the value from false to true

Now instead of the relevant panel opening automatically, if the PDF specifies that it should be displayed a green dot will appear on the sidebar button to alert you.

**Comment by orrblue** [comment] 2023-06-05 15:38
The setting to change seems to now be **pdfjs.sidebarViewOnLoad**. Set it to 0.
