### ISSUE TITLE
"Right bound" books not displaying properly in two-page view

### ISSUE THREAD

**Issue by twicepipes** [mozilla/pdf.js#13071] opened 2021-03-09 23:29 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 89.0.4389.82 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- Version hosted at https://mozilla.github.io/pdf.js/web/viewer.html
- Browser extension?: No

Steps to reproduce the problem:
1. Open a PDF with "Binding" property set to "Right Edge"
2. Set pdf.js to "wrapped scrolling"

**What is the expected behavior? (add screenshot)**
Pages within a right-bound book flow from right to left and are represented the same in the PDF viewer when the "right edge" binding is selected. 

This is from within Adobe Acrobat
![2021-03-09 18_31_47-](https://user-images.githubusercontent.com/23112157/110552691-c7b0bb80-8105-11eb-92e3-1eb5a01e3599.jpg)

**What went wrong? (add screenshot)**
Pages are displayed left to right in pdf.js
![2021-03-09 18_32_03-Window](https://user-images.githubusercontent.com/23112157/110552693-c8495200-8105-11eb-80ff-6a10e0b53d9c.jpg)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-03-10 10:56
Duplicate of #10736

**Closed** 2021-03-12 19:53 UTC
