### ISSUE TITLE
Print functionality inserts blank pages on Windows 10

### ISSUE THREAD

**Issue by pinkflag** [mozilla/pdf.js#6449] opened 2015-09-14 22:55 UTC
When I try printing in Chrome on my Windows 10 PC, I see blank pages inserted between regular ones. This doesn't happen on Win 7/8. This was a known issue: [2464](https://github.com/mozilla/pdf.js/issues/2464), which was resolved. But it seems to be back in Windows 10.

**Comment by timvandermeij** [comment] 2015-09-15 10:06
Closing as duplicate of #6345. This is a known bug in Chrome that has been fixed in the meantime in a later version.

**Closed by timvandermeij** 2015-09-15 10:06 UTC
