### ISSUE TITLE
Zoom issue in Chrome - Discolored line is getting displayed

### ISSUE THREAD

**Issue by gsampath127** [mozilla/pdf.js#7812] opened 2016-11-15 02:11 UTC
Link to PDF file (or attach file here):
http://hosted-stage.rightprospectus.com/documents/Harbor/summary_money_market.pdf

Configuration:
- Web browser and its version: Chrome Version 54.0.2840.71 m
- Operating system and its version: Window 7
- PDF.js version: Latest
- Is an extension: NA

Steps to reproduce the problem:
1) Open PDF file (http://hosted-stage.rightprospectus.com/documents/Harbor/summary_money_market.pdf) in Pdf Js Viewer in Chrome
2) Issue can be seen when we open PDF here - https://mozilla.github.io/pdf.js/web/viewer.html
3) Discolored line is getting shown as per below screen shots in all zoom modes except 100% zoom mode

What is the expected behavior? (add screenshot)
![100 zoom](https://cloud.githubusercontent.com/assets/12858790/20290499/4d897842-aaae-11e6-926a-5d41758ab14d.png)

What went wrong? (add screenshot)
1) Automatic Zoom
![automatic zoom](https://cloud.githubusercontent.com/assets/12858790/20290507/57a6b7ea-aaae-11e6-997b-3f00e13236bb.png)

2) 110% zoom
![110 zoom](https://cloud.githubusercontent.com/assets/12858790/20290513/63fb4718-aaae-11e6-9cd7-ba1f4b1f7c34.png)

3) 130 % zoom
![130 xoom](https://cloud.githubusercontent.com/assets/12858790/20290516/6a13d7c8-aaae-11e6-90d0-eea54e7277f0.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by gsampath127** [comment] 2016-11-23 21:49
Hi Team, Could you please look into above issue and lets us know.  Thanks.

**Comment by timvandermeij** [comment] 2016-11-23 21:57
I cannot reproduce this using Firefox 50, Arch Linux and the latest PDF.js development version. This appears to be a Chrome-specific issue that probably has to be reported upstream to the Chrome team.

**Comment by gsampath127** [comment] 2016-11-30 16:34
Hi Team,
This issue is happening in only Chrome. Could you please look into it and provide us details? did you raise ticket with Chrome team or do you want us to raise a ticket? (If you want us to raise, Can you guide us how to reach out to chrome team with steps regarding PDF.js - Chrome issue(regarding what could be reason causing this issue)).

Thanks.

**Comment by yurydelendik** [comment] 2016-11-30 16:48
I don't see defect of the Mac OSX.

The line in question is painted using regular setWidth, moveTo, lineTo and stroke operations:

<img width="1072" alt="screen shot 2016-11-30 at 10 46 39 am" src="https://cloud.githubusercontent.com/assets/1523410/20761971/5ac1df66-b6ea-11e6-9c69-a6bca66a1b31.png">

@gsampath127 Try to create HTML/Canvas test case and see if you can reproduce the problem -- Chrome team will request this test case.

**Comment by yurydelendik** [comment] 2016-11-30 19:32
@gsampath127 please report the following test case to the Chrome team:

http://jsbin.com/goyenunuvu/1/edit?js,output

```
<script>
var c = document.createElement('canvas');
c.width = 600; c.height = 600;
document.body.appendChild(c);
var ctx = c.getContext('2d');
ctx.fillStyle = 'green';
ctx.fillRect(0, 0, c.width, c.height);
ctx.strokeStyle = 'white';

for (var i = 0; i < 20; i++) {
  var scale = 1 + (i - 10) / 50;
  var y = i * 20 + 10;
  ctx.save();
  ctx.scale(scale, scale);
  ctx.translate(10, y);
  ctx.beginPath();
  ctx.moveTo(0, 0); ctx.lineTo(500, 0);
  ctx.stroke();
  ctx.restore();
}
</script>
```

**Comment by gsampath127** [comment] 2016-12-01 03:20
Thanks timvandermeij for HTML/Canvas test case. 

Issue has been reported in chrome forum, - 
https://productforums.google.com/forum/#!topic/chrome/3xbBhA7f3VY;context-place=forum/chrome

Please let me know if you want to add any details to above chrome post.
 
Will update you as soon as we get reply from chrome team.

**Comment by gsampath127** [comment] 2016-12-01 21:22
Hi Team,

As per reply from google team (https://productforums.google.com/forum/#!topic/chrome/3xbBhA7f3VY;context-place=forum/chrome), Unchecking **Use hardware acceleration (Menu> Settings> Show Advanced Settings > System menu)** did work and we do not see any issue. We hope this problem will be resolved in future Chrome versions.

Thanks yurydelendik for HTML/Canvas test case and looking into this.

**Comment by yurydelendik** [comment] 2016-12-01 21:45
@gsampath127  I don't think it was fixed --  it sounds like a workaround and certainly will make your instance of Chrome slower due to disabling hardware acceleration. Try reporting the issue at https://bugs.chromium.org/p/chromium/issues/ (without mentioning PDF.js since it's HTML/Canvas issue rather than PDF viewer)

**Comment by timvandermeij** [comment] 2020-05-24 14:18
Closing since this is not something we can fix and should be reported to the Chrome bug tracker instead. It might have been an upstream issue that is already resolved now.

**Closed by timvandermeij** 2020-05-24 14:18 UTC
Labels: 2-image-quality, 3-upstream, 4-chrome-specific, 4-os-windows
