### ISSUE TITLE
How to adjust the proportion of PDF printing

### ISSUE THREAD

**Issue by WuGuozhi** [mozilla/pdf.js#7968] opened 2017-01-18 08:50 UTC
Link to PDF file (or attach file [here):]111.pdf

Configuration:
- Web browser and its version: google chrome
- Operating system and its version: win10
- PDF.js version:1.4.20
- Is an extension:

Steps to reproduce the problem:
1. 
![image](https://cloud.githubusercontent.com/assets/7566177/22056755/9a2d049a-dd9c-11e6-9cdb-b89ef173d4cf.png)
![image](https://cloud.githubusercontent.com/assets/7566177/22056763/a9403e02-dd9c-11e6-9da0-d5a941576bba.png)
When printing
![image](https://cloud.githubusercontent.com/assets/7566177/22056860/14c3d5d0-dd9d-11e6-8c4c-9b608a379d44.png)
Wave line is not ink point

May be the proportion of printing problems, how to adjust the proportion of printing

2.

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/7566177/22056920/7900a26c-dd9d-11e6-94eb-526517013d7d.png)

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/7566177/22056935/85693dac-dd9d-11e6-9d11-3daaed581576.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[111.pdf](https://github.com/mozilla/pdf.js/files/713384/111.pdf)

**Comment by timvandermeij** [comment] 2021-04-25 15:59
Closing since this is a duplicate of #2750 where due to rasterization the quality is lower.

**Closed by timvandermeij** 2021-04-25 15:59 UTC
Labels: 2-image-quality, 4-printing
