### ISSUE TITLE
large image pdf not showing in iOS safari

### ISSUE THREAD

**Issue by strawhat-sugawara** [mozilla/pdf.js#16037] opened 2023-02-10 02:29 UTC
Attach (recommended) or Link to PDF file here:[noTextPdf.3.pdf](https://github.com/mozilla/pdf.js/files/10703028/noTextPdf.3.pdf)

Configuration:
- Web browser and its version: safari 15.5 / safari 14.1
- Operating system and its version: iOS 15.5 / iOS 14.5.1
- PDF.js version: 3.3.122 legacy
- Is a browser extension: none

Steps to reproduce the problem:
1.  Open this file (noTextPdf.3.pdf) on PDFjs Viewer
in PC Chrome/Edge/FireFox is Fine.
in iOS Safari is bad. (only white page)

What is the expecte behavior? (add screenshot)
It displays fine in PC Chrome/Edge/FireFox
![image](https://user-images.githubusercontent.com/24579744/217982943-cdddc6f9-7af9-4e8f-aa38-4c4f96e4c81a.png)

What went wrong? (add screenshot)
only white page in safari
![ファイル_000](https://user-images.githubusercontent.com/24579744/217984154-3c8e685e-c3f3-4d86-bca3-c0c127d0a6ce.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by strawhat-sugawara** [comment] 2023-02-10 03:01
It may have something to do with #6741
iOS and Android has a small canvas size.

**Comment by Snuffleupagus** [comment] 2023-02-10 09:08
Duplicate of #9474

**Closed by Snuffleupagus** 2023-02-10 09:08 UTC
