### ISSUE TITLE
pdf.js version 2.6 pdf forms support

### ISSUE THREAD

**Issue by 4vitek** [mozilla/pdf.js#12430] opened 2020-09-30 22:28 UTC
Hello,
I understand that starting with version 2.6  ,the support for pdf (acro) forms was added.
This feature works properly, but it seems that there is no support for the RTL languages like Hebrew or Arabic, when using the download and print methods.
Is there a way to accomplish this with PDF.js? 

Thank you,
Victor

**Comment by Snuffleupagus** [comment] 2020-10-01 08:11
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is there's no actionable information and the issue is thus INVALID.

**Comment by 4vitek** [comment] 2020-10-01 08:44
Attach (recommended) or Link to PDF file here: **Any PDF form will do.**

Configuration:
- Web browser and its version: **Version 85.0.4183.102 (Official Build) (64-bit)**
- Operating system and its version: Windows 10 Pro
- PDF.js version:  I reproduced it here: [](https://mozilla.github.io/pdf.js/web/viewer.html)


Steps to reproduce the problem:
1. Open [](https://mozilla.github.io/pdf.js/web/viewer.html)
2.upload any pdf form , fill Hebrew or Arabic 

What is the expected behavior? The RTL fonts will be saved correctly on download or printing form.

What went wrong? The text wasn't saved correctly.

**Comment by Snuffleupagus** [comment] 2020-10-01 08:57
This is possibly a duplicate of issue #12280, but there's still *required* information missing here!

> Attach (recommended) or Link to PDF file here: **Any PDF form will do.**

You still need to provide an actual PDF document here, since there's a possibility of that mattering and to save peoples time.

> Upload any pdf form , fill Hebrew or Arabic .

Since not everyone speaks those languages, you'll need to provide the *exact* strings you used when testing.
Furthermore, you should also mention in *exactly* which text fields those strings were added (or simply include a screen-shot).

**Comment by calixteman** [comment] 2020-10-01 09:14
@4vitek it'd be nice if you could provide several examples of such pdf.

**Comment by 4vitek** [comment] 2020-10-01 09:54
@calixteman Thank you. For example :
[test.pdf](https://github.com/mozilla/pdf.js/files/5310958/test.pdf)
With the viewer I fill Hebrew text  and after downloading I will get this file as a result:
[AftertestDownload.pdf](https://github.com/mozilla/pdf.js/files/5311016/AftertestDownload.pdf)

**Comment by Snuffleupagus** [comment] 2021-01-11 21:38
Duplicate of #12280, perhaps?

**Comment by calixteman** [comment] 2021-01-12 10:39
There are several problems here:
 - resources dictionaries are not correctly merged:
   * https://github.com/mozilla/pdf.js/blob/master/src/core/primitives.js#L211
   * if `value` is a `ref` and if it's merged with a `dict` then it doesn't work.
 - the font in `DA` is `/Tahoma` and this font is in `acroform` dictionary:
   * there is no `ToUnicode` entry so we can't encode a given string.
   * I don't find in the information we've for this font anything which help to know how to encode a string

First issue is easy to address but the for the second it's a way harder.
A perfect solution will be to find a suitable font to render the string, extract the glyphs we need and write everything in the file but we need to find a font.

**Comment by IsmailQasemNafee** [comment] 2021-01-20 09:48
hi
I have the same issue with Arabic text when using print or save
original file:- 
[new_document.pdf](https://github.com/mozilla/pdf.js/files/5841467/new_document.pdf)
file after print:-
[printfile.pdf](https://github.com/mozilla/pdf.js/files/5841477/printfile.pdf)

**Comment by marco-c** [comment] 2022-11-17 14:25
This should have been fixed by #15587.

**Closed by marco-c** 2022-11-17 14:25 UTC
Labels: annotations, form-acroform
