### ISSUE TITLE
Incorrect rendering of annotations

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#13915] opened 2021-08-20 06:58 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 95.0.4612.0 (Official Build) canary (64-bit)
- Operating system and its version: Windows 10 Home 20H2 19042.1165
- PDF.js version: 2.9.147
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Create a pdf with box annotation with formatting s.a. italics, bold, etc
2.

What is the expected behavior? (add screenshot)
1.Date and time should be set
2.Formatting should be respected (e.g., bold, italics, subscript, superscript)

mouse-over:
![pdfjs_OK](https://user-images.githubusercontent.com/2311076/130192780-7352f7bf-a01b-4b92-8d79-11cbed96bec9.jpg)

clicked:
![pdfjs_OK_full](https://user-images.githubusercontent.com/2311076/130193076-0f3b3830-5ea5-42d9-8274-472427fec133.jpg)

What went wrong? (add screenshot)
1.Date and time aren't displayed properly
2.Formatting not respected

![pdfjs_BAD](https://user-images.githubusercontent.com/2311076/130192847-0490f8c1-6a39-4adf-a0f1-1a9a5419afbd.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-08-20 19:34
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is required in order for this (or any) issue to be actionable/valid.

> PDF.js version: 2.9.147

That's not an official release; please please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Date and time should be set

That'd suggest a *custom* implementation of the viewer, where localization isn't handled correctly (since otherwise that cannot happen).

> Formatting not respected

Given that PopupAnnotations are handled separately from the general page rendering (in the PDF.js viewer), there may be some *smaller* formatting discrepancies between e.g. Adobe Reader and the PDF.js demo viewer.

**Comment by qwer1304** [comment] 2021-08-21 05:02
In version 2.3.164 (Official Chrome release) the result is the same.
(Chrome Version 94.0.4606.12 (Official Build) dev (64-bit))
From what I can see, pdf.js does NOT respect ANY formatting in annotations (italics, bold, subscript, superscript).

**Comment by Snuffleupagus** [comment] 2021-08-21 07:40
Duplicate of #2966

**Closed by Snuffleupagus** 2021-08-21 07:40 UTC
Labels: 4-information-requested
