### ISSUE TITLE
[Bug]: some HDR images are rendered duller in pdf.js than in Adobe Acrobat reader 

### ISSUE THREAD

**Issue by droidhdr** [mozilla/pdf.js#18485] opened 2024-07-23 05:11 UTC
### Attach (recommended) or Link to PDF file

[hdr.pdf](https://github.com/user-attachments/files/16343928/hdr.pdf)

### Web browser and its version

Firefox 128.0 (64-bit)

### Operating system and its version

macOS Sonoma version 14

### PDF.js version

3.11.174

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Use Firefox to open hdr.pdf attached in this bug report.
2. Observe that the images are rendered dull without high dynamic range of colors
3. For comparison, use Adobe Acrobat reader or macOS preview app to open hdr.pdf and observe that the images are rendered in high dynamic range of colors

### What is the expected behavior?

Expected: the images in hdr.pdf should be rendered with HDR colors in pdf.js and in Firefox since it uses pdf.js.

### What went wrong?

Actual: the images in hdr.pdf are not rendered with HDR colors in pdf.js and in Firefox.

**Comment by Snuffleupagus** [comment] 2024-07-23 07:08
Duplicate of #2856

**Closed by Snuffleupagus** 2024-07-23 07:08 UTC
