### ISSUE TITLE
PDF fails to open in pdf.js

### ISSUE THREAD

**Issue by kohepu** [mozilla/pdf.js#12242] opened 2020-08-19 02:54 UTC
Attach (recommended) or Link to PDF file here:
[Sample.pdf](https://github.com/mozilla/pdf.js/files/5093758/Sample.pdf)

Configuration:
- Web browser and its version: Firefox 79.0 (64-bit)
- Operating system and its version: Windows 10 1909
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
Attempt to view PDF linked above in https://mozilla.github.io/pdf.js/web/viewer.html

It opens correctly in Chrome/Edge and Acrobat, but is failing in Firefox/pdf.js.  Output:

> PDF.js v2.6.266 (build: b52b36f6)
> Message: 
> Stack: putBinaryImageData@https://mozilla.github.io/pdf.js/build/pdf.js:4971:13
> CanvasGraphics_paintInlineImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:6523:27
> CanvasGraphics_paintImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:6469:12
> CanvasGraphics_executeOperatorList@https://mozilla.github.io/pdf.js/build/pdf.js:5296:22
> _next@https://mozilla.github.io/pdf.js/build/pdf.js:3901:39
> _scheduleNext/<@https://mozilla.github.io/pdf.js/build/pdf.js:3889:16

**Comment by Snuffleupagus** [comment] 2020-08-19 07:57
Duplicate of #6741.

**Closed** 2020-08-19 19:40 UTC
