### ISSUE TITLE
How can I see which version of pdf.js I am using? (feature request for an about box)

### ISSUE THREAD

**Issue by foobar13373** [mozilla/pdf.js#6518] opened 2015-10-11 09:21 UTC
Where in pdf.js is the typical "about" window/box that programs use to have? There is none, isn't it? I think there should be such a thing.

I'm using the built-in version of FF41, but I have no idea for which version I should file a bug request if I ever should find one or in which changelog I have to look to find out if I already have this or that feature in my version.

**Comment by Snuffleupagus** [comment] 2015-10-11 09:32
Closing as duplicate of issue #5884.
As explained there, the version number can be found in the console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>).
When filing bugs, referring to the exact Firefox version is enough when using the built-in PDF Viewer.

**Closed by Snuffleupagus** 2015-10-11 09:32 UTC
