### ISSUE TITLE
PDF file not rendering properly

### ISSUE THREAD

**Issue by richkniles** [mozilla/pdf.js#7318] opened 2016-05-11 19:07 UTC
Link to PDF file (or attach file here):
[New.pdf](https://github.com/mozilla/pdf.js/files/259989/New.pdf)

Configuration:
- Web browser and its version:Chrome Version 50.0.2661.94 (64-bit),
   also Safari Version 9.0.1 (11601.2.7.2)
- Operating system and its version: Mac OS X v10.11.1
- PDF.js version: pdfjs-1.4.20-dist, also tried pdfjs-1.5.188-dist
- Is an extension: No

Steps to reproduce the problem:
Execute in dev tools console in Chrome:

    PDFJS.disableWorker = true;
    PDFJS.getDocument('<url to document>').then(function(pdf){
      pdf.getPage(1).then(function(page){
        viewport = page.getViewport(1);
        canvas = document.getElementById('render-doc-here');
        context = canvas.getContext('2d');
        canvas.width = viewport.width;
        renderContext = {canvasContext: context, viewport: viewport};
        page.render(renderContext);
      })
    });

What is the expected behavior? 
<img width="827" alt="screenshot if i just load the url of pdf" src="https://cloud.githubusercontent.com/assets/1834068/15192942/6f80cf76-1770-11e6-8e2a-3c05d59c2529.png">

What went wrong? 
<img width="625" alt="screenshot of bad render" src="https://cloud.githubusercontent.com/assets/1834068/15192948/7b069e02-1770-11e6-8ac2-515b80ac6f5a.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): not hosted

**Comment by yurydelendik** [comment] 2016-05-11 19:20
Did you try to setup proper PDFJS.cMapUrl and PDFJS.cMapPacked ? Some documents require external CMaps to be loaded. It will be easier to tell if the complete example was published online (code snippet is not helping in your case). Can you publish that for us?

**Comment by richkniles** [comment] 2016-05-11 20:28
I made a standalone example and the page renders properly in that.  So it must be some interaction between PDFJS and the rest of my app which is a rails served Ember.js app.

Is there some documentation about CMaps? I don't see anything about that in the examples.

**Comment by yurydelendik** [comment] 2016-05-11 20:43
> Is there some documentation about CMaps? I don't see anything about that in the examples.

See e.g. https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js

**Comment by yurydelendik** [comment] 2016-05-11 20:49
>  So it must be some interaction between PDFJS and the rest of my app which is a rails served Ember.js app

That is the important part of this issue. If you could provide minimal example online, we could see what you are doing wrong (plus probably created an example for future PDF.js Ember users with similar problem).

**Comment by richkniles** [comment] 2016-05-11 21:56
Incidently, it renders MANY other PDFs just fine, so there is something different about this pdf.

I'll think about how to reproduce in a minimal example.

**Comment by richkniles** [comment] 2016-05-14 03:00
here is a minimal example:

add pdf.js and pdf.worker.js, and the above attached New.pdf to the web directory of the pdf.js repo, and then add this file: 

test.html:

    <!DOCTYPE html>
    <html>
      <head>
        <script src='pdf.js'></script>
        <script src='pdf.worker.js'></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/ember.js/2.4.3/ember.min.js" ></script>
        <script>
          PDFJS.disableWorker = true;
          PDFJS.getDocument('http://localhost:8888/web/New.pdf').then(function(pdf){
            pdf.getPage(1).then(function(page){
              viewport = page.getViewport(1);
              canvas = document.getElementById('render-doc-here');
              context = canvas.getContext('2d');
              canvas.width = viewport.width;
              canvas.height = viewport.height;
              renderContext = {canvasContext: context, viewport: viewport};
              page.render(renderContext);
            })
          });
        </script>
      </head>
      <body style="font-size:12px;">
        <canvas id='render-doc-here'></canvas>
      </body>
    </html>

Then run gulp server, and load the page _http://localhost:8888/web/test.html_
when I load that page I get a display with only the two lines of text displayed above instead of a whole page of text. If I comment out the disableWorker = true line, it loads properly.  However in my real project that does not fix the problem. Eliminating the load of ember.min.js also makes it load properly.

**Comment by Snuffleupagus** [comment] 2016-05-14 12:17
I seems that the problem is with Ember, which is adding an enumerable `_super` property on Arrays. Hence this seem to be the same underlying problem as in #7064, please refer to the discussion there.

This is an issue with Ember, and not PDF.js, hence I'm closing this issue.

**Closed by Snuffleupagus** 2016-05-14 12:17 UTC
Labels: 1-other, 4-triage-needed

**Comment by richkniles** [comment] 2016-05-17 15:44
For future reference to others interested in using PDF.js with Ember, turning off extensions for Array appears to fix the issue of incorrect pdf rendering of some pdf files. 
 https://guides.emberjs.com/v2.5.0/configuring-ember/disabling-prototype-extensions/

**Comment by nabihahossain** [comment] 2016-05-31 19:35
@richkniles I am new to Ember.js and Node.js, and I'm having trouble using PDF.js with Ember. Can you please give me some guidance on proper installation and placement of code in the Ember app structure?

**Comment by lcc19941214** [comment] 2017-11-21 07:04
thx so much!!!!!
I used to struggle with this issue for a long time, because this issue happened cross different versions of pdfjs-dist. Some rendered correctly, while some not.
