### ISSUE TITLE
PDF produced with LuaTeX 2.08 renders badly on normal zoom levels

### ISSUE THREAD

**Issue by vedranmiletic** [mozilla/pdf.js#12835] opened 2021-01-08 10:34 UTC
Attach (recommended) or Link to PDF file here:

The PDF file produced by LuaTeX 1.12: [lipsum-112.pdf](https://github.com/mozilla/pdf.js/files/5786648/lipsum-112.pdf)

The PDF file produced by LuaTeX 2.08: [lipsum-208.pdf](https://github.com/mozilla/pdf.js/files/5786649/lipsum-208.pdf)

Viewing them with Evince (and I assume Adobe Reader, I don't have it at hand to test) shows only minor differences in (horizontal) character spacing, which I would expect; the text looks reasonably good either way. However, viewing them with PDF.js shows a large difference (details and screenshot below) at normal zoom levels; zooming in makes that difference go away.

Configuration:
- Web browser and its version: Firefox 84.0.1
- Operating system and its version: Fedora 33
- PDF.js version: whatever is bundled with Firefox 84.0.1
- Is a browser extension: no, built-in

Steps to reproduce the problem:
1. Open both attached PDF files in PDF.js.
2. Compare the differences.

What is the expected behavior? (add screenshot)

Both should be rendered like `lipsum-112.pdf` is. ![lipsum-pdfjs-112](https://user-images.githubusercontent.com/246061/104005069-dda50d00-51a4-11eb-8385-9915f383c57f.png)

What went wrong? (add screenshot)

Rendering of `lipsum-208.pdf` is pretty bad; as you can observe, b, m, n, p, and r (and possibly others) are moved slightly above other letters: ![lipsum-pdfjs-208](https://user-images.githubusercontent.com/246061/104005100-e8f83880-51a4-11eb-8b2e-f22b87bb440d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by janpe2** [comment] 2021-01-08 14:00
Those two fonts have different hinting information, so some rendering differences are expected. The value of the `BlueScale` entry is `3.963E-2` in `lipsum-112.pdf` but `0` in `lipsum-208.pdf`. `BlueScale` controls the overshoot suppression that should keep the tops/bottoms of glyphs at the same level. Probably zero is not a good value for `BlueScale`.

https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/T1_SPEC.pdf#%5B%7B%22num%22%3A252%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C87%2C541%2C1%5D

**Comment by calixteman** [comment] 2021-01-08 14:10
I opened the second pdf with Acrobat reader DC under windows 10 and at 125% there is the same rendering "issue":
![image](https://user-images.githubusercontent.com/5641725/104024390-e4695b00-5177-11eb-92fc-baf5840dc43e.png)
so as pointed by @janpe2 the issue is likely a font issue.

**Comment by timvandermeij** [comment] 2021-01-08 19:11
Closing since this looks like the expected behavior and is a problem with the font data in the file itself.

**Closed by timvandermeij** 2021-01-08 19:11 UTC
