### ISSUE TITLE
Crescendo music sign rendering broken using Firefox/Ubuntu 14.04

### ISSUE THREAD

**Issue by mfiedler** [mozilla/pdf.js#6036] opened 2015-05-20 21:41 UTC
The crescendo/decrescendo signs in [1] on page 6 are rendered incorrectly using Firefox 38.0/Ubuntu 14.04 x86-64 (tested using the built-in and the current demo version [2] of pdf.js). However, the problem does not occur using Iceweasel 31.7.0/Debian Wheezy x86 (tested built-in and current demo version).

  [1] http://petrucci.mus.auth.gr/imglnks/usimg/f/fc/IMSLP235031-WIMA.9b94-deumessb.pdf
  [2] http://mozilla.github.io/pdf.js/web/viewer.html

![screenshot from 2015-05-20 23 04 19](https://cloud.githubusercontent.com/assets/116578/7737161/4ee5bf96-ff49-11e4-8d44-0b2123bf4279.png)

**Comment by timvandermeij** [comment] 2015-05-21 10:03
Renders fine for me using Windows 7 x64, Firefox 38.0.1 and the latest PDF.js development version. Could you try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if the problem remains?

**Comment by mfiedler** [comment] 2015-05-21 11:50
As written in my report, I have already tried it with https://mozilla.github.io/pdf.js/web/viewer.html and the problem seems to depend only on the platform used, not on the pdf.js version.

**Comment by yurydelendik** [comment] 2015-05-21 12:48
Smaller test case http://jsbin.com/qisura/1/

**Comment by timvandermeij** [comment] 2016-02-23 22:30
@mfiedler Are you still able to reproduce this using up-to-date graphics drivers and the latest PDF.js viewer? I cannot reproduce this on Arch Linux.

**Comment by SamyCookie** [comment] 2016-02-24 07:24
Render fine either on Iceweasel 44, pdf.js 1.1.551 and Debian Stretch (testing) 64.

**Comment by mfiedler** [comment] 2016-03-01 12:36
I can still reproduce this running current pdf.js demo version on Ubuntu 15.10 x86-64 (Live CD) and Firefox 41.0.2 from Ubuntu (using a virtual machine with Ubuntu 14.04 as host system, don't know whether this could be important)

**Comment by timvandermeij** [comment] 2018-08-26 13:50
Fixed in the most recent version. Both the test case above and the PDF file render correctly on Linux. If any problem remains, consider using different graphics drivers as we cannot reproduce it anymore on other Linux-based platforms.

**Closed by timvandermeij** 2018-08-26 13:50 UTC
Labels: 4-font-conversion, 4-font-type1, 4-os-linux
