### ISSUE TITLE
PDF Render Issue in 2.3.200

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#11597] opened 2020-02-14 11:42 UTC
Attach (recommended) or Link to PDF file here:
[CLIENT_TEST.pdf](https://github.com/mozilla/pdf.js/files/4204251/CLIENT_TEST.pdf)

Configuration:
- Web browser and its version:Chrome 79.0.3945.130, Firefox 72.0.2
- Operating system and its version:Windows 10
- PDF.js version: 2.3.200
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached PDF, 
2. page 2 bottom left corner there is a callout with text "UV Blocking"
3. Issue relates to the width of the border and the gradient color.

What is the expected behavior? (add screenshot)
In Acrobat the border is thin and the gradient fades from the center to left and right
In Firefox built in pdfjs the border is a little bit thicker and the gradient fades left to right
In our own app using 2.2.228 the border render the same as with FireFox builtin. 
In our own app using 2.3.200 the border is very thick and fades left to right

What went wrong? (add screenshot)
PDF rendered differently between 2.3.200 and 2.2.228, border is double thickness

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by janpe2** [comment] 2020-02-18 19:34
Maybe a duplicate of #11018. A shading pattern is used as the "color" when a path is stroked.

**Closed** 2021-05-12 18:28 UTC
Labels: 4-shading-pattern
