### ISSUE TITLE
Set focus into the "Document Properties" dialog

### ISSUE THREAD

**Issue by MarioBatusic** [mozilla/pdf.js#9560] opened 2018-03-14 14:10 UTC
Configuration:
- Web browser and its version: ALL
- Operating system and its version: ALL
- PDF.js version: Last

Steps to reproduce the problem:
1. After activating the Button to open the "Document properties" dialog, the focus stays at the button and no announcement is provided for the screen reader software about the opening of a dialog pop-up. Thus a screen reader user has no access to this dialog.

What is the expected behavior? What is to do?

"Document properties" dialog is realised as a pop-up (the markup is positioned per JavaScript on the end of the DOM). 
* Use proper ARIA attributes to semantically mark-up the dialog;
* After shoing the dialog set the focus programmatically to the 1. interactive UI component in the dialog;
* Make the dialog modal also for a keyboard-only users.
* Look up the implementaion for the above tasks here: https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal

**Comment by Snuffleupagus** [comment] 2022-03-17 20:19
> FYI - making dialog modal does not help on the keyboard navigation per local testing.

I don't really understand what this actually means, since there's no standard "modal" HTML element.
Please keep in mind that *this issue* simply asks for better a11y for the existing UI element, and nothing more.

**Comment by Snuffleupagus** [comment] 2022-04-02 08:38
With the changes PR #14710, which fixed issue #14698, we're now using the `<dialog>` element for all of the previous overlays.
This *should* mean that a11y is generally improved here, and that additional improvements are (mostly) blocked by browser themselves improving handling and a11y of `<dialog>` elements.

Given the age of this issue, and in particular the changes made in PR #14710, I'm going to close this now. If there are remaining issues here, which are not caused by browser support for the `<dialog>` element, please open new issues specifically for those.

**Closed by Snuffleupagus** 2022-04-02 08:38 UTC
Labels: viewer, ux
