### ISSUE TITLE
text selection select all below or above on edge browser in iframe

### ISSUE THREAD

**Issue by FahadQurashi49** [mozilla/pdf.js#11367] opened 2019-11-28 07:31 UTC
Attach (recommended) or Link to PDF file here:
 https://mozilla.github.io/pdf.js/web/viewer.html (opened in iframe on edge browser)

Configuration:
- Web browser and its version: Microsoft Edge 44.18362.449.0
- Operating system and its version: windows 10
- PDF.js version:  used on pdfjs demo
- Is a browser extension: no

Steps to reproduce the problem:
1.  open pdfjs demo (https://mozilla.github.io/pdf.js/web/viewer.html) in an iframe on edge browser
2. code for running pdfjs demo in iframe:

```
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <iframe width="100%" height="100%" allowfullscreen="" 
          src="https://mozilla.github.io/pdf.js/web/viewer.html"
          style="left: 0px; top: 0px; position: fixed"
          mozallowfullscreen="" webkitallowfullscreen=""></iframe>
    </body>
</html>
```

3. copy paste above code in an html file with .html extension, save file. open that file in edge browser.

4. after pdf is opened select any text in it

What is the expected behavior? (add screenshot)
It should select text word by word as it is doing in other browsers than edge:
![pdfjs_chrome](https://user-images.githubusercontent.com/14121797/69785396-c5a93e80-11d9-11ea-9da6-2e67292610dc.png)

What went wrong? (add screenshot)
But it does not select text as expected and select all the text below or above the mouse pointer in edge browser:
![pdfjs_edge](https://user-images.githubusercontent.com/14121797/69785546-1de04080-11da-11ea-9031-4ed7a64f33ba.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

**Comment by Snuffleupagus** [comment] 2019-11-28 09:43
> Web browser and its version: Microsoft Edge 44.18362.449.0

Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support;
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

Furthermore, this may simply be a duplicate of e.g. issue #9843.

**Comment by FahadQurashi49** [comment] 2019-11-28 11:55
Thanks for quick response, 

> Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support;

its sad to hear that because we still have good number of edge browser users.

> Furthermore, this may simply be a duplicate of e.g. issue #9843.

I have already tried 
`PDFViewerApplication.preferences.set('textLayerMode', 2);`
but issue persisted.

**Comment by timvandermeij** [comment] 2019-11-28 22:14
Closing since this does look like a duplicate so we can track the status of this problem centrally over there. Thanks.

**Closed by timvandermeij** 2019-11-28 22:14 UTC
