### ISSUE TITLE
Why pdf js print file looks different than acrobat print file

### ISSUE THREAD

**Issue by 111crb111** [mozilla/pdf.js#5773] opened 2015-03-02 16:18 UTC
I use pdf js to print text on letterhead and the text should get into the form field, but pdf js, makes a big left margin and reduces the text size. Im compare with the acrobat, he prints it right.
How to remove the margin on the right and and disable text scaling?

**Comment by timvandermeij** [comment] 2015-03-02 19:05
@111crb111 Please post an example PDF file and more information on your browser and operating system.

**Comment by 111crb111** [comment] 2015-03-03 08:35
Thanks for answer! And sorry about low information.
I have Windows 7, browser Chrome 40.0.2214.115 m  
PDFJS.version = '1.0.1135';
PDFJS.build = 'ccf05c7';
Dont know its old version or not but i was try load file in example: http://mozilla.github.io/pdf.js/web/viewer.html and have same result.


![gr](https://cloud.githubusercontent.com/assets/6359188/6458836/c4997166-c190-11e4-9c37-926188f5ab8c.jpg)

Im embed pdf file with jpg extension becaouse cant load pdf so just replace .jpg with .pdf

Thanks for helping me :D

**Comment by robertbaer** [comment] 2015-06-15 17:25
I  log to my Chase banking account and look at a statement which is a PDF.
A new (smaller but can be made full screen) window pops up and i see my statement.
I have verified that WHAT I SEE is complete and correct by other means; about the last third of page one shows a number of transactions, below that(almost last line) is a statement like "this is a facsimile".
BUT when i go to print, NONE OF THAT exists.
![chase](https://cloud.githubusercontent.com/assets/12898949/8165754/f1daec0a-1347-11e5-9d97-9ea4cbe3cbd3.gif)
This is a screen capture of the top of the "Adobe viewer" that FireFox 37.0.2 brings up.
I assure you that is NOT ANY VIEWER i have available in my OS(Win7), and i have no plugins or addons that relate to PDFs.
SeaMonkey 2.29.1 brings up a viewer i do have available (Foxit reader),and that works correctly.
HELP??

**Comment by Snuffleupagus** [comment] 2019-02-04 08:42
> https://drive.google.com/file/d/0B869Sv33xwGWS3VmOTVocm9RTDQ/view?usp=sharing

The PDF file is no longer available, and furthermore the issue is really old; closing as INCOMPLETE for now?

**Closed** 2019-02-04 22:50 UTC
Labels: 4-printing
