### ISSUE TITLE
Weird characters from custom font type in TCPDF

### ISSUE THREAD

**Issue by RobbieLensen** [mozilla/pdf.js#6344] opened 2015-08-11 19:50 UTC
Hi all,

In my web application, I'm creating PDF files using the TCPDF libraries.
In one of my PDFs, I'm using an otf font (Tittilium) that I converted into .z, .ctg.z and .php using http://fonts.snm-portal.com/ for use in TCPDF.

So far, so good.

When I load this PDF from an int8Array (so not from a fysical file) using pdf.js 1.0.277 everything works as it should:

![image](https://cloud.githubusercontent.com/assets/8201556/9208183/5ae7c874-4072-11e5-8b97-ac01089e6497.png)

However, feeding the same document into pdf.js 1.1.215 the font is completely mangled:

![image](https://cloud.githubusercontent.com/assets/8201556/9208262/c88aa8c4-4072-11e5-9ec9-489d18b51860.png)

Do you have any idea what might be causing this?
Many, many thanks for your help!

**Comment by timvandermeij** [comment] 2015-08-11 21:04
It might be a regression. Could you provide an example PDF for us to work with?

**Comment by RobbieLensen** [comment] 2015-08-12 06:28
Hi Tim,

Sure, here it is:
http://home.lencae.be:9876/test/2015.pdf

**Comment by Snuffleupagus** [comment] 2015-08-12 12:49
Closing as duplicate of issue #6264 (which was fixed by PR #6270).

**Closed by Snuffleupagus** 2015-08-12 12:49 UTC
Labels: 4-information-requested
