### ISSUE TITLE
Using "Print button" or "Ctrl+print", a blank page will be added in the pdf

### ISSUE THREAD

**Issue by Lamsiulok** [mozilla/pdf.js#8606] opened 2017-07-04 09:39 UTC
Let say the pdf only get 1 page, but if i use "Print button" or "Ctrl+print", 
a blank page will be added in the pdf, the total page of the pdf change to 2.

the problem will not happen in pdf download. 

Link to PDF file (or attach file here):

Configuration: 
- Web browser and its version: Chrome 59.0.3071.115 (64bit)
- Operating system and its version: download link only
- PDF.js version: PDF Viewer 1.6.293
- Is an extension: No

Steps to reproduce the problem:
1. Using "Print button" or "Ctrl+print"
2. the preview page will add a blank page at the end

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
http://imgur.com/xdv5j6f
should be 1 page and no blank page at the end

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by movedoa** [comment] 2017-07-06 14:12
Same problem here

**Comment by jscheller** [comment] 2017-07-14 13:20
Possibly the same problem as [https://github.com/mozilla/pdf.js/issues/8520]?

**Comment by sousa-cit** [comment] 2017-07-18 12:17
Same problem here using Chrome. Any news about the solution? Tks

**Comment by timvandermeij** [comment] 2021-03-14 14:37
Closing since this is a duplicate of #9295 and this one has no example PDF file.

**Closed by timvandermeij** 2021-03-14 14:37 UTC
Labels: 4-printing
