### ISSUE TITLE
Images cropped with hardware acceleration

### ISSUE THREAD

**Issue by j201** [mozilla/pdf.js#5786] opened 2015-03-04 17:30 UTC
Over the past few weeks, the tops of many images have been failing to display in PDF.js for me. I'm using PDF.js 1.0.1040 with Firefox 37.0 on Windows 7 64-bit. The same problem occurs when using https://mozilla.github.io/pdf.js/web/viewer.html when using Firefox but not when using Chrome. Disabling hardware acceleration on Firefox solves the problem.

Sample: http://www.cic.gc.ca/english/information/applications/guides/pdf/5445EB-e.pdf

It should render like this:
![pdfcorrect](https://cloud.githubusercontent.com/assets/4549370/6488870/5f734cc0-c268-11e4-99fc-466027a61414.PNG)

But instead I get this:
![pdfbug](https://cloud.githubusercontent.com/assets/4549370/6488888/812804dc-c268-11e4-9461-f0cd8d5a5196.PNG)

**Comment by timvandermeij** [comment] 2015-03-04 18:40
That's strange because I use the same configuration as you (including HWA on) and it renders perfectly fine for me. Perhaps it is a driver issue?

**Comment by yurydelendik** [comment] 2015-11-05 15:40
Duplicate of #5986? Can you paste Graphics section from the about:support?

**Comment by SamyCookie** [comment] 2015-11-05 23:24
I cannot reproduce this bug and neither my old bug report #5986 with an old 37 Firefox version.
But today my computer has newer graphic pilot, and runs on Windows 10 (64 bits) instead Win 7 before.

**Comment by timvandermeij** [comment] 2015-11-07 14:26
This appears to have been an issue in Firefox. Multiple other related issues have been closed after updating Firefox. As you mention also this bug is Firefox-specific as it did not happen in Chrome. Closing as resolved. If there are still issues, please post the information requested above to reopen.

**Closed by timvandermeij** 2015-11-07 14:26 UTC
Labels: 4-information-requested
