### ISSUE TITLE
[Bug]: First page of the PDF is displayed at the end in Mozilla browsers

### ISSUE THREAD

**Issue by harishfalco** [mozilla/pdf.js#19257] opened 2024-12-25 14:28 UTC
### Attach (recommended) or Link to PDF file

**Issue**: In Firefox browsers, the first page of the PDF is rendered as the last page. This issue is happening for some PDF files on Firefox browsers on Windows and Mac. On iPhone Firefox, it works fine.

**Code Used**
```
        const pdfjsLib = window.pdfjsLib;
        pdfjsLib.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${window.pdfjsLib.version}/pdf.worker.min.mjs`;


        const blobUrl = URL.createObjectURL(imgFile);

        const loadingTask = pdfjsLib.getDocument({
          url: blobUrl,
          disableAutoFetch: true, // Disable auto-fetching of additional data
          disableStream: true, // Disable streaming to prevent partial loading
          isEvalSupported: false, // Disable JavaScript execution
        });
        loadingTask.promise.then(function (pdf) {
          const numPages = pdf.numPages;
          for (let pageNum = 1; pageNum <= numPages; pageNum++) {
            pdf.getPage(pageNum).then(function (page) {
              const viewport = page.getViewport({ scale: 1.0 });
              const desiredWidth = fileContainer.offsetWidth;
              const scale = desiredWidth / viewport.width;
              const scaledViewport = page.getViewport({ scale: scale });
              const canvas = document.createElement('canvas');
              const context = canvas.getContext('2d');
              const outputScale = window.devicePixelRatio || 1;

              canvas.style.width = '100%';
              canvas.style.height = '210%';
              canvas.width = Math.floor(scaledViewport.width * outputScale);
              canvas.height = Math.floor(scaledViewport.height * outputScale);

              context.scale(outputScale, outputScale);

              const renderContext = {
                canvasContext: context,
                viewport: scaledViewport,
              };

              page.render(renderContext).promise.then(() => {
                pdfContainer.appendChild(canvas);
                if (pageNum === numPages) {
                  URL.revokeObjectURL(blobUrl);
                }
              }).catch(function (error) {
                sendErrorToSentry(error);
                showPDFError();
              })
            });
          }
        }).catch(function (error) {
          console.log('error in pdfjs', error);
          sendErrorToSentry(error);
          // showPDFError();
        });

```

**PDF.JS version used**
https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.9.155/pdf.min.mjs
https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.9.155/pdf.worker.min.mjs

**Here's the sample PDF**

[sample-pdf.pdf](https://github.com/user-attachments/files/18246326/sample-pdf.pdf)

### Web browser and its version

Firefox (on Mac) and Version : 133.0.3

### Operating system and its version

MacOS , version : 13.2.1 (22D68)

### PDF.js version

4.9.155

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the attached PDF file using PDF.js in Firefox browsers on Windows or Mac.
2. You can see that the first page is displayed at the end Firefox

### What is the expected behavior?

The first page should be displayed at the beginning

### What went wrong?

The first page should be displayed at the beginning

**Comment by Snuffleupagus** [comment] 2024-12-25 14:53
Duplicate of #19251

**Closed by Snuffleupagus** 2024-12-25 14:53 UTC

**Comment by harishfalco** [comment] 2024-12-25 14:58
@Snuffleupagus , May I know why both the issues are closed? In the new issue that was raised , I have attached a valid PDF file in which the issue is replicable
