### ISSUE TITLE
PDF.js does not acknowledge page labels

### ISSUE THREAD

**Issue by noahleigh** [mozilla/pdf.js#5776] opened 2015-03-03 03:39 UTC
For instance, if the PDF has its initial pages designated by roman numerals and the rest by decimal arabic numerals, PDF.js's page numbering ignores that and only displays the *page index*.

This would be very helpful to fix when navigating large documents such as textbooks, where the *page numbers* and the *page index* are offset.

**More Information:**

[PDF17: Specifying consistent page numbering for PDF documents](http://www.w3.org/TR/WCAG20-TECHS/PDF17.html)

[PDF 1.7 (ISO 32000-1) Section 12.4.2 (Page Labels)](http://www.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf)

**Comment by Snuffleupagus** [comment] 2015-03-03 09:34
Closing as duplicate of issue #3165.

**Closed by Snuffleupagus** 2015-03-03 09:34 UTC
