### ISSUE TITLE
PDF renders incorrectly using SVG 

### ISSUE THREAD

**Issue by akankshaBiz** [mozilla/pdf.js#10487] opened 2019-01-24 07:26 UTC
Attach (recommended) or Link to PDF file here:
[Artwork-management-Process-Report.pdf](https://github.com/mozilla/pdf.js/files/2791207/Artwork-management-Process-Report.pdf)

Configuration:

Web browser and its version: Chrome
Operating system and its version: OSX High Sierra
PDF.js version: latest
Is a browser extension: no

I am trying to render the pdf as SVG but it is not correctly rendered.

actual file:
<img width="1186" alt="screenshot 2019-01-24 at 12 48 33 pm" src="https://user-images.githubusercontent.com/40818745/51661414-d647c180-1fd6-11e9-970c-de8a7a16d1b5.png">

rendered file:
<img width="967" alt="screenshot 2019-01-24 at 12 48 49 pm" src="https://user-images.githubusercontent.com/40818745/51661436-e5c70a80-1fd6-11e9-8253-8feec28e4cc6.png">

Also, I want to use hand tool cursor so I tried using the secondary tool as the hand tool is there but it seems we can't use specific tools. Since I want hand tool only I am passing that button in the options but in the code, we need to pass buttons for all the tools, why is that?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by akankshaBiz** [comment] 2019-01-24 07:38
Below is the screenshot of the error I am getting when this PDF renders.

<img width="352" alt="screenshot 2019-01-24 at 1 07 55 pm" src="https://user-images.githubusercontent.com/40818745/51662239-2e7fc300-1fd9-11e9-9a95-cefdae195575.png">

**Comment by Snuffleupagus** [comment] 2019-01-24 08:53
You need to provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue. If you ignore the `Attach (recommended) or Link to PDF file here:` point in particular, the issue is incomplete and will be closed as such (since it's impossible for anyone to help without access to the PDF file).

**Comment by akankshaBiz** [comment] 2019-01-24 10:23
@Snuffleupagus, I have attached the PDF in the issue. Please check this issue.

**Comment by timvandermeij** [comment] 2019-01-24 22:15
This will most likely be fixed by the patterns/gradients patch in the queue.

**Comment by terurou** [comment] 2019-03-17 02:31
Fixed partially by #10646.
Must implement these operators:

> Warning: Unimplemented operator beginGroup
> Warning: Unimplemented operator endGroup
> Warning: Unimplemented graphic state BM
> Warning: Unimplemented graphic state SMask
> Warning: Unimplemented: TilingPattern

**Comment by retrazil** [comment] 2019-06-08 10:39
The pdf linked in the issue seems to render fine now.

**Closed** 2022-10-29 11:01 UTC
Labels: svg
