### ISSUE TITLE
Layered Adobe Illustrator file when exported as PDF and import into myApp then it mix the layers. Is there any way to select the layer from PDF before import using PDF.js library ?

### ISSUE THREAD

**Issue by developerashu** [mozilla/pdf.js#11148] opened 2019-09-16 09:43 UTC
Attach (recommended) or Link to PDF file here: 
[faulty.pdf](https://github.com/mozilla/pdf.js/files/3615648/faulty.pdf)

Configuration:
- Web browser and its version: Firefox 69.0 32 bit
- Operating system and its version: Windows 7 local nginx server
- PDF.js version: latest

Steps to reproduce the problem:
1.  Make a pdf from layered .AI file Or Use the above attached faulty.pdf file to see the issue.
2. Import that PDF at http://usefulangle.com/post/20/pdfjs-tutorial-1-preview-pdf-during-upload-wih-next-prev-buttons 

What is the expected behavior? (added screenshot)
User should be able to select between layers or select TOP layer by default like this : 
![image](https://user-images.githubusercontent.com/31619923/64948788-710e4c80-d895-11e9-93b5-caa438a7f9d7.png)

What went wrong? (added screenshot)
Layers got mixed 
![image](https://user-images.githubusercontent.com/31619923/64948698-37d5dc80-d895-11e9-91b8-ca5b598949f0.png)

**Comment by developerashu** [comment] 2019-09-16 09:54
@Snuffleupagus : Please check the updated comment now. It did not update when you downvoted the comment.

**Comment by Snuffleupagus** [comment] 2019-09-16 10:00
Duplicate of #269.

**Closed** 2019-09-16 21:46 UTC
