### ISSUE TITLE
"arr is undefined" error and refresh the page to view a PDF

### ISSUE THREAD

**Issue by escuriola** [mozilla/pdf.js#9216] opened 2017-11-29 17:02 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox  56.0.2 (64 bit); 56.0.1 (64 bit).
- Operating system and its version: Windows
- PDF.js version:1.5.188
- Is a browser extension: No

Steps to reproduce the problem:
1. Just navigate to page where pdf is

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/6751237/33387947-de819892-d52e-11e7-851f-85557081afd4.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/6751237/33387912-cb225110-d52e-11e7-8e8e-5fe3134371e5.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

With the newer versions of Firefox, PDF are not opening first time we visit it, but if we refresh (sometimes) opens. The if refresh the page again (sometimes) goes wrong agian.

We suspect of cache and tried to deactivate the cache and reduce it to 0 MB in the firefox options, but the same occurs.

**Comment by Snuffleupagus** [comment] 2017-11-29 19:36
> PDF.js version:1.5.188

That version is no longer supported, please make sure that you're using the *latest* version; see https://github.com/mozilla/pdf.js/releases.

> Web browser and its version: Firefox 56.0.2 (64 bit); 56.0.1 (64 bit).

Firefox 57 was release two weeks ago, so those versions are probably no longer supported.

---

Based on the (limited) information provided, it appears that this is an issue with a custom deployment of PDF.js. If so, then as asked for in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) you need to provide access to a *working* example in order for the issue to be valid.

> With the newer versions of Firefox, PDF are not opening first time we visit it, but if we refresh (sometimes) opens. The if refresh the page again (sometimes) goes wrong agian.

Furthermore, please make sure that you provide *clear* STR (steps to reproduce), since the information provided thus far unfortunately isn't actionable.

Closing as incomplete.

**Closed by Snuffleupagus** 2017-11-29 19:36 UTC
