### ISSUE TITLE
Misprinting issue

### ISSUE THREAD

**Issue by ZubairAS** [mozilla/pdf.js#14486] opened 2022-01-24 13:31 UTC
[pdf1.pdf](https://github.com/mozilla/pdf.js/files/7925865/pdf1.pdf)

Configuration:

Web browser and its version: Version 97.0.4692.71 (Official Build) (64-bit)

Operating system and its version: - Windows 10

PDF.js version: v2.12.313

Is a browser extension: No

Steps to reproduce the problem:
I am working on PDF.js and trying to render a pdf on a webpage. I am facing misprinting issue when displaying pdf. You can see that some text is not printed properly
![image](https://user-images.githubusercontent.com/98324430/150791492-c1594e3b-6914-4b77-8a64-3a819d6d57cb.png)

However, when I see the pdf in Acrobat, it is displayed perfectly.
![image](https://user-images.githubusercontent.com/98324430/150791585-0b92eaa4-6aee-41d9-8a54-645f0bad632e.png)

Note* - The Pdf contains only text, no images.

I'm using very basic code to display the pdf file

`var url = './highlighter_updated.pdf';

// Loaded via <script> tag, create shortcut to access PDF.js exports.
var pdfjsLib = window['pdfjs-dist/build/pdf'];

// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';

// Asynchronous download of PDF
var loadingTask = pdfjsLib.getDocument(url);
loadingTask.promise.then(function(pdf) {
console.log('PDF loaded');

// Fetch the first page
var pageNumber = 1;
pdf.getPage(pageNumber).then(function(page) {
console.log('Page loaded');

var scale = 1.0;
var viewport = page.getViewport({scale});

// Prepare canvas using PDF page dimensions
var canvas = document.getElementById('the-canvas');
var context = canvas.getContext('2d');

canvas.height = viewport.height;
canvas.width = viewport.width;

// Render PDF page into canvas context
var renderContext = {
  canvasContext: context,
  viewport: viewport
};
var renderTask = page.render(renderContext);
renderTask.promise.then(function () {
  console.log('Page rendered');
});
});
}, function (reason) {
// PDF loading error
console.error(reason);
});`
`

Can anyone suggest what is wrong with this.

Thanks in advance.

**Comment by Snuffleupagus** [comment] 2022-01-24 13:33
Duplicate of #14485

(Please don't knowingly open a duplicate issue, when the original one is missing required information.)

**Closed by Snuffleupagus** 2022-01-24 13:33 UTC

**Comment by ZubairAS** [comment] 2022-01-24 13:41
> Duplicate of #14485
> 
> (Please don't knowingly open a duplicate issue, when the original one is missing required information.)

Should I open a new ticket as you have closed both of the the tickets and mark them as closed.

**Comment by Snuffleupagus** [comment] 2022-01-24 13:46
> Should I open a new ticket as you have closed both of the the tickets and mark them as closed.

No, since neither of them are actionable!

Your PDF document opens and renders just fine with https://github.com/mozilla/pdf.js#online-demo which suggests a bug in your code (or possibly in the browser, which we cannot fix). Hence I'd like to point to https://github.com/mozilla/pdf.js/issues/14485#issuecomment-1020089392 and again mention https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
