### ISSUE TITLE
Examples page renders blurry text

### ISSUE THREAD

**Issue by cuong-nguyen** [mozilla/pdf.js#10679] opened 2019-03-26 09:22 UTC
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/examples/

Configuration:
- Web browser and its version: Chrome 73, Firefox 66
- Operating system and its version: MacOS Mojave
- PDF.js version: 2.2.93
- Is a browser extension: no

Steps to reproduce the problem:
1. https://mozilla.github.io/pdf.js/examples/

What is the expected behavior? (add screenshot)
Text rendering should not be blurry

What went wrong? (add screenshot)
Text is blurry
<img width="643" alt="Screenshot 2019-03-26 at 5 21 37 PM" src="https://user-images.githubusercontent.com/5061591/54985399-b25f2700-4feb-11e9-8020-0971296ffc06.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/examples/

**Comment by cuong-nguyen** [comment] 2019-03-26 09:23
I followed the code sample and point to another PDF file, it's blurry too.

**Comment by Snuffleupagus** [comment] 2019-03-26 09:58
Duplicate of #10509.

**Closed** 2019-03-26 21:33 UTC

**Comment by snehiljain34** [comment] 2021-06-24 10:57
This code will surely help you guys for rendering crisp pdf according to the Div size given (responsive` pdf rendering)`var loadingTask = pdfjsLib.getDocument("your_pdfurl");
                loadingTask.promise.then(function(pdf) {
                    console.log('PDF loaded');

                    // Fetch the first page
                    var pageNumber = 1;
                    pdf.getPage(pageNumber).then(function(page) {
                        console.log('Page loaded');


                       

                        var container = document.getElementById("container") //your body container
                        var wrapper = document.getElementById("wrapper"); //your div where pdf is rendering
                        var canvas = document.getElementById('pdf');
                        var context = canvas.getContext('2d');
                        const pageWidthScale = container.clientWidth / page.view[2];
                        const pageHeightScale = container.clientHeight / page.view[3];

                        var scales = { 1: 3.2, 2: 4 },
                        defaultScale = 4,
                        scale = scales[window.devicePixelRatio] || defaultScale;

                        var viewport = page.getViewport({ scale: scale });
                        canvas.height = viewport.height;
                        canvas.width = viewport.width;

                        var displayWidth =  Math.min(pageWidthScale, pageHeightScale);;
                        canvas.style.width = `${(viewport.width * displayWidth) / scale}px`;
                        canvas.style.height = `${(viewport.height * displayWidth) / scale}px`;


                        // Render PDF page into canvas context
                        var renderContext = {
                            canvasContext: context,
                            viewport: viewport
                        };
                        var renderTask = page.render(renderContext);
                        renderTask.promise.then(function() {
                            console.log('Page rendered');
                        });
                    });
                }, function(reason) {
                    // PDF loading error
                    console.error(reason);
                });`
