### ISSUE TITLE
Dotted areas rendered as black.

### ISSUE THREAD

**Issue by sorenfalch** [mozilla/pdf.js#8741] opened 2017-08-03 07:16 UTC
Link to PDF file (or attach file here):
http://soap.plansystem.dk/pdfarchive/20_1057347_APPROVED_1193694109382.pdf

Configuration:
- Web browser and its version:  
        FireFox 54.0.1 (64-bit) [Does not work]
        Chrome Version 59.0.3071.115 (Official Build) (64-bit) [Works fine]
- Operating system and its version:
        macOS Sierra 10.12.6 (16G29) 
        (Problem is also reproducible on Windows computers)
- PDF.js version:
        1.8.593
- Is an extension:
We are seeing this problem when opening the document directly in FireFox 54 as well as on Chrome when using PDF.JS (both version 1.8.254 and 1.8.593) in our Angular 2 project.
Opening the document directly in Chrome, using the build in viewer, renderes the PDF correctly.

Steps to reproduce the problem:
1. Open the pdf referenced above in FireFox, use internal viewer (PDF.JS)
2. Zoom in on the grey areas show that they are in fact dotted.

What is the expected behavior? (add screenshot)
Images from Chrome 
![image](https://user-images.githubusercontent.com/2655958/28909734-e6190a7a-7829-11e7-9365-595699507d89.png)
![image](https://user-images.githubusercontent.com/2655958/28910185-f694c8b0-782b-11e7-8ae3-7b4e1063d8d2.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/2655958/28909569-48827e22-7829-11e7-92a8-547c7898521e.png)
![image](https://user-images.githubusercontent.com/2655958/28910191-095ffc62-782c-11e7-8ed6-f546b2ad0484.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by janpe2** [comment] 2017-08-22 15:32
This is a duplicate of #3226.

The problem is caused by the uncolored tiling pattern P1 that contains an image mask. It is used on the page like this:

```
  /Cs9 cs
  1 1 1 /P1 scn
  ...create and fill path...
```
  
The color components `1 1 1` should make the pattern white (in color space CalRGB) but PDF.js renders it as black. There is a bug that causes the default color black to be always used in image masks that are inside an uncolored pattern.

I'll create a pull request to fix this.

**Closed** 2017-09-12 12:27 UTC
Labels: 2-image-quality, 4-tiling-type
