### ISSUE TITLE
You cannot print vertically and horizontally in the same file.

### ISSUE THREAD

**Issue by beijingalex** [mozilla/pdf.js#11028] opened 2019-07-31 13:09 UTC
Attach (recommended) or Link to PDF file here:

Configuration:

Web browser and its version: chrome
Operating system and its version: ;win10
PDF.js version: 2.1.266
Is a browser extension:no
Steps to reproduce the problem:

You cannot print vertically and horizontally in the same file.

What is the expected behavior? (add screenshot)
[横向 纵向 .pdf](https://github.com/mozilla/pdf.js/files/3452014/default.pdf)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-07-31 13:30
Duplicate of #9297.

**Closed** 2019-07-31 20:51 UTC
