### ISSUE TITLE
Using bookmarklet to change filter also forces rezoom to 75%

### ISSUE THREAD

**Issue by ImperialSquid** [mozilla/pdf.js#16613] opened 2023-06-27 14:57 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox v114.0.1
- Operating system and its version: Windows 10 Enterprise (21H2)
- PDF.js version: Whatever is in FF 114
- Is a browser extension: Unknown

Steps to reproduce the problem:
1. Have a bookmarklet that affects the filter on pdfs, eg `javascript:(function(){viewer.style = 'filter: invert(1)'})()`
2. Open a pdf and use any zoom level other than 75%
3. Click bookmarklet and see that pdf zoom changes (if zoom was >75% it will be cropped down, if below there will be a blank space)

What is the expected behavior? 

Zoom does not adjust when a filter is applied (this used to be the case a few versions ago but I don't remember when it first started happening)

What went wrong?

Appling the filter resets the zoom level, if the previous zoom was >75% the pdf is cropped to size, if <75% there is a blank space, see gif for demo:

![8YSK475](https://github.com/mozilla/pdf.js/assets/44560551/3885d73f-482c-4464-8609-b1e2d3a4007d)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by ImperialSquid** [comment] 2023-06-27 14:58
This might be specific to firefox or more general to this repo, I wasn't sure exactly where to put it

**Comment by ronandalton** [comment] 2023-07-19 08:59
The issue is that `viewer.style` usually has the value of `--scale-factor: <scaling_factor>;` which is changed depending on how large the document should be on the screen. When the Javascript bookmarklet is executed, this scaling factor information is lost because it is overwritten by `filter: invert(1)`. The custom styling is applied but the zoom factor information is lost.

In order to keep the current scaling factor of the document, change your bookmarklet from `javascript:(function(){viewer.style = 'filter: invert(1)'})()` to `javascript:(function(){viewer.style.filter = 'invert(1)'})()`. This should then produce the desired behavior.

I'm guessing at some point in the past, `viewer.style` didn't contain the zoom factor information, so it wouldn't get messed up when this bookmarklet was run.

**Comment by Snuffleupagus** [comment] 2023-07-19 09:09
Closing as WFM, since https://github.com/mozilla/pdf.js/issues/16613#issuecomment-1641701910 provides both an explanation and solution to this issue; thank you!

**Closed by Snuffleupagus** 2023-07-19 09:09 UTC
Labels: viewer, other

**Comment by darsor** [comment] 2024-04-03 16:09
I'm seeing a related issue. When using either version of the bookmarklet provided, zooming the document also scrolls upwards. When the bookmarklet is not applied, zooming works normally by zooming into he current location.

I can open a new issue if needed, but this might be a quick fix similar to the one above.
