### ISSUE TITLE
Images are not rendered in PDF document

### ISSUE THREAD

**Issue by JasnaPaka** [mozilla/pdf.js#6028] opened 2015-05-18 08:55 UTC
PDF Document:
http://jasnapaka.com/bugs/Cach_cykloobousmerky.pdf

Firefox 40a1 (latest nightly).
PDF f81428bdbbc6671d523cdcd97bb700fa [1.4 GPL Ghostscript 8.63 / PDFCreator Version 0.9.6] (PDF.js: 1.1.114) viewer.js:6397:1
Warning: Error during JPEG image loading pdf.js:235:5
Warning: Dependent image isn't ready yet pdf.js:235:5
Warning: Error during JPEG image loading pdf.js:235:5
Warning: Dependent image isn't ready yet

Adobe Reader XI
- images are showed

**Comment by Snuffleupagus** [comment] 2015-05-18 08:57
Closing as duplicate of issue #6017.

**Closed by Snuffleupagus** 2015-05-18 08:57 UTC
