### ISSUE TITLE
Acroforms not rendered properly (Misplaced elements) 

### ISSUE THREAD

**Issue by smit-modi** [mozilla/pdf.js#10549] opened 2019-02-13 18:29 UTC
I tired the Acroform example at https://github.com/mozilla/pdf.js/blob/master/examples/acroform 
It is working perfectly with the given pdf.
But when I try to use the same code in my web app, the form input boxes and other elements are misplaced.

Attach (recommended) or Link to PDF file here: http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf

Configuration:
- Web browser and its version: Chrome; Version 72.0.3626.96 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Pro
- PDF.js version:  v2.1.245
- Is a browser extension: No

Steps to reproduce the problem:
I have used the files from web and build directories from `pdf.js\node_modules\pdfjs-dist`\ and put in my web-app direcotry as below:
```
    <script type="text/javascript" src="js/Lib/pdf.js"></script>
    <script type="text/javascript" src="js/Lib/pdf.worker.js"></script>
    <script type="text/javascript" src="js/Lib/pdf_viewer.js"></script>
    <link rel="stylesheet" href="js/Lib/pdf_viewer.css">
```
I have included the images folder from `pdfjs-dist\web` also in my `js/Lib` folder

The JavaScript code is as below: 
```
function renderPage(page_number_array)
{
   pageRendering = true;
    var DEFAULT_SCALE = 1.0;
    var container = document.getElementById('viewer_container');
    var t = page_number_array.shift();

    pdfDoc.getPage(t).then(function (page)
    {
        
        var pdfPageView = new pdfjsViewer.PDFPageView({
            container: container,
            id: t,
            scale: DEFAULT_SCALE,
            defaultViewport: page.getViewport({ scale: DEFAULT_SCALE, }),
            annotationLayerFactory:
                new pdfjsViewer.DefaultAnnotationLayerFactory(),
            renderInteractiveForms: true,
        });

        // Associate the actual page with the view and draw it.
        pdfPageView.setPdfPage(page);
        pdfPageView.draw();
 });
}
```
What is the expected behavior? 
![image](https://user-images.githubusercontent.com/16932686/52732526-11119980-2f86-11e9-85f3-4ff2799e9333.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/16932686/52733415-48814580-2f88-11e9-9cad-51713ce82a9a.png)

On the other note, I am new at JavaScript. I want to create a pdf web viewer in my web-app which supports Acroforms with Previous and Next button Navigation. I saw the PrevNext Example at  https://github.com/mozilla/pdf.js/blob/master/examples/learning/prevnext.html
But it is not meant for Acroform.

If you give me some guidance on how to create it,  I'd really appreciate your help.

**Comment by Snuffleupagus** [comment] 2019-02-13 18:42
Duplicate of #10333.

**Closed** 2019-02-13 21:40 UTC
