### ISSUE TITLE
Annotation pop render wrong position 

### ISSUE THREAD

**Issue by a7vickey** [mozilla/pdf.js#11702] opened 2020-03-16 10:01 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:74.0 (32-bit)
- Operating system and its version: Windows 8.1
- PDF.js version:2.0
- Is a browser extension:

Steps to reproduce the problem:
1.  Page no 6 strikeoutAnnotation text pop shows top of page not showing current mouse position. 
2. we cant able to access blue color strikeoutAnnotation and caretAnnotation. 

What is the expected behavior?  Page 5 preferably show annotation on current position. 

What went wrong? 
[m01TheAuditingAndAssuranceFramework_ProofPDF.pdf](https://github.com/mozilla/pdf.js/files/4337435/m01TheAuditingAndAssuranceFramework_ProofPDF.pdf)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2020-03-16 10:48
Duplicate of #11286

**Closed** 2020-03-16 20:43 UTC

**Comment by a7vickey** [comment] 2020-03-17 05:31
How can i resolve this problem. without solution bug is closed. Your people are dont know how to fix this issue?

**Comment by Snuffleupagus** [comment] 2020-03-17 09:17
> How can i resolve this problem. without solution bug is closed. Your people are dont know how to fix this issue?

It's commonplace in all (open source) bug trackers to close duplicates in order to keep the number of open issues more manageable and to ensure that relevant discussion occurs in one place; however this does *not* required that original issue is resolved.

Furthermore you need to remember that this is an *open source* bug tracker, with most people contributing in their spare time, and not *not* paid support.
Finally, please keep in mind that open source contributors are usually helping out if/when they can, however on one is *forced* to spend their spare time doing so and acting as if you're entitled to help/support is usually a good way ensure that people don't want to help you.
