### ISSUE TITLE
Zoom limit on iOS

### ISSUE THREAD

**Issue by gongevangen** [mozilla/pdf.js#11245] opened 2019-10-15 14:20 UTC
Attach (recommended) or Link to PDF file here: 
[zoom test.pdf](https://github.com/mozilla/pdf.js/files/3729738/zoom.test.pdf)

Configuration:
- Web browser and its version: Safari 12
- Operating system and its version: ipadOS 13.1.2
- PDF.js version: 2.1.266
- Is a browser extension: no

Steps to reproduce the problem:
1.  Open attached file in Safari on an iPad running ipadOS 13 in the pdfjs demo viewer https://mozilla.github.io/pdf.js/web/viewer.html
2. click zoom + button to zoom into 220%.
3. The file is no longer displayed instead all white is shown. If a Safari inspector is attached it will write "Canvas area exceeds the maximum limit (width * height > 16777216)." in the console.

What is the expected behavior? (add screenshot) : to be able to zoom more than 200%

What went wrong? (add screenshot): white is shown instead of the content of the file.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

It seems that the zoom limit is different for different files. Is there a way to calculate what it is at runtime each file so I avoid showing white instead of the file without having to set a very low zoom limit on iOS devices?

**Comment by Snuffleupagus** [comment] 2019-10-15 14:27
> The file is no longer displayed instead all white is shown. If a Safari inspector is attached it will write "Canvas area exceeds the maximum limit (width * height > 16777216)." in the console.

That's quite strange, since the maximum canvas size *should* be limited to a much smaller value on mobile platforms; see https://github.com/mozilla/pdf.js/blob/16ae7c6960c1296370c1600312f283a68e82b137/web/viewer_compatibility.js#L23-L29

**Comment by gongevangen** [comment] 2019-10-15 14:38
Then I guess I know what the problem is: Apple have made Safari on ipadOS 13 "a desktop class browser" which means that it reports EXACTLY the same navigator.userAgent string as Safari on MacOS reports => isIOS() returns false. According to https://stackoverflow.com/questions/57765958/how-to-detect-ipad-and-ipad-os-version-in-ios-13-and-up the only way currently to distinguish between Safari 13 on Mac and ipadOS is to test for navigator.maxTouchPoints > 1.

**Comment by Snuffleupagus** [comment] 2019-10-15 15:24
> Apple have made Safari on ipadOS 13 "a desktop class browser" which means that it reports EXACTLY the same navigator.userAgent string as Safari on MacOS reports => isIOS() returns false.

That seems kind of, for lack of a better word, stupid to me; but obviously that's part of the problem is not something we can fix...

Anyway, can you please check if preview build in PR #11246 is enough to work-around this issue?

**Comment by gongevangen** [comment] 2019-10-15 16:22
I can only agree!

**Comment by gongevangen** [comment] 2019-10-15 16:25
I can only agree.

The build at http://54.67.70.0:8877/65321f96da43bee/web/viewer.html works on my ipad pro running ipadOS 13.1.2. 

When will this fix be available in a build of the npm library?

**Comment by Snuffleupagus** [comment] 2019-10-15 19:00
> When will this fix be available in a build of the npm library?

Considering that it's neither approved nor landed yet, that's probably anyone's guess at this point :-)
Furthermore, this really doesn't seem anywhere near serious enough to warrant a new release right away.

Given that the default viewer (purposely) isn't shipping via npm, I'd assume that you're using the viewer components in some way. In that case, note that the [`PDFViewer` constructor](https://github.com/mozilla/pdf.js/blob/16ae7c6960c1296370c1600312f283a68e82b137/web/base_viewer.js#L121-L124) already accepts a custom `maxCanvasPixels` value; see https://github.com/mozilla/pdf.js/blob/16ae7c6960c1296370c1600312f283a68e82b137/web/base_viewer.js#L33-L66 hence you can already "fix" this yourself, in your implementation, until such a time that the PR lands!

**Closed** 2019-10-15 22:34 UTC
Labels: 1-viewer, 4-os-ios

**Comment by timvandermeij** [comment] 2019-10-15 22:36
The fix is now merged and will be in the next release, but it's not yet known when that is going to be made. For now it's best to set `maxCanvasPixels` yourself like in the comment above.

**Comment by seopei** [comment] 2020-06-28 21:50
I am running into the same issue. I tried to change `maxCanvasPixels` to 5242880. If I change it to a very low number eg 1000 it does work, but but obviously you can not read anything :) I am using `ng2-pdf-viewer` (https://github.com/VadimDez/ng2-pdf-viewer/issues/492)
