### ISSUE TITLE
[Bug]: IOS phone preview PDF zoom abnormal 

### ISSUE THREAD

**Issue by niubiqianshui** [mozilla/pdf.js#18723] opened 2024-09-10 03:36 UTC
### Attach (recommended) or Link to PDF file

When previewing PDFs on an iPhone, there may be a page cracking effect when zooming in 

![image](https://github.com/user-attachments/assets/dc8dcbf5-e259-4483-b04f-ef4f8888053a)

### Web browser and its version

latest ios

### Operating system and its version

latest ios

### PDF.js version

v4.6.82

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

open pdf in ios phone browser

### What is the expected behavior?

Can zoom in and out normally

### What went wrong?

Abnormal when zooming in quickly

**Comment by Snuffleupagus** [comment] 2024-09-10 07:46
Duplicate of #16155

**Closed by Snuffleupagus** 2024-09-10 07:46 UTC
