### ISSUE TITLE
How to zoom different pdf page sizes ?

### ISSUE THREAD

**Issue by SOftEngrAtta** [mozilla/pdf.js#8751] opened 2017-08-05 10:54 UTC
I am unable to accomplish the following:
Zoom is set to "Page-fit" and I have a PDF with different Actual Page Sizes. 
When I scroll to different pages, the Zoom level does not automatically adjust on the screen. 
I want all page sizes to be set to "Page-fit" zoom. This is how it works in other viewers (Adobe Acrobat, Google PDF viewer, etc...)
Can someone please help me? Thank you.

pdf file : [clean_code.pdf](https://github.com/mozilla/pdf.js/files/1202303/clean_code.pdf)

**Comment by AndrewRayCode** [comment] 2017-09-28 19:33
Other viewers do not do this, including google pdf viewer.

**Comment by Snuffleupagus** [comment] 2021-11-07 17:49
Duplicate of #5628

**Closed by Snuffleupagus** 2021-11-07 17:49 UTC
Labels: 1-other
