### ISSUE TITLE
Pdf doesnt open in IOS

### ISSUE THREAD

**Issue by charith93** [mozilla/pdf.js#7709] opened 2016-10-10 11:38 UTC
Pdf viewer works perfectly in android. But, in IOS doesnt go beyond the promise. No error or exception is displayed.

MY CODE:
var loadingTask = window['PDFJS'].getDocument(***some url***);
        var self = this;

//does not enter the promise, but when i do a console log for loadingTask i have an object of //promise

        loadingTask.promise.then(function (pdfDocument) {
            self.pdfDocument = pdfDocument;
            self.pdfViewer.setDocument(pdfDocument);
            self.pdfHistory.initialize(pdfDocument.fingerprint);

        }, function (exception) {
            console.log("exception", 
            }
        }).catch(function(error){
            console.log("error", error);
        })

**Comment by pjohn** [comment] 2016-10-10 12:32
We're experiencing this issue as well.  We have been able to notice that the issue is isolated to devices running iOS10.  PDFs load as expected on devices running 9.3 or olrder.

**Comment by yurydelendik** [comment] 2016-10-10 12:50
I wonder if it's related to https://github.com/mozilla/pdf.js/issues/5405#issuecomment-252546051 . @pjohn can you check if setting PDFJS.disableRange=true helps (you may clear the Safari's cache).

**Comment by prakash-mishra-josh** [comment] 2016-10-10 13:09
@yurydelendik Range requests are disabled for Safari [#7528](https://github.com/mozilla/pdf.js/issues/7528)

**Comment by yurydelendik** [comment] 2016-10-10 22:48
@pjohn I don't think this bug about iOS10. Can you open different issue for iOS with steps to reproduces. Thank you.

The original issue does not contain enough info to reproduce the issue. Closing as incomplete.

**Closed by yurydelendik** 2016-10-10 22:48 UTC
Labels: 4-os-ios

**Comment by fareshan** [comment] 2016-11-04 19:36
I have the same problem.
Did you find how to fix it ?

**Comment by yurydelendik** [comment] 2016-11-04 19:41
> Did you find how to fix it ?

@fareshan yes, just to add a proper check at compatibility.js at https://github.com/mozilla/pdf.js/blob/master/web/compatibility.js#L460 , but I cannot verify or test it.

**Comment by fareshan** [comment] 2016-11-04 20:42
@yurydelendik thanks, that is the problem
http://stackoverflow.com/questions/39120772/how-to-detect-safari-10-browser-in-javascript
