### ISSUE TITLE
Support editing/deleting already existing highlight-annotations

### ISSUE THREAD

**Issue by alvaropeirob** [mozilla/pdf.js#18407] opened 2024-07-08 16:03 UTC
### Attach (recommended) or Link to PDF file

[dummy_annotated.pdf](https://github.com/user-attachments/files/16131481/dummy_annotated.pdf)

### Web browser and its version

Firefox 127.0.2

### Operating system and its version

Ubuntu 22.04.4 LTS (Jammy Jellyfish)

### PDF.js version

4.4.168

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Add a highlight annotation
2. Save the pdf under a different name
3. Reload the saved pdf
4. The added highlight-annotation is "burnt in" and can't be edited nor deleted anymore

### What is the expected behavior?

I would have expected to be able to edit/remove the added annotation after some events (e.g. double-click on the highlight annotation)

### What went wrong?

The annotations are "burnt in" after saving. A double-click event could enable the "Edit Toolbar" to do the same actions as a new highlight annotation (change color, remove) so the document could be saved with said changes.

![edit_toolbar](https://github.com/mozilla/pdf.js/assets/61414054/b18cdc3b-ee66-40e7-b244-0dd08e177220)

### Additional context

_Disclaimer_: This is more or less a clone of [#16883](https://github.com/mozilla/pdf.js/issues/16883) and [#15403](https://github.com/mozilla/pdf.js/issues/15403) but applied to the highlight annotation

**Comment by Snuffleupagus** [comment] 2024-07-08 16:06
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1883884

**Closed by Snuffleupagus** 2024-07-08 16:06 UTC
