### ISSUE TITLE
Form Field doesn't have the correct font size

### ISSUE THREAD

**Issue by bksantiago** [mozilla/pdf.js#11199] opened 2019-10-03 18:05 UTC
Attach (recommended) or Link to PDF file here:
https://drive.google.com/open?id=1UjLxnFw2g3gn3tvNLRYLdmG6mFdFKCcr

Configuration:
- Web browser and its version: Chrome 77.0.3865.90
- Operating system and its version: Mac mojave 10.14.6
- PDF.js version: 2.3.194
- Is a browser extension: Nope

Steps to reproduce the problem:
1. Make sure to set `renderInteractiveForms` to `true`
2. The read-only form field(Sample title) doesn't honor it's proper font-size

What is the expected behavior?
<img width="862" alt="write" src="https://user-images.githubusercontent.com/4616548/66152094-4a009a80-e64b-11e9-81dc-178068055efa.png">

What went wrong?
<img width="842" alt="wrong" src="https://user-images.githubusercontent.com/4616548/66152100-4d942180-e64b-11e9-91a8-ad9caf451f98.png">

**Comment by timvandermeij** [comment] 2019-10-03 20:35
Most likely this is a duplicate of #7367, but I'm not entirely sure.

**Comment by bksantiago** [comment] 2019-10-07 16:01
> Most likely this is a duplicate of #7367, but I'm not entirely sure.

Not entirely sure either since based from my observation and the PDFs I've used, text fields has a default smaller font sizes regardless of it's true font-size.

**Closed** 2021-01-23 15:08 UTC
Labels: 4-annotations, 4-font-conversion, 4-form-acroform
