### ISSUE TITLE
disableFontFace is not working properly as in older Versions

### ISSUE THREAD

**Issue by deepak-ghimire** [mozilla/pdf.js#11865] opened 2020-05-01 16:14 UTC
Hi Team,
We develop a [3D flipbook](https://dearflip.com/realistic-3d-flipbook-wordpress-plugin/) using PDF.js. Recently while integrating a newer version of PDF.js we encountered fontface issues, which would normally happen when using a IOS device. `disableFontFace `is auto set to `true` in those IOS devices. Unfortunately, it's working properly as it used to. Are we missing something extra to implement?

Live Scenario:

**Attach (recommended) or Link to PDF file here:**
[The-Angels-Magazine-April-2020.pdf](https://github.com/mozilla/pdf.js/files/4565063/The-Angels-Magazine-April-2020.pdf)

**Configuration:**
- Web browser and its version: Any browser - recommended: Chrome Version 81.0.4044.122 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: 2.3.200
- Is a browser extension: no

**Steps to reproduce the problem:**
1. Goto Link: [https://dearflip.com/pdf-viewer/](https://dearflip.com/pdf-viewer/) 
2. Check "Disable FontFace(IOS issues)" checkbox ( see screenshot)
3. Open the attached PDF (The-Angels-Magazine-April-2020.pdf)

![PDF js fontface - old vs new - settings](https://user-images.githubusercontent.com/11489308/80819664-20195180-8bf5-11ea-8036-df0d072def92.JPG)

For custom environment: set `disabledFontFace =  true` and use the attached PDF

**What is the expected behavior?**
The text should be displayed as it was displayed using older versions. (right side of the screenshot below)

**What went wrong? (add screenshot)**
The text is not displayed in new versions of PDF.js. (Left side of the below screenshot)
![PDF js fontface - old vs new](https://user-images.githubusercontent.com/11489308/80819670-260f3280-8bf5-11ea-9486-337f7266b2f2.JPG)

**Link to a viewer** (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
**New version of PDF.js with fontface issues:**
[https://dearflip.com/pdf-viewer/](https://dearflip.com/pdf-viewer/)

**Old Version of PDF.js that doesn't have the issue:**
[https://dearflip.com/examples/jquery/demo-open-file.html](https://dearflip.com/examples/jquery/demo-open-file.html)

Best,
DearFlip Team

**Comment by Snuffleupagus** [comment] 2020-05-01 16:39
Duplicate of #4244

**Closed** 2020-05-01 21:50 UTC
