### ISSUE TITLE
Has anyone had issues with colour profiles being stripped out?

### ISSUE THREAD

**Issue by jamiegalbreath** [mozilla/pdf.js#12008] opened 2020-06-17 18:13 UTC
Attach (recommended) or Link to PDF file here:
<img width="1174" alt="Screenshot 2020-06-17 at 19 11 30" src="https://user-images.githubusercontent.com/5307969/84933872-6efc4700-b0ce-11ea-8de7-3d603c24e6df.png">
<img width="1219" alt="Screenshot 2020-06-17 at 19 11 21" src="https://user-images.githubusercontent.com/5307969/84933882-728fce00-b0ce-11ea-83c8-bfa2a7bacb5d.png">

Happy to send you the PDF just not publicly. 

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Mac osx
- PDF.js version: latest
- Is a browser extension:no

Steps to reproduce the problem:
1. Followed Guide

What is the expected behavior? (add screenshot)
Colours are not correct

What went wrong? (add screenshot)
Colour profile is being stripped out.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2020-06-17 18:20
Duplicate of #2856

(Which is a best guess, given that lack of a publicly available test-case.)

**Closed** 2020-06-17 21:20 UTC
