### ISSUE TITLE
Extra blank page printed in Chrome for single paged document

### ISSUE THREAD

**Issue by jisasebastine** [mozilla/pdf.js#10341] opened 2018-12-07 19:45 UTC
Attach (recommended) or Link to PDF file here:
[SinglePagedPDF.pdf](https://github.com/mozilla/pdf.js/files/2658546/SinglePagedPDF.pdf)

Configuration:
- Web browser and its version: Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Pro Version 1803
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1. Try to print a single paged document(see attached file) in the demo link https://mozilla.github.io/pdf.js/web/viewer.html
2. Check to see if it has an extra blank page appended to the end

What is the expected behavior? (add screenshot)
The document is a single paged document. When I print it, it should have only 1 page.

What went wrong? (add screenshot)
Adds an extra blank page.
![image](https://user-images.githubusercontent.com/1188529/49668897-2c5fa600-fa25-11e8-86be-3eb128d4f2b5.png)

When I tested, this behavior is only for single paged documents.

**Comment by timvandermeij** [comment] 2018-12-07 22:09
Closing since this is a duplicate of e.g., #9295.

**Closed by timvandermeij** 2018-12-07 22:09 UTC
