### ISSUE TITLE
μ (mu) gets rendered as α (alpha)

### ISSUE THREAD

**Issue by vale981** [mozilla/pdf.js#11399] opened 2019-12-09 20:02 UTC
In 
https://tu-dresden.de/mn/physik/iktp/ressourcen/dateien/studium/praktikum/LM_Anleitung_komplett.pdf?lang=en
μ (mu) gets rendered as α (alpha).
This doesn't usually happen so I figure that this is a font issue, maybe even specific to my machine.

Configuration:
- Web browser and its version: Firefox 71
- Operating system and its version: Arch Linux, Kernel Linux 5.1.12
- PDF.js version:
```js
var pdfjsVersion = '2.4.43';
var pdfjsBuild = '16ae7c69';
```
- Is a browser extension: no

Steps to reproduce the problem:
 - Just open the abovementioned pdf.

What is the expected behavior?
![image](https://user-images.githubusercontent.com/4025991/70468259-13218780-1ac7-11ea-89c6-ae3cf110c9c0.png)
In evince, the standard gnome pdf reader.

What went wrong?
![image](https://user-images.githubusercontent.com/4025991/70468282-1ddc1c80-1ac7-11ea-83aa-73370f295a98.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-12-09 21:00
That's a non-embedded "Symbol" font; the file renders correctly in Firefox Nightly 73 on Windows 7.

**Comment by timvandermeij** [comment] 2019-12-09 21:02
I can also reproduce this using Arch Linux, so since it's a non-embedded font it's most likely OS/configuration specific.

**Comment by Snuffleupagus** [comment] 2021-06-08 08:27
Duplicate of #4244

**Closed by Snuffleupagus** 2021-06-08 08:27 UTC
Labels: 4-font-conversion, 4-non-standard-fonts
