### ISSUE TITLE
Page break & blank page issue on safari 

### ISSUE THREAD

**Issue by muthu07** [mozilla/pdf.js#6654] opened 2015-11-18 09:14 UTC
While using pdf.js, i am facing issues like page breaks, margin issue, font issue and alignment issues on Safari. then i tried in pdf.js demo link that's showing alternate blank page issue. Kindly help on this. Could you please help on this..

**Comment by timvandermeij** [comment] 2015-11-18 20:27
Without a sample PDF file and more information about your configuration (OS name and version, browser version) there is not much we can do. Does it happen with printing or also with regular rendering?

**Comment by muthu07** [comment] 2015-11-19 06:26
Hi @timvandermeij,

Issues are mostly able to reproduce in all Safari browser versions, I have checked in OS X Yosemite - 10.10.5  / Safari 9.0.  while rendering its looking good, but we are facing issue on print the page. 
Its automatically print the page URL on the top(header) of the printed page. But page URL's not printing on any other browsers.

I have big confusion on pdf.js demo link, why its printing alternate page blank in safari.  But here i am getting page breaking ratio is based on header pageurl/page number. Please find below pdf screen shot. Most of my customer are using safari browser only.... :(


![screenshot_11](https://cloud.githubusercontent.com/assets/5626299/11263780/f0ea72d6-8e5b-11e5-94aa-6a49bf2924c5.jpg)

**Comment by timvandermeij** [comment] 2015-11-19 20:35
Closing as duplicate of #6248.

**Closed by timvandermeij** 2015-11-19 20:35 UTC
Labels: 4-printing

**Comment by muthu07** [comment] 2015-11-20 06:16
@timvandermeij 
I am not getting proper solution from your side., But you simply closed like dupicate of #6248. I am Getting stuck on this from past 4 month . #6248 issue something different from my issue., Please compare two screen shots.

And also, there is no solution available for #6248  issue, That is opened from last 5 months. Is PDF.js not supported for Safari browser??
below pdf.js demo link also not supported  in safari print..,

https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by timvandermeij** [comment] 2015-11-20 11:21
You had added a comment on that issue saying that the problem described there was the same as this one. There are already multiple issues open regarding page breaks and font issues for printing for all browsers, so if there is nothing new here we can work with those.
