### ISSUE TITLE
Putting canvas in a container with dir="rtl" messes up the rendering

### ISSUE THREAD

**Issue by wojtekmaj** [mozilla/pdf.js#12081] opened 2020-07-09 10:44 UTC
**Attach (recommended) or Link to PDF file here:**

[dummy.pdf](https://github.com/mozilla/pdf.js/files/4896193/dummy.pdf)

**Configuration:**
- Web browser and its version: Any
- Operating system and its version: Any
- PDF.js version: 2.4.456
- Is a browser extension: No

**Steps to reproduce the problem:**

https://codesandbox.io/s/pdfjs-rtl-container-cwtt6

1. Render canvas within a container with `dir="rtl"`
2. 💥 

It's easily fixed by adding `canvas.setAttribute("dir", "ltr");`, but I'm really not sure how this would affect RTL PDFs.

Original React-PDF bug for reference: https://github.com/wojtekmaj/react-pdf/issues/588

**What is the expected behavior? (add screenshot)**

![image](https://user-images.githubusercontent.com/5426427/87030211-90d67e80-c1e1-11ea-8416-3f68cbfc82ef.png)

**What went wrong? (add screenshot)**

![image](https://user-images.githubusercontent.com/5426427/87030225-9633c900-c1e1-11ea-980c-02eecafca20b.png)

**Comment by Snuffleupagus** [comment] 2020-07-09 10:49
Duplicate of #11457

**Comment by timvandermeij** [comment] 2020-07-09 21:26
Aside from the changes made in PR #11504 there doesn't appear to be anything else that we can do here unfortunately.

**Closed by timvandermeij** 2020-07-09 21:26 UTC
