### ISSUE TITLE
Wrong positioning of text when using a tiling pattern

### ISSUE THREAD

**Issue by luis4a0** [mozilla/pdf.js#9217] opened 2017-11-29 18:10 UTC
Attach (recommended) or Link to PDF file here:
[pattern.pdf](https://github.com/mozilla/pdf.js/files/1514950/pattern.pdf)

Configuration:
- Web browser and its version: Firefox 57.0 and Firefox 52.5.0
- Operating system and its version: Debian GNU/Linux 64-bit
- PDF.js version: the one bundled with Firefox
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached PDF with PDF.js.

What is the expected behavior?
![image](https://user-images.githubusercontent.com/11061462/33390875-fd61e21c-d515-11e7-86d5-1080dd54cbab.png)
(Image was captured from Adobe Reader DC for Windows)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/11061462/33390927-23dd03ea-d516-11e7-9d00-a208c2b9f530.png)
The text is rendered using a tiling pattern for non-stroking operations and shows up on the lower-left corner of the page when rendered with PDF.js. However, if we specify a color for non-stroking operations, the text is correctly positioned on the page.
(Image was captured from Firefox 57.0)

It should be stressed that the file is correctly rendered in Acrobat Reader DC, FoxIt Reader and Evince.

**Comment by Snuffleupagus** [comment] 2017-11-29 19:39
Closing as duplicate of e.g. issue #8940; which was fixed by PR #9090.

**Closed by Snuffleupagus** 2017-11-29 19:39 UTC
