### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by ensemblebd** [mozilla/pdf.js#7006] opened 2016-02-18 07:00 UTC
It works great, on beefy systems. As soon as someone brings out a tablet, it's game over.
Most businesses don't have gaming tablets, they have business tablets. And when the browser uses 3 to 400 mb of RAM on a single page pdf that has no images (AcroForm actually), it's brutal just scrolling the page!

Do you have any recommendations on improving this scenario? Or do I just need to embed a java applet and call it quits? 
I've analyzed the heap in chrome, and it's not reporting anything making use of that ram. At most, 30mb of usage across all fronts, rendering, javascript, system storage, gpu, everything. I can delete the entire head node AND body node from the document, and it's still using that ram (leaving an empty html node). 
 It seems to me after multiple passes, it isn't garbage collecting when the page changes. Making ~70mb (which is high enough on it's own) into 300.

Would really appreciate some pointers on what to do. Because the alternative to this system defeats the entire point of desiring pdf.js in the first place.

**Comment by yurydelendik** [comment] 2016-02-18 14:00
This question does not provide any details. Provide more information as was requested at https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md .

Notice the PDF.js was deployed and used at Firefox OS, which is a low-powered device. But it was solved by using specialized viewer based on PDF.js core library. Using generic/demo desktop version on slow device certainly will look bad. Closing as answered for now until more details are provided.

**Closed by yurydelendik** 2016-02-18 14:00 UTC

**Comment by yurydelendik** [comment] 2016-02-18 14:04
Also, there is only memory stats about single product. Can you also provide stats for the competition e.g. adobe reader or/and pdf viewer for android/ios? PDF is a format that might require more memory by design, see also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#optimize

**Comment by ensemblebd** [comment] 2016-02-18 14:09
Thanks for the response, and the information.
I'll configure a test environment this afternoon to provide you with, since that is a requirement to continue investigation, and also retrieve some numbers for analysis.
I appreciate the assistance

**Comment by ensemblebd** [comment] 2016-02-25 17:23
Alright I have performed some additional work to further and more adequately describe the problem.

You can see the test environment here: http://environment7.net23.net

On most browsers, especially desktop, it works just fine. On Android , that is where the main problem begins. However any device with low CPU speed performs poorly, and it appears to be whenever a scroll occurs, the framerate drops to 7 or lower and the CPU maxes out. 

As far as ram goes:
- Chrome(Desktop):  48mb
- IE9 Desktop:  230mb

- Android :: Chrome: 36mb
- Android :: Stock Webkit Browser:  148mb
- Windows tablet IE11:  85mb

After much testing, I don't believe the problem is PDF.js library, but that old devices (low cpu, low ram) can't handle it properly. 
If I were to re-ask my question, I would ask you why the different browsers have such a profound difference in memory usage. Why so high on android and IE?
