### ISSUE TITLE
render text layer chinese character is incorrect

### ISSUE THREAD

**Issue by RoyLiou** [mozilla/pdf.js#8069] opened 2017-02-14 03:12 UTC
Link to PDF file (or attach file here): https://drive.google.com/file/d/0B2FN2zsOzja-R1Z1QUVDWXg0WVE/view?usp=sharing

Configuration:
- Web browser and its version:  Chrome 56.0
- Operating system and its version: Mac OS 10.12.3
- PDF.js version:  1.7.290
- Is an extension:

Steps to reproduce the problem:
1. I would like on text layer display chinese character, but that incorrect. some character is duplicate. 

What is the expected behavior? (add screenshot)
I expected that display like english text (no superfluous character)

What went wrong? (add screenshot)
http://imgur.com/Rpt2Yjm.jpg

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Many thanks

**Comment by Snuffleupagus** [comment] 2017-02-14 10:59
I get similar broken behaviour in a number of other PDF readers as well, e.g. in both Adobe Reader and PDFium (in Chrome).
The issue is with the PDF file *itself*, since some of the embedded fonts are are not providing complete `ToUnicode` data which is required for text-selection to work properly.

Closing as invalid, since we unfortunately cannot do anything about the missing data in the PDF file.

**Closed by Snuffleupagus** 2017-02-14 10:59 UTC
