### ISSUE TITLE
Incorrect Text Extraction

### ISSUE THREAD

**Issue by VrajGohil** [mozilla/pdf.js#14621] opened 2022-03-01 14:32 UTC
Attach (recommended) or Link to PDF file here: https://certotest1.s3.ap-south-1.amazonaws.com/pdfs/35b44d3f4795477c94de594b9d46c1cd.pdf

Configuration:
- Web browser and its version: Chrome Version 98.0.4758.109 (Official Build) (x86_64)
- Operating system and its version: Windows 11
- PDF.js version: 2.13.216
- Is a browser extension: no

Steps to reproduce the problem:
1. Open https://jsfiddle.net/1zurgbsn/3/
2. Upload the pdf given above.

It fails to extract word **"Certificate"**, it extracts **"Certicate"**

**Comment by Snuffleupagus** [comment] 2022-03-01 14:50
Duplicate of #12237

**Closed by Snuffleupagus** 2022-03-01 14:50 UTC
