### ISSUE TITLE
Doesn't work deployed with newer versions of firefox

### ISSUE THREAD

**Issue by dimitrovmrtn** [mozilla/pdf.js#11632] opened 2020-02-27 08:43 UTC
Configuration:
- Web browser and its version: Mozilla latest
- Operating system and its version: Windows 10 64-bit
- PDF.js version: latest
- Is a browser extension: no

What is the expected behavior?
To convert a blob file to pdf

What went wrong?
It does not display any content, not even a blank page

It does work locally with all versions of Firefox. It also works deployed with older versions. But if I am using the latest Firefox it doesn't do it.

![fail](https://user-images.githubusercontent.com/26876540/75426703-df2f6300-594d-11ea-8a31-d21c7a2a19cd.PNG)

**Comment by Snuffleupagus** [comment] 2020-02-27 08:50
> Web browser and its version: Mozilla latest
> PDF.js version: latest

Please make sure to always provide *actual* version numbers, since "latest" could mean any number of things (e.g. release/beta/nightly build).

> What is the expected behavior?
> To convert a blob file to pdf

Please provide clear and concise steps-to-reproduce the issue, since this's unfortunately nowhere near enough information for anyone to be able to help.

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by dimitrovmrtn** [comment] 2020-02-27 09:17
Firefox Version - 73.0 (64-bit)
PDF.js Version - 2.2.228 

Due to company policy, I'm not allowed to provide access to the platform nor steps-to-reproduce the issue. But it is a fact, that it functions properly on older versions of Firefox.

**Comment by Snuffleupagus** [comment] 2020-02-27 09:23
> Due to company policy, I'm not allowed to provide access to the platform nor steps-to-reproduce the issue.

Without *any* actionable information provided, this unfortunately means that the issue will be closed as INCOMPLETE.

**Closed** 2020-02-27 22:14 UTC
