### ISSUE TITLE
Incorrect rendering of lines/vectors

### ISSUE THREAD

**Issue by Beaverkilla** [mozilla/pdf.js#14466] opened 2022-01-18 08:20 UTC
Attach (recommended) or Link to PDF file here:
[final7-SSS.pdf](https://github.com/mozilla/pdf.js/files/7887295/final7-SSS.pdf)

Configuration:
- Web browser and its version: Firefox 95.0.2
- Operating system and its version: Win 10 21H2 - 19044.1466
- PDF.js version: Unable to retrieve this
- Is a browser extension: Integrated?

Steps to reproduce the problem:
1. Open this pdf in firefox
2. Open this pdf in edge
3. View the difference, it renders correctly in edge but not firefox

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/8328061/149897673-82e86b64-1a89-4190-8017-34d721cd0b10.png)
The pieces of Out-Of-Bounds area on this map should be rendered as a relatively complex shape, showing the area including small differences.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/8328061/149897448-59235198-1abb-4b92-9884-0f6b2cd525da.png)
They're rendered as a diamond or square which is entirely incorrect and includes areas which aren't meant to be covered by this Out-Of-Bounds area. The broken area seems to resize with the size of the original shape ... seemingly proportionally but I can't really tell as it's quite hard to replicate the exact shape. It does always create this error viewing this particular pdf in firefox/pdf.js however.

**Comment by Snuffleupagus** [comment] 2022-01-18 09:58
> Web browser and its version: Firefox 95.0.2

WFM, using Firefox Nightly 98 with its built-in PDF.js version `2.13.24`.
This is most likely a duplicate of [bug 1642583](https://bugzilla.mozilla.org/show_bug.cgi?id=1642583), which was fixed in Firefox 96 (i.e. the current stable release).

Please update to the latest Firefox version, since the one you're using is no longer supported.

**Closed by Snuffleupagus** 2022-01-18 09:58 UTC
