### ISSUE TITLE
Can NOT show stamp

### ISSUE THREAD

**Issue by godwin668** [mozilla/pdf.js#8927] opened 2017-09-19 03:14 UTC
Link to PDF file (or attach file here):
[b.pdf](https://github.com/mozilla/pdf.js/files/1312932/b.pdf)

Configuration:
- Web browser and its version:Chrome
- Operating system and its version:Windows 10 & Mac
- PDF.js version: current version

Steps to reproduce the problem:
1. open online demo: https://mozilla.github.io/pdf.js/web/viewer.html
2. open the attached file and view.

What is the expected behavior? (add screenshot)
<img width="699" alt="screen shot 2017-09-19 at 11 10 08" src="https://user-images.githubusercontent.com/2181421/30574300-93ee2484-9d2b-11e7-91c5-dcca356ec97a.png">

What went wrong? (add screenshot)
Stamp disappears
<img width="703" alt="screen shot 2017-09-19 at 11 10 21" src="https://user-images.githubusercontent.com/2181421/30574312-a399b024-9d2b-11e7-9a45-1edd50105c3e.png">

**Comment by Snuffleupagus** [comment] 2017-09-19 07:47
Closing as duplicate of e.g. issue #4202.

**Closed by Snuffleupagus** 2017-09-19 07:47 UTC
