### ISSUE TITLE
selected/highlighted block collides in pdf in pdf.js

### ISSUE THREAD

**Issue by eaxle** [mozilla/pdf.js#6641] opened 2015-11-16 09:24 UTC
I have used https://gist.github.com/yurydelendik/f2b846dae7cb29c86d23 to highlight the selected text in pdf.I have used color blue and opacity 0.5 and border none in above code.The snapshot of highlight is 
![untitled](https://cloud.githubusercontent.com/assets/11533842/11178139/cd6bb814-8c72-11e5-9634-4882c7abfb82.png)
you can see the rectangular divs hav collided.You can see the line when the text are selected (while mouse  drag, before using the function from https://gist.github.com/yurydelendik/f2b846dae7cb29c86d23 ). Is there any way to omit the collision or to remove the underline seen while the selected text is highlighted. The pdf used is https://github.com/mozilla/pdf.js/blob/master/web/compressed.tracemonkey-pldi-09.pdf .The version of pdf.js used is PDF.js: 1.1.469

**Comment by eaxle** [comment] 2015-11-19 06:11
The divs of the text in pdf collides with each other .That is why the highlights were colliding with each other.Is there any way the collision of divs in pdf in pdf.js be omitted ?

**Comment by yurydelendik** [comment] 2015-11-19 12:39
Please provide information about browser and is? Also link to the custom solution you are referring to.

**Comment by yurydelendik** [comment] 2015-11-19 17:38
duplicate of #6614?

**Comment by timvandermeij** [comment] 2015-11-19 20:39
Yes, closing as duplicate of #6614 and #6456.

**Closed by timvandermeij** 2015-11-19 20:39 UTC
Labels: 4-information-requested, 4-text-selection

**Comment by eaxle** [comment] 2015-11-20 04:30
In https://gist.github.com/yurydelendik/f2b846dae7cb29c86d23 ,inside showHighlight function, instead of var pageElement = page.canvas.parentElement; I used var pageElement = page.canvas.parentNode.nextSibling; and I set the opacity value inside textLayer class from 0.2 to 0.5 .This solves my problem of the underline seen when highlighting the pdf.

**Comment by eaxle** [comment] 2015-11-24 11:17
@timvandermeij The highlighted annotation doesn't   work for zoom level more than 500% .
source https://github.com/eaxle/pdfjsannotation .my annotation code page is https://github.com/eaxle/pdfjsannotation/blob/master/web/showData.js
