### ISSUE TITLE
Black circles on top of some images in some documents.

### ISSUE THREAD

**Issue by justoneissue** [mozilla/pdf.js#5889] opened 2015-03-28 12:40 UTC
There is a bug in rendering some pdfs:
Black elliptic sectors appear in top-left corner of some images. It looks like this:
![image_1 28-03 13-33](https://cloud.githubusercontent.com/assets/11694138/6881050/09116624-d54f-11e4-8cb8-648b7a6e1147.jpg)

In Crome there is a tin black line on the left side of an image. Nothing at all in Adobe Reader.
Link to the document:
http://libgen.in/scimag/get.php?open=1&doi=10.1016%2Fj.saa.2014.06.089

**Comment by Snuffleupagus** [comment] 2015-03-28 12:43
Thanks for the report! However, given that this is a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=858128, I'm closing this issue.

**Closed by Snuffleupagus** 2015-03-28 12:43 UTC
