### ISSUE TITLE
Error: Could not find locale/locale.properties 404. The file is there, but still getting the error. 

### ISSUE THREAD

**Issue by padatshrestha** [mozilla/pdf.js#6506] opened 2015-10-05 19:17 UTC
![capture](https://cloud.githubusercontent.com/assets/4683165/10290788/b9c6b1a6-6b6b-11e5-86d4-5bc436e06003.PNG)

**Comment by timvandermeij** [comment] 2015-10-05 23:40
I have never seen this before, so I really think something is wrong with your server. Might `.htaccess` be blocking that file or the folder it is in? Try visiting the requested URL with your browser and see if it shows the file.

**Comment by padatshrestha** [comment] 2015-10-06 13:29
Hello Tim,
First of all thank you for the email. We are hosting the site on IIS using
DDN (dotnetnuke framework). I have tried accessing file using the url, its
not success. Here is the screen shot
[image: Inline image 1]

Thanks again for the help
Padat Shrestha

**Comment by timvandermeij** [comment] 2015-10-06 13:32
Right, so if you can't access the file using its URL in a browser too, then PDF.js cannot access it either. If the file is at the specified location, then your server is not allowing it to be accessed, probably because of `.htaccess` or some other permission verification component. Since this is a server problem and not a bug in PDF.js, I'm closing this issue.

(By the way, you cannot post screenshots from e-mail, only on the GitHub website itself.)

**Closed by timvandermeij** 2015-10-06 13:32 UTC
Labels: 4-information-requested

**Comment by padatshrestha** [comment] 2015-10-06 13:36
Sounds good! Thank you for your help Tim.

**Comment by AndresHurtadoRMT** [comment] 2018-12-17 10:34
Adding this to the webconfig file did the trick for me
 ```
   <staticContent>
        <mimeMap fileExtension=".json" mimeType="application/json" />
        <mimeMap fileExtension=".properties" mimeType="application/json" />
    </staticContent>
```
