### ISSUE TITLE
Safari viewer display issues

### ISSUE THREAD

**Issue by KieranP** [mozilla/pdf.js#15107] opened 2022-06-28 00:03 UTC
Attach (recommended) or Link to PDF file here: (any PDF)

**Configuration:**

- Safari 14.1.2
- MacOS 11.6
- PDF.js version: 2.14.305
- Is a browser extension: No

Issue does not occur on MacOS 12.4 with Safari 15.5. So issue appears to be on older versions of Safari.

**Steps to reproduce the problem:**

1. Embed PDF.js into existing website through iframe

**What is the expected behavior?** 

PDF displays correctly

**What went wrong?**

Some of the viewer is not hidden, and shows up both while PDF is loading and behind the PDF once it has loaded.

![2E886F7C-F2FE-4D25-8FC5-C8342E3EC12C](https://user-images.githubusercontent.com/16620/176058563-155afc7c-79c7-4083-b2e1-a0f1aef5792f.jpeg)

<img width="997" alt="Screenshot 2022-06-20 at 3 47 47 PM" src="https://user-images.githubusercontent.com/16620/176059175-5ba4b95c-4a35-4958-9cd9-8a9908eeade5.png">

**Comment by Snuffleupagus** [comment] 2022-06-28 07:37
Duplicate of #14995

**Closed by Snuffleupagus** 2022-06-28 07:37 UTC
