### ISSUE TITLE
bad XRef entry -- caused by incorrect merge of nested xref and ending xref

### ISSUE THREAD

**Issue by xrbd** [mozilla/pdf.js#6994] opened 2016-02-15 16:10 UTC
PDF.js v1.4.76 (build: 45fea88)
Message: bad XRef entry

I have a PDF file supplied by a customer, which fails to display with above message in 'http://mozilla.github.io/pdf.js/web/viewer.html?file='.  (Unfortunately, it is medical data, so I can't share it).

I have debugged the problem, and determined that the 1.3 version PDF has 2 %%EOFs and 2 xrefs.  The second (main) xref defines replacement objects for several objects defined in the previous xref.  When the two xrefs are merged in processXRefTable, the result is one of the objects is defined twice, due to xref sub-section header with what I believe to be an incorrect first object number, resulting in a mismatch later between the expected object number and the actual object number.

I have developed a fix, and am in the process of creating a pull request.  (This is my first github contribution, and my first contribution to pfd.js (though I have PDF internals experience).  So it will probably take me several more days to submit the pull request.)

**Comment by timvandermeij** [comment] 2016-02-15 16:14
Thank you for reporting this and working on a fix! It would really help if there would be a PDF test case. Since you have experience with PDF internals, couldn't you remove the sensitive parts from the PDF file to create a reduced test case? We normally request reduced test cases to avoid regressions in the future.

**Comment by xrbd** [comment] 2016-02-15 19:57
Hi Tim.  

I am trying to get a message to end-user, to determine what product generated the file.

I will construct a test-case using a binary editor if I am unable to get test-case from end-user.  

--Blair Davies

**Comment by SamyCookie** [comment] 2016-04-21 15:28
@xrbd Your issues should be fixed by #7233. Could you confirm that ?

**Comment by timvandermeij** [comment] 2016-04-21 20:06
Closing as fixed by #7233 since the proposed PR for this fix contained the same logic. If there is anything else to do here, please let us know and we'll reopen this.

**Closed by timvandermeij** 2016-04-21 20:06 UTC
Labels: 1-core, 4-information-requested
