### ISSUE TITLE
Some random area are selected if very end of the line being selected. 

### ISSUE THREAD

**Issue by HuiguangChu** [mozilla/pdf.js#16290] opened 2023-04-14 09:46 UTC
Attach (recommended) or Link to PDF file here:

https://mozilla.github.io/pdf.js/web/viewer.html

**Configuration:**
- Web browser and its version:  Chrome,  Version 112.0.5615.49 (Official Build) (x86_64)
- Operating system and its version: macOS Monterey(12.6.3)
- PDF.js version:  latest
- Is a browser extension:  no

**Steps to reproduce the problem:**
1. Open the demo page: https://mozilla.github.io/pdf.js/web/viewer.html
2. Try to select a line, to the very end of the line

**What is the expected behavior?** 

 Should work the same as on Firefox

> 

> https://user-images.githubusercontent.com/3482267/232009262-471f0f5e-1c6e-444e-a41a-183f2861612e.mov

**What went wrong?**

 Some random area are selected if very end of the line being selected. 

https://user-images.githubusercontent.com/3482267/232011202-62d982e8-ac41-4479-9fcd-3cda6dd9bae7.mov

**Comment by Snuffleupagus** [comment] 2023-04-14 09:53
Duplicate of #9843

**Closed by Snuffleupagus** 2023-04-14 09:53 UTC
