### ISSUE TITLE
Multiple issues for an NVIDIA pdf

### ISSUE THREAD

**Issue by birdie-github** [mozilla/pdf.js#10878] opened 2019-06-02 12:05 UTC
Attach (recommended) or Link to PDF file here: http://us.download.nvidia.com/Windows/361.43/361.43-win10-win8-win7-winvista-desktop-release-notes.pdf

Configuration:
- Web browser and its version: Firefox 68 beta 6
- Operating system and its version: Fedora 30 fully updated + proprietary NVIDIA drivers
- PDF.js version: no idea
- Is a browser extension: no

Steps to reproduce the problem:
1. Open this PDF

What is the expected behavior? (add screenshot)
(Google Chrome on the same PC)
![chrome](https://user-images.githubusercontent.com/4958603/58760996-59b28a00-8558-11e9-9355-7c003f534807.png)

What went wrong? (add screenshot)
* Wrong (varying) spacing between letters
* Wrong strokes width
* Bad kerning 

![notfixed](https://user-images.githubusercontent.com/4958603/58760982-37207100-8558-11e9-9334-d580bc81ffa8.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-06-02 12:13
Duplicate of #2739.

**Comment by birdie-github** [comment] 2019-06-02 12:20
#2739 was closed and never fully fixed.

**Comment by birdie-github** [comment] 2019-06-02 12:31
And this is how it should look like:

![adobe_reader](https://user-images.githubusercontent.com/4958603/58761313-3ee21480-855c-11e9-854f-a08c05f7578b.png)

**Comment by Snuffleupagus** [comment] 2019-06-02 14:01
> #2739 was closed and never fully fixed.

Please see https://github.com/mozilla/pdf.js/issues/2739#issuecomment-450633930:
> This PDF file looks good now on Arch Linux, i.e., it renders exactly the same in PDF.js for me as it does in Okular. Since the file does not embed its fonts, there is not much more we can do here.

**Comment by birdie-github** [comment] 2019-06-02 15:39
Arch Linux is not the Linux. Fedora is also very popular. There are literally hundreds of thousands of people who use NVIDIA proprietary drivers under Linux. It's not the reason to say _"there is not much more we can do here"_.

You're pretty much saying, _"We couldn't care less about a large number of Linux users because in our very particular distro under very particular graphics drivers it just works"_. No, it doesn't.

If you need any data from me, like drivers versions, libraries version, etc. I can readily provide it.

**Comment by automatedbugreportingfacility** [comment] 2019-06-02 16:52
This also seems to affect Windows:

![x](https://user-images.githubusercontent.com/3524640/58764447-57a3f780-8567-11e9-8431-ecc486dc1150.png)

Sorry for the noob question, but if the font isn't embedded, where does PDFium fetch it from in Chromium?

**Comment by Snuffleupagus** [comment] 2019-06-02 17:04
> Since the file does not embed its fonts, there is not much more we can do here.

The PDF file *itself* does not embed all of its fonts, which is a deprecated practice in the specification (because of font substitution issues similar to this one), and the PDF.js library is thus at the mercy of the platform/operating system to provide some reasonable default standard font.

**Comment by automatedbugreportingfacility** [comment] 2019-06-03 09:13
Yes, I know the font should be included in the PDF file, but the underlying OS providing the default standard font (Windows 10 1809) is the same for Chromium and Firefox Nightly, hence the question. Does PDFium come with some predefined set of fonts potentially unavailable in operating systems? Also, spacing seems to look better when PDF.js is running in Chromium (the screenshot I posted in the previous comment is from Nightly):

![x](https://user-images.githubusercontent.com/3524640/58790312-70a4bb00-85f0-11e9-94a0-27e9813bc9a5.png)

**Comment by timvandermeij** [comment] 2019-06-03 22:16
I'm not really sure how to proceed here. For me it looks exactly like the second screenshot in https://github.com/mozilla/pdf.js/issues/10878#issuecomment-498026964. Yes, it's a substituted font, but if the PDF file doesn't embed the fonts, we can only fall back to a close substitute as explained in https://github.com/mozilla/pdf.js/issues/10878#issuecomment-498048215. We could try to look into why it's not the same substitute as in Chrome, but it will always be a substitute and is likely to differ between operating systems and platforms.

> You're pretty much saying, "We couldn't care less [...]"

That's not true. If there is in fact something that can still be done about this or if there was an oversight, we're always willing to reopen issues (which we do now because I think the question is https://github.com/mozilla/pdf.js/issues/10878#issuecomment-498177749 is a good question), but only if the discussion is constructive. Remember that most people here aren't employees, but help out in their spare time.

**Comment by automatedbugreportingfacility** [comment] 2019-06-04 10:25
FWIW, PDFium matches what Adobe Acrobat Reader DC displays on the same system (fresh VBox VM for Windows 10):

![x](https://user-images.githubusercontent.com/3524640/58872114-a4044a00-86c3-11e9-80d0-cb963ba06420.png)

**Comment by timvandermeij** [comment] 2019-06-04 21:23
Thank you for making the comparison. Here I also see some differences between Adobe Acrobat Reader DC and PDFium, in particular the "December 21, 2015" text where the "5" character looks thicker (more bold) than in PDFium, but you're right that especially the large white text looks better in those two applications than in PDF.js.

**Comment by birdie-github** [comment] 2019-06-26 07:57
Another PDF with a completely broken kerning:

http://pascal.hansotten.com/uploads/docs/euler%20stanford%20CS-TR-65-20.pdf

**Comment by marco-c** [comment] 2023-05-12 07:39
#16363 might have fixed this, can you still reproduce in latest Firefox Nightly?

**Comment by automatedbugreportingfacility** [comment] 2023-05-13 02:11
PDFium displays it better than pdf.js, https://github.com/mozilla/pdf.js/issues/10878#issuecomment-498614407 still applies. https://github.com/mozilla/pdf.js/issues/10878#issuecomment-505764669 seems fixed, so that was something different.

**Closed** 2023-05-14 10:27 UTC
Labels: non-standard-fonts

**Comment by birdie-github** [comment] 2023-05-14 16:13
@calixteman 

It indeed looks to be fixed in the nightly - when will the fix land in stable?
