### ISSUE TITLE
pdf origal file form text missing

### ISSUE THREAD

**Issue by pisces22745** [mozilla/pdf.js#10929] opened 2019-06-25 06:46 UTC
Attach (recommended) or Link to PDF file here:
http://gongmall-file.oss-cn-hangzhou.aliyuncs.com/gmmanager-test/employeeContract/2_null/[80972577-%E9%82%B5%E7%82%89%E7%90%B4-33012219930226154X]%E7%94%B5%E7%AD%BE%E5%90%88%E5%90%8C.pdf?response-content-type=application/pdf
Configuration:

Web browser and its version: chrome 75.0.3770.100
Operating system and its version: windows10
PDF.js version: 2.0.943
Is a browser extension:
Steps to reproduce the problem: 1. 2.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/21116713/60081300-1bc61180-9764-11e9-9566-f46b75760054.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/21116713/60081332-284a6a00-9764-11e9-82a8-cedd9c66ff74.png)

form elements didn't show,how can I let the form elements shows

**Comment by Snuffleupagus** [comment] 2019-06-25 07:28
Without *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md this issue will be closed as INVALID.

**Comment by pisces22745** [comment] 2019-06-25 08:18
> Without _all_ of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md this issue will be closed as INVALID.

ok

**Comment by Snuffleupagus** [comment] 2019-06-25 08:26
WFM, when using PDF.js version `2.2.207` in Firefox Nightly. (The signature isn't displayed, but that's already tracked elsewhere).

**Comment by pisces22745** [comment] 2019-06-25 08:45
I comment the code in pdf.worker.js, authough, I don't favor this method
    // if (data.fieldType === 'Sig') {
      // _this2.setFlags(_util.AnnotationFlag.HIDDEN);
    // }

**Comment by timvandermeij** [comment] 2019-06-25 10:22
Closing since this is now a duplicate of the issues in https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-digital-signature.

**Closed by timvandermeij** 2019-06-25 10:22 UTC
