### ISSUE TITLE
Grey lines inserted into pdf, when the pdf file is opened with latest Firefox on a windows 10 machine

### ISSUE THREAD

**Issue by jeyanozice** [mozilla/pdf.js#9592] opened 2018-03-21 10:13 UTC
please see the following pdf, how it is properly shown with google chrome, but when opened with Firefox, some grey lines show up. This was seen on windows 10 machine

[FIRST_AID.pdf](https://github.com/mozilla/pdf.js/files/1840834/FIRST_AID.pdf)

How it is seen in Chrome (latest version):
![chrome](https://user-images.githubusercontent.com/37618069/37821047-34c5a4c2-2e8b-11e8-886b-3da1ef039683.jpg)

How it is seen in Firefox (latest version):
![firefox](https://user-images.githubusercontent.com/37618069/37821054-37beed96-2e8b-11e8-94a3-a73d6949fe47.jpg)

**Comment by jeyanozice** [comment] 2018-03-26 14:31
when i open the same link with the Ubuntu (16.04) 64 bit version of Firefox, the pdf is shown ok. The problem only shows up with the version of Firefox for windows (windows 10).

**Comment by Snuffleupagus** [comment] 2018-03-27 09:09
This is an upstream bug (most likely https://bugzilla.mozilla.org/show_bug.cgi?id=1336572), connected with hardware acceleration on Windows. Hence we can probably close this issue as duplicate of https://github.com/mozilla/pdf.js/issues/8022#issuecomment-277372590.

**Comment by timvandermeij** [comment] 2018-03-27 19:42
Yes, it looks like that is the same issue. Closing this one.

**Closed by timvandermeij** 2018-03-27 19:42 UTC
Labels: 4-firefox-specific, 4-os-windows
