### ISSUE TITLE
Problem in Chrome and Firefox

### ISSUE THREAD

**Issue by LoxodontaM** [mozilla/pdf.js#6870] opened 2016-01-14 12:30 UTC
I'm using pdf.js as PDF viewer in a web application to view PDF files. In Chrome, the attached file isn't rendered well: the dots on the purple squares are not shown in the 64 bit version of 47.0.2526.111 in Ubuntu 15.04 (and under Windows NT 5.1 (XP), Chrome/47.0.2526.106 as well). In Firefox also under Windows (Mozilla/5.0 (Windows NT 6.0; rv:43.0) Gecko/20100101 Firefox/43.0). No errors are thrown when viewing the page.

[question.pdf](https://github.com/mozilla/pdf.js/files/90319/question.pdf)

Behaviour in Chrome:
![chrome](https://cloud.githubusercontent.com/assets/16702446/12325518/10e849fa-bacb-11e5-9dae-75f604fe2819.png)
Behaviour in Firefox on Linux:
![ff](https://cloud.githubusercontent.com/assets/16702446/12325519/1105da56-bacb-11e5-8be4-c68d353f46e8.png)

**Comment by yurydelendik** [comment] 2016-01-14 13:31
Small test case with PDF to reproduce:

```
    ctx.lineCap = "round";
    ctx.lineWidth = 38;
    ctx.moveTo(181.492,168.539);
    ctx.lineTo(181.492,168.539);
    ctx.stroke();
```

/cc @Rob--W

**Comment by yurydelendik** [comment] 2016-01-14 13:48
Reported as https://code.google.com/p/chromium/issues/detail?id=577655

**Comment by LoxodontaM** [comment] 2016-01-20 12:42
Problem also occurs in Firefox on Windows. This is not Chrome-only.

**Comment by yurydelendik** [comment] 2016-01-20 15:41
@LoxodontaM, can you paste the graphics section from the about:support ? Firefox is using the same backend as Chrome for some configurations I wonder if it's your case.

**Comment by LoxodontaM** [comment] 2016-01-20 15:43
It's in Dutch, but I hope you have enough information this way:

Grafisch
Adapter-RAM	Unknown
Adapterbeschrijving	VirtualBox Graphics Adapter for Windows 8
Adapterstuurprogramma’s	VBoxDispD3D
Asynchroon pannen/zoomen	geen
Datum stuurprogramma	12-18-2015
Device-ID	0xbeef
Direct2D ingeschakeld	Geblokkeerd voor uw grafische kaart vanwege onopgeloste problemen met het stuurprogramma.
DirectWrite ingeschakeld	false (10.0.10586.0)
GPU #2 actief	false
GPU-versnelde vensters	1/1 Direct3D 11 WARP (OMTC)
Ondersteunt hardwarematige H264-decodering	No; Hardware video decoding disabled or blacklisted
Stuurprogrammaversie	5.0.12.0
Subsys-ID	00000000
Vendor-ID	0x80ee
WebGL-renderer	Geblokkeerd voor uw grafische kaart vanwege onopgeloste problemen met het stuurprogramma.
windowLayerManagerRemote	true
AzureCanvasBackend	skia
AzureContentBackend	cairo
AzureFallbackCanvasBackend	cairo
AzureSkiaAccelerated	0

**Comment by timvandermeij** [comment] 2016-01-20 19:24
Let me translate this a bit. An important problem here might be *Geblokkeerd voor uw grafische kaart vanwege onopgeloste problemen met het stuurprogramma*, which means "Blocked for your graphics card because of unresolved problems with the driver", indicating that this might be a driver issue. Please try to upgrade the graphics driver if is not yet the most recent version. I also wonder if VirtualBox might be causing issues here. I cannot reproduce the problem on Windows 10 x64 with the latest PDF.js development version.

**Comment by LoxodontaM** [comment] 2016-01-20 19:31
Someone has informed me of the error in Firefox and I was able to reproduce it in VirtualBox. Indeed, on my non-virtual Windows system, I also do not have this problem. Strange. I can't track the graphics properties of the person who informed me, but I suppose it's not a VirtualBox user.

**Comment by timvandermeij** [comment] 2016-05-04 22:33
The upstream Chrome bug is fixed. Is this still an issue using the latest version of PDF.js and Chrome/Firefox?

**Comment by Rob--W** [comment] 2016-05-04 23:21
I don't see any dots on the purple squares in the PDF.js Chrome extension, v1.4.55, Chromium	50.0.2661.94 on Linux.

**Comment by Snuffleupagus** [comment] 2022-02-13 12:51
WFM, using PDF.js version `2.13.136` in both Firefox Nightly 99 and Google Chrome Beta 99.

Given the age of this issue and that it seems to be *browser* rather than PDF.js related, closing this as WORKSFORME.

**Closed by Snuffleupagus** 2022-02-13 12:51 UTC
Labels: upstream, image-quality
