### ISSUE TITLE
How to get page wise base64

### ISSUE THREAD

**Issue by GaikwadVikas** [mozilla/pdf.js#8996] opened 2017-10-06 09:34 UTC
I want to display pdf pages preview ones it is browsed.

        var showInCanvas = function (url) {
            try {
                var pdfAsArray = convertDataURIToBinary(url);
                PDFJS.getDocument(pdfAsArray).then(function (pdf) {
                    TotalPagesCount = $this.TixSeatsObject.length + pdf.numPages;
                    for (var i = 1; i <= pdf.numPages; i++) {
                        pdf.getPage(i).then(function (page) {
                            console.log(page);
                            CreatePage(page);
                        });
                    }
                }, function (ex) {
                    SU.Loading(false, "Page");
                    SU.ShowAlert(LocalLocalizer.Get("Fail"), LocalLocalizer.Get(ex.message), null, "warning alertDialog zIndex9999");
                });
                var $Dialog = $(Dialog.RootElement).dialog("widget");
                $("#Remove", $Dialog).show();
            } catch (e) {
                CheckPreviewProcess();
            }
        }

        var convertDataURIToBinary = function (dataURI) {
            var BASE64_MARKER = ';base64,';
            var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
            var base64 = dataURI.substring(base64Index);
            var raw = window.atob(base64);
            var rawLength = raw.length;
            var array = new Uint8Array(new ArrayBuffer(rawLength));
            for (i = 0; i < rawLength; i++) {
                array[i] = raw.charCodeAt(i);
            }
            return array;
        }
        //Create Preview for Pdf Page 
        var CreatePage = function (page) {
            var viewport = page.getViewport(2.5);
            var canvas = document.createElement('canvas');
            var ctx = canvas.getContext('2d');
            canvas.height = viewport.height;
            canvas.width = viewport.width;

            var renderTask = page.render({
                canvasContext: ctx,
                viewport: viewport
            });
            // Wait for rendering to finish
            renderTask.promise.then(function () {
                console.log(page, ctx);
                ctx.globalCompositeOperation = "destination-over";
                ctx.fillStyle = "#ffffff";
                ctx.fillRect(0, 0, canvas.width, canvas.height);
                var imgSRC = canvas.toDataURL();
                var SeatId = Math.random().toString(36).substr(2, 9);

                $this.TixSeatsObject.push({
                    SeatId: SeatId,
                    Seat: "",
                    PdfStatus: Enumerations.ArtifactStatus.NotAvailable.Name,
                    BarcodeStatus: Enumerations.ArtifactStatus.NotAvailable.Name,
                    Barcode: "",
                    SeatStatus: Enumerations.SeatStatus.Any.Name,
                    Base64String: imgSRC,
                    Action: "Browsed",
                    Barcodes: []
                });

                CheckPreviewProcess();
            });
        }

        //Pdf Upload change event
        $("#UploadPDFInput", Dialog.rootElement).change(function () {
            try {
                if (this.files && this.files[0]) {
                    if (this.files[0].type == "application/pdf") {
                        SU.Loading(true, "Page", 99999);
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            showInCanvas(e.target.result);
                        }
                        reader.readAsDataURL(this.files[0]);
                    }
                    else {
                        SU.ShowAlert(LocalLocalizer.Get("Fail"), "Invalid file.", null, "warning alertDialog zIndex9999");
                    }
                }
            } catch (e) {
                CheckPreviewProcess();
            }
        });`

Please, check above code. In **CreatePage** function after **page.render** I
get base64 of image (**canvas.toDataURL**). But, I need base64 of pdf page.

Please, help me.

**Comment by Snuffleupagus** [comment] 2017-10-06 09:42
Closing as duplicate of #8995.

Please don't open *multiple* issues for the same problem, especially when the first one was closed because the details provided were not clear/detailed enough to easily understand what's being asked.

**Closed by Snuffleupagus** 2017-10-06 09:42 UTC

**Comment by GaikwadVikas** [comment] 2017-10-06 09:45
@Snuffleupagus , please try to understand my problem.

All details are provided in this previous one is closed.
