### ISSUE TITLE
Can't play our sound and AV files

### ISSUE THREAD

**Issue by neffe** [mozilla/pdf.js#7173] opened 2016-04-09 16:55 UTC
Apparently we can't play our sound and AV files any longer and I don't think its because of our pdf viewer. Can you explain that? Before we didn't have any problems with that.
See: [http://www.soundeffects.dk/article/view/5184/5430](url)
Regards
Niels Erik Frederiksen

Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2016-04-09 17:09
There has never been support for audio and video annotations in PDF.js. There is a work-in-progress PR, but it did not made it to master yet. You must have used another PDF viewer before that did have support for this feature. Closing as answered as the audio/video annotations are being tracked in #2787.

**Comment by yurydelendik** [comment] 2016-04-09 17:10
One on page 4? PDF.js does not support playback of the "Screen" annotations. I don't see any other PDF readers can, bot Adobe Reader can if unsafe feature is enabled.

> Before we didn't have any problems with that.

Please explain. Did you use other version of PDF.js, browsers, etc? I recommend to fill out the requested Configuration section. As is the issue is incomplete.

**Closed by timvandermeij** 2016-04-09 17:09 UTC
