### ISSUE TITLE
Partial loading of a PDF

### ISSUE THREAD

**Issue by epannekoucke** [mozilla/pdf.js#13803] opened 2021-07-27 13:43 UTC
OS : Windows 10 20H2
PDF.js version : 2.6.347
Browser : FireFox 78.9.0

While loading PDF with large page count, some pdf face infinite loading.

I also noticed this problem when scrolling too fast (up, down, up, down).

![Screenshot_7](https://user-images.githubusercontent.com/88041202/127164325-21567489-13c3-4fdd-82e0-21797c5b3a32.png)

Is this problem known and would you have a solution or a fix?

Regards.

**Comment by Snuffleupagus** [comment] 2021-07-27 13:45
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue is unfortunately missing all the necessary information to be actionable/valid.

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by epannekoucke** [comment] 2021-07-27 14:10
OS : Windows 10 20H2
PDF.js version : 2.6.347
Browser : FireFox 78.9.0

**Comment by Snuffleupagus** [comment] 2021-07-27 14:24
> PDF.js version: 2.6.347

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download; hence you'll have to update to an actually supported release first (before asking for help).

Furthermore, with *neither* the PDF file in question nor a runnable example provided (as asked for above), it's unfortunately completely impossible for anyone to help (since only a screen-shot cannot be used to reproduce/debug a problem).

Closing as INCOMPLETE for now; we can re-open this issue when all of the necessary information has been provided.

**Closed by Snuffleupagus** 2021-07-27 14:24 UTC
Labels: 4-information-requested
