### ISSUE TITLE
Hypelink in PDF not working in viewer

### ISSUE THREAD

**Issue by generiscorp** [mozilla/pdf.js#9283] opened 2017-12-15 13:20 UTC
The pdf.js viewer doesn't not allow clicking on hyperlinks in PDF documents.  I'm attaching a sample PDF - I created a sample Word document with a hyperlink and saved it as a PDF using Microsoft Word. Then opened with https://mozilla.github.io/pdf.js/web/viewer.html and the link is not clickable. 

[Uploading Hyperlink.docx…]()

Attach (recommended) or Link to PDF file here:
[hyperlink.pdf](https://github.com/mozilla/pdf.js/files/1562739/hyperlink.pdf)

Configuration:
- Web browser and its version: Chrome 63
- Operating system and its version: Mac
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: No

Steps to reproduce the problem:
1. Create a document in Word with a hyperlink and save as PDF
2. Open in viewer https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)
Hyperlink should be clickable

What went wrong? (add screenshot)
Hyperlink not clickable.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2017-12-15 14:29
Closing as duplicate of issue #9224 (and a multitude of others).

**Closed by Snuffleupagus** 2017-12-15 14:29 UTC

**Comment by generiscorp** [comment] 2017-12-15 14:37
@Snuffleupagus  I don't see this as a duplicate, there is no text with www that is not automatically hyperlinked, there is an actual hyperling in the content that works fine from Acrobat Reader and other tools like Brava and Arender. But it doesn't in PDF.js. The referred ticket refers to a different ticket.

**Comment by Snuffleupagus** [comment] 2017-12-15 14:41
Quoting (myself) from https://github.com/mozilla/pdf.js/issues/9224#issuecomment-348458347:
> That PDF file doesn't actually contain any links, but just standard text.
>
> Such "links" can work in e.g. Adobe Reader, but only if you have enabled automatic creation of hyperlinks (this setting seems to default to on).
>
> The issue is tracked in #3172, hence I'm closing this as duplicate.

**Comment by THausherr** [comment] 2017-12-28 10:31
@generiscorp  When I click on it with Adobe Reader DC nothing happens.
