### ISSUE TITLE
Annotation not showing in pdf.js web viewer

### ISSUE THREAD

**Issue by shazidhasan** [mozilla/pdf.js#11898] opened 2020-05-13 05:53 UTC
Attached PDF doesn't show popup annotations when view in https://mozilla.github.io/pdf.js/web/viewer.html

[output_62.pdf](https://github.com/mozilla/pdf.js/files/4620079/output_62.pdf)

Configuration:

Web browser and its version: all browsers, tested with Chrome and Firefox latest versions.
Operating system and its version: tested in Windows 10
PDF.js version: current (online version)

Steps to reproduce the problem:

Visit https://mozilla.github.io/pdf.js/web/viewer.html
Upload the above file
There have two annotations; one is polygon another is polyline annotation.
Which are not showing.

What is the expected behavior? (add screenshot)
![Screenshot_from Acrobat reader](https://user-images.githubusercontent.com/1089262/81776177-2f12d480-9510-11ea-9e80-b35331a3b279.jpg)

**Comment by THausherr** [comment] 2020-05-13 07:49
The two annotations have no appearance stream. Probably duplicate of #6810.

**Comment by timvandermeij** [comment] 2020-05-13 21:51
Definitely. Let's close this one as a duplicate.

**Closed by timvandermeij** 2020-05-13 21:51 UTC
