### ISSUE TITLE
rendering pdf : "Warning: Knockout groups not supported." pdf.js:201

### ISSUE THREAD

**Issue by mehlis** [mozilla/pdf.js#5640] opened 2015-01-13 09:48 UTC
redering seems not affected

http://www.100y.com.tw/pdf_file/39-Nordic-NRF51822.pdf

```
"PDF 44253951d25fcb334b58716166f84ff [1.6 Acrobat Distiller 10.1.4 (Windows) / FrameMaker 11.0] (PDF.js: 1.0.277)" viewer.js:3461
"Warning: Knockout groups not supported." pdf.js:201
"Warning: JavaScript is not supported" viewer.js:3401
"Warning: Knockout groups not supported." pdf.js:201
```

**Comment by Snuffleupagus** [comment] 2015-01-13 10:32
Thanks for the report!
This is a duplicate of issue #3136, hence I'm closing this one.

**Closed by Snuffleupagus** 2015-01-13 10:32 UTC
