### ISSUE TITLE
Text from pdf document appears faded on top of the document on document preview

### ISSUE THREAD

**Issue by harsha1029708** [mozilla/pdf.js#11594] opened 2020-02-13 13:49 UTC
Configuration:
Web browser and its version: Google Chrome Version 80.0.3987.100 (Official Build) (64-bit)
Operating system and its version: Windows 10
PDF.js version: '`-- pdfjs-dist@2.2.228'
Is a browser extension: NA
Steps to reproduce the problem:
Upload a PDF document to angular app with pdfjs viewer
Observe that, all the pdf text is accumulated on the top of preview in faded text
What is the expected behavior? (add screenshot): Faded text should not appear & user should be able to select Pdf text in the same format in the document
What went wrong? (add screenshot) Added,
Code snippet as below
public setupViewer(): void {
        this.pdfJs.disableTextLayer = false;

        this.pdfLinkService = new this.PDFJSViewer.PDFLinkService();
        this.pdfFindController = new this.PDFJSViewer.PDFFindController({ linkService: this.pdfLinkService });

        const pdfOptions: any = {
            container: this.scrollContainer.nativeElement,
            linkService: this.pdfLinkService,
            removePageBorders: false,
            textLayerMode: 1,
            findController: this.pdfFindController,
        };

        pdfOptions.annotationLayerFactory = new this.PDFJSViewer.DefaultAnnotationLayerFactory();
        this.pdfViewer = new this.PDFJSViewer.PDFViewer(pdfOptions);
        this.pdfLinkService.setViewer(this.pdfViewer);
    }

![faded text](https://user-images.githubusercontent.com/60999968/74441304-967ba280-4e95-11ea-888c-d131bfe099c5.JPG)

**Comment by Snuffleupagus** [comment] 2020-02-13 13:57
Duplicate of #11592, which is already answered.

*For future reference:* Please refrain from knowingly open duplicate issues!

**Closed** 2020-02-13 21:55 UTC
