### ISSUE TITLE
can we change the html code to implement annotation in pdf.js?

### ISSUE THREAD

**Issue by seanM29** [mozilla/pdf.js#7817] opened 2016-11-15 18:17 UTC
Link to PDF file (or attach file here):
use the pdf in the pdfjs-1.5.188-dist 
Configuration:
- firefox
- Ubuntu 14.04(VMware 12)
- pdfjs-1.5.188-dist
- no

Steps to reproduce the problem:
1. run the viewer.html in the pdfjs-1.5.188-dist.zip
2. I  change the html source code in Firefox Inspector using edit html, I found the code change, but the pdf display in t he screen did not change.

What is the expected behavior? (add screenshot)
the pdf displayed changed
What went wrong? (add screenshot)
the pdf change
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment] 2016-11-15 18:28
It's hard to tell what the issue is based on the description above. Change in HTML via the debug tools are not affect canvas display -- in best case it will affect text selection, UI or some types of annotations. Closing the issue as invalid since it works as expected.

**Closed by yurydelendik** 2016-11-15 18:28 UTC

**Comment by seanM29** [comment] 2016-11-15 18:36
thank you very much. so I wonder is there a way I can use to add annotation using pdf.js? or use other methods?
