### ISSUE TITLE
The pdf preview is displayed normally, but the DOM text is garbled

### ISSUE THREAD

**Issue by happyByteDance** [mozilla/pdf.js#14379] opened 2021-12-15 12:41 UTC
Attach (recommended) or Link to PDF file here:
Configuration:
[test.pdf](https://github.com/mozilla/pdf.js/files/7719368/test.pdf)
- Web browser and its version:chrome Version 96.0.4664.93 (official version) (x86_64)
- Operating system and its version:macOS version 10.15.7 
- PDF.js version:Stable (v2.10.377)
- Is a browser extension: no

Steps to reproduce the problem:
1. Open browser preview
2. View DOM text

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/96180924/146188206-f6461741-4d6b-479f-bbbb-485387d86af7.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/96180924/146187938-cc0de8b7-b565-40cb-9b12-9faab03b5939.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-12-15 12:44
Duplicate of #14378

**Closed by Snuffleupagus** 2021-12-15 12:44 UTC

**Comment by happyByteDance** [comment] 2021-12-15 12:51
@Snuffleupagus Thank you very much for coming to help me, this is my complete supplement
