### ISSUE TITLE
PDF only renders half the page at 100%

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#17754] opened 2024-02-29 11:43 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 121.0.6167.185 
- Operating system and its version: Windows 10
- PDF.js version: As used by current mozilla.github.io/pdf.js viewer 
- Is a browser extension: no

Steps to reproduce the problem:
1. Open PDF
2. Set zoom to 100%

What is the expected behavior? (add screenshot) The whole page is rendered

What went wrong? (add screenshot) Only the top half renders

[Stephens_SFLC747_Open_Never_Active_LBA_EM_02-27-24.pdf](https://github.com/mozilla/pdf.js/files/14447291/Stephens_SFLC747_Open_Never_Active_LBA_EM_02-27-24.pdf)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2024-02-29 11:56
Duplicate of #14982

**Closed by Snuffleupagus** 2024-02-29 11:56 UTC
