### ISSUE TITLE
Page Scrolling + Page Fit

### ISSUE THREAD

**Issue by vicencb** [mozilla/pdf.js#18177] opened 2024-05-27 23:49 UTC
Attach (recommended) or Link to PDF file here:
Reproducible with most PDF files.

Configuration:
- Web browser and its version: Firefox 126, also previous versions.
- Operating system and its version: Wayland on Linux 6.x, also previous versions.
- PDF.js version: as shipped with Firefox 126, also previous versions.
- Is a browser extension: No

Steps to reproduce the problem:
1. Select zoom to "Page Fit"
2. Select scroll mode to "Page Scrolling"
3. Select either "No", "Odd" or "Even Spreads"

What is the expected behavior?
Whole page(s) visible on screen with no scroll bars.
Mouse wheel changes page.

What went wrong?
Vertical scroll bar is visible and mouse wheel just scrolls a few pixels.

**Comment by Snuffleupagus** [comment] 2024-05-28 08:18
Effectively a duplicate of issue #7541.

**Closed by Snuffleupagus** 2024-05-28 08:18 UTC

**Comment by StephaneIFO** [comment] 2024-06-03 08:17
@Snuffleupagus : It's not the same bug
#7451 : problem with display of vertical scrollbar
#18177 : problem with mouse wheel not changing page

**Comment by guillaume-mueller** [comment] 2025-02-25 18:54
Completed ? Absolutely not.

This feature is so important to me that its absence is the number one reason I avoid reading PDFs in Firefox.

Have you ever tried Xreader on Linux Mint ? The requested feature is the default mode and behavior in it. Honestly when you try this, there's no coming back.
