### ISSUE TITLE
characters "ff" are not captured from return value of getTextContent()

### ISSUE THREAD

**Issue by warmice** [mozilla/pdf.js#11016] opened 2019-07-29 08:05 UTC
Attach (recommended) or Link to PDF file here:
[Sample3.pdf](https://github.com/mozilla/pdf.js/files/3440869/Sample3.pdf)

Configuration:
- Web browser and its version: not using browser
- Operating system and its version: MacOS 10.14.6 hosting a local nodejs server
- PDF.js version: pdfjs-dist@2.1.266
- Is a browser extension: no

Steps to reproduce the problem:
1. 
Run the following code snippet to print out the text to console.
The words such as "stuff", "offer" have the same issue that the "ff" is missing from the return value of the getTextContent() function, and become a weird character which cannot be compared or seen, which you can see the result from the screenshot below.
The code snippet is the following:
function getPDFText(data, callback, errorCallBack) {
    
    var loadingTask = pdfjsLib.getDocument(data);

    loadingTask.promise.then(function(pdf) {

        var maxPages = pdf._pdfInfo.numPages;
        var countPromises = []; // collecting all page promises

        for (var j = 1; j <= maxPages; j++) {

            var page = pdf.getPage(j);
    
            countPromises.push(page.then(function(page) { // add page promise
                var textContent = page.getTextContent();
                return textContent.then(function(text){ // return content promise
                    return text.items.map(function (s) { return s.str; }).join(''); // value page text 
                });
            }));
        }
        // Wait for all pages and join text
        Promise.all(countPromises).then(callback);
        
    }).catch(errorCallBack);
}

2.
What is the expected behavior? (add screenshot)
Expect to see the word "stuff" in the console.log, but instead only see "stu"

What went wrong? (add screenshot)
![textExtractedScreenShot](https://user-images.githubusercontent.com/4614570/62030279-a4880100-b199-11e9-9a16-d3bee5ce2703.jpeg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-07-29 08:18
This is a bug in the PDF file *itself* and not in the PDF.js library, which can also be reproduced in other viewers as well (e.g. Adobe Reader and PDFium in Google Chrome).
The problem is that the font in question contains incorrect data in the `Encoding` dictionary, which is why text-selection/copying doesn't work correctly.

**Comment by warmice** [comment] 2019-07-29 09:15
if that's the case, do you know any alternative workaround that i can use to extract the text from the PDF in this kind of scenario?

**Comment by warmice** [comment] 2019-07-29 17:57
> This is a bug in the PDF file _itself_ and not in the PDF.js library, which can also be reproduced in other viewers as well (e.g. Adobe Reader and PDFium in Google Chrome).
> The problem is that the font in question contains incorrect data in the `Encoding` dictionary, which is why text-selection/copying doesn't work correctly.

This is not corrected actually.
I opened it with the Preview application from Mac OS, and I did text-selection, it actually gives me the word "stuff" correctly. I did try it in Google Chrome, and it failed and gave me "stu".
But I think this justifies the point that it may not be a bug in the PDF file itself.

**Comment by Snuffleupagus** [comment] 2019-07-29 18:18
> This is not corrected actually.

Yes, it really is!
As already mentioned in https://github.com/mozilla/pdf.js/issues/11016#issuecomment-515893544, the `Encoding` dictionary has an incorrect entry.

> I opened it with the Preview application from Mac OS, and I did text-selection, it actually gives me the word "stuff" correctly.

*Generally speaking:* Just because you're able to find an example of a PDF viewer which has implemented a *work-around* to handle certain kinds of corrupt font data, that does *not* mean that the PDF file itself isn't the culprit.

> But I think this justifies the point that it may not be a bug in the PDF file itself.

No, it really *is* a bug in the PDF file itself (even if you don't agree). The fact that Adobe Reader, i.e. the PDF reference implementation, cannot handle this either is generally a quite good indication that the PDF file itself is corrupt.

**Comment by timvandermeij** [comment] 2019-07-29 20:21
Closing since I also don't see what we can do here. The PDF file itself is corrupt, and unless such a form of corruption happens very often, I don't see why we would need to work around this, if even possible.

**Closed by timvandermeij** 2019-07-29 20:21 UTC

**Comment by Snuffleupagus** [comment] 2019-07-30 10:52
> Closing since I also don't see what we can do here.

There's probably a fairly simple/cheap fix for this *particular* case, assuming tests pass of course, however these sort of hacks should obviously be done on a case-by-case basis only when real-world PDF examples can be provided.

**Comment by timvandermeij** [comment] 2019-07-31 21:34
Fixed by the pull request above.
