### ISSUE TITLE
PDF with a very tall document size doesn't render in its entirety

### ISSUE THREAD

**Issue by padenot** [mozilla/pdf.js#13038] opened 2021-03-01 17:17 UTC
Configuration:
- Web browser and its version: Firefox Nightly 88.0a1 (2021-02-27) (64-bit)
- Operating system and its version: macOS 10.14.6
- PDF.js version: Whatever is is this Fx Nightly
- Is a browser extension: yes

Steps to reproduce the problem:
1. Open https://dl.ubnt.com/qig/u6-lite
2. Scroll near the bottom of the document

What went wrong?

![Screenshot 2021-03-01 at 18 12 29](https://user-images.githubusercontent.com/270485/109533107-29e03f80-7aba-11eb-9312-23f48b841e9a.png)

Drawing doesn't work past a certain point. It's a single-page pdf with a very tall page.

**Comment by Snuffleupagus** [comment] 2021-03-01 17:22
Duplicate of #12957

**Closed** 2021-03-01 22:17 UTC
