### ISSUE TITLE
Printing Inconsistent Across Browsers

### ISSUE THREAD

**Issue by goodnowt** [mozilla/pdf.js#6060] opened 2015-05-28 20:06 UTC
Various inconsistent print errors occur across pdf.js in all browsers when we use it to print PDFs from our collections at Lafayette College’s Digital Scholarship Services.

We have tested printing in Chrome, Firefox, Safari, IE, and Opera in desktop environments. The four primary problems exhibited, which occur regardless of OS, are as such:

1) Inconsistent size of PDF pages on printed pages.  When printing in different browsers, such as Firefox and Chrome, PDF page will be printed at a different ratio to each printed page.  In addition, when printing from some browsers, white space will be printed before or after each PDF page.

2) Inconsistent page breaks between PDF pages when printed across browsers. For example, in Chrome, PDF pages will abut each other when printed, and printed page breaks will not occur between them, so that images will be broken across printed pages; whereas, in Firefox, a printed page break is correctly inserted between each PDF page.

3) In Chrome specifically, only a subset of pages, always starting from page 1, will be generated for print.  That is, if you were to print a 20+ page document, there will always be output less than 10 pages to print. There has been no discernible pattern to the number it will output.

4) In Safari specifically, it always hangs up while trying to output for print, and as such, I never even get to the browser’s print dialogue; I get stuck on PDF.js’s print generation dialogue. I have waited well over 10 minutes to see if it would ever resolve, and never seen it do so.

As can be seen from these myriad errors, pdf.js has proven to be very problematic for us in terms of printing.  Has anyone else experienced these errors?  Are there any known fixes?  I have yet to find any.

We do run a fork of pdf.js, but I have tested against the original source code as well as our fork, and both exhibit the same issues.  In addition, since we use it on our site as embedded within a larger page, I also tested against its behavior as “full-screen” in the browser versus within a larger page, and the behavior was the same.

Since we’re running a fork, I’ve also delved into the viewer.js to see if I could modify the print output to resolve issues, that was to no avail.  If I recall correctly, I was working around line 561, but it has been awhile and unfortunately am not 100% sure on that.  I do recall successfully modifying how it would output, but I was never able to fully resolve any of these inconsistency issues.  Plus, I would definitely put my JavaScript skills as intermediate, and only have so much time I can devote to it.

Moreover, I work a lot with CSS, and am rather well-versed in that area, so I worked extensively with it to try and resolve these issues. Unfortunately, I found the methodology for styling print output with pdf.js made the standards and methods I normally employ nigh impossible.  Essentially, I’ll normally use media queries to create print specific styling; however, since the print mark-up dynamically generated by pdf.js seems to be structured so differently from what is displayed in browser, and there is no way for me to visualize the structure of that print mark-up that is output, I have found myself at a loss as to how I could properly identify the elements I need to style in the print output via CSS.  I was curious as to why a technique that makes CSS styling so much more difficult was employed, and if it would not have been better to at least replicate the in-browser mark-up for the print output (for CSS purposes)?

**Comment by Rob--W** [comment] 2015-06-06 13:39
PDF.js's printing functionality is quite straightforward.

- In Firefox, the `mozPrintCallback` API is used to print. This API was designed for PDF.js, and allows PDF.js to render pages on the fly while printing. This gives PDF.js much control over the output, and it is also scalable (because unlike the next method, not every page needs to be held in memory).
- In other browsers, all other content in the document is hidden, each page is rendered in a separate `<canvas>` and the browser's print functionality is requested. From that point, we are left pretty much at the mercy of the browsers w.r.t printed result.  Historically, browsers have been terrible at sharing and giving control over the paper settings to web applications. The paged media CSS module (L3) specifies many improvements, but very few of them is actually implemented by browsers.

> 1) Inconsistent size of PDF pages on printed pages. When printing in different browsers, such as Firefox and Chrome, PDF page will be printed at a different ratio to each printed page. In addition, when printing from some browsers, white space will be printed before or after each PDF page.
> 2) Inconsistent page breaks between PDF pages when printed across browsers. For example, in Chrome, PDF pages will abut each other when printed, and printed page breaks will not occur between them, so that images will be broken across printed pages; whereas, in Firefox, a printed page break is correctly inserted between each PDF page.

Could you be a bit more specific: Which PDF.js commit did you try, which PDF files, which browser versions, what happens and what did you expect (screenshot / videos)?

> 3) In Chrome specifically, only a subset of pages, always starting from page 1, will be generated for print. That is, if you were to print a 20+ page document, there will always be output less than 10 pages to print. There has been no discernible pattern to the number it will output.

I just tried a 43-page paper, and Chrome printed all of them just fine.

> 4) In Safari specifically, it always hangs up while trying to output for print, and as such, I never even get to the browser’s print dialogue; I get stuck on PDF.js’s print generation dialogue. I have waited well over 10 minutes to see if it would ever resolve, and never seen it do so.

Which Safari version? How many pages? Does the console show any errors? Isn't Safari simply running out of memory?

> Moreover, I work a lot with CSS, and am rather well-versed in that area, so I worked extensively with it to try and resolve these issues. Unfortunately, I found the methodology for styling print output with pdf.js made the standards and methods I normally employ nigh impossible. Essentially, I’ll normally use media queries to create print specific styling. (...) I have found myself at a loss as to how I could properly identify the elements I need to style in the print output via CSS. I was curious as to why a technique that makes CSS styling so much more difficult was employed, and if it would not have been better to at least replicate the in-browser mark-up for the print output (for CSS purposes)?

PDFs are rendered on a `<canvas>`, so what's being printed is actually a kind of image, and these cannot be styled through CSS. You should stop thinking in terms of DOM elements if you want to fix printing, and instead start thinking in terms of paper size (and margins, etc.). The problem is not getting the PDF content on paper (because that mostly works fine), the problem is getting the paper to have a specific size (blank pages and cut-offs are just a symptom of this problem).

Instead of throwing all print issues that you find in a single post, try creating focused tickets, see https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md for instructions.
Also see the list of existing and fixed printing-related issue to get an idea of the current state of the printing functionality: https://github.com/mozilla/pdf.js/issues?q=label%3A4-printing

**Comment by timvandermeij** [comment] 2015-06-12 19:19
Closing as answered. Recently quite a few printing fixes landed and for example #6103 is also available now, so the problem is being worked on. If there are specific problems, please open one issue per problem and provide example documents.

**Closed by timvandermeij** 2015-06-12 19:19 UTC
Labels: 4-information-requested, 4-printing
