### ISSUE TITLE
Printing from PDF.js garbled characters - Unicode Boxes 

### ISSUE THREAD

**Issue by neatzsche** [mozilla/pdf.js#10437] opened 2019-01-09 15:34 UTC
Attach (recommended) or Link to PDF file here:
[Printed.pdf](https://github.com/mozilla/pdf.js/files/2741435/Printed.pdf)
[Original.pdf](https://github.com/mozilla/pdf.js/files/2741436/Original.pdf)

Configuration:
- Firefox 64.0 (64bit):
- Windows 8.1
- PDF.js version: 2.0.936
- No browser extensions enabled

Steps to reproduce the problem:
1. Open attached Original.pdf
2. Print it, either to PDF printer or physical printer

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/36679710/50909156-e49bb800-13f0-11e9-8b04-fae9f72df0aa.png)
The text should display as it does in the original. This works when printing to PDF or printing to a regular printer from Acrobat/Reader Tested 9, X and DC 17.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/36679710/50909203-faa97880-13f0-11e9-873a-1adc642dd610.png)
UTF-8 character boxes. You can check the whole of Printed.pdf or print it yourself. The same thing happens when printing to a physical printer.

![image](https://user-images.githubusercontent.com/36679710/50909433-70addf80-13f1-11e9-8d07-8b4ebdfa34f7.png)
This is the only error info in the log.

This pdf is generated by a website specifically to be printed. 

Turning on pdfjs.disableFontFace fixes this issue but breaks a lot of other PDFs.

**Comment by Snuffleupagus** [comment] 2019-01-26 10:53
Looks, for all intents and purposes, like a duplicate of #10414.

**Closed** 2019-01-26 14:52 UTC
Labels: 4-printing
