### ISSUE TITLE
Rendering issue...

### ISSUE THREAD

**Issue by dylanwoo** [mozilla/pdf.js#10806] opened 2019-05-10 13:39 UTC
This document(attached) won’t open with pdf.js.  In Firefox, 
[001 C0-0 - PROJECT INFORMATIONS.PDF](https://github.com/mozilla/pdf.js/files/3166679/001.C0-0.-.PROJECT.INFORMATIONS.PDF)
 error message:
PDF.js v2.0.943 (build: dc98bf76)
Message:
Stack: putBinaryImageData@https://www.thebluebook.com/globalassets/tools/pdf/build/pdf.js:10936:9
CanvasGraphics_paintInlineImageXObject@https://www.thebluebook.com/globalassets/tools/pdf/build/pdf.js:12181:9
CanvasGraphics_paintImageXObject@https://www.thebluebook.com/globalassets/tools/pdf/build/pdf.js:12140:7
CanvasGraphics_executeOperatorList@https://www.thebluebook.com/globalassets/tools/pdf/build/pdf.js:11165:11
InternalRenderTask__next/<@https://www.thebluebook.com/globalassets/tools/pdf/build/pdf.js:9648:35
InternalRenderTask__next@https://www.thebluebook.com/globalassets/tools/pdf/build/pdf.js:9644:14
InternalRenderTask__scheduleNext/<@https://www.thebluebook.com/globalassets/tools/pdf/build/pdf.js:9635:11
 
In Chrome, it just opens a blank page in the viewer. In both cases the documents are available for download and will successfully download and open with Adobe Reader.  

To ensure that my installation of pdf.js was not the issue I localized the file then tried to open directly in Firefox(native pdf.js) and got the same behavior.

**Comment by Snuffleupagus** [comment] 2019-05-10 13:41
Duplicate of #6741.

**Comment by dylanwoo** [comment] 2019-05-10 14:20
Thanks for catching the dupe Snuffle... do you know if there is something I can look at in using jquery to detect a blank canvas?

**Closed** 2019-05-10 21:02 UTC
