### ISSUE TITLE
Text selection causes unnecessary line breaks

### ISSUE THREAD

**Issue by gracile-fr** [mozilla/pdf.js#2569] opened 2013-01-15 19:14 UTC
PDFs created with "<a href="https://addons.mozilla.org/en-US/firefox/addon/print-pages-to-pdf/">Print Pages to Pdf</a>" addon based upon the opensource library <a href="https://github.com/antialize/wkhtmltopdf/">wkhtmltopdf </a> have an annoying issue when opened with pdf.js: if you copy and paste the textcontent of the PDF, each character is separated by a line break.

E.g.: With <a href="http://gracile-fr.github.com/misc/TheMozillaManifesto.pdf">this PDF</a>, if you copy and paste "The Mozilla Manifesto", you'll get:
T
h
e
M
o
z
i
l
l
a
M
a
n
i
f
e
s
t
o

**Comment by jasonparallel** [comment] 2015-06-02 17:41
@timvandermeij Does it still look like the current refactoring work will alleviate this issue?

**Comment by timvandermeij** [comment] 2015-06-02 17:50
@jasonparallel I'm afraid not. There are some PRs open for text layer alignment, but combining `div`s it not yet being looked into. If anyone is willing to do that, we welcome PRs anytime.

**Comment by rugk** [comment] 2015-11-16 21:02
Is this related to https://github.com/mozilla/pdf.js/issues/2989?
And was there any process made regarding this issue? because copy & pasting currently often works badly in pdf.js.

In any case here is another example: https://www.ietf.org/proceedings/82/slides/rtcweb-13.pdf
When copying the normal text everything works (expect that some characters like `{` and `` seem to be inserted in some places).
But when you copy a text which is displayed non-horizontally like the HTTPS (ROAP?) on site 6 you get many line breaks:
```
HTTPS
(R
OA
P?)
```

**Comment by yurydelendik** [comment] 2015-11-17 17:12
The origin PDF issue was fixed by #6590 (?). Rest of the problematic PDFs might have different problems -- the new issues shall be created for them. Closing as fixed.

**Closed by yurydelendik** 2015-11-17 17:12 UTC
Labels: 4-text-selection

**Comment by rugk** [comment] 2015-11-18 22:44
So the `HTTPS (ROAP?)` thing is fixed there?

And what about https://github.com/mozilla/pdf.js/issues/2989? Is this also closed by that PR?

And thirdly I've created a separate issue for the character problem: https://github.com/mozilla/pdf.js/issues/6658

**Comment by yurydelendik** [comment] 2015-11-18 22:53
> So the HTTPS (ROAP?) thing is fixed there?

No, it was not. The issue is closed once the reporter's issue is resolved.

> And what about #2989? Is this also closed by that PR?

The #2989 talks about using span elements vs div and/or using events to replace the clipboard.

> And thirdly I've created a separate issue for the character problem: #6658

Thank you.

**Comment by rugk** [comment] 2015-11-18 23:03
>> So the HTTPS (ROAP?) thing is fixed there?
>
> No, it was not. The issue is closed once the reporter's issue is resolved.

Okay, I've created a new issue for this: https://github.com/mozilla/pdf.js/issues/6659

**Comment by hfhchan** [comment] 2016-11-08 08:44
This affects nearly every single document I export from Word 2013.
