### ISSUE TITLE
Wishlist: Support DVJU in addition to PDF.

### ISSUE THREAD

**Issue by afarlie** [mozilla/pdf.js#12051] opened 2020-07-01 13:34 UTC
DJVU is a document storage structure , sometimes used in preference to PDF. in some applications , such as long term document storage for library archival purposes.

What is the support you want?:
The ability to view an manipulate DJVU files through the same interface as provided for PDF. 

The existing browser plugin listed at djvu.org  appears to be proprietary.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://djvu.sourceforge.net/

**Comment by Snuffleupagus** [comment] 2020-07-01 13:40
Duplicate of #6085

**Comment by afarlie** [comment] 2020-07-01 13:42
Closing as Duplicate...

**Closed** 2020-07-01 13:41 UTC
