### ISSUE TITLE
PDF.JS Dist is out of date

### ISSUE THREAD

**Issue by gamma** [mozilla/pdf.js#17532] opened 2024-01-18 11:05 UTC
It seems that the bot in https://github.com/mozilla/pdfjs-dist does not work anymore. There are no new releases of v4. I'm currently looking for the deployment of 4.0.379 using https://www.webjars.org

I can select the current version pdfjs-dist 4.0379 for deployment, but it never goes through.

Please check the bot or let us know if there is another way to deploy newer releases.

**Comment by Snuffleupagus** [comment] 2024-01-18 11:06
Duplicate of #17524

**Closed by Snuffleupagus** 2024-01-18 11:06 UTC
