### ISSUE TITLE
[Bug]: A extra white line shows up in background

### ISSUE THREAD

**Issue by ydwatibm** [mozilla/pdf.js#18660] opened 2024-08-28 14:18 UTC
### Attach (recommended) or Link to PDF file

[15666.pdf](https://github.com/user-attachments/files/16784565/15666.pdf)

### Web browser and its version

Chrome and Firefox

### Operating system and its version

Windows 11 version 23H2

### PDF.js version

pdf.js version 4.5.136

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1, open the attached pdf file with PDF.js viewer
2, scroll down to the bottom
3, there is a white line at the bottom (problem)

### What is the expected behavior?

1, open the attached pdf file with Adobe Acrobat 
2, there is no white line (what we expected)

### What went wrong?

![extra_white_line](https://github.com/user-attachments/assets/ac5707dd-5c5b-4826-b29b-106df4d63ca9)

**Comment by Snuffleupagus** [comment] 2024-08-28 14:26
Duplicate of #3351; note path-related explanation in https://github.com/mozilla/pdf.js/issues/3351#issuecomment-1112088508.

**Closed by Snuffleupagus** 2024-08-28 14:26 UTC
