### ISSUE TITLE
Pinch zoom doesn’t work on iPhone

### ISSUE THREAD

**Issue by amit777** [mozilla/pdf.js#12862] opened 2021-01-15 05:43 UTC
When testing out PDFjs on my iPhone at https://mozilla.github.io/pdf.js/web/viewer.html I can't seem to pinch to zoom. Is this a bug or expected?

**Comment by Snuffleupagus** [comment] 2021-01-15 09:50
Duplicate of #2582

**Closed** 2021-01-15 18:30 UTC
