### ISSUE TITLE
Error: Requesting object that isn't resolved yet on PDF even with disableFontFace

### ISSUE THREAD

**Issue by RafaPolit** [mozilla/pdf.js#9675] opened 2018-04-18 22:59 UTC
Failing PDF:
[15240917076692yt54e2iickoemgikbw486w29.pdf](https://github.com/mozilla/pdf.js/files/1926035/15240917076692yt54e2iickoemgikbw486w29.pdf)

Configuration:
- Version: **node v6.9.5**
- Operating system and its version: **Ubuntu 16.04LTS**

- PDF.js version: **2.0.0**

Steps to reproduce the problem:
1. Run the demo code found in https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js
2. Console outputs:
```
# PDF document loaded.
(node:1211) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Requesting object that isn't resolved yet Verdana_path_C
```

What is the expected behavior? 

**A successful conversion**

What went wrong?

```
# PDF document loaded.
(node:1211) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Requesting object that isn't resolved yet Verdana_path_C
```
This is happening even though the disableFontFace: true flag has been set, which seems wrong.

Thanks for any insight.  Best regards,
Rafa.

**Comment by RafaPolit** [comment] 2018-04-20 20:15
I believe that the error can be caught (instead of an UnhandledPromiseRejection) replacing the **_scheduleNext** function in https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L2452 with a catch.

What is causing the error is less clear at this point.

```
  _scheduleNext: function InternalRenderTask__scheduleNext() {
      if (this.useRequestAnimationFrame && typeof window !== 'undefined') {
        window.requestAnimationFrame(this._nextBound);
      } else {
        Promise.resolve(undefined).then(this._nextBound).catch(err => { this.callback(err); } );
      }
    }
```

**Comment by timvandermeij** [comment] 2018-05-29 21:37
Not yet. We've been busy with other pull requests first, but I do agree that the error handling should at least be improved here. The cause of the underlying issue is not yet clear.

**Comment by Snuffleupagus** [comment] 2018-06-04 13:15
> The cause of the underlying issue is not yet clear.

This is simply (another) duplicate of issue #4244, and should probably be closed as such.

(Also, it seems to me if a work-around is implemented, it really needs to apply *generally* and not only for a part of the problem. Hence the proposed PR does *not* strike me as a good solution.)

**Comment by diego-lipinski-de-castro** [comment] 2018-06-04 14:48
#4244 has been there for 4 years, AND THERE IS STILL NOT SOLUTION PROVIDED

**Comment by RafaPolit** [comment] 2018-06-11 17:05
Could the error handling be dealt with, even if the underlying cause is yet undetermined?  The underlying fix would be important to have a better overall experience, but the error handling is critical to have a working environment.

I think the PR I submitted could be merged without introducing any side effects or detrimental behaviors.  Please take a look at it, as it is crucial for us at this point moving forward.

Thanks, best regards,
Rafa.

**Comment by Snuffleupagus** [comment] 2018-06-11 18:58
> even if the underlying cause is yet undetermined?

Please see https://github.com/mozilla/pdf.js/issues/9675#issuecomment-394350263, and in particular issue #4244 that it refers to.

> I think the PR I submitted could be merged without introducing any side effects or detrimental behaviors.

It would cause a difference in behaviour depending on which of the [two code-paths](https://github.com/mozilla/pdf.js/blob/0e0fa489dd7aaa59fcae159501f5485aafac6a5c/src/display/api.js#L2457-L2461) are being used (canvas rendering vs operatorList fetching), which doesn't strike me as a particularly great situation.

**Comment by timvandermeij** [comment] 2018-06-16 15:57
The error handling is improved by #9689 and #9809. The underlying issue is a duplicate of #4244, so I'm closing this one.

**Closed by timvandermeij** 2018-06-16 15:57 UTC
Labels: 1-other, 4-node-specific

**Comment by gustawdaniel** [comment] 2020-06-11 18:29
But I have this error in my project.

I was using this file as example:

https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js

**Comment by guilherme-francisco** [comment] 2024-07-23 16:32
I am having this error with : 
page.objs.get(images[0]).then(object => {console.log(object)});
