### ISSUE TITLE
Text not rendering

### ISSUE THREAD

**Issue by johnhok** [mozilla/pdf.js#11737] opened 2020-03-23 16:38 UTC
Attach (recommended) or Link to PDF file here:
[font-issue.pdf](https://github.com/mozilla/pdf.js/files/4370677/font-issue.pdf)

Configuration:
- Web browser and its version: Firefox 74.0 (64-bit)
- Operating system and its version: macOS 10.15.2 (19C57)
- PDF.js version: 2.0.0
- Is a browser extension: No

Steps to reproduce the problem:
1. Open and view the PDF

What is the expected behavior?
![Screen Shot 2020-03-23 at 12 25 15 PM](https://user-images.githubusercontent.com/1030271/77339689-8d86b800-6d02-11ea-80ae-1b91984e45b3.png)

What went wrong?
![Screen Shot 2020-03-23 at 12 25 18 PM](https://user-images.githubusercontent.com/1030271/77339711-94adc600-6d02-11ea-9a76-079926fe7ea6.png)

Additional details:
I looked into the issue from the problematic PDF and it seems to be related to the embedded font. When I run the embedded font through `ttx` this is the result.
![Screen Shot 2020-03-23 at 12 35 11 PM](https://user-images.githubusercontent.com/1030271/77339886-d9d1f800-6d02-11ea-8713-e8715f44bcaf.png)

It seems other PDF viewers are able to recover from this problem somehow but in pdf.js, it fails to render some characters.

**Comment by janpe2** [comment] 2020-03-30 12:39
Glyph offsets are not sorted, so some glyphs get a negative length.

```
'loca' Table - Index To Location Table
--------------------------------------
Size = 264 bytes, 66 entries
	Idx   0 -> glyfOff 0x00002A9A* No contours *
	Idx   1 -> glyfOff 0x00002A9A* No contours *
	Idx   2 -> glyfOff 0x00002A9A* No contours *
	Idx   3 -> glyfOff 0x00002A9A
	Idx   4 -> glyfOff 0x00002A5C
	Idx   5 -> glyfOff 0x00000FA4
	Idx   6 -> glyfOff 0x00000D22
	...
```
For example, subtracting `0x00000FA4 - 0x00002A5C` gives a negative length.

PDF.js tries to fix the problematic glyphs in [fonts.js](https://github.com/mozilla/pdf.js/blob/c12ea21c14478df9a4f4bc10a078d902c174a6d6/src/core/fonts.js#L2020-L2058) but the result is that they are marked as having a length of 0, so they won't draw anything on the page.

**Comment by Snuffleupagus** [comment] 2020-03-30 13:05
Based on https://github.com/mozilla/pdf.js/issues/11737#issuecomment-605974605, this looks like a duplicate of #11131.

**Closed** 2020-03-30 21:41 UTC
Labels: 4-font-conversion

**Comment by jurijBass** [comment] 2020-04-28 13:35
Hi,
is this issue being resolved or is there any workaround=
