### ISSUE TITLE
build fails in IE

### ISSUE THREAD

**Issue by steventill** [mozilla/pdf.js#13236] opened 2021-04-13 20:10 UTC
there are => in /build/es5/pdf.worker.min.js
this is es5 there should not be any arrow functions in es5 files.  this breaks my IE 11 compatibility.

**Comment by timvandermeij** [comment] 2021-04-13 20:13
Duplicate of #12906, see https://github.com/mozilla/pdf.js/issues/12906#issuecomment-766990763 in particular. IE 11 is now explicitly unsupported.

**Closed by timvandermeij** 2021-04-13 20:13 UTC
