### ISSUE TITLE
FreeText does not support Chinese content

### ISSUE THREAD

**Issue by heyong3235** [mozilla/pdf.js#18173] opened 2024-05-27 00:22 UTC
When Chinese annotations entered using FreeText in PDF.js are exported to a PDF file, the PDF, when opened in Edge or Chrome browsers, does not display the Chinese annotations. However, they are displayed normally when opened in a PDF reader client. The content of FreeText in English or numbers is not affected; it seems that only the Chinese content is not supported. Research has found that the issue may be caused by a failure in encoding the FreeText content with the font used in the createNewAppearanceStream method. How can I add support for Chinese language fonts, or how can I improve this?

**Comment by Snuffleupagus** [comment] 2024-05-27 05:22
This is likely a duplicate of e.g. issue #15769, however given that you completely ignored the entire ISSUE_TEMPLATE it's difficult to know.

**Closed by Snuffleupagus** 2024-05-27 05:22 UTC
Labels: information-requested
