### ISSUE TITLE
PDF file corrupeted in Firefox download

### ISSUE THREAD

**Issue by jonathan0211** [mozilla/pdf.js#8988] opened 2017-10-02 16:48 UTC
Link to PDF file (or attach file here):
[document(4).pdf](https://github.com/mozilla/pdf.js/files/1349620/document.4.pdf)
Configuration:
- Web browser and its version: Firefox 55.0.2 (64-bit)
- Operating system and its version: Ubuntu 14.04 LTS

What is the expected behavior?
[expected.pdf](https://github.com/mozilla/pdf.js/files/1349633/expected.pdf)

What went wrong?
I am developing a system that generates a report in pdf, using prawn library in Ruby on Rails with charts generated by highcharts, the result is sent to front end buit in Angular. When I use Chrome, the result is ok (pdf with expected behavior is linked in this issue), but when I open with Firefox it's ok in preview, but when I download the file it became corrupted (first link in this issue).

**Comment by yurydelendik** [comment] 2017-10-02 16:56
Both files produce error in Adobe Reader for me.

**Comment by yurydelendik** [comment] 2017-10-02 17:09
Though, both viewable in Chrome/Firefox/Preview/Reader. Please provide more details on why if document.4.pdf is corrupted and expected.pdf is not.

**Comment by jonathan0211** [comment] 2017-10-02 17:16
Both are generated by the same code, the expected result is in expected.pdf

**Comment by jonathan0211** [comment] 2017-10-02 17:20
Sorry, I've downloaded expected.pdf in google chrome and the other one in Firefox, and I uploaded here, but the content are the same apparently, but when I use Firefox to download the content become wrong.

**Comment by yurydelendik** [comment] 2017-10-02 17:21
<img width="1308" alt="screen shot 2017-10-02 at 12 20 38 pm" src="https://user-images.githubusercontent.com/1523410/31090119-27d0ac36-a76c-11e7-874d-fcae012f9e40.png">

I still do not understand how can I tell if PDF corrupted or not?

**Comment by yurydelendik** [comment] 2017-10-02 17:22
(both files downloaded by Firefox) Are you using the Firefox extension that might corrupt the download?

**Comment by jonathan0211** [comment] 2017-10-02 17:25
This is a screen shot from this pdf downloaded by firefox 
![screen](https://user-images.githubusercontent.com/7417383/31090176-242e4e60-a77d-11e7-86f8-883c7b0ed5a5.png) and thats the expected result, from chrome pdf viewer
![scree2](https://user-images.githubusercontent.com/7417383/31090286-86bd2d12-a77d-11e7-8653-70bad63885a7.png)

**Comment by yurydelendik** [comment] 2017-10-02 17:28
Yes, the same you see with expected.pdf file in the Adobe Reader. Was this file downloaded by Firefox as well?

**Comment by yurydelendik** [comment] 2017-10-02 17:36
Looks like the issue is invalid. The Firefox and Chrome downloaded files shows the same corruption. It probably prawn library that generates the corrupted PDF. Notice the Firefox, Chrome and Preview can display these files, Adobe Reader and Evince (?) cannot. Closing.

**Closed by yurydelendik** 2017-10-02 17:36 UTC
Labels: 4-information-requested
