### ISSUE TITLE
[Bug] unable to view pdf file in iPhone xs with ios 15

### ISSUE THREAD

**Issue by sthukral82** [mozilla/pdf.js#16345] opened 2023-04-25 09:50 UTC
Attach (recommended) or Link to PDF file here: https://www.antennahouse.com/hubfs/xsl-fo-sample/pdf/basic-link-1.pdf

Configuration:
- Web browser and its version: Safari
- Operating system and its version: iPhone xs with ios 15
- PDF.js version: 3.5.141
- Is a browser extension: No

Steps to reproduce the problem:
I was using pdfjs-dist v3.2.146 in my Reactjs application. After updating the version of package to 3.5.141. it stops working in iPhone XS having ios 15 in it. Now the issue is that while reading pdf file using **getDocument** it is giving an error saying **Transfering of ArrayBuffer cannot be polyfilled in this engine**

```
const loadingTask = pdfjs.getDocument({ url: url })
loadingTask.then((result) => {
    console.log(result);
}).catch((error) => {
    console.error(
          'error when loading pdf from url',
           error,
    );
});
```

What is the expected behavior? (add screenshot)
it should show the pdf file

What went wrong? (add screenshot)
unable to read pdf file
![Screenshot from 2023-04-21 23-08-51](https://user-images.githubusercontent.com/50482955/234239200-2b903c5d-aac2-4ff5-abce-4cee06aa46f9.png)

**Comment by Snuffleupagus** [comment] 2023-04-25 09:56
Duplicate of #16255

**Closed by Snuffleupagus** 2023-04-25 09:56 UTC
