### ISSUE TITLE
I cant import PDFThumbnailViewer 

### ISSUE THREAD

**Issue by ademyalcin27** [mozilla/pdf.js#17695] opened 2024-02-19 15:17 UTC
Im trying to create custom pdf viewer I couldnt import PDFThumbnailViewer. 

I can only import as below, but Im getting error because there is only types. 

```
import { PDFThumbnailViewer } from "pdfjs-dist/types/web/pdf_thumbnail_viewer";

```

Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version: ^3.11.174
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
<img width="684" alt="Screenshot 2024-02-19 at 16 16 08" src="https://github.com/mozilla/pdf.js/assets/5026172/da4e6799-96fc-45b3-a2e9-3e655a006227">

![Screenshot 2024-02-19 at 16 16 34](https://github.com/mozilla/pdf.js/assets/5026172/2f8ca079-3b27-4cf8-a3db-6f61c96c6a3a)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2024-02-19 15:20
Duplicate of #15176

**Closed by Snuffleupagus** 2024-02-19 15:20 UTC
