### ISSUE TITLE
PDF file shows blank page, no warnings in console

### ISSUE THREAD

**Issue by intgr** [mozilla/pdf.js#8694] opened 2017-07-24 09:11 UTC
Link to PDF file (or attach file here): https://media.washingtonpost.com/wp-srv/politics/documents/Assessment_Redacted_092109.pdf?hpid=topnews

Configuration:
- Web browser and its version: Firefox Developer Edition (55.0b10)
- Operating system and its version: macOS Sierra 10.12.6
- PDF.js version: 1.8.439 (Firefox built-in)
- Is an extension: No

What went wrong? (add screenshot)

PDF.js displays an empty frame with no content at all. However, PDF.js correctly displays the PDF metadata and page count.

This PDF was apparently created with: 1.6 CPY Document Producer / Adobe Acrobat 8.1 Combine Files

<img width="903" alt="screen shot 2017-07-24 at 12 09 36" src="https://user-images.githubusercontent.com/137616/28516211-135856a8-7069-11e7-852d-6fd959db9b42.png">

**Comment by timvandermeij** [comment] 2017-07-24 20:32
I cannot reproduce this on Arch Linux with Firefox 54.0.1 (64 bits) and the most recent PDF.js development version. All 66 pages render perfectly fine for me. Could you download the file and open it with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar), to see if it's perhaps fixed in the most recent PDF.js version (I use 1.8.571 as of writing)?

**Comment by intgr** [comment] 2017-07-25 09:02
I can confirm that the newer version successfully loads this PDF. Will Firefox 55 stable release be updated to include this newer PDF.js version?

**Comment by timvandermeij** [comment] 2017-07-25 20:03
The fix will be included in a later Firefox version indeed. I don't think it will make it to version 55, but I think version 56 may include it. Closing since this is fixed.

**Closed by timvandermeij** 2017-07-25 20:03 UTC
Labels: 4-information-requested

**Comment by Snuffleupagus** [comment] 2017-07-25 21:11
> The fix will be included in a later Firefox version indeed. I don't think it will make it to version 55, but I think version 56 may include it. Closing since this is fixed.

I've just tested this in Firefox DevEdition 55.0b12 (32-bit) on Windows, using the built-in version of PDF.js (which is still at `1.8.439`), and I cannot reproduce the issue there.
