### ISSUE TITLE
Printing in IE

### ISSUE THREAD

**Issue by jctodd** [mozilla/pdf.js#5714] opened 2015-02-09 17:34 UTC
I'm experiencing an issue with IE (all versions) and printing.  When the user prints the document, the pages start halfway down the paper.  This has been replicated across multiple computers and IE versions.

**Comment by timvandermeij** [comment] 2015-02-09 22:17
Most likely a duplicate of #3983. Closing as such until more information is provided (screenshots especially).

**Closed by timvandermeij** 2015-02-09 22:17 UTC
