### ISSUE TITLE
whether i need to change pdf.js and pdf.worker.js code to support word-searching?

### ISSUE THREAD

**Issue by sunweiconfidence** [mozilla/pdf.js#11005] opened 2019-07-24 03:17 UTC
Configuration:
- Chrome 75.0.3770.142
- Windows 10:
- PDF.js 2.0.943:

Steps to reproduce the problem:
1. Navigate to https://mozilla.github.io/pdf.js/web/viewer.html
2 Type "CTRL+F" to open the find dialog
3 Type "like eat apple". 

What is the expected behavior? (add screenshot)
The search result will only contains "like eat apple" can be searched .
but in the pdf.js 1.7.225, The search result will list all contains "like" or "eat" or "apple" or "like eat apple"

What went wrong?
whether i need to change pdf.js and pdf.worker.js code to support word search like pdf.js 1.7.225 version's effect, or i only change to call PDFFindController.executeCommand with phraseSearch: false set in the state object like below:
 dispatchEvent(type, findPrev) { 
   this.eventBus.dispatch('find', { 
     source: this, 
     type, 
     query: this.findField.value, 
     phraseSearch: true, 
     caseSensitive: this.caseSensitive.checked, 
     entireWord: this.entireWord.checked, 
     highlightAll: this.highlightAll.checked, 
     findPrevious: findPrev, 
   }); 
 }

**Comment by Snuffleupagus** [comment] 2019-07-24 06:47
Duplicate of #11002; please refrain from knowingly open duplicate issues!

**Comment by timvandermeij** [comment] 2019-07-24 21:02
Indeed, and the solution is outlined over there.

**Closed by timvandermeij** 2019-07-24 21:02 UTC
