### ISSUE TITLE
Internal links in PDF link to incorrect pages

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#8468] opened 2017-05-31 22:33 UTC
Link to PDF file (or attach file here): 
[Sample File (2).pdf](https://github.com/mozilla/pdf.js/files/1043098/Sample.File.2.pdf)

Configuration:
- Web browser and its version: Latest Chrome 58.0.3029.110 / Firefox 53.0.3
- Operating system and its version: Mac OSX El Capitan
- PDF.js version: Latest available on https://mozilla.github.io/pdf.js/web/viewer.html (currently 1.8.408)
- Is an extension: No

Steps to reproduce the problem:
1. Open sample file in demo pdf.js viewer
2. Click any of links on the side, e.g. 'Risk Management'
3. Notice that you are redirected to the page after 'Risk Management'
4. Same happens for other links

What is the expected behavior? (add screenshot)
Clicking on link directs to correct page (confirmed this works in Chrome PDFium and Adobe Reader)

What went wrong? (add screenshot)
Clicking on link directs to page after correct one

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by Snuffleupagus** [comment] 2017-05-31 22:37
Closing as duplicate of issue #7154.

**Closed by Snuffleupagus** 2017-05-31 22:37 UTC
