### ISSUE TITLE
Out of flow elements

### ISSUE THREAD

**Issue by darylteo** [mozilla/pdf.js#9136] opened 2017-11-15 12:05 UTC
Attach (recommended) or Link to PDF file here:

https://www.listcorp.com/asx/mnf/mnf-group-limited/news/2017-ceos-agm-presentation-1732903.pdf

Configuration:
- Web browser and its version: any
- Operating system and its version: any
- PDF.js version: any
- Is a browser extension: no

Steps to reproduce the problem:
1. open pdf
2. drag text selection from first page across to second page
3. footer page number is not selected or is selected out of flow

What is the expected behavior? (add screenshot)

I understand this has much to do with the pdf standard. Just wondering if there was a reason why we could just simply do an insertion sort on the div nodes when rendering the text layer so that they are ordered by their top then left position? If there was prior discussion about this I apologise - I only found the discussion pertaining to improving text selection but nothing seems to have been resolved there beyond just expanding the div dimensions. 

I also note that Chrome's in built viewer also presents this symptom, so it may simply be a matter of consistency regarding the pdf standard, in which case I do understand.

At this point, I'm planning to do a hack involving the reordering of text nodes after rendering, to get more consistent text selection results.

Kind Regards,
Daryl

**Comment by Snuffleupagus** [comment] 2017-11-15 13:32
> Just wondering if there was a reason why we could just simply do an insertion sort on the div nodes when rendering the text layer so that they are ordered by their top then left position?

Please keep in mind that PDF files can contain text in languages using e.g. right-to-left or top-to-bottom reading order. Hence doing what you're suggesting would most likely (significantly) regress text-selection in anything but left-to-right text, and it might not even work too well there in the general case.

> I also note that Chrome's in built viewer also presents this symptom, so it may simply be a matter of consistency regarding the pdf standard, in which case I do understand.

I even get the same behaviour in Adobe Reader, and as you suspect this is caused by the PDF file *itself* since it specifies the text in that particular order.

Closing as answered, since this isn't something that we can (generally) fix.

**Closed by Snuffleupagus** 2017-11-15 13:32 UTC

**Comment by darylteo** [comment] 2017-11-15 22:23
Thanks for taking the time to reply!
