### ISSUE TITLE
Certain links (e.g. `textedit://...`) missing from renders

### ISSUE THREAD

**Issue by lhl2617** [mozilla/pdf.js#13374] opened 2021-05-13 11:14 UTC
Attach (recommended) or Link to PDF file here
[test (1).pdf](https://github.com/mozilla/pdf.js/files/6472040/test.1.pdf)

Configuration:
- [Online example](https://mozilla.github.io/pdf.js/web/viewer.html)

Steps to reproduce the problem:
1. Upload and view the attached PDF
2. Links on the note heads are missing, but the link in the footer 

What is the expected behavior? (add screenshot)

Links on the note heads are shown (From Adobe Acrobat)

![image](https://user-images.githubusercontent.com/33488131/118118114-672f4a80-b3e4-11eb-9d51-ff14eb299e1d.png)

What went wrong? (add screenshot)

Links on noteheads are missing.

**Comment by timvandermeij** [comment] 2021-05-13 11:21
The `textedit` protocol is not allowed by https://github.com/mozilla/pdf.js/blob/d9d626a5e16cb3662c188bd2f12cb8584360c86a/src/shared/util.js#L397-L412, which most likely explains this problem. Only whitelisted protocols are allowed for links for security reasons (and the `textedit` protocol also seems specific to one particular piece of software), especially since this tries to open local files.

**Comment by Snuffleupagus** [comment] 2021-05-13 11:22
Please note that we only "standard" protocols when creating/validating URLs, please refer to https://github.com/mozilla/pdf.js/blob/ba99e54c66c33562a7d88f1d230d7bc4d02bbadb/src/shared/util.js#L397-L434

This looks, for all intents and purposes, like a duplicate of e.g. issue #10057

**Closed by timvandermeij** 2021-05-13 11:21 UTC
