### ISSUE TITLE
Make easier page link sharing in updating url on new page

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#12852] opened 2021-01-11 18:55 UTC
Use the default file at https://mozilla.github.io/pdf.js/web/viewer.html.
Then go to page 7 for example, if I want to share this page url, I need to manually append `#page=7` to the url.
An idea could to append page number automatically to the url each time a page is rendered.

**Comment by Snuffleupagus** [comment] 2021-01-11 19:16
This functionality has existed basically since "forever", note the `viewBookmark` at the right-hand side of the toolbar which will append/update the hash corresponding to the current position:

![viewBookmark](https://user-images.githubusercontent.com/2692120/104227388-9a1efd00-5449-11eb-90fb-02cfc7d95bfd.png)

> An idea could to append page number automatically to the url each time a page is rendered.

There's a preference that will enable that behaviour, see `historyUpdateUrl`, however it can end up "fighting" with the `PDFHistory`-implementation which is why we do *not* want to enable that by default.

**Comment by timvandermeij** [comment] 2021-01-11 19:43
Closing since this works as intended as described above.

**Closed by timvandermeij** 2021-01-11 19:43 UTC
