### ISSUE TITLE
UX improvements proposal for the PDF viewer

### ISSUE THREAD

**Issue by madjoe** [mozilla/pdf.js#13901] opened 2021-08-17 14:31 UTC
Brief summary:

1. better naming within the settings
2. keep consistency within the settings

Details:

1. **no spreads**, **odd spreads** and **even spreads** should be way more intuitive (it is just not accurate this way): I would suggest to separate it in two settings (single page, double page) and if "double page" is selected, there should be a checkbox "even page on the left" (if unchecked, it will start with odd page on the left)
2. if I choose the current "odd spreads" and switch to the presentation mode, I am presented with a full screen and "no spreads" will enforced, which I didn't want - I expected the "odd spreads" setting will be followed even in the presentation mode, which didn't happen

**Comment by Snuffleupagus** [comment] 2021-08-17 17:05
>     1. **no spreads**, **odd spreads** and **even spreads** should be way more intuitive (it is just not accurate this way): I would suggest to separate it in two settings (single page, double page) and if "double page" is selected, there should be a checkbox "even page on the left" (if unchecked, it will start with odd page on the left)

Regardless of what exact names we choose to use, it's unfortunately going to be impossible to come up with something that satisfies all users and use-cases.
Also, using e.g. "single page" could be even *more* confusing since there can still be more than one page visible at once depending on e.g. zoom level (and similar with "double page").
Furthermore, having check-boxes in the SecondaryToolbar probably wouldn't look all that good or fit in very well.

All-in-all, this part of the issue seem (as far as I can tell) to be mostly a duplicate of #9813. However, please note that for the reasons outlined above it's quite likely that it'll be closed as WONTFIX (and the current UI has now existed for over three years).

>     2\. if I choose the current "odd spreads" and switch to the presentation mode, I am presented with a full screen and "no spreads" will enforced, which I didn't want - I expected the "odd spreads" setting will be followed even in the presentation mode, which didn't happen

That's essentially by design, since the purpose of PresentationMode has always been to be as simple as absolutely possible.
Furthermore, you can always use the fullscreen-mode of the browser itself (usually toggled with <kbd>F11</kbd>) to utilize the entire screen.

(Note also that *if* spreadMode-support had existed in PresentationMode it wouldn't be possible to change it without going back to the regular viewer first, which doesn't seem like a great UX.)

---

Given the link to a third-party implementation above, i.e. https://github.com/troyeguo/koodo-reader/issues/186, please note that it'd obviously be possible for them to change the viewer to implement these feature *there*; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Closed by Snuffleupagus** 2021-08-17 17:05 UTC

**Comment by madjoe** [comment] 2021-08-18 00:31
> Regardless of what exact names we choose to use, it's unfortunately going to be impossible to come up with something that satisfies all users and use-cases.

True, but that's not a valid reason not to improve. It's not about binary logic (_all_ or _none_), it's always about how to find the peak of that normal distribution and find the optimum result. Currently, the naming is just not cutting it imo.

> Also, using e.g. "single page" could be even _more_ confusing since there can still be more than one page visible at once depending on e.g. zoom level (and similar with "double page").

I was referring to how `Okular` does it. It uses way more intuitive `View mode` with the following options:

- Single page
- Facing pages
- Facing pages (Center First Page)
- Overview

> Furthermore, having check-boxes in the SecondaryToolbar probably wouldn't look all that good or fit in very well.

Checkbox was just a suggestion. I just noticed `Okular` did it surprisingly simpler by adding the "Center First Page" as a separate option, which diminishes a need for mentioning cumbersome `odd` vs `even` whatsoever.

> All-in-all, this part of the issue seem (as far as I can tell) to be mostly a duplicate of #9813. However, please note that for the reasons outlined above it's quite likely that it'll be closed as WONTFIX (and the current UI has now existed for over three years).

I agree, it is somewhat related to the existing issue. The fact it exists for 3 years is also not a valid argument it should stay like that.

> That's essentially by design, since the purpose of PresentationMode has always been to be as simple as absolutely possible.
> Furthermore, you can always use the fullscreen-mode of the browser itself (usually toggled with F11) to utilize the entire screen.

I was more thinking of providing options to choose usefulness rather than forcing "simplicity": pages are usually displayed in portrait and sometimes there may be graphics that spreads from the left page all the way to the end of the right page and it may be useful to show both pages at the same time during the presentation. F11 is currently not possible in `koodoo-reader` as a wrapper of `pdf.js`, but I will discuss this elsewhere.

> (Note also that _if_ spreadMode-support had existed in PresentationMode it wouldn't be possible to change it without going back to the regular viewer first, which doesn't seem like a great UX.)

I disagree. Since a user would deliberately click that view option, it would be intuitive to go out from the presentation mode with `Esc` to reach the menu (if needed). But in future releases even that option could be simplified with a ribbon menu, in case a user pushes the mouse pointer all the way to the top in the presentation mode.

> Given the link to a third-party implementation above, i.e. [troyeguo/koodo-reader#186](https://github.com/troyeguo/koodo-reader/issues/186), please note that it'd obviously be possible for them to change the viewer to implement these feature _there_; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine): ...

Noted, thanks. I'll check it with them.
