### ISSUE TITLE
can click the "previous page" at page 1 and go random page.

### ISSUE THREAD

**Issue by Einere** [mozilla/pdf.js#8999] opened 2017-10-06 15:34 UTC
Attach (reccomened) or Link to PDF file here:
[[선대]01.pdf](https://github.com/mozilla/pdf.js/files/1363166/01.pdf)

Configuration:
- Web browser and its version: firefox
- Operating system and its version: ubunt 16.04
- PDF.js version: i don't know how to find it...
- Is an extension: 

Steps to reproduce the problem:
1. open the pdf by pdf.js (now page is 1)
2. representation mode
3. mouse right click, i can click the "go to previous page"
4. repeat 3, go to random page (maybe)

What is the expected behavior? (add screenshot)
non click "go to previous page" 
What went wrong? (add screenshot)
![2017-10-07](https://user-images.githubusercontent.com/8300010/31285635-d0716dde-aaf6-11e7-8a2e-97f14299967d.png)
i can click the "go to previous page"

![2017-10-07 1](https://user-images.githubusercontent.com/8300010/31285637-d21e497c-aaf6-11e7-8fd9-57da3d0800b4.png)
after click, went page 3.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-10-06 16:13
The context menu button shown (highlighted) in your screen-shot is related to the history navigation of the browser itself, and cannot be disabled from a web page/app (which is what PDF.js is).

It's not possible to completely prevent history navigation in the browser from a regular web page, but it can be made slightly more difficult with the use of a [`beforeunload`](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload) event listener. However, one known problem with that particular event listener is that it disables caching, and can also cause problems when closing the browser (see https://bugzilla.mozilla.org/show_bug.cgi?id=1336763).
For all of the reasons above, we do *not* want to use `beforeunload` and hence we cannot prevent that button from working in presentation mode.

Closing, since this works as intended.

**Closed by Snuffleupagus** 2017-10-06 16:13 UTC

**Comment by Einere** [comment] 2017-10-07 05:08
thank for friendly explain!!
