### ISSUE TITLE
Some character is shown with incorrect orientation in vertical text

### ISSUE THREAD

**Issue by t-matsuu** [mozilla/pdf.js#13080] opened 2021-03-11 03:19 UTC
Attach (recommended) or Link to PDF file here:
https://www.mext.go.jp/content/20210222-mxt-hojinka-000012970_2.pdf

Configuration:
- Web browser and its version: Firefox Nightly 88.0a1 20210310215846
- Operating system and its version: Windows 10 x64
- PDF.js version: 2.8.188

Steps to reproduce the problem:
1. View the PDF file https://www.mext.go.jp/content/20210222-mxt-hojinka-000012970_2.pdf

What is the expected behavior? (add screenshot)
 U+3001, U+3002, U+FF08, and U+FF09 characters show with correct orientation in vertical text.

What went wrong? (add screenshot)
 U+3001, U+3002, U+FF08, and U+FF09 characters show with incorrect orientation in vertical text.

Screenshot available at BMO [Bug 1695816](https://bugzilla.mozilla.org/show_bug.cgi?id=1695816).
(Originally reported for PDF.js 2.8.117. But reproduced on 2.8.118)

**Comment by tamuratak** [comment] 2021-03-11 09:46
It seems to be duplicate of #12350.

**Closed** 2021-03-12 19:55 UTC
