### ISSUE TITLE
(Feature request) Denoting PDF pagination artifacts (i.e. page headers and footers) in HTML output

### ISSUE THREAD

**Issue by provpup** [mozilla/pdf.js#13857] opened 2021-08-03 17:18 UTC
Hello,

I am looking to use pdf.js to capture text selections a user makes in a PDF document.  If the user were to make a text selection spanning multiple pages, and if the pages have a header or footer, then the header/footer text is also selected.  Is there a way to add some ARIA role or equivalent markup to the rendered `span` elements for the header and footer so that my code can ignore them when computing the user's text selection?

According to Table 330 in Section 14.8.2.2.2 of the PDF spec: https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf (page 575), page headers and footers are specified using `/Artifact propertyList`, and from this code https://github.com/mozilla/pdf.js/blob/master/web/struct_tree_layer_builder.js, it looks to assign an ARIA role given a PDF element.

Thanks!

**Comment by Snuffleupagus** [comment] 2021-08-03 17:55
Please attach example PDF documents that can be used to reproduce this, since the issue doesn't seem easily actionable otherwise.
(When opening an issue, please remember to provide *all* of the information requested in the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md).)

@brendandahl Is this perhaps something that you'd want to implement as a follow-up/improvement to PR #13171?

**Comment by Snuffleupagus** [comment] 2021-11-13 13:15
> Please attach example PDF documents that can be used to reproduce this, since the issue doesn't seem easily actionable otherwise.

Given that no such PDF documents have been provided thus far, closing as INCOMPLETE for now.

**Closed by Snuffleupagus** 2021-11-13 13:15 UTC
Labels: 1-core, 2-feature
