### ISSUE TITLE
Pdf Text and logo hided or showed incorrectly in light grey after desabling textlayer color transparent setting.

### ISSUE THREAD

**Issue by jameliddin** [mozilla/pdf.js#9497] opened 2018-02-20 11:22 UTC
Attach (recommended) or Link to PDF file here:
[MissingLogoAndText.pdf](https://github.com/mozilla/pdf.js/files/1739847/MissingLogoAndText.pdf)

Configuration:
- Web browser and its version: IE 11.125.16299.0 / firefox 58.0.2 64
- Operating system and its version:Win 10
- PDF.js version: 1.8.188 + 1.10.88
- Is a browser extension: either directly with pdf.js from firefox or embedded in a web app.

Steps to reproduce the problem:
1. Upload the pdf with pdf version 1.7
2. Display with pdf.js

What is the expected behavior? (add screenshot)
Show the right logo and the text
![image](https://user-images.githubusercontent.com/36662495/36421395-8fcf0f90-1638-11e8-9a1a-7fe7432d9f20.png)

What went wrong? (add screenshot)
Logo was transformed in some kind of ascii place holder and only few letters from the whole text are displayed
![image](https://user-images.githubusercontent.com/36662495/36421414-a919526c-1638-11e8-86ba-95e7ab528ae1.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by jameliddin** [comment] 2018-02-20 12:46
Addendum: here are the custom fonts used for this document:
![image](https://user-images.githubusercontent.com/36662495/36424597-2053cc62-1644-11e8-9f1f-99f8b05bf09d.png)
The document is readable without troubles in Acrobat XI 11.0.23 and PDF-XChange 6.0

Thx a lot in advance for any helpful hints.

**Comment by Snuffleupagus** [comment] 2018-02-28 09:05
> Attach (recommended) or Link to PDF file here:
> MissingLogoAndText.pdf

It appears that the provided PDF file contains nothing more than an *image* of the problem.
In order for this issue to be actionable, you must provide the actual PDF file where the issue was encountered.

> PDF.js version: 1.8.188 + 1.10.88

Is this issue reproducible in the *latest* version of PDF.js, which can always be found at https://mozilla.github.io/pdf.js/web/viewer.html (use the "Open file" button on toolbar to open your file)?

**Comment by jameliddin** [comment] 2018-02-28 13:26
Hi there,

the document is a high confidential encrypted customer document and I cannot provide it anywhere unfortunately, sorry. The issue isr reproducible, even with the latest release, that I already took for testing bevor opening this issue.

There are no troubles at all neither with Acrobat Reader X nor  PDF-XChange nor with Chrome; the rendering is correct. Only with pdf.js, almost the whole ascii content is kept hidden, cause of an activated transparency property, that when desabled in the inspection popup shows the content in light grey. Only few somehow random letters are displayed in bold black and the logo itself is changed through an ascii place holder.

"Virtual printing" with PDF24 ends also with the following error

![image](https://user-images.githubusercontent.com/36662495/36789772-fb9460ee-1c92-11e8-80f2-a5ac74d3d6bb.png)

due to a ghoscript ps transformation problem 8as an additional hint).

**Comment by Snuffleupagus** [comment] 2018-02-28 13:56
> the document is a high confidential encrypted customer document and I cannot provide it anywhere unfortunately, sorry.

In that case we'll unfortunately have to close this issue as incomplete, since it's simply impossible to help without access to a test-case. My suggestion would be to, if possible, try and generate a PDF document with "dummy" content (which can be freely shared) using the same PDF creation software.

> [...] cause of an activated transparency property, that when desabled in the inspection popup shows the content in light grey.

Note that this is the text-layer, which is used only to allow text-selection and searching, but has nothing to do with the actual rendering of the PDF file itself (which is done using HTML `<canvas>` elements).

**Closed by Snuffleupagus** 2018-02-28 13:56 UTC
Labels: 4-font-conversion, 4-information-requested

**Comment by jameliddin** [comment] 2018-02-28 15:13
Well this is a very unusual, uncommon and strange way nowadays to "solve" problems and fix real existing bugs.

1. For the lgiht grey text its ok, but how and why and under what kind of circumstances a graphic component is replaced through ascii place holder?

2. Why and how are some letters randomly picked up and showed in bold black.

Have you at least an idea about these effects and at least which part of the code is relevant for both cases so I can at least keep on investigating on my own.

Thx in advance.

**Comment by THausherr** [comment] 2018-03-02 14:10
@jameliddin PDF is a very complex format. I work in a different PDF project (Apache PDFBox) and most of the time we can't fix problems without having the PDF. And when we got it, most of the time the cause of the problem wasn't the first guess. It's like when your pet is sick, you'll have to bring it to the vet despite 1) you thinking that the symptoms are obvious 2) the pet hating to go to the vet.

I suggest you open the file in the tools mentioned in https://github.com/mozilla/pdf.js/wiki/Debugging-PDF.js or Apache PDFBox PDFDebugger or itext RUPS to look for any weird things or any log messages.

**Comment by jameliddin** [comment] 2018-03-02 14:57
Great thx. I know its much easier to have the original material but as Ive mentionedit  bevor its a highly confidential encrypted bank document and am not allowed to make it public.

Anyways I'll give it a try with your suggestion and we'll see.

Greetings.

**Comment by georgezouq** [comment] 2021-09-07 09:35
same problem. did you fix this? @jameliddin
