### ISSUE TITLE
Horizontal scrollbar is coming when pdf is zoomed to 400%. The content need to reflow to accomodate in the viewport instead of horizontal scrollbar

### ISSUE THREAD

**Issue by karthikchakravarthy** [mozilla/pdf.js#16015] opened 2023-02-06 12:33 UTC
Attach (recommended) or Link to PDF file here: 

Configuration:
- Web browser and its version: chrome
- Operating system and its version: MAC OS
- PDF.js version: latest
- Is a browser extension: No

Steps to reproduce the problem:
1. Open https://mozilla.github.io/pdf.js/web/viewer.html. It opens with a default pdf.
2.Go to browser(chrome) menu and increase the zoom to 400%. Horizontal scroll is coming instead of content adapting/reflowing to the viewport.

What is the expected behavior? (add screenshot)
The content should reflow such that there is no horizontal scroll bar. There should be only vertical scroll bar. Similar to liquid mode in adobe acrobat reader.
![IMG_6C105DCC14C6-1](https://user-images.githubusercontent.com/21312471/216971762-8990a3f5-39e2-4b23-b867-698a425b2a5d.jpeg)

What went wrong? (add screenshot)
On zooming to 400% there are two scroll bars horizontal and vertical. There should be only vertical scroll bar instead and content in the pdf should reflow to accomodate in viewport.
![400% zoom](https://user-images.githubusercontent.com/21312471/216970763-cea828da-9dbf-4aad-91d8-8f9e222177c3.png)

Link to a viewer : https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2023-02-06 12:45
If you *explicitly* choose a percentage zoom value that's large enough that the document doesn't fit horizontally, then showing a scrollbar is the *correct/expected behaviour* since we can't very well just ignore the users choice here.

Most likely you want the "page-width" zoom-mode instead, which will always fit the document width to the available window width; closing as answered (or possibly even INVALID).

**Closed by Snuffleupagus** 2023-02-06 12:45 UTC

**Comment by calixteman** [comment] 2023-02-06 12:54
As far as I can tell, the first screenshot above comes from the Acrobat Reader app which is using the `liquid` mode to render the pdf. As far as I understand this `liquid` mode, the text and its structure (i.e. lines, paragraphs, columns, ...) is extracted from the pdf and then rendered in using usual layout (images are extracted either and inserted in the text flow).

**Comment by Snuffleupagus** [comment] 2023-02-06 13:01
> As far as I can tell, the first screenshot above comes from the Acrobat Reader app which is using the `liquid` mode to render the pdf. As far as I understand this `liquid` mode, the text and its structure (i.e. lines, paragraphs, columns, ...) is extracted from the pdf and then rendered in using usual layout (images are extracted either and inserted in the text flow).

Given that essentially everything in PDF documents, including text, is *absolutely positioned* such a thing almost sounds like it's "violating" the PDF specification itself by no longer respecting the actual document layout. (Since the whole point of the format is that documents should always look the same, regardless of e.g. the OS and viewer used.)

Hence that really sounds like WONTFIX, as far as I'm concerned.

**Comment by karthikchakravarthy** [comment] 2023-02-06 13:03
Is there any mode in pdf js which reflow the content atleast if pdf contains only paragraphs when zoom in to 400% instead of giving a horizontal scroll. So that it is easy for the reader to read in the perspective of accessibility.

**Comment by Snuffleupagus** [comment] 2023-02-06 13:12
> Is there any mode in pdf js which reflow the content [...]

No, since that's not really how PDF documents work internally; see https://github.com/mozilla/pdf.js/issues/16015#issuecomment-1419043116

**Comment by Snuffleupagus** [comment] 2023-02-06 13:21
> It could be something similar to the `reader view` mode in Firefox:

In that case, we could just call this a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1703168

**Comment by karthikchakravarthy** [comment] 2023-06-25 09:12
Hi,
     Just for confirmation as this information is not available anywhere in the internet.
How extent does PDF JS support PDF/UA standard regarding accessibility ? As of now the pdf js has support for tagged PDFs to support screen readers but there is no text reflow support even if the pdf is tagged( or PDF/UA supported) right ?
    Currently text reflow is supported by Abode Acrobat Reader Pro even in desktop. Open a file in Adobe reader -> zoom to any percentage like 400% then click "view" -> zoom -> reflow. Text reflows in the document.
<img width="1792" alt="Screenshot 2023-06-25 at 2 40 15 PM" src="https://github.com/mozilla/pdf.js/assets/21312471/0d80e265-10a0-4b93-868a-64bcc0450963">
