### ISSUE TITLE
Enter key does not work in page number field in IE 10/11

### ISSUE THREAD

**Issue by Thunderforge** [mozilla/pdf.js#6260] opened 2015-07-23 16:34 UTC
The viewer.js page number field allows the user to type in a desired page number. When the user is finished typing, they can either tab out of the field or press the enter key and the viewer will jump to the page that the user typed in, if valid.

On Chrome and Firefox, both the tab key and the enter key work. On Internet Explorer, only the tab key works. The enter key works in the [W3Schools demo](http://www.w3schools.com/htmL/tryit.asp?filename=tryhtml_input_number) for a number-formatted text field, so something in either viewer.js or viewer.css seems to be preventing the enter key from working when it normally would.

To reproduce:

 1. Go to the [PDF.js demo](http://mozilla.github.io/pdf.js/web/viewer.html) in IE 10 or 11
 2. Click on the page number field or use the tab key to get over to there.
 3. Type in a valid page number other than the one that the user is currently on
 4. Press the "Enter" key and note that nothing happens (it does in Chrome and Firefox)
 5. Press the "Tab" key and note that the page changes to the desired page

**Comment by Snuffleupagus** [comment] 2015-07-23 17:33
Closing as duplicate of issue #4551.

**Closed by Snuffleupagus** 2015-07-23 17:33 UTC
