### ISSUE TITLE
Font of selected text changes, in Kansas bill PDF, depending on whether window has focus

### ISSUE THREAD

**Issue by dholbert** [mozilla/pdf.js#4303] opened 2014-02-16 21:54 UTC
STR:
1. Visit http://www.kslegislature.org/li/b2013_14/measures/documents/hb2453_01_0000.pdf
2. Select some text (e.g. a section of Line 1)
3. Focus a different window (e.g. with Alt-Tab), but make sure you can still see the Firefox window.

ACTUAL RESULTS: When you focus a different window, the selected text changes font, for no apparent reason.

EXPECTED RESULTS: No font change.

I reproduced this in Firefox Nightly 30.0a1 (2014-02-16) with the latest pdf.js extension from http://mozilla.github.com/pdf.js/extensions/firefox/pdf.js.xpi

**Comment by timvandermeij** [comment] 2015-05-14 18:33
I cannot reproduce this anymore with Firefox 37.0.2 while I have seen this before. It appears to have been fixed upstream. Closing as fixed.

**Closed by timvandermeij** 2015-05-14 18:33 UTC
Labels: 4-text-selection

**Comment by dholbert** [comment] 2015-05-14 18:58
Yup, works for me too. (The highlight-region text also seems to be a much lighter color when Firefox isn't in the foreground now.)
