### ISSUE TITLE
PDF contents turns redacted (blackout) upon zoom-out to thumbnail size.

### ISSUE THREAD

**Issue by dhanbhan** [mozilla/pdf.js#14521] opened 2022-02-01 10:32 UTC
Attach (recommended) or Link to PDF file here:

Sample Document : 
[Sample_blackout.pdf](https://github.com/mozilla/pdf.js/files/7977687/Sample_blackout.pdf)

Configuration:
- Web browser and its version: Chrome, Firefox, MS Edge (latest versions)
- Operating system and its version: Windows, Mac
- PDF.js version: 2.12.313 (latest)
- Is a browser extension: NA

Steps to reproduce the problem:
1. Open attached `Sample_blackout.pdf` in pdfjs viewer
2. Zoom out the document to lesser than 30% or verify the content in thumbnail view
3. You will notice portion of the document content are turned black.

What is the expected behavior? : Document content should not change its style in thumbs view or while zoom out. 

What went wrong? : document content are turned black and even some portions are redacted.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

**Output in pdfjs viewer on zoom out :** 

<img width="241" alt="blackedOutResponse" src="https://user-images.githubusercontent.com/86353329/151952833-bdf359ab-3f55-4afb-afc5-cc4636a87971.png">

**Comment by Snuffleupagus** [comment] 2022-02-01 13:17
I wonder if this is *effectively* a duplicate of e.g. issue #13211.

**Comment by Btow01** [comment] 2022-02-04 16:46
[Sample_blackout.pdf](https://github.com/mozilla/pdf.js/files/8004767/Sample_blackout.pdf)


I have attached the file that we were able to recreate the issue with

**Closed** 2022-03-02 17:46 UTC
Labels: core
