### ISSUE TITLE
Document scramble and words are missing issue using pdf.js

### ISSUE THREAD

**Issue by brajesh081** [mozilla/pdf.js#15707] opened 2022-11-18 12:41 UTC
Attach (recommended) or Link to PDF file here:
[doc_blur_pdf.pdf](https://github.com/mozilla/pdf.js/files/10041262/doc_blur_pdf.pdf)

The words of the pdf are getting scrambled and missing using pdf.js. 
We are unable to use the pdf.js to read the the pdf.
Can you debug the issue on priority. 

Configuration:
- Web browser and its version:  107.0.5304.107(Chrome) && 107.0.1418.42(IE)
- Operating system and its version: Windows 11 Pro 22H2, OS Build - 22621.819
- PDF.js version: 2.14.305
- Is a browser extension: no
- Intel UHD graphics version: 31.0.101.3616

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/72693907/202705919-d9d3a81a-3f5d-4a18-ac0a-d7b3d4428776.png)

What went wrong?  (add screenshot) 
![doc_blur_issue](https://user-images.githubusercontent.com/72693907/202705601-84fe0451-205b-4e5b-84c3-b881b102c980.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-11-18 12:44
> PDF.js version: 2.14.305

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

Duplicate of #14641

**Closed by Snuffleupagus** 2022-11-18 12:44 UTC
