### ISSUE TITLE
Garbled text in PDF viewer

### ISSUE THREAD

**Issue by sumit-piq** [mozilla/pdf.js#15911] opened 2023-01-10 12:33 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: **Chrome (107.0.5304.122)**
- Operating system and its version: **Windows 10**
- PDF.js version: **2.5.207**
- Is a browser extension: **No**

Steps to reproduce the problem:
1. Load a pdf file with standard pdf contents or scanned images in the chrome browser
2. See the broken or missing character in the viewer

What is the expected behavior? (add screenshot)
The Text in UI must be as close as the Image. The image is part of the invoice.
<img width="528" alt="Screenshot 2023-01-10 at 6 21 30 PM" src="https://user-images.githubusercontent.com/97018709/211556804-ba612e03-eefa-41ef-889a-3b5089946380.png">

What went wrong? (add screenshot)
The **text is garbled** after rendering it in pdfjs
<img width="694" alt="Screenshot 2023-01-10 at 4 15 37 PM" src="https://user-images.githubusercontent.com/97018709/211551578-18c96910-cf1e-46a8-900d-f5b0a6e04862.png">

**Note:** The same pdf is getting loaded correctly in Chrome on Mac machines and other windows versions.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Can't mention the link here due to security reasons.

**Comment by Snuffleupagus** [comment] 2023-01-10 13:18
> Attach (recommended) or Link to PDF file here:

This part is *always required* in order for any issue to be actionable/valid.

> Web browser and its version: **Chrome (107.0.5304.122)**

This is probably a duplicate of e.g. issue #14641.

> PDF.js version: **2.5.207**

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Closed by Snuffleupagus** 2023-01-10 13:18 UTC

**Comment by devalberg** [comment] 2023-01-31 12:04
If there's any help, I've commented on a possible work around on this here:

https://github.com/mozilla/pdf.js/issues/14641#issuecomment-1398471525

2 others have found it a success 🙂

**Comment by devalberg** [comment] 2023-01-31 12:05
@sumit-piq - If there's any help, I've commented on a possible work around on this here:

https://github.com/mozilla/pdf.js/issues/14641#issuecomment-1398471525

2 others have found it a success 🙂
