### ISSUE TITLE
Image in PDF shows up as a black box

### ISSUE THREAD

**Issue by johnhok** [mozilla/pdf.js#12213] opened 2020-08-14 13:58 UTC
Attach (recommended) or Link to PDF file here:
[pdf-jpg-black.pdf](https://github.com/mozilla/pdf.js/files/5074949/pdf-jpg-black.pdf)

Configuration:
- Web browser and its version: Chrome 84.0.4147.125 (Official Build) (64-bit)
- Operating system and its version: OSX 10.15.6 (19G73)
- PDF.js version: PDF.js: 2.6.248
- Is a browser extension: no

Steps to reproduce the problem:
1. Open PDF in PDF.js

What is the expected behavior? (add screenshot)
<img width="1003" alt="Screen Shot 2020-08-14 at 9 56 17 AM" src="https://user-images.githubusercontent.com/1030271/90257036-9d6b7980-de14-11ea-9d2c-0511aba156c4.png">

What went wrong? (add screenshot)
<img width="808" alt="Screen Shot 2020-08-14 at 9 55 52 AM" src="https://user-images.githubusercontent.com/1030271/90257043-a0ff0080-de14-11ea-88b6-c871905fb92e.png">

**Comment by THausherr** [comment] 2020-08-17 11:34
This is a JPX image with an indexed colorspace with 4 bits per component. This file has the same problem (page 11, bottom right)
https://issues.apache.org/jira/secure/attachment/12655396/PDFBOX-2204-012411.pdf

This file
https://flh.fhwa.dot.gov/resources/design/pddm/Chapter_05A.pdf
has a similar image on the bottom of page 10, also JPX and indexed, but has 8 bits per component and is displayed. So I guess it's the usual bpc=4 that produces the problem.

**Comment by asimowski** [comment] 2021-06-04 17:54
We have the same problem.  Any workaround or solution?

Sample:
2 JPX images on left. 
[JPXimageprobem.pdf](https://github.com/mozilla/pdf.js/files/6600376/JPXimageprobem.pdf)

**Comment by THausherr** [comment] 2021-06-04 18:42
That one has 3 images with 4 bits per component. Of these, 2 are JPX images with DeviceGray colorspace and these don't get rendered.

**Comment by justinjdickow** [comment] 2021-06-07 18:59
@THausherr Do you happen to have a recommendation for a workaround for this issue?

**Comment by THausherr** [comment] 2021-06-07 19:05
I'm not with this project, I just hang around here and analyzed the file. If you created the file, then avoid creating 4 bit images.

**Comment by justinjdickow** [comment] 2021-06-07 20:52
FYI this issue was fixed for us by opening the PDF in Preview on MacOS > file > export... and choosing to export as "PDF/A".

**Comment by quaoaris** [comment] 2022-01-05 21:58
This seems to be a dupe of https://github.com/mozilla/pdf.js/issues/4648

**Closed** 2024-04-16 12:04 UTC
Labels: image-jpx
