### ISSUE TITLE
Images are not displayed propely in IE

### ISSUE THREAD

**Issue by gsampath127** [mozilla/pdf.js#7378] opened 2016-06-01 11:51 UTC
Can you please provide any workaround can be done for this or let us know the root cause of issue.

Link to PDF file (or attach file here):
1. http://hosted-stage.rightprospectus.com/Wasatch/Fund.aspx?cu=936772201&dt=SAR
2.http://hosted-stage.rightprospectus.com/documents/Wasatch/SEMI_Wasatch.pdf

Configuration:

    Web browser and its version: Internet Explorer , version:11
    Operating system and its version:Windows7
    PDF.js version:1.1.469
    Is an extension:

Steps to reproduce the problem:
1. Go to the given links with PDFJs Viewer both in Chrome and IE.
2.Compare the first page in IE with Chrome.
3.We can find the the picture on the front cover is not displayed properly.

What is the expected behavior? (add screenshot)
![chromewas](https://cloud.githubusercontent.com/assets/12858790/15708594/ef71d4f2-281c-11e6-8544-eba458edf2fc.png)

What went wrong? (add screenshot)
![iewas](https://cloud.githubusercontent.com/assets/12858790/15708602/fa6c0eea-281c-11e6-841e-65047778f3c1.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):http://hosted-stage.rightprospectus.com/Wasatch/Fund.aspx?cu=936772201&dt=SAR

PDF Document:
[SEMI_Wasatch.pdf](https://github.com/mozilla/pdf.js/files/293313/SEMI_Wasatch.pdf)

**Comment by Snuffleupagus** [comment] 2016-06-01 12:02
Closing as duplicate of issue #7375; which in itself is a duplicate of issue #5264.

Please take a moment to read through issue #5264 carefully, and you will see that this is caused by Internet Explorer not supporting Blend Modes. This is a limitation of the browser, and not something that we can fix!
Given that Blend Modes are not something that can be easily poly-filled, it should come as no surprise that the simple workarounds posted in various issues doesn't really work.

*For future reference, please __do not__ open multiple issues for the same PDF file!*

**Comment by gsampath127** [comment] 2016-06-01 12:02
Have logged the same for #7375 ,  verified the codes for Issues #5264 , #3900 this didn't help us.

**Closed by Snuffleupagus** 2016-06-01 12:02 UTC

**Comment by gsampath127** [comment] 2016-06-01 12:12
Thanks a lot !!
 Here are some questions from my side.
1. Can we recreate the pdf so that it did not break with this issue ?
2.If we can do the above and how it can be achievable ?
3.Reason why **this pdf** is breaking in IE ? (Is something wrong with PDF)

**Comment by yurydelendik** [comment] 2016-06-01 12:31
Hi @gsampath127 . I'm not sure you are reading the referenced bugs.

> 1. Can we recreate the pdf so that it did not break with this issue ?

Use tools to optimize PDF for web and performance. See https://helpx.adobe.com/acrobat/using/optimizing-pdfs-acrobat-pro.html (see Transparency options?)

> 2.If we can do the above and how it can be achievable ?

See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-types-of-pdf-files-are-slow-in-pdfjs-can-i-optimize-a-pdf-file-to-make-pdfjs-faster

Or you can polyfill blend mode functionality for HTML5 canvas for IE9,10,11. It works for IE Edge.

> 3.Reason why this pdf is breaking in IE ? (Is something wrong with PDF)

See conversation above -- IE11 and below does not support blending modes and was addressed by IE team is IE Edge.

See also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-browsers-are-supported
