### ISSUE TITLE
Cannot set fixed width (and height) on the pageviewer example

### ISSUE THREAD

**Issue by handhikadj** [mozilla/pdf.js#13989] opened 2021-09-08 16:32 UTC
Attach (recommended) or Link to PDF file here: it's on the example

Configuration:
- Web browser and its version: Chrome 93
- Operating system and its version: Mac M1
- PDF.js version: 2.9.359
- Is a browser extension: no

Steps to reproduce the problem:
1. set the width (and height) in `style` property of `<div id="pageContainer" class="pdfViewer singlePageView"></div>`
2. Go to: http://localhost:8888/examples/components/pageviewer.html

What is the expected behavior? (add screenshot)
Can set fixed width and height

What went wrong? (add screenshot)
Cannot set it

![image](https://user-images.githubusercontent.com/22522638/132548459-575c4417-7100-48c1-b452-6d9e175ef92f.png)

Notice the canvas and textLayer width and height don't get set

**Comment by Snuffleupagus** [comment] 2021-09-08 16:55
> set the width (and height) in `style` property of `<div id="pageContainer" class="pdfViewer singlePageView"></div>`

Sorry, but it's not expected to work like that since the `scale` (in the `pageviewer.js` file) is what controls the final size of the `canvas`.
To work-around that, you'll need to modify the `scale` accordingly to enforce a particular width or height; please see the "Alternatively, if you want the canvas to render to a certain pixel size you could do the following:"-part of the example at https://mozilla.github.io/pdf.js/examples/index.html#rendering-the-page

Closing as answered (or possibly a duplicate of e.g. issue #5628).

**Closed by Snuffleupagus** 2021-09-08 16:55 UTC
