### ISSUE TITLE
First page is mixed with the last page

### ISSUE THREAD

**Issue by TyDraniu** [mozilla/pdf.js#9462] opened 2018-02-08 11:48 UTC
Could you take a look on this file. The first page is mixed with the last page.

[cb7e7bd2362328f37fe97dc8dff151a3.pdf](https://github.com/mozilla/pdf.js/files/1706865/cb7e7bd2362328f37fe97dc8dff151a3.pdf)

Configuration:
- Firefox Nightly 60
- Windows 7

**Comment by Snuffleupagus** [comment] 2018-02-08 11:51
Closing as duplicate of issue #269.

**Closed by Snuffleupagus** 2018-02-08 11:51 UTC
