### ISSUE TITLE
Highlighting obscures text in IE11

### ISSUE THREAD

**Issue by ryanpf** [mozilla/pdf.js#6202] opened 2015-07-13 16:17 UTC
The highlighted text is being covered by the yellow highlighting. Works as expected in chrome, tested in v1.1.288 and v1.1.3. (https://mozilla.github.io/pdf.js/web/viewer.html)

File: (https://drive.google.com/file/d/0B6xJdPUaaUwZaXBONExUbExKcUE/view?usp=sharing)

![image](https://cloud.githubusercontent.com/assets/2955908/8654381/89ce0052-294f-11e5-986f-3818d5ee0bd2.png)

**Comment by Snuffleupagus** [comment] 2015-07-14 08:02
This might be a duplicate of issue #5264.

**Comment by Snuffleupagus** [comment] 2016-01-26 14:06
Closing as duplicate of issue #5264.

**Closed by Snuffleupagus** 2016-01-26 14:06 UTC
Labels: 4-ie11-specific
