### ISSUE TITLE
Basic functions guide/tutorial

### ISSUE THREAD

**Issue by fedyd** [mozilla/pdf.js#8133] opened 2017-03-06 15:14 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: FF, IE11, Chrome
- Operating system and its version: Windows 7 x64
- PDF.js version:  1.6.210-dist
- Is an extension:

Maybe not the right place where to ask this, I  don't know. 
Anyway I am another one who is trying to build from scratch a minimalist viewer: I would just need zoom, pan and actual page number/overall pages number.
I am able to set the initial zoom so that the pdf is shown as I want at the beginning. 
I can't find anywhere how I should do if I want to resize the pdf document or if I want to zoom it in and out:
should I reload the document and re-render? Should I only re-render it (as, if I haven't misunderstood, the pdf file once loaded, should be already available) with a new scale? Is there a less computation option than the 2 above? 
I tried the first one (calling the PDFJS.getDocument() on resize) but it is really consuming and sometimes I get a bad rendering.
Is there a reference for this and for pan somewhere? Thank you for your help and I apologize if this is the wrong place where to ask.

**Comment by yurydelendik** [comment] 2017-03-06 15:39
> I tried the first one (calling the PDFJS.getDocument() on resize) but it is really consuming and sometimes I get a bad rendering.

You don't need to call getDocument for every time you render a page. Really bad rendering is probably caused by using the same canvas for multiple renderings.

See [simple viewer](https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.html) and [mobile viewer](https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer) examples. Building a custom viewer is complex task, so we recommend to take demo viewer or one of the examples and modify for your own needs. Closing the issue as answered.

**Closed by yurydelendik** 2017-03-06 15:39 UTC

**Comment by fedyd** [comment] 2017-03-06 16:46
Thank you Yury. Before posting I took a look at the viewer you suggest, but I couldn't see (or maybe understand) if all the controls I need are there. I will try to see them again. I also firstly tried the approach of using the web viewer (also because I would like to have the scrollbar to move between pages) but it has too many elements to manage. For example I "disabled" the 2 sidebars setting their display property to hidden in the css file and then moving, in the html file, the pan button on the main toolbar, but then the pan didn't work...is there no guide even on how to customize the viewers? Thank you anyway. Best regards, Federico

**Comment by yurydelendik** [comment] 2017-03-06 17:03
> For example I "disabled" the 2 sidebars setting their display property to hidden in the css file and then moving, in the html file, the pan button on the main toolbar, but then the pan didn't work...is there no guide even on how to customize the viewers?

I don't know. "Hidding scrollbars" in HTML requires some JavaScript coding and does not sound trivial AFAIK. But adding a button to the toolbar easier (~10-20 lines of code) shall work.

There is no simple answers how to customize the viewer. Simple changes in HTML/CSS shall suffice most of the requirements in customization, e.g. changing theme, disabling button, switching PDF.js flags, etc.  Adding/changing functionality (such as an extra button, two-page view, pinch zoom support) might require more than average experience with JS/HTML/CSS, so there is nothing basic about it.

**Comment by fedyd** [comment] 2017-03-06 17:32
Ok!
