### ISSUE TITLE
Display a list of embedded document fonts

### ISSUE THREAD

**Issue by DragoonAethis** [mozilla/pdf.js#15591] opened 2022-10-18 19:15 UTC
In some PDF viewers it is possible to display some PDF metadata and a list of embedded fonts. For example, on [this PDF](https://sre.google/static/pdf/building_secure_and_reliable_systems.pdf), [Evince](https://apps.gnome.org/app/org.gnome.Evince/) can show you:

![image](https://user-images.githubusercontent.com/1546665/196519596-06b7fce9-15e4-4159-924d-0ed732201f85.png)

It would be great if PDF.js could list the embedded font list as well. Trying to right-click -> Inspect -> Fonts tab in DevTools does not show the actual font with which the document is rendered - for example in the PDF linked above, page 41, inspecting the code snippet should list "Ubuntu Mono", but the DevTools tab lists the default monospace font configured in the browser.

Configuration: Firefox 106.0 on Arch Linux (2022-10-18), embedded pdf.js.

**Comment by Snuffleupagus** [comment] 2022-10-18 19:54
Duplicate of #9199

**Closed by Snuffleupagus** 2022-10-18 19:54 UTC
