### ISSUE TITLE
Arabic characters clipped in Chrome on MacOS

### ISSUE THREAD

**Issue by MKR-e-boks** [mozilla/pdf.js#15607] opened 2022-10-21 09:07 UTC
PDF files for reproducing the issue:
[Characters-clipped.pdf](https://github.com/mozilla/pdf.js/files/9837350/Characters-clipped.pdf)
[Characters-rendered-correctly.pdf](https://github.com/mozilla/pdf.js/files/9837351/Characters-rendered-correctly.pdf)

Configuration:
- Web browser and its version: Chrome 106.0.5249.61
- Operating system and its version: MacOS Monterey 12.5.1
- PDF.js version: At the moment of writing this, it reports "PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 3.0.246 [7dc16c237])" in the Developer console of Chrome and the latest release on the pdf.js download page is 2.16.105.
- Is a browser extension: No

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/legacy/web/viewer.html in the latest Chrome (106.0.5249.61) on MacOS (Monterey)
2. Open the attached pdf (Characters-clipped.pdf)

What is the expected behavior?
All characters are shown without being clipped.
![image](https://user-images.githubusercontent.com/116341626/197153437-fd91c69d-b3ec-41cb-820b-ffd96c5ea6d3.png)
This screenshot is produced from using Characters-rendered-correctly.pdf

What went wrong?
Characters are clipped both horizontally and vertically. A few of the examples of this is circled in red in the following screenshot.
![image](https://user-images.githubusercontent.com/116341626/197155932-a2db0fd7-2b6f-4046-a7e5-81ccae43e737.png)

A few notes:
The latest Chrome on the latest MacOS provided by BrowserStack is used to do the test.

The font is different in the version of the PDF that is working fine from the version that has the errors, so it is maybe related to this.

The issue is seen both on the legacy and the "modern" version.

The issue looks similar to what is reported in 
https://bugzilla.mozilla.org/show_bug.cgi?id=1756855
and
https://github.com/mozilla/pdf.js/issues/14941
so it could have something to do with variable weight fonts.

**Comment by Snuffleupagus** [comment] 2022-10-21 09:11
Duplicate of #14941

**Closed by Snuffleupagus** 2022-10-21 09:11 UTC
