### ISSUE TITLE
Please add two pages view in pdfviewer

### ISSUE THREAD

**Issue by NitishRawat123** [mozilla/pdf.js#16052] opened 2023-02-13 05:44 UTC
Configuration:
- Web browser and its version:Version 110.0b9 (64-bit)
- Operating system and its version: Windows 10 Pro
- PDF.js version:
- Is a browser extension:No

Steps to reproduce the problem:
1. It shows only a single page but I want it to be a two page view like a book
![Screenshot (1)](https://user-images.githubusercontent.com/30903764/218379838-6b2d591d-1d21-439e-aecd-e481ab6ae5c1.png)

2. It should look as if we see pages of pdf in form of  book with two pages to be seen.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-02-13 08:52
Duplicate of #590, which was implemented in PR #9208 over four years ago :-)

**Closed by Snuffleupagus** 2023-02-13 08:52 UTC
