### ISSUE TITLE
Memory leak: some events aren't unregistered

### ISSUE THREAD

**Issue by stephanrauh** [mozilla/pdf.js#10946] opened 2019-07-05 18:49 UTC
Configuration:
- Web browser and its version: any version
- Operating system and its version: any OS
- PDF.js version: 2.2.222
- Is a browser extension: no (I'm using the generic browser to display PDFs embedded in a web application)

While investigating https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/101, I noticed there are three events that are registered but never unregistered. I suppose that's a memory leak. In my case, this causes trouble in my SPA when I try to print via CTRL+P after leaving the page using the PDF viewer.

- window.addEventListener('keydown', function (event) { [defined here](https://github.com/mozilla/pdf.js/blob/5517c94d66f22cc98df6dd1dab90ced15d49f3b8/web/pdf_print_service.js#L275)
- window.addEventListener('popstate', _boundEvents.popState); [defined here](https://github.com/mozilla/pdf.js/blob/5517c94d66f22cc98df6dd1dab90ced15d49f3b8/web/pdf_history.js#L592) 
- window.addEventListener('pagehide', _boundEvents.pageHide); [defined here](https://github.com/mozilla/pdf.js/blob/5517c94d66f22cc98df6dd1dab90ced15d49f3b8/web/pdf_history.js#L593) 

I suppose it's simply a matter of adding these three events to [PDFViewerApplication.unbindWindowEvents()](https://github.com/mozilla/pdf.js/blob/5517c94d66f22cc98df6dd1dab90ced15d49f3b8/web/app.js#L1460).

**Comment by timvandermeij** [comment] 2019-07-05 19:39
Thank you, I think you're right. I don't think it's necessarily a memory leak, but this should be refactored a bit so that the binding/unbinding of window events is in one place only.

**Comment by stephanrauh** [comment] 2019-07-05 19:45
Seems things are not so easy, although I don't know why yet:

- the keydown listener is registered when the viewer.js script is loaded, no matter if there's a PDF or not.
- I've added the removeEventListener as I suggested. To my surprise, CMD+P doesn't do anything (except highlighting the "edit" menu for a fraction of a second). Maybe that's a OSX problem. My theory is that registering the "keydown" event automatically kills the standard key binding. If that's true, we could simply re-bind it to `window.print()`.

BTW, here are my source code changes: https://github.com/stephanrauh/ngx-extended-pdf-viewer/commit/6f47d1bd7f790fa47872c11031fefae4e24e283e#diff-ff2d4af1f0673e3ea448a4b444ece1da

**Comment by stephanrauh** [comment] 2019-07-06 15:35
Forget about my last post - I've managed to get everything up and running. It's possible to restore the standard functionality after removing pdf.js from the DOM. Also see #10948, which is an unexpected side effect that confused me yesterday.

**Comment by timvandermeij** [comment] 2019-12-15 15:49
In pull request #11380 two out of the three registered event listeners are now also unregistered upon resetting. Only the print keydown event listeners remains for this issue.

**Comment by Snuffleupagus** [comment] 2019-12-15 19:46
> In pull request #11380 two out of the three registered event listeners are now also unregistered upon resetting.

Yes, but those event were was only fixed indirectly since it made sense for other reasons (such as consistency with other components) to allow for a PDFHistory` instance to be reset.

In general though I would be *very* tempted to suggest WONTFIX for the `PDFPrintService` code, for a couple of reasons:
 - This issue claims there's memory leaks, but doesn't actually provide *any* evidence to back that up.
 - The only embedding that the default viewer really supports is an `<iframe>`, where I cannot imagine that these event listeners should cause any trouble.[1]
 - This doesn't affect the `FirefoxPrintService` at all, since that registers no events. Hence trying to "fix" this in the `PDFPrintService` would thus make the different `PDFPrintServiceFactory` interfaces "unbalanced".
 - There's a *number* of `window` events being registered in `web/pdf_print_service.js`, and I think that you need to register them immediately upon load to not miss any events and/or not being the *first* event handler. Consequently, removing these event listeners *may* thus lead to unexpected behaviour later on.

---
[1] Note also http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Closed** 2019-12-15 23:09 UTC
Labels: 1-viewer

**Comment by stephanrauh** [comment] 2019-12-16 22:18
@Snuffleupagus I can't evade the impression you disapprove of the ngx-extended-pdf-viewer project. Is this correct? If so, why?

Just for the record: ngx-extended-pdf-viewer does build upon pdf.js. It adds 62 modifications to the core pdf.js files. It also adds a lot of additional value, especially compared to the iFrame approach. Currently, there's limited skinning. As far as I can see, almost every user is using it. Advanced skinning (i.e. Material Design and Bootstrap4) is on top of the users' wish-list, so it'll come soon. 

Putting it all together, I'm astonished you stress the "re-skin or build" bit so often.

**Comment by Snuffleupagus** [comment] 2019-12-17 16:55
> I can't evade the impression you disapprove of the ngx-extended-pdf-viewer project.

I don't even know what "ngx-extended-pdf-viewer" is, and don't have time to figure that out now :-)

---

*In general:* The reason that the default viewer shouldn't be used as-is, is that we want to avoid custom applications being mistaken for the built-in PDF Viewer in Firefox.

Unless the viewer looks significantly different from the PDF Viewer in Firefox, there's a risk that many users won't be able to tell the difference. The reason that this is a problem is that while the PDF Viewer in Firefox is updated *regularly*, there's simply no guarantee that everyone using the default viewer in custom applications will ensure that it's being kept up to date (in practice it's unfortunately seems common to find "custom" viewers which are *many years* out of date).
Using older versions of the PDF.js code-base, in custom applications, it's thus quite likely that end-users will encounter parsing/rendering bugs which have already been fixed upstream for some time.

When a *custom* default viewer looks, as far as most users are concerned more-or-less, identical to the PDF Viewer in Firefox, people will then report any problems *here* (or in Bugzilla, or through Webcompat) and the only answer that can be provided is "that's not the PDF Viewer in Firefox, please contact whoever maintains it".
All in all, this will easily cause the PDF.js project itself to look bad and/or to be blamed for bugs which have been fixed and/or which simply cannot be fixed *here*.

**Comment by Snuffleupagus** [comment] 2019-12-17 17:24
> I can't evade the impression you disapprove of the ngx-extended-pdf-viewer project.

Honestly I don't even know what the "ngx-extended-pdf-viewer" project is, and won't have time to figure that out now with Christmas just around the corner, hence I obviously don't have an opinion about it :-) 

---

*Generally speaking, not singling out any particular project:* The reason that the default viewer shouldn't be used as-is, is to avoid custom applications being mistaken for the built-in PDF Viewer in Firefox by virtue of looking more-or-less identical to many users.

**Comment by stephanrauh** [comment] 2019-12-17 17:52
@Snuffleupagus Thanks! That's a very good reason, something I can work with. I'll see what I can do to make "my" embedded viewer look different. In most cases, it'll look different simply because it's not a full-page viewer, but of course, I don't want to see my bugs on your bug tracker.

What I can offer is this: if someone files a bug report, and mentions "Angular", just CC me.

Best regards, and merry Christmas
Stephan

**Comment by timvandermeij** [comment] 2019-12-17 22:29
That's very nice of you, thanks! In general we mention skinning because we have seen bugs in custom deployments of PDF.js being reported here relatively often because users thought they were dealing with the official viewer when they were in fact looking at an unskinned copy of the default viewer. To avoid this, we usually mention this line, but in this case it was just to show that extending the viewer like you're doing is actually OK in this case, so no worries about that!

If you find issues in PDF.js, please always feel free to always report them. We have already fixed some problems based on your issues/comments, so that's very helpful.
