### ISSUE TITLE
PDFs print with an additional blank pages after each page with print

### ISSUE THREAD

**Issue by StevenDStanton** [mozilla/pdf.js#6095] opened 2015-06-08 16:28 UTC
I am running pdf.js version 1.1.3

Our system generates PDF's dynamically when a web page is visited.

We get the issue in Chrome Version 43.0.2357.81 m, FireFox Version 38.0.5, and IE 11.0.9600.17633IS

We load that PDF and it displays fine as a 4 page PDF

When we go to print instead of bringing up 4 pages it brings up 8 pages. 

At first some of the text from the print page was going onto the second blank page. We changed the print size to A4 and that solved that. Now it has 4 printed pages and after each of the pages it has a completely blank page.

We can download the pdf file and it prints 4 pages as expected.

**Comment by timvandermeij** [comment] 2015-06-08 18:28
Recently some patches landed to fix printing behavior, especially for non-Firefox browsers such as Chrome (example: #5857). Please try opening the PDF file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if the problem still occurs with the latest version. If so, please also post a link to the PDF file so we can try to reproduce it.

**Comment by StevenDStanton** [comment] 2015-06-11 14:23
It looks like the issue has been resolved testing it with the latest version.

I will try redownloading the latest stable version. I thought I had the 1.1.3 but I may have gotten a version earlier and not noticed the change

**Comment by StevenDStanton** [comment] 2015-06-11 18:59
When I test on the link you gave me doing the upload of the file it works perfectly for printing

When I test on my server using the same process and the 1.1.3 build I am still having the problem

should I use the beta build instead?

**Comment by timvandermeij** [comment] 2015-06-12 19:01
The fixes landed recently and are not in the stable build yet. If it is a critical issue for you, you can use the current master branch instead (because I'm not sure if beta already contains the fix), but otherwise I would suggest waiting until a new version is released.

Closing as fixed.

**Closed by timvandermeij** 2015-06-12 19:01 UTC
Labels: 4-information-requested
