### ISSUE TITLE
Problem in find . Required text is not properly highlighted.

### ISSUE THREAD

**Issue by meShakti** [mozilla/pdf.js#5728] opened 2015-02-13 16:18 UTC
It seems that on finding a string in pdf.js . The selected string is not properly highlighted . The issue is observed in both chrome and firefox browsers  in windows os . I didn't test for linux though . Here are the screenshots.
![issue](https://cloud.githubusercontent.com/assets/6806790/6190717/f5218aaa-b3c9-11e4-848e-018d9971ee4f.png)
![issue1](https://cloud.githubusercontent.com/assets/6806790/6190725/fec835d6-b3c9-11e4-9d4d-110672ea5bae.png)
![issue2](https://cloud.githubusercontent.com/assets/6806790/6190733/081bf82a-b3ca-11e4-9961-7d436ee1f739.png)

**Comment by Snuffleupagus** [comment] 2015-02-13 16:53
Closing as duplicate of issues such as: #5668 and #2980.

@meShakti For future reference: When reporting an issue, please remember to always include a link to the PDF file (see also [the first paragraph here](https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md)).

**Closed by Snuffleupagus** 2015-02-13 16:53 UTC
