### ISSUE TITLE
Official chrome extension outdated

### ISSUE THREAD

**Issue by ajarang** [mozilla/pdf.js#13669] opened 2021-07-05 00:50 UTC
It appears that the official chrome webstore extension by Rob W is outdated. It was last updated in 2019.

**Comment by Snuffleupagus** [comment] 2021-07-29 12:07
The Chrome extension is no longer "just" very outdated, but now it's unfortunately also *broken* for some documents when used in Google Chrome `92.0.4515.107` (and above).

One example of a broken file is https://github.com/mozilla/pdf.js/blob/master/test/pdfs/ZapfDingbats.pdf, which fails to render completely with the following error:
```
Warning: getOperatorList - ignoring errors during "GetOperatorList: page 0" task: "DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': function at() { [native code] } could not be cloned.".
```
The cause of this error is the, fairly recently added, [`Array.prototype.at()` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at) which was fixed in PR #12924 which is included in PDF.js release `2.8.335` and up.
Also, please note that the very same file renders correctly when opened using https://mozilla.github.io/pdf.js/web/viewer.html, in the Google Chrome `92.0.4515.107`.

---

While I completely understand that you've not had time to update the extension, it does feel somewhat unfortunate to list in prominently [in the README](https://github.com/mozilla/pdf.js#chrome) when it's in fact no longer working correctly. (Unless an update can be made "soon", I'd probably suggest that we *temporarily* remove that link from the README.)

As I recall, from the last time this was discussed in https://github.com/mozilla/pdf.js/pull/13117#issuecomment-803573230, you were slightly concerned about the recently added scripting support. Hence please note that you could, quite easily, disable scripting by default for *only* the Chrome extension (in case that'd help get an updated version out quicker).

/cc @Rob--W

**Comment by Rob--W** [comment] 2021-07-29 13:16
This will be one of my priorities this weekend.

**Comment by Rob--W** [comment] 2021-08-01 17:54
I did some manual tests with the basic functionality, and caught + fixed two regressions so far:
- https://github.com/mozilla/pdf.js/pull/13841
- https://github.com/mozilla/pdf.js/pull/13842
  - This is not extension-specific, so I filed an issue at https://github.com/mozilla/pdf.js/issues/13840 for future reference.

Next tasks:
- Evaluate other issues tagged https://github.com/mozilla/pdf.js/labels/4-chrome-specific
- Disable JS by default.
- Look at the list of 1.1k commits (excluding merge commits) made since the last release of the extension to see if there is anything noteworthy to list in the release notes.
- Clean up code if possible - I'll check the version usage to see what versions we need to support (which I've collected according to https://github.com/Rob--W/pdfjs-telemetry)
- More manual testing.

**Comment by Rob--W** [comment] 2021-09-11 23:14
I've done an audit of the new scripting engine and found that it's not unsafe, hence I decided to include it in the build instead. However, the functionality is disabled by default to minimize risk:
- https://github.com/mozilla/pdf.js/pull/14004

**Comment by Rob--W** [comment] 2021-11-01 00:23
I've been trying to get an update through. I'll need to update the store listing and developer account to meet the increasingly stricter requirements for listing an extension. Here is a write-up about a recent terrible experience: https://github.com/Rob--W/stackexchange-notifications/issues/31#issuecomment-919034619

I paused my effort on publishing, by investigating the recent report about the absence of the extension on ChromeOS (#14161). That in turn is blocked on getting a Chrome OS environment. I considered a physical device. Apparently it may be possible to run a VM (https://chromium.googlesource.com/chromiumos/docs/+/HEAD/cros_vm.md), but I have yet to test it.

I don't have as much time as before to dedicate to side projects, so my progress is slow.

**Comment by timvandermeij** [comment] 2021-11-03 18:27
Oh no, that does sound like a frustrating experience indeed. Hopefully it will work out better for this extension update, but in any case thanks for carrying on with this!

**Comment by LifeIsStrange** [comment] 2022-02-28 00:02
@Rob--W Any update? :)

**Comment by stevennyman** [comment] 2022-03-03 18:03
@Rob--W FYI the CloudReady Chromium OS distribution has a [pre-made VM image](https://cloudreadykb.neverware.com/s/article/Download-CloudReady-Image-For-VMware) available.

I'm also looking forward to an updated version of the extension; if the Chrome Web Store is causing too many issues for publication perhaps you could try submitting to the Edge Addons store :)

**Comment by SamB** [comment] 2022-03-18 20:01
@stevennyman Unfortunately, that probably wouldn't help Chrome users ...

**Comment by timvandermeij** [comment] 2022-09-18 12:30
For the time being, since the extension is very outdated now, we've removed a few bits about the Chrome extension in https://github.com/mozilla/pdf.js/pull/15452 which can be reverted once the extension is updated again.

**Comment by Rob--W** [comment] 2022-09-18 14:50
My next attempt to update the PDF.js Chrome extension is scheduled for the weekend of 15 October.

**Comment by ecstrema** [comment] 2022-11-02 09:31
Meanwhile, you can grab a build of this extension [here](https://github.com/mozilla/pdf.js/files/9914385/chromium.zip) and install manually.

**Comment by Snuffleupagus** [comment] 2022-11-02 09:47
> Meanwhile, you can grab a build of this extension [here]() and install manually.

Please let's not advertise an *unofficial* build here, refer to https://github.com/mozilla/pdf.js#chrome for instructions about building the extension yourself.

**Comment by timvandermeij** [comment] 2023-03-25 14:19
I'm afraid that at this point keeping the extension around does more harm than good. It's extremely outdated, it's broken for some documents and users are filing issues for it that we can't address. If we can't get it updated and maintained anymore, I feel like it might actually be better to remove the extension altogether, even though that would be very unfortunate (but in the end the development focus of the project is Firefox).

@Rob--W As the original extension maintainer, what do you think? Given https://github.com/mozilla/pdf.js/issues/13669#issuecomment-955822678 it seems like it will be hard to get it updated again, or has the situation improved on the Chrome web store side?

**Comment by stevennyman** [comment] 2023-03-25 21:44
It's worth noting that the extension will probably be automatically removed by Google in a few months anyway as part of their [manifest v2 depreciation timeline](https://developer.chrome.com/docs/extensions/migrating/mv2-sunset/) (though it seems that the exact dates are still under review at this point).

**Comment by Rob--W** [comment] 2023-03-25 22:22
I'm going to audit the changes since the last time I looked and if retry submission to the Chrome Web Store tomorrow (Sunday).



> It's worth noting that the extension will probably be automatically removed by Google in a few months anyway as part of their [manifest v2 depreciation timeline](https://developer.chrome.com/docs/extensions/migrating/mv2-sunset/) (though it seems that the exact dates are still under review at this point).

While the Chrome Web Store does not support new MV2 submissions, they still allow MV2 extensions (like the current PDF Viewer) to be updated. As long as that works, I will retry to submit an update with MV2.

FYI: The Chrome extension of this project relies on the blocking webRequest API in Chrome, which is not available in MV3. The replacement for blocking webRequest in MV3 is declarativeNetRequest, but that does not offer the ability to implement redirections based on the response header. Follow #15161 if you are interested in subscribing to news about the MV3 version of the extension.

**Comment by Rob--W** [comment] 2023-04-16 20:54
I have been analyzing log files (https://github.com/Rob--W/pdfjs-telemetry) to determine which Chrome versions should still be supported (basically to re-evaluate Chrome support as I did before in #9397).

Using the data from March:
- About 1M unique clients (due to anonimization, some clients may be counted twice)
- The majority (60%+) is on the latest stable version of Chrome.
- 98.59% is using Chrome 90+ (Chrome 90 was released exactly 2 years ago, 14 April 2021).
- 98.77% is using Chrome 87+ (Chrome 90 was first released in 11 November 2020).
- Chrome 87 has 0.10% usage.
- Chrome 86 has 0.06% usage.
- Chrome 85 has 0.03% usage.
- Chrome 84 has 0.05% usage.
- Chrome 79 has 0.10% usage.
- Chrome 76 has 0.14% usage.
- Chrome 67 has 0.18% usage.
- Chrome 57 has 0.33% usage.

Cursory testing (checking whether PDF.js loads / displays) shows:
- Chrome 84-: viewer is completely broken, because PDF.js uses assignment operators (e.g. [`||=`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment#browser_compatibility)) that are syntax errors when not supported.
- Chrome 84 - 86 : viewer renders, but layout is broken (canvas fills part of the page; toolbar items are squished together), because the [`inset` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/Inset#browser_compatibility) is not supported until Chrome 87.
- Chrome 87: seems to render fine.

Based on these observations, I am inclined to drop support for Chrome 86-. Since the latest version would not work for a bit over 1% of the users, it would be best to set [minimum_chrome_version](https://developer.chrome.com/docs/extensions/mv3/manifest/minimum_chrome_version/) to 87.

I'll do more testing and submit patches to drop obsolete code from the extension code.

**Comment by timvandermeij** [comment] 2023-04-22 12:39
Sounds good! Given that Chrome 86 is from 2020 already, that seems more than reasonable to me. Moreover, note that we already require Chrome >= 88 for the regular builds; see https://github.com/mozilla/pdf.js/blob/master/gulpfile.js#L82.

**Comment by ToxicSmurf** [comment] 2023-06-18 18:44
Are we just waiting for Google to automatically remove the extension?

**Comment by Rob--W** [comment] 2023-06-25 11:20
The updated PDF.js Chrome extension was approved two days ago.

I have set the [minimum supported Chrome version to 88](https://github.com/Rob--W/pdf.js/commit/6b9cb6589b808c09747c194a4cd035eb5f28e298) instead of 87 because of rendering bugs (ghosting) observed in 87, likely due to PDF.js minimum support for 88 (as Tim mentioned). The minimum supported Chrome version was bumped to 92 in #16499, so in a future extension update I'd have to re-evaluate whether to raise the version requirement.

Note that presently, there is a significant spike in usage at Chrome version 91 (2.48% in april 2023, 2.42% in may 2023), so I'm not keen on dropping support for these versions just yet. The vast majority of these are running on Chrome OS: From a sample recorded on June, 1st, 1201 were running Chrome 91, and of these 1036 (86%) were running on Chrome OS.

**Comment by Rob--W** [comment] 2023-06-25 12:32
I'm closing this issue since the Chrome Web Store now has an updated Chrome extension version of PDF.js. I'll monitor regressions (e.g. https://github.com/mozilla/pdf.js/issues/16594) and may publish a new update in the short term if needed.

The largest threat to the future of the PDF.js Chrome extension is the lack of proper API to support MIME-based PDF handling in Manifest Version 3. This is tracked in https://github.com/mozilla/pdf.js/issues/15161.

**Closed by Rob--W** 2023-06-25 12:32 UTC
Labels: addon, chrome-specific

**Comment by timvandermeij** [comment] 2023-06-25 13:09
Thank you for your work on this @Rob--W!
