### ISSUE TITLE
Disabling "Allow pages to choose their own font" leads to invisible fonts in pdfs

### ISSUE THREAD

**Issue by cosminribo** [mozilla/pdf.js#10157] opened 2018-10-15 12:08 UTC
Font settings in the Firefox Preferences seem to affect PDF display. Disabling the "Allow pages to choose their own font" reproducibly leads to invisible fonts in displayed pdfs. Enabling this option restores the normal behaviour and pdf files are viewed correctly.

Link to example PDF file here: https://www.has-sante.fr/portail/upload/docs/application/pdf/2008-11/solumedrol_-_ct-5879.pdf
Attached file: [solumedrol_-_ct-5879.pdf](https://github.com/mozilla/pdf.js/files/2478608/solumedrol_-_ct-5879.pdf)

Configuration:
- Web browser and its version: Firefox 62.0.3 (64-bit)
- Operating system and its version: Ubuntu Linux 18.04

Steps to reproduce the problem:
1. Unselect in the advanced Font configuration settings the "Allow pages to choose their own fonts, instead of your selections above"
2. Open a pdf file in Firefox.
3. Checking the option restores the view of pdf files to normal.

What is the expected behavior?
![normal](https://user-images.githubusercontent.com/5047356/46950039-b0c82500-d083-11e8-881e-e546ca530178.png)

What went wrong?
![problem](https://user-images.githubusercontent.com/5047356/46950043-bb82ba00-d083-11e8-8e29-078424bb7b52.png)

Thank you.

**Comment by Snuffleupagus** [comment] 2019-01-26 13:34
> Unselect in the advanced Font configuration settings the "Allow pages to choose their own fonts, instead of your selections above"

That makes this issue a duplicate of #4244, since not all font data is embedded in the PDF file itself.

**Closed** 2019-01-26 14:54 UTC
Labels: 1-other
