### ISSUE TITLE
Unchecking "allow pages to choose their own fonts" in Firefox causes blank PDFs.

### ISSUE THREAD

**Issue by mhoye** [mozilla/pdf.js#10058] opened 2018-09-10 15:29 UTC
Attach (recommended) or Link to PDF file here:  (any)

Configuration:
- Web browser and its version: Current Firefox Nightly
- Operating system and its version: Up-to-date Win10
- PDF.js version:  Current 
- Is a browser extension: no

Steps to reproduce the problem:
1.  In Firefox, Options -> Language And Appearance -> Advanced , uncheck the "Allow pages to choose their own fonts, instead of your selections above" checkbox and select a font of your own preference that is not one of the most commonly used (Arial/TimesNewRoman, etc..)
2. Open any PDF, results should be mostly blank.

What is the expected behavior? 

I'm not sure what the "right" behavior here is - when that option is toggled the browser falls back to the chosen default font to display web pages, but it appears that PDF.js falls back to nothing, so the PDF is full of blank spaces, and nothing is displayed.  Is the right behavior a best-effort rendering with the selected default font? Should pdf.js ignore that pref? I'm not sure; what it's doing is clearly not the right thing, but I don't know what a users' expectations should be in this case.

**Comment by timvandermeij** [comment] 2018-09-10 22:19
Closing since this is a duplicate of #7549. In short, we don't have such a fallback system yet.

**Closed by timvandermeij** 2018-09-10 22:19 UTC
