### ISSUE TITLE
Wrong content behaviour on the pdf

### ISSUE THREAD

**Issue by AlexP3** [mozilla/pdf.js#11332] opened 2019-11-14 11:05 UTC
Attach (recommended) or Link to PDF file here:
[pdf.pdf](https://github.com/mozilla/pdf.js/files/3846011/pdf.pdf)

Configuration:

- Firefox 70.0.1 (64-bit)
- Microsoft Windows 10 Pro, 10.0.18362 N/A Build 18362
- PDF.js: 2.3.101 (Firefox console output)
- built in

Steps to reproduce the problem:
Drag and drop the pdf file in a firefox browser.

What is the expected behavior? (add screenshot)
Line on the first page should have start coordinates x=100, y=100.
<img width="234" alt="pdf" src="https://user-images.githubusercontent.com/36297903/68851183-169b3c00-06de-11ea-88f9-47e2c90bd8ca.png">
I have checked on a Chrome and Adobe, works fine.

What went wrong? (add screenshot)
Line on the bottom of the first page has start coordinates x=0, y=0.
<img width="851" alt="pdf_wrong" src="https://user-images.githubusercontent.com/36297903/68851266-4ba78e80-06de-11ea-947e-0ec2b2d08316.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2019-11-14 22:29
I can reproduce this using Firefox 70.0.1 (64-bit, Linux). There are no warnings/errors in the console.

**Comment by THausherr** [comment] 2019-11-19 09:48
This one does the transformation after the path has been set but before the draw. All PDFs I have seen do the transformation first. I could not find which way is correct by looking at the PDF specification.

**Comment by Snuffleupagus** [comment] 2019-11-19 09:58
Looks like a duplicate of #10908.

**Comment by Snuffleupagus** [comment] 2021-01-31 09:33
Duplicate of #10908

**Closed** 2021-01-31 13:10 UTC
Labels: 1-core
