### ISSUE TITLE
how to print PDF width pdfjs-dist

### ISSUE THREAD

**Issue by 2016011969sunyifang** [mozilla/pdf.js#14954] opened 2022-05-24 09:59 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. cant find any doc about print 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-05-24 10:15
Duplicate of #10307; please note in particular https://github.com/mozilla/pdf.js/issues/10307#issuecomment-442254159.

**Closed by Snuffleupagus** 2022-05-24 10:15 UTC
