### ISSUE TITLE
(Re)ordering of the PDF textcontent elements in the DOM

### ISSUE THREAD

**Issue by Marsunpaisti** [mozilla/pdf.js#17191] opened 2023-10-27 08:20 UTC
Attach (recommended) or Link to PDF file here:
[ordering_example.pdf](https://github.com/mozilla/pdf.js/files/13186464/ordering_example.pdf)

I've had quite a few of these documents that for some reason have the text elements in an unexpected order, probably as a result of them being OCR'd or converted from other file types with whatever tools. It seems really common that the footer of a pdf page is for some reason one of the first elements in the textcontent array / rendered HTML even though it is (visually) the last item on the page.

PDFJS seems to respect the exact ordering of the elements as they appear in the PDF internally, which then causes selection behavior in to be very weird because a span of text at the top of the document can be next to a span of text that is (visually) at the bottom of the document when rendered to the DOM.
Also getting the text content via PDFPageProxy.getTextContent will produce the elements in the order that elements appear in the pdf internally instead of how it would be read intuitively by a human, so joining these into a string is not a viable solution.

Configuration:
- Web browser and its version: Happens regardless of browser
- Operating system and its version: Windows 11, Ubuntu 22.04 LTS
- PDF.js version: 3.8.162
- Is a browser extension: No

Steps to reproduce the problem:
1. Load above document via PDFJS, render it
2. Elements in the DOM are in an arbitrary order thats not top-to-bottom or anything
3. Selecting these text for copy pasting etc. will not work intuitively, expanding selection "forward" with shift+arrow keys for example will jump to unexpected places (as the next element in the dom is not necessarily what is visually/intuitively next)
4. Raw text content strings extracted from these kinds of documents will equally be in a mangled order depending on how the textcontent items are saved internally in the file.

What is the expected behavior?
PDF Text content spans are from top to bottom, left to right with selections working as you would intutively expect. I've managed to make something for extracting the "intuitive" text content by just sorting the textContent items according to their transforms from top to bottom, left to right and then merging them to produce a string. 
I think this should also happen in pdfjs internally to order the elements before rendering them?

What went wrong? (add screenshot)
As an example here I'm selecting text and because of how the textContent elements are ordered in the HTML, selection behavior doesnt properly let me select paragraphs etc.
![image](https://github.com/mozilla/pdf.js/assets/10946514/679d78d7-775b-4570-af7f-5dfefdc7d439)

**Comment by Snuffleupagus** [comment] 2023-10-27 09:28
> I've had quite a few of these documents that for some reason have the text elements in an unexpected order,

Please keep in mind that this is basically a bug in the PDF document *itself*, since it specifies the text in an "incorrect" order.

> PDF.js version: 3.8.162

While it might not matter in this particular case, please note that that version is no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I've managed to make something for extracting the "intuitive" text content by just sorting the textContent items according to their transforms from top to bottom, left to right and then merging them to produce a string.
> I think this should also happen in pdfjs internally to order the elements before rendering them?

Unfortunately that's probably less straightforward that you think in *the general case*, consider e.g. right-to-left and top-to-bottom writing modes.

---

Given that this problem is already tracked in existing issues, let's close this as a duplicate of e.g. issue #2344.

**Closed by Snuffleupagus** 2023-10-27 09:28 UTC
