### ISSUE TITLE
PDF not displaying properly in IE through Canvas

### ISSUE THREAD

**Issue by anishvyas** [mozilla/pdf.js#7601] opened 2016-09-06 10:12 UTC
I am facing an issue with the pdfjs version 1.5.188. 

I am displaying the contents of a PDF through canvas on browser by not using the Viewer.js . 

The problem seems to be with IE not displaying properly as it's working fine with Chrome and Firefox.

What is the expected behavior? 
![chrome_pdfjs](https://cloud.githubusercontent.com/assets/22025483/18269994/5ed8bc12-7448-11e6-8378-66143067716b.PNG)

What went wrong? 
![ie_pdfjs](https://cloud.githubusercontent.com/assets/22025483/18270018/79d750e6-7448-11e6-815d-1b3818443ff9.PNG)

From the above screenshots you can see the jumbled letters in a table.

**Comment by timvandermeij** [comment] 2016-09-06 10:15
This really looks like a driver issue. Try updating your graphics driver or disabling hardware acceleration. No link to the PDF file has been provided, nor are there details about the version of IE, so for now I'm closing this as there is nothing else we can do here.

**Comment by anishvyas** [comment] 2016-09-06 10:31
@timvandermeij Hi, I can understand that I did not provide any link to the PDF as it's a Client Document which I cannot share. What I can tell you is that I am using IE 11.0 on my system.
I don't think it as a graphics driver issue as its also not working on other systems and working on Chrome everywhere.

I can share the custom code with you : 
`<html>
<body>

<script type="text/javascript" src="./compatibility.js"></script>
<script type="text/javascript" src="./pdf.worker.js"></script>
<script type="text/javascript" src="./pdf.js"></script>
<script type="text/javascript">
function renderPDF(url, canvasContainer, options) {
    var options = options || { scale: 2};
        
    function renderPage(page) {
        var viewport = page.getViewport(options.scale);
        var canvas = document.createElement('canvas');
        canvas.id = 'canvasID';
        var ctx = canvas.getContext('2d');
        var renderContext = {
          canvasContext: ctx,
          viewport: viewport
        };
        
        canvas.height = viewport.height;
        canvas.width = viewport.width;
        canvasContainer.appendChild(canvas);
        
        page.render(renderContext);
    }
    
    function renderPages(pdfDoc) {
        for(var num = 1; num <= pdfDoc.numPages; num++)
            pdfDoc.getPage(num).then(renderPage);
    }
    PDFJS.disableWorker = true;
    PDFJS.getDocument(url).then(renderPages);
}   



</script> 

<div id="holder"></div>

<script type="text/javascript">
renderPDF('<LINK TO MY PDF>', document.getElementById('holder'));
</script>  

</body>
</html>`

**Comment by Snuffleupagus** [comment] 2016-09-06 11:35
Looking through the open IE11 specific issues, see https://github.com/mozilla/pdf.js/labels/4-ie11-specific, there already seems to be various mentions of similar rendering issues.

Given that this most likely is a hardware/driver specific issue related to just IE, and that there just isn't enough information provided for anyone else to reproduce this, I'm closing this issue as duplicate/incomplete.

**Closed by Snuffleupagus** 2016-09-06 11:35 UTC
Labels: 1-other, 4-ie11-specific

**Comment by anishvyas** [comment] 2016-09-08 07:12
@timvandermeij @Snuffleupagus   - I analysed the PDF more and found that the issue still persists. I looked through all the issues but couldn't find any which could help me. 

Can you tell me what more can I provide so that you guys can help me? I have a presentation today and can't seem to make it happen.

The issue is with Headers and Table columns particularly. Please help.

**Comment by yurydelendik** [comment] 2016-09-08 12:59
>Can you tell me what more can I provide so that you guys can help me?

@anishvyas please provide complete example online so the issue can be reproduce on different computer than yours.

**Comment by yurydelendik** [comment] 2016-09-08 13:35
> I looked through all the issues but couldn't find any which could help me. 

The issue indeed looks like out-of-date driver issues we had in the past (e.g. https://github.com/mozilla/pdf.js/issues/6798 or https://github.com/mozilla/pdf.js/issues/6956) It usually resolved by updating the drivers or disabling hardware acceleration .

**Comment by anishvyas** [comment] 2016-09-12 10:40
@timvandermeij @Snuffleupagus @yurydelendik Thank you for all your help. It was indeed an issue with drivers. It worked fine.
