### ISSUE TITLE
Unsupported bookmark features

### ISSUE THREAD

**Issue by waddlesplash** [mozilla/pdf.js#3214] opened 2013-05-06 19:34 UTC
The bookmarks in this PDF (download+rename to ".pdf") - [bookmark-unsupported-features pdf](https://f.cloud.github.com/assets/2175324/467817/fc5d9218-b683-11e2-8bad-3d02692e3e04.png) - should be self-explanatory of what the problem is.

So far, the only reader I've found that supports this is Adobe. Okular gets the link to Google right, but not the rest. Xpdf and ViewPDF crash when attempting to open the file. Evince, ApVLV, and gv don't show it right either.

**Comment by kvk123456** [comment] 2015-12-21 21:48
Any resolution for this? can you please let us know the hyperlink issue in bookmark will be fixed in next release?

**Comment by Snuffleupagus** [comment] 2015-12-21 21:55
Closing as duplicate of issue #5089, since that one contains more discussion/context.

**Comment by timvandermeij** [comment] 2016-01-19 21:22
Reopening to track the bold/italic and color issues. The URL issue is now fixed by #6822.

**Closed** 2016-03-02 21:42 UTC
Labels: 1-viewer, 2-feature
