### ISSUE TITLE
wrong PDF display

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#5811] opened 2015-03-07 19:03 UTC
As reported in sumatrapdfreader/sumatrapdf#112, pdf.js-1.0.1185 displays wrong the following file:

> http://www.alternativacivicacaino.it/files/2015-02-25-assemblea_pubblica.pdf

Here you have the mandatory screenshot:

![screenshot from 2015-03-07 19 42 50](https://cloud.githubusercontent.com/assets/203767/6542789/f3e37ff8-c504-11e4-8304-2e6546ea595d.png)

evince-3.10 and mupdf-1.6 display the file right.

**Comment by Rob--W** [comment] 2015-03-07 20:10
Reproduced in Fireox 36.0 on Linux. Looks good in Chromium 41.0.2272.77

**Comment by Snuffleupagus** [comment] 2015-03-07 21:09
I cannot reproduce, using: Windows 7 (64-bit), Firefox Nightly 39 (buildID: 20150307030233) with HWA on, and PDF.js 1.0.1185.
Perhaps a Linux (and Firefox) only issue? This is how PDF.js renders it on my computer:
![5811](https://cloud.githubusercontent.com/assets/2692120/6543279/5b4e03e6-c516-11e4-9872-fc6124cbc6a1.png)

**Comment by timvandermeij** [comment] 2015-03-07 22:33
I can confirm that this renders fine on Windows.

**Comment by wamatt** [comment] 2015-03-08 20:54
Slightly offtopic, but fow do you find `v1.0.1185`?

As far I can tell it would seem this repo on github makes no reference to that version, only `v1.0.1149`.

**Comment by timvandermeij** [comment] 2015-03-08 22:01
@wamatt You can always find the latest version number at https://github.com/mozilla/pdfjs-dist/releases which is updated everytime we merge a pull request. Note that this is only the development (alpha) version number: the stable and beta version numbers are listed on https://mozilla.github.io/pdf.js/getting_started/#download.

**Comment by wamatt** [comment] 2015-03-08 22:21
Ahh got it now, thanks @timvandermeij . I was having an issue with a Chinese character form, and the alpha seems v1.0.1185 to have sorted it out!

Will also keep in mind though that it's bleeding edge and may introduce new issues in future.

**Comment by timvandermeij** [comment] 2015-04-13 19:14
I can confirm that the original PDF is also broken in the same way on Arch Linux with Firefox 37.0.1.

**Comment by Lord-of-Darkness** [comment] 2015-05-15 20:14
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by opi** [comment] 2015-05-26 08:30
I also got an issue of "black" layer below some images. Here is the sample pdf : http://www.sstrn.fr/sites/default/files/pdf/sstrn_guide_des_services_aux_adherents_web.pdf

Below the coloured squares with text, 4 squares are black in FF, and not in chrome.

**Comment by yurydelendik** [comment] 2015-11-10 14:13
Closing as duplicate of #4648 and https://bugzilla.mozilla.org/show_bug.cgi?id=976322

**Closed by yurydelendik** 2015-11-10 14:13 UTC
Labels: 4-os-linux, 4-triage-needed
