### ISSUE TITLE
Download button disappears after opening a pdf

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#13997] opened 2021-09-10 10:58 UTC
STR:
  - Go to https://mozilla.github.io/pdf.js/web/viewer.html
  - Click on "Open File" and open a pdf

The `Download` button and the `Current view` one just disappear.
I can reproduce this bug with Firefox nightly, Chrome stable and Epiphany on debian.

**Comment by Snuffleupagus** [comment] 2021-09-10 11:30
Well, this is actually expected behaviour :-)
Please note https://github.com/mozilla/pdf.js/blob/d4caa8756029f4748b46398122162975927e0be6/web/app.js#L2489-L2494

**Comment by calixteman** [comment] 2021-09-10 11:37
Ok, so it means that if I open a form, fill it, then I can't save it (it was my use case with a local server).
Should we let the button in case of Acroform or XFA ?

**Comment by Snuffleupagus** [comment] 2021-09-10 11:49
> Ok, so it means that if I open a form, fill it, then I can't save it

To prevent complete data loss, note that in the GENERIC viewer we're triggering saving of form data automatically when closing an opened document; see https://github.com/mozilla/pdf.js/blob/d4caa8756029f4748b46398122162975927e0be6/web/app.js#L801-L812

> Should we let the button in case of Acroform or XFA ?

*Assuming that we're only talking about the Download-button here, since the ViewBookmark-button really does __not__ make any sense when you've opened a new document:*

While it may may seem easy at first, that may open a whole can of worms elsewhere in the code-base. More specifically, in the GENERIC `DownloadManager` where we're currently using the URL as a fallback when downloading fails.
Obviously the URL doesn't really make sense when you've opened a *new* document in the viewer, hence why the Download-button is being hidden. In order to address this, we'd thus need to differentiate between the *first* and any subsequent documents being opened in the GENERIC viewer.

All of this is obviously *possible* to implement, it'll just be a little less straightforward than simply showing the Download-button and call it a day :-)
I'm assigning this to myself, and will try to fix this during the weekend (time permitting).

**Comment by crich04** [comment] 2021-09-14 17:03
Along these same lines, can you please direct me to the correct way to "upload" said document?  In other words, somebody has opened a PDF and filled out a few fields.  I want to "upload" the changed document (or data) to a server for historical purposes.  It would work very similar to Download but, it's uploading to server side function.  Thanks!!

**Closed** 2021-09-18 14:31 UTC
Labels: 1-viewer
