### ISSUE TITLE
Instructions for using with Cordova

### ISSUE THREAD

**Issue by mixmastamyk** [mozilla/pdf.js#6455] opened 2015-09-16 22:32 UTC
Hi,

Haven't found any instructions for using with Cordova, primarily on recent Android.  Here is my code so far, but it does nothing. The canvas exists.

- How to use a local file path?  I've already cached to filesystem:
- Do I need workers?
- Compatibility?
- Am using bower, do I include files from web or build folders?
- No error messages?
- Under Chrome desktop I get this:
   404 http://localhost:8000/cordova.worker.js

Can anyone help?  Didn't find solutions in the other bugs here.

```js
            console.log('pdf time:....');
            PDFJS.disableWorker = true;
            PDFJS.getDocument(cached).then(function(pdf) {
                // Using promise to fetch the page
                pdf.getPage(1).then(function(page) {
                    var scale = 1;
                    var viewport = page.getViewport(scale);

                    // Prepare canvas using PDF page dimensions
                    var canvas = document.getElementById('pdfview');
                    var context = canvas.getContext('2d');
                    canvas.height = viewport.height;
                    canvas.width = viewport.width;

                    var renderContext = {
                        canvasContext: context,
                        viewport: viewport
                    };
                    page.render(renderContext);
                });
            });

```

**Comment by timvandermeij** [comment] 2015-09-17 11:46
I don't think anyone here has experience with Cordova. The code fragment looks good, so probably the issue is elsewhere in your code. You need workers for good performance. `compatibility.js` does not necessarily have to be included unless you need support for legacy browsers/systems. If there are errors, they are usually found in the console. For local files you will need a server, see also #5548.

Closing as answered for now. If there are specific bugs in PDF.js (i.e., not related to your custom implementation with Cordova), please open a new issue with steps to reproduce.

**Closed by timvandermeij** 2015-09-17 11:46 UTC

**Comment by yurydelendik** [comment] 2015-12-01 19:49
See also http://stackoverflow.com/a/34027997/1765767
