### ISSUE TITLE
Convert Byte array to pdf

### ISSUE THREAD

**Issue by jagrutidave** [mozilla/pdf.js#6047] opened 2015-05-25 15:49 UTC
On the Client I have byte array as response message, how I can convert this byte array to PDF ? Is it possible to convert it back to PDF using PDF.JS ? 

Encoded msg ="JVBERi0xLjQKJdP0zOEKMSAwIG9iago8PAovQ3JlYXRpb25EYXRlKEQ6MjAxNTA1MTgxMjA1NTYtMDQnMDAnKQovQ3JlYXRvcihQREZzaGFycCAxLjMyLjI2MDgtZyBcKHd3dy5wZGZzaGFycC5uZXRcKSkKL1Byb2R1Y2VyKFBERnNoYXJwIDEuMzIuMjYwOC1nIFwod3d3LnBkZnNoYXJwLm5ldFwpKQo+PgplbmRvYmoKMiAwIG9iago8PAovVHlwZS9DYXRhbG9nCi9QYWdlcyAzIDAgUgo+PgplbmRvYmoKMyAwIG9iago8PAovVHlwZS9QYWdlcwovQ291bnQgMgovS2lkc1s0IDAgUiA3IDAgUl0KPj4KZW5kb2JqCjQgMCBvYmoKPDwKL1R5cGUvUGFnZQovTWVkaWFCb3hbMCAwIDYxMiA3OTJdCi9QYXJlbnQgMyAwIFIKL0NvbnRlbnRzIDUgMCBSCi9SZXNvdXJjZXMKPDwKL1Byb2NTZXQgWy9QREYvVGV..=="

Decoded msg on client = %PDF-1.4
%ÓôÌá
1 0 obj
<<
/CreationDate(D:20150401230804-04'00')
/Creator(PDFsharp 1.32.2608-g \(www.pdfsharp.net\))
/Producer(PDFsharp 1.32.2608-g \(www.pdfsharp.net\))
>>
endobj
2 0 obj
<<
/Type/Catalog
/Pages 3 0 R
>>
endobj
3 0 obj
<<
/Type/Pages
/Count 2
/Kids[4 0 R 7 0 R]
>>
endobj
4 0 obj
<<
/Type/Page
/MediaBox[0 0 612 792]
/Parent 3 0 R
/Contents 5 0 R
/Resources

Ø3À;¶êÑýó_õ­Ç|ã]ÈŸ–_{W=OüÆ•å„¾ýIy‚÷‚=Î_Î»?O|àžøÐ?AÓƒ@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ O‘ùi-Ì*ÿ²C™
endstream
endobj
xref
0 10
0000000000 65535 f 
0000000015 00000 n 
0000000180 00000 n 
0000000228 00000 n 
0000000289 00000 n 
0000000519 00000 n 
0000000650 00000 n 
0000001993 00000 n 
0000002223 00000 n 
0000002354 00000 n 
trailer
<<
/ID[<AD641AC805109C418D0A470013329938><AD641AC805109C418D0A470013329938>]
/Info 1 0 R
/Root 2 0 R
/Size 10
>>
startxref
35848
%%EOF

Thank you,

**Comment by Rob--W** [comment] 2015-07-11 10:50
"Convert back to PDF"? If you meant, converting from a base64 string to a typed array (or some other format that can be opened by PDF.js), see e.g. https://stackoverflow.com/questions/12092633/pdf-js-rendering-a-pdf-file-using-a-base64-file-source-instead-of-url.

This question is not a bug, so I'm closing it.

**Closed by Rob--W** 2015-07-11 10:50 UTC
Labels: 1-other

**Comment by diasraphael** [comment] 2017-10-12 11:27
@timvandermeij : Whether you where able to solve the issue, I am also facing the same issue.

Getting decoded msg as mentioned on top, but the stackoverflow post doesnt help reg the decoded msg in client
