### ISSUE TITLE
[Bug] Some chars are unclear.

### ISSUE THREAD

**Issue by Sara2009** [mozilla/pdf.js#16216] opened 2023-03-27 08:09 UTC
Attach (recommended) or Link to PDF file here:
[Diss-387(1).pdf](https://github.com/mozilla/pdf.js/files/11076116/Diss-387.1.pdf)

Configuration:
- Web browser and its version: Chrome  Version 111.0.5563.111 (Official Build) (x64)
- Operating system and its version:  Microsoft Windows11  home 10.0.22621
- PDF.js version: 3.5.114  (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the PDF on https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)
<img width="1699" alt="image" src="https://user-images.githubusercontent.com/9332442/227878868-3baad6db-1c5d-46a2-b094-144af0a0d929.png">

What went wrong? (add screenshot)
Some chars are rendered uncorrect on Page 37. Not clear.

![image](https://user-images.githubusercontent.com/9332442/227880051-0cea0b56-f098-4e68-9880-0f5b62fa23d2.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-03-27 08:46
Duplicate of #14641

**Closed by Snuffleupagus** 2023-03-27 08:46 UTC
