### ISSUE TITLE
PDF not loading in chrome browser in load balancer server Error: Bad end offset in PDF.worker.js

### ISSUE THREAD

**Issue by shenbagaraj** [mozilla/pdf.js#7567] opened 2016-08-26 07:58 UTC
**Pdf is not loading only in chrome browser in our server**. Kindly help me. 
**_In lower environment its working in all the browser._**
Please find the below error and also attached the screen. _**its shows in ChunkedStreamManager_onReceiveData**_

Uncaught (in promise) Error: Bad end offset: 8312527
at error (https://stagecd-diabetes-wellnessinpracticenetwork.snfems.com/Areas/GlobalComponents/js/Global/components/PDFViewer/build/pdf.worker.js:2314:9)
at assert (https://stagecd-diabetes-wellnessinpracticenetwork.snfems.com/Areas/GlobalComponents/js/Global/components/PDFViewer/build/pdf.worker.js:2327:5)
at Object.ChunkedStream_onReceiveData as onReceiveData
at Object.ChunkedStreamManager_onReceiveData as onReceiveData
at Object. (https://stagecd-diabetes-wellnessinpracticenetwork.snfems.com/Areas/GlobalComponents/js/Global/components/PDFViewer/build/pdf.worker.js:6348:14)
![image](https://cloud.githubusercontent.com/assets/21241471/17998234/e8c846a6-6b90-11e6-8feb-00d19f4bfdd6.png)
Please let me know if you need any further information.

**Comment by Snuffleupagus** [comment] 2016-08-26 08:12
Closing as duplicate of issue #7566.

**Closed by Snuffleupagus** 2016-08-26 08:12 UTC

**Comment by shenbagaraj** [comment] 2016-08-26 08:16
Could u please Reopen this issue #7566
