### ISSUE TITLE
PDF poor quality on mobile

### ISSUE THREAD

**Issue by LukeGarrigan** [mozilla/pdf.js#15407] opened 2022-09-07 07:36 UTC
Refashioned version of [this issue](https://github.com/mozilla/pdf.js/issues/15405) which was closed.

Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google chrome Version 105.0.5195.102 (Official Build) (64-bit)
- Operating system and its version: MS Windows 10 Pro 
- PDF.js version: //mozilla.github.io/pdf.js/build/pdf.js

Steps to reproduce the problem:
1. Go to the [sandbox page](https://codesandbox.io/s/pdf-js-landscape-7fj422?file=/src/index.js) I've setup 
2. Run the application in a new window:
![image](https://user-images.githubusercontent.com/12545967/188713398-ecc2db65-a69d-4ad1-a013-b4d4d06268df.png)
3. Open up the chrome dev tools
4. Choose to use emulate a mobile 
![image](https://user-images.githubusercontent.com/12545967/188714554-7ed2cb4e-a20a-4bde-a97d-74aba046e9c0.png)

The quality is awful, is there anything I can do to improve this?

This is the meat of the code for rendering:
```javascript
function renderPage(num) {
  pageRendering = true;
  pdfDoc.getPage(num).then(function (page) {
    const desiredWidth = canvas.width;
    const scaledViewport = getScaledViewport(page, desiredWidth);
    canvas.height = scaledViewport.height;
    canvas.width = scaledViewport.width;
    var renderContext = {
      intent: "print",
      canvasContext: ctx,
      viewport: scaledViewport
    };
    var renderTask = page.render(renderContext);

    // Wait for rendering to finish
    renderTask.promise.then(() => {
      pageRendering = false;
      if (pageNumPending !== null) {
        renderPage(pageNumPending);
        pageNumPending = null;
      }
    });
  });


function getScaledViewport(page, desiredWidth) {
  const viewport = page.getViewport({ scale: 1 });
  if (viewport.width > viewport.height) {
    const scale = desiredWidth / viewport.height;
    return page.getViewport({ scale: scale, rotation: 90 });
  } else {
    const scale = desiredWidth / viewport.width;
    return page.getViewport({ scale: scale });
  }
}
```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://codesandbox.io/s/pdf-js-landscape-7fj422

**Comment by Snuffleupagus** [comment] 2022-09-07 07:47
Duplicate of #15405; note in particular https://github.com/mozilla/pdf.js/issues/15405#issuecomment-1239031272

**Closed by Snuffleupagus** 2022-09-07 07:47 UTC
