### ISSUE TITLE
Unable to fully select characters for copying and pasting

### ISSUE THREAD

**Issue by paulmenzel** [mozilla/pdf.js#17900] opened 2024-04-08 06:35 UTC
Attach (recommended) or Link to PDF file here:

[2021-140-EPS300_AS5114-48X-DS-R06-20211209.pdf](https://github.com/mozilla/pdf.js/files/14901785/2021-140-EPS300_AS5114-48X-DS-R06-20211209.pdf)

Configuration:
- Web browser and its version: 126.0a1, 20240407213050
- Operating system and its version: Debian sid/unstable
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. Select some text
2. Copy and paste it

What is the expected behavior? (add screenshot)

All the selected text should be pasted.

What went wrong? (add screenshot)

The characters are not highlighted, but in the screenshot you can see it looks like the four is selected too. But it is not copied/pasted.

![pdfjs-and-selection](https://github.com/mozilla/pdf.js/assets/9318792/25e55afd-a26e-454f-9e06-0dcc9ccf3a75)

**Comment by nicolo-ribaudo** [comment] 2024-04-08 09:58
This is the same problem as https://github.com/mozilla/pdf.js/issues/15114. The selection is not aligned with the underlying text because the font pdf.js uses to implement selection has characters of different widths than the font rendered in the PDF.

**Comment by timvandermeij** [comment] 2024-04-08 13:01
Thank you for triaging this! Closing as a duplicate of #15114 where we'll track this issue further.

**Closed by timvandermeij** 2024-04-08 13:01 UTC
