### ISSUE TITLE
Not an issue: Modify divs of text before or after the pdf is loaded.

### ISSUE THREAD

**Issue by AvdiuAndin** [mozilla/pdf.js#9305] opened 2017-12-21 18:26 UTC
My goal is to highlight some parts of the text and add a div with some Jquery functionality on it. Can someone suggest me solution for this problem?

I tried using mark Js library for highlighting text, but in some cases there are some words that do not appear to be together but when i search them with MARK JS they are concatenated :( . However, pdf find controller does the search perfectly for my case, but i don't know how to access the highlighted text and add some divs to it.

**Comment by timvandermeij** [comment] 2017-12-21 20:19
Closing since this is a duplicate of #9286.

**Closed by timvandermeij** 2017-12-21 20:19 UTC
