### ISSUE TITLE
Viewer does not show digital signatures

### ISSUE THREAD

**Issue by airnovadmin** [mozilla/pdf.js#13049] opened 2021-03-03 16:45 UTC
[Attach](url) (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:
Versions are [attached](url
![browsers](https://user-images.githubusercontent.com/79994694/109840266-94ee5b00-7c0d-11eb-9a87-f36ff5969f6e.png)
![viewer](https://user-images.githubusercontent.com/79994694/109840291-97e94b80-7c0d-11eb-950c-c84ebf4be2b4.jpg)

)

Steps to reproduce the problem:
1.  Open any signed PDF, there is nothing in the signature. Open offline with Adobe Acrobat, signature is there

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm/related?hl=en

**Comment by Snuffleupagus** [comment] 2021-03-03 16:56
Duplicate of #1076

**Closed** 2021-03-03 18:45 UTC
