### ISSUE TITLE
Interactive forms in landscape mode are not being rotated properly 

### ISSUE THREAD

**Issue by bksantiago** [mozilla/pdf.js#12180] opened 2020-08-06 15:02 UTC
Attach (recommended) or Link to PDF file here:
[landscape form 1.pdf](https://github.com/mozilla/pdf.js/files/5035721/landscape.form.1.pdf)

Configuration:
- Web browser and its version: **Chrome 84.0.4147.105**
- Operating system and its version: **MacOS / 10.15.6**
- PDF.js version: **2.5.153**
- Is a browser extension: **No**

Steps to reproduce the problem:
1.  Set `renderInteractiveForms` to true
2. Use a landscape(rotated) PDF with forms

What is the expected behavior? (add screenshot)
<img width="496" alt="image" src="https://user-images.githubusercontent.com/4616548/89547546-78856e00-d838-11ea-869a-2b3fba822976.png">

What went wrong? (add screenshot)
<img width="530" alt="image" src="https://user-images.githubusercontent.com/4616548/89547591-8804b700-d838-11ea-9671-e2b48b5784a4.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Just using the interactive form example under `/example/acroforms/acoforms.html`

**Comment by timvandermeij** [comment] 2020-08-06 20:45
Closing since this is a duplicate of #9596.

**Closed by timvandermeij** 2020-08-06 20:45 UTC
