### ISSUE TITLE
Text widget annotations are not rendering properly

### ISSUE THREAD

**Issue by dhanu-mamidi** [mozilla/pdf.js#10333] opened 2018-12-05 19:00 UTC
Not  sure what went wrong in implementing the acroforms in angular by using the example [acroforms.js](https://github.com/mozilla/pdf.js/blob/master/examples/acroforms/acroforms.js)

Configuration:
Using the latest version of Chrome on windows 10. 

Steps to reproduce the problem:
https://github.com/dhanu-mamidi/pdfjs-forms/blob/master/src/app/app.component.ts
npm install and start would result in the same issue with the above source.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/24209951/49536595-ee5f6680-f8ec-11e8-87ec-9bc28ab543e7.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/24209951/49536615-fae3bf00-f8ec-11e8-879a-0589b2c7b10c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2018-12-05 19:20
Looks like a duplicate of #9993; you'll need to include the `pdf_viewer.css` file for annotations (among other things) to be positioned correctly.

**Comment by timvandermeij** [comment] 2018-12-05 21:56
Yes, that should be the problem. Closing as answered.

**Closed by timvandermeij** 2018-12-05 21:56 UTC

**Comment by dhanu-mamidi** [comment] 2018-12-06 16:36
Yes, pdf_viewer.css is not loading. I have sorted that but after that all the annotations are rendering in the first page. and they are slightly above position they are supposed to be any insights on this.

With both pages
![image](https://user-images.githubusercontent.com/24209951/49597589-c6323f00-f9a2-11e8-983c-520477b0b01a.png)

With single page
![image](https://user-images.githubusercontent.com/24209951/49597740-17dac980-f9a3-11e8-95ec-5bccdd99734b.png)

Source: https://github.com/dhanu-mamidi/pdfjs-forms/blob/master/src/app/app.component.ts

**Comment by timvandermeij** [comment] 2018-12-06 21:38
It looks you have some margin or padding applied to the page or the annotation layer then since this doesn't happen in the default viewer/example.

**Comment by dhanu-mamidi** [comment] 2018-12-07 03:37
@timvandermeij thanks, that position is because of the margin. But even second-page annotations are rendered in the first page itself?

**Comment by dhanu-mamidi** [comment] 2018-12-17 11:31
Hi,

Can you give me more info on why annotation factory is not considering the padding and margins give for the parent div. It get the same transform origin co-ordinates with or without padding to the parent div.

Any solution for this

Thanks in advance

**Comment by timvandermeij** [comment] 2018-12-17 14:03
I don't know, but you can check `src/display/annotation_layer.js` to see if any styles are overwritten for the annotation types you use.

**Comment by dhanu-mamidi** [comment] 2018-12-18 06:21
Hi tim,
I have looked into annotation_layer.js there we are giving the rect from data where we are not considering the offset that div has. Is it because of that. Correct me if I'm wrong.

Thanks

**Comment by timvandermeij** [comment] 2018-12-18 21:36
That could be the case. You can check if it fixes your issue and if so, feel free to create a pull request for us to review.

**Comment by Snuffleupagus** [comment] 2018-12-19 07:42
> feel free to create a pull request for us to review.

But before considering doing that[1], please ensure that the changes don't break anything by actually testing them locally first; refer to https://github.com/mozilla/pdf.js/wiki/Contributing#4-run-lint-and-testing

---
[1] There was another recent issue, see #10348, where there was a suggestion of using `offsetLeft` in some calculations which would have caused quite severe rendering errors. Honestly, I'd imagine that the code under discussion *here* could easily be similarly effected.

**Comment by dhanu-mamidi** [comment] 2018-12-26 10:07
Hey ,
I have observed that by passing the offset value in the viewport for rendering the annotations. They are rendering properly with same position  value as offset is zero in viewport.

Can you please tell more on this 
Thanks

**Comment by timvandermeij** [comment] 2018-12-28 20:33
I think there is already a pull request for this, #10368, which I think does exactly what you want.

**Comment by dhanu-mamidi** [comment] 2018-12-31 09:57
Hi tim, this is exactly what I am thinking of. But I think pdfpageviee.setpage will change the viewport to the default offset 0. 

Thanks

**Comment by dhanu-mamidi** [comment] 2019-01-02 07:11
Hi ,
Everything seems fine except all annotations are rendering in the first page as I mentioned avove. Do you have any idea on this.

Thanks.

**Comment by timvandermeij** [comment] 2019-01-02 22:37
I don't know why that is happening. Check if it also happens with the unchanged AcroForm example that you mentioned. If not, there is an issue with your customized code.

**Comment by dhanu-mamidi** [comment] 2019-01-03 08:06
Yes Tim, it's happening with the default code too.

**Comment by Snuffleupagus** [comment] 2019-01-04 10:54
Running `gulp dist-install`[1] and then opening http://localhost:8888/examples/acroforms/acroforms.html locally works just fine for me, so I'm not entirely sure why this issue needed to be re-opened!?

Most likely testing wasn't done using *only* the `acroforms` example directly, without any other code and/or HTML elements around it.

---
[1] The instructions at https://github.com/mozilla/pdf.js/tree/master/examples/acroforms might need to be updated, since they mention `gulp dist` and all the other viewer component based examples use `gulp dist-install`.

**Comment by VineelG** [comment] 2020-07-23 09:47
Hi,



> 
> 
> Yes, pdf_viewer.css is not loading. I have sorted that but after that all the annotations are rendering in the first page. and they are slightly above position they are supposed to be any insights on this.
> 
> With both pages
> ![image](https://user-images.githubusercontent.com/24209951/49597589-c6323f00-f9a2-11e8-983c-520477b0b01a.png)
> 
> With single page
> ![image](https://user-images.githubusercontent.com/24209951/49597740-17dac980-f9a3-11e8-95ec-5bccdd99734b.png)
> 
> Source: https://github.com/dhanu-mamidi/pdfjs-forms/blob/master/src/app/app.component.ts

Hi,
Me too getting the same issue, after implementing AcroForms in Angular.  All annotations are rendering in the first page and they are not in actual position if margin or padding applied to the actual pdfviewer (offsets are not being calculated). 

The original AcroForms code is not customized, except its been implemented in Angular by changing referenced file paths. 
Could you please explain, what must be causing this issue? What files in pdfjs-dist are responsible for annotations population aligned to the pdfviewer?

Thanks
