### ISSUE TITLE
bad printing pdf fonts in the new firefox 52 (preview page ok)

### ISSUE THREAD

**Issue by chechovr** [mozilla/pdf.js#8186] opened 2017-03-22 22:36 UTC
i've a problem with epson ps printer since firefox include you own pdf in the last version v.52 , the problem is when send print pdf, in the preview page not have any error , but when send to the printer all text are cut and ilegible. i send a capture images of printed pages. 

in the others versions of firefox print all fine

![img_20170322_182731936](https://cloud.githubusercontent.com/assets/26611341/24223792/2b856aa0-0f2e-11e7-881a-9f4ec7e9ec65.jpg)
![img_20170322_183105762_burst000_cover_top](https://cloud.githubusercontent.com/assets/26611341/24223797/2fad9260-0f2e-11e7-9fe8-39496ebba242.jpg)

**Comment by timvandermeij** [comment] 2017-03-22 23:07
Closing since the provided information is incomplete (most importantly, no PDF file is provided to reproduce the issue). This sounds like an upstream issue since you say it's working in previous versions of Firefox, so I'd suggest filing an issue on Bugzilla instead.

**Closed by timvandermeij** 2017-03-22 23:07 UTC
