### ISSUE TITLE
PDF.js Search not working correctly

### ISSUE THREAD

**Issue by kvk123456** [mozilla/pdf.js#6478] opened 2015-09-25 16:15 UTC
Search functionality locating wrong place for some of the PDFs

![pdf js search issue](https://cloud.githubusercontent.com/assets/13853369/10105851/0b7ea750-637f-11e5-834e-510cfda4d0b3.jpg)

**Comment by kvk123456** [comment] 2015-09-25 16:16
Here is the PDF url http://hosted.rightprospectus.com/documents/WilliamBlair/PRO_Combined.pdf

**Comment by timvandermeij** [comment] 2015-09-25 18:01
The problem is that the text layer is not aligned properly.

**Comment by kvk123456** [comment] 2015-09-28 12:43
is there any fix available for this from PDF.js?

**Comment by timvandermeij** [comment] 2015-09-28 19:33
Not that I am aware of. Someone has to look into the cause of the misalignment.

**Comment by timvandermeij** [comment] 2015-11-07 14:23
Closing as fixed in the latest development version of PDF.js.

**Closed by timvandermeij** 2015-11-07 14:23 UTC
Labels: 4-text-selection
