### ISSUE TITLE
Can the electronic signature be displayed now?

### ISSUE THREAD

**Issue by wrtda** [mozilla/pdf.js#9019] opened 2017-10-11 06:18 UTC
Attach (reccomened) or Link to PDF file here:

Configuration:
- firefox 56.0.1
- windows 7
- PDF.js version: all 
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-10-11 08:52
Closing as duplicate of #1076 (which is still open).

**Closed by Snuffleupagus** 2017-10-11 08:52 UTC
