### ISSUE TITLE
Checkbox always checked in same group

### ISSUE THREAD

**Issue by Spounespoune** [mozilla/pdf.js#13127] opened 2021-03-22 10:47 UTC
Configuration:
- Web browser and its version: 86.0.1
- Operating system and its version: macos
- PDF.js version : -
- Is a browser extension: Yes

Hello,

I'm come here today for report a bug with default PDF viewer on Firefox.
I have a normal PDF document. I fill this document with PDFTK and my two cases is always checked but just one can normaly. (radio input)

My dump file with PDFTK (just for information)
FieldType: Button
FieldName: to_service_activity_field
FieldFlags: 1
FieldValue: MCO => Case checked
FieldJustification: Left
FieldStateOption: MCO
FieldStateOption: Off
FieldStateOption: SSR-PSY

Just for information (my fields in abode reader)
![2021-03-12-00-11-52-4b179d](https://user-images.githubusercontent.com/80510813/111976354-d33ab400-8b01-11eb-9c7a-20cc7fca91d8.png)

What is the expected behavior?
The screen is render view PDF of Chrome viewer or Adobe reader (with the same file, it works !)

![2021-03-12-00-18-42-80c610](https://user-images.githubusercontent.com/80510813/111976404-df267600-8b01-11eb-9ba7-f28fa799a54d.png)

What went wrong?
The screen is render view of Firefox PDF viewer (My trouble)

![2021-03-12-00-16-31-8c69e0](https://user-images.githubusercontent.com/80510813/111976389-db92ef00-8b01-11eb-97b4-fc58133c0923.png)

Thanks in advance

**Comment by Snuffleupagus** [comment] 2021-03-22 10:58
When opening an issue, please make sure that you provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md in order for the issue to be actionable/valid; in particular the "Attach (recommended) or Link to PDF file here:"-part is *required* here.

**Comment by Spounespoune** [comment] 2021-03-22 13:05
@Snuffleupagus Hello, thank you. I edit my post.

**Comment by Snuffleupagus** [comment] 2021-03-22 13:13
> Hello, thank you. I edit my post.

Uncomfortably you still haven't provided the *single most important* piece of information here (without which there's not really much point in opening an issue):
> Attach (recommended) or Link to PDF file here:

---

> About my pdf file is confidential.

Sorry, but that make the issue non-actionable/invalid since it's *impossible* to debug anything from a screen-shot alone.
What you can check, is if the issue is still present in the *latest* PDF.js version; try opening your document with the demo viewer at https://github.com/mozilla/pdf.js#online-demo

Also, as mentioned in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, it helps to provide a better title than "[Bug] Default PDF viewer".

**Comment by Snuffleupagus** [comment] 2021-03-22 13:50
Given the lack of *crucial* information, let's close this issue as a duplicate of #12716 for now.

**Comment by Spounespoune** [comment] 2021-03-22 16:36
@Snuffleupagus I see this issue and fix. But this bug always exist ... I hosted soon my PDF file

**Comment by Snuffleupagus** [comment] 2021-03-22 16:49
> But this bug always exist

Did you actually bother testing with the *latest* PDF.js version, which https://github.com/mozilla/pdf.js/issues/13127#issuecomment-804050673 specifically suggested?

**Comment by timvandermeij** [comment] 2021-03-24 19:31
Closing until a PDF file is provided.

**Closed by timvandermeij** 2021-03-24 19:31 UTC
