### ISSUE TITLE
Unable to remove toolbar and margins

### ISSUE THREAD

**Issue by JakeQZ** [mozilla/pdf.js#13153] opened 2021-03-28 04:21 UTC
Attach (recommended) or Link to PDF file here: irrelevant

Configuration:
- Web browser and its version: all
- Operating system and its version: all
- PDF.js version: 2.6.347-es5
- Is a browser extension: no

Steps to reproduce the problem:
1. Embed PDF via `iframe` with `src=/web/viewer.html?file=some.pdf`
2. Hack the `viewer.css` to add the following (to try to remove the toolbar and margins):

```css
div.toolbar {
  display: none;
}
#viewerContainer {
  top: 0;
}
.pdfViewer .page {
  margin: 0;
  border: 0;
  padding: 0;
}
```

What is the expected behavior? (add screenshot)

PDF content fills container

What went wrong? (add screenshot)

PDF content has (grey) margins to the right and below (randomly either about 32px right and 24px below or 8px right and 6px below, for A4 landscape PDF)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): n/a

<strong>`width` and `height` style properties are being set on the `div.page`, `div.canvasWrapper` and `div.textLayer` elements, as well as as attributes on the `canvas`.

I just need to know where in the JavaScript these are being set, so I can investigate further.  I have been unable to find what part of the code is doing this - surely somebody must know.</strong>

**Comment by JakeQZ** [comment] 2021-03-28 05:46
Solved it, I think.

It also needs

```css
#viewerContainer,
#viewer {
  overflow-y: hidden;
}
```

otherwise when it does the measuring there is (or might be) a scrollbar.

It also needs

```js
var SCROLLBAR_PADDING = 0;
var VERTICAL_PADDING = 0;
```

in `viewer.js` changing from the strange default values.

**Comment by Snuffleupagus** [comment] 2021-03-28 09:13
This looks essentially like a duplicate of issue #6087, and as mentioned in https://github.com/mozilla/pdf.js/issues/6087#issuecomment-808869080 this isn't really something that we'll support out of the box with the possible exception of the `#toolbar` hash-parameter.

**Closed** 2021-03-28 12:08 UTC

**Comment by JakeQZ** [comment] 2021-03-28 15:53
Does look like a bug though if the dimensions set for the container account for a non-existent scrollbar ***in addition to*** an extra `SCROLLBAR_PADDING` fudge factor.

**Comment by kirubalan** [comment] 2024-08-07 12:04
**Question**

I am trying to remove the toolbar from a PDF file displayed in an iframe using the following URL parameter: **#toolbar=0**. However, this parameter does not seem to work in Firefox, and I am unable to remove the toolbar across all browsers.

**Details**

PDF File Location: file:///C:/Users/DELL/Desktop/Test/Business.pdf
Current Implementation: iframe src="file:///C:/Users/DELL/Desktop/Test/Business.pdf#toolbar=0"
Question: How can I remove the toolbar for PDF files across all browsers, including Firefox?

**Comment by user234** [comment] 2024-09-11 06:24
I could hide the toolbar and margin by editing these in viewer.css:

`--toolbar-height: 0px;`

and adding this near the end of the file:

```
#toolbarContainer{
  display: none;
}

```
