### ISSUE TITLE
High memory usage when building CRA example

### ISSUE THREAD

**Issue by artisb45** [mozilla/pdf.js#11410] opened 2019-12-16 14:16 UTC
Attach (recommended) or Link to PDF file here: (any pdf produces the same result)

Configuration:
- Web browser and its version: Google Chrome 79.0.3945.79
- Operating system and its version: Windows 10 Enterprise 1903
- PDF.js version: 2.2.228
- Is a browser extension: false

- Node version: 12.13.1
- NPM version: 6.13.4
- Create React App version: 3.3.0
- React version: 16.12.0
- React-scripts version: 3.3.0

Steps to reproduce the problem:
1. Create new react app with create-react-app
2. npm install pdfjs-dist
3. Copy [example](https://github.com/mozilla/pdf.js/tree/master/examples/create-react-app) 
4. npm start or npm run build

What is the expected behavior? (add screenshot)
Start or build succesfully

What went wrong? (add screenshot)
- Very high memory usage 
![Memory usage](https://user-images.githubusercontent.com/13067633/70913233-4cee1300-201e-11ea-8952-09c75b1abf33.png)

- Fails with error
![NpmError](https://user-images.githubusercontent.com/13067633/70913370-90488180-201e-11ea-9537-66e45e194c4f.png)

**Comment by astrada** [comment] 2019-12-16 16:37
I'm experiencing the same issue. I did some tests ejecting, trying to pinpoint the issue, and it looks like the problem starts with `@babel/core` version 7.7.0+. If you eject and downgrade `@babel/core` to version 7.6.4, it works again for me.

**Comment by timvandermeij** [comment] 2019-12-16 21:54
This looks like a Babel regression then. Do you know if this is already reported upstream? If not, it should be reported to Babel so it can be fixed there.

**Comment by artisb45** [comment] 2019-12-17 08:21
I searched through babel issues, and it doesnt seem to be reported yet. Is there anything specific that you want me to tell them to make it more clear?

**Comment by astrada** [comment] 2019-12-17 08:25
@artisb45 I've uploaded a repo to test the issue with the CRA example: https://github.com/astrada/pdf.js-cra-test

**Comment by timvandermeij** [comment] 2019-12-17 22:36
Thank you all for helping out with reporting this upstream! It looks like there is already a pull request upstream to fix it, so that's great. Once it's merged and released, we can update Babel to fix it on our side as well.

**Comment by artisb45** [comment] 2019-12-18 07:23
Cheers, helped me out a lot aswell. For anyone who runs into this until it is merged, try overwriting `node_modules/@babel/core/lib/transformation/normalize-file.js` with [this file](https://gist.githubusercontent.com/JLHwung/a4e735de002261d84764b8c3ed136c24/raw/48239c4844129b04d7aed1ac1985d5ee5ea72e29/normalize-file.js) as mentioned in the [PR](https://github.com/babel/babel/pull/10885).

**Comment by midgethoen** [comment] 2019-12-18 09:18
> I tried replacing the file, but no success there, anyone got it to work?

patching @babel/core7.7.5 with the mentioned file doesnt fix the error for me either...

**Comment by midgethoen** [comment] 2019-12-18 09:39
However, When I delete the `//# sourceMappingURL ...`  comments from the pdfjs-dist package I can get CRA to run again. 

unfortunately I have no experience with troubleshooting these memory problems so im kind of stabbing in the dark here. Im not sure how i can be of more help

**Comment by timvandermeij** [comment] 2019-12-19 22:52
The upstream issue got fixed and we updated our dependency version too, so it's also fixed on our side now for the next release.

**Closed** 2019-12-19 22:51 UTC
Labels: 1-dependencies, 3-upstream

**Comment by Athelian** [comment] 2022-06-20 10:54
> However, When I delete the `//# sourceMappingURL ...` comments from the pdfjs-dist package I can get CRA to run again.
> 
> unfortunately I have no experience with troubleshooting these memory problems so im kind of stabbing in the dark here. Im not sure how i can be of more help

I tried patching the `//# sourceMappingURL` comments out of this package for my repository but I'm still failing to build my app on remote. I also tried upgrading Babel, but I'm on the verge of uninstalling this package altogether.

If anyone has any other tips on how to fix this please let me know 🙏🙏
