### ISSUE TITLE
Links are not being opened in fullscreen mode

### ISSUE THREAD

**Issue by cmtt** [mozilla/pdf.js#7234] opened 2016-04-21 15:25 UTC
Link to PDF file: http://www.theasciicode.com.ar/ascii-table-characters.pdf

Configuration:
- Web browser and its version: Firefox 45.0.1, 45.0.2
- Operating system and its version: MacOS X 10.11.3
- PDF.js version:
PDFJS.version = '1.3.76';
PDFJS.build = 'f7ec866';

Steps to reproduce the problem:
1. Open the aforementioned PDF.
2. Enter the fullscreen mode by clicking on the designated icon.
3. Click on the link on the first line.

What is the expected behavior? 

The browser should open the link in a new tab.

What went wrong?

The browser moves on to the second page of the document.

**Comment by Snuffleupagus** [comment] 2016-04-21 15:37
This is by design, to prevent the user from accidentally navigating away from the document whilst in *Presentation Mode*. (Note that this isn't a general "Fullscreen" mode, but rather a mode specifically intended for showing presentations.)

Closing as answered.

**Closed by Snuffleupagus** 2016-04-21 15:37 UTC

**Comment by yurydelendik** [comment] 2016-04-21 15:42
Also duplicate of #3172 ?
