### ISSUE TITLE
Electron/Node mistaken for Browser results in Exception

### ISSUE THREAD

**Issue by ashishkaul** [mozilla/pdf.js#14909] opened 2022-05-13 08:08 UTC
Attach (recommended) or Link to PDF file here: Any PDF

Configuration:
- Web browser and its version: NA
- Operating system and its version: Windows 10
- PDF.js version: 2.13.216
- Is a browser extension: No

Steps to reproduce the problem:
We are trying to extract data from a PDF file which is on my local machine using the "getDocument" method of the library.
We use electron as node environment but not in a renderer as Web environment.

Earlier we got the error: `"structuredClone" is not defined.`
"structuredClone" is a class which is accessible only for the WEB environment, so it cannot work because we use electron as node environment but not in a renderer as Web environment.

Therefore we switched to  a `legacy-build`, which is required in e.g. Node.js environments.
```
const pdfjs = require('pdfjs-dist/legacy/build/pdf');
pdfjs.getDocument({url: pdfPath, password: password});
```

What is the expected behavior? (add screenshot)
Extraction should work successfully.

What went wrong? 
But i get the following error in pdfjs-dist\legacy\build\pdf.worker.js at line 176 (See `if` condition):

```
for (var property in []) {
     enumerableProperties.push(property);
   }
if (enumerableProperties.length) {
        throw new Error("The `Array.prototype` contains unexpected enumerable properties: " + enumerableProperties.join(", ") + "; thus breaking e.g. `for...in` iteration of `Array`s.");
      }
```
Error: The 'Array.prototype' contains unexpected enumerable properties: where, select, selectMany, remove; thus breaking e.g. 'for...in' iteration of 'Array's.'

_What is the purpose of this code ? How can it work for other consumers of the pdfjs?_

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): NA

**Comment by Snuffleupagus** [comment] 2022-05-13 08:15
Duplicate of #14895

**Closed by Snuffleupagus** 2022-05-13 08:15 UTC

**Comment by ashishkaul** [comment] 2022-05-13 08:19
@Snuffleupagus I created a separate issue since I could not find the option to reopen the old issue. Could you let me know what would be the best way to:

- reopen the old issue

OR

- get assistance for the issue
