### ISSUE TITLE
pdf.js not rendering or erroneously until zoom is 10%

### ISSUE THREAD

**Issue by Kellsen** [mozilla/pdf.js#18334] opened 2024-06-25 19:46 UTC
### Attach (recommended) or Link to PDF file

For a while now the internal Firefox pdf viewer has become unusable. It just shows rubbish if anything at all. Fonts superimposed or blank pages that are transparent all the way to the desktop. The grey circular picture is my desktop background:

![pdf100%](https://github.com/mozilla/pdf.js/assets/93977235/f7e30ad6-1a46-45d6-a545-bd04524746ac)

When I zoom all the way out to 10% it seems to be alright but obviously unusable:

![pdf10%](https://github.com/mozilla/pdf.js/assets/93977235/1227833e-a5fb-4018-aba7-b076d96a000c)

Example pdf happened to be the "Risk" rulebook because that was the first that showed when I was looking for a random pdf to demonstrate. It does it with every pdf I open. The only way to use it is to download and show in LMDE's own pdf viewer which is obviously a hassle.
Can't tell if it's working in another browser since I only have Firefox installed and don't really want to use any other.
Disabling hardware acceleration doesn't do anything and forcing the Fonts in about:config neither.

GPU is a GeForce 3060Ti with the latest stable driver (550.90.07) installed. Rolling back to other versions doesn't change anything.
CPU is a Intel i5-12600KF, 48GB RAM, 1TB NVMe SSD

Where to start to track down what's going on?

### Web browser and its version

Firefox 127.0.1

### Operating system and its version

LMDE 6 (Debian Bookworm)

### PDF.js version

n/a

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. open any pdf online in browser

### What is the expected behavior?

show read- and usable pdf

### What went wrong?

see above

**Comment by timvandermeij** [comment] 2024-06-25 19:54
Is this perhaps a duplicate of #18310?

**Comment by Kellsen** [comment] 2024-06-25 19:56
> Is this perhaps a duplicate of #18310?

Could be.

**Comment by calixteman** [comment] 2024-06-25 20:06
As mentioned here: https://github.com/mozilla/pdf.js/issues/18310#issuecomment-2184939136 you should file a bug in Bugzilla.

**Comment by Kellsen** [comment] 2024-06-25 20:50
Right. What fixed it for me was changing the "gfx.canvas.accelerated" from true to false.

Don't know what that does but it fixed it for me :)

**Comment by timvandermeij** [comment] 2024-06-26 12:22
It looks like that's a hardware acceleration issue then. We are experimenting with disabling it for PDF.js in https://bugzilla.mozilla.org/show_bug.cgi?id=1902012 already, but in any case the fact that this suddenly broke is something that also really should be reported separately in Bugzilla for the graphics team (seeing that this is the second report we've had of it in a few days now, it's likely an upstream regression in Firefox). Closing since there isn't much more we can do here.

**Closed by timvandermeij** 2024-06-26 12:22 UTC
Labels: upstream

**Comment by droghio** [comment] 2024-08-01 04:26
For those interested a corresponding Bugzilla ticket is https://bugzilla.mozilla.org/show_bug.cgi?id=1910395
