### ISSUE TITLE
Pdf.js not rendering crystal Report's generated pdf properly

### ISSUE THREAD

**Issue by mrpandya007** [mozilla/pdf.js#5849] opened 2015-03-17 14:27 UTC
I have added signature and certificate in pdf programatically. PDF opens it in acrobat reader but not displays sign and certificate in pdf.js :(

**Comment by timvandermeij** [comment] 2015-03-17 19:18
Closing as duplicate of #1076 and others.

**Closed by timvandermeij** 2015-03-17 19:18 UTC
