### ISSUE TITLE
pdf.js seems to be ignoring annotations added using Preview.app

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [mozilla/pdf.js#9552] opened 2018-03-12 15:04 UTC
Attach (recommended) or Link to PDF file here:
https://github.com/Napoleon-BlownApart/Firefox_pdf.js_Problem

Configuration:
- Web browser and its version:
Nightly 49.0.1  (Last version that does not require signed addons)
- Operating system and its version:
MacOS 10.13.3
- PDF.js version:
*Standard version shipped with the build mentioned above.*
- Is a browser extension:

Steps to reproduce the problem:
1. Open PDF using Firefox (Nightly in my case) and two yellow annotations will be visible in the 2nd column of text on page 1.
2. Open PDF using Safari, or preview, (possibly other readers including Adobe), and four (4) other additional annotations will now be visible, also on the 1st page;
2a)  A "Note" in the top left,
2b) A comment "This is from Preview" near the top left,
2c) The first five (5) words of the Abstract will be highlighted in red, and
2d) The first five (5) words of the Introduction will be highlighed in orange.

What is the expected behavior? (add screenshot)
All annotations are rendered.
<img width="1163" alt="screen shot 2018-03-13 at 1 00 05 am" src="https://user-images.githubusercontent.com/6958677/37291335-27e2a540-265a-11e8-8f60-f3adc98db453.png">

What went wrong? (add screenshot)
Some annotations are not visible.
![screen shot 2018-03-13 at 12 59 55 am](https://user-images.githubusercontent.com/6958677/37291421-5558f538-265a-11e8-8b34-b7704a94df6f.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2018-03-12 18:33
Possibly a duplicate of issue #6811.

**Comment by janpe2** [comment] 2018-03-13 17:24
There is a console warning `Warning: Indexing all PDF objects`.
This is a duplicate of issue #9129, see [this comment](https://github.com/mozilla/pdf.js/issues/9129#issuecomment-344526370).

Here is the first page that I have fixed so that there are no xref problems:
[issue9552_page1.pdf](https://github.com/mozilla/pdf.js/files/1807975/issue9552_page1.pdf)
All annotations are shown correctly. No problems with QuadPoints.

**Closed** 2019-10-17 21:56 UTC
Labels: 4-corrupted-pdf
