### ISSUE TITLE
Try to extract text of LinkAnnotation

### ISSUE THREAD

**Issue by martiflette** [mozilla/pdf.js#11345] opened 2019-11-19 10:41 UTC
Hi,

I'm trying to extract text from LinkAnnotation in order to make focus on specific paragraph at the render of the PDF. 

I did not find any solution. Does anyone have one?

Thx

**Comment by Snuffleupagus** [comment] 2019-11-19 10:52
Duplicate of #9236.

**Closed** 2019-11-19 22:36 UTC
