### ISSUE TITLE
[Bug]: Page No incorrect

### ISSUE THREAD

**Issue by fengjac** [mozilla/pdf.js#18722] opened 2024-09-10 03:30 UTC
### Attach (recommended) or Link to PDF file

[HP DeskJet 2700 All-in-One Series.pdf](https://github.com/user-attachments/files/16938944/HP.DeskJet.2700.All-in-One.Series.pdf)

### Web browser and its version

Chrome is up to date Version 116.0.5845.97 (Official Build) (64-bit)

### Operating system and its version

Windows 11 professional

### PDF.js version

v4.6.82-legacy

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. The page no it shows is "a", "b", "iii", "iv", "v", "vi" instead of "1", "2", "3", "4", "5", "6";
2. And then in page "7", it shows page "1"

### What is the expected behavior?

It should show "1" when I am in page 1 instead of "a"

### What went wrong?

![image](https://github.com/user-attachments/assets/8a904cd8-00e5-474e-9433-679403a2a070)

**Comment by Snuffleupagus** [comment] 2024-09-10 07:42
Duplicate of #11583

**Closed by Snuffleupagus** 2024-09-10 07:42 UTC

**Comment by fengjac** [comment] 2024-09-10 08:35
@Snuffleupagus Is it possible to disable Page Labels by myself? Thanks

**Comment by Snuffleupagus** [comment] 2024-09-10 08:52
> Is it possible to disable Page Labels by myself?

https://github.com/mozilla/pdf.js/blob/5b4c2fe1a845169ac2b4f8f6335337c434077637/web/app_options.js#L183-L187

---

Also, please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
