### ISSUE TITLE
Radio buttons aren't shown properly

### ISSUE THREAD

**Issue by nghuuphuoc** [mozilla/pdf.js#7753] opened 2016-10-26 10:43 UTC
PDF file to test: [sample.pdf](https://github.com/mozilla/pdf.js/files/553055/sample.pdf)

Configuration:
- Web browser: Chrome Version 54.0.2840.71 (64-bit) 
- Operating system: MacOS Sierra 10.12
- PDF.js version: 1.6.210

Steps to reproduce the problem: Open the file with online viewer.

Expected behavior: The radio buttons should look better as checkboxes.

__Checkboxes__
![screen shot 2016-10-26 at 5 37 44 pm](https://cloud.githubusercontent.com/assets/4226036/19722982/5c6ca236-9ba3-11e6-8b86-ae3333b424c7.png)

What went wrong
__Radios__
![screen shot 2016-10-26 at 5 38 01 pm](https://cloud.githubusercontent.com/assets/4226036/19723007/7936b794-9ba3-11e6-9601-47ae881fa390.png)

**Comment by Snuffleupagus** [comment] 2016-10-26 10:55
When reporting an issue, please make sure that you provide *all* the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md. 

As it currently stands, this issue will be closed as incomplete.

**Comment by nghuuphuoc** [comment] 2016-10-26 10:57
I can't provide the full PDF file due to the company privacy. I will try to add a few pages here.

**Comment by nghuuphuoc** [comment] 2016-10-26 11:15
I updated the issue with needed information.

**Comment by Snuffleupagus** [comment] 2016-10-26 11:29
I cannot reproduce, when using: Windows 7 (64-bit), Firefox Nightly 52 (buildID: 20161025030205), and PDF.js version `1.6.264`. This is what it looks like in PDF.js, and in Adobe Reader:

![comparison](https://cloud.githubusercontent.com/assets/2692120/19724373/1896ed50-9b80-11e6-8a1e-0c22ffe5c800.png)

**Comment by yurydelendik** [comment] 2016-10-26 12:58
Closing as fixed.

**Closed by yurydelendik** 2016-10-26 12:58 UTC
Labels: 4-information-requested
