### ISSUE TITLE
Provide example of use PDFJs on Angular 4

### ISSUE THREAD

**Issue by brianhsb1671** [mozilla/pdf.js#8836] opened 2017-08-28 16:37 UTC
Im trying to use PDFJs on Angular 4 and i cant declarate on my module.ts. Please somebody can explain me how to use it.

**Comment by yurydelendik** [comment] 2017-08-28 16:40
Is it duplicate of #7364?

**Comment by yurydelendik** [comment] 2017-08-30 13:32
> i cant declarate on my module.ts

It sounds like a common problem of using CommonJS/Node.js modules in TypeScript. It is out of scope of this project. Did you try to use it without TypeScript?

Please provide complete example of what you have so far.

**Comment by timvandermeij** [comment] 2017-09-07 20:59
Closing since no more information has been provided.

**Closed by timvandermeij** 2017-09-07 20:59 UTC

**Comment by ashishyadav0019** [comment] 2017-11-13 10:34
please see
https://github.com/ashishyadav0019/pdfJS_angular4_Ts.git

**Comment by gelevanog** [comment] 2018-03-20 08:05
Try it:
npm i --save pdfjs-dist 
and
`import * as PDFJS from 'pdfjs-dist/build/pdf';`

**Comment by mtpultz** [comment] 2018-06-14 17:40
@gelevanog are you able to explain how to use `pdfjs-dist` in Angular to display a PDF?

**Comment by codehippie1** [comment] 2018-09-19 17:28
Two options for angular2+.
1. https://github.com/VadimDez/ng2-pdf-viewer (Great for configuring)
2. https://www.npmjs.com/package/ng2-pdfjs-viewer (Uses ViewerJS as well. Full disclosure - This is created by me)

**Comment by mightytyphoon** [comment] 2018-10-02 00:13
@gelevanog @mtpultz 

Once you have done :
 `npm i --save pdfjs-dist` 
AND 
`,npm i @types/pdfjs-dist --save` 

Just import PDFJS in your components, services, guards, whatever files :

`import { PDFJS } from 'pdfjs-dist'`
and then just use PDFJS.getDocument() with a good IDE you will have types and informations on methods.

you can also import lot of other objects from pdfjs-dist, check documentation.

**Comment by jzgoda** [comment] 2018-12-22 18:56
@mightytyphoon 
How are you getting the import to work like so?
```javascript
import { PDFJS } from 'pdfjs-dist';
```

The only way I've gotten this to work is with the following.
```javascript
import { PDFJSStatic } from 'pdfjs-dist';
const PDFJS: PDFJSStatic = require('pdfjs-dist');
```

I'd much prefer your import, but whenever I do that, I tells me that `PDFJS` is undefined.
Any hints?

**Comment by JaviRpo** [comment] 2019-02-12 05:42
@jzgoda Do you have some example to help me?

**Comment by jzgoda** [comment] 2019-02-12 12:32
@JaviRpo, I wrote this as a sample app to show how to get PDF.js working with Angular (7.1 at the time I wrote it): https://github.com/jzgoda/ng-pdfjs/tree/master/src/app

**Comment by JaviRpo** [comment] 2019-02-13 03:18
@jzgoda thanks for your help. I have one more question for you. 

Why did you put this code?
![image](https://user-images.githubusercontent.com/8562436/52684007-b2f79e80-2f12-11e9-95aa-fa01c40a1b24.png)

With that code, I have a new Thread per pdf opened
![image](https://user-images.githubusercontent.com/8562436/52684111-108beb00-2f13-11e9-8427-ac1bf22a1f3d.png)

If I modified the code a little bit to load 5 times the pdf
![image](https://user-images.githubusercontent.com/8562436/52684161-3a451200-2f13-11e9-88d0-cf1e923e39a0.png)

I have more Threads
![image](https://user-images.githubusercontent.com/8562436/52684179-4f21a580-2f13-11e9-98cf-75025bf457ea.png)

Now, if I remove those lines
![image](https://user-images.githubusercontent.com/8562436/52684246-9ad44f00-2f13-11e9-84f5-2e7242785cf8.png)

the PDF is still loading with a warning and an error per pdf loaded
![image](https://user-images.githubusercontent.com/8562436/52684288-c5260c80-2f13-11e9-818c-cfdc870a4d45.png)

So,
- Why did you put this code?
- Is there something missing?

**Comment by jzgoda** [comment] 2019-02-13 03:44
I was following the docs/examples.

See the following links:

https://mozilla.github.io/pdf.js/examples/
https://github.com/mozilla/pdf.js/blob/master/examples/webpack/main.js
https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website

**Comment by rohananarse** [comment] 2020-05-26 06:03
hey  how do we load all the pdfs at once right now it shows only one pdf
