### ISSUE TITLE
Signature info is not rendered in viewer

### ISSUE THREAD

**Issue by melentiev-e** [mozilla/pdf.js#11619] opened 2020-02-20 12:16 UTC
Hello! 
There is a problem with rendering electronic signature info:

**Configuration:**
- Web browser and its version: Chrome 80.0.3987.106 
- Operating system and its version: Windows 10 (1909)
- PDF.js version: PDF.js: 2.4.370
- Is a browser extension: no

**Steps to reproduce the problem:**
1. open demo page http://mozilla.github.io/pdf.js/web/viewer.html
2. upload file from attachment [тест(1).pdf](https://github.com/mozilla/pdf.js/files/4230610/1.pdf)

**Expected behavior:** 
there is signature at the left-bottom corner
screenshot from Chrome PDF viewer extention:
![image](https://user-images.githubusercontent.com/15359190/74932592-dc32f080-53ea-11ea-9179-acc1216603d3.png)

**What went wrong:**
there is no signature info at the left-bottom corner in pdf.js viewer:
![image](https://user-images.githubusercontent.com/15359190/74932588-d89f6980-53ea-11ea-8ebb-fefe044b77df.png)

It is possible to fix rendering of signature info?

**Comment by Snuffleupagus** [comment] 2020-02-20 12:33
Duplicate of #1076.

**Closed** 2020-02-20 22:17 UTC
