### ISSUE TITLE
Cannot import pdfjs-dist in react

### ISSUE THREAD

**Issue by nam0107** [mozilla/pdf.js#13399] opened 2021-05-19 01:24 UTC
-I haved add pdfjs-dist (pull from https://github.com/mozilla/pdfjs-dist#pdfjs) in node_modules, then import pdfjsLib from 'pdfjs-dist' in reactjs throught build or legacy folder but I don't recive any response. Any one can help me. Many thanks
![image](https://user-images.githubusercontent.com/45630755/118745258-fe325180-b87f-11eb-9e61-33f468ee6fc1.png)
This is my error when I try to import from build folder.
Version:  
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "^4.0.3",
- ps: i have install pdfjs-dist from npm but same err :(

**Comment by Snuffleupagus** [comment] 2021-05-19 06:53
First of all, when opening an issue please actually fill out the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md with all of the requested information (rather than just deleting it)!

Secondly, we cannot support React here, and please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Finally, this might be a duplicate of e.g. issue #13248.

**Closed** 2021-05-21 17:49 UTC
