### ISSUE TITLE
Read-only form annotations are not visible if AnnotationMode is set to 1 (Enable)

### ISSUE THREAD

**Issue by jernejjanez** [mozilla/pdf.js#17213] opened 2023-11-02 10:01 UTC
Attach (recommended) or Link to PDF file here: [form-annotations.pdf](https://github.com/mozilla/pdf.js/files/13237118/form-annotations.pdf)

Configuration:
- Web browser and its version: Mozilla Firefox 119.0
- Operating system and its version: Windows 11 Pro 22H2 22621.2428
- PDF.js version: v3.11.174
- Is a browser extension: No

Steps to reproduce the problem:
1. Modify the AnnotationMode of PDFViewerApplicationOptions to 1 (Enable). Default is set to 2 (Enable forms)
2. Open the the attached file (form-annotations.pdf) which has 2 form inputs. One of them is read only.

What is the expected behavior? (add screenshot)

Both form inputs should be visible.

![image](https://github.com/mozilla/pdf.js/assets/9250813/57e0fa9c-b908-4689-b08f-8d9b3631e1f5)

What went wrong? (add screenshot)

Only the first form input is shown. The read only form input is not visible.

![image](https://github.com/mozilla/pdf.js/assets/9250813/afbbae56-b20c-4b34-bdc7-f66b6c8c514c)

Note:

With the same configuration, the issue is not present in PDF.js v3.5.141. From v3.6.172 onward the issue is present.

**Comment by Snuffleupagus** [comment] 2023-11-02 10:34
Duplicate of #17064

---

*For future reference:* It's always a good idea to check that the bug is still present in the `master` branch, see github.com/mozilla/pdf.js#online-demo

**Closed by Snuffleupagus** 2023-11-02 10:34 UTC
