### ISSUE TITLE
Squashed characters of PDFs generated by TCPDF

### ISSUE THREAD

**Issue by my-name** [mozilla/pdf.js#6556] opened 2015-10-23 14:09 UTC
Our PDF documents are generated using TCPDF 6.2.9. When viewing them in a local PDF viewer (like Evince) everything looks fine:

![result-evince](https://cloud.githubusercontent.com/assets/5175793/10692361/508132a0-7991-11e5-9b15-db6ce3ec9a76.png)

However, when viewing the same PDF in Firefox (→ pdf.js, Firefox 41.0.2 on Ubuntu 15.10) the single letters seem to get squashed:

![result-pdf js](https://cloud.githubusercontent.com/assets/5175793/10692360/5080fe0c-7991-11e5-9157-ab932417c032.png)

The font used is [Roboto](https://www.google.com/fonts/specimen/Roboto). I've uploaded a sample PDF to [http://fallgaeuer.fusonic.net/SamplePdf.pdf](http://fallgaeuer.fusonic.net/SamplePdf.pdf).

Information from the JS console:

```
PDF 94753378c76d8179f7e3f37d9f290f25 [1.7 TCPDF 6.2.9 (http://www.tcpdf.org) / TCPDF] (PDF.js: 1.1.215)
```

**Comment by Snuffleupagus** [comment] 2015-10-24 10:14
This is most likely a duplicate of e.g. #5027, #5084, and [bug 1204903](https://bugzilla.mozilla.org/show_bug.cgi?id=1204903).
The issue appears to be that the `/W` (widths array) of the font dictionary lies about the *actual* glyph widths, since they are different from the glyph widths in the font file. According to the [PDF specification](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G8.1695902):
> The width information for each glyph shall be stored both in the font dictionary and in the font program itself. The two sets of widths shall be identical.

**Closed** 2015-12-08 13:01 UTC
Labels: 3-pdf-broken, 4-font-conversion, 4-font-type0
