### ISSUE TITLE
Demo page and build from source prints with a different font

### ISSUE THREAD

**Issue by bertung** [mozilla/pdf.js#6649] opened 2015-11-17 13:05 UTC
PDF.js demo page and the build I made from the source code displays correct but prints in a different font with messed up character spaces. I have tested this on both Mac and Windows. Firefox internal version prints correctly.

**Comment by bertung** [comment] 2015-11-17 13:16
This is exactly what I am seeing #6498

**Comment by timvandermeij** [comment] 2015-11-17 22:01
Closing as duplicate of #6498 in that case.

**Closed by timvandermeij** 2015-11-17 22:01 UTC
Labels: 4-printing
