### ISSUE TITLE
Barcode is not rendered on windows xp.

### ISSUE THREAD

**Issue by bhrt-DS** [mozilla/pdf.js#6340] opened 2015-08-10 13:36 UTC
hi,
  Viewer is not showing bar-code image. after zoom out (performing ctrl + scroll down) bar-code is getting reflected.
OS :: windows xp version 2002 service pack 3
chrome version :: 44.0.2403.130.
PFA,

Normal view:
![normal](https://cloud.githubusercontent.com/assets/13583436/9172661/c3d1d18a-3f92-11e5-8be3-41164125ac6f.JPG)

after zoom out
![zoom_out](https://cloud.githubusercontent.com/assets/13583436/9172673/d779a730-3f92-11e5-84fe-e0e32c078335.JPG)

**Comment by timvandermeij** [comment] 2015-08-10 22:31
Please post an example PDF so we can triage the issue.

**Comment by bhrt-DS** [comment] 2015-08-11 05:56
PDF ::

https://mail.google.com/mail/ca/u/0/?ui=2&ik=45542accea&view=att&th=14f1b533eee16323&attid=0.3&disp=safe&realattid=f_id6xmntz2&zw

**Comment by bhrt-DS** [comment] 2015-08-11 06:30
Pdf ::

https://drive.google.com/file/d/0Bxnd-uL1f4hkUFNsdGNWUUpKbHc/view?usp=sharing

**Comment by bhrt-DS** [comment] 2015-08-11 11:57
Hi,
 Same issue is also reproducing with Mozilla browser.

**Comment by timvandermeij** [comment] 2015-08-11 12:31
I cannot reproduce this using Windows 10 Pro x64, Firefox 39.0.1 and the latest PDF.js development version. Could you perhaps open the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if that resolves the issue. That is the latest version of PDF.js.

**Comment by bhrt-DS** [comment] 2015-08-11 13:24
yes, I already checked provided link, this issue is reproducing with "windows xp" only.

**Comment by timvandermeij** [comment] 2015-08-12 20:16
Could you try to update the graphics drivers, as far as they are still available for Windows XP?

**Comment by bhrt-DS** [comment] 2015-08-16 06:44
I update display driver to latest version but still issue is reproducing.

**Comment by bhrt-DS** [comment] 2015-08-21 07:15
Hi,
  I tried to update graphics drivers of XP to latest version but this is still not working for me.
Any updates from your side?

**Comment by timvandermeij** [comment] 2015-08-30 11:04
Perhaps the issue is related to hardware acceleration? Otherwise please post the contents of the Graphics section of `about:support` from Firefox here.

**Comment by bhrt-DS** [comment] 2015-09-07 10:36
Hi,
 Actually i am using chrome for my application, but same is reproducing with firefox is well, so here's the details of graphic section of Firefox,

Adapter Description	Intel(R) G41 Express Chipset
Adapter Drivers	igxprd32
Adapter RAM	Unknown
Asynchronous Pan/Zoom	none
Device ID	0x2e32
Direct2D Enabled	Blocked for your graphics driver version.
DirectWrite Enabled	false (0.0.0.0)
Driver Date	2-23-2012
Driver Version	6.14.10.5402
GPU #2 Active	false
GPU Accelerated Windows	0/1 Basic (OMTC) Blocked for your graphics driver version.
Subsys ID	00000000
Supports Hardware H264 Decoding	false
Vendor ID	0x8086
WebGL Renderer	Blocked for your graphics driver version.
windowLayerManagerRemote	true
AzureCanvasBackend	skia
AzureContentBackend	cairo
AzureFallbackCanvasBackend	cairo
AzureSkiaAccelerated	0

**Comment by timvandermeij** [comment] 2015-09-07 19:56
Drive date 2-23-2012 is pretty outdated. Also "Blocked for your graphics driver version" does not look good. This really appears to be a driver issue, I'm not sure if it's a PDF.js issue at all.

**Comment by timvandermeij** [comment] 2015-11-17 00:17
This renders exactly the same as Adobe Reader for me using the latest version of PDF.js and up-to-date drivers with Firefox on Windows 10 x64. I really think that the drivers are causing issues for you, not to mention that Windows XP is very old, and the fact that it happens with Chrome and Firefox makes this even more likely for me (there are also messages about features being blocked in the log). I don't think there is anything we can do from the PDF.js side here as this appears to be a configuration fault on the machine, so I'm closing this as invalid.

**Closed by timvandermeij** 2015-11-17 00:17 UTC
Labels: 4-triage-needed
