### ISSUE TITLE
Unrecognisable Blurry Image

### ISSUE THREAD

**Issue by jakejackson1** [mozilla/pdf.js#8083] opened 2017-02-20 01:11 UTC
Link to PDF file: [blurry-background-image.pdf](https://github.com/mozilla/pdf.js/files/786348/blurry-background-image.pdf)

Configuration:
- Web browser and its version: Firefox 51.0.1 (32-bit)
- Operating system and its version: Windows 7
- PDF.js version: Using version bundled with Firefox

Steps to reproduce the problem:
1. View Attached PDF with PDF.js in Firefox

What is the expected behavior? (add screenshot): Adobe Reader correctly shows the image and isn't blurry. PDF.js does not. See screenshot for comparison.

![pdfjs_adobe_reader](https://cloud.githubusercontent.com/assets/2918419/23108721/8d39072e-f765-11e6-9dd7-43be82286d02.png)

**Comment by THausherr** [comment] 2017-02-22 13:53
duplicate of #7731 ? (pattern with giant steps)

**Comment by jakejackson1** [comment] 2017-02-22 22:50
Maybe. I couldn't open the original PDF for that ticket to check if it was the same problem.

**Closed** 2019-03-28 23:01 UTC
Labels: 2-image-quality, 3-pdf-broken, 4-shading-pattern
