### ISSUE TITLE
SVG Renderer not displays some texts

### ISSUE THREAD

**Issue by mishase** [mozilla/pdf.js#14469] opened 2022-01-18 18:39 UTC
Attach (recommended) or Link to PDF file here:
[example-2.pdf](https://github.com/mozilla/pdf.js/files/7891536/example-2.pdf)

Configuration:
- Web browser and its version: Chrome 97.0.4692.71
- Operating system and its version: Windows 11
- PDF.js version: `gulp dist` generated from [master](https://github.com/mozilla/pdf.js/tree/f955b0e20c109919399a35f06bce3a75d7d4caaa)
- Is a browser extension: No

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/43600912/149997936-861169c7-5fb1-4049-b259-f93c5b60462c.png)
![image](https://user-images.githubusercontent.com/43600912/149997963-93e62d8f-4ad7-427a-9961-775ee89f2f93.png)

What went wrong? (add screenshot)
Some texts is not displayed
![image](https://user-images.githubusercontent.com/43600912/149998204-4920948a-f524-45bf-82c8-a8c2489c17cf.png)
![image](https://user-images.githubusercontent.com/43600912/149998220-0992e106-9f90-4b90-a622-17240729c33e.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
PDF.js SVG viewer using built components (examples/svgviewer/index.html)

**Comment by Snuffleupagus** [comment] 2022-01-18 18:44
Duplicate of #10935

Please also note that the SVG-backend is not officially supported, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

**Closed by Snuffleupagus** 2022-01-18 18:44 UTC
