### ISSUE TITLE
Dynamic form rendering not working from Javascript Action

### ISSUE THREAD

**Issue by jegathesan** [mozilla/pdf.js#16222] opened 2023-03-28 08:52 UTC
Sample PDF File: [Sample.pdf](https://github.com/mozilla/pdf.js/files/11087267/level1_v1.0.1.pdf)

**Configuration**:
- Web browser and its version: Firefox 110.0.1 (64-bit)
- Operating system and its version: MacOS 12.6.3
- PDF.js version: 3.3.56 
- Is a browser extension: Yes

**Steps to reproduce the problem:**
1. Open attached PDF file in Firefox browser
2. Select number of entities to 4. 
3. Click "AddPage" button at bottom of pdf. 

**What i went wrong?**

Javascript actions not working. Refer attachment 

<img width="1437" alt="Screenshot 2023-03-28 at 2 19 17 PM" src="https://user-images.githubusercontent.com/7248995/228182506-45eb809e-1603-4bba-8131-71d65ccf73bd.png">

**What is the expected behaviour?**

1. When number of entities getting changed It should render selected number of input fields. 
2. When click on "AddPage", It should add one more page

**Comment by Snuffleupagus** [comment] 2023-03-28 09:15
Duplicate of #14834

**Closed by Snuffleupagus** 2023-03-28 09:15 UTC

**Comment by jegathesan** [comment] 2023-06-29 07:46
The successful problem solver who can assist in squaring away this issue will be rewarded with **1000 AUD**. If you believe you have the necessary skills to troubleshoot this issue, kindly send us a message, outlining your proposed solution. We will follow up with you.
