### ISSUE TITLE
Annotation not letting text visible..only on IE

### ISSUE THREAD

**Issue by samit2015** [mozilla/pdf.js#6914] opened 2016-01-22 09:46 UTC
I m not able to see text under yellow annotation/stamp in IE , while its workign correct on Chrome/FF...

Any suggestion...I tried by removing color:transparent from viewer.css, but it leads to shadow of text.

any help....its urgent,.

![error1](https://cloud.githubusercontent.com/assets/16206635/12507331/1ac13f06-c0c3-11e5-8903-b7d37c06d91a.jpg)
Thanks in advance

**Comment by Snuffleupagus** [comment] 2016-01-22 12:06
Closing as duplicate of issue #5264.

**Closed by Snuffleupagus** 2016-01-22 12:06 UTC

**Comment by samit2015** [comment] 2016-01-22 13:22
Thanks Snuff, #5264 fix is not working for my IE 11 ...any other suggestion
