### ISSUE TITLE
pdfjs text overlapping/distorted for Win7/IE11

### ISSUE THREAD

**Issue by dcostarohan** [mozilla/pdf.js#9932] opened 2018-07-27 20:05 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE11
![ie version](https://user-images.githubusercontent.com/41804994/43344138-af030cb4-91b6-11e8-945a-c4d4354d9417.png)

- Operating System: Win7
- PDF.js version: 1.7.225
- Is a browser extension: no 

Steps to reproduce the problem:
1. Not reproducible on all machines
2. Happens only on some Win7 machines with IE11,

What is the expected behavior? (add screenshot)
PDF text is text readable. 

What went wrong? (add screenshot)
Some text shows up as overlapping/distorted hence unreadable, if we zoom into the viewer it looks fine. 
![capture](https://user-images.githubusercontent.com/41804994/43343943-14dc0b40-91b6-11e8-9ec3-c93c9b7f8f1c.PNG)

No issues while printing or saving. Have already tried the compatibilty.js solution. 
as per https://stackoverflow.com/questions/31542835/pdf-js-not-rendering-pdf-correctly-in-ie

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Internal to site hence cant be provided. Also Issue is reproducible only on some machines of Win7/IE11

**Comment by timvandermeij** [comment] 2018-07-27 22:05
It looks like a graphics driver issue. Check if there are updates for your graphics drivers and install them.

**Comment by timvandermeij** [comment] 2018-08-02 21:39
Closing since the issue does not look related to PDF.js itself, but rather to graphics driver issues (enforced by the fact that it can only be reproduced on some machines).

**Closed by timvandermeij** 2018-08-02 21:39 UTC
Labels: 1-other
