### ISSUE TITLE
Getting error while trying to load a pdf file in jsp from local storage.

### ISSUE THREAD

**Issue by nikhilreddy93** [mozilla/pdf.js#7736] opened 2016-10-19 06:53 UTC
`var url = 'D:/IIV3Project/Documents/Invoices/invoices/invoice.pdf';
PDFJS.getDocument(url) .then(function(pdf) {
	    	var elem = document.getElementById('myCanvas');
	    	$(".document").on('dblclick',function() {
	    	elem.addEventListener('dblclick', function() {
	    	}, false);
	    	    	        var index = $(this).attr("id");
	    	    	 });
	    });`

Below is the error i'm getting
![pdfjs error](https://cloud.githubusercontent.com/assets/12526688/19508425/d907560e-95f6-11e6-8447-cfbea7e5c034.PNG)

**Comment by Snuffleupagus** [comment] 2016-10-19 10:07
The problem, that `XMLHttpRequest` isn't allowed for `file://` URLs, is clearly indicated in your screen-shot of the error messages.
This is *not* a PDF.js issue, but rather a browser specific issue, and the solution is to use a local server instead. Please note that this browser limitation is mentioned in https://github.com/mozilla/pdf.js#getting-the-code.

Closing as answered/invalid.

**Closed by Snuffleupagus** 2016-10-19 10:07 UTC

**Comment by nikhilreddy93** [comment] 2016-10-19 10:51
Thanks for reply, I need some clarification on this, so as per your answer the above code should work fine with the local file reading. am i correct?

**Comment by yurydelendik** [comment] 2016-10-19 12:29
> I need some clarification on this, so as per your answer the above code should work fine with the local file reading. am i correct?

No, you are not. Due to your browsers limitation XHR cannot read from local file.

**Comment by nikhilreddy93** [comment] 2016-10-19 12:37
@yurydelendik okay, then how can i read from local storage. pls help.

**Comment by yurydelendik** [comment] 2016-10-19 12:54
> how can i read from local storage

By design of some browsers you cannot. Please view docs how to read using XMLHttpRequest from local file and what are limitation for your particular browser. You can also find way how to loosen this limitation for your use case. Notice that this question is not related to PDF.js.

**Comment by nikhilreddy93** [comment] 2016-10-19 12:56
Fine, thanks.
