### ISSUE TITLE
Zoom button overlaps with page count if language has a longer word for "Page" (e.g. "Página") or has many pages in the PDF

### ISSUE THREAD

**Issue by Thunderforge** [mozilla/pdf.js#6262] opened 2015-07-23 20:56 UTC
The default PDF has a toolbar that looks like this:

![image](https://cloud.githubusercontent.com/assets/6200170/8861912/b9d1206c-3152-11e5-9040-aa9066393ecb.png)

If you change the language to something that has a word for "Page" that is longer than that of English, such as Spanish, the zoom button can overlap with the page count:

![image](https://cloud.githubusercontent.com/assets/6200170/8861901/ae20603e-3152-11e5-9bcc-fa60d306ac68.png)

It appears that this can also happen if you view a PDF with a large number of pages. For instance, if there are over 1,000, then then zoom out sign is very close to the page count, and if you mouse over the count, the button highlight clearly overlaps with the page count:

![image](https://cloud.githubusercontent.com/assets/6200170/8861975/0b82ab1a-3153-11e5-95ca-23d00b9aa2e8.png)

Note that this happens with a screen size as small as 800px. Sometimes you have to increase or decrease the window size by about 50 px before this happens, since there is some resizable spacing between certain components.

**Comment by Snuffleupagus** [comment] 2015-07-23 20:58
This is probably a duplicate of issue #3683.

**Comment by Thunderforge** [comment] 2015-07-23 21:06
That issue does address the fact that it can be triggered by language changes, but not that it can be triggered by PDFs with many pages. So it's a partial duplicate?

**Comment by timvandermeij** [comment] 2015-07-23 21:55
The cause is the same (namely not enough space), so I have added to #3683 that a large page number can also cause this effect. We will track the issue there and the overall responsiveness issue in #6191, so we can close this.

**Closed by timvandermeij** 2015-07-23 21:55 UTC
