### ISSUE TITLE
How to force the highlighting engine to only handle the visible page/parts of the PDF displayed?

### ISSUE THREAD

**Issue by ribeaud** [mozilla/pdf.js#7932] opened 2017-01-06 10:43 UTC
Hi,

## Configuration
- Web browser and its version: Chrome v53.0.2785.143 m, IE 11
- Operating system and its version: Windows 7 Enterprise
- PDF.js version: v1.6.210
- I am using the available **viewer** (`viewer.js`, ...) with range requests.

## Description
This is more a question than an issue. But I did not find a better place to ask it.

I am working with huge PDFs (_500MB_ in worst cases and around _200MB_ is quite usual). **PDF** is maybe NOT the most appropriate format but, for now, this is OK.

I noticed the following in the whole process of displaying a certain **PDF** (kindly let me know if I am wrong):

1. **PDF** is completely downloaded by the client.
2. If a `search` parameter has been provided, then matches highlighting is starting in the background over the whole document (by clicking on the find button, one could see the ongoing process):
![highlighting](https://cloud.githubusercontent.com/assets/13186156/21715324/2604e688-d404-11e6-8091-81aae9d9e6e8.png)
This process is really slow in **IE**: if I jump to one of the last pages (using `page` parameter) once the whole document has been downloaded to client side, highlighting will NOT work in that case because the highlighting searching process is NOT finished yet.

Actually, would it not make more sense to highlight only matches which are in the visible parts of the **PDF** displayed? Respectively, how to do this?

Thanks for your time and the great work. Wish you a wonderful day.

Respectful,

Christian

**Comment by matt-curtis** [comment] 2017-01-14 22:11
Where or how are are said 200+ MB PDFs coming from / being made?

**Comment by ribeaud** [comment] 2017-01-17 18:34
Good evening,
Sorry for the late response. The PDFs are scanned books done by a tool called **ABBYY Recognition Server**. I am joining some **PDF** properties screenshots:
![pdf](https://cloud.githubusercontent.com/assets/13186156/22034198/bd766db2-dceb-11e6-9e5b-506265ebae39.png)
![pdf_bc002414491_isbn3856402853](https://cloud.githubusercontent.com/assets/13186156/22034201/bfaf448c-dceb-11e6-88e8-001e625c8284.png)
But I do NOT understand how this could play a role here. Or do I miss something? Cheers,
christian

**Comment by ribeaud** [comment] 2017-02-19 10:47
Hi,

Might I ask you how does it look like? Do you need more input from my side? Do you plan to fix this issue in a near future? Does this issue even make sense to you?

This issue is quite **critical** for us. I could help and try to fix it. But then, I would appreciate if you could give me some starting point: how the _highlighting_ is working and what would be a possible way to fix the issue.

Thanks for your feedback and your time.

Cheers and have a great day,

christian

**Comment by timvandermeij** [comment] 2017-02-19 13:59
Most of the highlighting (finding) code is here: https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js. It may be possible there to check with pages are in view and search only those, but I have not really looked into this. Hopefully this at least gives you a starting point.

**Comment by Snuffleupagus** [comment] 2017-02-19 14:27
Quoting from https://github.com/mozilla/pdf.js/issues/7932#issue-199170233:
> This process is really slow in IE: if I jump to one of the last pages (using page parameter) once the whole document has been downloaded to client side, highlighting will NOT work in that case because the highlighting searching process is NOT finished yet.

It thus seem that this is really an issue that is caused by the comparatively sub-par performance, and the missing features, of JavaScript as it exists in Internet Explorer (compared with e.g. Firefox and Chrome).
For example, note that IE doesn't support Promises natively, which PDF.js uses extensively, and that they thus need to be polyfilled (which is slow).

> Do you plan to fix this issue in a near future? Does this issue even make sense to you?

At this point, no version of IE could be considered to be a modern browser, and in *my* opinion it's simply a waste of both developer and reviewer time to try and hack around these limitations in Internet Explorer (unless it's limited to very simple polyfills, such as those in https://github.com/mozilla/pdf.js/blob/master/web/compatibility.js).

**Comment by Snuffleupagus** [comment] 2017-02-19 14:30
> It may be possible there to check with pages are in view and search only those, but I have not really looked into this. Hopefully this at least gives you a starting point.

Couldn't that very easily break the entire search functionality, or the users expectation of how it *should* work, since the whole point of searching ought to be to be able to find things not currently in view!?

**Comment by timvandermeij** [comment] 2017-02-19 14:35
> Couldn't that very easily break the entire search functionality, or the users expectation of how it should work, since the whole point of searching ought to be to be able to find things not currently in view!?

I definitely agree. I was only giving an idea to achieve:

> Actually, would it not make more sense to highlight only matches which are in the visible parts of the PDF displayed? Respectively, how to do this?

since that was asked specifically. I don't think it's a good idea either, and to be fair this does sound like an IE-specific issue because it lacks support for a lot of modern web features.

I'm closing this issue as answered since I don't think there is anything we could or should do on the PDF.js side.

**Closed by timvandermeij** 2017-02-19 14:35 UTC
Labels: 1-viewer, 4-text-selection

**Comment by Snuffleupagus** [comment] 2017-02-19 14:52
> Actually, would it not make more sense to highlight only matches which are in the visible parts of the PDF displayed? Respectively, how to do this?

Note that highlighting already isn't applied unless the page has actually been rendered *and* has a `textLayer`; please refer to https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js#L315.

Furthermore, note also that *one* of the reasons that searching continues after the first match has been found, regardless of whether "highlight all" is active or not, is to be able to display a counter of the number of results; see https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js#L240.

**Comment by ribeaud** [comment] 2017-02-20 08:33
Hi. Thanks a lot for your feedback. I see and understand your points. Just two last remarks from my side:
1. Because of hugeness of some PDFs, we somehow _externalize_ the search functionality (using a **Solr** index). In short, our users do NOT use the search functionality coming along with the library: they get a list of matches. Each match is a link to a given page of the original **PDF**. This works quite well actually.
1. The problem is noticeable with **Chrome** as well. But *IE* is especially slow.

But, as you mentioned, this could be too specific for the **pdf.js** library so that I will have to handle this by myself. Now I have some starting points I should look at. I allow me to come back to you if I have some more questions.

Wish you a good one. And thanks a lot again for your time and work.

**Comment by blenzi** [comment] 2023-03-07 05:30
Hello, I am dealing with large PDFs as well and trying to externalise the search functionality (to ElasticSearch instead of Solr). Would you have an example, please?

Thanks a lot

**Comment by ribeaud** [comment] 2023-03-07 08:05
Hi @blenzi. Kindly send me a private message (`risky'at'chri.ch`) if you are interested in a demo.
