### ISSUE TITLE
Incorrect page width for default scale

### ISSUE THREAD

**Issue by alex-lancer** [mozilla/pdf.js#10486] opened 2019-01-24 06:00 UTC
I open a PDF document and I now that its page width should be about 1200px (I see this width in FoxidReader or any other viewer when zoom is set to actual size or 100%) but when I retrieve viewport with scale = 1 the pages width is about 580px

```
var viewport = page.getViewport(1);
console.log(viewport.width); // <---- this will show approximately 580px
```

Configuration:
- Chrome, FF, IE, Edge, Opera
- Any OS
- PDF.js version: 1.9.426
- Is a browser extension: No

What is the expected behavior? 
Page width for scale = 1 is 1200px as in desctop viewers

What went wrong?
Page width is about 580px instead of 1200

Link to a viewer
Viewer is not used

**Comment by Snuffleupagus** [comment] 2019-01-24 08:58
You need to provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue. If you ignore the `Attach (recommended) or Link to PDF file here:` point in particular, the issue is incomplete and will be closed as such (since it's impossible for anyone to help without access to the PDF file).

> Link to a viewer
> Viewer is not used

Since this is apparently an issue related to a custom implementation of the library, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment] 2019-01-24 22:05
Closing since it's not actionable now. Please provide the requested information to reopen.

**Closed by timvandermeij** 2019-01-24 22:05 UTC
