### ISSUE TITLE
The tops of some of the letters are cutoff when viewing at different zoom levels 

### ISSUE THREAD

**Issue by anandpanse123** [mozilla/pdf.js#9225] opened 2017-12-01 16:16 UTC
Attach (recommended) or Link to PDF file here:
http://fundcompli.rightprospectus.com/documents/TIAACREFVA/TIAA_VA-1_soi.pdf

Configuration:
- Web browser and its version: All
- Operating system and its version: All
- PDF.js version: latest
- Is a browser extension: NA

Steps to reproduce the problem:
1. Open PDF file ( http://fundcompli.rightprospectus.com/documents/TIAACREFVA/TIAA_VA-1_soi.pdf) in Pdf Js Viewer.
Issue can be seen when we open PDF here - https://mozilla.github.io/pdf.js/web/viewer.html
2. The tops of some of the letters are cutoff when viewing at different zoom levels. Please find below screen shots at different zoom levels

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/33266067/33491444-50fbd28e-d688-11e7-8f52-2d1a68252a77.png)

What went wrong? (add screenshot)
Zoom Level - 100%
![image](https://user-images.githubusercontent.com/33266067/33491685-fd95cd24-d688-11e7-9784-b50016b1c4c7.png)

Zoom Level - Automatic 
![image](https://user-images.githubusercontent.com/33266067/33491662-f2b3bb78-d688-11e7-89ce-ccbc85e4b5ed.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): NA

**Comment by timvandermeij** [comment] 2017-12-01 20:45
I can reproduce this using Firefox 57.0.1 on Arch Linux.

**Comment by Snuffleupagus** [comment] 2021-05-31 11:43
> Attach (recommended) or Link to PDF file here:
> http://fundcompli.rightprospectus.com/documents/TIAACREFVA/TIAA_VA-1_soi.pdf

It appears that the linked document has changed (which is why we advice to *attach* files rather than linking them), since it no longer agrees with the screen-shots posted above.

The currently available PDF file does *not*, as far as my testing goes, seem to reproduce the original issue; hence closing this issue as WORKSFORME.

**Closed by Snuffleupagus** 2021-05-31 11:43 UTC
Labels: 1-viewer
