### ISSUE TITLE
Update `puppeteer` to version 19.1.0+

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#15865] opened 2022-12-25 12:13 UTC
As can be seen from the first round of testing in PR #15864, trying to update Puppeteer beyond version `19.0.0` completely breaks testing in Firefox. Curiously it does work locally when the `--noChrome` flag is being used, so it seems to be an issue with running tests in both Chrome *and* Firefox in parallel.

We need to fix this, likely by making some adjustments to our test-suite, such that we don't get "stuck" on an older version of Puppeteer without being able to update. (A temporary work-around could also be to disable testing in Chrome.)

**Comment by timvandermeij** [comment] 2023-01-01 13:59
In the logs the following is visible:

```
Error while starting firefox: Failed to launch the browser process! spawn /home/ubuntu/.cache/puppeteer/chrome/linux-1069273/firefox/firefox ENOENT
```

This is interesting because ENOENT seems to indicate the browser binary is missing somehow. The Puppeteer issue tracker has some pointers on this (https://github.com/puppeteer/puppeteer/search?q=enoent) but in general this can have a wide variety of causes. It's a bit more fortunate that this also seems to happen locally (I haven't tested it myself yet) because if we can reproduce this it will at least be easier to track down than having a bot-only issue...

**Comment by timvandermeij** [comment] 2023-01-01 14:17
Looking at the error more closely, and also reproducing it locally now, the whole path mentioned there doesn't make sense at all. Firefox lives in a separate folder, not inside the Chrome folder, since during installation the following is logged for me locally: `/home/timvandermeij/.cache/puppeteer/firefox/linux-110.0a1`.

Therefore, the issue that Puppeteer 19.1.0+ are apparently trying to look for the Firefox binary in the wrong path :-/

**Comment by timvandermeij** [comment] 2023-01-01 15:22
I figured out that if we swap Firefox and Chrome in `test.js` that Firefox will start and Chrome won't. Therefore, it indeed looks like Puppeteer 19.1.0+ introduces a bug/race condition that overwrites the browser fetcher state of the first browser while it's still starting if the second browser is started at the same time.

It's possible that this was actually already an issue in the way we create the browser sessions, but we were just lucky enough to never have it surface until recent internal changes in Puppeteer.

In any case, this is fixable in our code (which leads me to believe our code is using an unintended way of spawing the browsers) since we have to wait until the browser is actually started before going to the next one. I already have a hothacked version working, but this will require a bit of refactoring that I want to think about more.

**Comment by timvandermeij** [comment] 2023-01-01 18:19
I'm now 100% sure this is an upstream bug in Puppeteer and made a minimal reproducer to prove it. I'll report it to the Puppeteer issue tracker to get it fixed since it's a regression from a change made in version 19.1.0, which explains why we didn't run into it before. I think we should await that bugfix first because most likely we won't have to change our code at all once fixed.

**Comment by timvandermeij** [comment] 2023-01-29 16:51
Ugh, the original issue I filed upstream is fixed in Puppeteer 19.6.0, but now I've uncovered another (similar) bug in Puppeteer that sadly also prevents us to update :-(

I made a reduced test case again for the Puppeteer team and I'll report it to them as soon as I bisected in which release this broke exactly.

**Comment by timvandermeij** [comment] 2023-05-14 14:12
It looks like we can proceed with this again now that the upstream issues have been fixed. I have Puppeteer 20 mostly working now if we start the browsers in series (which all in all seems like a better idea anyway and it's how Puppeteer expects that API to be used). However, I still need to do more testing and fix the cleanup of old browser revisions (which I ignored for now to first get things working) since the Puppeteer 20 APIs for that are sadly not complete yet. I have opened https://github.com/puppeteer/puppeteer/issues/10174 for that, but fortunately I don't see that as a blocker since there seems to be a way around it; it's just a bit more code than I had hoped, but if it allows us to unblock the updates again that seems more important (and the code can become prettier later on if this feature request is implemented).

I'll try to get this done next week.

**Comment by Snuffleupagus** [comment] 2023-05-14 14:49
> I have Puppeteer 20 mostly working now if we start the browsers in series

What does running tests in series mean for the (overall) run-time of the test-suites?
Given that the bots aren't exactly fast as-is, it would be a little bit unfortunate if things became even slower.

**Comment by timvandermeij** [comment] 2023-05-18 10:47
The Puppeteer team implemented the `trimCache` functionality in https://github.com/puppeteer/puppeteer/pull/10199 after our request, so once that is released the code on our side will become much simpler, which should resolve the final issue for the upgrade.

**Closed** 2023-05-29 16:56 UTC
Labels: test, dependencies
