### ISSUE TITLE
Gradient is rendered incorrect

### ISSUE THREAD

**Issue by JanSlabon** [mozilla/pdf.js#10720] opened 2019-04-09 10:00 UTC
Attach (recommended) or Link to PDF file here: [gradient.pdf](https://github.com/mozilla/pdf.js/files/3058263/gradient.pdf)

Configuration:
- Web browser and its version: FF Quantum 66.0.1 
- Operating system and its version: Win 10
- PDF.js version: 2.2.129

Steps to reproduce the problem:
1. Open https://mozilla.github.io/pdf.js/web/viewer.html
2. Load the attached [PDF](https://github.com/mozilla/pdf.js/files/3058263/gradient.pdf)

What is the expected behavior?
![grafik](https://user-images.githubusercontent.com/12390057/55791405-b8123d80-5abe-11e9-81bc-931e5ffee296.png)

What went wrong?
![grafik](https://user-images.githubusercontent.com/12390057/55791434-c52f2c80-5abe-11e9-8fbd-5ec1aef30023.png)

**Comment by timvandermeij** [comment] 2019-04-09 21:20
It looks like this is a duplicate of #10680, but I'm not entirely sure.

**Comment by THausherr** [comment] 2019-04-10 09:45
Yeah, both issues are about type 7 shadings. This time it looks more obvious, the white areas are clearly angled white shapes, i.e. areas not painted.

**Comment by timvandermeij** [comment] 2019-04-10 21:34
Closing since this is a duplicate then. Thanks!

**Closed by timvandermeij** 2019-04-10 21:34 UTC
Labels: 1-core, 2-image-quality
