### ISSUE TITLE
PDF does not render correctly on Retina screens

### ISSUE THREAD

**Issue by tomaszczura** [mozilla/pdf.js#15989] opened 2023-02-01 06:51 UTC
Attach (recommended) or Link to PDF file here: [test-pdf.pdf](https://github.com/mozilla/pdf.js/files/10553987/test-pdf.pdf)

**Configuration:**
- Web browser and its version: Chrome 109.0.5414.119, Firefox 109.0.1
- Operating system and its version: MacOS 13.1
- PDF.js version:  3.3.122 (tested on https://mozilla.github.io/pdf.js/web/viewer.html)

**Steps to reproduce the problem:**
1. Open https://mozilla.github.io/pdf.js/web/viewer.html on retina screen
2. Upload `test-pdf.pdf`
3. Switch scale to 50% and scroll right

**What went wrong?** 
PDF looks bad on Retina screens - looks like part of it rendered correctly (black border), but the rest is too small:
<img width="1430" alt="Zrzut ekranu 2023-02-1 o 07 50 14" src="https://user-images.githubusercontent.com/2226792/215971895-4c5972aa-2b79-4c86-ab61-839f09f15c87.png">

**What is the expected behavior?**
This looks good on non-retina screens:
![Zrzut ekranu 2023-02-1 o 07 51 00](https://user-images.githubusercontent.com/2226792/215972020-d2e260fe-6a91-4415-a901-35f51f85895f.png)

**Comment by Snuffleupagus** [comment] 2023-02-01 09:25
Duplicate of #14982

**Closed by Snuffleupagus** 2023-02-01 09:25 UTC
