### ISSUE TITLE
After importing PDF, unexpected patterns are rendered.

### ISSUE THREAD

**Issue by QM36** [mozilla/pdf.js#13486] opened 2021-06-04 06:34 UTC
Attach (recommended) or Link to PDF file here: [1.pdf](https://github.com/mozilla/pdf.js/files/6596204/1.pdf)

Configuration:
- Web browser and its version: Google Chrome（90.0.4430.212）  Firefox（87.0）
- Operating system and its version: macOs Catalina (10.15.7 (19H1217))
- PDF.js version: v2.9.359
- Is a browser extension:  no

Steps to reproduce the problem:
1.   Download this pdf.js code
2. Start a local web server and open`http://localhost:8888/web/viewer.html`
3. Select the import file button

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/32392850/120755990-45d40100-c541-11eb-91af-12ec499a3b1a.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/32392850/120756034-53898680-c541-11eb-8a64-03f3fc22216d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Thanks for your help!!

**Comment by 1554312244** [comment] 2021-06-04 07:11
插眼！随时关注！

**Comment by SamyCookie** [comment] 2021-06-04 15:11
from console logs:
```
PDF aa89d9ded106cbb3e88bbacf7633ef6a [1.3 macOS 版本10.15.7（版号19H1217） Quartz PDFContext / Adobe Acrobat 9.0] (PDF.js: 2.9.45)
Warning: JPX: Trying to recover from: "JPX error: Out of packets".
```

**Comment by SamyCookie** [comment] 2021-06-04 15:13
seems to be a duplicate of #11957

**Comment by timvandermeij** [comment] 2021-06-04 18:11
Yes, closing as such.

**Closed by timvandermeij** 2021-06-04 18:11 UTC
Labels: 4-image-conversion, 4-image-jpx

**Comment by linfangrong** [comment] 2021-07-16 05:35
@QM36  https://github.com/mozilla/pdf.js/issues/11957
