### ISSUE TITLE
Crashes when rendering an OCRed PDF page on Firefox (works on Chrome, Safari)

### ISSUE THREAD

**Issue by mrtcode** [mozilla/pdf.js#14726] opened 2022-03-29 06:52 UTC
Attach (recommended) or Link to PDF file here:
[Granato.-.1996.-.Cultural.Values.Stable.Democracy.and.Economic.De.pdf](https://github.com/mozilla/pdf.js/files/8368671/Granato.-.1996.-.Cultural.Values.Stable.Democracy.and.Economic.De.pdf)

Configuration:
- Web browser and its version: Firefox 98.0.2
- Operating system and its version: macOS 12.3
- PDF.js version: v2.14.110
- Is a browser extension: no

Steps to reproduce the problem:
1. Just open the attached file and wait.

What went wrong?
A page gets rendered, but the loading spinner is still visible, and then suddenly it crashes with the page becoming blank.

```
PDF.js v2.14.110 (build: 0dd6bc9a8)
Message: 
Stack: getCanvas@https://mozilla.github.io/pdf.js/build/pdf.js:4926:27
paintInlineImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:7135:45
paintImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:7088:10
executeOperatorList@https://mozilla.github.io/pdf.js/build/pdf.js:5688:20
_next@https://mozilla.github.io/pdf.js/build/pdf.js:3382:37
__webpack_modules__</_scheduleNext/<@https://mozilla.github.io/pdf.js/build/pdf.js:3370:14
```

Works on Chrome and Safari, but rendering is slow and memory usage can be very high (3 GB).

**Comment by Snuffleupagus** [comment] 2022-03-29 08:40
Duplicate of #13643 (or possibly #6741).

**Closed by Snuffleupagus** 2022-03-29 08:40 UTC
