### ISSUE TITLE
iOS test selection is hard on certain b

### ISSUE THREAD

**Issue by paolocaminiti** [mozilla/pdf.js#7888] opened 2016-12-12 16:29 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Safari mobile
- Operating system and its version: iOS 9.3
- PDF.js version: 1.6.210
- Is an extension: false

Steps to reproduce the problem:
1. load the pdf viewer in safari with the linked pdf
(one easy way if you can access your machine over the network is: gulp generic; http-server in root; put the linked filename as default in build/generic/dev/viewer.js; copy the file in build/generic/dev/)
2. try to highlight the text

What is the expected behavior? (add screenshot)
Text elements should be highlighted consistently between the anchor and focus handlers.
![screen shot 2016-12-12 at 16 17 24](https://cloud.githubusercontent.com/assets/677599/21106611/9529dff0-c086-11e6-91ef-6ac6b09880c9.png)

What went wrong? (add screenshot)
The text selection is mostly disrupted although the anchor and focus handlers are correct, note that the textLayer elements are instead in the correct position rightly behind each word. Also it sometimes switches to rectangle selection instead of text span. (please ignore the safari menu on top)
![screen shot 2016-12-12 at 16 17 08](https://cloud.githubusercontent.com/assets/677599/21106614/98190164-c086-11e6-9be2-79986adbf722.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): None

**Comment by timvandermeij** [comment] 2016-12-13 22:38
The PDF file has not been provided. Please upload it here to GitHub or provide a link to where it's hosted.

**Comment by paolocaminiti** [comment] 2016-12-13 22:45
Oh sorry, I tought I provided the link in the message, here it is from the open access website:
http://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0166083&type=printable

**Comment by timvandermeij** [comment] 2016-12-13 22:49
The text flow in the PDF file appears to be normal. Labeling as iOS-specific at this moment.

**Comment by yurydelendik** [comment] 2017-07-25 16:33
Duplicate of #1803

**Closed by yurydelendik** 2017-07-25 16:33 UTC
Labels: 4-os-ios, 4-text-selection
