### ISSUE TITLE
first page of PDF goes blank after a period of time (minimising chrome or switching tabs)

### ISSUE THREAD

**Issue by wallaceturner** [mozilla/pdf.js#18116] opened 2024-05-19 23:35 UTC
Occurs on my local dev and also the dev site
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Version 124.0.6367.208 (Official Build) (64-bit)
- Operating system and its version: Windows 11
- PDF.js version: (latest 4.2.67)
- Is a browser extension: No

Steps to reproduce the problem:
1.  Navigate to https://mozilla.github.io/pdf.js/web/viewer.html in chrome
2. Open a new tab 
3. wait about 1-2min and switch back to the tab with pdf.js

What is the expected behavior? (add screenshot)
Expected behaviour is for the screen not to be blank
![image](https://github.com/mozilla/pdf.js/assets/2849980/98415d85-b708-44d8-8a23-5bbb1a220779)

If you scroll down the other pages are showing correctly

**Comment by Snuffleupagus** [comment] 2024-05-20 06:25
Duplicate of #18100

**Closed** 2024-05-20 06:25 UTC
