### ISSUE TITLE
Addon for Firefox Android?

### ISSUE THREAD

**Issue by upsuper** [mozilla/pdf.js#7483] opened 2016-07-13 14:40 UTC
The PDF Viewer addon on addons.mozilla.org seems to have discontinued because Firefox has been shipping with PDF.js already. But that isn't the case for Firefox Android.

It's obvious that Firefox Android doesn't include PDF.js, probably for package size consideration. And that makes viewing PDF very hard on Firefox Android. It has to download and invoke external app to open PDF files.

I hope there could be an addon for Firefox Android to view PDF directly. And ideally, Firefox Android could ask user to install that addon when user tries to open any PDF.

**Comment by Snuffleupagus** [comment] 2016-07-13 14:48
Closing as duplicate of issue #6136.

**Closed by Snuffleupagus** 2016-07-13 14:48 UTC
