### ISSUE TITLE
Font rendering on Chrome: PDF.js on Arch Linux x86_64

### ISSUE THREAD

**Issue by ghost** [mozilla/pdf.js#4903] opened 2014-06-07 14:49 UTC
These font rendering issues are accompanied by "Warning: Error during font loading: Font X is not available"/"Warning: fontRes not available" warnings.

Observed since at least Chromium/Chrome 33; was not using before. Also observed on Firefox 28 and 29. Currently using Google Chrome 37.0.2031.2 dev on an Arch Linux x86_64 setup.

~/.fonts.conf, ~/.config/fontconfig/fonts.conf, /etc/fonts/local.conf:

```
<fontconfig>
  <match target="font">
    <edit mode="assign" name="rgba">
      <const>rgb</const>
    </edit>
    <edit mode="assign" name="hinting">
      <bool>true</bool>
    </edit>
    <edit mode="assign" name="hintstyle">
      <const>hintslight</const>
    </edit>
    <edit mode="assign" name="antialias">
      <bool>true</bool>
    </edit>
    <edit mode="assign" name="lcdfilter">
      <const>lcddefault</const>
    </edit>
  </match>
</fontconfig>
```

~/.Xresources:

```
Xft.autohint: 0
Xft.dpi: 96
Xft.antialias: true
Xft.rgba: rgb
Xft.hinting: true
Xft.hintstyle: hintslight
Xft.lcdfilter: lcddefault
```

Screenshots:

![screenshot from 2014-06-07 10 46 05](https://cloud.githubusercontent.com/assets/7730129/3208989/e8b2f20a-ee52-11e3-994d-a7dc6828bc8b.png)
![screenshot from 2014-06-07 10 46 18](https://cloud.githubusercontent.com/assets/7730129/3208990/e8b3effc-ee52-11e3-956d-d2d115e59c15.png)

**Comment by Snuffleupagus** [comment] 2021-09-26 08:48
Closing this issue, for the following reasons:
 - The documents mentioned in https://github.com/mozilla/pdf.js/issues/4903#issuecomment-45420635 do not produce any warnings/errors now, and also seem to render well.
 - According to https://github.com/mozilla/pdf.js/issues/4903#issuecomment-45432221 this wasn't reproducible everywhere even with the same OS, hence it could very well be specific to a *particular* configuration.
 - The issue is fairly old, and furthermore the reporter is no longer around (replaced by the "ghost"-account).

**Closed by Snuffleupagus** 2021-09-26 08:48 UTC
Labels: 4-font-conversion
