### ISSUE TITLE
Text annotations with line breaks lose their first line

### ISSUE THREAD

**Issue by StevenSwitten** [mozilla/pdf.js#17079] opened 2023-10-06 12:46 UTC
Attach (recommended) or Link to PDF file here: Can be reproduced on the demo page: https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Chrome latest
- Operating system and its version: Windows
 

Steps to reproduce the problem:
**1.  Click the Text annotation button
2. Type something. Press enter key. Type some more
3. Save the PDF**

What is the expected behavior? (add screenshot)
**The new PDF should have the full text annotation**

What went wrong? (add screenshot)
**The first line of the text annotation is omitted**

![image](https://github.com/mozilla/pdf.js/assets/30682786/dab1fd9c-64c7-44d4-8226-d3e264b3b988)

![image](https://github.com/mozilla/pdf.js/assets/30682786/43755b0d-2df5-450a-a022-423133449b53)

**Comment by calixteman** [comment] 2023-10-06 13:04
Could you share the saved pdf please ?

**Comment by jatinder14** [comment] 2024-01-07 18:12
@Snuffleupagus  @StevenSwitten @calixteman  I want to resolve this issue .
would you be able to assign it to me ?

**Comment by Ztong55** [comment] 2024-01-08 03:29
I was stuck with this problem. I have find that this is caused by '#content' of text editor is different from the actual inner text of the text editor.

**Comment by jatinder14** [comment] 2024-01-08 10:32
@Ztong55  so should i fix it or no?

**Comment by Ztong55** [comment] 2024-01-08 10:43
@jatinder14 I am only a user of this package and can't decide whether you shall fix it.

**Comment by jatinder14** [comment] 2024-01-08 10:50
> I was stuck with this problem. I have found that this is caused by '#content' of text editor is different from the actual inner text of the text editor.

can you explain it more with screenshots or videos that could help me fixing it fast
I don't understand what are you saying

**Closed** 2024-01-15 09:40 UTC
Labels: annotations, chrome-specific, editor
