### ISSUE TITLE
Embedded PDF viewer does not display check marks inside check boxes correctly. I am using material UI.

### ISSUE THREAD

**Issue by write2nitinmalik** [mozilla/pdf.js#10524] opened 2019-02-06 15:27 UTC
Checkboxes are not coming as marked when viewing from the PDF viewer. I am using PDF.js(1.7.225) version
[document (2).pdf](https://github.com/mozilla/pdf.js/files/2836947/document.2.pdf)
 and material UI on the front end.

**Comment by timvandermeij** [comment] 2019-02-06 22:30
The font cannot be loaded: `Warning: Error during font loading: Font Helv is not available`

**Comment by write2nitinmalik** [comment] 2019-02-07 05:17
@timvandermeij what could be the possible solution to load the fonts or is it something which is handled by pdf.js

**Comment by Snuffleupagus** [comment] 2019-02-07 10:37
>  I am using PDF.js(1.7.225) version

That version is severely out of date, and is no longer supported.

Furthermore, the attached PDF document renders *identical* in Adobe Reader and PDF.js version `2.1.243` (and note that non of the checkboxes are actually checking in Adobe Reader either).

 > The font cannot be loaded: `Warning: Error during font loading: Font Helv is not available`

This is the "standard"-kind of error message which is printed for fonts associated in AcroForms entries, hence this issue should just be closed as a duplicate of e.g. #7788.

**Comment by THausherr** [comment] 2019-02-07 12:29
The checkbox "sex_male" has "True" as values for /V and /AS. The valid values would have been "Off" or "Yes". (See at Root/AcroForm/Fields/[9]/AP/N ). It's similar for the field "white". The valid values here are "Off" or "On", but "True" is set.

**Comment by write2nitinmalik** [comment] 2019-02-07 15:57
@THausherr , Thanks for suggesting the right values, i changes the values to "Yes" and "No" and it worked like a charm.

Thanks again ! 👍

**Closed** 2019-02-07 22:00 UTC
Labels: 4-font-conversion
