### ISSUE TITLE
PDF viewer page view issue of presentation mode in chrome

### ISSUE THREAD

**Issue by sanjivani2208** [mozilla/pdf.js#7160] opened 2016-04-07 06:12 UTC
On entering presentation mode if user navigates through PDF by next & previous keys or through mouse scroll, extra margin is set to pdf view. Thus causing the view to distort. Same pdf works correctly in other browsers like firefox and IE.

Browser: Chrome Version 49.0.2623.110 m
OS: Win 7
PDF.js version: 1.0.1194

Expected Behavior: 
![proper](https://cloud.githubusercontent.com/assets/12951180/14342212/aec0f362-fcb5-11e5-8edd-be857ab4dea8.png)

What went wrong?
![error](https://cloud.githubusercontent.com/assets/12951180/14342217/b6acf1d4-fcb5-11e5-84bd-7d97d89fd435.png)

**Comment by timvandermeij** [comment] 2016-04-07 11:31
Closing as incomplete because not all data from https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md has been provided. Once this is provided, we can reopen this.

**Comment by sanjivani2208** [comment] 2016-04-07 11:45
The issue is not specific to PDF file. Opening any pdf file in presentation mode shows the view distorted in chrome. Attching one of the sample PDF file added in viewer.

[5_things_to_consider_when_adopting_mobile_app_test_automation_defbvkd_skdg_skejfh_kswjef_wjehf_aejdhgf.pdf](https://github.com/mozilla/pdf.js/files/208269/5_things_to_consider_when_adopting_mobile_app_test_automation_defbvkd_skdg_skejfh_kswjef_wjehf_aejdhgf.pdf)

**Comment by yurydelendik** [comment] 2016-04-07 12:43
> PDF.js version: 1.0.1194

This version of the viewer is too old. Works for me at http://mozilla.github.io/pdf.js/web/viewer.html on Mac OS. Can you update version of PDF.js?

**Comment by timvandermeij** [comment] 2016-04-13 10:22
There is still not enough information here for us to work with. Please test with the latest version and report your findings.

**Comment by sanjivani2208** [comment] 2016-04-15 09:54
Update the version of PDF.js to 1.3.91 and tried. Still the issue persists.

**Comment by oekonomi** [comment] 2018-03-31 20:58
Could you please provide a sample PDF and steps to reproduce the issue?

**Comment by SerkanKorkusuz** [comment] 2018-11-04 19:43
> 
> 
> Closing as incomplete because not all data from https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md has been provided, most notably an example PDF file. Once this is provided, we can reopen this.

IHas not the time to reopen come?

**Comment by Snuffleupagus** [comment] 2019-02-16 10:25
> Browser: Chrome Version 49.0.2623.110 m
> OS: Win 7
> PDF.js version: 1.0.1194

> Update the version of PDF.js to 1.3.91 and tried. Still the issue persists.

Given that both those PDF.js version are very old (and no longer supported), and that the mentioned Chrome version is outdated as well, this looks on the face of it more like a platform/graphics/browser bug than a PDF.js viewer one. There hasn't been a lot of similar reports either, as far as I can tell; should this issue simply be closed now?

**Closed** 2019-02-16 13:30 UTC
Labels: 1-viewer, 4-chrome-specific
