### ISSUE TITLE
Touch-Event on Mobile Device (pdf.js integration into Xamarin Forms)

### ISSUE THREAD

**Issue by MickLesk** [mozilla/pdf.js#11098] opened 2019-08-26 11:19 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: -> Xamarin Forms Android + iOS 4.2xx
- Operating system and its version:  Android + iOS + UWP
- PDF.js version: actual stable 2.1.266
- Is a browser extension: NO

Steps to reproduce the problem:
1.  Binding pdf.js into Xamarin Forms (https://blog.verslu.is/xamarin/xamarin-forms-xamarin/showing-pdf-files-xamarin-forms/)
1.1 you can Use the full project of https://github.com/jfversluis/pdfjs
2. Open the App, and a pdf file, that will be correctly show, but it dont have touch events (double-tap for zoom in / zoom out), pinch to zoom (in/out).

What is the expected behavior? (add screenshot)
--- 

What went wrong? (add screenshot)
- No Pinch-To-Zoom Event / No Tap/DoubleTap-Event 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://github.com/jfversluis/pdfjs
https://blog.verslu.is/xamarin/xamarin-forms-xamarin/showing-pdf-files-xamarin-forms/

**Comment by Snuffleupagus** [comment] 2019-08-26 11:25
Duplicate of #2582.

(Please also note that we cannot provide any support for "Xamarin Forms" here, since we know nothing about it.)

**Comment by MickLesk** [comment] 2019-08-26 12:19
Hey,

when i use the pdfjs in a mobile Browser, i can't also not use the pinch-To-Zoom action. 
It give a Workarount (https://gist.github.com/jsprpalm/12217feab2f1acc14bd8e8508291619e) but with this i dont can swipe the Page/s.

it has nothing to do with xamarin forms, because its the native pdf-js.

**Comment by timvandermeij** [comment] 2019-08-26 20:33
We don't support pinch-to-zoom yet and it's tracked in #2582, so this can be closed as a duplicate.

**Closed by timvandermeij** 2019-08-26 20:33 UTC
