### ISSUE TITLE
text selection flow broken on page 5

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#7351] opened 2016-05-24 08:09 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome Version 51.0.2704.54 beta (64-bit)
- Operating system and its version: OS X El Capitan 10.11.3 (15D21)
- PDF.js version: online (May 24, 2016)
- Is an extension: no

Steps to reproduce the problem:
1. try selecting text from page 5 of the attached PDF 
[tourists.pdf](https://github.com/mozilla/pdf.js/files/279031/tourists.pdf)

2. text selection DIVs are following the actual text rendered (jumps between lines)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
Couldn't select text well.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2016-05-24 08:17
You get the exact same text-selection behaviour in Adobe Reader as well, which is a clear indication that the issue is with the PDF file itself and *not* PDF.js. Closing as invalid.

**Closed by Snuffleupagus** 2016-05-24 08:17 UTC

**Comment by ldenoue** [comment] 2016-05-24 08:21
It works great in Preview on my Mac.
PDFs don't have to be layout text in visual order. It's up to the viewer to do more work and eventually sort bounding boxes for example.

**Comment by Snuffleupagus** [comment] 2016-05-24 08:39
> It's up to the viewer to do more work and eventually sort bounding boxes for example.

In a perfect world, a PDF viewer shouldn't have to "fix" what is essentially caused by a bad PDF generator, since that usually slows things down and and can be prone to errors.

In practice, PDF.js tries do various things to recover from bad/corrupt PDF files. E.g. we use various heuristics to try and improve text-selection in badly generated file, but in general it's not easy to do.

Note that Adobe Reader (which could be thought of as the reference implementation of the PDF spec) is able to deal with a lot of weirdness in PDF files, so if even it fails there, then there *is* something wrong the the PDF file itself.

**Comment by ldenoue** [comment] 2016-05-24 12:49
I am specifically using pdfjs to extract text from PDFs, so I need clean text when it's not impossible.
But I understand that PDF.JS goals might be different.
Chrome Viewer (pdfium) is also not sorting the boxes correctly, as well as mupdf.
Laurent
