### ISSUE TITLE
Hyperlink issue with pdf.js

### ISSUE THREAD

**Issue by ubaidmohammed** [mozilla/pdf.js#6686] opened 2015-11-25 07:00 UTC
Hi,

Hyper link in the attached PDF is not working when I view it via pdf.js, any help will be greatly appreciated. I am sorry I know this was discussed and closed in Git before I just couldn't figure this one out.

Thanks,

[single.pdf](https://github.com/mozilla/pdf.js/files/43537/single.pdf)

**Comment by Snuffleupagus** [comment] 2015-11-25 12:05
That PDF file doesn't actually contain any links, but just text styled to *look* like standard hyperlinks.

Those links can work in e.g. Adobe Reader, but only if you have enabled automatic creation of hyperlinks (this setting seems to default to on).

The issue is tracked in #3172, hence I'm closing this as duplicate.

**Closed by Snuffleupagus** 2015-11-25 12:05 UTC
