### ISSUE TITLE
Pdf gets rendered with stripes

### ISSUE THREAD

**Issue by peirick** [mozilla/pdf.js#9829] opened 2018-06-20 09:55 UTC
Link to PDF file: [https://github.com/peirick/BugsInPdfJs/raw/master/BugWithStripes.pdf](https://github.com/peirick/BugsInPdfJs/raw/master/BugWithStripes.pdf)

Configuration:
- Web browser and its version: Firefox 60.0.2
- Operating system and its version: Windows 10
- PDF.js version: PDF.js: 2.0.402

Steps to reproduce the problem:
1. Open the pdf document

What is the expected behavior? (add screenshot)
In Chrome no stripes are shown:
![image](https://user-images.githubusercontent.com/15078132/41651336-9f03d864-7480-11e8-9aa4-b67b03bd0ffc.png)

What went wrong? (add screenshot)
In Firefox stripes are shown:
![image](https://user-images.githubusercontent.com/15078132/41651379-bd80e4a8-7480-11e8-875c-4c6df115c16e.png)

**Comment by Snuffleupagus** [comment] 2018-06-20 11:55
This is a duplicate of e.g. issue #3351.

**Closed** 2018-06-20 20:53 UTC
