### ISSUE TITLE
jquery.ajax request server return filestream(200MB),client browser google prompt memory insufficient

### ISSUE THREAD

**Issue by tenglongwentian** [mozilla/pdf.js#9767] opened 2018-06-01 06:09 UTC
jquery.ajax request server return filestream(200MB),client browser google prompt memory insufficient

**Comment by Hyoutei** [comment] 2018-06-01 06:14
666

**Comment by Hyoutei** [comment] 2018-06-01 06:15
six,six,six

**Comment by Hyoutei** [comment] 2018-06-01 06:16
It may be caused by the lack of browser virtual memory. Try to modify the browser's virtual memory and hope to help you.

**Comment by timvandermeij** [comment] 2018-06-01 21:52
Yes, this is not something that looks like it can be fixed on the PDF.js side. Otherwise, please provide the PDF file for analysis.

**Closed by timvandermeij** 2018-06-01 21:52 UTC
