### ISSUE TITLE
Rendering is blurry

### ISSUE THREAD

**Issue by nvesely** [mozilla/pdf.js#10917] opened 2019-06-20 12:23 UTC
Example: https://eprint.iacr.org/2012/071.pdf
![Screenshot from 2019-06-20 13-14-28](https://user-images.githubusercontent.com/3538418/59848607-7d017580-935d-11e9-85c6-0e973c6aced6.png)
This text renders much more clearly in the Chromium PDF reader and in Evince and qpdfview.

Configuration:
- Web browser and its version: 68.0b10
- Operating system and its version: Debian 10
- PDF.js version:
```js
var pdfjsVersion = '2.2.177';
var pdfjsBuild = '1421b2f2';
```

**Comment by Snuffleupagus** [comment] 2019-06-21 06:47
Possibly a duplicate of e.g. #10807.

**Comment by nvesely** [comment] 2019-06-21 09:30
I'm using a 1440p laptop screen. I have not modified that FF preference. I am using GNOME 2X scaling on Wayland.

**Comment by nvesely** [comment] 2019-06-23 22:19
Lmk if I should file a bug upstream w/ Mozilla.

**Comment by timvandermeij** [comment] 2019-06-24 08:50
I cannot reproduce this on Arch Linux with Firefox 67.0.4. Perhaps the canvas is being scaled (stretched) instead of rendered with the correct device pixel ratio, which would indicate a relation to #10807. I'm not familiar with GNOME 2X scaling; it's probably best to file this upstream because I don't really see how this is caused by PDF.js. If it turns out that we can in fact improve the rendering, then we can always reopen this. You can try to check the device pixel ratio and/or set the device pixel ratio yourself to see if that has any effect.

**Closed by timvandermeij** 2019-06-24 08:50 UTC
Labels: 1-viewer

**Comment by nvesely** [comment] 2019-06-24 20:30
After toggling off `privacy.resistFingerprinting` PDFs are rendering nicely. So I guess you and Mozilla are going to need to figure this one out together, or they just fix it on their end.
