### ISSUE TITLE
pdfjs-dist npm package is not compiling with core-js 3

### ISSUE THREAD

**Issue by shindesayalip** [mozilla/pdf.js#11548] opened 2020-01-30 08:53 UTC
Attach (recommended) or Link to PDF file here:
pdfjs-dist/lib/shared/compatibility.js

Configuration:
"pdfjs-dist": "2.2.228",

Steps to reproduce the problem:
1. Add npm dependency for pdfjs-dist version 2.2.228 in the node app
2. Add npm dependency for core-js version 3.3.2 in the node app
3. Build the app.
4. Notice the build errors.

What is the expected behavior? (add screenshot)
Node app should build successfully with core-js version 3.3.2. The file pdfjs-dist/lib/shared/compatibility.js is looking for some dependencies at core-js/fn/ path. However this path is changed in core-js 3.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/31127161/73433846-947cf400-436b-11ea-9d3b-f11802a43132.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): NA

**Comment by Snuffleupagus** [comment] 2020-01-30 10:39
Duplicate of #11539, note https://github.com/mozilla/pdf.js/issues/11539#issuecomment-579478752 in particular.

**Closed** 2020-01-30 22:34 UTC
