### ISSUE TITLE
On the last page of the latest version of Firefox

### ISSUE THREAD

**Issue by infosecliqin** [mozilla/pdf.js#12138] opened 2020-07-29 01:40 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  Firefox 78.0.2
- Operating system and its version: Windows10
- PDF.js version: 2.3.200
- Is a browser extension: no

Steps to reproduce the problem:
1. viewer.html Nested in the page through iframe
2. Select the local PDF file to open and click the "print" button. A blank page will appear after the last page

What is the expected behavior? (add screenshot)
No blank page for printing
What went wrong? (add screenshot)
print
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2020-07-29 21:31
Closing since this is a duplicate of the issues in https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-printing+blank.

**Closed by timvandermeij** 2020-07-29 21:31 UTC
