### ISSUE TITLE
resize zoom percentage with "ctrl+o"

### ISSUE THREAD

**Issue by Einere** [mozilla/pdf.js#9152] opened 2017-11-17 06:28 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: firefox
- Operating system and its version: ubuntu
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. select zoom size "130%" (i think that be able to choose any percentage...)
2. type "ctrl+o", so zoom size is "알아서 맞춤"
3. type "ctrl+o", yet zoom size is "알아서 맞춤" but ppt size is resized slightly. 

What is the expected behavior? (add screenshot)
don't resize ppt.

What went wrong? (add screenshot)
![2017-11-17](https://user-images.githubusercontent.com/8300010/32932528-b51fb038-cbab-11e7-9ee5-675a1308bbb3.png)
zoom percentage is 130%

![2017-11-17 1](https://user-images.githubusercontent.com/8300010/32932541-bf546a1c-cbab-11e7-8832-25bb75bd7827.png)
type "ctrl+o", ppt is resized and zoom will be "알아서 맞춤"

![2017-11-17 2](https://user-images.githubusercontent.com/8300010/32932587-d44ad4ba-cbab-11e7-8738-ef87f64bd105.png)
and type "ctrl+o", zoom percentage is "알아서 맞춤" yet, but resized slightly.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-11-17 08:21
> select zoom size "130%" (i think that be able to choose any percentage...)

What does the sentence in the parenthesis actually mean?

> type "ctrl+o", yet zoom size is "알아서 맞춤" but ppt size is resized slightly.

Do you mean <kbd>Ctrl</kbd>+<kbd>0</kbd> (zero, instead of the letter o), since the keyboard combination you referred to will trigger a "Open File" dialog?
Also, for those of us that do no speak Korean, what does that string actually mean (in English).
Finally, is "ppt" an abbreviation, and if so what does it actually mean in this instance?

Unfortunately it's currently somewhat difficult to understand what you're trying to report here. Can you please attempt to clarify what you mean?

**Comment by Einere** [comment] 2017-11-17 10:53
ah, i'm sorry about abstract information.
first, select zoom size "130%" (i think that be able to choose any percentage...) means that choose "not 알아서 맞춤". so, 1. choose non-"알아서맞춤" and 2. choose "알아서맞춤", then resizing pdf screen, and 3. choose "알아서맞춤", resize pdf screen slightly. (originally don't resize 2->3)

second, i misunderstands "ctrl+0 (number)"  to "ctrl+o (alphabet)". i'm sorry....

third, "알아서 맞춤" is "page_scale_auto". i find it at l10n/ko/viewer.properties.

forth, "ppt" is "pdf".. sorry..TT

**Comment by timvandermeij** [comment] 2017-11-24 21:15
I cannot reproduce this with the default Tracemonkey PDF file. Could you share the PDF file from the screenshot?

**Comment by timvandermeij** [comment] 2017-11-26 12:42
Closing since not enough information is provided to reproduce the issue. Furthermore, judging by the screenshots this is a very minor issue that I doubt is worth addressing.

**Closed by timvandermeij** 2017-11-26 12:42 UTC
Labels: 4-information-requested
