### ISSUE TITLE
Page Fit scale should not have any overflow

### ISSUE THREAD

**Issue by nt1m** [mozilla/pdf.js#15288] opened 2022-08-07 17:07 UTC
STR:

* Visit any PDF with a single page (or one with multiple pages in Page scrolling mode)
* Set scale to Page Fit

ER:
* No overflow

AR:
* Page can still be slightly be scrolled

Example with multiple pages (enable Page scrolling mode to make the issue obvious): https://www.irs.gov/pub/irs-pdf/p1ar.pdf

**Comment by Snuffleupagus** [comment] 2022-08-07 17:31
Duplicate of #7541

**Closed by Snuffleupagus** 2022-08-07 17:31 UTC
