### ISSUE TITLE
pdf loading but not displaying

### ISSUE THREAD

**Issue by tfierens** [mozilla/pdf.js#9450] opened 2018-02-07 01:29 UTC
I'm trying to get the pdf.js viewer to work in an asp.net MVC 5 application but while the pdf is definitely being process, it is not being displayed.

Configuration:
- Web browser and its version: Microsoft Edge (41.16299.15.0) and Chrome (64.0.3282)
- Operating system and its version: Windows 10 (Version 1709 - 16299.125)
- PDF.js version: 1.9.426
- Is a browser extension:

Steps to reproduce the problem:
1. Include pdf.js in a asp.net mvc project
2. Include the code from the Viewer.html into an Index.cshtml view and remove the body and head tags.
3. Modify various path for the .js and .css
4. If I click on the download button, the pdf file gets downloaded successfully.

What is the expected behavior? (add screenshot)

Expected behaviour would be to display the pdf document.

What went wrong? (add screenshot)

I'm not sure but it is definitely loading the pdf. It's just not displaying it.

1. The Viewer is displaying correctly and so is the toolbar.
2. I can see the number of pages in the pdf.
3. I can see the progress bar when the pdf document is loading.
4. If I provide an invalid pdf filename, it displays an error i.e. 'file not found'

I don't know if it's related, I'm getting a few errors and a lot of warnings:

Error: 

1. HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - http://localhost/PdfWeb/Scripts/pdf.js/web/locale/locale.properties

Warnings: 

1. http://localhost/PdfWeb/Scripts/pdf.js/web/locale/locale.properties not found.

The locale.properties is definitely located in this location.

2. Warning: "en-ie" resource not found

I've created a copy of en-UK and renamed it to en-ie but that this seem to have any effects.

3. I get dozoens if not hundreds of 'undefined' errors. Here are a few of them:

#document_outline_label is undefined.
#attachments is undefined.
#attachments_label is undefined.
.
.
.

#page_scale_percent is undefined.

I've attached a few snapshot highlighting the fact that the pdf is definitely being loaded and processed but as you can see it is not displayed, nor is a preview generated when I'm trying to print it.

<img width="908" alt="viewer_no_pdf_displayed" src="https://user-images.githubusercontent.com/13773041/35893570-940a5070-0ba6-11e8-8c28-03c2c5eb7650.PNG">
<img width="895" alt="viewer_totalpages" src="https://user-images.githubusercontent.com/13773041/35893571-943078c2-0ba6-11e8-9f0b-4d016322bb98.PNG">
<img width="885" alt="viewer_progress" src="https://user-images.githubusercontent.com/13773041/35893572-9451c2e8-0ba6-11e8-9129-4679f51e0054.PNG">
<img width="562" alt="viewer_printpreview_all_blank" src="https://user-images.githubusercontent.com/13773041/35893573-9482c73a-0ba6-11e8-9e1a-14257173859e.png">

I hope someone can help me with a) my issue where the pdf document is not being displayed and b) removing the error and the many warnings.

Thanks.

**Comment by tfierens** [comment] 2018-02-07 02:35
Hi,

I just thought I'd add some information. As you can see from the snapshot, it's definitely loading data as you can see from the developer's tab but I still can't explain why it's not displaying the page in the viewer.

<img width="1036" alt="viewer_hasdata" src="https://user-images.githubusercontent.com/13773041/35895427-46f22bc4-0baf-11e8-8264-4207b1c9fe77.PNG">

Why does the Viewer/Page does not have a white background?

Any ideas?

Thanks

**Comment by tfierens** [comment] 2018-02-07 02:53
Ok, I figured out what the problem is but I don't know how to fix it.

The problem lies with the ViewerContainer not being resized properly. When I change the following line:

`                <div id="viewerContainer" tabindex="0">
                    <div id="viewer"></div>
                </div>`

to 

`                <div id="viewerContainer" tabindex="0" style="width: 500px; height:500px">
                    <div id="viewer"></div>
                </div>`

and force a specific width and height, the viewer/page gets displayed 


<img width="975" alt="viewer_displayed_but_incorrect_size" src="https://user-images.githubusercontent.com/13773041/35896018-0f23dfbe-0bb2-11e8-8f34-6477b17470f8.PNG">

but it is obviously the wrong size as it should be the same width as the browser just as the toolbar and it should take the full browser's height.

**Comment by Rob--W** [comment] 2018-02-07 12:54
I cannot reproduce the issue with your steps-to-reproduce, because of the lack of detail. Can you show the difference in source code between the original PDF.js viewer and your modified version?

**Comment by tfierens** [comment] 2018-02-08 15:28
@timvandermeij I'll try to post something over the next few days but I've partially given up due to many other issues. 

One of my colleague figured out what was wrong with the above. Setting the height to 100% on various divs caused the viewer to display. 

I still have many other issues:

1. Thumbnails: Thumbnails not displaying 
2. Print: Prints blank pages.
3. Toolbar looks like it's floating over my website's toolbar.
4. Hard to resize.

Very likely related to my original issue with viewing the pdf.

For now, I ended up an iframe as this seems to work fine. The only downside is that I'll have to add code to the viewer.js (and other) in order to handle an id being passed instead of a file and make a request to our web service. Hopefully this will work.

Thanks.

**Comment by timvandermeij** [comment] 2018-02-12 21:33
I'm going to close this issue since it's not actionable for us, mostly due to customizations. If it turns out that there is a problem in PDF.js itself, please open a new issue with all requested details. Thanks.

**Closed by timvandermeij** 2018-02-12 21:33 UTC
Labels: 4-information-requested

**Comment by prashanthyD** [comment] 2019-02-19 08:30
Hi How to apply load event for the pdfjsviewer

**Comment by NextAlexM** [comment] 2019-05-07 12:57
I was experiencing the same issue inside a custom Chrome WebView for Xamarin Forms Android.

Following @tfierens investigation the culprit seems to be the `overflow: auto;` property on `#viewerContainer` in viewer.css.

Changing this to `overflow: visible;` displays the PDF as normal and can see no repercussions in doing this.

**Comment by NextAlexM** [comment] 2019-05-07 14:09
> I was experiencing the same issue inside a custom Chrome WebView for Xamarin Forms Android.
> 
> Following @tfierens investigation the culprit seems to be the `overflow: auto;` property on `#viewerContainer` in viewer.css.
> 
> Changing this to `overflow: visible;` displays the PDF as normal and can see no repercussions in doing this.

Upon further testing, this appeared to of resolved it the first time, but now the PDF appears to fail to load (even though the console indicates it has loaded)
