### ISSUE TITLE
[Feature]: Make shown URL in address bar pretty (http/https only, no chrome-extension:// prefix) in Chrome

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#19048] opened 2024-11-15 05:30 UTC
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

As discussed with @Rob--W and @shivaprsd in https://github.com/mozilla/pdf.js/issues/15161#issuecomment-2472442621, Chrome can save tab groups **only** with tabs with http/https schema (see https://issues.chromium.org/issues/331796399), which I've confirmed experimentally. @Rob--W agreed to add such an option in https://github.com/mozilla/pdf.js/issues/15161#issuecomment-2477358259 and requested that it's assigned to him.

**Comment by qwer1304** [comment] 2024-12-03 05:37
@Rob--W Hi Rob! Sorry for the nudge. Any news / schedule for this? Thx

**Comment by Snuffleupagus** [comment] 2024-12-21 08:22
Duplicate of #6444

**Closed by Snuffleupagus** 2024-12-21 08:22 UTC
Labels: addon, chrome-specific

**Comment by qwer1304** [comment] 2024-12-21 09:25
@Snuffleupagus Maybe it's a duplicate, but it's a much more recent one, gives an actual (not only convenience) use case where pdf.js breaks a Chrome (useful) feature (saved tabs), links to previous work by @Rob--W to upgrade from MV2 to MV3 and reports on a successful experiment to circumvent the issue, and Rob asked to open this feature and assign it to him. I'd hoped that a fix wouldn't be too hard and could benefit https://github.com/mozilla/pdf.js/issues/6444 too.
Please consider re-opening and keeping this as the lead issue report, which when fixed would allow to close https://github.com/mozilla/pdf.js/issues/6444 too.

**Comment by Rob--W** [comment] 2024-12-21 10:40
This is indeed a duplicate. I'll update the other issue and use it to track the development of this feature.
