### ISSUE TITLE
Open pdf with color issue

### ISSUE THREAD

**Issue by justalways** [mozilla/pdf.js#14591] opened 2022-02-21 03:05 UTC
Attach (recommended) or Link to PDF file here:
[MTB_8ft_Tower_2.pdf](https://github.com/mozilla/pdf.js/files/8105664/MTB_8ft_Tower_2.pdf)

Configuration:
- Web browser and its version: chrome
- Operating system and its version: windows 10
- PDF.js version: master branch
- Is a browser extension: no

Steps to reproduce the problem:
1. Original file opened on the computer. 
![KSCgXdM_dq-_UyUr1VZ_8J1mK6vJ-vFbog](https://user-images.githubusercontent.com/9329575/154878369-f5e35a93-c5d8-42a7-91d8-5cabd63811e0.png)

2. open in pdf viewer

![Wj_m5qHph0zo_I-BlPfwfX6m2NylgWtekw](https://user-images.githubusercontent.com/9329575/154882369-cf0ee1f8-6045-4860-9145-160f6b56aec9.png)

The color is bright about top area, help please!

**Comment by Snuffleupagus** [comment] 2022-02-21 09:24
WFM, using PDF.js version `2.13.133` in either Firefox Nightly 99 or Google Chrome Beta 99; note the following screen-shot:

![page1](https://user-images.githubusercontent.com/2692120/154925275-1c9ee59d-d722-44be-87d8-c283b0de3961.png)

> Web browser and its version: chrome

Please provide the actual version *number*, since as-is this information is incomplete.

> PDF.js version: master branch

Again, please provide an actual version *number* to remove confusion about the tested version.

> 1. Original file opened on the computer.

There's also no mention of what PDF Viewer this screen-shot was captured from, since the colours don't seem to completely match the rendering in Adobe Reader (i.e. the PDF reference implementation).

---

Closing as WORKSFORME, since I cannot reproduce this and given that the issue unfortunately doesn't really contain enough information in order to be actionable/valid.

**Closed by Snuffleupagus** 2022-02-21 09:24 UTC
Labels: information-requested

**Comment by calixteman** [comment] 2022-02-21 09:40
The blues are not exactly the same for me on Windows 11, Firefox nightly and Acrobat Pro DC (2021.011.20039):
![Screenshot 2022-02-21 103512](https://user-images.githubusercontent.com/5641725/154928405-ff470da0-3d42-42cb-a22c-762554a563b1.png)

With Acrobat, the blue has the value `#23408F` when it's `#0E3692` with Firefox.

**Comment by Snuffleupagus** [comment] 2022-02-21 09:48
> The blues are not exactly the same for me on Windows 11,

A *very slight* different is probably unavoidable here, given that the ColorSpace conversion in PDF.js (for /DeviceCMYK in this case) favours speed over perfect fidelity; note https://github.com/mozilla/pdf.js/blob/3635a9a3338feb0049be4f1521d5a5afd173a832/src/core/colorspace.js#L824-L888

**Comment by justalways** [comment] 2022-02-21 10:05
@Snuffleupagus 
Thank you for your explanation。
Do you want to optimize？

**Comment by Snuffleupagus** [comment] 2022-02-21 10:12
> Do you want to optimize it？

As already mentioned above, the implementation *is optimized* for performance (at the cost of rendering fidelity).

**Comment by Snuffleupagus** [comment] 2022-02-21 11:23
Duplicate of #2218
