### ISSUE TITLE
PDF Text is no longer being displayed

### ISSUE THREAD

**Issue by angelaperez1019** [mozilla/pdf.js#13814] opened 2021-07-28 16:08 UTC
Attach (recommended) or Link to PDF file here: I cannot attach the PDF for privacy purposes (and will block out some lines) but I will attach a small screenshot of the section having the issue.

Configuration:
- Chrome Version 92.0.4515.107 (Official Build) (64-bit)
   Edge Version 92.0.902.55 (Official build) (64-bit)
   Firefox Version 90.0.2 (64-bit) - Also has overlapping text issue
- Operating system and its version: Windows 10 (User base has a variety of operating systems)
- PDF.js version: Updated to latest stable version 2.9.359 and issue still occurring
- Is a browser extension: No

After the latest Chrome/Edge updates (Previous Working Version 91.*), there appears to be some text on our form that is no longer being displayed. It works when we download the PDF and view in another PDF Viewer.

What is the expected behavior?
![image](https://user-images.githubusercontent.com/14351846/127356523-fa7151a5-42d2-44f0-8840-36777afe4b9f.png)

What went wrong?
![image](https://user-images.githubusercontent.com/14351846/127356213-b24a28b3-8802-49ec-b49e-9378cc289f7e.png)

This warning is visible
pdf.worker.min.js:1 Warning: getOperatorList - ignoring errors during task: RenderPageRequest: page 1
![image](https://user-images.githubusercontent.com/14351846/127358093-7686169e-95cc-48bd-868f-f05056f6e195.png)

**Comment by Snuffleupagus** [comment] 2021-07-28 16:16
> Attach (recommended) or Link to PDF file here: I cannot attach the PDF for privacy purposes (and will block out some lines) but I will attach a small screenshot of the section having the issue.

Unfortunately this means that the issue isn't actionable, and will be closed as such, since it's *impossible* to do any meaningful debugging with nothing more than a screen-shot.

Duplicate of #13798 (which is a best guess, given the lack of crucial information).

**Closed by Snuffleupagus** 2021-07-28 16:16 UTC

**Comment by angelaperez1019** [comment] 2021-07-28 16:25
@Snuffleupagus Are you able to provide any feedback on the error shown? Also, it seems there are many users with this issue after the recent updates of chrome/edge, is there going to be a resolution?

**Comment by angelaperez1019** [comment] 2021-07-28 17:28
@Snuffleupagus  I have confirmed with business that I can send the PDF over. Can I send to you directly or do I have to post here?

**Comment by Snuffleupagus** [comment] 2021-07-28 17:57
All test-cases should be *attached directly* to the issue, since all issues need to be actionable for any contributor (given that this is an open-source project after all).

**Comment by marco-c** [comment] 2021-07-29 08:50
@angelaperez1019 if there is a private PDF that you can't share publicly, you can file a bug on Bugzilla (at https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=PDF%20Viewer) and select "Restrict the visibility of this bug to the assignee, QA contact, and CC list only".

**Comment by marco-c** [comment] 2021-07-29 08:51
If we can, we will then try to create a new PDF based on your PDF but with totally fake information, just so we can publish it here publicly.
