### ISSUE TITLE
Hi, I am currently using PDF.js v1.6.210 for a project. But I am getting blank page in ipad when trying to show pdf. It seems to be a random behavior. Can I get any hep for this issue. Thanks in advance. 

### ISSUE THREAD

**Issue by Pawan9977** [mozilla/pdf.js#8212] opened 2017-03-30 01:40 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-03-30 06:56
Closing as incomplete, since it's impossible to provide any assistance based on the information provided.

When opening an issue, please make sure to read [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) and to provide as much of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) as possible (for example, "Steps to reproduce the problem" is a *very* important point).

**Closed by Snuffleupagus** 2017-03-30 06:56 UTC
