### ISSUE TITLE
Canvas blending has no graceful fallback in IE

### ISSUE THREAD

**Issue by mahelious** [mozilla/pdf.js#3900] opened 2013-11-11 19:46 UTC
Highlighting annotations depend on Canvas blendmodes to display correctly.  This feature is not supported in IE 10/11, and result hides text, rather than emphasizing.

Suggest using globalAlpha property as a graceful fallback in pdf.js:

```
5364:    CanvasGraphics.prototype = {
...
5544:      setGState: function CanvasGraphics_setGState(states) {
...
5582:            case 'BM':

if (value && value.name && (value.name !== 'Normal')) {
  var mode = value.name.replace(/([A-Z])/g,
	function(c) {
	  return '-' + c.toLowerCase();
	}
  ).substring(1);
  this.ctx.globalCompositeOperation = mode;
  if (this.ctx.globalCompositeOperation !== mode) {
	warn('globalCompositeOperation "' + mode +
        '" is not supported');
	this.ctx.globalAlpha = 0.5;
  }
} else {
  this.ctx.globalCompositeOperation = 'source-over';
}
break;
```

**Comment by timvandermeij** [comment] 2016-05-04 22:26
Closing as duplicate of #5264. Let's track the bug there.

**Closed by timvandermeij** 2016-05-04 22:26 UTC
Labels: 4-ie10-specific, 4-ie11-specific, 4-ie9-specific

**Comment by clausreinke** [comment] 2017-02-22 17:05
#5246 suggests voting for fixing this in IE, but apparently, that isn't going to happen, as Edge does not have the issue.

Is there any reason not to ship the workaround suggested in this issue? It will only apply in browsers that fail to support `globalCompositeOperation`, and it seems better to render something than nothing (in our case, header/footer images were invisible in IE11 without this workaround).
