### ISSUE TITLE
Incorrect text selection feedback

### ISSUE THREAD

**Issue by greddyatpt** [mozilla/pdf.js#9748] opened 2018-05-22 21:22 UTC
Click somewhere to start selecting text.  That position establishes one end of the selection.  The other end is expected to be the i-beam position nearest to the current cursor position but it jumps all over when the cursor is not exactly between characters.

**Comment by martindu911** [comment] 2018-07-13 02:17
I get the same problem. When moving and dropping the mouse pointer in some point between lines, the start position of the selection goes way back to the beginning of the page instead of the nearest text block/line to the point. Curiously I tried Firefox and there is no such problem. I wonder if it's due to the version I'm using (I think is  1.1.159) or sth else.

Could someone point where should I look for a start, like viewer.js perhaps? thx in advance.

**Comment by rajacsharp** [comment] 2022-06-08 09:54
Is this addressed in any release ? we are still seeing this issue, Selection is not working properly

**Comment by Snuffleupagus** [comment] 2022-11-11 08:51
Duplicate of #9843

**Closed by Snuffleupagus** 2022-11-11 08:51 UTC
Labels: viewer, ux
