### ISSUE TITLE
Not hyper linking URLs in Footer and Side of PDF pages.

### ISSUE THREAD

**Issue by Haris-Jamil** [mozilla/pdf.js#10932] opened 2019-06-27 14:08 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 74.0.3729.169 
- Operating system and its version: Windows 7
- PDF.js version: 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. Pdf with link in footer and side area

What is the expected behavior? (add screenshot)
PDFJS should make links of URL.
In Chrome's default pdf reader links are working, but PDF JS is rendering them as plain text.

Yellow highlighted urls in below screen shots are not working

![d1](https://user-images.githubusercontent.com/10936956/60273037-ab0f2880-990e-11e9-92ac-c866a83608ca.PNG)

![d3](https://user-images.githubusercontent.com/10936956/60273050-b2363680-990e-11e9-94b9-7cba760e13e5.PNG)

while the links which are not in footer or side are working fine
![d2](https://user-images.githubusercontent.com/10936956/60273105-cc701480-990e-11e9-91fa-9e904ba69ff1.PNG)

Any help will be highly appreciated
Thanks!

**Comment by Snuffleupagus** [comment] 2019-06-27 14:18
> Attach (recommended) or Link to PDF file here:

Without this information, the issue will be closed as INVALID.

Most likely, given the missing information, this is a duplicate of issue #3172.

**Comment by Haris-Jamil** [comment] 2019-06-27 14:48
This is the PDF file
https://www.tandfonline.com/doi/pdf/10.1080/13528165.2019.1593732

**Comment by Snuffleupagus** [comment] 2019-06-27 18:31
It turns out that https://github.com/mozilla/pdf.js/issues/10932#issuecomment-506365973 was spot on, hence this should be closed as a duplicate of #3172.

**Closed** 2019-06-27 18:32 UTC
Labels: 4-annotations
