### ISSUE TITLE
Failed to load font

### ISSUE THREAD

**Issue by jianmyphy123** [mozilla/pdf.js#8197] opened 2017-03-26 17:23 UTC
Hello.
Some fonts and icons are not display in Chrome browser.
Following errors occur in chrome.
Warning: Failed to load font "g_d0_f1": SyntaxError: Invalid font data in ArrayBuffer.

Chrome version: 56.0.2924.87
OS: Windows 10
PDF.js version: 1.7.225

How can i solve this problem?
Thanks.

[QM-Handbuch.pdf](https://github.com/mozilla/pdf.js/files/870892/QM-Handbuch.pdf)

**Comment by timvandermeij** [comment] 2017-03-26 17:53
I don't get these errors in Firefox using https://mozilla.github.io/pdf.js/web/viewer.html (1.7.384 as of writing). The images, however, are distorted, but this is the same in Okular. Let's label this issue as problematic for both areas.

**Comment by jianmyphy123** [comment] 2017-03-26 18:46
Hello!
Thank you for your response.
There are no issues in Mozilla browser, but occur in Chrome.
Please tell me solution.

**Comment by fefedao** [comment] 2017-06-13 13:18
Same problem here guys, both in firefox and google chrome browser.

**Comment by yurydelendik** [comment] 2017-06-13 13:29
This issue is becoming confusing.

@fefedao, @frankTadlip,  @jianmyphy123 Can you open a separate issue with information about your configuration and attach your PDF? Please read [contribution guidelines first](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md)

**Comment by yurydelendik** [comment] 2017-06-13 13:31
I cannot reproduce font issue on Chrome and Firefox on Mac OSX.

**Comment by fefedao** [comment] 2017-06-13 13:39
sure @yurydelendik

**Comment by Snuffleupagus** [comment] 2017-06-13 13:51
I cannot reproduce this issue, when testing with PDF.js version `1.8.446` in Firefox Nightly 56 on Windows.

**Comment by fefedao** [comment] 2017-06-13 13:56
I manage to solve the problem by updating the version to the latest stable one.

**Comment by yurydelendik** [comment] 2017-06-13 13:57
Closing as WFM based on the comments above.

**Closed by yurydelendik** 2017-06-13 13:57 UTC
Labels: 4-chrome-specific, 4-font-conversion, 4-os-windows, 4-triage-needed

**Comment by sarankup** [comment] 2017-07-06 14:52
Hi,

We have the same problem, both in Firefox and Chrome browser, but it works well in IE, and Safari. Here is error message:

```
Warning: Failed to load font "g_d1_f1": SyntaxError: Invalid font data in ArrayBuffer.
Warning: Failed to load font "g_d1_f3": SyntaxError: Invalid font data in ArrayBuffer.

```
We have tested with 1.8.522 at https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by nasus0315** [comment] 2022-12-28 07:06
[compressed.tracemonkey-pldi-09-2.pdf](https://github.com/mozilla/pdf.js/files/10312707/compressed.tracemonkey-pldi-09-2.pdf)
i also has similar problem
