### ISSUE TITLE
CS50 guide renders incorrectly

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/pdf.js#10893] opened 2019-06-09 23:05 UTC
Attach (recommended) or Link to PDF file here: https://cs50.harvard.edu/college/2019/fall/guide.pdf

Configuration:
- Web browser and its version: Firefox 69
- Operating system and its version: macOS 10.14
- PDF.js version: 2.2.199
- Is a browser extension: no

Steps to reproduce the problem:
Open the linked PDF

What is the expected behavior? (add screenshot)
The PDF should be rendered as it is in Preview and the Chrome viewer:
<img width="793" src="https://user-images.githubusercontent.com/10314059/59165416-ef15c700-8ae0-11e9-9ed5-df1580e57911.png">

What went wrong? (add screenshot)

<img width="1011" src="https://user-images.githubusercontent.com/10314059/59165423-ffc63d00-8ae0-11e9-9e80-f74a6337ee1f.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-06-10 06:17
Duplicate of #269.

**Closed** 2019-06-10 09:53 UTC
