### ISSUE TITLE
Phrase match with any number of spaces

### ISSUE THREAD

**Issue by dgoiko** [mozilla/pdf.js#11750] opened 2020-03-26 13:15 UTC
I found out that "Hello world" does not match if the pdf is distributing text using extra spaces and there's a 

`"hello      <space>      world".`

I need this functionality, so I'm modifying  _calculateMatch(pageIndex) to alow regExp search. The needs for my project force me to ALLWAYS use it, so I'm doing it in a dirty way.

However, if you are interested in giving full regular expression support, I can work it out with you to agree with an acceptable implementation to be merged (new checkbox in the search view, allowing to do it from params somehow, etc).

**Comment by Snuffleupagus** [comment] 2020-03-26 13:22
Looks like a duplicate of #7355.

---

> new checkbox in the search view,

That's generally not accepted, unless similar functionality exists in the Firefox findbar (given that this project exists primarily for the PDF Viewer in Firefox).

> allowing to do it from params somehow

Again, we don't want non-standard hash parameters added.

**Comment by dgoiko** [comment] 2020-03-26 13:57
Okey, thanks. I'll keep it for my project then.

BTW, you said this findbar is used for firefox PDF viewer, but my firefox (v74 Win x64) does not display search option for pdfs, but if I use native firefox ctrl+f it appears to be equivalen, ¿is that normal, some kind of "new" enhanced behaviour? Never noticed it until now, tbh, I think last time I checked it was a separate button

**Comment by timvandermeij** [comment] 2020-03-26 22:36
Closing as answered in https://github.com/mozilla/pdf.js/issues/11750#issuecomment-604428097.

**Closed by timvandermeij** 2020-03-26 22:36 UTC
