### ISSUE TITLE
[Bug]: Weird characters display for some PDFs

### ISSUE THREAD

**Issue by lecorsim** [mozilla/pdf.js#18479] opened 2024-07-22 08:05 UTC
### Attach (recommended) or Link to PDF file

https://www.trenitalia.com/content/dam/tcom/allegati/trenitalia_2014/informazioni/orario_digitale/In_Treno_Orario_Le_Frecce.pdf
https://www.trenitalia.com/content/dam/tcom/allegati/trenitalia_2014/informazioni/orario_digitale/In_Treno_Orario_Intercity.pdf

### Web browser and its version

128.0

### Operating system and its version

Mac OS Sonoma 14.5

### PDF.js version

4.4.10 [5c51d5622]

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the file
2. Go to table pages (about #25)

### What is the expected behavior?

Displaying the correct table with text into
<img width="1482" alt="Capture d’écran 2024-07-22 à 10 05 31" src="https://github.com/user-attachments/assets/4208e7ea-e805-4728-8d46-9e2a6dec3478">

### What went wrong?

<img width="1482" alt="Capture d’écran 2024-07-22 à 10 05 42" src="https://github.com/user-attachments/assets/87d16c5c-581e-41b6-a8c7-8bb3d1201bf7">

**Comment by Snuffleupagus** [comment] 2024-07-22 08:11
Duplicate of issue #16091 perhaps?

**Comment by lecorsim** [comment] 2024-07-22 09:18
> Duplicate of issue #16091 perhaps?

Yes, sorry.

**Comment by timvandermeij** [comment] 2024-07-22 14:14
Closing since this is a duplicate then.

**Closed by timvandermeij** 2024-07-22 14:14 UTC
