### ISSUE TITLE
Enable WebGL by default?

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#5161] opened 2014-08-09 19:51 UTC
I was wondering if WebGL is considered stable enough to be enabled by default. It makes some PDFs render much faster and it has been off by default for a while now, so we have had quite some time to test it.

If we decide to enable WebGL by default, we should not forget to update https://github.com/mozilla/pdf.js/blob/master/extensions/chromium/preferences_schema.json#L39 as well.

/cc @yurydelendik 
/cc @Snuffleupagus (because IIRC you were testing WebGL too)

**Comment by jqnatividad** [comment] 2015-03-22 14:53
Are there any benchmarks as to how fast pdf.js is with/without WebGL?

Along those lines, has the team considered adding a complex/showcase PDF in the distribution that not only shows off PDF.js capabilities, but can be a standard way to get users to benchmark and report problems using a standard pdf?

I'm afraid the current demo file is just too simple.

And going back to WebGL, if its enabled by default, what would happen on a browser that doesn't support WebGL?  Will it just fallback to not using WebGL?

**Comment by timvandermeij** [comment] 2015-03-23 21:03
@jqnatividad That is exactly what we will need to look into, especially the fallback.

**Comment by yurydelendik** [comment] 2015-03-23 22:50
> Are there any benchmarks as to how fast pdf.js is with/without WebGL?

@jqnatividad see #4286

On my computer:

https://bug793542.bugzilla.mozilla.org/attachment.cgi?id=663870#pdfBug=Stats&webgl=true

Rendering takes 2788ms vs 3821ms (w/webgl=false). Please notice that this speed up is visible only for certain PDFs (in this case with smask operations)

> And going back to WebGL, if its enabled by default, what would happen on a browser that doesn't support WebGL? Will it just fallback to not using WebGL?

It will fallback to regular behavior.

**Comment by yurydelendik** [comment] 2015-06-06 14:55
I guess right now we are trying to decide "is it worth to take a risk to increase chance of breaking stuff for small amount of document on some platforms to gain some performance for them". Also only half of the computers on the web has properly functioning video drivers for webgl AFAIK.

**Comment by Snuffleupagus** [comment] 2015-08-13 16:21
Also, before we even consider enabling WebGL by default, I think that it would be necessary to be able to run the tests (on the bots) with WebGL enabled.
Otherwise it's way too easy for "trivial" breakage to occur, as e.g. PR #6354 shows.

**Comment by Snuffleupagus** [comment] 2019-10-16 15:02
Given the points mentioned in https://github.com/mozilla/pdf.js/issues/5161#issuecomment-109593055, especially the risks, should we simply close this as WONTFIX now (since there's been no additional WebGL support added in the meantime)?

**Comment by timvandermeij** [comment] 2019-10-16 21:52
In a sense yes, but if we choose not to continue with WebGL, shouldn't we just remove it altogether? Keeping it around if we don't intend to use it only seems like a maintenance burden to me...

**Comment by NawarA** [comment] 2019-12-02 19:29
This question was asked in 2014. Its now ~2020 and WebGL has become standardized. 

Back then, you observed a 37% performance boost by flipping a switch. That's huge.

On the web, performance matters.

Whatever you can do to speed this library up, do it. 🚀

**Comment by Snuffleupagus** [comment] 2019-12-02 19:50
> Back then, you observed a 37% performance boost by flipping a switch. That's huge.

You need to remember that the performance increase mentioned was/is limited to documents with *specific* features, e.g. certain Soft Masks and Patterns, but for most PDF documents there's nothing gained by the current WebGL implementation.

Furthermore, as also was mentioned above, there's most definitely an increased risk of rendering issues caused by e.g. bad/outdated graphics drivers.

**Comment by Snuffleupagus** [comment] 2021-05-09 11:57
Given that nothing really has changed here, should we now do what https://github.com/mozilla/pdf.js/issues/5161#issuecomment-542907169 suggests and simply remove the WebGL implementation (since it's neither used, tested, or maintained at this point)?

**Comment by Snuffleupagus** [comment] 2021-05-09 12:00
Given that nothing really has changed here, should we now do what https://github.com/mozilla/pdf.js/issues/5161#issuecomment-542907169 suggests and simply remove the unused WebGL implementation?

Note that, as of now, it's *neither* used, tested, and/or maintained; and thanks to version control it also should be (reasonably) easy to restore the code if needed in the future.

**Comment by timvandermeij** [comment] 2021-05-09 13:37
I'd say we go for the removal. The WebGL implementation never really got out of the experimental phase and nowadays rendering engines/PDF.js itself is much faster, which was the original reason for its implementation. It's only a small subset of documents that actually benefit from it, and especially since we never really tested it it seems better to just remove it. If need be it can always be recovered from Git.

**Closed** 2021-05-09 16:32 UTC
Labels: 1-core, 1-test

**Comment by LifeIsStrange** [comment] 2022-05-08 19:05
I have seen many reports of PDF.js being to slow on complex PDFs. WebGL is ubiquitous in 2021-2022 and simply being too slow for many PDF use cases is a net regression. It does not promote accessibility, it regress it. It could have stayed in experimental state, that would still have been better than removing it, and if there was major limitations (there wasn't) external users could have made a pull request. And do not wrongfully claim it is not used, this is totally wrong, the google chrome PDF.js which has more than 1000000 users easily expose the option to enable it so many users have tried it in the wild and some probably depend on it.
