### ISSUE TITLE
Cannot print files directly when disableAutoFetch is set to true

### ISSUE THREAD

**Issue by 123woscc** [mozilla/pdf.js#15703] opened 2022-11-17 03:43 UTC
Attach (recommended) or Link to PDF file here:
demo pdf file: https://mozilla.github.io/pdf.js/legacy/web/viewer.html

Configuration:
- Web browser and its version: 版本 107.0.5304.107（正式版本） （64 位）
- Operating system and its version:  windows11
- PDF.js version: pdfjs-3.0.279-legacy-dist

Steps to reproduce the problem:
1.  set disableAutoFetch as true;
![image](https://user-images.githubusercontent.com/13806929/202349156-06c03128-5117-4bc0-97b6-e9d1abcb032b.png)
2. click print button;
![image](https://user-images.githubusercontent.com/13806929/202349265-3cffcac0-65e6-4175-8cda-fad4628c4780.png)
3. Requires scrolling to view all pages before printing：
![image](https://user-images.githubusercontent.com/13806929/202349393-21b1d6af-1d19-4899-89e5-2ed92c466073.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

Is there an interface to render all pages before printing?

**Comment by Snuffleupagus** [comment] 2022-11-17 09:30
> Web browser and its version: 版本 107.0.5304.107（正式版本） （64 位）

I have no idea what this means; please remember to only use English in this bug tracker.

---

This is the expected behaviour when `disableAutoFetch = true` is set, since printing in browsers is *synchronous* and all pages thus need to be loaded *before* printing starts. To work-around that you can scroll through the entire document such that all pages have loaded, or simply not use `disableAutoFetch = true` if printing is a vital part of the work-flow.

Closing as answered, since this cannot be fixed (in general) when `disableAutoFetch = true` is used.

**Closed by Snuffleupagus** 2022-11-17 09:30 UTC

**Comment by 123woscc** [comment] 2022-11-18 07:48
> Web browser and its version: 版本 107.0.5304.107（正式版本） （64 位）

Sorry, this is the version of the chrome browser, I forgot to add the browser name。

if it cannot be fixed, Is there an interface to rerender all pages before printing? Or can only remove the setting of disableAutoFetch and then reload the page.
