### ISSUE TITLE
Annotation comment panel

### ISSUE THREAD

**Issue by SuperPat45** [mozilla/pdf.js#17518] opened 2024-01-15 17:14 UTC
One of the missing feature (available on Adobe Reader) is the annotation comment panel:

All annotations are displayed.

Clicking on an annotation takes you to the right page.

Possibility of adding an answer.

A context menu allows you to:
* copy text, 
* modify annotation color opacity, and stroke width,
* delete the annotation,
* modify or delete the answer.
* set a status between accepted, deleted, refused...

![image](https://github.com/mozilla/pdf.js/assets/7791600/e84bd76d-5d9e-43a1-8403-abc3449cd9ab)

Would it be possible, in time, to implement something similar in pdf.js?

**Comment by timvandermeij** [comment] 2024-01-20 13:00
Closing since this is a duplicate of #10982.

**Closed by timvandermeij** 2024-01-20 13:00 UTC
