### ISSUE TITLE
Incorrect letters order

### ISSUE THREAD

**Issue by keymnsk** [mozilla/pdf.js#9109] opened 2017-11-08 12:32 UTC
Hello. 
There is a problem with incorrect letters order in some words.

Attach (recommended) or Link to PDF file here:

[Нормативные положения по учебной работе 2017-18 (2).pdf](https://github.com/mozilla/pdf.js/files/1453830/2017-18.2.pdf)

Configuration:
- Web browser and its version: Firefox 56.0 64bit but the same if view it in viewer on chrome 61
- Operating system and its version: Linux Mint 18.1 but the same on windows
- PDF.js version: 1.9.523
- Is a browser extension: yes but the same if not an extension

Steps to reproduce the problem:
1. open the attached file, page 3
2.

What is the expected behavior? (add screenshot)
![1510144098679](https://user-images.githubusercontent.com/25773069/32549165-1a8522fe-c491-11e7-8580-9dd3f2bd42a8.jpg)

Thus it looks in chromium embedded pdf viewer

What went wrong? (add screenshot)
![1510144199142](https://user-images.githubusercontent.com/25773069/32549229-51ed95fa-c491-11e7-8ee0-a10fd4803642.jpg)

And this is the firefox extension but it looks the same in viewer.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-11-08 12:44
Closing as duplicate of issues #9024, #9039, and #9068.

**Closed by Snuffleupagus** 2017-11-08 12:44 UTC
