### ISSUE TITLE
Is it possible to load local PDF file using chunks?

### ISSUE THREAD

**Issue by bh213** [mozilla/pdf.js#5304] opened 2014-09-17 09:53 UTC
I'd like to iterate (but not render) all  PDF pages of a file that is accessible using HTML5 File API but is large (from 500MB up to few GB). 

Loading whole file using FileReader usually crashes the browser.

From my testing It seems that using DocumentInitParameters.data and pdfDataRangeTransport doesn't work as pdfDataRangeTransport  seems to only work with DocumentInitParameters.url.

Is is possible to enable chunked loading for local files at all?

Thanks.

**Comment by kimar** [comment] 2015-02-23 05:29
Hey @bh213, could you reupload your working sample? Would be really interested in taking a look at this :+1:

**Comment by bh213** [comment] 2015-02-23 08:33
@kimar, pull request is here:

https://github.com/mozilla/pdf.js/pull/5332

**Comment by bh213** [comment] 2015-03-09 15:23
A bit late but here is an example of how to load local file:

https://jsfiddle.net/6wxnd9uu/6/

**Comment by Snuffleupagus** [comment] 2021-05-27 15:10
Given first of all the *somewhat* specialized use-case outlined here, secondly that this issue hasn't seen a lot of activity during the years, and most importantly the sheer complexity of the patch attempted in PR #5332; I'm really not at all convinced that we should attempt/accept a patch which fundamentally re-writes the `ChunkedStream`/`ChunkedStreamManager`-implementations because of the regression risks involved (since it's crucial that this code works correctly).

Throughout the years, even a couple of small (and seemly safe) patches to the `ChunkedStream`/`ChunkedStreamManager`-code have caused breakage in real-world cases. Given the complexity of this code, it's *very unlikely* that e.g. unit-tests would be able capture all aspects of this code well enough to ensure that it's sufficiently tested.
A bigger re-factoring/re-write would thus put a lot of burden on first of all the reviewer, and secondly on the regular PDF.js contributors who have to maintain this code; all-in-all I'm thus suggesting that we WONTFIX this issue.

/cc @timvandermeij

**Comment by timvandermeij** [comment] 2021-05-28 19:17
That seems fair to me indeed. Let's close this for now.

**Closed by timvandermeij** 2021-05-28 19:17 UTC
Labels: 1-core
