### ISSUE TITLE
Line under text varies in thickness across multiple browsers

### ISSUE THREAD

**Issue by michaeldzjap** [mozilla/pdf.js#10957] opened 2019-07-10 10:32 UTC
### Attach (recommended) or Link to PDF file here: 
[20190709_test_voorbeeld-5.pdf](https://github.com/mozilla/pdf.js/files/3376975/20190709_test_voorbeeld-5.pdf)

### Configuration:
- Web browser and its version: Chrome v75.x
- Operating system and its version: MacOS v10.14.5
- PDF.js version: latest (whichever version is used for the online demo)
- Is a browser extension: no

### Steps to reproduce the problem:
1. Open the attached pdf in _Preview_ or _Adobe_: the line under the text looks like expected.
2. Open the attached pdf in the _pdf.js_ demo viewer: the line under the text looks extra thick for some reason.

### What is the expected behavior? (add screenshot)

Screenshot from _Adobe_:
![Screenshot 2019-07-10 at 12 20 42](https://user-images.githubusercontent.com/2669912/60961765-27d9d380-a30d-11e9-958c-a49cf68c4408.png)

Screenshot from _Preview_:
<img width="1050" alt="Screenshot 2019-07-10 at 12 29 50" src="https://user-images.githubusercontent.com/2669912/60962412-7cca1980-a30e-11e9-8044-125e62b288f7.png">

### What went wrong? (add screenshot)

_Chrome_ is especially bad. _Firefox_ and _Opera_ seem less severe, but the line is still too thick when compared to _Adobe_ or _Preview_.

Screenshot from _pdf.js_ demo viewer (_Chrome_):
![Screenshot 2019-07-10 at 12 21 51](https://user-images.githubusercontent.com/2669912/60961861-548deb00-a30d-11e9-93e1-cd2a6d8f3178.png)

Screenshot from _pdf.js_ demo viewer (_Firefox_):
<img width="1321" alt="Screenshot 2019-07-10 at 12 23 37" src="https://user-images.githubusercontent.com/2669912/60961999-9b7be080-a30d-11e9-9c98-776e8dadd18c.png">

Screenshot from _pdf.js_ demo viewer (_Opera_):
<img width="1258" alt="Screenshot 2019-07-10 at 12 24 54" src="https://user-images.githubusercontent.com/2669912/60962089-c9f9bb80-a30d-11e9-8125-be727e18bf0c.png">

**Comment by Snuffleupagus** [comment] 2019-07-10 11:05
Duplicate of #10566.

**Closed** 2019-07-10 19:29 UTC
