### ISSUE TITLE
Extraneous background image in PDF

### ISSUE THREAD

**Issue by agusdallalba** [mozilla/pdf.js#7085] opened 2016-03-13 21:21 UTC
The pdf in https://www.sofse.gob.ar/servicios/pdf/roca/tarifario_lr-const-laplata-bosques.pdf shows a background image that it probably shouldn't:

![pdf js](https://cloud.githubusercontent.com/assets/5017453/13731460/de1bd838-e947-11e5-96c6-c9e219804c1e.png)

Evince renders the PDF like I'd expect:

![evince](https://cloud.githubusercontent.com/assets/5017453/13731466/06ef58a2-e948-11e5-81ba-379c302351ab.png)

I see the following warning in the JavaScript console:
```PDF 5ba49325187bd0479c54ea256b9204e8 [1.5 Adobe PDF library 10.01 / Adobe Illustrator CS6 (Windows)] (PDF.js: 1.3.76) viewer.js:6862:1```

I'm running Firefox 45 on ArchLinux.

**Comment by Snuffleupagus** [comment] 2016-03-13 21:38
The PDF file uses layers, which we currently don't support.
Closing as duplicate of issue #269.

**Closed by Snuffleupagus** 2016-03-13 21:38 UTC
Labels: 2-image-quality, 3-pdf-broken
