### ISSUE TITLE
how to default language korean?

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [mozilla/pdf.js#9869] opened 2018-07-04 04:41 UTC
Attach (recommended) or Link to PDF file here:
![image](https://user-images.githubusercontent.com/30399546/42257000-5e8962a8-7f8f-11e8-97e0-b81b829c58fe.png)
this pdf  is korean pdf.
so the character is converted in cmaps/Adobe-Korea1-UCS2.bcmap.
so the speed is slow..
how to default in korean?? 

Configuration:
- Web browser and its version: chrome latest
- Operating system and its version: mac 
- PDF.js version: ^1.8.557
- Is a browser extension: 

Steps to reproduce the problem:
1.  korean pdf is slow because the character is converted...
2.

What is the expected behavior? (add screenshot)
how to default language korea??
because, the english pdf is not converting .. (cmaps/...._)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2018-07-04 20:17
It's not really clear what the problem is from the description. If a PDF file is loading slowly, you'll need to upload the PDF file here or this issue is not actionable. Closing until the file and more information about the exact problem is provided.

**Closed by timvandermeij** 2018-07-04 20:17 UTC
