### ISSUE TITLE
Corrupted display of polish letters in forms 

### ISSUE THREAD

**Issue by felin-bsl** [mozilla/pdf.js#15408] opened 2022-09-07 07:38 UTC
Attach (recommended) or Link to PDF file here:
[Empty.pdf](https://github.com/mozilla/pdf.js/files/9503739/Empty.pdf)
[Microsoft Edge.pdf](https://github.com/mozilla/pdf.js/files/9503740/Microsoft.Edge.pdf)
[Firefox.pdf](https://github.com/mozilla/pdf.js/files/9503745/Firefox.pdf)

Configuration:
- Web browser and its version: Firefox 104.0.2 
- Operating system and its version: Windows 10 21H2
- PDF.js version: (built-in)
- Is a browser extension: (built-in)

Steps to reproduce the problem:
1. Create PDF in any app (e.g. Adobe Acrobat, PDF-XChange Editor) and add forms
2. Fill data with polish characters (ą, ć, ę, ł, ń, ó, ś, ź, ż)
3. Open in any other app

What is the expected behavior? (add screenshot)
(Filled in Edge, opened in it)
![Saved in Edge opened in it](https://user-images.githubusercontent.com/108809240/188816368-fe666d55-645d-4ffa-a163-1e4662a8a9f5.png)
(Filled in Acrobat, opened in Edge)
![msedge_RzQiosFj5U](https://user-images.githubusercontent.com/108809240/188818040-e40e5d29-b714-4316-853b-65273fd74e7e.png)

What went wrong? (add screenshot)
(Filled in Firefox, opened in Edge)
![Saved in Firefox open in Edge](https://user-images.githubusercontent.com/108809240/188816416-84bccd5a-b7ef-4eed-a119-4f3b957fa6a4.png)
(Filled in Firefox, opened in Acrobat Reader)
![AcroRd32_RxAiSidQl1](https://user-images.githubusercontent.com/108809240/188818184-27ef91ac-563c-4846-96a4-722ebed38476.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
 - Using Firefox version 104.0.2

**Comment by Snuffleupagus** [comment] 2022-09-07 07:49
Duplicate of #12264

**Closed by Snuffleupagus** 2022-09-07 07:49 UTC
