### ISSUE TITLE
Find method not works, viewer detects spaces where there aren't

### ISSUE THREAD

**Issue by alvaroman23** [mozilla/pdf.js#18215] opened 2024-06-06 19:44 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Versión 125.0.6422.112 (Build oficial) (x86_64)
- Operating system and its version: Macos 14.4.1 (23E224)
- PDF.js version:   "version": "2.4.456"

Steps to reproduce the problem:
1.  I am using pdf.js through vue pdf app, in order to have the pdfviewer and use it. I am having problems as pdf viewer detects spaces where there aren't. So when I am trying to search some phrases specially those that has Text alignment, or tabs, or even indetation. Will attach the root cause so you will see that if I add spaces (that are not there) it will highlight the text .
![Captura de pantalla 2024-06-04 a las 22 19 14](https://github.com/mozilla/pdf.js/assets/152604950/d6bc671b-8db8-4eee-8b95-19fb13de1442)
![Captura de pantalla 2024-06-04 a las 22 19 14](https://github.com/mozilla/pdf.js/assets/152604950/d6bc671b-8db8-4eee-8b95-19fb13de1442)

What is the expected behavior? (add screenshot)
- The expected behavior is that when you search a paragraph for example in the search bar it will highlight the text.
What went wrong? (add screenshot)
- When searching, not found occurs. 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by calixteman** [comment] 2024-06-06 19:50
The version 2.4.456 has been released 4 years ago... and we fixed a lot of bugs since.
If you can reproduce your issue with https://mozilla.github.io/pdf.js/web/viewer.html then please provide us the pdf and a clear STR.

**Comment by Snuffleupagus** [comment] 2024-06-09 07:28
Closing for now, since it's opened a couple of days ago and it unfortunately still lacks enough information to be actionable.

**Closed by Snuffleupagus** 2024-06-09 07:28 UTC
Labels: information-requested
