### ISSUE TITLE
Cannot display all signatures with safari

### ISSUE THREAD

**Issue by bimbogino** [mozilla/pdf.js#9738] opened 2018-05-18 16:07 UTC
Attach file here:
[signatures.pdf](https://github.com/mozilla/pdf.js/files/2017597/signatures.pdf)

Configuration:
- Browser: Safari 11.1 (13605.1.33.1.4)
- Operating system: macOs High Sierra - v. 10.13.4
- PDF.js version: 1.2.109

Steps to reproduce the problem:
1. open signatures.pdf in viewer.html 

What is the expected behavior? signatures.pdf has 4 signatures in the last page
![expected](https://user-images.githubusercontent.com/5559033/40245368-c0090748-5ac5-11e8-9fca-f3b6a4bc95c7.png)

What went wrong? reloading the page with safari, or changing the zoom value, not all signature are rendered. The page changes in a random way. 
![wrong](https://user-images.githubusercontent.com/5559033/40245449-00e1b6d4-5ac6-11e8-8c1d-218bacb2776c.png)

**Comment by THausherr** [comment] 2018-05-20 18:52
This file was signed by PDFBox. The BBox is in the wrong order
https://issues.apache.org/jira/browse/PDFBOX-4011
This may or may not be the cause, it could also be #4743.

**Comment by bimbogino** [comment] 2018-05-21 07:25
Thank you: we will try with a correct pdf asap.
Also, I would like to point out that the problem only occurs with safari, and not with other browsers.

**Comment by THausherr** [comment] 2018-05-21 07:49
Make sure to use the latest PDFBox version (2.0.9), the BBox bug is fixed there. If possible, use the upcoming 2.0.10 which can be found at
https://repository.apache.org/content/groups/snapshots/org/apache/pdfbox/pdfbox-app/2.0.10-SNAPSHOT/
it fixes another weird signature problem that occured on chrome
https://issues.apache.org/jira/browse/PDFBOX-3631

**Comment by Snuffleupagus** [comment] 2021-03-23 15:40
Duplicate of #1076

**Closed** 2021-03-24 19:33 UTC
Labels: 4-image-conversion
