### ISSUE TITLE
Broken pdf

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15577] opened 2022-10-15 14:55 UTC
Attach (recommended) or Link to PDF file here:
https://gitlab.gnome.org/GNOME/evince/uploads/9632b1b51527bd0cb975088864f1f496/hang-080214-152005-90.pdf

It has been reported on Gnome bug tracker:
https://gitlab.gnome.org/GNOME/evince/-/issues/1837

Acrobat fails to open it but Chrome is ok.

**Comment by Snuffleupagus** [comment] 2022-10-15 15:18
This is corrupt at a level that I *really* question the value in even trying to fix this, since this particular issue shouldn't be common, given that it tries to reference a non-existent /Root dictionary (note now the generation doesn't match).
Not to mention that attempting to hack around this one issue also (potentially) seems messy, since you cannot just ignore the generation in the general case.

```
%PDF-1.2
%zG_   J   #s6 dR L s
1 0 obj
<<
/Type /Catalog
/Pages 3 0 R
/Outlines 2 0 R
>>
endobj

[...]

xref
0 16
0000000000 65535 f 
0000000034 00000 n 
0000000099 00000 n 
0000000145 00000 n 
0000000223 00000 n 
0000000251 00000 n 
0000000445 00000 n 
0000002909 00000 n 
0000003103 00000 n 
0000005042 00000 n 
0000005237 00000 n 
0000007111 00000 n 
0000007307 00000 n 
0000008976 128 n 
0000009094 00000 n 
0000009094 00000 n 
0000009207 -1 n 
trailer
<<
/Size 16
/Root 1 1 R
/Info 15 0 R
>>
startxref
9434
%%EOF
```

**Comment by calixteman** [comment] 2022-10-15 15:40
I just replaced 1 by 0 for the root ref and the rendering is ok.

When a generation doesn't exist, maybe we could try to fallback on the previous one (until 0), wdyt ?
I don't know if it make sense or not or if it could lead to have something really wrong, so if it's a stupid idea, tell me.

**Comment by Snuffleupagus** [comment] 2022-10-15 16:37
> I just replaced 1 by 0 for the root ref and the rendering is ok.

Yes, in this particular case it's appears to be quite simple but in the general case it's unfortunately more difficult.

> When a generation doesn't exist, maybe we could try to fallback on the previous one (until 0), wdyt ?

I've actually tried something along those lines myself, by modifying the `XRef.fetchUncompressed` method as below, however that causes at least one obvious regression in the `issue7496.pdf` document.
```diff
diff --git a/src/core/xref.js b/src/core/xref.js
index 9159ad437..326becdde 100644
--- a/src/core/xref.js
+++ b/src/core/xref.js
@@ -780,7 +780,17 @@ class XRef {
     const gen = ref.gen;
     let num = ref.num;
     if (xrefEntry.gen !== gen) {
-      throw new XRefEntryException(`Inconsistent generation in XRef: ${ref}`);
+      const msg = `Inconsistent generation in XRef: ${ref}`;
+      // Try falling back to a *previous* generation (fixes issue15577.pdf).
+      if (xrefEntry.gen < gen) {
+        warn(msg);
+        return this.fetchUncompressed(
+          Ref.get(num, xrefEntry.gen),
+          xrefEntry,
+          suppressEncryption
+        );
+      }
+      throw new XRefEntryException(msg);
     }
     const stream = this.stream.makeSubStream(
       xrefEntry.offset + this.stream.start
```

> I don't know if it make sense or not or if it could lead to have something really wrong, so if it's a stupid idea, tell me.

It's definitely *not* a bad idea, but unfortunately it doesn't really work out on its own. I can see a *potential* tweak, but then we're getting closer to the "ugly hack" territory unfortunately...

**Comment by calixteman** [comment] 2022-10-15 16:49
Ok so we could only fallback when what we're fetching is really fundamental like Root, but maybe it's what you're calling the "ugly hack" territory.

**Comment by Snuffleupagus** [comment] 2022-10-15 17:28
> Ok so we could only fallback when what we're fetching is really fundamental like Root,

Unfortunately that doesn't work, since `issue7496.pdf` breaks precisely during that part of the `XRef.indexObject` method.

**Comment by Snuffleupagus** [comment] 2022-10-16 11:19
This is the smallest patch that I can come up with, which is maybe not that bad (even though I'm not too excited about adding even more hacks to this part of the code-base): https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:pdf.js:issue-15577

**Comment by Snuffleupagus** [comment] 2022-10-18 17:35
@calixteman How do you feel about the patch above, do we actually want to try and fix this issue?

**Comment by calixteman** [comment] 2022-10-18 17:48
My main motivation is to try to keep the Firefox users and avoid to let them leave it for an other one even if it's just for a PDF and for 5 minutes.
But in the meantime, I completely understand that adding some complexity just for maybe one corner cases is a bit annoying.
So personally, I'd say "push it, we're able to manage the complexity" but I trust your judgement, experience, ... to know if it's worth adding it.
In general, I really appreciate the work you do to fix these corner cases because at the end the sum of those is likely not that much negligible and it helps to improve the overall quality of pdf.js and consequently Firefox.
Anyway +1 for me.

**Comment by Snuffleupagus** [comment] 2022-10-18 18:04
My general worry when dealing with this sort of /XRef corruption is that it can *sometimes* be easy to fix one thing and accidentally break another class of corrupt documents; guess how I know that :-)

In this case though, the latest version of the patch should be pretty safe since we'll only attempt the "generation fallback" as a last resort when nothing else worked *and* there were errors during parsing. I'll add a test-case and try to write a helpful commit message, so that we can try to get this landed (it passes all tests locally at least).

**Closed** 2022-10-19 07:44 UTC
Labels: pdf-broken, corrupted-pdf
