### ISSUE TITLE
RE : resolution problem

### ISSUE THREAD

**Issue by parksuhyun9321** [mozilla/pdf.js#17145] opened 2023-10-20 09:40 UTC
Attach (recommended) or Link to PDF file here:

Configuration:

Web browser and its version: Google Chrome (ver 118.0.5993.70)
Operating system and its version: Windows 11 Home 22H2
PDF.js version: 4.0.75
Is a browser extension:
Steps to reproduce the problem:

The resolution drops when load pdf from the window screen
Need a way to adjust the font on the pdf page
What is the expected behavior? (add screenshot)
https://github.com/mozilla/pdf.js/assets/59465364/6433d72a-a347-4b22-830c-36df3726be6e

What went wrong? (add screenshot)
https://github.com/mozilla/pdf.js/assets/59465364/b7dccca2-74d0-411d-a779-3cc6e88569b9

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-10-20 09:50
Duplicate of #17127

**Closed by Snuffleupagus** 2023-10-20 09:50 UTC
