### ISSUE TITLE
This PDF renders slowly when the window is large

### ISSUE THREAD

**Issue by jruderman** [mozilla/pdf.js#4572] opened 2014-04-07 23:19 UTC
1. Create a new Firefox profile
2. Maximize the Firefox window (important!)
3. Load http://makezineblog.files.wordpress.com/2013/07/integratedspaceplan2color.pdf

Result: PDF renders very slowly. When it is adding text, it adds one letter at a time IFF the word being drawn is on-screen.

(Firefox Nightly on Mac; Retina MBP with 1440x900 CSS-pixel resolution)

Sample: https://gist.github.com/jruderman/10072492

**Comment by timvandermeij** [comment] 2015-02-28 15:47
Closing as fixed. A lot of performance fixes have been merged in the meantime and I cannot reproduce the issue anymore using Firefox 36 on Windows. Even with text layer it renders quite fast (given that this is a huge PDF file to render). We have more open issues with similar files and issues, so this can be closed.

**Closed by timvandermeij** 2015-02-28 15:47 UTC
Labels: 2-performance, 4-text-selection
