### ISSUE TITLE
Change code base to improve performance of PDFJS (see the issue https://github.com/mozilla/pdf.js/issues/6493)

### ISSUE THREAD

**Issue by huyvandoan** [mozilla/pdf.js#6575] opened 2015-10-29 11:07 UTC
All,

According to the issue https://github.com/mozilla/pdf.js/issues/6493, there is a problem that relating to performance when rendering a special scanning file (CCITTFaxStream). 

I used the latest version of pdf js (v1.1.469). I deployed to IIS Manager and tested it on localhost but pdf.js renders slowly.
Here is detail information:
- File for testing: https://drive.google.com/open?id=0BzoKdQwBinAnXzVJcmdVZjBmbkE
- System detail: my computer's hardware: Window 7x 64, RAM: 12 GB, Processors: Intel Core i5. I use Chrome browser and its version is 46.0.2490.80 m

I have logged time at render function of PDF.JS as follows:

``` javascript
render: function PDFPageProxy_render(params) {
      var stats = this.stats;
      stats.time('Overall');
      ....
    function complete(error) {
       ...
        stats.timeEnd('Rendering');
        stats.timeEnd('Overall');

        console.log(stats.toString());
      }
}
```

This is logging time:
Page Request: 20ms
Rendering: 3284ms
=> Overall: 3304ms

I would like to change the code base to improve performance. I have done the following things:
- I found that pdf.js takes long time at the function putBinaryImageData
- I have checked the function putBinaryImageData . This function renders an image into canvas from bytes array. Because bytes array is too big (16,843,200 bytes), this function takes about 3s to render. Thus, in order to reduce the processing time, I think the solution is to scale down the input bytes array before rendering. But it is unable to do with JavaScript.

Could you possibly advise how to improve in this case?

Regards,
Huy

**Comment by timvandermeij** [comment] 2015-10-29 20:46
Renders withing two seconds for me. Not surprising as the image is 10000x13000, way too large for a web PDF. Marking as performance issue, but since this is a corner case, I don't expect it to be resolved soon.

**Comment by huyvandoan** [comment] 2015-10-30 11:37
Could you possibly advise me how to fix the issue? I will try to do it by myself. Thanks

**Comment by timvandermeij** [comment] 2015-10-30 12:37
I don't know, but if you have control over the PDF file creation you can try using the tips at https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#optimize.

**Comment by yurydelendik** [comment] 2015-10-30 12:41
Here is the place where image is  decoded  https://github.com/mozilla/pdf.js/blob/master/src/core/stream.js#L1331

**Comment by huyvandoan** [comment] 2015-11-02 12:47
Hi Tim, I don't have the control over the PDF creation, I just receive the data and display at client side.
Hi Yury, What should I do at decode method?

**Comment by yurydelendik** [comment] 2015-11-02 15:49
> What should I do at decode method?

That is where huge array created. So you can: a) change decoder to produce less data, b) resize data down in the caller of the decode method? I have no preference which method you choose in your solution -- both of them doable and at the same moment hard to implement efficiently.

**Comment by huyvandoan** [comment] 2015-11-06 17:39
Our team fixed the issue, the performance has been improved. I will check-in the changes in early next week so that you can give a feedback.

**Comment by fbender** [comment] 2015-11-16 15:48
@huyvandoan Did you already post the fix somewhere? May you please link to the PR in this issue?

**Comment by huyvandoan** [comment] 2015-11-19 13:29
Here is the fixes:

```javascript

/**
     * Added by RamSoft (11/5/2015) to resize large resolution PDFS as to improve rendering time
     */
    resizeGrayPixels: function(imgData, comps, bpc) {
      var result = false;

      //we only resize 1 bit per pixel or 8 bits per pixel grayscale image
      if (comps == 1 && (bpc == 1 || bpc == 8)) {
        var scaleBits;
        var h1 = imgData.height;
        var w1 = imgData.width;

        if ((h1 > 15000) || (w1 > 15000)) {
           scaleBits = 3;
        } else if ((h1 > 10000) || (w1 > 10000)) {
           scaleBits = 2;
        } else if ((h1 > 5000) || (w1 > 5000)) {
           scaleBits = 1; // 25% - 4
        } else {
           scaleBits = 0;
        }

        if (scaleBits > 0) {
          var w2 = w1 >> scaleBits;
          var h2 = h1 >> scaleBits;

          var newRowBytes = (w2 * comps * bpc + 7) >> 3;
          var originalRowBytes = (w1 * comps * bpc + 7) >> 3;;

          var numBytes = h2*newRowBytes; 
          var pixelArrayOutput = new Uint8Array(numBytes);
           
          if (bpc == 1) {

            for (var i = 0; i < h2; i ++) {
              var y2 = i << scaleBits;
              var originalRowStart = y2*originalRowBytes;
              var newRowStart = i*newRowBytes; 

              for (var j = 0; j < w2; j++) {
                  var x2 = j << scaleBits;

                  //we want original value of pixel [x2, y2] value in original image
                  //to populate pixel [i, j] in new image

                  var originalColByteStart = x2 >> 3;
                  var originalColBitMask = 1 << (7 - (x2 & 7)); 
                  //most signifcant bit is first pixel due to Little Endian

                  //fastmodule for power of 2 = dividend & (divisor - 1) = dividend % divisor
                  //https://www.chrisnewland.com/high-performance-modulo-operation-317

                  var originalColByte = imgData.data[originalRowStart + originalColByteStart];
                  var pixelValue = originalColByte & originalColBitMask;

                  if (pixelValue > 0) {
                    var newColByteStart = j >> 3;
                    var newColBitMask = 1 << (7 - (j & 7));
                    //most signifcant bit is first pixel due to Little Endian

                    var newColByte = pixelArrayOutput[newRowStart + newColByteStart];

                    newColByte = newColByte | newColBitMask; 
                    //set pixel bit to 1
                    pixelArrayOutput[newRowStart + newColByteStart] = newColByte; 
                  }     
              }
            }
          } else {
            for (var i = 0; i < h2; i ++) {
              var newRowStart = i*newRowBytes;             
              var y2 = i << scaleBits;
              var originalRowStart = y2*originalRowBytes;             

              for (var j = 0; j < w2; j++) {
                  var x2 = j << scaleBits;
    
                  pixelArrayOutput[newRowStart + j] = imgData.data[originalRowStart + x2];
              }
            }
          }

          imgData.data = pixelArrayOutput;
          imgData.width = w2;
          imgData.height = h2; 

          result = true;
        }
      }

      return result;
    },

    createImageData: function PDFImage_createImageData(forceRGBA) {
      var drawWidth = this.drawWidth;
      var drawHeight = this.drawHeight;
      var imgData = { // other fields are filled in below
        width: drawWidth,
        height: drawHeight
      };

      var numComps = this.numComps;
      var originalWidth = this.width;
      var originalHeight = this.height;
      var bpc = this.bpc;

      // Rows start at byte boundary.
      var rowBytes = (originalWidth * numComps * bpc + 7) >> 3;
      var imgArray;

      if (!forceRGBA) {
        // If it is a 1-bit-per-pixel grayscale (i.e. black-and-white) image
        // without any complications, we pass a same-sized copy to the main
        // thread rather than expanding by 32x to RGBA form. This saves *lots*
        // of memory for many scanned documents. It's also much faster.
        //
        // Similarly, if it is a 24-bit-per pixel RGB image without any
        // complications, we avoid expanding by 1.333x to RGBA form.
        var kind;
        if (this.colorSpace.name === 'DeviceGray' && bpc === 1) {
          kind = ImageKind.GRAYSCALE_1BPP;
        } else if (this.colorSpace.name === 'DeviceRGB' && bpc === 8 &&
                   !this.needsDecode) {
          kind = ImageKind.RGB_24BPP;
        }
        if (kind && !this.smask && !this.mask &&
            drawWidth === originalWidth && drawHeight === originalHeight) {
          imgData.kind = kind;

          imgArray = this.getImageBytes(originalHeight * rowBytes);
          // If imgArray came from a DecodeStream, we're safe to transfer it
          // (and thus neuter it) because it will constitute the entire
          // DecodeStream's data.  But if it came from a Stream, we need to
          // copy it because it'll only be a portion of the Stream's data, and
          // the rest will be read later on.
          if (this.image instanceof DecodeStream) {
            imgData.data = imgArray;
          } else {
            var newArray = new Uint8Array(imgArray.length);
            newArray.set(imgArray);
            imgData.data = newArray;
          }
          if (this.needsDecode) {
            // Invert the buffer (which must be grayscale if we reached here).
            assert(kind === ImageKind.GRAYSCALE_1BPP);
            var buffer = imgData.data;
            for (var i = 0, ii = buffer.length; i < ii; i++) {
              buffer[i] ^= 0xff;
            }
          }
          
          // Added by RamSoft (11/4/2015)
          // Not resize data when rendering on web
          if (!this.print) {
            if (kind == ImageKind.GRAYSCALE_1BPP) {
              this.resizeGrayPixels(imgData, numComps, bpc);
            }
          }

          return imgData;
        }
        if (this.image instanceof JpegStream && !this.smask && !this.mask &&
            (this.colorSpace.name === 'DeviceGray' ||
             this.colorSpace.name === 'DeviceRGB' ||
             this.colorSpace.name === 'DeviceCMYK')) {
          imgData.kind = ImageKind.RGB_24BPP;
          imgData.data = this.getImageBytes(originalHeight * rowBytes,
                                            drawWidth, drawHeight, true);
          return imgData;
        }
      }

      imgArray = this.getImageBytes(originalHeight * rowBytes);

      if (this.colorSpace.name === 'DeviceGray') {
        var resizedImgData = {
          data: imgArray,
          width: originalWidth,
          height: originalHeight
        };

        //Added by RamSoft (11/4/2015)
        // Not resize data when rendering on web
        if (!this.print) {
          if (this.resizeGrayPixels(resizedImgData, numComps, bpc)) {
            imgArray = resizedImgData.data;
            originalHeight = resizedImgData.height;
            originalWidth = resizedImgData.width;
            rowBytes = (originalWidth * numComps * bpc + 7) >> 3;
          }
        }
      }

      // imgArray can be incomplete (e.g. after CCITT fax encoding).
      var actualHeight = 0 | (imgArray.length / rowBytes *
                         drawHeight / originalHeight);

      var comps = this.getComponents(imgArray);

      // If opacity data is present, use RGBA_32BPP form. Otherwise, use the
      // more compact RGB_24BPP form if allowable.
      var alpha01, maybeUndoPreblend;
      if (!forceRGBA && !this.smask && !this.mask) {
        imgData.kind = ImageKind.RGB_24BPP;
        imgData.data = new Uint8Array(drawWidth * drawHeight * 3);
        alpha01 = 0;
        maybeUndoPreblend = false;
      } else {
        imgData.kind = ImageKind.RGBA_32BPP;
        imgData.data = new Uint8Array(drawWidth * drawHeight * 4);
        alpha01 = 1;
        maybeUndoPreblend = true;

        // Color key masking (opacity) must be performed before decoding.
        this.fillOpacity(imgData.data, drawWidth, drawHeight, actualHeight,
                         comps);
      }

      if (this.needsDecode) {
        this.decodeBuffer(comps);
      }
      this.colorSpace.fillRgb(imgData.data, originalWidth, originalHeight,
                              drawWidth, drawHeight, actualHeight, bpc, comps,
                              alpha01);
      if (maybeUndoPreblend) {
        this.undoPreblend(imgData.data, drawWidth, actualHeight);
      }

      return imgData;
    }

```

**Comment by huyvandoan** [comment] 2015-11-19 13:32
With these changes, the rendering time is significant (within 1 second, Chrome has the best performance - 0.5 second). Edge takes more time (around 1.5 second) but I believe that it will be improved in near future

**Comment by huyvandoan** [comment] 2015-11-30 08:39
All, can you review the changes and let me know your thoughts?

**Comment by brendandahl** [comment] 2015-11-30 16:54
@huyvandoan Can you open a pull request with the changes? That will be easier to review.

**Comment by Vishnupriya112** [comment] 2018-07-20 06:20
Which Version is this pdf.js 2012 Version?

**Comment by Vishnupriya112** [comment] 2018-07-20 09:09
@huyvandoan  Where are you calling this function createImageData?

**Comment by timvandermeij** [comment] 2019-01-15 22:49
The pull request above is closed; refer to https://github.com/mozilla/pdf.js/pull/7047#issuecomment-454581807 for the reasons. We'll keep this open for tracking the issue and we can reopen/revisit the PR if the other PR does not already have enough effect for this.

**Comment by Snuffleupagus** [comment] 2021-09-28 10:12
> File for testing: https://drive.google.com/open?id=0BzoKdQwBinAnXzVJcmdVZjBmbkE

That file is no longer available, but given that https://github.com/mozilla/pdf.js/issues/6575#issue-114027248 mentions "CCITTFaxStream" let's mark this as duplicate of #6741.

**Closed by Snuffleupagus** 2021-09-28 10:12 UTC
Labels: 1-core, 2-performance
