### ISSUE TITLE
Black Circle is displayed - incorrect rendering in FF 37

### ISSUE THREAD

**Issue by dmpe** [mozilla/pdf.js#5810] opened 2015-03-07 11:51 UTC
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0 Beta 3

The file is protected by copyright from http://www.sciencedirect.com/science/article/pii/S0146638011000301, but here is the link to the copy. 

![ff](https://cloud.githubusercontent.com/assets/1799661/6541309/8483d112-c4c8-11e4-8a5c-83cccd018cce.PNG)

https://drive.google.com/file/d/0B1NSNTZNwoWnQkp2dXRGdGItVGs/view?usp=sharing

Please ask for more questions if needed.

**Comment by Snuffleupagus** [comment] 2015-03-07 11:58
Thanks for the report! However, given that this is a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=858128, I'm closing this issue.

**Closed by Snuffleupagus** 2015-03-07 11:58 UTC

**Comment by dmpe** [comment] 2015-03-07 12:05
Thanks.
