### ISSUE TITLE
./node_modules/pdfjs-dist/build/pdf.js Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by akhil-sreenivasan** [mozilla/pdf.js#13729] opened 2021-07-14 09:36 UTC
Steps to reproduce the problem:
after ReactRenderer installation getting compilation error in react project using Webpack 4
1. import { ReactRenderer } from '@atlaskit/renderer';

What is the expected behavior? (add screenshot)
Compiler error must removed

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/51120982/125599646-77c35302-0f65-442c-955d-e0b532d7d475.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-07-14 09:46
Duplicate of #10324, note e.g. https://github.com/mozilla/pdf.js/issues/10324#issuecomment-568179067 and that you're most likely using an outdated version of the PDF.js library.

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue contains nowhere near enough information to be actionable/valid.

**Closed by Snuffleupagus** 2021-07-14 09:46 UTC
