### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#17911] opened 2024-04-09 10:41 UTC
Attach (recommended) or Link to PDF file here:
[24-HTFFFCU-00921_Auto_Refi_Preapproval_1.pdf](https://github.com/mozilla/pdf.js/files/14917421/24-HTFFFCU-00921_Auto_Refi_Preapproval_1.pdf)

Configuration:
- Web browser and its version: Chrome 123.0.6312.86
- Operating system and its version: Windows 10
- PDF.js version: version used in viewer mozilla.github.io/pdf.js
- Is a browser extension: no

Steps to reproduce the problem:
1. open attached PDF
2. got to page 2

What is the expected behavior? (add screenshot)
![Screenshot_2024-04-08_at_2 42 44_PM](https://github.com/mozilla/pdf.js/assets/947206/089275ad-1e69-4545-9b0d-36b2a98fe499)

What went wrong? (add screenshot)
Parts of a background not rendered

See above screenshot (left side shows the error - right side shows it as it should be)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2024-04-09 11:10
I cannot reproduce the issue when opening the PDF file with https://mozilla.github.io/pdf.js/web/viewer.html on Arch Linux with Firefox 124.0.2. The screenshot also shows what looks like a modified PDF.js viewer or maybe even a whole different viewer that is not PDF.js, so this issue is most likely related to the custom implementation or to Chrome/Windows (since otherwise one would expect it to be broken _consistently_ everywhere). Unless it can be shown that in fact vanilla PDF.js contains a bug, this issue is therefore closed as invalid for now.

**Closed by timvandermeij** 2024-04-09 11:10 UTC

**Comment by blackmambahk** [comment] 2024-04-09 11:20
Thanks for closing the issue without even waiting for a response.

I replicated the client reported issue using the PDFJS  demo viewer in the current version of **Chrome and windows 10 AS STATED IN THE ABOVE REPORT.**

I then added a screenshot sent by the client to help add information as to what looks wrong, clearly that was my mistake I should not have bothered.

**Comment by calixteman** [comment] 2024-04-09 12:15
> Thanks for closing the issue without even waiting for a response.
> 
> I replicated the client reported issue using the PDFJS demo viewer in the current version of **Chrome and windows 10 AS STATED IN THE ABOVE REPORT.**
> 
> I then added a screenshot sent by the client to help add information as to what looks wrong, clearly that was my mistake I should not have bothered.
> 
> Is ti now the case we have to replicate an issue on Firefox running on linux in order to make a report valid??

Just as a reminder, pdf.js is developed for Firefox and because it's open source and thanks to the contributors it has an existence outside Firefox.
So yes, if a bug cannot be reproduced with Firefox on linux/windows/mac then it's very very likely because of the browser you're using.
And here it's the case: I can reproduce the bug with Chrome but if I disable `Accelerated 2D canvas` in `chrome://flags` then the bug isn't here anymore, so please file a bug in the Chrome [bug tracker](https://issues.chromium.org/issues) (and you can add a link to the issue here to let the people having a similar issue know).
