### ISSUE TITLE
After importing the pdf file, some pictures disappeared.

### ISSUE THREAD

**Issue by QM36** [mozilla/pdf.js#12930] opened 2021-01-29 09:31 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome & firefox
- Operating system and its version: chrome(88.0.4324.96) firefox(84.0.2)
- Operating system and its version: macOS Catalina 10.15.7
- PDF.js version: the latest(here are the logs)
![image](https://user-images.githubusercontent.com/32392850/106257106-15105200-6257-11eb-9be2-aa361230be14.png)

Steps to reproduce the problem:
1. git clone pdf.js
2. npm i
3. gulp server
4. Visit this address in a browser: http://localhost:8888/ 

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/32392850/106257350-63bdec00-6257-11eb-93a7-b8b813662069.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/32392850/106257409-7506f880-6257-11eb-94df-66bac4bc7bdd.png)
Obviously, the red seal is gone.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[demo.pdf](https://github.com/mozilla/pdf.js/files/5892928/demo.pdf)

**Comment by Snuffleupagus** [comment] 2021-01-29 09:56
Duplicate of #1076

**Closed** 2021-01-29 19:59 UTC
