### ISSUE TITLE
Viewer display wrong with textbox vertical (lastest version)

### ISSUE THREAD

**Issue by anhvt1989** [mozilla/pdf.js#15002] opened 2022-06-08 04:56 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome
- PDF.js version: lastest

Steps to reproduce the problem: ( Green box)
1. Open file with https://mozilla.github.io/pdf.js/web/viewer.html
2. Open file with default browser
![Screenshot from 2022-06-08 11-51-33](https://user-images.githubusercontent.com/107095424/172534679-fea25603-753c-4d5d-b060-cbc304bebfad.png)
![Screenshot from 2022-06-08 11-52-04](https://user-images.githubusercontent.com/107095424/172534690-2519ad42-3618-47a2-82bb-5fc7c7cdbc19.png)

**Comment by Snuffleupagus** [comment] 2022-06-08 08:05
> Attach (recommended) or Link to PDF file here:

Without that information, this issue (or any issue really) is not actionable/valid.

---

Duplicate of #9596 (which is a best guess, given that lack of *crucial* information).

**Closed by Snuffleupagus** 2022-06-08 08:05 UTC
Labels: information-requested

**Comment by marco-c** [comment] 2022-06-29 12:48
@anhvt1989 the issue should be fixed in latest pdf.js master (or latest Firefox Nightly).
