### ISSUE TITLE
PDF Taking a Long Time To Render

### ISSUE THREAD

**Issue by Jon-Murray** [mozilla/pdf.js#9581] opened 2018-03-18 14:30 UTC
[architectural_-_annotation_scaling_and_multileaders.SECTIONS AND DETAILSs2 (2).png.pdf](https://github.com/mozilla/pdf.js/files/1822749/architectural_-_annotation_scaling_and_multileaders.SECTIONS.AND.DETAILSs2.2.png.pdf)
![architectural_-_annotation_scaling_and_multileaders sections and detailss2](https://user-images.githubusercontent.com/2168795/37567041-ff19c8f6-2ab8-11e8-8482-c35a7d9ed6cc.png)

Hi guys,

Apologies, as I hate these types of bug filings, but I have a relatively simple PDF which takes a long time to load on FF 59. This loads pretty much instantly in other PDF viewers. The PDF is just an embedded PNG inside a PDF document (though the attached document has a simple annotation added as well, this happens without it). It is causing me some grief as it takes ~40 seconds to load in Firefox/embedded PDFJS (both the most up-to-date versions as of March 2018) but has no issues in other browsers. Both the PDF and the original PNG should be attached here.

Configuration:
- Web browser and its version: FF 59
- Operating system and its version: Windows, Ryzen 1700, 16GB RAM
- PDF.js version: (PDF.js: 2.0.288) and older
- Is a browser extension: Both native FF and using PDFJS in other browsers

Steps to reproduce the problem:
1.  Open the attached PDF

What is the expected behavior? (add screenshot) Renders ~5s

What went wrong? (add screenshot): Consistently renders ~40s

I really have no further information nor the skills to say why the resultant PDF is complex, sorry. 

Thanks!

**Comment by Jon-Murray** [comment] 2018-03-18 14:31
![architectural_-_annotation_scaling_and_multileaders sections and detailss2](https://user-images.githubusercontent.com/2168795/37567046-102fd392-2ab9-11e8-80bf-d5603d480dce.png)

**Comment by timvandermeij** [comment] 2018-03-18 14:36
Evince takes about six seconds to render this PDF file. I think the problem is that the embedded image is 8000 x 5333 pixels, which is really large. Vector images would be much faster than large embedded PNG images. To fix this, we most likely need canvas tiling.

**Comment by Jon-Murray** [comment] 2018-03-18 14:46
Hi, thanks for getting back so ridiculously quickly! I have tried resizing this to a standard (scaled) A4 PDF as well which also seems to take quite a while to render. This is a different file but both are attached here. Again this renders slowly on FF/PDFJS but quickly on other browser. These are both images generated from CAD drawings so may be complex.

Thanks again
[architectural_-_annotation_scaling_and_multileaders.Model (1).png.pdf](https://github.com/mozilla/pdf.js/files/1822771/architectural_-_annotation_scaling_and_multileaders.Model.1.png.pdf)
![architectural_-_annotation_scaling_and_multileaders model](https://user-images.githubusercontent.com/2168795/37567183-25182aaa-2abb-11e8-9203-25fbbd29fc2c.png)

**Comment by Jon-Murray** [comment] 2018-03-18 14:47
![architectural_-_annotation_scaling_and_multileaders model](https://user-images.githubusercontent.com/2168795/37567189-30e0c4dc-2abb-11e8-8b02-f073f3f10367.png)

**Comment by THausherr** [comment] 2018-03-19 09:32
Related / Duplicate of issue #6741 ?

**Comment by mauro1855** [comment] 2018-12-06 09:38
Hi,
We have the issue. We are using pdf.js to render a 1-page, 444 kB PDF with a  7027x4972 image embeded. It takes around 15 to 20 seconds to render this PDF. The same happens if I try to open the PDF with FF 63.0.3 default previewer.
The same does not happen when opening the PDF in Chrome and Edge, its immediate.

Thanks,
Mauro

**Comment by timvandermeij** [comment] 2020-06-07 11:10
Closing since this file now renders in about 5 seconds after the fix above, as indicated in the original post and as I found Okular takes too.

**Closed by timvandermeij** 2020-06-07 11:10 UTC
Labels: 1-core, 2-performance, 4-image-conversion
