### ISSUE TITLE
PDFs with bookmarks (outline) annoyingly revert to Page Fit zoom level when clicking on a bookmark

### ISSUE THREAD

**Issue by fitojb** [mozilla/pdf.js#9235] opened 2017-12-04 21:05 UTC
Configuration:
- Browser: Firefox 57
- OS: Windows 7 SP1/Ubuntu 18.04 development version
- PDF.js version: the one included with Fx 57
- Is a browser extension: no

Steps to reproduce the problem:
1. Open [this file](https://dspace.utamu.ac.ug/bitstream/123456789/182/1/Research-Methods-in-Education-sixth-edition.pdf).
2. Change the default zoom level to e.g. Fit Width.
3. Click on any item from the outline.

I expect the zoom level to stay the same after clicking on the bookmark; the only effect of clicking it is to jump to a certain page. Instead, what happens is that I get to the requested page but the zoom level reverts to Page Fit.

**Comment by yurydelendik** [comment] 2017-12-04 21:15
That's expected behavior -- PDF bookmark indeed override zoom to fit the page. Acrobat Reader behaves the same way. Closing as invalid.

**Comment by Snuffleupagus** [comment] 2017-12-04 21:15
The "links" (or destinations, as they are called in PDF files), can and in this case do specify the zoom level that should be used when they are clicked.
Compare with e.g. Adobe Reader, where the behaviour is the same as in PDF. Please refer to the PDF specification for additional information, e.g. [here](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G11.1947713) and [here](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G11.1696125).

Closing as invalid, since this works as intended.

**Closed by yurydelendik** 2017-12-04 21:15 UTC
Labels: 1-viewer

**Comment by fitojb** [comment] 2017-12-10 03:05
Can’t we have an about:config preference to override this behavior?

**Comment by SwiftWinds** [comment] 2020-07-13 08:44
Sorry for bumping a 3 year old issue, but for posterity's sake, but this:

> Can’t we have an about:config preference to override this behavior?

now exists. Simply enable `pdfjs.ignoreDestinationZoom` in `about:config`.

**Comment by fitojb** [comment] 2020-07-13 09:47
Too late for me — I’ve stopped using Firefox after a plurality of fuck-ups by Mozilla Corporation.
