### ISSUE TITLE
Find-in-page highlight-box is at wrong y-position in Coway airmega PDF-manual

### ISSUE THREAD

**Issue by dholbert** [mozilla/pdf.js#12334] opened 2020-09-06 15:23 UTC
Attach (recommended) or Link to PDF file here:
https://images-na.ssl-images-amazon.com/images/I/D1SWYNC4nwS.pdf
[D1SWYNC4nwS.pdf](https://github.com/mozilla/pdf.js/files/5179859/D1SWYNC4nwS.pdf)

Configuration:
- Web browser and its version: Firefox Nightly 82.0a1 (2020-09-05)
- Operating system and its version: Windows 10
- PDF.js version: Not sure; whatever's shipped with Nightly right now
- Is a browser extension: not an extension that I manually installed; just the built-in version.

Steps to reproduce the problem:
1. Load attached PDF
2. Find-in-page (Ctrl+F) and type "clean".
3. (optional): Ctrl+G to skip through a few matches

What is the expected behavior?
The text "clean" should be highlighted for each match.

What went wrong? (add screenshot)
The highlighted box is above the text, approximately one line-height away:
![image](https://user-images.githubusercontent.com/426803/92329076-02804c80-f01a-11ea-872c-6e0a4fdac227.png)
![image](https://user-images.githubusercontent.com/426803/92329088-0d3ae180-f01a-11ea-99d3-5174c8c112a0.png)

**Comment by piexpie** [comment] 2020-09-23 06:27
Yeah, so I tried to reproduce the bug and it is evident that the y-position is not correct.

This is not a problem with the PDF document itself since the same document selection is rendered correctly in Edge's PDF Viewer. This probably has to do with the y-offset in rendering the selection.

**Comment by piexpie** [comment] 2020-09-25 05:48
Please assign this issue, I can begin some work on this.

**Comment by timvandermeij** [comment] 2021-02-13 15:28
Closing since this got fixed by #12896 and other work.

**Closed by timvandermeij** 2021-02-13 15:28 UTC
Labels: 4-text-selection
