### ISSUE TITLE
Empty page added when printing in Firefox

### ISSUE THREAD

**Issue by amster007** [mozilla/pdf.js#10829] opened 2019-05-16 11:31 UTC
Problem appears on Windows 10, Firefox 65 and higher, PDF.js 1.8.186 and higher using pdf.js library (problem doesn't appears when using embedded firefox pdf viewer).

Problem doesn't appears on Chrome 72

Steps to reproduce:
1. Add pdf document to pdf.js viewer (e.g. 3 pages)
2. Click print button from pdf.js viewer
3. On print preview number of pages is correct
4. Print document
5. There are 4 pages printed and the last page is almost empty except few pixel rows on top of the page which did not fit on last page from pdf.js viewer preview

Actual results:
It seems pdf.js prints a picture of html page shows in the viewer but few last pixel rows did not fit on last page. So another page is added.

Expected results:
Firefox should print exact number of document pages.

**Comment by timvandermeij** [comment] 2019-05-16 19:23
Closing since this is a duplicate of some other issues in https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-printing regarding extra pages being printed.

**Closed by timvandermeij** 2019-05-16 19:23 UTC

**Comment by amster007** [comment] 2019-05-17 16:05
@timvandermeij You will do nothing with it? That's how you fix the bugs?

**Comment by timvandermeij** [comment] 2019-05-17 21:37
There is no point in having multiple issues open for the same problem. It's still tracked in the other issues so it can be solved.
