### ISSUE TITLE
Unable to render PDF on drawing document (blank result)

### ISSUE THREAD

**Issue by azizikhoirulhaq** [mozilla/pdf.js#5755] opened 2015-02-23 11:43 UTC
https://drive.google.com/file/d/0B3OU3WoaKy-XclZYblpjV08xVjQ/view?pli=1
Perfectly rendered on MacOS and Ubuntu Linux OS.
![normal_on_acrobat](https://cloud.githubusercontent.com/assets/8193125/6327181/9802e5e8-bb8b-11e4-8366-3deed05e775c.png)
 

but problem found on Windows.
![error_page](https://cloud.githubusercontent.com/assets/8193125/6327188/a52f907c-bb8b-11e4-93ac-de9ecba55cca.png)

Detail:
OS: Windows 7 32 bit
Processor: Pentium Dual Core T4300 2.10 GHz
Memory: 2GB
Browser: Mozilla Firefox 35.0.1

Please help me.. Thanks..

**Comment by yurydelendik** [comment] 2015-02-24 19:43
Contains picture  7192x11154 -- windows graphics backend (dx?) has known to have problems with loading picture with size more than 8192.

**Comment by Snuffleupagus** [comment] 2015-02-24 19:52
Interestingly this issue seem to be fixed upstream, since I can reproduce with Firefox 36, but *not* with Firefox&nbsp;37. (Tested with the latest version, `1.0.1149`, of PDF.js in both browsers.)

**Comment by azizikhoirulhaq** [comment] 2015-03-10 08:23
Thanks for your help, Mr. yurydelendik, Snuffleupagus, timvandermeij..

**Comment by timvandermeij** [comment] 2015-07-21 20:26
Works for me too now. Closing as fixed upstream.

**Closed by timvandermeij** 2015-07-21 20:26 UTC
Labels: 3-pdf-broken, 4-os-windows
