### ISSUE TITLE
Error: JPEG error: marker was not found

### ISSUE THREAD

**Issue by volochiy-s** [mozilla/pdf.js#7568] opened 2016-08-26 11:45 UTC
I've seen that similar issue was already fixed, however it happens with one of my test files (attached)
[gre_research_validity_data.pdf](https://github.com/mozilla/pdf.js/files/439115/gre_research_validity_data.pdf)

Configuration:
- Google Chrome Version 52.0.2743.116 m, FireFox 47.0.1, Edge 25.10586.0.0 (haven't tried on other browsers)
- Windows 10 Pro version 1511, build 10586.545:
- PDF.js version: pdfjs-dist 1.5.376
- Is an extension: no

Steps to reproduce the problem:
1. Open given PDF with Edge (or any other PDF viewer like Foxit Reader etc.). Notice that there are 4 valid pages.
2. Open given PDF with pdf.js (for example, from [demo page](https://mozilla.github.io/pdf.js/web/viewer.html))
3. Notice that you'll be able to see 4 pages, but 1, 3 and 4 will be blank

actual/expected results side-by-side:

![issue](https://cloud.githubusercontent.com/assets/6917987/18004285/93da9d28-6b9b-11e6-8f0c-5424b5ee96ac.PNG)

**Comment by volochiy-s** [comment] 2016-08-26 11:52
stack trace:

pdf.worker.js:2 Error: JPEG error: marker was not found
2016-08-26 14:51:49.046 pdf.worker.js:2     at o (https://laser-qa.quickhelp.com/dist/pdf.worker.js:2:8390)
    at Object.e.ensureBuffer (https://laser-qa.quickhelp.com/dist/pdf.worker.js:10:22872)
    at Object.e.getBytes (https://laser-qa.quickhelp.com/dist/pdf.worker.js:10:22939)
    at Object.getImageBytes (https://laser-qa.quickhelp.com/dist/pdf.worker.js:15:27973)
    at Object.createImageData (https://laser-qa.quickhelp.com/dist/pdf.worker.js:15:26980)
    at https://laser-qa.quickhelp.com/dist/pdf.worker.js:16:31304
2016-08-26 14:51:49.047 pdf.worker.js:2 Warning: Unable to decode image: Error: JPEG error: marker was not found
2016-08-26 14:51:49.051 ... Warning: Dependent image isn't ready yet

**Comment by Snuffleupagus** [comment] 2016-08-26 12:19
Closing as duplicate of issue #4090.

**Closed by Snuffleupagus** 2016-08-26 12:19 UTC

**Comment by joopeed** [comment] 2017-05-15 18:39
Bug still remains in version 52.0.2

**Comment by doront99** [comment] 2017-09-19 10:38
Hi,
I have the same problem. I have noticed that this problem occures mainly on pdf produced from Samsung printers.

here is a link to a file:
https://drive.google.com/open?id=0By6fVX-F2s1xbGEyeG4xNldKbkNDQ1l1UHFkcXdQZFZ2MXM0

if you need more files, please ask.

Can we re-open the bug?

Thanks,
Doron
