### ISSUE TITLE
overlapping PDF pages.

### ISSUE THREAD

**Issue by munish31** [mozilla/pdf.js#14840] opened 2022-04-26 08:03 UTC
we are encountering an issue where the PDFs pages are overlapping in the viewer.
Attach (recommended) or Link to PDF file here:

Configuration:
Web browser and its version: Google chrome Version 100.0.4896.127
Operating system and its version: Mac OS big Sur
PDF.js version: v2.7.570 and older versions
Is a browser extension: NA
Steps to reproduce the problem:

Notice that there is no gap between pages. Every page is on top of its previous page.
Created PDF viewer using PDF.js library.
What is the expected behavior? (add screenshot) Pdf pages should not overlap with each other.

What went wrong? (add screenshot)Pdf pages are overlapping.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
<img width="1792" alt="Screenshot 2022-04-26 at 1 00 08 PM" src="https://user-images.githubusercontent.com/5114600/165251686-0b89a5dc-5422-4f7d-b873-3a2bbc4da08c.png">

**Comment by Snuffleupagus** [comment] 2022-04-26 08:15
Duplicate of #14839

**Closed by Snuffleupagus** 2022-04-26 08:15 UTC
