### ISSUE TITLE
Multiple downloads

### ISSUE THREAD

**Issue by Motard** [mozilla/pdf.js#9153] opened 2017-11-17 11:13 UTC
I am having the following problem. When I open the first document in pdf.js viewer and click the download button, that document is downloaded. But when I open a second document, and click download, that document is downloaded two times. And if I open a third document, click download, the document is downloaded three times. And so on. Do you have any ideia how I can resolve this issue?

**Comment by timvandermeij** [comment] 2017-11-17 21:00
Which browser are you experiencing this with and on which operating system? Which PDF.js version do you use (web version or extension)?

**Comment by Motard** [comment] 2017-11-18 09:14
This is happening in chrome, I am using macOS, and using web version of PDF.js I think. I should also mention that I am using angular-pdfs-viewer.

**Comment by Snuffleupagus** [comment] 2017-11-18 09:37
> I should also mention that I am using angular-pdfs-viewer.

Can you reproduce this issue in an unmodified version of the PDF.js default viewer, i.e. the one available at https://mozilla.github.io/pdf.js/web/viewer.html?
Personally I cannot reproduce this with the PDF.js default viewer, and please keep in mind that in *our* viewer the download button should even be hidden when you've opened more than one file.

It's certainly possible that this issue is limited to the "angular-pdfs-viewer", in which case you'll need to contact them for support.

**Comment by Motard** [comment] 2017-11-18 09:42
The problem here is, I think, that the event to download is being binded to the download button multiple times. So when I open the viewer the first time, the event is binded to the button. I close and open again, and the event is binded again, and so on. So what I really need is a way to unbind the event when I close the viewer. And I am not yet been able to do that.

**Comment by timvandermeij** [comment] 2017-11-18 13:24
I do not see this happening in the code, so I think this is indeed a problem caused by the Angular library. Can you reproduce it without the Angular library, i.e., with the link provided above?

**Comment by timvandermeij** [comment] 2017-11-21 20:53
Closing since this issue is not actionable at the moment without more information on how to reproduce the issue.

**Closed by timvandermeij** 2017-11-21 20:53 UTC
Labels: 4-information-requested
