### ISSUE TITLE
Incorrect rendering of CMYK color

### ISSUE THREAD

**Issue by dmitri-lobach** [mozilla/pdf.js#14259] opened 2021-11-11 09:30 UTC
I've encountered a problem while viewing this document in Firefox or PDF.js demo viewer
http://docs.mygaru.com/presentations/Audit_log_white_paper.pdf

The problem seems related to using CMYK

Configuration:
- Web browser and its version: latest Firefox,  Chrome (when using PDF.js demo viewer)
- Operating system and its version: MacOS, Windows
- PDF.js version: 2.10+
- Is a browser extension: no

Steps to reproduce the problem:
1. Open linked document in Firefox or PDF.js demo viewer
2. Open linked document in Chrome PDFium or other PDF Viewer

What is the expected behaviour? 
Background color should be {r: 15, g: 183, b: 156}

What went wrong? 
Background color in PDF.js/FF rendered as {r: 104, g: 182, b: 156}

Chrome version is on the left, Firefox version is on the right

![Screenshot 2021-11-11 at 10 54 35](https://user-images.githubusercontent.com/12696338/141270658-d2ce4296-85dd-4acd-9fb0-21399683657e.png)

**Comment by Snuffleupagus** [comment] 2021-11-11 10:14
Duplicate of #2856

**Closed by Snuffleupagus** 2021-11-11 10:14 UTC
