### ISSUE TITLE
Attempted to assign to readonly property in iPad

### ISSUE THREAD

**Issue by quanth29** [mozilla/pdf.js#5814] opened 2015-03-09 03:56 UTC
I had an error when i open pdf.js in Safari in iPad ( iOS 8.1.2). Console log below : 
Attempted to assign to readonly property. Line code :   this.current.fillColor = color;
Block code : 
setFillRGBColor: function CanvasGraphics_setFillRGBColor(r, g, b) {
      var color = Util.makeCssRgb(r, g, b);
      this.ctx.fillStyle = color;
      this.current.fillColor = color;
      this.current.patternFill = false;
    },
And it line code :  this.current.charSpacing = spacing;
Block code :
setCharSpacing: function CanvasGraphics_setCharSpacing(spacing) {
      this.current.charSpacing = spacing;
    },

My pdf file in here https://www.copy.com/s/ttxyWC1szNr6x33d

**Comment by Snuffleupagus** [comment] 2015-03-09 11:48
Closing as duplicate of issue #5341.

**Closed by Snuffleupagus** 2015-03-09 11:48 UTC
