### ISSUE TITLE
ie10: console6000, warning: Unable to decode image: DataCloneError

### ISSUE THREAD

**Issue by Zen33** [mozilla/pdf.js#6957] opened 2016-02-05 02:45 UTC
Hi all, first of all, PDF.js is a awesome plugin that helped me solve batch of problems.
Recently, I have an issue is that when I render pdf in ie10, the console shows me a warning: Dependent image isn't ready yet, and some images in pdf are not rendered to canvas, other modern browsers (Chrome, Firefox) are both okay, any one can help me deal with this issue? thanks a lot.

**Comment by yurydelendik** [comment] 2016-02-05 15:05
Please provide steps to reproduce to issue and provide link to the PDF and/or your web site.

**Comment by timvandermeij** [comment] 2016-02-08 11:34
Closing until more information as requested above is provided. Please read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md for filing an issue too.

**Comment by jbiffis** [comment] 2016-02-22 20:15
Can I have this re-opened if I provide a pdf? 
http://www.stevenaverycase.org/wp-content/uploads/2016/01/Jury-Trial-Transcript-Day-3-2007Feb14.pdf

**Comment by timvandermeij** [comment] 2016-02-22 20:18
Sure, reopening.

**Comment by jbiffis** [comment] 2016-02-22 20:20
Thanks, let me know if you need anymore information.

**Comment by TammyHe19900522** [comment] 2016-02-23 09:32
waiting for the result.

**Comment by Zen33** [comment] 2016-03-15 06:58
Any solutions?

**Comment by brendandahl** [comment] 2016-03-15 18:42
This looks to be a regression with how post message transfer support works. IE10/11 doesn't support transferring typed arrays and it looks like we don't disable the transferring.

Temporary workaround is to set `PDFJS.postMessageTransfers = false;`

**Comment by jslatts** [comment] 2016-03-17 17:45
The temporary work around did not work for me on a IE10/Windows8 Microsoft test VM, but the fix in PR #7088 did.

**Closed** 2016-03-18 20:08 UTC
Labels: 2-image-quality, 3-regression, 4-ie10-specific

**Comment by Zen33** [comment] 2016-04-06 01:20
@brendandahl The temporary workaround did not work for me either.

**Comment by brendandahl** [comment] 2016-05-04 18:32
> @brendandahl The temporary workaround did not work for me either.

There were two issues at play. Use the real solution in #7088.
