### ISSUE TITLE
text appears incorrectly aligned

### ISSUE THREAD

**Issue by samth** [mozilla/pdf.js#15073] opened 2022-06-20 16:02 UTC
Attach (recommended) or Link to PDF file here: attached below, also at https://arxiv.org/pdf/2206.08896.pdf

Configuration:
- Web browser and its version: Firefox Nightly 103.0a1 (2022-05-30) (64-bit)
- Operating system and its version: Ubuntu 22.04 LTS
- PDF.js version: (integrated with firefox)
- Is a browser extension: no

Steps to reproduce the problem:
1. See page 2 for example
2.

What is the expected behavior? (add screenshot) text should be level and correctly aligned 
![image](https://user-images.githubusercontent.com/244723/174641092-273e14e8-3c38-4645-90d3-bd584ed866ce.png)

What went wrong? (add screenshot) see the word "language" for example, where the letters are not all aligned with the baseline
![Screenshot from 2022-06-20 11-57-31](https://user-images.githubusercontent.com/244723/174641165-dfdef5fd-f1bf-4b1c-8f3e-20d15c3347f7.png) 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

[2206.08896.pdf](https://github.com/mozilla/pdf.js/files/8942078/2206.08896.pdf)

**Comment by calixteman** [comment] 2022-06-20 16:06
Is it better if you set `gfx.canvas.accelerated` to `false` in `about:config` ?

**Comment by samth** [comment] 2022-06-20 16:07
@calixteman Yes, that seems to fix it.

**Comment by calixteman** [comment] 2022-06-20 16:09
It's a duplicate of [bug 1773936](https://bugzilla.mozilla.org/show_bug.cgi?id=1773936) and it should be fixed in a recent nightly.
You can find some links to the nightly releases containing the patch:
https://hg.mozilla.org/mozilla-central/rev/ebab824061a2

**Closed by calixteman** 2022-06-20 16:09 UTC
