### ISSUE TITLE
pdf.js displaying PDF after fetching complete file while range request enabled

### ISSUE THREAD

**Issue by aman-gupta-doc** [mozilla/pdf.js#17128] opened 2023-10-16 06:53 UTC
Attach (recommended) or Link to PDF file here:
1. PDF with issue : https://test-stream-pdf.s3.ap-southeast-1.amazonaws.com/01H9NB6T9F1BH7AJH87Y75S2A0+(2)+(1).pdf
a. downloading whole file before displaying.
3. PDF working fine : https://test-stream-pdf.s3.ap-southeast-1.amazonaws.com/demo-abc.pdf
a. displaying the PDF as chunk downloaded.

Configuration:
- Web browser and its version: Chrome latest
- Operating system and its version: Ubuntu 22.10
- PDF.js version: latest (master branch)

Steps to reproduce the problem:
1. Open demo using URL :   https://mozilla.github.io/pdf.js/web/viewer.html
2. To load your PDF, run the below lines of code in the browser's console.
```
PDFViewerApplication.open({
  url: <pdf-url> , 
  disableAutoFetch: true,
  disableRange: false,
  disableStream: true,
  verbosity: 5,
  rangeChunkSize: 1024**2,
})
```

**What is the expected behavior?** 

When I load PDF with the above configuration, I expected that the pages render as the chunk downloaded. But It was downloading all chunk first and then render pages.

**What went wrong?**

It was downloading the entire file before rendering any page.

**Finding**
When I dig deeper in pdf.js code, I saw while resolving `xref's` of PDF file [XRef class](https://github.com/mozilla/pdf.js/blob/master/src/core/xref.js#L35) in PDF.js fetching more chunks by throwing `MissingDataException` in some PDFs but works fine with rest of PDFs.

When I inspect the structure of PDF using https://pdfux.com/inspect-pdf/ I found out one difference in the structure of PDFs that in PDFs with issue `Root -> Pages ` contain all `xrefs` are on root level and no page level information or grouping there.
But in Working PDFs, `Root -> Pages ` is nested and grouped to page level.

Please help me with the issue and if Problems are with PDF how can I fix them.

Thanks

**Comment by Snuffleupagus** [comment] 2023-10-16 07:13
> [...] I found out one difference in the structure of PDFs that in PDFs with issue `Root -> Pages ` contain all `xrefs` are on root level and no page level information or grouping there.
> But in Working PDFs, `Root -> Pages ` is nested and grouped to page level.

It sounds like you've already pinpointed the issue yourself :-)

This is effectively a duplicate of issue #14570, please note https://github.com/mozilla/pdf.js/issues/14570#issuecomment-1041318623 which contains additional context and https://github.com/mozilla/pdf.js/issues/14570#issuecomment-1654181647 which contains a possible way to fix your PDF document.

**Closed by Snuffleupagus** 2023-10-16 07:13 UTC
