### ISSUE TITLE
Unable to decode image "img_p1_1": "TypeError: Found invalid object in transferList

### ISSUE THREAD

**Issue by yaotengyuan** [mozilla/pdf.js#16393] opened 2023-05-06 03:53 UTC
![微信图片_20230506115309](https://user-images.githubusercontent.com/22164554/236598334-10c7cd73-cdc8-4c57-8619-e7ecfef71edd.png)
              > > Attach (recommended) or Link to PDF file here:
> 
> This part of the ISSUE_TEMPLATE is _always required_ when opening an issue, since as-is this unfortunately isn't actionable/valid.
> 
> > I use the pdfjs in electron，is this matter with the problem？
> 
> Maybe; please note that we don't support Electron here.
I got it.But my pdf has only one picture,many other pdfs have the same problem,so it seems that there is something incorrect to my environment.Did you know what does it mean.
`Warning: Unable to decode image "img_p1_1": "TypeError: Found invalid object in transferList".`

_Originally posted by @yaotengyuan in https://github.com/mozilla/pdf.js/issues/16390#issuecomment-1536436389_

**Comment by Snuffleupagus** [comment] 2023-05-06 06:21
Duplicate of #16390

**Closed by Snuffleupagus** 2023-05-06 06:21 UTC
