### ISSUE TITLE
MAX1551 datasheet broken

### ISSUE THREAD

**Issue by alexander255** [mozilla/pdf.js#5965] opened 2015-04-25 16:59 UTC
This datasheet (.pdf) doesn't display correctly: The missing text seems to be there, but in the wrong color (white instead of black)...

URL to view the datasheet: http://datasheets.maximintegrated.com/en/ds/MAX1551-MAX1555.pdf
How it should look like: ![Screenshot of Atril](https://i.imgur.com/SyS8mFj.png)
pdf.js version: Unknown, bundled with Iceweasel/Firefox 38.0

**Comment by CodingFabian** [comment] 2015-04-25 18:29
Thanks for your report,
the pdf renders fine with the latest version of the viewer. can you double check for us if it works ok for you as well?
https://mozilla.github.io/pdf.js/web/viewer.html and upload the pdf with the button on the top right.

**Comment by alexander255** [comment] 2015-04-26 13:02
The PDF is displayed correctly in Chromium/Chrome 40, but not under Iceweasel/Firefox 38.0, so this is probably a Firefox-specific issue.
(I tested this on Debian 8.0 (Linux) with KDE 5, native X11 rendering and desktop compositing enabled - not that it should matter ;-) ... )
Firefox screenshot: ![Screenshot of broken PDF in latest version](http://i.imgur.com/tf7XgVJ.png)

The text layer is generated correctly under both Firefox and Chrome. Both browsers report `Warning: Knockout groups not supported.` twice while loading the PDF.

**Comment by Snuffleupagus** [comment] 2015-04-26 13:32
Possibly a duplicate of issue #4967.

**Comment by timvandermeij** [comment] 2015-06-09 22:42
Closing as duplicate of #6096 which is also about the same type of datasheet.

**Closed by timvandermeij** 2015-06-09 22:42 UTC
Labels: 4-os-linux, 4-triage-needed
