### ISSUE TITLE
When using PDF.js in node, need for worker seems overkill and many example uses of pdf.js fail.

### ISSUE THREAD

**Issue by Bondifrench** [mozilla/pdf.js#13969] opened 2021-09-03 15:06 UTC
Configuration:
- Using node, not in the browser
- Operating system and its version: Windows 8.1
- PDF.js version: 2.9.359
- Is a browser extension: No

Steps to reproduce the problem:
Example 1. 
Code from Folder example [getinfo.js](https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js)
- Works fine with version 2.8.335
- Breaks with version 2.9.359

Example 2.
Code from this video (https://www.youtube.com/watch?v=V_v5vqXbnCA&t=185s)
- As require("pdfjs-dist/es5/build/pdf") example uses version 2.7.570 and works with until that version
- Will work with require("pdfjs-dist/es5/build/pdf") when using version 2.8.335
- Will break with version 2.9.359

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/4905917/132023166-34ea2ebc-9e47-4fa4-9450-2d27bbb820e9.png)

What is the expected behavior? (add screenshot)
Expected behaviour is for [node example](https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js) to work straight after `npm install pdfjs-dist` and not need to install anything else as, to be honest, steps to add worker unclear and use of worker in Node probably unnecessary for most use cases.

**Comment by Snuffleupagus** [comment] 2021-09-03 15:25
> Code from this video (https://www.youtube.com/watch?v=V_v5vqXbnCA&t=185s)

Sorry, but that's not an official example an as such we cannot provide support for it here.

> As require("pdfjs-dist/es5/build/pdf") example uses version 2.7.570 and works with until that version
> Will work with require("pdfjs-dist/es5/build/pdf") when using version 2.8.335
> Will break with version 2.9.359

In the latest versions of the PDF.js library, you'll need to change the import path to `require("pdfjs-dist/legacy/build/pdf")` in Node.js environments; please refer to issue #12976 and PR #12978.

> Expected behaviour is for [node example](https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js) to work straight after `npm install pdfjs-dist` and not need to install anything else as,

The current version of that file already contains the the correct import path, so it should just work without the need to install anything else. Possibly what's causing the issue is a change in how npm handles `peerDependencies`, which will be worked-around in a future PDF.js release; please refer to PR #13833 for additional details.

> steps to add worker unclear and use of worker in Node probably unnecessary for most use cases.

Note that while Node.js environments doesn't support Web Workers, the `pdf.worker.js` file is still necessary since that's where all parsing actually happens (although the file *should* be loaded automatically in Node.js).

---

Closing for now since this *should* be working with the correct import paths (see above), and that we cannot provide additional assistance without more information; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Closed by Snuffleupagus** 2021-09-03 15:25 UTC
