### ISSUE TITLE
Wrong rendering of JPX images with transparency

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#18194] opened 2024-05-31 09:58 UTC
Attach (recommended) or Link to PDF file here:
[out2.pdf](https://github.com/user-attachments/files/15511847/out2.pdf)

File is from https://gitlab.freedesktop.org/poppler/poppler/-/issues/1486

Configuration:
- Web browser and its version:
FF 126.0.1
- Operating system and its version:
Windows  10.0.19045.4474
- PDF.js version:
latest https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. open the file

What is the expected behavior? (add screenshot)
![grafik](https://github.com/mozilla/pdf.js/assets/6665575/590d7784-2c30-430a-9daa-66abfca91a02)

What went wrong? (add screenshot)
![grafik](https://github.com/mozilla/pdf.js/assets/6665575/fa8c52e5-7fd5-4566-96fb-d140444eb94f)

**Comment by Snuffleupagus** [comment] 2024-05-31 10:03
Duplicate of #16782

**Closed by Snuffleupagus** 2024-05-31 10:03 UTC

**Comment by pubpub-zz** [comment] 2024-06-04 20:56
@Snuffleupagus 
the issue is still present with  PDF.js: 4.1.379 [017e49244]
![image](https://github.com/mozilla/pdf.js/assets/4083478/def72c08-c051-474f-bd43-33a607064124)

This issue should be reopened

**Comment by calixteman** [comment] 2024-06-04 21:16
> This issue should be reopened

The issue is fixed so we won't reopen it (you can open your pdf in https://mozilla.github.io/pdf.js/web/viewer.html).
The fix will be available in the next release.
