### ISSUE TITLE
PDF Render issue

### ISSUE THREAD

**Issue by ms3534** [mozilla/pdf.js#14832] opened 2022-04-25 08:21 UTC
[Issue1.pdf](https://github.com/mozilla/pdf.js/files/8552748/Issue1.pdf)
Configuration:
- Web browser and its version: Chrome Version 100.0.4896.127
- Operating system and its version: Windows 10
- PDF.js version: Latest from Master (https://github.com/mozilla/pdf.js)

Used the downloaded project, loaded the attached PDF(Screenshot1)
Rendering in Chrome: Screenshot2
Rendering in Firefx: Screenshot3
![Screenshot3](https://user-images.githubusercontent.com/104185732/165049295-3e5084c9-2f1d-4345-b8b5-83fa1f36ceb2.JPG)
![Screenshot1](https://user-images.githubusercontent.com/104185732/165049300-e6dfb555-8bcf-4cc8-bf06-a4a247e60551.JPG)
![Screenshot2](https://user-images.githubusercontent.com/104185732/165049303-a07e4489-0f24-4843-85e4-027ee6bff549.JPG)

PDFJs should load the PDF as rendered in Chrome/Firefox

**Comment by Snuffleupagus** [comment] 2022-04-25 08:25
Duplicate of #14821

---

> Web browser and its version: Chrome Version 100.0.4896.127

This suggests a bug in the *browser* itself, rather than the PDF.js library, since otherwise you'd expect it to be consistently broken everywhere (and e.g. Firefox works).

**Comment by ms3534** [comment] 2022-04-25 09:52
@Snuffleupagus: The issue is reproducible on the browsers like Google Chrome, Microsoft Edge, Opera,  Brave & Vivaldi. I agree that it's working on Firefox. But, I think that pdf.js should investigate why their component cannot show the attached file properly in other browsers.

**Comment by Snuffleupagus** [comment] 2022-04-25 09:59
> The issue is reproducible on the browsers like Google Chrome, Microsoft Edge, Opera, Brave & Vivaldi.

All of those browsers are Chromium-based, so it's probably not too surprising if they're all affected.

> But, I think that pdf.js should investigate why their component cannot show the attached file properly in other browsers.

First of all, please note that this library exists *primarily* to develop the Firefox *built-in* PDF Viewer.
Secondly, this issue suggests a bug (e.g. `canvas`-related) in the browser itself which can't really be fixed *here*.

**Closed by Snuffleupagus** 2022-04-25 09:59 UTC

**Comment by ms3534** [comment] 2022-04-26 03:57
@Snuffleupagus: Hi, I raised a request with Chromium, they are asking what is the issue with Canvas, Can you please share the issue,so that the same be shared with them.
Ticket ID: https://bugs.chromium.org/p/chromium/issues/detail?id=1319362

**Comment by toddcollinson** [comment] 2022-04-27 09:08
@ms3534 I've checked your PDF from the chromium issue using a PDF checker - it suggests there is corruption in the pdf file based on this tool: https://www.datalogics.com/products/pdf-tools/pdf-checker/

The file also cannot be opened by Adobe PDF reader as it advises the file is damaged and cannot be repaired.

**Comment by ms3534** [comment] 2022-04-27 10:28
[Issue1_new.pdf](https://github.com/mozilla/pdf.js/files/8571180/Issue1_new.pdf)
@toddcollinson : The PDF got corrupted while removing the meta data information using Notepad++, uploaded new copy of the same pdf. Can you please check it and respond to the issue
