### ISSUE TITLE
how to disable right click on pdf in iframes. 

### ISSUE THREAD

**Issue by keerti1508** [mozilla/pdf.js#13621] opened 2021-06-23 18:23 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-06-23 18:26
Duplicate of #13620

---

Please don't open a new and equally incomplete issue; this is missing the necessary information mentioned in https://github.com/mozilla/pdf.js/issues/13620#issuecomment-867051562.

**Closed by Snuffleupagus** 2021-06-23 18:26 UTC
