### ISSUE TITLE
 Fails to render colors from xcolor package in LaTeX PdfTeX document

### ISSUE THREAD

**Issue by Merlin04** [mozilla/pdf.js#15417] opened 2022-09-08 20:55 UTC
Attach (recommended) or Link to PDF file here:

[color_test.pdf](https://github.com/mozilla/pdf.js/files/9530499/color_test.pdf)
https://www.overleaf.com/read/hmnyprntcdbb

This is a simple LaTeX document that uses the `xcolor` package to make some text in the document blue (using the `\textcolor{blue}{text goes here}` command. 

Configuration:
- Web browser and its version: Firefox 103.0.1
- Operating system and its version: openSUSE Tumbleweed
- PDF.js version: 2.15.129
- Is a browser extension: I think so?

Steps to reproduce the problem:
1. Open the PDF in pdf.js

What is the expected behavior? (add screenshot)

The text should be blue - this screenshot is from Gnome's Document Viewer application, but it also renders correctly in Overleaf's PDF viewer.
![image](https://user-images.githubusercontent.com/11800751/189223418-1fc4a2cc-1d5c-45cc-b290-e2fa8d6ce353.png)

What went wrong? (add screenshot)

In pdf.js the text is black, not blue (looking it now it also appears the background is light gray instead of white but that's not the most important issue)
![image](https://user-images.githubusercontent.com/11800751/189223554-43fee2d4-6c90-4843-b22b-e5edad889b44.png)

**Comment by Snuffleupagus** [comment] 2022-09-09 07:49
WFM, using PDF.js `3.0.7` in Firefox Nightly 106 on Windows.

---

Possibly a duplicate of [bug 1778068 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1778068) and [issue 15141](https://github.com/mozilla/pdf.js/issues/15141), which was fixed in Firefox 104.

**Comment by marco-c** [comment] 2022-09-09 09:32
I can't reproduce this problem in any Firefox version. @Snuffleupagus are you able to reproduce in 103?

**Comment by Snuffleupagus** [comment] 2022-09-09 09:35
> @Snuffleupagus are you able to reproduce in 103?

Nope, but I also don't use any of the browser settings that'd potentially affect this; see e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1778068#c0

**Comment by marco-c** [comment] 2022-09-09 09:36
@Merlin04 could you give us more details on your settings? Can you test again in Nightly and tell us if you can still reproduce there?

**Comment by Sterzz** [comment] 2022-09-12 13:42
I can't reproduce this on openSUSE Tumbleweed with Firefox Nightly 106.0a1.
![444](https://user-images.githubusercontent.com/112873644/189669608-02c09494-ac74-4fd5-ae27-97abd8ceb39f.png)

**Comment by calixteman** [comment] 2022-09-12 13:51
As Jonas said, it's a dup of #15141 and [bug 1778068](https://bugzilla.mozilla.org/show_bug.cgi?id=1778068).

**Closed by calixteman** 2022-09-12 13:51 UTC
Labels: core, information-requested

**Comment by Merlin04** [comment] 2022-09-12 17:51
Sorry for lack of response - I've confirmed that the workaround mentioned in #15141 (https://github.com/mozilla/pdf.js/issues/15141#issuecomment-1178646456) works for me. I've tested in Firefox Nightly 106.0a1 and the issue appears to be fixed.
