### ISSUE TITLE
PDF Doesn't Render - White Screen + Error Message

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#15181] opened 2022-07-19 05:23 UTC
Attach (recommended) or Link to PDF file here: (File too big to upload)
https://drive.google.com/file/d/10lF5KnrrTp3_zbw3HEuJXRROXfE3rHK9/view?usp=sharing

Configuration:
- Web browser and its version:  Chrome 103.0.5060.114 and Firefox 102.0.1 (64-bit
- Operating system and its version: Windows 10
- PDF.js version: (PDF.js: 2.15.268)
- Is a browser extension:

Steps to reproduce the problem:
1. Open file in PDFJS Viewer - Displays as blank white page
2. Open file directly in Chrome using chrome built in viewer - Displays correctly

What is the expected behavior? (add screenshot)
Should display correctly

What went wrong? (add screenshot)
PDFJS Viewer just shows white screen
In Firefox using PDFJS Viewer I get an error message

PDF.js v2.15.268 (build: 5bfba89b0)
Message: 
Stack: putBinaryImageData@https://mozilla.github.io/pdf.js/build/pdf.js:6670:11
paintInlineImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:8577:25
paintImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:8528:10
executeOperatorList@https://mozilla.github.io/pdf.js/build/pdf.js:7061:20
_next@https://mozilla.github.io/pdf.js/build/pdf.js:3501:37
__webpack_modules__</_scheduleNext/<@https://mozilla.github.io/pdf.js/build/pdf.js:3489:14

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-07-19 08:00
Duplicate of #12307

**Closed by Snuffleupagus** 2022-07-19 08:00 UTC
