### ISSUE TITLE
Print quality when printing from firefox

### ISSUE THREAD

**Issue by Hawex** [mozilla/pdf.js#9423] opened 2018-01-31 09:02 UTC
Hi, I've got a problem when printing files directly from firefox, quality of print is very poor . Is there any way to improve it without editing pdf.js (for ex. in firefox options or by page css)? 

Attach (recommended) or Link to PDF file here:
 https://mozilla.github.io/pdf.js/web/viewer.html
Configuration:
- Web browser and its version: Firefox 58.0.1
- Operating system and its version: Windows 10 Home
- PDF.js version: dont know
- Is a browser extension: no

Steps to reproduce the problem:
1. Open  https://mozilla.github.io/pdf.js/web/viewer.html
2. Download default file
3. Print default file from firefox

<img src="https://image.ibb.co/cdcTim/comparsion.png" />

**Comment by timvandermeij** [comment] 2021-03-14 15:15
Closing since this is a duplicate of #2750.

**Closed by timvandermeij** 2021-03-14 15:15 UTC
Labels: 4-printing
