### ISSUE TITLE
Poor print quality

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#7094] opened 2016-03-21 05:41 UTC
I'm getting poor print quality from pdf.js compared to Google's plugin.
This is on Win 10 64b, Chrome Version 51.0.2686.0 canary (64-bit), PDF Viewer 1.4.55.
The source file is [here](http://kibinimatika.co.il/Upload/%d7%93%d7%a4%d7%99%20%d7%a0%d7%95%d7%a1%d7%97%d7%90%d7%95%d7%aa%20%d7%91%d7%9e%d7%aa%d7%9e%d7%98%d7%99%d7%a7%d7%94/nushaon_3%20_yehidot_%20k_2011.pdf).
I'm attaching the files generated by pdf.js and Google plugin with "Save pdf" print destination. The real paper print is the same.

[print_pdf.js.pdf](https://github.com/mozilla/pdf.js/files/181717/print_pdf.js.pdf)
[print_google.pdf](https://github.com/mozilla/pdf.js/files/181718/print_google.pdf)

**Comment by roxinetaylor** [comment] 2016-03-23 18:39
I just worked with a customer that is experiencing the same issue. I did a remote support session and seen the lack of quality/ difference.  

Poor print quality from pdf.js compared to Google's plugin.
This is on Win 7 Pro 32-bit Chrome version 49.0.2623.87 m
, PDF Viewer 1.4.55.
The source file is here.
[Form_normal_2.pdf](https://github.com/mozilla/pdf.js/files/186634/Form_normal_2.pdf)
[Form_SnapAndRead_2.pdf](https://github.com/mozilla/pdf.js/files/186635/Form_SnapAndRead_2.pdf)

I'm attaching the files generated by pdf.js and Google plugin with "Save pdf" print destination. The real paper print is the same.

**Comment by RobsonMi** [comment] 2016-04-12 20:41
I can confirm the same. What I was able to discover however is that in my case it only happens to files altered with FPDI & FPDF on server. They render perfect in Chrome or Adobe Reader but in pdf.js they become blurry and low quality on high zoom levels. Originals that were not edited with FPDI do not present the same behavior.

I cannot provide screenshot's as the files are proprietary. Would love a solution. Any ideas?

**Comment by c-e-p-x-u-o** [comment] 2018-04-12 22:57
Is it a dup for #2750?

**Comment by timvandermeij** [comment] 2021-03-14 14:57
Closing since this is a duplicate of #7094.

**Closed by timvandermeij** 2021-03-14 14:57 UTC
Labels: 4-printing
