### ISSUE TITLE
pdf color issue

### ISSUE THREAD

**Issue by justalways** [mozilla/pdf.js#14593] opened 2022-02-21 09:56 UTC
Attach (recommended) or Link to PDF file here:
https://github.com/mozilla/pdf.js/files/8105664/MTB_8ft_Tower_2.pdf
Configuration:
- Web browser and its version: chrome Version 96.0.4664.110 (Official Build) (64-bit)
- Operating system and its version: windows 10
- PDF.js version: 2.13.174
- Is a browser extension: no

Steps to reproduce the problem:
1. open with Adobe Acrobat Reader , top area color is #23408F
![image](https://user-images.githubusercontent.com/9329575/154929615-82229c70-c791-4a1a-95e9-8f8759124743.png)

![image](https://user-images.githubusercontent.com/9329575/154929229-60869812-dc8f-4069-9e49-1fed14e05fe2.png)

2. top area color is #0E3692,open with https://mozilla.github.io/pdf.js/web/viewer.html
    pdf viewer version : 
PDF 5b330a4f3fa04deba00e29cc518b4005 [1.3 Adobe PDF Library 15.0 / Adobe InDesign CC 13.1 (Macintosh)] (PDF.js: 2.13.174)
![image](https://user-images.githubusercontent.com/9329575/154928734-ba6c5993-53e8-4b49-a640-ea0c13f1ab87.png)

The color is bright about top area , #23408F VS #0E3692, help please again!
https://github.com/mozilla/pdf.js/issues/14591 has been closed, so i open a new one.

**Comment by Snuffleupagus** [comment] 2022-02-21 09:59
Duplicate of #14591, please note https://github.com/mozilla/pdf.js/issues/14591#issuecomment-1046671998.

**Closed by Snuffleupagus** 2022-02-21 09:59 UTC
