### ISSUE TITLE
The image on the PDF has a Horizontal Line displayed on pdf.js, which doesn't exist if it's opened in Adobe Acrobat

### ISSUE THREAD

**Issue by jndami-112** [mozilla/pdf.js#17745] opened 2024-02-28 14:34 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome/Safari/Firefox latest version
- Operating system and its version: Windows/Mac OS latest version
- PDF.js version: 4.0.379
- Is a browser extension: No

Steps to reproduce the problem:
Use pdf.js to open the pdf file attached.

What is the expected behavior? There should not be a white horizontal line on the image of the first page.

What went wrong? There is a white horizontal line on the image of the first page. See the screenshot attached.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
<img width="1537" alt="PDFJS" src="https://github.com/mozilla/pdf.js/assets/161580665/212bddeb-9f06-4e7b-8522-e262ee76205c">
<img width="1425" alt="PDFJS01" src="https://github.com/mozilla/pdf.js/assets/161580665/ec57e7f8-df6c-4328-a4f8-47603aadacd8">
[Neuheiten_2024_1.Halbjahr_703.20240201082004302 (1).pdf](https://github.com/mozilla/pdf.js/files/14435436/Neuheiten_2024_1.Halbjahr_703.20240201082004302.1.pdf)

**Comment by Snuffleupagus** [comment] 2024-02-28 14:41
Duplicate of #3351

**Closed by Snuffleupagus** 2024-02-28 14:41 UTC
