### ISSUE TITLE
Selection Annotation is hard

### ISSUE THREAD

**Issue by sharanmunyal** [mozilla/pdf.js#7275] opened 2016-04-29 21:20 UTC
Link to PDF file (or attach file here):
[Mario Mystery.docx (2).pdf](https://github.com/mozilla/pdf.js/files/243245/Mario.Mystery.docx.2.pdf)

Configuration:
- Web browser and its version: Chrome 50.x
- Operating system and its version: Mac
- PDF.js version: 1.5.222
- Is an extension: No

Steps to reproduce the problem:
1. Select hyperlinks in the document attached

What is the expected behavior? (add screenshot)
It should just select the text

What went wrong? (add screenshot)
It selects the whole page

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2016-04-30 10:02
Duplicate of #7013?

**Comment by timvandermeij** [comment] 2017-11-19 14:30
Closing since this is a duplicate of #7013.

**Closed by timvandermeij** 2017-11-19 14:30 UTC
Labels: 1-ux, 4-annotations
