### ISSUE TITLE
Using `PDFViewerApplication.open` is indeed the correct way to do this and should allow you open a PDF file using raw binary data (use typed arrays). Closing as answered.

### ISSUE THREAD

**Issue by xtsudhan** [mozilla/pdf.js#10923] opened 2019-06-21 12:39 UTC
Using `PDFViewerApplication.open` is indeed the correct way to do this and should allow you open a PDF file using raw binary data (use typed arrays). Closing as answered.

_Originally posted by @timvandermeij in https://github.com/mozilla/pdf.js/issues/9487#issuecomment-372036644_

**Comment by xtsudhan** [comment] 2019-06-21 12:39
But PDFViewerApplication is undefined it is saying .

**Comment by Snuffleupagus** [comment] 2019-06-21 13:02
Duplicate of #10922; please refrain from knowingly open duplicate issues!

**Comment by xtsudhan** [comment] 2019-06-21 14:39
to use PDFViewerApplication.Open which js and version we need to refer as source in our javascript?

Currently I am using PDF.js 2.2.2

**Closed** 2019-06-21 20:47 UTC

**Comment by Even-Lau** [comment] 2020-09-29 00:47
I came across the same problem. Is there any solution? @xtsudhan
