### ISSUE TITLE
Release version 2.2.199

### ISSUE THREAD

**Issue by uxmaster** [mozilla/pdf.js#10887] opened 2019-06-05 17:15 UTC
PDF.js version 2.2.199 used in the [demo](https://mozilla.github.io/pdf.js/web/viewer.html) should be available in this repository, but there's only version 2.1.266 here.

**Comment by Snuffleupagus** [comment] 2019-06-05 17:34
The viewer at https://mozilla.github.io/pdf.js/web/viewer.html always contains the *latest development* version of the PDF.js library, hence that exact version is not expected to to be found at https://github.com/mozilla/pdf.js/releases since those are the official releases. 

Please refer also to the FAQ, in particular https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#version for additional information.

This is thus, effectively, a duplicate of issue #10819.

**Comment by uxmaster** [comment] 2019-06-05 18:16
Thanks for the fast response. 

Sure, 2.2.199 is the development version, but stable Firefox 67.0 is using PDF.js 2.2.71, which has not been tagged or released here or at [pdfjs-dist](https://www.npmjs.com/package/pdfjs-dist). It seems against the FAQ answer (unless Firefox grabbed the code without you pushing it out).

**Comment by timvandermeij** [comment] 2019-06-05 21:22
Yes, the release schedule has been changed a bit. I'll update the FAQ and close this as a duplicate of the other issue mentioned above that tracks the next release.

**Closed by timvandermeij** 2019-06-05 21:22 UTC
