### ISSUE TITLE
Printing fails part-way through

### ISSUE THREAD

**Issue by GKFX** [mozilla/pdf.js#6381] opened 2015-08-23 09:57 UTC
When I attempt to print [this PDF document](https://drive.google.com/file/d/0ByFKXGLNiyvRM1B1anliSnQxOVc5eTloa3lrUHpzWWdCQ0x3/view?usp=sharing), I get the error message
![Print Preview Error: An error occurred while printing.](https://cloud.githubusercontent.com/assets/5357642/9427728/60e1dbc8-4984-11e5-80dd-c3439aa5f588.png)
As a result, only part of the document prints. I'm attempting to print 2 pages per sheet, having unchecked "Ignore scaling and shrink to fit page width", set "shrink page if necessary to fit borders" to expand, set color to grayscale, and resolution to 360 × 240 DPI. I also see the "may not be displayed properly" message when I open it. Evince can print it without trouble.

I'm on Debian Stretch (testing), using Firefox (stable) 39.0.3.

**Comment by Rob--W** [comment] 2015-08-26 22:25
Can't reproduce with the PDF, 2 pages per sheet, ignore scaling, shrink to fit, grayscale, US letter size, DPI auto, Firefox 40.0.2.

Do you also experience the same issues with other PDFs and/or other print settings and/or printer?

> Evince can print it without trouble.

With exactly the same settings?

Did you see any errors in the global JavaScript console and/or Firefox' stdout/stderr?

**Comment by timvandermeij** [comment] 2015-09-04 15:47
Closing as incomplete for now. Please provide the details requested above to reopen.

**Closed by timvandermeij** 2015-09-04 15:47 UTC
Labels: 4-information-requested, 4-os-linux, 4-printing

**Comment by GKFX** [comment] 2015-09-05 17:53
Sorry for the delay; I've tested it in Nightly 43.0a1 (2015-08-30), and it doesn't happen any more. This makes me suspect that you've fixed it. The PDF was failing persistently to print in FF 39, so I don't think this is a case of an intermittent fault just not showing up this time.
I had seen it in other PDF documents (many from the a similar source), and if I do see it again on Nightly, I will get back to you.
