### ISSUE TITLE
SVG: Text cannot be displayed in the browser console.

### ISSUE THREAD

**Issue by cuiyc2000** [mozilla/pdf.js#15277] opened 2022-08-05 03:15 UTC
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf
Configuration:
- Web browser and its version:  Chrome  103.0.5060.134 (arm64)
- Operating system and its version: MacBook Pro（13，M2，2022）
- PDF.js version: 2.15.349
- Is a browser extension: No

Steps to reproduce the problem:
1.  I render the pdf using SVG backend as usual
``` js
...
        pdf.getPage(pageNumber).then(function (page) {
          var scale = 1.5;

          // Get viewport (dimensions)
          var viewport = page.getViewport({scale});

          // Get div#the-svg
          var container = document.getElementById("pdfContainer");

          // Set dimensions
          container.style.width = viewport.width + 'px';
          container.style.height = viewport.height + 'px';

          // SVG rendering by PDF.js
          page.getOperatorList()
              .then(function (opList) {
                var svgGfx = new PDFJS.SVGGraphics(page.commonObjs, page.objs);
                return svgGfx.getSVG(opList, viewport);
              })
              .then(function (svg) {
                container.appendChild(svg);
              });
         })
...
```

What went wrong? (add screenshot)

I wanted to copy the text from the rendered pdf but failed. The text looks normal only in an outward appearence. When I check the element in the console, it shows like this: 

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/68642492/182992504-59fe1b0e-f8b9-42bb-8e87-85eacb3d1f66.png">

It leads to unreadable code when I copy from the pdf.

**Comment by Snuffleupagus** [comment] 2022-08-05 07:36
Duplicate of #10205

**Closed by Snuffleupagus** 2022-08-05 07:36 UTC
