### ISSUE TITLE
pdf.js build is failing with "SyntaxError: Unexpected token (354:0)"

### ISSUE THREAD

**Issue by jeffdare** [mozilla/pdf.js#15647] opened 2022-10-30 14:41 UTC
Trying to dev build on local system for v2.16 and I get the below error

Steps to reproduce the problem:
1. Git clone the repository
2. run npm i
3. gulp generic

What is the expected behavior? (add screenshot)
Build should be successful

What went wrong? (add screenshot)
I get the below error

```
webpack 5.74.0 compiled successfully
[19:50:15] 'createGeneric' errored after 9.45 s
[19:50:15] Error in plugin "webpack-stream"
Message:
    Module build failed (from ./external/webpack/pdfjsdev-loader.js):
SyntaxError: Unexpected token (354:0)
    at Parser.pp$4.raise (/Users/jeffdare/jeff/Daeja/localpdf/manual/pdf.js.latest/node_modules/acorn/dist/acorn.js:3459:15)
    at Parser.pp$9.unexpected (/Users/jeffdare/jeff/Daeja/localpdf/manual/pdf.js.latest/node_modules/acorn/dist/acorn.js:760:10)
    at Parser.pp$5.parseExprAtom (/Users/jeffdare/jeff/Daeja/localpdf/manual/pdf.js.latest/node_modules/acorn/dist/acorn.js:2843:12)
    at Parser.pp$5.parseExprSubscripts (/Users/jeffdare/jeff/Daeja/localpdf/manual/pdf.js.latest/node_modules/acorn/dist/acorn.js:2635:21)
    at Parser.pp$5.parseMaybeUnary (/Users/jeffdare/jeff/Daeja/localpdf/manual/pdf.js.latest/node_modules/acorn/dist/acorn.js:2601:19)
    at Parser.pp$5.parseExprOps (/Users/jeffdare/jeff/Daeja/localpdf/manual/pdf.js.latest/node_modules/acorn/dist/acorn.js:2528:21)
    at Parser.pp$5.parseMaybeConditional (/Users/jeffdare/jeff/Daeja/localpdf/manual/pdf.js.latest/node_modules/acorn/dist/acorn.js:2511:21)
    at Parser.pp$5.parseMaybeAssign (/Users/jeffdare/jeff/Daeja/localpdf/manual/pdf.js.latest/node_modules/acorn/dist/acorn.js:2478:21)
    at Parser.pp$5.parseExpression (/Users/jeffdare/jeff/Daeja/localpdf/manual/pdf.js.latest/node_modules/acorn/dist/acorn.js:2441:21)
    at Parser.pp$8.parseStatement (/Users/jeffdare/jeff/Daeja/localpdf/manual/pdf.js.latest/node_modules/acorn/dist/acorn.js:950:47)
Details:
    domainEmitter: [object Object]
    domainThrown: false

[19:50:15] 'generic' errored after 11 s
```

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/7148351/198884703-4b9cada4-6d6e-4714-9d1a-9b76b50305d7.png">

**Comment by Snuffleupagus** [comment] 2022-10-30 14:53
> Trying to dev build on local system for v2.16 and I get the below error

WFM, against the `master` branch. Please keep in mind that the version you're using is no longer supported.

> Steps to reproduce the problem:
>     1. Git clone the repository
>     2. run npm i
>     3. gulp generic

It's not clear *exactly how* you cloned the repository, since looking at https://github.com/mozilla/pdf.js#getting-the-code there's at least one step missing (e.g. related to `gulp` installation). Possibly you need to run `npm install -f` instead, as outlined in issue #15429.

Closing as WORKSFORME, given that there's not really enough information provided to reproduce your set-up.

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Closed by Snuffleupagus** 2022-10-30 14:53 UTC
Labels: information-requested
