### ISSUE TITLE
PDF renders as blank in Chrome extension viewer

### ISSUE THREAD

**Issue by diracdeltas** [mozilla/pdf.js#8395] opened 2017-05-09 19:22 UTC
Link to PDF file (or attach file here):
https://npgallery.nps.gov/pdfhost/docs/NHLS/Text/70000736.pdf

Configuration:
- Web browser and its version: Chrome 58
- Operating system and its version: Mac
- PDF.js version: 1.6.293 version of the chrome extension
- Is an extension: Yes

Steps to reproduce the problem:
1. Load the PDF
2. It's blank

What is the expected behavior? (add screenshot)
Should not be blank; it displays properly in chrome's built-in PDF viewer

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-05-09 19:28
Closing as duplicate of issue #2073.

**Closed by Snuffleupagus** 2017-05-09 19:28 UTC
