### ISSUE TITLE
Combine text items is off

### ISSUE THREAD

**Issue by luiscastro193** [mozilla/pdf.js#8963] opened 2017-09-28 12:17 UTC
Link to PDF file: [Hyphenator.pdf](https://github.com/mozilla/pdf.js/files/1340729/Hyphenator.pdf)

Configuration:
- Web browser and its version: Firefox 55.0.2 and Chrome 61.0.3163.100.
- Operating system and its version: Linux Mint 18.1
- PDF.js version: 1.9.602
- Is an extension: No

Steps to reproduce the problem:
1. Try to extract the text from the PDF. For example:

```html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>PDF.js test</title>
		<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>
	</head>

	<body>
		<input type="file" onchange="readText(this)" autofocus>
		<pre id="text"></pre>
		<script>
			var pre = document.getElementById("text");
		
			function readText(filePath) {
				var reader = new FileReader();
				var fileName = filePath.files[0].name;
				
				reader.onload = function(event) {
					PDFJS.getDocument(new Uint8Array(event.target.result)).then(function(pdf) {
						var maxPages = pdf.pdfInfo.numPages;
						var countPromises = [];
						
						for (var i = 1; i <= maxPages; i++) {
							countPromises.push(pdf.getPage(i).then(function(page){
								return page.getTextContent().then(function(text){
									return text.items.map(function(item) { return item.str; }).join('\n');
								});
							}));
						}
					
						Promise.all(countPromises).then(function(texts) {
							pre.innerHTML = texts.join('\n');
						});
					});
				};
			
				reader.readAsArrayBuffer(filePath.files[0]);
			}
		</script>
	</body>
</html>
```

2. Compare the result with the original PDF.

What is the expected behavior?

![original pdf](https://user-images.githubusercontent.com/7590880/30965808-010ed3c4-a457-11e7-952b-d7694b79e167.png)

A plain text version of the original PDF.

What went wrong?

![rendered pdf](https://user-images.githubusercontent.com/7590880/30965909-52f9a25e-a457-11e7-9685-e7318c907d0f.png)

Text from the same line is not combined properly.

**Comment by yurydelendik** [comment] 2017-09-28 12:46
Closing as duplicate of #2140

**Closed by yurydelendik** 2017-09-28 12:46 UTC

**Comment by luiscastro193** [comment] 2017-09-28 14:03
I am trying to use a regex with the text of a PDF. Is it posible?

**Comment by yurydelendik** [comment] 2017-09-28 14:24
> I am trying to use a regex with the text of a PDF. Is it posible?

It's possible. You need to a) preprocess text items based on their positions, or b) build regex without relying on the line breaks.

**Comment by luiscastro193** [comment] 2017-09-28 18:59
You are right, the y-coordinate is the same for items on the same line. But I still can´t deal with the random spaces it adds splitting a words in halves.

Well, I guess I could disable combine text items and concatenate each symbol but... shouldn´t it be just as easy to fix directly in the combine text items implementation?

**Comment by luiscastro193** [comment] 2017-09-28 19:04
Actually the random spaces are not solved by disableCombineTextItems. :(

**Comment by luiscastro193** [comment] 2017-09-28 19:37
Workaround:

```html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>PDF.js test</title>
		<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>
	</head>

	<body>
		<input type="file" onchange="readText(this)" autofocus>
		<pre id="text"></pre>
		<script>
			var pre = document.getElementById("text");
		
			function readText(filePath) {
				var reader = new FileReader();
				var fileName = filePath.files[0].name;
				
				reader.onload = function(event) {
					PDFJS.getDocument(new Uint8Array(event.target.result)).then(function(pdf) {
						var maxPages = pdf.pdfInfo.numPages;
						var countPromises = [];
						
						for (var i = 1; i <= maxPages; i++) {
							countPromises.push(pdf.getPage(i).then(function(page){
								return page.getTextContent().then(function(text){
									"use strict";
									let lastY, str = '';
								
									for (let item of text.items) {
										if (lastY == item.transform[5])
											str += item.str;
										else {
											str += '\n' + item.str;
											lastY = item.transform[5];
										}
									}
									
									return str;
								});
							}));
						}
					
						Promise.all(countPromises).then(function(texts) {
							pre.innerHTML = texts.join('\n');
						});
					});
				};
			
				reader.readAsArrayBuffer(filePath.files[0]);
			}
		</script>
	</body>
</html>
```

**Comment by luiscastro193** [comment] 2018-12-01 11:17
Even though the "duplicate" is fixed, this issue still isn't. Since the API has changed in the last year, this is now the code to test it:

```html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>PDF.js test</title>
		<script src="https://unpkg.com/pdfjs-dist/build/pdf.min.js"></script>
	</head>

	<body>
		<input type="file" onchange="readText(this)" autofocus>
		<pre id="text"></pre>
		<script>
			var pre = document.getElementById("text");
		
			function readText(filePath) {
				var reader = new FileReader();
				var fileName = filePath.files[0].name;
				
				reader.onload = function(event) {
					pdfjsLib.getDocument(event.target.result).then(function(pdf) {
						var maxPages = pdf.numPages;
						var countPromises = [];
						
						for (var i = 1; i <= maxPages; i++) {
							countPromises.push(pdf.getPage(i).then(function(page){
								return page.getTextContent().then(function(text){
									return text.items.map(function(item) { return item.str; }).join('\n');
								});
							}));
						}
					
						Promise.all(countPromises).then(function(texts) {
							pre.innerHTML = texts.join('\n');
						});
					});
				};
			
				reader.readAsArrayBuffer(filePath.files[0]);
			}
		</script>
	</body>
</html>
```

**Comment by luiscastro193** [comment] 2021-01-11 17:13
After all this time, the issue is still not fixed. This is the updated code to test it:

```html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>PDF.js test</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script src="https://unpkg.com/pdfjs-dist/build/pdf.min.js"></script>
	</head>
	<body>
		<input type="file" onchange="readText(this)" autofocus>
		<pre id="text"></pre>
		<script>
			"use strict";
			let pre = document.getElementById("text");
		
			function readText(filePath) {
				let reader = new FileReader();
				
				reader.onload = async function(event) {
					let pdf = await pdfjsLib.getDocument(event.target.result).promise;
					let pages = Array.from({length: pdf.numPages}, (_, i) => i + 1)
						.map(index => pdf.getPage(index).then(page => page.getTextContent())
							.then(text => text.items.map(item => item.str).join('\n')));
					pre.innerHTML = (await Promise.all(pages)).join('\n');
				};
			
				reader.readAsArrayBuffer(filePath.files[0]);
			}
		</script>
	</body>
</html>
```
