### ISSUE TITLE
pdf rendering error

### ISSUE THREAD

**Issue by supun19** [mozilla/pdf.js#10134] opened 2018-10-05 03:09 UTC
I got this error when render pdf in  nodejs.

Warning: TT: undefined function: 32
(node:10531) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
    at FontLoader.fontLoaderInsertRule [as insertRule] (/Users/supun/projects/meetrix/draw/node_modules/pdfjs-dist/build/pdf.js:9899:42)
    at FontLoader.fontLoaderBind [as bind] (/Users/supun/projects/meetrix/draw/node_modules/pdfjs-dist/build/pdf.js:9957:16)
    at WorkerTransport.transportObj (/Users/supun/projects/meetrix/draw/node_modules/pdfjs-dist/build/pdf.js:9422:29)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/Users/supun/projects/meetrix/draw/node_modules/pdfjs-dist/build/pdf.js:1063:19)
    at LoopbackPort.<anonymous> (/Users/supun/projects/meetrix/draw/node_modules/pdfjs-dist/build/pdf.js:8944:20)
    at Array.forEach (<anonymous>)
    at /Users/supun/projects/meetrix/draw/node_modules/pdfjs-dist/build/pdf.js:8943:27
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

This is my code snip

`pdfjsLib.getDocument(url).then(function (pdfDocument) {
        console.log('# number of pages.',pdfDocument.pdfInfo.numPages);

        var numerOfPage= parseInt(pdfDocument.pdfInfo.numPages);
        var currentPage = 1;
        // Get the first page.
        var lastPromise;
        lastPromise = pdfDocument.getMetadata().then(function (data) {
            console.log('# Metadata Is Loaded');
            console.log('## Info');
            console.log(JSON.stringify(data.info, null, 2));
            console.log();
            if (data.metadata) {
                console.log('## Metadata');
                console.log(JSON.stringify(data.metadata.getAll(), null, 2));
                console.log();
            }
        });

        var loadPage = function (pageNumber) {
            pdfDocument.getPage(pageNumber).then(function (page) {
                // Render the page on a Node canvas with 100% scale.
                var viewport = page.getViewport(1.0);
                var canvasFactory = new NodeCanvasFactory();
                var canvasAndContext = canvasFactory.create(viewport.width, viewport.height);
                var renderContext = {
                    canvasContext: canvasAndContext.context,
                    viewport: viewport,
                    canvasFactory: canvasFactory
                };

                page.render(renderContext).then(function () {
                    

                });

            });
        }
        lastPromise.then(loadPage.bind(null, 1));

        return lastPromise

    }).catch(function(reason) {
        console.log(reason);
    });`

node version v8.11.3
pdfjs-dist versio0n 2.0.489

if pdf has only text it does not give an error but it has images. it will give above error.can some help to solve this

if url="http://www.africau.edu/images/default/sample.pdf" working
if url="http://www.pdf995.com/samples/pdf.pdf" not working

**Comment by Snuffleupagus** [comment] 2018-10-05 07:59
This looks like a duplicate of issue #9533.

For future reference: When filing an issue you should always provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, and as mentioned in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md you should provide a runnable example since only code snippets aren't that useful.

**Comment by supun19** [comment] 2018-10-05 08:57
Attach (recommended) or Link to PDF file here:

working pdf [http://www.africau.edu/images/default/sample.pdf](url)
not working pdf [http://www.pdf995.com/samples/pdf.pdf](url)

Configuration:

- not use web browser nodejs backend
- osx
- pdfjs-dist version 2.0.489
- no
- node verison  v8.11.3

Steps to reproduce the problem:  

- clone the reposatory [https://github.com/supun19/PDFToJpeg.git](url)

- simple run the node server

- I hardcoded 2 sample url

- you can see the error in terminal

What is the expected behavior?
 should print the base64 string of jpeg image

What went wrong?

this is the error

  (node:15761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15761) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
    at FontLoader.fontLoaderInsertRule [as insertRule] (/Users/supun/projects/meetrix/PDFToJpeg/node_modules/pdfjs-dist/build/pdf.js:9899:42)
    at FontLoader.fontLoaderBind [as bind] (/Users/supun/projects/meetrix/PDFToJpeg/node_modules/pdfjs-dist/build/pdf.js:9957:16)
    at WorkerTransport.transportObj (/Users/supun/projects/meetrix/PDFToJpeg/node_modules/pdfjs-dist/build/pdf.js:9422:29)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/Users/supun/projects/meetrix/PDFToJpeg/node_modules/pdfjs-dist/build/pdf.js:1063:19)
    at LoopbackPort.<anonymous> (/Users/supun/projects/meetrix/PDFToJpeg/node_modules/pdfjs-dist/build/pdf.js:8944:20)
    at Array.forEach (<anonymous>)
    at /Users/supun/projects/meetrix/PDFToJpeg/node_modules/pdfjs-dist/build/pdf.js:8943:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:15761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

@Snuffleupagus could you give the some instruction to solve this probleb

**Comment by Snuffleupagus** [comment] 2018-10-05 10:11
> could you give the some instruction to solve this problem

It's commonplace in all bug tracker to close duplicates, in order to keep the number of open issues more manageable and to have relevant discussion occur in *one* place.
Please note that it's *not* necessary for an issue to have been solved in order for it to be marked as a duplicate, which happens to be the case here.

**Closed** 2018-10-05 20:36 UTC
