### ISSUE TITLE
Content-Range and PDF.js

### ISSUE THREAD

**Issue by Dingo64** [mozilla/pdf.js#10278] opened 2018-11-20 21:39 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
Mozarella Firefox Quantum 63.0.1, 64 bit

- Operating system and its version:
Windows 7

- PDF.js version:
2.0.943-dist

- Is a browser extension:
No

Steps to reproduce the problem:
1. Try to load PDF with PDF.JS and watch network activity
2. It does 3 requests. One for first 64kB of PDF, one for last 64 kB of PDF, and one for the whole PDF

What is the expected behavior? (add screenshot)
Don't request whole PDF. Only first and last 64 kB

What went wrong? (add screenshot)
I want to show the first page of a PDF which is 20 MB. PDF.JS loads first and last 64kB of the PDF and renders the PDF perfectly. But it also requests the whole PDF and this is unnecessary 20 MB.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
```

	pdfjsLib.getDocument('my_pdf.pdf').then(function(pdf) 
	{
		pdf.getPage(1).then(function(page) 
		{
			var viewport = page.getViewport(1);
			
			var canvas = $('#viewer canvas')[0];
			var context = canvas.getContext('2d');
			
			var maxWidth = $popBody.width();
			var maxHeight = $popBody.height(); 
			
			var scaleX = maxWidth / viewport.width;
			var scaleY = maxHeight / viewport.height;
			
			var scale = scaleX < scaleY ? scaleX : scaleY;
			
			var scaledViewport = page.getViewport(scale);		
			
			canvas.width = scale * viewport.width;
			canvas.height = scale * viewport.height;
			
			var left = (maxWidth - canvas.width) >> 1;
			var top = (maxHeight - canvas.height) >> 1;			
			
			$(canvas).css('margin-left', left).css('margin-top', top);			
			
			var renderContext = 
			{
				canvasContext: context,
				viewport: scaledViewport
			};
			page.render(renderContext);
		});
```
	});

**Comment by timvandermeij** [comment] 2018-11-20 22:30
Closing since this most likely indicates that the server is not configured correctly and it looks like a duplicate of e.g., #9609.

**Closed by timvandermeij** 2018-11-20 22:30 UTC

**Comment by Snuffleupagus** [comment] 2018-11-20 22:37
> I want to show the first page of a PDF which is 20 MB. PDF.JS loads first and last 64kB of the PDF and renders the PDF perfectly. But it also requests the whole PDF and this is unnecessary 20 MB.

You'll need to provide the appropriate options, when calling `getDocument`, in order for this to work; see https://github.com/mozilla/pdf.js/blob/6ebdbb244f3b9acbe42766654b411584d85f7626/src/display/api.js#L188-L196

Essentially, the `getDocument` call needs to looks something like so:
```javascript
var loadingTask = pdfjsLib.getDocument({
  url: 'my_pdf.pdf',
  disableAutoFetch: true,
  disableStream: true,
});
loadingTask.promise.then(function(pdfDocument) {
  // The document in now loaded...
}); 
```

**Comment by Dingo64** [comment] 2018-11-21 00:02
@Snuffleupagus Thank you, this solves the issue.  
https://i.imgur.com/9QyKUhW.png
