### ISSUE TITLE
Empty page added in when printing from Viewer in Chrome

### ISSUE THREAD

**Issue by jureles** [mozilla/pdf.js#10094] opened 2018-09-21 11:00 UTC
Attach (recommended) or Link to PDF file here:
[Sample.pdf](https://github.com/mozilla/pdf.js/files/2404969/Sample.pdf)

Configuration:
- Web browser and its version: 69.0.3497.100 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: DEMO version (https://mozilla.github.io/pdf.js/web/viewer.html) on 21.9.2018

Steps to reproduce the problem:
1. Open Chrome (browser) and load the PDF.js viewer (e.g. https://mozilla.github.io/pdf.js/web/viewer.html).
1. In the PDF.js viewer open the attached "Sample.pdf" document.
2. Click the Print button in the viewer's toolbar.
3. The Chrome's native print preview shows the document has 2 pages which is wrong. The document only has a single page containing a short text.

What is the expected behavior? (add screenshot)
The Chrome's print preview shows additional empty page. It seems like this only happens in Chrome when printing a document in the Landscape orientation. The same document with a single page in the Portrait orientation will be correctly shown in the Chrome's print preview. It is not just about the preview - if you actually print the document 2 pages will be printed instead of one.
This misbehavior seems to only be present in Chrome. IE11 and Edge will print the document properly.

What went wrong? (add screenshot)
On the screenshot below you can see that the print preview shows additional empty (second) page - note that the attached document only has one page.
![image](https://user-images.githubusercontent.com/36080399/45877296-a1fc9400-bd9d-11e8-85de-627cbec18ddc.png)

**Comment by mkenigs** [comment] 2018-11-08 06:47
Think this is a duplicate of #9295

**Closed** 2018-11-08 21:45 UTC
Labels: 4-printing

**Comment by Tekhlay** [comment] 2022-08-07 13:42
Control the html and body sizes using the following code snnniper in 
<style>
@media print{
html, body { height: auto; }
}
</style>
