### ISSUE TITLE
introduce PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by shikhar-scs** [mozilla/pdf.js#9365] opened 2018-01-15 15:31 UTC
This issue is not an issue with some pdf and that is why I have not followed the TEMPLATE format.

As a good practice I guess, there must be some PR template too, similar to the `ISSUE_TEMPLATE` maybe because often the filed PRs contain insufficient information and thus prolongs/wastes important time later on.

A `PR template` exists on almost major repositories across github and thus, it would only do more good to this repository. (if accepted) I would like to work on this issue.

 I leave it up to the mentors to decide.

**Comment by Snuffleupagus** [comment] 2018-01-15 17:00
> [...] because often the filed PRs contain insufficient information and thus prolongs/wastes important time later on.

In those cases, the problem is usually with the *commit message* of the patch itself rather than the PR, since by default (in GitHub) the contents of the commit message becomes the PR contents.

It's not (generally) sufficient if the PR itself contains useful information, but that information must be present in the *commit message* as well, such that it's possible to get a basic understanding of what a patch does, and importantly *why*, just from e.g. the Git command line. For example, this is very useful when running `git bisect` locally.

**Comment by shikhar-scs** [comment] 2018-01-15 19:59
Then maybe we can introduce a `standard commit format`, something like what `mozilla/fxa-content-server` implements. But that would be more of a task as a commit is a multiple-time thing but pull requests are more or less a one-time thing. On a shorter note, I would strongly want if either one of these exist.

**Comment by shikhar-scs** [comment] 2018-01-20 03:27
Any updates on this ? @timvandermeij @Snuffleupagus

**Comment by timvandermeij** [comment] 2019-01-31 21:40
In practice we don't see too many problems with pull requests, but rather with issues. The issue template did improve this, but still it's often the case that important information is not provided. For pull requests this problem isn't so big because pull requests usually resolve an issue that contains the required context.

Closing since I don't really see what we would put into such a template to make it more useful than the current situation.

**Closed by timvandermeij** 2019-01-31 21:40 UTC
Labels: 1-other
