### ISSUE TITLE
预览PDF添加水印

### ISSUE THREAD

**Issue by 790944715** [mozilla/pdf.js#10643] opened 2019-03-14 03:07 UTC
我想在预览PDF时在特定的页面添加水印，这个应该怎么做？
这个插件能不能以tab的形式预览多个PDF文件？

**Comment by theJian** [comment] 2019-03-14 06:49
Probably duplicate of #7783 
I don't think the watermarking feature will be implemented by pdf.js. You can render a watermark as a overlay.

**Comment by theJian** [comment] 2019-03-14 06:53
To my knowledge, pdf.js doesn't have built-in support for rendering multiple pdf files each of which at their own tab, you need to implement at your own.

**Comment by 790944715** [comment] 2019-03-14 11:49
如果要实现多文件标签的方式，有没有可以参考的文档

**Closed** 2019-03-14 21:45 UTC
