### ISSUE TITLE
Poor zoom quality 

### ISSUE THREAD

**Issue by fsjobeck** [mozilla/pdf.js#14737] opened 2022-04-01 06:45 UTC
Configuration:
- Google Chrome v100

Operating system and its version:
- Window 11, 21H2

PDF.js version:
Currrent Demo per 220401

Steps to reproduce the problem:
1. Load up file
2. Zoom to 1000% and compare

What is the expected behavior? (add screenshot)
Image quality is blurry and poor

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/20165007/161209782-b83d4b28-899b-4aaa-a0f6-4db3ab8b22b1.png)

File:
[Zonindelning - Plan 01-02v2.pdf](https://github.com/mozilla/pdf.js/files/8395299/Zonindelning.-.Plan.01-02v2.pdf)

**Comment by Snuffleupagus** [comment] 2022-04-01 08:07
Duplicate of #6419

**Closed by Snuffleupagus** 2022-04-01 08:07 UTC
