### ISSUE TITLE
Why range value in the request header doesn't sort in   ascending order? Will it affect page render?

### ISSUE THREAD

**Issue by Feeoly** [mozilla/pdf.js#11355] opened 2019-11-24 11:34 UTC
Attach (recommended) or Link to PDF file here: 
https://mozilla.github.io/pdf.js/web/viewer.html?file=compressed.tracemonkey-pldi-09.pdf
Configuration:
- Web browser and its version: Chrome v78
- Operating system and its version:  Win10
- PDF.js version: 2.0.0
- Is a browser extension: no

Steps to reproduce the problem:
1. after the 200 response, the browser got a series of  206 response, see the first range request, it ranges from 0 to 65535, then the second one range from 983040-1016314(just for example), the third one range from 65536 to 131071, etc

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
I wonder if the range request is not in the ascending order, like 0-2, 3-5,5-7, etc., rather than 0-2, 5-7, 3-5. How to make the render in the correct order. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-11-24 13:32
> PDF.js version: 2.0.0

Note that it really matters for *this* particular issue, but that version number has never actually existed...

> [...] then the second one range from 983040-1016314

For the `tracemonkey` file that ought to correspond to the very *last* chunk, which is totally expected behaviour if you actually look at the code in https://github.com/mozilla/pdf.js/blob/827eb64b75f8d0c3b4203202a7cf15c7cbd2ce26/src/core/chunked_stream.js#L534-L545

The reason for this special-case is that the XRef table is located at the end of the PDF document, and without the XRef table being available it's generally impossible (with the exception of linearized documents) to parse/render the various document objects.

> [...] the third one range from 65536 to 131071, etc

The remaining range requests will simply be dispatched in the *necessary* order, depending on which part (e.g. what page) of the document that's currently being parsed/rendered (since pages can be obviously be read out-of-order in the viewer).

> How to make the render in the correct order.

There's no particular reason for the range requests to be dispatched strictly in order, since as explained above the data is being fetched in "as requested" order; hence the implication that the code isn't correct here seems dubious at best.
(Note also that since streaming is also used, in addition to range requests, there shouldn't generally be that many range requests dispatched either.) 

*In closing:* I'm not sure if this is a *valid* issue, since there's no evidence provided that the current implementation is actually wrong.

**Closed** 2019-11-25 21:15 UTC
Labels: 1-other
