### ISSUE TITLE
single page viewer's currentScaleValue = "page-width" creates too small canvas

### ISSUE THREAD

**Issue by d01010101** [mozilla/pdf.js#12118] opened 2020-07-24 14:34 UTC
I use PDFSinglePageViewer from pdfjs 2.4.456. It works well until I want the wrapper div to be filled entirely by the PDF page:

```
   eventBus.on("pagesinit", function () {
      pdfSinglePageViewer.currentScaleValue = "page-width";
    });

```
as suggested by the tutorial. In the case of a div which is 1000px wide this creates a canvas of dimensions (805px, 20900px) scaled up to the screen size of (960px, 24992px) with its own, inline style. Together with LCD optimizations, this creates colorful 2x2 pixel blocks, in practice too ugly to be usable.

Without changing the scale value, the canvas has instead the size (612, 15940) without any upscaling. So, "page-width" makes the canvas bigger in fact, but not big enough. It might be that is is an imprecision caused by the page proportions.

**Comment by Snuffleupagus** [comment] 2020-07-24 14:47
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; as-is this issue unfortunately contains no actionable information.

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by d01010101** [comment] 2020-07-24 14:56
I initially used `singlepageviewer` from `https://github.com/mozilla/pdf.js/blob/master/examples/components`. Then I modified it only in the sense of the placement of files and I suppose that it is still functionally identical and that the scaling problem was there from the beginning. I might be wrong, though. Do you have this example running anywhere on the network, so that I can replace the PDF url with another?

**Comment by d01010101** [comment] 2020-07-24 15:19
Alternately, I could provide you with the test PDF file.

**Comment by d01010101** [comment] 2020-07-24 17:35
The problems happens **only with the "long page" PDF**. Width **other PDFs**, including your example PDF, **it works perfectly**.

**typical A4 PDF**: no upscaling problems with or without page-width, canvas size is well adjusted and stable

**the "long page" PDF**:
    without page-width: canvas size is unstable: it is too small from the beginning, then it changes somewhat when a link is clicked
    with page-width: the canvas is upscaled, giving blocky artefacts

 So I suggest that you take my PDF for tests, because it is only with it, when the canvas size becomes wrong/unstable.

**Comment by Snuffleupagus** [comment] 2020-07-24 18:12
It's really quite difficult to understand *exactly* what the problem is without any screen-shots, which is why the `ISSUE_TEMPLATE.md` ask for those to be provided (among other information).

*If I were to guess:* The problem is most likely related to CSS zooming, which is necessary in order to prevent browser errors with huge canvases, and this would thus be (for all intents and purposes) a duplicate of issue #6419.

**Closed** 2020-07-24 21:11 UTC

**Comment by d01010101** [comment] 2020-07-24 21:20
Snuffleupagus, the screenshot looks simply like an upscaled bitmap. As of the limits, I guess that you are right and I added a comment to the other issue, with the test pdf included.
