### ISSUE TITLE
How to extract unsupported annotation details?

### ISSUE THREAD

**Issue by shabeerksbr** [mozilla/pdf.js#9685] opened 2018-04-22 09:00 UTC
Steps to reproduce the problem:
1.  Using external application to annotate our pdf e.g. Pit Stop Server
2. When opening the annotated pdf using pdf.js, All the layers have been merged.

I know it's similar to issue: [#6804](https://github.com/mozilla/pdf.js/issues/6804)

What is the expected behavior? (add screenshot)
[Expected Result](http://tinypic.com/r/141phfc/9)

What went wrong? (add screenshot)
[PDF js rendered](http://tinypic.com/r/dr5q3t/9)

I know PDF js has not worked on bookmarks layers yet. How can I get those annotations points, So I can draw rectangle over canvas on my own.

**Comment by timvandermeij** [comment] 2018-04-22 11:36
No example PDF file is attached, which is asked for in the issue template. Moreover, it's not clear what the issue is about: layers, annotations and colors (as seen in the screenshot) are three different concepts in the PDF file format. There are already open issues for layers support, so I'm closing this one in favor of those.

**Closed by timvandermeij** 2018-04-22 11:36 UTC
