### ISSUE TITLE
view pdf as svg  GUI is not same as PDF file

### ISSUE THREAD

**Issue by hurrry** [mozilla/pdf.js#8682] opened 2017-07-21 02:41 UTC
Link to PDF file (or attach  here):
http://techexcel.devsuite.net/appweb/k6.pdf
Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1.  view this pdf file as svg is not good!
2. please see two screenshot in below.

What is the expected behavior? (add screenshot)
[http://techexcel.devsuite.net/appweb/2.png](url)
What went wrong? (add screenshot)
[http://techexcel.devsuite.net/appweb/1.png](url)
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by Snuffleupagus** [comment] 2019-01-26 15:42
> Link to PDF file (or attach here):
> http://techexcel.devsuite.net/appweb/k6.pdf

The PDF file is no longer available, and additionally the `Configuration` section is completely empty; closing as INCOMPLETE for now?

**Comment by timvandermeij** [comment] 2019-01-27 13:55
The PDF file is available in the Web Archive at https://web.archive.org/web/20180403195550/https://techexcel.devsuite.net/appweb/k6.pdf.

**Comment by timvandermeij** [comment] 2019-04-07 14:41
This is mostly fixed now. Only blend modes are missing and the calendar icon at the top of each page misses a line.

**Comment by Snuffleupagus** [comment] 2021-05-31 11:34
Given that blend modes support for the SVG back-end is already being tracked in issue #10935, we can probably close this issue as a duplicate of that one (also given the *unsupported* status of the SVG back-end itself).

Duplicate of #10935

**Closed by Snuffleupagus** 2021-05-31 11:34 UTC
Labels: 4-svg
