### ISSUE TITLE
PDF file renders with incorrect colors

### ISSUE THREAD

**Issue by mikedanger** [mozilla/pdf.js#5623] opened 2015-01-07 20:41 UTC
Link to PDF: http://demo.finalsite.com/supporttest1/uploaded/mike_test/2015_Brochure.pdf

Location in PDF: all pages

Screenshots: http://fnlst.co/1tPctZI , http://fnlst.co/1tPcywC (What these should look like per Preview: http://fnlst.co/1tPcxbV , http://fnlst.co/1tPcDjH )

Browser version: Firefox 34.0 : http://fnlst.co/1tPcCMK

Operating system: OS X 10.9.5 : http://fnlst.co/1tPcJrD

PDFJS.version = '1.0.712';

JavaScript console warning/error messages: 

Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:58
Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:73
Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:82
Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:90
Unknown pseudo-class or pseudo-element 'selection'.  Ruleset ignored due to bad selector. viewer.css:1250
"PDF 4a8255f99ea09878d5c821a0221eb6ff [1.5 PDFlib Personalization Server 8.0.4p6 (C++ legacy/Win32) / Rampage PDF PageAssembly] (PDF.js: 1.0.712)" viewer.js:3523

**Comment by yurydelendik** [comment] 2015-01-07 20:52
I see CMYK JPEG which has Decode array `[1, 0, 1, 0, 1, 0, 1, 0]` -- probably we don't take the inversion into account.

**Comment by Snuffleupagus** [comment] 2015-02-23 22:24
This appears to be the exact same issue as #4090, since the errors are identical and both files are generated by the same software.

**Comment by Snuffleupagus** [comment] 2015-05-18 11:17
Closing as duplicate of issue #4090.

**Closed by Snuffleupagus** 2015-05-18 11:17 UTC
Labels: 3-pdf-broken, 4-image-jpeg
