### ISSUE TITLE
How to get html span array for pdf file having 30 pages at once

### ISSUE THREAD

**Issue by viju2008** [mozilla/pdf.js#12553] opened 2020-10-29 18:19 UTC
This has reference to issue #12545 

**I am also i need need of the same thing ... but for 30 pages at once and this is an important Requirement as we need to save the comments and annotation. After 10 pages the span changes so the highlights also which we have custom create as getting lost as the span no longer exists for the first 10 pages**

### Please help

Configuration:

Web browser and its version: Google Chrome
Version 86.0.4240.111 (Official Build) (64-bit)
Operating system and its version: Windows 10
PDF.js version: pdf.js 2.6.401
Steps to reproduce the problem:

Trying to get html span array which is rendered by pdf.js
at a time html span is available for only 10 pages
What is the expected behavior? (add screenshot)
need to get html span for more than 10 pages at once

What went wrong? (add screenshot)
when moving to page -11, span elements of page-1 is getting removed from html dom.
is there any way to get this rid of 10 pages restriction?
screenshot shows html element details where page-13 is loaded, we can see page-1 to page-4 does not contain any span tags.
this is because pdf.js loads only 10 pages at a time (page-5 to page14) in our case.

https://user-images.githubusercontent.com/73604779/97474339-04a7bd00-1972-11eb-93d8-7956420a1bcd.png

Reference to issue https://github.com/mozilla/pdf.js/files/5453823/ttt.pdf

**Comment by timvandermeij** [comment] 2020-10-29 21:32
Closing since this is a duplicate of the other issue; please don't open duplicate issues on purpose.

**Closed by timvandermeij** 2020-10-29 21:32 UTC

**Comment by viju2008** [comment] 2020-10-30 05:18
Request to please help us with our comments on issue 12545
