### ISSUE TITLE
The pdf file with # in the url address cannot be displayed. After removing #, it can be displayed normally

### ISSUE THREAD

**Issue by wolonggl** [mozilla/pdf.js#18211] opened 2024-06-06 07:57 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2024-06-06 08:03
Duplicate of #10632

*For future reference:* Please actually fill out the ISSUE_TEMPLATE when opening an issue.

**Closed by Snuffleupagus** 2024-06-06 08:03 UTC
