### ISSUE TITLE
PDFjs print IPad

### ISSUE THREAD

**Issue by designworxz** [mozilla/pdf.js#4582] opened 2014-04-09 12:25 UTC
Am new to pdfjs and am facing wired issue.. When i open web app on desktop print works but when opened on Ipad print doesn't work only blank paper comes out of printer.

This is how am loading pdf file using iframe with scr =
http://mozilla.github.io/pdf.js/web/viewer.html?file=' + http://abc.com/abc.pdf

**Comment by timvandermeij** [comment] 2016-09-06 10:01
Closing as duplicate of #7597 which has more details.

**Closed by timvandermeij** 2016-09-06 10:01 UTC
Labels: 4-os-ios, 4-printing
