### ISSUE TITLE
SVG: Unreadable headline

### ISSUE THREAD

**Issue by doublex** [mozilla/pdf.js#10619] opened 2019-03-05 19:48 UTC
html renderer works
PDF: [xx.pdf](https://github.com/mozilla/pdf.js/files/2932550/xx.pdf)

Screenshot:
![corrupt](https://user-images.githubusercontent.com/274624/53832938-b6b59880-3f87-11e9-9358-11ac18238839.png)

Steps to reproduce:
````
gulp dist-install
node examples/node/pdf2svg.js /tmp/xx.pdf
````

Console output:
````
# Document Loaded
Number of Pages: 1

# Page 1
Size: 612x792

Warning: Unknown colorspace 12
Warning: Unknown colorspace 12
Warning: Unknown colorspace 12
Warning: Unknown colorspace 12
Warning: Unimplemented operator setFlatness
Warning: Unimplemented operator setFlatness
Warning: Unimplemented operator setFlatness
Warning: Unimplemented operator setFlatness
Warning: Unimplemented operator setFlatness
Warning: Unimplemented operator setFlatness
Warning: Unimplemented operator setFlatness
Warning: Unimplemented operator setFlatness
Warning: Unimplemented operator setFlatness
Page: 1
# End of Document
````

**Comment by Snuffleupagus** [comment] 2019-03-05 19:57
Possibly a duplicate of issue #10588.

**Closed** 2019-03-08 22:16 UTC
Labels: 4-svg
