### ISSUE TITLE
CSP Policy break unsafe-eval

### ISSUE THREAD

**Issue by chintan3100** [mozilla/pdf.js#10387] opened 2018-12-27 08:51 UTC
var g = function () {
  return this;
}() || Function("return this")();

**Comment by timvandermeij** [comment] 2018-12-27 23:01
Closing since this is a duplicate of #10229 which is fixed and will be part of the next release.

**Closed by timvandermeij** 2018-12-27 23:01 UTC

**Comment by Que3216** [comment] 2019-01-30 14:07
When's the next release planned for?

**Comment by timvandermeij** [comment] 2019-01-30 21:19
It's tracked in #10416 and while there is no fixed date yet, we hope to get to this soon.
