### ISSUE TITLE
Downloading error while running gulp makeref

### ISSUE THREAD

**Issue by Peter-Takhar** [mozilla/pdf.js#10849] opened 2019-05-23 21:44 UTC
Attach (recommended) or Link to PDF file here:

PDF link found in test/pdfs/issue6360.pdf.link

Configuration:
- Web browser and its version: N/A
- Operating system and its version: Ubuntu 18.04.2 LTS
- PDF.js version: Master
- Is a browser extension: No

Steps to reproduce the problem:
1. Fork repository and follow instructions to install local version from pdf.js/README.md.
2. Run gulp makeref.

What is the expected behavior? (add screenshot)

All pdfs succesfully downloaded.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/15222014/58287983-64169c00-7d80-11e9-9220-69dd6640d5d1.png)

When I took a look at the file issue6360.pdf.error, it states:
`Error: parse error`

When I took a look at the output of gulp makeref, this came up for the pdf in question: 
![image](https://user-images.githubusercontent.com/15222014/58288331-4564d500-7d81-11e9-943e-5fb6c700b58b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

**Comment by timvandermeij** [comment] 2019-05-23 22:03
It looks like a temporary outage of the Web Archive, because if I try the URL manually it works fine. Could you throw away the `.error` file and try again?

**Comment by Peter-Takhar** [comment] 2019-05-23 22:29
When I deleted `.error` file, it stated that the MD5 hashses didn't match up. 
![image](https://user-images.githubusercontent.com/15222014/58290011-303e7500-7d86-11e9-8507-7b00d8f416a0.png)

I tried to also delete the generated `.pdf` afterwards, but I got the same error stating `Parse error`. 

I decided to look through at the test files through a viewer using `http://localhost:8888/test/pdfs/?frame` found in README.md, and got this output:
![image](https://user-images.githubusercontent.com/15222014/58290427-adb6b500-7d87-11e9-8f93-ae01ee87d711.png)

Seems like it handles the pdf fine in the viewer. Now I am wondering if this is something due to my machine/installation.

**Comment by monchouchou** [comment] 2019-06-27 11:56
Hey @Peter-Takhar, did you figure out this issue? I'm facing the same thing.

**Comment by timvandermeij** [comment] 2019-06-29 10:54
I can reproduce this now after removing the file and trying to redownload it. Printing the full error objects gives:

```
{ Error: Parse Error
    at TLSSocket.socketOnData (_http_client.js:447:22)
    at TLSSocket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at TLSSocket.Readable.push (_stream_readable.js:231:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:154:17)
  bytesParsed: 8523,
  code: 'HPE_HEADER_OVERFLOW',
  reason: 'Header overflow' }
```

I have no clue yet what could cause this...

**Comment by timvandermeij** [comment] 2019-06-29 11:48
The fix for this is in the PR above, but it's pending some updates on our testing bots. If you want, you can apply those changes locally to get the tests working again. Note that you do need to remove the `.pdf` and `.pdf.error` files of the files that have a `.pdf.error` file associated with it.

**Closed** 2019-07-05 19:45 UTC
Labels: 1-test
