### ISSUE TITLE
Slash key should pop up Find bar on Firefox

### ISSUE THREAD

**Issue by yurikhan** [mozilla/pdf.js#7981] opened 2017-01-22 15:24 UTC
Configuration:
- Web browser and its version: Firefox 50.1.0 (and other versions before this)
- Operating system and its version: Ubuntu 16.04
- PDF.js version: 1.5.365 build 19105f0 as far as I can tell
- Is an extension: Yes and no (it’s bundled in Firefox’s omni.ja)

Steps to reproduce the problem:
1. In Firefox, browse to any PDF containing searchable text ([example][1])
2. Press the `/` key (which normally displays the Quick Find bar in Firefox)

[1]: http://www.atmel.com/Images/Atmel-7766-8-bit-AVR-ATmega16U4-32U4_Datasheet.pdf

What is the expected behavior? (add screenshot)

* Either the Quick Find bar or the regular Find bar should pop up, populated with the currently selected text, if any.

What went wrong? (add screenshot)

* No reaction

Additional considerations: On the [web demo][2], the `/` key works, although the highlight position is slightly off.

[2]: http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2017-01-22 15:29
For reference, please see https://bugzilla.mozilla.org/show_bug.cgi?id=940150.

**Comment by Snuffleupagus** [comment] 2019-02-22 11:56
> For reference, please see https://bugzilla.mozilla.org/show_bug.cgi?id=940150.

Let's close this as a duplicate of that bug, since the relevant code now lives *only* in mozilla-central.

**Closed** 2019-02-22 21:14 UTC
Labels: 1-addon, 3-upstream, 4-firefox-specific
