### ISSUE TITLE
Scanned PDF using Koufax capture are not getting  rendered in PDF.js 

### ISSUE THREAD

**Issue by ShruArora** [mozilla/pdf.js#15561] opened 2022-10-11 06:34 UTC
Attach (recommended) or Link to PDF file here:
The scanned document using Koufax capture is not getting rendered and shows a waiting sign. In the console we see 
Warning: Unsupported header type 1667523942 (cdef)
util.js:282 Warning: Unsupported header type 1970628964 (uuid)
Configuration:
- Web browser and its version: Mozilla any version
- Operating system and its version: Any Os, Tested on windows
- PDF.js version: 2.14
- Is a browser extension:

Steps to reproduce the problem:
1. Open the sample document and you will see the wait sign going on continuously.
2.

What is the expected behavior? (add screenshot) It should render the file or show relevant error what is going wrong.

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by JanMikolasek78** [comment] 2022-10-11 06:38
[ELE_00662_02_V_017.pdf](https://github.com/mozilla/pdf.js/files/9751825/ELE_00662_02_V_017.pdf)

**Comment by Snuffleupagus** [comment] 2022-10-11 07:30
> Attach (recommended) or Link to PDF file here:

Note that the PDF document should be attached directly when opening an issue, rather than to a subsequent post.

> PDF.js version: 2.14

*As previously mentioned:* That's not a complete version number, and it's also not a supported version; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

Duplicate of issues such as e.g. #5649 and #11306.

**Closed by Snuffleupagus** 2022-10-11 07:30 UTC
