### ISSUE TITLE
in PDF.js , window.getSelection().getRangeAt(0).getClientRects() is coming always 0 in IE 

### ISSUE THREAD

**Issue by amitK007** [mozilla/pdf.js#10927] opened 2019-06-24 13:07 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE 11 
- Operating system and its version: Windows
- PDF.js version: 2.0.7XX
- Is a browser extension:

What is the expected behavior? (add screenshot)
I need to get the highlighted/selected text from Angular 

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/34776401/60020983-b49a5580-96ae-11e9-81c4-a9048757d1da.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-06-24 13:11
Duplicate of #5513.

**Closed** 2019-06-25 10:19 UTC
