### ISSUE TITLE
PDF Font displaying incorrectly

### ISSUE THREAD

**Issue by g19i85g** [mozilla/pdf.js#9378] opened 2018-01-18 12:51 UTC
The font spacing in this PDF doesn't look good.

[font.pdf](https://github.com/mozilla/pdf.js/files/1642824/font.pdf)

Configuration:
- Firefox Quantum 59.0b1 (64-bit) and Firefox ESR 52.0 (64-Bit)
- Ubuntu 16.04.3 LTS
- PDF.js: 2.0.250 and PDF.js: 1.6.315

What is the expected behavior?
![bildschirmfoto vom 2018-01-18 13-48-24](https://user-images.githubusercontent.com/7912187/35098977-80bdcf9c-fc56-11e7-8642-e6df74e65baa.png)

What went wrong? (add screenshot)
![bildschirmfoto vom 2018-01-18 13-49-41](https://user-images.githubusercontent.com/7912187/35098982-89b02532-fc56-11e7-8c17-332defb00c57.png)

**Comment by Snuffleupagus** [comment] 2018-01-18 13:40
Closing as duplicate of issue #5550.

**Closed by Snuffleupagus** 2018-01-18 13:40 UTC
