### ISSUE TITLE
Highlighting selects wrong things when moving to non-text spaces

### ISSUE THREAD

**Issue by rstanyan** [mozilla/pdf.js#3200] opened 2013-05-03 22:07 UTC
I notice when I highlight text if I move to a space between lines the highlight changes to only cover all the text prior to the start point.

**Comment by Snuffleupagus** [comment] 2015-02-13 14:19
Since this issue contains no specific test-case, meaning that it will be difficult to know if/when it's actually fixed, I'm closing this as duplicate of [many existing text selection issues](https://github.com/mozilla/pdf.js/labels/4-text-selection).

**Closed by Snuffleupagus** 2015-02-13 14:19 UTC
Labels: 4-text-selection
