### ISSUE TITLE
Warning: FormatError: TrueType Collection does not contain "DCWGQU+CambriaMath" font.

### ISSUE THREAD

**Issue by crystalYY** [mozilla/pdf.js#13774] opened 2021-07-22 11:30 UTC
Attach (recommended) or Link to PDF file here: [demo pdf](http://keynoteali.fbstatic.cn/keynotes/517bcbd790d5e01a188ed6b83a838a6e?Expires=1627920000&OSSAccessKeyId=LTAILfW7HL6Nr1Dn&Signature=2hrD22%2B2cXcEc2CjtxKBOad5kDs%3D)

Configuration:
- chorme 91.0.4472.114:
- mac os 10.13.6:
- PDF.js version 2.8.335:
- angular 12:

Steps to reproduce the problem:
1.  pdf resource url is "[demo pdf](http://keynoteali.fbstatic.cn/keynotes/517bcbd790d5e01a188ed6b83a838a6e?Expires=1627920000&OSSAccessKeyId=LTAILfW7HL6Nr1Dn&Signature=2hrD22%2B2cXcEc2CjtxKBOad5kDs%3D)", and there is a problem on page 24
2. when I use the examples demo of official website to upload my pdf, it works well
![image](https://user-images.githubusercontent.com/15272209/126629478-ad745950-8ab9-4107-81a2-4d26f8c83531.png)
 [online-demo](https://github.com/mozilla/pdf.js#online-demo)
3. but when i open it in my angular project, it shows like this, 
![image](https://user-images.githubusercontent.com/15272209/126629377-34474047-fc93-4c11-987e-28300836c757.png)
and has then warning" FormatError: TrueType Collection does not contain "DCWGQU+CambriaMath" font."
this is the online demo [https://stackblitz.com/edit/angular-ivy-hrzruf?file=src/app/app.component.html](https://stackblitz.com/edit/angular-ivy-hrzruf?file=src/app/app.component.html)

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/15272209/126629478-ad745950-8ab9-4107-81a2-4d26f8c83531.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/15272209/126629377-34474047-fc93-4c11-987e-28300836c757.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
 [https://stackblitz.com/edit/angular-ivy-hrzruf?file=src/app/app.component.html](https://stackblitz.com/edit/angular-ivy-hrzruf?file=src/app/app.component.html)

**Comment by Snuffleupagus** [comment] 2021-07-22 11:37
Duplicate of #13193

**Closed by Snuffleupagus** 2021-07-22 11:37 UTC

**Comment by 847901054** [comment] 2024-07-02 07:35
兄弟 这个乱码的问题你解决了吗

**Comment by crystalYY** [comment] 2024-07-02 07:36
您好，您的邮件我已收到，会尽快回复！樊
