### ISSUE TITLE
Use more natural zooming on mobile

### ISSUE THREAD

**Issue by snorp** [mozilla/pdf.js#2582] opened 2013-01-18 19:27 UTC
Right now you have to hit the plus/minus buttons even on mobile in order to zoom the document. This is really strange especially since pinch-to-zoom is active as well. I think the best way to go on mobile is maybe to render at a "natural" size, and let the browser control the zoom, similar to a web page.

**Comment by liuyutao** [comment] 2015-07-08 02:37
Is there any progress.I'm expecting this new feature.

**Comment by sasikanth513** [comment] 2015-09-07 09:20
+2 for this

**Comment by MickL** [comment] 2015-11-19 13:31
Someone got a solution for this 2 year old issue?

**Comment by timvandermeij** [comment] 2015-11-19 20:37
Nothing has been done about this as far as I know. I refer to my previous comment in https://github.com/mozilla/pdf.js/issues/2582#issuecomment-30316908. We invite anyone to submit a PR for this once there is working code.

**Comment by rorysmorris** [comment] 2016-03-10 18:08
Would love to see a solution for this. At the moment this is the only thing that is stopping me from using PDF.JS :(

**Comment by Manmade** [comment] 2016-03-20 10:11
Pinch zoom would be great! I found this jquery plugin that uses pdf.js and has pinch zoom and swiping pages. http://touchpdf.net/demo/index.htm But it would be good if it was build in pdf.js from the start :-)

**Comment by ltullman** [comment] 2016-08-04 14:40
+1 Would love to see this here.

**Comment by sporkman** [comment] 2016-10-05 03:55
+1, also would the example elsewhere that uses hammer.js to capture the event and then call the pdf.js zoom functions not be a relatively "clean" method?

**Comment by rorysmorris** [comment] 2016-10-05 07:32
@sporkman what i did in the end was to render the canvas really large, then to use native browser zooming to allow zooming (my app was designed for touch devices). i can share the source if needed.

**Comment by toplay3** [comment] 2016-10-05 13:14
@rorysmorris how did you manage to get around disabling native browser zoom when pinching while scrolling? I have also implemented hammer.js on pdf.js but cannot get around that particular issue

**Comment by Rob--W** [comment] 2016-10-05 14:29
Have you tried to use the `touch-action` CSS property?
https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

**Comment by toplay3** [comment] 2016-10-05 15:44
@Rob--W 
wow genius! works perfectly now! thanks so much!

**Comment by anik786** [comment] 2016-10-14 13:34
When is this issue planning to be implemented? Its been quite some time since this issue was originally posted. Needless to say +1!

**Comment by MickL** [comment] 2016-10-14 14:32
I also check this issue every week since a year now. Would be awesome to have it in core or as a addon with hammer js.
Am 14.10.2016 15:35 schrieb Yahya Uddin <notifications@github.com>:When is this issue planning to be implemented? Its been quite some time since this issue was originally posted. Needless to say +1!

**Comment by yurydelendik** [comment] 2016-10-14 15:49
To be more constructive on this thread, here is requirements for UI (if somebody wants to really help out and speed out the resolution of the issue) and there is nothing specific to PDF.js:

  - to zoom and pan set of DIVs (with different sizes) that are vertically stacked
  - not allowing user to get lost in viewport at different scales
  - detect and inform when a div visibility or scale changes.

The latter is important since we don't want paint all pages at max resolution on low powered devices. If somebody will have prototype, find to me at IRC I'll help to hook PDFPageView for visibility and scale events. Shall I also set 5-good-beginner-bug?

**Comment by timvandermeij** [comment] 2016-10-14 17:32
I agree that this would be a good beginner bug, so I'm labeling it as such.

**Comment by Rob--W** [comment] 2016-10-17 22:08
This is not just for mobile, I'm also getting feature requests to support two-finger trackpad zooming (on Mac).

From my brief investigation, I found that there is no cross-browser way to support zoom gestures yet.

- Safari has some specific gesture events: https://developer.apple.com/reference/webkitjs/gestureevent
- Firefox add-on code has access to gesture events: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mouse_gesture_events
- Some bugzilla discussion on converting pinch events to ctrl-wheel (with input and references to other browsers): https://bugzilla.mozilla.org/show_bug.cgi?id=1052253

**Comment by Goldenflamer** [comment] 2016-10-25 18:27
+1

**Comment by Manmade** [comment] 2016-10-26 06:31
@toplay3 and @Rob--W What did you do to get it working? Adding "touch-action: auto;"? To what? Thanks!

**Comment by squallstar** [comment] 2016-11-30 09:32
Hi everyone, like most of you I'm interested in getting pinch to zoom working, has anyone been able to do so, even by using external libs like hammer? If so, what is the set up? @rorysmorris @toplay3 @Rob--W thanks

**Comment by kosssi** [comment] 2016-11-30 13:20
👍

**Comment by squallstar** [comment] 2016-12-01 14:26
@rorysmorris any advice about the above question? thanks :)

**Comment by rorysmorris** [comment] 2016-12-01 14:33
Hi @squallstar - at first I tried to use a JS pinch and zoom library to handle this for me, but I found a few problems. It didn't zoom how i wanted, i.e. it would allow the PDF canvas to go completely off-screen, when i never wanted the edges to be away from the screen edge, if that makes sense. In the end, I just used the native zooming that's built into the mobile browser to pinch/zoom/navigate. I setup PDF.js to render the PDF at 3x the pixel size it was being displayed, then scaled down with CSS, so it would remain *fairly* crisp when zoomed in. If you need any help, I could show you a working example of my implementation.

**Comment by squallstar** [comment] 2016-12-01 14:34
@rorysmorris thanks, it would be great if you show me (or send a snippet) or how you implemented it. Much appreciated 👍

**Comment by rorysmorris** [comment] 2016-12-01 14:35
@squallstar send me an email through the contact form on my site and I'll get a demo over to you later on today :) http://rorymorris.co.uk

**Comment by MickL** [comment] 2016-12-01 14:51
@squallstar This is not really a solution but kind of a workaround. Disadvantages are: Performance, result has devices dependency, zoom is not endless.

**Comment by rorysmorris** [comment] 2016-12-01 14:57
The performance is *greatly improved* by using native scrolling and panning, as opposed to using JavaScript to perform those tasks. Maximum zoom-level is easily configurable with a meta viewport tag, and who wants endless zoom on a rasterised image anyway? Great looking "JS-ImageResizer" library by the way! @MickL

**Comment by MickL** [comment] 2016-12-01 15:05
Performance was more a guess. Lets say using an iPhone Plus in landscape @ 2208px width. Now you would have a 6624px Canvas. Depending on the PDF complexity and count of pages you may have 3 rendered 6000px Canvas with HTML-text, graphics etc.

I guess your solution is great for a lot of people. But as you described its more a fake-zoom than it actually triggers PDF.js zoom and rerendering :)

**Comment by rorysmorris** [comment] 2016-12-01 15:10
True, performance-wise from that aspect isn't great. In my particular use-case for this, I had to render out 300+ page PDF's at iPad (retina) size, as well as have a drawing canvas on top of each one!

PDF.js would crash the browser (iOS Safari) at around 10 rendered PDF pages, so in the end I had to only show one PDF page at a time with previous/next buttons. Not ideal! And I agree, native zoom functionality built into PDF.js would've been a lot nicer.

**Comment by toplay3** [comment] 2016-12-02 05:42
checkout kamihq.com for working pinch-zoom example

**Comment by squallstar** [comment] 2016-12-02 12:07
@rorysmorris I've sent you my email yesterday evening through the contact form, any chance you can send me the example you were talking about? :) thanks

**Comment by ltullman** [comment] 2016-12-13 20:54
Can anyone who has a working example (@rorysmorris, @Rob--W, etc) please share?

**Comment by hetalv985** [comment] 2017-01-26 21:09
@rorysmorris I tried to contact you through your website. If anyone has a working example of this, can you please share?

**Comment by squallstar** [comment] 2017-01-26 21:21
@ltullman @hetalv985 I managed to have it working, check my gist here:

https://gist.github.com/squallstar/1d720e93eabe7f60dc61b547d2c19228
simply paste that to the end of viewer.html 👍  that's it.

**Comment by hetalv985** [comment] 2017-01-27 18:00
Thanks squallstar. But we are not using the viewer.html. We are rendering the pdf in our iOS mobile app inside a div tag. How do we use this feature in that case? Do we need to include the viewer files?

**Comment by MickL** [comment] 2017-03-20 11:24
So we have the function `handleMouseWheel` which is very similar. Why not use the exact same function with touch gesture oder hammer js?

**Comment by timvandermeij** [comment] 2017-03-20 21:38
Unfortunately it's not that easy. Please refer to my previous comment at https://github.com/mozilla/pdf.js/issues/2582#issuecomment-30316908. We need to limit the amount of touch gestures so that the canvas is not re-rendered on every delta change, which is a major performance issue. If someone is willing to work on this, feel free to submit a PR and we'll review it.

**Comment by MickL** [comment] 2017-03-21 08:08
If thats the only issue... :)

**Comment by MickL** [comment] 2017-03-27 09:16
I invested alot of time in this. Actually it seem possible but there are several problems i couldn't solve:

- hammer.js only works on pinchend (pinchmove always gets canceled when pdf.js zooms)
- I could not scroll perfectly to the center of pinchend even though i used the same method as mousewheel-zoom does
- I tried to add css transformation on pinchmove which would give great performance but again i was not able to scroll perfectly (position #viewer with css translate)
- hammer.js prevents any other touch-action(in our case regular page scroll) so i had to modify hammer.js to only prevent when 2 fingers are used

Even if all problems would be solved iOS 10 allows page-zoom even when it is disabled with `user-scalable=no`. A few times preventDefault() is not working and the whole page is zoomed. This would lead in to major issue for the end user (only way to get out is to double-tap the toolbar).

**Comment by betovidal** [comment] 2017-03-29 01:48
@MickL I gave it a try. I was able to avoid the "pinch zoom" cancellation by adding the CSS property "pointer-events: none" to the classes pdfViewer and page (and calling stopPropagation + preventDefault when viewerContainer dispatches double touch events so the entire page doesn't zoom on iOS).

I'm having the same issue you describe of not having the perfect zoom position event when I use the modified mousewheel method (pass the next scale to be applied, current "middle position" or target and the delta of "middle position" to know how much to move to left, right, up, down, managed by pdfViewer.container.scrollLeft and pdfViewer.container.scrollTop). There seems to be always an error introduced maybe by the timeout that keeps the viewer from rendering on every double touch event.

Any hint on where to apply those CSS scale transformations to avoid rendering everything on every scale delta?

**Comment by buzzyboy** [comment] 2017-08-07 21:50
@betovidal I know it's been a few months since your last post. Have you made any updates on getting pinch-zooming to work in PDF.js? I'm working on a project for work that requires this.
Maybe we could work together to figure something out?

**Comment by vuinguyen** [comment] 2017-09-18 17:33
@squallstar I tested your solution on iOS very briefly. But so far, it's working for me! Thanks for sharing your solution 💯

**Comment by squallstar** [comment] 2017-09-19 08:40
@vuinguyen thanks! I'm glad it worked for you too ;)

**Comment by sunsus** [comment] 2017-10-30 06:36
+1

**Comment by joselcvarela** [comment] 2017-11-03 10:16
Hey,
Can't we pinch zoom and re-render the page? In my case I want this feature to work width touch desktops.

**Comment by prohtex** [comment] 2018-01-22 21:08
Any hope of getting @squallstar's code integrated into a PR? Currently, if a user tries to pinch and zoom on a mobile device, they are often "locked" out of scrolling, and have to reload the page simply to navigate further. Relying on the tiny "+" and "-" buttons to navigate is rather counterintuitive for a mobile viewer in 2018.

**Comment by MickL** [comment] 2018-01-22 21:13
Pinch-zoom is "broken" on iOS since iOS 10. Even if everything is implemented perfectly Safari will screw everything up.

**Comment by prohtex** [comment] 2018-01-22 21:14
Is this an iOS specific issue? Is it possible to pinch zoom a PDF served by pdfjs on Android?

**Comment by MickL** [comment] 2018-01-22 21:19
Depends on the browser. I assume that only iOS browsers ignores "user-scalable=no".

**Comment by prohtex** [comment] 2018-01-22 21:21
> Right now you have to hit the plus/minus buttons even on mobile in order to zoom the document. This is really strange especially since pinch-to-zoom is active as well. I think the best way to go on mobile is maybe to render at a "natural" size, and let the browser control the zoom, similar to a web page.

To me, this says it all.

**Comment by amurillo17** [comment] 2018-05-31 17:08
I saw that "Box Content Preview" (which uses PDFJS to show PDFs) does a good implementation for this. This is a Codepen of their viewer:

https://codepen.io/box-platform/pen/rmZdjm

And this is the pull request for their fix:

https://github.com/box/box-content-preview/pull/567

I thought that maybe someone could make something similar for PDFJS, based on their solution. I'll try to implement it myself and post the code if I do. I'll be great if someone else (that probably have more experience than me) can also collaborate and try it!

**Comment by prohtex** [comment] 2018-06-01 15:32
@amurillo17 thanks for the link. The Box solution looks fantastic. I'd love to see something like this working with pdfjs. Please keep us updated on your progress!

**Comment by rcarretteGroupeBRIAND** [comment] 2019-03-18 16:25
any updates ? Thanks

**Comment by AnReZa** [comment] 2019-04-10 09:40
Are there any simple ways to add this feature to the existing viewer?

**Comment by prohtex** [comment] 2019-04-10 09:48
> Are there any simple ways to add this feature to the existing viewer?
No.

**Comment by AnReZa** [comment] 2019-04-10 09:51
@prohtex Hm, that's pretty sad. I hope, that such a feature will be added soon after all these years.

**Comment by prohtex** [comment] 2019-04-10 09:53
> @prohtex Hm, that's pretty sad. I hope, that such a feature will be added soon after all these years.

It will only be added when someone steps up and integrates code into a PR (not me, sadly), and even then, it could take years.

**Comment by M-Reimer** [comment] 2019-04-22 12:39
I have a workaround, but it is "Android only" as I don't care about iOS in my "Firefox for Android" addon:
https://github.com/M-Reimer/android-pdf-js/blob/master/patches/pdfjs-pinch-gestures.js
My Makefile just appends this to "web/viewer.js". It registers to the touch events and translates the pinch gestures to button clicks.

**Comment by AnReZa** [comment] 2019-04-23 07:07
> I have a workaround, but it is "Android only" as I don't care about iOS in my "Firefox for Android" addon:
It works on my iPad as well, but it feels a little bit sluggish and not very natural. It zooms one step after each pinch. So you have to release the fingers to make it zoom and it doesn't matter how far of a distance you have pinched. Is this the normal behavior, or just a device-specific bug? Thank you anyways, cause this is a step into the right direction.

**Comment by prohtex** [comment] 2019-04-23 07:10
> It works on my iPad as well, but it feels a little bit sluggish and not very natural. It zooms one step after each pinch. So you have to release the fingers to make it zoom and it doesn't matter how far of a distance you have pinched. Is this the normal behavior, or just a device-specific bug? Thank you anyways, cause this is a step into the right direction.

Looking at the code, this is not a viable solution or even a good workaround. All this does is watch for zoom events and simulate clicking on the [-] [+] buttons with jQuery.

**Comment by AnReZa** [comment] 2019-04-23 07:20
@prohtex Exactly. If you try it, it does something, but it doesn't work well at all.

**Comment by M-Reimer** [comment] 2019-04-23 08:54
As I said: Not perfect but better than nothing.
At least for me it's easier to do the pinch gesture than to hit a small zoom button on a small mobile screen. It makes gestures work that every mobile device user expects to work.

> It works on my iPad as well, but it feels a little bit sluggish and not very natural. It zooms one step after each pinch. So you have to release the fingers to make it zoom and it doesn't matter how far of a distance you have pinched. Is this the normal behavior, or just a device-specific bug? Thank you anyways, cause this is a step into the right direction.

It hits the buttons. "Natural zooming" is not possible with this simple approach and I don't want to mess too much with PDF.js. This is not the goal of my Addon.

But it should be possible to do multiple button presses depending on how far the fingers have moved. I'll try that.

> Looking at the code, this is not a viable solution or even a good workaround. All this does is watch for zoom events and simulate clicking on the [-] [+] buttons with jQuery.

I'm open to suggestions, but as this is part of an Addon which just wants to make PDF.js usable as PDF viewer inside Firefox, I won't do deep modifications.

BTW: There is not a single line of jQuery in my code. This is raw JavaScript.

**Comment by M-Reimer** [comment] 2019-04-23 08:57
It should be actually possible to do the zoom steps while moving the fingers...
I'll try to do some more improvements, but the only communication path, I'll use, are the two buttons that I'll remote-control. This way my code doesn't interfere with PDF.js.

**Comment by prohtex** [comment] 2019-04-23 09:00
> BTW: There is not a single line of jQuery in my code. This is raw JavaScript.
I stand corrected. Hoping for a mature solution soon.

**Comment by MickL** [comment] 2019-04-23 09:03
The way to accomplish this is by using css transformation while pinch-zoom. Also the movement of the fingers needs to be applied not just the zoom. Then on pinch-zoom-end you can reset css transformation and apply actual zoom and scroll to pdf.js.

**Comment by AnReZa** [comment] 2019-04-23 09:06
> P.S. Using jQuery inside a non-jQuery project already seems like a bad practice to me.

Where does @M-Reimer use JQuery? As he already stated, his workaround does only use plain Javascript.

**Comment by prohtex** [comment] 2019-04-23 09:09
Yeah.. my bad. Point being, this solution doesn't work well.

**Comment by M-Reimer** [comment] 2019-04-27 15:12
Updated so the distance between fingers changes the zoom amount:
https://github.com/M-Reimer/android-pdf-js/blob/master/patches/pdfjs-pinch-gestures.js
It is not possible to zoom while moving the fingers as, for some reason, the actual zoom and redraw causes the touch event to somehow "end".
Again: Better than not handling the gesture at all.

**Comment by AnReZa** [comment] 2019-05-07 11:59
@M-Reimer Thank you very much for your work. At least, it's an improvement compared to the last version. Maybe someone finds a solution to make it redraw while zooming. Or it might be possible to temporarily zoom using css transformations and then redraw it eventually after the touch gesture ends.

**Comment by AnReZa** [comment] 2019-05-15 13:44
@anvaka Looked into the case and it seems like there might be [a rather simple solution](https://github.com/anvaka/panzoom/issues/95#issuecomment-492658637). Unfortunately I currently don't have the time to test it, but maybe one wants to try and test it.

**Comment by ipartola** [comment] 2019-10-08 19:15
Is there still no fix for this issue? I'd like to use pdf.js on mobile but without the ability to zoom it is mostly useless on smaller screens.

**Comment by MickL** [comment] 2019-10-08 20:45
I made it work without the use of hammer.js but since it was for a customers project i cant share the code. I implemented pinch and doubletap and zoomed with css and on pinchend i zoomed pdf.js. Some elements require to set width/height and some can be transformed with css-transform. Also while zooming the scroll-watch of pdf.js viewer.js has to be prevented. Took me lot of time but it worked pretty well in the end.

**Comment by prohtex** [comment] 2019-10-08 20:56
> Is there still no fix for this issue? I'd like to use pdf.js on mobile but without the ability to zoom it is mostly useless on smaller screens.

Until a developer experienced with the pdf.js codebase steps to offer a solution, it will be up to each person who implements pdf.js to cobble something together. Doesn’t seem to be a big priority for this project. 

https://github.com/mozilla/pdf.js/issues/2582#issuecomment-539660914

**Comment by aidrouge** [comment] 2019-10-08 23:02
https://gist.github.com/jsprpalm/12217feab2f1acc14bd8e8508291619e

@jsprpalm  thank you works great needs a fix please someone help to fix

**Comment by larsneo** [comment] 2019-11-08 23:20
@aidrouge https://gist.github.com/larsneo/bb75616e9426ae589f50e8c8411020f6

**Comment by M-Reimer** [comment] 2019-11-10 10:13
> @aidrouge https://gist.github.com/larsneo/bb75616e9426ae589f50e8c8411020f6

I've added this one to my PDF viewer addon. Seems to work pretty well.
https://addons.mozilla.org/android/addon/android-pdf-js/

**Comment by prohtex** [comment] 2019-11-10 19:31
Works but seems to be wreaking havoc on rendering of text in OCR’d PDF’s

**Comment by punisher97** [comment] 2019-12-17 05:31
For me working more natural setting this:

```
<meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=10.0, minimum-scale=1.0"
    />
```

**Comment by KazysNoobiys** [comment] 2020-01-29 03:52
How do I set the minimum zoom? I can reduce the image so much that it turns into a dot.

**Comment by youngAe** [comment] 2020-05-17 19:40
I have a question. What is this link? Is it what has said very long time?  

https://www.integratingstuff.com/2014/09/14/displaying-a-part-of-a-pdf-page-and-reading-acroforms-with-pdf-js/

**Comment by vniehues** [comment] 2020-07-29 10:26
I have the same question as @KazysNoobiys.
minimum-scale on the viewport doesn't affect the zooming

**Comment by bradporter** [comment] 2020-10-12 01:29
I'm working on another work around:  a transparent css layer overlaying pdf.js to handle various swipe functionality.  The overlay portion works now, but I don't know what functions to call.
if(swipe=='left')   ????
What function would I call in order to advance to the next page or backup to the previous page or zoom?

**Comment by WeiFei365** [comment] 2020-10-19 09:26
save your time & life, edit your .html file like this
```html
// delete the 'maximum-scale'
<meta name="viewport" content="width=device-width, initial-scale=1">
```
eg. https://github.com/mozilla/pdf.js/blob/master/web/viewer.html#L26

**Comment by 438198602** [comment] 2021-02-05 03:40
https://github.com/manuelstofer/pinchzoom is good

**Comment by cepm-nate** [comment] 2021-04-13 18:08
I'm designing for Android and iOS. Several people mentioned modifying the meta tag in the viewer.html file to something like this:

`<meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=10.0, minimum-scale=1.0"
/>`

On Android, this does not seem to have any effect. Pinching does nothing on the PDFs in the viewer. Has anyone successfully used the native zooming on Android within the viewer.html?

**Comment by kikuchy** [comment] 2022-05-19 09:14
Sorry but is there any progress?

**Comment by KnIfER** [comment] 2022-10-24 04:25
in pdf.js comment out 
```
    // window.addEventListener("touchstart", webViewerTouchStart, {
    //   passive: false
    // });
```
then the native blurry zooming by `<meta` will work again. 
but if you use desktop browser and enable devtools/mobile mode , pinching on the touchpad will change the pdf canvas zoom directly...

**Comment by angelaki** [comment] 2022-11-15 13:52
Any news on this? Isn't this a super desired feature? Scrolling on desktop using Ctrl+Mousewheel is so super smooth, why not just offer this behavior for pinching?

**Comment by KarstenK77** [comment] 2022-12-19 21:00
Seven years later? No one interessted anymore in using PDF.js with gestresst? Or what I have missed?

**Closed** 2023-01-04 16:20 UTC
Labels: viewer, feature

**Comment by szaimen** [comment] 2023-01-04 16:21
🎉🎉🎉🎉🎉
