### ISSUE TITLE
How can i display stamp in pdf?

### ISSUE THREAD

**Issue by kiner-tang** [mozilla/pdf.js#8149] opened 2017-03-10 10:32 UTC
Link to PDF file (or attach file here):

Configuration:

Web browser and its version:chrome[56.0.2924.87 (64-bit)],safari[10.0.2 (11602.3.12.0.1)],Android 7.0 NRD90M
Operating system and its version:OS X [10.11.6 (15G1217)]
PDF.js version:0.8.0
Is an extension:
Steps to reproduce the problem:

Get a pdf with a stamp
2.Use pdf.js to load the pdf file
What is the expected behavior? (add screenshot)
Pdf can show stamp
![image](https://cloud.githubusercontent.com/assets/10286961/23791915/d5e3d0fe-05bf-11e7-9210-0c2db2423c8d.png)

What went wrong? (add screenshot)
Pdf does not show stamp
![image](https://cloud.githubusercontent.com/assets/10286961/23791921/dc473e04-05bf-11e7-9307-3995b774b74f.png)

pdf url:

https://pan.baidu.com/s/1i4B8OO9

**Comment by Snuffleupagus** [comment] 2017-03-10 11:22
*I'm attaching the PDF file directly to the issue, to save others (who like myself don't speak Chinese) from figuring out how to download it:* [test_bak.pdf](https://github.com/mozilla/pdf.js/files/833742/test_bak.pdf)

I cannot reproduce this issue, using the *latest* version (which as of this writing is `1.7.357`) of PDF.js. Opening the above PDF file with the default viewer, this is what it looks like:

![stamp](https://cloud.githubusercontent.com/assets/2692120/23793453/9ace0310-058b-11e7-9d4d-4c2c89d6429b.png)

---
@kiner-tang Can you reproduce this issue issue in the demo viewer (by clicking on the "Open file" button on the toolbar), available at https://mozilla.github.io/pdf.js/web/viewer.html?

> PDF.js version:0.8.0

There hasn't ever been a PDF.js release with that version number, so I'd suggest making sure that you're using the *latest* version of PDF.js.

**Comment by kiner-tang** [comment] 2017-03-11 03:48
Thanks, maybe my pdf source file is in question

**Comment by timvandermeij** [comment] 2017-03-11 14:08
Closing for now since the provided file seems to works as expected with the most recent version of PDF.js.

**Closed by timvandermeij** 2017-03-11 14:08 UTC
Labels: 4-information-requested
