### ISSUE TITLE
NS_ERROR_FAILURE when trying to open a PDF file

### ISSUE THREAD

**Issue by AnasAl-tamemy** [mozilla/pdf.js#8260] opened 2017-04-10 07:10 UTC
Link to PDF file (or attach file here):
[pdfjs_issue.pdf](https://github.com/mozilla/pdf.js/files/909251/pdfjs_issue.pdf)

Configuration:
- Web browser and its version: Firefox 52.0.2 (32-bit), Chrome  57.0.2987.133 
- Operating system and its version: Windows 10 Pro 64-bit Version 1067 (OS Build 14393.953)
- PDF.js version: 1.8.177
- Is an extension: No

Steps to reproduce the problem:
1. Try to open the attached pdf file using the viewer demo "https://mozilla.github.io/pdf.js/web/viewer.html"
2. It will not open, on FireFox you will get error in console "NS_ERROR_FAILURE"
3. Also i tried to open it using plain PDFJS api's and get the same error.

What is the expected behavior? (add screenshot)
The file to open correctly, (or at least an error returned to the error callback)

What went wrong? (add screenshot)
The file will not open and the error callback will not be triggered.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2017-04-10 09:25
Closing as duplicate of issue #6741.

**Closed by Snuffleupagus** 2017-04-10 09:25 UTC

**Comment by AnasAl-tamemy** [comment] 2017-04-13 07:20
i have opened the file with illustrator and removed the png image then added it again then saved.
i tried the new file and it is working ([pdfjs_issue_comp.pdf](https://github.com/mozilla/pdf.js/files/918753/pdfjs_issue_comp.pdf)), so i don't think the issue is related to huge images in pdf.

**Comment by Snuffleupagus** [comment] 2017-04-13 08:07
> [...] so I don't think the issue is related to huge images in pdf.

Unfortunately this conclusion is incorrect, since in the broken PDF file the image is two orders of magnitude larger than the image in the working PDF file.
Please compare the `Width`/`Height` of the images in the two PDF files, using the screen-shot below, and you'll see the difference:

![comparison](https://cloud.githubusercontent.com/assets/2692120/24995821/90bd89e4-2030-11e7-8430-d0cc3765b2a5.png)

**Comment by AnasAl-tamemy** [comment] 2017-04-13 10:41
I am sorry, you are right.
it would be great if pdfjs return error for such files in order to handle fallback.
