### ISSUE TITLE
Grey Rectangles Appearing in background of PDF

### ISSUE THREAD

**Issue by buzzyboy** [mozilla/pdf.js#10101] opened 2018-09-24 17:53 UTC
Attach (recommended) or Link to PDF file here:
[Day Trade Spy Case Study(v1).pdf](https://github.com/mozilla/pdf.js/files/2412228/Day.Trade.Spy.Case.Study.v1.pdf)

Configuration:
- Web browser and its version: Chrome 68.0.3440.106 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: 
- Is a browser extension: No

Steps to reproduce the problem:
1. Open pdf with PDFJS
2. Observe gray rectangles in background

What is the expected behavior? (add screenshot)
![expectedresult](https://user-images.githubusercontent.com/7034667/45969241-f5fab900-bfe7-11e8-8c72-ae64dd6a46b9.png)

What went wrong? (add screenshot)
![howitlooks](https://user-images.githubusercontent.com/7034667/45969244-f98e4000-bfe7-11e8-8a55-a653995fd786.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2018-09-24 18:06
Duplicate of issue #269.

**Closed** 2018-09-24 23:09 UTC
