### ISSUE TITLE
about the file name is chinese

### ISSUE THREAD

**Issue by qiannianhappy** [mozilla/pdf.js#5621] opened 2015-01-07 08:42 UTC
The pdf.js demo support pdf name is “compressed.tracemonkey-pldi-09.pdf” ,if the name change to chinese,such as "文档.pdf", pdf.js can not find it.The Regular Expressions to find pdf is not  match?

**Comment by Snuffleupagus** [comment] 2015-01-07 12:03
Unfortunately it's not entirely clear from the description what "pdf.js can not find it" means.
@qiannianhappy Please provide detailed, step-by-step, instructions that can be used to reproduce the issue.

**Comment by yurydelendik** [comment] 2015-01-07 15:22
works for me at http://www.edu.tw/userfiles/url/20140529105812/%EF%BC%88%E7%AC%AC3%E7%89%88%EF%BC%89%E9%82%81%E5%90%91%E8%8F%AF%E8%AA%9E%E6%96%87%E7%94%A2%E6%A5%AD%E8%BC%B8%E5%87%BA%E5%A4%A7%E5%9C%8B%E5%85%AB%E5%B9%B4%E8%A8%88%E7%95%AB1030526-%E4%BE%9D%E5%9C%8B%E7%99%BC%E6%9C%83%E6%84%8F%E8%A6%8B%E4%BF%AE.pdf

![screen shot 2015-01-07 at 9 17 52 am](https://cloud.githubusercontent.com/assets/1523410/5647785/b9d794be-964e-11e4-9bbc-820c5f3e5ed9.png)

**Comment by qiannianhappy** [comment] 2015-01-08 01:32
Thanks for your replay,What's the version of pdf.js used to the link you gived to me? But mine not work.
Whether any js file is added or not?

**Comment by qiannianhappy** [comment] 2015-01-08 03:02
![qq 20150108103204](https://cloud.githubusercontent.com/assets/9958697/5657202/c2970bfc-9725-11e4-85d9-b3b0fce64a68.jpg)

**Comment by yurydelendik** [comment] 2015-01-08 03:24
> What's the version of pdf.js used to the link you gived to me?

We are using different versions of PDF.js, OS-es and browsers. You shall specify as many details as possible as requested in https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.

I see you are using a custom solution. We would prefer to see this online to see and troubleshoot the issue. Looks like you don't encode URL, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

**Comment by qiannianhappy** [comment] 2015-01-08 06:05
encodeURI  or decodeURIComponent? decodeURIComponent I have tried.Encode the whole URL or just only encode Pdf file name?
![qq 20150108135949](https://cloud.githubusercontent.com/assets/9958697/5658569/fd389622-973e-11e4-96e5-3c3987a0acac.jpg)
![qq 20150108140046](https://cloud.githubusercontent.com/assets/9958697/5658568/fcaf9426-973e-11e4-8107-4dc7ffc9ded0.jpg)

**Comment by qiannianhappy** [comment] 2015-01-08 06:06
encodeURIComponent

**Comment by qiannianhappy** [comment] 2015-01-09 02:30
@yurydelendik   The Link you give to me don not  have used Pdf.js. You can try to open it  by Chrome Or IE9+.

**Comment by timvandermeij** [comment] 2015-01-11 21:29
Closing as incomplete. Please provide as much details as possible as requested by @yurydelendik to reopen, specifically an online demo (hosted on your own webserver or jsfiddle.net/jsbin.com for example). When this information is provided, the issue can be reopened.

**Closed by timvandermeij** 2015-01-11 21:29 UTC
Labels: 4-information-requested
