### ISSUE TITLE
Modify the appearance with 'Theme Selector'

### ISSUE THREAD

**Issue by johnmara** [mozilla/pdf.js#7208] opened 2016-04-16 16:27 UTC
Me and my friend are thinking of creating a tool for changing the appearance(color, text, formatting etc.) of pdf.js viewer. So people with vision problems will have an easier navigation.
It's an easy task and it's actually for a uni course. But it's also a chance to get to know the basics of pdf.js and make a bigger change later.

**Comment by timvandermeij** [comment] 2016-04-16 16:57
There is also #3528 that is related to this issue.

**Comment by Snuffleupagus** [comment] 2016-04-18 08:30
This seems similar enough to e.g. #3528 that I think we can close this one as a duplicate of that issue.

**Closed by Snuffleupagus** 2016-04-18 08:30 UTC
Labels: 1-ux, 1-viewer, 2-feature
