### ISSUE TITLE
Trouble with opening PDFs with non-ASCII characters

### ISSUE THREAD

**Issue by wojtekmaj** [mozilla/pdf.js#8937] opened 2017-09-20 17:16 UTC
Link to PDF file (or attach file here):
[23.pdf](https://github.com/mozilla/pdf.js/files/1318569/23.pdf)

Configuration:
- Web browser and its version: Any
- Operating system and its version: Windows 10
- PDF.js version: 1.9.577, likely does not matter
- Is an extension: No

What is the expected behavior? (add screenshot)

I have a package that makes a bridge between pdf.js and React, [react-pdf](https://github.com/wojtekmaj/react-pdf). Recently I was informed that the file attached above does not render correctly.
I tested the file in my project and in pdf.js online viewer to confirm. It did not work on my project, worked correctly on online viewer. However, I've noticed that online viewer makes additional server requests while opening the file, which fail on my project.

* What is the file it's trying to load?
* Can I somehow make it work with Webpack without the need to force my users to manually add the files to their projects?
* And finally, why baseUrl was null in the first place and why the request was not stopped because of it?

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/5426427/30657405-ce25d892-9e37-11e7-99f3-7fb897991655.png)

![image](https://user-images.githubusercontent.com/5426427/30657391-c6a790f6-9e37-11e7-8b6b-6fada73d33af.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

http://projekty.wojtekmaj.pl/react-pdf/test

**Comment by yurydelendik** [comment] 2017-09-20 18:25
Here is what we do to configure demo viewer https://github.com/mozilla/pdf.js/blob/master/web/app.js#L51-L64

Try specifying cMapUrl/cMapPacked globals.

**Comment by yurydelendik** [comment] 2017-09-20 18:34
> What is the file it's trying to load?

External CMap files that can be referred from some PDFs (similar to non-embedded fonts). They are not included into the main code due to their size

>  Can I somehow make it work with Webpack without the need to force my users to manually add the files to their projects?

The files needs to be present, so PDF.js can lazily fetch them when need. Sorry, we don't have JSONP option yet (from CDN). Somebody welcome to work on it.

> And finally, why baseUrl was null in the first place and why the request was not stopped because of it?

No reason. Adding the null-check before issuing a request or, even better, using "always fails" CMapReaderFactory will be a good addition to the PDF.js core library.

**Comment by jamiebikies** [comment] 2017-09-28 03:49
What is the cause of the null baseUrl, though? I am running into this as well. When I specify a `PDFJS.cMapUrl` the change doesn't seem to take effect as I still get the 404 on the odd url:

![image](https://user-images.githubusercontent.com/212150/30948518-75d10cb4-a3de-11e7-9cc6-df47ae85e540.png)

**Comment by Snuffleupagus** [comment] 2017-10-05 10:38
> No reason. Adding the null-check before issuing a request or, even better, using "always fails" CMapReaderFactory will be a good addition to the PDF.js core library.

Can we close this as fixed by PR #8962, or are additional changes required first?

**Comment by timvandermeij** [comment] 2017-10-05 20:39
Yes, I would say so. If more changes are required now that the validation is implemented, please open a new issue with all required details.

**Closed by timvandermeij** 2017-10-05 20:39 UTC
Labels: 1-core
