### ISSUE TITLE
PDF viewer shows document fine, but manually parsing it gives error

### ISSUE THREAD

**Issue by markotaht** [mozilla/pdf.js#11348] opened 2019-11-20 07:31 UTC
Im developing a PDF signing app which has its base in PDF.js. Now i have a PDF document that the viewer read and views just fine, but when i do:
` const pdf = new PDFDocument({ evaluatorOptions: { isEvalSupported: false, }, }, pdfArray);
  pdf.parseStartXRef();
  pdf.parse();` I get 

> XRefParseExceptionClosure@webpack:///./node_modules/pdfjs-dist/lib/core/core_utils.js?:80:34\n@webpack:///./node_modules/pdfjs-dist/lib/core/core_utils.js?:84:2\n./node_modules/pdfjs-dist/lib/core/core_utils.js@http://localhost:8080/main.bundle.js:4656:1\n__webpack_require__@http://localhost:8080/main.bundle.js:64:30\n@webpack:///./node_modules/pdfjs-dist/lib/core/parser.js?:43:38\n./node_modules/pdfjs-dist/lib/core/parser.js@http://localhost:8080/main.bundle.js:4908:1\n__webpack_require__@http://localhost:8080/main.bundle.js:64:30\n@webpack:///./node_modules/pdfjs-dist/lib/core/obj.js?:35:34\n./node_modules/pdfjs-dist/lib/core/obj.js@http://localhost:8080/main.bundle.js:4884:1\n__webpack_require__@http://localhost:8080/main.bundle.js:64:30\n@webpack:///./node_modules/pdfjs-dist/lib/core/document.js?:31:31\n./node_modules/pdfjs-dist/lib/core/document.js@http://localhost:8080/main.bundle.js:4680:1\n__webpack_require__@http://localhost:8080/main.bundle.js:64:30\n@webpack:///./src/ksipdftool/ksi_pdf_signer.js?:42:106\n./src/ksipdftool/ksi_pdf_signer.js@http://localhost:8080/main.bundle.js:5926:1\n__webpack_require__@http://localhost:8080/main.bundle.js:64:30\n@webpack:///./src/ksipdftool/ksi_js_pdf_tools.js?:16:92\n./src/ksipdftool/ksi_js_pdf_tools.js@http://localhost:8080/main.bundle.js:5890:1\n__webpack_require__@http://localhost:8080/main.bundle.js:64:30\n@webpack:///./src/ksi_signature_viewer.js?:24:106\n./src/ksi_signature_viewer.js@http://localhost:8080/main.bundle.js:5842:1\n__webpack_require__@http://localhost:8080/main.bundle.js:64:30\n@webpack:///./src/app.js?:43:99\n./src/app.js@http://localhost:8080/main.bundle.js:5722:1\n__webpack_require__@http://localhost:8080/main.bundle.js:64:30\n@webpack:///./src/viewer.js?:20:15\n./src/viewer.js@http://localhost:8080/main.bundle.js:6262:1\n__webpack_require__@http://localhost:8080/main.bundle.js:64:30\n@webpack:///multi_(webpack)-dev-server/client?:2:18\n0@http://localhost:8080/main.bundle.js:6285:1\n__webpack_require__@http://localhost:8080/main.bundle.js:64:30\n@http://localhost:8080/main.bundle.js:199:18\n@http://localhost:8080/main.bundle.js:202:10\n".

This is the PDF document that causes this behaviour:
[2018.01.15.an_signed_original.pdf] (https://github.com/mozilla/pdf.js/files/3867845/2018.01.15.an_signed_original.pdf)

What might be the cause of this issue?

**Comment by Snuffleupagus** [comment] 2019-11-24 14:58
> `const pdf = new PDFDocument({ evaluatorOptions: { isEvalSupported: false, }, }, pdfArray); pdf.parseStartXRef(); pdf.parse();` I get

It looks like you're attempting to utilize code residing in the https://github.com/mozilla/pdf.js/tree/master/src/core directory *directly*, rather than using the actual API as found in https://github.com/mozilla/pdf.js/blob/master/src/display/api.js
Please note that this isn't generally advisable, for a couple of reasons:
 - Only the API itself will be officially supported, and changes in major/minor version numbers will *only* reflect changes to the official API.
 - The code in the `src/core/` directory is intended to run in a worker-thread for performance reasons, since parsing of PDF documents is often quite resource intensive.
 - The various files and interfaces in `src/core/` should be regarded as internal implementation details. Hence they are subject to change at *any* time, as needed, and there's simply no guarantee that classes/methods/functions will remain available and/or work as in previous PDF.js versions.

Hence if you're, as it seems, attempting to call https://github.com/mozilla/pdf.js/blob/827eb64b75f8d0c3b4203202a7cf15c7cbd2ce26/src/core/document.js#L370-L393 directly then you'll also need to handle any exceptions yourself. I'd suggest drawing inspiration from how the `src/core/worker.js` file implements this, please see https://github.com/mozilla/pdf.js/blob/827eb64b75f8d0c3b4203202a7cf15c7cbd2ce26/src/core/worker.js#L273-L317

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by markotaht** [comment] 2019-11-25 09:45
The reason im using the PDFDocument from the core, is that i need the access to the underlying structure, XREF, objects, trailer, root, etc. And through api I cant seem to find a way to get this data. Im using it to append data to the end of the pdf file.

**Comment by timvandermeij** [comment] 2019-11-25 21:22
This information is not exposed through the API yet, which makes this a duplicate of #4992.

**Closed by timvandermeij** 2019-11-25 21:22 UTC
Labels: 1-other
