### ISSUE TITLE
Ctrl+f not searching entire document

### ISSUE THREAD

**Issue by AlbertFaust** [mozilla/pdf.js#7067] opened 2016-03-06 21:37 UTC
When a large file is open and a (ctrl+f) search is performed, no matches are found in the parts of the pdf that have not been loaded yet. #2168 seems to have addressed a similar issue in 2012 but does not look like it has been implemented. 
Even a notification to say that the pdf has not been fully loaded may be helpful as I have searched files for a term, not found it and closed it only to find out that when I download it and search it the terms are further down in the file.

**Comment by Snuffleupagus** [comment] 2016-06-08 09:55
I cannot reproduce this, and with the information provided it's difficult to guess what the problem might be.
@AlbertFaust Please provide detailed steps to reproduce the issue (e.g. by using https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by timvandermeij** [comment] 2016-06-13 19:32
Closing as incomplete until the information requested above is provided.

**Closed by timvandermeij** 2016-06-13 19:32 UTC
Labels: 4-information-requested, 4-text-selection
