### ISSUE TITLE
scroll bar position doesn't render for pdfs in FF Dev Edition (FF 57) on mac

### ISSUE THREAD

**Issue by cartazio** [mozilla/pdf.js#9016] opened 2017-10-10 16:26 UTC
![screen shot 2017-10-10 at 12 23 13 pm](https://user-images.githubusercontent.com/4290/31398188-192fa38a-adb6-11e7-9b61-9895950a3e03.png)

for some reason the document position cursor / scroll bar position marker isn't rendering in any pdfs I view in FF 57 / dev edition on my mac OS high sierra machine (this seems to hold for every pdf i've looked at :( )

**Comment by timvandermeij** [comment] 2017-10-10 20:30
This looks like an upstream regression. Could you report it at Bugzilla?

**Comment by brendandahl** [comment] 2017-10-20 03:24
@cartazio I can't reproduce w/ ff 57 on macOS sierra. Did you have this issue before upgrading to high sierra?

**Comment by cartazio** [comment] 2017-10-20 11:37
Not that I’m aware of , no.  Did you test with the developer edition or a
vanilla 57 build ? I am have been using developer edition .

I didn’t report upstream yet cause I had a bad cold much of this past week.
I’ll see about figuring. Out butzilla later today.

**Comment by brendandahl** [comment] 2017-10-20 20:21
I tested with dev edition.

**Comment by Snuffleupagus** [comment] 2019-02-16 10:16
This looks entirely like a graphics/platform issue, which unfortunately cannot be fixed here; closing as INVALID since it's clearly an upstream bug?

**Closed** 2019-02-16 13:30 UTC
Labels: 1-viewer, 3-upstream, 4-firefox-specific
