### ISSUE TITLE
Math rendering distorted

### ISSUE THREAD

**Issue by andrenarchy** [mozilla/pdf.js#7276] opened 2016-04-30 08:57 UTC
#### PDF file
https://arxiv.org/pdf/1604.08580v1.pdf

#### Configuration:
- Web browser and its version: Chrome 50 and Firefox 46
- Operating system and its version: Ubuntu 16.04
- PDF.js version: 1.5.222
- Is an extension: No

#### Steps to reproduce the problem:
1. Open the PDF (page 5)
2. Zoom in/out

#### What is the expected behavior?

![screenshot from 2016-04-30 10-54-29](https://cloud.githubusercontent.com/assets/1874116/14934974/ef714218-0ec1-11e6-9db9-e98f9ccb6cf1.png)

#### What went wrong?
Math elements are rendered incorrectly (e.g., sums and parentheses):

![screenshot from 2016-04-30 10-50-29](https://cloud.githubusercontent.com/assets/1874116/14934980/02221950-0ec2-11e6-9634-920b5a31fcf3.png)

#### Link to a viewer
The issue can be reproduced with https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by timvandermeij** [comment] 2016-04-30 10:02
Closing as duplicate of #2594.

**Closed by timvandermeij** 2016-04-30 10:02 UTC
