### ISSUE TITLE
Unwanted gray horizontal line appears in document

### ISSUE THREAD

**Issue by gsampath127** [mozilla/pdf.js#6841] opened 2016-01-06 10:21 UTC
When the pdf document is opened with pdf.js , unwanted gray line appears in some pages .
This does not happens with native pdf viewers or adobe.
Please , suggest any solution for this.
Doc : http://hosted.rightprospectus.com/documents/Harbor/annual_report_equity.pdf (10th Page)
![image](https://cloud.githubusercontent.com/assets/12858790/12140336/18005c6c-b48d-11e5-8cff-3acd682ab639.png)

**Comment by Snuffleupagus** [comment] 2016-01-06 11:12
Will be fixed by PR #6796.

**Comment by gsampath127** [comment] 2016-01-07 10:03
Thanks for response!!
Still the issue Exists.
We have applied the fix mentioned in Decreased `Shadings.SMALL_NUMBER` #6796 .
Made Shadings.SMALL_NUMBER = 1e-2 to Shadings.SMALL_NUMBER = 1e-6.
We can not see Gray line at default zoom level , when we zoom the document s the gray line appears.
This is not happening in adobe or native pdf viewers.


Can you please provide permanent solution for this issue.

**Comment by gsampath127** [comment] 2016-01-07 10:53
Can you please describe the issue in detail? 
Do we know if there was anything unique about the PDF, that PDF.js could not resolve or is it something related to the zoom in level or any known issue?

**Comment by SamyCookie** [comment] 2016-01-07 11:26
As I can see, the gray line is a lot thiner for me now than before, and only for some zoom level. So there is a kind of improvement with this patch.
Maybe the last visible line is related to another bug, like #3331

**Comment by timvandermeij** [comment] 2016-01-07 12:58
Reopening for the line on other zoom levels.

**Comment by Snuffleupagus** [comment] 2016-01-07 13:10
I'm wondering if setting `Shadings.SMALL_NUMBER` to a constant value might be the issue here?
Do we perhaps need to make it dynamic, by taking the current transformation into account during rendering (i.e. would it be necessary to do handle the extend in `pattern_helper.js`), or could we maybe use the pattern size in some way?

**Comment by kvk123456** [comment] 2016-01-14 15:16
Could someone please tell us is there any fix for this? will this be fixed in next PDF.js release

**Comment by kvk123456** [comment] 2016-01-14 15:19
Please provide some suggestion to make the setting Shadings.SMALL_NUMBER to dynamic, To change it accordingly with zoom size.

**Comment by kvk123456** [comment] 2016-01-22 14:42
Hi Guys, any update on this issue? We are still facing the Grey line issue. We tried different values 1e-8, 1e-6 for the variable Shadings.SMALL_NUMBER. Still the Grey Line is shown in some or other zoom level. Please help us to solve this

**Comment by timvandermeij** [comment] 2016-01-22 20:36
We are not yet sure what is causing this. It is probably an issue that is unrelated to the small number.

**Comment by kvk123456** [comment] 2016-02-02 19:02
Hi Team, any one working on this issue? Could some one help us on this?

**Comment by kvk123456** [comment] 2016-02-02 19:04
Could you please check is there any property or settings of the PDF causing this issue

**Comment by yurydelendik** [comment] 2016-02-02 19:13
The last table is painted from three parts (second left-bottom rectangle is just  filled on the picture):

<img width="984" alt="screen shot 2016-02-02 at 1 11 25 pm" src="https://cloud.githubusercontent.com/assets/1523410/12760929/89e9b842-c9ae-11e5-8de0-9ce4a8201ae5.png">

And yes, the line comes from gradient that used to fill this small rectangle. Question: why gradient?

**Comment by kvk123456** [comment] 2016-02-02 19:28
But this line is not visible when we open the PDF directly. Why only PDF.js showing this?

**Comment by kvk123456** [comment] 2016-02-02 19:32
Also could you please suggest if any settings in the PDF can fix this issue

**Comment by yurydelendik** [comment] 2016-02-02 19:34
> Why only PDF.js showing this?

Here is screenshot of Mac OSX Preview:

![Uploading Screen Shot 2016-02-02 at 1.33.03 PM.png…]()

It depends on graphics backend used, e.g. I cannot see this gray line in PDF.js on Max OSX Firefox.

**Comment by kvk123456** [comment] 2016-02-02 19:38
Yes a light grey line is visible in this if you zoom the image and if you try different zoom levels it will be visible clearly in some zoom level. Thats how it happens in windows

![image](https://cloud.githubusercontent.com/assets/13853369/12761849/a0144ad6-c9ba-11e5-97bd-14b1c3db20a4.png)

**Comment by yurydelendik** [comment] 2016-02-02 19:41
So it's not "only PDF.js" as you stated then?

**Comment by kvk123456** [comment] 2016-02-02 19:51
Sorry yurydelendik, when i open the PDF directly in windows using Native PDF, there is no grey line at all. But when i open using PDF.js in IE/Chrome i am seeing this in some zoom level

**Comment by yurydelendik** [comment] 2016-02-02 19:56
@kvk123456  That's how PDF.js interprets draw operations in the PDFs. Some PDF viewer might do some operations in hiding defects, some don't. By reading the operations in your PDF you keep that to the chance that PDF viewer might hide that defect. (It's better if the table was just painted as a rectangle, and not a a gradient where the same color is used)

**Comment by Snuffleupagus** [comment] 2021-05-29 12:18
> Doc : http://hosted.rightprospectus.com/documents/Harbor/annual_report_equity.pdf (10th Page)

That document has apparently been changed since this issue was first opened, given that it no longer agrees with the screen-shots posted in this issue (which is why we always suggest *attaching* files, rather than linking them).

Furthermore, based on the previous comments, this was apparently *mostly* fixed by PR #6843 and the very small remaining issue (according to the screen-shots) seem to be caused by the PDF document *itself* being poorly generated; note e.g. https://github.com/mozilla/pdf.js/issues/6841#issuecomment-178765565 and https://github.com/mozilla/pdf.js/issues/6841#issuecomment-178777582.

All-in-all, it doesn't really make sense to keep this issue open any longer.

**Closed by Snuffleupagus** 2021-05-29 12:18 UTC
Labels: 2-image-quality
