### ISSUE TITLE
Uncaught SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by st4086** [mozilla/pdf.js#8265] opened 2017-04-10 18:31 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome 56.0.2924.87
- Operating system and its version: Windows 10
- PDF.js version: 1.6.210
- Is an extension: no

Steps to reproduce the problem:
1. download the pdf.js and include it into a .net project
2. threw "Uncaught SyntaxError: Unexpected token (" while loading the pdf.js file

What is the expected behavior? (add screenshot)
should not throw exception 

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/3535605/24876612/315601b2-1de1-11e7-8baa-00262c4d3e97.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2017-04-10 20:23
I cannot reproduce this using the regular viewer at https://mozilla.github.io/pdf.js/web/viewer.html (most recent version). There is most likely a problem when you included it in the .Net project. Since no example to reproduce is provided, I'm closing this issue as incomplete.

**Closed by timvandermeij** 2017-04-10 20:23 UTC
