### ISSUE TITLE
The TextLayer sometimes becomes visible when printing

### ISSUE THREAD

**Issue by waddlesplash** [mozilla/pdf.js#5831] opened 2015-03-12 01:02 UTC
Reported by `bwalker` in IRC, [this pdf](http://petrucci.mus.auth.gr/imglnks/usimg/f/fb/IMSLP261415-PMLP127088-IMSLP207324-WIMA.6cd5-BWV4_Haps.pdf)'s textLayer sometimes appears in the printed version (page 8 for him and for me).

I've seen this before on some PDFs like [this one](http://ocw.mit.edu/courses/mathematics/18-01sc-single-variable-calculus-fall-2010/unit-4-techniques-of-integration/part-a-trigonometric-powers-trigonometric-substitution-and-completing-the-square/problem-set-9/MIT18_01SC_pset5prb.pdf) (which also happens to cause "Error occurred while printing" about 50% of the time), but nothing 100% reproducible like the above.

(Happens for me using a HP LaserJet, and "Microsoft XPS Document Writer" printers.)

Win8.1, FF 36.0.1, PDFjs 1.0.1194.

**Comment by waddlesplash** [comment] 2015-03-12 01:12
Hmm, it appears my initial analysis was wrong. Somehow the font suddenly changes from one page to the next...? That doesn't make much sense.

**Comment by waddlesplash** [comment] 2015-03-12 01:13
*@waddlesplash silently wonders if @Snuffleupagus will one day in a fit of rage scrap canvas-based text rendering and just use freetype2.js for everything.*

**Comment by Snuffleupagus** [comment] 2015-03-12 09:14
I'm assuming that this issue is related to the `CLEANUP_TIMEOUT` and thus most likely a duplicate of issues such as #5006, #5058 and #5279.

One way to improve the printing experience *might* be to not actually use the canvas back-end, but use SVG instead, Unfortunately the SVG back-end isn't yet feature complete, and I don't think anyone is currently working on it, but the [SVG viewer lives here](https://github.com/mozilla/pdf.js/tree/master/examples/svgviewer).

PS. @waddlesplash From reading IRC scrollback, it appears that you had trouble getting `#textLayer=visible` to work. Please note that for various reasons we've disabled the debugging hash parameters by default, see [Debugging PDF.js](https://github.com/mozilla/pdf.js/wiki/Debugging-pdf.js) for instructions on activating them.

**Comment by waddlesplash** [comment] 2015-03-12 13:40
> PS. @waddlesplash From reading IRC scrollback, it appears that you had trouble getting #textLayer=visible to work.

I did, but I just gave up and opened the browser console and made the textLayer visible that way.

**Comment by Snuffleupagus** [comment] 2015-06-22 13:40
Closing as duplicate of issue #5006.

**Closed by Snuffleupagus** 2015-06-22 13:40 UTC
Labels: 4-printing
