### ISSUE TITLE
Windows 11 Issues

### ISSUE THREAD

**Issue by icechat** [mozilla/pdf.js#15700] opened 2022-11-15 23:36 UTC
Windows 11 Home 64bit 22H2 OS Build 22621.819
Chrome 107.0.5304.107
Microsoft Edge 107.0.1418.42 

Using the examples at https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples

The HelloWorld example works but not the Previous/Next jsFiddle example, the pdf is very distorted, unreadable.

**Comment by Snuffleupagus** [comment] 2022-11-16 08:24
Duplicate of #14641, which is a best guess given the lack of screen-shots illustrating what you mean.

**Closed by Snuffleupagus** 2022-11-16 08:24 UTC
