### ISSUE TITLE
Firefox - PDFs in SharePoint or OneDrive not rendering - screen flashes then goes blank

### ISSUE THREAD

**Issue by AgileHandover** [mozilla/pdf.js#15227] opened 2022-07-27 00:42 UTC
Attach (recommended) or Link to PDF file here: https://agilehandovercom-my.sharepoint.com/:b:/g/personal/jeff_nolan_agilehandover_com/EfAOWu_OwT5HsAzSIKXYsDEBCSx05xBxgNhd_E62cgzGQg?e=BuTkXq

Both SharePoint and OneDrive display the same error - The above link is one of the bad files I put in OneDrive for you - if opened with FireFox it does not render properly. If opened in Chrome or Edge - it works fine.

Configuration:
- Web browser and its version: FireFox 103.0 (64-bit)
- Operating system and its version: Windows 10 Enterprise version 20H2
- PDF.js version: PDF.js v2.15.129 (build: be2dfe45f)
        -  according to error log... included below
- Is a browser extension: no

Steps to reproduce the problem:
1. Open Sharepoint or OneDrive online
1. Click on PDf file to open from Sharepoint ( both the preview and open options do not render properly ) 
2. The file opens - shows for a split second - then flashes - then goes away leaving a blank screen.

What is the expected behavior? for the file to render properly and not go away

What went wrong? The file does not render at all. Some files render partially. Overall - most customer files do not work.

Here are all the error codes that I got from the DOM Inspector:

An error occurred while rendering the page.
PDF.js v2.15.129 (build: be2dfe45f)
Message: 
Stack: putBinaryImageData@resource://pdf.js/build/pdf.js:5920:11
paintInlineImageXObject@resource://pdf.js/build/pdf.js:7857:25
paintImageXObject@resource://pdf.js/build/pdf.js:7808:10
executeOperatorList@resource://pdf.js/build/pdf.js:6338:20
_next@resource://pdf.js/build/pdf.js:3365:37
__webpack_modules__</_scheduleNext/<@resource://pdf.js/build/pdf.js:3353:14
[viewer.js:1183:15](resource://pdf.js/web/viewer.js)
renderView: "[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://pdf.js/build/pdf.js :: putBinaryImageData :: line 5920"  data: no]" [viewer.js:7796:19](resource://pdf.js/web/viewer.js)
    renderView resource://pdf.js/web/viewer.js:7796
An error occurred while rendering the page.
PDF.js v2.15.129 (build: be2dfe45f)
Message: 
Stack: putBinaryImageData@resource://pdf.js/build/pdf.js:5920:11
paintInlineImageXObject@resource://pdf.js/build/pdf.js:7857:25
paintImageXObject@resource://pdf.js/build/pdf.js:7808:10
executeOperatorList@resource://pdf.js/build/pdf.js:6338:20
_next@resource://pdf.js/build/pdf.js:3365:37
__webpack_modules__</_scheduleNext/<@resource://pdf.js/build/pdf.js:3353:14
FrameRequestCallback*_scheduleNext@resource://pdf.js/build/pdf.js:3352:14
renderContinueCallback@resource://pdf.js/web/viewer.js:12158:9
__webpack_modules__</paintOnCanvas/renderTask.onContinue@resource://pdf.js/web/viewer.js:12350:16
_continue@resource://pdf.js/build/pdf.js:3344:17
operatorListChanged@resource://pdf.js/build/pdf.js:3333:10
_renderPageChunk@resource://pdf.js/build/pdf.js:2046:26
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2085:14
[viewer.js:1183:15](resource://pdf.js/web/viewer.js)
renderView: "[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://pdf.js/build/pdf.js :: putBinaryImageData :: line 5920"  data: no]" [viewer.js:7796:19](resource://pdf.js/web/viewer.js)
    renderView resource://pdf.js/web/viewer.js:7796
    (Async: FrameRequestCallback)
    _scheduleNext resource://pdf.js/build/pdf.js:3352
    renderContinueCallback resource://pdf.js/web/viewer.js:12158
    onContinue resource://pdf.js/web/viewer.js:12350
    _continue resource://pdf.js/build/pdf.js:3344
    operatorListChanged resource://pdf.js/build/pdf.js:3333
    _renderPageChunk resource://pdf.js/build/pdf.js:2046
    pump resource://pdf.js/build/pdf.js:2085

**Comment by calixteman** [comment] 2022-07-27 07:56
The pdf contains an image 12000x16430 and we're failing in allocation a canvas for it.

**Comment by calixteman** [comment] 2022-07-27 07:57
Duplicate of #12307.

**Closed by calixteman** 2022-07-27 07:57 UTC

**Comment by Snuffleupagus** [comment] 2022-07-27 08:00
Note, this is *actually* a duplicate of #6741 (since a /CCITTFaxDecode stream is involved).

**Comment by calixteman** [comment] 2022-07-27 08:04
Isn't it only a matter of image size at the end ?

**Comment by Snuffleupagus** [comment] 2022-07-27 08:13
> Isn't it only a matter of image size at the end ?

Yes, that's the basic issue here.
However the vast majority of these issues concern /CCITTFaxDecode images in particular, hence why I figured that it cannot hurt to keep track of that.

**Comment by AgileHandover** [comment] 2022-07-27 12:19
Does 'Closed' mean you all are going to fix it? Or should I submit this same thing directly to Firefox support?? Should I tell our customers using Firefox / Sharepoint online -- to switch to Chrome - or that this is going to be fixed and to wait for new release? - Thanks

**Comment by marco-c** [comment] 2022-07-27 12:35
@AgileHandover this was closed as a duplicate because the same issue was already reported, it is in our plans to fix this hopefully soon.

**Comment by AgileHandover** [comment] 2023-05-26 18:03
This appears to be happening again, but now it is happening in Chrome, Edge, and Firefox. Overview - file shows for a second then disappears. Here is a link to a testing file -> https://hhmionline-my.sharepoint.com/:b:/g/personal/nolanj2_hhmi_org/EVhf6nEjvWtJl37eZp7HwLoBYdxZmEz_2fATTfXuQ4dQOQ?e=UTJ6QE
