### ISSUE TITLE
[Bug]: Conditional radio buttons stay hidden

### ISSUE THREAD

**Issue by theodoor** [mozilla/pdf.js#18913] opened 2024-10-17 11:16 UTC
### Attach (recommended) or Link to PDF file

https://justis.nl/sites/default/files/2022-12/Aanvraagformulier%20Verklaring%20Omtrent%20het%20Gedrag%20%28VOG%29%20niet%20ingezetenen.pdf

### Web browser and its version

Firefox 132

### Operating system and its version

Windows 11

### PDF.js version

4.7.18 

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the PDF
2. Click the first radio button of question 2.4

### What is the expected behavior?

The radio buttons of question 2.4a should become visible

![image](https://github.com/user-attachments/assets/55f32bd9-1a48-4582-b327-8a7c7a6ca030)

### What went wrong?

Only the first radio button of question 2.4a becomes visible. 

![image](https://github.com/user-attachments/assets/9955a134-657b-4279-b2d7-1fa29abb4e7c)

### Additional context

https://bugzilla.mozilla.org/show_bug.cgi?id=1922766 was filed for this issue.

**Comment by Snuffleupagus** [comment] 2024-10-17 11:42
Possibly a duplicate of issue #18906.

**Closed** 2024-10-17 18:21 UTC
Labels: form-js
