### ISSUE TITLE
Carlito font rendering isn’t correct with pdf.js

### ISSUE THREAD

**Issue by CheckMatt** [mozilla/pdf.js#9601] opened 2018-03-23 16:45 UTC
Attach (recommended) or Link to PDF file here: http://www.ligue-ara-echecs.fr/wp-content/uploads/2018/03/Convocation-CoDir-31-03-18.pdf

Configuration:
- Web browser and its version: Firefox 59.0.1
- Operating system and its version: Fedora 27 (same thing on Windows)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the file at the link above in Firefox with PDF.js.
2. The font rendering is not correct on Firefox but it's working on Chromium or with [Evince](https://wiki.gnome.org/Apps/Evince)

What is the expected behavior? (add screenshot)
The behavior expected is what Chromium do :-) !
![capture d ecran de 2018-03-23 17-43-41](https://user-images.githubusercontent.com/2353766/37842197-c1bcfffc-2ec1-11e8-9e09-c2517954ddd1.png)

What went wrong? (add screenshot)
![capture d ecran de 2018-03-23 17-42-23](https://user-images.githubusercontent.com/2353766/37842136-985c8754-2ec1-11e8-9624-077027dfa399.png)

Thanks for your help !

**Comment by Snuffleupagus** [comment] 2018-03-23 16:59
This looks like a duplicate of issue #9458, which was fixed by PR #9460.

**Comment by timvandermeij** [comment] 2018-03-23 22:08
Yes, this is fixed if you open the file with the latest viewer at https://mozilla.github.io/pdf.js/web/viewer.html.

**Closed by timvandermeij** 2018-03-23 22:08 UTC

**Comment by CheckMatt** [comment] 2018-03-24 09:42
Thanks for your answers. When will this last version of pdf.js be integrated in Firefox ?
