### ISSUE TITLE
Word Div created for every character instead of word

### ISSUE THREAD

**Issue by sharanmunyal** [mozilla/pdf.js#7224] opened 2016-04-19 22:11 UTC
Link to PDF file (or attach file here):
[Tutorial of React.pdf](https://github.com/mozilla/pdf.js/files/226899/Tutorial.of.React.pdf)

Configuration:
- Web browser and its version: Chrome Version 50.0.2661.75 (64-bit)
- Operating system and its version: Mac OSX 10.11.4
- PDF.js version: 1.4.258
- Is an extension: No

Steps to reproduce the problem:
1. Upload the file attached to the version mentioned above
2. Inspect the DOM and you will see word Divs created for every character instead of word

What is the expected behavior? (add screenshot)
Word Div should be created for every word or couple of words

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Tested this behavior here http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2016-04-20 10:43
This is most likely a duplicate of issue #4626, see the https://github.com/mozilla/pdf.js/issues/4626#issuecomment-154582527 in particular.

**Closed** 2021-04-30 18:39 UTC
Labels: 4-text-selection
