### ISSUE TITLE
on /PageMode /FullScreen again

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#13974] opened 2021-09-04 18:22 UTC
[This issue was already reported in #9159. I report again to ask for another approach.]

> Attach (recommended) or Link to PDF file here:

[Uncompressed PDF document with `/PageMode /FullScreen`](https://github.com/mozilla/pdf.js/files/7110298/full-screen.pdf).

The document contains the following code:

```
19 0 obj
<<
  /Type /Catalog
  [...]
  /PageMode /FullScreen
  /Version /1.7
>>
endobj
```

@Snuffleupagus [replied to the original issue](https://github.com/mozilla/pdf.js/issues/9159#issuecomment-345454922) with this information:

```
+ * Converts API PageMode values to the format used by `PDFSidebar`.
+ * NOTE: There's also a "FullScreen" parameter which is not possible to support,
+ *       since the Fullscreen API used in browsers requires that entering
+ *       fullscreen mode only occurs as a result of a user-initiated event.
```

At least the reader version of _Acrobat_ (which can be considered a _de facto_ standard for PDF) asks the user if fullscreen is allowed or not for the document.

If PDF.js asks for permission before going fullscreen, `/PageMode /FullScreen` could be implemented in PDF.js (including the proper warning message to the user).

Many thanks for your help.

**Comment by Snuffleupagus** [comment] 2021-09-04 19:23
> If PDF.js asks for permission before going fullscreen, `/PageMode /FullScreen` could be implemented in PDF.js (including the proper warning message to the user).

Not only would that require a implementing/maintain a bunch of code for something that's arguably *very much* an edge-case feature, the "ask for permission"-part would likely require a dialog-box (since I cannot imagine how it'd work otherwise) which would most likely end up annoying *a significant portion* of all users (since they'd need to dismiss the dialog to "get to" the document).

All-in-all, closing as WONTFIX (or perhaps a just duplicate of #9159).

**Closed by Snuffleupagus** 2021-09-04 19:23 UTC
