### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by WXY8888** [mozilla/pdf.js#18695] opened 2024-09-05 09:24 UTC
### Attach (recommended) or Link to PDF file

Typed
![Snipaste_2024-09-05_17-18-00](https://github.com/user-attachments/assets/5ccee9eb-3eee-4552-ac5d-7c9f917f094d)
![Snipaste_2024-09-05_17-17-39](https://github.com/user-attachments/assets/d9a8437a-8998-4dba-b04e-2046c5341884)to the file. Online previews can be displayed

### Web browser and its version

edge  126.0.2592.113

### Operating system and its version

windows 10 22H2

### PDF.js version

4.6.82

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the pdfjs viewer and enter the Chinese font
2. Save the document and open the pdf file you just saved using the edge browser

### What is the expected behavior?

Enter the Chinese font, save and download the print file

### What went wrong?

输入中文字体的中文字体无法保存

**Comment by Snuffleupagus** [comment] 2024-09-05 09:27
Duplicate of #15769

**Closed by Snuffleupagus** 2024-09-05 09:27 UTC

**Comment by Snuffleupagus** [comment] 2024-09-05 09:34
*For future reference:* Please take more care when reporting bugs, since there's a number of "issues" with this.
 - No meaningful issue title was provided.
 - A bunch of unrelated information under the `Attach (recommended) or Link to PDF file`-heading. That context belongs under *other* heading further down in the template.
 - Not enough details under the `Steps to reproduce the problem`-heading, since someone that doesn't know Chinese cannot easily write a text-string with those characters.
 - Non-English text under the `What went wrong?`-heading.

**Comment by WXY8888** [comment] 2024-09-05 09:38
edge does not display the typed Chinese font, but firefox can display it normally

**Comment by WXY8888** [comment] 2024-09-05 09:43
[compressed.tracemonkey-pldi-09 (3).pdf](https://github.com/user-attachments/files/16887303/compressed.tracemonkey-pldi-09.3.pdf)
