### ISSUE TITLE
Softhyphen is treating as normal hyphen 

### ISSUE THREAD

**Issue by a7vickey** [mozilla/pdf.js#13950] opened 2021-08-31 06:28 UTC
Attach (recommended) or Link to PDF file here:

Configuration:

Web browser and its version: Version 92.0.4515.159 (Official Build) (64-bit)

Operating system and its version: Windows windows 8

PDF.js version:
"betaVersion": "2.10.377",
"stableVersion": "2.9.359",
"baseVersion": "156762c482a75261e631948168a65a8adb82f21a",
"versionPrefix": "2.11."

Is a browser extension:

Steps to reproduce the problem:

Refer the attached image, few soft hyphens are there in the file. When we are copying content using Acrobat professional it is treating them as soft hyphen and text only copying where as while copying trhough pdf.js, it is treating them as normal hyphen and additional hyphen is coming. Could you please check and give the option to avoid soft hyphen. Also confirm that how will you differentiate hard hyphen and soft hyphen?

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![hyphen](https://user-images.githubusercontent.com/7369163/131452853-d30244ed-8315-4a64-9e27-805a182a6732.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-08-31 07:51
Duplicate of #13947; please don't open a new and equally incomplete issue since crucial parts of the required information is still missing.

**Closed by Snuffleupagus** 2021-08-31 07:51 UTC
