### ISSUE TITLE
why npm install encounter a mistake? How can i fix this problem?

### ISSUE THREAD

**Issue by cgsthtm** [mozilla/pdf.js#16189] opened 2023-03-22 03:48 UTC
D:\MyStudy\pdf.js>node --version
v18.14.2

D:\MyStudy\pdf.js>npm --version
9.5.1

D:\MyStudy\pdf.js>npx --version
9.5.1

D:\MyStudy\pdf.js>gulp --version
CLI version: 2.3.0
Local version: Unknown

D:\MyStudy\pdf.js>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-plugin-mozilla@3.0.1
npm ERR! Found: eslint-plugin-prettier@4.2.1
npm ERR! node_modules/eslint-plugin-prettier
npm ERR!   dev eslint-plugin-prettier@"^4.2.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-prettier@"^3.0.0" from eslint-plugin-mozilla@3.0.1
npm ERR! node_modules/eslint-plugin-mozilla
npm ERR!   dev eslint-plugin-mozilla@"^3.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint-plugin-prettier@3.4.1
npm ERR! node_modules/eslint-plugin-prettier
npm ERR!   peer eslint-plugin-prettier@"^3.0.0" from eslint-plugin-mozilla@3.0.1
npm ERR!   node_modules/eslint-plugin-mozilla
npm ERR!     dev eslint-plugin-mozilla@"^3.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-03-22T03_44_12_226Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-03-22T03_44_12_226Z-debug-0.log

D:\MyStudy\pdf.js>

------------------------------------------------------------------------------------------------------
2023-03-22T03_44_12_226Z-eresolve-report.txt
'Log files:
C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-03-22T03_44_12_226Z-debug-0.log

-# npm resolution error report

While resolving: eslint-plugin-mozilla@3.0.1
Found: eslint-plugin-prettier@4.2.1
node_modules/eslint-plugin-prettier
  dev eslint-plugin-prettier@"^4.2.1" from the root project

Could not resolve dependency:
peer eslint-plugin-prettier@"^3.0.0" from eslint-plugin-mozilla@3.0.1
node_modules/eslint-plugin-mozilla
  dev eslint-plugin-mozilla@"^3.0.1" from the root project

Conflicting peer dependency: eslint-plugin-prettier@3.4.1
node_modules/eslint-plugin-prettier
  peer eslint-plugin-prettier@"^3.0.0" from eslint-plugin-mozilla@3.0.1
  node_modules/eslint-plugin-mozilla
    dev eslint-plugin-mozilla@"^3.0.1" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

--------------------------------------------------------------------------------------------
2023-03-22T03_44_12_226Z-debug-0.log
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@9.5.1
2 info using node@v18.14.2
3 timing npm:load:whichnode Completed in 19ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:D:\MyStudy\pdf.js\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\Administrator\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\Administrator\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 2ms
16 timing config:load Completed in 14ms
17 timing npm:load:configload Completed in 14ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install
21 verbose argv "install"
22 timing npm:load:setTitle Completed in 9ms
23 timing config:load:flatten Completed in 8ms
24 timing npm:load:display Completed in 9ms
25 verbose logfile logs-max:10 dir:C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-03-22T03_44_12_226Z-
26 verbose logfile C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-03-22T03_44_12_226Z-debug-0.log
27 timing npm:load:logFile Completed in 11ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 1ms
30 timing npm:load Completed in 65ms
31 timing arborist:ctor Completed in 2ms
32 silly logfile start cleaning logs, removing 7 files
33 silly logfile error removing log file C:/Users/Administrator/AppData/Local/npm-cache/_logs/2023-03-20T00_43_49_479Z-debug-0.log [Error: EPERM: operation not permitted, lstat 'C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-03-20T00_43_49_479Z-debug-0.log'] {
33 silly logfile   errno: -4048,
33 silly logfile   code: 'EPERM',
33 silly logfile   syscall: 'lstat',
33 silly logfile   path: 'C:\\Users\\Administrator\\AppData\\Local\\npm-cache\\_logs\\2023-03-20T00_43_49_479Z-debug-0.log'
33 silly logfile }
34 timing idealTree:init Completed in 2222ms
35 timing idealTree:userRequests Completed in 0ms
36 silly idealTree buildDeps
37 timing idealTree:#root Completed in 1ms
38 silly fetch manifest eslint-plugin-prettier@^3.0.0
39 silly logfile done cleaning log files
40 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-prettier 5763ms (cache revalidated)
41 silly fetch manifest eslint@^7.23.0 || ^8.0.0
42 http fetch GET 200 https://registry.npmjs.org/eslint 200ms (cache revalidated)
43 silly fetch manifest prettier@^1.19.1
44 http fetch GET 200 https://registry.npmjs.org/prettier 197ms (cache revalidated)
45 timing idealTree Completed in 8425ms
46 timing command:install Completed in 8442ms
47 verbose stack Error: could not resolve
47 verbose stack     at PlaceDep.failPeerConflict (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:503:25)
47 verbose stack     at new PlaceDep (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:157:21)
47 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:943:31
47 verbose stack     at Array.map (<anonymous>)
47 verbose stack     at [buildDepStep] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:943:8)
47 verbose stack     at async Arborist.buildIdealTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:207:7)
47 verbose stack     at async Promise.all (index 1)
47 verbose stack     at async Arborist.reify (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:5)
47 verbose stack     at async Install.exec (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:146:5)
47 verbose stack     at async module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\cli.js:134:5)
48 verbose cwd D:\MyStudy\pdf.js
49 verbose Windows_NT 10.0.19045
50 verbose node v18.14.2
51 verbose npm  v9.5.1
52 error code ERESOLVE
53 error ERESOLVE could not resolve
54 error
55 error While resolving: [1meslint-plugin-mozilla[22m@[1m3.0.1[22m
55 error Found: [1meslint-plugin-prettier[22m@[1m4.2.1[22m[2m[22m
55 error [2mnode_modules/eslint-plugin-prettier[22m
55 error   [33mdev[39m [1meslint-plugin-prettier[22m@"[1m^4.2.1[22m" from the root project
55 error
55 error Could not resolve dependency:
55 error [35mpeer[39m [1meslint-plugin-prettier[22m@"[1m^3.0.0[22m" from [1meslint-plugin-mozilla[22m@[1m3.0.1[22m[2m[22m
55 error [2mnode_modules/eslint-plugin-mozilla[22m
55 error   [33mdev[39m [1meslint-plugin-mozilla[22m@"[1m^3.0.1[22m" from the root project
55 error
55 error Conflicting peer dependency: [1meslint-plugin-prettier[22m@[1m3.4.1[22m[2m[22m
55 error [2mnode_modules/eslint-plugin-prettier[22m
55 error   [35mpeer[39m [1meslint-plugin-prettier[22m@"[1m^3.0.0[22m" from [1meslint-plugin-mozilla[22m@[1m3.0.1[22m[2m[22m
55 error   [2mnode_modules/eslint-plugin-mozilla[22m
55 error     [33mdev[39m [1meslint-plugin-mozilla[22m@"[1m^3.0.1[22m" from the root project
55 error
55 error Fix the upstream dependency conflict, or retry
55 error this command with --force or --legacy-peer-deps
55 error to accept an incorrect (and potentially broken) dependency resolution.
56 error
56 error
56 error For a full report see:
56 error C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-03-22T03_44_12_226Z-eresolve-report.txt
57 verbose exit 1
58 timing npm Completed in 8603ms
59 verbose unfinished npm timer reify 1679456652349
60 verbose unfinished npm timer reify:loadTrees 1679456652357
61 verbose unfinished npm timer idealTree:buildDeps 1679456654582
62 verbose unfinished npm timer idealTree:node_modules/eslint-plugin-mozilla 1679456654585
63 verbose code 1
64 error A complete log of this run can be found in:
64 error     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-03-22T03_44_12_226Z-debug-0.log

**Comment by Snuffleupagus** [comment] 2023-03-22 07:22
Duplicate of #15429

**Closed by Snuffleupagus** 2023-03-22 07:22 UTC
