### ISSUE TITLE
pdf.js & Internet Download Manager

### ISSUE THREAD

**Issue by webitsa** [mozilla/pdf.js#9722] opened 2018-05-13 21:57 UTC
Please check these links on Firefox, Chrome & Edge while Internet Download Manager is installed on your system:
https://mozilla.github.io/pdf.js/web/viewer.html
http://mozilla.github.io/pdf.js/web/viewer.html

When you open second link that used "http", the IDM download window opens and browsers show:
PDF.js v2.0.493 (build: c5c06bf5)
Message: Unexpected server response (204) while retrieving PDF "http://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf".

But in "https" everything is ok.

Also  I saw this problem on PDF.js v1.9.426 (build: 2558a58d)

I use: Internet Download Manager 6.30 & windows 10 last update.

**Comment by Snuffleupagus** [comment] 2018-05-31 07:46
It sounds like "Internet Download Manager" (whatever software that is), is doing something that prevents PDF.js from working correctly. Hence this doesn't seem like an issue that PDF.js can fix (or should even attempt to), but the problem should rather be reported to the vendor of "Internet Download Manager".

**Comment by timvandermeij** [comment] 2018-05-31 21:01
I agree with the above, hence I'm closing this. It can be reopened if it can be proved that it's an issue caused by PDF.js and not by the download manager.

**Closed by timvandermeij** 2018-05-31 21:01 UTC
Labels: 1-other, 4-os-windows

**Comment by okechukwu0127** [comment] 2019-08-26 10:09
I there no way to detect if the user-brwoser have IDM extention installed with javascript and then flag to the user that 
 =>**PDF-JS will not work if you have IDM imstalled on your browser**

That would make a lot of sence, as i have seem Javascript detect adsBlocker...
