### ISSUE TITLE
Add view PDF button

### ISSUE THREAD

**Issue by xelan** [mozilla/pdf.js#12130] opened 2020-07-27 13:42 UTC
Configuration:
- Web browser and its version: Chrome 84.0.4147.89 64-bit
- Operating system and its version: Windows 10 1909
- PDF.js version: 2.6.150
- Is a browser extension: no

Steps to reproduce the problem:
1. Open a PDF with pdf.js viewer
2. You want to open the PDF using the browsers native PDF viewer (e.g. Chrome or Edge)
3. You need to download the PDF with the download button, open the downloads folder, drag in browser window again

What is the expected behavior?
3. An easy-to-use button (similar to the download button) allows to view the PDF directly (basically just a link to the current PDF url, displayed as toolbar button)

If others are interested in this feature as well, I'd be glad to submit a PR. The new feature would improve the document handling workflow e.g. with large PDFs, where the native viewers provide more features, but PDF.js is a nice and consistent user interface.

Thank you very much!

**Comment by Snuffleupagus** [comment] 2020-07-27 15:34
> You want to open the PDF using the browsers native PDF viewer (e.g. Chrome or Edge)

Note that with the built-in Firefox PDF Viewer, which is why this library exists in the first place, clicking the download button should (by default) offer the user a choice of either saving the file or open it with the system default PDF viewer.

> (basically just a link to the current PDF url, displayed as toolbar button)

Given that a PDF document can also be opened using binary data (e.g. in a `Uint8Array`), there's generally no guarantee that a link actually exists. Furthermore, in some cases even if a link exists, it may e.g. only be valid *once* and trying to access it again could thus fail. (All of this is why the download functionality, in the PDF.js default viewer, will attempt to offer the download as *binary* data whenever possible)
Hence the assumption that "just a link to the current PDF url" would work isn't generally correct, unfortunately.

All-in-all, I'm really not convinced that you want *yet another* "download"-button, since that'd also risk causing unnecessary user-confusion (in addition to the points above).

*Ninja-edit:* Duplicate of #2553

**Closed** 2020-07-27 21:35 UTC

**Comment by xelan** [comment] 2020-07-28 06:55
Ok, thank you for the quick feedback.
