### ISSUE TITLE
How to load all pages at once

### ISSUE THREAD

**Issue by heixincai** [mozilla/pdf.js#11244] opened 2019-10-15 12:29 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Chrome 76.0.3809.132
- Operating system and its version:windows 7
- PDF.js version:2.2.228
- Is a browser extension:

What went wrong? (add screenshot)
How to load all pages at once,Now the default load is 2 pages，Continue loading when the mouse scrolls to a page。
I want to load all pages at once.Thank you ~

**Comment by Snuffleupagus** [comment] 2019-10-15 12:32
Duplicate of #11179.

**Closed** 2019-10-15 21:23 UTC
