### ISSUE TITLE
PDF rendered using pdf.js shows square like garbage

### ISSUE THREAD

**Issue by subhashlg26** [mozilla/pdf.js#9279] opened 2017-12-14 16:57 UTC
[document_Redacted-rev-6751.pdf](https://github.com/mozilla/pdf.js/files/1560105/document_Redacted-rev-6751.pdf)
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 62.0.3202.94 (Official Build) (64-bit)
- Operating system and its version: Mac 10.12.6 (16G29)
- PDF.js version: pdfjs-1.9.426-dist
- Is a browser extension: No

Steps to reproduce the problem:
1. Use latest version pdf.js to render attached document.

What is the expected behavior? 
Text should have been displayed as it is directly opened from chrome.
![image](https://user-images.githubusercontent.com/657554/34004418-d9b3acce-e11d-11e7-929d-e7e2ea5a700f.png)

What went wrong? (add screenshot)
Square like garbage is displayed
![image](https://user-images.githubusercontent.com/657554/34004462-f7745894-e11d-11e7-86a6-8b0b85aa502d.png)

**Comment by Snuffleupagus** [comment] 2017-12-14 17:06
Possibly a duplicate of issue #9278.

**Comment by THausherr** [comment] 2017-12-15 10:10
"Warning: Ran out of space in font private use area."

Here's a reduced file with the same problem
[PDFJS-9279-reduced.pdf](https://github.com/mozilla/pdf.js/files/1562314/PDFJS-9279-reduced.pdf)

**Comment by timvandermeij** [comment] 2018-09-08 15:52
Fixed by #9340.

**Closed by timvandermeij** 2018-09-08 15:52 UTC
Labels: 4-font-conversion, 4-font-wont-sanitize
