### ISSUE TITLE
Feature request: Fit visible width 

### ISSUE THREAD

**Issue by sherwoodinc** [mozilla/pdf.js#8337] opened 2017-04-26 20:20 UTC
Hello!

Some pdf viewers (Okular and the TexStudio embedded PDF viewer, for instance) provide the option to trim the text white margins. This allows for bigger text in reduced screen size situations.

I request the same functionality in the default PDF.js viewer.
I couldn't find anything similar in the issue list, sorry if I am making a duplicate request.

Regards.

**Comment by timvandermeij** [comment] 2017-04-26 21:18
Closing since this is a duplicate of e.g., #2288 and #5880.

**Closed by timvandermeij** 2017-04-26 21:18 UTC
