### ISSUE TITLE
Time delay in rendering the pdf file which contains image

### ISSUE THREAD

**Issue by prmahima** [mozilla/pdf.js#14979] opened 2022-06-02 09:20 UTC
Attach (recommended) or Link to PDF file here:
The PDF file will be attached in the comment section shortly (within couple of hours of this issue creation).

Configuration:
- Web browser and its version: 
Microsoft Edge  Version 101.0.1210.47
Google Chrome Version 101.0.4951.67
- Operating system and its version: Windows (Not specific to OS)
- PDF.js version: 2.9.359
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the pdf file using pdf.js viewer.
2. Notice the time delay to render the pdf file.

What is the expected behavior? (add screenshot)
Better/acceptable performances (in terms of time) when rendering the pdf document on pdf.js viewer.

What went wrong? (add screenshot)
The document does display but with bad response time, between 13 and 25 seconds.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-06-02 09:48
> Attach (recommended) or Link to PDF file here:
> The PDF file will be attached in the comment section shortly (within couple of hours of this issue creation).

*Once more:* Please save everyone's time by actually following the ISSUE_TEMPLATE and *directly attaching* the PDF document to the initial post *immediately* when opening an issue.

Please keep in mind that this is an open-source *bug tracker*, frequented by many volunteers, rather than paid tech-support.

> PDF.js version: 2.9.359

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by Snuffleupagus** [comment] 2022-06-02 09:51
Duplicate of #12307

**Closed by Snuffleupagus** 2022-06-02 09:51 UTC
Labels: information-requested
