### ISSUE TITLE
esbuild bundler not working when using "import". Only works if I use "require"

### ISSUE THREAD

**Issue by GitMurf** [mozilla/pdf.js#14987] opened 2022-06-04 19:53 UTC
Configuration:
- Web browser and its version: **Electron app (newest version 19)**
- Operating system and its version: **Windows 11**
- PDF.js version: `"pdfjs-dist": "^2.14.305"`
- Is a browser extension: **No**

I am having trouble packaging `pdfjs` library with `esbuild` for my Electron TS project.

1) I have to set the `pdfjs` package as an `external` package option in the `esbuild config` so that it only adds a `require` reference to the library and include the pdfjs code packaged with my app in node modules instead of bundling the `pdfjs` code within my bundled `main.js` output file. This isn't that big of a deal but I am wondering if this can be solved.

2) The more important thing is that for some reason I cannot use `import` for pdfjs library. I have to use `require` otherwise the build will not load properly. Below I show what my package import/require statements look like in my TS file and what the corresponding output is with my bundler `esbuild`. Is this expected to only work with `require`?

```js
// In my main.ts
import pdfjs from 'pdfjs-dist/legacy/build/pdf';
// esbuild outputs to main.js (does NOT work)
var import_pdf = __toESM(require("pdfjs-dist/legacy/build/pdf"));
```

```js
// In my main.ts
const pdfjs = require('pdfjs-dist/legacy/build/pdf');
// esbuild outputs to main.js (this works)
var pdfjs = require("pdfjs-dist/legacy/build/pdf");
```

**Comment by Snuffleupagus** [comment] 2022-06-04 20:12
This is possibly a duplicate of issue #14915, but it's somewhat difficult to tell...

> I am having trouble packaging `pdfjs` library with `esbuild` for my Electron TS project.

Unfortunately this isn't really something that we can support here, since we don't really know the mentioned packages/frameworks here.
More generally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Closed** 2022-06-04 21:33 UTC
Labels: information-requested
