### ISSUE TITLE
Font rendering on Linux is "ugly" now

### ISSUE THREAD

**Issue by sknorr** [mozilla/pdf.js#7859] opened 2016-11-30 18:11 UTC
Link to PDF file (or attach file here): (any file)

Configuration:
===========

- Web browser and its version: Firefox 50
- Operating system and its version: openSUSE 13.2
- PDF.js version: built-in version of Firefox 50 + current Web version (sorry for the unhelpful answer but it seems I can't easily find out)
- Is an extension: no

Steps to reproduce the problem:
=========================

1. Open a PDF, for example  my earlier test document at: https://github.com/mozilla/pdf.js/files/109718/test.pdf
2. Zoom to 200% (just for the sake of comparability here -- the issue shows at all zoom levels though).

What is the expected behavior?
=========================

Behavior from the version of PDF.js that was built into Firefox 49 which blurred things a little more but kept character shapes intact.

**Screenshot from Evince (display used to be _similar_ in Firefox 49):**
![Screenshot from Evince](https://cloud.githubusercontent.com/assets/5476547/20764891/773bee66-b730-11e6-9541-af001b9c1f32.png)

What went wrong?
======

Notice that the character "a" seems (almost) open at the bottom, the "e" and "c" character similarly have very thin bottom strokes. Text looks overly "cleared up", much like the default settings on older Linux systems, or for a Windows analogy: overzealous ClearType.

**Screenshot from PDF.js in Firefox 50:**
![Screenshot from PDF.js](https://cloud.githubusercontent.com/assets/5476547/20764608/32eed76a-b72f-11e6-8d48-63c9f2b13d98.png)

I can also see this issue in the current Web version of PDF.js at https://mozilla.github.io/pdf.js/web/viewer.html .
I am ultimately not sure whether this is a PDF.js issue or maybe an issue with Firefox itself. I haven't noticed rendering differences in other parts of the Web, though.

**Comment by timvandermeij** [comment] 2016-11-30 19:51
I cannot reproduce this using Firefox 50, Arch Linux and the latest PDF.js development version. Since you mentioned it happened after the Firefox 50 update, it sounds like either an upstream Firefox issue or a local issue. Did you try running Firefox with a clean profile (to make sure that it's not because of some old custom setting)? Could you also post the Graphics section contents of `about:support`?

**Comment by Snuffleupagus** [comment] 2016-11-30 19:59
Since it sounds like this may be a Firefox issue (rather than a PDF.js issue), it'd would be most helpful if http://mozilla.github.io/mozregression/ was used to attempt to find out where this regressed, and report an upstream bug in https://bugzilla.mozilla.org once the offending changeset is found.

**Comment by sknorr** [comment] 2016-12-01 10:12
@timvandermeij 
1. New profile: does not help in my case.
2. about:support#graphics:

```
Features
Compositing	Basic
Asynchronous Pan/Zoom	none
WebGL Renderer	NVIDIA Corporation -- Quadro K620/PCIe/SSE2
WebGL2 Renderer	(no info)
Hardware H264 Decoding	No
Audio Backend	pulse
GPU #1
Active	        Yes
Description	NVIDIA Corporation -- Quadro K620/PCIe/SSE2
Vendor ID	NVIDIA Corporation
Device ID	Quadro K620/PCIe/SSE2
Driver Version	4.5.0 NVIDIA 367.57
Diagnostics
AzureCanvasAccelerated	0
AzureCanvasBackend	skia
AzureContentBackend	cairo
AzureFallbackCanvasBackend	none
CairoUseXRender	0
Decision Log
HW_COMPOSITING	      blocked by default: Acceleration blocked by platform
OPENGL_COMPOSITING    unavailable by default: Hardware compositing is disabled
```

@Snuffleupagus I had feared this would be some kind of Firefox issue. I quickly tried out mozregression, but it seems I can't reproduce this with the upstream builds at all. My colleagues also can't reproduce this. So, this might even be an incompatibility issue with FreeType or so.

Feel free to close, I guess.

**Comment by timvandermeij** [comment] 2016-12-01 13:37
Closing as this does not look like a PDF.js issue. If it turns out to be, feel free to let us know and we'll re-open.

**Closed by timvandermeij** 2016-12-01 13:37 UTC
Labels: 3-upstream, 4-os-linux
