### ISSUE TITLE
The pdf file displayed incorrectly

### ISSUE THREAD

**Issue by gsh434541340** [mozilla/pdf.js#11848] opened 2020-04-27 04:41 UTC
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/4537519/test.pdf)

Configuration:
- Web browser and its version: Chrome 80
- Operating system and its version: win10
- PDF.js version: 2.5.127
- Is a browser extension:

the source file 
![image](https://user-images.githubusercontent.com/11783376/80334367-97f91c00-8883-11ea-8501-37d98f313906.png)

the demo 
![image](https://user-images.githubusercontent.com/11783376/80334545-1d7ccc00-8884-11ea-9b0e-48ae057ff0ea.png)

**Comment by Snuffleupagus** [comment] 2020-04-27 08:03
Duplicate of #6741

**Closed** 2020-04-27 10:36 UTC
