### ISSUE TITLE
Disable scrolling in custom PDF Viewer

### ISSUE THREAD

**Issue by MFoxx** [mozilla/pdf.js#13826] opened 2021-07-31 10:53 UTC
We have a custom pdf viewer

`
const pdfViewerVar = new pdfjsViewer.PDFViewer({
					container: container,
					eventBus: eventBus,
					pdfLinkService,
					pdfFindController,
					useOnlyCssZoom: false,
					textLayerMode: 2
				});
`
with input that allows user to change page. But now if user changes page, it start scrolling to the page, is there an option, to skip the scroll, and just jump to the desired page ?

**Comment by timvandermeij** [comment] 2021-07-31 11:08
Looking at https://mozilla.github.io/pdf.js/web/viewer.html and changing the page, it immediately jumps to the page, and that's also what the viewer components do, so I doubt this behavior is caused by PDF.js itself; maybe another library does this scrolling effect? Without a runnable example, there is no way for us tell unfortunately, so until that's provided we'll have to close this.

**Closed by timvandermeij** 2021-07-31 11:08 UTC

**Comment by MFoxx** [comment] 2021-07-31 11:20
I don't belive it's caused by other library, because it's using PDFJS function scrollIntoView

**Comment by timvandermeij** [comment] 2021-07-31 11:27
The `scrollIntoView` function, see https://github.com/mozilla/pdf.js/blob/82660296d6fe6eb9d2bf4c944faefe97684e8799/web/ui_utils.js#L102-L138, also seems to change the position immediately, so there is no scrolling logic there too. If you have a runnable example we could take a look, but without it it's simply not possible to tell what's causing this. Try running the minimal examples in https://github.com/mozilla/pdf.js/tree/master/examples in isolation, outside of your custom viewer, and see if you can reproduce it then too.

**Comment by MFoxx** [comment] 2021-07-31 11:40
Allright, turns out it was caused by CSS property scroll-behaviour: smooth, set on PDFViewer
