### ISSUE TITLE
How to switch languages dynamically

### ISSUE THREAD

**Issue by edgeTurbo** [mozilla/pdf.js#15191] opened 2022-07-20 07:33 UTC
I have made a website that can switch between Chinese and English, how can I dynamically switch the button prompt language on the PDF through the user's choice of Chinese or English

**Comment by Snuffleupagus** [comment] 2022-07-20 07:45
Duplicate of e.g. #11829; which is a best guess given the complete lack of information required to make this issue actionable/valid.

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Closed by Snuffleupagus** 2022-07-20 07:45 UTC
