### ISSUE TITLE
Numbers and symbols not shown correctly in a certain document

### ISSUE THREAD

**Issue by OmarWKH** [mozilla/pdf.js#10541] opened 2019-02-11 14:15 UTC
Attach (recommended) or Link to PDF file here: 
[1Password for Teams White Paper.pdf](https://github.com/mozilla/pdf.js/files/2851160/1Password.for.Teams.White.Paper.pdf) ([original](https://1password.com/files/1Password%20for%20Teams%20White%20Paper.pdf))

Configuration:
- Web browser and its version: Firefox 65.0 (64-bit)
- Operating system and its version: Windows 10 Pro Version 1809 Build 17763.253
- PDF.js version: 2.1.97
- Is a browser extension: No

Steps to reproduce the problem:
1. Go to page 10 of the PDF
2. Look after the sentence "A Master Password with four such words will be one of" (this is one of several number and symbols that have the problem in this document).

What is the expected behavior? (add screenshot)
The number "18000<sup>4</sup>" is shown correctly.

Using SumatraPDF v3.1.2:
![image](https://user-images.githubusercontent.com/10570290/52566750-a17f9b00-2e1b-11e9-9628-e098dc779361.png)

What went wrong? (add screenshot)
The number is unreadable.

![image](https://user-images.githubusercontent.com/10570290/52568169-0be60a80-2e1f-11e9-8430-d3aa1d217b5b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Console log:
```
PDF f22bb023e2e92110a02d2bd381ef5d99 [1.5 XeTeX 0.99999 / LaTeX with hyperref] (PDF.js: 2.1.97) viewer.js:1179:7
Warning: Failed to load font "g_d0_f8": SyntaxError: An invalid or illegal string was specified pdf.js:525:5 
```

Adobe Acrobat Reader DC 2019.010.20069 shows numbers and symbols correctly but displays a warning message. The message pops up after interacting with the document (a few text selections or going to a page number). I'm not exactly sure what triggers it. The message is:
> "Cannot extract the embedded font 'VENLVK+FiraMath-Regular-Identity-H'. Some characters may no display or print correctly."

![image](https://user-images.githubusercontent.com/10570290/52568544-1c4ab500-2e20-11e9-9f75-3d65512b442e.png)

**Comment by Snuffleupagus** [comment] 2019-02-11 14:37
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1524888 (there's no need to track it twice).

**Closed** 2019-02-11 22:18 UTC
