### ISSUE TITLE
Error in mounted hook: "TypeError: pdfjs_dist_build_pdf__WEBPACK_IMPORTED_MODULE_0___default.a is undefined"

### ISSUE THREAD

**Issue by abhimanusharma** [mozilla/pdf.js#12449] opened 2020-10-05 11:46 UTC
I am trying to implement pdfjs with vue js.

```
import pdfjsLib from "pdfjs-dist/build/pdf";
import { PDFViewer } from "pdfjs-dist/web/pdf_viewer";
import "../../../node_modules/pdfjs-dist/web/pdf_viewer.css";

export default {
	created: function () {
		const url = process.env.MIX_API_URL+'stored_file1.pdf';
		pdfjsLib.getDocument(url).promise.then(pdfDoc_ => {
			pdfDoc = pdfDoc_;
			console.log(pdfDoc);
		});
	}
}
```

I am getting error

```
[Vue warn]: Error in mounted hook: "TypeError: pdfjs_dist_build_pdf__WEBPACK_IMPORTED_MODULE_0___default.a is undefined"

found in

---> <Pdf> at resources/js/components/WebViewer.vue
       <Fullscreen>
         <MdDialog> at src/components/MdDialog/MdDialog.vue
           <PdfViewerModal> at resources/js/pages/dashboard/reuseComponents/PdfViewerModal.vue
             <Documents> at resources/js/pages/dashboard/Documents.vue
               <DashboardLayout> at resources/js/pages/dashboard/Index.vue
                 <App> at resources/js/App.vue
                   <Root> app.js:216705:15
    warn http://localhost:3000//js/app.js:216705
    logError http://localhost:3000//js/app.js:217984
    globalHandleError http://localhost:3000//js/app.js:217979
    handleError http://localhost:3000//js/app.js:217939
    invokeWithErrorHandling http://localhost:3000//js/app.js:217960
    callHook http://localhost:3000//js/app.js:220255
    insert http://localhost:3000//js/app.js:219188
    invokeInsertHook http://localhost:3000//js/app.js:222397
    patch http://localhost:3000//js/app.js:222622
    _update http://localhost:3000//js/app.js:219979
    updateComponent http://localhost:3000//js/app.js:220102
    get http://localhost:3000//js/app.js:220513
    run http://localhost:3000//js/app.js:220599
    flushSchedulerQueue http://localhost:3000//js/app.js:220347
    nextTick http://localhost:3000//js/app.js:218085
    flushCallbacks http://localhost:3000//js/app.js:218007
    (Async: promise callback)
    timerFunc http://localhost:3000//js/app.js:218035
    nextTick http://localhost:3000//js/app.js:218096
    queueWatcher http://localhost:3000//js/app.js:220443
    update http://localhost:3000//js/app.js:220588
    notify http://localhost:3000//js/app.js:216822
    reactiveSetter http://localhost:3000//js/app.js:217147
    proxySetter http://localhost:3000//js/app.js:220682
    openPdfViewerDialog http://localhost:3000//js/app.js:28940
    click http://localhost:3000//js/app.js:167404
    invokeWithErrorHandling http://localhost:3000//js/app.js:217949
    invoker http://localhost:3000//js/app.js:218280
    _wrapper http://localhost:3000//js/app.js:223577
    (Async: EventListener.handleEvent)
    add$1 http://localhost:3000//js/app.js:223582
    updateListeners http://localhost:3000//js/app.js:218307
    updateDOMListeners http://localhost:3000//js/app.js:223601
    invokeCreateHooks http://localhost:3000//js/app.js:222085
    createElm http://localhost:3000//js/app.js:221956
    patch http://localhost:3000//js/app.js:222538
    _update http://localhost:3000//js/app.js:219974
    updateComponent http://localhost:3000//js/app.js:220102
    get http://localhost:3000//js/app.js:220513
    Watcher http://localhost:3000//js/app.js:220500
    mountComponent http://localhost:3000//js/app.js:220109
    $mount http://localhost:3000//js/app.js:225049
    $mount http://localhost:3000//js/app.js:227860
    init http://localhost:3000//js/app.js:219170
    createComponent http://localhost:3000//js/app.js:221981
    createElm http://localhost:3000//js/app.js:221930
    createChildren http://localhost:3000//js/app.js:222068
    createElm http://localhost:3000//js/app.js:221953
    createChildren http://localhost:3000//js/app.js:222068
    createElm http://localhost:3000//js/app.js:221953
    createChildren http://localhost:3000//js/app.js:222068
    createElm http://localhost:3000//js/app.js:221953
    patch http://localhost:3000//js/app.js:222538
    _update http://localhost:3000//js/app.js:219974
    updateComponent http://localhost:3000//js/app.js:220102
    get http://localhost:3000//js/app.js:220513
    Watcher http://localhost:3000//js/app.js:220500
    mountComponent http://localhost:3000//js/app.js:220109
    $mount http://localhost:3000//js/app.js:225049
    $mount http://localhost:3000//js/app.js:227860
```

**Comment by Snuffleupagus** [comment] 2020-10-05 11:56
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment] 2020-10-05 11:56
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately isn't actionable/valid.

Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by abhimanusharma** [comment] 2020-10-05 12:57
@Snuffleupagus I can understand that to understand the problem you require full document to how the problem have caused. 
The problem in my case is, I just did total of three steps.

1. `npm i pdfjs-dist`
2. Saved a pdf file in the public folder to access it via (https://www.mysite.com/my.pdf)
3. Put the above code as it is in my vue component (pdfViewer.vue)

Just wanted to console log the properties of pdfjsLib object.
(Using this for reference)[https://www.youtube.com/watch?v=ydCSSgwZjzs]

after building and reloading the webpage I am getting mentioned error in the console.

**Comment by Snuffleupagus** [comment] 2020-10-05 13:13
> The problem in my case is, I just did total of three steps.
> 
>     1. `npm i pdfjs-dist`
> 
>     2. Saved a pdf file in the public folder to access it via (https://www.mysite.com/my.pdf)
> 
>     3. Put the above code as it is in my vue component (pdfViewer.vue)

First of all, please keep in mind that people may not be familiar with certain frameworks (e.g. Vue.js in this case).
Secondly, having to *completely manually* try to reproduce something takes way too much time in general (what if every issue required that?). Also, please keep in mind that this isn't paid support, but volunteers helping out in their spare time.
Finally, without a *complete and runnable* example it's impossible to know if you're testing the *exact* same thing as the reporter (even more so when the entire ISSUE_TEMPLATE is missing).

Again, without an *easily runnable* example this issue will unfortunately be closed as INCOMPLETE.

**Comment by timvandermeij** [comment] 2020-10-05 20:37
The error message itself is not related to PDF.js per se, but it _seems_ to be something in the way you import it; refer to https://stackoverflow.com/questions/61388663/typeerror-react-webpack-imported-module-0-default-is-not-a-function. This might very well be something Vue-specific looking at https://www.google.com/search?q=__WEBPACK_IMPORTED_MODULE_0___default.a+vue, which unfortunately none of us is familiar with. Unless it's shown that this can be reproduced outside of Vue as well, this doesn't seem actionable here unfortunately.

**Closed by timvandermeij** 2020-10-05 20:37 UTC
