### ISSUE TITLE
Document print missaligned

### ISSUE THREAD

**Issue by Merlignux** [mozilla/pdf.js#13264] opened 2021-04-19 15:12 UTC
Configuration:
- Web browser and its version: Firefox 88
- Operating system and its version: Windows 10 20H2
- PDF.js version: the one shipped in Firefox 88
- Is a browser extension: No

Latest changes to the PDF printing dialog started to center a document Vertically and Horizontally (**when a document is smaller than the page where it is to be printed on**).
This is causing problems with POS receipt printers.

The thing is that, because the original document is - vertically - smaller (72 × 146 mm) than the paper sheet where it's going to be printed (80 x 297 mm)on, it is placed on the middle of the printing page. 
This results in the printer printing a huge margin on the top of the sheet.

Original Document:
![document](https://user-images.githubusercontent.com/8130393/115259097-7e528380-a129-11eb-9d54-e1b1a8f322e9.png)

Preview and actual Print:
![print_preview](https://user-images.githubusercontent.com/8130393/115259225-9924f800-a129-11eb-8565-9e78017a8abb.png)

Before, when it was aligned on top, this problem did not exist.
(It is not viable to set page sizes as the document size changes constantly)

**Comment by Snuffleupagus** [comment] 2021-04-19 15:24
Generally speaking, as mentioned previously, without the PDF file in question this (or any other issue) isn't really actionable/valid.

> Latest changes to the PDF printing dialog started to center a document Vertically and Horizontally (**when a document is smaller than the page where it is to be printed on**).

Without those changes, *a lot* of cases would be ever more broken; for example issue #13129 :-)

> (It is not viable to set page sizes as the document size changes constantly)

That's why the intention is to use CSS `@page { size }`-rules to automatically set correct page sizes, however that's not yet implemented in Firefox. For all intents and purposes, this is basically a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1697778#c17

**Comment by Merlignux** [comment] 2021-04-19 15:55
Thanks for reply @Snuffleupagus 

Well, as we dealing with receipt invoices i cannot, naturally, post one here :)
( unless someone signs a very loooong and boring no-discloser agreement and _bla bla bla_ - i think no-one wants that! )

Despite everything else I think the images explain the point of what's happening and _my_ other issue - #13129 was indeed fixed with this update.

But now, there's this one...
In our case scenario _horizontal align to center_ + _vertical align to top_ would be ideally - but i understand others may prefer other configurations and we can satisfy everyone

i really hope `@page{size} ` fixes this things...
@Snuffleupagus if you're sure this will get fixed by  `@page{size} ` i'm ok with closing this issue and keeping the garbage in the trashcan - there's no point in having duplicates.

(as a side note: chrome has this working - i don't know about 13129, however - by logic it should not be working there)

**Comment by Snuffleupagus** [comment] 2021-04-19 16:06
> Despite everything else I think the images explain the point of what's happening and _my_ other issue

That's sort of beside the point, since no actual debugging/testing can be done with just a screen-shot alone!

> In our case scenario _horizontal align to center_ + _vertical align to top_ would be ideally - but i understand others may prefer other configurations and we can't satisfy everyone

Yes, centering both horizontally *and* vertically is bound to give the best results in a *majority* of cases.

> if you're sure this will get fixed by `@page{size} ` i'm ok with closing this issue and keeping the garbage in the trashcan - there's no point in having duplicates.

Obviously none of this is actually implemented yet, but it *should* be possible to fix these kind of issues in PDF.js once `@page`-support arrives in Firefox; unfortunately we do not know when that might happen. 
However, without a test-case there's unfortunately not really much point in keeping a non-actionable issue open.

**Comment by Merlignux** [comment] 2021-04-20 11:11
> That's sort of beside the point, since no actual debugging/testing can be done with just a screen-shot alone!
>...
> However, without a test-case there's unfortunately not really much point in keeping a non-actionable issue open.

Ok, then to leave this open i've come up with test document that also does the trick (has the same problem):

[receipt simulation.pdf](https://github.com/mozilla/pdf.js/files/6342921/receipt.simulation.pdf)

In short: when the page where this document is to be printed on has - in this particular case - the dimensions 80 x 297 mm, this creates a margin on top that "should" not be there.

I understand this is expected considering the latest changes, but the bug should get fixed / reviewed after  `@page{size}` implementation

**Comment by maverick74** [comment] 2021-05-12 17:14
@Snuffleupagus 
is the `@page` you mention this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1647845

**Comment by Merlignux** [comment] 2021-07-01 10:36
Can someone, please, list which bugs this one depends on?

on Bugzilla it's been mentioned above bug 1697778 and i have found 1647849, 851441, 1717703 and another one closed 1647851.

Does this depends on them all or just some of them? Are there more?

I need to keep an eye on this as close as possible, as it's creating increasing problems inside the business and i have to report any updates on this regularly...

thank you

**Comment by maverick74** [comment] 2022-07-15 15:33
Is this related to

@page {size:**_auto_**} 

as specified in https://www.w3.org/TR/css-page-3/#valdef-page-size-auto ?

Or not related to "auto" specifically?

**Comment by Snuffleupagus** [comment] 2023-06-05 10:10
Given that `@page` support was implemented, for the *built-in* Firefox PDF Viewer, in PR #16241 we can probably close this now.

**Closed by Snuffleupagus** 2023-06-05 10:10 UTC
Labels: printing

**Comment by maverick74** [comment] 2023-06-05 10:47
Aligning the document top-left must have solved the OP problem because his problem started when pdf begun being centered.

This reverted that change so it's probably fixed
