### ISSUE TITLE
Uncaught Error: Cannot find module './pdf.worker.js'

### ISSUE THREAD

**Issue by Vingtoft** [mozilla/pdf.js#6960] opened 2016-02-08 13:00 UTC
Something is wrong when I initialize the system. I get the following error:
```
Uncaught Error: Cannot find module './pdf.worker.js'
```
It refers to pdf.js line 8310:

```
var fakeWorkerFilesLoader = useRequireEnsure ? (function (callback) {
  require.ensure([], function () {
    require('./pdf.worker.js'); // THIS LINE!!
    callback();
  });
}) : (typeof requirejs !== 'undefined') ? (function (callback) {
  requirejs(['pdfjs-dist/build/pdf.worker'], function (worker) {
    callback();
  });
}) : null;
```

If I change ``` require('./pdf.worker.js') ```to the absolute path to the pdf.worker.js then it works.

**Comment by yurydelendik** [comment] 2016-02-08 15:36
Please provide complete example and steps to reproduce the issue.

**Comment by yurydelendik** [comment] 2016-02-08 18:32
Duplicate of #6932 ?

**Comment by Vingtoft** [comment] 2016-02-09 08:34
Yes, it appears to be a duplicate of #6932. I'm using Electron as well.
Thank you for your help, I wish you a good day.

**Closed** 2016-02-09 20:28 UTC
Labels: 4-information-requested
