### ISSUE TITLE
Text selection is difficult on touchscreen mobile devices

### ISSUE THREAD

**Issue by ShevonKuan** [mozilla/pdf.js#17520] opened 2024-01-16 05:27 UTC
![image](https://github.com/mozilla/pdf.js/assets/49824574/754cbdf8-979b-4be0-b651-f4634e652e33)

As shown in the picture above, it is difficult for me to select text on iOS, and there is a big difference between the actual selection box and the display selection box.

**Comment by Snuffleupagus** [comment] 2024-01-16 09:18
Duplicate of #15691

---

*For future reference:* Please don't just delete/ignore the ISSUE_TEMPLATE when opening an issue.

**Closed by Snuffleupagus** 2024-01-16 09:18 UTC
