### ISSUE TITLE
PDF not loading in  load balancer server Error: Bad end offset in PDF.worker.js

### ISSUE THREAD

**Issue by shenbagaraj** [mozilla/pdf.js#7566] opened 2016-08-25 13:00 UTC
When i try to open the PDF in viewer getting the below error  
Bad end offset: 3163199  in pdf.worker.js
Attached the screen shot of the issue
![image](https://cloud.githubusercontent.com/assets/21241471/17969665/d6fd57ea-6af0-11e6-8c76-9c17c3db5d10.png)

and some times getting PDF.js v1.5.188 (build: 0e2d50f)
Message: Unexpected server response (403) while retrieving PDF

We are using the load balancer server(2 server to load the balance)
 
**Browser version:  Chrome 52.0.2743.116 m
 PDF.js version: pdfjs-1.5.188-dist**
Could you please help us in resolving this .
Please let me know if you need any further information.

**Comment by yurydelendik** [comment] 2016-08-25 15:43
If an HTTP server instructs that it can handle range requests, PDF.js is trying to use range requests. Looks like your load balancer servers cannot handle range requests, so the workaround will be to configure the servers to disable such functionality (e.g. don't return "Accept-Ranges: bytes"). PDF.js has the option to disable range requests, but that's created for diagnostics and to intended to mainstream use. Closing as answered.

**Closed by yurydelendik** 2016-08-25 15:43 UTC

**Comment by shenbagaraj** [comment] 2016-08-26 07:48
Hi Yurydelendik,
Thanks for your response. **the pdf is not loading only in chrome browser in our server**. Kindly help me. how to disable the Accept-Ranges?
In lower environment its working in all the browser.
**_Please find the below error and also attached the screen. its shows in ChunkedStreamManager_onReceiveData_**
In IE and firefox its o
Uncaught (in promise) Error: Bad end offset: 8312527
    at error (https://stagecd-diabetes-wellnessinpracticenetwork.snfems.com/Areas/GlobalComponents/js/Global/components/PDFViewer/build/pdf.worker.js:2314:9)
    at assert (https://stagecd-diabetes-wellnessinpracticenetwork.snfems.com/Areas/GlobalComponents/js/Global/components/PDFViewer/build/pdf.worker.js:2327:5)
    at Object.ChunkedStream_onReceiveData [as onReceiveData] (https://stagecd-diabetes-wellnessinpracticenetwork.snfems.com/Areas/GlobalComponents/js/Global/components/PDFViewer/build/pdf.worker.js:6086:7)
    at Object.ChunkedStreamManager_onReceiveData [as onReceiveData] (https://stagecd-diabetes-wellnessinpracticenetwork.snfems.com/Areas/GlobalComponents/js/Global/components/PDFViewer/build/pdf.worker.js:6495:21)
    at Object.<anonymous> (https://stagecd-diabetes-wellnessinpracticenetwork.snfems.com/Areas/GlobalComponents/js/Global/components/PDFViewer/build/pdf.worker.js:6348:14)
![image](https://cloud.githubusercontent.com/assets/21241471/17997717/f87d7506-6b8d-11e6-9b5c-08f8f61c238a.png)

**Comment by shenbagaraj** [comment] 2016-08-26 08:15
Hi Could you please Reopen this #7566 issue and provide me the fix.

**Comment by yurydelendik** [comment] 2016-08-26 13:17
@shenbagaraj there is not enough information provided to troubleshot the issue. Please provide access for public for your balancer servers to observe the issue.

**Comment by yurydelendik** [comment] 2016-08-26 13:23
> In IE and firefox its o

Every browser (it also depends on versions) behaves differently when range requests are enabled, e.g. Firefox continue loading file incrementally regardless failing range requests (not possible to do on other browsers yet).

**Comment by shenbagaraj** [comment] 2016-08-26 13:37
Thanks you very much 
PDF are loading after i disable the range in pdf.worker.js

>  this._disableRange = true; 

But now the pdf are loading after the complete progress bar ends :)

Is it possible to make my load balance accepts range ?
Could you  please share any url r document to setup that?

Thanks you very much in advance!

**Comment by yurydelendik** [comment] 2016-08-26 14:07
> Is it possible to make my load balance accepts range ?

You did not provide any information about "load balance". But I assume a web application/scripts you have does not properly configured to handle range requests.

**Comment by shenbagaraj** [comment] 2016-08-30 13:33
Hi,
Yes its web application. 
Please let me know what information you required on our servers.
how to check its properly configured or not?

**Comment by yurydelendik** [comment] 2016-08-30 14:25
> Please let me know what information you required on our servers.

Minimal example to reproduce the issue on any computer.

> how to check its properly configured or not?

The application reports 403 error -- you need to find out exact reason why your application is doing that, e.g. via looking at logs files, turning on debug mode, etc.
