### ISSUE TITLE
PDFPageProxy.prototype.render().promise resolves even after being canceled.

### ISSUE THREAD

**Issue by kevinbeal** [mozilla/pdf.js#12428] opened 2020-09-30 15:55 UTC
Attach (recommended) or Link to PDF file here: N/A

Configuration:
- Web browser and its version: Brave 1.14.81
- Operating system and its version: Ubuntu 18.04.5
- PDF.js version: 2.6.347
- Is a browser extension: nope

Steps to reproduce the problem:
1. call PDFPageProxy.prototype.render()
2. call renderTask.cancel() before the task

What is the expected behavior?
`renderTask.promise` should not resolve. I'd expect that the promise resolving to indicate that rendering is complete. It instead means that rendering is either complete or canceled.

What went wrong?
`renderTask.promise` _does_ resolve after calling `renderTask.cancel()`. It's really nice that there is a cancel method though. Thanks for that and this project generally. It will greatly increase the value proposition of my own products.

**Comment by Snuffleupagus** [comment] 2020-09-30 16:18
> `renderTask.promise` should not resolve.

Note that as mentioned in the JSDocs, it's actually *rejected* when when rendering is cancelled; see https://github.com/mozilla/pdf.js/blob/d49b2f6cc2b7ed86da22d55ddb1af0b8a5fe5a1e/src/display/api.js#L2753-L2758 
Furthermore, there's also unit-tests that enforce this behaviour; see https://github.com/mozilla/pdf.js/blob/d49b2f6cc2b7ed86da22d55ddb1af0b8a5fe5a1e/test/unit/api_spec.js#L1766-L1789

Hence it's quite possible that you're simply running into the following situation `If the task is currently rendering it will not be cancelled until graphics pauses with a timeout.`, given that rendering may actually finish *before* it has a change to get cancelled.

If the above isn't sufficient to address this issue, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by kevinbeal** [comment] 2020-09-30 16:57
It appears to be the timeout pause in my case. Thank you for pointing to these things.

Forgive my ignorance of canvas/webGL and the PDF.js canvas rendering classes, but I see a lot of method names like "clear", "endDrawing", "delete", etc that give the impression of removing what was painted. This was what I was seeing (sorry for lack of running code to show).

If `.cancel()` _does_ remove what was painted and calling it may take no effect until after the page is already rendered due to this timeout issue, then cancel doesn't actually cancel anything in this scenario, but instead just clears the canvas.

If my observations are correct so far, then it seems to me `.cancel()` serves an unintuitive and probably unwanted (by most consumers) effect in these cases. Specifically, the purpose of calling cancel for me is to limit resource consumption, but this means I have to render it again.

Have I understood correctly?

**Comment by Snuffleupagus** [comment] 2020-09-30 17:40
> Forgive my ignorance of canvas/webGL and the PDF.js canvas rendering classes, but I see a lot of method names like "clear", "endDrawing", "delete", etc that give the impression of removing what was painted.

It's probably a lot less confusing, at least initially, to only focus on the *official* API as found in https://github.com/mozilla/pdf.js/blob/master/src/display/api.js
The methods you mention are mostly internal implementation details, that you either can't or at least shouldn't call directly, which you don't (generally) have to worry about.

> If `.cancel()` _does_ remove what was painted
> [...]
> but instead just clears the canvas.

`RenderTask.cancel` simply stops parsing/rendering, as soon as that's possible, there's nothing being removed/cleared here.
(Please keep in mind that *a lot* of the processing in the PDF.js library is done asynchronously.)

It's possible that you're just testing with PDF documents that are too small/simple, w.r.t. the number of rendering operators in each page, to really notice the benefits of cancelling rendering.

> If my observations are correct so far,

Not really, as far as I can tell, unfortunately...

> Specifically, the purpose of calling cancel for me is to limit resource consumption,

Well, you obviously want to cancel rendering if you're no longer interested in a particular page; that way you free up memory/CPU resources for pages that you *do* want to render and thus increasing overall performance.
For example, when implementing a viewer: You probably want to stop rendering of pages that become scrolled out-of-view and/or when zooming happens.

> but this means I have to render it again.

It's not possible to re-start a `RenderTask` after it's been cancelled, if that's what you're asking about, hence that's expected behaviour.

**Comment by kevinbeal** [comment] 2020-09-30 17:57
> The methods you mention are mostly internal implementation details, that you either can't or at least shouldn't call directly, which you don't (generally) have to worry about.

I'm only calling public API's. I only mention the "clear" method (etc.) to explain my assumption about the clearing of the canvas.

> It's possible that you're just testing with PDF documents that are too small/simple, w.r.t. the number of rendering operators in each page, to really notice the benefits of cancelling rendering.

Would not be surprised, but canceling does not cause a rejection of the promise, and the promise resolves with a blank/cleared canvas.

> For example, when implementing a viewer: You probably want to stop rendering of pages that become scrolled out-of-view and/or when zooming happens.

That's exactly my use-case. My abstraction over the viewport scaling (i.e. zoom) called the `render` method and called cancel at the wrong time. I wrote a bug and didn't know it was a bug with my code for a long time due to my expectation that the `renderTask.promise` would not resolve when I called `cancel`. The page simply did not render, and without any errors, making it difficult to track down.

I assumed that cancel would not let the promise be fulfilled. My assumption was wrong and hence me writing this issue.

> It's not possible to re-start a RenderTask after it's been cancelled, if that's what you're asking about, hence that's expected behaviour.

Yeah, not exactly as you have stated, but I'm re-rendering it successfully when the previously mentioned bug is not a problem.

I don't know if therefor something needs to change or not. I just found the API to work differently than I expected. The JSDoc may explain my issue, I don't know if that's been established or not.

**Comment by Snuffleupagus** [comment] 2020-09-30 18:17
> That's exactly my use-case. My abstraction over the viewport scaling (i.e. zoom) called the `render` method and called cancel at the wrong time.

You may perhaps find the `viewer component` examples helpful, see https://github.com/mozilla/pdf.js/tree/master/examples/components, since they provide a [higher-level abstraction](https://github.com/mozilla/pdf.js/blob/master/web/base_viewer.js) compared to using the API directly; see e.g. the `simpleviewer`  example there or perhaps also the [`mobile-viewer`](https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer) example.

Note that those examples are using the same components that are also used to build the full demo viewer: https://github.com/mozilla/pdf.js#online-demo

---

Finally, as already mentioned, it's unfortunately going to be difficult for anyone to provide further assistance without a runnable example here.

**Comment by timvandermeij** [comment] 2020-09-30 19:48
Closing as answered for now unless a runnable example can be provided. Thanks.

**Closed by timvandermeij** 2020-09-30 19:48 UTC
