### ISSUE TITLE
Failing GitHub Actions font-test was marked as successful

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#17396] opened 2023-12-09 10:34 UTC
In a recent PR the font-tests failed completely *on Windows*, however the GitHub Actions workflow didn't actually catch the failure which means that the test was marked as successful: https://github.com/mozilla/pdf.js/actions/runs/7150415038/job/19473662790?pr=17395#step:8:20

That seems quite bad, since it means that we could very easily overlook a failing test. (Running `gulp fonttest` locally on Windows works fine though, so I'm not sure how to debug this.)

/cc @timvandermeij Any ideas here?

**Comment by timvandermeij** [comment] 2023-12-09 12:54
Yikes, that's not great indeed. I'll have a look at that.

**Comment by timvandermeij** [comment] 2023-12-10 15:06
It looks like this is a more general problem with exceptions occurring in the test orchestration code. I have at least managed to reproduce the issue by putting back the code from https://github.com/mozilla/pdf.js/pull/17172#discussion_r1421038879 (which also talks about an invalid browsing context in BiDi mode which is what we also see here) and a hothacked `node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Connection.js` file where the exception on line 123 is raised _unconditionally_. Putting back the page closing lines is required to trigger the `##onContextDestroyed` function and that in turn raises the exception. It's still a bit unclear if we're dealing with a bug in Puppeteer here or not, but at least the exception handling on our end is also insufficient given that the process exits with a zero status code which indicates success and which is why the GitHub Actions build succeeds.

**Comment by Snuffleupagus** [comment] 2023-12-10 15:31
As a *temporary* solution, depending on how difficult/time-consuming a proper fix is, could we do something similar to the old botio font-test and check that the success message is being logged and manually throw an exception?
https://github.com/mozilla/botio-files-pdfjs/pull/42/files#diff-aa6bfe19954403f5a8eac1c2259476609786b1c9b05bfaa81a360a87430a7710L26-L33

**Comment by timvandermeij** [comment] 2023-12-10 15:37
Yes, I think that could work as a temporary solution indeed. Let's await a response to the message above, and if it's indeed an upstream issue that we can't fix here we can decide to:

1. Revert from BiDi back to CDP which didn't have this issue.
2. Introduce the workaround and remove it once a patch is released upstream.
3. Wait for a new upstream release if the fix can be made quickly.

**Comment by whimboo** [comment] 2023-12-11 12:01
This is indeed strange. So when a browsing context gets destroyed in the browser it's basically gone after the `browsingContext.contextDestroyed` event has been received. So something might have already removed the given browsing context from [`this.#browsingContexts` in `Connection.ts`](https://github.com/puppeteer/puppeteer/blob/8cf71e7c118491e4662b78718ea8d759013f2700/packages/puppeteer-core/src/bidi/Connection.ts#L282-L285). The only method removing entries is [`unregisterBrowsingContexts`](https://github.com/puppeteer/puppeteer/blob/8cf71e7c118491e4662b78718ea8d759013f2700/packages/puppeteer-core/src/bidi/Connection.ts#L305), which is called from [`dispose` in `BrowsingContext.ts`](https://github.com/puppeteer/puppeteer/blob/8cf71e7c118491e4662b78718ea8d759013f2700/packages/puppeteer-core/src/bidi/BrowsingContext.ts#L184).

@sadym-chromium could you maybe help while @orkon is away?

**Comment by sadym-chromium** [comment] 2023-12-11 12:25
@whimboo could you please provide a link to the test in `pdfjs` which is failing?

**Comment by whimboo** [comment] 2023-12-11 13:46
I don't know which exact test fails here but see the initial comment with a link to the CI log. All the font tests can be found at https://github.com/mozilla/pdf.js/tree/master/test/font.

@timvandermeij and @Snuffleupagus could you may give more details about the code that actually triggers this exception?

**Comment by Snuffleupagus** [comment] 2023-12-11 13:54
This breaks when run, on Windows, as part of this GitHub Actions workflow: https://github.com/mozilla/pdf.js/blob/master/.github/workflows/font_tests.yml

**Comment by timvandermeij** [comment] 2023-12-11 21:40
I have been working on making a reduced test case that would demonstrate the issue in isolation, and while doing this I figured out I had been chasing a red herring in my previous analysis where I thought the Puppeteer exception didn't bubble up to our test runner. It turns out it actually _does_ and that is an issue in our test runner that has been there since basically "forever" (I could trace it back to a commit from 7 years ago). For some reason we never noticed this before, but the following code is problematic here:

https://github.com/mozilla/pdf.js/blob/master/gulpfile.mjs#L693-L695

The issue that we take the exit code from the spawned Node.js process and then... do nothing with it. This pattern exists in more places, so that's something we can fix on our end.

However, if we do that _now_ the builds will actually fail and might block merging patches, so we still need to do something about this Puppeteer exception being raised in the first place, so one of the options from https://github.com/mozilla/pdf.js/issues/17396#issuecomment-1848998447. Strangely this _only_ happens on Windows in our CI, and I also can't reproduce it on Linux at all so that makes it quite difficult. However, it does happen consistently 100% of the time in the CI; the most recent run is https://github.com/mozilla/pdf.js/actions/runs/7173542922/job/19533117343.

Does the traceback provide any hints as to why the browsing context in Puppeteer could be `undefined`? Would it perhaps make sense to guard for that in Puppeteer?

**Comment by whimboo** [comment] 2023-12-11 22:10
Thank you for the update Tim! To get even more details of what might go wrong I would suggest the following:

1. For the Puppeteer options add the `dumpio` field and set it to `true`.
2. Especially for Firefox set the preference `remote.log.level="Trace"` which will enable trace logs
3. Upload the changes to the CI and trigger the relevant tests

I could then have a look at the logs tomorrow to see what might go wrong on our side.

But you could also additionally add the `DEBUG="puppeteer:*` environment variable (maybe as a separate log) so that we can see which puppeteer commands and events are actually in use.

**Comment by timvandermeij** [comment] 2023-12-17 20:39
@whimboo Sorry for the delay here, but I have made #17432 to apply the debugging suggestions you mentioned (removed all other workflows and limited the font tests workflow to just Windows to make sure the logs are as usable as possible). You can find the (incorrectly marked as successful) build with its logs here: https://github.com/mozilla/pdf.js/actions/runs/7240827940/job/19724245810?pr=17432. It's still quite a bit of logs, but I hope it helps you to debug what Puppeteer is doing here.

The final logs when the exception happens are:

```
1702845086027	RemoteAgent	DEBUG	WebDriverBiDiConnection 0cc49e5b-65db-42dd-a862-46623e93bec5 <- {"type":"event","method":"browsingContext.contextDestroyed","params":{"url":"chrome://gfxsanity/content/sanitytest.html","children":null,"parent":null}}
file:///D:/a/pdf.js/pdf.js/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Connection.js:123
            throw new Error(`BrowsingContext ${contextId} does not exist.`);
```

I'm not sure what "chrome://gfxsanity/content/sanitytest.html" is, but maybe that's the anomaly that causes this only on Windows somehow.

**Comment by whimboo** [comment] 2023-12-18 10:19
Oh wow! Yes, this is indeed a problem with the sanity test window then! This window should not be used at all and we have it disabled for geckodriver and Marionette but forgot about it in Puppeteer. So temporarily you could set the preference `media.sanity-test.disabled` to `true`. Mind checking if that (alone) works? If yes I'll go ahead and provide a patch for Puppeteer.

**Comment by whimboo** [comment] 2023-12-20 16:17
I've created a PR for Puppeteer so that it should be fixed with the next release.

**Comment by timvandermeij** [comment] 2023-12-23 18:24
@whimboo  I have created #17457 and can confirm that setting `media.sanity-test.disabled` to `true` fixes the issue on Windows. You can find the logs here: https://github.com/mozilla/pdf.js/actions/runs/7309787007/job/19917756293?pr=17457. Thank you for making the patch upstream; we'll await a new release then and update the test code on our side as well to respect non-zero exit codes.

**Comment by whimboo** [comment] 2024-01-04 13:56
A new puppeteer release is out which contains my fix:
https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v21.7.0

So you could get this issue fixed by upgrading Puppeteer. CC @calixteman.

**Comment by timvandermeij** [comment] 2024-01-06 13:11
I'm reopening this because even though the upstream issue is fixed now we still need to update our Gulpfile to not ignore non-zero exit codes, to prevent this from going by unnoticed again in the future.

**Closed** 2024-01-21 19:34 UTC
Labels: test
