### ISSUE TITLE
Getting error : ui_utils.js:38 Uncaught TypeError: Cannot read property 'PDFJS' of undefined

### ISSUE THREAD

**Issue by chirag-metacube** [mozilla/pdf.js#7614] opened 2016-09-08 06:25 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: chrome, latest
- Operating system and its version: Windows 10
- PDF.js version: latest
- Is an extension: chrome app

Steps to reproduce the problem:
    <script src="js/vendor/pdf/ui_utils.js" type="text/javascript"></script>
    <script src="js/vendor/pdf/text_layer_builder.js" type="text/javascript"></script>
    <script src="js/vendor/pdf/pdf.js" type="text/javascript"></script>
ui_utils.js
text_layer_builder.js
pdf.js

added pdf.js scripts in this form, and got error  'PDFJS' of undefined, though i can see PDFJS object in console. i tried to change sequence of javascript and it doesn't help me.

Also not able to get "TextLayerBuilder" object in console, even after getting text_layer_builder.js

Is their anything i have done wrong?

**Comment by yurydelendik** [comment] 2016-09-08 13:48
The issue is not complete, please provide enough information to reproduce it easy on other computer. See https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md

**Comment by chirag-metacube** [comment] 2016-09-09 04:31
I had added pdf.js files in these sequence in my chrome app.
![pdf_issue_1](https://cloud.githubusercontent.com/assets/19548829/18375475/299c7bb4-7674-11e6-9db5-964f448ceb34.PNG)

Getting error in console.
![pdf_issue_2](https://cloud.githubusercontent.com/assets/19548829/18375476/29d5cdf6-7674-11e6-9aa6-db82ff9120c9.PNG)

Not able to find 'TextLayerBuilder' object in console. and can able to find PDFJS object
![pdf_issue_3](https://cloud.githubusercontent.com/assets/19548829/18375477/29e343dc-7674-11e6-8858-72e0d81fcaa5.PNG)
![pdf_issue_4](https://cloud.githubusercontent.com/assets/19548829/18375499/6cd33d6e-7674-11e6-9d2b-0c4613ba0b55.PNG)

**Comment by Snuffleupagus** [comment] 2016-09-09 11:44
It's very difficult to do any kind of meaningful debugging just based on a couple of screen-shots, and since you've not provided access to a working example it's very difficult to know why things aren't working.

However, the problem may be that you're attempting to use the various `.js` files as-is, without building them first, which isn't really supported. (For example, note how e.g. the `web/text_layer_builder.js` file has a number of dependencies: https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js#L18-L29.)

If you're attempting to build a custom viewer, I'd recommend that you instead use the pre-built that are published automatically in: https://github.com/mozilla/pdfjs-dist.
The `build` folder contains the necessary `pdf.js`/`pdf.worker.js` files, whereas the `web` folder has the `pdf_viewer.js` file which among other things includes the `TextLayerBuilder`.

Closing as answered. (If you need further assistance, please provide a link to a working example.)

**Closed by Snuffleupagus** 2016-09-09 11:44 UTC
Labels: 4-information-requested
