### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by iberezansky** [mozilla/pdf.js#12854] opened 2021-01-12 15:05 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 87.0.4280.141 (Official Build) (64-bit)
- Operating system and its version: Win7, Win10
- PDF.js version: 2.5.207, 2.7.512
- Is a browser extension: no

Steps to reproduce the problem:
1.  open the attached PDF in https://mozilla.github.io/pdf.js/web/viewer.html
[Buergernnews_01_21_compressed-8.pdf](https://github.com/mozilla/pdf.js/files/5802904/Buergernnews_01_21_compressed-8.pdf)

Some of images are missed:
![1](https://user-images.githubusercontent.com/18655020/104331992-c8abdf00-5500-11eb-8f41-634c11bc3228.png)

**Comment by Snuffleupagus** [comment] 2021-01-12 17:17
WFM, when testing in Firefox Nightly 86.

**Comment by calixteman** [comment] 2021-01-12 19:27
WFM with firefox nightly on Linux too but with chrome (87.0.4280.88) the picture on the bottom right is missing.

**Comment by timvandermeij** [comment] 2021-01-12 19:37
In that case it very much looks like a duplicate of #12123 which needs to be fixed on Chrome side. Seemingly random elements are missing intermittently in Chrome and it's also what affects our test runs. If someone can report this upstream, that would be great.

**Closed by timvandermeij** 2021-01-12 19:37 UTC
