### ISSUE TITLE
Document pages goes blank out after chrome updates

### ISSUE THREAD

**Issue by MauricioGrMDS** [mozilla/pdf.js#18137] opened 2024-05-21 15:55 UTC
## **Attach (recommended) or Link to PDF file here:**

You can use the official Modern browsers PDF example to reproduce this bug: 
https://mozilla.github.io/pdf.js/web/viewer.html

## **Configuration:**

**- Web browser and its version:**  I was testing in multiple browsers(Brave, Firefox, Chrome) and I only was able to reproduce on Chrome after this version: 124.0.6367.92 that was released at April 26, 2024, currently I am using the most recent version: 125.0.6422.61 and the issue is still there you can replicate.
One point that would be great to add here, I downgraded the chrome version to use this one: 123.0.6312.12 that was released at April 12, 2024 and doing the same steps I was not able to replicate the issue.

**- Operating system and its version:** macOS, Sonoma 14.4.1

**- PDF.js version:** In my local project I am using this version: "pdfjs-dist": "3.8.162", but we can replicate it here: https://mozilla.github.io/pdf.js/web/viewer.html as well, don't really know which version are you using

**- Is a browser extension:** No, it's a NPM package

## **Steps to reproduce the problem:**
1. Open the official modern browser example: https://mozilla.github.io/pdf.js/web/viewer.html
2. Open a new tap with whatever content.
3. Swap between the taps a couple of times and after that keep the page that is not the PDF document selected
4. After a couple of minutes(Could be more than 3 minutes) try to open again the tap where is the document
5. If you are lucky you will able to reproduce it

**What is the expected behavior? (add screenshot)**
You should see how the Document pages goes blank out and after we scroll down and then up the document page is back.

https://github.com/mozilla/pdf.js/assets/146257340/1ba6a0cc-134e-4a3e-b297-74c8c6b84bf5

https://github.com/mozilla/pdf.js/assets/146257340/bec839a6-3102-40bd-86d9-1f5cecc80729

**What went wrong? (add screenshot)**
Document pages goes blank out

![Screenshot 2024-05-21 at 9 45 09 AM](https://github.com/mozilla/pdf.js/assets/146257340/67ed88fd-c479-4e78-80d0-2bbd159d0e64)

**Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):** Not able to share my internal project, but you can try with this: https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2024-05-21 16:06
Duplicate of #18100

**Closed by Snuffleupagus** 2024-05-21 16:06 UTC
Labels: upstream, chrome-specific
