### ISSUE TITLE
Hindi does not display correctly

### ISSUE THREAD

**Issue by Qutbiddin** [mozilla/pdf.js#5682] opened 2015-01-28 12:43 UTC
Hello!
Hindi does not display correctly. The PDF Viewer gives extra spaces for the hindi joining characters, and does not combine with the letters. 

On iOS are multiple emojis/emoticons appearing. This is only occurring on iOS devices. It appears to be that certain diacritics are being rendered as the emojis instead of diacritics.

See example.
http://www.pdf-archive.com/2015/01/28/hindisssues/hindisssues.pdf

It is rendered normally in other PDF readers, including Adobe Reader.

Best regards.
Qutbiddin.

**Comment by Snuffleupagus** [comment] 2015-01-28 12:56
Closing as duplicate of issue #5677.

**Closed by Snuffleupagus** 2015-01-28 12:56 UTC
