### ISSUE TITLE
SyntaxError: expected expression, got '.' 

### ISSUE THREAD

**Issue by hershkoy** [mozilla/pdf.js#12623] opened 2020-11-14 19:53 UTC
Happens all the time, same issue in two versions on firefox: 72.0.2 & 46.0
Doesn't happen in chrome

SyntaxError: expected expression, got '.'pdf.js:2370:45

This is the line that I have in my main file:
```
<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>	
```

The line that is causing the issue is:
```
      this._pumpOperatorList({
        pageIndex: this._pageIndex,
        intent: renderingIntent,
        renderInteractiveForms: renderInteractiveForms === true,
        annotationStorage: annotationStorage?.getAll() || null        // this line is causing the error in firefox.
      });
```

**Comment by timvandermeij** [comment] 2020-11-14 22:30
This is an exact duplicate of https://github.com/mozilla/pdf.js/issues/12601#issuecomment-725614981. Please read that thoroughly, and in particular *never* directly use https://mozilla.github.io/pdf.js/build/pdf.js as explained in that comment.

**Closed by timvandermeij** 2020-11-14 22:30 UTC
