### ISSUE TITLE
Pdf not printing properly in chrome browser.

### ISSUE THREAD

**Issue by madhav1985** [mozilla/pdf.js#7963] opened 2017-01-17 11:43 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome & 35
- Operating system and its version: Windows 10
- PDF.js version: pdfjs-1.6.210-dist version
- Is an extension:
[msgfile.pdf](https://github.com/mozilla/pdf.js/files/710872/msgfile.pdf)

Steps to reproduce the problem:
1. We tried printing in mozilla firefox and  found working fine with the attached pdf but fails in chrome.
2. Print is blur and not redable in chrom browser. 

What is the expected behavior? (add screenshot)
Please provide as solution or provide us the link to download the pdf.js developer version.

What went wrong? (add screenshot)
print is blur in chrome.If we print through pdf.js

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2017-01-17 21:14
Could you add a screenshot of the bad and good rendering for comparison?

**Comment by madhav1985** [comment] 2017-01-18 11:29
Hi Tim,

    We verified in both chrome 35 and 55 versions and found print is appearing blur.
[msgfile_printedwithchrome55.pdf](https://github.com/mozilla/pdf.js/files/713730/msgfile_printedwithchrome55.pdf)

Please find the attached printed file from chrome for your reference.

Thanks,
Madhavan

**Comment by Rob--W** [comment] 2017-01-22 17:45
Looks good to me in the Chrome extension, PDF.js 1.6.293 in 55.0.2883.75.

[710872.pdf](https://github.com/mozilla/pdf.js/files/722123/710872.pdf)

I think that the difference in behavior is caused by #7697. So try the latest master version of PDF.js and the print quality will likely improve.

**Comment by pplr** [comment] 2017-01-25 17:20
I observed the same issue on Chrome when GPU acceleration is not available (see chrome://gpu). With GPU acceleration available, printing quality is perfect.

With the master version of PDF.js printing quality is good with or without GPU acceleration.

**Comment by timvandermeij** [comment] 2017-01-25 22:23
Thank you. Closing as fixed.

**Closed by timvandermeij** 2017-01-25 22:23 UTC
Labels: 4-chrome-specific, 4-printing
