### ISSUE TITLE
Font nearly unreadable in PDF.js on windows

### ISSUE THREAD

**Issue by danez** [mozilla/pdf.js#6735] opened 2015-12-07 18:15 UTC
When opening the attached pdf on any browser (tested IE, Edge and chrome) in windows makes the font unreadable (1. image). To me it looks like it is to much anti aliased. When zooming in at around ~200% it starts looking good.
On mac the pdf always works. Also Acrobat looks good (2. image).
![pdfjs](https://cloud.githubusercontent.com/assets/231804/11635397/c65c9ff2-9d16-11e5-862c-23b584cf797e.png)
![acrobat](https://cloud.githubusercontent.com/assets/231804/11635399/c831e4b8-9d16-11e5-98ab-d3f6307cb084.png)
[Kopp,Grupp,Huber,Rätsch - Person Tracking and 3D Model-based Face Analysis for Robust Human-Robot Interaction - BaWü15_pub (1).pdf](https://github.com/mozilla/pdf.js/files/54387/Kopp.Grupp.Huber.Ratsch.-.Person.Tracking.and.3D.Model-based.Face.Analysis.for.Robust.Human-Robot.Interaction.-.BaWu15_pub.1.pdf)

**Comment by timvandermeij** [comment] 2015-12-07 22:27
I can reproduce this using Windows 10 x64, Firefox 42 and the latest PDF.js development preview. The are no messages in the console indicating any font warning or error.

**Comment by danez** [comment] 2017-01-06 10:21
I just tested again with latest master and it works fine now.
Thanks to the person who fixed it. :)

**Comment by stijndeschuymer** [comment] 2018-04-18 13:50
Are there plans to fix this, I'm running into a similar issue.
Or maybe someone can point me in the right direction to try to fix it myself.
Thanks!

**Comment by timvandermeij** [comment] 2018-09-08 20:09
Closing since I cannot reproduce this anymore. However, if any problems remain, let us know and we can reopen this.

**Closed by timvandermeij** 2018-09-08 20:09 UTC
Labels: 4-font-conversion
