### ISSUE TITLE
Hyperlinks not extracted for particular PDF 

### ISSUE THREAD

**Issue by websirnik** [mozilla/pdf.js#7538] opened 2016-08-12 17:03 UTC
Hyperlinks are not getting extracted for this particular PDF. Other PDF viewers, including Chrome, Mac Preview & Acrobat, do render hyperlinks correctly.

Link to PDF file: https://cdn.relayto.com/media/files/ftV2Quw9QaWGCh7vZZbZ_BearingPoint_Annual_Report_2015.pdf

Configuration:
- Web browser and its version: Chrome 52
- Operating system and its version: Mac OS
- PDF.js version: http://mozilla.github.io/pdf.js/web/viewer.html (12.08.2016) 
- Is an extension: No

Steps to reproduce the problem:
1. Upload the PDF into http://mozilla.github.io/pdf.js/web/viewer.html
2. Get 0 hyperlinks

**Comment by Snuffleupagus** [comment] 2016-08-12 18:01
Those are not actually proper `Link` annotations, but instead that PDF file  they (for some inexplicable reason) use `Widget` annotations which we don't fully support yet.

**Comment by Snuffleupagus** [comment] 2016-08-12 18:04
Those are not actually proper `Link` annotations, but instead that PDF file (for some inexplicable reason) uses `Widget` annotations to simulate normal links.
Note that currently, we only support a subset of the possible `Widget` annotations.

**Comment by timvandermeij** [comment] 2016-08-13 11:29
Duplicate of #4872?

**Comment by THausherr** [comment] 2016-08-17 17:49
They're using an acroform push button (with no appearance stream) with an URI action, e.g. for the "HyperCube" link on page 6:
Root/AcroForm/Fields/[84]/A/URI
Root/Pages/Kids/[0]/Kids/[1]/Annots/[7]/A/URI

Yes it's a duplicate, the only difference is that the other issue has an annotation with an appearance stream.

**Comment by websirnik** [comment] 2016-12-22 18:51
I have another PDF where internal hyperlinks fail(page 3, table of contents): https://cdn.relayto.com/media/files/Wq7cashxQCO2JyWvkTlo_rapport-transparence-pwc-septembre2016.pdf

I'm not very familiar with a different type of annotations `Link` vs. `Widget`. Is there a way to convert from one type of annotations to another via a third-party tool, like Adobe Acrobat or similar?

**Comment by websirnik** [comment] 2016-12-27 18:58
@timvandermeij will the work you doing on buttons https://github.com/mozilla/pdf.js/issues/7613 be a solution for this issue?

**Comment by timvandermeij** [comment] 2016-12-27 20:50
Yes, this will be fixed once pushbuttons (with actions and appearance streams) are implemented, which is all tracked in that issue. Your PDF generator is doing a somewhat bad job by making links a `Widget` annotation, while the `Link` annotation is the standard for this. Essentially it's emulating a normal link by a transparent button, which is a bit of a workaround. I'm not sure why your PDF generator does that, but you might want to check the export settings to make sure it's not exported as a form.

*Note*: Since a recent PR, we now show these kinds of issues in the console in a more specific manner. Opening the PDF in the first message in this thread now shows `Warning: Unimplemented button widget annotation: pushbutton` in the console.

**Comment by websirnik** [comment] 2016-12-27 22:31
@timvandermeij Thanks for the explanation! I've just pulled the latest and saw the warning. Is there an approximate timeline for the pushbuttons?

**Comment by timvandermeij** [comment] 2016-12-27 22:48
No, there is no timeline. I think https://github.com/mozilla/pdf.js/issues/7613#issuecomment-251895091 describes the situation quite well. It's a large project and it takes a good amount of time to fully understand the specification and implement it properly. Rendering the pushbuttons themselves is not too difficult, but the associated actions (what happens when the button is clicked) and the appearance streams (how should it look) are much harder, yet required for proper pushbutton support.

**Closed** 2017-11-27 21:31 UTC
Labels: 4-annotations
