### ISSUE TITLE
Unable to save the page rotation after rotating the pdf in pdfjs viewer

### ISSUE THREAD

**Issue by nikhilreddy93** [mozilla/pdf.js#7903] opened 2016-12-20 07:13 UTC
When i'm trying to rotate the pages in viewer, it is working fine but if i refresh the browser after rotating, pages were setting back into the previous positions. How can i solve this problem?

**Comment by Snuffleupagus** [comment] 2016-12-20 10:31
Closing as duplicate of issue #5927.

**Closed by Snuffleupagus** 2016-12-20 10:31 UTC
