### ISSUE TITLE
Random pages blank in this document

### ISSUE THREAD

**Issue by berricks** [mozilla/pdf.js#8145] opened 2017-03-09 23:59 UTC
Link to PDF file (or attach file here): [The study of the effect of shock and vibration in the distributio.pdf](https://github.com/mozilla/pdf.js/files/832584/The.study.of.the.effect.of.shock.and.vibration.in.the.distributio.pdf)

Configuration:
- Web browser and its version:  Firefox 52
- Operating system and its version:  Mac OS 10.12.3
- PDF.js version: 1.5.188  Also tried this on the pdf.js demo
- Is an extension: no

Steps to reproduce the problem:
1. Open the pdf. Scroll down the pages and notice many pages are blank
2. Go to page 21 and notice this page is rendered. 

What is the expected behavior? (add screenshot)  all pages should be rendered. 

What went wrong? (add screenshot)
not sure.  Some of the blank pages do see to have a text layer that's selectable.  All pages are viewable in Mac Preview.  Chrome pdf view does not correctly render the pages that are blank in pdf.js, here's an example of page 17.
![servefile](https://cloud.githubusercontent.com/assets/18216868/23776147/9ebae9ae-04e9-11e7-8109-90a401b20c44.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-03-10 00:14
Closing as duplicate of issue #2073.

**Closed by Snuffleupagus** 2017-03-10 00:14 UTC
