### ISSUE TITLE
Move 2.6.347 to release and add new release

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#12851] opened 2021-01-11 18:30 UTC
It's been awhile. @timvandermeij do you have time to do a new one?

**Comment by Snuffleupagus** [comment] 2021-01-11 19:20
Can we try and get PR #12726 landed first, such that it's included in the next release?

**Comment by timvandermeij** [comment] 2021-01-11 19:44
Yes, we can do this, but it would be great to have that PR included if possible. Brendan, do you have time to finish that one?

**Comment by Snuffleupagus** [comment] 2021-01-20 15:54
Unless PR #12726 is unlikely to be updated soon, should we perhaps do the following:
 1. Create a new release ASAP, given how long it's been since the last one.
 2. Once PR #12726 lands, create a new release very soon afterwards. Given the potential impact of that PR, it might even warrant its "own" release anyway!?

**Comment by timvandermeij** [comment] 2021-01-20 19:49
I'd be fine with that. @brendandahl Do you think that PR can be updated soon, or should we proceed with this release?

**Comment by brendandahl** [comment] 2021-01-21 21:52
I've been looking into it. I'm trying to do some benchmarks, but unfortunately our current setup doesn't really measure the font conversion. I'm going to do some pushes to mozilla's talos to see how perf is there.

**Comment by Snuffleupagus** [comment] 2021-01-24 12:03
Given that PR #12726 looks to be further from landing than I hoped, given the performance regressions, let's just create a new release ASAP :-)

The release notes, for the new release, should probably mention that IE 11 is now unsupported.

**Comment by timvandermeij** [comment] 2021-01-24 12:43
Yes, I'll get this done today.

**Comment by timvandermeij** [comment] 2021-01-24 18:11
The release is done. I'm only waiting for the bot to push a new version of the website and the viewer, which for some reason hasn't happened yet even though the bots are available. Maybe this takes some more time.

On NPM the `next` tag is already updated with version 2.7.570. @brendandahl Because of #12324 the `latest` tag is not updated again. Could you update it manually to version 2.6.347?

**Comment by brendandahl** [comment] 2021-01-25 19:48
done

**Comment by timvandermeij** [comment] 2021-01-26 22:36
Thanks!

**Closed by timvandermeij** 2021-01-26 22:36 UTC
Labels: 1-other
