### ISSUE TITLE
Cannot save pdf document from ieeexplore

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#7090] opened 2016-03-18 07:38 UTC
The save control doesn't work on http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6162941&isnumber=6259910 whether the top frame is removed or stays.
This is on Win 10 64b, Chrome Version 51.0.2682.0 canary (64-bit)

**Comment by timvandermeij** [comment] 2016-03-18 19:58
Works for me on Arch Linux with the latest version of PDF.js and Firefox 44.0.2. Are there any messages in the console?

**Comment by qwer1304** [comment] 2016-03-19 07:12
Console messages:
stamp.jsp?tp=&arnumber=6162941&isnumber=6259910:22 GET http://staticieeexplore.ieee.org/assets/js/analytics/pagetagEvent-min.js?cv=20160225_000000 404 (Not Found)
 The problem seems to be some sort of incompatibility between pdf.js and frames. If you drill down into the page elements until the pdf is exposed outside the frame, pdf.js saves it happily. While the pdf is in a frame, save doesn't work.

**Comment by Rob--W** [comment] 2016-03-19 20:54
Works fine for me in Chrome 49.0.2623.75 on ArchLinux, with the [PDF Viewer extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm?hl=EN) at version 1.4.55.

To trigger a download, I clicked on the download button within the viewer at the upper-right corner (in your second page, the viewer was small, so I first had to open the menu by clicking on the ">>" icon in the upper-right corner).

Also works following the same steps in Chrome 51.0.2685.0.
But if I start Chrome with the `--isolate-extensions` flag, clicking on the download button does not work any more. That's obviously a bug, so I've reported it here: https://bugs.chromium.org/p/chromium/issues/detail?id=596283

Did you enable this experimental flag by any chance?

**Comment by qwer1304** [comment] 2016-03-20 05:46
OK, seems I've found the problem.
It's indeed the #enable-site-per-process flag.
It seems that canary comes up with this flag enabled, eventhough chrome://flags shows it as disabled.
When I clicked "Enable", then immediately "Disable" and then relaunched Chrome, download started to work.

**Comment by timvandermeij** [comment] 2016-03-20 13:56
Is there anything else we can do here or should we close this, @Rob--W ?

**Comment by Rob--W** [comment] 2016-03-20 13:59
I can think of a work-around, but that's not worth the efforts, since this issue is caused by a bug in Chrome with an experimental flag enabled. The bug should be fixed in Chrome.

**Closed by Rob--W** 2016-03-20 13:59 UTC
Labels: 4-chrome-specific
