### ISSUE TITLE
Failure in integration test in linux bot

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14293] opened 2021-11-19 18:18 UTC
The logs
```
  Stack:
    Error: Protocol error (Target.createTarget): can't access property "closing", selectedTab is null _setPositionalAttributes@chrome://browser/content/tabbrowser-tabs.js:1123:11
    _insertTabAtIndex@chrome://browser/content/tabbrowser.js:3286:25
    addTab@chrome://browser/content/tabbrowser.js:2710:16
    addTab@chrome://remote/content/shared/TabManager.jsm:24:31
    createTarget@chrome://remote/content/cdp/domains/parent/Target.jsm:90:28
    execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
    execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
    onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36
    onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
    handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14
    openPromptSync@resource://gre/modules/Prompter.jsm:1057:17
    alert@resource://gre/modules/Prompter.jsm:1329:17
    alert@resource://gre/modules/Prompter.jsm:80:7
    _displayPrintingError@chrome://global/content/printUtils.js:572:21
```
My feeling is that something is wrong with the printing test and an alert is generated which blocks following attempts to get the current selected tab (see https://searchfox.org/mozilla-central/source/toolkit/components/printing/content/printUtils.js#572).

**Comment by calixteman** [comment] 2021-11-19 18:21
When I wrote the printing test I had to play with some firefox options:
https://github.com/mozilla/pdf.js/blob/c6cb39ef3091fa41dce0be44af639cffeb048d61/test/test.js#L929-L934
maybe one must be changed or we must add a new one.

**Comment by timvandermeij** [comment] 2021-11-20 14:44
Given that this happened very recently, most likely in an upstream nightly build that we use in the tests, the regression range should be limited to a few days. Maybe we can find out if changes relating to printing were merged upstream, in e.g., Bugzilla or with `mozregression`?

**Comment by Snuffleupagus** [comment] 2021-11-20 15:12
https://bugzilla.mozilla.org/show_bug.cgi?id=1741698 looks somewhat relevant for us as well, since based on quickly skimming through that one it seems that `print.always_print_silent = true` is now being ignored.

**Comment by timvandermeij** [comment] 2021-11-28 18:31
@calixteman Running the integration tests locally on Linux (in non-headless mode) did show me that Firefox shows an "An error occurred during printing" dialog, which I guess is not expected and might be the cause of this? The change linked above seems relevant; do you have any ideas what could cause this?

**Comment by calixteman** [comment] 2021-11-28 19:20
This test is causing the issue:
https://github.com/mozilla/pdf.js/blob/c14552874b7464b95adc27a8060a5f5f0b60470b/test/integration/scripting_spec.js#L353
I waited for a fix in Firefox but it takes longer than I expected.
Anyway we can disable the test for Firefox in waiting for a fix, does it sound good for you ?

**Comment by timvandermeij** [comment] 2021-12-02 18:36
I see there's an upstream patch in progress now, so I guess we can await that then. If it becomes too annoying and/or the upstream patch doesn't land, we can always indeed disable the test for the time being.

**Comment by timvandermeij** [comment] 2021-12-12 15:21
I have disabled the test in the PR above for the time being until it's fixed upstream.

**Closed** 2022-01-04 13:37 UTC
Labels: 1-test
