### ISSUE TITLE
Auto sizing of font not working for form fields

### ISSUE THREAD

**Issue by PailaGH** [mozilla/pdf.js#17455] opened 2023-12-22 14:09 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome, 120.0.6099.110
- Operating system and its version: Windows
- PDF.js version: Latest (demo page)
- Is a browser extension:

Steps to reproduce the problem:
1.  Open attached document and start fill the email field with long text than field **PdfjsViewerAutoSizeTextField@gmail.com**
2.  Text field is scrolling instead of autosizing
3. Open the same attached document in adobe, form field auto resizes to the text entered

What is the expected behavior? (add screenshot)
![2023-12-22 08_06_14-](https://github.com/mozilla/pdf.js/assets/25868810/79f012fc-511a-4a43-b1a9-b9e69cc2b584)
[1-Estate Planning Checklist 2023.pdf](https://github.com/mozilla/pdf.js/files/13753106/1-Estate.Planning.Checklist.2023.pdf)

What went wrong? (add screenshot)
![2023-12-22 08_07_25-NotWorking](https://github.com/mozilla/pdf.js/assets/25868810/85f1dcb9-94fe-4c68-9e25-dec44d83281f)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-12-22 14:29
Duplicate of #15605

**Closed by Snuffleupagus** 2023-12-22 14:29 UTC
