### ISSUE TITLE
Auto-hide toolbar & sidebar

### ISSUE THREAD

**Issue by kekkc** [mozilla/pdf.js#9414] opened 2018-01-28 11:36 UTC
Hi everyone,

Chrome auto-hides the toolbar at the top and the sidebar after some seconds to gain some space when reading. Looking at the pdfium code it implementation seems a litte overkill, showing the toolbars any time the mouse is moved and gets "near" the toolbars. 

Maybe a simpler implementation could be used for pdf.js so that the bars are only showing for some seconds when the mouse is moving?

Nevertheless, Chrome's implementation feels pretty smooth and cool.

**Comment by Snuffleupagus** [comment] 2018-01-28 11:42
Closing as duplicate of issue #2784.

**Closed by Snuffleupagus** 2018-01-28 11:42 UTC

**Comment by hamad12a** [comment] 2024-08-01 22:45
but that duplicate doesn't address auto-hide efficiently!

**Comment by hamad12a** [comment] 2024-08-02 20:03
why was my comment marked as duplicate?

**Comment by kekkc** [comment] 2024-08-02 20:43
Yeah, this went into the wrong direction.

Opera / Chrome disabled the auto-hide for their toolbar 3 years ago (although they still have a cool sidebar slide-effect). For them there is the workaround that presentation mode can be used.

For FF this is not a workaround, since "combinded pageview" or any other settings is not respected in fullscreen. Issues mentioning this seem to be closed as duplicates to other - not directly relevant - issues:
https://github.com/mozilla/pdf.js/issues/14907
https://github.com/mozilla/pdf.js/issues/13901

Only now after research, I found Snuffleupagus comment in 13901 that browser fullscreen F11 can be used as a workaround. That is crazy, a user expects the PDF.js settings to be the same as the browser settings (download button should download the PDF file as FFs Save Website, print should show the same dialog as FF print page and for sure the presentation mode should use the same fullscreen as FF).

I don't get it how FF sometimes has the talent to present sth. as awesome as PDF.js so miserably to the common user because of some non-practical, theoretical and individual ideology philosophies that most users might not care about.

**Comment by hamad12a** [comment] 2024-08-02 21:52
I found the implementation of the autohide toolbar feature in another repository https://github.com/James-Yu/LaTeX-Workshop/blob/master/viewer/components/gui.ts but due to my incompetence in javascript/typescript mindset, I couldn't re-implement it directly to pdf.js
