### ISSUE TITLE
PDF file load error PDF.js v2.1.266 (build: 81f5835c) Message: Failed to fetch # 10967)

### ISSUE THREAD

**Issue by 1470983522** [mozilla/pdf.js#10967] opened 2019-07-13 00:00 UTC
I have this problem. When I use PDF.js to preview an PDF file, I prompt for an error to load, but the same code can be previewed on my computer with a local area network and a mobile phone. However, opening the local code that exists on the phone cannot be previewed, showing the load error 
PDF.js v2.1.266 (build: 81f5835) Message: Failed to fetch)

**Comment by Snuffleupagus** [comment] 2019-07-13 07:45
When opening an issue you need to actually fill out https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md with *all* of the requested information, and make sure to write in English, otherwise this will be closed as INVALID.

**Closed** 2019-07-13 12:25 UTC

**Comment by pcdinizbr** [comment] 2021-03-29 19:24
I have the same issue. PDF.js v2.6.11 (compilation: 7a034dc8) Mensagem: Failed to fetch. I'm using an App called Folderit and when I try to preview any PDF file it give to me this error and the file is not showed. I tried using other computers in the same network and works well. The issue is specific with my device. Windows 10 Pro Version 20H2 OS build 19042.868 - Experience Windows Feature Experience Pack 120.2212.551.0. I'm using Java version 8 updated for Windows 10. Version 8 Updated 281 - (build 1.8.0_281-b09). You can see a video here - https://share.getcloudapp.com/NQuJy0Lo

**Comment by amani-alabadi** [comment] 2022-09-22 10:52
same issue. 
PDF.js v2.6.11 (build: 7a034dc8)
Message: Failed to fetch
 I'm using an Folderit App as well and when I try to preview any PDF file.

**Comment by pcdinizbr** [comment] 2022-09-22 11:11
After a while the problem disapeared but 30 days ago the issue came backup. Now with the same message as yours.
PDF.js v2.6.11 (compilação: 7a034dc8) Mensagem: Failed to fetch.
I'm contacting the Folderit support to verify if they have a solution for that issue. I'm using Windows 10 Pro 21H2.
