### ISSUE TITLE
One part of a PDF takes very long to render

### ISSUE THREAD

**Issue by liamengland1** [mozilla/pdf.js#17840] opened 2024-03-25 22:26 UTC
Attach (recommended) or Link to PDF file here: `https://bugzilla.mozilla.org/attachment.cgi?id=9377778`

Configuration:
- Web browser and its version: Firefox 124.0.1
- Operating system and its version: Windows 11
- PDF.js version: 4.1.249
- Is a browser extension: No

Steps to reproduce the problem:
1. Visit the PDF

What is the expected behavior? It should render quickly.

What went wrong? The "Department of Veteran Affairs" logo/seal causes the page to render extremely slowly at any zoom level.

Profiler: `https://share.firefox.dev/3PAJDJU`

I think this is a shading pattern issue, as I see over 7,000 samples of `shadingFill` in the profile.

Also tracked at `https://bugzilla.mozilla.org/show_bug.cgi?id=1878133`

**Comment by Snuffleupagus** [comment] 2024-03-26 08:57
Let's close as a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1878133 then, since there's no need to report the same thing in both Bugzilla and GitHub.

**Closed by Snuffleupagus** 2024-03-26 08:57 UTC
