### ISSUE TITLE
use Fetch API where available (Firefox, Chrome, Opera)

### ISSUE THREAD

**Issue by nschloe** [mozilla/pdf.js#6348] opened 2015-08-12 21:42 UTC
Right now, pdf.js uses XMLHttpRequest (XHR) for fetching the PDF, see https://github.com/mozilla/pdf.js/blob/master/src/core/network.js.

With the recent development of the [Fetch API](https://fetch.spec.whatwg.org/) ([released in Chrome 42, Firefox 39, Opera 30](http://caniuse.com/#search=fetch)), a clean replacement for XHR is now in place; see

  * https://hacks.mozilla.org/2015/03/this-api-is-so-fetching/,
  * http://davidwalsh.name/fetch,
  * https://github.com/GoogleChrome/samples/blob/gh-pages/fetch-api/fetch-response-stream.html.

It can [easily be detected](https://hacks.mozilla.org/2015/03/this-api-is-so-fetching/) if the current browser has `fetch()`, so this indeed looks like a interesting alternative.

**Comment by timvandermeij** [comment] 2015-08-12 21:48
That sounds great. If someone is willing to work on this, feel free to submit a pull request. We must be sure to remain compatible for old browsers, so we probably need a fallback to XHR or a polyfill for `fetch()` to do so.

**Comment by yurydelendik** [comment] 2015-08-12 21:49
Dup of #5319 ?

**Comment by existentialism** [comment] 2015-08-12 21:49
Also https://github.com/mozilla/pdf.js/issues/6126

**Comment by timvandermeij** [comment] 2015-08-12 21:52
Right, closing as duplicate of #6348. Let's continue there.

**Closed by timvandermeij** 2015-08-12 21:52 UTC
Labels: 1-core
