### ISSUE TITLE
Not able view pdf of A0 page size

### ISSUE THREAD

**Issue by simonmathew** [mozilla/pdf.js#5916] opened 2015-04-06 04:24 UTC
Not able view pdf with A0 page size. These pdf are created from images that are scanned from drawings.
Sample pdf can be downloaded from this 
http://weddings.celusion.com/uploads/1.PDF

In chrome this is the screenshot 
![screenshot from 2015-03-27 09 16 15](https://cloud.githubusercontent.com/assets/8577608/7002642/cccb3e5a-dc6b-11e4-8ffb-d02d75f3670d.png)
In firefox it keep loading nothing happens.

**Comment by Snuffleupagus** [comment] 2015-04-06 08:32
When reporting an issue, please make sure that you read: https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md. Especially the *first* paragraph, which I'm also quoting:
> The issues are used to track both bugs filed by users and specific work items for developers. Try to file one issue per problem observed. Please specify a valid title (e.g. "Glyph spacing is incorrect" instead of "PDF.js does not work") and provide more details about the issue: **link to the PDF, location in the PDF, screenshot, browser version, operating system, PDF.js version and JavaScript console warning/error messages. Issues that do not have enough details provided will be closed as invalid/incomplete.**

**Comment by timvandermeij** [comment] 2015-04-06 09:52
Works for me with Windows 7 x64, Firefox 37.0.1 and the PDF.js development version. Please provide the information mentioned above.

**Comment by simonmathew** [comment] 2015-04-06 10:05
If you are viewing in browser it can be viewed but when we view through viewer.html it shows such error.
My chrome version is 39.0.2171.95 and Ubuntu 14.04 LTS 32bit.

**Comment by timvandermeij** [comment] 2015-04-06 13:44
Labeling as Chrome specific for now as it cannot be reproduced on Firefox.

**Comment by simonmathew** [comment] 2015-04-06 13:55
Its not chrome specific issue we checked in Firefox but it is not loading and this is not like very time this issue is coming in chrome and Firefox but some time it loads properly but some time it doesn't. But we cannot tell this to the client and now we are using a i frame so it take browser default viewer but the user will be able to print and download the pdf that's why we need a viewer in the application.

**Comment by timvandermeij** [comment] 2015-04-06 15:15
Which Firefox version do you have? Some other issues with large scanned images were resolved lately by the Firefox 37 release.

**Comment by simonmathew** [comment] 2015-04-07 04:10
I have Firefox 33.0 and i shall update my Firefox and try. What is the system basic requirement for viewing such PDFs and what is the chrome and Firefox versions or is there any other solution for this issue.

**Comment by timvandermeij** [comment] 2015-04-07 18:25
You should indeed upgrade to the most recent Firefox version. This is most likely a browser bug in combination with a feature called canvas tiling, which is not yet implemented.

**Comment by simonmathew** [comment] 2015-04-09 06:59
I have updated the Firefox to 37.0.1 but still it is not loading all the time and it taking much time for loading. But if we are opening in browser directly it works fine. Is there any other option or solution for viewing this type pdf in any browser without giving the user the permission for downloading and printing..?

**Comment by Lord-of-Darkness** [comment] 2015-05-15 20:14
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by mcorb** [comment] 2015-05-25 07:49
Interesting datapoint: The linked PDF consistently crashes Apple Preview (though PDF.js seems fine with it here in all browsers, OS X Yosemite).

**Comment by mcorb** [comment] 2015-05-26 01:26
Perhaps extract the JPEG image from the file and inspect it for correctness. If Chrome and Preview are both crashing on this file it could indicate a libjpeg issue as that's the only component these viewers really have in common. It's a shame getting backtraces is so difficult these days.

**Comment by yurydelendik** [comment] 2015-11-10 14:10
The PDF contains 9928x14043 JPEG image. That's 1200 DPI -- no wonder most of apps crash. This PDF is not designed to be redistributed on the web.

**Comment by timvandermeij** [comment] 2020-06-07 11:29
Closing since the PDF file is no longer available and many optimizations have been implemented since. There are also other issues that already track large image tiling.

**Closed by timvandermeij** 2020-06-07 11:29 UTC
Labels: 2-performance
