### ISSUE TITLE
[Bug]:When selecting text,  the selected area automatically expanding

### ISSUE THREAD

**Issue by spStep** [mozilla/pdf.js#18641] opened 2024-08-23 02:45 UTC
### Attach (recommended) or Link to PDF file

[compressed.tracemonkey-pldi-04.pdf](https://github.com/user-attachments/files/16724142/compressed.tracemonkey-pldi-04.pdf)

### Web browser and its version

 Chrome 127.0.6533.120 (arm64)

### Operating system and its version

macOS Sonoma 14.6.1

### PDF.js version

4.5.136

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem
When selecting text, I frequently encounter the selected area automatically expanding. At these times, the following code always returns. I checked and found that range.endOffset and range.startOffset are the same, which is unusual since they should be different when text is normally selected.

```
const s = document.getSelection();
let range = null;
range = s.getRangeAt(s.rangeCount - 1);
if (!s.toString() || range.endOffset - range.startOffset === 0) return;
```

https://github.com/user-attachments/assets/4df2133a-8374-43f5-9533-89778e16ab82

### What is the expected behavior?

The selection area should not automatically expand, and endOffset and startOffset should return correct results.

### What went wrong?

When the selection area automatically expands,I checked and found that range.endOffset and range.startOffset are the same, which is unusual since they should be different when text is normally selected.
```
const s = document.getSelection();
let range = null;
range = s.getRangeAt(s.rangeCount - 1);
if (!s.toString() || range.endOffset - range.startOffset === 0) return;
```

**Comment by Snuffleupagus** [comment] 2024-08-23 07:08
First of all, please make sure that you place information under the *correct* headings (note the edits above).

> ### Is the bug present in the latest PDF.js version?
> 
> Yes

Sorry, but did you *actually* check this in https://github.com/mozilla/pdf.js#online-demo (which contains the latest development version)?

I cannot reproduce what's shown in the screen-recording in either Firefox Nightly 131.0a1 or Google Chrome Beta 129.0.6668.12, and this seems like something that PR #18481 may have fixed (that one will be included in the next release).

**Comment by timvandermeij** [comment] 2024-08-23 17:14
I also can't reproduce the issue using the most recent development version. Closing since this is most likely already fixed, and otherwise we'll need more information about how to reproduce the issue in the development version linked above.

**Closed by timvandermeij** 2024-08-23 17:14 UTC
Labels: information-requested

**Comment by spStep** [comment] 2024-08-26 03:20
> First of all, please make sure that you place information under the _correct_ headings (note the edits above).
> 
> > ### Is the bug present in the latest PDF.js version?
> > Yes
> 
> Sorry, but did you _actually_ check this in https://github.com/mozilla/pdf.js#online-demo (which contains the latest development version)?
> 
> I cannot reproduce what's shown in the screen-recording in either Firefox Nightly 131.0a1 or Google Chrome Beta 129.0.6668.12, and this seems like something that PR #18481 may have fixed (that one will be included in the next release).

Thank you for your reply. I have looked at the link https://github.com/mozilla/pdf.js#online-demo. I have a question: Can I get the latest development version, or do I have to wait for the next release version? I tried using the master branch and started a local server, but I encountered the same issue.

**Comment by spStep** [comment] 2024-08-26 04:42
> I also can't reproduce the issue using the most recent development version. Closing since this is most likely already fixed, and otherwise we'll need more information about how to reproduce the issue in the development version linked above.



> headings (

I have uploaded another file named test.pdf. This file reproduces the issue easily, so you can give it a try. I’ve also uploaded a video under the ‘What went wrong?’ section.

**Comment by Snuffleupagus** [comment] 2024-08-26 06:32
> I have uploaded another file named test.pdf.

First of all, never report multiple *differerent* problems in the same issue.

> This file reproduces the issue easily, so you can give it a try

That works fine in Firefox Nightly 131.0a1 with its *built-in* PDF Viewer, which is the primary development target; hence this unfortunately doesn't seem like a valid issue.
