### ISSUE TITLE
PDF is not visible in normal view but shown in full screen view

### ISSUE THREAD

**Issue by faisal-iqbal** [mozilla/pdf.js#8142] opened 2017-03-09 09:54 UTC
**Link to PDF file:**
Issue is reproducible on sample PDF as well.
http://mts.folio3.com:6081/wp-content/themes/mtsobek/page-templates/catalog/compressed.tracemonkey-pldi-09.pdf

**Configuration:**
- Web browser and its version: **Chrome Version 56.0.2924.87**
- Operating system and its version: **Ubuntu 14.10**
- PDF.js version: **1.6 stable**
- Is an extension: No

**Steps to reproduce the problem:**
1.  Go to PDF viewer, PDF is not visible. Click on full screen and PDF can be seen.
2.  Exit full screen, PDF is still not visible

**What is the expected behavior?**
PDF should be visible. Using code from stable 1.6 download.

**What went wrong?**
No error is shown on chrome developer tool. PDF is loading completely. Console shows:
```
Navigated to http://mts.folio3.com:6081/catalog?file=http://mts.folio3.com:6081/wp-content/themes/mtsobek/page-templates/catalog/compressed.tracemonkey-pldi-09.pdf
pdf.worker.js:42959 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
viewer.js:8400 PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 1.6.210)
```

**Link to a viewer:**
http://mts.folio3.com:6081/catalog?file=http://mts.folio3.com:6081/wp-content/themes/mtsobek/page-templates/catalog/compressed.tracemonkey-pldi-09.pdf

**Comment by Snuffleupagus** [comment] 2017-03-09 11:02
Neither of the links you provided works unfortunately, so it's not possible to reproduce the problem.
In order for this issue to be valid, please provide working links!

Also, does the default viewer, i.e. https://mozilla.github.io/pdf.js/web/viewer.html, work correctly?
Because if it does, that would suggest an issue with your custom implementation.

**Comment by timvandermeij** [comment] 2017-03-11 14:09
Closing for now since the provided information is too incomplete for us to work with.

**Closed by timvandermeij** 2017-03-11 14:09 UTC
Labels: 4-information-requested

**Comment by faisal-iqbal** [comment] 2017-03-16 13:17
Sorry about the links. I have updated them to the puplic ones

**Comment by timvandermeij** [comment] 2017-03-16 21:10
Works fine in Firefox. Did you test this with the link posted by Snuffleupagus above?
