### ISSUE TITLE
How to disable save oprion

### ISSUE THREAD

**Issue by doitajin** [mozilla/pdf.js#6300] opened 2015-08-01 12:00 UTC
how to disable save and print from top bar and ctrl+s.

**Comment by timvandermeij** [comment] 2015-08-02 21:14
You will need to remove those elements and the associates JS code youself, or create a custom viewer using the web components (see the `examples` folder). Closing as answered and duplicate of #6087 and others.

**Closed by timvandermeij** 2015-08-02 21:14 UTC
