### ISSUE TITLE
Dishwasher installation PDF (single page) uses up all memory

### ISSUE THREAD

**Issue by baraclese** [mozilla/pdf.js#18176] opened 2024-05-27 15:48 UTC
Attach (recommended) or Link to PDF file here:
[9001171159_A.pdf](https://github.com/mozilla/pdf.js/files/15457179/9001171159_A.pdf)

Configuration:
- Web browser and its version: Firefox 126.0
- Operating system and its version: Arch Linux x64
- PDF.js version: 4.1.379
- Is a browser extension: No

Steps to reproduce the problem:
1. Open PDF
2. Observe unreasonable memory usage

What is the expected behavior? (add screenshot)
Use less memory for this:
![dishwasher](https://github.com/mozilla/pdf.js/assets/1628879/b22732b0-4468-4a2c-b426-7a6b8c0c79fe)

What went wrong? (add screenshot)
Tab crashes or browser gets killed.

Upon further investigation I installed pdf.js as browser extension in Chromium. The reported PDF.js version is 4.3.84. There appears to be no problem with memory usage in Chromium. Rendering the PDF is still somewhat slow however.

**Comment by Snuffleupagus** [comment] 2024-05-27 19:10
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1731514

**Closed by Snuffleupagus** 2024-05-27 19:10 UTC
