### ISSUE TITLE
ADP paystubs render slightly incorrectly (underscores below commas and dots)

### ISSUE THREAD

**Issue by cbiesinger** [mozilla/pdf.js#2126] opened 2012-09-14 20:00 UTC
The ADP paystubs from https://ipay.adp.com/ render slightly incorrect for me - all dots and commas render with an underscore. See the attached screenshot. evince and acroread render it correctly without these underscores.

**Comment by timvandermeij** [comment] 2018-12-23 12:35
Closing since there have been many font-related fixes in the meantime, no (reduced) PDF file is available and no working links to screenshots are available. If this is still not fixed in the meantime, please open a new issue with all the details from the issue template filled in. Thanks.

**Closed by timvandermeij** 2018-12-23 12:35 UTC
Labels: 2-image-quality

**Comment by dholbert** [comment] 2018-12-27 18:57
I can still reproduce with the built-in version of PDF.js in Firefox, FWIW.

**Comment by dholbert** [comment] 2018-12-27 18:57
(using my own paystub, which I sadly can't attach, for obvious privacy reasons)

**Comment by dholbert** [comment] 2018-12-27 19:00
Here's a screenshot -- notice the underscore below the period:
![paystub-screenshot](https://user-images.githubusercontent.com/426803/50491332-9c2ed400-09c6-11e9-9b73-ae9fbf096f39.png)

**Comment by dholbert** [comment] 2018-12-27 19:08
Anyway, as-requested, I filed a new issue and filled out the template. https://github.com/mozilla/pdf.js/issues/10388
