### ISSUE TITLE
PDF Print in Shrink Format

### ISSUE THREAD

**Issue by manikandanmk3** [mozilla/pdf.js#9070] opened 2017-10-25 23:46 UTC
Attach (recommended) or Link to PDF file here: Sorry it is not a github project and internal to organization. Hence could not share the link to PDF file.

Configuration:
- PDF.js Version: Version 2 - From build **pdfjs-1.8.188-dist.zip**
- Web browser and its version:  IE 11, Chrome, Firefox 
- Operating system and its version: Windows 7, Windows 10
- Is a browser extension: No

Steps to reproduce the problem:
 - We are using PDF.js plugin for our application to print any PDFs. Our customers reported that while they are preview the file before printing, they are not able to preview all the pages. Only first half portion of the first page is been previewed and while printing also only half page is getting printed. So we have upgraded our PDF.js build, web folders and since then we are having preview issue only in IE but not in Chrome or Mozilla. Also other main issue is when the user printing the PDF they are getting the pdf page printed in a shrinked way. Please let us know if there are any existing issues like this and provide your inputs in fixing the issue and let us know if you need more information on it.

What is the expected behavior? User should be able to preview all the pages and should print all the pages in a page-fit format without any shrink.

What went wrong? While printing the PDF using viewer.html the page getting printed in a shrink format. Means the whole page is getting printed in the top left portion of the paper and the remaining areas are blank

**Comment by yurydelendik** [comment] 2017-10-26 00:10
Can you reproduce the same issue with http://mozilla.github.io/pdf.js/web/viewer.html ? If not, the problem most likely with your proprietary solution, and we cannot assist with something we cannot observe.

**Comment by manikandanmk3** [comment] 2017-10-26 20:14
When i browse with  http://mozilla.github.io/pdf.js/web/viewer.html, the internet explorer did not load all the pages while doing a Print Preview. Please see the file attached. Out of 14 pages, it just shows only 2 pages. Also when i tried in Chrome to preview it closes the tab itself which it did not happen for our PDFs in Chrome. Please let us know your inputs.
![printpreview](https://user-images.githubusercontent.com/33101776/32074847-ac0e7abe-ba68-11e7-85a1-7aa1a2ff5842.jpg)

**Comment by manikandanmk3** [comment] 2017-10-30 13:14
Could you please provide your suggestion on the above issue?

**Comment by manikandanmk3** [comment] 2017-11-06 15:38
Will there be any suggestion or solution for the above problem i am facing while printing the PDF?

**Comment by timvandermeij** [comment] 2017-11-06 21:07
Printing is not really supported well across browsers. In the web viewer we pre-render all pages before sending it to the print preview, but if you use the print button, we cannot always do that, which is what you see. This is, more often than not, a browser limitation that we have to work around. For now there is not much we can do in the short term I think.

**Comment by manikandanmk3** [comment] 2017-11-08 15:25
Thanks for your inputs Tim. But in IE when we Print the PDF using the Print option in WebViewer.html the page is getting printed in a shrink way. Mean the whole page is getting printed but in the upper left side of the Paper.  Please find the attachment and suggest us a solution. This is happening after we upgrade our PDF.js Version as: Version 2 - From build pdfjs-1.8.188-dist.zip
[Print.pdf](https://github.com/mozilla/pdf.js/files/1454424/Print.pdf)

**Comment by ishraqsyed0407** [comment] 2019-03-19 13:43
Facing some issues while previewing the PDF using pdf.js on Edge and Firefox. On both these browsers if the content of lets say the first page is large it moves to the second page along with the footer and so on. Here is the behavior.
![firefox_Edge_issue](https://user-images.githubusercontent.com/48717236/54610293-b5519900-4a7a-11e9-9ba5-0eb09aa5ae99.PNG)

Another issue is that a blank page is printed at the end. 

![firefox_edge_issue_2](https://user-images.githubusercontent.com/48717236/54610416-fc3f8e80-4a7a-11e9-91ea-4fc85275e5b7.PNG)

Works fine on Chrome and IE11.

**Comment by timvandermeij** [comment] 2021-03-14 15:10
Closing since the issues mentioned here are either fixed now or cannot be fixed because the browser (IE) is now officially unsupported by PDF.js.

**Closed by timvandermeij** 2021-03-14 15:10 UTC
Labels: 4-printing
