### ISSUE TITLE
ALT+Left arrow not working in IFrame

### ISSUE THREAD

**Issue by Nataraj67** [mozilla/pdf.js#13265] opened 2021-04-19 17:55 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 89.0.4389.114 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: Beta (v2.8.335)
- Is a browser extension:

Steps to reproduce the problem:
1.  Create document url using PDF.js
2.  Any ASP.NET application create Iframe and set iframe url as document url
3.  for EX,   <iframe src='https://mozilla.github.io/pdf.js/web/viewer.html'></iframe>
4.  Click document page 1 , 3, and 2
5.  press ALT+Left arrow

What is the expected behavior? (add screenshot) 
 It moves to tab 3  then tab 1

What went wrong? (add screenshot)
 Normally its working but inside iframe not working

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2021-04-19 18:16
Duplicate of #8121; note in particular https://github.com/mozilla/pdf.js/issues/8121#issuecomment-475860205.

**Comment by Nataraj67** [comment] 2021-04-19 19:00
Is any possibility  to make sure the "ALT+Left arrow" functionality should working fine in the iframe

If yes .  please provide steps to resolve the issue 

Note : I am currently using Latest version v2.8.335. I already used PDF.js older version 2.2.228 that not having this functionality i hope recent versions its updated. but its not working in the iFrame & object html tag's

**Comment by Snuffleupagus** [comment] 2021-04-19 20:36
> Is any possibility to make sure the "ALT+Left arrow" functionality should working fine in the iframe

While technically possible, for the reasons outlined in https://github.com/mozilla/pdf.js/issues/8121#issuecomment-475860205 we're *not* going to implement that. (You may of course implement this in a *custom* viewer, however it's not something that we'll support.)

**Closed** 2021-04-20 19:33 UTC
