### ISSUE TITLE
Unsupported ShadingType

### ISSUE THREAD

**Issue by 296500148** [mozilla/pdf.js#11679] opened 2020-03-09 06:58 UTC
how to solve this problem？
[第二课时 找一个数的因数和倍数.pdf](https://github.com/mozilla/pdf.js/files/4305035/default.pdf)
The background of this pdf is a bit special

**Comment by Snuffleupagus** [comment] 2020-03-09 08:14
Duplicate of #5046.

*For future reference:* When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Closed** 2020-03-09 21:37 UTC

**Comment by 296500148** [comment] 2020-03-11 02:00
Can I change this color? Pink looks too noticeable ...
