### ISSUE TITLE
Two-Up?

### ISSUE THREAD

**Issue by Moistly** [mozilla/pdf.js#1475] opened 2012-04-03 08:04 UTC
I have a client that is asking for Page displays as found in Adobe Reader (Two-Up, Two-Up Continuous, Show Gaps Between Pages and Show Cover Pages During Two-Up)

Would this be possible? Either now or sometime in the future?

Thanks

**Comment by Snuffleupagus** [comment] 2015-02-13 17:06
Closing as duplicate of issue #590.

**Closed by Snuffleupagus** 2015-02-13 17:06 UTC
Labels: 1-ux, 1-viewer
