### ISSUE TITLE
Can anyone help me how to disable download/print options on pdf viewer macro. 

### ISSUE THREAD

**Issue by venkataraog** [mozilla/pdf.js#10617] opened 2019-03-05 11:58 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by venkataraog** [comment] 2019-03-05 12:01
I was using PDF Viewer macro to upload these pdfs and I just want to restrict users to perform other actions except read.

**Comment by timvandermeij** [comment] 2019-03-05 23:20
Closing since this is a duplicate of #9238.

**Closed by timvandermeij** 2019-03-05 23:20 UTC
