### ISSUE TITLE
Custom error handling on PDFJS.getDocument request failure

### ISSUE THREAD

**Issue by xmityaz** [mozilla/pdf.js#7513] opened 2016-07-29 09:08 UTC
I'm using `PDFJS.getDocument` request to load the pdf file. And in a case of any error from the server side, I'm expecting the specific error format in response from the server to show the notification message with the real reason of an error.

The approximate code:

`PDFJS.getDocument($URL)`
`.then(...)`
`.catch(error => showErrorNotification(error));`

But if request failed inside catch, instead of the error from the server response I'm getting an `error` created inside [pdf.js _onError hanlder](https://github.com/mozilla/pdf.js/blob/122d4732398ca67381cc469dc2f49696b824c98d/src/core/network.js#L490). It has different data format and doesn't provide any data from original error (except error status)

Is it possible to bind some custom error handler, before it will be handled inside pdf.js _onError function?

**Comment by timvandermeij** [comment] 2016-07-29 12:31
Without a working version of the code you're using this will be really hard to debug. Please create a minimal example (on JSBin for example) and post it here as code snippets do not really help with debugging.

**Comment by xmityaz** [comment] 2016-07-31 15:49
Sorry for delay. 
JSBin example: http://jsbin.com/qulinaweho/1/edit?html,console,output

**Comment by Snuffleupagus** [comment] 2019-02-10 11:24
Duplicate of #9750.

**Closed** 2019-02-10 13:50 UTC
Labels: 1-core
