### ISSUE TITLE
Font ignored for numbers in Safari

### ISSUE THREAD

**Issue by rijk** [mozilla/pdf.js#8854] opened 2017-08-31 10:23 UTC
Link to PDF file: https://s3.eu-central-1.amazonaws.com/s3.envoy.rocks/uniti/sitomeca/algemene-voorwaarden/BBCtqc_Sitomeca+GTCs+v1.2.pdf

Configuration:
- Web browser and its version: Safari Version 10.1.2 (12603.3.8)
- Operating system and its version: OS X 10.12.6
- PDF.js version: pdfjs-dist@1.9.491 
- Is an extension: no

What is the expected behavior? (screenshot from Chrome)

<img width="194" alt="screen shot 2017-08-31 at 12 21 49" src="https://user-images.githubusercontent.com/159500/29918785-15eb4ffa-8e47-11e7-9007-c711423e586d.png">

What went wrong? (screenshot from Safari) — note the style of the numbers

<img width="195" alt="screen shot 2017-08-31 at 12 21 56" src="https://user-images.githubusercontent.com/159500/29918791-1996f3ac-8e47-11e7-80b5-4f3bbbbcb706.png">

**Comment by Snuffleupagus** [comment] 2017-08-31 10:31
Closing as duplicate of #8852.

**Closed by Snuffleupagus** 2017-08-31 10:31 UTC

**Comment by rijk** [comment] 2017-08-31 10:42
Sorry, I tried to do it one issue per problem, per your guidelines :(
