### ISSUE TITLE
Impossible to select text correctly (word by word display?)

### ISSUE THREAD

**Issue by zagoa** [mozilla/pdf.js#11252] opened 2019-10-16 14:05 UTC
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html
Configuration:
- Web browser and its version: Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- Operating system and its version: Ubuntu 18.04
- PDF.js version: 2.2.18
- Is a browser extension: false

Steps to reproduce the problem:
1. Select a `span` of the TextLayer and change the transparent color to red. 
2. Look at the end of the first page on the right corner the word *same*
3. You see the *e* is not drifting on the right and not exactly in place

What is the expected behavior?
Have words of TextLayer perfectly corresponding to the display layer. Like that we can select and copy past correctly the text. 

My question is : That is possible to render the TextLayer word by word to avoid this type of problem ? Where in the code I can tweak that if there is no option ?

**Comment by timvandermeij** [comment] 2019-10-16 22:05
Closing since this is a duplicate of #7865 and some other issues in the `4-text-selection` category. Basically making the text layer overlap exactly is not possible in all cases because of font differences or calculation differences. What we're doing now is a best-effort rendering. If there are specific issues, we track them in open issues, but since this question is about the general case, I would say: no, that most likely won't solve the issue, nor is it easily possible.

**Closed by timvandermeij** 2019-10-16 22:05 UTC

**Comment by zagoa** [comment] 2019-10-22 14:26
So after some days of digging into the code I achieve my goal by splitting the text after each space. Thank to that, the code can create little `span` and not a line `span`. The more little they are the more we are sticking to the canvas text.
My question is do you think there is problem to implement this type of solution (perf maybe ?) ? And maybe that could be implemented as optional. Could I have your opinion on that ? 


So in the code I add an attribute `containSpace` to the `textContentItem`. And if during the `buildTextContentItem` we detect a space this attribute change to true. Then in the `OPS.showSpacedText ` we flush content if `containSpace` is true. Like this we split the text in little pieces, and we have much better results during text selection.

_evaluator.js_
```
function ensureTextContentItem() {
        if (textContentItem.initialized) {
          return textContentItem;
        }
        textContentItem.containSpace = false;
       [...]
}

 function buildTextContentItem(chars) {
        var font = textState.font;
        var textChunk = ensureTextContentItem();

        var width = 0;
        var height = 0;
        var glyphs = font.charsToGlyphs(chars);
        for (var i = 0; i < glyphs.length; i++) {
          var glyph = glyphs[i];
          var glyphWidth = null;
          if (font.vertical && glyph.vmetric) {
            glyphWidth = glyph.vmetric[0];
          } else {
            glyphWidth = glyph.width;
          }

          var glyphUnicode = glyph.unicode;
          var NormalizedUnicodes = getNormalizedUnicodes();
          if (NormalizedUnicodes[glyphUnicode] !== undefined) {
            glyphUnicode = NormalizedUnicodes[glyphUnicode];
          }
          glyphUnicode = reverseIfRtl(glyphUnicode);

          var charSpacing = textState.charSpacing;
          if (glyph.isSpace) {
            var wordSpacing = textState.wordSpacing;
            charSpacing += wordSpacing;
            if (wordSpacing > 0) {
              addFakeSpaces(wordSpacing, textChunk.str);
            }
          }

          var tx = 0;
          var ty = 0;
          if (!font.vertical) {
            var w0 = glyphWidth * textState.fontMatrix[0];
            tx = (w0 * textState.fontSize + charSpacing) *
              textState.textHScale;
            width += tx;
          } else {
            var w1 = glyphWidth * textState.fontMatrix[0];
            ty = w1 * textState.fontSize + charSpacing;
            height += ty;
          }
          textState.translateTextMatrix(tx, ty);

          textChunk.str.push(glyphUnicode);

          if (glyphUnicode === ' ') {
            textChunk.containSpace = true;
          }

        }

        if (!font.vertical) {
          textChunk.lastAdvanceWidth = width;
          textChunk.width += width;
        } else {
          textChunk.lastAdvanceHeight = height;
          textChunk.height += Math.abs(height);
        }

        return textChunk;
      }

[...]
case OPS.showSpacedText:
              var items = args[0];
              var offset;
              for (var j = 0, jj = items.length; j < jj; j++) {
                if (typeof items[j] === 'string') {
                  buildTextContentItem(items[j]);
                  if (textContentItem.containSpace) {
                    flushTextContentItem();
                  }
                } else if (isNum(items[j])) {
                  ensureTextContentItem();

                  // PDF Specification 5.3.2 states:
                  // The number is expressed in thousandths of a unit of text
                  // space.
                  // This amount is subtracted from the current horizontal or
                  // vertical coordinate, depending on the writing mode.
                  // In the default coordinate system, a positive adjustment
                  // has the effect of moving the next glyph painted either to
                  // the left or down by the given amount.
                  advance = items[j] * textState.fontSize / 1000;
                  var breakTextRun = false;
                  if (textState.font.vertical) {
                    offset = advance;
                    textState.translateTextMatrix(0, offset);
                    breakTextRun = textContentItem.textRunBreakAllowed &&
                      advance > textContentItem.fakeMultiSpaceMax;
                    if (!breakTextRun) {
                      // Value needs to be added to height to paint down.
                      textContentItem.height += offset;
                    }
                  } else {
                    advance = -advance;
                    offset = advance * textState.textHScale;
                    textState.translateTextMatrix(offset, 0);
                    breakTextRun = textContentItem.textRunBreakAllowed &&
                      advance > textContentItem.fakeMultiSpaceMax;
                    if (!breakTextRun) {
                      // Value needs to be subtracted from width to paint left.
                      textContentItem.width += offset;
                    }
                  }
                  if (breakTextRun) {
                    flushTextContentItem();
                  } else if (advance > 0) {
                    addFakeSpaces(advance, textContentItem.str);
                  }

                  if (textContentItem.containSpace) {
                    flushTextContentItem();
                  }
                }
              }
[...]
```

**Comment by timvandermeij** [comment] 2019-10-22 21:21
Yes, this is basically what we tried to avoid in previous text layer patches because it turned out to be really expensive in terms of the number of DOM elements and their rendering. The heavier the DOM gets, the more trouble browsers have rendering it, causing scrolling delays and even memory issues. Unfortunately this solution is therefore not acceptable for the library itself, but depending on your use cases, it might be acceptable for your custom build.
