### ISSUE TITLE
Edge engine performance

### ISSUE THREAD

**Issue by kanaxz** [mozilla/pdf.js#7530] opened 2016-08-08 02:14 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Window store Universal App ( EdgeHTML and Chakra, like Edge )
- Operating system and its version: Windows 10 
- PDF.js version: 3.1.91
- Is an extension: no

Steps to reproduce the problem:
1.  Open a document in Chrome and Edge
2.  Print a document on both( to got the render process )
![print process](https://cloud.githubusercontent.com/assets/16597976/17467397/2b9eee70-5d1e-11e6-9a3d-2f9da6a650ec.png)
3.  See the difference of speed between Edge and Chrome

What is the expected behavior?
The point is, that Chrome is 200x faster compared to Edge to render & print a document containing 1000 pages 

What went wrong?
The print performances is a blocking point for my app.
Is there a way to increase the performances on Edge engine ? Like switching functions ?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2016-08-08 08:21
> Is there a way to increase the performances on Edge engine ? Like switching functions ?

Given that this is an issue with a particular browser, there's unfortunately not much that we can do about this in PDF.js. As mentioned in https://github.com/mozilla/pdf.js/issues/6350#issuecomment-223497065 (note also the suggested workaround there), the issue seems to be that the Promise implementation in Edge is/was very slow, compared to other browsers.
Closing as duplicate of issue #6350.

**Closed by Snuffleupagus** 2016-08-08 08:21 UTC
