### ISSUE TITLE
Unable to open hyperlink inside a pdf.

### ISSUE THREAD

**Issue by shravanipraharaj** [mozilla/pdf.js#15226] opened 2022-07-26 16:44 UTC
I have a pdf with links to external websites, It seems to be working fine in chrome browser and also in adobe, but when I try to open the same in firefox it wont open.
[sample.pdf](https://github.com/mozilla/pdf.js/files/9191763/sample.pdf)
http://www.ema.europa.eu - this is the link to the external website
Firefox version : 18.05

**Comment by Snuffleupagus** [comment] 2022-07-26 17:42
Duplicate of #3172

---

> Firefox version : 18.05

That's hopefully not correct, and if it it you *really* should update, since Firefox 18 was released in 2013.

**Closed by Snuffleupagus** 2022-07-26 17:42 UTC
