### ISSUE TITLE
PDF is blank in firefox 69.0 (64-bit)

### ISSUE THREAD

**Issue by jkester79** [mozilla/pdf.js#11140] opened 2019-09-11 18:32 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: FIREFOX 69.0 (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: Not sure how to determine the version of PDF.js since I believe it's built into Firefox
- Is a browser extension:

Steps to reproduce the problem:
1. open the attached PDF in firefox, get blank page
[Page.pdf](https://github.com/mozilla/pdf.js/files/3602225/Page.pdf)

2. Works fine in chrome and IE

What is the expected behavior? (add screenshot)
https://flic.kr/p/2he4M8w
What went wrong? (add screenshot)
https://flic.kr/p/2he4M8S

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-09-11 18:38
Duplicate of #11052.

**Closed** 2019-09-11 21:33 UTC
