### ISSUE TITLE
Search functionality is not working properly.

### ISSUE THREAD

**Issue by jigskpatel** [mozilla/pdf.js#9421] opened 2018-01-30 15:05 UTC
Attach (recommended) or Link to PDF file here:
[486561.pdf](https://github.com/mozilla/pdf.js/files/1678147/486561.pdf)

Configuration:
- **Web browser and its version:** Google Chrome : Version 63.0.3239.132 (Official Build) (64-bit)
- **Operating system and its version:** Windows 10 x64
- **PDF.js version:** 1.9.426
- **Is a browser extension:** No

 **Step For Reproduced The problem:**

1. Click on search button(Find in Document) of the top bar.
2. Enter text "MTX" in text field.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/11785531/35572753-52daf39e-05fb-11e8-89d5-235cec551177.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/11785531/35572623-025d752c-05fb-11e8-92f4-54123677e7eb.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by jigskpatel** [comment] 2018-02-01 10:43
@timvandermeij any update?

**Comment by timvandermeij** [comment] 2018-02-01 21:47
This is a known issue with some PDF files. There are similar other issues open. Anyone who is willing to look into the cause of this is welcome to.

**Comment by rossj** [comment] 2018-02-09 21:18
I looked into this briefly while dealing with other text selection issues. Most of the fonts in this PDF have a rather large `ascent` value, around 2500 glyph units. These large ascent values are then used to adjust the text divs' `top` position [here](https://github.com/mozilla/pdf.js/blob/7bb066494f3f15c396941c3532b83da6d3465c6b/src/display/text_layer.js#L87), causing the div misplacement that we see. Commenting out the font ascent / descent adjustment here provides much better text placement results for this PDF.

It seems to me that the ascent and descent values in this PDF are set incorrectly, as they are quite large and are also significantly different from the font bbox values. I also think the text div placement math needs some changes. Perhaps it should always consider the ascent and descent values together, e.g. by calculating a centerline based on them, instead of aligning based solely on the ascent value alone. Perhaps there should also be some sort of clamp to prevent wacky ascent / descent values from moving the text line too far from the baseline.

**Comment by timvandermeij** [comment] 2021-02-13 14:44
Closing since this is now fixed after recent text layer fixes.

**Closed by timvandermeij** 2021-02-13 14:44 UTC
Labels: 4-text-selection
