### ISSUE TITLE
Pinch to zoom out shows Tabs Overview in Safari

### ISSUE THREAD

**Issue by shivaprsd** [mozilla/pdf.js#14725] opened 2022-03-29 06:30 UTC
Pinch-out on trackpad reduces the zoom level, however the default action does
not seem to be prevented. Does not happen elsewhere e.g. Google maps.

I guess #2582 should be linked, could not find any mention about this there.

---

Attach (recommended) or Link to PDF file here: *Any pdf*

Configuration:
- Web browser and its version: *Safari 15.4*
- Operating system and its version: *macOS 11.6*
- PDF.js version: `pdfjsLib.version = 2.14.110`
- Is a browser extension: *No*

Steps to reproduce the problem:
1. Open any PDF in Safari on a Mac with trackpad
2. Pinch inwards to zoom out

What is the expected behavior? (add screenshot)
*Scale does get reduced.*

What went wrong? (add screenshot)
![pdfjs-bug](https://user-images.githubusercontent.com/18247990/160545727-59271ea2-af78-4940-8dce-eab1dddb99eb.gif)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): *NA*

**Comment by Snuffleupagus** [comment] 2022-03-29 08:37
Duplicate of #2582

(Since we currently don't support pinch-zooming, which that issue already tracks. Note also that Safari isn't the primary focus of development in this project.)

**Closed by Snuffleupagus** 2022-03-29 08:37 UTC

**Comment by shivaprsd** [comment] 2022-03-29 18:12
@Snuffleupagus 
Al right. But I do hope it gets addressed when you finally round off the feature.
