### ISSUE TITLE
PDF Viewer in Web not displaying content

### ISSUE THREAD

**Issue by jclgs** [mozilla/pdf.js#8019] opened 2017-02-02 16:18 UTC
Incorrect display on PDF file.

Configuration:
- Chrome/Firefox
- Windows/MAC
- PDF.js version: 1.4.20 - 1.6.210

**Bug #1**
The issue is on PDF using Symbol Layer in Illustrator. The issue is only in Chrome MAC/PC. It works well in Safari, Firefox, IE. You can see the good result in picture #1 in Adobe Reader and the bug in picture #2.
The first picture is from a PDF opened in AdobeReader. The second picture is with the PDF.js.

![image](https://cloud.githubusercontent.com/assets/24614035/22557398/6b9f4d52-e938-11e6-8bd4-3530dea02e0e.png)

As soon as we unlink Symbol Layer in Illustrator and generate a new PDF, the second picture with missing information is now printing the text in PDF.js.

Is it possible to get Symbol Layer working in Chrome. It works in IE, Fifefox, Safari but not Chrome, one of the most use browser.

**Bug #2** 
The second issue is related to MASK item in Illustrator. In Firefox, the MASK is not displayed correctly, but that time, in Chrome, it is working well. Look at the orange Circle in Firefox. In Firefox, it should be displayed like Chrome is doing.

![image](https://cloud.githubusercontent.com/assets/24614035/22557640/18c36a4a-e939-11e6-8094-cbfd61d1e87a.png)

If PDF is needed to debug, I can transfer them to you. Is this possible send those in private because they are business content.
Thanks
Jonathan

**Comment by yurydelendik** [comment] 2017-02-02 16:32
Can you try to disable hardware/GPU  acceleration 2d canvas in Chrome (via chrome://flags), see if it will fix the issue?

**Comment by yurydelendik** [comment] 2017-02-02 16:34
> If PDF is needed to debug, I can transfer them to you. Is this possible send those in private because they are business content.

Can you recreate them in smaller examples, e.g. by editing sensitive material in Illustrator?

**Comment by jclgs** [comment] 2017-02-02 18:10
Hello.

For Bug #1 in Chrome, if I disable Acceleration 2d canvas, it solves the issue. The only thing, I cannot ask all my customer to disable that feature. Is there a workaround or fix can be release.

For Bug #2 in Firefox, I will transfer you a example with sensitive data remove. I will ask one of our graphic artist to generate me a new PDF file.

Thanks

**Comment by yurydelendik** [comment] 2017-02-02 18:13
> For Bug #1 in Chrome, if I disable Acceleration 2d canvas, it solves the issue. The only thing, I cannot ask all my customer to disable that feature. Is there a workaround or fix can be release.

There no workaround, but narrows down the problem. But it maybe fixed in future Chrome versions. Also try to update video drivers. Can you also check if only your computer is affected?

**Comment by jclgs** [comment] 2017-02-02 18:22
Hi.

For Bug #1, the issue is in Chrome, PC/MAC. The issue is present on all computer, corporate computer, customer computer, MAC and PC. We have also a workaround on our side, it's to ask our graphic artist to Unlink Symbol Layer before generating their PDF file. We don't like that option because it's extra step for our graphic artist and also if they forgot to do it, our customer will get a wrong view of the PDF. I was thinking that a fix could be made.

For Bug #2, I'm waiting an example and will forward it to you.
Thanks

**Comment by yurydelendik** [comment] 2017-02-02 18:28
Looks like both issues are browsers specific, so need to be reported upstream. We can help to triage, but having example PDFs is a must. Having small example will speed up the process. Without ability to reproduce issues it's impossible to solve it or talk about a workaround.

> will forward it to you.

By "you", I hope, you don't mean me personally. Please attach the PDF(s) to this issue so other contributors might assist you.

**Comment by jclgs** [comment] 2017-02-02 18:56
Bug #2 
Here is a PDF not diplaying correctly into Firefox but works on all other browser.

[R9450_5_2_jersey.pdf](https://github.com/mozilla/pdf.js/files/748704/R9450_5_2_jersey.pdf)

**Comment by yurydelendik** [comment] 2017-02-02 19:02
@jclgs I cannot observe that on Firefox for Mac OSX. Could be something related to Firefox for Windows. Can you provide more information from graphics section from about:support ?

**Comment by yurydelendik** [comment] 2017-02-03 19:18
The Firefox issue looks like #8022, let's move Firefox-part issue there and keep this one for Chrome.

**Comment by jclgs** [comment] 2017-02-06 21:24
BUG #2

Hi.

Sorry for the late reply. I was working on an another bug and coming back from the weekend.

On my side, I discover that my problem is on all our Lenovo Laptop. One of my teammate is working on an HP Desktop computer and is not having the issue. I tested also with Firefox on a virtual machine, not having the issue. Tested also on BrowserStack and not having the issue.

I was able to get the issue solve on my laptop when I disable the INTEL HD Graphic driver and now in Windows 7 and my Firefox, it is working.

**Also need to mention that it was working on Windows 7 with Firefox version 47 and before and with INTEL HD Graphic Driver ENABLED**.

With INTEL HD Graphic driver and latest version of Firefox, we are getting the issue. The only way to get it working with Windows 7 and latest version of Firefox, it,s to disable the Intel HD Graphic driver and use Windows Driver.

Summary:
Win 7 + Firefox 47 and before + Intel HD Graphic Driver Enabled = Working
Win 7 + Firefox 51 + Intel HD Graphic Driver Enabled = Not Working
Win 7 + Firefox 51 + Windows Graphic Driver = Working

This is the result of all our tests.

Don't know where the issue is. Firefox, Intel HD Graphic Driver, PDF.js ?? I let you check your stuff, but what I can say, for Bug #2, this is always working in Chrome.

**Comment by jclgs** [comment] 2017-02-16 18:26
Bug #2
Any news with that. 

Did someone know if Firefox is working to find the bug? Firefox older version like 41, 47 is displaying the pdf correctly with latest version of pdf.js.

Thanks

**Comment by christianheimann** [comment] 2017-08-24 11:09
We had the described issue with svgs which were embedded in html on Firefox/Xul-Runner which was used in an eclipse RCP application. Using the userprefs.js and setting the property
`pref("gfx.direct2d.disabled", true)`
did the trick. All the hidden/missing line or miss interpretations are done now correctly.

**Comment by mepowerlmay** [comment] 2021-02-19 06:57
> Bug #2
> Any news with that.
> 
> Did someone know if Firefox is working to find the bug? Firefox older version like 41, 47 is displaying the pdf correctly with latest version of pdf.js.
> 
> Thanks

I try to remove Intel HD Graphic Driver 4600 , it is ok

**Comment by Snuffleupagus** [comment] 2021-12-04 07:36
WFM, using PDF.js version `2.12.248` in either Firefox Nightly 96 or Google Chrome Beta 97 on Windows.

**Closed by Snuffleupagus** 2021-12-04 07:36 UTC
Labels: 3-upstream, 4-chrome-specific
