### ISSUE TITLE
pdf parse garbled

### ISSUE THREAD

**Issue by 296500148** [mozilla/pdf.js#12772] opened 2020-12-23 12:34 UTC
Attach (recommended) or Link to PDF file here:
[example.pdf](https://github.com/mozilla/pdf.js/files/5735120/example.pdf)

Configuration:
- Web browser and its version:Chrome/70.0.3538.110
- Operating system and its version:windows 10  18363.1256
- PDF.js version:2.5.31
- Is a browser extension:false

Steps to reproduce the problem:
1. 

2.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/43374341/102996320-e4554280-455d-11eb-9fc7-0d45f552b8f7.png)
What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/43374341/102996473-27171a80-455e-11eb-96d7-5748f3bec3c6.png)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2020-12-23 12:40
Looks like a duplicate of #11798, note that (again) even Adobe Reader cannot render the document "correctly".

**Closed** 2020-12-28 18:40 UTC
