### ISSUE TITLE
Expose fragment IDs in the URL

### ISSUE THREAD

**Issue by BigBlueHat** [mozilla/pdf.js#5258] opened 2014-09-03 14:11 UTC
PDF.js uses fragment IDs for navigating within a PDF, but those fragment IDs are not exposed to the URL / browsing history. However, they are _usable_ directly from the location bar and even work with the PDF viewer included in Chrome 36 (with the exclusion of `page=123`).

Having these in the browsing history would mean that one could easily create links into specific sections of a PDF.

Here are some example URL's pulled from the source code--which I'd much have preferred to crib from the location bar. :smile_cat: 
PDF section identifier-based fragment ID (afaik):
http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/pdf_reference_1-7.pdf#G13.1696671

PDF.js "proprietary" `?page=#` style URL:
http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/pdf_reference_1-7.pdf#page=607

Thanks for consider this idea! :bulb:

**Comment by andrenarchy** [comment] 2015-03-31 16:45
I proposed to place a `div` for each named destination at the corresponding position in #5892 where the `id` attribute is set based on the name. Links could then simply point to these divs via the hash part of the URL. What do you think?

**Comment by Snuffleupagus** [comment] 2015-03-31 18:23
@andrenarchy As explained in https://github.com/mozilla/pdf.js/issues/5258#issuecomment-54633345, HTML links are *not* identical to the destinations used in PDF files.
First of all, the PDF specification supports both "named" and "explicit" destinations, please refer to the links in https://github.com/mozilla/pdf.js/issues/5258#issuecomment-54633345, and both kinds are used in practice.
Secondly both kind of destinations can also, apart from specifying a page/position, set the zoom level of the document (both directly and indirectly, again see the links above).
I hope that the above is enough to explain why implementing what you are suggest is unfortunately not going to be possible.

Finally, in PDF.js we only render the currently visible pages, for performance and memory reasons. If your suggestion was implemented, that would mean that links wouldn't work unless the page had already been rendered.

**Comment by andrenarchy** [comment] 2015-04-01 10:21
Thx @Snuffleupagus for your explanation! Now I understand why my proposal isn't a good idea.

I'll try to see why links don't work in my viewer-based application. Probably only the scrolling part doesn't work...

**Comment by Snuffleupagus** [comment] 2019-01-19 12:35
@timvandermeij Let's just close this as a duplicate of #5753, since these issues are similar enough and the (optional) functionality from PR #10423 is the only thing we could/should do here.

**Closed** 2019-01-19 13:58 UTC
Labels: 1-viewer, 2-feature
