### ISSUE TITLE
Fonts are not loading

### ISSUE THREAD

**Issue by Anand-setty** [mozilla/pdf.js#8929] opened 2017-09-19 11:37 UTC
Link to PDF file (or attach file here):
[document (2).pdf](https://github.com/mozilla/pdf.js/files/1314047/document.2.pdf)

Configuration:
- Web browser and its version: Chrome Version 60.0.3112.113 (Official Build) (64-bit)
- Operating system and its version: Mac OS sierra 10.12
- PDF.js version: Latest
- Is an extension:

Steps to reproduce the problem:
1. Open the attached file in the pdf js viewer(https://mozilla.github.io/pdf.js/web/viewer.html).
2. Getting below errors
Warning: Failed to load font "g_d1_f1": SyntaxError: Invalid font data in ArrayBuffer.
util.js:276 Warning: Failed to load font "g_d1_f7": SyntaxError: Invalid font data in ArrayBuffer.
util.js:276 Warning: Failed to load font "g_d1_f13": SyntaxError: Invalid font data in ArrayBuffer.

What is the expected behavior? (add screenshot)
<img width="1378" alt="screen shot 2017-09-19 at 5 07 18 pm" src="https://user-images.githubusercontent.com/16985967/30590620-05c8522e-9d5d-11e7-9628-9df7d48cce36.png">

What went wrong? (add screenshot)
<img width="1402" alt="screen shot 2017-09-19 at 5 06 32 pm" src="https://user-images.githubusercontent.com/16985967/30590665-375f819a-9d5d-11e7-98de-efba431a20bf.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-09-19 11:44
Closing as duplicate of #7507 (and #8710).

**Closed by Snuffleupagus** 2017-09-19 11:44 UTC
