### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#7420] opened 2016-06-16 10:38 UTC
Link to PDF file (or attach file here): https://indico.cern.ch/event/506415/contributions/2205899/attachments/1292661/1926029/lhc-mm-16JUN16_WH.pdf

Configuration:
- Web browser and its version: Chrome Version 53.0.2768.0 canary (64-bit)
- Operating system and its version: Win 10, 1511, 64b, Build 10586.420
- PDF.js version: 1.5.294
- Is an extension: Yes

Steps to reproduce the problem:
1. Click the link
2.

What is the expected behavior? (add screenshot)
Link opens

What went wrong? (add screenshot)
Crash (Aw, snap!)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2016-06-16 10:51
It sounds like this probably is a duplicate of issue #7395, and furthermore it's likely to be a Chrome issue rather than a PDF.js issue. I'd suggest following the advice in https://github.com/mozilla/pdf.js/issues/7395#issuecomment-225233493, i.e `Does it happen on older versions of chrome, if not, probably it's a good time to bisect the regression?`, to try and pinpoint the issue. Closing as duplicate of issue #7395 for now.

**Closed by Snuffleupagus** 2016-06-16 10:51 UTC

**Comment by qwer1304** [comment] 2016-06-16 10:57
I'm not sure it is the same.
I set up the default zoom to 50% in options.
Then clicked the link.
I can see the file loading with "Automatic Zoom", then it briefly flashes "50%" zoom and then it crashes.
