### ISSUE TITLE
Blank PDF on Firefox (Windows) but displays correctly on Firefox (Mac)

### ISSUE THREAD

**Issue by JakobWyatt** [mozilla/pdf.js#15621] opened 2022-10-25 03:55 UTC
Attach (recommended) or Link to PDF file here:
[pdf_bug_ex.pdf](https://github.com/mozilla/pdf.js/files/9856958/pdf_bug_ex.pdf)
This is one page from a larger, sensitive pdf.

Configuration:
- Web browser and its version: Firefox 106.0.1
- Operating system and its version: Windows 10 22H2 (Also broken on Windows 10 21H2).
- PDF.js version: Using built in PDF viewer.

Steps to reproduce the problem:
1. Open PDF in built-in Firefox PDF viewer on Windows.

What is the expected behavior?
Displays text. Renders correctly in Adobe Acrobat, Google Chrome, and Firefox 106.0.1 on Mac.
<img width="320" alt="correct" src="https://user-images.githubusercontent.com/14144056/197678370-9944b216-f2e4-43db-a0f5-81ee8fa556ce.PNG">

What went wrong?
Blank page. Other pages from full document had strange symbols (E020 character)
<img width="441" alt="broken" src="https://user-images.githubusercontent.com/14144056/197678085-202b050f-236f-483b-a560-0e493bdcbc78.PNG">

**Comment by Snuffleupagus** [comment] 2022-10-25 07:05
Duplicate of #15289

---

Please note https://github.com/mozilla/pdf.js/issues/15289#issuecomment-1222203041 in particular.

**Closed by Snuffleupagus** 2022-10-25 07:05 UTC
