### ISSUE TITLE
Unknown IR type: Shading

### ISSUE THREAD

**Issue by dengBox** [mozilla/pdf.js#14473] opened 2022-01-20 09:48 UTC
Attach (recommended) or Link to PDF file here:
[1.pdf](https://github.com/mozilla/pdf.js/files/7903968/1.pdf)

Configuration:
- Web browser and its version: Google Chrome  97.0.4692.71
- Operating system and its version: masOS Big Sur 11.01
- PDF.js version: 2.6.347
- Is a browser extension:

Steps to reproduce the problem:
1. `pdfjs.getDocument(...).getPage(1)`
2.` page.getOperatorList()`
3.`pdfjs.SVGGraphics(page.commonObjs, page.objs)`

What is the expected behavior? (add screenshot)
Normal operation
What went wrong? (add screenshot)
Error: Unknown IR type: Shading
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-01-20 10:03
> PDF.js version: 2.6.347

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

Furthermore, as already mentioned in the FAQ, the SVG-backend is *not officially supported*; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

**Comment by Snuffleupagus** [comment] 2022-01-20 10:07
Duplicate of #8045

**Closed by Snuffleupagus** 2022-01-20 10:07 UTC
