### ISSUE TITLE
PDF Rendering Issues on iPad - iOs 10.3.3 Safari

### ISSUE THREAD

**Issue by anandpanse123** [mozilla/pdf.js#9092] opened 2017-10-31 19:55 UTC
Attach (recommended) or Link to PDF file here:
http://hosted.rightprospectus.com/documents/Alliance_Bernstein/Factsheets/fs_bro.pdf

Configuration:
- Web browser and its version: iPad - iOs 10.3.3 Safari
- Operating system and its version: iOs 10.3.3
- PDF.js version: latest
- Is a browser extension: NA

Steps to reproduce the problem:
1. Open PDF file ( http://hosted.rightprospectus.com/documents/Alliance_Bernstein/Factsheets/fs_bro.pdf
) in Pdf Js Viewer on iPad - iOs 10.3.3 Safari
2. PDF Rendering Issues on Page 3 and 4. Invalid special symbols are getting displayed.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/33266067/32245885-a5084e90-be53-11e7-963f-45b149408c8b.png)

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/33266067/32245876-991ed64e-be53-11e7-8232-20f9ae5a2345.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-10-31 20:00
Closing as duplicate of #8267.

**Closed by Snuffleupagus** 2017-10-31 20:00 UTC
