### ISSUE TITLE
the newest version of pdfjs-dist - error Runtime error - TypeError: Cannot read properties of undefined (reading 'AnnotationEditorType')

### ISSUE THREAD

**Issue by OkaSroka** [mozilla/pdf.js#16803] opened 2023-08-08 09:47 UTC
Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows 11
- PDF.js version: 3.9.179

Steps to reproduce the problem:
1. Runtime error - TypeError: Cannot read properties of undefined (reading 'AnnotationEditorType')
2. AnnotationEditorType seems to be imported not correctly

**Comment by Snuffleupagus** [comment] 2023-08-08 09:50
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by foodornt** [comment] 2023-08-08 15:40
> Have the same issue. v3.8.162 works great but the new version v3.9.179 has such an error (chrome):
> 
> ```
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'PromiseCapability')
>     at PDFFindController.reset_fn (:8083/node_modules/.vite/deps/pdfjs-dist_web_pdf_viewer.js?v=f3edd46e:407:57)
>     at new PDFFindController (:8083/node_modules/.vite/deps/pdfjs-dist_web_pdf_viewer.js?v=f3edd46e:268:57)
> ```
> 
> More useful error message from firefox:
> 
> ```
> Uncaught (in promise) TypeError: _pdfjsLib is undefined
>     reset_fn pdf_find_controller.js:591
>     PDFFindController pdf_find_controller.js:405
> ```

try importing this way:
`import * as pdfjs from "pdfjs-dist"`
instead of
`importpdfjs from "pdfjs-dist"`

**Comment by r331** [comment] 2023-08-08 15:51
> try importing this way: `import * as pdfjs from "pdfjs-dist"` instead of `importpdfjs from "pdfjs-dist"`

I have only such code 

`import { PDFFindController } from "pdf-dist/web/pdf_viewer" `

**Comment by Snuffleupagus** [comment] 2023-08-08 16:43
Duplicate of #16778 (which is the best guess given the lack of a runnable example).

**Closed by Snuffleupagus** 2023-08-08 16:43 UTC
Labels: information-requested

**Comment by Blackfaded** [comment] 2023-08-10 10:25
> > try importing this way: `import * as pdfjs from "pdfjs-dist"` instead of `importpdfjs from "pdfjs-dist"`
> 
> I have only such code
> 
> `import { PDFFindController } from "pdf-dist/web/pdf_viewer" `

Having the exact same issue.
This is my code
```ts
import { getDocument, GlobalWorkerOptions } from 'pdfjs-dist';
import type { DocumentInitParameters } from 'pdfjs-dist/types/src/display/api';
import { EventBus, PDFFindController, PDFLinkService, PDFViewer } from 'pdfjs-dist/web/pdf_viewer';
import { TypedEmitter } from 'tiny-typed-emitter';

import 'pdfjs-dist/web/pdf_viewer.css';
import { pdfRendererUrls } from '@/libs/shared/components/pdfviewer/pdfRendererUrls';

// TODO: Refactor whem migration to vitest is complete to the following:
// GlobalWorkerOptions.workerPort = new Worker(new URL('pdfjs-dist/build/pdf.worker.js', import.meta.url));
GlobalWorkerOptions.workerSrc = pdfRendererUrls.workerSrc;
interface MyClassEvents {
  page: (value: number) => void;
  pages: (value: number) => void;
  scale: (value: number) => void;
  matchescount: (value: MatchesCount) => void;
  initialized: () => void;
}
type EventBusDispatch = {
  find: FindDispatchEventPayload;
};

type EventBusOn = {
  pagesinit: PdfEvent;
  pagechanging: PageChangeEvent;
  scalechanging: ScaleChangeEvent;
  updatefindmatchescount: FindMatchesCountEvent;
  updatefindcontrolstate: FindMatchesCountEvent;
};

interface FindDispatchEventPayload {
  type: '' | 'again';
  query: string;
  highlightAll?: boolean;
  phraseSearch?: boolean;
  findPrevious: boolean;
  entireWord?: boolean;
}

interface PdfEvent {
  source: PDFViewer;
}

interface PageChangeEvent extends PdfEvent {
  pageNumber: number;
  pageLabel: string | null;
  previous: number;
}

interface ScaleChangeEvent extends PdfEvent {
  scale: number;
  presentValue?: number;
}

export interface MatchesCount {
  current: number;
  total: number;
}
interface FindMatchesCountEvent extends PdfEvent {
  matchesCount: MatchesCount;
}

export type SearchType = 'initial' | 'previous' | 'next';

export type PdfRendererScale = number | 'page-width' | 'page-height';

interface PdfRendererOptions {
  src: string | ArrayBuffer;
  initialScale: PdfRendererScale;
}

export class PdfRenderer extends TypedEmitter<MyClassEvents> {
  private pdfViewer: PDFViewer;

  private eventBus = new EventBus();

  // (Optionally) enable hyperlinks within PDF files.
  private pdfLinkService = new PDFLinkService({
    eventBus: this.eventBus,
  });

  // (Optionally) enable find controller.
  private pdfFindController = new PDFFindController({
    eventBus: this.eventBus,
    linkService: this.pdfLinkService,
    updateMatchesCountOnProgress: true,
  });

  private pageWidthScale = 1;
  private pageHeightScale = 1;

  constructor(
    private container: HTMLDivElement,
    private options: PdfRendererOptions,
  ) {
    super();

    this.pdfViewer = new PDFViewer({
      container: this.container,
      eventBus: this.eventBus,
      linkService: this.pdfLinkService,
      findController: this.pdfFindController,
      // @ts-expect-error
      l10n: null,
    });

    this.pdfLinkService.setViewer(this.pdfViewer);

    this.initPdf();
    this.initEvents();
  }

  private initPdf = async () => {
    const options: DocumentInitParameters = {
      rangeChunkSize: 512 * 1024,
      disableAutoFetch: true,
      disableStream: true,
      standardFontDataUrl: pdfRendererUrls.standardFontDataUrl,
      cMapUrl: pdfRendererUrls.cMapUrl,
      cMapPacked: pdfRendererUrls.cMapUrl !== undefined,
    };
    if (typeof this.options.src !== 'string') {
      options.data = new Uint8Array(this.options.src);
    } else {
      options.url = this.options.src;
    }
    const loadingTask = getDocument(options);

    const pdfdata = await loadingTask.promise;

    this.pdfViewer.setDocument(pdfdata);
    this.pdfLinkService.setDocument(pdfdata, null);
  };

  private initEvents = () => {
    this.eventBusOn('pagesinit', e => {
      const viewport = this.getCurrentPage().viewport;
      this.pageWidthScale = this.pdfViewer.container.clientWidth / viewport.width;
      this.pageHeightScale = this.pdfViewer.container.clientHeight / viewport.height;
      this.setScale(this.options.initialScale);

      this.emit('pages', e.source.pagesCount);
      this.emit('initialized');
    });

    this.eventBusOn('pagechanging', e => {
      this.emit('page', e.pageNumber);
    });
    this.eventBusOn('scalechanging', e => {
      this.emit('scale', e.scale);
    });
    this.eventBusOn('updatefindmatchescount', e => {
      this.emit('matchescount', e.matchesCount);
    });
    this.eventBusOn('updatefindcontrolstate', e => {
      this.emit('matchescount', e.matchesCount);
    });
  };

  private getCurrentPage = () => {
    return this.pdfViewer.getPageView(this.pdfViewer.currentPageNumber - 1);
  };

  private eventBusDispatch = <T extends keyof EventBusDispatch>(event: T, payload: EventBusDispatch[T]) => {
    this.eventBus.dispatch(event, payload);
  };

  private eventBusOn = <T extends keyof EventBusOn>(event: T, payload: (payload: EventBusOn[T]) => void) => {
    this.eventBus.on(event, payload);
  };

  // public methods
  get scale() {
    return this.pdfViewer.currentScale;
  }

  get isScaledPageWidth() {
    return this.scale === this.pageWidthScale;
  }

  get isScaledPageHeight() {
    return this.scale === this.pageHeightScale;
  }

  setScale = (scale: PdfRendererScale) => {
    if (typeof scale === 'string') {
      if (scale === 'page-width') {
        this.pdfViewer.currentScale = this.pageWidthScale;
        return;
      }
      if (scale === 'page-height') {
        this.pdfViewer.currentScale = this.pageHeightScale;
        return;
      }
    }
    this.pdfViewer.currentScale = scale;
  };

  setPage = (page: number) => {
    this.pdfViewer.currentPageNumber = page;
  };

  search = (query: string, type: SearchType) => {
    this.eventBusDispatch('find', {
      type: type === 'initial' ? '' : 'again',
      query,
      highlightAll: true,
      phraseSearch: true,
      findPrevious: type === 'previous',
    });
  };
}
```

```ts
import { version } from 'pdfjs-dist';

const cdnBasePath = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${version}`;

export const pdfRendererUrls = {
  workerSrc: `${cdnBasePath}/build/pdf.worker.js`,
  cMapUrl: `${cdnBasePath}/cmaps/`,
  standardFontDataUrl: `${cdnBasePath}/standard_fonts/`,
};
```

**Comment by calixteman** [comment] 2023-08-10 10:38
I don't really understand why you're adding some comments related to the error `Cannot read properties of undefined (reading 'PromiseCapability')` when the title of this **closed** issue is `Cannot read properties of undefined (reading 'AnnotationEditorType')`.
So please open a new bug and avoid to add some useless noise to this one: thank you.

**Comment by OkaSroka** [comment] 2023-08-16 06:43
This is my code:
`  import { Component, Vue, Prop } from 'vue-property-decorator';
  import * as pdfjsLib from 'pdfjs-dist/build/pdf.js';
  import {
    NullL10n,
    EventBus,
    PDFLinkService,
    PDFViewer,
    PDFSinglePageViewer
  } from 'pdfjs-dist/web/pdf_viewer.js';

  pdfjsLib.GlobalWorkerOptions.workerSrc = new URL(
    'pdfjs-dist/build/pdf.worker.js',
    import.meta.url
  );`

Do I import something wrongy, I have checked this:
https://github.com/mozilla/pdf.js/blob/master/examples/components/singlepageviewer.html
and it looks same for me
I am not even importing this AnnotationEditorType - it looks like it is library issue
Error:
`Runtime error - TypeError: Cannot read properties of undefined (reading 'AnnotationEditorType')
    at new PDFViewer (pdf_viewer.js:198:27)
    at VueComponent.getAllPagesPdf (CPdfPreview.vue:60:1)
    at VueComponent.getPdf (CPdfPreview.vue:56:1)
    at VueComponent.mounted (CPdfPreview.vue:111:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:3017:61)
    at callHook$1 (vue.runtime.esm.js:4031:13)
    at Object.insert (vue.runtime.esm.js:4423:13)
    at invokeInsertHook (vue.runtime.esm.js:6942:38)
    at VueComponent.patch2 [as __patch__] (vue.runtime.esm.js:7153:9)
    at Vue2._update (vue.runtime.esm.js:3769:25)`
    
    and it is redirecting me to this place in pdf_viewer.js
`    #annotationEditorMode = AnnotationEditorType.NONE;`

**Comment by atrinker** [comment] 2023-10-20 21:14
Has anyone found a resolution to this issue? I'm inclined to agree with @OkaSroka that this is a library issue.

I have received both the "AnnotationEditorType" and "PromiseCapability" errors discussed above.

Note that I did not receive any errors on my code (below) prior to updating pdfjs-dist from version 3.6.172. I would remain on that version, but my program requires access to the new annotation editor features that have been added in recent versions.

I receive the errors when attempting to create new PDFFindController/PDFViewer objects with the below code

`import { EventBus, PDFLinkService, PDFFindController, PDFViewer } from "pdfjs-dist/web/pdf_viewer";

function createPDFViewer(pdfDoc: pdfDocObject){
        if(!pdfDoc.pdfViewer){
           
            var viewer = pdfDoc.viewer;
            viewer.style.display = "block";
            const container = document.getElementById('viewerContainer') as HTMLDivElement;
            const eventBus = new EventBus();
            const pdfLinkService = new PDFLinkService({
                eventBus,
            });
            const pdfFindController = new PDFFindController({
                eventBus,
                linkService: pdfLinkService,
            });
            const pdfViewerInstance = new PDFViewer({
                container,
                viewer,
                eventBus: eventBus,
                findController: pdfFindController,
                linkService: pdfLinkService
            });
            pdfViewerInstance.setDocument(pdfDoc.pdf);
            pdfLinkService.setDocument(pdfDoc.pdf);
            pdfFindController.setDocument(pdfDoc.pdf);
            pdfLinkService.setViewer(pdfViewerInstance);
}}`



`pdf_find_controller.js:591 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'PromiseCapability')
    at PDFFindController.reset_fn (pdf_find_controller.js:591:37)
    at new PDFFindController (pdf_find_controller.js:405:5)
    at createPDFViewer (PDFViewerApp.tsx:273:39)
    at PDFViewerApp.tsx:141:21
    at Array.forEach (<anonymous>)
    at Object.fn (PDFViewerApp.tsx:136:27)
    at runComputation (dev.js:777:22)
    at updateComputation (dev.js:756:3)
    at runTop (dev.js:869:7)
    at runUserEffects (dev.js:982:36)

pdf_viewer.js:204 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'AnnotationEditorType')
    at new PDFViewer (pdf_viewer.js:204:27)
    at createPDFViewer (PDFViewerApp.tsx:276:39)
    at PDFViewerApp.tsx:140:21
    at Array.forEach (<anonymous>)
    at Object.fn (PDFViewerApp.tsx:135:27)
    at runComputation (dev.js:777:22)
    at updateComputation (dev.js:756:3)
    at runTop (dev.js:869:7)
    at runUserEffects (dev.js:982:36)
    at dev.js:938:34
`

While digging around the library, I noticed that both AnnotationEditorType and PromiseCapability are exported from "pdfjs-dist/build/pdf.js."  I'm not sure if that hints at a common source of the issue, but thought I'd note it regardless.

**Comment by Jayraj-R** [comment] 2024-01-18 12:34
@OkaSroka Getting the same issue on calling `new PdfViewer`. Did you find a workaround?

**Comment by kabirulhassan** [comment] 2024-01-22 07:15
I just deleted node modules and reinstalled, and the issue was fixed.
