### ISSUE TITLE
White spots when rendering PDFs

### ISSUE THREAD

**Issue by frokohl** [mozilla/pdf.js#16000] opened 2023-02-03 16:22 UTC
I opened this issue again, after updating to a newer version did not solve the problem.

Attach (recommended) or Link to PDF file here:
[03_Zeugnis.pdf](https://github.com/mozilla/pdf.js/files/10580696/03_Zeugnis.pdf)

Configuration:
Chrome Version: 103.0.5060.134 (Offizieller Build) (64-Bit)
PDF.js Version: 3.1.81
Operating system:
Edition	Windows 11 Pro
Version	21H2
Betriebssystembuild	22000.795
Leistung	Windows Feature Experience Pack 1000.22000.795.0

We render the PDF within a custom solution.
Is a browser extension: no

Steps to reproduce the problem:
1. Render PDF in Browser

What is the expected behavior? (add screenshot)
Display fully readable PDF

What went wrong? (add screenshot)
White spots on the PDF preview 
![160809442-c3ee0cf9-8c1e-4f96-a90c-e3ae9e3ffa89](https://user-images.githubusercontent.com/22612550/216654115-f2f103e0-a175-4533-859a-c05d4eed812a.png)

Link to a viewer (if hosted on a site other than [mozilla.github.io/pdf.js](http://mozilla.github.io/pdf.js) or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-02-03 16:30
Duplicate of #14641

**Closed by Snuffleupagus** 2023-02-03 16:30 UTC
