### ISSUE TITLE
Text-selection error in double-column PDF

### ISSUE THREAD

**Issue by iamCristYe** [mozilla/pdf.js#8408] opened 2017-05-15 16:56 UTC
Link to PDF file (or attach file here):
[Nat Struct Mol Biol 2008 Zenklusen.pdf](https://github.com/mozilla/pdf.js/files/975293/Nat.Struct.Mol.Biol.2008.Zenklusen.pdf)

Configuration:
- Web browser and its version: Chrome 58.0.3029.96
- Operating system and its version: Windows 15063.250
- PDF.js version: 1.7.225
- Is an extension: No

Steps to reproduce the problem:
1. double click any word at the end of a line

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/12642018/26068961/43031646-3954-11e7-85f8-89301e40dbd8.png)

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/12642018/26069011/63f26cb2-3954-11e7-9852-39e0e1335858.png)

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/12642018/26069024/6fade220-3954-11e7-857d-fbb4f9fd4e98.png)

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/12642018/26069056/858add78-3954-11e7-9049-8af1bce9fea3.png)

**Comment by huntersnk** [comment] 2017-05-20 03:38
I have the same issue.

**Comment by hubgit** [comment] 2018-01-09 08:14
This issue also occurs in single-column PDFs (see #9341).

**Comment by Ayassaka** [comment] 2020-05-14 21:53
This problem is likely to be caused by different selection policy of Chrome on adjacent `position: absolute` containers. Injecting a `<br>` after every text element seems to fix this.

**Comment by timvandermeij** [comment] 2021-02-13 15:17
Closing since this is a duplicate of #6678.

**Closed by timvandermeij** 2021-02-13 15:17 UTC
Labels: 4-chrome-specific, 4-text-selection
