### ISSUE TITLE
Large image pdf's beyond 120cm in original scanning width not displaying

### ISSUE THREAD

**Issue by veratechnz** [mozilla/pdf.js#14855] opened 2022-04-29 04:16 UTC
Attach (recommended) or Link to PDF file here:
https://archives.cityofsydney.nsw.gov.au/nodes/view/1450926

Configuration:
- Web browser and its version: Chrome latest
- Operating system and its version: Windows 10 latest
- PDF.js version: Latest 2.13.216
- Is a browser extension: No

Steps to reproduce the problem:
1. See in link: https://archives.cityofsydney.nsw.gov.au/nodes/view/1450926

What is the expected behavior? (add screenshot)
To display working picture of pdf
What went wrong? (add screenshot)
Only white blank screen displayed. Pdf, which is a large image works on other viewers (adobe acrobat, google chrome native viewer).
This pdf has a original scan size of pages are 1205mm x 920mm and is above 350ppi. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://archives.cityofsydney.nsw.gov.au/nodes/view/1450926

**Comment by Snuffleupagus** [comment] 2022-04-29 07:21
Duplicate of #6741

---

Also, please bring the following information to the attention of the website http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Closed by Snuffleupagus** 2022-04-29 07:21 UTC
