### ISSUE TITLE
Document loading on page 2 instead of 1

### ISSUE THREAD

**Issue by econolution** [mozilla/pdf.js#10449] opened 2019-01-13 22:45 UTC
URL: https://mozilla.github.io/pdf.js/web/viewer.html?file=https://s3.amazonaws.com/townlife_production/public/uploads/bylaws/995/Bylaw_1152_10.pdf#zoom=auto

Configuration:
- Web browser and its version: reproduced on firefox and safari (not browser dependant)
- PDF.js version: we are using 1.7.225 but bug still happens with your URL (see above)

Steps to reproduce the problem:
1.  Load URL 
2. Starts on page 2 of 4, not page 1 as expected (and desired)

Attempts for force page with url: https://mozilla.github.io/pdf.js/web/viewer.html?file=https://s3.amazonaws.com/townlife_production/public/uploads/bylaws/995/Bylaw_1152_10.pdf#zoom=auto#page=1 results in loading on page 3/4 instead of 1 is there a way to hardcode the starting page in the url?

**Comment by econolution** [comment] 2019-01-13 23:12
Well, now I found https://github.com/mozilla/pdf.js/wiki/Viewer-options which helps but raises a need for updating the documentation...

FAILS (to load doc on page 1 of 4)= https://mozilla.github.io/pdf.js/web/viewer.html?file=https://s3.amazonaws.com/townlife_production/public/uploads/bylaws/995/Bylaw_1152_10.pdf#zoom=auto 

FAILS (to load doc on page 1 of 4) = https://mozilla.github.io/pdf.js/web/viewer.html?file=https://s3.amazonaws.com/townlife_production/public/uploads/bylaws/995/Bylaw_1152_10.pdf#zoom=auto&page=1

LOADS CORRECTLY = https://mozilla.github.io/pdf.js/web/viewer.html?file=https://s3.amazonaws.com/townlife_production/public/uploads/bylaws/995/Bylaw_1152_10.pdf#page=1

BUT can I trust automatic zoom is the default?  == > unknown declaration and documentation does not state which is the default on https://github.com/mozilla/pdf.js/wiki/Viewer-options

Specifically
"zoom: zoom level. Example: zoom=200 (accepted formats: `[zoom],[left],[top]`, `page-width`, `page-height`, `page-fit`, `auto`)" is poor documentation
does this mean the variations are
zoom=200 (for 200% zoom)
zoom=page-fit
zoom=auto
zoom=page-height
what is the syntax for left and top?
left=auto? = unknown what left/top are or their example syntax
what is the default??

**Comment by Snuffleupagus** [comment] 2021-11-07 17:36
Duplicate of #10163

**Closed by Snuffleupagus** 2021-11-07 17:36 UTC
Labels: 1-viewer
