### ISSUE TITLE
app.launchUrl links not working in Chrome or Firefox. They do work in IE

### ISSUE THREAD

**Issue by banjahman** [mozilla/pdf.js#8445] opened 2017-05-25 13:46 UTC
Link to PDF file (or attach file here):
https://content.highmarkprc.com/Files/EducationManuals/ProviderTraining/fdr-medicare-general-compliance-training.pdf 

Link to PDF file within PDF.js viewer
https://dev.highmarkprc.com/pdfviewer/web/viewer.html?file=ViewPdf.aspx%3Furl%3Dhttps%3A%2F%2Fcontent.highmarkprc.com%2FFiles%2FEducationManuals%2FProviderTraining%2Ffdr-medicare-general-compliance-training.pdf

Configuration:
- Web browser and its version: Chrome 58.0.3029.110 (64-bit)
- Operating system and its version: Windows 7
- PDF.js version: 1.8.384
- Is an extension: Yes/No

Steps to reproduce the problem:
1. On page 15 of the document there are 2 links (Medicare Parts C and D .., etc). These links are meant to open in a new window. The code is: app.launchURL("url", true);
2. When viewed in IE using the default PDF viewer these links open just fine. When viewed in IE using the PDF.js viewer they also work. When viewed in Firefox (using the PDF.js plugin) they do not work. When viewed in Chrome using the PDF.js plugin, they do not work.

What is the expected behavior?
Links should open in a new window, or at least open.

What went wrong?
Links do not open in Chrome or Firefox using the PDF.js plugin or viewer

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://dev.highmarkprc.com/pdfviewer/web/viewer.html?file=ViewPdf.aspx%3Furl%3Dhttps%3A%2F%2Fcontent.highmarkprc.com%2FFiles%2FEducationManuals%2FProviderTraining%2Ffdr-medicare-general-compliance-training.pdf

**Comment by Snuffleupagus** [comment] 2017-05-25 14:59
I cannot reproduce this, using Firefox Nightly 55 (buildID: 20170525030225) on Windows.

> https://content.highmarkprc.com/Files/EducationManuals/ProviderTraining/fdr-medicare-general-compliance-training.pdf

This works fine for me, using Firefox Nightly 55, with the latest version (1.8.384) of the PDF.js addon.

> https://dev.highmarkprc.com/pdfviewer/web/viewer.html?file=ViewPdf.aspx%3Furl%3Dhttps%3A%2F%2Fcontent.highmarkprc.com%2FFiles%2FEducationManuals%2FProviderTraining%2Ffdr-medicare-general-compliance-training.pdf

This works fine for me, using either Firefox Nightly 55 or Google Chrome Beta 59.

**Comment by Snuffleupagus** [comment] 2017-06-08 08:54
> Link to PDF file (or attach file here):
> https://content.highmarkprc.com/Files/EducationManuals/ProviderTraining/fdr-medicare-general-compliance-training.pdf

> On page 15 of the document there are 2 links (Medicare Parts C and D .., etc). These links are meant to open in a new window. The code is: app.launchURL("url", true);

First of all, it appears that the PDF file may have been changed on the server, since the current PDF document *only* contains 14 pages.
Second of all, PDF.js does support `app.launchURL` links (provided that they contain valid absolute URLs), and I wasn't able to reproduce any of the reported issues when testing previously.

Based on the above, closing the issue as WORKSFORME.

**Closed by Snuffleupagus** 2017-06-08 08:54 UTC
Labels: 4-triage-needed
