### ISSUE TITLE
Crashing Browser: Throwing Aww Snap

### ISSUE THREAD

**Issue by chandrika14** [mozilla/pdf.js#9902] opened 2018-07-19 10:36 UTC
http://jsfiddle.net/pdfjs/wagvs9Lf/?utm_source=website&utm_medium=embed&utm_campaign=wagvs9Lf

Configuration:
- Chrome 67.0.3396.87
- Android 8.1.0
- PDF.js version: 2.0.690

Steps to reproduce the problem:
1. Attaching link which I am referring for device. While loading on mobile it shows aww snap but similar is working fine on desktop.

**Comment by Vishnupriya112** [comment] 2018-07-20 07:18
Am also facing this problem in my application , And I am using 2012 version

**Comment by Vishnupriya112** [comment] 2018-07-23 05:58
@chandrika14 @timvandermeij  Have you find any solution to fix this issue.

**Comment by Vishnupriya112** [comment] 2018-07-23 06:16
![crash](https://user-images.githubusercontent.com/38549946/43060314-f636fcb8-8e6d-11e8-9d0c-f8f8049b7755.png)
 Am getting like this while loading the page

**Comment by jisasebastine** [comment] 2018-10-12 17:17
Hi,
I am trying to render a **1471** page pdf document. Google chrome crashes giving an Aw Snap error while trying to load this "huge" file. Mozilla firefox renders the whole document without any error. I am following the hello world examples (Previous/Next example in https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples). 

I am passing the the **XMLHttpRequest response to the getDocument() function instead of the url**. 
Chrome was crashing at around page 300 when i was NOT waiting for the response of renderPage() function before trying to render another page. ( Although this approach was okay for a 600 page document as long as I was updating the pageNumPending variable.)
I changed my approach and I call renderPage(num) after I get a response from the previous renderPage() function. This allowed me to render till page=850. I am also calling pdfDoc.cleanup() and page.cleanUp() in every renderPage() function to avoid memory leak which was another guess. After rendering page 850 it crashes in Google Chrome giving an **Aw Snap error**. 
Note: **Except Mozilla Firefox**, it fails on every other browsers (I tested on google chrome, edge, IE).

Thanks,
Jisa

**Comment by dschissler** [comment] 2019-05-11 00:41
On `2.1.266` calling `cleanup` on both `loadingTask` (`doc`) and the page doesn't fix anything.  I'm using a scanned pdf within document per page and I can only get to page 38 before it crashes.  It works well enough on an older `1.something` release if I disable web workers for Chrome.

**Comment by dmisdm** [comment] 2019-07-22 02:17
So i'm not sure if this fixes your issue, but i was facing the same behaviour in chrome, and i found that it was the debugging that was causing the issue!
I was calling `console.log(pdfPage)` or `console.log(textLayerBuilder)` in a few places, and noticed through chrome's performance recording that i was getting a DOM leak (a very very large number of DOM nodes, most of which were detached), and that forcing a GC in dev tools wasn't clearing them.
Removing any `console.log` statements removed any references to the detached nodes and seemed to fix the issue.
This could definitely be unique to me though.
This is for `2.2.213` by the way.

**Comment by dschissler** [comment] 2019-07-23 18:31
@dmisdm I haven't had any problems with `2.1.266` ever since I took a deep breath, commented out the console.log messages and accepted my fate.  I think that you are correct.  The problem is that I couldn't find good documentation for the things that I wanted to do and so I was logging objects to see what type that they were in order to piece together what to do with them.  This created a cycle of everything failing and the more that I tried to figure it out the worse that it performed.  This is not too different than giving up in the morning on finding your car keys to instead walk to work then finding the keys in your shoes because it seemed like a good place to put them the previous night after drinking.

**Comment by Snuffleupagus** [comment] 2021-06-28 09:40
> http://jsfiddle.net/pdfjs/wagvs9Lf/?utm_source=website&utm_medium=embed&utm_campaign=wagvs9Lf
> [...]
> While loading on mobile it shows aww snap but similar is working fine on desktop.

That unfortunately points to an issue with the particular device/platform/browser that's being used here, caused e.g. by general resource constraints, rather than the PDF.js library itself.
Please note that example referenced above is a fairly bare-bones one, and that parsing/rendering PDF documents is generally quite a bit more resource intensive than e.g. just rendering an image.

All-in-all, given the age of this issue and that there doesn't appear to be anything *specific* we can really do here, closing for now.

**Closed by Snuffleupagus** 2021-06-28 09:40 UTC
Labels: 1-other, 4-chrome-specific
