### ISSUE TITLE
Error: Requesting object that isn't resolved yet Helvetica_path_F

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#8127] opened 2017-03-03 12:54 UTC
Link to PDF file (or attach file here):
https://tcpdf.org/files/examples/example_026.pdf

Configuration:
- Web browser and its version: FF 51.0.1
- Operating system and its version: W7
- PDF.js version: latest

Steps to reproduce the problem:
click on link

What is the expected behavior? (add screenshot)
![ok](https://cloud.githubusercontent.com/assets/6665575/23551787/aceb4b8e-0018-11e7-924a-a82cf135b5be.png)

What went wrong? (add screenshot)
![nok](https://cloud.githubusercontent.com/assets/6665575/23551788/b0f9a734-0018-11e7-8588-4ed495dafd65.png)

Error message:
Error: Requesting object that isn't resolved yet Helvetica_path_F  pdf.js:312:5
PDFObjects_get@resource://pdf.js/build/pdf.js:8496:9
FontFaceObject_getPathGenerator@resource://pdf.js/build/pdf.js:1798:20
CanvasGraphics_paintChar@resource://pdf.js/build/pdf.js:5766:21
CanvasGraphics_showText@resource://pdf.js/build/pdf.js:5942:13
CanvasGraphics_executeOperatorList@resource://pdf.js/build/pdf.js:5179:11
InternalRenderTask__next@resource://pdf.js/build/pdf.js:8701:30

**Comment by Snuffleupagus** [comment] 2017-03-03 13:24
Closing as duplicate of issue #4244 (and also issue #6301 :-).

**Comment by THausherr** [comment] 2017-03-03 13:25
Oops, sorry.

**Closed by Snuffleupagus** 2017-03-03 13:24 UTC

**Comment by Snuffleupagus** [comment] 2017-03-03 13:43
> Oops, sorry.

No worries!
It's not (always) entirely straightforward to find out if an issue has already been filed for a particular problem, and it's definitely *much* better to report issues (and having them closed as duplicate) rather than not opening issues at all!
