### ISSUE TITLE
Not available for Firefox 35.0 ???

### ISSUE THREAD

**Issue by polejam** [mozilla/pdf.js#5750] opened 2015-02-20 20:56 UTC
Hey just wondering why this isn't available for the updated version of firefox? Hope you can sort that one out soon.

**Comment by CodingFabian** [comment] 2015-02-20 21:04
firefox ships pdf.js by default without the need for an addon.

**Comment by Snuffleupagus** [comment] 2015-02-20 21:14
Closing as duplicate of #5645.

**Closed by Snuffleupagus** 2015-02-20 21:14 UTC
