### ISSUE TITLE
iOS Image cannot be displayed

### ISSUE THREAD

**Issue by Jaydar** [mozilla/pdf.js#10865] opened 2019-05-28 12:30 UTC
Attach (recommended) or Link to PDF file here:
https://jaydar.github.io/test.pdf

Configuration:
- Web browser and its version: safari 
- Operating system and its version: ios 12.2
- PDF.js version: pdfjs-2.0.943
- Is a browser extension: 

Steps to reproduce the problem:
1. Browse  https://mozilla.github.io/pdf.js/web/viewer.html?file=https://jaydar.github.io/test.pdf

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

The phone is not displaying properly

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2019-05-28 21:37
The PDF file contains large images (4160 x 5864 pixels for the first page) and most likely iOS cannot handle that. Most likely this is a duplicate of #9474 and some other open issues.

**Closed by timvandermeij** 2019-05-28 21:37 UTC
