### ISSUE TITLE
Pdf.js is not able to open PDFs with large-page-size pages in Firefox and IE11

### ISSUE THREAD

**Issue by MatrixDoge** [mozilla/pdf.js#7896] opened 2016-12-14 23:47 UTC
Link to PDF file (or attach file here):
https://github.com/Parthas-Menethil/Pdfjs_LargePageSizeIssue

Configuration:
- Web browser and its version: 
Firefox 50.1.0
IE 11.0.9600.18524 IEUpdateVersions:(11.0.37 KB3197655)
Chrome 54.0.2840.99

- Operating system and its version:
Windows 7

- PDF.js version:
The version used by "Firefox 50.1.0"?

- Is an extension:
Not applicable

Steps to reproduce the problem:
1. Open Firefox
2. Drag pdf file in

What is the expected behavior? (add screenshot)
A pdf with "TEST" text shown on the page

What went wrong? (add screenshot)
Pdf.js in firefox or IE is not able to open this PDF.
However, the same version of pdf.js can open the pdf in Chrome(Maybe V8's javascript optimization/performance is better)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Not applicable

Comments:
I found pdf.js running on Firefox/IE has issues opening a pdf file with large-page-size pages. On Chrome, I can see a viewer built by Pdf.js takes a bit longer to load up this simple pdf but it finally shows the correct result. However, on Firefox/ID, it never returns anything but a blank white page with minutes of waiting.

As I mentioned in "What went wrong? (add screenshot)" section, I think there are some expensive operations within pdf.js while opening a pdf with large-page-size pages. Chrome's V8 is able to handle this expensive operation but Firefox/IE's js engine is not.

There's no error message in the js console of Firefox when this happens. It seems the browser will quit script execution after it hangs for a few seconds.

Please feel free to share your ideas about this issue, Thank you.

**Comment by timvandermeij** [comment] 2016-12-15 00:22
The PDF contains a huge image resource, for which allocating space probably fails. Marking as performance issue.

**Comment by marco-c** [comment] 2023-02-16 13:51
Duplicate of #6741.

**Closed by marco-c** 2023-02-16 13:51 UTC
Labels: performance, pdf-broken
