### ISSUE TITLE
Failure to render PDF (text) content

### ISSUE THREAD

**Issue by djc** [mozilla/pdf.js#7486] opened 2016-07-14 13:18 UTC
Link to PDF file (or attach file here):

http://www.bloomline.com/wp-content/uploads/Prijsljst-OmniwAve-Consumer-2016-1.pdf

Configuration:
- Web browser and its version: Firefox Nightly, 50.0a1 (2016-07-13)
- Operating system and its version: OS X 10.11.5
- PDF.js version: whatever ships with this version of Firefox
- Is an extension:

Steps to reproduce the problem:
1. Open PDF file

What is the expected behavior? (add screenshot)

![expected-preview](https://cloud.githubusercontent.com/assets/158471/16840647/17aadf60-49d6-11e6-8828-f79db1a92b5e.png)

What went wrong? (add screenshot)

<img width="1440" alt="actual-firefox" src="https://cloud.githubusercontent.com/assets/158471/16840646/17aa4df2-49d6-11e6-95ad-908bc1e072f8.png">

**Comment by Snuffleupagus** [comment] 2016-07-14 13:23
Looks like a duplicate of the upstream graphics [bug 1285263](https://bugzilla.mozilla.org/show_bug.cgi?id=1285263), which was caused by [bug 1167235](https://bugzilla.mozilla.org/show_bug.cgi?id=1167235).

**Comment by timvandermeij** [comment] 2016-07-21 14:39
The fix for the referenced bug landed today, so it will probably be in today's or tomorrow's Nightly. @djc Could you confirm if upstream fixed this bug in that Nightly?

**Comment by Snuffleupagus** [comment] 2016-07-21 14:48
> The fix for the referenced bug landed today, so it will probably be in today's or tomorrow's Nightly.

Based on the fact that this *just* landed on central (less than half an hour ago), that patch will be in tomorrows Nightly at the earliest (provided that there's no issues).

**Comment by Snuffleupagus** [comment] 2016-07-21 19:31
I've applied the patch from [bug 1285263](https://bugzilla.mozilla.org/show_bug.cgi?id=1285263) locally and built Firefox to test this, and I can confirm that this issue (and the others) are fixed now.

As mentioned in https://github.com/mozilla/pdf.js/issues/7486#issuecomment-234277258, it will take until tomorrow for the patch to be included in Nightly, but I'm closing this issue as fixed since there's nothing left to do here :-)

**Closed by Snuffleupagus** 2016-07-21 19:31 UTC
Labels: 3-upstream, 4-firefox-specific
