### ISSUE TITLE
Text missing on zoom level 150/300 % in Chrome

### ISSUE THREAD

**Issue by ms3534** [mozilla/pdf.js#15670] opened 2022-11-07 11:56 UTC
Attach (recommended) or Link to PDF file here:
PDF: 
[Missing lines.pdf](https://github.com/mozilla/pdf.js/files/9951129/Missing.lines.pdf)

Configuration:
Web browser and its version:
Chrom Version 106.0.5249.120

Operating system and its version:
Windows 10

PDF.js version: 
Latest

Steps to reproduce the problem:
1. Open the PDF in viewer in Chrome browser
2. Increase the Zoom Level then the row with text is missing.

What is the expected behavior? (add screenshot)
The row containing should not disappear

What went wrong? (add screenshot)
![Screenshots](https://user-images.githubusercontent.com/104185732/200303708-16ca1c3a-5b1a-4b9e-990c-0b28307b19cc.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-11-07 12:06
Duplicate of #15098

**Closed by Snuffleupagus** 2022-11-07 12:06 UTC
