### ISSUE TITLE
Pages blank in Chrome in main view but not in thumbnail

### ISSUE THREAD

**Issue by TheSpiritXIII** [mozilla/pdf.js#9232] opened 2017-12-04 16:00 UTC
#### Web browser and its version
Uploaded bad PDF to the [viewer](https://mozilla.github.io/pdf.js/web/viewer.html). Chrome 62 displayed the page correctly as a thumbnail but did not display the page in main view. However, I am able to select text as if it's there. IE11 and Firefox 57 do not have issues.

I noticed a pattern. It was always the 9th page that had the issue.
[Bad PDF Sample 1.pdf](https://github.com/mozilla/pdf.js/files/1527798/Bad.PDF.Sample.1.pdf)
[Bad PDF Sample 2.pdf](https://github.com/mozilla/pdf.js/files/1527799/Bad.PDF.Sample.2.pdf)
[Bad PDF Sample 3.pdf](https://github.com/mozilla/pdf.js/files/1527800/Bad.PDF.Sample.3.pdf)

![image](https://user-images.githubusercontent.com/4027687/33562021-3ae30704-d8e2-11e7-8988-a13efc89d80b.png)

#### Operating system and its version
Windows 7.

#### PDF.js version
The viewer seems to show PDF.js 2.0.183 in the console as of creating this bug. In production, my company utilizes PDF.js 1.4.20 and it exhibits this issue as well.

#### Is a browser extension
No.

#### Steps to reproduce the problem:
1. Open viewer and open the side panel. Ensure thumbnail previews are showing.
2. Load PDF and scroll down to page 9.
3. Verify that the thumbnail shows correctly and page is blank when it should not be.

### Other Information
I generated the PDF using Chromium's Remote Debugger Protocol and then modified it via Apache PDFBox. Other PDF viewers show up correctly. I have tried Adobe Reader and Chrome's built-in PDF viewer. I have not tried dropping the PDFBox modifications, but if other PDF viewers are displaying as intended, then this is likely a PDF.js bug. We have not observed this issue when we were still using PhantomJS to generate PDFs.

I have tried hiding various sections before generating the PDF and in other configurations, the PDF displays correctly. It may be an ordering problem. This issue does feel intermittent but it is consistent when it happens.

**Comment by dorasun** [comment] 2018-03-20 15:40
I was testing this on Chrome on MacOS 10.12.5, and I noticed when I zoomed in sometimes the entire PDF would load and sometimes it would not. These are screenshots from the same PDF page as above (Bad PDF Sample 3.pdf, page 9) at various levels of zooming in:

<img width="1280" alt="screen shot 2018-03-20 at 11 32 34 am" src="https://user-images.githubusercontent.com/10905385/37665244-343b43cc-2c33-11e8-9a5d-85103ea889d0.png">
<img width="1280" alt="screen shot 2018-03-20 at 11 32 45 am" src="https://user-images.githubusercontent.com/10905385/37665251-373c0e4e-2c33-11e8-981d-b693bbd22708.png">
<img width="1280" alt="screen shot 2018-03-20 at 11 32 54 am" src="https://user-images.githubusercontent.com/10905385/37665280-450febe4-2c33-11e8-9f4f-b93500e8fc8b.png">
<img width="1280" alt="screen shot 2018-03-20 at 11 33 17 am" src="https://user-images.githubusercontent.com/10905385/37665303-4e46e53c-2c33-11e8-9e7e-991ea8e83b22.png">
<img width="1280" alt="screen shot 2018-03-20 at 11 33 17 am" src="https://user-images.githubusercontent.com/10905385/37665324-5ab29b4a-2c33-11e8-82ff-6e278c1f9c7f.png">

Notice that the amount of the PDF shown changes even at the same zoom level

**Comment by timvandermeij** [comment] 2018-03-20 22:29
I would suggest to file an upstream bug in the Chrome issue tracker since this doesn't really look like it's caused by PDF.js, but rather by a browser/graphics driver issue.

**Comment by Snuffleupagus** [comment] 2019-02-10 11:53
Is it meaningful to keep this issue open, given that it's not something that can be fixed in the PDF.js library?

**Closed** 2019-02-10 13:52 UTC
Labels: 1-viewer, 3-upstream, 4-chrome-specific
