### ISSUE TITLE
image not rendered transparent

### ISSUE THREAD

**Issue by Chrille79** [mozilla/pdf.js#7556] opened 2016-08-22 14:02 UTC
Edge + Pdfjs works
Chrome + Pdfjs works
Firefox + Pdfjs the transparant image is no longer transparent

PDF file: 
[test (2).pdf](https://github.com/mozilla/pdf.js/files/430303/test.2.pdf)

Configuration:
- Web browser and its version: Firefox 48.0.1
- Operating system and its version: Windows 10, Windows 7

Steps to reproduce the problem:
1.  Open pdf file in firefox

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/5775147/17857312/86daeb90-6881-11e6-9500-0f78efccd03e.png)

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/5775147/17857297/7a4738a2-6881-11e6-9471-2d89c55d1dac.png)

**Comment by Snuffleupagus** [comment] 2016-08-22 14:29
Running [mozregression](http://mozilla.github.io/mozregression/) on Windows points to https://bugzilla.mozilla.org/show_bug.cgi?id=1258168, since I get this regression range: https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=ca5142203259cd252723d34e75d3e3b799b21765&tochange=538d248fa252a4100082fd9bc3fdc08d322cda22.

We probably need to create a reduced test-case in order to report the issue upstream.

**Comment by Snuffleupagus** [comment] 2016-09-26 15:20
This is tracked upstream in https://bugzilla.mozilla.org/show_bug.cgi?id=1303534.

**Comment by Snuffleupagus** [comment] 2016-09-29 22:26
[Bug 1303534](https://bugzilla.mozilla.org/show_bug.cgi?id=1303534) has just been fixed, and should (hopefully) be uplifted to Firefox 50/51.

Closing, since there's nothing left to do here.

**Closed by Snuffleupagus** 2016-09-29 22:26 UTC
Labels: 2-image-quality, 3-regression, 3-upstream, 4-firefox-specific
