### ISSUE TITLE
A PDF file is showing vertical lines on a page and the content on the page is lost while rendering on thumbnail view in PDF.js viewer

### ISSUE THREAD

**Issue by prmahima** [mozilla/pdf.js#15303] opened 2022-08-12 06:04 UTC
Attach (recommended) or Link to PDF file here: Attached in the comment section. As the sample document belongs to our customer we can not attach the PDF file directly here. 

Configuration:
- Web browser and its version: Google Chrome Version 104.0.5112.79

Firefox Version 103.0.2 does not even render the file and shows this error-  
PDF.js v2.16.48 (build: ab1297f05)
Message: 
Stack: putBinaryImageData@https://mozilla.github.io/pdf.js/build/pdf.js:6867:11
paintInlineImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:8705:25
paintImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:8656:10
executeOperatorList@https://mozilla.github.io/pdf.js/build/pdf.js:7191:20
_next@https://mozilla.github.io/pdf.js/build/pdf.js:4254:37
__webpack_modules__</_scheduleNext/<@https://mozilla.github.io/pdf.js/build/pdf.js:4242:14

- Operating system and its version: Windows (Not specific to OS)
- PDF.js version: 2.16.48
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF file in pdf.js viewer - https://mozilla.github.io/pdf.js/web/viewer.html
2. Click to show thumbnails view and scroll down to page number 9. You will see the page contains vertical lines and it's content is lost.

What is the expected behavior? (add screenshot)
: Content should be visible/rendered properly in the thumbnail view.

What went wrong? (add screenshot)
: Vertical lines appear on the page and the page content is lost while rendering in the thumbnail view. Please refer to the screenshot here-
<img width="307" alt="vertical-lines" src="https://user-images.githubusercontent.com/17292837/184291558-c3fa51ee-5bdb-463f-a8a0-791142ab9fc4.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by billynexify** [comment] 2022-08-12 06:07
[40016810713_v1.pdf](https://github.com/mozilla/pdf.js/files/9314058/40016810713_v1.pdf)
sample file

**Comment by Snuffleupagus** [comment] 2022-08-12 06:51
Duplicate of #12307

**Closed by Snuffleupagus** 2022-08-12 06:51 UTC
