### ISSUE TITLE
Harmonize scrolling between Vimium and PDF.js

### ISSUE THREAD

**Issue by mackdata** [mozilla/pdf.js#7938] opened 2017-01-09 13:08 UTC
I hope that the J/K keybindings can be harmonized on PDF.js. The vimium implementation is really better than the way pdf.js does it right now. 

In practice that would mean that you'd:

Map J key to scroll down x lines.
Map K key to scroll up x lines.
Where x could be set to be something like 4 or 5 lines.

**Comment by timvandermeij** [comment] 2017-01-09 20:35
Closing as duplicate of #7019.

**Closed by timvandermeij** 2017-01-09 20:35 UTC
