### ISSUE TITLE
Selection behaves weirdly across web link

### ISSUE THREAD

**Issue by jlebar** [mozilla/pdf.js#1403] opened 2012-03-23 20:35 UTC
http://www.irs.gov/pub/irs-pdf/f1040es.pdf

There's a link to "www.irs.gov/form1040es" on the first page.  Start selecting text on that line, to the left of the link.  As the cursor passes over the link, the selection suddenly expands to the whole bottom of the page.  Then, as the cursor passes off to the right of the link, the selection again behaves normally.

**Comment by timvandermeij** [comment] 2015-01-27 19:39
I cannot reproduce this anymore with the latest PDF.js development version. Closing as fixed.

**Closed by timvandermeij** 2015-01-27 19:39 UTC
Labels: 1-viewer, 4-text-selection
