### ISSUE TITLE
Preview not showing some content

### ISSUE THREAD

**Issue by jjtfsalgado** [mozilla/pdf.js#13870] opened 2021-08-04 17:01 UTC
Configuration:
- Web browser and its version: Chrome Version 92.0.4515.107 (but tried in Mozilla and Edge and still got it)
- Operating system and its version: Windows 10 Pro N - 19042.1110
- PDF.js version: 2.1.266
- Is a browser extension: no

Steps to reproduce the problem:
1. Preview through pdf.js and some content it's missing.

What is the expected behavior? (add screenshot)
![example](https://user-images.githubusercontent.com/14180997/128222035-45304c2a-2740-4eb5-aba9-bd9ed3b442c6.png)

What went wrong? (add screenshot)
Not sure if is a coincidence or not but the content missing have a different font from the rest but even parts of the grid are missing as you can see below.
![example_issuepng](https://user-images.githubusercontent.com/14180997/128222038-22f5bde7-d046-4d57-96fa-b4308c19cfb9.png)

Do you guys have any suggestion in what could be the cause of this? Is strange because most of our pdfs are being rendered correctly (> 95%) but recently some customers complained about this.  Any suggestion would be great. Thanks!

Ps: Sorry but I had to blur some content

**Comment by brendandahl** [comment] 2021-08-04 17:47
Do you have a PDF you can post publicly? Without that it will be extremely hard to fix this issue.

**Comment by Snuffleupagus** [comment] 2021-08-04 17:57
> PDF.js version: 2.1.266

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by Snuffleupagus** [comment] 2021-08-05 14:13
Squinting at the screen-shot (since there's no test-case provided), this could very well be a duplicate of e.g. issue #13798 which you can easily confirm by checking in the console.
In that case you simply need to *update* to a supported PDF.js release, as mentioned previously, and the problem will go away.

**Closed by Snuffleupagus** 2021-08-05 14:13 UTC
Labels: 4-information-requested

**Comment by jjtfsalgado** [comment] 2021-08-05 15:03
Indeed we've updated to v2.9.359 at it fixed that. Thanks!
