### ISSUE TITLE
Garbled text in Chrome/Edge (Works fine in Firefox)

### ISSUE THREAD

**Issue by clarkk** [mozilla/pdf.js#15817] opened 2022-12-13 01:02 UTC
In the latest versions of Chrome and Edge text in all PDF's are garbled. I couldn't find any issue mentioning it so submitted a new issue

To "fix" the garbled text you have to disable 2d canvas-something in the browser which is enabled by default.

PDFjs is not compatible with the new default settings in Chrome and Edge

https://github.com/wojtekmaj/react-pdf/issues/1025

Two weeks ago I got a new computer (windows 11) and by default text is antialiased in the system (not only in the browser). It has probably something to do with that. On my old computer PDFjs render text correctly, but on my old computer (also windows 11) the text is pixelated (like it usually is on windows)

I don't know what kind of setting makes windows render text by antialiasing at system level? But thats probaby the "new-thing" on windows 11

`PDFjs v3.1.81`

**Comment by Snuffleupagus** [comment] 2022-12-13 10:31
Duplicate of #14641

**Closed by Snuffleupagus** 2022-12-13 10:31 UTC

**Comment by clarkk** [comment] 2022-12-13 10:32
This is not a duplicate...

**Comment by clarkk** [comment] 2022-12-13 10:32
@Snuffleupagus  this is not the same error

**Comment by Snuffleupagus** [comment] 2022-12-13 10:40
All of these issues are related to hardware-acceleration being enabled, in combination with certain GPUs, in Chromium-based browsers; hence the duplicate is correct since it's a *browser* bug and not a PDF.js-library one!
