### ISSUE TITLE
Zooming with mouse wheel has huge steps

### ISSUE THREAD

**Issue by kuro68k** [mozilla/pdf.js#16685] opened 2023-07-13 10:59 UTC
**Attach (recommended) or Link to PDF file here:**

Any PDF will work.

**Configuration:**
- Chrome Version 114.0.5735.199 (Official Build) (64-bit)
- Windows 10 x64, latest patches as of 2023/07/13
- PDF.js version: 3.9.49
- Is a browser extension: Yes

**Other relevant info:**
Using a high DPI (4k) display at 175% zoom in Windows settings. Zoom at 100% in Chrome.

**Steps to reproduce the problem:**
1. Hold ctrl key
2. Move mouse wheel up or down

**What is the expected behavior? (add screenshot)**
Zoom in small steps

**What went wrong? (add screenshot)**
Zoom changes in huge steps, e.g.
100% -> 510%
100% -> 10%

This used to work fine until recently, now zooming is ridiculously fast and unusably with the ctrl+scroll wheel technique.

**Comment by Snuffleupagus** [comment] 2023-07-13 11:03
Duplicate of #16325

**Closed by Snuffleupagus** 2023-07-13 11:03 UTC
