### ISSUE TITLE
can not show the pdf content when pdf is produceds by outlook

### ISSUE THREAD

**Issue by lianyzhou** [mozilla/pdf.js#11120] opened 2019-09-05 03:29 UTC
Attach (recommended) or Link to PDF file here:

File Content Of Pdf is（Viewed by FuxiReader）：
![image](https://user-images.githubusercontent.com/6295633/64309559-7931d680-cfcf-11e9-80fb-b77cc9df7f4f.png)

Configuration:
- Web browser and its version:  Chrome  76.0.3809.132（64 Bit）
- Operating system and its version: Windows 10.0.17134.950
- PDF.js version:  PDF.js: 1.9.446
- Is a browser extension:  false

Steps to reproduce the problem:
1. pdf file is produces by microsoft outlook software
2. pdf.js can not show the file content，but FuxiReader can show the content
3. can pdf.js support this kind of file, or how can i develop this feature, I am a JavaScript developer ，and 80% of our customer files is made by outlook

**Comment by lianyzhou** [comment] 2019-09-05 03:30
Thanks To pdf.js which made view pdf on the web possible

**Comment by heianqishizhisuiyuan** [comment] 2019-09-05 03:32
I've met the question as you too。

**Comment by Snuffleupagus** [comment] 2019-09-05 06:41
Duplicate of #4282.

---

> Attach (recommended) or Link to PDF file here:

*For future reference:* Without this piece of information, an issue will generally be closed as incomplete.

**Closed** 2019-09-05 21:21 UTC
