### ISSUE TITLE
Attached PDF Renders very slowly

### ISSUE THREAD

**Issue by sethnk** [mozilla/pdf.js#5663] opened 2015-01-21 14:34 UTC
https://pdf.yt/d/StMRgGUi1Ms8-95v

This PDF renders very slowly compared to others.  It is not a large file (~600kb) and has 6 pages.

Interestingly, I notice that the problem does not occur with the viewer on the pdf.yt site.

Using Chrome 39.0.2171.95 and Windows 8.1 x64

**Comment by fkaelberer** [comment] 2015-01-21 18:19
This document contains sevaral 32Mpixel JBIG2 images. JBIG2 decoding has speed has improved a little in #5114 which was merged last August, so if you have an older version of pdf.js, try to use a newer one.

**Comment by yurydelendik** [comment] 2015-01-21 19:29
@sethnk can you add a version number to the report?

**Comment by sethnk** [comment] 2015-01-21 20:32
It was the latest version under 'example' on the pdf.js homepage.  Is there a simple way to to identify the version for this?

**Comment by yurydelendik** [comment] 2015-01-21 20:38
> It was the latest version under 'example' on the pdf.js homepage. Is there a simple way to to identify the version for this?

Version for the PDF.js viewer is usually printed in the console. If you have a custom solution, please provide a public URL or exact steps in details, so contributors could reproduce the problem you have.

**Comment by sethnk** [comment] 2015-01-21 21:58
Yury - I am using the version on the pdf.js website (version 1.0.1086).  There are no customisations.

**Comment by yurydelendik** [comment] 2015-01-21 23:39
Oh, I see it's something specific to Chrome. Rendering times on Firefox:

![screen shot 2015-01-21 at 5 32 06 pm](https://cloud.githubusercontent.com/assets/1523410/5847580/6240267a-a194-11e4-8311-df6d50207282.png)

On Chrome 39 it takes 3-4 seconds per page

**Comment by yurydelendik** [comment] 2015-01-21 23:49
5b83e0b9a3b2fbed8cc92397b8f874ab4375fc6d is the first bad commit

Introduced by #5114

**Comment by yurydelendik** [comment] 2015-01-21 23:50
@fkaelberer looks like Chrome does not like this optimization. (The question: why?)

**Comment by fkaelberer** [comment] 2015-01-22 07:49
At [jbig2.js#L185](https://github.com/mozilla/pdf.js/blob/master/src/core/jbig2.js#L185) the array indices are sometimes out of range. Looks like [Chrome and IE11 don't like it](http://jsperf.com/typed-array-index-out-of-range), so I guess we should check the array index boundaries ourselves.

**Comment by yurydelendik** [comment] 2015-01-22 12:24
Very interesting. So it is somewhat corrupted PDF.

**Comment by fkaelberer** [comment] 2015-01-23 08:44
This was intended, but I didn't know it would slow things down. I'll provide a fix soon.

**Closed** 2015-01-26 18:10 UTC
Labels: 2-performance, 3-regression, 4-chrome-specific
