### ISSUE TITLE
When the page's width is big,the content will not be clear on mobilephone.How to deal with it?

### ISSUE THREAD

**Issue by laicelery** [mozilla/pdf.js#12309] opened 2020-09-01 06:46 UTC
Attach (recommended) or Link to PDF file here:
The file may is private.
But the file show like this.
[
![捕获222](https://user-images.githubusercontent.com/70512093/91811318-e79c8980-ec61-11ea-942b-ef60658c4862.PNG)
](url)
Configuration:
- Chrome: 84.0.4147.135
- windows 7
- PDF.js: 2.2.228

Steps to reproduce the problem:
1. excel convert to pdf
2.show pdf with viewer.html

What is the expected behavior? (add screenshot)
the file is clear like on PC.

What went wrong? (add screenshot)
on mobilephone:
[
![捕获000](https://user-images.githubusercontent.com/70512093/91810295-36e1ba80-ec60-11ea-87bd-6c766da9186d.PNG)
](url)

on PC:
![捕获111](https://user-images.githubusercontent.com/70512093/91810500-8cb66280-ec60-11ea-87a8-3299d531e541.PNG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2020-09-01 10:52
> The file may is private.
> But the file show like this.

Without access to a test-case, this issue (or anyone else) is unfortunately not actionable and will be closed as such.

> PDF.js: 2.2.228

Note that that version is no longer supported; you can always find the latest releases at https://github.com/mozilla/pdf.js/releases

---

Given the lack of *crucial* details here, this is most likely a duplicate of issue #6419.

**Closed** 2020-09-01 19:52 UTC
