### ISSUE TITLE
Pinch zoom gesture does not work on touchscreen

### ISSUE THREAD

**Issue by Esokrates** [mozilla/pdf.js#13326] opened 2021-05-03 11:45 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 88
- Operating system and its version: Ubuntu 21.04
- PDF.js version: 2.8.243
- Is a browser extension: No

Steps to reproduce the problem:
1. Open a pdf in Firefox on a touchscreen device
2. Try to zoom using the pinch gesture

What is the expected behavior?

Pinch zoom works.

What went wrong?

Pinch zoom does not work.

Related bugs reports on the firefox bugzilla:

https://bugzilla.mozilla.org/show_bug.cgi?id=1677933
https://bugzilla.mozilla.org/show_bug.cgi?id=1659492

**Comment by Snuffleupagus** [comment] 2021-05-03 11:52
> Related bugs reports on the firefox bugzilla:
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1677933
> https://bugzilla.mozilla.org/show_bug.cgi?id=1659492

Please note that there's really no need to track the *same* bug in both Bugzilla and Github; hence this can be closed as a duplicate.

**Comment by Snuffleupagus** [comment] 2021-05-03 12:05
> Related bugs reports on the firefox bugzilla:
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1677933
> https://bugzilla.mozilla.org/show_bug.cgi?id=1659492

Duplicate of #2582 (for all intents and purposes); please also note that it's also generally not necessary to "re-file" issues from Bugzilla here at GitHub.

**Closed** 2021-05-05 17:53 UTC
