### ISSUE TITLE
Adding Custom Canvas on top of each pdf.JS page does not get included in Print Preview

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#7686] opened 2016-10-03 10:24 UTC
in viewer.js this line of code 

canvases = document.querySelectorAll('canvas');

gets all canvases for print preview. when i add a custom canvas beside each pdf.js canvas page, it does not get included in the print preview.

**Comment by timvandermeij** [comment] 2016-10-03 12:39
It is located in `web/mozPrintCallback_polyfill.js`, so that is only done for browsers other than Firefox, meaning that it will probably work differently in Firefox. There is no use-case for us for adding more canvases and from the issue it's not clear/reproducible what the problem is, so I'm closing this for now.

**Closed by timvandermeij** 2016-10-03 12:39 UTC

**Comment by chitgoks** [comment] 2016-10-04 03:12
hi tim. thank you for the feedback. yes you are right, that is where i checked the code. in my use case, i added another canvas layer on top of the pdf.js page canvas because i display my own custom annotations.

i would like to have those same annotations get printed but they do not seem to get included. in the canvases variable, they are part of it but somehow like in chrome, i checked the print preview and the annotations do not get shown. only the pdf.js canvas pages are shown.

any ideas?

**Comment by timvandermeij** [comment] 2016-10-04 11:46
The only thing I can think of is that the PDF.js canvas layer is placed on top of your annotation canvas layer, but it's not possible to say for sure without seeing your code.

**Comment by Snuffleupagus** [comment] 2016-10-04 11:56
PDF.js does *not* print the canvases that are visible in the viewer, but rather renders to *printing-specific* canvases during the print process; please refer to this code: https://github.com/mozilla/pdf.js/blob/d2a4974785ac7ed199fa25b62903ebbed63bd882/web/pdf_page_view.js#L544.

Hence if you want to print the contents of *other* canvases as well, you will have to implement that yourself (perhaps in the `PDFPageView_beforePrint` method), since it's out of scope for the PDF.js viewer.

**Comment by chitgoks** [comment] 2016-10-04 12:51
thank you for the tips. i will check it out!

**Comment by dacsy** [comment] 2017-05-22 02:48
Hi Chitgoks
How about your solution to resolve this issues ?
I am having the same issues than you at the moment. Thank you

**Comment by chitgoks** [comment] 2017-05-22 02:51
hello dacsy. 
i dont understand pdf.js code deep within so I ended up using the pdf.js canvas since there is no way to force pdf.js  to include your custom canvas without having to modify it.

**Comment by dacsy** [comment] 2017-05-22 03:07
Oh, okie I got it. Thank you for your answering my question

**Comment by chitgoks** [comment] 2018-11-27 08:55
@Snuffleupagus hi, this is an old post, but i thought the need to revisit and ask if you have an idea
on how to get references to this "but rather renders to printing-specific canvases"?

**Comment by KasunSandruwan** [comment] 2019-06-19 12:31
hi chitgoks,
How about your solution to resolve this issues ?
I have create pdf annotated using pdf.js and viewer.js 
but canvas not print and download ... if you have solution pl,,,  help
