### ISSUE TITLE
annotation highlight in pdf.js not working properly

### ISSUE THREAD

**Issue by eaxle** [mozilla/pdf.js#6687] opened 2015-11-25 10:01 UTC
I have created an annotation highlight for pdf in pdf.js.The source for annotation in pdf.js is https://github.com/eaxle/eaxle.github.io .The annotation code is https://github.com/eaxle/eaxle.github.io/blob/master/web/showData.js .The pdf used is https://github.com/eaxle/eaxle.github.io/blob/master/web/compressed.tracemonkey-pldi-09.pdf
.The code works fine for zoom level below 500% for this pdf. But for above 500% the annotion layer doesn't sit in the selected place
![untitled](https://cloud.githubusercontent.com/assets/11533842/11393930/9c4e6e1a-938a-11e5-89d2-15b0f746910a.png)
In above,The selected text was trace.This only happens when zoom In or zoom Out button is clicked for zoom above 500%.But if you reload the page at zoom level above 500% and then select and highlight the text,the problem doesn't occur.Only when zoom in or zoom out button is clicked and text is selected and highlight button is clicked the highlighted div doesn't sit in the desired position.This doesn't happen for zoom level less than 500%.Also,the zoom level varies for different pdf file for this problem to occur.The highlighted div is created inside the textLayer div.For demo you can use http://eaxle.github.io/web/viewer.html .

**Comment by eaxle** [comment] 2015-11-27 10:29
https://github.com/mozilla/pdf.js/issues/6463 and https://github.com/kimgronqvist/pdfjs-annotation-example/issues/1 helped me solve my problem but I have noticed that when text of two consecutive pages are selected the lower is highlighted but not the upper one and the lower page whole is highlighted despite the selection
![untitled](https://cloud.githubusercontent.com/assets/11533842/11439138/aee2c1dc-9521-11e5-9f53-69ca5fffe532.png)
you can produce the problem in http://eaxle.github.io/web/viewer.html

**Comment by timvandermeij** [comment] 2016-01-22 23:02
Since the remaining issue is one most likely caused by your custom implementation, I'm closing this issue as resolved since there appears to be no PDF.js bug here. For further assistance, please use the mailing list or IRC.

**Closed by timvandermeij** 2016-01-22 23:02 UTC
Labels: 4-triage-needed
