### ISSUE TITLE
Page size is different in a PDF file

### ISSUE THREAD

**Issue by luhantao** [mozilla/pdf.js#8439] opened 2017-05-24 07:27 UTC
Link to PDF file (or attach file here):
[Linux+Bible+2010.pdf](https://raw.githubusercontent.com/luhantao/pdf.js/master/build/generic/web/Linux+Bible+2010.pdf)

When I use the official demo to render this PDF file, the first page is much smaller than other pages. The screenshot is below:

![screenshot](https://raw.githubusercontent.com/luhantao/pdf.js/master/screenshot/1.JPG)

My question is , **_Is there any ways that I can render all pages in a same size (width)?_**  I have tried to change all PDFPageView objects' width attribute into a same value for all pages in viewer.js , but it doen't work. Does any one has any suggestions about this? Thanks a lot!

**Comment by adadgio** [comment] 2018-03-21 13:31
I am having the same issue here, whatevet the scale chosen: 

```
let pdfPageView = new PDFJS.PDFPageView({
                    container: this.viewerPlaceholder.nativeElement,
                    id: pageIndex,
                    scale: 1.0,
                    defaultViewport: pdfPage.getViewport(1.0),
                    // we can enable text/annotations layers, if needed
                    // textLayerFactory: new PDFJS.DefaultTextLayerFactory(),
                    // annotationLayerFactory: new PDFJS.DefaultAnnotationLayerFactory()
                })

      pdfPageView.setPdfPage(pdfPage)
      let task = pdfPageView.draw()
// then call other pages to be rendered in a loop...
```

**Comment by Snuffleupagus** [comment] 2021-01-31 11:12
> Link to PDF file (or attach file here):
> [Linux+Bible+2010.pdf](https://raw.githubusercontent.com/luhantao/pdf.js/master/build/generic/web/Linux+Bible+2010.pdf)

That document is no longer available, however this issue looks for all intents and purposes like a duplicate of #9359.

**Closed** 2021-01-31 13:14 UTC
Labels: 1-other
