### ISSUE TITLE
PDF appears with lines through several images

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#9481] opened 2018-02-15 00:50 UTC
Attach (recommended) or Link to PDF file here:
[Tabletop_report_digital.pdf](https://github.com/mozilla/pdf.js/files/1726090/Tabletop_report_digital.pdf)

Configuration:
- Web browser and its version: Chrome 64.0.3282.140, Firefox 59.0b7
- Operating system and its version: Mac OSX 10.12.6
- PDF.js version: Latest on pdfjs-dist (tested with v2.0.374 at time of ticket)
- Is a browser extension: No

Steps to reproduce the problem:
1. Visit http://mozilla.github.io/pdf.js/web/viewer.html?file=
2. Upload attached file

What is the expected behavior? (add screenshot)
Page 1:
![2018-02-14_16-48-13](https://user-images.githubusercontent.com/689351/36235667-dea57faa-11a6-11e8-9dfa-9e04bbf7f4f9.png)

Page 3:
![2018-02-14_16-48-51](https://user-images.githubusercontent.com/689351/36235685-f1824f68-11a6-11e8-8a60-ce5a5a3f4f00.png)

What went wrong? (add screenshot)
Page 1 (note horizontal lines):
![2018-02-14_16-49-17](https://user-images.githubusercontent.com/689351/36235695-013fccdc-11a7-11e8-8728-0fc642b91490.png)

Page 3:
![2018-02-14_16-49-45](https://user-images.githubusercontent.com/689351/36235711-11315e8a-11a7-11e8-8577-2f37b2d2de27.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A, used viewer at http://mozilla.github.io/pdf.js/web/viewer.html?file=

**Comment by Snuffleupagus** [comment] 2018-02-15 10:38
Closing as duplicate of e.g. issue #3351.

**Closed by Snuffleupagus** 2018-02-15 10:38 UTC
