### ISSUE TITLE
on scroll change page

### ISSUE THREAD

**Issue by ricardo5401** [mozilla/pdf.js#6793] opened 2015-12-22 22:21 UTC
hi, im use pdfjs on iframe, works great, but when i click to full screen can´t see complete the page. i try scroll page but doesn´t work (change to next page). When i use F11 works good :/

**Comment by yurydelendik** [comment] 2015-12-22 22:42
We don't have "full screen" and rely on F11 to bring viewer into full screen mode. Are you talking about presentation mode? Presentation mode button works as expected for me at https://www.eff.org/document/eff-ninth-circuit-amicus-brief

Please provide more details to reproduces the issue, e.g. link to the web page.

**Comment by ricardo5401** [comment] 2015-12-23 14:37
the reader is inside a container, and with javascript i do the full screen container request (
![normal mode](https://cloud.githubusercontent.com/assets/14843154/11978316/92813abe-a958-11e5-913c-2d477b2d25ee.png) . Full screen 
![full mode](https://cloud.githubusercontent.com/assets/14843154/11978318/9ff28586-a958-11e5-88be-916f77f9cae0.png)

**Comment by yurydelendik** [comment] 2015-12-23 14:50
Can you provide a link to the web page displayed above?

**Comment by ricardo5401** [comment] 2015-12-23 14:57
shure, wait a sec please

**Comment by ricardo5401** [comment] 2015-12-23 15:11
http://morning-island-9322.herokuapp.com/read/7302421981
user: ricardo_izasiga@hotmail.com
pswd: lolman123
Thnks

**Comment by yurydelendik** [comment] 2015-12-23 15:26
Looks like the code of PDF.js is heavy modified and it uses some custom full screen logic that uses our presentation mode display (you can track it down and disable it). Please contact the vendor of this component if you are not able to do it yourself. Closing as answered.

**Closed by yurydelendik** 2015-12-23 15:26 UTC
Labels: 4-information-requested

**Comment by ricardo5401** [comment] 2015-12-23 15:29
thnks :)
