### ISSUE TITLE
Font not rendered at all

### ISSUE THREAD

**Issue by tiaxter** [mozilla/pdf.js#12646] opened 2020-11-21 22:58 UTC
Link to PDF file:
[https://www.interno.gov.it/sites/default/files/2020-10/modello_autodichiarazione_editabile_ottobre_2020.pdf](https://www.interno.gov.it/sites/default/files/2020-10/modello_autodichiarazione_editabile_ottobre_2020.pdf)

Configuration:
- Web browser and its version: I'm using NodeJS not browser
- Operating system and its version: Windows 10
- PDF.js version: "^2.5.207",
- Is a browser extension: No

Steps to reproduce the problem:
```javascript

const pdf = "https://www.interno.gov.it/sites/default/files/2020-10/modello_autodichiarazione_editabile_ottobre_2020.pdf";

(async function () {

    const pdfBuffer = await fetch(pdf).then(res => res.buffer()).then(buffer => buffer);

    await convert2PNG(file);

    async function convert2PNG(pdfFile) {
        PDFJavaScript.disableWorker = true;
        PDFJavaScript.disableFontFace = true;
        const loadingTask = pdfjsLib.getDocument(pdfFile);
        const pdfDocument = await loadingTask.promise;
        const page = await pdfDocument.getPage(1);

        const viewport = page.getViewport({scale: 1.0});
        const canvasFactory = new NodeCanvasFactory();
        const canvasAndContext = canvasFactory.create(
            viewport.width,
            viewport.height
        );
        const renderContext = {
            canvasContext: canvasAndContext.context,
            viewport: viewport,
            canvasFactory: canvasFactory,
            renderInteractiveForms: true,
        };
        await page.render(renderContext).promise;
        const image = canvasAndContext.canvas.toBuffer();
        fs.writeFile("output.png", image, function (error) {
            if (error) {
                console.error("Error: " + error);
            } else {
                console.log("Finished converting first page of PDF file to a PNG image.");
            }
        });

    }
});

```

What is the expected behavior?
![image](https://user-images.githubusercontent.com/33230281/99889402-01dc7700-2c55-11eb-8975-3c80707418ae.png)

What went wrong? 
The initial part of PDF, and font is not rendered at all. 
![output](https://user-images.githubusercontent.com/33230281/99889412-1ae52800-2c55-11eb-9d16-ff90609e9f7e.png)

I noticed that fonts are not embedded, so may I ask is there a way to embed missing fonts?

**Comment by Snuffleupagus** [comment] 2020-11-22 10:35
Duplicate of #4244

**Closed** 2020-11-22 11:46 UTC
