### ISSUE TITLE
Error while rendering PDF in Firefox

### ISSUE THREAD

**Issue by vbeilin** [mozilla/pdf.js#14589] opened 2022-02-20 20:58 UTC
Attach (recommended) or Link to PDF file here:  http://file.magzdb.org/gazette/%D0%9B%D0%B8%D1%82%D0%B5%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%BD%D0%B0%D1%8F%20%D0%B3%D0%B0%D0%B7%D0%B5%D1%82%D0%B0/1938/%D0%9B%D0%B8%D1%82%D0%B5%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%BD%D0%B0%D1%8F%20%D0%B3%D0%B0%D0%B7%D0%B5%D1%82%D0%B0%201938%20%E2%84%96%20037%20(%D0%B8%D1%8E%D0%BB%D1%8C%2005).pdf

A number of other files linked from http://magzdb.org/j/4143, row '1938' have this issue.

Configuration:
- Web browser and its version: Firefox 97.0.1
- Operating system and its version: Windows 10 21H2
- PDF.js version: 2.13.174 ( https://mozilla.github.io/pdf.js/web/viewer.html), 2.13.24 (bundled with Firefox)
- Is a browser extension:

Steps to reproduce the problem:
1.  open the linked PDF directly in Firefox, or in https://mozilla.github.io/pdf.js/web/viewer.html in Firefox.

What is the expected behavior? (add screenshot)
![pdf.js on Edge](https://user-images.githubusercontent.com/979017/154864011-c99204d2-bdd6-41af-8748-1245b5413951.png)

What went wrong? (add screenshot)
![pdf.js on Firefox](https://user-images.githubusercontent.com/979017/154864025-522a8690-dfb7-4301-a154-81465b87f50f.png)

In the console:

```
PDF.js v2.13.174 (build: 3635a9a33)
Message: 
Stack: getCanvas@https://mozilla.github.io/pdf.js/build/pdf.js:4941:27
paintInlineImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:7173:45
paintImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:7126:10
executeOperatorList@https://mozilla.github.io/pdf.js/build/pdf.js:5703:20
_next@https://mozilla.github.io/pdf.js/build/pdf.js:3397:37
__webpack_modules__</_scheduleNext/<@https://mozilla.github.io/pdf.js/build/pdf.js:3385:14
```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-02-20 21:04
Duplicate of #13643

**Closed by Snuffleupagus** 2022-02-20 21:04 UTC
