### ISSUE TITLE
Broken pdf in Firefox only - works in Chrome using pdf.js (completely blank rendering - putBinaryImageData?)

### ISSUE THREAD

**Issue by temx** [mozilla/pdf.js#10415] opened 2019-01-04 17:47 UTC
See attached file: [pdfjsissue.pdf](https://github.com/mozilla/pdf.js/files/2727977/pdfjsissue.pdf)
I don't think this ever worked on Firefox. It works (without warnings) at least on:

* pdf.js under Chrome
* Chrome native built-in viewer
* Acrobat (9, X, XI, newer)
* Evince (Poppler)

Guess: native image decode error

The file was re-saved using Acrobat but the original exhibits exactly the same issue.

Console error messages (two different versions):

An error occurred while rendering the page.
PDF.js v2.1.153 (build: 5a2bd9fc)
Message: 
Stack: putBinaryImageData@https://mozilla.github.io/pdf.js/build/pdf.js:13996:9
CanvasGraphics_paintInlineImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:15442:9
CanvasGraphics_paintImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:15396:7
CanvasGraphics_executeOperatorList@https://mozilla.github.io/pdf.js/build/pdf.js:14269:11
_callee$@https://mozilla.github.io/pdf.js/build/pdf.js:11833:42
tryCatch@https://mozilla.github.io/pdf.js/build/pdf.js:11959:14
invoke@https://mozilla.github.io/pdf.js/build/pdf.js:12134:22
defineIteratorMethods/</prototype[method]@https://mozilla.github.io/pdf.js/build/pdf.js:12002:16
asyncGeneratorStep@https://mozilla.github.io/pdf.js/build/pdf.js:9549:103
_next@https://mozilla.github.io/pdf.js/build/pdf.js:9551:194
_asyncToGenerator/</<@https://mozilla.github.io/pdf.js/build/pdf.js:9551:364
_asyncToGenerator/<@https://mozilla.github.io/pdf.js/build/pdf.js:9551:97
_next@https://mozilla.github.io/pdf.js/build/pdf.js:11858:18
_scheduleNext/<@https://mozilla.github.io/pdf.js/build/pdf.js:11809:13

An error occurred while rendering the page.
PDF.js v2.1.97 (build: 45c01974)
Message: 
Stack: putBinaryImageData@resource://pdf.js/build/pdf.js:8029:9
CanvasGraphics_paintInlineImageXObject@resource://pdf.js/build/pdf.js:9475:9
CanvasGraphics_paintImageXObject@resource://pdf.js/build/pdf.js:9429:7
CanvasGraphics_executeOperatorList@resource://pdf.js/build/pdf.js:8302:11
_next@resource://pdf.js/build/pdf.js:6841:30
_scheduleNext/<@resource://pdf.js/build/pdf.js:6829:11

**Comment by Snuffleupagus** [comment] 2019-01-04 20:17
Duplicate of #6741.

**Closed** 2019-01-04 22:17 UTC
