### ISSUE TITLE
How can I load only one or a few pages at one time?

### ISSUE THREAD

**Issue by godwin668** [mozilla/pdf.js#8899] opened 2017-09-12 09:39 UTC
Even if pdf.js support Range Request that load pages lazily. But still load too many pages when open the page first time.

I've already set PDFJS.disableAutoFetch = true, but still load too many pages. There are several or dozens of Range Requests and loaded too many pages and waste a lot of network. I just only want to load only a few pages when page loaded first time.

Is there any option to set number of pages or chunks loaded at one time?

**Comment by Snuffleupagus** [comment] 2017-09-12 09:51
Closing as duplicate of #8897.

**Closed by Snuffleupagus** 2017-09-12 09:51 UTC
