### ISSUE TITLE
We are having space trimmed issue in pdf parsing

### ISSUE THREAD

**Issue by Kunwar1024** [mozilla/pdf.js#15871] opened 2022-12-27 11:11 UTC
Steps to reproduce the problem:
1.  We have checked and found that there is issue with all pdf version which is released after 2.11.338 version.
2. When User can go and parse the below attached pdf file with 2.11.338 or older versions. User get the output with spaces. Please have a look of below added screenshot for the same. I have highlighted in attached image.
[031902101_60_2022-01-27T11-39-08.pdf](https://github.com/mozilla/pdf.js/files/10307644/031902101_60_2022-01-27T11-39-08.pdf)
![image](https://user-images.githubusercontent.com/121488031/209656290-3fa4578b-e585-4b0b-8bff-f39fcaa36d22.png)
3. When User parse the same pdf file with 2.12.313 version or all the version which is released after this. User can not get the spaces. It trimmed out the spaces. Please have a look of below added screenshot - 
![image](https://user-images.githubusercontent.com/121488031/209657052-80ed2f91-ffbf-4b62-a7c8-915cea5f8f87.png)

What is the expected behavior? 
![image](https://user-images.githubusercontent.com/121488031/209656743-5d1a93ce-dd7b-4e13-8f9b-d1bec0245a02.png)

What went wrong? It trimmed out spaces in all the version which is release after 2.11.338 version.
![image](https://user-images.githubusercontent.com/121488031/209657119-d426fe7c-bc5b-46a8-9b8e-bcc36530f96b.png)

Please let us know if I missed some config so that it is avoiding spaces or what I need to do so that I can get resolution for the same.

**Comment by Snuffleupagus** [comment] 2022-12-27 11:32
*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since most of the requested details are missing here.

> When User can go and parse the below attached pdf file with 2.11.338 or older versions.

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

In later releases, numerous text-extraction and text-layer improvements have been made. Part of this was work was related to coalescing/elimination of repeated spaces in spaces in text, hence this seems like an expected change here (and it actually improves many/most cases). Furthermore, there's no option to restore the old behaviour unfortunately.

Closing, since this works as intended.

**Closed by Snuffleupagus** 2022-12-27 11:32 UTC
