### ISSUE TITLE
Safari MacOs and iOs forcing website zu reload

### ISSUE THREAD

**Issue by donmb1** [mozilla/pdf.js#14054] opened 2021-09-20 08:50 UTC
Attach (recommended) or Link to PDF file here:
cannot attach the file due to privacy reasons

Configuration:
- Web browser and its version: Safari 14.1.2
- Operating system and its version: MacOS Bg Sur 11.6
- PDF.js version: 2.9.359

Unfortunately I cannot give exact steps to reproduce this issue but I try to be as precise as possible.

We use the pdfjs viewer in an `<iframe>` within a `Vue` application which is working perfectly fine for many documents.
```
<iframe src="/pdfjs/web/viewer.html" width="100%" id="pdfViewer" ref="pdfViewer" frameBorder="0" />
```

via `localStorage` we save a PDF Base64 string within the app and let the viewer consume it.

```
      var base64 = localStorage['currentPDFBase64']
      base64 = base64.split(";base64,")[1]

      function base64ToUint8Array(base64) {
        var raw = atob(base64);
        var uint8Array = new Uint8Array(raw.length);
        for (var i = 0; i < raw.length; i++) {
        uint8Array[i] = raw.charCodeAt(i);
        }
        console.log("4 Returning Value Uint8")
        return uint8Array;
      };

      pdfData = base64ToUint8Array(base64);

      PDFViewerApplication.open(pdfData)
```

now this works also fine

But the second after `PDFViewerApplication.open(pdfData)` is called, Safari (and only Safari!) is reloading the website and gives me the following awesome message:
![Screenshot 2021-09-20 at 10 05 52](https://user-images.githubusercontent.com/3296757/133977007-0feac7a9-eb2e-4c2a-a67e-29566fb364ad.png)

I tried to identify possible problems in the documents but cannot find any.
I just want to know why Safari is reloading the page and how I can prevent it

Maybe this issue is know and you can give me any hints in the right direction?

Many thanks in advance.

**Comment by Snuffleupagus** [comment] 2021-09-20 09:22
> Attach (recommended) or Link to PDF file here:
> cannot attach the file due to privacy reasons

That unfortunately means that we cannot really help, since it's not possible to debug an issue that cannot be (easily) reproduced.

> We use the pdfjs viewer in an `<iframe>` within a `Vue` application which is working perfectly fine for many documents.

Furthermore, please note that we unfortunately cannot provide support for various JavaScript frameworks (e.g. "Vue" in this case).
Also, code-snippets are usually not all that helpful on their own; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

> But the second after `PDFViewerApplication.open(pdfData)` is called, Safari (and only Safari!) is reloading the website and gives me the following awesome message:

That sounds somewhat like issue #13726, which is a bug in the Safari browser *itself*.

---

All-in-all, closing since we cannot provide assistance without a lot more information and that it's likely a duplicate of #13726.

**Closed by Snuffleupagus** 2021-09-20 09:22 UTC
