### ISSUE TITLE
[Bug]: Cannot Select or Highlight Link Text

### ISSUE THREAD

**Issue by srshupe** [mozilla/pdf.js#18422] opened 2024-07-11 08:36 UTC
### Attach (recommended) or Link to PDF file

[link_basic.pdf](https://github.com/user-attachments/files/16173719/link_basic.pdf)

### Web browser and its version

Chrome v126.0.6478.127, also tried Firefox v128.0 and Edge v126.0.2592.87

### Operating system and its version

Windows 11 v10.0.22621

### PDF.js version

4.5.53

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. In the attached PDF, try to highlight the text or even click on the 4th link: "Link to an external file..." The user is unable to.
2. The other, valid, links can be clicked but cannot be highlighted and the text cannot be copied.

### What is the expected behavior?

Being able to highlight/copy the visible text to a link. This was possible in PDF.js v2.5.207 but stopped working around v3.5.141. I think in 2.5.207 links were not supported and were just being rendered as text.

### What went wrong?

Text cannot be selected. If the link is not recognized by PDF.js it cannot be clicked on either.

**Comment by Snuffleupagus** [comment] 2024-07-11 08:41
Duplicate of #18266

**Closed** 2024-07-11 08:41 UTC
