### ISSUE TITLE
this keyword different behavior in Firefox compared to ie and chrome

### ISSUE THREAD

**Issue by yn1378** [mozilla/pdf.js#7460] opened 2016-06-30 14:09 UTC
Using the _next: function InternalRenderTask__next() { function in pdf.js (line 10521) when in Internet Explorer or Chrome I get to line

this.operatorListIdx = this.gfx.executeOperatorList(this.operatorList,
                                            this.operatorListIdx,
                                            this._continueBound,
                                            this.stepper);
it behaves fine and I get correct results. But in Firefox this line of code trigger function

this._onComObjOnMessage = function messageHandlerComObjOnMessage(event) {
in line 1671 which causes to change this.operatorList.argsArray.length value and consequently this.operatorListIdx that changes the results.

How can I resolve this issue in Firefox?

**Comment by yurydelendik** [comment] 2016-06-30 14:26
How can we reproduce your issue? There is no guarantee that code will execute is the same sequence on legacy browsers (e.g. IE9) in comparison as on modern browsers. Please provide exact steps and example online. The issue is incomplete without this information.

**Comment by yn1378** [comment] 2016-06-30 14:48
Hi Yury,
Thank you very mush for your quick response. This is a website which is a base for an app that extract highlights from pdf files and I do not want to put it online. Can I send it to you as an attachment? For your information I am using latest ie and with ie I can extract all the highlights in a pdf file.
RegardsYahya Najafi 

    On Thursday, June 30, 2016 10:27 AM, Yury Delendik <notifications@github.com> wrote:
 

 How can we reproduce your issue? There is no guarantee that code will execute is the same sequence on legacy browsers (e.g. IE9) in comparison as on modern browsers. Please provide exact steps and example online. The issue is incomplete without this information.—

**Comment by yn1378** [comment] 2016-06-30 15:36
Following please find the code that I am using in pdf.js file. For your information I am using the latest vertion of ie, chrome and firefox.

_next: function InternalRenderTask__next() {
      if (this.cancelled) {
        return;
      }
      this.operatorListIdx = this.gfx.executeOperatorList(this.operatorList,
                                        this.operatorListIdx,
                                        this._continueBound,
                                        this.stepper);

      if (this.operatorListIdx === this.operatorList.argsArray.length) {
         

          ++icounter;
          var pageT = document.body.children[1].childElementCount;
          if (pageT != 0 ) pageTotal = pageT;

          if (icounter <= pageTotal) {
              // Calculate annTotalNum
          }

          if(pageTotal > 0 && icounter > pageTotal){
              // do something
              }

              // Do some operations


              setInterval(function () {
                  progBarWidth = progBarWidth >= 100 ? 100 : Math.round((annNum/(annTotalNum))*100);  
                  document.getElementById('myBar').style.width = progBarWidth + '%';
                  document.getElementById("label").innerHTML = progBarWidth * 1 + '%';}, 200); 

              if (annNum == annTotalNum) {  
                  //show final results
              }
          }

        this.running = false;
        if (this.operatorList.lastChunk) {
          this.gfx.endDrawing();
          this.callback();
        } 
      }
    }

Also folowing you can find the main.js file:

function loadPDFJS() {
    PDFJS.workerSrc = './build/pdf.worker.js';
    var pdfUrl = '3.pdf'

    var pdf = PDFJS.getDocument(pdfUrl).then(function (pdf) {
        var container = document.getElementById("container");
        for (var i = 1; i <= pdf.numPages; i++) {
            pdf.getPage(i).then(function (page) {
                var scale = 1;
                var viewport  = page.getViewport(scale);
                var div = document.createElement("div");
                
                div.setAttribute("id", "page-" + (page.pageIndex + 1));
                div.setAttribute("style", "position: relative");
                container.appendChild(div);
                var canvas = document.createElement("canvas");
                div.appendChild(canvas);

                var context = canvas.getContext('2d');
                canvas.height = viewport.height;
                canvas.width = viewport.width;

                var renderContext = {
                    canvasContext: context,
                    viewport: viewport
                };
                page.getAnnotations().then(function (annotations) {
                    var render = page.render(renderContext, annotations);
                });
            });
        }
    });
}

**Comment by yurydelendik** [comment] 2016-06-30 15:40
I'll close the issue until steps the reproduce and example online provided. I'm sorry, there is nothing we can do at this point.

**Closed by yurydelendik** 2016-06-30 15:40 UTC
Labels: 4-information-requested

**Comment by yn1378** [comment] 2016-07-04 16:54
Attached you can have all the website code. If we run it and add a breakpoint at line 10312 of pdf.js file you can see that in IE it loops all the 3 pages for this.operatorList.argsArray.length = 0 and then loops for other values of this.operatorList.argsArray.length on all 3 pages (total loop 6). But in Firefox it loops only for values of this.operatorList.argsArray.length other than 0 (total loop 3). In Chrome total loops are 4 and it will loop only first page for this.operatorList.argsArray.length = 0. Is it possible to force IE behavior on Firefox and Chrome?
 

    On Thursday, June 30, 2016 11:41 AM, Yury Delendik <notifications@github.com> wrote:
 

 I'll close the issue until steps the reproduce and example online provided. I'm sorry, there is nothing we can do at this point.—
