### ISSUE TITLE
Watermarks are opaque and not semi-transparent on FireFox 49.0.1 

### ISSUE THREAD

**Issue by chishtie** [mozilla/pdf.js#7695] opened 2016-10-06 18:47 UTC
Link to PDF file (or attach file here):
[tst-wmark.pdf](https://github.com/mozilla/pdf.js/files/514547/tst-wmark.pdf)

Configuration:
- FF 49.0.1
- Operating system and its version: OSX 10.9.5
- PDF.js version: 1.6.219 on https://mozilla.github.io/pdf.js/web/viewer.html. I have seen the same opaque watermarks on 1.5.188 and 1.4.20.
- Is an extension: No - can be seen on PDFjs viewer demo on github

Steps to reproduce the problem:
1. Use the attached PDF file and open it in FF 49.0.1 and you will see opaque watermarks.
2. Open the same file on FF 48.0.2 (or Chrome 53 or Safari 9.1.2 and you will see semi-transparent watermark as expected. Same semi-transparent watermark can be seen with Adobe Reader too.

No errors were reported by PDF.js however. So I assume something changed in FF 49.0 that causes this issue. 
<img width="1195" alt="screenshot-adobereader" src="https://cloud.githubusercontent.com/assets/1591206/19165877/27491eb4-8bcb-11e6-82c5-2ea24a59f465.png">
<img width="1320" alt="screenshot-ff49 0-viewer" src="https://cloud.githubusercontent.com/assets/1591206/19165881/2c611ffa-8bcb-11e6-8c27-929c6618cdba.png">

**Comment by Snuffleupagus** [comment] 2016-10-06 19:49
Closing as duplicate of issue #7674 (the upstream bug will be fixed in Firefox 50).

**Closed by Snuffleupagus** 2016-10-06 19:49 UTC
