### ISSUE TITLE
PDF JS shows black page for very big Excel spreadsheet

### ISSUE THREAD

**Issue by sai571** [mozilla/pdf.js#7952] opened 2017-01-12 22:12 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:Version 55.0.2883.95 (64-bit)
- Operating system and its version: Mac OS X El Captain 10.11.6
- PDF.js version: 1.5.188
- Is an extension: No

Steps to reproduce the problem:
1.  Open the PDF file using the browse option in the PDFJS Viewer
[PeakLoadGrowth_Redacted.xlsx.pdf](https://github.com/mozilla/pdf.js/files/703007/PeakLoadGrowth_Redacted.xlsx.pdf)

2. Goto the second page and you can see the black page

What is the expected behavior? (add screenshot)
You can see it renders properly in Chrome browser
<img width="1277" alt="screen shot 2017-01-12 at 2 10 23 pm" src="https://cloud.githubusercontent.com/assets/3194481/21910445/ea2bded8-d8d0-11e6-9083-3cbace6c9637.png">

What went wrong? (add screenshot)
You can see below, the 2nd page itself is totally black
<img width="1277" alt="screen shot 2017-01-12 at 2 11 31 pm" src="https://cloud.githubusercontent.com/assets/3194481/21910480/0ce73b3e-d8d1-11e6-92d6-4665a6d1f62b.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment] 2017-01-15 15:18
duplicate of #2541?

**Comment by CWickell** [comment] 2019-11-05 21:59
How did you convert the .xlsx file to .xlsx.pdf?

**Comment by Snuffleupagus** [comment] 2021-09-29 11:18
Duplicate of #12957

**Closed by Snuffleupagus** 2021-09-29 11:18 UTC
Labels: 1-core, 2-performance, 3-pdf-broken
