### ISSUE TITLE
pdf render upside down

### ISSUE THREAD

**Issue by fachhoch** [mozilla/pdf.js#10518] opened 2019-02-04 00:29 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  Chrome, IE all browsers
- Operating system and its version:  windows 7
- PDF.js version: 2.0.943
- Is a browser extension:

Steps to reproduce the problem:
attached project, 
[test.zip](https://github.com/mozilla/pdf.js/files/2826177/test.zip)

What is the expected behavior? (add screenshot) ![correct](https://user-images.githubusercontent.com/450078/52185056-2bf74780-27e9-11e9-93ef-317a6ee9aa23.JPG)

What went wrong? (add screenshot)
![renderissue](https://user-images.githubusercontent.com/450078/52185051-1124d300-27e9-11e9-8279-94f041092015.JPG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-02-04 07:35
Duplicate of #10418.

**Closed** 2019-02-04 22:51 UTC

**Comment by 759325100** [comment] 2019-09-04 03:05
How any update? The problem still exists. @Snuffleupagus  @timvandermeij

**Comment by xdvarpunen** [comment] 2020-05-06 04:35
Problem still occurs using syntax `page.getViewport({scale: 1.0})`.
