### ISSUE TITLE
Document gets Inverted/Black

### ISSUE THREAD

**Issue by pradeep-ns** [mozilla/pdf.js#7922] opened 2016-12-30 07:42 UTC
The documents gets inverted/black while opening in PDF.JS. The document with white background and black text is getting inverted to black background and white text. These documents contain DeviceGray decode params and they  render properly in Adobe reader 

PDF.JS version used: 1.1.3

Could you please let me know if there is any workaround to resolve this issue.

**Comment by Snuffleupagus** [comment] 2016-12-30 09:50
Closing as incomplete, please provide *all* the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md to re-open.

> PDF.JS version used: 1.1.3

That version more than one and a half years old, please also check if the issue is still present in the *latest* version of PDF.js.

**Closed by Snuffleupagus** 2016-12-30 09:50 UTC
