### ISSUE TITLE
Is imageCache in Parser working?

### ISSUE THREAD

**Issue by ThomasdenH** [mozilla/pdf.js#8790] opened 2017-08-18 09:40 UTC
Relevant to latest version. (8c8d8fa2390bac75a3afbe9f4f0cbd60bb708282)

The `imageCache` property in the parser seems very strange to me. I don't think it works at all in its current form. When initialized, it is an empty object. An image is added to the cache if its adler32 hash is not 'undefined'. But apparently looking up an image from the cache is incorrect. It checks the non-existent property 'adler32' and compares it to a string.

It seems the relevant changes have been made in 970c048d50335658f1646b88acd2bf17d9c88230. The cache has been refactored here, but the old properties are still accessed.

**Comment by yurydelendik** [comment] 2017-08-18 11:29
Steps to reproduce a problem and PDF is needed.

**Comment by ThomasdenH** [comment] 2017-08-18 12:15
I have no problem, it's just that I think something is not working as expected.

**Comment by yurydelendik** [comment] 2017-08-18 13:27
Closing as incomplete.

**Comment by timvandermeij** [comment] 2017-08-18 21:37
You're correct that this is in fact not working as expected. The pull request above should solve the issue. Thank you for reporting this, and sorry it got closed before. We regularly get reported issues where not enough requested information is provided, making the ticket not actionable. This particular issue took more time to verify because a PDF file had to be found that exposed the issue (since we tend to avoid blindly fixing things without something to verify it, even though this cache lookup was indeed wrong).

**Closed** 2017-08-19 07:12 UTC
Labels: 1-core

**Comment by ThomasdenH** [comment] 2017-08-20 14:33
It's not a problem. Great that this could be fixed so quickly!
