### ISSUE TITLE
couldn't display the electronic signature of the attach pdf

### ISSUE THREAD

**Issue by Yanghailong1024** [mozilla/pdf.js#9522] opened 2018-03-02 07:44 UTC
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/1774086/test.pdf)

Configuration:
- Web browser and its version:Internet Explorer 11
- Operating system and its version:Windows 10
- PDF.js version:pdfjs-dist 2.0.185
- Is a browser extension:No

Steps to reproduce the problem:
1. Open the PDF file.

What is the expected behavior? (add screenshot)
1.Make the electronic signature show it self
![image](https://user-images.githubusercontent.com/36982401/36888162-3a384908-1e2f-11e8-9d55-a36aee52a1d6.png)

What went wrong? 
1. the electronic signature on the second page and the content of the second could not be seen.

**Comment by Snuffleupagus** [comment] 2018-03-02 07:51
Closing as duplicate of issues such as #1076, #4202, and #4743.

**Closed by Snuffleupagus** 2018-03-02 07:51 UTC
