### ISSUE TITLE
'textlayerrendered' event not alway fired when added by document.addEventListener

### ISSUE THREAD

**Issue by futurist** [mozilla/pdf.js#6497] opened 2015-10-03 14:59 UTC
I have a code in my project like below:
````
document.addEventListener('textlayerrendered', function (e) {
  var pageIndex = e.detail.pageNumber - 1;
  var pageView = PDFViewerApplication.pdfViewer.getPageView(pageIndex);
  console.log('text rendered', pageView );
  [ below is my logic ]
}, true);
````
But problem is `textlayerrendered` not alway fired, some times there's no CONSOLE output; and [my logic] part don't work at all, and no error reported in console. But after a fresh(F5), the event fired with no problem;

It's hard to catch, about 2-5% chance to encounter this; Please confirm whether some thing went buggy? or it's the problem of my network?

**Comment by timvandermeij** [comment] 2015-10-03 18:57
Could you set up a jsFiddle, jsBin or another minimal example that shows the problem for you so we can try to reproduce it?

**Comment by timvandermeij** [comment] 2015-10-10 11:04
Closing as incomplete for now until the information requested above is provided.

**Comment by anirudh-modi** [comment] 2016-04-20 11:22
This issue is occurring for me also..I have noticed this is occurring in mobile, after a specific zoom level..
In viewer.js please add a breakpoint, when the event is being listened line 8212..
And start zooming in debugger mode...

http://jsbin.com/fikazakane/edit?output


Here is the jsbin

**Comment by timvandermeij** [comment] 2016-09-04 22:06
The provided JSBin is just the regular viewer in an `iframe`, so this does not display the problem. Since this issue was opened, there has been refactoring of the viewer events. Closing as incomplete until a clear example is provided that shows the problem.

**Closed by timvandermeij** 2016-09-04 22:06 UTC
Labels: 1-viewer, 4-triage-needed

**Comment by diwakar1911** [comment] 2019-02-22 22:49
set "eventBusDispatchToDOM": true in viewer.js why isn't anyone telling this!
