### ISSUE TITLE
unexpected scroll to second page

### ISSUE THREAD

**Issue by TZanke** [mozilla/pdf.js#8743] opened 2017-08-03 09:25 UTC
Link to PDF file (or attach file here):
[compressed.tracemonkey-pldi-09-rotated.pdf](https://github.com/mozilla/pdf.js/files/1196646/compressed.tracemonkey-pldi-09-rotated.pdf)

Configuration:
- Web browser and its version: Chrome 60 Firefox 54
- Operating system and its version: Ubuntu 16.04 + Customers complain on windows 
- PDF.js version:  tested with 1.4 stable and 1.7 stable
- Is an extension: original code

Steps to reproduce the problem:
1. rotate a pdf on disk
2. sidenote: now pdf.js inverts scrollLeft and scrollTop in pdfjs.history when scrolling
3. localstorage set "pdfjs.preferences" to {"defaultZoomValue":"auto", "showPreviousViewOnLoad": 0}
4. which defaultZoomValue does not matter, just add some valid setting
5. reload viewer, now the document is scrolled to the second page, if the document only has one page, you are watching the footer of the page

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html?file=https%3A%2F%2Fs2.nofilecdn.io%2Fg%2FfbVTs8aqWb0y8KaapkjUKpeiqvSc8JBKFPFZUAnCl83oFdnAfqq1M9yqTUAj4Q2P%2Fcompressed.tracemonkey-pldi-09-rotated.pdf

File is uploaded for 30 days, hope this is enough

**Comment by Snuffleupagus** [comment] 2017-08-03 09:40
> rotate a pdf on disk

Based on this, closing as duplicate of #5927.

> localstorage set "pdfjs.preferences" to {"defaultZoomValue":"auto", "showPreviousViewOnLoad": 0}

As an aside: `showPreviousViewOnLoad` should be a boolean and not an integer, please use `PDFViewerApplication.preferences.set(...)` rather than editing localStorage manually.

**Closed by Snuffleupagus** 2017-08-03 09:40 UTC

**Comment by TZanke** [comment] 2017-08-04 10:19
I rechecked the problem. Now i dont think its the same problem as you mentioned.

Idea:
disabling showPreviousViewOnLoad does not load the history data of X/Y coordinates, instead it set both to 0.

If we have a PDF file with orientation 0° the Position 0,0 is top left, so we scroll to the top => ok
If the PDF has a orientation 90 clockwise, the 0,0 position now is top right, we scroll to the top, all is working fine.
But now, i rotate the page 90° **counter clockwise**, the 0,0 position is left bottom, now pdf.js scrolls to this position. Now we see the second page.
Same for 180°, 0,0 is now right bottom, we also scroll to the second page.

So it looks like there is something wrong with the 0,0 coordinates for rotated pdf files, because 0,0 depends on the orientation of the page
