### ISSUE TITLE
pdf completely rendered blank

### ISSUE THREAD

**Issue by gHensges** [mozilla/pdf.js#9285] opened 2017-12-15 16:07 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
Chrome Version 63
- Operating system and its version:
Windows 7
- PDF.js version:
Your actual Demo Project
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/29802177/34050160-302eb066-e1ba-11e7-86cd-8f50e3dfdeb5.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/29802177/34050183-48863eae-e1ba-11e7-9d09-2fedfbe8e632.png)
[4149180-355989.pdf](https://github.com/mozilla/pdf.js/files/1563256/4149180-355989.pdf)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2017-12-15 20:29
Interesting. I have not seen the "too much recursion" exception before. Okular on Linux handles it just fine. The console log is:

```
Warning: getOperatorList - ignoring errors during task: RenderPageRequest: page 0
Warning: Unable to decode image: InternalError: too much recursion
Warning: Dependent image isn't ready yet
Warning: getOperatorList - ignoring errors during task: RenderPageRequest: page 1
Warning: Unable to decode image: InternalError: too much recursion
Warning: Dependent image isn't ready yet
```

**Comment by Snuffleupagus** [comment] 2017-12-20 13:33
This appears to be a "regression" from PR #6112, even though the underlying issue seem to be older.

**Comment by gHensges** [comment] 2018-01-03 08:26
Is there any progress made on this issue or do I have to go for an alternative renderer?

**Comment by timvandermeij** [comment] 2018-01-03 21:58
The pull request above contains a fix, but it is not yet merged.

**Closed** 2018-01-12 21:01 UTC
Labels: 3-pdf-broken, 3-regression, 4-image-conversion

**Comment by shiguanglu** [comment] 2018-03-26 15:16
@gHensges , Did the fix works for you? since I have same problem and it seem still not working fro me.
Thanks

**Comment by gHensges** [comment] 2018-03-26 15:55
@shiguanglu , Yes this fix solved my problem.
