### ISSUE TITLE
2nd PDF on same page does not finish loading using pdfjs-dist SimpleViewer example

### ISSUE THREAD

**Issue by redfox05** [mozilla/pdf.js#12052] opened 2020-07-02 15:34 UTC
I am unable to successfully load two PDF documents consecutively, even two identical PDFs.

I am using the official SimpleViewer component example from PDF.js, which works fine for a single document with several pages, until I try to load multiple documents, which does not work as expected.

The first document loads correctly, the second document just displays loading indicators, and no errors.

### PDF used
Attach (recommended) or Link to PDF file here: The example PDF https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf

### Configuration:
- Web browser and its version: Version 83.0.4103.116 (Official Build) (64-bit)
- Operating system and its version: macOS Catalina 10.15.4
- PDF.js version: 2.5.207
- Is a browser extension: No. Embedded in webpage.

### Steps to reproduce the problem:
1. Go to JSFiddle here: https://jsfiddle.net/redfox05/xvpzwLc2/
2. Run the code, and scroll down paste the first rendered pages until you see loading indicators. This is the second instance of the same PDF, but attempting to load in fully separate containers.
If not using the JSFiddle, the way to reproduce is as follows:
1. Use the SimpleViewer example from https://github.com/mozilla/pdf.js/tree/master/examples/components
2. Modify the initial script to take an array of urls, and add in a promise from the loadingTask to start loading the second document when the first is finished.

### What is the expected behavior? (add screenshot)
The PDF document is successfully loaded twice, and no more loading indicators are pending.
Unable to add screenshot, as have not been able to get it to work.

### What went wrong?
First PDF document loads as expected, but the second document never finishes loading, and just hangs with loading indicators on each page.

### Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://jsfiddle.net/redfox05/xvpzwLc2/

**Comment by Snuffleupagus** [comment] 2020-07-02 16:58
I believe that this issue is, for all intents and purposes, a duplicate of #11626.

A possible work-around could be to place each `simpleviewer` instance in its own `<iframe>`.

**Comment by redfox05** [comment] 2020-07-02 17:04
@Snuffleupagus Thanks for the quick reply.
Yeah I was wondering that too, but the iframe route is my last resort. I would like to try to identify what is causing this, as the iframe route is more going around the problem, and sadly the iframe route also has its own problems for my implementation.

Having looked at this none stop for the last few days, I'm thinking this should be related to some kind of global variables, event listeners or something else that is global.

I tried it with the most simplest implementation of the helloworld examples, and multiple documents works, however, these options are too basic, as theres no multi page, no text selection, and no annotations/links. But at least this tells me PDF.js CAN do this, theres just a bug somewhere in the more complicated viewer implementations.

**Comment by redfox05** [comment] 2020-07-02 17:06
Looking at #11626, its referring to CSS positioning, but surely this is more than a visual thing, as looking at the actual DOM, the PDF contents of the second document is not loading into the container divs, its still just stuck with the loading indicator. Which makes me think its just got stuck somewhere. But im not familiar with the more complicated viewer codes, so im hoping someone could help me here, or at least suggest places to look to debug further.

**Comment by redfox05** [comment] 2020-07-02 17:33
Im still trying to figure out how this can be a duplicate of that other issue, if you could explain that, it might help. Reading the other issues related to this, you and other devs have tried pointing people to the examples in the component directory for better understanding, so I have tried to do that, but does not seem to clarify where things are not working.

I'm currently trying to figure out PDFViewer (used by SimpleViewer) vs PDFPageView (used by PageViewer). Could you explain the differences? I first thought page view is for single pages, and simple is to view all, but the classes they depend on are vastly different, would have thought one would extend the other. Anyways, just thought this could be another option for you to help if you are unable to help figure out the main issue I am having.

**Comment by Snuffleupagus** [comment] 2020-07-02 17:37
> I would like to try to identify what is causing this,

The fact your second `simpleviewer` is *relatively positioned*, which is *not* currently supported, and that's what issue #11626 is already tracking.

Actually, I'm not even convinced that your first `simpleviewer` instance is working correctly either (it also appears to be *relatively positioned*), since it seems to always treat every page as visible.

---

Basically, unless the viewer container itself if *absolutely positioned* then the `getVisibleElements` function cannot accurately determine which pages are visible and you get the sort of problems described here.
Fixing this, without obviously breaking the default viewer and thus Firefox in the process, is unfortunately not that simple which is why issue #11626 is still open.

**Comment by redfox05** [comment] 2020-07-03 11:52
@Snuffleupagus okay that helps understand it a bit more. So would it help if I looked into having the containers absolutely positioned during rendering, and then place as needed on the page after its all done?

I'm assuming this is to do with loading PDF pages as the user scrolls, but what if you just want to load them immediately one after another, why would there be a need to know which elements are visible?

**Comment by Snuffleupagus** [comment] 2020-07-03 12:09
> So would it help if I looked into having the containers absolutely positioned during rendering, and then place as needed on the page after its all done?

With the current behaviour of requiring *absolute* positioning of the viewer container[1], it simply *needs* to remain positioned in that way unfortunately. If you change that, even after the fact, the `getVisibleElements` function no longer works correctly and things will break in one way or another.

> I'm assuming this is to do with loading PDF pages as the user scrolls,

Correct.

> but what if you just want to load them immediately one after another,

As explained in the Wiki, that is really not a good idea for performance/memory reasons (consider e.g. a 1000 page document); see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages

> why would there be a need to know which elements are visible?

To know which pages of the document, out of potentially thousands, are currently visible (see above).

---
[1] The default viewer is/was originally written for Firefox, where it's used stand-alone, rather than for custom embedding; unfortunately that show rather clearly in some areas :-(

**Comment by timvandermeij** [comment] 2020-07-03 22:32
Closing as answered and tracked in the other mentioned issue.

**Closed by timvandermeij** 2020-07-03 22:32 UTC
