### ISSUE TITLE
Invalid color display of images in PDF, wrong in all browsers in different ways

### ISSUE THREAD

**Issue by ssaring** [mozilla/pdf.js#11400] opened 2019-12-10 08:32 UTC
**Attached Example PDF document:**

[Elevation_Map_2D_Report.pdf](https://github.com/mozilla/pdf.js/files/3943711/Elevation_Map_2D_Report.pdf)

**Configuration:**
- Web browser and its version: Firefox 71, Chrome 78, Edge 44, Safari 13
- Operating system and its version: Windows 10 v1809 and macOS Catalina 10.15.1
- PDF.js version: 2.4.176 (the one on https://mozilla.github.io/pdf.js/web/viewer.html as of today)
- Is a browser extension: No

**Steps to reproduce the problem:**
1.  Open Firefox, Chrome, Edge or Safari
2.  Go to https://mozilla.github.io/pdf.js/web/viewer.html
3.  Open the attached PDF Elevation_Map_2D_Report.pdf

**What is the expected behavior?** 

Screenshot from Adobe Acrobat DC on Windows 10 v1809):

![Screenshot-Acrobat_Reader_DC](https://user-images.githubusercontent.com/1352763/70508562-fa4cbc80-1b2e-11ea-8cbc-defe3fd427fd.png)

**What went wrong? (see screenshots)**

The images in the center of the document are rendered with wrong colors in all of the listed browsers. The colors are too bright in each browser, but on a different level. And in Firefox and Safari the right image has even brighter colors than the left image.

Image rendered in Firefox 71 on Windows 1809:

![Screenshot-Firefox_71](https://user-images.githubusercontent.com/1352763/70509914-64fdf800-1b2f-11ea-9486-71cd5d037f4d.png)

Image rendered in Chrome 78 on Windows 1809:

![Screenshot-Chrome_78](https://user-images.githubusercontent.com/1352763/70510068-6fb88d00-1b2f-11ea-9b43-e74211d630a9.png)

Image rendered in Edge 44 on Windows 1809:

![Screenshot-Edge_44](https://user-images.githubusercontent.com/1352763/70510187-7810c800-1b2f-11ea-886a-f5cb7122363d.png)

Image rendered in Safari 13 on macOS 10.15.1:

![Screenshot-Safari_13](https://user-images.githubusercontent.com/1352763/70540135-fc317280-1b64-11ea-994a-1492846848b2.png)

Does anybode else has problems with this coloring bug and is there a feasible workaround?

**Comment by DevWurm** [comment] 2019-12-10 08:40
We have exactly the same issue in our project :confused:

**Comment by Snuffleupagus** [comment] 2019-12-10 10:49
This looks, for all intents and purposes, just like another duplicate of #3351.

**Comment by timvandermeij** [comment] 2019-12-10 22:03
Wouldn't that only explain the white lines and not the overall color differences?

**Comment by Snuffleupagus** [comment] 2019-12-10 23:03
> Wouldn't that only explain the white lines and not the overall color differences?

Maybe not necessarily; if you consider that as the segments of the "whole" image becomes narrower, there needs to be a lot more of them to make up the full image. Given that every edge between segments result a white line, an increased number of image segments would then increase the amount of white lines and thus result in the "whole" image looking more faded.

**Comment by ssaring** [comment] 2019-12-11 10:20
@Snuffleupagus You're probably right, it seems to be the same problem as in bug #3351.  I've analyzed the image structure in the attached PDF, every single line of an image seems to be a new segment. When there are white lines between those segment lines, this results in a brighter rendering.
Its's also interesting, that the left and the right images are using separarte segment lines, this could be the reason why the images are different brighter when using the FireFox browser.

The issue / bug #3351 is now more than 6 years old and there's the pull request #10016 with a potential bugfix with no activity since last year - both are in state "Open". 

@Snuffleupagus @timvandermeij Unfortunately I have no programming skills in this PDF and rendering context, is there any other way to support the progress on these issues? We're depending on a solution in our current project, it would be helpful to know whether there's a chance for solving these problems.

**Comment by Snuffleupagus** [comment] 2019-12-11 14:24
> [...] and there's the pull request #10016 with a potential bugfix with no activity since last year

If you look at the test results in that PR, there's simply way too many outright rendering regressions (and generally too much movement in lot of tests) for that PR to be acceptable in its current form.

**Comment by DevWurm** [comment] 2020-03-24 15:55
Is there any update on this? Would be really important for us...

**Comment by Snuffleupagus** [comment] 2021-06-06 14:28
Duplicate of #3351

**Closed by Snuffleupagus** 2021-06-06 14:28 UTC
Labels: 1-core, 2-image-quality
