### ISSUE TITLE
Question: pageColors seems to be an unsatisfactory change in release >= 3.5.141 on safari

### ISSUE THREAD

**Issue by maxiloEmmmm** [mozilla/pdf.js#16847] opened 2023-08-18 02:36 UTC
maybe this https://stackoverflow.com/questions/51549143/context-filter-not-working-on-safari

https://github.com/mozilla/pdf.js/blob/c72cb5436def2d6f2e703447c8b901e92b4dd403/src/display/canvas.js#L1168

old version use 
https://github.com/mozilla/pdf.js/blob/5620456072246f4f9f9eda37137b580863e6526c/src/display/canvas.js#L1145

this seems to be an unsatisfactory change
@Snuffleupagus

_Originally posted by @maxiloEmmmm in https://github.com/mozilla/pdf.js/issues/16838#issuecomment-1680164661_

**Comment by Snuffleupagus** [comment] 2023-08-18 06:13
Duplicate of #16838

**Closed by Snuffleupagus** 2023-08-18 06:13 UTC
