### ISSUE TITLE
Poor Quality Font Substitution

### ISSUE THREAD

**Issue by jwillia3** [mozilla/pdf.js#17401] opened 2023-12-10 03:31 UTC
# Problem
[Example PDF](http://harmful.cat-v.org/cat-v/)

Font substitutions for PDFs that use Times without embedding it are of poor quality.

It appears that the builtin Firefox viewer is trying to use **DejaVu Serif** as a substitute for **Times**.

This font choice is surprising on my system for three reasons:
1. **DejaVu Serif** is not metric compatible with **Times** and makes the document illegible. ([Specified here, if I understand this correctly](https://github.com/mozilla/pdf.js/blob/master/src/core/font_substitutions.js#L51))
2. **Nimbus Roman** exists on my system but was not selected
3. My system has substitutions that remap **Times**, **Times New Roman**, and **Times-Roman** to **Linux Libertine**. These are not honoured

Excerpt from fonts.conf implementing aliases
```
  <match target="pattern">
    <test qual="any" name="family"><string>Times</string></test>
    <edit name="family" mode="assign" binding="strong"><string>Linux Libertine</string></edit>
  </match>
  <match target="pattern">
    <test qual="any" name="family"><string>Times-Roman</string></test>
    <edit name="family" mode="assign" binding="strong"><string>Linux Libertine</string></edit>
  </match>
  <match target="pattern">
    <test qual="any" name="family"><string>Times New Roman</string></test>
    <edit name="family" mode="assign" binding="strong"><string>Linux Libertine</string></edit>
  </match>
```

# Configuration:
Firefox 120.0 (64-bit)

```
# uname -a

FreeBSD pepperflower 14.0-STABLE FreeBSD 14.0-STABLE #3 stable/14-n265760-ae8387cc818a: Mon Nov 20 18:29:14 CST 2023     root@pepperflower:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64
```

Using built-in viewer.

# Steps to reproduce the problem:
1. Remove or disable the font Times New Roman
5. Open a PDF that uses Times without embedding it
6. Observe an alternate font being used
7. Re-add Times New Roman
8. Observe the correct font being used

# What is the expected behavior?
Properly using Times New Roman
![times-new-roman](https://github.com/mozilla/pdf.js/assets/650663/76d6cb51-13c2-4e54-a26d-e89a5b170f3e)

# What went wrong?
Using DejaVu Serif substitution
![dejavu-serif](https://github.com/mozilla/pdf.js/assets/650663/7b4493ed-7afb-4218-9d17-c3fc31550dc3)

**Comment by Snuffleupagus** [comment] 2023-12-10 12:39
This might be a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1839860, since it looks very similar.

**Comment by jwillia3** [comment] 2023-12-10 21:23
Sorry, I didn't see that one.
I think there is still an issue that wasn't addressed on the other thread, so I'll pick it up from there.
Thank you

**Comment by calixteman** [comment] 2023-12-11 09:29
@jwillia3 would you mind to test with the viewer:
https://github.com/mozilla/pdf.js/pull/17405#issuecomment-1849088795

According to the [css specifications](https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#src-desc):
```
For OpenType and TrueType fonts, this string is used to match only the Postscript name or the full font name in the name table of locally available fonts. Which type of name is used varies by platform and font, so authors should include both of these names to assure proper matching across platforms. Platform substitutions for a given font name must not be used. 
``
so `@font-face { src: local(...) }` shouldn't use platform substitutions.

**Closed** 2024-01-16 13:32 UTC
Labels: font-conversion
