### ISSUE TITLE
wingdings font not rendered properly

### ISSUE THREAD

**Issue by interstellerS** [mozilla/pdf.js#7454] opened 2016-06-29 11:36 UTC
Link to PDF file (sorry for not being able to attach file link since it's confidential pdf content):

Configuration:
- Web browser and its version: chrome (50.0.2661.94 m) , IE (11) , Firefox (46)
- Operating system and its version: Windows 7
- PDF.js version:1.5.309
- Is an extension:no

What is the expected behavior? (add screenshot)
![checkboxok](https://cloud.githubusercontent.com/assets/10755262/16450614/4af79388-3dfe-11e6-80e0-18e99768476f.png)

What went wrong? (add screenshot)
![checkboxko](https://cloud.githubusercontent.com/assets/10755262/16450621/51c9c92e-3dfe-11e6-90dc-7c603318f029.png)

The checkboxes are rendered fine with adobeReader and with chrome pdfjs Extension but cant renderer wingdings fonts properly .

**Comment by timvandermeij** [comment] 2016-06-29 19:14
I don't think there is anything we can do about this without a test PDF. Could you create a minimal example PDF that has the problem and share it here, or strip the main content out of the original PDF file?

**Comment by Snuffleupagus** [comment] 2016-06-29 19:17
Also, this could possibly be a duplicate of issue #6353.

**Closed** 2016-06-29 21:15 UTC
Labels: 4-information-requested

**Comment by interstellerS** [comment] 2016-07-08 13:45
The issue is closed but i ve been struggling to find a workaroud to my case without success .
Here I cropped the part of the pdf file that i mentioned first .
Any help is appreciated .
[checkboxError.pdf](https://github.com/mozilla/pdf.js/files/354357/checkboxError.pdf)

**Comment by interstellerS** [comment] 2016-07-08 13:46
The same Pdf is OK when viewed with chrome build in pdfjs viewer but failed in the online version of pdfViewer .

**Comment by THausherr** [comment] 2016-07-08 15:11
@interstellerS The other issue is still open.

**Comment by interstellerS** [comment] 2016-07-08 15:17
I don't think it's the same . I tested with many pdfjs Version old and new ones . I still get the same issue .

**Comment by yurydelendik** [comment] 2016-07-08 15:20
> The same Pdf is OK when viewed with chrome build in pdfjs viewer but failed in the online version of pdfViewer .
> I tested with many pdfjs Version old and new ones

Can you be more specific about versions when you are talking about old, new or build-in? (Version of the viewer is visible in the console while viewing PDF)

**Comment by yurydelendik** [comment] 2016-07-08 15:25
> OK when viewed with chrome build in pdfjs viewer 

This statement tells us that the viewer worked at one point. If not, that it's possible duplicate of the opened #6353 as it was triaged at https://github.com/mozilla/pdf.js/issues/7454#issuecomment-229459592 

> i ve been struggling to find a workaroud

There is no workaround on PDF.js side. If you will change PDF to embed fonts inside PDF file the issue shall go away.
