### ISSUE TITLE
Touchscreen: long pressing breaks touch interface

### ISSUE THREAD

**Issue by leezu** [mozilla/pdf.js#8776] opened 2017-08-14 02:54 UTC
On a device with touchscreen capabilities and with `MOZ_USE_XINPUT2=1` (possibly also without) I can normally use touch gestures to navigate / scroll a PDF file with pdf.js.

Long pressing triggers the right-click menu.

Once the right click menu is shown one, touch input does not work anymore in any pdfjs tab. Touch input continues to work correctly in other tabs.

Triggering the right-click menu via an actual right click does not break touchscreen.

Please let me know how to provide further information that may be relevant to identify what causes the bug.

This happens on Firefox 55.0 (64-bit) compiled from sources with the included version of pdfjs.

**Comment by timvandermeij** [comment] 2017-08-14 20:09
I think PDF.js only supports touch gestures for presentation mode, but AFAIK we don't support it for the default viewing mode. If it helps, the presentation mode touch gestures code is here: https://github.com/mozilla/pdf.js/blob/05b1ef2d2380d699c9d66dcdd9b1af4dab699b91/web/pdf_presentation_mode.js#L348. I'm not aware of any special handling of the right-click menu.

**Comment by leezu** [comment] 2017-08-15 10:53
I'm not sure how touch events are processed by firefox and pdfjs. What I referred to as gestures before is simple scrolling using a touch screen. I.e. dragging your finger along on the touch screen to scroll the website. As you're likely familiar from Android/iOS, the page continues to scroll after the finger is lifted.

I was reporting this issue here (and not the firefox bugtracker), as the "normal" firefox behaviour when long pressing via touch is to select text (again as on Android/iOS), whereas in pdfjs it opens the right click menu (and subsequently breaks all touch interaction in tabs using pdfjs).

Please let me know if I should raise this issue at the firefox bugtracker instead.

**Comment by timvandermeij** [comment] 2017-08-15 21:06
Thank you for the clarification. Long pressing should allow for text selection to happen, but perhaps it only works if the long press happens on the text layer, i.e., it could be that a long press on the canvas element itself has a different effect. The text layer does not overlap the entire page right now, only the relevant text portions. You could try enabling the (somewhat experimental) `enhanceTextSelection` preference (https://github.com/mozilla/pdf.js/blob/master/web/default_preferences.json#L16) as that should make the text layer fill the entire page, and see if the problem can still be reproduced.

**Comment by leezu** [comment] 2017-08-16 00:02
Thanks @timvandermeij . I need to build pdf.js from source to enable the preference, is that correct?

In the meantime I realized that the breakage of the touch interface is likely just https://bugzilla.mozilla.org/show_bug.cgi?id=1321069 , though it is not clear why pdfjs is opening the right click menu in the first place.

Let me further clarify the behaviour in Firefox and Chromium.
Firefox:
- Long press area in pdf with text
- Right click menu appears and word below is actually selected (sorry, I forgot to mention that the selection actually works. While in my memory the selection didn't work at all and only the right click menu appeared, it seems that was wrong..)
- Touch navigation completely stops working in pdfjs tabs, while the behaviour described in https://bugzilla.mozilla.org/show_bug.cgi?id=1321069 happens in other tabs

Chromium:
- Long press area in pdf with text
- Only text selection. No right click menu is shown

Sometimes I managed to get a right click menu by doing a long press after a fresh start of Chromium, but touch navigation continued to work afterwards. I could not reproduce getting the right click menu every time.


In Firefox the right click menu is shown every time. However there is no advantage in showing the right click menu. It shouldn't be shown.
Shall I change the title accordingly or open a new bug?

**Comment by timvandermeij** [comment] 2017-08-16 20:01
You can also try it as follows:

1. Open https://mozilla.github.io/pdf.js/web/viewer.html
2. Open the console (Ctrl + Shift + K) and enter the following command: `PDFViewerApplication.preferences.set('enhanceTextSelection', true);`
3. Refresh the page and try the steps to reproduce again.

Alternatively, you could build it from source, yes. It does sound like the Bugzilla issue you mentioned. I'm labeling this as upstream for now, so no need to change the title.

**Comment by timvandermeij** [comment] 2018-06-23 13:33
Closing since this issue is fixed upstream.

**Closed by timvandermeij** 2018-06-23 13:33 UTC
Labels: 1-viewer, 3-upstream
