### ISSUE TITLE
Viewer does not render data from a filled pdf (all data blank)

### ISSUE THREAD

**Issue by danielstachowiak** [mozilla/pdf.js#11068] opened 2019-08-14 15:15 UTC
Try rendering the attached document in the demo viewer: all fields appear blank.

[1 pager malfunctioning file.pdf](https://github.com/mozilla/pdf.js/files/3502038/1.pager.malfunctioning.file.pdf)

This issue is critical for all users who need to use fillable pdf documents.

**Comment by THausherr** [comment] 2019-08-15 10:05
This is not an acroform problem (although I suspect this is a flattened form). The problem is a missing font, as shown in this error message: "Error during font loading: Font Ffcs1 is not available". Just use some default font.

**Comment by Snuffleupagus** [comment] 2020-03-09 21:29
Should this be closed as fixed now, given the PR referenced above?

**Closed** 2020-03-09 21:45 UTC
Labels: 4-font-conversion
