### ISSUE TITLE
Toggling on/off features capability

### ISSUE THREAD

**Issue by tungnv** [mozilla/pdf.js#6186] opened 2015-07-09 09:15 UTC
Hi guys,

I'm using PDF.js as main PDF viewer for all pdf documents in our product on supported browers. We dont use all build in features on our PDF viewers but some of them. I believe the case also happens to any consumer. So please think about to support toggle on/off build in features capability for PDF.js programmatically.

**Comment by timvandermeij** [comment] 2015-07-09 11:17
Could you be more specific about which features you are talking about?

**Comment by tungnv** [comment] 2015-07-09 12:31
Hi Tim, 

Thanks for writting back to me. In details, in our application we're displaying PDF as a popup opened on any page and the features are being used: Page thumbnail, Paging, Zoom in/out, Page navigation bar but no searching,printing, .... Seeing that with current use of PDF.js we cant turn off a feature that we dont intend to represent to users. In some way when the PDF viewer is displayed some event and code still executed.

**Comment by timvandermeij** [comment] 2015-07-09 12:36
We are currently working on refactoring the code base to create web components to improve code structure but also to enable custom implementations to remove/disable them. We want to do this for the viewer API too, but since that is largely being tracked in #5830, I'm closing this one as a duplicate of that issue.

**Closed by timvandermeij** 2015-07-09 12:36 UTC
Labels: 4-information-requested

**Comment by timvandermeij** [comment] 2015-07-09 12:38
By the way, since what you are asking is not currently possible, the best solution would be to fork PDF.js and remove the code that you do not need youself.

**Comment by tungnv** [comment] 2015-07-09 14:23
Not a big deal. Thanks for replying and helpul information about next changes. Anyway, feature flag is also a good development approach.
