### ISSUE TITLE
PDF created from scanner is displayed with wrong orientation. (must not be displayed in landscape)

### ISSUE THREAD

**Issue by jespermandalhansen** [mozilla/pdf.js#6909] opened 2016-01-21 12:26 UTC
[pdf_that_is_rotated_wrong.pdf](https://github.com/mozilla/pdf.js/files/99101/pdf_that_is_rotated_wrong.pdf)

I have attached a pdf file that is displayed correct in Adobe, but in PDFViewer the pdf file is display in landscape mode. I hope somebody could have a look at it.

Best regards
Jesper

**Comment by Rob--W** [comment] 2016-01-21 13:07
Looks good to me in the latest version of PDF.js (1.3.231), and also older versions (1.1.527). Are you sure that you didn't accidentally hit the <kbd>R</kbd> key to rotate the page?

**Comment by timvandermeij** [comment] 2016-01-21 13:37
Looks good to me too using the latest version of PDF.js on Windows 10 x64.

**Comment by jespermandalhansen** [comment] 2016-01-21 13:44
Hi Rob Wu

 

I am very sure that it is only that specific PDF that is displayed in landscape mode, because we have many other PDF files that are displayed correct.

I know the customer from which we have this PDF file from, is scanning a document to PDF and those scanned documents are displayed wrong in PDFViewer, but correct in Adobe.

I have upgraded to version 1.2.109, but the problem remains the same.

 

Do you have an url to a location where I could try to upload the PDF and test with another PDFViewer than mine ? 

 

 

Best regards

Jesper

 

 

 

 

Fra: Rob Wu [mailto:notifications@github.com] 
Sendt: 21. januar 2016 14:07
Til: mozilla/pdf.js
Cc: jesper mandal hansen
Emne: Re: [pdf.js] PDF created from scanner is displayed with wrong orientation. (must not be displayed in landscape) (#6909)

 

Looks good to me in the latest version of PDF.js (1.3.231), and also older versions (1.1.527). Are you sure that you didn't accidentally hit the R key to rotate the page?

**Comment by timvandermeij** [comment] 2016-01-21 13:46
Please try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar), which is the latest version of PDF.js.

**Comment by timvandermeij** [comment] 2016-01-25 19:32
Closing for now as we cannot reproduce this issue with the most recent version of the viewer. It might be a problem with your custom viewer. We can reopen this when more information is provided to reproduce the issue (most importantly a link to your custom viewer and information about whether or not the issue occurs with the link posted above). Thanks.

**Closed by timvandermeij** 2016-01-25 19:32 UTC
Labels: 4-information-requested

**Comment by jespermandalhansen** [comment] 2016-01-25 20:13
Hi Tim
I found the problem. It was that we explicit set the rotation to 0. This caused a specifi PDF document to be displayed rotated 90 degrees to landscape mode. We have now neclected to set the rotation and just let PDF viewer decide the rotation and now everything is fine.
Thanks for answering so fast after i posted the issue.
Best regards
Jesper

**Comment by vvkbnd** [comment] 2021-10-21 12:09
Hi Jesper,
Can you please show the code where you had made changes in this library? It will be very helpful as I am facing the same issue.
