### ISSUE TITLE
Cannot read property 'WorkerMessageHandler' of undefined Why?

### ISSUE THREAD

**Issue by LiuSandy** [mozilla/pdf.js#11787] opened 2020-04-08 06:49 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 80.0.3987.149
- Operating system and its version:MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports
- PDF.js version:2.2.228
- Is a browser extension:

Steps to reproduce the problem:
1. This is the demo of the recurrence problem
[https://codesandbox.io/s/quizzical-sanderson-1zte2](https://codesandbox.io/s/quizzical-sanderson-1zte2)

What is the expected behavior? (add screenshot)
I want to know where the problem is and how to solve it
What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/22876827/78752758-3f7edf00-79a7-11ea-84a0-4111a9b7b4d9.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by LiuSandy** [comment] 2020-04-08 07:21
Using https in front of the url seems to resolve the problem for me:
`pdfjs.GlobalWorkerOptions.workerSrc = "https://cdn.bootcss.com/pdf.js/2.2.228/pdf.worker.js";`

**Comment by Snuffleupagus** [comment] 2020-04-08 09:59
> Web browser and its version: 80.0.3987.149

The actual browser *name* seems to be missing here (there's only a version number).

> PDF.js version: 2.2.228

That version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases

> This is the demo of the recurrence problem
> https://codesandbox.io/s/quizzical-sanderson-1zte2

That example seems to be using React, which I don't think any of the PDF.js core contributors know much about. Can you reproduce the error when using the PDF.js library *directly* without React?

---

*Ninja-edit:* Looking briefly at your example, there's this line:
```javascript
pdfjsLib.GlobalWorkerOptions.workerSrc = require("pdfjs-dist/build/pdf.worker.js");
```
That's not correct, since as you can see in the JSDocs that parameter must be a String: https://github.com/mozilla/pdf.js/blob/4fe92605b75d7e0952738b7f1575d78145b69aeb/src/display/worker_options.js#L27-L33

**Comment by timvandermeij** [comment] 2020-04-08 20:22
Closing as answered/solved based on the above.

**Closed by timvandermeij** 2020-04-08 20:22 UTC
