### ISSUE TITLE
Text selection Issue - when dragging past the end-of-line

### ISSUE THREAD

**Issue by lawriebaberscovell-solirius** [mozilla/pdf.js#11188] opened 2019-10-01 17:24 UTC
Attach (recommended) or Link to PDF file here: [compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/3677684/compressed.tracemonkey-pldi-09.pdf)

**Configuration:**
- Web browser and its version: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Pro (64 bit)
- PDF.js version: Latest on PDF.js Demo (2.3.198)
- Is a browser extension: No

**Steps to reproduce the problem:**
1. Go to [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)
2. Wait for the example document to load (compressed.tracemonkey-pldi-09.pdf)
3. Place the mouse pointer on the first text line of the second text column, starting with "and is used for"
4. Drag the mouse to the end of the second line, ending with "Zimbra Col-", selecting the text in the process.
5. Move the mouse further out to the right, towards the right side edge of the document
6. Observe the selection highlight, selecting either remaining text above or below the mouse pointer.

**What is the expected behavior? (add screenshot)**
Text selection highlight should be inline with the horizontal of the mouse (this is how PDF viewers and google pdf viewer highlights). So when the mouse moves beyond the end of the line, the highlight still remains inline with the mouse. This makes the selection more predictable and easier to use; especially for those with accessibility issues.

_Fox Reader_ - Highlight Example (pointer wasn't grabbed by the screenshot)
![Fox Reader - Highlight](https://user-images.githubusercontent.com/45463122/65983529-9a260400-e475-11e9-8185-7ba6ea014a78.png)

_Chrome PDF Reader_ - Highlight Example (pointer wasn't grabbed by the screenshot)
![Chrome PDF Reader - Highlight](https://user-images.githubusercontent.com/45463122/65983574-b7f36900-e475-11e9-8029-2c5f1f039e11.png)

**What went wrong? (add screenshot)**
Highlighting function selects remaining text, above or below, the starting position - depending on the mouse location - when the drag selection is past the line return.

![PDF js Reader - Highlight](https://user-images.githubusercontent.com/45463122/65983584-c17cd100-e475-11e9-9ffc-e6a9a08ac50c.png)

**Link to a viewer** (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by Snuffleupagus** [comment] 2019-10-01 17:42
Probably a duplicate of e.g. issue #9843.

**Closed** 2019-10-01 21:13 UTC

**Comment by FahadQurashi49** [comment] 2019-11-28 09:19
I already tried:
`PDFViewerApplication.preferences.set('textLayerMode', 2);`
but it does not solve the issue
