### ISSUE TITLE
Why is pdfjs-dist out of date?

### ISSUE THREAD

**Issue by maxsu** [mozilla/pdf.js#16947] opened 2023-09-14 05:43 UTC
Hi all, I was wondering how the [pdfjs-dist npm package](https://www.npmjs.com/package/pdfjs-dist) package stays up to date even though the [pdfjs-dist repo](https://github.com/mozilla/pdfjs-dist) is 8 minor versions behind the main repo. I could not find any github actions that build the NPM package, or find out where the build on npm comes from. I'm probably missing something basic, like maybe npm is doing the build from the upstream now.

I would appreciate some help to learn where the package is being built, since right now it seems a little spooky! Thanks! 👻

**Comment by Snuffleupagus** [comment] 2023-09-14 06:08
The `pdfjs-dist` library has always been build, and pushed to GitHub and NPM, by one of our bots (see https://github.com/mozilla/botio-files-pdfjs).
While publishing to NPM still works as intended, some time ago (see issue #15975) the updating of the GitHub-repo broke and I don't believe that we fully figured out why unfortunately.

This will hopefully be fixed once issue #11851 is done, however that's a fair amount of work involved in that.

**Closed by Snuffleupagus** 2023-09-14 06:08 UTC

**Comment by maxsu** [comment] 2023-09-14 07:15
Looks like you've given me all the info I need to understand how the bot works, and all the info I would need to help the conversion to github issues! The mystery is solved, and I can rest easy, and plan a colab!

Thank you, @Snuffleupagus, I can tell you really care about the pdfjs project!  Wishing the best to you!
