### ISSUE TITLE
Till When the pinch and zoom functionality would be implemented?

### ISSUE THREAD

**Issue by Gamerakki** [mozilla/pdf.js#6896] opened 2016-01-19 06:00 UTC
Hii, 
Fristly, great work done by you guys.. hats off to you.. 
I have read many issue thread and would like know till when the pinch and zoom functionality would be implemented?

**Comment by Snuffleupagus** [comment] 2016-01-19 08:57
There is no time-line for this, closing as duplicate of issue #2582.

**Closed by Snuffleupagus** 2016-01-19 08:57 UTC
