### ISSUE TITLE
Opening PDFs hangs for 5 seconds before displaying content, local or remote

### ISSUE THREAD

**Issue by dcog989** [mozilla/pdf.js#17463] opened 2023-12-26 10:05 UTC
Attach (recommended) or Link to PDF file here: https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

Configuration:
- Web browser and its version: Firefox Beta 122.0b3 64-bit (2023-12-26 build)
- Operating system and its version: Win11 Version 10.0.22635 Build 22635

- PDF.js version: 4.0.347
- Is a browser extension: no

Steps to reproduce the problem:
1. open any PDF, network or local

What is the expected behavior? Content should display instantly - which is true for Google Chrome and MS Edge

What went wrong? blank page is displayed for ~5 seconds before content is displayed.

![firefox-pdf-1](https://github.com/mozilla/pdf.js/assets/89043002/04d8fd5a-f383-4b4e-a7c3-09b78937267f)

**Comment by Snuffleupagus** [comment] 2023-12-26 10:23
> Attach (recommended) or Link to PDF file here: https://www.planetebook.com/free-ebooks/robinson-crusoe.pdf

Unfortunately that link doesn't work, at least for me, since it brings up a `403 Forbidden` error-page.
(Hence why the ISSUE_TEMPLATE recommends *attaching* the file, rather than linking to it.)

---

This *could* be a duplicate of e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1840762

**Comment by dcog989** [comment] 2023-12-26 12:32
> Unfortunately that link doesn't work

I've updated with a different PDF file, but as per rest of ticket, the exact PDF is irrelevant. Any PDF demonstrates the same behaviour.

> This _could_ be a duplicate of e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1840762

Thanks. I did search Bugzilla but drew a blank. Looks like https://searchfox.org/mozilla-central/rev/892475f3ba2b959aeaef19d1d8602494e3f2ae32/toolkit/components/pdfjs/content/web/viewer.js#3103 could be the culprit:

`setDisableAutoFetch(delay = 5000) {`

?????

**Comment by Snuffleupagus** [comment] 2023-12-26 12:47
> but as per rest of ticket, the exact PDF is irrelevant. Any PDF demonstrates the same behaviour.

I cannot reproduce this, and given the discussion in the bug it unfortunately doesn't appear that any developer has (so far) been able to reproduce it either.

> Looks like https://searchfox.org/mozilla-central/rev/892475f3ba2b959aeaef19d1d8602494e3f2ae32/toolkit/components/pdfjs/content/web/viewer.js#3103 could be the culprit:

As mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1840762#c17 that code should be unrelated here.

---

Let's just close this as a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1840762

**Closed by Snuffleupagus** 2023-12-26 12:47 UTC
Labels: information-requested
