### ISSUE TITLE
Sigma glyph not rendering in IE11

### ISSUE THREAD

**Issue by baldwin47** [mozilla/pdf.js#9254] opened 2017-12-08 21:11 UTC
Attach (recommended) or Link to PDF file here:
[formula.pdf](https://github.com/mozilla/pdf.js/files/1543813/formula.pdf)

Configuration:
- Web browser and its version: IE 11.0.9600.18816
- Operating system and its version: Windows 7
- PDF.js version: 1.7.255
- Is a browser extension: No

Steps to reproduce the problem:
1. Open a PDF with math formulas in pdf.js in IE 11
2. Note that the Σ character is replaced by a ? mark
This works properly in Chrome and Firefox

What is the expected behavior? (add screenshot)
![formula chrome](https://user-images.githubusercontent.com/9043572/33785239-1f287dc0-dc32-11e7-8498-da9e2836ca9d.png)

What went wrong? (add screenshot)
![formula ie11](https://user-images.githubusercontent.com/9043572/33785217-10ab068c-dc32-11e7-9912-b7d0742c527d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Our viewer is behind a paywall, but I tested in this viewer: https://mozilla.github.io/pdf.js/web/viewer.html in IE vs. Chrome using the PDF above, and see the same behavior

**Comment by Snuffleupagus** [comment] 2017-12-08 21:49
Closing as duplicate of issue #3599.

**Closed by Snuffleupagus** 2017-12-08 21:49 UTC
