### ISSUE TITLE
Invalid XRef stream header

### ISSUE THREAD

**Issue by sach0908** [mozilla/pdf.js#8607] opened 2017-07-04 12:10 UTC
Hi,
I am receiving the below error while loading all pdfs in pdfjs viewer. The same pdf stream was working fine couple of days back. After a recently code rebuild this error is encountered. Any leads on this will be appreciated.

Link to PDF file (or attach file here):
[pdfstream.txt](https://github.com/mozilla/pdf.js/files/1121935/pdfstream.txt)
The attached text file has the pdf stream.

Configuration:
- Web browser and its version: chrome v59.0.3071.115
- Operating system and its version:
- PDF.js version: 1.4.83
- Is an extension:

Steps to reproduce the problem:
1. I make a webapi call to get the pdf stream and load it in pdfjs.
2. pdfjs was working fine for a long time and recently this error started occurring when i rebuilt my code.

What is the expected behavior? (add screenshot)
pdf should load in the viewer

What went wrong? (add screenshot)
![pdferror](https://user-images.githubusercontent.com/29862952/27829458-5bd9b636-60df-11e7-9afb-9f2e6b29cda2.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-07-04 13:00
> PDF.js version: 1.4.83

First of all, that version is more than a year out of date. Please update to the latest release, see https://github.com/mozilla/pdf.js/releases, and check if the issue still exists.

> I am receiving the below error while loading all pdfs in pdfjs viewer. The same pdf stream was working fine couple of days back. After a recently code rebuild this error is encountered. Any leads on this will be appreciated.

This seem to suggest that there's an issue with the way that the PDF.js code was built, but without further information it's not really possible to provide additional assistance!
As asked for in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), please provide access to a working example since otherwise we cannot help.

**Comment by timvandermeij** [comment] 2017-07-14 10:42
Closing since the issue is incomplete. Provide the information requested above to reopen.

**Closed by timvandermeij** 2017-07-14 10:42 UTC
Labels: 4-information-requested
