### ISSUE TITLE
Don't work on huawei P30 and vivo X27

### ISSUE THREAD

**Issue by ZhuoJunErGe** [mozilla/pdf.js#14779] opened 2022-04-14 08:48 UTC
Attach (recommended) or Link to PDF file here:
https://www-sta.kbao123.com/gateway/oss4/insprolibs/T0001/B00042/T0001/term/2022/04/07/PRO20220303001076/1512009901235372034/%E9%99%84%E5%8A%A0%E8%87%BB%E9%80%89%E6%8A%95%E4%BF%9D%E4%BA%BA%E8%B1%81%E5%85%8D%E4%BF%9D%E9%99%A9%E8%B4%B9%E9%87%8D%E5%A4%A7%E7%96%BE%E7%97%85%E4%BF%9D%E9%99%A9%E6%9D%A1%E6%AC%BE%EF%BC%882022%E7%89%88001%E5%8F%B7%EF%BC%89.pdf?Expires=2280046227&OSSAccessKeyId=LTAIcKulqkzS6mjy&Signature=0mzbRcQ%2BZtdyJUF8uzFOso4I%2FEE%3D&

Configuration:
- Web browser and its version:chrome内核，版本不确定
- Operating system and its version:Android 11
- PDF.js version:2.13.216-dist
- Is a browser extension:

Steps to reproduce the problem:
1. app内建webview加载pdf
2.

What is the expected behavior? (add screenshot)
正常加载
What went wrong? (add screenshot)
无法加载，显示空白页面
![image](https://user-images.githubusercontent.com/14290645/163349182-4bc156c6-0568-4d82-bb4f-e50a224f36f0.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2022-04-14 09:39
Duplicate of #14778

*Please note:* You need to communicate *in English* when using this bug-tracker!

> PDF.js version:2.13.216-dist

It's possible that that you need to use a `legacy`-build of the PDF.js library, as mentioned in https://github.com/mozilla/pdfjs-dist/blob/master/README.md

**Closed by Snuffleupagus** 2022-04-14 09:39 UTC
