### ISSUE TITLE
Receive this errore message: null is not an object

### ISSUE THREAD

**Issue by Raf2061** [mozilla/pdf.js#9242] opened 2017-12-05 16:11 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: WkWebView
- Operating system and its version: iOS on iPhone
- PDF.js version: 2.0.185
- Is a browser extension:

Steps to reproduce the problem:
1. click on <a href="viewer.html?file=myfile.pdf">
2. receive in viewer.html following error
PDF.js v2.0.185 (build: f2994736)
Message: null is not an object (evaluating 'fullReader.headersReady')
and no pdf is displayed

**Comment by Snuffleupagus** [comment] 2017-12-05 16:37
This issue is unfortunately missing too much of the required information to be actionable!
Also, please understand that cannot provide detailed support for various frameworks (e.g. "WkWebView"), and that the STR (steps to reproduce) provided are nowhere near detailed enough to be useful.

Finally, as mentioned in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), for issues with custom deployments of PDF.js a complete (runnable) example must be provided (since code snippets aren't very useful).

Closing as incomplete.

**Closed by Snuffleupagus** 2017-12-05 16:37 UTC
