### ISSUE TITLE
No visual indicator when a find toolbar checkbox or zoom dropdown are focused in Chrome

### ISSUE THREAD

**Issue by Thunderforge** [mozilla/pdf.js#6211] opened 2015-07-14 23:03 UTC
When using Chrome, there is no visual indicator when you tab over to the "Highlight All" and "Match Case" checkboxes within the find toolbar.

Steps to reproduce:
1. Open Chrome
2. Go to the [PDF.js demo PDF viewer](http://mozilla.github.io/pdf.js/web/viewer.html)
3. Click on the Find button
4. Use the tab keys to navigate over to either the "Highlight All" checkbox, the "Match Case" checkbox, or the zoom dropdown
5. Note that there is no visual indicator that any of these elements are focused

In Firefox and Internet Explorer 11, the user can clearly see that these elements are focused because the label has a highlight around it. Note that the element is still able to be activated by using the spacebar (there is [a separate issue](https://github.com/mozilla/pdf.js/issues/6210) regarding this behavior not working in Firefox or Internet Explorer 11), but there is no visual focus to indicate that the element has focus.

**Comment by timvandermeij** [comment] 2015-07-17 18:55
Is this not an upstream browser issue then, if only Chrome has the problem, or do you think that this can somehow be caused by the PDF.js codebase?

**Comment by Thunderforge** [comment] 2015-07-20 14:40
The issue seems to be an issue with viewer.css. When you look at a CSS-less [dropdown menu](http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select) or [checkbox[(http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_checkbox_get), there is highlighting in Chrome. In fact, if you comment out the line to import the viewer.css, you can focus those elements.

**Comment by slimjim181** [comment] 2016-06-22 01:30
@Thunderforge is correct that it is an issue with viewer.css
However this issue of no focus states is present in more than just chrome as I have reproduced in:
Safari (9.1.1 11601.6.17)
Edge (25.10586.0.0)
IE11 (11.420.10586.0)
FF Win (47.0) - does have a 1px outline focus but is not as visible as FF Mac blue glow
FF 47.0 (Ubuntu 16.04)
Note these are all the latest versions of the browsers as of 22 Jun 2016 NZST

**Comment by Snuffleupagus** [comment] 2021-02-19 23:33
This should have been (indirectly) fixed by the re-styling in PR #11077.

**Closed** 2021-02-20 13:43 UTC
Labels: 1-viewer, 4-chrome-specific
