### ISSUE TITLE
window resize,it render black blocks

### ISSUE THREAD

**Issue by luqingxuan** [mozilla/pdf.js#7593] opened 2016-09-05 02:54 UTC
i see the github example for pdf.js,
but when i open more tab page(with chrome browser),
deactivate the example page,then resize browser,and then active example pdf.js page,
the example is not visible,it just render black blocks,when i scroll example,it is still bad,
i don't know why

**Comment by Snuffleupagus** [comment] 2016-09-05 09:31
Given the limited information provided, I'm closing as a duplicate of issue #7497.

**Closed by Snuffleupagus** 2016-09-05 09:31 UTC
