### ISSUE TITLE
MS Edge - Images render with artifacts

### ISSUE THREAD

**Issue by tiriana** [mozilla/pdf.js#9708] opened 2018-05-09 14:44 UTC
Some time ago we started using PDF.js in Egnyte. It works very well, but just now we have some problems with pdf containg images on MS Edge. They render with artifacts sometime. 
I'm using following viewer flags: 
```
disableStream = true;
disableAutoFetch = true;
```
But changing them to false does not seem to help.

PDF.js reports no errors and no errors are thrown in console.

All **resources** (source pdf, screenshots, har files) can be found here: https://phantombit.egnyte.com/fl/Ur3Km8eza6

**Configuration:**
- Web browser and its version: Microsoft Edge 41.16299.15.0
- Operating system and its version: Windows 10 (OS Build: 16299.19) (I'm running this on virtualBox [image taken from here: [](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) ], but these issues appear also when Windows is master OS)
- PDF.js version: 1.9.661
- Is a browser extension: no

**Steps to reproduce the problem:**
1. Open the file with viewer
2. In about 50% of cases it renderes with artifacts

**What is the expected behavior?**
Images are rendered correctly
![image](https://user-images.githubusercontent.com/5216143/39821059-9a5627e4-53a7-11e8-8b28-95fbd79c11e0.png)
![image](https://user-images.githubusercontent.com/5216143/39821106-b6935aa8-53a7-11e8-8ccf-508c05c371d7.png)

**What went wrong?**
Images are rendered with artifacts on them
![image](https://user-images.githubusercontent.com/5216143/39820992-73194f3a-53a7-11e8-95fb-c1bb283fd8bd.png)
![image](https://user-images.githubusercontent.com/5216143/39821091-aeed312a-53a7-11e8-9b74-130c9d5e4f4c.png)

**Link to a viewer:**
https://phantombit.egnyte.com/fl/Ur3Km8eza6#folder-link/ 
click on file icon
![image](https://user-images.githubusercontent.com/5216143/40110386-234617a0-5900-11e8-9400-ec3a7a8be0cf.png)

Things I checked already:
* I tried disabling webGL (with disableWebGL flag) to check if it's not related to it - no luck
* I tried disabling range (with disableRange flag) to check if it's not related to it - no luck
* I tried reproducing it in your demo, but everything works well there.

Generally I suspect that this may be related with network, and sending this file in chunks. The random nature of this bug leads me to this conclusion. But as you have chance to see in attached .har files - there does not seem to be anything wrong with requests. None of them is empty, there are no errors. I'm kinda in dead end here at this point.

Any kind of help/advice is welcome :-)

**Comment by iberezansky** [comment] 2018-05-15 18:44
Reproduced:

PDFJS: 2.0.493
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

Options:
`disableStream = true;
disableAutoFetch = true;`
give no difference.

Library is not stable in Edge - it changes the result after page refresh, sometimes getDocument cannot open PDF at all and there are not errors/warnings in the console.

**Comment by iberezansky** [comment] 2018-05-17 09:16
Found a solution:
`window.PDFJSgetDocumentTask = getDocument('test.pdf');`
Save reference for getDocument task in achievable from the global space variable. It seems the task destroys in other case because there are not other references on it.

**Comment by ruinunes** [comment] 2019-04-17 09:21
We are also getting the same problem, a PDF containing an image will occasionally render with artifacts/offsetted positioning/wrong colors.

**Comment by ko06** [comment] 2019-05-27 09:35
We are also getting the same problem, a PDF containing an image will occasionally render with artifacts/offsetted positioning/wrong colors. but this thing only happens in  MS EDGE. Its working fine in chrome, chromium, firefox.


Edge version :

Microsoft Edge 42.17134.10
Microsoft EdgeHTML 17.17134

**Comment by ko06** [comment] 2019-05-27 09:36
@tiriana any workaround available for this issue?

**Comment by tiriana** [comment] 2019-06-05 21:35
@ko06 Unfortunately not, we don't have any workaround. TBH - I don't have a clue what can be the cause. I'd bet on the worker, but that's just my guess.

**Comment by timvandermeij** [comment] 2019-11-09 13:17
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.

**Closed by timvandermeij** 2019-11-09 13:17 UTC
Labels: 1-core, 4-ie-edge-specific
