### ISSUE TITLE
The pdf file had a wrong color in pdf viewer

### ISSUE THREAD

**Issue by justalways** [mozilla/pdf.js#17448] opened 2023-12-20 10:13 UTC
Attach (recommended) or Link to PDF file here:
https://static.ruf.eu/wp-content/uploads/2023/09/RUF_Produktprogramm_A4quer_DE_09-2023_Screen-3.pdf
Configuration:
- Web browser and its version: chrome  120.0.6099.110
- Operating system and its version:windows latest
- PDF.js version:4.0.269
- Is a browser extension:no

Steps to reproduce the problem:
1. open https://mozilla.github.io/pdf.js/web/viewer.html
2.upload my pdf file

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/9329575/7663b4ad-bc67-4a91-b068-63bc9456b157)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/9329575/f34929f8-8940-4a23-b636-ecaa0594fd3f)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-12-20 10:17
Duplicate of #2856

**Closed by Snuffleupagus** 2023-12-20 10:17 UTC
