### ISSUE TITLE
Only the last canvas is displayed

### ISSUE THREAD

**Issue by natcohen** [mozilla/pdf.js#7703] opened 2016-10-09 08:38 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome 53.0.2785.143
- Operating system and its version: Windows 10
- PDF.js version: 1.6.210
- Is an extension: -

Steps to reproduce the problem:
1. Upload any pdf using html input
2. Read and display it as follow
```

if (FileReader && files && files.length) {
      var fr = new FileReader();
      var extension = files[0].name.split('.').pop().toLowerCase();
      fr.onload = function(e) {
        success = fileTypes.indexOf(extension) > -1;
        if (success) {
          console.debug("Parsing PDF document...");
          //PDFJS.workerSrc = '<path_to_pdf.worker.js>';
          PDFJS.getDocument(e.target.result).then(function getPdf(pdf) {
            //
            // Fetch the first page
            //
            pdf.getPage(1).then(function getPage(page) {
              var scale = 1.5;
              var viewport = page.getViewport(scale);

              //
              // Prepare canvas using PDF page dimensions
              //
              $(parentEl).append('<canvas class="preview"/>');
              var canvas = $(parentEl).find("canvas.preview").get(0);
              var context = canvas.getContext('2d');
              canvas.height = viewport.height;
              canvas.width = viewport.width;

              //
              // Render PDF page into canvas context
              //
              var renderContext = {
                canvasContext: context,
                viewport: viewport
              };
              page.render(renderContext);
            });
          });
        }

      }
      fr.onloadend = function(e) {
        console.debug("Load End");
      }
      fr.readAsArrayBuffer(files[0]);
 }
```
3. Display multiple canvas (and multiple pdf) on one html page

What is the expected behavior? (add screenshot)

Display all previews correctly

What went wrong? (add screenshot)

Only the last canvas is displayed

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2016-10-09 14:38
Closing as duplicate of #7693. For future reference, note that we cannot debug anything with just some code snippets. Be sure to provide a *complete* runnable example that shows the issue.

**Closed by timvandermeij** 2016-10-09 14:38 UTC
