### ISSUE TITLE
Incorrect rendering

### ISSUE THREAD

**Issue by kockicica** [mozilla/pdf.js#7523] opened 2016-08-04 09:40 UTC
Link to PDF file (or attach file here):
[Untitled1.pdf](https://github.com/mozilla/pdf.js/files/401306/Untitled1.pdf)

Configuration:
- Web browser and its version: Chrome latest, Firefox latest
- Operating system and its version: Windows 7, Ubuntu 12.04
- PDF.js version: latest
- Is an extension: no

Steps to reproduce the problem:
1. http://mozilla.github.io/pdf.js/web/viewer.html open attached pdf file

What is the expected behavior? 
![good](https://cloud.githubusercontent.com/assets/2874042/17397378/0cd0bff2-5a38-11e6-9077-93bfc13f4e8a.PNG)

What went wrong? 
![current](https://cloud.githubusercontent.com/assets/2874042/17397384/1c3a6592-5a38-11e6-9bd7-7d9b61523fe7.PNG)

**Comment by Snuffleupagus** [comment] 2016-08-04 10:34
Closing as duplicate of issue #5550.

**Closed by Snuffleupagus** 2016-08-04 10:34 UTC
