### ISSUE TITLE
Unable to open pdf file

### ISSUE THREAD

**Issue by lakshmi-hashtaag** [mozilla/pdf.js#8872] opened 2017-09-05 10:43 UTC
Link to PDF file (or attach file here):
[cowo1504560427613-page_full-ilovepdf-compressed.pdf](https://github.com/mozilla/pdf.js/files/1277105/cowo1504560427613-page_full-ilovepdf-compressed.pdf)

Configuration:
- Web browser and its version: Google chrome -Version 60.0.3112.113 (Official Build) (64-bit), Safari Version 10.1.2 (10603.3.8)
- Operating system and its version: OS x Yosemite version 10.10.5 (14F2511)

Steps to reproduce the problem:
1. open https://mozilla.github.io/pdf.js/web/viewer.html link.
2. Try to open attached pdf file.

What is the expected behavior? It shud render the opened pdf file.

What went wrong? Unable to open pdf file and getting below error.
 PDF.js v1.9.524 (build: cd25a51a)
Message: Unexpected server response (200) while retrieving PDF "blob:https://mozilla.github.io/e6fbff6b-fbc1-4343-a9fa-32ebb62c952d".

**Comment by Snuffleupagus** [comment] 2017-09-05 11:03
Closing as duplicate of #8870.

**Closed by Snuffleupagus** 2017-09-05 11:03 UTC
