### ISSUE TITLE
structuredClone is not defined (electron)

### ISSUE THREAD

**Issue by Orgins** [mozilla/pdf.js#15120] opened 2022-07-01 08:04 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: "electron": "^13.0.0"  / Node.JS 16.13.0
- Operating system and its version: Windows 11 64 bits
- PDF.js version: "pdfjs-dist": "^2.14.305"
- Is a browser extension: no
- Installation method: yarn add pdfjs-dist
Steps to reproduce the problem:
1. Load a PDF using the code below: 

      `  const loadingTask = PDFJS.getDocument(reader.result);
        loadingTask.promise.then(function(pdf) {})`

2. Run the code using node 

What is the expected behavior? (add screenshot)

No error should be reported ,As the browser runs

What went wrong? (add screenshot)

When the browser is running 

![b](https://user-images.githubusercontent.com/35723631/176852177-c6a84fb6-06d6-4daa-9d8b-1d57f055a40a.jpg)

When the electronis running 

![e](https://user-images.githubusercontent.com/35723631/176852239-8d9e4102-2d24-4611-8bdb-2ab6a4dd778e.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**There is no problem running in the browser, but the following errors will appear when running in electron**

`ReferenceError: structuredClone is not defined
at LoopbackPort.postMessage (pdf.js?7aa6:2240)
at MessageHandler.sendWithPromise (pdf.js?7aa6:8555)
at _fetchDocument (pdf.js?7aa6:1356)
at eval (pdf.js?7aa6:1302)`

**I saw the same problem before #14729 , but I didn't get help. Maybe I should try to reduce the version**
**I think it may have something to do with electron or my installation**

**Comment by Snuffleupagus** [comment] 2022-07-01 08:21
> Web browser and its version: "electron": "^13.0.0"  / Node.JS 16.13.0

Sorry, but we cannot provide support specifically for "electron" since we don't know anything about that framework here.

> Load a PDF using the code below:
>   `  const loadingTask = PDFJS.getDocument(reader.result); loadingTask.promise.then(function(pdf) {})`
> 
>  Run the code using node

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> I saw the same problem before #14729 , but I didn't get help.

Did you *actually follow* https://github.com/mozilla/pdf.js/issues/14729#issuecomment-1082831050, by importing from the `legacy/`-folder, since that's required in Node.js environments?

> Maybe I should try to reduce the version

Using anything except the *latest* PDF.js version is neither recommended nor supported.

Duplicate of #14729

**Closed by Snuffleupagus** 2022-07-01 08:21 UTC
