### ISSUE TITLE
Printing bug in Crome and IE

### ISSUE THREAD

**Issue by Ewout-Spitaels** [mozilla/pdf.js#5922] opened 2015-04-09 13:58 UTC
Printing in Chrome and IE isn't working for us: the pages in print-preview are shown at 50% of page size. Also an extra white page is added between every other page.

Problem can be viewed on this url:
https://graduator.be/document/Gerechtelijk+recht+2015+Deel+1+GOEDE+LAY+OUT/2433

![chrome_error](https://cloud.githubusercontent.com/assets/1496578/7068211/21787f8c-ded1-11e4-86bf-d023f8b0c3d5.PNG)

Users have reported the same problem for IE, but not Firefox.

**Comment by Snuffleupagus** [comment] 2015-04-09 14:08
Closing as duplicate of issues such as #5718 and #3983.

**Closed by Snuffleupagus** 2015-04-09 14:08 UTC

**Comment by Ewout-Spitaels** [comment] 2015-04-21 11:15
I seem the have this problem just with certain PDF's. 
All works fine with the default PDFjs PDF that's used in the examples.
But the next PDF for example seems to be a problem: any thoughts why?

http://graduator.be/res/items/documents_hint/pre-2015/1420724404-2048-hint.pdf
