### ISSUE TITLE
how to make the electronic signature can be displayed normally in the latest version of PDFJS? 

### ISSUE THREAD

**Issue by fireWinters** [mozilla/pdf.js#12902] opened 2021-01-25 07:44 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:87.0.4280.88
- Operating system and its version:Mac/windows 10
- PDF.js version:2.5.207
- Is a browser extension:

Steps to reproduce the problem:
Hello, how to make the electronic signature can be displayed normally in the latest version of PDFJS? Do you have the corresponding sample?Due to the sensitive data problem of the file, I cannot provide the original PDF file Thank you very much. Looking forward to your reply.

**Comment by Snuffleupagus** [comment] 2021-01-25 08:17
Duplicate of #1076 

---

> PDF.js version: 2.5.207

Furthermore, note that that version is no longer supported.

**Closed** 2021-01-25 18:54 UTC
