### ISSUE TITLE
PDF.js - While printing it shows blank pages

### ISSUE THREAD

**Issue by dshivnani** [mozilla/pdf.js#6084] opened 2015-06-05 06:37 UTC
First of all, I thank to team of PDF.js as it had solved our issue of controlled printing.

We are using PDF.js 1.1.3 and it renders file correctly on Windows 7 Professional and Google Chrome 43.0.2357.81 m. However for few machines with same configuration, it shows blank page in google chrome print preview after clicking on Print button in pdf.js viewer. on the same machine if we do Ctrl+Shift+P on the entire web page it shows correctly the entire page.

Please let us know if you there is any solution for the same as I searched on github but no luck yet.

Regards
Deepak

**Comment by Rob--W** [comment] 2015-06-06 09:59
Sounds like #6031. Could you confirm whether that's the case?

**Comment by dshivnani** [comment] 2015-06-06 10:10
No, when we click on print from PDF.JS it opens print preview of chrome and therein only its blank page, users is not doing any other activity.Chrome version is 43.0.2357.81 m
Blank in Chrome
![chromeblank](https://cloud.githubusercontent.com/assets/12757338/8019244/3e9f1d0a-0c62-11e5-8f47-1e6b04fc264d.PNG)
PDFJS, proper rendering
![pdfjs](https://cloud.githubusercontent.com/assets/12757338/8019248/5add2c96-0c62-11e5-9a04-4d4dfc9db1b9.PNG)

**Comment by Rob--W** [comment] 2015-06-06 10:20
In which version of Chrome is PDF.js working fine?

The screenshot looks fine, and since you've reported that it also worked fine on "some machines", I suspect that this is a bug in Chrome. After searching on their issue tracker, I found https://code.google.com/p/chromium/issues/detail?id=470083, which looks like a plausible cause for this bug.

**Comment by dshivnani** [comment] 2015-06-06 10:25
Interesting thing is both working and non-working machines have same version of chrome 43.0.2357.81 m

**Comment by Rob--W** [comment] 2015-06-06 10:26
Are these machines identical? Please visit `chrome://gpu` and check whether there is any notable difference between the output.

**Comment by dshivnani** [comment] 2015-06-06 10:43
Also if I do CTRL+P on entire web page in Chrome it gives print preview properly , only for PDF printed from our viewer it gives blank page...

Dont see much difference in machine, apart from canvas and multiple raster threads

![working](https://cloud.githubusercontent.com/assets/12757338/8019327/670e3b64-0c66-11e5-94e8-b0e73d0857a0.PNG)
![nonworking](https://cloud.githubusercontent.com/assets/12757338/8019328/67778e3e-0c66-11e5-8d64-2fecc0d066c1.PNG)

**Comment by dshivnani** [comment] 2015-06-06 10:45
Chrome web page print preview

![chrome](https://cloud.githubusercontent.com/assets/12757338/8019342/29ad9610-0c67-11e5-9620-f6ed9e360cdc.PNG)

**Comment by Rob--W** [comment] 2015-06-06 11:15
When I open the demo (https://mozilla.github.io/pdf.js/web/viewer.html) in Chromium 43.0.2357.81, then only the second page is visible and the rest is blank. If I do the same with a bleeding-edge version of Chrome (version 45.0.2416.0), I don't see the bug any more.
I bisected Chrome, and found that the bug was fixed as of 44.0.2372.0 (https://chromium.googlesource.com/chromium/src/+/e76399b0e23f81ea887424f8b60e87d34bc32630, which contains https://chromium.googlesource.com/skia/+/00b7e5eb973a1b1e4d1affa74fc0341e8c41e3da that fixes https://code.google.com/p/chromium/issues/detail?id=470083, which in their turn causes this bug in PDF.js).

There is nothing that PDF.js can do to work around this bug. The Chromium team has already fixed the bug, and [acknowledged](https://code.google.com/p/chromium/issues/detail?id=470083#c26) that the fix will be in the next patch-release for Chrome 43. If you cannot wait that long, use Chrome beta (currently version 44, https://www.google.com/chrome/browser/beta.html).

**Closed by Rob--W** 2015-06-06 11:15 UTC
Labels: 4-chrome-specific, 4-printing

**Comment by dshivnani** [comment] 2015-06-06 11:30
We identified that on our most of the PC's, Intel(R) HD graphics is installed & i.e having Multiple Raster thread : Enabled , but the system i.e having issue is having Intel(R) Graphics media accelerated driver & also  Multiple Raster thread : Disabled

Is this the root cause behind the issue?

**Comment by Rob--W** [comment] 2015-06-06 11:41
@dshivnani No, that's a red herring. If I disable multiple raster threads in Chrome 45.0.2416.0 (`--num-raster-threads=1`), then the bug does not show up. Toggling the flag in Chrome 43.0.2357.0 does not affect the reproducibility of the bug either).

I've already explained the root cause of the bug in https://github.com/mozilla/pdf.js/issues/6084#issuecomment-109565842. If you want a quick fix, use Chrome 44. If you have patience, wait a few days or a few weeks until the Chrome team rolls out an update.

**Comment by Rob--W** [comment] 2015-06-11 11:57
For the record, the latest version of Chrome (43.0.2357.124, published two days ago after 43.0.2357.81) contains the bugfix.

**Comment by amitK007** [comment] 2019-10-11 05:58
in firefox, while printing for RTF file , blank pages are coming one after another. It working file in chrome and IE 11.
plz help me.
in below attached  a file 
[dzczdfsdfsdfsdfsd.pdf](https://github.com/mozilla/pdf.js/files/3715830/dzczdfsdfsdfsdfsd.pdf)

**Comment by THausherr** [comment] 2019-10-11 07:51
@amitK007 this is a closed issue, and was related to a bug in Chrome. Please create a new issue. (Might still be closed or duplicate, and IIRC some versions of MSIE are not supported)
