### ISSUE TITLE
Incorrect rendering of pattern + stencil

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#13572] opened 2021-06-17 10:04 UTC
Attach (recommended) or Link to PDF file here:
[gs-bugzilla690297.pdf](https://github.com/mozilla/pdf.js/files/6669206/gs-bugzilla690297.pdf)

Configuration:
- Web browser and its version: FF 89.0.1
- Operating system and its version: W10 10.0.19041.1052
- PDF.js version: latest

Steps to reproduce the problem:
1. load file
2. look at the bottom of the image

What is the expected behavior?  Tiffany, Kelly and Doris are visible
![grafik](https://user-images.githubusercontent.com/6665575/122375371-749b9f80-cf63-11eb-968f-56032d65e585.png)

What went wrong? Tiffany, Kelly and Doris are missing
![grafik](https://user-images.githubusercontent.com/6665575/122375530-972db880-cf63-11eb-840d-be12228d4e09.png)

**Comment by Snuffleupagus** [comment] 2021-06-17 10:43
Duplicate of #6297

**Closed by Snuffleupagus** 2021-06-17 10:43 UTC
