### ISSUE TITLE
Can`t render some PDFs correctly

### ISSUE THREAD

**Issue by KvantVS** [mozilla/pdf.js#8871] opened 2017-09-04 18:51 UTC
Link to PDF file (or attach file here):
[РЧ Баканас.pdf](https://github.com/mozilla/pdf.js/files/1275321/default.pdf)

Configuration:
- Chrome, v60.0.3112.113 (64)
- Win7 SP1 64:
- PDFJS.version = '1.0.892';
- PDFJS.build = 'c8d729f';
- Is an extension: NO

Steps to reproduce the problem:
1. View file with viewer.html
2. All file on russian and correct, except the page 4 and 5 - there is...unknown letters\hieroglyphs.

What is the expected behavior:
![2017-09-05_00-37-02](https://user-images.githubusercontent.com/25001042/30036208-e67a39b8-91d2-11e7-8c4d-451b37731667.png)

What went wrong:
![2017-09-05_00-34-44](https://user-images.githubusercontent.com/25001042/30036221-f9162474-91d2-11e7-9dd2-e9cfa3b16737.png)

Current viewer on http://mozilla.github.io/pdf.js/web/viewer.html work the same way.

Is there a way to pdf.js show us the same render as browser? Maybe there is the way to specify encoding exactly in javascript or in URL or something like that?

**Comment by timvandermeij** [comment] 2017-09-04 19:46
PDF.js 1.0.892 is an ancient version. Please open the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if the problem remains.

**Comment by KvantVS** [comment] 2017-09-05 06:30
![2017-09-05_12-28-06](https://user-images.githubusercontent.com/25001042/30047996-cc12ecc4-9235-11e7-82a0-f71166243e12.png)
I did what you tell me, and here is error

**Comment by rijk** [comment] 2017-09-05 08:40
I got that error last week as well — I think that page is broken.

**Comment by timvandermeij** [comment] 2017-09-05 19:28
The fix for that has just been merged and I can confirm that this now works again. Could you check again?

**Comment by KvantVS** [comment] 2017-09-06 06:31
![2017-09-06_12-30-28](https://user-images.githubusercontent.com/25001042/30097379-2e5e738e-92ff-11e7-8e00-b98fa03ed60b.png)
Sorry, but nope... Error was gone, but still getting an hieroglyphs

**Comment by Snuffleupagus** [comment] 2017-09-06 08:03
The PDF file contains *corrupt* font data, note how even Adobe Reader (i.e the reference implementation) cannot render that page correctly.
When the file is opened with Adobe Reader, there's a warning about one of the fonts (TimesNewRomanPSMT) and this is how page 4 renders:

![page4](https://user-images.githubusercontent.com/2692120/30100489-5758953c-92e9-11e7-8fc2-1aceb53b1c75.png)

Using http://brendandahl.github.io/pdf.js.utils/browser/ to browser the contents of the PDF file, you can see that two *different* fonts point to the *same* `FontDescriptor`, which is a problem since one of them is a TrueType font and the other a CIDFontType2 font. Furthermore, note how that (shared) `FontDescriptor` doesn't include any embedded font data.

**Comment by KvantVS** [comment] 2017-09-06 10:01
So... can we do something with it, except telling creators of this PDF-file changing that font?

**Comment by timvandermeij** [comment] 2017-09-06 20:24
The solution would indeed be to not create these corrupt PDF files in the first place. Since even Adobe Reader/Acrobat has problems with this, it's unlikely that we'll we able to work around this, and even if we can the question remains if we should introduce a workaround for a single case of a corrupt PDF file, mainly because workarounds themselves can have other unforeseen consequences. We'll leave this issue open for investigation though.

**Comment by Snuffleupagus** [comment] 2021-06-28 15:10
Closing as WONTFIX, or possibly even INVALID, since it's the PDF document *itself* which is broken here; please see https://github.com/mozilla/pdf.js/issues/8871#issuecomment-327407289 for additional details.

**Closed by Snuffleupagus** 2021-06-28 15:10 UTC
Labels: 4-corrupted-pdf, 4-font-conversion
