### ISSUE TITLE
Improve form rendering

### ISSUE THREAD

**Issue by ejstembler** [mozilla/pdf.js#1313] opened 2012-03-07 04:54 UTC
Everyone who uses PDF forms is already used to how they are rendered natively in the Adobe Acrobat desktop client or the Reader web plugin.  Here are a few suggestions to consider:

* Change the background color of form fields to `#dde4ff`
* Change checkboxes to use a toggled font checkmark *(i.e. Acrobat uses the "Adobe Pi Std" font (AdobePiStd.otf) for checkmarks)*

[Rendering Differences](http://dl.dropbox.com/u/3040414/form_rendering/differences.png)
[Adobe Pi Std Font](http://dl.dropbox.com/u/3040414/form_rendering/adobe_pi_std.png)

**Comment by fbender** [comment] 2015-11-16 10:23
#1459 seems to be some form of meta-issue.

**Comment by fbender** [comment] 2015-11-16 10:25
For reference, here are the attached images (uploaded from Dropbox):

- Differences: ![differences](https://cloud.githubusercontent.com/assets/357895/11179568/a5442e34-8c54-11e5-8482-9e74ca5b8d69.png)
- Adobe Pi Std Font: ![adobe_pi_std](https://cloud.githubusercontent.com/assets/357895/11179569/a544a72e-8c54-11e5-868c-0d823eb01df9.png)

**Comment by fbender** [comment] 2015-11-16 14:30
Also see #2738 concerning other Formfield/Font related issues

**Comment by timvandermeij** [comment] 2016-09-13 11:47
Closing as duplicate of #7613, in which we are tracking this.

**Closed by timvandermeij** 2016-09-13 11:47 UTC
Labels: 2-feature, 4-form-acroform
