### ISSUE TITLE
Form field text values too large

### ISSUE THREAD

**Issue by BHSPitMonkey** [mozilla/pdf.js#7367] opened 2016-05-27 19:38 UTC
Link to PDF file (or attach file here): [detect-form-fields.pdf](https://github.com/mozilla/pdf.js/files/287227/detect-form-fields.pdf)

Configuration:
- Web browser and its version: Firefox 46.0.1
- Operating system and its version: Ubuntu 16.04
- PDF.js version: 1.3.231
- Is an extension: No

Steps to reproduce the problem:
1. Open PDF
2. Look at entered text in form sections 8a and 9a

What is the expected behavior? Text is correct size:

![screenshot from 2016-05-27 12-32-04](https://cloud.githubusercontent.com/assets/33672/15619145/32ff065a-2407-11e6-8cfb-95905526fd91.png)

What went wrong? Text is very large:

![screenshot from 2016-05-27 12-30-58](https://cloud.githubusercontent.com/assets/33672/15619160/45016442-2407-11e6-85c0-faee9879c20d.png)

PdfBug console output:

```
11:56:13.291 PDF ef2293a3b9f4e0accbef97ee38798a2c [1.3 Mac OS X 10.11.1 Quartz PDFContext / Amgraf OneForm Designer Plus] (PDF.js: 1.3.231)1 viewer.js:6800:7
11:56:13.292 Warning: AcroForm/XFA is not supported1 viewer.js:6824:9
11:56:13.424 Warning: Unimplemented annotation type "FreeText", falling back to base annotation1 pdf.worker.js:9407:5
11:56:13.806 Warning: fontRes not available1 pdf.worker.js:9407:5 (logged 54 times)
11:56:13.898 Warning: Error during font loading: Font Helvetica-Bold is not available1 pdf.js:368:5
```

**Comment by puzzydeztroyer** [comment] 2018-04-25 05:45
I have the same issue right now. I am inserting values in the proper place, and it automatically uses bigger font than I am using. However after downloading and saving the pdf using pdf js, the issue dissapears when using acrobat reader or foxit.

**Comment by hveit** [comment] 2019-09-17 07:10
I have a similiar problem, but I do not yet know what to do about it:
If this is a problem with AcroForms support within PDF.js, why is this ticket (https://github.com/mozilla/pdf.js/projects/1) resolved/closed while this one here is still open?

I can still reproduce this in version 2.3.171.
Is there a chance to circumvent the problem somehow, i.e. by installing fonts etc.?

**Comment by THausherr** [comment] 2019-09-17 11:01
The problem with the file here is that the appearance streams are missing. /NeedAppearances is set so the viewer should generate them. In the field "f1_13(0)" the /DA (default appearance) is "/Helvetica-Bold 9 Tf 0 g". However the font "Helvetica-Bold" does not exist in in the Acroform default resources of the PDF (I suspect that the PDF was poorly merged from a cover page and the original SS4 form). So PDF.js makes some decision about what font to use, and from the screeenshot this looks like Comic Sans 🤣

@hveit make sure that the software that generates / fills the PDF also creates the appearance streams of the fields. If you're not sure what is going on, create a new issue here.

@timvandermeij you closed this issue but no explanation why.

**Comment by hveit** [comment] 2019-09-17 11:29
@THausherr thanks for the explanation.
Can you confirm, that it is the same problem with my PDF file from issue #11151?

**Comment by THausherr** [comment] 2019-09-17 11:36
@hveit I'll answer there.

**Comment by automatedbugreportingfacility** [comment] 2020-09-09 17:21
This looks much better now, but the values are cut off a little:

![form](https://user-images.githubusercontent.com/3524640/92631358-8879ed00-f2d1-11ea-9bc6-adc2f11dba91.png)

**Closed** 2021-01-23 15:08 UTC
Labels: 4-annotations, 4-font-conversion, 4-form-acroform
