### ISSUE TITLE
Print on Chrome 45 prints extra blank pages

### ISSUE THREAD

**Issue by xlc** [mozilla/pdf.js#6345] opened 2015-08-12 02:37 UTC
This was fixed by #5857 but break again on Chrome 45.0.2454.26 beta (64-bit) and OS X 10.10.4.
It is working on Chrome 44.
I tried many PDFs (including compressed.tracemonkey-pldi-09.pdf) and all of them have extra blank page before actual content page.

**Comment by xlc** [comment] 2015-08-12 03:07
I found out the fix for Chrome 45 is change `PRINT_OUTPUT_SCALE` to 1 (https://github.com/mozilla/pdf.js/blob/master/web/pdf_page_view.js#L496)

**Comment by timvandermeij** [comment] 2015-08-12 18:30
Perhaps #6160 will help a bit as that touches the output scale too?

**Comment by xlc** [comment] 2015-08-12 22:15
Yes #6160 fixes this problem. Any plan to merge it in?

**Comment by timvandermeij** [comment] 2015-08-13 19:54
We need more cross-browser tests that to make sure nothing regresses. Otherwise that patch looks good.

**Comment by Hengjie** [comment] 2015-08-24 08:12
@timvandermeij what specific testing would you like to see? I had tested non-IE browsers and it doesn't appear to regress. I didn't test IE because presumably the OP was testing in IE to fix an IE issue.

**Comment by timvandermeij** [comment] 2015-08-30 11:11
We need to have manual testing results on that PR for various configurations to be reasonable sure that nothing regresses. I am thinking of the following tests:

- Firefox stable on Windows, Linux and OS X
- Firefox beta/aurora/nightly on Windows, Linux and OS X
- IE 11/Edge on Windows
- Chrome (latest) on Windows, Linux and OS X

**Comment by kivervinicius** [comment] 2015-08-31 21:58
On linux version 45 beta have the same problem, on windows too.

**Comment by Rob--W** [comment] 2015-09-04 11:41
This is probably not a bug in PDF.js, it was a bug in Chrome: https://code.google.com/p/chromium/issues/detail?id=526098 (fixed in 47, as of writing 45 and 46 are affected).

**Comment by dankirberger** [comment] 2015-09-18 00:10
I'm actually seeing a blank page inserted before *every* page, but only on Chrome 45.

Worth noting on an old version of the viewer we use/modified (1.0.1040) I see a single blank page inserted, newer versions (1.1.215 and your snapshot demo site) i see the blank page before every page.

**Comment by Rob--W** [comment] 2015-09-18 09:19
@dankirberger Which version of Chrome are you using? This has been fixed in 45.0.2454.93.

**Comment by dankirberger** [comment] 2015-09-18 15:09
Had to restart Chrome, I have 45.0.2454.93 now, an earlier 45.x before restarting. All is well now, thanks!

**Comment by timvandermeij** [comment] 2015-09-18 20:23
If this is fixed upstream, can we close this or is there anything else left to do here?

**Comment by dankirberger** [comment] 2015-09-18 21:16
I saw the same issues the reporter did, and more, all were fixed by updating Chrome. I think this can be closed.

**Closed** 2015-09-18 21:51 UTC
Labels: 3-upstream, 4-printing

**Comment by matthiasg** [comment] 2016-07-05 07:42
With Chrome 51 and Electron the Issue still exists, in Windows 10 and in MAC OS.

**Comment by giordy** [comment] 2016-08-04 16:19
The problem is still present in Firefox 48 on Fedora 24 x84_64
