### ISSUE TITLE
array of items in getTextContent() not always in correct order

### ISSUE THREAD

**Issue by BartCardan** [mozilla/pdf.js#14493] opened 2022-01-25 13:03 UTC
Sample: https://technobility.nl/tests/pdf.html

Configuration:
- Chrome 97
- Windows and Mac
- PDF.js version: Latest from: https://mozilla.github.io/pdf.js/build/pdf.js

### Steps to reproduce the problem:
1. I've used a example from this github which shows page by page.
2. As soon as a page is loaded use `page.getTextContent();` to receive all items on the page.
3. Output the first string of every items-array with `console.log(textContent['items'][0]['str']);`

### What is the expected behavior?
I hoped to get the first string on the page with this method. 

### What went wrong?
On most pages I get indeed the first string, but on some pages not.
In the sample (see above) on page 13 I get the following string "Er worden ondertitels voor doven en slechthorenden geleverd voor alle live audiocontent in".
The first string should be the heading above this sentence.

When I use function `getStructTree()` I see that the heading is the first object. This is also logged in console.log in the sample.
Also when checking the code-base of the PDF (tags) I see the heading is the first on the page.

Somehow the first string as found by `page.getTextContent()` is not always the string from the first object as found by `page.getStructTree()`

### What do I need?
I need a method to get every first string on every page. 
getTextContent() looks promising, but gives wrong results on some pages.

**Comment by Snuffleupagus** [comment] 2022-01-25 13:15
> I need a method to get every first string on every page.
> getTextContent() looks promising, but gives wrong results on some pages.

Unfortunately that's a bug in the PDF document *itself*, rather than in the PDF.js library, since the text-content of the page is apparently rendered out-of-order. In general this is a quite difficult problem to work-around.

Duplicate of #2344 (since it's for all intents and purposes the same issue).

**Closed by Snuffleupagus** 2022-01-25 13:15 UTC

**Comment by BartCardan** [comment] 2022-01-25 13:43
> Unfortunately that's a bug in the PDF document _itself_, rather than in the PDF.js library, since the text-content of the page is apparently rendered out-of-order. In general this is a quite difficult problem to work-around.

I don't know if this is correct. The order in the PDF is correct as `getStructTree()` get's the correct order from the page.
It's strange that I can get the correct elements on the page with the correct order with `getStructTree()`, but I don't get the correct strings in the right order with `getTextContent();`

Let me ask it in another way:
Is it somehow possible to get contents (string) from the first element on the page given by `getStructTree()`?
Or: is it possible to add the contents (string) in the data returned by `getStructTree()`?

**Comment by calixteman** [comment] 2022-01-25 13:47
@BartCardan, there's nothing actionable without the pdf, so please provide it.

**Comment by Snuffleupagus** [comment] 2022-01-25 13:56
> The order in the PDF is correct as `getStructTree()` get's the correct order from the page.
> [...]
> but I don't get the correct strings in the right order with `getTextContent();`

The structTree and the textContent are completely different data-structures, in the PDF specification, hence it's not actually strange that they don't agree completely w.r.t. for example the ordering.

> Or: is it possible to add the contents (string) in the data returned by `getStructTree()`?

No, since as mentioned they are *not* directly related and their parsing is (purposely) independent.

**Comment by Snuffleupagus** [comment] 2022-01-25 14:06
Although, I suppose that you might be able to infer the desired information by using the `PDFPageProxy.getStructTree()` and `PDFPageProxy.getTextContent({ includeMarkedContent: true, })` methods together; please refer to https://github.com/mozilla/pdf.js/blob/583c39b85966f640292f95ccd1d05207ce9f9ca5/src/display/api.js#L1076-L1077

**Comment by BartCardan** [comment] 2022-01-25 16:01
> @BartCardan, there's nothing actionable without the pdf, so please provide it.

The PDF used in the example: https://technobility.nl/tests/test.pdf

**Comment by BartCardan** [comment] 2022-01-25 16:13
@Snuffleupagus Thank you. This helped. I think.
With `page.getStructTree()` I can get the ID of the first element.
With `page.getTextContent({ includeMarkedContent: true, }); ` I can get a list of all items on the page. Next step is to get the first item with content AFTER the item which contains the same ID of the first element. 

This looks promising. As soon as I have a working code I will add it to this issue for other users.
