### ISSUE TITLE
Possibility to view embedded PDF files in viewer

### ISSUE THREAD

**Issue by Laurens-makel** [mozilla/pdf.js#13526] opened 2021-06-09 14:09 UTC
Somestimes we encounter PDF documents that have PDF files embedded inside of them.

It shows like this:
![image](https://user-images.githubusercontent.com/37303445/121370329-f163c380-c93c-11eb-8fde-6c360adacb13.png)

Default behaviour on click event is to open the embedded file in another tab, is there a way to open the embedded document in case of PDF in the PDF viewer?

**Comment by Snuffleupagus** [comment] 2021-06-09 14:20
> is there a way to open the embedded document in case of PDF in the PDF viewer?

While it's obviously technically possible to implement something like that, note that there's however no option for doing that in the demo viewer (which I guess is what you're *actually* asking about here).

Please note that if you just *replaced* the current document there'd be no simple way of going back to original document, hence why this behaviour isn't something that we offer e.g. as an option; closing as answered.

---

*For future reference:* When opening an issue, please remember provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue a little "light" on the details.

**Closed by Snuffleupagus** 2021-06-09 14:20 UTC

**Comment by Snuffleupagus** [comment] 2021-06-09 14:28
> is there a way to open the embedded document in case of PDF in the PDF viewer?

In the `GENERIC` demo viewer, a PDF attachment should already open in the PDF Viewer (but in a new tab); this behaviour can be tested e.g. with https://github.com/mozilla/pdf.js#online-demo

Hence it's somewhat difficult to tell *exactly* what you're actually asking about here, without more information; please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue is easily actionable/valid.

Unless you're perhaps asking about an option to *replace* the current document with the opened attachment?
If so, we don't provide any option for that since it'd result in a bad UX given that there'd be no way to return to the original document.
