### ISSUE TITLE
PasswordException error not thrown on pdf.js@2.4.456

### ISSUE THREAD

**Issue by arthur-feral** [mozilla/pdf.js#12407] opened 2020-09-23 09:36 UTC
Attach (recommended) or Link to PDF file here:
[letter-protected.pdf](https://github.com/mozilla/pdf.js/files/5268611/letter-protected.pdf)

Configuration:
- Web browser and its version: any
- Operating system and its version: any
- PDF.js version: 2.5.207
- Is a browser extension: no

Steps to reproduce the problem:
1. open a password protected PDF using `pdfjs.getDocument`
2. the task reject with undefined

What is the expected behavior?
It should reject with a proper error `PasswordException`
![Screenshot 2020-09-23 at 11 34 34](https://user-images.githubusercontent.com/1699430/93995071-d6dac180-fd90-11ea-90df-2856b6b42f1a.png)

What went wrong?
Looks like the error `PasswordException` is not thrown anymore so in the reject callback, the error is `undefined`

**Comment by Snuffleupagus** [comment] 2020-09-23 09:55
> Attach (recommended) or Link to PDF file here:
> (any password protected PDF file)

Please ensure that you *always* provide the PDF document in question, to ensure that the issue can be easily reproduced (and to save time).

> PDF.js version: 2.4.456

That version is no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download or https://github.com/mozilla/pdf.js/releases

> 1. open a password protected PDF using `pdfjs.getDocument`

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

Given that no runnable example was provided, I'm going to guess that you're using a *minified* version of the PDF.js library. If so, this issue is most likely a duplicate of #12209 which is fixed in PDF.js version `2.6.347` (and above).

**Comment by arthur-feral** [comment] 2020-09-23 14:05
Hello @Snuffleupagus ,
Thank you for your reply.

I've updated a bit the PR description with the version I'm currently using and uploaded a PDF used to reproduce the issue as you asked.

After looking at the issue you liked regarding the minified version of PDFjs, I can definitely tell this is the same issue and I'm glad it's fixed. Indeed, this happens only on production build and not development environment, detail that I should've mentioned.

Since it's fixed, I'm closing this issue.

Thank you, have a nice day!

**Closed** 2020-09-23 14:06 UTC
