### ISSUE TITLE
Blurred font in PDF printing

### ISSUE THREAD

**Issue by sunafei** [mozilla/pdf.js#10921] opened 2019-06-21 01:42 UTC
I use the latest version. The font in PDF is imitation Song-Dynasty-style typeface. It prints normally with PDF reader and blurs with pdfjs.
![微信图片_20190621094134](https://user-images.githubusercontent.com/26369465/59891705-c8249280-9408-11e9-8f60-f2415e99fa07.jpg)

**Comment by Snuffleupagus** [comment] 2019-06-21 07:05
Without *all* of of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md provided, this issue will be closed as INCOMPLETE.

**Comment by sunafei** [comment] 2019-06-21 08:17
I can't speak English. This is the result of machine translation....
Attach (recommended) or Link to PDF file here:
[Application.pdf](https://github.com/mozilla/pdf.js/files/3313493/Application.pdf)
Configuration:
Web browser and its version:  Chrome 72, IE11
Operating system and its version: Windows 10
PDF.js version: 1.8.188
Is a browser extension: no
Steps to reproduce the problem:
Preview my PDF file on the web and click Print
The font in PDF is imitation Song-Dynasty-style typeface. It prints normally with office and blurs with pdfjs
What is the expected behavior? (add screenshot)
This is printed using office
![7209b50f9a338056467300eb5e08fb4](https://user-images.githubusercontent.com/26369465/59908290-a98dbe00-943f-11e9-9c75-3101a0f9a8d3.jpg)
What went wrong? (add screenshot)
![f45392d5b1e15b580b212e27a26da8c](https://user-images.githubusercontent.com/26369465/59908319-ba3e3400-943f-11e9-962f-e8f171f5501a.jpg)
![db8e39810d0994f81233275dac86380](https://user-images.githubusercontent.com/26369465/59908328-bf02e800-943f-11e9-96c1-fa6cd28a2410.jpg)

**Comment by Snuffleupagus** [comment] 2019-06-21 08:22
> PDF.js version: 1.8.188

That version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases

**Comment by sunafei** [comment] 2019-06-21 08:25
> > PDF.js version: 1.8.188
> 
> That version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases

The problem with the latest version is the same

**Comment by slidertom** [comment] 2019-06-21 12:25
Probably this is the identical issue as
https://github.com/mozilla/pdf.js/issues/6241

**Comment by beijingalex** [comment] 2019-07-31 10:35
我也遇到同样的问题：

查看PDF文件时，清晰度是正常的。
但是打印到纸上是，非常模糊，不能正常使用。
使用PDF.js最新的版也一样。

另外， 我还遇到另一个问题。

就是，不能打印 横向的文件。

**Comment by timvandermeij** [comment] 2019-07-31 20:53
@beijingalex Please only post comments in English. We cannot provide any support in other languages and as such those comments will be removed.

**Comment by wd3mo** [comment] 2019-10-11 08:53
You can set the PRINT_RESOLUTION in web/viewer.js in the function renderPage() to 600 or even 900. Thats still not the perfect print but it is at least acceptable.

**Comment by brainchild0** [comment] 2021-01-09 23:11
I can confirm that printing text produces results at very poor resolution. Printing the same target files  from a native viewer on the same system shows no similar problem.

**Comment by timvandermeij** [comment] 2021-03-14 15:16
Closing since this is a duplicate of #2750.

**Closed by timvandermeij** 2021-03-14 15:16 UTC
Labels: 4-printing
