### ISSUE TITLE
Printing fails when closing PDF Viewer tab too early

### ISSUE THREAD

**Issue by fbender** [mozilla/pdf.js#2729] opened 2013-02-16 19:27 UTC
Fx 19b06 Mac OS X 10.8.2 on MBA 2012. 

STR: 
1. Goto http://home.arcor.de/thiessen-berlin/WB%20von%20Stahl.pdf
2. Hit print button, confirm printing modal (I selected Duplex printing but it should work either way). 
3. Immediately close the tab with the PDF.js viewer. 
4. After a few seconds, a warning appears stating that printing failed. 

Rough guess: Document is GCed before printing can start / print message is sent completely.

**Comment by yurydelendik** [comment] 2016-10-06 13:49
Closing criteria or expected result for the issue is not specified. I would say it works as needed and assuming it there is nothing can be done here.

**Closed by yurydelendik** 2016-10-06 13:49 UTC
Labels: 1-viewer, 4-printing
