### ISSUE TITLE
gulp generic AND gulp server throwing Code Error during build

### ISSUE THREAD

**Issue by Faizranas** [mozilla/pdf.js#12867] opened 2021-01-16 08:43 UTC
Hello Snuffleupagus,
Thanks for your response. I cloned the code from https://github.com/mozilla/pdf.js#getting-the-code as suggested by you. Now, the code is throwing error and not working in dev & prod both environments. As I informed you earlier that we are using 
Node 11.0.0, Chrome 84 and Windows7 for our development. Please help us to resolve this problem so we can move further and look into customization.

We are getting following errors when we run gulp server command:
Navigated to http://localhost:8888/web/viewer.html
app.js:1765 Uncaught (in promise) SyntaxError: Unexpected token '??=' in app.js
we found below syntax in app.js 
this._contentLength ??= contentLength; // See `getDownloadInfo`-call above.
when I removed ?? then we got below error in ui_utils js.
Uncaught (in promise) SyntaxError: Unexpected token '||=' in ui_utils.js:866
(externalListeners ||= []).push(listener);

We don't know understand why this invalid syntax is there in your code-lab. Please help us to resolve it.
please see the screenshot below
![dev](https://user-images.githubusercontent.com/6050477/104807332-365b5200-5804-11eb-91da-06d80507a5a2.PNG)

We are getting following errors when we run gulp generic command:
same pdf worker error is coming
Uncaught (in promise) Error: Setting up fake worker failed: "Cannot load script at: http://localhost:8000/build/pdf.worker.js".
    at api.js:2047

We don't see pdf.worker.js file in build folder.
build folder conatins only pdf.js and pdf.sandbox
please see the screen shot below.
![prod](https://user-images.githubusercontent.com/6050477/104807361-876b4600-5804-11eb-8298-a74f28ad8b60.PNG)

_Originally posted by @Faizranas in https://github.com/mozilla/pdf.js/issues/12860#issuecomment-761528497_

**Comment by Snuffleupagus** [comment] 2021-01-16 09:15
Duplicate of #12860; please do not knowingly "spam" the bug tracker with duplicated issues!

**Closed** 2021-01-16 14:28 UTC
