### ISSUE TITLE
Failing to display correct background colours

### ISSUE THREAD

**Issue by HigherPhilosophy** [mozilla/pdf.js#13925] opened 2021-08-22 17:37 UTC
Attach (recommended) or Link to PDF file here: 
[HumeSection2a.pdf](https://github.com/mozilla/pdf.js/files/7027800/HumeSection2a.pdf)

Configuration:
- Web browser and its version: PDF.js is being used in Chrome Version 92.0.4515.107 but same problem if PDF is simply viewed in Firefox 91.0.1 (64-bit)
- Operating system and its version: Mac OSX version 10.12.6
- PDF.js version: 2.9.359
- Is a browser extension: No

Steps to reproduce the problem:
1. View PDF in Firefox or using PDF.js
2.

What is the expected behavior? (add screenshot)
The pdf appears correctly if loaded directly into Chrome/Safari/Opera/Preview/AdobeReader
![ShouldBe](https://user-images.githubusercontent.com/87994282/130364411-f6c60872-c552-4607-bd79-5c14e4174efb.png)

What went wrong? (add screenshot)
As it appears in Firefox or when using pdf.js in any browser
![DisplayingAs](https://user-images.githubusercontent.com/87994282/130364418-efe04077-d8c1-4cb6-ab92-121bcc5d4046.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://HigherPhilosophy.github.io/MoodleFiles/web/viewer.html
higherphilosophy.github.io/MoodleFiles/web/viewer.html?file=../Hume/HumeSection2a.pdf

**Comment by Snuffleupagus** [comment] 2021-08-22 17:49
Duplicate of #5046

**Closed by Snuffleupagus** 2021-08-22 17:49 UTC
