### ISSUE TITLE
Scrolling and vim

### ISSUE THREAD

**Issue by aloispichler** [mozilla/pdf.js#14845] opened 2022-04-26 17:30 UTC
The pdf.js shortcuts to scroll to the next and the previous page are
* next page: `n`, `j` and `space bar`,
* previous page: `p`, `k` and `shift+space bar`.

Desired behavior:

Instead of having triple key combinations for scrolling the page, the shortcuts for simple (but more important) line scrollings are missing. It is desirable (and would be very useful) to adopt the vim-like behavior:
* cursor down: `j` (line scrolling, same as cursor `↑`),
* cursor up: `k` (line scrolling, same as cursor `↓`).

Please, also see Evince or Zathura. Both use this desired behavior.

Thank you.

**Comment by Snuffleupagus** [comment] 2022-04-26 17:39
Duplicate of #7019

**Closed by Snuffleupagus** 2022-04-26 17:39 UTC

**Comment by aloispichler** [comment] 2022-04-26 19:51
pdf.js is integrated in various other programs, one example is LaTeX Workshop.
For this – and other reasons – it would really be important to fix this issue, as it breaks the workflows.

Thanks again.
