### ISSUE TITLE
PDF.js rendering too slow.

### ISSUE THREAD

**Issue by HusseinTaha** [mozilla/pdf.js#7292] opened 2016-05-04 10:19 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:IE 11
- Operating system and its version: windows server 2012 or server 2008
- PDF.js version:10.0.907
- Is an extension:

Steps to reproduce the problem:
1. Open a pdf document.

What is the expected behavior? (add screenshot)
It should open in 1-2 seconds.
What went wrong? (add screenshot)
The problem is that the rendering takes from 5 to 6-7 seconds.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2016-05-04 11:05
As it currently stands, this issue will be closed as incomplete.
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md. In particular, you need to attach/link to the PDF file in question, since it's impossible for anyone to reproduce this issue without the PDF file.

> PDF.js version:10.0.907

I'm assuming that this was meant to say version `1.0.907`. That version is fairly old by now, so the first thing you should do is test this is the *latest* PDF.js version, using e.g. the demo viewer: http://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by timvandermeij** [comment] 2016-05-06 21:11
Closing as incomplete until the information requested above is provided.

**Closed by timvandermeij** 2016-05-06 21:11 UTC
Labels: 4-information-requested
