### ISSUE TITLE
Use HTML anchors for named destinations

### ISSUE THREAD

**Issue by andrenarchy** [mozilla/pdf.js#5892] opened 2015-03-31 16:09 UTC
Currently, the viewer realizes internal links via a javascript onclick handler that navigates to the referenced named destination. Wouldn't it simplify the code if the named references are injected into the annotation layer as `<div>` elements at their corresponding positions? If such a div has its `id` attribute set to the corresponding destination's name, one could use standard HTML hash links for navigating to this position. What do you think?

Disclaimer: I'm not an expert for PDF named destinations and I didn't go through the entire (quite complex) link service code, so maybe there's something that I miss. :)

**Comment by Snuffleupagus** [comment] 2015-03-31 16:27
I'm tentatively closing this as a duplicate of issue #5258.
*Note:* that issue also contains references for further reading regarding destinations in PDF files.

**Closed by Snuffleupagus** 2015-03-31 16:27 UTC
