### ISSUE TITLE
Gimage reader leaves some Hindi words unrecognised.

### ISSUE THREAD

**Issue by abhinavmosesben** [mozilla/pdf.js#9133] opened 2017-11-15 01:13 UTC
Hi !
I have been using Gimagereader as an OCR to convert Hindi Pdf into text. It works perfectly well when it recognises the words, however it leaves some words unrecognised. I have tried the whole page recognition also but it still leaves some words unrecognised. Am I missing something? Please help.

**Comment by Snuffleupagus** [comment] 2017-11-15 08:34
Closing as duplicate of issue #9132; please don't open *multiple* virtually identical issues, especially when they are all missing the necessary details to be actionable (see https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Closed by Snuffleupagus** 2017-11-15 08:34 UTC
