### ISSUE TITLE
Wavy funny condescending text at specific zoom levels

### ISSUE THREAD

**Issue by abrahimladha** [mozilla/pdf.js#15249] opened 2022-07-31 10:58 UTC
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Firefox 102.0a1 (2022-05-23) (64-bit)
- Operating system and its version: Arch Linux 5.18
- PDF.js version: Newest with firefox nightly
- Is a browser extension:

Steps to reproduce the problem:
1. Open a PDF file
2. Zoom in and out until it 

What is the expected behavior? (add screenshot)
![2022-07-31-065336_214x75_scrot](https://user-images.githubusercontent.com/6496702/182022757-ad6db05c-34b8-409e-b115-ff6f27fa20ed.png)

What went wrong? (add screenshot)

![2022-07-31-064624_218x76_scrot](https://user-images.githubusercontent.com/6496702/182022562-824405d3-8b03-4739-b4dd-a91558f9b2fa.png)
![2022-07-31-063947_416x56_scrot](https://user-images.githubusercontent.com/6496702/182022495-a8be7761-cf6d-45fb-8fb2-a075d03fc4d4.png)

All zoom levels appear to have this wavy effect, but the height difference of adjacent letters depends on the zoom level. At higher zoom levels, and at very very low zoom levels, this effect is not noticable. This effect only appears in firefox nightly 102.0a1, and not in firefox 102.0.1. 

Also, zoomed out quite a bit, periods appear to do this:
![2022-07-31-065640_385x517_scrot](https://user-images.githubusercontent.com/6496702/182022879-c22c6a74-cb32-4432-b867-8fa340fce637.png)

**Comment by Snuffleupagus** [comment] 2022-07-31 11:09
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1770706 and/or https://bugzilla.mozilla.org/show_bug.cgi?id=1773936

**Closed by Snuffleupagus** 2022-07-31 11:09 UTC
