### ISSUE TITLE
Black pages / loopDict is null

### ISSUE THREAD

**Issue by JanSlabon** [mozilla/pdf.js#8221] opened 2017-03-31 07:25 UTC
Link to PDF file (or attach file here): [permanent-resident-card-application.pdf](https://github.com/mozilla/pdf.js/files/884800/permanent-resident-card-application.pdf)

Configuration:
- Web browser and its version: 52.0.2 (ESR)
- Operating system and its version: Windows 10

- PDF.js version: 1.6.315
- Is an extension: yes

Steps to reproduce the problem:
1. Open the PDF

What is the expected behavior? no black pages

What went wrong? 
![grafik](https://cloud.githubusercontent.com/assets/12390057/24540459/a3e14b10-15f3-11e7-8864-343659d9f740.png)

Additional info: 
On https://mozilla.github.io/pdf.js/web/viewer.html the error is "only" a warning and the file is viewable. So maybe it is already fixed?

**Comment by Snuffleupagus** [comment] 2017-03-31 08:04
> On https://mozilla.github.io/pdf.js/web/viewer.html the error is "only" a warning and the file is viewable. So maybe it is already fixed?

Closing as duplicate of issue #8143 (it was fixed by PR #8144).

**Closed by Snuffleupagus** 2017-03-31 08:04 UTC
