### ISSUE TITLE
Touch selection jumps when spanning over multiple lines

### ISSUE THREAD

**Issue by tomak-git** [mozilla/pdf.js#10868] opened 2019-05-29 06:43 UTC
Attach (recommended) or Link to PDF file here:
http://www.cedefop.europa.eu/files/czech_republic_-_european_inventory_on_nqf_2018.pdf

Configuration:
- Web browser and its version: Firefox v. 67.0
- Operating system and its version: Windows 10 Pro v. 1803 build 17134.799
- PDF.js version: could not find (default)
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the linked pdf (although the problem persists over many other pdfs I tried).
2. On a touch screen double tap a word to initiate selection.
3. Drag the selection over multiple lines down.
4. The selection jumps and selects text in the opposite direction.

What is the expected behavior? (add screenshot)
I would expect the selection to beahave the same way as when selecting with cursor using mouse or touchpad.

**Comment by RBSUS** [comment] 2023-03-23 13:01
Want to bump this. Have there been any developments?

**Comment by limonovthesecond2** [comment] 2024-05-15 12:34
The issue is fixed with PR#[17923](https://github.com/mozilla/pdf.js/pull/17923)

**Closed** 2024-05-15 12:46 UTC
Labels: text-selection
