### ISSUE TITLE
TOC width can't be changed

### ISSUE THREAD

**Issue by MadMax74** [mozilla/pdf.js#7474] opened 2016-07-06 12:00 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Firefox 47
- Operating system and its version: Linux
- PDF.js version: how i can find it
- Is an extension:

TOC width can not be changed. PDF's with TOC opening on miniatures by default.
Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2016-07-06 12:12
Closing as duplicate of issue #2072.

**Closed by Snuffleupagus** 2016-07-06 12:12 UTC
