### ISSUE TITLE
Blueprintjs + PDF.js (by way of react-pdf) causes error

### ISSUE THREAD

**Issue by nschwan94** [mozilla/pdf.js#9043] opened 2017-10-18 18:55 UTC
Configuration:
- Web browser and its version: Electron v1.6
- Operating system and its version: Mac OSX
- PDF.js version: `pdf.js-dist@^1.9.476`
- copdependency of `react-pdf@^2.0.0`

Steps to reproduce the problem:

https://github.com/nschwan94/electron-react-boilerplate on branch `blueprintjs_reactpdf_issue`, install packages and execute `dev` npm script. When `@blueprintjs/core` is imported in `Home.js` component error is thrown, when it is not imported there is no error.

Error is:
```
Uncaught TypeError: Cannot read property 'PDFJS' of undefined
    at Object.defineProperty.value (pdf.js:13270)
    at __w_pdfjs_require__ (pdf.js:45)
    at Object._typeof (pdf.js:7416)
    at __w_pdfjs_require__ (pdf.js:45)
    at Object.defineProperty.value (pdf.js:88)
    at pdf.js:91
    at webpackUniversalModuleDefinition (pdf.js:18)
    at Object../app/node_modules/pdfjs-dist/build/pdf.js (pdf.js:25)
    at __webpack_require__ (bootstrap 53283a0…:686)
    at fn (bootstrap 53283a0…:105)
```

**Comment by nschwan94** [comment] 2017-10-18 18:55
https://github.com/wojtekmaj/react-pdf/issues/90

**Comment by brandonros** [comment] 2017-10-24 22:04
I have this error without any involvement of BlueprintJS. Any advice? Does rolling back to a different version do anything worthwhile?

**Comment by yurydelendik** [comment] 2017-10-25 13:09
Works for me (kind of, but requested pdf is not avaialable):

<img width="1010" alt="screen shot 2017-10-25 at 8 08 15 am" src="https://user-images.githubusercontent.com/1523410/32000258-bbb74c42-b95b-11e7-8111-a4cc5ac40eee.png">

More information needed.

**Comment by timvandermeij** [comment] 2017-10-29 12:21
Closing until more information is provided since it cannot be reproduced.

**Closed by timvandermeij** 2017-10-29 12:21 UTC
Labels: 4-information-requested

**Comment by nschwan94** [comment] 2017-11-06 15:19
the error occurs when using yarn, but it doesn't occur when using npm.

**Comment by nschwan94** [comment] 2018-01-03 23:02
sorry guys, this ended up being a messed up webpack config on my part. turns out when all the signs point to a configuration issue... it's not a dependency issue.
