### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by Teir** [mozilla/pdf.js#12502] opened 2020-10-21 09:00 UTC
Attach (recommended) or Link to PDF file here:
[example.pdf](https://github.com/mozilla/pdf.js/files/5414586/example.pdf)

Configuration:
- Web browser and its version: Google Chrome 86.0.4240.75
- Operating system and its version: Windows 10
- PDF.js version: 2.5.207 and 2.7.164 from demo
- Is a browser extension:

Steps to reproduce the problem:
1. Open example.pdf in PDF.js.

What is the expected behavior? (add screenshot)
All data is displayed, just like in Google Chrome PDF-Viewer
![chrome_pdf_viewer](https://user-images.githubusercontent.com/19780067/96697580-c0765480-1394-11eb-88c2-3d9ba3697dd3.png)

What went wrong? (add screenshot)
Some data is missing.
![pdfjs](https://user-images.githubusercontent.com/19780067/96697670-da179c00-1394-11eb-923d-5dd795c108a1.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by calixteman** [comment] 2020-10-21 09:04
Click on the icon with the green point on the upper left: the fourth button on the right is for layers, then check that all the layers are checked in order to be rendered.

**Comment by Teir** [comment] 2020-10-21 09:10
> Click on the icon with the green point on the upper left: the fourth button on the right is for layers, then check that all the layers are checked in order to be rendered.

All layers are checked
![layers](https://user-images.githubusercontent.com/19780067/96698844-40e98500-1396-11eb-801d-bbc0d86c0370.png)

**Comment by Snuffleupagus** [comment] 2020-10-21 09:27
WFM, when testing in Firefox Nightly 84 on Windows (with its built-in PDF.js version `2.7.99`); see

![layers](https://user-images.githubusercontent.com/2692120/96700484-c87fc580-138f-11eb-9f95-de777fb152b1.png)

> Web browser and its version: Google Chrome 86.0.4240.75

*If this is indeed specific to just one browser:* That would suggest a canvas, hardware acceleration, and/or driver issue specific to Google Chrome, rather than the PDF.js library; as such it's unfortunately very difficult to see that this can be fixed here.

**Comment by calixteman** [comment] 2020-10-21 09:30
WFM on linux debian, with chrome and firefox nightly.

**Comment by timvandermeij** [comment] 2020-10-21 21:03
I have been noticing many similar-looking issues regarding this in combination with Chrome the last few days. Either something really broke upstream in Chrome or it's a coincidence, but I couldn't help but be slightly surprised about the number of similar-looking reports. Moreover, we have been seeing lots of issues with Chrome on the bots as well (with intermittently missing parts in the Tracemonkey PDF file), so perhaps it's all related; not sure.

In any case, this doesn't look like something that can be fixed here, but I'd instead suggest to report this to the Chrome development team upstream in their issue tracker. Thanks.

**Closed by timvandermeij** 2020-10-21 21:03 UTC

**Comment by TMmaxx** [comment] 2020-10-22 10:03
A workaround that we are using for the interim is turning of hardware acceleration. Definitely not ideal, but it allows our users to continue working while we work to fix the issue

**Comment by SamyCookie** [comment] 2020-11-03 10:05
for cross references: duplicate of #12462
