### ISSUE TITLE
Test selection 

### ISSUE THREAD

**Issue by bikb** [mozilla/pdf.js#10616] opened 2019-03-05 11:50 UTC
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html
Configuration:
- Web browser and its version:
latest Firefox, latest Chrome
- Operating system and its version:
Windows 7 64 Bit
- PDF.js version:
latest version of demo
- Is a browser extension:
no

Steps to reproduce the problem:
Text selection in Chrome and Firefox differs if starting position is "WHITE SPACE" (NO textLayer > span):
Chrome: all text starting from the starting text selection till the end of the page is selected.
Firefox: all text starting from the beginning of the page is selected.

Can one change the default behavior? Is it possible to prevent automatical text selection of the preceeding or the following text?

Thank you.

Best regards.

**Comment by timvandermeij** [comment] 2019-03-05 23:19
Could you provide a bit more explanation about the problem, i.e., where should we start the selection to be able to reproduce this? Screenshots would help to illustrate the problem.

**Comment by Snuffleupagus** [comment] 2019-03-05 23:45
Probably a duplicate of e.g. issue #9843.

**Comment by timvandermeij** [comment] 2019-03-05 23:47
Yes, looks like it.

**Closed by timvandermeij** 2019-03-05 23:47 UTC
Labels: 4-information-requested, 4-text-selection
