### ISSUE TITLE
PDF creative has different visible components in Acrobat Reader & pdf.js

### ISSUE THREAD

**Issue by singhkaushlendra** [mozilla/pdf.js#12007] opened 2020-06-17 13:22 UTC
Attached file has different visible components in Acrobat Reader & PDF.js
The document uses layers. Acrobat reader understand which layers are visible and hence display the required components.
[Layer Test 2.pdf](https://github.com/mozilla/pdf.js/files/4792720/Layer.Test.2.pdf)

**Comment by Snuffleupagus** [comment] 2020-06-17 13:28
Duplicate of #269

**Closed** 2020-06-17 21:21 UTC
