### ISSUE TITLE
Pdf js downloads the complete PDF in Firefox

### ISSUE THREAD

**Issue by jsangari-ssat** [mozilla/pdf.js#7425] opened 2016-06-20 12:59 UTC
Hi ,
The Service returns the following response Accept-Ranges header on the initial get request .In firefox i saw that it downloads the complete pdf and renders it , In Chrome it cancels the first request and proceeds with requesting the partial content and rendering it. Sounds like a bug

**Comment by Snuffleupagus** [comment] 2016-06-20 13:18
This is by design, since PDF.js uses a combination of streaming *and* range requests to speed up loading/rendering of PDF files in Firefox, please refer to PR #5263 and issue #4739. Closing as invalid.

**Closed by Snuffleupagus** 2016-06-20 13:18 UTC

**Comment by jsangari-ssat** [comment] 2016-06-20 15:54
Thanks @Snuffleupagus  for the quick reply. In this usecase we do not want the user to download the completed PDF so I guess the only way of doing that is through the disableStream setting to true ..
