### ISSUE TITLE
Image interpolation flag also apply when the image is downscaled

### ISSUE THREAD

**Issue by BrianMwit** [mozilla/pdf.js#16306] opened 2023-04-17 11:52 UTC
This is the same issue as https://github.com/mozilla/pdf.js/issues/16273 with additional information

Attach (recommended) or Link to PDF file here: [Test.pdf](https://github.com/mozilla/pdf.js/files/11200736/Test.pdf)

Configuration:
- Web browser and its version: Firefox 111.0.1, Chrome 112.0.5615.87
- Operating system and its version: Windows 10 21H2
- PDF.js version: v3.5.141
- Is a browser extension: No

Steps to reproduce the problem:
1. Using 100% DPI display
2. Open the PDF file in https://mozilla.github.io/pdf.js/web/viewer.html
3. Set zoom to 100%

What is the expected behavior? (add screenshot)
The image renders fine in Firefox
![](https://user-images.githubusercontent.com/84440240/231173752-81d24e7b-8902-4316-b7d1-0c951ed3e203.png)

What went wrong? (add screenshot)
The image is pixelated in Chrome
![](https://user-images.githubusercontent.com/84440240/231173865-10cb29d4-674f-4685-a373-4be118a4a24d.png)

The attached PDF file contain an image with Interpolation flag set off. However, the image is already 1299x184px, large enough that it would get down-scaled most of the time, only 1:1 resolution at ~200% zoom.

Since the interpolation flag is explicitly set in the file, Currently, PDF.JS simply pass the `false` value through to browser canvas' `imageSmoothingEnabled` property, making it look bad.
https://github.com/mozilla/pdf.js/blob/342dc760dabf9749eb33730a1eb07ecf1ee13b38/src/display/canvas.js#L917-L935
The difference is Chrome and Safari will always follow the `imageSmoothingEnabled` flag regardless of upscaling / downscaling.
However, Firefox will always interpolate the image when downscaled, ignoring the flag, making the image look good.
Demo of canvas `imageSmoothingEnabled` behavior https://jsfiddle.net/brianmwit/mnsbaxeg/7/.

Neither PDF spec nor HTML canvas spec mention anything about behavior for downscaling and Interpolate / `imageSmoothingEnabled` flag. Observing the behavior on both Adobe Acrobat Reader and Chromium's embedded PDF reader, they both always interpolate the image when down-scaled.
Can PDF.JS' `getImageSmoothingEnabled()` also always interpolate the image when down-scaling, so the behavior is consistent with Adobe Reader and doesn't rely on Firefox's specific implementation of canvas?

**Comment by Snuffleupagus** [comment] 2023-04-22 07:07
> This is the same issue as #16273 with additional information

*For future reference:* Please comment on an already existing issue, rather than opening a duplicate.

Duplicate of #16273

> Observing the behavior on both Adobe Acrobat Reader and Chromium's embedded PDF reader, they both always interpolate the image when down-scaled.

Without any references, e.g. to source-code, it's impossible to tell if the mentioned PDF viewers will *always* interpolate when downscaling and we really want to avoid (unnecessary) regressions in the Firefox PDF Viewer.

*Generally speaking:* Please keep in mind that Firefox is the *primary* development target for this library.

**Closed by Snuffleupagus** 2023-04-22 07:07 UTC
