### ISSUE TITLE
Disabling Font Download in IE results in blank PDF being rendered

### ISSUE THREAD

**Issue by seankenny** [mozilla/pdf.js#10453] opened 2019-01-15 10:31 UTC
Attach (recommended) or Link to PDF file here:
[https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)

Configuration:
- Web browser and its version: IE (any version)
- Operating system and its version: Windows 10
- PDF.js version: 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. Disable font download in Internet Options > Security Settings
![image](https://user-images.githubusercontent.com/435556/51173338-23c48000-18ad-11e9-9a18-7779a749e73a.png)
2. Navigate to the viewer link above using IE.

What is the expected behavior? (add screenshot)
Pdf content (some) should be rendered but is not.  

You can see an example of expected behaviour here in an unrelated issue (screenshot 3) using an older version - [https://github.com/mozilla/pdf.js/issues/6018#issuecomment-102863247](https://github.com/mozilla/pdf.js/issues/6018#issuecomment-102863247)

What went wrong? (add screenshot)
This issue appears to have surfaced in V2.0.943.  

V2.0.489/V2.0.550 seem OK.

Screenshot of viewer using V2.0.943:
![image](https://user-images.githubusercontent.com/435556/51173818-2d021c80-18ae-11e9-932c-c16f462eb54b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-01-15 14:54
> Disable font download in Internet Options > Security Settings
>
> Pdf content (some) should be rendered but is not.

I don't think there's any guarantee, implicit or otherwise, that things will kind of "work" or exactly how rendering will break if you *completely* disable font loading in the browser; hence this is probably just a duplicate of issue #6018. 

Besides, it seems that https://github.com/mozilla/pdf.js/issues/6018#issuecomment-103162379 is very much relevant here as well.

**Comment by seankenny** [comment] 2019-01-15 19:30
While I agree to an extent regarding a guarantee, I would have thought that a non-major version update from 2.0.550 to 2.0.943 produces such a different result.  A major version change, then yes maybe but not a minor.

I do not think this is a duplicate of #6018 though.

**Comment by Snuffleupagus** [comment] 2019-01-16 17:02
First of all, please keep in mind that IE 11 is *not* listed as fully supported at https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support.
Second of all, while the visible effect might now be different the underlying cause is *exactly* the same; hence why it's a duplicate of issue #6018.

**Comment by timvandermeij** [comment] 2019-01-16 21:46
I agree; closing as a duplicate of #6018. We'll track the issue there.

**Closed by timvandermeij** 2019-01-16 21:46 UTC
Labels: 1-other, 4-ie-edge-specific, 4-ie11-specific
