### ISSUE TITLE
Missing font exception not handled

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#7149] opened 2016-04-04 10:44 UTC
Link to PDF: https://www.dropbox.com/s/lu2o8gaxnpmtjlu/ArtsBeerCans2016-2.pdf?dl=1

There is an unhandled error if I try to display page 24 of this PDF:

![screen shot 2016-04-04 at 11 11 31](https://cloud.githubusercontent.com/assets/786238/14244995/4142095e-fa56-11e5-9f69-7433eb60d139.png)

It's conceivable this may be due to an inconsistency within the PDF, but other viewers seem to handle it correctly.

Your standard fully-functional test viewer.html doesn't display the error in the console, but it does just hang indefinitely until I to move on to another page.

The same error happens in all browsers I've tried (Chrome, FF, Safari in Mac).

pdf.js - using git commit 553928c26e0de247af07e0613cc84242fb430e09

Thank you for your help - I hope this is useful.

Dan

**Comment by Snuffleupagus** [comment] 2016-04-04 10:55
Closing as duplicate of issue #4244.

**Closed by Snuffleupagus** 2016-04-04 10:55 UTC
