### ISSUE TITLE
PDF render blank

### ISSUE THREAD

**Issue by shiguanglu** [mozilla/pdf.js#9607] opened 2018-03-28 10:13 UTC
Attach (recommended) or Link to PDF file here:
[A2 Id. Sup. Ct. Orig. Drwg.PDF](https://github.com/mozilla/pdf.js/files/1855494/A2.Id.Sup.Ct.Orig.Drwg.PDF)

Configuration:
- Web browser and its version:
Chrome: Version 65.0.3325.181 (Official Build) (64-bit)

- Operating system and its version:
Mac OSX 10.13.3

- PDF.js version:
Latest master branch on with commit a8e9f6cc290e4f12ceb01f36c783477d1fc75bfe

- Is a browser extension:
No

Steps to reproduce the problem:
1.  After upload the pdf, it render as blank page 
2. No error shows on Inpsector 

What is the expected behavior? (add screenshot)
 Show open it will all the content 

What went wrong? (add screenshot)
Blank page 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2018-03-28 10:42
This is a duplicate of issue #6741, and should be closed as such.

**Comment by shiguanglu** [comment] 2018-03-28 10:45
I see the #6741 is still open for over 2 years.  Will there be a fix for this?

**Comment by timvandermeij** [comment] 2018-03-28 19:57
Closing since this is a duplicate.

**Closed by timvandermeij** 2018-03-28 19:57 UTC
