### ISSUE TITLE
No Link generated for bookmark

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10972] opened 2019-07-14 13:26 UTC
Attach (recommended) or Link to PDF file here:
[160202-2.pdf](https://github.com/mozilla/pdf.js/files/3389902/160202-2.pdf)

Place this pdf in a folder named 10-11
[172-405b.pdf](https://github.com/mozilla/pdf.js/files/3389906/172-405b.pdf)

Configuration:
- Web browser and its version: Chrome 75.0.3770.100
- Operating system and its version: Windows 10
- PDF.js version: 2.1.266
- Is a browser extension: No

Steps to reproduce the problem:
1. Click outline button in sidebar
2. Click the bookmark "Go to another file" (Nothing happens)
3. Right click on the text and select "Inspect"
4. In dev console, there is no hyperlink generated

What is the expected behavior? (add screenshot)
There should be some sort of link in the anchor tag href so that it will go to another file. If you open this in Acrobat Reader, it works and prompts you if you wish to open 172-405b.pdf

What went wrong? 
No link was generated

**Comment by Snuffleupagus** [comment] 2019-07-14 13:36
Duplicate of #8771.

**Closed** 2019-07-14 14:06 UTC

**Comment by chitgoks** [comment] 2019-07-15 03:18
hi @Snuffleupagus i tracked this one too. thought I tried to set the base url in viewer.js but it still does not work and im not sure if i understood the thread right.

does this mean the workaround is to make my own pdf.js viewer that will call getDocument() with the base url?

please advise. thank you

**Comment by chitgoks** [comment] 2019-07-15 03:33
@Snuffleupagus thank you. just a quick question for confirmation.
based on that thread, does this mean it is not possible with the current viewer and i that i have make a custom viewer that includes that base url when getDocument() is called?

I tried to manually set base urls in variables like baseDocumentUrl, url, baseUrl but to no avail. 

please advise.

**Comment by yvk36** [comment] 2019-07-18 04:47
@chitgoks do you know where the pdfjsLib.getDocument needs to be included?
