### ISSUE TITLE
PDF Viewer links off by one page in PDF js #7243

### ISSUE THREAD

**Issue by santhoshcd** [mozilla/pdf.js#7246] opened 2016-04-25 10:20 UTC
Link to PDF file (or attach file here):

Configuration:
  Web browser and its version: Firefox 43.0.4
  Operating system and its version: Windows 8
  PDF.js version: v1.4.20

Steps to reproduce the problem:
1. Open pdf file in html page using html Object tag 
2. Click on page number link(hyperlink) which is show incorrect page number of PDF files in pdf.js.
![pdf_js_error1](https://cloud.githubusercontent.com/assets/15076081/14780879/c2ebddf2-0afc-11e6-94b5-714a1f8baa8f.PNG)

What is the expected behavior? (add screenshot)
It is expected that clicking the links will move to the correct page in the PDF, however the pages seem to be offset by 1 page.

What went wrong? (add screenshot)
![pdf_js_error1](https://cloud.githubusercontent.com/assets/15076081/14780889/d1d8521e-0afc-11e6-888f-fd78f22c0852.PNG)

Which is working fine when i open same pdf file in firefox with pdf.js(in URL sample.
pdf#page1 or sample.pdf#page=1) and in Adobe reader(chrome)

![pdf_js_success1](https://cloud.githubusercontent.com/assets/15076081/14780940/11f84480-0afd-11e6-85fc-0ca5b2a97556.PNG)
![pdf_js_success2](https://cloud.githubusercontent.com/assets/15076081/14780941/13d0926c-0afd-11e6-9aa7-843276e89eae.PNG)

I created in jsfiddle but i am not able to include pdf files

[https://jsfiddle.net/santhoshcd/9ngm5Lke/](url)

I checked pdf.js [https://github.com/mozilla/pdf.js/issues/7154](url) but i did not get any solution for this problem. They are telling there is a problem in PDF file, if there is a problem then how Same pdf file is working fine in adobe reader and firefox with PDF.js(sample.pdf#page=3 or sample.pdf#page=4).

Please give me solution for this issue.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2016-04-25 10:52
> https://jsfiddle.net/santhoshcd/9ngm5Lke/

This example doesn't actually seem to do anything, since it appears to refer to a local file. If you want help, you must provide a *working* example that someone else (besides you) can actually run.

![not-working](https://cloud.githubusercontent.com/assets/2692120/14781658/1afc6af2-0ae4-11e6-9d2e-45ce586e8372.png)

But looking at the your code, you are for some reason setting the initial position to `...&zoom=75,0,0`, which is equal to the *bottom left* corner of a page. Try setting only it `...&zoom=75` and see if that helps.

Again, since you're not provided a working example, it's very difficult for anyone to help here.

**Comment by santhoshcd** [comment] 2016-04-26 07:52
Thanks, it solved the problem but how this one is working fine(..&zoom=75,0,0) for other pdf files in pdf.js and adobe reader?. 
I did not get file hosting site to which gives me the url contains '.pdf' at the end of the url that's why I added 'sample.pdf' instead of actual file sorry for that.

**Comment by Snuffleupagus** [comment] 2016-04-26 09:08
> Thanks, it solved the problem but how this one is working fine(..&zoom=75,0,0) for other pdf files in pdf.js and adobe reader?

Again, without working examples, we cannot tell what is wrong in your custom implementation.
However, since it sounds like you got things to work now, I'm closing this issue.

**Closed by Snuffleupagus** 2016-04-26 09:08 UTC
Labels: 4-information-requested

**Comment by vipulvkp** [comment] 2016-05-05 09:39
@Snuffleupagus  : Hi we replaced zoom parameter from (75,0,0) to (75) . 
This solution obviously works , but the problem is it works for some documents and for some documents it still shows the old feature of spilling over to next page.

Eg 1: 

<my application>/show_pdf/123.pdf#page=2&zoom=75 ->goes to page 2 . Works well.

<my application>/show_pdf/456.pdf#page=2&zoom=75 ->goes to page 3 !!!!  If I remove zoom parameter, it redirects fine to page 2.

So can u please tell why this happening . For one pdf it works well, but for some other pdf it still shows the same old behavior. 

Are there any other factors related to pdf document that we should take care of???

Thanks
