### ISSUE TITLE
Japenese Document issue

### ISSUE THREAD

**Issue by pillaiabhilash** [mozilla/pdf.js#6734] opened 2015-12-07 15:36 UTC
Hi Guys,

We got a Japanese document, attached here:

[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/54127/compressed.tracemonkey-pldi-09.pdf)

It has problem when rendered using PDF.js (attached images show how the original is & how does it look with PDF.js..

![original document - view](https://cloud.githubusercontent.com/assets/12607134/11631038/38b865ae-9d26-11e5-8540-87379a88f8cf.png)
![document using this tool - view](https://cloud.githubusercontent.com/assets/12607134/11631037/38b6f5e8-9d26-11e5-9b69-a025024e4e31.png)

Any thoughts?

Thanks
Abhi

**Comment by timvandermeij** [comment] 2015-12-07 22:25
This is rendered correctly with the latest PDF.js development version for me on Windows 10 x64. Please open the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if you can reproduce the issue with the latest PDF.js development version. If not, we can close this issue. If you can, please also provide more information about your OS name and version and browser name and version.

**Comment by pillaiabhilash** [comment] 2015-12-08 08:13
Hello,

Thank you for your reply. The document that you have used seems to be different. We tried with both the BETA version & the latest Released version of PDF.js, but still we are unable to see the Japanese characters correctly. We are on windows 7 OS with browsers: Chrome, Firefox and IE 11.

Any further help would be much appreciated.

Thanks
Abhi

**Comment by Snuffleupagus** [comment] 2015-12-08 09:11
> We tried with both the BETA version & the latest Released version of PDF.js,

The question was if this issue is present in the *latest* version of PDF.js (as of this writing that is `1.3.62`), which is newer than both the release and beta versions.
To check if you PDF file works in the latest version of PDF.js, please follow these steps *exactly*:
 1. Open http://mozilla.github.io/pdf.js/web/viewer.html.

 2. Click on the "Open file" button on the toolbar (see the screen-shot below).
![openfile](https://cloud.githubusercontent.com/assets/2692120/11651692/027bde40-9d93-11e5-9488-cd974077338a.png)

 3. Open your PDF file (i.e. the same file that you attached here).

If you follow these steps *exactly*, is your file rendered correctly in the *lastest* version of PDF.js?

**Comment by pillaiabhilash** [comment] 2015-12-08 09:52
Hey,

Thanks again. Yes it renders fine on that link, when i try to open it.

Could you please provide a direct download link to the PDF.js version 1.3.62

Thanks
Abhi

**Comment by pillaiabhilash** [comment] 2015-12-08 10:28
Hi Again,

Actually i am looking at the complete package with version 1.3.62 - the download link to the complete package will help us test this scenario again through the application.

Thanks for your help.

Thanks
Abhi

**Comment by SamyCookie** [comment] 2015-12-08 10:34
Hi,
'1.3.62' is the trunk (the current) development version of PDF.js.
You can see it in the 'code' tab of github, and get it by cloning it with git, or by clicking on the 'download ZIP' button.

**Comment by pillaiabhilash** [comment] 2015-12-08 11:00
Hey,

We downloaded the zip file from the code tab and observed that the document is not working in it" we have also got another link for  https://github.com/mozilla/pdfjs-dist (1.3.62) version which has Cmap folder in it while the project which we have downlaoded with the Zip do not have such folders and files.

Any thoughts?

Thanks
Abhi

**Comment by Snuffleupagus** [comment] 2015-12-08 11:00
Since it appears that this issue is with a custom deployment of PDF.js, it *might* not be necessary/enough to update PDF.js to the latest version (I've tested the included PDF file in versions older than the current release, and it still works).

It's quite possible that this issue is in fact caused by the CMaps not being included properly, or that the path them are not correct, in your custom deployment. If that is the case, this should be indicated by a warning/error being printed in the browser console.

**Comment by pillaiabhilash** [comment] 2015-12-08 13:35
Thanks for your reply. I guess we are getting there now. Doing few rounds of test!

Thanks
Abhi

**Comment by timvandermeij** [comment] 2015-12-09 21:27
Since it's working with the current PDF.js version and even previous versions, I strongly suspect that the CMaps are causing the issue for you. I'm closing this as resolved since the problem really appears to be your custom deployment. We can reopen this if it turns out to be an issue in PDF.js after all, but it's really not likely from the information present here.

**Closed by timvandermeij** 2015-12-09 21:27 UTC
Labels: 4-information-requested
