### ISSUE TITLE
Provide preview text of each search items through updatefindmatchescount event

### ISSUE THREAD

**Issue by cgiontrading** [mozilla/pdf.js#16621] opened 2023-06-29 09:24 UTC
Hello there,

I came across this [PDF.js Express viewer](https://pdfjs.express/demo/viewer) which have a find panel listing down all of the found entries.
Clicking on the entry lets user to jump directly to that point.

![pdfjs_express_reference](https://github.com/mozilla/pdf.js/assets/66666847/6b99a616-c251-48bf-9596-2ac98998f21e)

In my web application I would like to have similar functionality. For this I tried to study the `text layer` implementation and was able to implement something working, sort of. For this I used the `_pageMatches` and `_pageMatchesLength` from the `PDFFindController` (which I think is not good way to do).

![image](https://github.com/mozilla/pdf.js/assets/66666847/6ffeb4f9-3953-494f-a139-fc5b07e16d64)

I was able to extract the text around the matched content but its not perfect.
1. I am not able to honour the white space around the words.
2. Its is not so performant as I have to extract text content for each page where the math is found.

It will be great if the sentence or few words around the match text can be provided somehow.
In case this can be already be done with existing APIs, please guide me how to do so.

Test PDF file [Lorem Ipsum.pdf](https://github.com/mozilla/pdf.js/files/11904138/Lorem.Ipsum.pdf)

Thanks.

**Comment by Snuffleupagus** [comment] 2023-06-29 09:42
Looks (effectively) like a duplicate of issues #7605 and #12892.

---

> I came across this [PDF.js Express viewer](https://pdfjs.express/demo/viewer) which have a find panel listing down all of the found entries.

Please keep in mind that the mentioned example has no affiliation/relation to the PDF.js project, hence we cannot provide any help/support for that here.

> In case this can be already be done with existing APIs, please guide me how to do so.

This feature is unfortunately not (currently) planned, since it's not really relevant for the *built-in* Firefox PDF Viewer; hence there's no specific functionality available to make that easy to implement.
(Please keep in mind that this is first and foremost a *bug tracker*, rather than a support forum.)

**Closed by Snuffleupagus** 2023-06-29 09:42 UTC

**Comment by cgiontrading** [comment] 2023-06-29 10:17
@Snuffleupagus, thanks for the reference. The reference code you shared is very simple. Its does not account for case sensitivity, whole word and diacritics settings.

To handle this at application side is basically reimplement everything what the `PDFFindController` is doing.
It will be easy to integrate this directly inside `PDFFindController` as it already have things required in place. Just need to add another regular expression to extract the preview.

Additional flag can be added to the `PDFFindController` config to enable preview text.

**Comment by cgiontrading** [comment] 2023-06-29 10:20
> (Please keep in mind that this is first and foremost a bug tracker, rather than a support forum.)

@Snuffleupagus, can you please point be to correct place to request new features :)

**Comment by Snuffleupagus** [comment] 2023-06-29 10:32
> It will be easy to integrate this directly inside `PDFFindController` as it already have things required in place. Just need to add another regular expression to extract the preview.

First of all, as already mentioned above this isn't relevant to the *built-in* Firefox PDF Viewer; hence we won't implement this since every new feature adds maintenance/support burden and we generally don't want to add a bunch of unused code.
Secondly, you're most likely underestimating the size/scope of something like this since code not only needs to be written, but also reviewed, tested, and finally maintained/supported (potentially) for years.

**Comment by cgiontrading** [comment] 2023-06-29 10:50
@Snuffleupagus, thanks for the clarification, really appreciate your time and efforts :)

**Comment by benlieb** [comment] 2024-08-08 18:53
@cgiontrading Did you ever get this implemented? We are wanting to do something similar. 

Looks like we went with the wrong library in pdfjs, if it's only meant to support the use case of Firefox pdf rendering. That would explain why the documentation is so sparse. 😞

**Comment by nicolo-ribaudo** [comment] 2024-08-08 20:21
@benlieb If https://github.com/mozilla/pdf.js/pull/18549 lands, you can probably subclass PDFFindController overwriting `.match` to get the info you want.

**Comment by benlieb** [comment] 2024-08-08 20:56
> @benlieb If #18549 lands, you can probably subclass PDFFindController overwriting `.match` to get the info you want.

@nicolo-ribaudo Sounds unlikely to land. 

I just need to know how to navigate to the matches. I don't understand the structure of the matches and the source code is pretty hard for me to follow.

**Comment by cgiontrading** [comment] 2024-08-09 05:39
@benlieb, yes, I was able to implement this. As I said in my previous post, it's not so performant and blindly based on what the PDFFindController is doing.

**Comment by benlieb** [comment] 2024-08-09 16:55
Curious how you did it if you're willing to share @cgiontrading

**Comment by cgiontrading** [comment] 2024-08-12 05:19
Sure, but as mentioned by @Snuffleupagus this is not the correct place to discuss such things 😊
Will post a link in few days describing the steps and pseudo code. Does this work for you @benlieb?

**Comment by cgiontrading** [comment] 2024-08-14 06:23
@benlieb [Rich find panel with PDF.js](https://gist.github.com/cgiontrading/03b3d5a85af953a4d4cd11cbf656e4c3#file-pdfjs_find_panel-md) I hope this find you useful.

**Comment by benlieb** [comment] 2024-08-14 16:48
> @benlieb [Rich find panel with PDF.js](https://gist.github.com/cgiontrading/03b3d5a85af953a4d4cd11cbf656e4c3#file-pdfjs_find_panel-md) I hope this find you useful.

Thanks so much for this! I'll get to compare our approaches.

**Comment by benlieb** [comment] 2024-09-18 17:48
@cgiontrading I was able to get something working but it was pretty uncomfortable and quite hacky. your code definitely put me on the right track but I had to make a lot of modifications for our used case and script. Here's a video

https://github.com/user-attachments/assets/a03dd1cf-475c-4138-b669-f0b21e95ad85

**Comment by anas-koraspond** [comment] 2024-10-20 12:11
@benlieb please can u share the code which you have implemented
