### ISSUE TITLE
PDF文档预览失真

### ISSUE THREAD

**Issue by xietongjian** [mozilla/pdf.js#12757] opened 2020-12-19 07:02 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Google Chrome   版本 84.0.4147.89（正式版本） （64 位）
- Operating system and its version: win10
- PDF.js version:
- 
![image](https://user-images.githubusercontent.com/16096832/102683330-1fc4d980-420b-11eb-8e5d-f6675ee676a5.png)

- Is a browser extension:

Steps to reproduce the problem:
1. 
![image](https://user-images.githubusercontent.com/16096832/102683301-cb215e80-420a-11eb-913e-5457c61984b8.png)

2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment] 2020-12-19 13:08
We can only assist in English and with a PDF file provided. From the screenshot this looks like a duplicate of #11957.

**Closed by timvandermeij** 2020-12-19 13:08 UTC
