### ISSUE TITLE
Using Web Crypto API

### ISSUE THREAD

**Issue by dyue** [mozilla/pdf.js#11501] opened 2020-01-11 09:33 UTC
I see that pdf.js is using Javascript to decrypt byte streams.  Is there any plan to leverage Web Crypto API to improve performance?

**Comment by Snuffleupagus** [comment] 2020-01-11 12:42
A couple of quick questions:
 - Do you have examples of encrypted PDF documents where the performance is currently bad, because of the implementation in [src/core/crypto.js](https://github.com/mozilla/pdf.js/blob/master/src/core/crypto.js)?
 - Does the Web Crypto API support the encryption algorithms commonly used in PDF documents, see e.g. https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G6.1817214 and https://github.com/mozilla/pdf.js/blob/4729fdc0e930154c9e4c4688b6239ed4708f0e5e/src/core/crypto.js#L1839-L1869
 - How well is the Web Crypto API supported across browsers?

**Comment by dyue** [comment] 2020-01-11 18:13
- I can't enclose the secured PDF that I have because of NDA.    However, newer secured PDFs will likely be encrypted using AES and AES can be pretty slow to run compared to RC4, especially on a phone.  I did some optimization to the AES in crypto.js (like using double buffering instead of recreating the working buffer to help with garbage collection and to lessen the amount of array accesses when doing the xor's), but the improvement is only around 10-20%.

- Here's a link on examples using Web Crypto: https://github.com/diafygi/webcrypto-examples.  RC4 is likely not supported, but it should be possible to use Web Crypto for AES.   The idea is not to remove crypto.js, but to have logic in crypto.js to switch to use Web Crypto AES when possible instead of Javascript version of AES.     

- Here's a link on browser compatibility: https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API.   The idea is that if the browser has an instance defined for window.crypto and userAgent is not blacklisted, there is Web Crypto.   There should also be a setting value to disable the usage of Web Crypto if there is a problem.

**Comment by Snuffleupagus** [comment] 2020-01-11 18:52
> I can't enclose the secured PDF that I have because of NDA.

That's somewhat of a problem in general, since that makes it impossible for anyone else to reproduce the issue you're seeing. (And it also becomes more difficult to know when an issue is "fixed").

**Comment by Snuffleupagus** [comment] 2020-01-11 19:00
> I can't enclose the secured PDF that I have because of NDA.

That's unfortunately somewhat of a problem in general, since that makes it impossible for anyone else to reproduce the issue you're seeing. (And it also becomes more difficult to know when an issue is "fixed").

> The idea is that if the browser has an instance defined for window.crypto and userAgent is not blacklisted

Please note that the code in question, i.e. `src/core/crypto.js`, runs in a Web Worker and *not* in a `window` context. Generally speaking you also need to do actual feature detection, rather than relying on the userAgent (since the latter is easily spoofed).

**Comment by timvandermeij** [comment] 2020-01-11 20:59
I think using the Web Crypto API is an interesting idea and it appears to be well supported across browsers according to MDN. Here is an overview of the supported operations: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

**Comment by Snuffleupagus** [comment] 2020-01-11 21:02
> [...] it appears to be well supported across browsers according to MDN.

Well, not if you look at the "Available in workers" line in the support table, so assuming that information is actually correct this is essentially impossible until proper web platform support exists.

**Comment by timvandermeij** [comment] 2020-01-11 21:05
Good point, I didn't notice that the worker support was specified separately. It does mean we could still have a benefit from feature-detecting and using this to potentially speed up the crypto operations for Firefox (and other browsers if they add support). It would be nice to do a benchmark of the Web Crypto implementation and our implementation to see if it's worth the effort.

**Comment by Snuffleupagus** [comment] 2020-01-13 11:43
> It does mean we could still have a benefit from feature-detecting and using this to potentially speed up the crypto operations for Firefox (and other browsers if they add support).

There seem to be another problem here, if you look at https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto#Methods
All methods are listed as being asynchronous (i.e. they return a `Promise`), which quite simply is *not* going to work since that means that it'd become *impossible* to access *any* data synchronously on the worker-thread. Note e.g. the following code used in the `XRef` class: https://github.com/mozilla/pdf.js/blob/40f531ee873f523e2991fd6c2ca00a336fdbfbdd/src/core/obj.js#L1811-L1812

Assuming that I've understood things correctly, the only way that `SubtleCrypto` could be ever be used would be to if the *entire* `src/core/` folder was re-factored such that all dictionary lookups (and thus essentially all data access) would only be asynchronous. That wouldn't only be a *huge* project (years), but would also add *a lot* of complication to the the code, and in all likelihood *regress* overall performance (for all documents) a fair bit in the process.

All-in-all, what's suggested in this issue simply doesn't seem feasible and given the lack of a test-case I'd suggest closing this since it's unfortunately not actionable.

**Closed** 2020-01-13 23:47 UTC
Labels: 1-core
