### ISSUE TITLE
getTextContent() Shows jumbled symbols instead of text

### ISSUE THREAD

**Issue by RonenR** [mozilla/pdf.js#8044] opened 2017-02-08 11:10 UTC
[Scriptures - John Lesson 17.pdf](https://github.com/mozilla/pdf.js/files/760419/Scriptures.-.John.Lesson.17.pdf)
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Linux / Mac
- PDF.js version: 1.6.418
- Is an extension: 

Steps to reproduce the problem:
1. Simply load document and read text. 
2. Real code where we do that: http://ttsreader.com
3. Try to upload the attached file.

What is the expected behavior? Text

What went wrong? Jumbled symbols instead.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): http://ttsreader.com

Thanks!

**Comment by Snuffleupagus** [comment] 2017-02-08 11:21
I get similar broken behaviour in a number of other PDF readers as well, e.g. in both Adobe Reader and PDFium (in Chrome).
The issue is with the PDF file *itself*, since the embedded fonts are missing the `ToUnicode` entries required for text-selection to work properly.

Closing as invalid, since we unfortunately cannot do anything about the missing data in the PDF file.

**Closed by Snuffleupagus** 2017-02-08 11:21 UTC
