### ISSUE TITLE
[Bug]: issue with missing characters in the right

### ISSUE THREAD

**Issue by shivansh488** [mozilla/pdf.js#18386] opened 2024-07-04 17:24 UTC
### Attach (recommended) or Link to PDF file

the pdf with Arial regular font  espacilly which have more than 20 pages are have a issue where the test on right side of the page is missing 

If the same pdf is opened  in Adobe Reader or Chrome (again using Adobe Reader) All the text shows up correctly.

### Web browser and its version

latest Firefox 127.0. 2

### Operating system and its version

windows 10 

### PDF.js version

19.

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

just open a pdf with the font provided above with 20 or  more pages

### What is the expected behavior?

the right bunch of text would be missing

### What went wrong?

the right bunch of text would be missing

### Link to a viewer

http://skincarerx.com/p_include/rebates/sc13-9842-003-skincarerx-dec-rebate-offer.pdf

**Comment by Snuffleupagus** [comment] 2024-07-04 17:57
> Attach (recommended) or Link to PDF file

You haven't actually attached the PDF document here, making this issue non-actionable.

> ### PDF.js version
> 
>

Please note that this information is *required*.

> ### What is the expected behavior?
> 
> the right bunch of text would be missing

> ### What went wrong?
> 
> the right bunch of text would be missing

This is missing the requested screen-shots.

> ### Link to a viewer
> 
> http://skincarerx.com/p_include/rebates/sc13-9842-003-skincarerx-dec-rebate-offer.pdf

This link doesn't work.

**Comment by timvandermeij** [comment] 2024-07-05 14:00
Closing since based on the above the issue is not actionable at this point in time. We can reopen this if _all_ requested information from the template is provided.

**Closed by timvandermeij** 2024-07-05 14:00 UTC
Labels: information-requested
