### ISSUE TITLE
Misplaced dieresis in umlauts and spurious character displayed

### ISSUE THREAD

**Issue by hagman** [mozilla/pdf.js#4130] opened 2014-01-16 15:38 UTC
My PDFs (e.g. http://www.redeker.de/makepdf.php/main-V2.php/de/news/pm20140110.html?pdfdesign=pm&md5=a140c7c59b4554d0e41436e97f9f0747&pdftype=.pdf ) display with the following problems:
1. The dots over umlauts are misplaced. They appear shifted to the left and seemingly at the same position, i.e. too low for upper case letters (e.g. "Öffentlichkeitsarbeit")
2. A spurious grey "S" appears in the logo on top. Its size and position seem to depend on the zoom factor (it grows and moves up and to the right with the zoom factor: with 100% it appears very small below the fourth letter; with 240% it nearly matches the 8th letter; with 400% it is much bigger than the logo letters and gets cropped on top) 

Tested with PD viewer 0.8.874 on Firefox 26.0.

The PDF is created with PDFLaTeX with embedded fonts and displays nicely in "all other" pdf viewers (kpdf, okular, adobe, ...)

**Comment by brendandahl** [comment] 2017-11-05 01:48
This doesn't appear to be an issue anymore. I'll close the issue, but if you still see issues let us know and we'll re-open.

**Comment by deboerk** [comment] 2018-11-19 22:05
There still seems to be a problem with misplaced umlaut dots. See: [test.pdf](https://github.com/mozilla/pdf.js/files/2597151/test.pdf) I tested pdf.js in Firefox 63 on Debian 9. The PDF is created with PDFLatex with embedded fonts and it is correctly displayed in Okular, Adobe Reader, and MacOS Preview.

**Comment by timvandermeij** [comment] 2018-11-19 22:17
I can confirm the finding above with Firefox 63.0.3 (64-bits) on Arch Linux with the latest development viewer at https://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by Snuffleupagus** [comment] 2018-11-20 06:52
@timvandermeij Let's open a new issue for https://github.com/mozilla/pdf.js/issues/4130#issuecomment-440058536 instead[1], and let this one remain closed, since there's no strong reason to believe that it describes the *same* problem as in the OP.

---
[1] That should be pretty simple, using the new "Open new issue" button in the '...' menu on the comment :-)

**Closed** 2020-08-24 19:55 UTC
Labels: 4-font-conversion
