### ISSUE TITLE
PDFs generated from Confluence Cloud pages that have text formatted as inline code are broken

### ISSUE THREAD

**Issue by G-Rath** [mozilla/pdf.js#15066] opened 2022-06-19 23:45 UTC
PDFs are not something I have any real knowledge about so while I'm happy try and help I can't promise I'll be any use - similarly, I've tried to look for duplicates but I also don't really know what I'm looking for on the lower-level side so this might have already been reported.

Attach (recommended) or Link to PDF file here: [557058d020c1ca508c4447a05433a8fcaca5ca-test-230522-0209.pdf](https://github.com/mozilla/pdf.js/files/8936605/557058d020c1ca508c4447a05433a8fcaca5ca-test-230522-0209.pdf)

### Configuration:
- Web browser and its version: Chrome Version 102.0.5005.115 (Official Build) (64-bit)
- Operating system and its version: Windows 11
- PDF.js version: unknown (couldn't find a way to have the extension tell me?)
- Is a browser extension: Yes, v2.3.164

### Steps to reproduce the problem:
1. Create a page in Confluence Cloud
2. Write a sentence with some inline code in the middle
3. Export the page as a PDF

### What is the expected behavior? (add screenshot)

When opened in Edge Version 102.0.1245.44 (Official build) (64-bit) native PDF viewer:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/3151613/174504564-b027610f-5465-4648-87b9-55e782a2336b.png">

### What went wrong? (add screenshot)

When opened in Chrome Version 102.0.5005.115 (Official Build) (64-bit) pdf.js extension viewer:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/3151613/174504568-662505af-9b86-4065-b613-633e8e8f577f.png">

The text formatted as inline code is not visible, and impacts complex structures (e.g. tables & bullet points)

Here's an example of how breaking this is:
![image](https://user-images.githubusercontent.com/3151613/174504465-8582f0a0-732b-4b43-acc3-b3ce1538db65.png)

(the white-with-black-border boxes are me covering sensitive text that can be ignored).

Removing all of the inline code styled text resulted in a PDF that could be opened without issue.

### Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://chrome.google.com/webstore/detail/oemmndcbldboiebfnladdacbdfmadadm

**Comment by Snuffleupagus** [comment] 2022-06-20 07:21
Duplicate of #13669

**Closed by Snuffleupagus** 2022-06-20 07:21 UTC
