### ISSUE TITLE
Exceptions when load a document while loading document

### ISSUE THREAD

**Issue by xlc** [mozilla/pdf.js#6523] opened 2015-10-13 00:09 UTC
Using demo viewer with Chrome v46

While loading a PDF from internet or a huge pdf from local file, while the file is loading, open another document sometimes will cause some exceptions. I have throttled the network so the file is not loading too fast.

I think the solution is to teardown the worker properly before loading a new document.

```
Uncaught (in promise) TypeError: Cannot read property 'pdfPage' of undefined
(…)(anonymous function) @ viewer.js:4894
Promise.resolve (async)messageHandlerComObjOnMessage @ pdf.js:1494
2015-10-13 13:05:43.304 viewer.html:1 Uncaught (in promise) TypeError: Cannot read property 'pdfPage' of undefined
(…)(anonymous function) @ viewer.js:4894
Promise.resolve (async)messageHandlerComObjOnMessage @ pdf.js:1494
```

```
Uncaught TypeError: Cannot read property '_renderPageChunk' of undefined
transportRender @ pdf.js:2718
messageHandlerComObjOnMessage @ pdf.js:1522
2015-10-13 13:06:57.811 pdf.js:2718 Uncaught TypeError: Cannot read property '_renderPageChunk' of undefined
transportRender @ pdf.js:2718
messageHandlerComObjOnMessage @ pdf.js:1522
```

**Comment by Snuffleupagus** [comment] 2015-10-13 09:41
Closing as duplicate of issue #3485.

**Closed by Snuffleupagus** 2015-10-13 09:41 UTC
