### ISSUE TITLE
Toolbar Option In Presentation Mode

### ISSUE THREAD

**Issue by cooperstevenson** [mozilla/pdf.js#9884] opened 2018-07-09 21:23 UTC
Hello All,

Feature Request. 

It is said (#4816, #5993, and #6688) that a toolbar in presentation mode is out of scope for the default viewer. I humbly submit that presentation mode offers a higher quality reading experience and that adding an option for developers to include the toolbar in presentation mode is a great feature to have.

I created a video outlining a [UI analysis for why this is so](http://portfolio.cooper.stevenson.name/images/pdf_js_presentation.mp4).

The long and short of my argument hinges around the idea that PDF"s can be easily rendered to fit the user's device. When the page is perfectly matched to the device and thumbnail/content views you get a quality reading experience with the ability to navigate quickly and intuitively through the document.

Would you please add an option to include the toolbar in presentation mode or offer a pointer where I may implement this feature?

Configuration:
- Web browser and its version:
All Browsers
- Operating system and its version:
All OS's.

- PDF.js version:
All versions.

- Is a browser extension:
No.

Steps to reproduce the problem:
1. Use Presentation Mode
2. Note absence of toolbar

What is the expected behavior? (add screenshot)
Have option to add a toolbar to presentation mode

What went wrong? (add screenshot)
No Tool Bar

**Comment by cooperstevenson** [comment] 2018-10-19 00:14
I don't want to degrade my own feature request or embarrass anyone--if I can make this change simply with JS or CSS I'd like to know.

Beyond that, if we could have full screen with the thumbnail/contents menu I mentioned plus even/odd spreads (by server option and/or URL option) then that would be sublime.

**Comment by cooperstevenson** [comment] 2018-11-16 17:32
As I [noted in the video](http://portfolio.cooper.stevenson.name/images/pdf_js_presentation.mp4), an entire tool chain exists for building PDF's having dimensions perfectly suited for the client's device. Dimensioned PDF's combined with media queries from the client result in perfect PDF presentation _if_ this feature is implemented.

I would happily contribute to this project in any way I can to get this feature into the project.

**Comment by Snuffleupagus** [comment] 2018-11-16 18:59
> It is said (#4816, #5993, and #6688) that a toolbar in presentation mode is out of scope for the default viewer.

This *exact* feature request has been rejected a number of times, as suggested by the quoted text, since the added complexity was/is not wanted *and* browsers already contains a native fullscreen mode.
Hence it's not really clear why *yet* another issue was opened here (rather than just commenting on one of those); it seems to me that *this* issue probably should be closed as DUPLICATE of those ones.

> [...] when used in an iframe you can only use fullscreen in presentation mode with no toolbars,

There's an easy work-around available, by middle-clicking[1] on the "View Bookmark"-button to open the file in a separate tab/window. Then you can easily utilize the native browser fullscreen mode, e.g. with <kbd>F11</kbd>.

---
[1] Or right-clicking and choosing "Open Link in New Tab" from the context menu.

**Comment by timvandermeij** [comment] 2018-11-16 21:46
Closing since I also agree with the comment above. If need be, you can implement this in a custom deployment in https://github.com/mozilla/pdf.js/blob/master/web/pdf_presentation_mode.js.

**Closed by timvandermeij** 2018-11-16 21:46 UTC
Labels: 1-other, 1-ux, 1-viewer
