### ISSUE TITLE
Comment status (Accepted or Rejected)

### ISSUE THREAD

**Issue by bimalgeorge1** [mozilla/pdf.js#13181] opened 2021-04-05 09:55 UTC
Attach (recommended) or Link to PDF file here:
[ext-aconexwebservices-developersguide-150316-1448.pdf](https://github.com/mozilla/pdf.js/files/6257706/ext-aconexwebservices-developersguide-150316-1448.pdf)

Configuration:
- Web browser and its version: Firefox 87.0 64 bit
- Operating system and its version: Win 8.1
- PDF.js version: v2.6.347
- Is a browser extension: no

Steps to reproduce the problem:
1. open a file add some comments and change the status to accept or reject
2.open in PDF JS viewer it will not shows the status of the comment

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/13362914/113564859-afaa5a00-9627-11eb-95c4-8ecd7a3e8de1.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/13362914/113565092-116ac400-9628-11eb-8e39-a9a8b620c56c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):  mozilla.github.io/pdf.js

**Comment by Snuffleupagus** [comment] 2021-04-05 10:14
> Attach (recommended) or Link to PDF file here:
> [ext-aconexwebservices-developersguide-150316-1448.pdf](https://github.com/mozilla/pdf.js/files/6257531/ext-aconexwebservices-developersguide-150316-1448.pdf)
> [,..]
> What went wrong? (add screenshot)

The screen-shot doesn't seem to agree with the PDF document linked above, which makes part more confusing than helpful.

---

This looks, for all intents and purposes, like a duplicate of #10982

**Comment by bimalgeorge1** [comment] 2021-04-05 10:50
> 
> 
> > Attach (recommended) or Link to PDF file here:
> > [ext-aconexwebservices-developersguide-150316-1448.pdf](https://github.com/mozilla/pdf.js/files/6257531/ext-aconexwebservices-developersguide-150316-1448.pdf)
> > [,..]
> > What went wrong? (add screenshot)
> 
> The screen-shot doesn't seem to agree with the PDF document linked above, which makes part more confusing than helpful.
> 
> This looks, for all intents and purposes, like a duplicate of #10982

sorry for the inconvenience. i am updated the post .

**Comment by timvandermeij** [comment] 2021-04-05 11:28
This is indeed a duplicate of #10982.

**Closed by timvandermeij** 2021-04-05 11:28 UTC
