### ISSUE TITLE
Update toolbar overflow and sidebar icons to align with Firefox visual styles

### ISSUE THREAD

**Issue by rtestard** [mozilla/pdf.js#15401] opened 2022-09-06 10:24 UTC
We have to update some toolbar icons (primary UI) with https://github.com/mozilla/pdf.js/pull/15384#issuecomment-1236098185 in 106. This creates visual inconsistencies with overflow menu, find bar and side bar icons which now need a refresh.

This issue is for updating the icons from the overflow menu and sidebar in accordance with new Firefox icon styles:
- provide icon visual assets (UX)
- implement icon changes (engineering)

**Comment by Snuffleupagus** [comment] 2022-09-06 10:32
... and please don't forget about the icons in the `findbar`, since that one is actually used in the Firefox PDF Viewer for PDF documents placed in e.g. `iframe`-elements.

**Comment by rtestard** [comment] 2022-09-06 10:56
Thanks I now updated my comment and request to UX

**Comment by Snuffleupagus** [comment] 2022-09-13 09:49
Given the time-line mentioned in https://github.com/mozilla/pdf.js/pull/15384#issuecomment-1237986642, we should probably let this issue block the release of PDF.js version `3` (assuming it's not already fixed by the time we consider making the release).

/cc @timvandermeij

**Comment by timvandermeij** [comment] 2022-09-18 12:19
Yes, we'll keep this one in mind indeed and otherwise postpone the release of PDF.js 3.0 until it's completed.

**Comment by timvandermeij** [comment] 2022-09-24 12:54
I'm postponing the PDF.js 3.0 release until this issue is completed. Is there already an update from upstream on the timeline for this?

@calixteman @Snuffleupagus I've created the `release-blocker` label and assigned it to this issue so I have visibility on issues that block the upcoming release. If there are more, such as regressions, please add that label to the issues.

**Comment by Snuffleupagus** [comment] 2022-10-03 09:11
@rtestard @marco-c @calixteman There's now been (almost) *four weeks* without any sort of update here, which is twice the time mentioned in https://github.com/mozilla/pdf.js/pull/15384#issuecomment-1237986642.

Please note that this is holding up the next PDF.js release, so *some insight* into the process would surely help here!

**Comment by rtestard** [comment] 2022-10-04 15:40
Apologies for delay, I'm given Oct 8th as deadline for icon handoff by UX

**Comment by shivaprsd** [comment] 2022-10-14 14:59
Let me mention an associated issue: the current editor icons get easily lost in PDFs with dark areas (which is not often, but still).

Demo:
![editor-cursor](https://user-images.githubusercontent.com/18247990/195878202-b0474313-b912-4988-b1fc-a8f8d60db013.gif)

Solution: use a 1px thin white outline to the icons, which is standard for system I-beam and pointer cursors.

**Comment by timvandermeij** [comment] 2022-10-15 10:05
@rtestard October 8th is a week ago now; is there any news from the UX team already since this is the final release blocker for us?

**Comment by calixteman** [comment] 2022-10-15 10:10
I've been pinged yesterday about the new icons and they're almost ready, so we should have something next week.
Sorry about the delay.

**Closed** 2022-10-21 10:46 UTC
Labels: viewer, ux, release-blocker

**Comment by shivaprsd** [comment] 2022-10-22 06:12
Since https://github.com/mozilla/pdf.js/issues/15401#issuecomment-1279123677 did not get addressed by the finalised update, I have opened a new ticket #15611.

**Comment by Snuffleupagus** [comment] 2022-10-22 07:41
> Since [#15401 (comment)](https://github.com/mozilla/pdf.js/issues/15401#issuecomment-1279123677) did not get addressed by the finalised update, I have opened a new ticket #15611.

That wasn't really expected to happen unfortunately, since the scope of this issue was summarized in https://github.com/mozilla/pdf.js/issues/15401#issue-1363060359 and the cursor icons had already been updated previously.

*For future reference:* Please keep in mind that it's always better to report a new issue, and then have it be closed as a duplicate of an existing one (where doing so makes sense), rather than reporting different things in the same issue. Having a couple of (subtly) different problems reported in same issue could make it very difficult to know when any one issue is really fixed, which makes tracking things more difficult in general; see also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#issue

**Comment by timvandermeij** [comment] 2022-10-23 10:03
Since this was the final release blocker, I'd like to propose that I'll release PDF.js 3.0 next weekend since then it's both end of the month (and we can resume our normal release schedule again) and so we have a few more days to test and fix any last issues if we find any. @Snuffleupagus @calixteman Are you OK with that plan?

**Comment by Snuffleupagus** [comment] 2022-10-23 10:31
> Since this was the final release blocker, I'd like to propose that I'll release PDF.js 3.0 next weekend since then it's both end of the month (and we can resume our normal release schedule again) and so we have a few more days to test and fix any last issues if we find any. @Snuffleupagus @calixteman Are you OK with that plan?

Yes, that sounds reasonable to me.

**Comment by calixteman** [comment] 2022-10-23 12:30
Yes I'm.
