### ISSUE TITLE
Error in rendering Chinese character text annotation

### ISSUE THREAD

**Issue by yidu864** [mozilla/pdf.js#16960] opened 2023-09-17 02:37 UTC
Attach (recommended) or Link to PDF file here:
 1. origin pdf (generate from Microsoft® Word 2021):  [origin pdf](https://files.catbox.moe/od273s.pdf)
 2. origin pdf add text-annotation: [pdf](https://files.catbox.moe/twupw3.pdf)
 3.  open prev pdf and edit text-annotation: [pdf](https://files.catbox.moe/3eqwte.pdf)

Configuration:
- Web browser and its version: `Google Chome 116.0.5845.188 （64 Bit） (cohort: Stable) `
- Operating system and its version: `Windows 11 Version 21H2 (Build 22000.2416)`
- PDF.js version: `PDF.js: 3.9.49 [47b6bbf5a]`
- Is a browser extension: Yes, [PDF Viewer 3.9.49](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm)

Steps to reproduce the problem:
1. Open the first named 'origin' pdf above, then add any Chinese character text-annotation and save as new pdf
2. Open the new pdf saved in the first step, edit the existing Chinese character text-annotation (use any Chinese characters), and save as new pdf
3. Open the pdf that saved in the secend step, you will see chinese character text-annotation will be rendering error

What is the expected behavior? (add screenshot)
   Correct rendering of Chinese character annotations, like 
   ![expected](https://files.catbox.moe/1axald.jpg)
What went wrong? (add screenshot)
  Rendering error after secondary editing of Chinese character text-annotation
  error render
  ![unexpected](https://files.catbox.moe/91p8mg.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

None, I'm using pdf.js as a chrome extension, Use [PDF Viewer](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) to open the above pdf file link to see the results

Others: 
1. This exception does not only appear in the PDF files I provided. It seems that this error will occur in any PDF after executing the above steps to reproduce the problem.
2. Files that use [PDF Viewer](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) to add Chinese character annotation are abnormal when opened in other PDF viewers (e.g: Chrome built-in, Adobe-Acrobat). Chinese character annotation will be missing, and the behavior is as follows
![chrome-built-in](https://files.catbox.moe/wxprbc.jpg)
![adobe-acrobat](https://files.catbox.moe/pdn0e3.jpg)

**Comment by Snuffleupagus** [comment] 2023-09-17 05:31
Duplicate of #15769

**Closed by Snuffleupagus** 2023-09-17 05:31 UTC
