### ISSUE TITLE
Wrong landscape printing from Win10 Cordova app

### ISSUE THREAD

**Issue by dakus** [mozilla/pdf.js#11074] opened 2019-08-17 12:42 UTC
Demo PDF file:
[TMP9B17.PDF](https://github.com/mozilla/pdf.js/files/3511970/TMP9B17.PDF)

Configuration:
- Web browser and its version: Microsoft Edge 42.17134.1.0 embeded in Cordova 9.0.0
- Operating system and its version: Windows 10 (x64)
- PDF.js version: DEMO version https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. Open a landscape PDF file in viewer

![pdf-viewer](https://user-images.githubusercontent.com/5312135/63211565-4051c080-c0f9-11e9-8031-d4e8cc4702f6.png)

2. Click on the Print icon to see the print preview popup window

![pdf-preview](https://user-images.githubusercontent.com/5312135/63211603-c5d57080-c0f9-11e9-80d1-edffcc49005f.png)

What is the expected behavior?
The print preview should show the page in landscape mode.

What went wrong?
The print preview shows the page in portrait mode (see screenshot above).
After manually selecting landscape orientation, the page content is not shrunk to fit all available space and there is no a scale option to do that manually:

![pdf-preview-landscape](https://user-images.githubusercontent.com/5312135/63211683-f7027080-c0fa-11e9-8550-70b748fe93a4.png)

While opening the same PDF file directly in the Edge browser (not embeded in Cordova), the print preview still shows the portrait mode instead of landscape, but there is the "Scale" option which helps to shrink the content after manually switching portrait to landscape:

![pdf-preview-edge](https://user-images.githubusercontent.com/5312135/63211776-206fcc00-c0fc-11e9-988e-ae10a65b45a6.png)

**Comment by Snuffleupagus** [comment] 2019-08-17 13:34
Duplicate of #9297.

**Comment by dakus** [comment] 2019-08-17 14:42
> 
> 
> Duplicate of #9297.

The issue #9297 is related to auto-rotation, which is only a part of the problem described by me and not the most critical one, because without auto-rotation user still has the "Orientation" dropdown to rotate the page manually. A bigger problem is scaling, because user has no any possibility to fix it manually. Until auto-rotation and auto-scaling is implemented, is there any workaround to scale the landscape document (at least manually)? Please keep in mind that the problem is with embedded Edge, not standalone browser.

**Comment by Snuffleupagus** [comment] 2019-08-17 15:58
Please keep in mind that the ability to influence various printing options from JavaScript/CSS is *extremely* limited in general.

> Please keep in mind that the problem is with embedded Edge, not standalone browser.

As outlined in the FAQ, support for Internet Explorer is very limited, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

**Comment by timvandermeij** [comment] 2019-11-09 13:36
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.

**Closed by timvandermeij** 2019-11-09 13:36 UTC
Labels: 4-printing
