### ISSUE TITLE
print PDF not print correctly (header and footer appear)

### ISSUE THREAD

**Issue by rabat22** [mozilla/pdf.js#11071] opened 2019-08-16 09:40 UTC
Hi
I have a problem when i want to print PDF in IE11, i have always header and footer who appear. I know that we can in option IE change this, but i want to change it on source code. Can you change it on library pdfjs (i see there is a file name viewer.js but i don't find where we can resolve this problem.

I need a solution please because i can't continue like this.

![image](https://user-images.githubusercontent.com/25502578/63159001-ca772780-c01a-11e9-8b63-08cd5156de51.png)

**Comment by Snuffleupagus** [comment] 2019-08-16 09:43
Duplicate of #10125.

*For future reference:* You need to provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue, otherwise it will be closed as INCOMPLETE.

**Closed** 2019-08-16 20:50 UTC
