### ISSUE TITLE
[Feature]: stop renderring pages when user slide very quickly

### ISSUE THREAD

**Issue by HairlessVillager** [mozilla/pdf.js#18315] opened 2024-06-23 09:08 UTC
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

When I slide the pdf very quickly, the disk load will be very high and lots of pages will be rendered out of screen. I hope that when I slide the pdf at a very high speed, not all the page will be rendered.

**Comment by Snuffleupagus** [comment] 2024-06-23 09:23
Note that we already abort parsing/rendering of pages that are scrolled out of view.

Most likely this is a duplicate of e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1866296, however given the lack of a test-case it's impossible to tell for sure.

**Closed by Snuffleupagus** 2024-06-23 09:23 UTC
