### ISSUE TITLE
Incomplete rendering when using browser other than Firefox

### ISSUE THREAD

**Issue by nishanh** [mozilla/pdf.js#12497] opened 2020-10-19 17:33 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
Browser(s): Chrome 86.0.4240.75, Edge 86.0.622.43, Brave 86.0.4240.99
OS: Windows 10 64-bit (latest)
PDF.js: 2.5.207
Browser extension: No

Steps to reproduce the problem:
1. Navigate to the PDF.js demo viewer at https://mozilla.github.io/pdf.js/web/viewer.html
2. Load the attached PDF file [Postcard.pdf](https://github.com/mozilla/pdf.js/files/5403651/Postcard.pdf)
3. Notice that when using a browser other than Firefox, some of the strings attached to the sales tags are either missing or partially rendered. Mac/Safari browser seems to render ok.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/20070611/96490675-fc26e800-11f5-11eb-8a92-99bad662d379.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/20070611/96490816-2d9fb380-11f6-11eb-8e00-eb38244f1208.png)

Link to a viewer: https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment] 2020-10-20 12:55
> Notice that when using a browser other than Firefox, some of the strings attached to the sales tags are either missing or partially rendered. Mac/Safari browser seems to render ok.

That would suggest a canvas, hardware acceleration, and/or driver issue specific to Chromium-based browsers, rather than the PDF.js library; as such it's unfortunately very difficult to see that this can be fixed here.

**Comment by nishanh** [comment] 2020-10-20 14:52
In v2.2.228 the problem was much worse. Attached is a pic from 2.2.228 from our QA department. So something changed between versions that improved the situation and I'm left to conclude that there are still residual rendering issues in PDF.js. This is not exclusive to my hardware configuration. All of QA and the various project stakeholders are seeing this. If you don't wish to address the issue, I will indicate this to our project management so they can advise against the use of all browsers other than FF in our release notes.
![PDF Left VD Right](https://user-images.githubusercontent.com/20070611/96603732-24bbea00-12a9-11eb-8068-c590abd351ee.JPG)

**Comment by Snuffleupagus** [comment] 2020-10-25 08:28
> Browser(s): Chrome 86.0.4240.75, Edge 86.0.622.43, Brave 86.0.4240.99

All of these are Chromium-based, and we've seen a fair number of issues reported lately that *only* affect Chromium browsers.

> If you don't wish to address the issue,

As is hopefully obvious, we simply can't fix bugs in the browser *itself*; this issue should probably be closed as a duplicate of e.g. #12462, note in particular https://github.com/mozilla/pdf.js/issues/12462#issuecomment-713878908. /cc @timvandermeij

**Closed** 2020-10-25 11:19 UTC
Labels: 1-core, 2-image-quality
