### ISSUE TITLE
[Bug]: The Chinese characters of exported pdf files are not displayed after annotations are made using text tools

### ISSUE THREAD

**Issue by SprASum** [mozilla/pdf.js#19092] opened 2024-11-22 17:18 UTC
### Attach (recommended) or Link to PDF file

[2024.11.23.pdf](https://github.com/user-attachments/files/17873775/2024.11.23.pdf)

### Web browser and its version

Chrome 131.0.6778.86

### Operating system and its version

win10 && win11

### PDF.js version

4.8.69

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Use text tools to annotate Chinese in PDF

### What is the expected behavior?

The marked Chinese characters are displayed in the exported file

![image](https://github.com/user-attachments/assets/b049b31b-60eb-42e9-bb67-18ac63dfd277)

### What went wrong?

No Chinese characters are displayed
![image](https://github.com/user-attachments/assets/dc45a1d5-3017-4ccb-9f08-3ea70ae0759d)

### Additional context

When using the PDF extension in the document, the Chinese annotations will be displayed normally, but when opening the PDF file directly, it will not be displayed

**Comment by Snuffleupagus** [comment] 2024-11-22 17:20
Duplicate of #15769

**Closed by Snuffleupagus** 2024-11-22 17:20 UTC
