### ISSUE TITLE
Firefox 81 on Windows browser zoom affects the text layer alignment

### ISSUE THREAD

**Issue by neilkuumar** [mozilla/pdf.js#12523] opened 2020-10-23 11:13 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 81
- Operating system and its version: Windows 10
- PDF.js version: ~~`"pdfjs-dist": "2.1.266"`~~ `"pdfjs-dist": "2.5.207"`
- Is a browser extension: no

Steps to reproduce the problem:
1. Use pdf-dist to render a PDF in Firefox on Windows 10
2. Change the browser zoom and notice how the text layer misaligns

What is the expected behavior? This is fine in Chrome at 150% browser zoom
![image](https://user-images.githubusercontent.com/25818773/96997120-0f54f300-1529-11eb-85a4-784935bea4eb.png)
![image](https://user-images.githubusercontent.com/25818773/96997118-0b28d580-1529-11eb-873e-796ec809569f.png)

What went wrong? On Firefox (only on windows) 150% browser zoom
![image](https://user-images.githubusercontent.com/25818773/96997075-f3e9e800-1528-11eb-81f1-646bb4bbf9ec.png)
![image](https://user-images.githubusercontent.com/25818773/96997051-e92f5300-1528-11eb-997a-b7664c570f69.png)

**Comment by Snuffleupagus** [comment] 2020-10-23 11:46
> PDF.js version: `"pdfjs-dist": "2.1.266"`

That version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases

**Comment by neilkuumar** [comment] 2020-10-23 11:58
@Snuffleupagus can confirm the issue still exists after upgrading to `2.5.207`

**Comment by Snuffleupagus** [comment] 2022-08-10 13:32
Duplicate of #15229

**Closed by Snuffleupagus** 2022-08-10 13:32 UTC
Labels: text-selection
