### ISSUE TITLE
ie print will be compression

### ISSUE THREAD

**Issue by yangdailin** [mozilla/pdf.js#8215] opened 2017-03-30 09:41 UTC
'<div style="width:1000px;">'
	<iframe width="100%" height="910px" src="xxxxpdf"></iframe>
	'</div>'

when i set 'iframe' in 'div', and the 'div' set width, such as 1000px ,pdf print will be compression in IE

**Comment by timvandermeij** [comment] 2017-03-30 20:17
Closing since you did not provide all information required to reproduce the issue, as outlined in the issue template. Moreover, we already have open issues for IE behavior in combination with printing and iframes.

**Closed by timvandermeij** 2017-03-30 20:17 UTC
