### ISSUE TITLE
PDF file freezing Firefox

### ISSUE THREAD

**Issue by jpfleury** [mozilla/pdf.js#4242] opened 2014-02-04 03:57 UTC
The following PDF file freezes Firefox (and even all my system):

http://imslp.org/wiki/Special:ImagefromIndex/180073

When trying to view this PDF file, Firefox uses way too much CPU and RAM.

Tested with a default profile, no extensions, Firefox 26, Xubuntu 13.10.

**Comment by Snuffleupagus** [comment] 2021-09-28 10:09
Duplicate of #6741

**Closed by Snuffleupagus** 2021-09-28 10:09 UTC
Labels: 4-image-conversion
