### ISSUE TITLE
The browsing of some A0 drawings and superimposed A0 drawings may be blurry

### ISSUE THREAD

**Issue by DiverYang** [mozilla/pdf.js#16910] opened 2023-09-07 06:29 UTC
Attach (recommended) or Link to PDF file here:
[Uploading A0 test.pdf…]()
[A0 3 Splices test.pdf](https://github.com/mozilla/pdf.js/files/12545306/A0.3.Splices.test.pdf)

Configuration:
- Web browser and its version: firefox117.0,Chrome116.0.5845.180,Edge116.0.1938.69
- Operating system and its version:window10,window11
- PDF.js version:pdfjs-3.10.111
- Is a browser extension:No

Steps to reproduce the problem:
1. open pdf file
2.

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/30024556/f1f70440-99ff-488f-a1cb-5573f457ceef)
It displays normally in the integrated PDF browser of Edge and Chrome.
What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/30024556/b578cb0a-1900-40c9-9f4f-b2b398537b6d)
Run pdfjs-3.10.111 to display blurry in all browsers.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-09-07 06:43
Duplicate of #6419

**Closed by Snuffleupagus** 2023-09-07 06:43 UTC
