### ISSUE TITLE
Printing freezes using Chrome Extension

### ISSUE THREAD

**Issue by PaulProe** [mozilla/pdf.js#13894] opened 2021-08-13 02:45 UTC
I am re-submitting this ticket, with appropriate data requested.

[ShipmentArtifact-282401582864.PDF](https://github.com/mozilla/pdf.js/files/6979535/ShipmentArtifact-282401582864.PDF)

Configuration:
- Chrome Version 92.0.4515.131 (Official Build) (64-bit)
- Windows 10Pro Vers 21H1 Build 19043.1165
- PDF.js version: 2.3.164
- Is a browser extension: Yes, PDf Viewer ID: oemmndcbldboiebfnladdacbdfmadadm

Steps to reproduce the problem:
PDF files open in browser fine, download fine, but when you try to print, Dialog box opens and reports "Preparing document for printing with a progress bar and 0%" but app freezes at that point.
![image](https://user-images.githubusercontent.com/62920661/129296941-76cc5538-2469-4cd3-9ff3-d57eda4e7219.png)

Using a similar plugin in FireFox, the same procedure occurs however the print dialog box opens and you are able to print a a copy of the PDF.

This is a cut and paste from the Console:
viewer.js:1502 PDF 26419dad50c990faf0c69318bcfe9635 [1.4 FedEx Services / FedEx Customer Automation] (PDF.js: 2.3.164)
pdf.worker.js:1710 Warning: getOperatorList - ignoring errors during "GetOperatorList: page 0" task: "DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': function at() { [native code] } could not be cloned.".

I have filed tickets with WooCommerce, PluginHive (the plugin developer) and Google. All are pointing fingers at the chrome extension (right or wrong, I don't know who is at fault). The error is repeatable on three different machines with similar configuration. The problem seems to occur also on MS Edge.

The procedure worked successfully in the past, up until a few weeks ago but unable to trace to any given update. I just tried to print the attachment by opening it and clicking the icon and the problem is there.

Thanks for any ideas

Paul

**Comment by Snuffleupagus** [comment] 2021-08-13 07:58
Duplicate of #13889; please note that (as mentioned) this is already being tracked in issue #13669.

**Closed by Snuffleupagus** 2021-08-13 07:58 UTC
