### ISSUE TITLE
Showing toolbar in full screen mode

### ISSUE THREAD

**Issue by drjjw** [mozilla/pdf.js#5993] opened 2015-05-09 14:24 UTC
Hello,

Is it possible to enable the toolbar (especially search and navigation buttons) when the PDF is displaying in fullscreen/presentation mode?

Jordan

**Comment by yurydelendik** [comment] 2015-05-09 14:35
It's possible. For custom solution change the behavior of presentation mode to request full screen for the entire document (which means button will not be called "Switch to presentation mode" anymore).

Or mean to provide the same functionality browser exposes as "Enter Full Screen"? (F11 key?)

**Comment by drjjw** [comment] 2015-05-09 14:47
When selecting toolbar button 'Switch to Presentation Mode', I was wondering if the toolbar can display as it does in regular viewing mode. It seems that as it is now, in Presentation Mode, the PDF is nice display, but without any ability to navigate or find content.

**Comment by Snuffleupagus** [comment] 2015-05-09 20:35
As @yurydelendik mentioned above, it's already possible to use the browser full screen mode (e.g. with <kbd>F11</kbd>) to achieve the desired result.

The whole point of the Presentation Mode is to provide a mode without any visible UI, hence adding a toolbar to it would completely defeat its purpose. It would also mean basically duplicate the already existing browser full screen mode, hence I believe that this issue is out of scope of the default PDF.js viewer.

**Comment by timvandermeij** [comment] 2015-05-09 23:00
Indeed it is a duplicate issue. Closing as duplicate of #4816 (which by the way provides a custom implementation for this feature).

**Closed by timvandermeij** 2015-05-09 23:00 UTC
Labels: 2-feature

**Comment by drjjw** [comment] 2015-05-10 00:14
Sorry, but it wouldn't defeating the purpose of full screen mode
whatsoever.. There's a very obvious application for using what I am
inquiring about; If there is a PDF embedded in an iframe but the user
prefers to view that PDF at full screen rather than in the iframe they
could do so with the added advantage of having the navigation elements in
that mode.
