### ISSUE TITLE
Eval Function("return this") is not secure

### ISSUE THREAD

**Issue by FitsnerAS** [mozilla/pdf.js#10818] opened 2019-05-13 16:29 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version: WIN 10
- PDFjs-dist version: 2.1.266
- Is a browser extension:

Steps to reproduce the problem:
1. Include lib to project with <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline'>
2.

What is the expected behavior? (add screenshot)
Please replace Function("return this") with not eval approach. Thanks a lot!
What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2019-05-13 17:09
> Please replace Function("return this") with not eval approach.

This is done for performance reasons, and will consequently *not* be removed; as such this issue is INVALID.

However, if you look at the API documentation you'll see that this is already user-configurable when calling `getDocument`: https://github.com/mozilla/pdf.js/blob/fef86cc3e327f0554136482fee901b52909fa37a/src/display/api.js#L178-L180

**Comment by FitsnerAS** [comment] 2019-05-13 17:35
It is happens only in two cases:
var g = function () {
  return this;
}() || Function("return this")();
AND
(function () {
  return this;
}() || Function("return this")());
/* WEBPACK VAR INJECTION */}.call(this, __w_pdfjs_require__(140)(module)))

May be it is happens before you add check isEvalSupported with try catch

**Comment by Snuffleupagus** [comment] 2019-05-13 18:48
What's described in https://github.com/mozilla/pdf.js/issues/10818#issuecomment-491916264 sounds like a duplicate of issue #10229 (which wasn't clear from original comment above).

**Comment by timvandermeij** [comment] 2019-05-13 20:36
Yes, I would agree on the duplicate.

**Closed by timvandermeij** 2019-05-13 20:36 UTC
