### ISSUE TITLE
Consider configurable PDFPageProxy_getOperatorList

### ISSUE THREAD

**Issue by wojtekmaj** [mozilla/pdf.js#9625] opened 2018-04-02 15:15 UTC
The problem:

Current solution to render SVG relies on PDFPageProxy_getOperatorList called. PDFPageProxy_getOperatorList sets renderIntent to `oplist`. There's no way to change it to `display`, and thus, there's no way for getting operator list regarding annotations.

Proposed solution:

Making `renderIntent` configurable would make working on SVG rendering much easier.

That should work fine:

```js
function PDFPageProxy_getOperatorList({ intent: renderingIntent = 'oplist' }) {
```

**Comment by timvandermeij** [comment] 2018-04-03 19:37
Could you elaborate a bit here on why this is necessary to fetch annotations? AFAIK we have https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L411 for that.

**Comment by timvandermeij** [comment] 2018-04-03 21:32
Good point. Since we support annotations for canvas rendering, I think we should use a similar approach for the SVG back-end. To do that, I think we need to make the back-end a proper toggle, because some places in the code still assume the canvas back-end (search for `CanvasGraphics` and you'll find most of them in `api.js`), so we had to find another way to hook the SVG back-end in the viewer. I think if we add more abstraction there, we can use the same mechanism for the canvas back-end and the SVG back-end. Moreover, it would make reference testing for the SVG back-end (like we have for the canvas back-end) possible too.

**Comment by Snuffleupagus** [comment] 2021-06-06 08:57
First of all, please note that as (now) mentioned in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends, the SVG back-end is *not* officially supported.[1]

Secondly, annotation support for the SVG back-end is being tracked in issue #10165; of which this is thus essentially a duplicate.

> There's no way to change it to `display`, and thus, there's no way for getting operator list regarding annotations.

Simply adding support, in `getOperatorList`, for e.g. a "display" rendering intent would *not* on its own really fix annotation rendering in the SVG back-end. Furthermore, please note that the "display" rendering intent contains a number of `canvas`-specific optimizations that may not even make sense with the SVG back-end (and would just add even more unsupported operators to it).

All-in-all, this issue is mostly a duplicate of issue #10165; or possibly WONTFIX since adding "rendering intent" to `getOperatorList` unfortunately doesn't seem generally desirable.

---
[1] Currently, there's no real development happening for it either, since it's unlikely to ever perform as well as the `canvas` back-end.

**Closed by Snuffleupagus** 2021-06-06 08:57 UTC
Labels: 1-core
