### ISSUE TITLE
pdf.js  preview can display electronic signature，but it can not  display Transparent electronic signature 

### ISSUE THREAD

**Issue by yenaikafei** [mozilla/pdf.js#12273] opened 2020-08-24 12:20 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:IE 11
- Operating system and its version:windows 7
- PDF.js version:2.0
- Is a browser extension:

Steps to reproduce the problem:
1. download a pdf with electronic signature,it is no problem
2. preview a pdf with pdf-dist.js ,it can not  display Transparent electronic signature 

What is the expected behavior? (add screenshot)
display Transparent electronic signature 

What went wrong? (add screensh ot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2020-08-24 12:22
Duplicate of #1076

**Closed** 2020-08-24 19:47 UTC
