### ISSUE TITLE
[Document Properties]: Focus does not move to interactive element in the opened pop up after selecting "Document Properties "control.

### ISSUE THREAD

**Issue by seahawksq** [mozilla/pdf.js#14650] opened 2022-03-08 23:34 UTC
If focus will not land on interactive element of the newly opened pop-up or tab, then users who depend on keyboard for navigation will get disoriented as they will be unaware of the elements which are skipped and also they would need to perform extra navigation to reach to desired element.

Configuration:
- Web browser and its version: Chrome Version 97.0.4692.71 (Official Build) (64-bit) /Edge Version 97.0.1072.69 (Official build) (64-bit)
- Operating system and its version: 21H2(OS build 22000.376)
- PDF.js version: 2.13.107
- Is a browser extension: No

Steps to reproduce the problem:
1. Navigate to https://mozilla.github.io/pdf.js/web/viewer.html
2. Select Document Properties from secondary toolbar
3. Use keyboard Tab key to navigate

What is the expected behavior? (add screenshot)
Focus should move to interactive element after selecting the "Document Properties" control i.e., "Close" button in the opened pop up.

What went wrong? (add screenshot)
Focus does not move to interactive element in the opened pop up i.e., "Close" button after selecting "Document Properties" control even after selecting the tab key focus moves to toggle Sidebar control.

**Comment by Snuffleupagus** [comment] 2022-03-09 08:49
Duplicate of #9560

**Closed by Snuffleupagus** 2022-03-09 08:49 UTC
