### ISSUE TITLE
Slow PDF rendering

### ISSUE THREAD

**Issue by alrigh** [mozilla/pdf.js#8924] opened 2017-09-18 06:54 UTC
I have noticed rather slow rendering times for PDF's that contain tables or images. It is especially noticeable when a document with numerous pages is being loaded (please see below). As a comparison, loading the same file in Edge results in ~10x faster loading times.  

[Link to PDF file](https://aoanjrr.sahmri.com/documents/10180/275066/Hip%2C%20Knee%20%26%20Shoulder%20Arthroplasty) 

Configuration:
- Web browser and its version: 
Firefox 55.0.3 (64bit) vs Microsoft Edge 40.15063.0.0
- PC config
Intel i7-6700K; 16GB RAM; SSD Samsung 950 pro

- Operating system and its version:
Windows 10 (64bit)
- PDF.js version:
Latest

**Comment by Snuffleupagus** [comment] 2017-09-18 08:34
The rendering seems very quick in my testing, i.e. *well* below 1 second for all the pages I've tried, in PDF.js version `1.9.572`.
However, considering that the document contains a total of 380 pages and that certain ones could be slower, you really need provide information about which *particular* pages renders slowly.

**Comment by alrigh** [comment] 2017-09-20 02:09
Thanks for your reply.

1) The whole document: As mentioned above, loading the whole document in FF vs IE: 6.22sec vs 0.66 sec. I don't see any content for about for >6sec while pdf.js does its thing. It doesn't matter which page.

2) Individual page loading: Once the document has been loaded, using the scroll bar to any page causes lag. I picked random pages and it didn't matter whether they had graphics, text or tables. This is not the case when browsing page by page.

**Comment by timvandermeij** [comment] 2017-09-20 20:20
I observe the same as @Snuffleupagus for this PDF file in Firefox: fast rendering below one second per page. Do you have hardware acceleration enabled in Firefox?

**Comment by alrigh** [comment] 2017-09-21 02:17
Hardware acceleration is enabled. How long does the file load when you first open it?

**Comment by timvandermeij** [comment] 2017-09-21 20:53
After downloading it renders immediately. Downloading takes approximately 10 seconds (slow server).

**Comment by yurydelendik** [comment] 2017-09-22 13:31
> It would be great to know what sort of settings/ setup you are using/ would recommend

We recommend any standard setup and browsers that support standard HTML5 features. It's hard to tell why it's slow in your particular setup. Try removing extensions/addons, re-installing Firefox, start clean profile, updating video drivers (can you post your about:support graphics section here?)

**Comment by timvandermeij** [comment] 2017-09-29 20:12
Closing since nobody here is able to reproduce the issue and because the information asked above is not provided (and therefore this issue is not actionable at the moment).

**Closed by timvandermeij** 2017-09-29 20:12 UTC
Labels: 4-information-requested
