### ISSUE TITLE
How to get metaData info 'Author' name on 'documentload' eventBus

### ISSUE THREAD

**Issue by venusakthiv** [mozilla/pdf.js#9202] opened 2017-11-28 09:15 UTC
Attach (recommended) or Link to PDF file here: na

Configuration:
- Web browser and its version: 
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot) How to get metaData info 'Author' name on 'documentload' eventBus

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2017-11-28 10:07
To access the metadata, the following API method is used: https://github.com/mozilla/pdf.js/blob/3e34eb31d940f5e8add0af5ee9b262c9f3ad1462/src/display/api.js#L596-L604

If you're using the default viewer, then the metadata will be available trough `PDFViewerApplication.metadata` once the file is loaded.
Or you can can fetch it yourself, using `PDFViewerApplication.pdfDocument.getMetaData()` in the default viewer (again once the file has loaded).
Note though that this information isn't directly available through the `eventBus` (duplicate of issue #5765).

Closing as answered, given that lack of details provided.

**Closed by Snuffleupagus** 2017-11-28 10:07 UTC

**Comment by venusakthiv** [comment] 2017-11-28 11:56
thanks!!!
