### ISSUE TITLE
Latest Pdfjs version 2.0.943 issue on load embedded in Javafx web view 

### ISSUE THREAD

**Issue by anuj1992** [mozilla/pdf.js#10240] opened 2018-11-08 13:18 UTC
Attach (recommended) or Link to PDF file here:

Configuration:

JavaFx desktop application webView with netbeans 8.1
Pdfjs version 2.0.943
I have used the latest version with my Javafx project and able to open any PDF, it's showing error on load of PDFjs.
What is the expected behavior?
It's should open my PDF, but it's showing error

I have also added compatibility.js for this issue but still it exists
![pdf js new issues](https://user-images.githubusercontent.com/14055454/48201114-368b7780-e387-11e8-8579-9d0a98cf4b3c.png)

**Comment by Snuffleupagus** [comment] 2018-11-08 13:43
Duplicate of #10198.

**Closed** 2018-11-08 21:56 UTC
