### ISSUE TITLE
How can I display stamp in pdf?

### ISSUE THREAD

**Issue by kiner-tang** [mozilla/pdf.js#8148] opened 2017-03-10 09:26 UTC
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:chrome[56.0.2924.87 (64-bit)],safari[10.0.2 (11602.3.12.0.1)],Android 7.0 NRD90M
- Operating system and its version:OS X [10.11.6 (15G1217)]
- PDF.js version:0.8.0
- Is an extension:

Steps to reproduce the problem:
1. Get a pdf with a stamp
2.Use pdf.js to load the pdf file

What is the expected behavior? (add screenshot)
Pdf can show stamp
![image](https://cloud.githubusercontent.com/assets/10286961/23789612/83be9fc4-05b6-11e7-9dc7-2fce173f52c6.png)

What went wrong? (add screenshot)
Pdf does not show stamp
![image](https://cloud.githubusercontent.com/assets/10286961/23789615/89aebf18-05b6-11e7-88b5-759e93ed03b0.png)

**Comment by Snuffleupagus** [comment] 2017-03-10 10:21
Closing as duplicate of issue #8147, please don't open multiple issues for the same problem!

As mentioned in https://github.com/mozilla/pdf.js/issues/8147#issuecomment-285615959, amend the original issue with *all* of the requested information.
Please note that the *single most important* information is still missing, i.e. access to a PDF file that can be used to reproduce this.

**Closed by Snuffleupagus** 2017-03-10 10:21 UTC
