### ISSUE TITLE
Italics, bold kinda messed up when printing from Firefox (v33)

### ISSUE THREAD

**Issue by brianloveswords** [mozilla/pdf.js#5058] opened 2014-07-18 19:23 UTC
Firefox Version: 33.0a1 (2014-07-17) on OS X 10.9.3

**Steps to Reproduce:**
1. Print a document with bold or italic text (i.e. http://math.ucsd.edu/~jrabin/publications/ProblemFreeActivity.pdf)

**Expected Results:**
1. The text on the printed page should be italicized on the screen.

**Actual Results:**
![see here](https://i.cloudup.com/yCP9q9gaBn.png)

The page on the left was printed from Preview on OS X, the page on the right printed directly from Firefox using the "print" icon in the PDF viewer.

**Comment by Snuffleupagus** [comment] 2015-06-22 13:39
Closing as duplicate of issue #5006.

**Closed by Snuffleupagus** 2015-06-22 13:39 UTC
Labels: 4-printing
