### ISSUE TITLE
error:Transferring of ArrayBuffer cannot be properly polyfilled in this engine

### ISSUE THREAD

**Issue by 17825252869** [mozilla/pdf.js#16367] opened 2023-04-28 02:51 UTC
Attach (recommended) or Link to PDF file here:
any pdf
Configuration:
- Web browser and its version:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 。360 speed browser with Google kernel
- Operating system and its version:win10
- PDF.js version:older browsers v3.5.141
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/85288947/235042880-a81ce818-a7b5-47ed-aec3-902006fbb106.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment] 2023-04-28 06:57
Duplicate of #16255

**Closed by Snuffleupagus** 2023-04-28 06:57 UTC

**Comment by pzubar** [comment] 2023-05-19 15:02
Hello @Snuffleupagus. I am unsure if it is a duplicate of the [issue](https://github.com/mozilla/pdf.js/issues/16255). In fact, I'm facing the same error on Safari 14 (`pdfjs-dist` `/legacy` `v3.6.172`).

Moreover, the issue happens on `v3.6.172` when I'm trying to upload the pdf document a second time -- the first time it works well. However, downgrading to `v3.4.120` seems to fix the issue. Do you have any ideas of what could be the reason? I really appreciate any help you can provide.
