### ISSUE TITLE
Migrate code to es6 or to Typescript

### ISSUE THREAD

**Issue by luisvt** [mozilla/pdf.js#7931] opened 2017-01-05 18:04 UTC
Code will have better readability if it is migrated to es6 or to Typescript.

**Comment by yurydelendik** [comment] 2017-01-05 18:07
Closing as duplicate of https://github.com/mozilla/pdf.js/projects/3

**Closed by yurydelendik** 2017-01-05 18:07 UTC

**Comment by luisvt** [comment] 2017-01-05 18:17
what would you prefer to use: es6 or Typescript?

**Comment by yurydelendik** [comment] 2017-01-05 18:27
> what would you prefer to use: es6 or Typescript?

This is an opinion based question and shall not be part of this issue (see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md about non-technical problems). ES6 was chosen as evolutionary step of the same programming language and moving entire project to be modular.

**Comment by luisvt** [comment] 2017-01-05 18:39
ok, I'll begin doing migrations to es6 then
