### ISSUE TITLE
Two words are presented as one while on the real pdf they are not together

### ISSUE THREAD

**Issue by AvdiuAndin** [mozilla/pdf.js#9286] opened 2017-12-15 17:31 UTC
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 63.0.3239.84
- Operating system and its version: Win 10
- PDF.js version: 
- Is a browser extension: NO

Steps to reproduce the problem:
1.  
[FINAL-TEST.pdf](https://github.com/mozilla/pdf.js/files/1563463/FINAL-TEST.pdf)

2. when I do a search with markJS ( https://markjs.io/) words like "burgim deri" "por mungon" appear to be together. i need to do this search with markJS to avoid extra spaces between the words, since the pdf controller needs spaces to be exact :(.

**Comment by himanish-star** [comment] 2017-12-20 18:47
@AvdiuAndin what do you mean by 
>markJS words

**Comment by AvdiuAndin** [comment] 2017-12-20 19:02
Mark js is a library that i want to use to search words on the pdf. I want to use this because pdf find controller only highlights the words and it is hard to add some functionality on it. OR maybe i did not find a better way that can help me to add some styling on that text. If you have one please feel free to tell me :)

**Comment by himanish-star** [comment] 2017-12-20 19:04
Ya @AvdiuAndin I recently searched this. Ok let me see how far I can proceed with this issue

**Comment by Snuffleupagus** [comment] 2017-12-21 08:47
> Mark js is a library that i want to use to search words on the pdf.

This issue is currently somewhat difficult to understand, since it's not really clear if you're attempting to report a problem with PDF.js itself or with some library (i.e. mark.js).
If it's the latter case, please understand that we know nothing about that library and consequently are not able to provide support for it.

> when I do a search with markJS ( https://markjs.io/) words like "burgim deri" "por mungon" appear to be together. i need to do this search with markJS to avoid extra spaces between the words, since the pdf controller needs spaces to be exact :(.

Can you please try to clarify the above, in terms of what the issue is in PDF.js *itself*, since this issue is probably not actionable (and would be closed as such) in its current state?

**Comment by AvdiuAndin** [comment] 2017-12-21 09:13
I'm highlighting words with pdf find controller. I also need to add some styling to that text ( for example add a click event on the text to pop up a modal ). Can u suggest a way how can I add that kind of functionality to the text ?

**Comment by timvandermeij** [comment] 2017-12-21 20:18
The PDF find controller gives you the matches as output. Take a look at https://github.com/mozilla/pdf.js/blob/80c33253ed0f70708753a13e49e361ebdac354f2/web/text_layer_builder.js#L189 for how the highlighting is done. With the output from the PDF find controller you should be able to control `mark.js`. Note, however, that this is out of scope for the PDF.js project, so I'm closing this issue as resolved.

**Closed by timvandermeij** 2017-12-21 20:18 UTC
Labels: 4-information-requested, 4-text-selection

**Comment by AvdiuAndin** [comment] 2017-12-22 13:33
Lets start from the beginning. I want highlight more than 1 sentence on pdf. Can u suggest a way how can i do that ?

**Comment by Shakti2303** [comment] 2020-06-19 06:17
> I'm highlighting words with pdf find controller. I also need to add some styling to that text ( for example add a click event on the text to pop up a modal ). Can u suggest a way how can I add that kind of functionality to the text ?

Could you please tell me how you used pdfFindController as i'm not able to use it in my javscript code...could you suggest some steps and files required for that

**Comment by AvdiuAndin** [comment] 2020-06-19 08:00
Hey man, it has been a while !! All I remember was that when I was fetching the text from the pdf some of the words were concatenated, but when you read the pdf the words were separated.
