### ISSUE TITLE
Duplicate Form field should have the same property

### ISSUE THREAD

**Issue by bksantiago** [mozilla/pdf.js#11310] opened 2019-11-07 17:40 UTC
Attach (recommended) or Link to PDF file here:
[result-no-sensitive-duplicate-field.pdf](https://github.com/mozilla/pdf.js/files/3820962/result-no-sensitive-duplicate-field.pdf)

Configuration:
- Web browser and its version: Chrome 77.0.3865.120
- Operating system and its version: MacOS 10.15
- PDF.js version: 2.3.194
- Is a browser extension: Nope

Steps to reproduce the problem:
1. Set interactiveFields to true
2. Use the given PDF and open it via PDFJS viewer or in `examples/acroforms/acroforms.html`

What is the expected behavior? (add screenshot)
- 1st and 2nd field with the same name should be displayed as readonly like in adobe acrobat and chrome
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/4616548/68413128-91d58d00-01c8-11ea-9f9c-91e2b795bb12.png">

What went wrong? (add screenshot)
- Only the first field was displayed as readonly, 2nd field is not being displayed as readonly
<img width="873" alt="image" src="https://user-images.githubusercontent.com/4616548/68413173-a7e34d80-01c8-11ea-9758-5d22fea117c6.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by bksantiago** [comment] 2019-11-19 03:35
Hi @timvandermeij do you know which part of the code is probably the cause. I have a little bit of understanding of the PDF structure, so i'll see if I can pinpoint the cause and create a PR. Just wanna have a starting point.

**Comment by timvandermeij** [comment] 2019-11-19 22:42
The core annotation layer code lives in https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js, which is most likely where this needs to be changed. I would start by identifying in a PDF browser, for example https://brendandahl.github.io/pdf.js.utils/browser, what properties the annotations have and then find out what PDF.js is not parsing (correctly).

**Comment by timvandermeij** [comment] 2019-11-23 19:39
I looked into this and I cannot help but feel like PDF.js (and Okular for example) is doing the right thing. A field is read-only if its read-only field flag is set in the `Ff` property of the annotation. This corresponds to the first bit of the unsigned 32-bit integer (see https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=441&zoom=auto,-215,356). The annotation on the first page doesn't have a `Ff` property, but inherits it from its parent annotation since the `Ff` property is inheritable. This value is 8388609, which is 100000000000000000000001 in binary, so the read-only flag is set (lowest order bit).

However, the annotation on the second page, while having a parent annotation with `Ff = 8388609`, defines its own `Ff` value: 8388608, which is 100000000000000000000000 in binary, so the read-only flag is not set.

I can only imagine that the endianness is different in this PDF file, but I haven't found any resources that state that the PDF format's endianness can differ and if the way we interpret the field flags would be incorrect, we wouldn't be able to for example render radio buttons, so I think our code is actually correct, also looking at how e.g., PDFBox implements it.

Therefore, I cannot think of any reason how Adobe Reader can behave differently in this situation...

**Comment by Snuffleupagus** [comment] 2021-09-28 15:49
Having also looked at this now, I have to agree completely with the analysis done in https://github.com/mozilla/pdf.js/issues/11310#issuecomment-557826890.
All-in-all, let's close this as WONTFIX for the time being since:
 - This particular PDF document is clearly specifying the `Ff`-entry incorrectly here.
 - The PDF specification doesn't mention anything, as far as I can find, about it being OK to ignore an explicit `Ff`-entry for Annotations with a /Parent. Hence trying to hack around this, in order to support one particular document, *could* thus easily lead to regressions elsewhere.
 - This shouldn't be a particularly common problem, since it's (to the best of my knowledge) the only similar report we've seen.

**Closed by Snuffleupagus** 2021-09-28 15:49 UTC
Labels: 4-annotations, 4-form-acroform
