### ISSUE TITLE
PDF viewer unable to correctly render some pages of PDF

### ISSUE THREAD

**Issue by LinGrin** [mozilla/pdf.js#10574] opened 2019-02-21 20:50 UTC
Attach (recommended) or Link to PDF file here: 
[CC 2017 US6M RI TRB L01(1).pdf](https://github.com/mozilla/pdf.js/files/2891197/CC.2017.US6M.RI.TRB.L01.1.pdf)
(originally reported to: https://bugzilla.mozilla.org/show_bug.cgi?id=1519218)

Configuration:
- Web browser and its version: Firefox 63.0.1 and onwards to Firefox 65.0
- Operating system and its version: Mac OS X 10.13
- PDF.js version: whatever came with Firefox 63 all the way up to whatever is in Firefox 65
- Is a browser extension: No (using built-in version)
The PDF is created using Adobe InDesign CC 2017

Steps to reproduce the problem:
1. Open the above linked pdf
2. The pdf is rendered incorrectly on pages 3, 6, and 7

What is the expected behavior? (add screenshot)
If you open the link in chrome the pdf renders the way it's supposed to for those pages, page 3 on chrome:
<img width="659" alt="screen shot 2019-02-21 at 3 39 13 pm" src="https://user-images.githubusercontent.com/43445438/53200290-31c59900-35ef-11e9-8ead-8513acd8f866.png">

What went wrong? (add screenshot)
In Firefox the colors are incorrect and content either shifts or disappears altogether 
<img width="599" alt="screen shot 2019-02-21 at 3 39 46 pm" src="https://user-images.githubusercontent.com/43445438/53200321-430ea580-35ef-11e9-9a00-ec850b9c2a51.png">

**Comment by Snuffleupagus** [comment] 2019-02-21 20:59
> (originally reported to: https://bugzilla.mozilla.org/show_bug.cgi?id=1519218)

There's no need to track issues *twice*, let's just close this as a duplicate of the referenced bug.

**Closed** 2019-02-21 21:07 UTC
