### ISSUE TITLE
nodejs: pdf2png: Junk chars when substituting non embedded cmap font

### ISSUE THREAD

**Issue by panneer** [mozilla/pdf.js#16165] opened 2023-03-17 05:08 UTC
**PDF:**
[incorrect_render.pdf](https://github.com/mozilla/pdf.js/files/10997944/incorrect_render.pdf)

**Configuration:**
- **NodeJS: V16.19.1**
- **Operating system and its version: Windows 7**
- **PDF.js-dist** version: 3.4.120
- **Is a browser extension: NO**

**Steps to reproduce the problem:**
1. Transform the given PDF as PNG using https://github.com/mozilla/pdf.js/tree/master/examples/node/pdf2png

**What is the expected behavior?**
Expected blank page (instead of junk characters)

**What went wrong?**
![incorrect_render-p0001](https://user-images.githubusercontent.com/161330/225815673-3db93e95-90ec-42fa-9d72-6304ca9cca46.png)

**Description**
I have developed a node module to convert PDF to PNG using pdfjs-dist. It works well for most PDFs except the attached one.
The attached PDF is stripped down (i.e, removed other potential content) version to represent the problematic content alone.

In my understanding, I believe the following could be the reason
- Text is applied with Arial (non embedded), Identity-H encoded font
- pdf.js-dist (node) internal name mapping already looks fine (Maps Arial to Helvetica correctly)
- When rendering the text, charmap must follow Identity-H using substituted font
- **pdf.js-dist (node) seems to use standard encoding (like WinAnsi) instead of Identity-H**
**Hence the chars become junk**

**Code excerpt from <pdfjs-dist>\legacy\build\pdf.worker.js**
```
async translateFont(_ref9) {
    ...
    if (fontFile) {
      ...
    } else if (cssFontInfo) {
      ...
    //!!!Here, the font is simply substituted without checking the encoding!!!
    } else if (!isType3Font) {
      const standardFontName = (0, _standard_fonts.getStandardFontName)(fontName.name);
      if (standardFontName) {
        isStandardFont = true;
        fontFile = await this.fetchStandardFontData(standardFontName);
        isInternalFont = !!fontFile;
      }
    }
    ...
}
```

**Comment by Snuffleupagus** [comment] 2023-03-17 08:59
This isn't Node.js specific, but can be reproduce in browsers as well (with suitable API-options set).

Duplicate of #14843, since we'd need to replace the bundled standard-fonts in order to fix this (and other issues).

**Closed by Snuffleupagus** 2023-03-17 08:59 UTC
