### ISSUE TITLE
Feature request: 'Save as' option when downloading PDFs

### ISSUE THREAD

**Issue by cfr42** [mozilla/pdf.js#9198] opened 2017-11-28 03:08 UTC
Attach (recommended) or Link to PDF file here: N/A (Feature request)

Configuration:
- Web browser and its version: Firefox Quantum "57.0 (64 did)"
- Operating system and its version: Arch Linux - version N/A, updated from stable 2017-11-27
- PDF.js version: whatever is built-in to Firefox 57
- Is a browser extension: no - built-in

Steps to reproduce the problem: N/A

What is the expected behaviour? (add screenshot) No idea how to add screenshot for feature request. I would like an option to make the download button trigger 'save file as ...' rather than saving with the default file name. Many journal archives use long alpha-numeric sequences in file names. In order to keep track when downloading multiple papers, I have to keep switching to another programme to rename each file right after download. Otherwise, I cannot tell which paper is which. 

Alternatively, another button for 'save as ...', but I'd prefer the option for the current download button, if possible.

What went wrong? (add screenshot) Nothing went wrong. But this is only possible currently using the contextual menu and this does not work correctly in all cases. (I think if the PDF is embedded in HTML, then downloading works but 'save file as ...' downloads the HTML & not the PDF. Embedding in this way is increasingly common for journal archives, so that picking the file name is often not possible at all.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by GauravV-02** [comment] 2017-12-07 17:31
@cfr42 Hi, I am a student taking open source development course at Seneca college, looking for an issue to fix as a requirement of my course. Can I work on this?

Regards

**Comment by Snuffleupagus** [comment] 2017-12-07 18:09
> I would like an option to make the download button trigger 'save file as ...' rather than saving with the default file name.

Works for me, when clicking the "Download" button on the PDF.js toolbar; see the following screen-shot.

![save](https://user-images.githubusercontent.com/2692120/33730710-1e3656f0-db81-11e7-90a4-f2714e21b2d0.png)

I don't think that this is behaviour that a web-app (that PDF.js is) can really affect, since whether or not the file is directly downloaded is a *browser* setting; please see https://support.mozilla.org/en-US/kb/where-find-and-manage-downloaded-files-firefox#w_change-where-downloads-are-saved (there should be a "Always ask you where to save files" option in Firefox)

> Alternatively, another button for 'save as ...', but I'd prefer the option for the current download button, if possible.

That part would probably be a duplicate of issue #2553 (even if that discussion is somewhat difficult to follow at this point).

Closing, since I don't think there's anything we can fix here.

**Closed by Snuffleupagus** 2017-12-07 18:09 UTC
Labels: 2-feature
