### ISSUE TITLE
Looks like some Invalid array length even tho when I try to open PDF on the browser it works fine

### ISSUE THREAD

**Issue by fatonh** [mozilla/pdf.js#12472] opened 2020-10-12 09:37 UTC
Configuration:
- Web browser and its version: Google chrome 85.0.4183.121
- Operating system and its version: macos and 10.15.6:
- PDF.js version: PDF.js v2.2.228
- Is a browser extension: no

What went wrong? 

PDF.js v2.2.228 (build: d7afb74a)
Message: Array buffer allocation failed

![Screenshot 2020-10-12 at 11 25 37](https://user-images.githubusercontent.com/3781157/95729818-b3af7d80-0c7d-11eb-8ea7-4d88a573436f.png)

**Comment by timvandermeij** [comment] 2020-10-12 20:18
Closing since no PDF file is provided to reproduce the problem, which is required in the issue template. "Array buffer allocation failed" means that you're running into a memory limit, so it's most likely a platform issue.

**Closed by timvandermeij** 2020-10-12 20:18 UTC
