### ISSUE TITLE
Missing letters

### ISSUE THREAD

**Issue by vlastimilmaca** [mozilla/pdf.js#10519] opened 2019-02-04 08:10 UTC
Attach (recommended) or Link to PDF file here:
[Dar_smlouva.pdf](https://github.com/mozilla/pdf.js/files/2826984/Dar_smlouva.pdf)
Configuration:
- Web browser and its version: Chrome 71.0.3578.98 64bit (bug appears on IE,Edge and Firefox too)
- Operating system and its version: Windows 10 Pro 1809
- PDF.js version:  master (2.1.237)
- Is a browser extension: no

Steps to reproduce the problem:
1. Open attached file
2. See missing letters

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/6502310/52195950-3b62a900-285a-11e9-89aa-8ae78b6889aa.png)

What went wrong? (add screenshot)
Missing letters 'D' (twice) and 'B'
![image](https://user-images.githubusercontent.com/6502310/52196005-79f86380-285a-11e9-82b3-0e717a3e3561.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by janpe2** [comment] 2019-04-30 20:27
The missing characters 'D' and 'B' are at glyph index zero in two CIDFontType2 fonts. Pull request #3433 should have resolved these problems but it fixed only fonts that have `/CIDToGIDMap /Identity`. Now the value of the `CIDToGIDMap` entry is a PDF stream object. Glyphs at index zero are never rendered because they are discarded when the stream is read:

https://github.com/mozilla/pdf.js/blob/f87dc42780d9aaefe3b3c01c1127d88d05ac5763/src/core/evaluator.js#L2132-L2147

If I delete the lines `if (glyphID === 0) { continue; }`, the issue gets fixed. However, this increases memory consumption because in some PDFs the stream could contain thousands of unnecessary zeros. Does anyone have a better idea to fix this?

Maybe we could store only a few entries that are mapped to zero. In this issue we would need to store only two entries at the start of the stream because CIDs 0 and 1 are mapped to zero and the missing characters are at CID 1. However, then we might find another PDF in which two is not enough.

**Comment by Snuffleupagus** [comment] 2019-04-30 22:11
> However, this increases memory consumption because in some PDFs the stream could contain thousands of unnecessary zeros. Does anyone have a better idea to fix this?

I've not yet had time to run tests, but one possible way to reconcile this could perhaps be to check the `toUnicode` value in the `glyphID === 0` case.
This would obviously require calling `PartialEvaluator.readCidToGidMap` *after* the `ToUnicode` data has been completely parsed, but that doesn't seem particularly difficult; e.g. something along these lines could probably work[1]:
```diff
diff --git a/src/core/evaluator.js b/src/core/evaluator.js
index 8f7917f7..fc918d55 100644
--- a/src/core/evaluator.js
+++ b/src/core/evaluator.js
@@ -1810,7 +1810,7 @@ var PartialEvaluator = (function PartialEvaluatorClosure() {
     extractDataStructures:
         function PartialEvaluator_extractDataStructures(dict, baseDict,
                                                         properties) {
-      var xref = this.xref;
+      var xref = this.xref, cidToGidBytes;
       // 9.10.2
       var toUnicode = (dict.get('ToUnicode') || baseDict.get('ToUnicode'));
       var toUnicodePromise = toUnicode ?
@@ -1829,7 +1829,7 @@ var PartialEvaluator = (function PartialEvaluatorClosure() {
 
         var cidToGidMap = dict.get('CIDToGIDMap');
         if (isStream(cidToGidMap)) {
-          properties.cidToGidMap = this.readCidToGidMap(cidToGidMap);
+          cidToGidBytes = cidToGidMap.getBytes();
         }
       }
 
@@ -1909,11 +1909,17 @@ var PartialEvaluator = (function PartialEvaluatorClosure() {
       properties.baseEncodingName = baseEncodingName;
       properties.hasEncoding = !!baseEncodingName || differences.length > 0;
       properties.dict = dict;
+
       return toUnicodePromise.then((toUnicode) => {
         properties.toUnicode = toUnicode;
         return this.buildToUnicode(properties);
-      }).then(function (toUnicode) {
+      }).then((toUnicode) => {
         properties.toUnicode = toUnicode;
+
+        if (cidToGidBytes) {
+          properties.cidToGidMap = this.readCidToGidMap(cidToGidBytes,
+                                                        toUnicode);
+        }
         return properties;
       });
     },
@@ -2129,18 +2135,17 @@ var PartialEvaluator = (function PartialEvaluatorClosure() {
       return Promise.resolve(null);
     },
 
-    readCidToGidMap: function PartialEvaluator_readCidToGidMap(cidToGidStream) {
+    readCidToGidMap(glyphsData, toUnicode) {
       // Extract the encoding from the CIDToGIDMap
-      var glyphsData = cidToGidStream.getBytes();
 
       // Set encoding 0 to later verify the font has an encoding
       var result = [];
       for (var j = 0, jj = glyphsData.length; j < jj; j++) {
         var glyphID = (glyphsData[j++] << 8) | glyphsData[j];
-        if (glyphID === 0) {
+        var code = j >> 1;
+        if (glyphID === 0 && !toUnicode.has(code)) {
           continue;
         }
-        var code = j >> 1;
         result[code] = glyphID;
       }
       return result;
```

---
[1] Purposely keeping the `getBytes` call at the same spot, to not unnecessarily modify the timing of the code too much.

**Closed** 2019-05-14 22:04 UTC
Labels: 4-font-conversion

**Comment by caot** [comment] 2020-11-07 20:25
PDF.js version 2.6.347 ES5: Missing letter 'A' and 'a' in IE, however it's good in Firefox, Chrome, and Safari.

PDF.js version 2.5.207 ES5 doesn't have the above issue.

![image](https://user-images.githubusercontent.com/5083030/98450709-e29a0180-210c-11eb-9f6d-339ef34a174a.png)

**Comment by BrianLeishman** [comment] 2021-07-15 16:09
Confirmed this to be the case with Chrome as well

Affected: pdfjs-dist@2.8.335/legacy/build/pdf.min.js

Not affected: pdfjs-dist@2.5.207/es5/build/pdf.min.js

Seem to be missing letters A and R of both upper and lower cases
