### ISSUE TITLE
[Bug]: Glyph-fallback letters cannot be copied as a single character

### ISSUE THREAD

**Issue by LinqLover** [mozilla/pdf.js#18832] opened 2024-10-01 20:59 UTC
### Attach (recommended) or Link to PDF file

[test.pdf](https://github.com/user-attachments/files/17216346/test.pdf)

### Web browser and its version

Google Chrome 129.0.6668.58

### Operating system and its version

Linux x64 6.5.0-45-generic (Ubuntu 22)

### PDF.js version

https://mozilla.github.io/pdf.js/web/viewer.html

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open a file with glyph substitution letters\* such as a macron-a letter (`ā`) in the attached file
2. Select the combined glyph\*
3. Copy it (<kbd>Cmd</kbd> + <kbd>C</kbd>)
4. Paste it somewhere else

\* Please apologize if I used the incorrect terminology, I'm happy if you educate me about the correct terms for this.

### What is the expected behavior?

The true character (`ā`) is pasted.

### What went wrong?

Two separate characters (`¯a`) are pasted.

### Additional context

Other viewers such as Evince do support this.

Original context of this observation: https://tex.stackexchange.com/questions/726953/how-can-i-insert-a-proper-macron-a-letter-%c4%81-using-pdftex#comment1809647_726953

**Comment by LinqLover** [comment] 2024-10-01 21:00
![image](https://github.com/user-attachments/assets/aea69398-639d-4a91-a8a7-65554f641c18)

**Comment by Snuffleupagus** [comment] 2024-10-02 07:08
Please note that there's actually no "combined glyph" in your PDF document, since the text is being rendered as `Nav¯a` i.e. using five *separate* glyphs and `¯` and `a` are just placed "on top" of each other.

Note also that Adobe Reader (i.e. the PDF reference implementation) and PDFium (i.e. the Google Chrome PDF Viewer) both copy-and-paste the same way as PDF.js for this document, since it's really a broken PDF unfortunately.

Duplicate of [bug 1432023](https://bugzilla.mozilla.org/show_bug.cgi?id=1432023).

**Closed by Snuffleupagus** 2024-10-02 07:08 UTC

**Comment by LinqLover** [comment] 2024-10-07 18:06
Thank you for the clarification, so it seems that other viewers such as Evince (for Ubuntu) are just "probably too smart" here.

**Comment by calixteman** [comment] 2024-10-07 19:00
The way we build the text layer makes this bug uneasy to fix.
In the pdf you shared, first we draw the string "Nava" and then, in a second time, a macron is drawn back over the "a".
Potentially, once the string "Nava" is got, it could be sent from the worker to the main thread in order to be added in the text layer (the chunks of text are streamed from the worker). In this case, the macron should be combined with the "a" but in the main thread and then it'll break the boxes we created around the chunk of text.
So, maybe we could change the way we decide to send the chunks we've, for example, only flush when we've a punctuation sign or something like that, but it could have some negative impacts on performances.
